### ISSUE TITLE
Echarts 实际使用过程中，部分IE版本CPU占用过高问题

### ISSUE THREAD

**Issue by jxchanghe** [ecomfe/echarts#1036]
你好，在实际使用echarts过程中，遇到以下问题，还请帮助解决。
项目测试过程中发现，2.1.8以前版本 IE8 CPU占用高，IE9不高。
2.1.8，2.1.9 版本 IE9 CPU占用过高，IE8 CPU占用不高。
谢谢。

**Comment by 823844596** [comment]
请问解决CPU过高的问题了嘛？谢谢~

**Comment by jxchanghe** [comment]
后来问题被Yi Shen<notifications@github.com>关闭了。不是很清楚。




在 2015-06-16 17:21:40，"823844596" <notifications@github.com> 写道：


请问解决CPU过高的问题了嘛？谢谢~

**Comment by 823844596** [comment]
@jxchanghe 恩 谢谢~

**Comment by li2215890610** [comment]
请问你cpu过高的问题是怎么解决的
