### ISSUE TITLE
Echarts饼图数据少于等于3条的时候在Safari上面没响应

### ISSUE THREAD

**Issue by p13766** [ecomfe/echarts#1056]
Safari 版本 8.0.2 (10600.2.5)
打开http://echarts.baidu.com/doc/example/pie1.html 
把以下内容粘贴过去，点刷新，浏览器就没响应了。
option = {
    title : {
        text: '某站点用户访问来源',
        subtext: '纯属虚构',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:['直接访问','邮件营销','联盟广告']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true, 
                type: ['pie', 'funnel'],
                option: {
                    funnel: {
                        x: '25%',
                        width: '50%',
                        funnelAlign: 'left',
                        max: 1548
                    }
                }
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    series : [
        {
            name:'访问来源',
            type:'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'}
            ]
        }
    ]
};

**Comment by kener** [comment]
follow by @pissang

**Comment by xiong4824956** [comment]
@kener @pissang 
这个不是BUG把..只是因为formatter后面他换行了,,,,就算是bug也不会是echarts的bug,,,任何人在js中写字符串不换行都会报错.,..
