### ISSUE TITLE
x轴为Time类型时，柱状图可以进行堆积吗？

### ISSUE THREAD

**Issue by spp1987** [ecomfe/echarts#1084]
如这样的代码，页面不显示，也不提示错误：
option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
    },
    toolbox: {
        show : true,
        orient: 'vertical',
        x: 'right',
        y: 'center',
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'time',

        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
       
        {
            name:'百度',
            type:'bar',
            barWidth : 15,
            stack: '搜索引擎',
            data:[[new Date("2014-01-01"),620],[new Date("2014-01-02"),732]]
        },
        {
            name:'谷歌',
            type:'bar',
            stack: '搜索引擎',
            data:[[new Date("2014-01-01"),120] ,[new Date("2014-01-01"),132]]
        }
        
    ]
};

**Comment by kener** [comment]
你会想到办法的。
