### ISSUE TITLE
mac safari8.0 下会出现页面假死状态

### ISSUE THREAD

**Issue by beiluo** [ecomfe/echarts#1086]
低版本的没有问题，chrome、火狐等也没有问题。只有最新版本的safari才会出现问题

**Comment by kener** [comment]
http://echarts.baidu.com/doc/example/topic/10-me-china/index.html ?

**Comment by beiluo** [comment]
http://echarts.baidu.com/doc/example/pie5.html

我重新测试了下，不是折线图的问题，是环形图的问题。
你们的演示示例，在mac下的最新版本的safari下会存在卡死的问题。多刷新两次就会出现
