### ISSUE TITLE
在散点图中使用 tooltip 组件 showTip 接口出现 bug

### ISSUE THREAD

**Issue by YvonneZhang** [ecomfe/echarts#1089]
如果在散点图中加上 markline 时，再如下使用 tooltip 组件 showTip 接口：

- 其他 dataIndex 值的 tooltip 能够正常显示；

但是，
- `myChart.component.tooltip.showTip({ seriesIndex: "0", dataIndex:"0" }) `
会显示第一条 markline 的 tooltip：
![screen shot 2014-12-29 at 2 55 15](https://cloud.githubusercontent.com/assets/4408102/5566666/00d013c2-8f6b-11e4-8e3d-d9c62432fc26.png)

- `myChart.component.tooltip.showTip({ seriesIndex: "0", dataIndex:"1" }) `
会显示第一条 markline 的 tooltip：
![screen shot 2014-12-29 at 2 54 48](https://cloud.githubusercontent.com/assets/4408102/5566669/10f462a8-8f6b-11e4-9e13-ea593b0c92ee.png)

- - -
请问这是一个 bug 么？有什么方法可以避免这种情况？

**Comment by kener** [comment]
谢谢反馈，应该是bug
