### ISSUE TITLE
axisTick和splitLine的展示

### ISSUE THREAD

**Issue by wyzfzu** [ecomfe/echarts#1093]
能否让axisTick和splitLine根据需要来显示或隐藏某一个，加一个类似tooltip那边的formatter回调函数？
例如，我有6个月的数据（不是每天都有），在X轴坐标只想展示每个月有数据的第一天的axisTick和splitLine。

**Comment by kener** [comment]
赞建议。interval支持function后不可思议的强大，不仅是label，还能做智能区间分色了！
