### ISSUE TITLE
firefox下出现NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by liboysoft** [ecomfe/echarts#1094]
你好，很高兴使用echarts!

我们在项目应用的时候火狐下出现这个错误，场景是这样的：
我们前端用nginx，后端用virgo (tomcat)；前端使用框架是easyui，也就是说会有很多tab页，tab页是使用iframe。在其中一个tab页中，我们使用了echarts的折线图，并且跟后端以长连接的方式不断推送数据过来往图表里面加(addData)。

然而我们在打开多个tab页的时候，图表报错。

> NS_ERROR_FAILURE: 
> echarts-map.js (第 2693 行)

```JAVASCRIPT
 e.save(), this.setContext(e, r), this.setTransform(e), r.textFont && (e.font = r.textFont), e.textAlign = r.textAlign || "start", e.textBaseline = r.textBaseline || "middle";
```
在`chrome`下不会出现这种问题
> firefox 34

**Comment by errorrik** [comment]
NS_ERROR_FAILURE通常是请求的问题，下面的链接可能会有些帮助

http://stackoverflow.com/questions/11202153/ns-error-failure-on-javascript-post

**Comment by meathross** [comment]
这个有什么解决的办法饿？一般只要报错，就会一直报错，导致浏览器卡死。@liboysoft  @errorrik

**Comment by rocky-191** [comment]
遇到了同样的问题，chrome没问题，火狐报错

**Comment by 13620557355** [comment]
很郁闷，我也遇到这个问题，求解

**Comment by pea3nut** [comment]
看起来是 fx 没处理好 canvas API 调用的很频繁的时候的情况

https://stackoverflow.com/questions/8660867/firefox-throws-error-0x80004005-when-working-with-canvas

**Comment by Marybigdog** [comment]
有人解决了吗 求解
