### ISSUE TITLE
echarts 对 drilldown 明细图是否有支持计划？

### ISSUE THREAD

**Issue by gihnius** [ecomfe/echarts#1097]
或者现有没有好的替代方案？

**Comment by RiceZhang** [comment]
我们可能需要做一个类似有面包屑导航的 上钻 下钻的 一个实现， 有这方面的支持吗？或者说自定义图表的一个扩展提供？

**Comment by phping1** [comment]
其实利用万能的setOption就能够实现，看这里有详细的实现，且提供代码打包下载：http://phping1.github.io/2016/09/19/echarts-line-drill-down/
