### ISSUE TITLE
坐标轴刻度是否支持非线性？

### ISSUE THREAD

**Issue by charlestang** [ecomfe/echarts#1099]
比如现在的坐标轴刻度，都是 0，5，10，15，20，这样确实没问题，但是我要显示的数据有尖峰，
比如1，2，13，23，4，20100，4，5，6，这样以来，会发现，除了一个柱子特别高，其他都是在0附近，数据的细节被磨灭了。我希望数据刻度能按照指数来分布，甚至可以用函数，随意调整刻度线分布，这样，我能让数据的变化性，在某个区段比较敏感，在某个区段不敏感。之前用的jquery.flot 坐标轴有个transform 和 inversetransform属性，可以做到这个事情。不知道echarts是否支持？不支持的话，能否支持一下？

**Comment by kener** [comment]
跟后端有什么关系？这纯前端的数据映射。

**Comment by charlestang** [comment]
噢，明白了，就是js拿到数据后，先自己变换一下？好吧……
