### ISSUE TITLE
坐标轴时间型的使用问题

### ISSUE THREAD

**Issue by RomanticCryst** [ecomfe/echarts#1102]
示例line8.html中
    series : [
        {
            name: 'series1',
            type: 'line',
            showAllSymbol: true,
            data: (function () {
                var d = [];
                var len = 0;
                var now = new Date();
                var value;
                while (len++ < 5) {
                    d.push([
                        new Date(2014, 9, 1, 0, len * 10000),
                        (Math.random()*30).toFixed(2) - 0
                        //(Math.random()*100).toFixed(2) - 0
                    ]);
                }
                return d;
            })()
        }
    ]
series的data的第三个参数代表什么，是否有对itemStyle的支持

**Comment by kener** [comment]
你删了代码了吧，symbol是个function，用的就是第三个参数。这是数据维度的问题，如果你只有两个维度，传两个就好。
支持itemStyle，就像 http://echarts.baidu.com/doc/example/scatter.html 一样
