### ISSUE TITLE
English typo in banner3.png?

### ISSUE THREAD

**Issue by RiZKiT** [ecomfe/echarts#1103]
In ./doc/asset/img/banner3.png:

"200,000 data redering in seconds" feels wrong, you may ment: 

"200,000 data re**n**dering in seconds" or
"200,000 data re**n**dering**s** in seconds" or
"200,000 data re**n**dering**s** **per** second" ?

**Comment by kener** [comment]
Roger, should be rendering, thanks. :+1:

**Comment by kener** [comment]
done
