### ISSUE TITLE
在toolbox中新加一个按钮，实现"所有线条都不显示"

### ISSUE THREAD

**Issue by sunflowerss** [ecomfe/echarts#1104]
我现在的问题是，如何在option内部取到legend，并且设置为不显示
请给出一个思路或者代码，谢谢。

**Comment by kener** [comment]
option在你手。实例有getOption方法，设置legend的selected参数控制显示与否，重新setOption，玩EC数据驱动的思路一定要掌握。

**Comment by sunflowerss** [comment]
好的，已实现，非常感谢
