### ISSUE TITLE
扩展的区县地图上的区名以及县名重叠怎么办

### ISSUE THREAD

**Issue by yx142578** [ecomfe/echarts#1105]
县名重叠

**Comment by kener** [comment]
如果空间够，可以自己定义textFix参数，或者指定文本位置放开。
如果是太小地图就不可避免，无法同时显示，改成hover时显示是常见的作法。
或者还可以通过markLine从目标地方引出一条线到别的地方显示文本，类似pie的作法，需要自己写点markPoint的代码，无内置。

**Comment by yx142578** [comment]
@kener 多谢！描述的很清晰

**Comment by yx142578** [comment]
@kener  还有一个问题，markPoint上怎么显示名字。

**Comment by kener** [comment]
formatter
