### ISSUE TITLE
模块化单文件引入

### ISSUE THREAD

**Issue by Janking** [ecomfe/echarts#1111]
如果我当前页已经用了requirejs，还要模块化单文件引入echarts，该怎么做？

**Comment by kener** [comment]
尝试改用我们的esl.js？不会比require.js差的，ec里复杂的循环依赖（软依赖）require.js搞不定，有require.js实现我们没做到可用提 @errorrik @erik168

**Comment by errorrik** [comment]
好吉利的issue id

[esl](https://github.com/ecomfe/esl) 现在除了shim不支持外，其他amd feature都是完备的。
