### ISSUE TITLE
echarts在angularjs中如何当directive来写

### ISSUE THREAD

**Issue by liekkas** [ecomfe/echarts#1113]
hi,这是我写的一段代码，            
var chart = echarts.init(element);  这行报错 TypeError: Cannot read property 'init' of undefined。

烦请解答，谢谢！

js:
```
app.directive("areaMap",function(){
    return {
        link:function(scope,element,attrs,echarts){
            var chart = echarts.init(element);
            var option = {
                series : [
                    {
                        name: '中国',
                        type: 'map',
                        mapType: '中国',
                        selectedMode : 'single',
                        itemStyle:{
                            normal:{label:{show:true}},
                            emphasis:{label:{show:true}}
                        },
                        data:[
                            {name:'广东',selected:true}
                        ]
                    }
                ]
            };
            chart.setOption(option);
        },
        restrict:'EA'
    }
});
```
html中：
```
<area-map style="padding: 0px;height: 450px"></area-map>
```

**Comment by kener** [comment]
引入方式是script引入。保证执行init是echarts.js已经加载

**Comment by liekkas** [comment]
能获取到echarts，但还是不行，不知道我这种集成写法正确不 

function(scope,element,attrs,echarts){
            var chart = echarts.init(element);

function(scope,element,attrs){
            var chart = echarts.init(element);

这两者都试过

**Comment by kener** [comment]
很多人封装过，search echarts 问问他们吧
https://github.com/violet-day/angular-echarts
https://github.com/zuiyuexuan/angularjs-requirejs-echarts

**Comment by liekkas** [comment]
原来如此，多谢，解决了！请closed掉

**Comment by radishmillet** [comment]
@liekkas 请问后来是怎么解决这个init的问题的，最近也想用e-charts，不知道怎么写 directive

**Comment by liekkas** [comment]
@radishmillet 我封装了一下，你可以看看 https://github.com/liekkas/ng-echarts

**Comment by radishmillet** [comment]
@liekkas  谢谢谢谢~
