### ISSUE TITLE
toolbox中的功能是否能够默认启用？

### ISSUE THREAD

**Issue by achivil** [ecomfe/echarts#1114]
例如在toolbox中添加了dataZoom控件，是否能设置为默认启用该功能，不需要点击图标启用呢？

**Comment by kener** [comment]
暂无接口，如果你不介意工具栏上的显示状态不同步的话可以用这个hack

myChart.component.toolbox._onDataZoom({target:{id:myChart.component.toolbox.shapeList[1]}});
