### ISSUE TITLE
使用线图显示多个serie时，某些serie的最后几个数据不显示

### ISSUE THREAD

**Issue by gavincilp** [ecomfe/echarts#1117]
使用线图显示多个serie时，某些serie的最后几个数据不显示，放大后可以显示出来，缩小回去又不显示了
![qq 20150106144832](https://cloud.githubusercontent.com/assets/1650646/5625305/5c7a9a6e-95b3-11e4-80ab-00861a11eacb.png)
![qq 20150106144950](https://cloud.githubusercontent.com/assets/1650646/5625307/6202ead6-95b3-11e4-92b7-7db81eb638f0.png)

**Comment by kener** [comment]
不可解决的矛盾，你仔细想想1000px显示3000数据，1px（最小精度）下要响应呈现3个甚至更多的数据的时候你会怎么做？

**Comment by gavincilp** [comment]
1个像素是显示不了3个点，但是是后面的数据没显示出来就不对了吧

**Comment by kener** [comment]
数据长度没对齐

**Comment by gavincilp** [comment]
实际上已经对齐了，否则放大也应该不对齐，但是放大后那个数据就有了，缩小了数据又没了

**Comment by kener** [comment]
console.log(option.series[0].data.length, option.series[1].data.length)

**Comment by gavincilp** [comment]
明白了，谢谢
