### ISSUE TITLE
坐标轴名称能不能放在坐标轴正中位置，貌似现在只能放在 start / end 两端？

### ISSUE THREAD

**Issue by gihnius** [ecomfe/echarts#1118]
这个选项：
{string} nameLocation	'end'	数值型，时间型	坐标轴名称位置，默认为'end'，可选为：'start' | 'end'

是否支持放在中间？

**Comment by kener** [comment]
暂不支持，现阶段可以直接用一个markPoint作为文字载体显示到你希望显示的地方。

**Comment by gihnius** [comment]
@kener 好, 谢谢，有个建议，如果支持，可以在坐标轴末端加个箭头，然后通过箭头的 tooltip 显示完整的坐标轴名称。

**Comment by sdhhqb** [comment]
markPoint能不能取消出现时的动画效果呢。
