### ISSUE TITLE
怎么去手动触发地图上的点击事件

### ISSUE THREAD

**Issue by yx142578** [ecomfe/echarts#1119]
点击一个button 或者其他 东西，触发地图上某一个点的点击事件

**Comment by kener** [comment]
setOption，通过地图data的selected控制地图的区域选中样式更新。
调用你希望地图被选时需要调用的事件

**Comment by yx142578** [comment]
下一次setOption 无法取消上一次的选中状态，地图上会选中2块内容

**Comment by kener** [comment]
你需要响应地图选中事件并记录下来，自己维持这个hashmap并在二次setOption时利用这个确保唯一性
