### ISSUE TITLE
Hiding of x-axis column labels

### ISSUE THREAD

**Issue by brechmos** [ecomfe/echarts#1120]
I copied a bar chart from the website and implemented it.  The column labels seem to be hidden or visible depending on the width of the chart. Is there a way to have all the labels present and maybe just staggered vertically? (or rotated?)

The graphs are gorgeous.  Thanks for putting this out there.

**Comment by kener** [comment]
yeap, check this http://ecomfe.github.io/echarts/doc/doc-en.html#AxisAxislabel
and it can be controlled by axis.axisLabel.[ interval | rotate ]

thx for your appreciates.

**Comment by brechmos** [comment]
That's perfect.  Thank you.
