### ISSUE TITLE
Pie Chart allow to control inner label position

### ISSUE THREAD

**Issue by ehartford** [ecomfe/echarts#1122]
When Pie Chart's itemstyle.label.position is "inner", then it should use the "distance" option to decide the radius of the labels.  (currently the "distance" option only applies to chord charts.)  

This should be a percentage, 0% means the center of the circle, and 100% means the edge of the circle.

It's currently hard coded to 50% the radius of the pie, which is too close to the center.  I need to place my labels at around 80-85%.

**Comment by ehartford** [comment]
![image](https://cloud.githubusercontent.com/assets/1117701/5635253/616cfc0e-959c-11e4-919f-fc84a6698324.png)

**Comment by kener** [comment]
That would be a good idea. But I'm sorry for ECharts' pie chart can not support this right now.
We will make it in the future.

Thanks.

**Comment by albertshaw** [comment]
This function is really what i need, pls take a look at [PR-1138](https://github.com/ecomfe/echarts/pull/1138), hope it's ok for you
