### ISSUE TITLE
关于编码问题

### ISSUE THREAD

**Issue by huangjunhua** [ecomfe/echarts#1123]
现在echarts默认用的UTF-8，页面convert为GBK的时候，里面的编码部分会转换出错，因为项目这边统一使用GBK，echarts可否提供一个GBK版本的？谢谢

**Comment by kener** [comment]
抱歉，官方没有，但你可以把源码下载下来转换后重新打包。
但需要注意的是这样地图你可能会有问题，因为我们的地图数据是经过我们自己的压缩算法的，这个压缩算法利用了utf-8的编码，你可能需要改源码放弃这个压缩和解压过程。

**Comment by kener** [comment]
no，不会做这种时代倒退的事情就像不会花精力去优化IE8一样

**Comment by errorrik** [comment]
可以使用这种这种方式引入echarts

```html
<script src="echart-url" chartset="UTF-8"></script>
```

或者，对echarts的文件进行unicode转码
