### ISSUE TITLE
标准条形图的横纵坐标轴互换，dataZoom纵向布局在左侧或者右侧时，拖动区域与动态加入方向不相符

### ISSUE THREAD

**Issue by edisun** [ecomfe/echarts#1124]
标准条形图的横纵坐标轴互换，dataZoom在使用纵向布局时，无论在左侧或者在右侧。使用数据漫游，拖动或者增大区域动态加入数据与拖拽方向相反。如dataZoom在向y轴向下拖动时，图表中新显示内容则在y轴上方加入。操作方向与加入数据位置不符，会有歧义，请确认是否为bug或有修改方向方法，请指教，谢谢。

**Comment by kener** [comment]
赞！确实有这个问题，一直没人这样用过没注意到这个问题，后续修复。

谢谢反馈，
