### ISSUE TITLE
折线图最大值markPoint 错误

### ISSUE THREAD

**Issue by sarsshitou** [ecomfe/echarts#1128]
option = {
    "title": {
        "text": "电量仪历史数据",
        "link": "",
        "target": null,
        "subtext": "",
        "sublink": "",
        "subtarget": null,
        "x": "center",
        "y": "top",
        "textAlign": null,
        "backgroundColor": "rgba(0,0,0,0)",
        "borderColor": "#ccc",
        "borderWidth": 0,
        "padding": 5,
        "itemGap": 5
    },
    "series": [
        {
            "data": [
                "22.24",
                "22.16",
                "22.08",
                "22.24",
                "22.00",
                "22.48",
                "22.08",
                "10.0",
                "128.8",
                "130.3",
                "130.0",
                "129.7",
                "129.9",
                "129.6",
                "129.4",
                "129.6",
                "129.6",
                "128.7",
                "129.9"
            ],
            "markPoint": {
                "data": [
                    {
                        "type": "max",
                        "name": "最大值"
                    },
                    {
                        "type": "min",
                        "name": "最小值"
                    }
                ]
            },
            "name": "A相电流",
            "type": "line",
            "yAxisIndex": 0
        },
        {
            "data": [
                "25.52",
                "25.52",
                "25.52",
                "25.52",
                "25.60",
                "25.84",
                "25.44",
                "100.1",
                "105.7",
                "105.9",
                "106.0",
                "105.9",
                "105.9",
                "106.2",
                "106.0",
                "106.3",
                "106.0",
                "105.7",
                "106.8"
            ],
            "markPoint": {
                "data": [
                    {
                        "type": "max",
                        "name": "最大值"
                    },
                    {
                        "type": "min",
                        "name": "最小值"
                    }
                ]
            },
            "name": "B相电流",
            "type": "line",
            "yAxisIndex": 0
        },
        {
            "data": [
                "13.60",
                "13.52",
                "13.52",
                "13.60",
                "13.44",
                "13.76",
                "13.52",
                "10.0",
                "102.3",
                "102.6",
                "103.2",
                "102.9",
                "103.3",
                "103.3",
                "102.4",
                "102.6",
                "102.4",
                "102.1",
                "102.4"
            ],
            "markPoint": {
                "data": [
                    {
                        "type": "max",
                        "name": "最大值"
                    },
                    {
                        "type": "min",
                        "name": "最小值"
                    }
                ]
            },
            "markLine": {
                "data": []
            },
            "name": "C相电流",
            "type": "line",
            "yAxisIndex": 0
        }
    ],
    "legend": {
        "data": [
            "A相电流",
            "B相电流",
            "C相电流"
        ],
        "show": true,
        "orient": "horizontal",
        "x": "center",
        "y": "bottom",
        "backgroundColor": "rgba(0,0,0,0)",
        "bordercolor": "#ccc",
        "borderWidth": 0,
        "padding": 5,
        "itemGap": 10,
        "itemWidth": 20,
        "itemHeight": 14,
        "selectedModel": true,
        "selected": null
    },
    "xAxis": {
        "scale": true,
        "axisLine": {
            "show": true,
            "onZero": true
        },
        "type": "category",
        "show": true,
        "boundaryGap": true,
        "data": [
            "2014-10-14 10:37:30",
            "2014-10-14 10:48:13",
            "2014-10-14 11:24:17",
            "2014-10-14 11:40:22",
            "2014-10-15 13:19:19",
            "2014-10-15 13:23:32",
            "2014-10-15 13:24:37",
            "2014-10-15 13:29:31",
            "2014-10-15 14:00:56",
            "2014-10-15 14:41:22",
            "2014-10-15 14:45:21",
            "2014-10-15 15:57:02",
            "2014-10-15 16:31:49",
            "2014-10-15 17:12:47",
            "2014-10-16 9:44:24",
            "2014-10-16 10:24:56",
            "2014-10-16 10:26:58",
            "2014-10-16 11:55:17",
            "2014-10-16 15:22:59"
        ]
    },
    "yAxis": [
        {
            "type": "value",
            "axisLabel": {
                "show": true,
                "rotate": 0,
                "margin": 8,
                "clickable": false,
                "formatter": "{value}A"
            },
            "axisLine": {
                "show": true,
                "onZero": true
            },
            "scale": true,
            "name": "电流（A）"
        }
    ],
    "tooltip": {
        "show": true,
        "showContent": true,
        "trigger": "axis",
        "formatter": null,
        "islandFormatter": "0027{a} 003c br/003e{b} : {c}0027",
        "backgroundColor": "rgba(0,0,0,0.7)",
        "borderColor": "#333",
        "borderRadius": 4,
        "borderWidth": 0,
        "padding": 5,
        "showDelay": 20,
        "hideDelay": 100,
        "transitionDuration": 0.4
    },
    "grid": {
        "x": 80,
        "y": 60,
        "x2": 80,
        "y2": 60,
        "backgroundColor": "rgba(0,0,0,0)",
        "borderWidth": 1,
        "borderColor": "#ccc"
    },
    "backgroundColor": "rgba(255,255,255,0.8)",
    "calculable": false
}

![image](https://cloud.githubusercontent.com/assets/7335763/5657638/8faff350-972c-11e4-9cc7-ee4149dcecec.png)

**Comment by kener** [comment]
series.data数组内内容应该是Number，用string出现各种不可以预料的事情是不可控的

**Comment by sarsshitou** [comment]
改为Number后解决 谢谢
