### ISSUE TITLE
EChart 多数据柱状图，存在空值时，柱状不显示问题

### ISSUE THREAD

**Issue by JSoon** [ecomfe/echarts#1129]
如题，描述如下图
图1显示正常：
![1](https://cloud.githubusercontent.com/assets/7589350/5658309/b426c71e-973a-11e4-8d71-f3227eb36a3b.jpg)

图2显示异常：
![2](https://cloud.githubusercontent.com/assets/7589350/5658310/b50cf0e0-973a-11e4-9f00-504e7a421608.jpg)

这是一个 bug 么请问？@kener

**Comment by kener** [comment]
是的，谢谢反馈

**Comment by JSoon** [comment]
修复之后能否告知，谢谢：）@kener
