### ISSUE TITLE
[gauge]图表在IE11下的问题

### ISSUE THREAD

**Issue by pc61551** [ecomfe/echarts#1130]
你们好：

      我在应用仪表盘组件中发现了一个奇怪的问题。
      
      背景说明：我开发了一个KPI页面，然后这个页面中大约需要加载显示六七十个仪表盘。我在火狐跟IE10下边测试都是正常显示。但是在IE11下测试发现有一部分仪表盘未能加载显示。

       DEMO页面源码如下：

       <!DOCTYPE html>
<html>
<head>
        <title>test</title>
        <meta http-equiv="x-ua-compatible" content="IE=edge" />
        <script type="text/javascript" src="js/echarts.js"></script>
        <style>
            .chart{ width:300px; height:300px; float:left; }
        </style>
</head>
<body>
    <div id="Div1" class="chart"></div>
    <div id="Div2" class="chart"></div>
    <div id="Div3" class="chart"></div>
    <div id="Div4" class="chart"></div>
    <div id="Div5" class="chart"></div>
    <div id="Div6" class="chart"></div>
    <div id="Div7" class="chart"></div>
    <div id="Div8" class="chart"></div>
    <div id="Div9" class="chart"></div>
    <div id="Div10" class="chart"></div>
    <div id="Div11" class="chart"></div>
    <div id="Div12" class="chart"></div>
    <div id="Div13" class="chart"></div>
    <div id="Div14" class="chart"></div>
    <div id="Div15" class="chart"></div>
    <div id="Div16" class="chart"></div>
    <div id="Div17" class="chart"></div>
    <div id="Div18" class="chart"></div>
    <div id="Div19" class="chart"></div>
    <div id="Div20" class="chart"></div>
    <div id="Div21" class="chart"></div>
    <div id="Div22" class="chart"></div>
    <div id="Div23" class="chart"></div>
    <div id="Div24" class="chart"></div>
    <div id="Div25" class="chart"></div>
    <div id="Div26" class="chart"></div>
    <div id="Div27" class="chart"></div>
    <div id="Div28" class="chart"></div>
    <div id="Div29" class="chart"></div>
    <div id="Div30" class="chart"></div>
    <div id="Div31" class="chart"></div>
    <div id="Div32" class="chart"></div>
    <div id="Div33" class="chart"></div>
    <div id="Div34" class="chart"></div>
    <div id="Div35" class="chart"></div>
    <div id="Div36" class="chart"></div>
    <div id="Div37" class="chart"></div>
    <div id="Div38" class="chart"></div>
    <div id="Div39" class="chart"></div>
    <div id="Div40" class="chart"></div>
    <div id="Div41" class="chart"></div>
    <div id="Div42" class="chart"></div>
    <div id="Div43" class="chart"></div>
    <div id="Div44" class="chart"></div>
    <div id="Div45" class="chart"></div>
    <div id="Div46" class="chart"></div>
    <div id="Div47" class="chart"></div>
    <div id="Div48" class="chart"></div>
    <div id="Div49" class="chart"></div>
    <div id="Div50" class="chart"></div>
    <div id="Div51" class="chart"></div>
    <div id="Div52" class="chart"></div>
    <div id="Div53" class="chart"></div>
    <div id="Div54" class="chart"></div>
    <div id="Div55" class="chart"></div>
    <div id="Div56" class="chart"></div>
    <div id="Div57" class="chart"></div>
    <div id="Div58" class="chart"></div>
    <div id="Div59" class="chart"></div>
    <div id="Div60" class="chart"></div>
    <div id="Div61" class="chart"></div>
    <div id="Div62" class="chart"></div>
    <div id="Div63" class="chart"></div>
    <div id="Div64" class="chart"></div>
    <div id="Div65" class="chart"></div>
    <div id="Div66" class="chart"></div>
    <div id="Div67" class="chart"></div>
    <div id="Div68" class="chart"></div>
    <div id="Div69" class="chart"></div>
    <div id="Div70" class="chart"></div>
    <div id="Div71" class="chart"></div>
    <div id="Div72" class="chart"></div>
    <div id="Div73" class="chart"></div>
    <div id="Div74" class="chart"></div>
    <div id="Div75" class="chart"></div>
    <div id="Div76" class="chart"></div>
    <div id="Div77" class="chart"></div>
    <div id="Div78" class="chart"></div>
    <div id="Div79" class="chart"></div>
    <div id="Div80" class="chart"></div>
    <div id="Div81" class="chart"></div>
    <div id="Div82" class="chart"></div>
    <div id="Div83" class="chart"></div>
    <div id="Div84" class="chart"></div>
    <div id="Div85" class="chart"></div>
    <div id="Div86" class="chart"></div>
    <div id="Div87" class="chart"></div>
    <div id="Div88" class="chart"></div>
    <div id="Div89" class="chart"></div>
    <div id="Div90" class="chart"></div>
    <div id="Div91" class="chart"></div>
    <div id="Div92" class="chart"></div>
    <div id="Div93" class="chart"></div>
    <div id="Div94" class="chart"></div>
    <div id="Div95" class="chart"></div>
    <div id="Div96" class="chart"></div>
    <div id="Div97" class="chart"></div>
    <div id="Div98" class="chart"></div>
    <div id="Div99" class="chart"></div>
    <div id="Div100" class="chart"></div>

    <script type="text/javascript">
        require.config({
            paths: {
                echarts: 'js'
            }
        });
        require(
            [
                'echarts',
                'echarts/chart/gauge'
            ],
            function (ec) {
                for (var i = 1; i < 101; i++) {
                    var chart = ec.init(document.getElementById('Div' + i + ''));
                    var option = {
                        "animation": false,
                        "series": [
                                        {
                                            "name": "chart",
                                            "type": "gauge",
                                            "min": 0,
                                            "max": 200,
                                            "splitNumber": 10,
                                            "axisLine": {
                                                "lineStyle": {
                                                    "color": "auto",
                                                    "width": 8
                                                }
                                            },
                                            "axisTick": {
                                                "splitNumber": 10,
                                                "length": 12,
                                                "lineStyle": {
                                                    "color": "auto"
                                                }
                                            },
                                            "axisLabel": {
                                                "textStyle": {
                                                    "color": "auto"
                                                }
                                            },
                                            "splitLine": {
                                                "show": true,
                                                "length": 16,
                                                "lineStyle": {
                                                    "color": "auto"
                                                }
                                            },
                                            "pointer": {
                                                "width": 5
                                            },
                                            "detail": {
                                                "formatter": i,
                                                "offsetCenter": [0, "50%"],
                                                "textStyle": {
                                                    "color": "blue",
                                                    "fontWeight": "bolder",
                                                    "fontSize": 30
                                                }
                                            },
                                            "data": [{ "value": i, "name": ""}]
                                        }
                                    ]
                    };
                                    chart.setOption(option);
                }
            }
        );
    </script>
</body>
</html>

在火狐下的显示效果：
![default](https://cloud.githubusercontent.com/assets/5986948/5659074/c7ef72f8-9746-11e4-80fd-7ba156989820.png)

在IE10下也是显示正常：
![ie10](https://cloud.githubusercontent.com/assets/5986948/5659078/d862af24-9746-11e4-9335-140496a2bba3.png)

在IE11默认情况下，显示到【36】后，下边的仪表盘就没能正常加载：
![ie11](https://cloud.githubusercontent.com/assets/5986948/5659087/f39ab93a-9746-11e4-9129-a39c462981a4.png)

但是奇怪的是，在IE11下边，按F12打开开发工具后，重新刷新页面，后面的仪表盘有能正常显示了：
![ie11_2](https://cloud.githubusercontent.com/assets/5986948/5659117/4cb5c3a2-9747-11e4-92ad-a4f6db4a8176.png)

我有怀疑过是不是echarts.js里边的console对象判断的问题，但是我全部注释了console后重新测试，发现问题还是存在。

谢谢！

**Comment by kener** [comment]
IE11做了些“性能优化”，他有时候会直接跳过了“远离”可视区域的canvas渲染，我只能这样描述，我也确实碰到过。so，建议滚动时触发当前视区内图表更新（resize或refresh啥的），要不就是分页显示不要太过“远离”

**Comment by pc61551** [comment]
好的。。我试试。。谢谢解答！

**Comment by pc61551** [comment]
你好：

       但我在Demo页面做了修改，缩小了仪表盘的尺寸。让所有的仪表盘都在同一页面上显示。可是在IE11上。还是会在【36】这边停了：

​谢谢！

在 2015年1月8日 下午3:56，linfeng <notifications@github.com>写道：
