### ISSUE TITLE
地图数据迁移特效问题

### ISSUE THREAD

**Issue by huyinghuan** [ecomfe/echarts#1133]
因为定制需要， 需要实现 展示实时数据迁移（官方文档中没有这个demo）， 现在通过修改一部分代码（仅测试使用）基本了实现了 需求。
修改的代码是src/chart/base.js的第1501到1510行将
```
        animationMark: function (duration, easing, addShapeList) {
            var shapeList = addShapeList || this.shapeList;
            for (var i = 0, l = shapeList.length; i < l; i++) {
                if (!shapeList[i]._mark) {
                    continue;
                }
              this._animateMod(false, shapeList[i], duration, easing);
            }
            this.animationEffect(addShapeList);
        },
```
注释掉一部分：
```
        animationMark: function (duration, easing, addShapeList) {
            var shapeList = addShapeList || this.shapeList;
            // for (var i = 0, l = shapeList.length; i < l; i++) {
            //     if (!shapeList[i]._mark) {
            //         continue;
            //     }
            //   this._animateMod(false, shapeList[i], duration, easing);
            // }
            this.animationEffect(addShapeList);
        },
```
效果如下图（ubuntu chrome）：
![20150108-160059_capture](https://cloud.githubusercontent.com/assets/3005433/5659602/e4c0cdd8-974f-11e4-94e5-3d541df5b031.gif)

但是在firefox下， mac 下的chrome， firefox， windows下的chrome都会出现一下问题， 炫光移动结束后， 会出现残余的光晕，如下图（因为没有找到firefox的git录制工具，仅贴一个静态效果图）：
![image](https://cloud.githubusercontent.com/assets/3005433/5659645/a8a3a914-9750-11e4-9335-ac1b7339fb42.png)

我去找了 上述关联的代码/src/util/ecEffect.js,修改了部分参数 但是没有发现找到关键代码或参数。
我也修改了makeline的参数effect的参数```shadowColor: 'rbga(0,0,0,0)'``` 发现 还是有残影，只是没有那么粗了而已。

有没有办法能够去除掉这些残余的光晕？

**Comment by kener** [comment]
残影的事情存在已久，我们是是过很多方法，包括用原生canvas实现绘制时也会出现这个问题，暂时没找到彻底解决的方法。
现阶段我们一般是把底色调整未接近残影的色调，然后一段时间后调用refresh以清除残影。

**Comment by huyinghuan** [comment]
用node-webkit 0.8版 打包后，window 7， ubuntu， xp下都没有出现残影问题了

**Comment by kener** [comment]
那么神奇？什么情况？

**Comment by huyinghuan** [comment]
不清楚， 估计是浏览器的原因造成的。我用node-webkit 下面 所有的残影都没有，测试通过了ubuntu， xp， window7 。 只有 mac没测。  和浏览器渲染引擎有关？
node-webkit的版本
0.8.6: (Apr 18, 2014, based off of Node v0.10.22, Chrome 30.0.1599.66)

下载了linux 64位和 window 32位进行的测试。

**Comment by kener** [comment]
你是自己编译了个chrome？

**Comment by huyinghuan** [comment]
没有， 是直接拿node-webkit 编译好的执行文件打包的。
