### ISSUE TITLE
IE11 下的attachEvent  错误问题

### ISSUE THREAD

**Issue by loveitmac** [ecomfe/echarts#1134]
发现在IE11下，使用echarts时会出现 attachEvent 错误，查过资料，发现IE11是去除了该函数。
echarts应该使用了该函数，是否有处理方案？

**Comment by kener** [comment]
啥意思？有判断啊，我也是IE11，好着啊

**Comment by loveitmac** [comment]
@kener  多谢，发现是jQuery版本问题。
