### ISSUE TITLE
echarts的散点图、气泡图、条形图在ie7、ie8不显示

### ISSUE THREAD

**Issue by liuzl0218** [ecomfe/echarts#1135]
百度下载：echarts-2.1.10\doc\example\www2\js\echarts-all.js
使用非模块化加载图形，在ie7和ie8下散点图、气泡图、条形图不显示

另外，添加的dataZoom区域缩放，ie7、ie8下使用不流畅经常卡克

**Comment by kener** [comment]
看控制台是否有报错吧，检查自己的代码。
EC已经18个月了，如果ie7、8真用不了，你不会是第一个发现的。

ps，关于ie8-只保证能看，不保证用户体验，我们并不希望他能活更久。
