### ISSUE TITLE
github当前版本用echarts-optimize构建后面积图yAxis的name无法显示

### ISSUE THREAD

**Issue by moonshine42** [ecomfe/echarts#1136]
github当前版本用echarts-optimize构建后面积图yAxis的name无法显示
但是echarts/build/dist/路径下的文件正常，不过，项目需要横坐标抽稀后仍保留峰值(有对源码做了小修改)，需要重新编译，但重新编译后yAxis的name不能显示。
可以排除自己修改源码造成的影响，因为直接下载github最新版，直接编译也是存在yAxis的name无法显示的问题。
麻烦帮忙看下哈~谢谢

**Comment by kener** [comment]
谢谢反馈，还在开发就有人测试，真好：）

**Comment by moonshine42** [comment]
响应好及时：）   赞！

**Comment by camnpr** [comment]
yAxis的name无法显示的问题，移动版的，没有修复。
