### ISSUE TITLE
symbol自定义图片不应被自动拉伸扩张成正方形

### ISSUE THREAD

**Issue by iamweilee** [ecomfe/echarts#1140]
内置的markpoint symbol可以再加几种么？ 还有自定义的symbol 可不可以 保留它原来的样式 而不是拉伸使它变成正方形

**Comment by kener** [comment]
不会再增加更多内置了。
-_- |||，真心的请思考一下，symbol要求宽高相等并不阻碍你做出任何显示比例的图形，宽高相等是个简单而合理的定位逻辑，可以开放出这个比例让用户使用，但懂做图的人真心不需要也不会去用，而且以我的经验随意让我选，我也更愿意使用1:1的定位逻辑比例去实现自定义图形。

**Comment by iamweilee** [comment]
我的情形是这样的。我需要一个10像素宽 1像素高的图形；
的确，我可以做成10乘10的图片，然后再图片的中间位置画出我需要的1像素高的线，但我有另个需求，我需要鼠标hover到这个横线上时显示tooltip，那么如果做成10乘10的图片问题就来了，因为这个图片是10乘10的，只有中间部分是我实际需要的，其余的都是透明的，那么当我hover到透明部分时tooltip也显示出来了，但这不是我需要的结果，我只是想hover到那根横线上才出来tooltip。
不知道是否有更好的方法变通一下解决这问题。

**Comment by kener** [comment]
恩，那就没办法了，其实1px是很难hover的，对于小于4px的图形我还专门做了交互扩展
