### ISSUE TITLE
axisPointer 设置的lineStyle或者crossStyle宽度不能精确展现

### ISSUE THREAD

**Issue by iamweilee** [ecomfe/echarts#1141]
axisPointer 设置的lineStyle或者crossStyle宽度为1 但实际图形上看到的效果明显比1px粗哈

**Comment by kener** [comment]
亚像素优化

**Comment by iamweilee** [comment]
![222](https://cloud.githubusercontent.com/assets/1096160/5704432/38b6a78c-9aac-11e4-82c9-97a31b5466e5.jpg)
这张图上 k线和成交量的axispointer的linestyle设置的width都是1px，为何两张图上的线看上去宽度不一样呢，k线的图上的线看上去是2px。成交量图上的线看上去却是期望的1px。  为何呢。
