### ISSUE TITLE
x轴为Time类型时，浏览器不显示内容。后台无提示错误

### ISSUE THREAD

**Issue by spp1987** [ecomfe/echarts#1148]
hi，如题。
在IE11版本以及以下版本后台无错误，绘图区域也展示，legend也显示，但是数据不显示。
360兼容模式也无法显示，极速模式下数据能展示。谷歌下数据能展示，火狐不能展示数据。

**Comment by kener** [comment]
估计是option中的time的数据类型，只接受new Date能有效的参数。
