### ISSUE TITLE
[Feature] [Gauge] Is there a way to have clickable axisLine ?

### ISSUE THREAD

**Issue by RobinDev** [ecomfe/echarts#1149]
Hello,

Is there a way to have clickable axisLine with `Gauge` ?

Thank you for sharing.

**Comment by kener** [comment]
I'm afraid not. Why you need a clickable axisLine? What is the difference interactive between them?

**Comment by RobinDev** [comment]
Ok,
I wanted a `half pie` with the `gauge cursor` (and so, have a on click function).

But finally, I draw a `half pie` from a `pie` (with half invisible) and forgot this cursor idea for the time.

Thank you.

I think we can close this issue.

**Comment by kener** [comment]
Aha ~, you create a new usage.
