### ISSUE TITLE
折线图的dataZoom能否指定下标而不是百分比？

### ISSUE THREAD

**Issue by nilday** [ecomfe/echarts#1150]
在对折线图的dataZoom进行处理的时候，如果是x轴的项目数超过了100，使用dataZoom的0到100的选项就不能很好的指定到某个特定点的起止位置（如果我没猜错是使用了取整操作？）。能否dataZoom的start end选项使用index来表示而不是0到100？同理DATA_ZOOM事件能否返回下标而不是0-100的百分比，在转化 时候总会失去一些精度。

**Comment by kener** [comment]
start是floor，end是ceil。不应该有无法指定的位置啊？取index只是一个乘法问题。

**Comment by nilday** [comment]
实际上看来确实有精度问题
start : start=='start'?0:xAxis.indexOf(start)/xAxis.length*100,
end : end=='end'?100:xAxis.indexOf(end)/xAxis.length*100
这样一个语句，其中start,end分别代表横轴序列xAxis中的一个元素，这样取出来的start，end不会精确的显示为以start为开始，end为结束的一个区间。

另一方面，在拖动data_zoom产生DATA_ZOOM事件的时候，由于返回的是0-100的整数，如果横轴元素大于100个，会出现拖动到多个元素都返回同一个整数的情况，无法精确获取到底起止位置是哪一个index。

**Comment by kener** [comment]
你是对的，dataZoom事件返回的start和end不应该去精度，已升级，谢谢反馈。
