### ISSUE TITLE
模块化引入的bug

### ISSUE THREAD

**Issue by kevinwon1985** [ecomfe/echarts#1153]
echarts2.1.10中，我使用了requireJS作为模块加载器，采用 “模块化单文件引入（推荐）” 的方式使用echarts。 当require('echarts/chart/line')时， 控制台会抛出404, 找不到'echarts/util/shape/HalfSmoothPolygon'的模块文件。

解决办法， 将line.js中的'echarts/util/shape/HalfSmoothPolygon'移动到'echarts/chart/line'模块上。

其他这类图表模块文件包含多个js模块的都有该问题。

我猜想是你们的合并压缩工具echarts-optimizer 出了问题。

**Comment by kener** [comment]
@erik168 @errorrik

**Comment by errorrik** [comment]
检查了一下构建产物，line.js里面是包含`define("echarts/util/shape/HalfSmoothPolygon"`片段的，也就是说这个模块是存在的。

可以换用[esl](https://github.com/ecomfe/esl)试试，或者把你的代码贴上来看看？

**Comment by kevinwon1985** [comment]
line.js里是包含define("echarts/util/shape/HalfSmoothPolygon" 没错..但是顺序不对..把这个放到define('echarts/chart/line',上面去就没这bug了.

**Comment by errorrik** [comment]
那就是requirejs实现的问题了。

amd的提出人，requirejs的作者James Burke在amd spec文档的`Transporting more than one module at a time`章节中有提到

> Multiple define calls can be made within a single script. The order of the define calls SHOULD NOT be significant. Earlier module definitions may specify dependencies that are defined later in the same script. It is the responsibility of the module loader to defer loading unresolved dependencies until the entire script is loaded to prevent unnecessary requests.

see: https://github.com/amdjs/amdjs-api/blob/master/AMD.md

所以，请你先检查requirejs的版本是不是最新的2.1.15？如果是并且还有问题，不如试试esl？

**Comment by kevinwon1985** [comment]
我之前是2.1.5， 换成2.1.15后， 问题依然存在。对比这文档，应该是requireJS实现有问题。
不过鉴于requireJS的用户数，仍然建议你们的修复此问题。

**Comment by huyinghuan** [comment]
这个问题确实是存在， 表示遇到过

**Comment by errorrik** [comment]
这个issue我们会一直开着，并安排尝试optimize产物支持requirejs。解决了或解决不了会在此issue里说明。

**Comment by errorrik** [comment]
经过测试，即使我们反转了模块定义的顺序，仍然没有好转。在某种特定的顺序下，使用requirejs能让图表正常展现，但是浏览器还是对很多模块发起了很多无用请求。

这个问题，我们猜测是因为模块存在循环依赖，对于循环依赖，requirejs对装载时依赖和运行时依赖的加载顺序有特定要求。我们之前分析过requirejs的加载机制，是无法解决所有类型的循环依赖的。

所以，我只能建议遇到这个问题的朋友，使用鲁棒性更好的esl。

**Comment by kevinwon1985** [comment]
谢谢。要是循环依赖的话，requirejs还真是无解。

**Comment by Gaubee** [comment]
我的天，你确定是循环依赖的问题？
是，requireJS确实在循环依赖上不够智能，但是我看你的源代码后，原因只是出现在requireJS在依赖定义与模块定义的BUG，你把lien.js文件里面：```define("echarts/util/shape/HalfSmoothPolygon"```放到```define("echarts/chart/line"```前面，就解决了。我的requireJS版本是：2.1.14

**Comment by Gaubee** [comment]
我自己反转了模块定义的顺序，确实可以不报错。
但是关于循环依赖，我看你源代码后，核心文件echarts.js的模块定义与依赖运作都很正常啊，不知道 @errorrik 你说的循环依赖问题在哪里。

----
@kevinwon1985  你可以把line.js文件里头的```define("echarts/util/shape/HalfSmoothPolygon"```放到```define("echarts/chart/line"```前面，就解决了。我的requireJS版本是：2.1.14

**Comment by kevinwon1985** [comment]
@Gaubee =,=我提问题的时候就，已经提出了这个解决方案了。
不过后面说的循环依赖造成的问题仍然会存在，line.js 里的两个模块没有循环依赖， 才能通过反转模块定义顺序解决。

**Comment by Gaubee** [comment]
@kevinwon1985 嗯，我后来也不想改加载器，毕竟已经也写了一些requireJS插件，换加载器的话有点伤，目前是想用一个的iframe指到特定页面，往里头加载echarts.js，然后传入相关的代码来运行echarts。

**Comment by lieefu** [comment]
echartjs不该污染模块定义环境。如果先引用echarjs，lodash就无法使用，因为chartjs定义了全局define，让lodash误以为是被模块化引用，放弃全局dash的定义了。请chartjs放弃这样的引用模式。让用户显式使用ejs或者requirejs，不要一职两则，既然是chart插件，就不要做模块引用插件职责了。同意@zhump 的观点，不过最好还是跟requireJS兼容。echartjs做的还是不错的，功能上面给点赞。
