### ISSUE TITLE
统计某个时间区间内某个ip的访问次数趋势图，用哪种图做比较合适？

### ISSUE THREAD

**Issue by huguangju** [ecomfe/echarts#1155]
要用图表示出某个时间区间内某个ip的访问次数趋势，一个ip可能在某天只访问一次，或连续或n天断续访问n次。
x轴为时间(天)，y轴为次数，z轴为某个ip（如何表示），柱状和拆线都不适合。散点图可能会适合一点，但无法描述时间趋势。
用哪种图做比较合适呢？

**Comment by kener** [comment]
ip应该作为系列，如果每次查看的ip个数不多，折线和柱形都合适。
如果ip数很多，散点图就可以，散点图x轴可以是time啊
