### ISSUE TITLE
请问force图数据比较多时布局速度慢的问题

### ISSUE THREAD

**Issue by SoAanyip** [ecomfe/echarts#1157]
您好，我想请问一下force图，是必须先让点平铺了再计算聚集系数的吗？因为觉得平铺之后重绘的过程在数据多（例如100k点100k线）的时候太漫长了，有办法避免吗？

**Comment by pissang** [comment]
对于原始的数据布局过程是难免的，平铺只是随机了一个初始化位置（在不提供位置的情况下）。不过确实应该有个机制可以本地使用脚本预计算布局，最后展现的时候可以跳过布局直接绘制。

**Comment by SoAanyip** [comment]
可能在这种情况下比较适用的是动态的加载？比如先加载10%，剩下的数据逐渐的计算完再往上添加？

**Comment by pissang** [comment]
计算的过程是全局的，每个节点都可能影响到其它的节点，不能做增量。

100k 点和线的图 其实不光是对于布局，对于前端的渲染也是很大的压力。

**Comment by SoAanyip** [comment]
是的。。现在正在苦恼这个数据量太大导致加载速度的问题。如果要做现场演示，就只能提前好几分钟先加载好。

**Comment by pissang** [comment]
能大致描述一下你们数据的形状么，多少节点多少边？

**Comment by SoAanyip** [comment]
遇到问题的是一个微博转发层次图，以发微博人为中心辐射形状的展示，选取的是一条有100k转发的微博，以点为人 边为转发关系，所以约有点边各100k，每一个点都只设置成如{category:2, name: '123',value : 8}的形式，边是{source : '123', target : '234'}的形式。

**Comment by SoAanyip** [comment]
是的 :cold_sweat: 只是要求上需要展示数据越多越好。。  谢谢你解答疑问
