### ISSUE TITLE
能否设置dataRange的当前值

### ISSUE THREAD

**Issue by zhangxuanchao** [ecomfe/echarts#1158]
echarts实例中的“ECharts扩展百度地图扩展BMap”页面，缩放地图或者平移地图的时候，echarts都要刷新。这样导致用户之前选择的dataRange的范围又恢复到最初的状态。是否有方法可以获取dataRange的当前值，然后在刷新完后设置回去。

**Comment by kener** [comment]
响应dataRange事件，refresh后调用更新dataRange的值
