### ISSUE TITLE
地图markLine， markPoint清除问题

### ISSUE THREAD

**Issue by huyinghuan** [ecomfe/echarts#1159]
在API中有写到
```
{self} delMarkLine
{number} seriesIdx 
{string} markName	删除单个标线接口，其中 
seriesIdx 系列索引 
markName [标线]名称
```
但是没有批量清除的所有的markLine或者markPoint的接口。当批量添加markLine 或者markPoint的时候，这些markLine，markPoint的数据会持续累积， 造成浏览器卡顿现象。在这中（不断循环）批量添加的情况下， 上述接口逐个删除 批量添加的数据是不合适的。 另外 尝试了refresh方法，发现该方法没有做清除工作（按一般实际应用需求 不做清除是正确的。）但对于我目前的需求来说是清除数据， 因为在下面这个应用中不存在 地图数据， 更多的还是对于了markLine和markPoint的处理。
这个是正常效果(持续运行时间比较短)：
![20150114-114101_capture](https://cloud.githubusercontent.com/assets/3005433/5733703/09d3033e-9be2-11e4-9575-e1878e7df30e.gif)

当不断添加数据后，cpu负载明显增加，画面出现严重卡顿， 炫光效果消失，线变成点，不连续，因此需要对已存在的markLine数据进行清理， 这里卡顿效果无法截图，在每秒添加10-20条数据后，经过大概20十分钟画面就明显出现了卡顿现象。

这个是定时refresh刷新的效果（从这里我发现最开始的数据都重新显示出来了，数据没有进行清除）：
![20150114-114255_capture](https://cloud.githubusercontent.com/assets/3005433/5733712/5d71a6f8-9be2-11e4-9e15-9e987f9eed58.gif)

通过读原代码 暂时没有找到相关markPoint，markLine的数据存在什么地方，和存储的动作。能否指出相关代码，方便修改。（通过对delMarkPoint等函数的分析，知道数据存在什么地方了，但是没有找到这个数据在执行addMarkPoint存储的相关关代码）谢谢！！

另附：修改了一行去除实线：
echarts-all.js第14411行：
由
```
                 if (!shapeList[i]._mark) {
                     continue;
                 }
```
修改为：
```
                 if (!shapeList[i]._mark || shapeList[i]._mark === 'line') { //break_point
                     continue;
                 }
```

**Comment by kener** [comment]
批量删除建议用setOption，通过改数据来改变图表，注意第二个参数要传入true。

**Comment by huyinghuan** [comment]
因为只有一个页面需要而且只有一个地图展示不涉及其他的图形，干脆就一条道走到黑了，已经修改源码了 嘿嘿。 echart 支持很快速，非常感谢！ 另外问一句，如果浏览器长时间（24小时，循环）播放echart的特效(类似第一个图)会不会出现使浏览器资源占用过多 变卡的情况？ 或者说什么情况可能会出现浏览器渲染echarts特效时卡顿（pc只运行基本系统服务和浏览器）？ 现在有个需求是把echarts结合数据用node-webkit封装成一个包安装到树莓派上,这样可以很方便的进行数据演示。但是树莓派的配置比较低，不知道扛不扛得动... 树莓派公司采购去了，所以还没测试....

**Comment by zhaojun12** [comment]
你好，左下角动态变化的数据显示是怎么做到的？谢谢

**Comment by hktalent** [comment]
@huyinghuan  怎么动态添加数据，不清除原数据啊？
另外，这些线条 和光效，为什么不用html5的canvas啊？这个效率比svg好很多，当数据量大的时候也不至于卡顿
