### ISSUE TITLE
曲线图legend与xAxis重叠错乱

### ISSUE THREAD

**Issue by moonshine42** [ecomfe/echarts#1160]
legend放于底部，并且legend个数较多的情况下，横坐标与图例会重叠。
![image](https://cloud.githubusercontent.com/assets/8499671/5734058/c8fd04b6-9be8-11e4-8ce3-bf2ae0644838.png)

**Comment by kener** [comment]
配置grid留出空间

**Comment by moonshine42** [comment]
但是这样在个数少的情况下又感觉有点浪费空间，要动态控制gird的y2也不好控制，因为随着图例的字符长度不同，要达到多少个会产生换行是不确定的

**Comment by errorrik** [comment]
这个我们没有办法动态计算。

如果预期图例个数或字数比较多，还是建议留出超过一行的空间。这样，只要不是图例个数太少，就算只有一行，显示效果也不会很突兀。

**Comment by Object-Kandy** [comment]
如果显示数目较多的话，如何控制折线分开显示啊 就是别堆积到一块

**Comment by kener** [comment]
多图联动

**Comment by modeyang** [comment]
请问这个问题解决了吗？

**Comment by Darren-chenchen** [comment]
<img width="331" alt="2018-09-13 4 53 48" src="https://user-images.githubusercontent.com/16269032/45478056-a4dfff00-b775-11e8-80f1-ed7211f1a6f0.png">
怎么才能往下排版呢
