### ISSUE TITLE
如何让 legend 区分坐标轴？

### ISSUE THREAD

**Issue by gihnius** [ecomfe/echarts#1165]
如果 x 为类目，有两个 y 坐标轴的时候， legend 都是显示在一块的，很难区分那个是 左轴或右轴的？
有什么好解决办法吗？

**Comment by kener** [comment]
https://github.com/ecomfe/echarts/issues/973
legend只是一方面，双轴要做视觉引导的，axisLine要跟series有呼应关系，只有两个系列好办，同色就行，多个系列就冷暖色调。

**Comment by gihnius** [comment]
嗯，谢谢。只是觉得 legend 支持的话会比较清晰。
