### ISSUE TITLE
Iphone6多图情况下会崩溃

### ISSUE THREAD

**Issue by ShanxiangWei** [ecomfe/echarts#1166]
环境：iphone6、6+, tlc闪存
浏览器：safari、chrome
页面场景：一个条形图，一个折线图，2个柱形图
表现：页面重刷4、5次然后浏览器崩溃，如果访问例子的主题页面，手机直接崩溃重启

**Comment by errorrik** [comment]
我们正在针对mobile设备进行体验和性能的优化，近期将会完成，感谢关注。

**Comment by ShanxiangWei** [comment]
据说本月会有一个移动端版本，不知何时会release？谢谢

**Comment by joostshao** [comment]
MX4的浏览器,很卡,性能上还需要提升.

**Comment by pissang** [comment]
echarts-m？
