### ISSUE TITLE
请问force图不能从categories里面设置每一类的linkStyle吗？

### ISSUE THREAD

**Issue by SoAanyip** [ecomfe/echarts#1167]
例如从
```
categories : [
    {
         name: '类1',
         itemStyle : {
            normal : { 
                linkStyle : {
                    //...here
                }
            }
        }
    }
```

而且设置nodeStyle也不是在normal里面的nodeStyle设置的吗？直接在normal里面设置就生效了，好像跟doc有出入？

**Comment by pissang** [comment]
category 只对节点分类，所以是直接使用 normal 下的颜色设置，不会分为 nodeStyle 和 linkStyle，文档确实没有表述清楚，抱歉，力导向图中单个节点和category上的itemStyle是没有nodeStyle的。
