### ISSUE TITLE
数据区域选择和ios不兼容？

### ISSUE THREAD

**Issue by advanceSS** [ecomfe/echarts#1169]
数据区域选择在ios上面不能使用，也就是滑动条不能滑动

**Comment by kener** [comment]
发过邮件了吧。。。

**Comment by advanceSS** [comment]
是的!请问echarj mobile 这个月底回发布吗？老板催着要项目呢

**Comment by kener** [comment]
不用等ec-m发布，自己用源文件构建主版本就已经能用了

**Comment by advanceSS** [comment]
是的，我知道我已经构建成功了，但是有很多兼容性的问题，就比如我提的数据区域选择的功能已经做好了，在android上面很好用就是在ios上面不能滑动？

**Comment by kener** [comment]
确定你用的是最新的zrender源码？

**Comment by advanceSS** [comment]
我是前几天才做的，js文件都是从官网下载的呀！

**Comment by advanceSS** [comment]
我刚看了是2014/12/11 的应该是最新的吧

**Comment by kener** [comment]
用github上的源码

**Comment by advanceSS** [comment]
为什么我换成github上的js文件会出现require失败
