### ISSUE TITLE
小数的精度问题

### ISSUE THREAD

**Issue by sukui123** [ecomfe/echarts#1170]
如何在图形中控制小数的精度问题，例如有一组数据 data:[11, 11, 15, 13, 12, 13, 10.3333333333333],如何控制小数精度？

**Comment by kener** [comment]
你指的是什么？你自己的业务逻辑还是显示？

**Comment by sukui123** [comment]
就是如果我有一个后台计算好的一组数据，其中有某个数据是个无限循环小数，如0.3333333333，这个小数在图形上的tooltip显示同样的值为0.33333333333，能否在图形上控制数据的精度显示为0.33，类似给图形配置一个精度的属性，而不是定义个function去实现

**Comment by kener** [comment]
暂无，做到自己的数据层业务逻辑里去吧，别依赖图表层 -_-

**Comment by sukui123** [comment]
明白了，多谢！
也希望能考虑这种需求，同类产品如fusioncharts也有类似功能。有时在数据层处理这种逻辑也很麻烦。

**Comment by kener** [comment]
是的，他们还会在做一些数据类型转换，比如常见的number转成string，string转成time之类。我们经常讨论ec该不该做，但最终还是觉得不该做，我们更应该往小而精（虽然ec已经很大）发展，专注在做好一件事情上面，做得足够好，而不是把相关的周边配套全纳入（比如你说的数据层处理，甚至很多人希望我们提供ajax功能，提供数据表格，提供pdf导出，提供数据统计分析模型等等），这其实都应该抽象成别的模块去完成，比如时间转换就应该用像moment这样优秀的库，数据统计分析可以接R包等等，我们没必要重复造车或者生硬的把其他库引入进来支持。

哪怕我们有了，但很多人是不需要的人，比如我们自己的业务处理就不会出现想你这种情况，我们的后台会把这些处理好，这也是他们的责任，增加这些功能对我们自己的业务就是累赘的代码。

ec2.0以来我们一直在努力的做一件事情，就是细粒度的拆分，满足更个性化的动态组装，也是为了这个目标，我们已经觉得做得太多，对很多并不需要那么多高级功能的人来说太多了，我们需要拆分和做减法，这不是推脱责任，恰好是对你项目的负责，我们不希望你的项目冗余太多你并不需要的代码，也不希望ec包揽太多以致于步履蹒跚。

关于这个的问题随着ec关注度的提高，大家对他的期待也越高，问得也更多了，借这个话题就多说点日后引过来大家看就好。这是我们的考虑和做ec的态度。

谢谢关注。

**Comment by sukui123** [comment]
多谢能耐心回复。
期待echarts能越来越好!

**Comment by plh2** [comment]
## config
```js
option = {
  xAxis: {
    type: 'category',
  },
  yAxis: {
  },
  series: [
    {
      name: 'Email',
      type: 'line',
      data: [0.00000000006]
    },
  ]
};
```

![image](https://user-images.githubusercontent.com/14355994/198206082-94009994-c246-4e58-a5cc-35177b3de25b.png)


数据精度有问题啊...,如何处理?? 这才 11 位小数
