### ISSUE TITLE
Labels Translations

### ISSUE THREAD

**Issue by Igcorreia** [ecomfe/echarts#1171]
I cannot find the way to translate to English the labels of the icons of the graphs.

**Comment by pissang** [comment]
Title of the icons in the toolbox is configurable.
Like 
```
var option = {
    toolbox: {
        show: true,
        feature: {
            mark: {
                title: {
                    mark: 'Mark',
                    markUndo: 'Mark Undo'
                }
            }
        }
    }
}
```
More details can be found the doc. http://echarts.baidu.com/doc/doc-en.html#Toolbox

**Comment by Igcorreia** [comment]
Worked Perfectly :) +1
