### ISSUE TITLE
datazoom 中的数据如何指定于图表中的某条线匹配

### ISSUE THREAD

**Issue by wind-direction** [ecomfe/echarts#1175]
datazoom 在多条线的图表中，默认匹配的是某个线的数据缩放，如何才能指定缩放某条线的数据呢？比如说，点击某条线之后，则显示此线的datazoom。。doc中的xAxisIndex没有示例场景。。。麻烦告知一下，谢谢

**Comment by kener** [comment]
dataZoom不能动态改变控制系列的
