### ISSUE TITLE
柱状图宽度设置问题

### ISSUE THREAD

**Issue by spp1987** [ecomfe/echarts#1177]
hi ,
这个在文档里没有看到关于这个设置，看到柱状图间距、类目间柱形距离 这个设置。 问下有没有柱状图宽度设置。 因为当当个柱状图时，太宽。

**Comment by errorrik** [comment]
可以设置series item的 `barWidth`

http://echarts.baidu.com/doc/doc.html#SeriesCartesian

**Comment by spp1987** [comment]
谢谢。

**Comment by kener** [comment]
相信 barMaxWidth 你会更喜欢

**Comment by spp1987** [comment]
对啊。 这个应该更适合。  应该限制最大宽度是多少。。。不胜感激涕零
