### ISSUE TITLE
getPosByGeo获取平面坐标问题

### ISSUE THREAD

**Issue by xingmolu** [ecomfe/echarts#1178]
请问，如果多series的地图，两个maptype都是'江苏'，请问如何获取这两个地图中南京各自的平面坐标呢？

**Comment by kener** [comment]
你能在一个地图上同时出现两个mapType都江苏的地图？求教怎么做的 -_-||

**Comment by xingmolu** [comment]
恩，确实不行，我把其中一个用经纬度绘制，自定义了maptype解决了，谢谢啊，可以close了
