### ISSUE TITLE
map.js:236   .getGeoJson(this._mapDataCallback(mt, valueData[mt], mapSeries[mt])) 闭包存在有内存泄漏

### ISSUE THREAD

**Issue by linzhenjie** [ecomfe/echarts#1180]
235                   _mapParams[mt.replace(/\|.*/, '')].getGeoJson(
236                        this._mapDataCallback(mt, valueData[mt], mapSeries[mt])
237                    );

250        _mapDataCallback : function (mt, vd, ms) {
                 var self = this;
                return function (md) {
                /******//
                }
项目我是用seajs加载模块的。。加载地图组件失败。。追踪代码发现这里执行不下去了。个人觉得是组件之间互相依赖调用，望大侠帮忙解决

**Comment by kener** [comment]
用script式引入吧，偶们是AMD，seajs是CMD。

你说的内存泄漏是jq会持有这个callback，callback持有这个this，地图dispose了这个this依然存在？
