### ISSUE TITLE
饼状图能直接显示百分比吗？

### ISSUE THREAD

**Issue by lyjamare** [ecomfe/echarts#1182]
我想做的是在
![image](https://cloud.githubusercontent.com/assets/4861591/5818018/93e73874-a0ec-11e4-827d-a0f231fe583e.png)
的Safari旁边直接显示百分比，不想把鼠标放到图块上，才显示。
这个能设置吗？

**Comment by kener** [comment]
http://echarts.baidu.com/doc/example/pie.html
http://echarts.baidu.com/doc/doc.html#ItemStyle

**Comment by lyjamare** [comment]
多谢
