### ISSUE TITLE
不知道有没办法使echarts能在IE8下边，导出base64的图片数据

### ISSUE THREAD

**Issue by shuqiyige** [ecomfe/echarts#1183]
不知道有没办法使echarts能在IE8下边，导出base64的图片数据，因为我们这边想用echarts的图表某一时刻的数据(有IE8的限制)，想把这个数据传送到服务器保存，方便以后读取查看，不知道有这方面的可能吗？

**Comment by kener** [comment]
https://github.com/ecomfe/echarts/search?utf8=%E2%9C%93&q=%E5%AF%BC%E5%87%BA%E5%9B%BE%E7%89%87&type=Issues
