### ISSUE TITLE
有没有不带地图的Echart文件

### ISSUE THREAD

**Issue by biexpert** [ecomfe/echarts#1184]
项目确定不会用地图，发现地图貌似占了大半个文件的大小。所以想知道有没有不带地图的echart脚本啊

**Comment by kener** [comment]
http://echarts.baidu.com/doc/doc.html#引入ECharts2
-_-|||

**Comment by biexpert** [comment]
不好意思应该说的详细点。我注意到文档提到模块话加载是可以单文件加载的，不过我们是个老程序没用过模块加载。我看网上有人提到有个叫echart-origin的文件是不含地图的，单我下载版本里没有找到。

**Comment by kener** [comment]
https://github.com/ecomfe/echarts-optimizer
可以自己按需构建

**Comment by biexpert** [comment]
明白了，谢谢。
