### ISSUE TITLE
echarts在同时注册单击和双击事件后，双击事件很难被触发。不晓得是不是使用方式不对

### ISSUE THREAD

**Issue by shuqiyige** [ecomfe/echarts#1185]
代码如下：
	et.on("click",function(){
			alert("一次");
		});
		et.on("dblclick",function(){
			alert("两次");
		});
没有办法我只有改为以下办法，将单击事件延迟以下，然双击有足够的响应事件：
                var processflag =true;
		et.on("click",function(){
			setTimeout(function(){
				if(processflag){
					alert("一次");
				}
				},300);
		});
		et.on("dblclick",function(){
			processflag =false;
			alert("两次");
			setTimeout(function(){processflag =true;},300);
		});

**Comment by kener** [comment]
版本？
试试线上的 http://echarts.baidu.com/doc/example/event.html

**Comment by shuqiyige** [comment]
我将(http://echarts.baidu.com/doc/example/event.html)代码改成这样，会出现两次("单击一次")+一次("单击两次"),如果是用alert则只响应(单击事件)
myChart.on(ecConfig.EVENT.CLICK, function(){
	console.debug("单击一次");
});
myChart.on(ecConfig.EVENT.DBLCLICK, function(){
	console.debug("单击两次");
});

**Comment by shuqiyige** [comment]
我本地是2.1.8,我看最新版本好像是2.1.10,
