### ISSUE TITLE
虚线的markline的弯曲方向能设置吗？

### ISSUE THREAD

**Issue by solobat** [ecomfe/echarts#1186]
Hi，工作中需要绘制一些能指定弯曲方向的虚线，在文档中没看到有参数可以设置，源码中的smoothSpline.js又看不懂，求教啊

**Comment by solobat** [comment]
看了下源码，在markline.js中修改deltaAngle可以实现。可否新增一个参数用来配置？

**Comment by kener** [comment]
恩，2.2.0已经支持这个参数配置了，本月内发布，谢谢关注。
