### ISSUE TITLE
从2.0.0升级到2.1.10，地图取值范围出现重叠bug

### ISSUE THREAD

**Issue by liminjun** [ecomfe/echarts#1188]
![image](https://cloud.githubusercontent.com/assets/966009/5831068/85dfca24-a165-11e4-9b9f-5d745799c6dd.png)

2.0.0中，如果地图数据只有一条，然后min和max都设置为同一个值，地图的markpoint显示不了。2.1.10上修复了这个bug，但是在取值范围控件上出现数字重叠的bug。option配置如下：

https://github.com/liminjun/myprojects/blob/master/echart_map.html

**Comment by kener** [comment]
如不需要，关闭hoverLink http://echarts.baidu.com/doc/doc.html#DataRange <http://echarts.baidu.com/doc/doc.html#DataRange>
--------------------------------------------------------------
@Kener-林峰 <http://weibo.com/kenerlinfeng> ·  Data Visualization <http://echarts.baidu.com/> ✉
