### ISSUE TITLE
环形饼状图label可以设置默认值吗？

### ISSUE THREAD

**Issue by FionaWong** [ecomfe/echarts#1189]
如题，环形饼状图默认进去中间是空的，想填充文字进去，要怎么实现呢？

**Comment by FionaWong** [comment]
找到了，在normal里面配置label可以实现

**Comment by FionaWong** [comment]
normal  和emphasis里面同事配置label会有冲突。。。。怎么破？

**Comment by kener** [comment]
要什么效果？

**Comment by FionaWong** [comment]
效果：饼图中间显示默认值，鼠标Hover到饼图的每个区域，中间变成显示该区域的内容

**Comment by kener** [comment]
抱歉，这个暂时做不到。

**Comment by sunrw** [comment]
同求饼图中间显示默认值
