### ISSUE TITLE
datazoom 

### ISSUE THREAD

**Issue by IlovedJoey** [ecomfe/echarts#1192]
在_syncFillerShape方法里， 
this._zoom.end = Math.ceil((Math.max(a, b) + this._handleSize - this._location.y) / this._location.height * 100); 
有时会重新赋值为 101

在_getDetail方法里 var end = Math.ceil(this._zoom.end / 100 * length);
                end -= end >= length ? 1 : 0;

处理过后的end值仍有可能等于data.length;
此时data[end].value 就会报“Uncaught TypeError: Cannot read property 'value' of undefined”
![echarts-datazoom-issue](https://cloud.githubusercontent.com/assets/10646771/5850149/ec962482-a22a-11e4-82d4-921645de78a6.png)

**Comment by kener** [comment]
最新源码应该改过了，试试？

**Comment by IlovedJoey** [comment]
OK,TKS
