### ISSUE TITLE
IE7,IE8兼容还是有问题

### ISSUE THREAD

**Issue by CastielCheng** [ecomfe/echarts#1193]
ie8下，图没有画出来，鼠标指过去会有tooltip显示，ie7下完全没有图，连tooltip都没有，
用ie7，ie8反问官网的例子也有这样的问题。。

**Comment by kener** [comment]
-_-||| 用你的ie访问官网例子。

**Comment by CastielCheng** [comment]
也有问题，我的问题跟#475一样，显示空白

**Comment by CastielCheng** [comment]
问题已解决，把透明度和背景颜色改一下就可以了。

**Comment by ttwa** [comment]
试试

**Comment by z543jie** [comment]
@CastielCheng @ttwa 请问下， 修改透明度和背景颜色，具体是怎么做的？
