### ISSUE TITLE
DataZoom不同长度的曲线拖动时会有问题

### ISSUE THREAD

**Issue by evenX86** [ecomfe/echarts#1194]
你好
 我现在图上画了两条曲线，其中一条是满刻度的，另外一条不是满刻度，当我拖动datazoom的控制手柄s时候发现那条不是满刻度的曲线的重点会变化，如图:

![echart 1](https://cloud.githubusercontent.com/assets/8177099/5857555/ae681762-a287-11e4-81cd-2b729c1f4622.png)
现在红线的终点在23:48多一点
![echart 2](https://cloud.githubusercontent.com/assets/8177099/5857557/b4157970-a287-11e4-811e-7cb73c7c66e4.png)
现在红线终点变成了16点51多了
谢谢指导。

**Comment by kener** [comment]
多系列dataZoom必须补齐系列数据长度的，空数据用'-'补

**Comment by evenX86** [comment]
恩恩，填充了就不会出现上述问题了，谢谢kener
