### ISSUE TITLE
EChart 线图手机端 电脑端显示区别问题

### ISSUE THREAD

**Issue by Garrylin** [ecomfe/echarts#1195]
为何我在浏览器（使用Chrome）测试时，比如说我用线图，总共有3条线，都穿有参数，在浏览器上显示良好，但是，问题来了，当我把echart放到android项目里用webview显示出来时，每条线都有一条水平线（从那条线的起点水平延伸至终点的水平位置），这是为何！！！！！我看图表选项也好，各种选项也好都找不到问题，是手机浏览器和Chrome 不同吗？

**Comment by Garrylin** [comment]
已解决，抱歉，数据没补全原因

**Comment by kener** [comment]
？

**Comment by Garrylin** [comment]
问题补充：亲测华为畅玩3x 显示有问题，就是问题描述的每条线都有两条问题，其他机型目前测试小米，谷歌手机均和网页显示一般无异，求解答

**Comment by Garrylin** [comment]
![1](https://cloud.githubusercontent.com/assets/7848678/5870127/03297ff6-a301-11e4-860e-8bd27c198d89.jpg)

**Comment by Garrylin** [comment]
如图所示，测试机型中，华为畅玩3x出现上图问题，xiatu下图为其他机型正确显示形式
![2](https://cloud.githubusercontent.com/assets/7848678/5870159/205a35f6-a302-11e4-8cd0-6c1e8656e323.jpg)

**Comment by Garrylin** [comment]
再补充，4.2的模拟器，畅玩3x也是4.2的，小米4.4，就4.2android系统下显示有问题

**Comment by kener** [comment]
动画跟不上，暂时先关闭动画试试。animation:false

**Comment by Garrylin** [comment]
问题解决Thanks！，但kener，动画跟不上是4.2系统缺陷么   请教

**Comment by kener** [comment]
恩，目前看来是，这个月发布一个新版本，也会有一个mobile beta版出来，我们尽量降低对内存和计算的要求，到时你试试。
谢谢反馈~

**Comment by Garrylin** [comment]
(*^__^*)   支持你

**Comment by kerwin0104** [comment]
我也是遇到类似问题。
android的系统的原生浏览器经常会出现这种重叠。不只是动画，setOption改变line的数据有时候会出现两条line，设置了tooltip之后，axisPointer的线偶尔也会出现两条。

**Comment by Garrylin** [comment]
对，我也遇到了这种重叠问题，字体会变形，图形图表也会变形（手指触碰显示数据条时），这些都是在4.2android系统手机上发生的，再次测试，4.2就是一直会有问题，快崩溃了，4.4的完全没问题。。。。还没试试4.1手机

**Comment by Garrylin** [comment]
问题如图，重叠问题，没点击，图表如图
![5](https://cloud.githubusercontent.com/assets/7848678/5933477/1ae384c6-a6fc-11e4-9259-4701abf4858c.png)

点击如图柱状图后，图标变成这样。。。
![6](https://cloud.githubusercontent.com/assets/7848678/5933481/2cb821b6-a6fc-11e4-8bb3-6bf04712bf8e.png)
这根本不能用嘛。。。我去kener求解决方案

**Comment by Garrylin** [comment]
不仅是柱状图，饼图，仪表，地图，全都会字体重叠图表重叠

**Comment by missmisslonely** [comment]
mx3   4.2的手机动画关了依旧没有解决
