### ISSUE TITLE
[如图] ‘甲、乙、丙’ 在 ‘一月、二月、三月’ 各有 ‘1、2、3’，不知道柱状图怎么处理？

### ISSUE THREAD

**Issue by xianghongai** [ecomfe/echarts#1198]
![1](https://cloud.githubusercontent.com/assets/2075006/5871757/086263ea-a31d-11e4-9460-854b6627e039.png)

‘甲、乙、丙’  在  ‘一月、二月、三月’  比较，
‘甲、乙、丙’ 比较项由 ‘1、2、3’ 部分组成，并作为 图例开关 。

**Comment by Garrylin** [comment]
堆积柱状图http://echarts.baidu.com/doc/example/bar2.html

**Comment by xianghongai** [comment]
THX，是这样的。
