### ISSUE TITLE
我想展示某一段时间内，和某一个关键词相关的其他关键词在百度这个平台上搜索量，应该如何展现呢？

### ISSUE THREAD

**Issue by joostshao** [ecomfe/echarts#1199]
我想过这里面有好几个问题：
1： 关键词有可能不能分类，虽然都是类似的，聚合在比如 游戏上，但是业务上其实根本没有把这些关键词分组分类，所以无法做二级展示。
2： 关键词很多很多，而且会一直扩充，所以普通的气泡图也不行。
3： 有些类型的关键词有可能搜索量很大，有些可能很小，所以展示起来很不合比例。

所以我想请教一下百度的大神们。
比如我的百度搜索指数，在2014年的搜索数据展示。

**Comment by kener** [comment]
想明白你希望表达的是什么就知道该用什么形式了。
“【某段时间】【相关关键词】的【搜索量】”，谁是主要维度？想表达相关性还是对比？
可有的方式有很多，每一种方式可能侧重的表现点是不一样的，取决于的表达诉求。
时间是个很特别的因素，可以作为数据维度去做图形映射，也可以作为变量参数作为其他维度的控制因素（如timeAxis，dataZoom，timeLine就是对时间维度不同的处理）
相关性的描述倾向于力导、和弦、散点、气泡。
对比性的描述倾向于柱形、折线、气泡、散点。
