### ISSUE TITLE
echarts BUG 返回NaN

### ISSUE THREAD

**Issue by dolphineor** [ecomfe/echarts#1200]
![image](https://cloud.githubusercontent.com/assets/9883493/5872959/21f7d844-a32c-11e4-8601-d60859d6d7d5.png)

![image](https://cloud.githubusercontent.com/assets/9883493/5872972/58418260-a32c-11e4-8297-284c9f932448.png)
调用map时 给map设置series出现错误
1.当series为空时 不会有以上错误
2.当series设置为{name:'四川',value:100}  出现以上错误
3.引用的是echarts/2.1.10/echarts-all.js

出错源代码

var a = 1;
    var legenddata;
    pieChart = function (showData, showName, showId) {
        var dataString;
        if(a==1) {
            legenddata = eval("({ " + showName[1] + " : false," + showName[2] + " : false," + showName[3] + " : false})");
        }
        $(showId).show();
        $("#container").hide();
        var myCharts = echarts.init(document.getElementById(showId));
        var optionBin = {
            tooltip : {
                trigger: 'item',
                formatter: '{b} {a}<br/>占全国百分比：{c}%'
            },
            legend: {
                orient: 'vertical',
                x:'left',
                selected: legenddata,
                data:[showName[0],showName[1],showName[2],showName[3]]
            },
            dataRange: {
                min: 0,
                max: 100,
                x: 'left',
                y: 'bottom',
                text:['高','低'],           // 文本，默认为数值文本
                calculable : true
            },
            toolbox: {
                show: true,
                orient : 'vertical',
                x: 'right',
                y: 'center',
                feature : {
                    restore : {show: true},
                    saveAsImage : {show: true}
                }
            },
            series : [
                {
                    name: '中国',
                    type: 'map',
                    mapType: 'china',
                    roam: false,
                    itemStyle:{
                        normal:{label:{show:true}},
                        emphasis:{label:{show:true}}
                    },
                    data:showData[0]
                },{
                    name: showName[1],
                    type: 'map',
                    mapType: 'china',
                    itemStyle:{
                        normal:{label:{show:true}},
                        emphasis:{label:{show:true}}
                    },
                    data:showData[1]
                },{
                    name: showName[2],
                    type: 'map',
                    mapType: 'china',
                    itemStyle:{
                        normal:{label:{show:true}},
                        emphasis:{label:{show:true}}
                    },
                    data:showData[2]
                },{
                    name: showName[3],
                    type: 'map',
                    mapType: 'china',
                    itemStyle:{
                        normal:{label:{show:true}},
                        emphasis:{label:{show:true}}
                    },
                    data:showData[3]
                }
            ]
        };
        a++;
        myCharts.setOption(optionBin);
        // 动态添加默认不显示的数据

        myCharts.on(echarts.config.EVENT.LEGEND_SELECTED, function (param){
            var clickName = param.target;
            if (clickName == showName[0]) {
                legenddata = eval("({ "+showName[1]+" : false,"+showName[2]+" : false,"+showName[3]+" : false})");
                pieChart(showData,showName,showId);
            }
            if (clickName == showName[1]) {
                legenddata = eval("({ "+showName[0]+" : false,"+showName[2]+" : false,"+showName[3]+" : false})");
                pieChart(showData,showName,showId);
            }
            if (clickName == showName[2]) {
                legenddata = eval("({ "+showName[0]+" : false,"+showName[1]+" : false,"+showName[3]+" : false})");
                pieChart(showData,showName,showId);
            }
            if (clickName == showName[3]) {
                legenddata = eval("({ "+showName[0]+" : false,"+showName[1]+" : false,"+showName[2]+" : false})");
                pieChart(showData,showName,showId);
            }
        });
    }

**Comment by kener** [comment]
1月23？我们没发布过版本啊，你用源码自己构建的？
如果问题还存在，请给一个可以在example里指教执行的option，谢谢

**Comment by dolphineor** [comment]
我使用的是echarts-2.1.10版本出现的这个问题

**Comment by dolphineor** [comment]
我已经用别的方式绕过了这个问题实现了功能， 还是感谢了
