### ISSUE TITLE
柱状图单击事件获取的参数有时候正确，有时错误。这是为何？

### ISSUE THREAD

**Issue by 336Project** [ecomfe/echarts#1201]
![image](https://cloud.githubusercontent.com/assets/8856601/5886401/9917a03e-a3d7-11e4-8c52-df7e3ec19971.png)

![image](https://cloud.githubusercontent.com/assets/8856601/5886408/bc993568-a3d7-11e4-8a86-729ba7d0217f.png)
如图所示，多次点击3、4  忽然就冒出一次点击获取的数据不是当前点击的项，而是第一个项。点击其他的柱行结果同上

**Comment by kener** [comment]
地图？给个可复现的option吧，这帮不了你

**Comment by 336Project** [comment]
为了测试，已取消地图符合，当前仅单纯的柱状图
![image](https://cloud.githubusercontent.com/assets/8856601/5886427/23f11f7c-a3d9-11e4-8f24-03cc53de6fd2.png)

**Comment by kener** [comment]
example可用的option，代码... -_-||
