### ISSUE TITLE
关于chord图的问题

### ISSUE THREAD

**Issue by lyjamare** [ecomfe/echarts#1202]
我想问一下，
我想做的是鼠标点击红色，例如拜仁慕尼黑，能直接跳转到一个网址或网站
![qq 20150125141034](https://cloud.githubusercontent.com/assets/4861591/5890564/110b5e18-a49c-11e4-9255-4cfbd61aad8d.png)

**Comment by kener** [comment]
http://echarts.baidu.com/doc/example/event.html
