### ISSUE TITLE
力导向图中link的线条颜色设置与文档不符，版本：2.1.10

### ISSUE THREAD

**Issue by winneryong** [ecomfe/echarts#1204]
文档中描述为：
 itemStyle:{
   normal:{
     linkStyle:{
      borderColor:'#FF0000'
    }
  }
}

设置无效，设置为下面的option才生效：
itemStyle:{
   normal:{
      strokeColor:'#FF0000'
  }
}

**Comment by winneryong** [comment]
最新版本也有同样的问题，最新的版本中文档已经变成了 linkStyle:{
color:'#FF0000'
}

**Comment by pissang** [comment]
linkStyle 只有在serie的 itemStyle 中才会用到，每个link的itemStyle是没有linkStyle的，节点也是一样，这个最近在文档上做了说明但是还没更新到线上

**Comment by winneryong** [comment]
好的，谢谢！
