### ISSUE TITLE
series.data的点改了itemStyle 无法生效

### ISSUE THREAD

**Issue by humanhuang** [ecomfe/echarts#1205]
series.data
      
      
      [
      12, 34,
      {
            value: 56,
            itemStyle: {
                  normal: {
                        lineStyle: {
                              color: 'red'
                        },
                        areaStyle: {
                              color: 'red'
                        },
                        textStyle: {
                              color: 'red'
                        },
                        color: 'red'
                  },
            }
      },
      10, 23
      ]

颜色并没有变为红色

**Comment by kener** [comment]
全option，什么图表类型？

**Comment by huangjunhua** [comment]
"{
	"title": {},
	"grid": {
		"x": 0,
		"y": 0,
		"x2": 0,
		"y2": 0,
		"backgroundColor": "white",
		"borderWidth": 0
	},
	"tooltip": {
		"trigger": "axis"
	},
	"yAxis": {
		"show": false,
		"max": 0
	},
	"xAxis": [
		{
			"show": false,
			"boundaryGap": false,
			"data": [
				"周一",
				"周二",
				"周三",
				"周四",
				"周五",
				"周六",
				"周日"
			]
		}
	],
	"series": [
		{
			"symbolSize": 0,
			"name": "行业排行",
			"type": "line",
			"smooth": true,
			"itemStyle": {
				"normal": {
					"lineStyle": {
						"color": "#85E3E3"
					}
				}
			},
			"data":
[
  12, 34,
  {
        value: 56,
        itemStyle: {
              normal: {
                    lineStyle: {
                          color: 'red'
                    },
                    areaStyle: {
                          color: 'red'
                    },
                    textStyle: {
                          color: 'red'
                    },
                    color: 'red'
              },
        }
  },
  10, 23
  ]
		}
	]
}"

**Comment by kener** [comment]
折线图没有这个控制，连续折线是一整条的，不支持分段设置。
如需要，用markLine，axis的splitArea强调或者换成柱形图。
