### ISSUE TITLE
关于堆积图的问题

### ISSUE THREAD

**Issue by 853495865** [ecomfe/echarts#1206]
1.可不可以设置line的hover事件，当hover在line的时候，改变areaStyle？
2.http://echarts.baidu.com/doc/example/line4.html 这个连接是从 堆积面积图中点进去的，当切换折线图的时候没有反映，然后点柱形图切换，切换到柱形图后，再点堆积图切换，又没反应了。。。点平铺，再点堆积，又切换成了刚才的柱形图了。。。这个切换总觉得有点问题。。我想问的是 这个点进去呈现的图到底是什么图？
3.我把图表呈现出来以后，需要点击一下切换到堆积图的按钮，才是我想要的图表，于是我想获取 切换到堆积图的按钮的元素，然后 $("..").click() ，但是这个元素获取不到，我就想当绘制好图表以后，给他一个方法，切换到堆积图。但是在Echarts文档中找不到相应的方法。

**Comment by kener** [comment]
1、不支持，只支持symbol高亮
2、就是你点的选项开启
3、option就设置成你需要的样式

**Comment by 853495865** [comment]
第三个问题：这个我知道呀。。。我按照Echarts实例绘制的堆积图图表，绘制完毕后 ，不是我想要的图表（不知道是什么原因），但是当我点了magicType里面的切换到堆积图按钮，呈现出来的就是我想要的图表了


 option = {
        toolbox: {
            show: true,
            feature: {
                magicType: { show: true, type: ['stack'] },
                restore: { show: true },
                saveAsImage: { show: true }
            }
        },
        calculable: true,
        xAxis: [
            {
                type: 'category',
                boundaryGap: false,
                data: x
            }
        ],
        yAxis: [
            {
                type: 'value'
            }
        ],
        tooltip: {
            formatter: function (e) {
             
            }
        },
        series: array
    };
    myChart.clear();
    myChart.setOption(option);

其中array是这样的形式的数组：
 array.unshift({
                name: "XXXXXX", type: 'line', data: XXXXXXXX, symbol: 'none', itemStyle: {
                    normal: {
                        areaStyle: {
                            type: 'default', color: (function () {
                                var zrColor = zrender.tool.color;
                                return zrColor.getLinearGradient(
                                    0, 100, 0, 400,
                                     [[0, 'rgba(66,139,202,0.8)'], [0.8, 'rgba(66,139,202,0.1)']]
                                )
                            })()
                        }, lineStyle: { width: 1, color: '#fff' }
                    }
                }
            })

**Comment by 853495865** [comment]
所以我就想 当myChart.setOption(option)以后，执行一下 切换到 堆积图 的方法。。。。

**Comment by kener** [comment]
如何堆积，见文档

**Comment by 853495865** [comment]
那个文档，我真心读了N遍了，，，就是不知道问题出在哪里。。。我也写了不少图表了，都很顺利，分分钟搞定，就是这个堆积图搞了三天，还是没有结果。。。

**Comment by kener** [comment]
不就是一个stack参数吗？

**Comment by 853495865** [comment]
太谢谢了，原因问题就出在这里。
