### ISSUE TITLE
以后会不会出svg版的

### ISSUE THREAD

**Issue by czbaa** [ecomfe/echarts#1207]
是不是svg的图形的多端适配要比canvas要容易, 还在看文档, 不过觉得canvas的绘图方式适配起来会麻烦一些吧,.....\n
...
以后会不会出svg版的?

**Comment by kener** [comment]
暂无计划，canvas的路相对比较崎岖，确实要做更多的事情，但前途是光明的，canvas会有更多的可能。而且这都是对实现的要求，不需要深度定制或二次开发应该不会对使用方带来什么麻烦。

**Comment by xvacant** [comment]
会不会出WebGL版的?
WebGL是不是性能会更好?

**Comment by pissang** [comment]
会

**Comment by waylau** [comment]
顶！，我一直以为  echarts 是 svg 做的
