### ISSUE TITLE
Echarts与jquery无法兼容么，还是有先后顺序

### ISSUE THREAD

**Issue by shangyue1110** [ecomfe/echarts#1208]
开发一页式应用，上下文环境中有设定全局的jquery，然后再使用Echarts的实例化时~一直提示echarts的变量为undefined~但是看官网demo时~~发现 echarts的实例化之后，再引入的jquery~ 难道真的有这么强的限制么？

**Comment by shangyue1110** [comment]
最后发现~造成原因在这里~ https://github.com/ecomfe/echarts/issues/657

**Comment by kener** [comment]
多玩玩就明白了。
