### ISSUE TITLE
折线图 分割 问题

### ISSUE THREAD

**Issue by hsh075623201** [ecomfe/echarts#1210]
数据格式如下：
x=['2013-1','2013-2','2013-3',...'2013-12','2014-1','2014-2',...'2014-3']
y=[10,20........15]
现可以画出一条折线图。

但如何在x='2013-12'上 加一条 分割线，将这个折线图进行分割：并且如何将分割线的右侧，即2014年的数据 的折线图变成一条虚线？？？

问题关键点：
markLine：如何定位的画一条线？；
如何只在折线的部分区段进行虚线处理？？

**Comment by kener** [comment]
1、markLine.data，见文档
2、两段数据分成两个系列，空数据补全

**Comment by hsh075623201** [comment]
![image](https://cloud.githubusercontent.com/assets/7548881/5915522/c7eca6d6-a641-11e4-9159-feca90bc8d51.png)

 markLine : {
                        data:[
                                        [
                                                {value : null, xAxis: xaix[60], yAxis: 0 },
                                                 {value : null, xAxis: xaix[60], yAxis: 'm' }//这个M如何确定呢？ 如图所示：箭头超出区域
                                        ]
                                ]
}

**Comment by kener** [comment]
Number.MAX_VALUE

**Comment by hsh075623201** [comment]
OK，十分感谢！！
