### ISSUE TITLE
关于散点图的颜色和区域缩放

### ISSUE THREAD

**Issue by romanticaa** [ecomfe/echarts#1211]
请问下：散点图的默认颜色是很漂亮的透明的，但是如果给series里加itemStyle改颜色，就变成不透明的颜色了，应该如何自定义透明的颜色呢？

另外，发现散点图series的data数组内值为对象时，比如 data: [{value:[161.2, 51.6]},{value: [167.5, 59.0]} ],区域缩放就无效了，这个是设定如此吗？

**Comment by kener** [comment]
1、rgba。
2、已经修复，本周发布新版本。
