### ISSUE TITLE
雷达图opt.polar[0].indicator[0].max属性，有时会自动缩放不按照max属性显示。

### ISSUE THREAD

**Issue by aDaiCode** [ecomfe/echarts#1212]
类似如下设置，雷达图中的数据点并不会显示在雷达图的最外端的多边形上。
是bug还是我使用有误？！
请注意，把max设置为20，如果设置为５或者其他个别数字，则又显示正常。
option = {
　backgroundColor:'#000',
　polar : [
　　{
　　　indicator : [
　　　　{ text: '1', max: 20},
　　　　{ text: '2', max: 20},
　　　　{ text: '3', max: 20},
　　　　{ text: '4', max: 20},
　　　　{ text: '5', max: 20},
　　　　{ text: '6', max: 20}
　　　]
　　}
　],
　series : [
　　{
　　　type: 'radar',
　　　data : [
　　　{
　　　　value : [20,20, 20, 20, 20, 20],
　　　}
　　　]
　　}
　]
};

**Comment by kener** [comment]
@wind108369

**Comment by wind108369** [comment]
@i6ma

**Comment by i6ma** [comment]
另见：#1222
简述一下分段计算函数，以供参考，期待围观pr：
function smartSteps(min, max, section, opts) {}

前三个参数简单，最小值、最大值、指定分段数（缺省时自动选取段数）
但问题是：输入的 min, max 并不一定等于函数的输出值，计算过程中会多次调节它们的值，以期输出一份比较人性化的结果（个人觉得大多数需求如此）。

所以有第四个参数：opts.min, opts.max
限定 min, max 不要被修改（及其它一些自定义项），要求输出值忠实于指定值
但问题是：仍然会对限定值作小幅度的调节，如 5.6789 -> 5.69

还有：没有考虑特定需求下的计算问题
求pr

**Comment by aDaiCode** [comment]
感谢各位关注。

请问该问题大概什么时间可以修复呢？
有木有暂时的替代解决方案？

我们的需求 不需要展示tooltip，无奈我把polar[0].indicator[i].max=100，然后把所有值都对应100做了同比例放大。

**Comment by wind108369** [comment]
更新最新的代码就可以解决了

**Comment by aDaiCode** [comment]
= =！ OK 抱歉。。忘了强刷了。。
