### ISSUE TITLE
坐标轴的文本标签，是否可以设置在坐标轴的内侧？同时文本显示在图形之上。

### ISSUE THREAD

**Issue by aDaiCode** [ecomfe/echarts#1213]
例如，居左的左边轴，文本标签在坐标轴的右侧。
同时，文本标签在图形(如堆积折线或柱状图)之上，文本不会被图形遮挡到。

**Comment by kener** [comment]
设axisLabel的textStyle align为left，设置一个负margin
    axisLabel: {           // 坐标轴文本标签，详见axis.axisLabel
            show: true,
            margin: -1,
            // clickable: false,
            // formatter: null,
            textStyle: {       // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                align: 'left',
                baseline: 'bottom',
                color: '#333'
            }
        },

**Comment by aDaiCode** [comment]
OK 感谢回答。
目前还有一个问题是：markLine会遮挡到坐标轴标签。如下：
麻烦，感谢！
option = {
　 xAxis: [
　　{
　　　type: 'category',
　　　boundaryGap: false,
　　　data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
　　}
　],
　 yAxis: [
　　{
　　　 type: 'value',
　　　zlevel: 1,
　　　z: 1,
　　　axisLabel: {
　　　　 textStyle: {
　　　　align: 'left',
　　　　fontSize: 20
　　　　},
　　　margin: -1
　　　}
　　}
　],
　series: [
　　{
　　　 type: 'line',
　　　 zlevel: 0,
　　　z: 0,
　　　data: [1, 2, 5, 3, 2, 0],
　　　markLine: {
　　　　itemStyle: {
　　　　　 normal: {
　　　　　　lineStyle: {
　　　　　　　type: 'solid',
　　　　　　　width: 10
　　　　　　}
　　　　　}
　　　　},
　　　　data: [
                    [{value: 100,xAxis: 0,yAxis: 2},
                    {value: 100,xAxis: 3,yAxis: 2}
                    ]
                ]
            }
        }
    ]
}

**Comment by kener** [comment]
init echarts时传入主题吧yAxis的z设高
init(dom, {valueAxis:{z:5}})

**Comment by aDaiCode** [comment]
您好，
我试了  
self.chart = echarts.init($chart[0],{yAxis:{z:5}});
和 
init(dom, {valueAxis:{z:5}})
依然markline会挡道坐标轴lable，但后改了需求，没有过多测验，
感谢您的解答。

**Comment by caojwaqzh** [comment]
你好 如果左边的x轴文字在轴的右侧 同时 最后一个标签要保证在轴的左侧怎么实现？
