### ISSUE TITLE
不知道算不算显示的小bug~x轴刻度显示与数据曲线上对应点的位置错位

### ISSUE THREAD

**Issue by shangyue1110** [ecomfe/echarts#1215]
在官方demo里的[折线散点混搭](http://echarts.baidu.com/doc/example/mix4.html)中尝试将以下片段中的`boundaryGap `属性设置为true：
```javascript
 xAxis : [
        {
            type : 'category',
            boundaryGap : true,
            data : function (){
                var list = [];
                for (var i = 1; i <= 30; i++) {
                    list.push('2013-03-' + i);
                }
                return list;
            }()
        },
        {
            type : 'value',
            scale : true,
            splitNumber: 31,
            axisLabel: {show:true},
            splitLine: {show:false}
        }]
```
刷新后，效果如下图
![qq 20150127171423](https://cloud.githubusercontent.com/assets/8033150/5916085/07b96d66-a648-11e4-9b02-0e34a8a6ca32.png)
会发现line类型图表前确实加入了gap，但是下方的横轴坐标刻度线却未与之同步，对比前后显示效果，可以发现横轴标签是有偏移，但是却与错位的刻度放在一起，会让人理解错误

**Comment by kener** [comment]
不用那么长的数据你就明白label对齐在什么地方了，而且默认类目和数值的axisTick策略也不一样。

**Comment by shangyue1110** [comment]
哈哈~~其实就只是纠结坐标轴上的刻度~~没有细心的阅读api文档~~~诶~~谢谢解答！
ps：doc中搜索axis.axisTick就有对应的设置
