### ISSUE TITLE
IE7下地图有问题

### ISSUE THREAD

**Issue by CastielCheng** [ecomfe/echarts#1216]
![222](https://cloud.githubusercontent.com/assets/10651287/5930867/88457dca-a6d0-11e4-85a4-6b3c3ca47db3.png)

ie7下地图城市名不显示。再刷新一下页面又可以了，这是哪里不对啊？？
怎么修改地图城市名的样式啊，lineStyle，areaStyle都不行。
渲染后再修改样式也不行。。

**Comment by kener** [comment]
http://echarts.baidu.com/doc/example/map.html

**Comment by CastielCheng** [comment]
连接打开如下图
![qq 20150131134121](https://cloud.githubusercontent.com/assets/10651287/5986983/049343d2-a94f-11e4-8069-9a64f09ee639.jpg)
