### ISSUE TITLE
有滚动条的情况下设置addMarkPoint多次会死Point问题。

### ISSUE THREAD

**Issue by longFeiLi** [ecomfe/echarts#1219]
var option = {
			tooltip: {
				trigger: 'axis',
				formatter: '{b}<p>成功率:<br/>&nbsp;&nbsp;{c0}%'
			},
			grid: {
				y: 60,
				y2: 30,
				x2: 40,
				x: 50
			},
			//横轴默认为类目型'category'，纵轴默认为数值型'value'
			xAxis: [ //x 数据
				{
					type: 'category',
					boundaryGap: true,
					data:['05:00','06:00','07:00','08:00','09:00']
				}
			],
				dataZoom: {
						show: true,
						realtime: false,
						start: 40,
						end: 60
					},
			yAxis: [ //y 数据
				{
					min: 0,
					max: 150,
					axisLabel: {
						formatter: '{value}%'
					},
					type: 'value'
					
				}
			],
			//line'（折线图） | 'bar'（柱状图） | 'scatter'（散点图） | 'k'（K线图）'pie'（饼图） | 'radar'（雷达图） | 'chord'（和弦图） | 'force'（力导向布局图） | 'map'（地图）
			//数据
			series: [{
				name: '成功率', //这里的名称要和图例的名称一样
				type: 'bar',
				data: [95,94,93,95,94,93],
				markPoint: {
					//先定义样式，再填充数据
					data: [{
								type: 'max',
								name: '最大值',
								symbolSize: 6,
								unit: '%', //提示单位
								itemStyle: {
									normal: {
										color: '#0b5914',
										label: {
											position: 'bottom',
											textStyle: {
												fontSize:12
											}
										}
									}
								}
							}, {
								type: 'min',
								name: '最小值',
								symbolSize: 6,
								unit: '%', //提示单位
								itemStyle: {
									normal: {
										color: '#e61f1a',
										label: {
											position: 'top',
											textStyle: {
												fontSize:12
											}
										}
									}
								}
						}]
				},
				markLine: {
								data: [{
									type: 'average',
									name: '平均值',
									
									itemStyle: {
										normal: {
											borderWidth: 1,
											lineStyle: {
												//线条类型，默认虚线
												//线条颜色
												color: 'blue',
												//光影
												shadowBlur: 15
											}
										}
									}
								}]
							}
			}]
		};

var timeTickets = setInterval(function() {
 tmp=Math.round(Math.random() * 50)
    // 动态数据接口 addData
 
    myChart.addData([ [ 0, // 系列索引
         tmp,// 新增数据
        false, // 新增数据是否从队列头部插入
        false
        ]
      ]
   );
 
},10000);

上面有Option  和addData代码片段
问题演示：
首先页面运行出来，10000毫秒推送一个数据,然后打开控制台，在控制台中加入代码：
  var point=new Array();
							                 var d={};
							                 d.name='07';
							                 d.value='2';
							                 d.xAxis='08:00';
							                 d.yAxis=500;
							                  d.symbol='arrow';
							                  d.symbolSize=6;
							                  d.itemStyle={
										      	      normal:{
											              color:'red',
											              label:{
											              	    position:'top',
											              	    formatter: '3322'
											              	   }
										              } 
										             }
							                 point.push(d);
							                  var ccc={}; 
							                  ccc.data=point;
myChart.addMarkPoint(0,ccc);

里面的xAxis的值改变一下。执行2次，然后拖动滚动条，就会发现页面上多了一个点。同理 添加线也会多一条死线了

**Comment by longFeiLi** [comment]
addShapeList  方法
   for (var i = 0, l = lastShapeList.length; i < l; i++) {
                	  
                    key = this._getAnimationKey(lastShapeList[i]);
                    console.info(key);
                 

                    if (key.match('undefined')) {
                        this.zr.delShape(lastShapeList[i].id);
                    } else {
                        key += lastShapeList[i].type;
                        if(oldMap.hasOwnProperty(key)){
                        	console.info(233333333);
                         this.zr.delShape(lastShapeList[i].id);
                        }else{
                         oldMap[key] = lastShapeList[i];
                        }
                    }
                }     源码 里面加了个判断     if(oldMap.hasOwnProperty(key))

**Comment by kener** [comment]
thx
