### ISSUE TITLE
legend很多，能否实现全选和反选

### ISSUE THREAD

**Issue by baobinluo** [ecomfe/echarts#1220]
就是比如legend有30个，默认进去selected 3个，然后一个个去点全部选完太麻烦了，该如何做到全选legend来看出最大值呢

**Comment by kener** [comment]
目前只有单选和复选。可以自定义两个作为全选反选系列，响应legend事件，调用legend接口或者重新setOption做你需要做的事情

**Comment by baobinluo** [comment]
我做的图类似于：http://echarts.baidu.com/doc/example/bar11.html，要加在哪里？我现在是在画布外面加个全选button，点击后dispose图表，再重绘完成的，这样子要冲刷整个图表，会很明显画面闪烁，求百度大神讲清楚一点，麻烦了

**Comment by kener** [comment]
更新数据的刷新使用setOption会有过渡动画就会和谐点了。
了解一点就够了，在ec里，不管什么交互，其实都是改变数据后setOption或refresh，你的需要就说seleted的on/off问题，管理和维护你自己的selectedMap就好。
