### ISSUE TITLE
Documentation - missing example of true line chart type: "time" as xAxis

### ISSUE THREAD

**Issue by cpou** [ecomfe/echarts#1221]
Please can you provide an explanation on how to have a simple line chart with an xAxis of type: "time".

I suppose once you set your xAxis on "time" , you need to manipulate the serie structure.
I've tried for 2 hours, looking into the doc, hacking examples, doing my own, but did not succeed.

Thx for the hardwork by the way

**Comment by kener** [comment]
Sorry for hear that.
https://github.com/ecomfe/echarts/blob/master/doc/example/line8.html

**Comment by cpou** [comment]
Xie Xie :)
