### ISSUE TITLE
关于echarts雷达图相关开发的几个问题

### ISSUE THREAD

**Issue by bupo** [ecomfe/echarts#1222]
我有以下几个问题需要请教一下，希望给予解答。
       
  如图:
![qq 20150129105003](https://cloud.githubusercontent.com/assets/9344925/5951626/b9f43d96-a7a4-11e4-82ef-a16fdee6468c.png)

       一、当我的min与max是4、5时，为什么没有出小数等分；
       二、我修改了文字颜色为红色，但是没有效果；
       三、外围的name我修改了margin值也没有效果；

**Comment by kener** [comment]
1、2 @wind108369 
3、margin是number类型 180

**Comment by wind108369** [comment]
1、smartSteps 计算逻辑的问题，#1212应该也是这个造成的
2、我已修改

**Comment by kener** [comment]
1、 @i6ma

**Comment by wind108369** [comment]
1、已解决
