### ISSUE TITLE
ECharts 能提供国际化的功能吗 

### ISSUE THREAD

**Issue by xieqingxiao** [ecomfe/echarts#1224]
在toolbox 中把鼠标放在保存为图片的按钮上 ，会有中文提示“保存为图片” ，ECharts 有接口切换语言吗，能显示英文 或其他语言

**Comment by kener** [comment]
同 #1171

**Comment by xieqingxiao** [comment]
你的答复完美的解决了我的问题

**Comment by xyzshen** [comment]
> 在toolbox 中把鼠标放在保存为图片的按钮上 ，会有中文提示“保存为图片” ，ECharts 有接口切换语言吗，能显示英文 或其他语言

我也需要，请问 你知道怎么设置的吗？
