### ISSUE TITLE
关于无data时的事件触发的一个小问题

### ISSUE THREAD

**Issue by romanticaa** [ecomfe/echarts#1227]
写了一个点击事件，就是点一项就把哪一项消失掉
option.series[param.seriesIndex].data.splice(param.dataIndex, 1);

后来在全消完进入无数据提示界面里，不管点哪都会再相应这个事件，而且方法参数传的是最后那一个参，应该是哪边没清理掉吧？

**Comment by kener** [comment]
给个复现demo？
