### ISSUE TITLE
需要给 v2.2.0 版本加个 relese tag

### ISSUE THREAD

**Issue by muzuiget** [ecomfe/echarts#1229]
就是这里 https://github.com/ecomfe/echarts/releases 还没有 2.2.0 版本，不能通过 bower 升级和安装。

**Comment by kener** [comment]
是的，还没打，一般放出来几天就会有反馈是否出现重大问题，这个版本升级较多所有看看反馈而已。
目前看来正常，tag 已经打了，谢谢关注。
