### ISSUE TITLE
markline给定value，并动态改变如何设置？

### ISSUE THREAD

**Issue by baobinluo** [ecomfe/echarts#1230]
如图：http://echarts.baidu.com/doc/example/bar11.html ，在 'name':'金融','yAxisIndex':1,'type':'bar',下面添加：markLine : {
          		 data:[
                                    [{name: '标线1起点', value: 100, x:150, y: 120}, 
                                      {name: '标线1终点', x: 850, y: 120}
                                    ]  
                                  ]
               },
确实会有一条线，但是他的位置是设置死的，能否设置变成和GDP的标线一样（注意：要添加的标线不是min,max,avg，是自定义的一个值），线的位置和y轴的刻度对应

**Comment by kener** [comment]
见markLine data文档
