### ISSUE TITLE
给Map加上timeLine后自动播放地图数据不刷新

### ISSUE THREAD

**Issue by LiuQ1ang** [ecomfe/echarts#1232]
如题，在Map里加上timeLine后，我的series有的省份是缺失数据的，本来缺失应该是灰色，但是这些缺失的省份在timeline播放的情况下，会展示之前的数据，只是部分，是否每次都做了刷新？

**Comment by kener** [comment]
notMerge 见文档

**Comment by LiuQ1ang** [comment]
这是代码，可是我只有一个option啊，麻烦运行看一下，本来最后一个数据全部是0的，但是还显示了数据，非常不解。
function es_ssl(){
	//all  
	var ssl_0 = [{"name":"北京","value":10.97},{"name":"江西","value":10.84},{"name":"河南","value":7.05},{"name":"云南","value":6.82},{"name":"海南","value":6.54},{"name":"新疆","value":6.31},{"name":"宁夏","value":5.32},{"name":"辽宁","value":4.98},{"name":"甘肃","value":4.89},{"name":"青海","value":4.81},{"name":"河北","value":4.45},{"name":"山西","value":4.39},{"name":"安徽","value":4.22},{"name":"天津","value":4.16},{"name":"山东","value":3.99},{"name":"浙江","value":3.66},{"name":"贵州","value":3.49},{"name":"湖南","value":3.45},{"name":"江苏","value":3.38},{"name":"陕西","value":3.17},{"name":"四川","value":3.06},{"name":"福建","value":3},{"name":"黑龙江","value":2.83},{"name":"吉林","value":2.79},{"name":"内蒙古","value":2.77},{"name":"重庆","value":2.69},{"name":"广东","value":2.63},{"name":"广西","value":2.14},{"name":"上海","value":0.03}]
	//借款合同纠纷 + 金融借款合同纠纷 
	var ssl_2 = [{"name":"北京","value":6.56},{"name":"浙江","value":3.41},{"name":"江西","value":3.33},{"name":"山西","value":2.92},{"name":"河南","value":2.37},{"name":"甘肃","value":2.1},{"name":"青海","value":2.04},{"name":"云南","value":1.98},{"name":"陕西","value":1.78},{"name":"宁夏","value":1.7},{"name":"新疆","value":1.39},{"name":"贵州","value":1.39},{"name":"江苏","value":1.2},{"name":"辽宁","value":1.19},{"name":"山东","value":1.03},{"name":"河北","value":1},{"name":"内蒙古","value":0.96},{"name":"湖南","value":0.94},{"name":"广东","value":0.84},{"name":"安徽","value":0.79},{"name":"广西","value":0.78},{"name":"天津","value":0.73},{"name":"福建","value":0.68},{"name":"吉林","value":0.67},{"name":"四川","value":0.66},{"name":"重庆","value":0.51},{"name":"海南","value":0.47},{"name":"黑龙江","value":0.25},{"name":"上海","value":0.03}]
	//同业拆借纠纷
	var ssl_7 = [{"name":"贵州","value":0},{"name":"山东","value":0},{"name":"重庆","value":0},{"name":"江苏","value":0},{"name":"陕西","value":0},{"name":"福建","value":0},{"name":"河南","value":0},{"name":"河北","value":0},{"name":"广西","value":0},{"name":"宁夏","value":0},{"name":"天津","value":0},{"name":"四川","value":0},{"name":"吉林","value":0}]
	//企业借贷纠纷
	var ssl_4 = [{"name":"北京","value":35.94},{"name":"云南","value":22.76},{"name":"河南","value":15.54},{"name":"吉林","value":12.68},{"name":"山西","value":12.5},{"name":"新疆","value":10.59},{"name":"河北","value":9.76},{"name":"甘肃","value":8.7},{"name":"辽宁","value":8.56},{"name":"内蒙古","value":8.2},{"name":"浙江","value":7.67},{"name":"山东","value":7.52},{"name":"安徽","value":7.26},{"name":"海南","value":7.14},{"name":"宁夏","value":7.14},{"name":"天津","value":6.59},{"name":"贵州","value":6.02},{"name":"福建","value":5.96},{"name":"江苏","value":5.48},{"name":"湖南","value":5.41},{"name":"广东","value":4.95},{"name":"重庆","value":4.27},{"name":"黑龙江","value":4.21},{"name":"四川","value":3.61},{"name":"广西","value":3.33},{"name":"青海","value":2.38},{"name":"陕西","value":2.27},{"name":"上海","value":0.52},{"name":"西藏","value":0},{"name":"江西","value":0}]
	//民间借贷纠纷
	var ssl_1 = [{"name":"海南","value":12.25},{"name":"北京","value":11.04},{"name":"江西","value":10.49},{"name":"河南","value":8.7},{"name":"云南","value":8.47},{"name":"天津","value":7.93},{"name":"新疆","value":7.29},{"name":"山东","value":6.6},{"name":"辽宁","value":6.53},{"name":"河北","value":6.45},{"name":"宁夏","value":6.23},{"name":"吉林","value":6.07},{"name":"甘肃","value":5.71},{"name":"湖南","value":5.43},{"name":"安徽","value":5.2},{"name":"青海","value":4.86},{"name":"四川","value":4.62},{"name":"黑龙江","value":4.56},{"name":"山西","value":4.35},{"name":"贵州","value":4.22},{"name":"江苏","value":4.01},{"name":"重庆","value":3.95},{"name":"浙江","value":3.62},{"name":"广东","value":3.61},{"name":"福建","value":3.56},{"name":"陕西","value":3.38},{"name":"内蒙古","value":3.11},{"name":"广西","value":2.77},{"name":"上海","value":0.02}]
	//小额借款合同纠纷
	var ssl_3 = [{"name":"宁夏","value":5.59},{"name":"云南","value":5.32},{"name":"天津","value":4.55},{"name":"安徽","value":3.57},{"name":"青海","value":3.57},{"name":"山东","value":2.82},{"name":"河南","value":2.18},{"name":"浙江","value":2.12},{"name":"内蒙古","value":1.89},{"name":"北京","value":1.85},{"name":"黑龙江","value":1.75},{"name":"新疆","value":1.46},{"name":"福建","value":1.4},{"name":"辽宁","value":1.36},{"name":"河北","value":1.14},{"name":"吉林","value":1.08},{"name":"贵州","value":0.75},{"name":"山西","value":0.74},{"name":"陕西","value":0.72},{"name":"湖南","value":0.71},{"name":"甘肃","value":0.64},{"name":"江苏","value":0.63},{"name":"四川","value":0.48},{"name":"广东","value":0.47},{"name":"重庆","value":0.13},{"name":"上海","value":0},{"name":"广西","value":0},{"name":"海南","value":0},{"name":"江西","value":0}]
	//金融不良债权转让合同纠纷 '黑龙江',750.00,
	var ssl_6 = [{"name":"海南","value":50},{"name":"浙江","value":40},{"name":"天津","value":38.46},{"name":"吉林","value":34.09},{"name":"福建","value":33.33},{"name":"河南","value":28.57},{"name":"云南","value":28.57},{"name":"四川","value":25},{"name":"山东","value":19.3},{"name":"辽宁","value":18.92},{"name":"陕西","value":15.38},{"name":"内蒙古","value":15.38},{"name":"重庆","value":14.29},{"name":"安徽","value":14.29},{"name":"北京","value":12.5},{"name":"湖南","value":9.09},{"name":"江苏","value":8.47},{"name":"广东","value":6.67},{"name":"河北","value":5.71},{"name":"山西","value":0},{"name":"上海","value":0},{"name":"新疆","value":0},{"name":"贵州","value":0},{"name":"青海","value":0},{"name":"江西","value":0},{"name":"宁夏","value":0}]
	//金融不良债权追偿纠纷 
	var ssl_5 = [{"name":"甘肃","value":66.67},{"name":"辽宁","value":62.07},{"name":"贵州","value":50},{"name":"吉林","value":30},{"name":"天津","value":21.43},{"name":"内蒙古","value":16.67},{"name":"云南","value":14.29},{"name":"山西","value":14.29},{"name":"湖南","value":14.29},{"name":"海南","value":12.9},{"name":"山东","value":12.73},{"name":"重庆","value":12.5},{"name":"福建","value":10.26},{"name":"陕西","value":7.14},{"name":"广东","value":5.43},{"name":"河北","value":5.41},{"name":"江苏","value":5.13},{"name":"河南","value":4.52},{"name":"安徽","value":1.69},{"name":"四川","value":0},{"name":"浙江","value":0},{"name":"黑龙江","value":0},{"name":"青海","value":0},{"name":"广西","value":0},{"name":"江西","value":0},{"name":"新疆","value":0},{"name":"宁夏","value":0}]

	var option = {
			timeline:{
				show : true,
				controlPosition : 'left',
				notMerge : true,
				data:[
      		        '2008','2009','2010','2011','2012','2013','2014','2015'
//				      '总计','民间借贷纠纷','金融借款合同纠纷','小额借款合同纠纷','企业借贷纠纷','金融不良债权追偿纠纷','金融不良债权转让合同纠纷','同业拆借纠纷'

				      ],
				      label : {
				    	  	interval: 0,
				            formatter : function(s) {
				                return s.slice(0, 0);
				            }
				        },
				      height : 30,
				      autoPlay : true,
				      loop : true,
				      playInterval : 1500
			},
			options:[
			         {
			        	 title : {
			        		 text: '全国各省案件上诉率',
			        		 x:'center',
			        		 y:-1
			        	 },
			        	 tooltip : {
			        		 'trigger':'item',
			        		 formatter : '{b} : </br> 所占比例：{c}'
			        	 },
			        	 legend: {
			        		 show : false,
			        		 orient: 'vertical',
			        		 x:'left',
			        		 data :[
			  				      '总计','民间借贷纠纷','金融借款合同纠纷','小额借款合同纠纷','企业借贷纠纷','金融不良债权追偿纠纷','金融不良债权转让合同纠纷','同业拆借纠纷'

			        		        ]
			        	 },
			        	 dataRange: {
			        		 min: 0,
			        		 max: 15,
			        		 x: 'left',
			        		 y: 'bottom',
			        		 text:['高','低'],           // 文本，默认为数值文本
			        		 calculable : true
			        	 },
			        	 toolbox: {
			        		 show: true,
			        		 orient : 'vertical',
			        		 x: 'right',
			        		 y: 'center',
			        		 feature : {
			        			 mark : {show: true},
			        			 dataView : {show: true, readOnly: false},
			        			 restore : {show: true},
			        			 saveAsImage : {show: true}
			        		 }
			        	 },
			        	
			        	 series : [
			        	           {
			        	        	   "type": "map",
			        	        	   "roam" : false,
			        	        	   "showLegendSymbol" :false,
			        	        	   "mapType":"china",
			        	        	   "mapLocation":{
			        	        		   height : '300' 
			        	        	   },
			        	        	   "itemStyle":{
			        	        		   normal:{label:{show:true}},
			        	        		   emphasis:{label:{show:true}}
			        	        	   },

			        	           		'data': ssl_0
			        	           },
			        	           ]
			         },
			         {
			        	 title : {'text':'全国各省民间借贷纠纷案件上诉率'},
			        	 dataRange: {
			        		max : 15
			        	 },
			        	 series : [

			        	           {'data': ssl_1}
			        	           ]
			         },
			         {
			        	 title : {'text':'全国各省金融借款合同纠纷案件上诉率'},
			        	 dataRange: {
				        		max : 10
				        	 },
			        	 series : [

			        	            {'data': ssl_2}
			        	           ]
			         },
			         {
			        	 title : {'text':'全国各省小额借款合同纠纷案件上诉率'},
			        	 dataRange: {
				        		max : 10
				        	 },
			        	 series : [

			        	           {'data': ssl_3}
			        	           ]
			         },
			         {
			        	 title : {'text':'全国各省企业借贷纠纷案件上诉率'},
			        	 dataRange: {
				        		max : 40
				        	 },
			        	 series : [

			        	           {'data': ssl_4}
			        	           ]
			         },

			         {
			        	 title : {'text':'全国各省金融不良债权追偿纠纷案件上诉率'},
			        	 dataRange: {
				        		max : 70
				        	 },
			        	 series : [

			        	           {'data': ssl_5}
			        	           ]
			         },
			         {
			        	 title : {'text':'全国各省金融不良债权转让合同纠纷案件上诉率'},
			        	 dataRange: {
				        		max : 50
				        	 },
			        	 series : [

			        	           {'data': ssl_6}
			        	           ]
			         },
			         {
			        	 title : {'text':'全国各省同业拆借纠纷案件上诉率'},
			        	 dataRange: {
				        		max : 10
				        	 },
			        	 series : [

			        	            {'data': ssl_7}
			        	           ]
			         }

			         ]
	};
	var chart = echarts.init(document.getElementById('es_ssl'));
	chart.setOption(option);

**Comment by LiuQ1ang** [comment]
OK，已解决，THX
