### ISSUE TITLE
请问有没有画百度图谱的实例？

### ISSUE THREAD

**Issue by robin521111** [ecomfe/echarts#1236]
不知道echart 可不可以画了百度指数中的需求图谱？以下是样例图。
http://index.baidu.com/?tpl=demand&word=%B4%D2%B4%D2%C4%C7%C4%EA%2C%D2%BB%B2%BD%D6%AE%D2%A3#655757-qzone-1-5827-2a36e2a4d4b0c34b8ee30457d06d6a88

**Comment by kener** [comment]
这不就是散点图吗？加个背景图片就好了。
如果觉得背景图片不够真实也需要有数据解读，那就用pie做背景
