### ISSUE TITLE
地图的tooltip能不能获得不求和的数据

### ISSUE THREAD

**Issue by yeahe83** [ecomfe/echarts#1237]
我想用地图一次性显示几个完全不能相加的东东，但是似乎自定义tooltip只有和值？

地图 : a（系列名称），b（区域名称），c（合并数值）, d（无）

**Comment by LiuQ1ang** [comment]
Map里的series中 mapValueCalculation可以设置'sum'（总数） | 'average'（均值）

**Comment by yeahe83** [comment]
好吧，我拿全局变量存在外面吧，不考虑用params获得数据了。

**Comment by kener** [comment]
function的参数都打印出来看看，data会返回，里面可做索引技巧。
另外this指向当前实例，实例可以getOption。
当然，全局变量实例也是可以的。
