### ISSUE TITLE
线条图 legend 现在默认8种颜色循环，如何添加其他颜色

### ISSUE THREAD

**Issue by itlizhi** [ecomfe/echarts#1239]
![qq 20150204120952](https://cloud.githubusercontent.com/assets/10509513/6035051/debc161e-ac66-11e4-8c73-d7ab22b77654.png)

如图，谢谢

**Comment by IlovedJoey** [comment]
http://echarts.baidu.com/doc/doc.html#Color 
文档里有
Color属性，可以自定义一个数组

**Comment by LiuQ1ang** [comment]
1.option下的color数组，传递一个数组。
2.itemStyle中的normal下的color属性需要添加一个回调函数，在回调函数中指定每个series要添加的颜色

**Comment by itlizhi** [comment]
@IlovedJoey,@LiuQ1ang   非常感谢
