### ISSUE TITLE
更新2.2.0 之后 markpoint 获得焦点后，之前所选条目垂直线不消失，如图

### ISSUE THREAD

**Issue by IlovedJoey** [ecomfe/echarts#1241]
![item-miss](https://cloud.githubusercontent.com/assets/10646771/6035752/d9f2da34-ac73-11e4-80aa-5aacc4881786.png)

如上图，截图时焦点在最大值的markpoint上面 ，版本2.1.10时还没有这个问题。
请大神看看是否是个bug。

**Comment by kener** [comment]
谢谢反馈~
