### ISSUE TITLE
echarts数据较多时，动态设置div的宽和高报错

### ISSUE THREAD

**Issue by shuqiyige** [ecomfe/echarts#1242]
<div style="overflow:auto;width:500px;height:300px;">
	<div id="barMore" ></div>
</div>

我在js文件中动态设置了barMore的高和宽，就会导致echarts报错，数据有一点大，要出滚动条才行，默认提供的dataZoom功能计算出的百分比，设置有样式问题很丑
![2015-02-05_172304](https://cloud.githubusercontent.com/assets/8336657/6037914/6ce7e6b2-ac93-11e4-8322-86f37c30c48b.png)

这个是使用dataZoom的效果，（不知道后期可不可以支持，宽度设置为像素）
![2015-02-05_172839](https://cloud.githubusercontent.com/assets/8336657/6037928/91496648-ac93-11e4-98b9-db5f88e71a67.png)
还有上次我提交的那个问题，不晓得你过后看我的回复没有#1185

**Comment by kener** [comment]
什么样式问题？看看你做的滚动条？
