### ISSUE TITLE
升级2.2.0之后，力导向图的工具和图例会跟着图一起缩放

### ISSUE THREAD

**Issue by saki-kkkkkyo** [ecomfe/echarts#1247]
设置的roam:true，用滚轮缩放图时toolbox和legend跟着一起缩放了。之前用的版本2.1.8没有这个现象。

**Comment by pissang** [comment]
示例中没有这个问题，这个问题应该是你把 toolbox， legend 的 zlevel 和 力导向配置成一样了，默认的是力导向是 1，其它是 0。
