### ISSUE TITLE
雷达图疑问

### ISSUE THREAD

**Issue by baobinluo** [ecomfe/echarts#1249]
![screenshot](https://cloud.githubusercontent.com/assets/8412566/6056129/c5cd0992-ad47-11e4-9f9a-3f4cdb1f10c1.png)
如图，我想在axisLabel添加'%'（即10，20，30，40，50后面），但是我发现polor的axisLabel里面只有show: true生效，其他均无效，我用官网的textStyle来调试也无效：polar : [
                       {
                           indicator : [
                               { text: '18～20', axisLabel: {show: true,textStyle:{fontSize:20,color: 'red'}}},
                               { text: '21～25'},
                               { text: '26～30'},
                               { text: '31～35'},
                               { text: '35以上'}]
                        }
                    ]
请问大侠是哪里没调对？版本是2.1.10

**Comment by kener** [comment]
@wind108369

**Comment by wind108369** [comment]
颜色、字号等，更新一下代码就可以了

现在还不支持 formatter，之后升级再加上

**Comment by baobinluo** [comment]
好吧，thx,只能等版本升级了

**Comment by wind108369** [comment]
最新的代码已支持formatter
