### ISSUE TITLE
饼状图不只显示数据名称,还要显示数字和百分比.

### ISSUE THREAD

**Issue by sheldon-xie** [ecomfe/echarts#1250]
![1](https://cloud.githubusercontent.com/assets/10841796/6058417/356536ac-ad62-11e4-9bac-d5804b5b1ec0.png)

如上图红线处,饼状图不只显示数据名称,还要显示数字和百分比.

**Comment by kener** [comment]
label.formatter 见文档
http://echarts.baidu.com/doc/example/pie.html
