### ISSUE TITLE
echarts connect 的支持的事件可否进行扩展；

### ISSUE THREAD

**Issue by Kuroky360** [ecomfe/echarts#1251]

**Comment by Kuroky360** [comment]
另外，conncet联动的多个图表在数据源相同和不同的处理细节

**Comment by kener** [comment]
具体什么扩展？另外问的是啥？

**Comment by Kuroky360** [comment]
1>图形连动的时候，文档里说明：
![connect](https://cloud.githubusercontent.com/assets/10414243/6075618/046b2b2e-ae11-11e4-9aef-62a6d9081d51.png)
我的意思是现在支持的事件就上面这几个，可否再封装一些其他的事件，比如说CLICK等事件，假设现在有这样的场景：现有同一个数据源做出的一个饼图和一个折线图，点击饼图的一个扇区，折线图只展示所点击扇区所选数据。
类似上面的Click连动事件，能否也进行封装呢
2>对于不同数据源所画出的不同图形，可以进行连动吗？或者有什么要注意的呢

**Comment by kener** [comment]
1、这个事件不应该联动啊，你要这个效果，响应图A的click去改图B的内容就行。

2、业务逻辑、业务处理，不为联动而联动，有数据解读意义才是根本。

**Comment by Kuroky360** [comment]
OK
