### ISSUE TITLE
能否添加表格绘制

### ISSUE THREAD

**Issue by ShanxiangWei** [ecomfe/echarts#1253]
从图形展示上来看我觉得已经很全面了，但是很多情况下需要用表格与图形的关联展示数据，所以不知道能否补充支持，我可以写个功能需求：
名称：tablix
属性：column:{
	color://背景色
	borderWithd://线框设置。。。
	width:{auto/number}//列宽，auto为根据内容多少动态设定，number为制定的宽
	textStyle:{}//内容配置
	sortable:{true/false}//排序
	filter:{true/false}//筛选
	aggregation:{enable://是否启用
			type:avg,min,max,sum//聚集方法
				Name:}//聚集行名
	locked:{true/false}//是否冻结，是指在内容窗口左右滑动时该列是否冻结
	data://配置数据（设置列名）
},
row:{
	color://背景色
	borderWithd://线框设置。。。
	height:{auto/number}//列宽，auto为根据内容多少动态设定，number为制定的宽
	textStyle:{}//内容配置
	filter:{true/false}//筛选
	aggregation:{enable://是否启用
			type:avg,min,max,sum//聚集方法
				Name:}//聚集行名
	locked:{true/false}//是否冻结，是指在内容窗口左右滑动时该列是否冻结
	data://内容数据
}
grid:{
	breakScreen: true/false//是否突破div范围，如果为false，则根据div宽度高度自动平均分配列宽和行高，如果为true，根据column和row的设定，如果实际宽高大于div的宽高，则可出现滚动条滑动展示未展示的列和行
}
event.onclick {}//能够获取点击当前行对应的各列的列名和值，或者能够获取当前单元格行号和列名

**Comment by kener** [comment]
谢谢，但是应该不会包含在echarts体系内，往 https://github.com/ecomfe/esui 里建议吧，谢谢关注。
