### ISSUE TITLE
时间轴怎么不支持中文？

### ISSUE THREAD

**Issue by kissstudio** [ecomfe/echarts#1254]
1、timeline.data
参考demo写这个["2002-01-01","2003-01-01"]就没问题
换成中文["2013年1月","2013年2月"]就不行了，只显示了第一个。
13-1这种缩写格式也不行。

2、当时间轴变化的时候 图表上的数据没有全部更新。
如果前一个时间数据是[{name:"a",value:1},{name:"b",value:2}]
而后一个只有[{name:"a",value:1}]

时间变更后{name:"b",value:2}依然保留在图标里。

**Comment by kener** [comment]
1、data仅接受new Date能接受的数据，显示中午通过formatter完成。
3、见文档，理解notMerge参数

**Comment by kissstudio** [comment]
thanks.
