### ISSUE TITLE
Map chart: "Uncaught TypeError: e.toFixed..." when using strings instead of numbers (2.2.0 only)

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#1255]
Hi ECharts team!
I'm trying the new 2.2.0 release and getting an error when using strings instead of numbers in map data, for example: 

data:[
    {name : 'China', value : "1359821.465"}
]

shows the Uncaught TypeError: e.toFixed in the console when hovering over China in the World Map example. 

where this works fine: 
data:[
    {name : 'China', value : 1359821.465}
]

This leads into something like this when hovering over countries: 
![image](https://cloud.githubusercontent.com/assets/561365/6101803/ea06986a-b02a-11e4-9d80-d173ab5aebe7.png)

I guess using numbers is more appropriate but it used to work in 2.1.10 so would be nice if it's backwards compatible. 

Haven't found any other issues with 2.2.0 so far which is impressive!

Anyway, thanks everyone for your hard work.

**Comment by kener** [comment]
Catch you. I will fixed it.

But I don't think using string would be ok even in 2.1.10.
We have not made any convert between string and number, so it must be wrong in some case like multiple map series, the sum or the average result would be wrong.

So we recommend name should be string, value should be number just like its literal comprehension.

Thanks @jarben , see you again.

**Comment by jarben** [comment]
Great, thanks!
