### ISSUE TITLE
Echarts与dojo冲突如何解决

### ISSUE THREAD

**Issue by zhll912** [ecomfe/echarts#1258]
如题，这两者之间有很多关键字是相同的，比如require，我在使用他们时，在页面中，哪个在前，哪个可以正常加载，另一个则不能显示，比如我用dojo显示arcgis的地图，但是就不能用echarts显示数据图表，请问如何解决？谢谢

**Comment by pissang** [comment]
使用 echarts-all.js

**Comment by countryer** [comment]
echarts3版本的 echarts-all.js从哪里可以得到？

**Comment by DukeGJ** [comment]
http://echarts.baidu.com/download.html @countryer
