### ISSUE TITLE
echarts的几个线性图、饼图绘制问题

### ISSUE THREAD

**Issue by greenHandpo** [ecomfe/echarts#1259]
1、如何取消线形图中的网格线，只留markline，也就是只要横向的线，不要竖向的线
2、如何绘制一个中间圆中的字固定不会变动的环形图
3、饼图中只有tooltip里的的formatter可以使用“<br/>”，series里的itemStyle的formatter无法使用"</br>"，也就是说，每一个扇形区域的名称若太长无法分两行写

**Comment by i6ma** [comment]
http://echarts.baidu.com/doc/asset/img/doc/axisDetail.png
http://echarts.baidu.com/doc/doc.html#Xaxis


http://echarts.baidu.com/doc/example/pie2.html
itemStyle : {
    normal : {
        label : {
            show : true,
            position : 'center'
        },
        labelLine : {
            show : false
        }
    },
    emphasis : {
        label : {
            show : true,
            position : 'center',
            textStyle : {
                fontSize : '30'
            },
            formatter: function (v) {return v.name.split('').join('\n');}
        }
    }
}


tooltip 换行用 '<br />'
itemStyle 换行用 '\n'
