### ISSUE TITLE
移动版还是多处出现重影现象

### ISSUE THREAD

**Issue by Amberllo** [ecomfe/echarts#1263]
移动版还是多处出现重影现象，包括折线图，仪表盘，柱状图，这里是tooltip在某些Android设备发生异常

![dd2bac94b938a17ed1410f4000f58e0f](https://cloud.githubusercontent.com/assets/2193074/6124547/4a51b028-b149-11e4-8541-39afd89efbde.jpg)

**Comment by Amberllo** [comment]
其中的动画已经关闭了

**Comment by kener** [comment]
![why-echarts-m-cn](https://cloud.githubusercontent.com/assets/1711855/6128311/7bb152a6-b16f-11e4-9b17-16ac7c1fb4de.png)
用你是设备试试这个看问题存在吗？

**Comment by xf222zt** [comment]
是的，我在安卓客户端中调用了js显示折线图。可是就是会出现多条线的状况，如果带有填充的话，根本看不清哪条线是哪条，很纠结，这是上面问题呀？

**Comment by xf222zt** [comment]
![device-2015-02-27-121347](https://cloud.githubusercontent.com/assets/9381440/6425169/cad60d5e-bf57-11e4-86dd-f4b15e801ee2.png)

**Comment by 823844596** [comment]
请问这个问题解决了嘛？同遇相同的问题...thanks

**Comment by xf222zt** [comment]
恩，你可以将动画效果关闭试试，在android4.2以上是可以用的，但是4.2以下就会出现那种效果，所以将animation属性设为false。就好了

**Comment by 823844596** [comment]
恩  好的，那你遇到过仪表盘图形在webview下有时都不出的情况嘛？直接图形的部分就是空白的。谢谢了！

**Comment by xf222zt** [comment]
你看看是图像的问题么，用浏览器将html打开，如果浏览器也看不到，那就是图像的问题了

**Comment by 823844596** [comment]
我在安卓的浏览器上打开html的话，图表显示的都是正常的，但是在webview下，显示就不正常了，仪表盘出现过双指针，折线图出现过折线显示不对，仪表盘和折线图有时不显示的情况，方便留个QQ或者其他的联系方式嘛，可以咨询一下~

**Comment by 823844596** [comment]
把动画去掉了，双指针的问题解决掉了，这个问题困扰很久了，非常感谢！现在初始化echarts对象时，我是先判断对象存不存在，如果存在就dispose，然后在init出来。

**Comment by linmuxi** [comment]
数据动态新增是调用addData方法，animation、addDataAnimation 都设置成false了，还是会出现重影。。。

**Comment by 823844596** [comment]
我之前就是判断对象是否存在，如果不存在就dispose掉，重新init，这样不会出现仪表盘双指针的情况... 你也这样试试？

**Comment by linmuxi** [comment]
@823844596  我页面数据更新频率较快，10s刷新一次，不知道这样频繁的dispose会不会有什么影响。

**Comment by linmuxi** [comment]
遇到这个问题的人好像还挺多的，不晓得echart的各位大牛有没有比较好的解决方案。
