### ISSUE TITLE
关于折线图布局100%宽度的需求

### ISSUE THREAD

**Issue by beidoufe** [ecomfe/echarts#1264]
在项目开发里，经常会遇到这种视觉需求：
![qq 20150210173823](https://cloud.githubusercontent.com/assets/7550810/6124813/a2891892-b14b-11e4-9e00-f1288a51d502.png)

可见，坐标的`x`和`x2`，能为0最好，可以撑到100%，与上面的控制面板等宽。
但存在的问题是，横轴坐标的lable，要么`algin:left` 要么`align:right` 要么`align:center`，总是会被display:hidden一部分。
有没有可能新增一个配置来支持此视觉设计？
目前我自己用的方法是，在 x轴的`axisLabel`配置里，用`formatter`给标签数组头和尾的标签内容加空格，感觉有点矬……

BTW. 折线图中，线条 hover之后的 `symbol` 是可配置吗？如上图，静态时symbol是none，hover后是circle，可以配置吗？找了半天没找到 = =

**Comment by kener** [comment]
其实可以做到，但我并不推荐，这样x轴label与线的映射对齐规则不一致，数据量少还好，多了数据误导比较严重。
真要实现的方法就是类目轴里data级的textStyle，第一个左对齐，最后一个右对齐就好。

BTW的方案，目前symbolSize是不区分normal和emphasis的，可以有的解决方案是靠borderWidth
基本能接近这个效果
   symbolSiaze: 0.5,
          itemStyle: {
            normal: {borderWidth:0},
            emphasis: {borderWidth:4}
          },

BTW，配色真好看，邀请你们的设计师给ECharts设计个主题吧，代码不好写，给设计图就行
http://echarts.baidu.com/doc/example/theme.html
