### ISSUE TITLE
移动版echarts在微信浏览器中崩溃的问题

### ISSUE THREAD

**Issue by wbdu** [ecomfe/echarts#1266]
我这有个微信公共号应用，使用了环图和bar图，在多个图形页面切换大约30次左右，微信崩溃，safari也也有此现象，但safari可自动装载页面，隐藏了此问题。
在iphone6+上必然出现，安卓手机未发现。

ps：数据量非常小。

**Comment by kener** [comment]
内存使用限制，这跟你切换时是否释放（dispose），图表数量，数据数量都有关系。

**Comment by amio** [comment]
你们的公众号是单页应用还是每次重新刷新的？
