### ISSUE TITLE
echarts-2.2.0, noDataLoadingOption配置不生效

### ISSUE THREAD

**Issue by hail812** [ecomfe/echarts#1269]
在option里面配置了，不生效；

查看到 _noDataCheck 方法里，执行了一句 this.clear(), 把option清掉了

**Comment by kener** [comment]
谢谢反馈，是个bug，暂时先用theme配置吧，init时传入，这个应该有效。

**Comment by flyingFlowers** [comment]
将代码改了  但是text只有当effect是whirling和spin的时候有效，其他效果都看不到文字
`
_noDataCheck:function(e){for(var t=e.series,n=0,i=t.length;i>n;n++)if(t[n].type==a.CHART_TYPE_MAP||t[n].data&&t[n].data.length>0||t[n].markPoint&&t[n].markPoint.data&&t[n].markPoint.data.length>0||t[n].markLine&&t[n].markLine.data&&t[n].markLine.data.length>0||t[n].nodes&&t[n].nodes.length>0||t[n].links&&t[n].links.length>0||t[n].matrix&&t[n].matrix.length>0||t[n].eventList&&t[n].eventList.length>0)return!1;var o=this._option&&this._option.noDataLoadingOption||this._themeConfig.noDataLoadingOption||a.noDataLoadingOption||{text:this._option&&this._option.noDataText||this._themeConfig.noDataText||a.noDataText,effect:this._option&&this._option.noDataEffect||this._themeConfig.noDataEffect||a.noDataEffect};this.clear();return this.showLoading(o),!0},
`
