### ISSUE TITLE
饼图label超出可视区域

### ISSUE THREAD

**Issue by luckyadam** [ecomfe/echarts#1270]
由于label较长，结果超出了饼图可视区域，求解决方案~使用版本2.2.0
![qq20150211-1](https://cloud.githubusercontent.com/assets/1782542/6147905/44eb5a5a-b237-11e4-9123-f9808ebd2c25.png)

**Comment by kener** [comment]
label formatter插入'\n'分行（常见的会在百分比前分行）
或者扩大图形区域，缩小饼图半径

**Comment by luckyadam** [comment]
恩，插入分行有些情况下会影响美观，而由于数据的不确定性，扩大图形区域和缩小饼图半径也只能解决部分问题。能不能够做到自动折行呢？
