### ISSUE TITLE
z not correct for axis and series line

### ISSUE THREAD

**Issue by Desuvader** [ecomfe/echarts#1271]
![](http://u.cubeupload.com/Horo/JflXvH.png)

I want the line to be in front of the axis. Is this a bug, or intended?

```javascript
var options = {
    xAxis: {
        z: 1 // <-- 1!
    },
    series: [
        {
            z: 2 // <-- 2! In front.
            type: 'line'
        }
    ]
}
```

**Comment by kener** [comment]
Sorry for the doc is not clear enough. z & zlevel is available in the option right now, it only can be set by theme. We will think about whether is a common use as options.
Right now, you can use it like this:

           var myChart = ec.init(
                document.getElementById('main'),
                {
                    line: {z: 5}          // as a theme params when init()
                }
            );

Thanks.

**Comment by Desuvader** [comment]
Thanks for the quick response! Closing this issue.
