### ISSUE TITLE
Qestion: DataZoom能不能加个监听事件？

### ISSUE THREAD

**Issue by IlovedJoey** [ecomfe/echarts#1276]
比如显示每天的销售数量趋势。Y轴表示销售数量，X轴是 天
默认显示10天，我在series里配置了itemStyle: {normal: {label: { show: true, position: 'top'}}}， 这样直接就可以显示出每天的销量。
但当我拖动datazoom显示较多的数据时，item的label就会挤到一起。看起来比较混乱。
如何监听当显示30天以上的数据时，把lable的show 设置为false?

求指点。。。

**Comment by kener** [comment]
先看看有没有再求？http://echarts.baidu.com/doc/doc.html#实例方法

**Comment by IlovedJoey** [comment]
Thanks !  居然没看到这里。。。。。。
