### ISSUE TITLE
Positive and negative area color

### ISSUE THREAD

**Issue by Desuvader** [ecomfe/echarts#1278]
Is something like this possible right now?:
![](http://u.cubeupload.com/Horo/BftBs6.png)

**Comment by xiong4824956** [comment]
![lizi](https://cloud.githubusercontent.com/assets/10083782/6184876/62efbb06-b3a2-11e4-86d9-0df87a1874cb.png)

this??

**Comment by Desuvader** [comment]
@xiong4824956 The graph is supposed to be *continuous*. Like:
![](http://u.cubeupload.com/Horo/zvWzhw.jpg)

**Comment by Desuvader** [comment]
Ping @kener (?)

**Comment by kener** [comment]
I'm afraid it can't be supported right now.

Maybe you can change the yaxis.splitArea.lineStyle.color = [nColor, pColor, pColor, pColor, pColor] and let the line areaStyle.color be rgba(x,x,x,0.3), maybe that would be a simulation.

And I think bar chart is another choice. http://ecomfe.github.io/echarts/doc/example/bar8.html#-en

**Comment by ramkumarkb** [comment]
Hi, 

This seems to be an old issue but are such charts possible in the newer versions of eCharts?

Thank you for the guidance 🙏
