### ISSUE TITLE
MarkPoint的最大值和最小值怎么格式化？

### ISSUE THREAD

**Issue by kissstudio** [ecomfe/echarts#1280]
RT.

**Comment by IlovedJoey** [comment]
http://echarts.baidu.com/doc/doc.html#SeriesMarkPoint

itemStyle属性， label 里面可以定义formatter,支持模板和function

例如：
markPoint : {
	data : [
			{
				type : 'max',
				name : ' 最大值'
	}],
	itemStyle: {
		normal: {
			label: {
				show: true,
				formatter:function(para){
					return para.name+"\n"+para.value;
				}
			}
		}
	}
}

**Comment by kissstudio** [comment]
如果既有值格式化器也有ToolTip等其他组件格式化器是否要方便很多。

这样 valueFormatter就可以在其他地方，如
tooltipFomatter(valueFormatter(value)),
itemStyleFormatter(valueFormatter(value)),
yAxisFormatter(valueFormatter(value)),
seriesFormatter(valueFormatter(value))
中复用。

值格式化器也可以全局使用了。

**Comment by kener** [comment]
赞
