### ISSUE TITLE
[遗漏？] xAxis的type为time时　无法触发x轴的tooltrip

### ISSUE THREAD

**Issue by huyinghuan** [ecomfe/echarts#1283]
官方demo,
http://echarts.baidu.com/doc/example/line8.html

修改tooltip: trigger: 'axis'
无法触发　基于Ｘ轴的tooltip　ui

**Comment by huyinghuan** [comment]
额，不对 触发了　基于Ｙ轴的tooltips, 如何触发基于X轴的tooltips?

**Comment by chenyi** [comment]
我也碰到同样的问题，我需要触发基于x轴的tooltip，但是因为x轴的type是time，变为y轴触发。我需要的是x轴触发
