### ISSUE TITLE
急：andriod版微信链接到echarts图表页面手机显示有问题

### ISSUE THREAD

**Issue by stella252** [ecomfe/echarts#1284]
在微信项目中，从微信链接到有echarts图表的页面，手机上的显示问题如下：
我们用的包是echarts2.1.8, 样式基本上是默认的，只有数据是加载页面时动态填充的。
图表在iso的微信、系统自带浏览器、android自带浏览器上显示都是正常的，只有在andoid微信上链接到响应的页面后会“网格和坐标轴无法对齐，放大或缩小或向下滑动都会使得网格和坐标轴分离”。
我们调试过后，感觉和手机及自定义样式没有关系。

不知道这是否是echarts的兼容性问题？

**Comment by kener** [comment]
![why-echarts-m-cn](https://cloud.githubusercontent.com/assets/1711855/6425653/658a0870-bf6f-11e4-9491-20420150e1c2.png)
试试这个？

**Comment by icode** [comment]
手机版本直接更换类库就可以么？不需要更换实现吧？为什么不是在一起的？用loader自动区分实现？

**Comment by kener** [comment]
是该自动区分啊，但不是类库完成的，自己需要写这个业务逻辑。

**Comment by Windancer** [comment]
这个Demo用微信看确实有兼容问题
