### ISSUE TITLE
使用 '-' 来填充断档数据的时候出现若干问题

### ISSUE THREAD

**Issue by xiong4824956** [ecomfe/echarts#1285]
2.2.0版本下
在折线图中使用'-'的时候会出现一个默认拐点样子的一个灰色小拐点,设置当前拐点size为0的时候才能消失
在柱状图中使用'-'的时候会出现一个灰色框框,,解决办法目前是值直接设为0,,,
如果用折线图和柱状图,做切换,,,貌似就没有什么办法了,
建议改成只要使用'-'的data,当前点或者bar或者其他什么的,就直接没有了,不要出现灰色的点点或者框框
不知道算不算bug..

**Comment by kener** [comment]
-_-|| 拖拽重计算特性，默认就是关闭的，你自己开了
