### ISSUE TITLE
echart图表呈现时，图表canvas和父容器div之间有空白，类似padding

### ISSUE THREAD

**Issue by terrycheng11** [ecomfe/echarts#1286]
如题：
echart图表呈现时，图表canvas和父容器div之间有空白，类似padding，这在手机上看图表，发现图表会很小，且屏幕两边空白面积居多

请问如何让图表自动填充满父容器，使两边的空白尽可能小？

**Comment by xiong4824956** [comment]
grid 里面设置属性的时候用百分比会好一些,
跟布局或者距离有关设置的时候,尽量都采用百分比,

**Comment by ahxukai** [comment]
我也遇到相同的问题了，现在有什么好的解决方法吗

**Comment by walshzhang** [comment]
在option里边使用grid属性，将x,y,x2,y2的值设小一些。
    var option = {
          grid: {
               x: 40, //默认是80px
               y: 20, //默认是60px
               x2: 20, //默认80px
               y2: 30 //默认60px
          }
    }

**Comment by preservance717** [comment]
@walshzhang 设置grid是对直角坐标系是有效的，但是对于饼图怎么设置，才能消除图表canvas和父容器div之间的空白

**Comment by a243650557** [comment]
@preservance717 请问你有解决吗。消除饼图之间的空白

**Comment by preservance717** [comment]
@a243650557 我是通过修改`radius`和`center`来消除饼图之间的空白。
![image](https://user-images.githubusercontent.com/18299850/42609123-8b3412f6-85bd-11e8-8282-9708455c0c4b.png)
