### ISSUE TITLE
为什么折线图的y轴比例不对，比如数值是13，对的y轴是26，为什么？

### ISSUE THREAD

**Issue by zhangkuiworld** [ecomfe/echarts#1287]
数据格式没问题，配置如下：
var addUserOption = {
        			title : {
        				text:'开发者数量趋势统计图'
        			},
        			tooltip : {
        				trigger: 'axis'
        			},
        			symbolList: [ 
        			    'diamond', 'diamond','diamond' 
        			],
        			legend : addUserData.legend,
        			toolbox: {
                         show : true,
                         feature : {
                             mark : {show: true},
                             dataZoom : {show: true},
                             magicType : {show: true, type: ['line', 'bar']},
                             restore : {show: true},
                             dataView : {show: true, readOnly: false},
                             saveAsImage : {show: true}
                         }
                     },
                     calculable : true,
                     dataZoom : {  
                         y: 270,
                         show : true,
                         realtime: true,
                         start : 90,
                         end : 100
                     },
                     grid: {
                    	 x: 80,
                         y: 40,
                         x2:20,
                         y2:60
                     },
                     xAxis : [
                            {
                                type : 'category',
                                boundaryGap : true,
                                axisTick: {onGap:false},
                                splitLine: {show:false},
                                data : addUserData.xAxis[0].data
                            }
        	         ],
        	         yAxis : [
        	                    {
        	                        type : 'value',
        	                        scale:true,
        	                        splitNumber: 3,
        	                        axisLabel: {
        	                            formatter: function (v) {
        	                                return v + ' 个';
        	                            }
        	                        },
        	                        splitArea : {show : true}
        	                    }
        	         ],
        	         series:addUserData.series
        	};

**Comment by zhangkuiworld** [comment]
如图：

**Comment by kener** [comment]
stack

**Comment by jiabinxiong** [comment]
删除 stack 有用 
但是为什么这个问题 官方还不解决了

**Comment by plus-zhang** [comment]
@jiabinxiong 真神奇
