### ISSUE TITLE
如何将时间轴选定的饼图名称设置到legend里？

### ISSUE THREAD

**Issue by zakk89** [ecomfe/echarts#1288]
var ecConfig= require('echarts/config');
	           industryChart.on(ecConfig.EVENT.TIMELINE_CHANGED,function (param) {
	        	   var selIndex = param.currentIndex;
	        	   var industryData = industryChartOption.options[selIndex].series[0].data;
	        	   var temp = [];
	        	   for(var i=0,j=industryData.length;i<j;i++){
	        		   temp.push(industryData[i].name);
	        	   }
	        	   industryChartOption.options[0].legend.data = temp;
	           });

这样实现后legend内容不随时间轴切换

**Comment by kener** [comment]
改原始option是没用的，重新setOption
