### ISSUE TITLE
echarts 散列图绑定数据可否传入更多参数？

### ISSUE THREAD

**Issue by jayshao830413** [ecomfe/echarts#1289]
echarts在做数据绑定的时候，传入的是一个由x,y值组成的数组，我想问一下如果我想给散列图绑定更多的参数要怎样做呢？

**Comment by kener** [comment]
传多少个不是重点，重点是你需要怎么把数据影视为图形元素？还是数仅仅时传进去某个时刻如formatter时拿来用

**Comment by jayshao830413** [comment]
我有一个需求， 每个点都是一个(x,y),我还需要绑定每个(x,y)所代表的数据个数，这个个数是当我点击每个散列图上的点的时候这个数据要显示在popup上

**Comment by kener** [comment]
formatter
