### ISSUE TITLE
markPoint自定义文字描述说明

### ISSUE THREAD

**Issue by chigco** [ecomfe/echarts#1290]
markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            }
悬停显示中貌似都是  [名称]:[值] 的显示方式，如果我想这样 “ 1元可以兑换[值]万 ”   多元化的自定义描述可以实现吗？
刚接触echarts不久，望指教。

**Comment by kener** [comment]
label formatter，见文档
