### ISSUE TITLE
 2.2.0版series-zlevel无效

### ISSUE THREAD

**Issue by huangyef** [ecomfe/echarts#1291]
在series里各个对象使用不同的zlevel，但并没有成功的分开canvas。
我之前是在marker的canvas和底图的canvas之间插热力图的，现在两个canvas和在一块了，热力图就插不进去了。
我觉得应该是bug。如果我使用方法错了，能不能给个示例呢？

**Comment by pissang** [comment]
同 #1271 目前只能通过 theme 的方式设置 zlevel 和 z
