### ISSUE TITLE
animation:false is not applied when map is roamed

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#1292]
Just noticed that setting animation:false to map has no effect after the map is zoomed/moved etc. Can be reproduced in this example: http://ecomfe.github.io/echarts/doc/example/map11.html#-en

Tested on master, not sure about 2.1.0 though. 

Thanks!

**Comment by kener** [comment]
animate for what？

**Comment by jarben** [comment]
Apologize for a late reply, here is a demo:

![echarts-animation](https://cloud.githubusercontent.com/assets/561365/7928035/576f0952-08e9-11e5-9fd1-f1716501c2ff.gif)

I've set animation:false, all is ok when the chart is loaded, however, it starts animate after zoom, roam etc.

**Comment by pissang** [comment]
Hi jarben, from you demo it seems you should disable the effect option in series instead of animation.

**Comment by jarben** [comment]
I see what you mean - thanks for your answer
