### ISSUE TITLE
感觉delMarkLine(index,markName)接口设计不太好用

### ISSUE THREAD

**Issue by ccdevote** [ecomfe/echarts#1293]
```javascript
markName = markName.split(' > ');
```
这段代码显示传入的markName会以 ` > ` 分割成两个，重要的是 `>`两边的空格。如果如果写`北京 > 上海` 这样不会有问题。如果`>`两边少了空格，如：`北京>上海`，那这样就出问题了，结果就是不能删除标线。so，不知能不能增加一种接口实现，如：
```javascript　
delMarkLine(index,markName1,markName2)
```
或者其他更好的方式

**Comment by longFeiLi** [comment]
可以自己写个方法啊。然后自己里面做。

**Comment by kener** [comment]
嗯嗯，我也觉得不好，当时瞎写的，没想到这个接口那么常用，这个' > '连接不应该作为del时需要关心的参数，改！
