### ISSUE TITLE
在echarts里添加能拖拽的zrender

### ISSUE THREAD

**Issue by romanticaa** [ecomfe/echarts#1295]
柱状图的echarts，也设置为可拖拽，然后拖转addShape进去的图形，松开的时候就变成一个圈了。。。

**Comment by kener** [comment]
？

**Comment by kener** [comment]
不需要拖拽重计算就关闭calculable

**Comment by Seven0711** [comment]
试着把calculaable关了，也没用，zrender的图一拉动，旁边就会多一个圈。

**Comment by hushicai** [comment]
如果还有问题，请贴出更详细的信息，然后再打开这个issue。
