### ISSUE TITLE
2.2.0版echarts mac版chrome渲染问题

### ISSUE THREAD

**Issue by nilday** [ecomfe/echarts#1296]
之前一直以为是我电脑的问题，发现其他电脑也有同样的问题。
在Mac OSX 10.10下40.0版chrome，当使用chrome打开含有echarts的页面，在加载过程中切换到其他网页，等echarts渲染结束后返回页面，会出现渲染问题（也就是渲染的时候页面未显示出来）。在之前的echarts版本中未发现类似问题。
![image](https://cloud.githubusercontent.com/assets/3797285/6225221/50ecbb3e-b6c2-11e4-9c44-c56d1dca9375.png)
![image](https://cloud.githubusercontent.com/assets/3797285/6225230/5dd8dd82-b6c2-11e4-9aaf-5a06ae82836b.png)
![image](https://cloud.githubusercontent.com/assets/3797285/6225233/6ac689a4-b6c2-11e4-9f6a-9b2d9927f1b1.png)

正常的图像分别如下：
![image](https://cloud.githubusercontent.com/assets/3797285/6225317/69c1a240-b6c3-11e4-87a4-a27b4c0126ec.png)
![image](https://cloud.githubusercontent.com/assets/3797285/6225322/737045bc-b6c3-11e4-8096-973664b9cca1.png)
![image](https://cloud.githubusercontent.com/assets/3797285/6225334/8a9498ba-b6c3-11e4-838b-08822314747a.png)

**Comment by pissang** [comment]
谢谢反馈，应该是个 bug，resize 之后就好了 @kener

**Comment by nilday** [comment]
对，resize之后是重新绘制了一遍吧。

**Comment by kener** [comment]
是requestAnimateFrame的问题？没显示时自动优化？

**Comment by nilday** [comment]
目前发现windows版的chrome也有同样的问题。

**Comment by nilday** [comment]
2.2.1版该问题仍然存在，firefox 35.0.1 windows 也发现该问题

**Comment by penciltim** [comment]
问题依然存在，windows 7 64bit, chrome 46.0.2490.86 m
