### ISSUE TITLE
Building Docs

### ISSUE THREAD

**Issue by JudeRosario** [ecomfe/echarts#1297]
What is the best way to build docs ? Want to send in a couple of PRs but Im sure the package does not ship with docs sources

**Comment by pissang** [comment]
uhhhh...We write the doc in html brutally, no other tools are used. But in [ZRender](https://github.com/ecomfe/zrender) we are using jsdoc

**Comment by JudeRosario** [comment]
Oh that must be real painful to do .. btw great product. 

I helped [FusionCharts](www.fusioncharts.com) write their API docs and usage guides, I used to work there. Will chip in here with some edits when I get time. 

Cheers
