### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by bamos** [ecomfe/echarts#1299]
http://derecho.elijah.cs.cmu.edu:8585/ecomfe/echarts

**Comment by kener** [comment]
？

**Comment by bamos** [comment]
Sorry, these links in the README are broken for me. 
(Search the README for `example/map`)
The links to `echarts.baidu.com` are not prefixed with `http://`,
so GitHub is prefixing them with the GitHub URL for this repo:

+ https://github.com/ecomfe/echarts/blob/master/echarts.baidu.com/doc/example/map12.html
+ https://github.com/ecomfe/echarts/blob/master/echarts.baidu.com/doc/example/map11.html
