### ISSUE TITLE
怎么去掉南丁格尔图表里的圆线？

### ISSUE THREAD

**Issue by shallker** [ecomfe/echarts#1302]
![image](https://cloud.githubusercontent.com/assets/2121871/6392215/65c82140-bdf9-11e4-873f-c14b3b738236.png)

中心圆圈里的那条灰色圆线怎么去掉？

**Comment by shallker** [comment]
在保留内半径radius的基础上

**Comment by kener** [comment]
关闭拖拽重计算，默认就是关闭的。
