### ISSUE TITLE
能否增加map的一个平移和放大动画效果?

### ISSUE THREAD

**Issue by talentwing** [ecomfe/echarts#1303]
做地图标注的时候需要一段时间(或者鼠标点击触发)以某个MarkPoint为中心放大并显示一些信息..
看了一下文档,貌似没有关于这方面效果的方法,能不能增加或者别的方法实现?

**Comment by kener** [comment]
要实现平移放大，有三个方案：
1、利用mapLocation改变坐标和大小
2、触发模拟鼠标的拓展和滚轮
3、有个roamController组件，目前没公开方法，但你可以看看源码直接调用这个组件的方法实现平移和放大。

**Comment by talentwing** [comment]
第一个方式没有过度的效果.
第二个方式试了半天没弄出来(鼠标滚轮事件貌似不能模拟?)
第三个方式也没搞懂.(是否能有DEMO参考一下?)
现在只能试着在map.js里加自己的方法来实现了...

**Comment by zhiyaohaha** [comment]
echarts 鼠标滚轮事件触发的函数是什么 我一直没找见
