### ISSUE TITLE
安卓使用Echarts时，折线图重影，出现多条折线

### ISSUE THREAD

**Issue by xf222zt** [ecomfe/echarts#1304]
数据都是对的，并且只加载了一次，但是有的会正常显示，有的就会出现重影，这个是不能接受的呀，还有什么地方没有设置么，或者怎么修改啊？！急求解答....
![device-2015-02-27-121347](https://cloud.githubusercontent.com/assets/9381440/6425184/90fe8be6-bf58-11e4-9aaa-2b36dd27bcb0.png)

**Comment by kener** [comment]
关闭动画试试？

**Comment by xf222zt** [comment]
这个有关系？我原来试过了，还是不行呀？位置写错了么？你在哪里改的

**Comment by linmuxi** [comment]
关闭动画也出现，如何修复
