### ISSUE TITLE
这是bug吗？横坐标动态从B(如:1,2,3,4)到A(如:周一，周二),横坐标将变为(周一，周二,3,4)

### ISSUE THREAD

**Issue by callmeJozo** [ecomfe/echarts#1305]
如题，这是bug还是是可以解决的？本人菜尝试了好久没能成功，求大牛牛解答下我哦，谢谢

**Comment by callmeJozo** [comment]
贴上测试代码（新手还不会用markdown，体谅哦）

myChart.on(ecConfig.EVENT.LEGEND_SELECTED, function (param){
				    var selected = param.selected;
				    var xdata = option.xAxis[0].data;
				    if (selected['本周']) {
				    	xdata.splice(0,xdata.length,'周一','周二','周三','周四','周五','周六','周日')
				    	adddata('本周',[100, 200, 150, 130, 50, 130, 100]);
				    	console.log(xdata);
				    	console.log(option);
				    	myChart.setOption(option);
				    }
				    if (selected['本月']) {
				    	xdata.splice(0,xdata.length,'周一','周二','周三','周四','周五','周六','周日','1','2','3')
				    	adddata('本月',[1,2,3,4,5,6,7,8,9,10]);
				    	console.log(xdata);
				    	console.log(option);
				    	myChart.setOption(option);
				    }
				    if(selected['上月']){
				    	xdata.splice(0,xdata.length,'周一','周二','周三','周四','周五','周六','周日')
				    	adddata('上月',[10,20,30,40,50,60,70]);
				    	console.log(xdata);
				    	console.log(option);
				    	myChart.setOption(option);
				    }
				});

在这之后，横坐标就一直都是（'周一','周二','周三','周四','周五','周六','周日','1','2','3'） 最长的那个

**Comment by kener** [comment]
setOption 第二个参数，见文档

**Comment by callmeJozo** [comment]
(⊙o⊙)…  没看到第二个参数的作用，3Q
