### ISSUE TITLE
line 图标，y轴数据不匹配

### ISSUE THREAD

**Issue by liangjie** [ecomfe/echarts#1307]
![image 3-2-15 at 3 36 pm](https://cloud.githubusercontent.com/assets/121752/6437275/5f36b9f8-c0f7-11e4-9875-f5dc904520f3.jpg)

如图：自左到右，几个高峰的点的值分别是：

10:00   7031551
20:00   9954629
21:00   9662864
22:00   9033693
23:00   9622263

时间选择范围缩小绘图的点则减少，就不会出现这个问题。出问题的如上图，一共是1440个点绘图。
当前使用版本：2.2.0  已经升级到最新版本，发现问题仍然存在。

部分代码如下：

var option = {
        tooltip : {
   	trigger: 'axis',
        axisPointer:{
        	type : 'line',
        	lineStyle : { color: 'red', width: 1, type: 'solid' }
                }
        },
        grid:{x:65,y:20,x2:25,y2:30},
        legend:{ data:legendData },
        toolbox: {
        	show : false,
        	feature : {
        		mark : {show: false},
        		dataView : {show: false, readOnly: false},
        		magicType : {show: false, type: ['line', 'bar']},
        		restore : {show: false},
        		saveAsImage : {show: true}
        		}
        },
        dataZoom : { show : false, start : '0', end : '100', realtime:true },
        xAxis : [ { type : 'category', boundaryGap : false, data : x_data } ],
        yAxis : [ { type : 'value', scale: true, precision:1, boundaryGap: [0, 0.2] } ],
        series : seriesArray
};

**Comment by liangjie** [comment]
请问下，这是一个bug吗？
还是我使用不正确？
还是我需要再提供什么数据来说明这个问题吗？

**Comment by liangjie** [comment]
@kener  请问下，这个问题我反馈的方式有问题？还是你们无法知道是啥问题？

谢谢

**Comment by kener** [comment]
了解了，这是数据抽取算法的问题，只是做了最简单的间隔挑选，没有做极值判断。
抽取算法简单来说就是当前空间显示不下时会做筛选，比如1000px下显示3000个数据，每一个单位像素要同时表达3个不同的数据是不可能的，所以会有抽取算法，可以做极值（最高、最低），可以做均值，也可以像目前实行那样就是固定选择第一个（间隔筛选）。

这里的设计目标应该是公开这个逻辑让用户可以自定义的，一直是个升级点。谢谢反馈。

**Comment by liangjie** [comment]
@kener 非常感谢你的这段描述，让我明白了问题所在。
请问，这个支持自定义的接口的升级点预计能在哪个版本上呢？

**Comment by kener** [comment]
暂无安排，可以看看line的源码，如果不考虑通用性改成极值就几行代码的事

**Comment by liangjie** [comment]
@kener 
好的，那我们修改下默认的值。多谢，指教！

**Comment by liangjie** [comment]
@kener  请问下，要修改的代码在哪个地方？代码行数在哪？

我这边看了下，修改的都不对。
谢谢了。
