### ISSUE TITLE
横坐标为time类型时的问题

### ISSUE THREAD

**Issue by huangyef** [ecomfe/echarts#1309]
![image](https://cloud.githubusercontent.com/assets/11002227/6456535/8a035020-c1a0-11e4-8efa-0d5c949984b8.png)
![image](https://cloud.githubusercontent.com/assets/11002227/6456580/2ea5b78a-c1a1-11e4-84d1-4b07f202ec29.png)

图一横坐标为time类型
图二横坐标为category类型
如何让图一的横线变为图二那样的竖线？

**Comment by kener** [comment]
双数值型的图表没办法用直线作为axisPointer，改一下axisPointer的type为cross吧，这在双数值型图表会更好。

**Comment by huangyef** [comment]
谢谢
