### ISSUE TITLE
echarts 使用requirejs 问题

### ISSUE THREAD

**Issue by firstsko** [ecomfe/echarts#1311]
require.config({
	baseUrl: '/js',
	paths: {
		'echarts': 'libs/echarts/build/dist/echarts-all',
	},

require([ 'backbone','echarts','echarts/chart/bar'], function(Backbone,ec) {

})

GET http://192.168.8.246:3100/js/libs/echarts/build/dist/echarts/chart/bar.js 
require.js:8 Uncaught Error: Script error for: echarts/chart/bar

一直报这个错误，请问如何解决呢？

**Comment by longFeiLi** [comment]
echarts-all  这个文件是单文件的引用。 你要换成 echarts 试一下。然后去看下文档吧。 http://echarts.baidu.com/doc/start.html

**Comment by wh1100717** [comment]
@firstsko 
[5分钟上手写ECharts的第一个图表](http://echarts.baidu.com/doc/start.html) 中列举的两种第一种引用方式并非是requirejs的引用。

而 [文档](http://echarts.baidu.com/doc/doc.html#引入ECharts1) 中通用性模块化的方案用需要额外下载zrender库，因为模块依赖的关系，会引入很多小文件。

如果要使用requirejs的话，个人还是建议使用echarts-all单文件，然后再require中配置一下shim就可以了。

```coffee
require.config {
    paths: {
        echarts: "/xxx/echarts-all"
    }
    shim: {
        echarts: {
            exports: "echarts"
        }
    }
}
```
