### ISSUE TITLE
x轴为时间序列时，仅设置起始时间和时间间隔的需求

### ISSUE THREAD

**Issue by for5million** [ecomfe/echarts#1313]
这个是从highcharts来的需求，highcharts，当x轴为时间时，可以设置起始时间和时间间隔，highcharts会根据数据列的多少，来生成日期的格子。
对于时间序列的报表来说很有用，起码不需要自己再重新创建数据列那么多的日期对象了。

**Comment by kener** [comment]
起始和结束时间也不需要，我们是这样做的
http://echarts.baidu.com/doc/example/line8.html

**Comment by cheeringsoul** [comment]
@kener 我看了这个例子是 根据series里给的数据，自动获取最大时间和最小时间来作为曲线图x轴的两个端点。
但是我现在不希望把我初始化时给定的那个最大时间作为x轴上的右端点，这个有什么办法吗？我其实是想绘制股票实时图，最大最小时间是固定的，而曲线是随着时间慢慢生成的，我看你给的例子一初始化就把最大的时间作为x轴的右端点了。。
