### ISSUE TITLE
Light version problem

### ISSUE THREAD

**Issue by mgohin** [ecomfe/echarts#1314]
Hi,

In my index.html I have

    <script src="bower_components/echarts/build/source/echarts.js"></script>
    <script src="bower_components/echarts/build/source/chart/line.js"></script>

Then when trying to get echarts

    require('echarts')

I got this error ```Error: [MODULE_MISS]"echarts" is not exists!```

And if I use ```build/dist/echarts-all.js ``` I got this error ```require is not defined```, so I try to call global var echarts and it's working.

How can I use light version (echarts.js with line.js) ?

**Comment by kener** [comment]
Maybe you need require.config, check this

http://ecomfe.github.io/echarts/doc/start-en.html

**Comment by mgohin** [comment]
Ok it's working, I don't know what I missed last night ... nothing's better than a good sleep ;)

**Comment by mgohin** [comment]
Still got a question : why is -all.js version not the same as light version ?
