### ISSUE TITLE
Show tooltip for every data point, but skip xAxis labels?

### ISSUE THREAD

**Issue by ericbae** [ecomfe/echarts#1315]
Is it possible to show tooltips for every data point, but be able to skip the xAxis labels?

I do the following

      xAxis : [{
        type : "category",
        axisLabel:{
          interval:0
       }
     }]

But my xAxis labels overlap each other. But if I set the interval to "5", then I lose my tooltips for some data points.

**Comment by kener** [comment]
What is your chart’s type? line? bar?
You can try to let the tooltip’s trigger to be ‘axis’ like this

    tooltip: {
      trigger: ‘axis
    }

**Comment by ericbae** [comment]
hi @kener 

My tooltip trigger setting is already set to "axis".

My chart type is "line".

The issue is that 

    axisLabel: {
      interval:0
    }

makes my chart looks like below image

![screen shot 2015-03-04 at 2 52 16 pm](https://cloud.githubusercontent.com/assets/614459/6477993/15c676b8-c27e-11e4-9ea4-9f6533c08936.png)

But if I set the the interval to a higher number, tooltip doesn't work for every point.

**Comment by kener** [comment]
check this http://echarts.baidu.com/doc/example/line6.html
and maybe you can give me your options

**Comment by ericbae** [comment]
Awesome. Thank you very much.

I realised it was my mistake. I had a duplicate "tooltip" settings.

So I had

    tooltip: {
      trigger:"axis"
    }

and then down the further line, I had
    
    tooltip: {
      show:true
      axisPointer:
        type:"none"
    }

Thank you for all your help.
