### ISSUE TITLE
改写toolbox的dataView 怎么办？

### ISSUE THREAD

**Issue by sheldon-xie** [ecomfe/echarts#1316]
领导要求这个展示界面要改，改写这个功能，改成html的table展示，请问怎么改最好？

**Comment by kener** [comment]
目前的optionToContent只支持自定义返回字符串到textArea里，暂不支持覆盖这个textArea为其他类型的dom，这其实是我们最初的想法，是应该可以让用户复写为如table这样的展现形式，谢谢反馈，后续升级吧。

**Comment by IlovedJoey** [comment]
本人暂时的做法.

1. 添加一个隐藏绝对定位的div（自己控制位置，可以刚好覆盖显示图表的canvas），在这个div里用table的形式展示数据
2. toolbox里添加一个自定义的功能 (http://echarts.baidu.com/doc/example/toolbox.html)，在这个自定义功能的onclick属性里控制  div显示和隐藏

希望能帮到你。

**Comment by kener** [comment]
![dataview](https://cloud.githubusercontent.com/assets/1711855/6500889/7611b48c-c34c-11e4-803c-9dd1736f20e7.png)

**Comment by chj-damon** [comment]
@kener 目前这个textarea无法滚动，当表格数据很多的时候，应该怎么配置？
