### ISSUE TITLE
漏斗图宽度问题

### ISSUE THREAD

**Issue by TooBug** [ecomfe/echarts#1317]
比如这个[demo](http://echarts.baidu.com/doc/example/funnel1.html)，将第一个图最大的数字从100变成200，宽度就会超出预定宽度。

![image](https://cloud.githubusercontent.com/assets/1243593/6476774/37887e00-c255-11e4-80dd-824bc4b11dc3.png)

**Comment by kener** [comment]
漏斗图min max设置，见文档

**Comment by TooBug** [comment]
多谢指点，解决了。我自己没仔细看这里的文档，以为会根据最大最小值自动适应……
