### ISSUE TITLE
力导向图问题

### ISSUE THREAD

**Issue by sarsshitou** [ecomfe/echarts#1319]
http://echarts.baidu.com/doc/example/webkit-dep.html
隐藏掉一种类型，比如other再点击让他在图上显示
中间图直接没有了 左上角有一小块东西
如图：
![image](https://cloud.githubusercontent.com/assets/7335763/6478673/f3f3f9ee-c272-11e4-8375-ab2537837e6b.png)

**Comment by pissang** [comment]
嗯好像新版本在 useWorker 的时候有 bug，谢谢指出，可以先关闭 useWorker 选项
