### ISSUE TITLE
横纵坐标轴互换并且option设置dataZoom:{show:true}时报错

### ISSUE THREAD

**Issue by fqtrnt** [ecomfe/echarts#1320]
在横坐标轴互换的柱状图里，给option设定属性dataZoom:{show:true}时，柱状图不能显示，控制台有报错提示。
具体例子：
http://echarts.baidu.com/doc/example/bar3.html ， 在option里加入dataZoom:{show:true}，点刷新按钮后，柱状图不能显示。改为false或者把yAxis和xAxis的值互换，再刷新状态图可以显示。

在老的版本（2.1.10）里是正常的。
请确认。
使用的版本是2.2.0

**Comment by kener** [comment]
bug，谢谢反馈
