### ISSUE TITLE
能否增加一个查看大图或者全屏查看的工具效果

### ISSUE THREAD

**Issue by web5** [ecomfe/echarts#1322]
业务中，有需要点击查看大图的场景，能否把这个功能直接添加的工具栏中

**Comment by kener** [comment]
好想法，可以做一个工具箱的自定义扩展功能试试

**Comment by web5** [comment]
工具箱的自定义拓展，是你们已经有了自定义的接口，我们去写拓展，还是需要等你写好自定义接口？

**Comment by kener** [comment]
http://echarts.baidu.com/doc/example/toolbox.html 支持自定义扩展，功能得自己实现，也不是什么难事，再渲染一个就好

**Comment by web5** [comment]
ok,了解

**Comment by ready360go** [comment]
@kener  这个是2.0的demo， 3.0的不行哦   3.0不支持自定义toolbox的吧
