### ISSUE TITLE
中国主要城市地图缺安徽巢湖市，怎么补上呢？

### ISSUE THREAD

**Issue by dataliven** [ecomfe/echarts#1328]
如题，请教一下制作方法或指示一下哪里可下载，谢谢！

**Comment by iyaozhen** [comment]
这里？http://geojson.io/#map=2/20.0/0.0

**Comment by hushicai** [comment]
地图数据现在可以在这里获取：http://ecomfe.github.io/echarts-map-tool/

巢湖市在合肥市中。
