### ISSUE TITLE
关于地图中数值的展示问题

### ISSUE THREAD

**Issue by lingqi82** [ecomfe/echarts#1330]
使用默认的全国地图，按照例子只能展示出各省市名称，使用 itemstyle 中的 label标签只能展现出省的名称，无法展现出对应的数值，只有鼠标放上去时才有数值在悬浮框中出现，请问使用什么参数才能展现出地图中各省的赋值数据？

**Comment by lingqi82** [comment]
另外还有一般饼图的各类目对应的数值，也是和地图一样，用什么参数可以让其默认就显示出来，就像EXCEL中一样。柱状图可以用 itemstyle 中的 label标签展示出数值，但其他的图貌似都没办法

**Comment by iyaozhen** [comment]
label中显示的值也可以格式化输出的：

![image](https://cloud.githubusercontent.com/assets/4395553/6525842/a7d926f4-c445-11e4-907c-68325c8a2671.png)

http://echarts.baidu.com/doc/example/map.html
