### ISSUE TITLE
echarts地图模拟点击问题

### ISSUE THREAD

**Issue by ahxukai** [ecomfe/echarts#1331]
最近在做一个实时数据交互界面，大概是从后台向前台推一段数据，例如某个市的数据，然后地图上立马在该市的标记点上悬浮出一个悬浮框，上面展现出从后台获取的数据，我一开始准备自己做一个悬浮框悬浮到该标记点上，无奈我做的悬浮框无法定位到该市的标记点，所以放弃了，现在想利用echarts本身自带的标记，也就是说数据一来我立刻根据市名生成一个标记正好就定位到了该市，但是此时我无法显示出悬浮框，我的想法是在我点击该标记时会跳出悬浮框，但是现在的规则是不能用鼠标操作，所以我想问一下有没有什么方式可以模拟的点击一下标记点，就像html的button可以通过js模拟点击一样不需要用到鼠标

**Comment by pissang** [comment]
如果需要定位到该市的标记点可以试试 [myChart.chart.map.getPosByGeo](http://echarts.baidu.com/doc/doc.html#MapInterface) 方法

**Comment by ahxukai** [comment]
试过了，解决了，谢谢
