### ISSUE TITLE
使用esl加载echarts出现一些关联文件请求404

### ISSUE THREAD

**Issue by iyaozhen** [ecomfe/echarts#1332]
图表能正常出来，但js有报错，一些关联文件404

![baiduhi_2015-3-6_20-49-0](https://cloud.githubusercontent.com/assets/4395553/6525595/487cea40-c442-11e4-9119-23f64badbf3b.png)

相关代码：

![baiduhi_2015-3-6_20-50-5](https://cloud.githubusercontent.com/assets/4395553/6525607/718c7edc-c442-11e4-836c-da83d294f05d.png)

环境：win7; chrome 41; echarts 2.2; esl 2.04

IE上好像没发现这个问题。

**Comment by pissang** [comment]
如果是加载打包后的文件，因为 `force` 中和 `line` 中所依赖的模块都在 `echarts` 文件中，所以需要先把 `echarts` 文件中的所有模块先加载进来，建议按照文档中模块化单文件引入的方式。
```
   <!-- 这里通过标签引入加载所有 echarts 的基础模块 -->
    <script src="./js/echarts.js"></script>
   <!-- 配置一下后面按需加载的图表模块加载的查找路径 -->
    require.config({
            paths: {
                echarts: './js/dist'
            }
        });
```

**Comment by iyaozhen** [comment]
不知道原生esl引入和echarts.js中内置的esl加载器加载方式有什么区别。

更多的代码：
![image](https://cloud.githubusercontent.com/assets/4395553/6549378/fb6e0718-c64c-11e4-81d4-a5d6063cf7a8.png)

这种方式和上面的效果一样，图表显示没有任何问题，但控制台js文件报错（404）。
![image](https://cloud.githubusercontent.com/assets/4395553/6549384/149eea7c-c64d-11e4-977b-3bec06ba2b41.png)

按照官方的模块化单文件引入：
![image](https://cloud.githubusercontent.com/assets/4395553/6549419/8dd4d730-c64d-11e4-8e01-37a93751a572.png)

图表不能正确显示，echarts主文件找不到。
![image](https://cloud.githubusercontent.com/assets/4395553/6549408/6a79a266-c64d-11e4-9482-0ccae0d5c8d1.png)

**Comment by iyaozhen** [comment]
引入echarts.js就已经有了esl环境，就没必要再引入esl了。

我再需要加入其它符合AMD规范的模块，直接require进来就行。

Over

**Comment by pissang** [comment]
赞
