### ISSUE TITLE
ZTE QT Q802T  webview中 出现数字重影

### ISSUE THREAD

**Issue by randyliu77** [ecomfe/echarts#1333]
![cache_46bce72b4d4c5a33](https://cloud.githubusercontent.com/assets/7233814/6539776/257aa36c-c4b9-11e4-87a6-720596112de1.jpg)
安卓4.3版本。

估计是对此款安卓手机的webkit浏览器的支持有问题。能否麻烦看一下？

此前有另外一位用户也报告过类似情况。

**Comment by Garrylin** [comment]
没错，我也遇到了，捉急ing

**Comment by randyliu77** [comment]
金立的一款手机中也出现类似的情况，请问何时能修复？
