### ISSUE TITLE
折线图的点击事件

### ISSUE THREAD

**Issue by wind-direction** [ecomfe/echarts#1335]
你好，我想问下，如何个折线图增加点击事件呢？不是单个点，而是整条线。就是说点击线中非节点的地方，触发事件，同时画一条线。。到是有一个markline，但是无法跟线的点击事件绑定。
我想问下，echarts支持线本身的点击事件么，万谢！

**Comment by longFeiLi** [comment]
TOOLTIP_HOVER    

function tooltipHover(param) {
    var index = param.dataIndex;
    var data = param.data;
    var xData = this.component.xAxis.option.xAxis[0].data;
    var name = this.component.xAxis.option.series[0].name;
    vParam = {};
    vParam.dataIndex=index;
    vParam.event = param.event;
    vParam.name = xData[index];
    vParam.value = 0;
    vParam.seriesName = name;
    vParam.data = data;
    
};

你去试一下这个事件，或许能够帮助你。

**Comment by wind-direction** [comment]
此方法不能达到产品的需求。不过还是谢谢了。
另外，我想再问个问题，如何才能阻止双击触发单击事件呢？

**Comment by longFeiLi** [comment]
没办法阻止哦。我是没有办法了。之前也是纠结了很久、

**Comment by wind-direction** [comment]
(⊙﹏⊙)b。。。。。这样不好。。

**Comment by zjjott** [comment]
Hi，你好，我用了TOOLTIP_HOVER这个事件，但是event.which在滚轮滚动的时候也是1，这是为什么呢？

**Comment by hellobq** [comment]
why close? 有没有线点击事件呢
