### ISSUE TITLE
折线图问题

### ISSUE THREAD

**Issue by ahxukai** [ecomfe/echarts#1336]
折线图的x轴坐标和y轴坐标的坐标线都有配置可以隐藏掉，怎么跟x轴和y轴面对面的两条线隐藏不掉，请问在哪里配置，翻了好久翻不到配置项在哪里
![2015-03-09_105731](https://cloud.githubusercontent.com/assets/9835434/6549307/c3899d54-c64b-11e4-8e53-cbe82d3fd1c3.png)

**Comment by longFeiLi** [comment]
option.yAxis[0].splitLine.show: false"

**Comment by ahxukai** [comment]
我不是说y轴和x轴坐标轴，而是与x，y面对面的两条边框线隐藏不掉，丑死了

**Comment by longFeiLi** [comment]
http://tushuo.baidu.com/   自己调试去吧。

**Comment by i6ma** [comment]
```
option = {
    grid: {
        borderWidth: 9,
        borderColor: '#999'
    },
    xAxis: {
        splitLine: {
            lineStyle: {
                width: 2,
                color: '#222'
            }
        },
        type: 'category', boundaryGap: false, data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    },
    yAxis: {type: 'value'},
    legend: {data: ['最高气温', '最低气温']},
    series: [{name: '最低气温', type: 'line', data: [1, -2, 2, 5, 3, 2, 0]}]
};
```

**Comment by ahxukai** [comment]
搞定了，神助攻，再问一个渲染出来的图形和父容器之间的空白好大，会让图形变得很小，留了好多空白位置，地图和饼图都可以调节大小解决，折线图和柱状图怎么破

**Comment by longFeiLi** [comment]
http://echarts.baidu.com/doc/doc.html#Grid   看下是不是这个。用x  y
