### ISSUE TITLE
柱状图密集一些gap不太一样的问题

### ISSUE THREAD

**Issue by signals2** [ecomfe/echarts#1337]
bar图在柱子密集一些的情况下, 比较容易看到, 有的是有间隔, 有的已经粘连在一起了, 同样的情况K线图没有这个问题, 是不是柱图的间距和宽度计算有点问题?

**Comment by IlovedJoey** [comment]
同问。
http://echarts.baidu.com/doc/example/dataZoom.html 
还有转成柱状图时，密集情况下，有些柱子底部是与X轴紧挨的，有些有一两个像素的空隙.

**Comment by pissang** [comment]
嗯好像是有这个问题，我们跟进下
