### ISSUE TITLE
【新图表】增加TreeMap类型，请大家讨论需求

### ISSUE THREAD

**Issue by loutongbing** [ecomfe/echarts#1341]
数据表示结构
TreeMap根据树的每个节点的值的大小递归地把某个区域切分为对应大小的小矩形。
例如下面的图例：
![gradient_grouped_treemap](https://cloud.githubusercontent.com/assets/5877766/6570038/c0f7ff5c-c72e-11e4-9400-621cdcc04d60.jpg)
![afa7cf270a995758974bb641dfb39692_r](https://cloud.githubusercontent.com/assets/5877766/6570226/c522f3fe-c731-11e4-8e51-23f017ffb869.jpg)
所需的配置项就是一个tree的数据结构，暂时支持三级。

点击：进入第二级并查看第三级。
hover：展示本节点详细信息的tip。

还有什么需求请留言。

**Comment by pissang** [comment]
treemap 的 Layout 部分代码单独拎出来放在 layout 目录下吧。

数据结构的表示下面两个选哪个

```javascript
nodes: [
    {
        name: '',
        value: 10,
        children: []
    }
]
```

或者所有节点是一个平坦的数组，通过 parent 属性指定层级关系

```javascript
nodes: [
    {
        name: 'a',
        value: 10
    },
    {
        name: 'b',
        value: 5,
        parent: 'a'
    }
]
```

**Comment by pissang** [comment]
还有点击数据下钻的交互上，应该是内置这个交互逻辑呢，还是通过触发事件让用户重新 setOption 更新数据。如果是内置的话是不是还需要一个面包屑导航

**Comment by kener** [comment]
就一层，点击下钻的逻辑不应该内置。
建议用children，@pissang 看看是否未来可以做什么动态类型切换？数据可视标准化

**Comment by pissang** [comment]
以后会新添加数据结构一样的树图，因为 Tree 都可以用 Graph 表示，所以可以单向切换到 Force 和 Chord。

**Comment by quillblue** [comment]
建议用Children的格式，比较接近数据结构里树和图的原生格式，可以在TreeMap-力导向-弦图之间切换比较方便。
