### ISSUE TITLE
Trellis Bar Chart

### ISSUE THREAD

**Issue by wlindner** [ecomfe/echarts#1342]
Does ECharts support Trellis Bar Charts? Here's an example: http://buffalobi.com/qlikview/qlikview-trellis-chart/. If ECharts does not support it, that would be a great improvement.

> If you search Google for the definition of a Trellis Chart, it is defined as the layout of smaller charts in a grid with consistent format.

I was able to create a Trellis Pie Chart: http://codepen.io/wlindner/pen/NPLodK

but, my Trellis Bar Chart just combines into one chart: http://codepen.io/wlindner/pen/wBEVap?editors=001.

Is it possible to do this?

**Comment by pissang** [comment]
Only one cartesian coordinate system can exist in a single chart instance. So all line series and bar series will be combined together.

The only way to implement trellis bar charts is creating a div each cell and initialize a chart instance on it.

**Comment by wlindner** [comment]
Ok, I see. I also found this example: http://echarts.baidu.com/doc/example/bar9.html

It looks like the best approach is either what the above example does, or just create a separate div for each bar chart.

Thanks for the explanation.
