### ISSUE TITLE
力导向图只能画单方向箭头，双方向后两根线就重叠啦

### ISSUE THREAD

**Issue by onclearall** [ecomfe/echarts#1344]
能否控制成双线显示，如图
![20150311100604](https://cloud.githubusercontent.com/assets/8892555/6589179/f161ed30-c7d6-11e4-95fa-29ba90a800cb.png)
或者可以增加两点双弧线箭头

当前力导向图不能够动态添加删除节点和连线

以上问题参考过springy拓扑图和qunee拓扑图

**Comment by pissang** [comment]
谢谢建议，以后会支持曲线上加箭头，曲线可以防止双向边重叠的情况

**Comment by pissang** [comment]
直线的双向边在各自法线方向加了小段位移防止重叠，效果跟问题图示一样
