### ISSUE TITLE
如何禁止折线图上的点拖动？

### ISSUE THREAD

**Issue by kinsoo** [ecomfe/echarts#1345]
折线图上的点拖动可以拖动，拖动后“线”就断了，如下图，如何禁止拖动呢？
![echarts](https://cloud.githubusercontent.com/assets/8814342/6589783/d834e0ec-c7e0-11e4-806b-c7b2d2322c93.png)

**Comment by pissang** [comment]
关闭拖拽重计算特性

**Comment by zuibunan** [comment]
怎么控制拖拽范围？
