### ISSUE TITLE
Labels inside of Bars

### ISSUE THREAD

**Issue by psumstr** [ecomfe/echarts#1346]
Hi,

I would like to know if it's possible to configure the labels of a bar chart to show inside of each bar as opposed to the axis. I tried using itemStyle.label, but then saw it was not available for bar charts. Is there a way to extend the chart options to allow this?

**Comment by pissang** [comment]
`itemStyle.normal.label` should work

```javascript
series: [{
    type: 'bar',
    itemStyle: {
        normal: {
            label: {
                 show: true,
                 position: 'inside'
            }
        }
    }
}]
```

**Comment by psumstr** [comment]
Thank you. The documentation made it seem as it if wasn't supported. Works great.

**Comment by psumstr** [comment]
Sorry, one last thing: Is there a way to rotate those labels 90 degrees? I want to show them in a column bar chart, and rotating them vertically gives me more space for longer labels.

**Comment by pissang** [comment]
Sorry there is no way to rotate the labels

**Comment by psumstr** [comment]
@pissang Do you have any tips on how I may be able to rotate labels inside of bars? Would it have to be a custom build of Echarts or would label rotation happen at the zrender level?

**Comment by Ovilia** [comment]
See #5309
