### ISSUE TITLE
X轴为时间类型时，可以设置不显示X轴的第一个Label和最后一个Label吗？

### ISSUE THREAD

**Issue by zhujianfeng** [ecomfe/echarts#1347]
1、当X轴为时间类型时，X轴上的时间Label都是自动计算的，但是第一个和最后一个都会顶格显示，如果不想让他们俩显示应该怎么设置？
2、我设置了boundaryGap为[0.1,0.1]，曲线两头会留白，但是X轴的首尾两个Label却没有跟着曲线向中间靠拢，仍然是顶格显示的，这个是可以设置的么？
3、当X轴为category的时候，可以设置首尾两个Label左对齐和右对齐，当X轴为time类型的时候想设置首尾Label左右对齐应该怎么设置？

谢谢

**Comment by kris-J** [comment]
遇到同样问题，求解答

**Comment by xfworld** [comment]
时间类型貌似没法控制，类目类型的可以设置区间为0，就默认显示所有的label了
