### ISSUE TITLE
官网的示例就有问题，theme丢失Y轴。。（2.2.0）

### ISSUE THREAD

**Issue by yeahe83** [ecomfe/echarts#1349]
![echart](https://cloud.githubusercontent.com/assets/9261385/6591959/2e84ae98-c802-11e4-882f-2de051d88b1d.jpg)

请直接点这个链接：
http://echarts.baidu.com/doc/example/line1.html#infographic

还有其他几个皮肤也是一样。

**Comment by Garrylin** [comment]
线图也有问题（比如y轴数据对应），虽说可能是为了放大差距，http://echarts.baidu.com/doc/example/line2.html#

**Comment by pissang** [comment]
@Garrylin 这个例子是因为开启了堆叠，@yeahe83 好像是有偶然出现 Y 轴丢失的情况。
