### ISSUE TITLE
力导向布局图series下links里面的weight问题？

### ISSUE THREAD

**Issue by samveduan** [ecomfe/echarts#1350]
大家好，请问ECharts里面力导向布局图series下links里面的weight代表什么？是不是值越大，距离就越短，表示关系越亲密？

**Comment by pissang** [comment]
是的

**Comment by R--J** [comment]
当前版本中有weight属性吗？如何设置graph中节点之间的距离？一旦点过多，图就显得特别密。

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-graph.force.edgeLength
