### ISSUE TITLE
echarts中基于BMap的map的图例用微软雅黑红色字体会出现灰色字体阴影。

### ISSUE THREAD

**Issue by xinbu** [ecomfe/echarts#1351]
在下载的Echarts2.2.0里面的代码测试。对echarts-2.2.0\extension\BMap\doc\example.js修改如下：
176行的'aqua'改为'#ff3333'，
200行的textStyle｛｝里加fontFamily:'微软雅黑'，
然后访问同目录下的example.html,图例中的“上海”会出现灰色阴影，你可以亲自试一下。
如果“上海”改成“故障”，效果更明显。lime，Orange和灰色不会出现阴影，red和Green都会出现阴影，其他颜色没测试。以上所有测试都是在背景颜色为#044161。

**Comment by i6ma** [comment]
补充一下
字体设置 `微软雅黑`，并启用字体抗锯齿渲染（默认已启用）
文字颜色 `#ff3333`，背景色 `#044161`

![887b033c489e07781b9f8c1a93f88174](https://cloud.githubusercontent.com/assets/8434901/6611622/426bf2b6-c8a9-11e4-9c72-a3ae14979dcf.PNG)
问题截图，红色文字周围有灰影


![c54c5033d6f2cabe6643ebcdeca70f57](https://cloud.githubusercontent.com/assets/8434901/6611625/5bb505aa-c8a9-11e4-8cae-26fc36f957de.PNG)
换浅色背景后（其它条件不变）问题基本消失



![cbcb77c3e420a984438860b865a31d0c](https://cloud.githubusercontent.com/assets/8434901/6611630/733a8e16-c8a9-11e4-9215-f1fd6560a4fd.JPG)
局部放大（上图下半部分）与 photoshop 模拟效果（上半部分）对比

**Comment by xinbu** [comment]
补充一点，出现阴影是在图例里的某一项没有Selected的情况下，鼠标停留在该项或划过该项
