### ISSUE TITLE
新版本不同切换有问题

### ISSUE THREAD

**Issue by sarsshitou** [ecomfe/echarts#1352]
例如折线图和柱状图的来回切换 柱状图的柱直接看不到了
悬浮可以看到当前的
http://echarts.baidu.com/doc/example/bar1.html
![image](https://cloud.githubusercontent.com/assets/7335763/6613545/b3b00b18-c8c9-11e4-9ffe-e0bf05c66625.png)
饼图漏斗图切换

**Comment by sarsshitou** [comment]
![image](https://cloud.githubusercontent.com/assets/7335763/6613577/0c5fa494-c8ca-11e4-80cd-21f77d5f848c.png)

**Comment by sarsshitou** [comment]
官网 echarts-2.2.1

**Comment by sarsshitou** [comment]
@kener

**Comment by pissang** [comment]
谢谢反馈，我们看下是什么问题
