### ISSUE TITLE
map areaStyle color填充颜色无效

### ISSUE THREAD

**Issue by Bijiabo** [ecomfe/echarts#1355]
设备：OSX 
chrome 41.0.2272.74
firefox 34.0.5
iOS 8 wkwebkit

想改变一下地图区域的灰色，包括官方示例，都无效呢，求解答，谢谢。

**Comment by huangw-t** [comment]
@Bijiabo 我也想知道怎么改默认的灰色？

**Comment by Bijiabo** [comment]
我也忘记后来有没有解决了...

**Comment by Bijiabo** [comment]
我也忘记后来有没有解决了 @huangw-t

**Comment by echoyuanliang** [comment]
我也遇到这个问题了,osx,chrome
