### ISSUE TITLE
对同一个echarts多次setOption，当某次option的series为空后，“暂无数据”的图层永远不会消失

### ISSUE THREAD

**Issue by mingbai2006** [ecomfe/echarts#1356]
操作步骤
1、初始化一个echarts对象，我的例子是折线和柱状混合图。
2、每次点击按钮，就触发ajax，将返回的数据包装成option对象，然后调用echarts对象的setOption(option, true)方法将option覆盖进去

问题：如果某次option的数据字段，也就是series为空的话，图表会显示为“暂无数据”。这时候如果下次setOption的数据字段不为空，图表能够重新显示出图表，但是上次的”暂无数据“图层并不会消失，而是以半透明的形式覆盖在图表上。

**Comment by romanticaa** [comment]
调hideLoading()方法就好了
