### ISSUE TITLE
markPoint 的悬停事件

### ISSUE THREAD

**Issue by wind-direction** [ecomfe/echarts#1357]
我想问下，echarts中，markPoint是否支持自定义的悬停事件呢？是markPoint的不是series的。。如果有的话，能否给个示例？万谢。。

**Comment by scgy5555** [comment]
你找到事件了吗？为什么关闭了问题

**Comment by wind-direction** [comment]
我所在的版本（2.0）并不支持。后来换了一种处理方式，改成了单击触发消息。

**Comment by scgy5555** [comment]
单击markPoint吗？我正好需要，能分享下吗

**Comment by wind-direction** [comment]
不是点击markPoint,而是单击线上的点
点击事件
myChart.on(ecConfig.EVENT.CLICK,function (param){
                  //todo......
});
其中的ecConfig就是echarts 开发包中，解压之后的根目录中一个配置文件config.js 
如果你用require开发的话，只需引入这个js组件即可。

**Comment by wind-direction** [comment]
我建议你直接咨询下echarts的开发团队。不知道后续的版本有没有增加这样的功能。echarts的版本升级跳动很大。

**Comment by scgy5555** [comment]
监听click是可行的，但是地图区域本身的点击也会触发
所以现在我的方案是比较地区区域的参数和markpoint的参数来判断我点的是什么
再做处理，我感觉这是很蛋疼的事

地图本身就多了很多事件 干脆加一个markpointClick不就解决问题了吗
百度的开源库果然没有一个好用的

**Comment by wind-direction** [comment]
当初我们这么做也是迫于支持事件类型太少，迫不得已。。
echarts 整体够炫，但是我觉得他们的方向有些偏了。。好在源码公开，如果有兴趣，其实可以做些拓展。
