### ISSUE TITLE
Dual Category Axis

### ISSUE THREAD

**Issue by wlindner** [ecomfe/echarts#1358]
Is it possible to create a bar chart with more than one level of category grouping?

Something like this:
![Dual Category Axis](http://peltiertech.com/wp-content/img200804/DualCategoryAxis.png)
http://peltiertech.com/chart-with-a-dual-category-axis/

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=xryk_0DRml

**Comment by vikramrc** [comment]
Hi There,

Thanks for posting an answer. However, I cannot open this link. Results in an empty page (without a chart).

Could you please post a fresh link here again ?

best regards,
Vikram
