### ISSUE TITLE
请问echart怎么实现 响应式缩放啊？

### ISSUE THREAD

**Issue by qiter** [ecomfe/echarts#1364]
是有参数设置嘛？

**Comment by liminjun** [comment]
@qiter 从目前使用的情况来看，还没有地方配置。最多自己监听resize然后改echart容器div不同的高度和宽度。

**Comment by psycoHo** [comment]
式设计缺陷么?只能设置尺寸吗？

**Comment by qiter** [comment]
谢谢 @liminjun 的回答。。。我已经搞定了。
