### ISSUE TITLE
echarts.js 现在350k 还能不能再小点啊。我只想用常规的图表？

### ISSUE THREAD

**Issue by qiter** [ecomfe/echarts#1365]
如题。其他图表文件可以选择加载。
但主文件感觉还是有点大。主文件echarts.js能不能被拆分啊？

**Comment by stanleyxu2005** [comment]
我在ide里面打开source/echarts-all.js，结果没有响应了。看了一下，接近2mb...

**Comment by pissang** [comment]
source 里是没压缩过的自然大了，而且这个不是源代码，里面还带有压缩后的地图数据。

不过文件体积的优化是下一步要做的。

**Comment by Z-starts** [comment]
通过在线构建工具，只构建折线图都有压缩后都390kb+，希望大神能继续压缩代码，加油！！！

**Comment by stanleyxu2005** [comment]
他们是鼓励用他的AMD模块做懒汉加载的。如果想一次加载，可根据自己的需求用z-optimizer做个性化打包，直接加载是达不到上线标准的，压缩之后也近1MB了...
