### ISSUE TITLE
怎样设置图在面板中的位置（怎样让图铺满当前div）

### ISSUE THREAD

**Issue by changjiasheng** [ecomfe/echarts#1367]
![screenshot from 2015-03-13 16 19 55](https://cloud.githubusercontent.com/assets/3156889/6635076/878ca496-c99c-11e4-8256-2ef40624faad.png)

**Comment by vipjeffreylee** [comment]
grid:{x:20,y:20,x2:20,y2:20}
试试，x y是左上角坐标，x2 y2是右下角坐标（分别是距离边缘的数值）
