### ISSUE TITLE
【紧急】echarts折线图 数据抽稀精度缺失问题

### ISSUE THREAD

**Issue by moonshine42** [ecomfe/echarts#1370]
相同的数据，Echarts图表绘制的有效数据点数明显比AmCharts少得多，容易造成该时间点数据为0的误解，影响图标数据的可读性。。。。
这个问题影响度还是比较广的，麻烦尽快解决下，客户对数据要求很高，不能有太多偏差
https://cloud.githubusercontent.com/assets/8499671/6638744/027ef84e-c9c4-11e4-854c-1144cbd1da62.png

**Comment by moonshine42** [comment]
![image](https://cloud.githubusercontent.com/assets/8499671/6684653/5b8e8280-ccce-11e4-928c-98f8eec63adb.png)
![image](https://cloud.githubusercontent.com/assets/8499671/6684661/64e4d582-ccce-11e4-8ac7-3d3fd42ec460.png)
同样一组一模一样的数据，amcharts跟Echarts绘制出来的精度差别有点大，有些重要点被过滤掉了，严重影响数据可视化。。。希望能尽快得到支持，客户对数据要求蛮严格的。。。

**Comment by pissang** [comment]
嗯，我们接下去会对数据抽希算法做调整。

**Comment by moonshine42** [comment]
能否有个大概的时间点哈？我们系统3月底就要上线对外开给客户，客户量比较多，比较紧急哦，希望你们能把这个优先级调高哈~

**Comment by pissang** [comment]
这个问题我们会在这几天就提交更新，如果很急的话可以在我们提交代码后从源代码构建。

**Comment by moonshine42** [comment]
感谢支持~ : )  +1:

**Comment by moonshine42** [comment]
嗯 ，可以构建了跟我说下哈~

**Comment by pissang** [comment]
line 添加配置项 dataFilter，支持 `'min'`, `'max'`, `'average'`, `'nearst'` 选项，默认为 `'nearest'`。除了这四个默认的 filter 也可以是自定义函数。
