### ISSUE TITLE
svg VS canvas

### ISSUE THREAD

**Issue by candy20094369** [ecomfe/echarts#1371]
当初选择使用canvas来做的初衷是什么呢？为什么没有选择用SVG做？大数据的支持？那对于canvas依赖分辨率和不支持事件处理是不是造成了比较大的困难，对单个图形操作会很困难

**Comment by pissang** [comment]
还好吧也没那么困难，最后带来的收益是可以更灵活的加入自己想加的东西，比如尾迹特效和大规模散点图，相信就这两点对 SVG 就很困难了，在开发 ECharts-X 分支的时候更让我们坚信当初选择 Canvas 是一个很明智的决定，因为 Canvas 和 WebGL 更加契合，举个简单的例子，Canvas 是可以直接用作 WebGL 中的纹理的，ECharts-X 中我们就是用这种方式把地图的底图画到 Canvas 上然后当做纹理贴到地球的圆上。
