### ISSUE TITLE
建议去掉 http://echarts.baidu.com/ 这个域名

### ISSUE THREAD

**Issue by nikogu** [ecomfe/echarts#1374]
虽然是百度出来的产品，不过既然作为这么大的开源框架，还是不要挂到百度下面比较好，BAT其它团队想用都有所顾虑。

既然是在github上，那就是源于百度，发展与世界，不要当做百度的产品比较好

**Comment by iamweilee** [comment]
"BAT其它团队想用都有所顾虑。"
这只能说明他们的心态不够开放，如此不用也罢。。
