### ISSUE TITLE
百度迁徙2015为什么在自己电脑上不能显示呢？

### ISSUE THREAD

**Issue by lechart** [ecomfe/echarts#1376]
http://echarts.baidu.com/doc/example/map22.html

就是这张地图，下载Echart到自己电脑后打开就只能显示底图了？求指点这是什么原因呢？

**Comment by pissang** [comment]
看一下报了什么错？

**Comment by lechart** [comment]
谢谢大佬回复！

接下来我的问题可能不够专业，多谢耐心指点^^

其他地图我可以直接在网页端或者下载到自己电脑之后直接在左侧更改代码中相关内容，右侧图形会相应改变，比如这张map11的地图：http://echarts.baidu.com/doc/example/map11.html，可以成功进行修改。

但是map22需要读入一个叫migration.json的数据文件，所以我在本地电脑上将这个文件进行了修改，但是并没有用，而且看起来下载到本地之后Echarts并没有成功读入这个文件，因为打开后只能显示底图，不知道应该如何操作进行修改? echarts的文件夹我放在电脑桌面上。

**Comment by pissang** [comment]
google 搜索报的是什么错误。

**Comment by lechart** [comment]
求看：


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="ECharts">
    <meta name="author" content="kener.linfeng@gmail.com">
    <title>ECharts · Example</title>

    <link rel="shortcut icon" href="../asset/ico/favicon.png">

    <link href="../asset/css/font-awesome.min.css" rel="stylesheet">
    <link href="../asset/css/bootstrap.css" rel="stylesheet">
    <link href="../asset/css/carousel.css" rel="stylesheet">
    <link href="../asset/css/echartsHome.css" rel="stylesheet">
    
    

    <script src="./www/js/echarts.js"></script>
    <script src="../asset/js/codemirror.js"></script>
    <script src="../asset/js/javascript.js"></script>

    <link href="../asset/css/codemirror.css" rel="stylesheet">
    <link href="../asset/css/monokai.css" rel="stylesheet">

    <style type="text/css">
        .CodeMirror {
            height: 550px;
        }
    </style>
</head>

<body>
    
    <div class="navbar navbar-default navbar-fixed-top" role="navigation" id="head"></div>


    <div class="container-fluid">
        <div class="row-fluid example">
            <div id="sidebar-code" class="col-md-4">
                <div class="well sidebar-nav">
                    <div class="nav-header"><a href="#" onclick="autoResize()" class="glyphicon glyphicon-resize-full" id ="icon-resize" ></a>option</div>
                    <textarea id="code" name="code">

option = {
    backgroundColor: '#1b1b1b',
    title : {
        text: '百度迁徙2015',
        x:'center',
        y:'top',
        textStyle: {
            color: 'white'
        }
    },
    legend: {
        show: true,
        selected: {},
        x: 'left',
        orient: 'vertical',
        textStyle: {
            color: 'white'
        },
        data: []
    },
    series : [{
        name: "Migration",
        type: 'map',
        mapType: 'china',

        itemStyle: {
            normal: {
                borderColor:'rgba(100,149,237,0.2)',
                borderWidth:0.5,
                areaStyle: {
                    color: '#1b1b1b'
                }
            }
        },
        data: [{}],
        hoverable: false,
        clickable: false,
        roam: true,
        markLine: {
            effect: {
                color: 'rgba(204, 246, 255, 0.09)',
                show: true,
                period: 40
            },
            bundling: {
                enable: true
            },
            large: true,
            smooth: true,
            smoothness: 0.1,
            symbol: ['none', 'none'],
            itemStyle: {
                normal: {
                    lineStyle: {
                        color: 'rgba(2, 166, 253, 0.05)',
                        type: 'solid',
                        width: 0.5,
                        opacity: 0.2
                    }
                }
            },
            data: []
        },
        markPoint: {
            symbol: 'circle',
            symbolSize: 1.5,
            itemStyle: {
                normal: {
                    color: 'rgba(255, 0, 0, 0.5)'
                }   
            },
            data: []
        }
    }]
};

var geoCoord = {省略。。。};

function getGeoCoord (name) {
    var city = name.split('_').pop();
    var coord = geoCoord[city];
    return coord;
}

$.ajax({
    url: 'data/migration.json',
    dataType: 'json',
    success: function(data) {
        option.series[0].markLine.data = data.allLine.sort(function (a, b) {
            return b.num - a.num
        }).slice(0, 3000).map(function (line) {
            return [{
                geoCoord: getGeoCoord(line.start)   
            }, {
                geoCoord: getGeoCoord(line.end)
            }]
        });

        option.series[0].markPoint.data = data.topCityOut.map(function (point) {
            return {
                geoCoord: getGeoCoord(point.name)
            }
        });
        myChart.setOption(option);
    }
});
                    </textarea>
              </div>
            </div>
            <div id="graphic" class="col-md-8">
                <div id="main" class="main" style="height: 530px;"></div>
                <div>
                    <button type="button" class="btn btn-sm btn-success" onclick="refresh(true)">刷 新</button>
                    <span class="text-primary">切换主题</span>
                    <select id="theme-select"></select>

                    <span id='wrong-message' style="color:red"></span>
                </div>
            </div>
        </div>
        
        </div>

    <footer id="footer"></footer>
    
    
    <script src="../asset/js/jquery.min.js"></script>
    <script type="text/javascript" src="../asset/js/echartsHome.js"></script>
    <script src="../asset/js/bootstrap.min.js"></script>
    <script src="../asset/js/echartsExample.js"></script>
</body>
</html>

**Comment by lechart** [comment]
没有找到报错，但是似乎文件没有正确被读，求方案TAT

**Comment by lechart** [comment]
问题解决了！需要把数据放到服务器上才能正确读取。
