### ISSUE TITLE
使用时间型X轴后，tooltip设置为axis触发，图表显示bug

### ISSUE THREAD

**Issue by zhujianfeng** [ecomfe/echarts#1378]
将官网文档中这个例子的tooltip trigger改成axis后，tooltip显示如下：
![echartstooltip](https://cloud.githubusercontent.com/assets/2062804/6665215/db31fb06-cc11-11e4-97b5-646f26a5eb4f.png)

预期tooltip的线应该是垂直于X轴的，但是图中确垂直于Y轴

**Comment by babyforward** [comment]
我也遇到了这个问题，不知道肿么解决

**Comment by xieaolin** [comment]
同问+1

**Comment by parkghost** [comment]
+1

**Comment by cityhunterok** [comment]
+1

**Comment by cityhunterok** [comment]
这个问题怎么解决呢？
