### ISSUE TITLE
在大分辨率下渲染慢

### ISSUE THREAD

**Issue by delphidoc** [ecomfe/echarts#1379]
最近我们同事在超高分辨率下（分辨率11520*4320，浏览器为最新火狐）对EChart做过测试，存在严重的性能问题（当然有很大程度是浏览器本身渲染的问题）；虽然这么大分辨率有些极端，但是现在4K显示器越来越普及，EChart是否考虑对超大分辨率做一些相关的优化。

**Comment by pissang** [comment]
15-inch retina 屏幕下就是以 2880 x 1800 的分辨率渲染，超高分辨率下吃紧的主要是显卡，如果显卡性能可以，4K 显示器应该也不会很卡，至于优化我们能做的只是把 viewport 的分辨率降低。
