### ISSUE TITLE
echart 自定义toolbox的item大小明显和不原生的匹配，明显小一圈，而且没有api可以调整

### ISSUE THREAD

**Issue by xuanwubing** [ecomfe/echarts#1384]
详见官网给出的事例
![image](https://cloud.githubusercontent.com/assets/10760439/6701707/517940d6-cd5b-11e4-8e45-42f28ce70f6a.png)

**Comment by hushicai** [comment]
自定义图标可以外部修整后再传入，比如图片四周不要留白，那么大小就会一致。
