### ISSUE TITLE
能不能设置默认字体

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1391]
我只找到`myChart.setOption`里面可以对不同的组件设置字体。但我优先使用web字体的话。在字体加载完成之前，会用默认的字体`fontFamily: 'Arial, Verdana, sans-serif',`个人感觉有点丑。所以我在看是不是能够在最开始的什么地方把`fontFamily`给重写一下。

有这样的方法吗？或者能不能考虑加入一下呢？

**Comment by longFeiLi** [comment]
用样式试一下、、我知道是可以改变字体大小滴。、

**Comment by stanleyxu2005** [comment]
@longFeiLi 我找到echarts-optimizer，然后自己把改动过的config.js编译进去了。一了百了。

**Comment by stanleyxu2005** [comment]
知道了，可以在初始化的时候，把theme object替换掉的。
