### ISSUE TITLE
ECharts可在windows程序中使用吗？

### ISSUE THREAD

**Issue by wuwencheng** [ecomfe/echarts#1392]
ECharts很炫很酷，但是作为一个纯javascript开发的图形库，除了在浏览器内运行外，是否有办法可在windows窗体程序中运行？如果可行，ECharts应用范围将扩大很多，要知道windows窗体程序的图形库都很丑。如果ECharts支持windows桌面程序开发，那么我们就可以使用visual studio进行开发了。

**Comment by muzuiget** [comment]
嵌入浏览器控件就行了，WebView 什么的。

**Comment by 823844596** [comment]
echarts通过webview加载，有时候折线图或者时钟图绘制不出来，或者时钟图出现两个指针。有解决办法嘛？
