### ISSUE TITLE
external zoom options

### ISSUE THREAD

**Issue by mg1075** [ecomfe/echarts#1397]
In Google's stock chart, there are *zoom options* for a particular range of time. 

Does echarts have an example using these external custom zoom options?

It's a fairly common scenario for any type of stock chart implementation.

![image](https://cloud.githubusercontent.com/assets/2031435/6757911/aa653a12-cf02-11e4-81dd-c7d002de6a84.png)

https://www.google.com/finance?q=NASDAQ%3ABIDU&ei=U2EMVZD3HOHwsQelnoHwAw

**Comment by pissang** [comment]
Method  `myChart.component.dataZoom.absoluteZoom` is for setting the zoom by hand.

More detail in the doc http://echarts.baidu.com/doc/doc-en.html#DataZoomInterface
