### ISSUE TITLE
力导向图节点之间的边(link) 如何在上面显示字符串

### ISSUE THREAD

**Issue by xxandtiaozi** [ecomfe/echarts#1399]
![image](https://cloud.githubusercontent.com/assets/10328400/6772682/73060252-d13e-11e4-8d3b-a9076d403b89.png)
这个节点之间的线上面显示字符串，试过了官网很多api都找不到方法，网上搜到的加了这个text和textPisition属性就可以了，但是官网api里没有，
![image](https://cloud.githubusercontent.com/assets/10328400/6772687/834002ee-d13e-11e4-8baf-77cd6985ff62.png)
请问不用这个属性用官网api提供的属性可以吗？困扰很久了，非常感谢！！如果无法实现，也请告知一下

**Comment by pissang** [comment]
抱歉连线无法显示文字

**Comment by xxandtiaozi** [comment]
@pissang 但是加了text和textPosition属性就可以啊，api里没有这个属性，这是为什么呢，麻烦了

**Comment by pissang** [comment]
嗯，但是这不能算是标准的 label 配置。原本是不打算支持边线上加标签这个功能的。

**Comment by xxandtiaozi** [comment]
@pissang 好的，谢谢了，只能找别的办法了

**Comment by kella591** [comment]
求问楼主有没有找到别的方法……

**Comment by tiaozi1218** [comment]
@kella591 ，上面说的那种不标准的配置就是最终解决办法，没有别的办法

**Comment by gluo1130** [comment]
@pissang @Ovilia 
https://www.echartsjs.com/examples/editor.html?c=graph-simple
