### ISSUE TITLE
如何通过dom对象获取echarts对象

### ISSUE THREAD

**Issue by chenli0906** [ecomfe/echarts#1400]
有init函数可以通过dom生成echarts对象，但是我想通过dom对象获取绑定在上面的echarts对象，请问如何获取？谢谢！

**Comment by pissang** [comment]
目前没有直接的方法，可以
```javarscript
echarts.getInstanceById(dom.getAttribute('_echarts_instance_'));
```

**Comment by chenli0906** [comment]
@pissang 还是不行，我是在不知道echarts对象的情况下去获取的，所以echarts.getInstanceById这个方法返回不了对象

**Comment by pissang** [comment]
echarts 是一个全局的，或者 require('echarts') 就能得到的命名空间。

**Comment by chenli0906** [comment]
@pissang 确实可行，没想到还有个隐藏属性_echarts_instance_，多谢啦！
