### ISSUE TITLE
图表上的默认文字（提示信息）是否支持国际化？

### ISSUE THREAD

**Issue by Anne623** [ecomfe/echarts#1404]
在Echarts 图表中，默认文字（比如tool box的Restore 提示文字 ```还原```）是否支持国际化，比如切换到英文界面后，ECharts图表中默认文字提示信息统一都是英文。

现在的做法是使用title参数修改需要展示的内容，但这个需要一个一个去修改，也就是说每个图形的title都要修改，容易出现不统一的文字。

**Comment by xieqingxiao** [comment]
同 https://github.com/ecomfe/echarts/issues/1171
