### ISSUE TITLE
color 模块不存在

### ISSUE THREAD

**Issue by highsea** [ecomfe/echarts#1405]
> 使用中发现 color 模块不存在 报错； **require.config** 配置是正确的，其他模块都能用

    Uncaught Error: [MODULE_MISS]"zrender/tool/color" is not exists!

>  加载：

    var zrColor = require('zrender/src/tool/color');

**Comment by longFeiLi** [comment]
不是应该这样引用么。var color = require('zrender/tool/color');

**Comment by highsea** [comment]
这个…… 也报错，上面的 src 是我画蛇添足加上的，

    var color = require('zrender/tool/color');

后来索性不要  **彩虹色** 了，没用这个模块 0.0

**Comment by longFeiLi** [comment]
那你就引用下zrender

**Comment by highsea** [comment]
^_^ 三克油啦
