### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by Rykka** [ecomfe/echarts#1407]
How to use it in webpack? Is there a npm module of echarts??

**Comment by pissang** [comment]
We put it on the bower

**Comment by knightli** [comment]
+1

**Comment by Rykka** [comment]
@pissang  when using in bower, I found that I can not use it by module, I can only import the whole file `echarts-all`

**Comment by pissang** [comment]
`echarts.js` and all chart modules in the chart folder are also available. If you means including the modules in the `src` folder. Yes you can't use them after installing from bower because the missing of [zrender](https://github.com/ecomfe/zrender)
