### ISSUE TITLE
Timeline初始化 如何定位到指定的时间点，在线等，急

### ISSUE THREAD

**Issue by nikogu** [ecomfe/echarts#1409]
查找了所有样例和文档，都为发现初始化的时候指定当前时间点，全是从第一个时间开始的（最左侧），是否有这个功能？特来发个issue求解，在线等，急！

**Comment by dawnwords** [comment]
这个问题最后有解决么？

**Comment by redmed** [comment]
timeline属性里有个currentIndex参数，表示"当前索引位置，对应options数组，用于指定显示特定系列"。可以指定某个时间的索引。

参考API: http://echarts.baidu.com/doc/doc.html#Timeline

**Comment by nikogu** [comment]
@redmed 两回事

**Comment by nikogu** [comment]
@dawnwords 没，issue一直挂在这

**Comment by nikogu** [comment]
@redmed ok了
