### ISSUE TITLE
2.2.1版本里面的webkit-dep.html打不开

### ISSUE THREAD

**Issue by liaojie823** [ecomfe/echarts#1410]
下载2.2.1版本后，打开webkit-dep.html，发现网页中一直显示暂无数据。不知道是什么原因。我并没有改过任何东西

**Comment by liaojie823** [comment]
如图所示：
![qq 20150325122217](https://cloud.githubusercontent.com/assets/7010288/6818421/32854578-d2ea-11e4-9ad7-1a64ba07cc71.png)

**Comment by nikogu** [comment]
你可以看下控制台是否有报错，或者网络请求是否异常

**Comment by hushicai** [comment]
最新版的webkit-dep.html，我这打开是没有问题的。

如果还有问题，请贴出更详细的信息，然后重新打开这个issue。
