### ISSUE TITLE
IE8下看不到Chart

### ISSUE THREAD

**Issue by eshengsky** [ecomfe/echarts#1411]
我用IE11调成IE8兼容模式，看不到图表，官网的所有例子也一样都看不到，空白的。
没有提示脚本错误。
我是用的Bootstrap框架，官网好像也是，都针对IE9以下引用了Html5shiv和respond这2个js了。
求教如何解决？还是ECharts就不支持IE8？
貌似现在国内还是IE8市场份额最大吧。。

**Comment by nikogu** [comment]
IE8应该是可以查看官网的例子的，如：http://ecomfe.github.io/echarts/doc/example/pie1.html

或者你的意思是copy官网的例子到自己项目中看不到，在chrome中是否正常，或者ie8本身页面结构有问题，导致charts容器那部分dom没有展示出来？

**Comment by eshengsky** [comment]
再次试了下，还是看不到。
我用IE11模拟IE8访问，是直接访问官方网址的。
莫非是兼容模式的问题？请问你是IE几模拟的IE8

**Comment by eshengsky** [comment]
专门下了个IETester，在那里面模拟IE8访问是可以的。。。
貌似真是IE11的兼容模式的问题。
