### ISSUE TITLE
为什么我已经用了最新版的echarts，那报表还是不能自动伸缩？

### ISSUE THREAD

**Issue by aigh37** [ecomfe/echarts#1414]
我已经在官网下载了最新版本的echarts，2.2.1，也按着教程去做演示，但发现报表不能随着浏览器的大小来改变，但我看官网上的实例是可以随着浏览器来改变的，请问我是缺少调用了哪个js嘛？我用的代码是入门教程的。

**Comment by longFeiLi** [comment]
resize	{void}	ECharts没有绑定resize事件，显示区域大小发生改变内部并不知道，使用方可以根据自己的需求绑定关心的事件，主动调用resize达到自适应的效果，常见如window.onresize = myChart.resize。
