### ISSUE TITLE
如果能在数据透视图中传入 图标dom可能更好

### ISSUE THREAD

**Issue by greengerong** [ecomfe/echarts#1416]
在echart-all.js 17640 - 17645 将  
   
    customContent(this.option) 

变为  

    customContent(this.option, this)

全部code：

    if (typeof customContent != 'function') {
      this._textArea.value = this._optionToContent();
    } else {
      this._textArea = document.createElement('div');
     this._textArea.innerHTML = customContent(this.option, this);
    }

**Comment by hushicai** [comment]
目前还不考虑将`this`传出去。

如果你有什么特殊需求，可以描述得更清楚一些，然后重新打开这个issue。
