### ISSUE TITLE
你好，我是百度云安全的

### ISSUE THREAD

**Issue by rayrlee2013** [ecomfe/echarts#1418]
你好，我是百度云安全的，用图表的时候，工具盒中的选取框可以放大密集的数据，同时出发dataZoom事件，我想获取选取框对应的左右临界点的x值，如 单击事件中获得的 e.name的值，有方法没

**Comment by lifeforfun** [comment]
我也需要找这个回调，而且我认为dataZoom区间选择的回调的存在是理所当然的，不然只能把区间上所有数据读取出来了，这对前后端都将是很大的考验
