### ISSUE TITLE
紧急！ echarts2.0，事件绑定问题

### ISSUE THREAD

**Issue by Kuroky360** [ecomfe/echarts#1420]
2个echarts图表都做了CLICK事件绑定,
当我用鼠标点击时，如何知道我点击了哪一个echarts实例呢

或者说：在进行事件绑定时候，如何传入除param之外的参数
function eConsole(param){
  //todo
}
myChart.on(ecConfig.EVENT.CLICK, eConsole);

**Comment by kuroky360** [comment]
function genFn(A,B){

return function(param){
//todo
}
}

mychart.on(ecConfig.EVENT.CLICK,genFn(A,B));

**Comment by longFeiLi** [comment]
this
