### ISSUE TITLE
Chart is not rendered correctly when browser tab is not active during loading

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#1422]
Reproducible with the latest 2.2.1 release in both Chrome and FF

Try to open this link http://ecomfe.github.io/echarts/doc/example/bar3.html#-en
and go promptly to another browser tab before chart is loaded

Go back to the tab when loaded and notice the chart looks like this: 
![image](https://cloud.githubusercontent.com/assets/561365/6884114/707b435a-d5dd-11e4-9d60-bb422aee1354.png)

Resizing the browser fixes this issue..

**Comment by pissang** [comment]
Thanks. It's a known issue. We will try to fix it in next version.

**Comment by WinnieK** [comment]
Was it fixed already?

**Comment by 100pah** [comment]
yeah, try echarts-2.2.3 please :)

**Comment by jarben** [comment]
Confirming that it's fixed now:) Thanks!
