### ISSUE TITLE
实例方法 addData    dataGrow 参数问题

### ISSUE THREAD

**Issue by wjy4124** [ecomfe/echarts#1423]
官方的例子
http://echarts.baidu.com/doc/example/dynamicLineBar.html
 把112 118原的false改为true 就不动了??

dataGrow // 是否增长数据队列长度，默认，不指定或false时移出目标数组对位数据 
试了一下 为true时 数据加不进去??

**Comment by M-smilexu** [comment]
相同问题，有解决方案吗

**Comment by hushicai** [comment]
最新版已解决
