### ISSUE TITLE
关于当前散点图的区域缩放问题

### ISSUE THREAD

**Issue by romanticaa** [ecomfe/echarts#1425]
第一次缩放没有问题，但在第一次缩放后的基础上再次框选，框选区域和实际缩放结果就会有很大的出入，经常有对着点框结果是空的，框个空的地方反而有点的情况

**Comment by romanticaa** [comment]
没人理我我自己粗略看了下代码，缩放时是根据记录所框的四角在grid中的占比，多次缩放则将这个占比累积，在_synScatterData里面，根据最初的横竖坐标起始，计算出在这个范围内的点。
乍一想好像是没啥问题，可是第一次框的区域范围又不是直接变为缩放结果的坐标起始啊，极端一点，第一次只框一个点的话，scatter1.html 那个图，我框190cm到200cm、100kg到120kg，出来的是190cm到200cm、100kg到110kg啊，这基础上再缩放当然结果就不对了。。。
虽然很想自己动手改了不过苦于水平有限，还请百度大大支援~

**Comment by pissang** [comment]
谢谢详细指出，抱歉之前没注意到这个问题，我们看下。

**Comment by ShaoClean** [comment]
> 谢谢详细指出，抱歉之前没注意到这个问题，我们看下。

你好  请问这个bug修复到哪里了 没有看到相关的版本记录
