### ISSUE TITLE
跨域加载自定义svg地图

### ISSUE THREAD

**Issue by GeeBar** [ecomfe/echarts#1427]
对于自定义的svg地图， echarts采用的是ajax动态加载的方法 
getGeoJson: function (callback) {
        $.ajax({
            url: "svg/baidu-building.svg",
            dataType: 'xml',
            success: function(xml) {
                callback(xml)
            }
        });
    }

不过我的问题是svg地图在不同的服务器上，而且暂时没有设置跨域选项；
而html5的canvas是可以支持通过img来跨域加载svg的。

所以我的问题是有没有什么途径来修改下来适配我的需求。比如修改某一个回调函数？找不到...

**Comment by pissang** [comment]
没有，用代理服务器。不明白你说的通过 img 来跨域加载 svg 是什么

**Comment by GeeBar** [comment]
@pissang  我的表达有问题。我是说img标签的src属性可以直接加载svg

**Comment by pissang** [comment]
没试过这样是否能画到 canvas 上，主要问题是这样加载的 svg 就是一个图片对象，不能获取里面更详细的层级，样式，名称信息。

**Comment by GeeBar** [comment]
@pissang 了解。你们有一个重绘渲染的过程吧。多谢
