### ISSUE TITLE
echarts如何与RequireJS兼容

### ISSUE THREAD

**Issue by chenli0906** [ecomfe/echarts#1428]
我想在项目中定义自己的模块，但是echarts.js文件中已经包含了一个模块加载器了，再使用RequireJS会有冲突，有没有办法能够同时使用RequireJS呢？因为我需要基于创建的图表再做一次模块封装，比如需要添加ajax请求来获取数据等，谢谢！

**Comment by hushicai** [comment]
高级的开发用户可以直接使用源代码进行开发。
