### ISSUE TITLE
有没有办法可提高ECharts图表的清晰度及分辨率？

### ISSUE THREAD

**Issue by wuwencheng** [ecomfe/echarts#1431]
ECharts图表类型丰富，但是生成的图表总感觉不够清晰，稍微放大一些，就锯齿感很明显。不同word、excel生成的表格，不管放大到多大，都感觉很清晰。ECharts图表如能够提高清晰度很分辨率就好了，如果没有办法，总感觉难以在商业中应用。

**Comment by wuwencheng** [comment]
在echart中如何生成无损的svg或其他高清晰度的图表？具体参数如何调整和设置？能不能给出一个具体例子，我看不少用户都有这个需求。

**Comment by pissang** [comment]
目前不行，好像是个不错的需求

**Comment by zhuligang** [comment]
过去这么久了，现在可生成矢量图了吗？
