### ISSUE TITLE
force 图 legend 的颜色应该读取 categories 的颜色

### ISSUE THREAD

**Issue by highsea** [ecomfe/echarts#1432]
发现 **categories** 设置的颜色会影响 nodes 但是改变不了 **legend**

居然左侧分类的颜色是固定的，顺序如下：

     ['#FF7F50', '#87CEFA', '#DA70D6', '#32CD32', '#6495ED', '#FF69B4', '#BA55D3', '#CD5C5C', '#FFA500', '#40E0D0', '#1E90FF', '#FF6347', '#7B68EE', '#00FA9A', '#FFD700']

> 如果  legend 的颜色应该读取 categories 的颜色那该多好！

**Comment by pissang** [comment]
category 设置颜色后 legend 取的就是 category 的颜色

**Comment by highsea** [comment]
力导向图 的不会改变

    type:'kforce',
