### ISSUE TITLE
有没有内部函数能查询经纬度？

### ISSUE THREAD

**Issue by limichange** [ecomfe/echarts#1437]
就是传一个地名，然后得到经纬度？就是在geojson里做查询的函数？

**Comment by pissang** [comment]
http://echarts.baidu.com/doc/doc.html#MapInterface

**Comment by limichange** [comment]
谢谢。

**Comment by limichange** [comment]
这已经是3年前的事了……我已经毫无记忆了

**Comment by chfw** [comment]
请参考这个项目：https://github.com/pyecharts/geo-region-coords
