### ISSUE TITLE
无数据时显示的问题

### ISSUE THREAD

**Issue by a378042176** [ecomfe/echarts#1442]
现在我需要在无数据的时候不需要效果图，因为系统的原因，无数据时加上效果太花了，只需要在图中间显示自定义的文字，比如：暂无数据，应该怎样做

**Comment by longFeiLi** [comment]
去掉动画么？  隐藏动画就好了

**Comment by a378042176** [comment]
对，不需要显示动画，但是我看noDataOption配置里没有设置无动画的选项，能不能请您给一个配置，谢谢

**Comment by pissang** [comment]
```javascript
myChart.hideLoading()
```

**Comment by longFeiLi** [comment]
那样无数据的字 也就没有咯。用hideLoading

**Comment by a378042176** [comment]
那我只能用hideLoading后 自己在层中间写个字符串了？

**Comment by longFeiLi** [comment]
看了一下代码发现也只能这样了。你可以写个div 然后隐藏 显示去吧。

**Comment by a378042176** [comment]
好的，多谢了。
