### ISSUE TITLE
eCharts 能否支持坐标轴倒转？

### ISSUE THREAD

**Issue by jayshao830413** [ecomfe/echarts#1444]
通常情况下eCharts的图表的坐标轴都是由小到大的，现在我需要这样一个场景，需要把坐标轴从大到小，也就是说比如y轴，max=-10, min=10，请问eCharts支持这样的设置嘛？

**Comment by m68115** [comment]
遇到跟 jayshao830413 一樣相似的問題,要做倒圖的效果,目前自己嘗試沒辦法由大到小!!
有沒有高手可以給一點建議.

**Comment by xvacant** [comment]
有个变通的办法，准备数据时把数值取反，x= -x，然后在坐标轴的formatter中再取反一次，如果需要的话，其他地方的formatter中也要取反。
