### ISSUE TITLE
demo地图标注markPoint值域漫游李，不在geoCoord里的城市会在地图外面冒泡

### ISSUE THREAD

**Issue by woderia** [ecomfe/echarts#1445]
demo地图标注markPoint值域漫游李，不在geoCoord里的城市会在地图外面冒泡，求解

**Comment by liminjun** [comment]
我们实际项目开发中也遇到了这个问题，我们目前解决的办法是，定义这些城市到一个不显示在地图上的位置，比如南海的最下角。理论上你应该在geoCoord中设置所有的城市对应的坐标。
