### ISSUE TITLE
如果ECharts真的不与RequireJS兼容，就在文档中，写清楚把。。。

### ISSUE THREAD

**Issue by zhump** [ecomfe/echarts#1446]
之前一直用2.0版本，没有遇到RequireJS到处乱拉文件的问题，，升级过后，发现问题就跑来看看，搜了一大串，解释最清楚的在这https://github.com/ecomfe/echarts/issues/1153  说是 RequireJS循环依赖处理不行，如果真的是RequireJS的原因，希望各位大大能在ECharts官网中说明清楚要害，不然真的是耽误时间，如果有临时解决办法，也希望有大神可以赐教。ps:真的解决不了，以后官网就直接说，你们都用esl，不用考虑其他的啦。。不然以后再有坑，可真上不来了。。

**Comment by hushicai** [comment]
echarts是符合amd标准的，如果你想用requirejs作为模块加载器，可以直接用echarts/zrender源码进行开发。
