### ISSUE TITLE
requirejs下我要怎么配路径？

### ISSUE THREAD

**Issue by rayliao** [ecomfe/echarts#1452]
// 路径配置
        require.config({
            paths: {
                echarts: 'lib/echarts/src'
            }
        });
假设我的path是这样配，可是你看下`echarts.js`:

    define(function (require) {
    var ecConfig = require('./config');
    var zrUtil = require('zrender/tool/util');
    var zrEvent = require('zrender/tool/event');
    
    var self = {};
    
    var _canvasSupported = require('zrender/tool/env').canvasSupported;
    var _idBase = new Date() - 0;
    var _instances = {};    // ECharts实例map索引
    var DOM_ATTRIBUTE_KEY = '_echarts_instance_';
    
    self.version = '2.2.1';
    self.dependencies = {
        zrender: '2.0.8'
    };
    /**
     * 入口方法 
     */
    self.init = function (dom, theme) {
        var zrender = require('zrender');

我贴一部分代码，
`require('zrender/tool/util')`
`require('zrender')`
难道不觉得路径会有问题吗？
这样的话，我就需要`require('zrender/zrender')`才不会出错。
如果我改成`echarts: 'lib/echarts/src/echarts'`
那`require('zrender/tool/util')`路径就不对了。

**Comment by pissang** [comment]
使用源代码的话配置 packages
