### ISSUE TITLE
提高Y轴刻度标签的宽度

### ISSUE THREAD

**Issue by totoroii** [ecomfe/echarts#1453]
![y](https://cloud.githubusercontent.com/assets/8350374/7110387/a427a80e-e1e2-11e4-8132-035621b16c98.png)

如上图，Y轴最大的刻度标签是“163250”，但Y轴上的数据刻度因为预留的空间过小，导致数据显示不全而出现了“53250”的假象。现在想问下是否可以扩大Y轴数据标签的空间（其实就是提高刻度数值的宽度）

**Comment by pissang** [comment]
设置 grid 的 大小，或者旋转标签

**Comment by whuwb** [comment]
这种情况下，我设小grid x好像不起作用

**Comment by pissang** [comment]
grid.x应该设大
