### ISSUE TITLE
tooltip的backgroundColor等属性不起作用

### ISSUE THREAD

**Issue by nuannuan1005** [ecomfe/echarts#1454]
图表是江苏省地图，设置tooltip时，样式都不起作用
tooltip : {
        trigger: 'item',
        showContent:true,
        borderRadius:10,
        backgroundColor:'rgba(253,253,253)',
        borderWidth:10,
        borderColor:'#ccc',
        textStyle:{
        	color:'#0000ff'
        	},
        formatter: '{b}<br/>用户数：{c}'
    },

还有，title的x,y设置数值也不起作用

请问，这个要怎么设置的？

**Comment by hushicai** [comment]
我在example上设置是没有问题的。

如果还有问题，请贴出更详细的信息（比如有没有什么异常信息），以便我们排查。
