### ISSUE TITLE
Symbol 为image 的时候如何控制图片的尺寸, 不想显示正方形...

### ISSUE THREAD

**Issue by i17c** [ecomfe/echarts#1462]
如题...

**Comment by i17c** [comment]
目前自己的解决方式是 在 改变 getSymbolShape 方法, 将 var U=this.deepQuery(u,"symbolSize"); 后面增加一行 var UH=this.deepQuery(u,"symbolHeight")||U; 然后 后面L=new这个对象的时候, 本来 width:2*U, height:2*U,  改为 width:2*U,height:2*UH 至少,设置个symbolHeight可以解决这个问题了

**Comment by pissang** [comment]
2.2.2 中支持
