### ISSUE TITLE
对于采用cmd标准构建的应用来说，一次引入900+kb的脚本文件简直是个梦魇！

### ISSUE THREAD

**Issue by kevgithub** [ecomfe/echarts#1466]

**Comment by pissang** [comment]
马上就会发布在线构建工具，可以选择要打包的图表

**Comment by zhump** [comment]
@pissang  大神-。- 跪求你能不能支持一下 requirejs

**Comment by pissang** [comment]
使用新版本 esl 或者使用新版本 requirejs 都是可以加载的，或者等打包工具出来后打包一个非 AMD 模块的版本。

**Comment by vipjeffreylee** [comment]
@pissang <https://github.com/pissang>
 等待你们支持requirejs，echarts太好用了，但不支持requirejs把架构打乱了。

2015-04-16 21:09 GMT+08:00 Yi Shen <notifications@github.com>:

**Comment by kevgithub** [comment]
做一个打包工具按需打包也只是个权宜之计，cmd开发的项目通常项目都部署了自己的打包压缩工具，期待能一并原生的支持cmd

**Comment by honchy** [comment]
我重写了部分代码，是能够在CMD规范中引用，但是在分析echarts代码时感到很困惑，因为echarts代码中，重新定义了很多模块，既然是重写，为什么不更改本来的文件呢？这样的话，echarts 要翻译成为对应的CMD 就变的很复杂了。因为对于AMD，模块名称和路径其实关系不大，和直接写模块名字，但是CMD的模块是好路径息息相关的。

**Comment by luqin** [comment]
echarts内置了一个require，cmd规范的噩梦啊，完全模块化加载不了，才发现eacharts代码写的太烂了，而且发布到npm了吗？

**Comment by pissang** [comment]
可以在 http://ecomfe.github.io/echarts-builder-web/ 构建非AMD 版本的，如果使用 CMD 想要从源代码加载，只有 map.js 里异步加载的部分是不兼容的。

**Comment by luqin** [comment]
@pissang  能否提供真正的CMD支持呢？随着babelJS之类的编译工具流行，前端采用CMD规范会越来越多。

**Comment by uooo** [comment]
已经发布了webpack集成版本，详见：https://github.com/uooo/echarts
