### ISSUE TITLE
柱状图和饼图怎么转换

### ISSUE THREAD

**Issue by wujiandong** [ecomfe/echarts#1471]
柱状图和饼图怎么转换

**Comment by joostshao** [comment]
多组的柱状图　和　有时间横轴的饼图是可以转换的，

http://echarts.baidu.com/doc/example/bar15.html

http://echarts.baidu.com/doc/example/pie7.html

**Comment by wujiandong** [comment]
HI，看了下柱状图和折线图可以转换，不能和饼图转换

**Comment by pissang** [comment]
可以 setOption 改 type

**Comment by shihua-guo** [comment]
同问，那么是需要自己手动转化吗
