### ISSUE TITLE
如何在地图中增加链接

### ISSUE THREAD

**Issue by seifer08ms** [ecomfe/echarts#1477]
比如在示例中的“地图标准事件响应”（map3）中的二级地图中，如何加入每个市区对应的不同链接？谢谢

**Comment by pissang** [comment]
添加点击事件

**Comment by seifer08ms** [comment]
是否是指map的点击事件和选择地图事件一样，都可以判定当前操作的地块是哪个？

**Comment by pissang** [comment]
是的，参数的 `name` 属性
