### ISSUE TITLE
地图中 markline能设置不同粗细吗？

### ISSUE THREAD

**Issue by Carman330** [ecomfe/echarts#1479]
地图中，从一个地方连接出去的线能设置不同粗细吗，比如北京-》上海，borderWidth:1，北京-》天津，borderWidth:2

**Comment by pissang** [comment]
markLine 第一项的 `itemStyle.normal.borderWidth`

**Comment by Carman330** [comment]
这个一设置，所有的线都变了，我是想分别设置的，可以么？

**Comment by hushicai** [comment]
markLine有多级控制，可以用`series[i].markLine.data[i].itemStyle.normal.borderWidth`进行分别设置。
