### ISSUE TITLE
chrome（ 41.0.2272.118）图表显示问题

### ISSUE THREAD

**Issue by zhaohng** [ecomfe/echarts#1484]
chrome浏览器，经常碰到图表显示不正常的情况，多次刷新有时能正常，如图：
这是chrome
![chrome](https://cloud.githubusercontent.com/assets/8034308/7292077/d5df3f52-e9ca-11e4-8874-28d16a1e13d7.png)
这是ie11
![ie11](https://cloud.githubusercontent.com/assets/8034308/7292078/d5e035c4-e9ca-11e4-9649-fd54b008b98e.png)

**Comment by xiaoweiqb** [comment]
我也遇到过,就是直接加载点,线连不到一起!
