### ISSUE TITLE
eventRiver2Data.js 好乱啊 能有个说明吗

### ISSUE THREAD

**Issue by 59466832** [ecomfe/echarts#1492]
eventRiver2Data 格式有说明吗

**Comment by pissang** [comment]
看文档

**Comment by 59466832** [comment]
以下这些在文档中真心没找到
"event_name": "aa", 
            "daycount": [103, 1, 1], 
            "cate_id": 15, 
            "date": ["20140803", "20140804", "20140807"], 
            "trend": 0, 
            "media_analysis": 
            {
                "event_mailuo": 
                {
                    "mailuo":

**Comment by pissang** [comment]
这些自定义的数据

**Comment by 59466832** [comment]
哦 这样啊 谢谢
