### ISSUE TITLE
echarts实例使用dispose()之后

### ISSUE THREAD

**Issue by mitoop** [ecomfe/echarts#1493]
echarts实例使用dispose之后打印实例变量不为空 还是对象 查看官方文档dispose()函数 释放图表实例，释放后实例不再可用 不太明白dispsoe具体指什么意思呢?

**Comment by longFeiLi** [comment]
就是整个实例都不能用了，要用必须重新init

**Comment by pissang** [comment]
dispose 会释放内部占用的一些资源和事件绑定，但是解除实例的引用我们是做不到的，你可以赋值 null

**Comment by wustzhaohui** [comment]
> dispose 会释放内部占用的一些资源和事件绑定，但是解除实例的引用我们是做不到的，你可以赋值 null

dispose之后能把`VM5534 react_devtools_backend.js:2842 Instance ec_1629442149102 has been disposed`这个log关掉么
