### ISSUE TITLE
通过setSeries方法或者setOption方法修改data值，实现单选效果

### ISSUE THREAD

**Issue by ghost** [ecomfe/echarts#1495]
想通过其他事件触发，通过调用setSeries方法设置data值，指定某个省被选中，但之前的选中的省还是会被选中，如何去掉之前选中效果

**Comment by pissang** [comment]
怎么设置的？之前选中的把 selected 设成 false？

**Comment by i-tang** [comment]
是想和地图的点击配合使用，在地图上也可以点击，通过其他事件也可以选中。通过其他事件选中，之前在地图上点击选中的没去除
