### ISSUE TITLE
tooltip悬停在markPoint上的params

### ISSUE THREAD

**Issue by yeahe83** [ecomfe/echarts#1496]
关于tooltip的params，感觉文档说的有点含糊。

暂时用的indicator区别悬停于markPoint和其他区域。

另，怎么能让非markPoint不显示tooltip呢？

[
    {
        
        seriesIndex: 0,
        seriesName: '一周销量',
        name: '周一',
        dataIndex: 0,
        data: data,
        name: name,
        value: value,
        percent: special,       // 饼图
        indicator: special,     // 雷达图、力导向、和弦
        value2: special2,       // 力导向、和弦
        indicator2: special2    // 力导向、和弦
    },
    {..},
    ...
]

**Comment by longFeiLi** [comment]
在markPoint  里面加上 tooltip   设置show：false
