### ISSUE TITLE
示例就有问题？timeline的星星在手工点击时位置总是不对

### ISSUE THREAD

**Issue by yeahe83** [ecomfe/echarts#1497]
http://echarts.baidu.com/doc/example/map14.html
慢一拍？

**Comment by fengzheng101** [comment]
我的代码timeline+map也有这个问题，解决了没呢？

**Comment by liminjun** [comment]
Chrome浏览器里面这个demo确实有这个问题，不过我实际在项目使用的timeline+气泡图是可以的。@yeahe83

**Comment by fengzheng101** [comment]
我的项目里面timeline+bar图也是可以的，唯独map图不行，这个例子在其他浏览器都有问题@kener

**Comment by zhaohng** [comment]
#1515

**Comment by pissang** [comment]
Fixed

**Comment by fengzheng101** [comment]
经验证，更新zrender可以正常显示，目前官网的demo还没有更新，可以去http://ecomfe.github.io/zrender/去下载最新的
