### ISSUE TITLE
有时候图表显示不正确,点击restore后回复正常

### ISSUE THREAD

**Issue by rikan** [ecomfe/echarts#1498]
![bar-before](https://cloud.githubusercontent.com/assets/1563596/7384248/96bee5b6-ee61-11e4-851b-4ff78c22487a.png)
加载进来的时候是这个样子

![bar-hover](https://cloud.githubusercontent.com/assets/1563596/7384252/b754446a-ee61-11e4-90b1-77f37b9691c6.png)
我随便选一个比较夸张的,当把鼠标放上去的时候,这个bar就会自己变长,其他的bar不变.每一个bar都是这样

![bar-after](https://cloud.githubusercontent.com/assets/1563596/7384269/1ef0992a-ee62-11e4-9c8f-aac36c713720.png)

当点击右上角还原按钮时,所有的bar又回复到了正常状态

饼图也有问题

![pie-before](https://cloud.githubusercontent.com/assets/1563596/7384271/3c4d731c-ee62-11e4-946d-05dd3036153d.png)

点击还原按钮后
![pie-after](https://cloud.githubusercontent.com/assets/1563596/7384275/4be38492-ee62-11e4-89ee-3a9c6852e80a.png)

我主动在echarts.init后调用过restore或者refresh方法都没有作用

**Comment by rikan** [comment]
Any one can help me?

**Comment by 100pah** [comment]
可否把代码发来看看？

**Comment by rikan** [comment]
这个问题找到原因了, 加载大量数据,或者图表较多的时候,容易出现这个问题,问题出现在动画上,我把动画关掉就好了
