### ISSUE TITLE
Multiple marklines per serie

### ISSUE THREAD

**Issue by ruudtimmermans** [ecomfe/echarts#1504]
Is it possible to add multiple marklines per serie? Also i want a label on the right side of the markline, can't get this working.

**Comment by ruudtimmermans** [comment]
The code until now:
<code>
require.config({
            paths: {
                echarts: 'http://echarts.baidu.com/build/dist'
            }
        });
        
        require(
            [
                'echarts',
                'echarts/chart/line'
            ],
            function (ec) {
                var line2Chart = ec.init(document.getElementById('line2Chart')); 

                var option = {
					    title : {
					        text: 'Title',
					        subtext: 'subtitle'
					    },
					    tooltip : {
					        trigger: 'axis'
					    },
					    legend: {
					        data:['data1']
					    },
					    color: ['#017e8d', '#e48f24'],
					    calculable : true,
					    xAxis : [
					        {
					            type : 'category',
					            data : ['PB', 'LB', 'WL', 'TMS', 'OZL', 'OWL', 'EMS', 'KS', 'LV', 'CA', 'WS', 'TB', 'KR', 'LS']
					        }
					    ],
					    yAxis : [
					        {
					            type : 'value'
					        }
					    ],
					    series : [
					        {
					            name:'data1',
					            type:'line',
					            data:[7, 5, 5, 4, 8, 5, 6, 6, 4, 9, 10, 6, 9 ],
					            itemStyle: {
					            	normal: {
						                label : {
						                	show: true,
						                	position: 'bottom',
									    	textStyle : {
					                            color: '#017e8d'
					                        }
						                },
						                labelLine : {
					                        show : false
					                    }
					            	}
					            },
					            markLine : {
					            	symbol: ['none', 'none'],
					            	itemStyle: {
					            		normal: {
					            			color: '#e48f24',
					            			lineStyle: {
							            		type: 'solid',
							            		width: 4
							            	}
					            		}
					            	},

					                data: [
									    [
									        {xAxis: 0, yAxis: 10},
									        {xAxis: 100, yAxis: 10}
									    ]
									]
					            }
					        }
					    ]
					};
					                    
                line2Chart.setOption(option); 
            }
        );
</code>

**Comment by pissang** [comment]
Yes，data of markLine is an array, which means you can add more than one data to show multiple markLine. The position of label is determined by the direction of markLine to avoid overlapping.

**Comment by DoisKoh** [comment]
The problem with this is that the markLines must have the same style.
