### ISSUE TITLE
折线图面积如何不显示多余点

### ISSUE THREAD

**Issue by seifer08ms** [ecomfe/echarts#1511]
如何控制不显示空数据的灰点，以及只显示水平线上的第一个点？
option = {
    title : {
        text: '某楼盘销售情况',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['意向','预购','成交']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'成交',
            type:'line',
            smooth:false,
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:['-', '-', '-', '-', '-', 1000, 1000]
        },
        {
            name:'预购',
            type:'line',
            smooth:false,
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:['-', '-', '-', 800, 800, 800, 800]
        },
        {
            name:'意向',
            type:'line',
            smooth:false,
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:['-', 1320, 1320, 1320, 1320, 1320, 1320]
        }
    ]
};

**Comment by pissang** [comment]
关闭可拖拽特性，calculable 设置为 false

**Comment by seifer08ms** [comment]
水平线上的第一个之后的数据点没法隐藏了吗？
