### ISSUE TITLE
雷达图【数据视图】修改数据不显示,官网实例同样问题！example/radar1.html

### ISSUE THREAD

**Issue by bugmeng** [ecomfe/echarts#1513]
望修复，最近要演示功能，此功能无法正常
地址:example/radar1.html

**Comment by seifer08ms** [comment]
楼主，我这里可以的

**Comment by bugmeng** [comment]
@seifer08ms 修改数据视图，你那里可以正常？你用的什么浏览器，我用谷歌和IE都不可以

**Comment by seifer08ms** [comment]
我是直接修改代码里面的数据，数据视图没试过，我再试试

**Comment by seifer08ms** [comment]
的确是有问题，在数据视图里面修改数据，会变成只有两个数，雷达图上图案消失。我是火狐37.0.2

**Comment by bugmeng** [comment]
@seifer08ms 恩,代码里修改没有问题。我修改了标题,这下应该是个问题了。

**Comment by bugmeng** [comment]
@errorrik
