### ISSUE TITLE
timeline bug

### ISSUE THREAD

**Issue by sunyanjun1701** [ecomfe/echarts#1515]
发现时间线与上面的标题对应不上。一开始还以为是我的参数有问题，后来发现，官网的例子也是这样。
http://echarts.baidu.com/doc/example/map14.html
![qq 20150507094145](https://cloud.githubusercontent.com/assets/12285538/7507127/5b60efd6-f49d-11e4-952d-c61509c39987.png)

**Comment by zhaohng** [comment]
自动播放的时候，时间轴的显示和数据差一位，比如2009年，时间轴上显示的是2008年。
手动点击的时候，地图还是能显示正确的数据，但时间轴就各种不对了。

**Comment by bugmeng** [comment]
确实，遇到过这个问题，没有提，不过确实有这个BUG，点击的时间轴和数据对不上!显示为上一个

**Comment by seifer08ms** [comment]
+1，我也发现了这个问题

**Comment by zhaohng** [comment]
@pissang 项目要上线，能否帮忙在本周解决该bug？多谢

**Comment by pissang** [comment]
Fixed

**Comment by zhaohng** [comment]
@pissang 什么时候能提交代码呢？

**Comment by pissang** [comment]
更新 zrender 的代码
