### ISSUE TITLE
Map的炫光效果与Timeline共用的问题

### ISSUE THREAD

**Issue by MatrixYuri** [ecomfe/echarts#1516]
Map里series的markLine的effect设置为true，
如果加上时间轴，那么

在时间轴切换下一时间点之后，炫光效果的轨迹并没有消失，而是残留在了图像上，
拖动或缩放一下图像，痕迹会被清除，重新绘制整个画面。

但是如果不做任何操作，观看时间轴自动播放，痕迹会一直叠加起来，非常难看...

尝试过了notMerge，并没有消除这个轨迹...

**Comment by MatrixYuri** [comment]
如图：
![image](https://cloud.githubusercontent.com/assets/4649294/7514464/0d84f0c0-f4f0-11e4-9638-7608c6fd6a43.png)

浅灰色的轨迹是之前时间点产生的炫光效果轨迹。

**Comment by pissang** [comment]
这个残痕确实纠结了我们挺久的
