### ISSUE TITLE
Treemap显示未定义

### ISSUE THREAD

**Issue by scottlyz** [ecomfe/echarts#1524]
<script src="./js/echarts.js"></script>
    <script type="text/javascript">
        // 路径配置
        require.config({
            paths: {
                echarts: './js'
            }
        });        
        // 使用
        require(
            [
                'echarts',
                'echarts/chart/treemap'
            ],
		DrawChart
		)

treemap.js 显示：Uncaught ReferenceError: $ is not defined

**Comment by loutongbing** [comment]
我开发的时候不小心用到了jquery。
目前在修复这个bug。
