### ISSUE TITLE
当仪表盘的值处在开口所在的半圆时，鼠标未放到指针上就已经显示指针选中

### ISSUE THREAD

**Issue by zdw406** [ecomfe/echarts#1526]
https://cloud.githubusercontent.com/assets/7029254/7560411/7a4da4b0-f7f5-11e4-831b-934aa2c8af5c.png

如题，当仪表盘的值处在开口所在的半圆时，鼠标未放到指针上就已经显示指针选中。在官网实例也是如此，http://echarts.baidu.com/doc/example/gauge2.html就存在这种问题。

**Comment by 100pah** [comment]
仪表盘的指针hover判断是依照指针的bounding box，感觉没有必要做更精细的判断。（有必要么~）

**Comment by zdw406** [comment]
感觉鼠标还没到呢就提示了还是不应该啊。
