### ISSUE TITLE
Gauge圖表無法resize

### ISSUE THREAD

**Issue by yancey918** [ecomfe/echarts#1532]
試著改變DOM的size 但它都一樣  , is this bug ??
```javascript
 <div id="main" style="height:500px;width:650px;"></div>
```
![gauge](https://cloud.githubusercontent.com/assets/9336708/7578153/cabd031c-f883-11e4-8edf-1aada373b6f2.png)

**Comment by pissang** [comment]
`radius` 设置成百分比试试
