### ISSUE TITLE
legend 图例的样色的问题。

### ISSUE THREAD

**Issue by Genffy** [ecomfe/echarts#1533]
非常好奇，为啥图例的颜色不能设置，但是自动获取的方式却又很奇怪。

业务场景：折线图数据动态变化，秒级监控那种
在option的color 未赋值的情况下，legend的 textStyle.color 和 line的lineStyle 都是特殊设置的情况下，legend图例的样色就取默认取主题的样色。

这逻辑有点怪。或者是我需求变态？

**Comment by lanhouzi** [comment]
把你的代码贴上来

**Comment by Genffy** [comment]
伪代码：
![qq20150512-2](https://cloud.githubusercontent.com/assets/1506972/7584871/4c7d24e6-f8d3-11e4-988a-9746622247f4.png)
最后效果：

![qq20150512-1](https://cloud.githubusercontent.com/assets/1506972/7584911/90219632-f8d3-11e4-8cab-464ac8c764a0.png)

**Comment by pissang** [comment]
legend 的颜色不是设置 textStyle.color

**Comment by Genffy** [comment]
常规的用法确实是这样的，当你需要实现这种事实的数据图时，即便设置了<code>itemStyle.normal.color</code> 你会发现 legend 的样色和线的样色压根不匹配。
