### ISSUE TITLE
请不要把define放到全局空间

### ISSUE THREAD

**Issue by yadongwen** [ecomfe/echarts#1534]
太容易起冲突，比如jquery。。。

**Comment by pissang** [comment]
jquery 还有 define？

**Comment by vipjeffreylee** [comment]
再比如momentjs

2015-05-12 20:28 GMT+08:00 Yi Shen <notifications@github.com>:

**Comment by yadongwen** [comment]
我刚开始做前端，因为这个花了几个小时 https://github.com/jquery/jquery-ui/blob/master/ui/widget.js#L17

**Comment by vipjeffreylee** [comment]
我也是，调整了几次js文件的加载顺序，发现了这个问题，全局define不该被echarts定义。你一个图表插件就老老实实做图表功能，不该融合进requirejs的功能

2015-05-13 14:52 GMT+08:00 Yadong Wen <notifications@github.com>:

**Comment by wh1100717** [comment]
@vipjeffreylee @yadongwen echarts-all.js中是没有对外暴露require或者define变量的吧？ 你是不是使用的是模块化单文件引用的方式？

**Comment by vipjeffreylee** [comment]
可能现在的版本已经不存在这个问题了吧。

2015-05-20 13:39 GMT+08:00 Eric Wang <notifications@github.com>:

**Comment by yevon-cn** [comment]
经试用，模块化单文件引用的方式仍然存在define冲突问题（想不通为什么要定义会引起冲突的全局define、require），而单文件引用方式则不存在这个问题（似乎使用时没有模块化单文件引用灵活）

**Comment by hushicai** [comment]
高级开发用户，可以直接使用源代码进行开发。

部署后的代码中，模块化单文件引用的方式会内置define、require。

源代码就没有内置，支持常见的符合amd规范的模块加载器。
