### ISSUE TITLE
中国地图标注重叠问题

### ISSUE THREAD

**Issue by moonshine42** [ecomfe/echarts#1535]
![image](https://cloud.githubusercontent.com/assets/8499671/7604427/126171c0-f975-11e4-9700-bccf540c75a2.png)
官网的地图是ok的（香港、澳门没有重叠），但项目要求地图支持中英文版，因此修改了echarts\src\util\mapData\geoJson\china_geo.js文件中的地名"name"属性，在根据此key进行绘图前的nameMap映射。发现源码可能有对香港、澳门的地标做特殊处理，修改了香港、澳门"name"属性后地标重叠。
请问name属性修改之后如何保证香港澳门不重叠，还应修改哪个文件？
![image](https://cloud.githubusercontent.com/assets/8499671/7604478/f0d79de4-f975-11e4-8da8-927df0b0f0f0.png)

**Comment by seifer08ms** [comment]
有个属性是修正label的位置的，通过制定xy的像素偏移，看看文档里面有

**Comment by moonshine42** [comment]
没有找到文档的对应位置哈~ 能帮忙贴出对应示例吗？ 感恩~

**Comment by seifer08ms** [comment]
例如，北京的地图的series中添加名字的像素单位的偏移量
textFixed:{'石景山区' : [-15, 0],'丰台区' : [-15, 5],'朝阳区' : [10, -15],'海淀区' : [-15, -5],'崇文区' : [-5, 10],'宣武区' : [20, 0],'东城区' : [20, 0],'西城区' : [-15, -10]},

**Comment by moonshine42** [comment]
嗯，感谢~
刚刚找到这个例子，通过geoCoord配置也可以
http://echarts.baidu.com/doc/example/map.html
geoCoord: {
                            "hk": [116.2578, 22.0242],
                        }

**Comment by hl-stone** [comment]
@HelKyle 没有用了
