### ISSUE TITLE
zrender/tool/util  clone() 方法判断对象是否为数组在跨frame时有问题

### ISSUE THREAD

**Issue by soulaxin** [ecomfe/echarts#1536]

**Comment by hushicai** [comment]
instanceof判断array在同一个window中，是没问题的。

**Comment by soulaxin** [comment]
额，对，但是如果不同呢，因为我使用的时候就是不同的window的，所以我改了这个判断的。
建议用这种方式：Object.prototype.toString.call(arr)=="[object Array]"
我是谷歌的！
