### ISSUE TITLE
力导向图节点重叠的问题

### ISSUE THREAD

**Issue by xiejun** [ecomfe/echarts#1540]
想用力导向图图做一个拓扑结构，将树形结构的节点改成了矩形，并把文字显示在上面，但是显示的效果却是节点都重叠在了一起（如下图），gravity已经设置的很小了，有什么方法能让他自动适应节点大小不重叠吗？还有节点之间的线只能是直线和曲线吗？能否用折线表示？
![qq 20150514104222](https://cloud.githubusercontent.com/assets/1418991/7625112/f20103c6-fa25-11e4-9326-40c62b7019a1.png)

**Comment by pissang** [comment]
规整的拓扑结构不推荐使用 echarts 的力导向，可以使用 dagre https://github.com/cpettitt/dagre-d3
