### ISSUE TITLE
IE10 下hover，click，drag事件都不能正确触发，鼠标一直是defalut状态，谷歌正常。

### ISSUE THREAD

**Issue by stevefoxuser** [ecomfe/echarts#1546]
build2.2.   
IE10 下hover，click，drag时间都不能正确触发 ， 包括toolbox也不能点击，官方势力也一样，不知道是不是zindex之类的问题，鼠标也一直是defalut状态，谷歌浏览器正常。

我很奇怪这么明显的bug为什么没有人提起，研发团队也不可能不测试IE10 . highcharts没有这个bug。

**Comment by 100pah** [comment]
我这边没有复现出这个问题。
是build2.2.几？
有没有什么特殊的环境因素导致这个问题出现？
