### ISSUE TITLE
echarts的数据导入问题，var option = $("#chartsdata").text(); 不显示，直接写就行，为什么？

### ISSUE THREAD

**Issue by zpost** [ecomfe/echarts#1547]
如题：
以var option = $("#chartsdata").text();导入的数据，不显示。而
1、alert能看到数据，导入没有问题。
2、直接将数据写在option中，也可以显示，数据没有问题。
请各位大师解答，谢谢

建议官网上，给一些简单的例子，大家都眼巴巴国产开源软件，不是不想支持呀！用不起来，急！！！

**Comment by zpost** [comment]
找到问题了，写成var option = eval("("+$("#yearchartsdata").text()+")");就可以了。ajax方案，也百度了一推，没有好使的，正在摸索中...
谢谢

**Comment by pissang** [comment]
$("#chartsdata").text() 只是一个字符串，需要转成对象。eval 就是做了这事，高版本浏览器也可以用 JSON.parse
