### ISSUE TITLE
timeline各时间点数据长度不同

### ISSUE THREAD

**Issue by dawnwords** [ecomfe/echarts#1549]
刚刚接触echarts，用到了timeline的时候遇到了这样一个情况，以下面的demo为例：

* timeline上有两个时间点2012,2013
* 2012对应有一个`series: [{data: [12, 13, 4, 32], name: '销量', type: 'bar'}]`
* 2013对应有一个`series: [{data: [22, 12], name: '销量', type: 'bar'}]`

数据长度不一致，结果点到2013的时候，还是显示4个bar，后面两个空位会不上2012的后两个bar
预期的效果是2012显示4个bar，2013只显示两个bar，需要怎么做呢？

**Comment by zhaohng** [comment]
同 #1515

**Comment by redmed** [comment]
timeline中有notMerge参数，表示时间轴上多个option切换时是否进行merge操作，默认false。
修改为true即可。

参考API: http://echarts.baidu.com/doc/doc.html#Timeline
