### ISSUE TITLE
Echarts 和 Polymer 无法兼容?

### ISSUE THREAD

**Issue by Colstuwjx** [ecomfe/echarts#1552]
Polymer版本：~0.5
Echarts版本：2.2.2

想使用Polymer + Echarts 制作一个图表的Element，发现没有显示效果：

```
<!-- Inside Polymer, Echarts element! -->
    <template>
        <div id="graph_area" style="width: 800px; height: 400px;"></div>
    </template>

    <script type="text/javascript" src="/static/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="/static/sui/semantic.min.js"></script>
    <script src="/static/ECharts/echarts-all.js" ></script>

    <script>
        Polymer('at-metrics-graph', {
            ready: function(){
                var myChart = echarts.init(this.$.graph_area);
                ...
                myChart.setOption(option);
                ...
```

在app page里使用该标签，没有显示效果：

```
<xx>
     <at-metrics-graph></at-metrics-graph>
<xx>
```
希望能得到回复。谢谢！

Edited:
在Polymer 第一层的shadowRoot有显示效果，嵌套element之后无法显示。

**Comment by Colstuwjx** [comment]
ADD:

BTW，在更换方式之后，貌似是可以show出来了，解决方案是，不在element ready方法里初始化myChart对象，而是选择在上层element调用一个showGraph（在echarts element里定义）方法，该方法内部实现展现逻辑。

有没有更好的办法? 目前看样子这样的情况可能是由于Polymer本身的shadow DOM特性导致DOM结构无法很好的被ECharts对象读取和处理。

**Comment by g0267** [comment]
polymer1+echart3正常显示
如下
Data-charts.html：
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../components/echarts-import.html">
<dom-module id="Data-charts">
    <style></style>
    <template>
        <div id="echart" style="width:1000px;height:400px"></div>
    </template>
    <script>
        Polymer({
            is: "Data-charts",
            ready:function(){
                var  myChart = echarts.init(document.getElementById('echart'));

                // 指定图表的配置项和数据
                var option = {
                    title: {
                        text: 'ECharts 入门示例'
                    },
                    tooltip: {},
                    legend: {
                        data:['销量']
                    },
                    xAxis: {
                        data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                    },
                    yAxis: {},
                    series: [{
                        name: '销量',
                        type: 'bar',
                        data: [5, 20, 36, 10, 10, 20]
                    }]
                };

                // 使用刚指定的配置项和数据显示图表。
                myChart.setOption(option);
            }
        });
    </script>
</dom-module>


echarts-import.html：
<script src="../components/echarts.min.js"></script>
