### ISSUE TITLE
dataRange 如何设置类似下图的值？如何设置当前值？

### ISSUE THREAD

**Issue by hywliu** [ecomfe/echarts#1553]
![image](https://cloud.githubusercontent.com/assets/4516803/7674045/b1235712-fd51-11e4-88ea-aa2afb1704eb.png)
![image](https://cloud.githubusercontent.com/assets/4516803/7674064/22897ed6-fd52-11e4-977f-c7cef9324ae9.png)

**Comment by 100pah** [comment]
在option中的dataRange里面，提供了一个`range`属性能够对这个区域进行初始化：

**Comment by hywliu** [comment]
非常感谢回答，请问第二个图，如何在加载后就指定一个当前值？

**Comment by 100pah** [comment]
第二个图初始指定一个当前值，目前还不支持~
