### ISSUE TITLE
一个Tab中使用echarts，除了默认的avtive项的图表能显示，其他图表切换时都无法显示

### ISSUE THREAD

**Issue by zhm8932** [ecomfe/echarts#1558]
一个Tab中使用echarts，除了默认的avtive项的图表能显示，其他图表切换时都无法显示（使用display:none）。求解决方法

       <ul class="tabhd"><li class="active">今天</li><li>近30天</li><li>全部</li></ul>
       <ul class="echarts">
                       <li><div id="todayNum"  style="display:block"></div></li>
                       <li><div id="monthsNum"></div></li>
                       <li><div id="allNum"></div></li>
         </ul>

**Comment by xcf007** [comment]
js切换tab时初始化各个图表咯
