### ISSUE TITLE
echarts2.2.2在微信端显示，折线图变形的问题。

### ISSUE THREAD

**Issue by fengzhibin** [ecomfe/echarts#1561]
当折线图下方有内容，手机需要上下滚动的时候，随着页面往上滚动，折线图逐渐上移，折线图会出现轻微的变形问题。变形的情况为底部往上收缩。

暂时只发现在微信有这个问题，自带手机浏览器和电脑端的谷歌浏览器都没这个问题。

真是个奇怪的问题，之前在微信端使用百度地图遇到地图变形的问题，这次遇到在微信端使用echarts上下拖动变形的问题。貌视这个两者都是用到了html5的Canvas。
同样的情况，刚才卸载了微信，再重装。再测试一下，上下拖动折线图正常。关闭页面再次测试，折线图又开始变形了。上次测试百度地图的时候也是这种情况。

现在发现是部分手机的会出现这样的问题。苹果5S没任何问题，小米1S，红米1S有问题。

**Comment by kentchenj** [comment]
我的也有这个问题，和楼主的情况一模一样。请问楼主你解决了没有？

**Comment by fengzhibin** [comment]
@kentchenj 没有解决，问题被搁置了，微信浏览器确实是问题很多。

**Comment by 823844596** [comment]
如果把  动画  置成false 试试呢

**Comment by fengzhibin** [comment]
@823844596 一直都是false,因为这个echarts在一些比较旧的单核平板，开启动画效果，会出现两条折线错乱的。关了动画效果就正常了。一直没开动画效果。

**Comment by 823844596** [comment]
@fengzhibin 有点蒙...意思是这个问题不是因为开启动画导致的？

**Comment by fengzhibin** [comment]
@823844596 不是。我这边一直是开闭这个动画效果的。

**Comment by 823844596** [comment]
@fengzhibin  “开闭” 是？  API上说的是：
animation
{boolean} true，是否启用图表初始化动画，默认开启，建议IE8-关闭
