### ISSUE TITLE
饼图 怎么获取到 百分比的 值 有这个接口吗 

### ISSUE THREAD

**Issue by hypo1986** [ecomfe/echarts#1563]
饼图 怎么获取到 百分比的 值 有这个接口吗

**Comment by zhaohng** [comment]
{d}

**Comment by hypo1986** [comment]
可能 我没说明白 我说的 是 如获取 颜色 myChart.component.legend.getColor(name);
那么 获取 初始化后的 {d} 值 应该 怎么做 呢 谢谢

**Comment by huangchunhai0201** [comment]
同问 因为在其他文字描述中也会要计算百分比 有可能显示的百分比不同就麻烦了
