### ISSUE TITLE
雷达图的indicator 无法获取点击事件

### ISSUE THREAD

**Issue by wangdy326** [ecomfe/echarts#1567]
polar : [{
          indicator : [
              { text: '销售', max: 6000},
              { text: '管理', max: 5000},
              { text: '信息技术', max: 7000},
              { text: '客服', max: 8000},
              { text: '研发', max: 10000},
              { text: '数量', max: 6000},
              { text: '美工', max: 8000},
              { text: '3D', max: 6000},
              { text: '行政', max: 5000},
              { text: '市场', max: 2500}
           ],
           name: {
               show: true,
               textStyle:{
                   color:"#000"
               }
           },
           radius : 120,
           center : ['55%', '50%'],
       }],

**Comment by wangdy326** [comment]
查阅了API文档，indicator无clickable等相关属性，无法给销售、市场等10个标签添加单击事件 :(

**Comment by cnxh** [comment]
@wangdy326  同样问题  看样子是不支持 @leeight

**Comment by leeight** [comment]
@cnxh，应该是 cc @pissang

**Comment by pissang** [comment]
抱歉不支持

**Comment by cnxh** [comment]
@leeight  @pissang   谢谢
