### ISSUE TITLE
顶部留白体验问题

### ISSUE THREAD

**Issue by feng524822** [ecomfe/echarts#1569]
当title、toolbox都不显示时顶部还是会留出一段空白，占用空间

**Comment by vipjeffreylee** [comment]
这个可以自己定义消除它。

2015-05-21 17:47 GMT+08:00 坚壳 <notifications@github.com>:

**Comment by feng524822** [comment]
求教怎么配置，翻了好久的配置都没有找到配置项

**Comment by pissang** [comment]
`grid.y`

**Comment by vipjeffreylee** [comment]
option ={
     grid: {
x: 50,
y: 25,
x2: 50,
y2: 60
},

}
分别是左上角，右下角坐标

2015-05-21 20:17 GMT+08:00 Yi Shen <notifications@github.com>:

**Comment by feng524822** [comment]
many thks

**Comment by jodo4x** [comment]
@pissang 貌似 对于`pie chart`没有效果。
