### ISSUE TITLE
多地图功能中，会显示崇文区和宣武区

### ISSUE THREAD

**Issue by pkuzhg** [ecomfe/echarts#1571]
多地图功能中，选中北京，展开二级地图中会显示崇文区和宣武区，如何可以避免这个问题？这两个区已经合并到别的区了
我用的是2.2.2版本

**Comment by seifer08ms** [comment]
是echarts默认压缩的geojson文件的区域是旧的吧,
可以考虑 扩展geojson,自己加载个新的矢量文件
