### ISSUE TITLE
echarts 与前端MVVM框架avalonJS冲突

### ISSUE THREAD

**Issue by penweizgx** [ecomfe/echarts#1573]
页面引入JS冲突：
< script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
< script src="http://rubylouvre.github.io/mvvm/javascripts/avalon.js"></script>  
< script type="text/javascript">
        // 路径配置
        require.config({
            paths: {
                echarts: 'http://echarts.baidu.com/build/dist'
            }
        });
        
        // 使用
        require(
            [
                'echarts',
                'echarts/chart/bar' // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {
                // 基于准备好的dom，初始化
..........................）
然后再页面加载的时候出问题了：
![image](https://cloud.githubusercontent.com/assets/6983487/7773721/ee66897a-00d8-11e5-9681-8f14ffafeecb.png)

**Comment by hushicai** [comment]
你的require.config中paths配置有问题，不能指向http://echarts.baidu.com/build/dist。

**Comment by penweizgx** [comment]
我用的官方的demo，在不导入avalon.js时是没有问题的

**Comment by pissang** [comment]
应该是因为 avalon.js 也有自己的加载器的缘故，可以标签加载 echarts-all.js ，如果太大的话可以从 [ECharts 在线构建工具](http://ecomfe.github.io/echarts-builder-web) 上打包下载
