### ISSUE TITLE
当series数据中包含null时，图表不显示，是必须处理为0吗？

### ISSUE THREAD

**Issue by ynioba** [ecomfe/echarts#1575]
我们有在项目中使用echarts，而且部分用在了MES系统中，主要用于显示采集到的工控数据，动态数据还好，当是null的时候，会显示灰色虚点，如果是静态图表数据中有null，例如：[1，2，null，3，4，1，null，3，4]，图表是不显示的，实际上在mes系统中，null表示未能采集到数据，而0，表示采集到的数据为0，例如：温度为0，送风量为0.两者是有区别的。当数据中有null的的时候，个人认为应该是断开的点，x轴的时间是有的，只是y轴数据为null，这样显示出来的实际上是3条线段。从界面上来看非常的直观。

请问，如何让数据中有null（时间X轴正常）也能让图表正常显示？？

**Comment by wyzfzu** [comment]
无数据可以用 - 来表示。

**Comment by ynioba** [comment]
@wyzfzu  这位大大，貌似不可以。

例如这个例子，我把series中的数据改为了-，图表依然不显示的。

option = {
    title : {
        text: '未来一周气温变化',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['最高气温','最低气温']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLabel : {
                formatter: '{value} °C'
            }
        }
    ],
    series : [
        {
            name:'最高气温',
            type:'line',
            data:[-, 11, -, 13, 12, 13, 10],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            }
        },
        {
            name:'最低气温',
            type:'line',
            data:[1, -2, -, 5, 3, 2, 0],
            markPoint : {
                data : [
                    {name : '周最低', value : -2, xAxis: 1, yAxis: -1.5}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name : '平均值'}
                ]
            }
        }
    ]
};

**Comment by wyzfzu** [comment]
@ynioba 是不是没加引号，参考实例中的折线图-折线图那个例子。

**Comment by ynioba** [comment]
@wyzfzu  

果然，非常感谢，明白了！！

**Comment by kkw1201** [comment]
我现在也有这个问题，我不仅要区分为null和0的区别，还要在折线图展示出来，就是x:1, y:null
x:2, y:0这样的展示请问有办法吗，
