### ISSUE TITLE
x轴为time类型，x轴展示问题。

### ISSUE THREAD

**Issue by spp1987** [ecomfe/echarts#1576]
当x轴为time类型时候 ，data就两条数据。 因x轴为time时，只能接受new Date()数据 ，x轴展示就会出现
2013 2013 2013 2014 （其实只有2013,2014两条数据）。

**Comment by hushicai** [comment]
用category吧，然后自己format以下axisLabel.

**Comment by spp1987** [comment]
hi，不用类目类型作为x轴的考虑 是因为 一开始 用来 切换 日、周、月、年 等周期，而且每个日期下面数据不连贯。存在断片的数据，但是还需要连线起来。
