### ISSUE TITLE
为什么在andorid的webview里展示,从柱状图切换到折线图会两个图重合在一起?

### ISSUE THREAD

**Issue by zhouyu629** [ecomfe/echarts#1577]
因为显示重影问题,我关闭了动画,但奇怪的是从柱状图切换到折线图时居然柱状图不消失,柱和折线重合在一起.

![screenshot_2015-05-26-09-48-19](https://cloud.githubusercontent.com/assets/4645421/7803916/3bfa0750-038d-11e5-9a5a-a8efa60e71d7.png)

**Comment by zhouyu629** [comment]
说明:我直接在andorid浏览器打开是正常的。但放到webview里就不行了。

**Comment by ynioba** [comment]
webView只是浏览器的一个子集，另外，android浏览器从4.4开始就变成了chrome的一个子集。

我个人建议这样，先施放掉echarts，然后，重新生成！
if(myEcharts)
{ 
       myEcharts.clear();
       myEcharts.dispose();
}

 myEcharts= echarts.init(document.getElementById('echartMainDiv'));
myEcharts.setOption(option);

**Comment by 823844596** [comment]
在webview中显示的仪表盘图有时会出现双指针或者仪表盘图都不出，这个怎么解决？

**Comment by linmuxi** [comment]
关注，没人解决吗？
