### ISSUE TITLE
2.0.2 版本xAxis 的show:false属性不生效了？

### ISSUE THREAD

**Issue by shangjiuliu** [ecomfe/echarts#1587]
想隐藏x轴与y轴，在示例http://echarts.baidu.com/doc/example/scatter2.html增加属性show:false可以隐藏掉坐标轴，但是在我本地不行。
后来查阅资料发现可能是因为我本地使用得2.0.2版本已不支持这个属性了，这样我怎么做到隐藏坐标轴呢

**Comment by pissang** [comment]
2.0.2 是很老的版本了啊

**Comment by shangjiuliu** [comment]
但是kener大神说：
2.0+规范了option，像grid、xAxis、yAxis、legend，如果不需要请删除这个属性就行。
show：false的使用会在别的场景下使用，当这种场景下也得需要保持legend配置是合法的，如data必须。

ps:最新的版本又支持这个属性了么
