### ISSUE TITLE
X轴各数据项文字过长怎么办？

### ISSUE THREAD

**Issue by pkuzhg** [ecomfe/echarts#1588]
我在做一个柱图，但X轴每个数据项的文字都比较长，可能十来个字，这样做出来导致显示的图X坐标轴文字不全，这怎么办？
![x](https://cloud.githubusercontent.com/assets/12557533/7856877/03232e6a-055f-11e5-8cdd-675ebdd18e24.jpg)

**Comment by wyzfzu** [comment]
每个x坐标label用formatter格式化换行，2-4个字一行展示。不够的话，把x轴展示的interval设置成0。

**Comment by HuaJson** [comment]
axisLabel : {
formatter: function(value){
      return value.substring(0,8)+"...";
}
}
