### ISSUE TITLE
【严重bug】Echarts 扩展 map出错了，无法正常显示【所有浏览器均有问题】

### ISSUE THREAD

**Issue by liuzhengjun** [ecomfe/echarts#1590]
Echarts 扩展 map出错了，无法正常显示
http://echarts.baidu.com/extension/BMap/doc/example.html

![image](https://cloud.githubusercontent.com/assets/9263526/7874275/015349e0-05e0-11e5-84fa-8e8d27128ced.png)

**Comment by HuaJson** [comment]
浏览器兼容的问题吧
Chrome显示正常
IE稍稍有点问题
你的是什么浏览器？

**Comment by liuzhengjun** [comment]
不是兼容的问题，我刚刚用chrome也试过了，还是一样的问题。
![image](https://cloud.githubusercontent.com/assets/9263526/7875394/2a8846c6-05ef-11e5-9077-671ad7855b93.png)
![image](https://cloud.githubusercontent.com/assets/9263526/7875395/2c5b5736-05ef-11e5-92f4-3017f59eaae5.png)
