### ISSUE TITLE
图像不能默认显示

### ISSUE THREAD

**Issue by llzzss** [ecomfe/echarts#1591]
同一页面已经加载过echarts 
第二次调用，使用这种方式时
require('echarts').init(document.getElementById('DivPic')).setOption(optionPie)；
我的饼图不显示出来，只有点一下工具条的饼图按钮才能显示出饼图？怎么才能是它一开始网页打开就显示图片

**Comment by 823844596** [comment]
楼主解决了嘛?我也遇到了同样的问题...
