### ISSUE TITLE
关于柱形/条形图的排序问题

### ISSUE THREAD

**Issue by azraelrabbit** [ecomfe/echarts#1599]
目前使用的版本是2.2.2.
1.使用中发现,如果后台提供的数据排序是升序排列,那么 柱状图或条形图的排序是按照 降序排列的.
2. 比如使用条形图,要让最长的条显示在最上方,最短的条显示在最下方,那么必须 是series的顺序为升序.否则会混乱.
3. 堆积 柱/条 ,的话,也是基本依照以上的排序原则,但是根据具体数据序列的不同,需要自行测试调整直至找到合适的排序组合. 这点很坑爹.

所以,能不能在 条形/柱形 上 增加一个显示排序的功能??不要用猜的好吗?!!!
同样,堆积 柱/条 能不能也增加一个 能计算堆积后的总数值的功能,同时可根据总数值进行排序?!!

**Comment by lianyzhou** [comment]
+1

**Comment by jamssssss** [comment]
+2

**Comment by preservance717** [comment]
+1
