### ISSUE TITLE
【咨询】eharts是否支持API调用方式？

### ISSUE THREAD

**Issue by w2009211777** [ecomfe/echarts#1602]
eharts是否支持API调用方式？如发送一些数据，然后返回给我一张图片文件。
我的需求是这样的：定时发送邮件，邮件内容包含图表信息。
但是发送邮件就是在后台完成的事情，并不与前台浏览器进行交互，因此图片无法生成，很苦恼

**Comment by upson** [comment]
我的理解是不能。
echarts是基于canvas的纯javascript engine，而你需要的是一个后台绘图工具。如果你非要用echarts的话，我能想到的可能的方法有两种:1.在后台跑js，直接通过echarts导出静态图片，2.另起一个http服务，通过访问服务上的echarts图，加上echarts的图片生成工具方法得到静态图片。

**Comment by LitterRoach** [comment]
我现在也有这个需求，有没有能通过后台跑js生成echarts图的例子

**Comment by hushicai** [comment]
echarts配合phantomjs是可以做到的。

**Comment by jessezhang1986** [comment]
我也有这样的需求，求办法
