### ISSUE TITLE
（急）请教个tooltip的问题，api里面有把hover出现tooltip的，改成click的么？谢谢！

### ISSUE THREAD

**Issue by pensacola1989** [ecomfe/echarts#1605]

**Comment by pensacola1989** [comment]
或者说axisPointer有没有相关的时间绑定的接口？

**Comment by Seven0711** [comment]
可不可以先把tooltip设为隐藏(show:false)，再添加点击事件，当点击时，把tooltip设置为显示(show:true)?

**Comment by pensacola1989** [comment]
@Seven0711 不行的。。axisPointer没有相关事件绑定的Api，只有数据图部分可以点击啊 。
