### ISSUE TITLE
请问tree可以支持反方向吗?

### ISSUE THREAD

**Issue by upson** [ecomfe/echarts#1608]
目前的水平方向的tree固定为root在左，从左往右；而垂直方向固定为从上往下。可以支持从右往左，从下往上的树吗？

例如，目前的水平方向tree，我尝试了series.rootLocation.x = 'right' ，结果不太对。

**Comment by loutongbing** [comment]
现在还不支持，我正在升级

**Comment by loutongbing** [comment]
谢谢 已经升级了 新增 direction: 'inverse'属性。下个版本上线。

**Comment by hbthanki** [comment]
Is this available with version 3.0?  When I tried [here](https://ecomfe.github.io/echarts-examples/public/editor.html?c=tree-basic), it is not working. Is `direction `property part of `series` or `option`?
Also I tried searching in docs but coundn't find.
Thanks.
