### ISSUE TITLE
dataZoom数据区域缩放组件可以将最大值拖到最小值前边

### ISSUE THREAD

**Issue by huguangju** [ecomfe/echarts#1609]
[http://echarts.baidu.com/doc/example/dataZoom1.html](http://echarts.baidu.com/doc/example/dataZoom1.html)

![792c8e58-9d27-4de2-8c16-fb05f4b56dac](https://cloud.githubusercontent.com/assets/6972433/7914233/54ddba44-08a8-11e5-82c0-6d7b0d68ac35.png)

> 有办法避免吗？

**Comment by HuaJson** [comment]
幸亏你用的横的dataZoom，你用到竖直dataZoom各种问题膈应死你
从echarts的源代码来看，dataZoom是允许最大值在最小值后面的，你可以自己写一个方法，绑定dataZoom事件
var ecConfig = require('echarts/config');
myChart.on(ecConfig.EVENT.DATA_ZOOM, doSomeThing);
function doSomeThing(param){
balabalabla~~
}

**Comment by HuaJson** [comment]
判断如果start>end 就恢复start,end到原来的值什么的
好像你需要refresh一下

**Comment by huguangju** [comment]
通过EVENT.DATA_ZOOM事件应该可以，不过太麻烦了，如果echarts提供选项可以自定义是否允许这种操作就好了
