### ISSUE TITLE
是不是数据多了最大值标记出现问题

### ISSUE THREAD

**Issue by sarsshitou** [ecomfe/echarts#1610]
![image](https://cloud.githubusercontent.com/assets/7335763/7927378/96c52f0a-0911-11e5-871d-7a24026bb866.png)

**Comment by sarsshitou** [comment]
markPoint 的气泡 漂浮的位置那个数据没有画出来，实际数据是有的

**Comment by sarsshitou** [comment]
@pissang

**Comment by pissang** [comment]
嗯，这个目前来看应该是折线图在对大数据量做优化的时候造成的。http://echarts.baidu.com/doc/doc.html#SeriesCartesian 参见这里的 dataFilter，可以把值设成 max 试试

**Comment by pissang** [comment]
想了想设置 max 的话最小值会出问题，应该改进，或者加一个关闭优化的选项

**Comment by sarsshitou** [comment]
谢谢
