### ISSUE TITLE
echarts 支持累加吗？

### ISSUE THREAD

**Issue by wuyazi** [ecomfe/echarts#1612]
比如数据为：1,2,3,4,5,6，用柱状图显示为：1,2,3,4,5,6
点一下按钮，显示的柱状图变为：1,3,6,10,15,21

**Comment by pissang** [comment]
不支持，在传入的数据上做处理吧

**Comment by longFeiLi** [comment]
只能重新setOption

**Comment by wuyazi** [comment]
已实现，我是在后端准备了两份数据，setOption 时刷新累加数据

**Comment by wuyazi** [comment]
感谢
