### ISSUE TITLE
（急急急）svg扩展类地图浏览器问题

### ISSUE THREAD

**Issue by handsometong** [ecomfe/echarts#1613]
echarts-2.2.2\echarts-2.2.2\doc\example中的例子map18.html只能在火狐浏览器中正常运行，ie和谷歌浏览器都有问题，是不是svg的图存在浏览器兼容问题？这个有没什么办法可以解决？

![Uploading QQ截图20150602144033.png…]()
![Uploading QQ截图20150602144159.png…]()

**Comment by handsometong** [comment]
echarts-2.2.2\echarts-2.2.2\doc\example中的例子map18.html只能在火狐浏览器中正常运行，ie和谷歌浏览器都有问题，是不是svg的图存在浏览器兼容问题？这个有没什么办法可以解决？

[Uploading QQ截图20150602144033.png…]()
[Uploading QQ截图20150602144159.png…]()

**Comment by hushicai** [comment]
不是svg存在兼容性问题，而是crhome对以`file:///`协议开头的ajax请求有限制。

解决办法：

* 搭建一个本地server
* 参考 #1626
