### ISSUE TITLE
setTheme时坐标轴的修改axisLabel的textStyle属性无效?

### ISSUE THREAD

**Issue by wuqi** [ecomfe/echarts#1617]
http://echarts.baidu.com/doc/example/theme.html  例子里可以重现,先进去,然后点dark跳到http://echarts.baidu.com/doc/example/theme.html#dark  页面,可以发现,坐标轴的字的颜色并没有改变,很暗

最新的firefox和opera都试了,暗的主题和亮的主题如果切换就会发现坐标轴上的字颜色很淡

**Comment by JenningsWu** [comment]
同遇到这个问题，感觉是bug，希望早日fix

**Comment by shawneezhao** [comment]
我也遇到这个问题，怎么解决啊~~

**Comment by wuqi** [comment]
这问题没解决啊....为啥关了?

**Comment by pissang** [comment]
2 的 setTheme 存在问题，所以在多个 theme 间切换会 “泄露” 配置项，3 里强制 theme 切换只能重新创建示例
