### ISSUE TITLE
折线图坐标axisLabel的改进方案咨询

### ISSUE THREAD

**Issue by zhoujiantao** [ecomfe/echarts#1618]
涉及直角坐标的axisLabel显示，目前的方案是设置合适的grid,以便在y轴左侧有足够的空间来显示label,但是，根据业务数据的不同，有时候可能label显示的文字长度很小或者很大，设置固定的grid就不合理，因为label太长，显示不下，有部分被截掉了，label都很小的话，左侧空间显得太大，想请问有没有其他方案

**Comment by hushicai** [comment]
空间有限，请自行按照业务场景调整grid的相关配置。
