### ISSUE TITLE
救命啊万分紧急烦看一下Echarts使用setOption添加数据时出现问题

### ISSUE THREAD

**Issue by HuaJson** [ecomfe/echarts#1621]
项目使用Echarts做监控图表,每过十秒钟从后台推送数据刷新前台显示图,我的做法是开始初始化图表,之后新数据来的时候,(因为每次推送上来的数据和之前可能完全不同,于是将坐标轴数据也放倒Option里面了),利用下面代码

stationChart.setOption({yAxis:[{data : yAxisData}],series:[{ data:seriesData}]});

来刷新图表数据,利用这个方法改了将近二十个柱状图和饼图.今天测试突然发现利用这种方法会造成残留数据的问题.

举个例子对于柱状图,假如以前有五个柱子,新数据会生成六个柱子,那么一切OK,动画效果也很漂亮,但是如果新数据会有四个柱子,那么原图仍然会存在五个柱子,残留的一个无法去掉.

求好心人帮帮忙,notMerge方法,addData方法我都试过了,都不好使,项目马上上线了确实挺着急的,而且图表中有大量DataZoom,尽量别使用init方法初始化Echarts,否则改动量将巨大.

**Comment by huguangju** [comment]
@HuaJson setOption之前clear了吗？
#894 

```javascript
stationChart.clear();
stationChart.setOption({yAxis:[{data : yAxisData}],series:[{ data:seriesData}]});
```

> 之前也遇到过

**Comment by HuaJson** [comment]
clear()一下就把整个图去掉了,白茫茫一片,不好使

**Comment by HuaJson** [comment]
而且我还需要保持原有的DataZoom的位置,clear()一下什么都没有了

**Comment by longFeiLi** [comment]
万能接口，配置图表实例任何可配置选项（详见option），多次调用时option选项默认是合并（merge）的，merge的设计可以让setOption很方便的成为更新任何属性的万能方法，比如你仅需要改title文字，则仅需要：
    setOption({title : {text : '新标题'}}); 
如果不需要，可以通过notMerger参数为true阻止与上次option的合并，如多次setOption间数据改变、长度不一致等的场景。     

注意setOption后面有个参数

**Comment by HuaJson** [comment]
stationChart.setOption({yAxis:[{data : yAxisData}],series:[{ data:seriesData}]},true);
这个我试过，加上之后图都不显示了，是我使用方法错误么

**Comment by HuaJson** [comment]
是我考虑不周全，已解决
代码如下，希望能帮到碰到我这个问题的朋友
  var dbChartOption=dbChart.getOption();
  dbChartOption.yAxis[0].data=dbStations;
  dbChartOption.series[0].data=sentRecords;
  dbChart.setOption(dbChartOption,true);

**Comment by corecible** [comment]
调用这个方法有些无法刷新

**Comment by zmwxiaoming** [comment]
getOption得不到option为啥

**Comment by hktalent** [comment]
@HuaJson 我想adddata，也就是不断的通过web socket添加新数据到地图，没有找到add的方法啊，请指导，谢谢

**Comment by Marylely** [comment]
我看官网推荐用setOption 如果还是想用这个的话 需要怎么解决呀
