### ISSUE TITLE
webpack能加载echarts吗？

### ISSUE THREAD

**Issue by luqin** [ecomfe/echarts#1624]

**Comment by standino** [comment]
+1

**Comment by standino** [comment]
npm 能够发现echarts-react  ，但是下载不了。是不是在开发中啊？

$ npm search echarts
NAME                  DESCRIPTION                                                  AUTHOR            DATE       VERSION KEYWORDS
avs-statechart        Statecharts for Node.js                                      =gigerlin         2014-03-10 0.1.6   statechart
bemuse-indexer        Parse and index BMS notecharts                               =dtinth           2015-05-20 1.2.0
d3pie                 A highly configurable, re-usable library built on d3.js for… =benkeen          2015-05-01 0.1.8   d3 piecharts charts graphs
dnode-smoothiecharts  Smoothie Charts middleware for DNode                         =chrispartridge   2011-05-14 0.0.1   dnode smoothiecharts charting
echarts-optimizer                                                                  =errorrik =ecomfe 2015-01-28 0.2.18
echarts-react                                                                                        2015-05-09
foxx_generator        Generate Foxx APIs using Statecharts and Domain Driven…      =moonglum         2014-11-27 0.5.1   foxx arangodb generator hypermedia
hexo-tag-googlecharts A hexo tag for inserting google charts in your blog.         =juampi92         2015-06-03 1.0.2
react-echarts                                                                                        2015-05-09
scion                 StateCharts Interpretation and Optimization eNgine (SCION)…  =jbeard           2012-09-13 0.0.10  scxml statecharts w3c javascript
scion-core            StateCharts Interpretation and Optimization eNgine (SCION)…  =jbeard4          2015-02-05 1.0.0   scxml statecharts w3c javascript
scion-ng              StateCharts Interpretation and Optimization eNgine (SCION)…  =jbeard           2013-05-14 0.1.2   scxml statecharts w3c javascript
scion-shell           A nodejs-based SCXML execution environment.                  =jbeard           2012-09-29 1.0.0   scxml statecharts w3c javascript shell
scxml                 An implementation of SCXML in JavaScript.                    =jbeard           2015-02-05 2.0.1   scxml statecharts w3c javascript
scxml-test-framework  A set of SCXML tests, and an HTTP client test runner for…    =jbeard           2012-04-03 0.0.1   scxml statecharts w3c javascript

**Comment by hushicai** [comment]
同 #1625

**Comment by hushicai** [comment]
这有个[例子](https://github.com/hushicai/echarts-develop/blob/master/webpack.config.js)，可以参考一下。

**Comment by uooo** [comment]
echarts webpack 版已发布到 npm ：

```sh
npm install echarts@2.2.7-beta7
```

```js
import echarts from 'echarts/src/echarts';
import 'echarts/src/chart/wordCloud';

let mychart = echarts.init(dom);
let charCloudOption = {...};
mychart.setOption(charCloudOption);
```
