### ISSUE TITLE
能否支持CMD规范？或者标准的AMD规范？

### ISSUE THREAD

**Issue by luqin** [ecomfe/echarts#1625]

**Comment by pissang** [comment]
请问哪里使用不标准的AMD规范了？

**Comment by luqin** [comment]
@pissang 我现在使用webpack打包js，webpack支持加载AMD规范的文件。其他第三方jquery插件都能加载，而echarts却加载失败。请问是什么原因？

**Comment by hushicai** [comment]
请仔细看一下webpack的[resolving](https://github.com/webpack/docs/wiki/resolving)。

**Comment by hushicai** [comment]
echarts支持标准的amd规范，但是webpack的[module resolving](https://github.com/webpack/docs/wiki/resolving)过程并不符合标准的amd规范。

echarts因为依赖于zrender，所以使用时，需要配置zrender的package信息：

```javascript
require.config({
    name: 'zrender'.
    location: 'dep/zrender/src', // 注意是src目录，而不是根目录zrender
    main: 'zrender'
});
```

echarts可以通过以上配置找到zrender，同样webpack要想打包echarts，也得找得到zrender才行。

根据官网的文档，可以通过alias找到zrender模块：

```javascript
    resolve: {
        alias: {
            zrender: path.join(__dirname, 'dep/zrender/src')
        }
    }
```

echarts有好多类似如下的代码：

```javascript
var zrender = require('zrender'); 
var CircleShape = require('zrender/shape/Circle');
```

当webpack打包时，发现`require('zrender')`时，会匹配alias，根据以上配置，发现require的是一个目录，那么就会到zrender所对应的目录（dep/zrender/src）中查找`package.json`文件，并取出main field字段，但是dep/zrender/src目录下并没有package.json（上一层目录中有），文件查找失败；发现`require('zrender/shape/Circle')`时，匹配alias之后，路径为dep/zrender/src/shape/Circle，文件查找成功。

找不到`require('zrender')`怎么办？

上面的配置是将alias分别指向zrender/src，假如我将alias直接指向zrender会怎么样？

```javascript
    resolve: {
        alias: {
            zrender: path.join(__dirname, 'dep/zrender')
        }
    }
```

这个时候，你会发现，require('zrender')可以通过zrender/package.json中的main field找到文件，但是require('zrender/shape/Circle')就找不到了，因为Circle文件实际路径是在zrender/src/shape/Circle.js，而alias匹配出来的路径是zrender/shape/Circle.js，文件不存在。

webpack打包失败的原因就是zrender多了一层src目录，并且package.json不在src目录下，而在实际require的时候又没有这一层src目录。

webpack如果能支持amd的packages配置就可以解决。

echarts不会改变现有的目录结构，如果你用webpack打包echarts，建议你看看webpack的module resolving过程，然后配合webpack，在相应目录下添加package.json即可。

至于你的jquery插件为什么能打包成功，这得视插件的目录结构而论了。

**Comment by luqin** [comment]
@hushicai 非常感谢，已经集成到webpack项目了。

**Comment by zhbhun** [comment]
我也遇到了类似的问题，可以参考我写的一个例子[webpack echarts](https://github.com/zhbhun/WebpackStudyDemo/tree/master/echarts)

**Comment by uooo** [comment]
echarts webpack 版已发布到 npm ：

```sh
npm install echarts@2.2.7-beta7
```

```js
import echarts from 'echarts/src/echarts';
import 'echarts/src/chart/wordCloud';

let mychart = echarts.init(dom);
let charCloudOption = {...};
mychart.setOption(charCloudOption);
```

**Comment by timqian** [comment]
Thanks for your efforts, @luqin. 请问只有 2.2.7-beta7 支持这种方式吗?  2.2.8 以及之后的版本支持吗?

**Comment by luqin** [comment]
@timqian 官方才2.2.7版本

**Comment by timqian** [comment]
2.2.8 了

**Comment by luqin** [comment]
@timqian 那就可以安装了

**Comment by timqian** [comment]
好的, thanks @luqin
