### ISSUE TITLE
(急)svg扩展类地图本地访问问题

### ISSUE THREAD

**Issue by handsometong** [ecomfe/echarts#1626]
echarts-2.2.2\echarts-2.2.2\doc\example\map18.html 在本地访问不能正常显示svg图，但是部署到服务器上就可以正常正常显示？这问题有什么好的方法可以解决吗？

**Comment by hushicai** [comment]
你是指在本地用`file:///xxx`访问？map18中的svg是通过ajax获取之后转换成xml传入echarts的；如果你想用`file:///xxx`而不是`localhost`来访问，ajax方式就不适用了。

如果你不想部署到服务器上，可以这么干：

* 将svg源文件中内容写到一个div中，比如：

```html
<div id="source" style="display: none;">
   svg源文件的内容...
</div>
```

然后，获取div#source的innerHTML:

```javascript
var source = document.getElementById('test').innerHTML;
```

当然你也可以直接将源文件内容写成一个js变量而不用将内容写到一个div上：

```javascript
var source = 'svg源文件的内容';
```

然后用[DOM-Parsing](http://www.w3.org/TR/DOM-Parsing/)将字符串内容解析成xml：

```javascript
var xml = new DOMParsing().parseFromString(source, 'text/xml');
```

_提示：IE下可以用ActiveXObject的XMLDOM来解析。_

svg地图扩展本质上就是将svg源文件内容解析成xml来用，不关心你用什么方式来获取svg源文件内容。
