### ISSUE TITLE
拖拽漫游时，边两端的箭头没有跟上

### ISSUE THREAD

**Issue by zjjott** [ecomfe/echarts#1627]
![image](https://cloud.githubusercontent.com/assets/3733548/7976760/b3a5b0e8-0ab2-11e5-9e79-be67517bbe34.png)
![image](https://cloud.githubusercontent.com/assets/3733548/7976762/beb5f3d0-0ab2-11e5-9b6a-77dbd0ddfa00.png)
如图所示

这个是BUG吧？还是feature？

**Comment by pissang** [comment]
同 #1604  已修复

**Comment by zjjott** [comment]
http://ecomfe.github.io/echarts-builder-web/ 从这个网页编译的js，为啥问题依旧存在。。。
