### ISSUE TITLE
柱状图的动画效果，可以从上到下么？

### ISSUE THREAD

**Issue by ioryloo** [ecomfe/echarts#1630]
因为业务需要，做了一个降雨倒挂图。柱状图的动画效果，一直是从下向上的。有什么办法，可以让动画是从上向下的呢？

**Comment by pissang** [comment]
抱歉没有直接的办法，试试传入负的数据然后用 formatter 在显示的时候再处理成正的

**Comment by ioryloo** [comment]
您说的方法我们已经试过了，动画方向一直是从下向上。感谢您的回复，期待以后的版本能完善这个效果。
