### ISSUE TITLE
可否直接显示一个身份的地图（不要全国地图）

### ISSUE THREAD

**Issue by hheedat** [ecomfe/echarts#1631]
假如我要用echarts直接显示一个山西省的地图，有没有这种例子...
我看官方的例子里面只有先显示全国的，然后再显示某个省份 [[URL]](http://echarts.baidu.com/doc/example.html)；
或者是类似香港扩展那样的 [[URL]](http://echarts.baidu.com/doc/example/map6.html)  ，
香港扩展那样的我在 [[URL]](http://ecomfe.github.io/echarts-map-tool/) 这个里面生成了山西省的数据，
然后仿照香港那种照猫画虎载入，发现不行啊...也不报错...

效果是这样的：
![image](https://cloud.githubusercontent.com/assets/5009547/7983308/9566a206-0af1-11e5-91b8-c06bf22e2963.png)

当然很有可能是我使用的姿势不对，不过相信把工具做的让我这种智商的人也能顺利使用，echarts就成功了...T-T  简单可依赖么...

希望echarts在开发的同时，也能注重下文档的体验，比如在地图生成页那里，下面的那个例子，
看起来是标签式单文件引入形式的，但是引入了http://echarts.baidu.com/build/dist/echarts-all.js 之后，发现会报错；比如在例子里面直接用到了<code> $.getJSON</code>，却从来没有告诉我要引用第三方的库，我还以为echarts自己实现了一套Ajax封装咧，等等；

搞开源不容易啊，祝愿echarts越来越好。

**Comment by pissang** [comment]
是不是编码不是 UTF-8?

**Comment by giscafer** [comment]
完全可以的。可以用这个转换https://github.com/giscafer/mapshaper-plus
