### ISSUE TITLE
请原生支持webpack

### ISSUE THREAD

**Issue by standino** [ecomfe/echarts#1632]
#1625 是可以解决webpack和echarts的集成。但是，为什么echarts不原生支持webpack以节省开发人员的时间。我是花了一天的时间才发现解决方案。

我希望可以用下面的方式直接使用echarts,不用关心echarts还需要依赖其他的包。

npm install echarts --save

然后在js文件中直接 require('echarts‘)

就这两步，不需要额外配置。谢谢。

**Comment by xieaolin** [comment]
支持！顺便求你的解决方案~~我也折腾一天了~~但是还没找到~~ @standino 

很奇怪为什么其他 AMD 标准的库都可以用 webpack 直接加载，但是 echarts 不能~~囧rz

**Comment by standino** [comment]
我的解决方案是  ： 
var React = require('react');
require('echarts/build/dist/echarts-all');
require('./echarts.css');
Echarts = React.createClass({
    renderChart: function () {
        if (!this.props.config) {
            throw newError('Config has to be specified, for the Highchart component')
        }

        var config = this.props.config;
        var node = this.refs.chart.getDOMNode();

        if (!config.chart) {
            config = React.addons.update(config, {chart: {$set: {}}})
        }

        config = React.addons.update(config, {chart: {renderTo: {$set: node}}});

        // 基于准备好的dom，初始化echarts图表
        var myChart = myChart || echarts.init(node);
        // 为echarts对象加载数据
        myChart.setOption(config);
    },

    componentDidMount: function () {
        this.renderChart();
    },
    componentDidUpdate: function () {
        this.renderChart();
    },
    render: function () {
        return <div id="echarts" className = "chart" ref = "chart" />
    }
});
module.exports = Echarts;

**Comment by xieaolin** [comment]
谢谢 @standino ~~你这个可以作为我最后的手段~~不过我还不想一上来就放弃治疗啊~~

我决定今天折腾一下深入研究下 webpack ，有进展了再来分享~~

**Comment by xieaolin** [comment]
折腾了 all day ~~不过收货还是不少：

1. 首先确认了 webpack 是按照 AMD 的规则办事的，只不过 echart 模块中对 zrender 的路径应该是配置了别名一类的东西，所以在 resovle.alias 中同样配置即可
1. echart 的 src 目录确实是 AMD 标准的模块，但是 build 目录下是包装过的代码，目的是为了兼容没有使用 requirejs 的小伙伴们直接通过 script 标签加载
1. echart 中 package.json 不符合 npm 标准的问题也很高解决，把 main 属性的值改为 src/echarts.js 就好了，zrender 同理

但是我最终放弃了使用 webpack 来打包 echarts，因为每次 build 都包含 echarts 实在太慢 (4000ms+)，而且加上其他依赖我这边第三方的包都有 2MB 了！囧~~

所以最后我换了个思路，用 jQuery.getScript 来动态加载 echarts 了，当然这也是因为我的业务中并非每个页面都需要 echarts :smile:

**Comment by luqin** [comment]
我的方案是：

1. webpack配置：

```
    resolve: {
        alias: {},
        modulesDirectories: ['node_modules', 'node_modules_custom'],
        extensions: ['', '.webpack.js', '.web.js', '.js', '.jsx']
    },
```
其中zrender放入node_modules_custom目录，zrender的文件请自行调整一下

2. 如何使用：

```
import echarts from '@my/echarts/src/echarts';
import '@my/echarts/src/chart/wordCloud';

let mychat = echarts.init(dom);
mychat.setOption(charCloudOption);
```

**Comment by kaiyuzhao** [comment]
@standino 请问，百度 echart 有没有计划在以后的版本中官方支持webpack呢？

**Comment by hushicai** [comment]
@kaiyuzhao  看你怎么用了，官方版本中echarts-all.js完全可以支持webpack的打包。

**Comment by kaiyuzhao** [comment]
@hushicai 多谢，那么将来支持单个图表的webpack打包吗？

如果使用uooo提供的forked echarts，在只需要wordcloud的情况下只导入 wordcloud就可以了。但echarts以后会不断更新更多功能，我的理解是如果想使用新版本，就得用echarts-all.js，除非uooo能不停的发布新的fork version。

我想问的是，百度官方在以后版本中是否会考虑集成使用uooo的webpack的方法呢？

**Comment by hushicai** [comment]
他那方法虽然可行，但似乎只是调整了zrender的目录结构。

这有个[例子](https://github.com/hushicai/echarts-develop/blob/master/webpack.config.js)，可以直接从源代码用webpack按需bundle！

研究一下webpack的plugin，你想怎么玩都行。

**Comment by uooo** [comment]
@kaiyuzhao 目前我的方案只是调整了依赖zrender的目录结构，通过url的方式直接依赖，但是这种方式不是长久之计。目前的echarts已发布到[npm](https://www.npmjs.com/package/echarts)，并且支持webpack单文件的按需require。我fork的readme中给的例子就是按需require。
我的fork中还需要改善对zrender的处理，并且能支持browserify。

**Comment by nttdocomo** [comment]
我用requirejs，但echarts经过uglify之后require调用就会报错，目前还找不到解决办法
