### ISSUE TITLE
echarts-x  map3d 旋转请教

### ISSUE THREAD

**Issue by yhduan** [ecomfe/echarts#1634]
您好：
       我使用echarts-x  map3d  word地图，设置了自动旋转。设置了定时器，想获取当前那个区域旋转到了正对着电脑屏幕前方，请指点。

      没有找到上述API，想获取地图当前的旋转角度，让后根据角度自己对应那个区域旋转到了前面，请问
我怎么才能获取到地图当前旋转的角度？

**Comment by pissang** [comment]
抱歉不能获取，你是想要通过这个实现什么功能？

**Comment by yhduan** [comment]
做自动导航，当前地图那个区域旋转到了屏幕前方，界面其他元素自动切换显示对应区域的业务数据

**Comment by yhduan** [comment]
echarts 是否有接口自动触发相关事件？  比如自动触发echarts map3d 的鼠标滑过事件，传递一个地图中间的坐标值给接口，通过定制鼠标滑过事件，在事件中获取事件参数得到滑过区域的信息

**Comment by pissang** [comment]
有鼠标点击或者滑过的事件，可以参考 http://echarts.baidu.com//x/doc/example/map3d_mix2.html

**Comment by yhduan** [comment]
多谢，我想要的是代码自动触发 echarts-x 的鼠标滑过的事件的方法，这样也能一定程度做到自动导航
