### ISSUE TITLE
折线图：多条折线数据 显示问题

### ISSUE THREAD

**Issue by halleytl** [ecomfe/echarts#1636]
我们有一个需求 a数据， b 数据，总数，默认当传入三条数据，折线图将会显示三条数据信息， 能不能设置在默认第一次加载的时候只显示我们关注的数据。当我们点击lenged的时候在显示其他的数据。

series:[
{
show：true， #true 显示，false 默认不显示数据。
}
]

**Comment by shady7shen** [comment]
http://echarts.baidu.com/doc/example/legend.html

注意“降水量”

**Comment by halleytl** [comment]
谢谢你给我的帮助非常大。
