### ISSUE TITLE
想问一下 ，echarts的时间响应支持不支持右键？？？

### ISSUE THREAD

**Issue by xushuo** [ecomfe/echarts#1637]
普通的右键插件很多，但是 echarts 的右键没有在文档中找到额？

**Comment by longFeiLi** [comment]
没有,你可以控制div的右键、

**Comment by xushuo** [comment]
div的右键不能获取到 echarts的相关数据啊。

**Comment by longFeiLi** [comment]
再加上个鼠标移动事件

**Comment by xushuo** [comment]
鼠标移动？？麻烦能否详细说下，我不太理解。

**Comment by longFeiLi** [comment]
就是用div控制右键 事件， 图表的移动事件      2个事件绑定一个变量。当右键的时候判断移动事件里面有没有值就可以了。

**Comment by xushuo** [comment]
恩，谢谢。只是我在网上找到右键菜单JS是封装好的。不知道怎么 触发右键响应事件

**Comment by pissang** [comment]
把 click 事件绑定在根 dom 节点上，至于怎么判断是否是右键触发的网上有很多资料

**Comment by xushuo** [comment]
我已经解决啦。谢谢啦

**Comment by sliontc** [comment]
@xushuo ,请问是怎么解决的？

**Comment by sliontc** [comment]
我想用在力导向图里，删除节点

**Comment by gangyahaidao** [comment]
http://gallery.echartsjs.com/editor.html?c=xHySt3pEpx
可以参考这个例子
