### ISSUE TITLE
实例方法中关于事件有了绑定on方法和解绑un方法，能不能加一个触发的fire方法呢

### ISSUE THREAD

**Issue by kinjee** [ecomfe/echarts#1639]
业务中肯定会遇到需要个性化关联触发的事件，如果有了fire，应用灵活多了，you see?

**Comment by pissang** [comment]
如果想要触发鼠标事件的话，你可以搜索一下 dom 事件触发相关的，如果是其它例如dataZoom的事件的 it depends
