### ISSUE TITLE
require.js加载echart.amd.js完美。。换成esl加载echart.amd.js就悲剧了

### ISSUE THREAD

**Issue by zhump** [ecomfe/echarts#1646]
这种写法，require.js可以完美展示出echarts.amd.js中的图形。没有任何问题
![image](https://cloud.githubusercontent.com/assets/7962067/8030270/23bbf87c-0df8-11e5-8757-759807173b5c.png)
可只要把代码片段中的require.js换成 esl,直接就悲剧了 什么都出不来。。。
esl该怎么使用 echarts.amd.js，求指点
![2222222222](https://cloud.githubusercontent.com/assets/7962067/8030346/beebfd88-0df8-11e5-8a05-1010087ac3e1.png)

**Comment by errorrik** [comment]
你这不是AMD的用法，只是利用了requirejs额外提供的一些功能，把async require存粹当作加载script文件用了。

`echarts.amd.js`文件里面包含了`echarts`、`zrender`、以及其他的一些模块定义，但是并不包含`ET`模块的定义，`ET`模块永远都不会ready，所以你的第一个callback压根就不会执行。

既然你只是想存粹的加载文件，建议使用一个单独的script标签

```html
<script src="echarts.amd.js"></script>
<script>
require.config({
  // ......
});
require(['echarts', 'echarts/theme/red', 'echarts/chart/bar'], function () {
  // ......
});
</script>
```

**Comment by pissang** [comment]
@zhump 这个问题如果想要继续探讨的话可以去 [esl](https://github.com/ecomfe/esl) 那提个 issue

**Comment by zhump** [comment]
果然可以了。。谢谢。。


![j 4 v p_5fiu52vfy10zjlo](https://cloud.githubusercontent.com/assets/7962067/8051218/6511d152-0eac-11e5-8d1c-b0fb3f4eeb89.gif)
