### ISSUE TITLE
发现一个 tooltip 的坑，显示不正确的坑

### ISSUE THREAD

**Issue by hheedat** [ecomfe/echarts#1651]
![qq 20150609190145](https://cloud.githubusercontent.com/assets/5009547/8056408/54085b00-0eda-11e5-90f3-e36eaafcfe13.png) ![qq 20150609190221](https://cloud.githubusercontent.com/assets/5009547/8056409/5408cab8-0eda-11e5-83d7-9d77eecbb8f1.png)

鼠标悬浮上去的时候，tooltip 的样式一直不符合预期，最开始我以为是下载的 echarts 版本有问题，结果引用了百度 cdn 的地址，还有问题，可是引用百度 cdn 地址的另一个项目没有问题，咋回事咧？

我各种找原因，最后发现是由于在某个父级元素下，有个 CSS 是 <code> div { height:500px } </code>，而 tooltip 原来是 DOM 元素，哈哈。这个问题花了我一个小时来研究...┑(￣Д ￣)┍

建议在文档上表明一下，给出个注意事项；

**Comment by rikan** [comment]
div { height:500px }  就没有人会这样写

**Comment by hheedat** [comment]
@rikan 未必吧，比如在某个CSS class下面有一些div，有需求的话在范围内写个div { height:500px } 有何不可，就不必再起个class名了

**Comment by rikan** [comment]
@hheedat 你不就是遇到了这个问题了? 就算在某个范围内(从你的问题可以看到这个范围并不小),你无法保证将来别人或别的库以后会不会添加新的div,这些别人的元素会不会受你的影响.所以要避免使用你这种根据标签设置,特别是div,span这样的东西.我觉得会有更好的解决方案,这种暴力的方法不是唯一的方法.如果实在是真要这么做,也是要把你的范围缩小的最小.

**Comment by hheedat** [comment]
@rikan 你说的有道理；

哈哈，我只是建议在文档还是哪里描述一下，告诉这个东西其实是DOM元素，哈哈，无所谓啦
