### ISSUE TITLE
请问能否支持国际化

### ISSUE THREAD

**Issue by easyreal** [ecomfe/echarts#1653]
首先对开发组表示敬意，真的非常专业，一点不比FusionChart和AnyChart差，但是有个小问题，就是不支持国际化，外国人或者外国项目没法用，能不能考虑支持一下？

**Comment by diysimon** [comment]
我们有英文版
http://echarts.baidu.com/index-en.html

**Comment by easyreal** [comment]
谢谢回复，我是为公司的一个项目做图表选型，这个项目要求支持国际化，可能不只是英文，我看需要国际化的地方主要是toolbox.js，如果里边的标签允许通过外围自定义的话也可以解决这个问题，谢谢

**Comment by pissang** [comment]
见 #1171

**Comment by easyreal** [comment]
谢谢，问题已解决

**Comment by lestchun** [comment]
@diysimon   http://echarts.baidu.com/index-en.html  这里面的地图  省份 显示的是 中文的

**Comment by simonguo** [comment]
好像只能通过nameMap 进行设置

**Comment by fanzhengbiao** [comment]
可以参考下官方的数据注入，china的各省份和地区是可以通过外部的json文件进行数据注入，从而达到国际化效果。

**Comment by GendSmith** [comment]
请问yAxis和legend有办法配置吗，文档写的的是yAxis的name的类型是string
