### ISSUE TITLE
数据缩放轴上没有显示一些刻度（dataZoom）

### ISSUE THREAD

**Issue by blueicetodo** [ecomfe/echarts#1658]
在实际使用组件的过程中遇到了客户的挑战，问题是在数据缩放轴上没有显示一些刻度，比如我们有些数据是2000年至2015年，我们希望在缩放轴上显示一些刻度，如2000,2001,2002...2015等值，不知道如何实现呢?

类似HighStock的样子

**Comment by Ovilia** [comment]
试试 `xAxisIndex`
