### ISSUE TITLE
(急)您好！请教个svg扩展问题！

### ISSUE THREAD

**Issue by handsometong** [ecomfe/echarts#1659]
我自己画的svg图中的文字显示不出来，而且鼠标移动图上整个图都会加上黄色的底色？用你们的baidu-building.svg就不会，但是football.svg也会，这个是什么原因造成的，有没什么解决方案。
![qq 20150610170134](https://cloud.githubusercontent.com/assets/12708876/8079395/b2ebe486-0f96-11e5-9803-a6ad3c08b289.jpg)
![qq 20150610171656](https://cloud.githubusercontent.com/assets/12708876/8079402/bbc0b03c-0f96-11e5-85b5-d943bfe503f4.jpg)
![qq 20150610173141_](https://cloud.githubusercontent.com/assets/12708876/8079407/c1d8af74-0f96-11e5-9db1-1862e279c241.jpg)

**Comment by EGGD** [comment]
您好  我想问下这个问题解决了吗  如果解决了的话可以方便告知一下吗

**Comment by handsometong** [comment]
记得好像设置下一个什么属性就可以了，认真看下文档，文档里有，具体什么属性我也忘记，太久了

**Comment by EGGD** [comment]
我找到那个属性了 谢谢谢谢 帮大忙了
