### ISSUE TITLE
图例(legend)太多 会和数据区重叠着， 可以自动分配宽度不

### ISSUE THREAD

**Issue by zhaoyangsoft** [ecomfe/echarts#1661]
![image](https://cloud.githubusercontent.com/assets/1456421/8098165/c4232e16-101e-11e5-959b-8ecaf2759335.png)

**Comment by hushicai** [comment]
空间有限，目前不能自动分配宽度，需自行通过echarts提供的配置项合理安排布局。

**Comment by xfworld** [comment]
@hushicai  echarts提供的配置项哪儿有相关的例子说明啊？

**Comment by xiaoke4869** [comment]
Hi,楼主解决了吗？
