### ISSUE TITLE
【Bug Reporting】容器边缘滑入动画抖动

### ISSUE THREAD

**Issue by rinnko** [ecomfe/echarts#1662]
最近准备用echarts绘制统计报表，使用中发现了一些问题
1. 当容器右边距不足以容纳tooltip的宽度时，tooltip框会有一个向左滑入的动画。然而当鼠标悬停在该元素上时，tooltip框会出现抖动，疑似是在鼠标进入该区域时忘记解绑触发该动画的事件。详情参见[echarts测试页](https://github.com/ecomfe/echarts/blob/master/test/allchart/all.html)的第五个图，将鼠标移到右侧饼图靠近容器边缘的一部分就可以复现这个问题。
![pgq 952hdbgqxu066 l ir3](https://cloud.githubusercontent.com/assets/7036875/8103283/e2484576-1059-11e5-8db2-1c135ac30a5f.png)

2.[echarts测试页](https://github.com/ecomfe/echarts/blob/master/test/allchart/all.html)最后一张图不能绘制，控制台报错*Uncaught TypeError: Cannot read property 'length' of undefined*。经查证，[echarts测试页](https://github.com/ecomfe/echarts/blob/master/test/allchart/all.html)第1812行应该为data而不是eventList。
3.目前鼠标在数据点上移动时，tooltip会有明显的卡顿，这个问题是否能够解决？

**Comment by Ale-cc** [comment]
解决办法 tooltip 设置延迟、关闭动画，新版本也还存在这问题。

tooltip: {
          showDelay: 500,
          hideDelay: 500,
          transitionDuration: 0,
        },`
`
