### ISSUE TITLE
ECharts docs data

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#1665]
Hi ECharts team!
I'd like to write a content assist plugin for ECharts and was thinking if you have your documentation generated from somewhere that can be converted into JSON? If not, any plans on that? :)

Thanks, 
Jaro

**Comment by diysimon** [comment]
We are reorganizing the document now, maybe we'll release it in Aug.

what kind of the plugin you said? in code editor for code assist?

sorry for my poor english :)

**Comment by jarben** [comment]
Sounds good, let me know when something is ready to be tested:)

Yeah, it's a content assist plugin for the ace.c9.io (using esprima.org to get caret position in the echarts config)

**Comment by jarben** [comment]
Just noticed the docs schema - excellent - is this somewhere on github? Or can I just use: 
http://echarts.baidu.com/docv/data/schema/optionSchema.json?_v_=1.0.4

for the content assist?

**Comment by pissang** [comment]
This schema is used in the the [option tool](http://echarts.baidu.com/doc/option.html).
