### ISSUE TITLE
为什么tree不显示

### ISSUE THREAD

**Issue by textboy** [ecomfe/echarts#1669]
项目中之前用到line,bar,pie等图，突然这次要用到tree图，但是用tree怎么都没有图显示，后台也没报错，如果把series > data > children 去掉然后换成用pie图就没问题。tree.js 已经换成github上的最新代码。请教这是什么情况？
代码精简如下：
				//绘制表
				require(
						[
						 'echarts',
						 'echarts/chart/tree'
						 ],
						 function (ec) {
							var myChart = ec.init(document.getElementById('names_chart'));
							var option = {
									title : {
										text: '级别对应人员图'
									},
									series : [
											{
											    type:'tree',
											    name : "Force tree",
											    data : [
										                {
										                    name: '根节点',
										                    value: 60
										                    ,
										                    children: [
										                               {
										                                   name: '节点2',
										                                   value: 40
										                               }
										                           ]
										                }
										            ]
											}
									]
							};
							myChart.setOption(option);
						}
				);//======end require=======

**Comment by hushicai** [comment]
这段代码在我这是正常的。

![image](https://cloud.githubusercontent.com/assets/1249423/8175777/3dba6e86-1422-11e5-8365-f4212e94b951.png)

设备：chrome
