### ISSUE TITLE
echar地图小数点进度的问题

### ISSUE THREAD

**Issue by lsj304** [ecomfe/echarts#1670]
我使用的是map地图，
数据是---地区消费花销 : 
北京:1297.68, 天津:594.83, 上海:1273.74, 重庆:929.69, 河北:1702.21, 河南:1798.40, 云南:1459.32, 辽宁:1959.94, 黑龙江:1196.25, 湖南:1855.19, 安徽:1098.19, 山东:874.52, 新疆:1327.16, 江苏:1168.39, 浙江:1363.85, 江西:1825.19, 湖北:903.24, 广西:1547.14, 甘肃:1347.88, 山西:1545.23, 内蒙古:1373.61, 陕西:736.35, 吉林:1117.71, 福建:1142.59, 贵州:741.93, 广东:1418.01, 青海:1193.99, 西藏:1360.41, 四川:1806.94, 宁夏:623.81, 海南:1316.59, 香港:1209.83, 澳门:1830.70, 北京:18910.15, 天津:28483.45, 上海:12921.93, 重庆:4812.69, 河北:27092.39, 河南:11563.89, 云南:8228.28, 辽宁:16173.90, 黑龙江:8130.55, 湖南:12027.24, 安徽:15749.83, 山东:13968.73, 新疆:10792.78, 江苏:15764.25, 浙江:5385.29, 江西:24054.52, 湖北:16204.34, 广西:26406.27, 甘肃:12592.70, 山西:13009.71, 内蒙古:4874.88, 陕西:12805.99, 吉林:29841.99, 福建:11273.69, 贵州:14503.18, 广东:21946.73, 青海:4687.02, 西藏:11178.83, 四川:19284.39, 宁夏:9679.86, 海南:22361.60, 香港:10436.09, 澳门:15282.84
其中没有任何小数位超过了2位小数，但是在地图上显示却是很多位小数，我在series上设置了mapValuePrecision ： 2但是也没有效果

**Comment by hushicai** [comment]
#1713
