### ISSUE TITLE
Treemap feedback

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#1674]
I've been playing with the new treemap chart and noticed few things: 
- I'm not able to show labels on sub items (the drill down example)
- There is 1px border when using childBorderWidth:0, should be 0. Setting anything different that 0 works as expected. 
- I can't get rid of the text at the left bottom corner (the breadcrumb?), shows the name property in the series, I need to set name:''. I've tried breadcrumb:{show:false} but that doesn't help

Anyway, really glad to see all the new charts in 2.2.3!

**Comment by loutongbing** [comment]
hi thank you for using the treemap chart.
please give me your options that can not work.

**Comment by jarben** [comment]
Hi, here is the code: 
{
    "series": [
        {
            "name": "test",
            "type": "treemap",
            "itemStyle": {
                "normal": {
                    "label": {
                        "show": true,
                        "formatter": "{b}"
                    },
                    "childBorderWidth": 0,
                    "childBorderColor": "#ffffff",
                    "borderWidth": 0,
                    "borderColor": "#ffffff"
                },
                "emphasis": {
                    "label": {
                        "show": false
                    }
                }
            },
            "data": [
                {
                    "name": "Monday",
                    "children": [
                        {
                            "name": "test1",
                            "value": 10
                        },
                        {
                            "name": "test2",
                            "value": 20
                        },
                        {
                            "name": "test3",
                            "children": [
                                {
                                    "name": "test a",
                                    "value": 10
                                },
                                {
                                    "name": "test b",
                                    "value": 20
                                },
                                {
                                    "name": "test c",
                                    "value": 30
                                }
                            ],
                            "value": 30
                        }
                    ],
                    "value": 100
                },
                {
                    "name": "Tuesday",
                    "value": 20
                },
                {
                    "name": "Wednesday",
                    "value": 40
                },
                {
                    "name": "Thursday",
                    "value": 60
                },
                {
                    "name": "Friday",
                    "value": 60
                },
                {
                    "name": "Saturday",
                    "value": 75
                },
                {
                    "name": "Sunday",
                    "value": 70
                }
            ]
        }
    ]
}

and here is the output: 
![image](https://cloud.githubusercontent.com/assets/561365/8233351/18c808d0-15d6-11e5-977e-30b1ad8ea1c0.png)

- childBorderWidth:0 should render child items without border
- not sure how to display labels test1, test2, test3
- seems like there are only two levels of data supported, test a, test b, test c is not considered
- sorry, the breadcrumb:{show:false} works fine

Anyway, this is an awesome chart!

**Comment by loutongbing** [comment]
I will research it.  Please wait for days.

**Comment by loutongbing** [comment]
- I have fixed the bug of childBorderWidth:0. You will see it in the next version.
- not support to display sub labels and sub sub data, because we cant find a good way to show them. You have to make use of drilling down
My English is not so good. If you cant understand, you can commit again :)

**Comment by jarben** [comment]
Thanks for that! 
Regarding sub data, what if you do something that d3.js does, for example: 

![image](https://cloud.githubusercontent.com/assets/561365/8390406/37c456f8-1c93-11e5-9418-e6179757f829.png)

the structure of this tree map is: 
root
    - button
    - tabset
        - tab
        - tab
            - button
            - button

Which means parents with children don't show label - they are just containers. This allows better control of how things group.

Thanks again!

**Comment by jarben** [comment]
sorry, the structure got flatten after commenting, here is a snip: 

![image](https://cloud.githubusercontent.com/assets/561365/8390423/d423c6b4-1c93-11e5-9f20-9d8cb648dde8.png)

**Comment by loutongbing** [comment]
we dont support it now.  sorry.

**Comment by jarben** [comment]
no problem - thanks a lot for the border fix in 2.2.5!
