### ISSUE TITLE
想问下Qt QML当中是否可以使用该js库？

### ISSUE THREAD

**Issue by toby20130333** [ecomfe/echarts#1675]
echarts绝对给力的图表库，想应用到桌面当中来，也就是pc客户端当中，而且QML是支持js扩展的，兼容绝大多数js语法，但是需要纯js的图表库，不知道echarts是否可以胜任，当然需要改动大量源码。谢谢

**Comment by hushicai** [comment]
这取决于qml的javascripthost environment能否支持dom。

**Comment by toby20130333** [comment]
QML不支持DOM 只支持canvas 画布，基本包含html的画布的大部分特性，PS，js图表库Charts是可以移植到QML当中的，想咨询下echarts能否切入其中  charts的项目是 https://github.com/jwintz/qchart.js/tree/master  麻烦您看看

**Comment by pissang** [comment]
如果不支持 DOM 的话是无法使用 ECharts 的。

**Comment by 0312birdzhang** [comment]
@toby20130333 https://github.com/jwintz/qchart.js/tree/master  这个看上去不错的样子，按理说echarts也可以。

**Comment by toby20130333** [comment]
@0312birdzhang 你觉得可行吗？有兴趣 可以阅读 www.heilqt.com

**Comment by 0312birdzhang** [comment]
@toby20130333 Qt5.7还有十几天就来了，有Qt Charts，看上去实现的不错 :smiley: ，不用造轮子了
