### ISSUE TITLE
ajax跟echarts的结合示例感觉不好找

### ISSUE THREAD

**Issue by chaegumi** [ecomfe/echarts#1676]
通过百度是百度到了，但是官网有没有示例

**Comment by hushicai** [comment]
请详细描述问题。

**Comment by chaegumi** [comment]
就是echarts的数据用ajax获取的完整示例代码，我现在是这样做的
$.getJSON(BASE_URL + 'manage/stat_user_summary/data?callback=?&', function(data){
										var html = '';
										for(itm in data.data){
											html += '<tr><td>' + itm + '</td><td>' + data.data[itm] + '</td></tr>';
											option.xAxis[0].data.push(itm);
											option.series[0].data.push(data.data[itm]);
										}
										$('#detaildata').html(html);
										myChart.setOption(option);
									});
