### ISSUE TITLE
使用了datatable这个插件，再引入echarts的话，会出现

### ISSUE THREAD

**Issue by chaegumi** [ecomfe/echarts#1680]
$.extend( $.fn.DataTable.defaults, {
			responsive:true,
			processing: true,
			serverSide:true,
			language:{
					"processing": "数据加载中",
					"lengthMenu": "每页显示 _MENU_ 条记录",
					"zeroRecords": "没有符合条件的记录",
					"info": "显示第_PAGE_/_PAGES_页, 总共_TOTAL_条记录",
					"infoEmpty": "显示第0 / 0记录, 总共0条记录",
					"emptyTable": "没有符合条件的记录",
					"infoFiltered": "(最多 _MAX_  总记录)",
					"infoPostFix": "",
					"search": "搜索",
					"url": "",
					"paginate": {
						"first":    "第一页",
						"previous": "上一页",
						"next":     "下一页",
						"last":     "最后一页"
					}
				}
		});

以下错误
Uncaught TypeError: Cannot read property 'defaults' of undefined

**Comment by hushicai** [comment]
这点信息很难定位问题，请详细地描述一下问题。

**Comment by chaegumi** [comment]
http://stackoverflow.com/questions/26165263/datatables-uncaught-typeerror-cannot-read-property-defaults-of-undefined

**Comment by chaegumi** [comment]
可能是我自己使用上出问题了，不是冲突。
