### ISSUE TITLE
x轴为时间序列时，多组数据使用柱状图展示问题

### ISSUE THREAD

**Issue by alaxli** [ecomfe/echarts#1682]
参考http://echarts.baidu.com/doc/example/line8.html# 使用时间坐标进行柱状图展示，发现多组数据展示时会覆盖，是否可以按照标准柱状图或者堆积柱状图进行展示？谢谢
多组数据生成按照series1 data的方式，时间一致，数据为随机数乘以不同数值生成。

**Comment by pissang** [comment]
可以使用 category 类型而不是 time 类型，time 类型会把坐标轴当做数值轴处理
