### ISSUE TITLE
时间坐标最小精度到分，每分钟只显示了1条数据，其余数据不显示

### ISSUE THREAD

**Issue by Syingying** [ecomfe/echarts#1683]
请教个问题！网上找不到相关答案。。如题，时间坐标最小精度到分，每分钟只显示了1条数据，其余数据不显示。比如，数据为[12:00:01,12:00:12,12:00:56,12:01:11]这种形式，然后只能显示12:00:56和12:01:11.谢谢！

**Comment by pissang** [comment]
如果你指的是刻度的话，时间轴在 echarts 中属于数值类型，对于数值类型的坐标轴 echarts 会根据数据的范围，配置的 splitNumber 去调整坐标轴上的刻度。如果你一定要所有都显示的话可以配置成 category 类型而不是 time 类型。

**Comment by bestplay** [comment]
I think i fixed it.


    return {
        name: now.toString(),
        value: [
            [**now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/') + " " + now.getHours()+":"+now.getMinutes()+":"+now.getSeconds(),**
            Math.round(value)
        ]
    }
