### ISSUE TITLE
自己画的svg，文字部分显示不出来，是不支持吗？

### ISSUE THREAD

**Issue by handsometong** [ecomfe/echarts#1684]
其他部分都很正常，下面是svg的文本部分
![qq 20150616140030](https://cloud.githubusercontent.com/assets/12708876/8176743/220a19d0-1430-11e5-86f8-b21cbde4645e.jpg)

**Comment by pissang** [comment]
恩目前是不支持

**Comment by handsometong** [comment]
我想在右上角加些备注文字，有什么解决方法吗
![qq 20150617114259](https://cloud.githubusercontent.com/assets/12708876/8199330/020721d0-14e6-11e5-9847-f4b25bf6af99.jpg)
