### ISSUE TITLE
有考虑增强 legend formatter 么？

### ISSUE THREAD

**Issue by Phinome** [ecomfe/echarts#1690]
R;T

现在的 legend 的 formatter 参数只有 name ，不能通过该方法实现类似与如下的效果：

![https://cloud.githubusercontent.com/assets/9817065/5215016/fe196fc8-765d-11e4-93b2-d2bbf9c5ab49.JPG](https://cloud.githubusercontent.com/assets/9817065/5215016/fe196fc8-765d-11e4-93b2-d2bbf9c5ab49.JPG)

@kener 在 #968 中提供了解决方案，但还是不太够，而且通过该方案实现后，图例的形状没法改变。因此，提问。

Thx

**Comment by hushicai** [comment]
只能通过 #968 的方案解决。
