### ISSUE TITLE
when set legend data is a number, the icon is gray and disable.

### ISSUE THREAD

**Issue by free421xiaobai** [ecomfe/echarts#1691]
option = {

...
legend:{
data:[1, 2]
}
}

**Comment by free421xiaobai** [comment]
if two series name is same and only the first series icon in legend will show

**Comment by pissang** [comment]
讲中文？

**Comment by free421xiaobai** [comment]
图例区域如果是数字的话，图标是灰色的；如果两个图例名字重复，只有第一个图例的图标会显示出来。。
