### ISSUE TITLE
nodes(data)中的{string} label  是否可以不仅能默认显示name作为标签 ？

### ISSUE THREAD

**Issue by liupengyuan** [ecomfe/echarts#1693]
即设一个label 的{string}text属性，设为非默认的文本值？

**Comment by pissang** [comment]
可以使用 node 的 label 属性

**Comment by liupengyuan** [comment]
示例给出的nodes以及文档说明中没有label属性应该如何设置非默认值吧？

nodes:[
                {
                    category:0, name: '乔布斯', value : 10,
                    symbol: 'image://http://www.damndigital.com/wp-content/uploads/2010/12/steve-jobs.jpg',
                    symbolSize: [60, 35],
                    draggable: true,
                    itemStyle: {
                        normal: {
                            label: {
                                position: 'right',
                                textStyle: {
                                    color: 'black'
                                }
                            }
                        }
                    }
                },
                {category:1, name: '丽萨-乔布斯',value : 2},
                {category:1, name: '保罗-乔布斯',value : 3},
                {category:1, name: '克拉拉-乔布斯',value : 3},
                {category:1, name: '劳伦-鲍威尔',value : 7},
                {category:2, name: '史蒂夫-沃兹尼艾克',value : 5},
                {category:2, name: '奥巴马',value : 8},
                {category:2, name: '比尔-盖茨',value : 9},
                {category:2, name: '乔纳森-艾夫',value : 4},
                {category:2, name: '蒂姆-库克',value : 4},
                {category:2, name: '龙-韦恩',value : 1},
            ],

**Comment by pissang** [comment]
> {string} label		节点标签名称，默认显示name作为标签
