### ISSUE TITLE
请问renderAsImage选项是否支持设置背景色？

### ISSUE THREAD

**Issue by fywstar** [ecomfe/echarts#1694]
图表本来是使用默认的backgroundColor，即透明。
调用 setOption({renderAsImage: true})后就变成白色背景了。
getImage()返回的图片也是白色背景。
想让得到的图片仍然是透明背景，请问是否有办法解决？

**Comment by hushicai** [comment]
renderAsImage时，backgroundColor默认值被重置为#fff。

文档中似乎没有特殊说明这种情况。

如果你想要透明的图片，需要手动设置backgroundColor为`rgba(0, 0, 0, 0)`。
