### ISSUE TITLE
yAxis的max设置小于5的整数，永远是5

### ISSUE THREAD

**Issue by somax** [ecomfe/echarts#1696]
![2015-06-18 3 29 41](https://cloud.githubusercontent.com/assets/5010811/8226192/ec94df2e-15ce-11e5-84f4-2c39d482988b.png)
![2015-06-18 3 29 46](https://cloud.githubusercontent.com/assets/5010811/8226191/ec8d31fc-15ce-11e5-9250-ec135a32dfb2.png)
当我设置成有小数的值的时候，确可以正确显示
![2015-06-18 3 29 16](https://cloud.githubusercontent.com/assets/5010811/8226193/ec980af0-15ce-11e5-811b-1fa17e4116eb.png)
![2015-06-18 3 29 09](https://cloud.githubusercontent.com/assets/5010811/8226194/ecc16d14-15ce-11e5-9338-7aa98db6aa8b.png)

**Comment by rikan** [comment]
这是个坑,对于整数,min和max都要设置才能起作用,你可以试一下
