### ISSUE TITLE
map中series.markPoint:{ geoCoord:{'山西':[110.15,34.50]} } 会导致地图无法显示，并且报错

### ISSUE THREAD

**Issue by zameol** [ecomfe/echarts#1703]
根据API文档可进行经纬度标注，如上代码，但实际操作会报错：
Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by hushicai** [comment]
markPoint.data是必选项。

**Comment by hushicai** [comment]
@pissang 

文档中所说的`series[i].markPoint.geoCoord`似乎是无效的？

`series[i].geoCoord`或`series[i].markPoint.data[i].geoCoord`才有效果。

**Comment by zameol** [comment]
markPoint:{
                geoCoord:{'山西':[110.15,34.50]},
                data:[{name: '标注1', value: 100}]
            }，没效果啊

**Comment by zameol** [comment]
markPoint:{ data:[{
                    name: '标注1', 
                    value: 100, 
                    geoCoord:{
                        '山西':[110.15,34.50]
                    }}]
            }也没效果

**Comment by hushicai** [comment]
`series[i].markPoint.data[i].geoCoord`直接是个数组。

```javascript
markPoint: {
    data: [{name: '山西', value: 100, geoCoord: [110.15, 34.50]}]
}
```

**Comment by hushicai** [comment]
还有一种配置：

```javascript
markPoint: {data: [{name: '山西', value: 100}]},
geoCoord: {'山西': [110.15, 34.50]}
```

**Comment by zameol** [comment]
恩，太感谢了！不过，API文档描述的确有误，希望改一下

**Comment by hushicai** [comment]
已修正  a6135703f3de0a4dddd17f67068f92967423bfc7
