### ISSUE TITLE
关于标签式单文件的主题加载问题

### ISSUE THREAD

**Issue by yevon-cn** [ecomfe/echarts#1705]
首先提个http://echarts.baidu.com/doc/example/theme.html 下载主题的bug，当我选择dark主题，然后点下载，弹出的是http://echarts.baidu.com/doc/example/theme/%5Bobject%20Object%5D.js 因此导致无法下载。
然后就是我想问的问题：
因为从官网下载的主题js文件都是用define方式定义的，似乎只适用于“模块化单文件引入”，如果我要用“标签是文件引入”的话，请问我该如何在不修改从官方下载的dark.js主题的情况下使用dark主题？

**Comment by hushicai** [comment]
那只是一个示例。

如果是标签引入的话，你需要修改主题文件。
