### ISSUE TITLE
legend 的data字段添加alias……

### ISSUE THREAD

**Issue by halfblood369** [ecomfe/echarts#1706]
伟大的作者，请问legend的data字段能不能添加alias属性，感觉这个需求挺强烈的……
因为想在图标中显示每个item的数量，但是又不想所有地方都如此，这个时候alias属性的优势就出来了。有alias则显示alias，没有就用name。
期待你的回复……

**Comment by pissang** [comment]
可以使用 `legend.formatter` 对部分 item 加上数量
