### ISSUE TITLE
请问2.0+的版本是否向下兼容

### ISSUE THREAD

**Issue by anyexinglu** [ecomfe/echarts#1707]
题主的项目一直用1.4.1的echarts，现在需要加一个漏斗(funnel)的类型，发现funnel只有在2.0+的版本才有。于是想到两种解决方法：（1）将项目中的echarts升级到最新版本（但是这样需要改动的板块比较多）。（2）修改funnel的代码，加入到项目依赖的1.4.1版echarts模块中。—— 题主尝试这种方法，发现funnel.js依赖的一些文件（如base.js等）在1.4.1里并没有，所以猜测2.0+的版本并未向下兼容，也就是说，如果采用方法（2），需要添加/修改的文件除了funnel.js还有其他一些文件吗？

**Comment by pissang** [comment]
向下兼容是 1.4.1 的 option 可以使用在 2.0+ 上，单独的图表模块必须在同一版本中使用
