### ISSUE TITLE
力导向图如果draggable=true，那么单击节点时，click方法进不去。

### ISSUE THREAD

**Issue by jamie-phil** [ecomfe/echarts#1710]
貌似这个问题和coolDown参数有关，但这个参数在文档中没有说明。如果加上coolDown:0.99，那么就可以进去了。这个参数是区别点击动作和拖拽动作的吗？

另外，设置了emphasis.linkStyle，怎么没有反应呢？如果没有这个功能，强烈建议加上。

**Comment by pissang** [comment]
没什么问题呀，coolDown 决定的是布局的稳定速度。一般不推荐设置。

emphasis.linkStyle 是可以设置的，但是默认透明度 opacity 为 0，可以把 opacity 设置成 1
