### ISSUE TITLE
树图或者冰桶图，如何让子节点有多个父节点？

### ISSUE THREAD

**Issue by yzxFox** [ecomfe/echarts#1717]
树图或者冰桶图，如何让子节点有多个父节点？?

**Comment by pissang** [comment]
一棵树是不可能一个子节点有多个父节点的

**Comment by yzxFox** [comment]
我是想问，echars有这种图的形式吗。类似于树的简洁效果，不要像人物关系图那样复杂。
另外dagre.js 可否给个链接？

**Comment by pissang** [comment]
https://github.com/cpettitt/dagre-d3
