### ISSUE TITLE
数据视图中刷新和关闭按钮没有设置type

### ISSUE THREAD

**Issue by liekkas3175** [ecomfe/echarts#1728]
数据视图中刷新和关闭button没有设置type=“button”，在IE以外的浏览器会默认为submit，导致如果图表包含在form表单中时，点击两个按钮会提交表单

**Comment by hushicai** [comment]
从w3c对[button](http://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element)的定义上看，不加type的话，在标准浏览器上确实默认为submit。
