### ISSUE TITLE
在line和bar型的图标之间切换有事件可以触发回调吗？

### ISSUE THREAD

**Issue by rockxsj** [ecomfe/echarts#1729]
我有个这样的需求，当切换line和bar的时候，下面的一张table不一样。所以我想问下怎么在一个echarts的情况下，切换的时候我能知道这个切换事件？

**Comment by rockxsj** [comment]
table只是样式不一样，数据是一样的  不要问我为什么  产品经理说要怎么干  :(

**Comment by pissang** [comment]
有 MAGIC_TYPE_CHANGED 事件， http://echarts.baidu.com/doc/doc.html#附录图表实例接口
