### ISSUE TITLE
散点图中能在点与点之间画连线吗？

### ISSUE THREAD

**Issue by gracelinmumu** [ecomfe/echarts#1730]
在画散点图时，可不可以像d3.js一样，在点与点间绘制连线呢？ 如有知道的小伙伴请告知~~~~

**Comment by pissang** [comment]
可以使用 markLine

**Comment by gracelinmumu** [comment]
多谢 ~   我试过了 markline可以，但是会有箭头，怎样取消箭头呢  有没有样式修改？

**Comment by pissang** [comment]
有

**Comment by gracelinmumu** [comment]
请问怎么画呢 我用linkStyle没有起效果

**Comment by gracelinmumu** [comment]
我试着用itemStyle改变了连线的颜色， itemStyle:{normal:{color:'#A3E066'}}  但箭头不知道怎么去掉。。    @_@

**Comment by zameol** [comment]
用双数值轴折线图不可以吗？直接就相当于将散点连接起来构成折线图

**Comment by gracelinmumu** [comment]
呃 原来也想过用折线图，因为是想要画类似星型拓扑的结构，所以总觉得画不出，你刚刚一讲，我仔细想想看，貌似也是可以的呀  稍后试试看~  多谢~

**Comment by chensjmail** [comment]
markLine.symbolSize:[0, 0]
把这属性设置为0,是数组值

**Comment by gracelinmumu** [comment]
Bingo~  赞~   @chensjmail 方法OK，多谢~~~~

**Comment by DXuYang** [comment]
@gracelinmumu 在散点图上 怎么用markLine呢?麻烦您了

**Comment by DXuYang** [comment]
解决了，谢啦。
