### ISSUE TITLE
markPoint 怎么样才不显示tooltip markLine也有同样的问题!!!在线等....

### ISSUE THREAD

**Issue by chensjmail** [ecomfe/echarts#1731]
markPoint 怎么样才不显示tooltip markLine也有同样的问题?
我现在只想显示 markPoint.itemStyle.normal.label信息,不想鼠标上去还再显示tootip信息重复了,而且显示重合了?

样例代码:
```javascript
option= {
			tooltip:{
				show:false
			},
			xAxis:[{
				type:'category',
				splitLine:{
					show:false
				},
				data:['招行', '浦发', '中信', '兴业', '民生', '光大', '华夏', '广发', '平安', '恒丰', '浙商', '渤海']
			}],
			yAxis:[{
				type:'value'
			}],
			series:[{
				tooltip:{
					show:false
				},
				name:'辅助',
				type:'bar',
				stack:'总量',
				itemStyle:{
					normal:{
						barBorderColor:'rgba(0,0,0,0)',
						color:'rgba(0,0,0,0)'
					},
					emphasis:{
						barBorderColor:'rgba(0,0,0,0)',
						color:'rgba(0,0,0,0)'
					}
				},
				data:[15, 10, 10, 10, 10, 10],
				markPoint:{
					itemStyle:{
						normal:{
							label:{
								show:true,
								position:'bottom',
								formatter:function(params_){
									return params_.name.replace(/\{a\}/ig, params_.data.yAxis);
								},
								y:1010,
								textStyle:{
									fontSize:14
								}
							}
						}
					},
					data:[{
						xAxis:0,
						yAxis:5,//显示在刻度上的值
						name:'招行: {a} 亿\n比前1位还差:xxx',
						symbolSize:20,
						symbol:'image://./icon/image001.png'
					}, {
						xAxis:1,
						y:50,
						name:'浦发',
						symbolSize:20,
						symbol:'image://./icon/image003.png'
					}, {
						xAxis:2,
						yAxis:10,
						name:'中信',
						symbolSize:20,
						symbol:'image://./icon/image005.png'
					}, {
						xAxis:3,
						y:350,
						name:'K',
						symbolSize:20,
						symbol:'image://../asset/ico/K线图.png'
					}, {
						xAxis:4,
						y:350,
						name:'Pie',
						symbolSize:20,
						symbol:'image://../asset/ico/饼状图.png'
					}, {
						xAxis:5,
						y:350,
						name:'Radar',
						symbolSize:20,
						symbol:'image://../asset/ico/雷达图.png'
					}, {
						xAxis:6,
						y:350,
						name:'Chord',
						symbolSize:20,
						symbol:'image://../asset/ico/和弦图.png'
					}, {
						xAxis:7,
						y:350,
						name:'Force',
						symbolSize:20,
						symbol:'image://../asset/ico/力导向图.png'
					}, {
						xAxis:8,
						y:350,
						name:'Map',
						symbolSize:20,
						symbol:'image://../asset/ico/地图.png'
					}, {
						xAxis:9,
						y:350,
						name:'Gauge',
						symbolSize:20,
						symbol:'image://../asset/ico/仪表盘.png'
					}, {
						xAxis:10,
						y:350,
						name:'Funnel',
						symbolSize:20,
						symbol:'image://../asset/ico/漏斗图.png'
					}, ]
				}
			}, {
				tooltip:{
					show:false
				},
				name:'生活费',
				type:'bar',
				stack:'总量',
				data:[0, 0, 0, 0, 0, 0]
			}]
		};
```

**Comment by chensjmail** [comment]
没有理还是没人懂?

**Comment by chensjmail** [comment]
自行解决:
emphasis:{
							label:{
								show:false
							}
						}
所重显关闭

option= {
			tooltip:{
				show:false
			},
			xAxis:[{
				type:'category',
				splitLine:{
					show:false
				},
				data:['招行', '平安', '浙商', '浦发', '恒丰', '光大', '华夏', '中信', '兴业', '民生', '渤海', '广发']
			}],
			yAxis:[{
				type:'value'
			}],
			series:[{
				name:'辅助',
				type:'bar',
				//stack:'总量',
				itemStyle:{
					normal:{
						barBorderColor:'rgba(0,0,0,0)',
						color:'rgba(0,0,0,0)'
					},
					emphasis:{
						barBorderColor:'rgba(0,0,0,0)',
						color:'rgba(0,0,0,0)'
					}
				},
				data:[100, 0],
				markPoint:{
					itemStyle:{
						normal:{
							label:{
								show:true,
								position:'bottom',
								formatter:function(params_){
									return params_.name.replace(/\{a\}/ig, params_.data.yAxis);
								},
								textStyle:{
									fontSize:20
								}
							}
						},
						emphasis:{
							label:{
								show:false
							}
						}
					},
					data:[{
						xAxis:0,
						yAxis:80,//显示在刻度上的值
						name:'招行: {a} 亿\n比前1位还差:xxx',
						symbolSize:20,
						symbol:'image://./icon/招行.png'
					}, {
						xAxis:1,//显示在x轴刻度上的值
						yAxis:90,//显示在y轴刻度上的值
						name:'平安',
						symbolSize:20,
						symbol:'image://./icon/平安.png'
					}, {
						xAxis:2,//显示在x轴刻度上的值
						yAxis:65,//显示在y轴刻度上的值
						name:'浙商',
						symbolSize:20,
						symbol:'image://./icon/浙商.png'
					}, {
						xAxis:3,//显示在x轴刻度上的值
						yAxis:49,//显示在y轴刻度上的值
						name:'浦发',
						symbolSize:20,
						symbol:'image://./icon/浦发.png'
					}, {
						xAxis:4,//显示在x轴刻度上的值
						yAxis:53,//显示在y轴刻度上的值
						name:'恒丰',
						symbolSize:20,
						symbol:'image://./icon/恒丰.png'
					}, {
						xAxis:5,//显示在x轴刻度上的值
						yAxis:78,//显示在y轴刻度上的值
						name:'光大',
						symbolSize:20,
						symbol:'image://./icon/光大.png'
					}, {
						xAxis:6,//显示在x轴刻度上的值
						yAxis:42,//显示在y轴刻度上的值
						name:'华夏',
						symbolSize:20,
						symbol:'image://./icon/华夏.png'
					}, {
						xAxis:7,//显示在x轴刻度上的值
						yAxis:29,//显示在y轴刻度上的值
						name:'中信',
						symbolSize:20,
						symbol:'image://./icon/中信.png'
					}, {
						xAxis:8,//显示在x轴刻度上的值
						yAxis:45,//显示在y轴刻度上的值
						name:'兴业',
						symbolSize:20,
						symbol:'image://./icon/兴业.png'
					}, {
						xAxis:9,//显示在x轴刻度上的值
						yAxis:58,//显示在y轴刻度上的值
						name:'民生',
						symbolSize:20,
						symbol:'image://./icon/民生.png'
					}, {
						xAxis:10,//显示在x轴刻度上的值
						yAxis:61,//显示在y轴刻度上的值
						name:'渤海',
						symbolSize:20,
						symbol:'image://./icon/渤海.png'
					}, {
						xAxis:11,//显示在x轴刻度上的值
						yAxis:13,//显示在y轴刻度上的值
						name:'广发',
						symbolSize:20,
						symbol:'image://./icon/广发.png'
					}]
				}
			}, {
				name:'生活费',
				type:'bar',
				stack:'总量',
				data:[0, 0, 0, 0, 0, 0]
			}]
		};

**Comment by chensjmail** [comment]
markLine暂时还是没有办法解决

**Comment by chensjmail** [comment]
觉得好乱

**Comment by HuMonkey** [comment]
markline下面设置silence: true 
不响应鼠标事件就好。
