### ISSUE TITLE
echarts 不支持 bower?

### ISSUE THREAD

**Issue by z2** [ecomfe/echarts#1733]
不支持 npm?

**Comment by hushicai** [comment]
bower是支持的，安装之后可以使用bower_components/echarts/build/dist/下面的文件。

然后再按[文档](http://echarts.baidu.com/doc/doc.html#引入ECharts2)引入。

bower不支持从源代码引入echarts。

npm目前是不支持的。

**Comment by uooo** [comment]
@z2 echarts 支持npm了，使用webpack可以按需加载源码。
