### ISSUE TITLE
请问如何为力导向图中的节点自定义tooltip？

### ISSUE THREAD

**Issue by thinksea** [ecomfe/echarts#1735]
请问如何为力导向图中的节点自定义tooltip？
echarts 版本号2.2.4

**Comment by pissang** [comment]
现在不能用 formatter 自定义 tooltip？

**Comment by thinksea** [comment]
搞定了，谢谢！
通过tooltip的formatter配置节搞定，具体如下。
                            formatter: function (params, ticket, callback) {
                                //params.seriesName
                                if(params.indicator2) //判断鼠标悬停位置是节点还是关系线
                                {
                                    return "节点关系：" + params.name; //显示关系线的name属性值
                                }
                                else
                                {
                                    return "节点：" + params.data.label; //显示节点的label属性值
                                }
                            },
