### ISSUE TITLE
echarts的tooltip中可以放图片、超链接之类的元素吗？

### ISSUE THREAD

**Issue by gracelinmumu** [ecomfe/echarts#1740]
如题，可以在鼠标悬浮时的tooltip中显示图片、超链接等元素吗？

**Comment by rikan** [comment]
图片可以,超链接也可以放,但是你点不到

**Comment by gracelinmumu** [comment]
多谢小伙伴  已经试过了，拼接字符串可以在tooltip中添加图片 超链接  ~   使用enterable: true设置tooltip为可点击操作，是可以click的 @rikan

**Comment by chensjmail** [comment]
怎么弄的,怎么都不贴代码的?

**Comment by gracelinmumu** [comment]
可以在tooltip气泡中使用字符串拼接的方式添加img、超链接等元素，设置enterable为true，使得tooltip可点击，代码如下： 
tooltip: {                                 
            enterable: true,
            padding: [20, 10, 10, 20],
            backgroundColor: 'rgba(255,255,255,0.8)',
            borderColor: '#999999',
            borderRadius: 8,
            borderWidth: 1,
            width: 500,
            position: function(p) {
                return [p[0] + 20, p[1] + 20];
            },
            formatter: function(params, ticket, callback) {
                var str = '<img class="img" src="' + params[2][5] + '" />'
                               + '<a href="#">查看</a>';
             return str;
            },
            trigger: 'item'  
        },

**Comment by chensjmail** [comment]
用括号代替html的括号?这么奇葩的办法都被echarts想到了,哈哈
一会试试,谢谢

**Comment by xfworld** [comment]
这个办法不错，留个记号

**Comment by gracelinmumu** [comment]
str里的圆括号用尖括号替换掉就OK啦~ 
一直想要这个功能，忽然想到反正formatter也是返回字符串，那就拼接试试看，没想到OK

**Comment by chensjmail** [comment]
哦,是这样,OK,
和highcharts类似
这样好

**Comment by zfengqi** [comment]
大家有没发现尽管设置了enterable:true
tooltip被悬浮时还是有很大几率会消失不见了

**Comment by yymoxiaochi** [comment]
> 大家有没发现尽管设置了enterable:true
> tooltip被悬浮时还是有很大几率会消失不见了

个人认为是tooltip的position跟着鼠标一直刷新导致的，我设置
position: function(p) {
                return [p[0] - 20, p[1] - 20];
            },
可以解决，不知道有没有更好的方式

**Comment by Jordon-Chen** [comment]
This works well for me.
```
tooltip: {
  position: function (pos, params, dom, rect, size) {
    const tooltipWidth = window.getComputedStyle(dom).width.replace('px', '')
    if (pos[0] < size.viewSize[0] / 2) {
      return [pos[0], pos[1] - 20]
    } else {
      return [pos[0] - tooltipWidth, pos[1] - 20]
    }
  }
}
```

**Comment by Listeningx** [comment]
这个src应该放什么链接呢，为什么我一直显示不出来图片
