### ISSUE TITLE
legend文字前面的图标可以自己更改吗?

### ISSUE THREAD

**Issue by mqliutie** [ecomfe/echarts#1742]
在[这个例子](http://echarts.baidu.com/doc/example/legend.html)中,我看到icon是可以自定义的,为什么我自己设置的时候不行呢?

**Comment by chensjmail** [comment]
icon : 'image://../asset/ico/favicon.png'
改成自己的图片就可以,注意这里的路径是相对的
icon : 'image://http://img0.imgtn.bdimg.com/it/u=3609535433,981749261&fm=21&gp=0.jpg'
这样是绝对地址

**Comment by mqliutie** [comment]
- - 我可以说没效果么... , 是使用的是折线图,这有区别吗?

**Comment by pissang** [comment]
看自定义样式的示例 line.html
