### ISSUE TITLE
数值型坐标轴 axisLabel 能否在回调中提供更有用的 data? 目前是 undefined.

### ISSUE THREAD

**Issue by fallingfree** [ecomfe/echarts#1744]
在把 axisLabel 设置为 clickable: true 之后, 在 echarts 实例上通过监听事件获取到的值, 除了 axis 的 name, 其它都是无用的, 返回如下:

```
{
	data: undefined,
	dataIndex: -1,
	event: MouseEvent,
	name: 2004,
	seriesIndex: -1,
	seriesName: undefined,
	special: undefined,
	type: "click",
	value: undefined
}
```

能否能把当前 x/y轴 值的数组传到 data 中? 

是否有方法可以通过 axisLabel 的点击获取到当前所在 x/y轴 所有的数据? 或者像处理坐标点数据一样, 把数组传到 data 中.

**Comment by BlackCodes** [comment]
同样的问题，能否带一个回调函数

**Comment by xiaoyunchen** [comment]
我也需要对X轴进行事件监听
但是 axisLabel  配置中并没有 clickable 这个配置项啊，请问是在哪配置的

**Comment by mansion-sun** [comment]
https://echarts.apache.org/zh/option.html#xAxis.triggerEvent
