### ISSUE TITLE
markLine能不能画在靠底层的位置，有没有类似z-index的属性?

### ISSUE THREAD

**Issue by gracelinmumu** [ecomfe/echarts#1752]
如题，想要绘制散点连线图，在scatter中添加markLine绘制连线，但连线位于最上层了，有没有什么方法把它画在靠底层的位置，类似z-index的属性?

**Comment by matteodesanti** [comment]
Same issue to me: please help to manage z-index of markLines

**Comment by pissang** [comment]
把 markLine 放在一个新的系列里然后设置该系列的 z 值
