### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGeoJson' of undefined

### ISSUE THREAD

**Issue by oneroundseven** [ecomfe/echarts#1753]
页面上直接引入的是dist/echarts.js
![1122](https://cloud.githubusercontent.com/assets/1825295/8427053/1657595a-1f47-11e5-93a3-b01696fd6db8.JPG)

    require.config({
        paths: {
            echarts: './script/libs/echarts-2.2.4'
        }
    });

    require(['echarts', 'echarts/src/util/mapData/params', 'echarts/chart/map'], function(ec, params) {
        params.params.HK = {
            getGeoJson: function(callback) {
                $.getJSON('./script/geoJson/HK_geo.json',callback);
            }
        };

        // 基于准备好的dom，初始化echarts图表
        var myChart = ec.init(document.getElementById('mapTest'));

        var option = {
            tooltip : {
                trigger: 'item',
                formatter: '{b}'
            },
            series : [
                {
                    name: 'test',
                    type: 'map',
                    mapType: 'HK',
                    roam: true,
                    selectedMode : 'single',
                    itemStyle:{
                        normal:{label:{show:false}},
                        emphasis:{label:{show:true}}
                    },
                    data:[]
                }
            ]
        };

        myChart.setOption(option);
    });

 这是什么原因？ 不能这么玩么？是不是哪里写错了

**Comment by hushicai** [comment]
`echarts-2.2.4/src`就不需要了，不能混用src和dist。

页面上用script方式引入echarts-2.2.4/echarts.js之后，直接这么用就行：

```javascript
require.config({
    paths: {echarts: './scripts/libs/echarts-2.2.4'}
});

require(['echarts', 'echarts/chart/map'], function (echarts) {
    var mapDataParams = require('echarts/util/mapData/params');
    mapDataParams.params.HK = {getGeoJSON: function () {}};
    // ...
});
```

`echarts/util/mapData/params`已经打包在`echarts/chart/map`中了，所以只需要动态require('echarts/chart/map')就行了。

**Comment by oneroundseven** [comment]
谢谢，解决了。 对照着文档示例 怎么调试都报错，差点就放弃了
