### ISSUE TITLE
开放面积图颜色的计算

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1755]
我在制作多条数据的堆积图（Line Chart)的时候，如果不指定颜色，数据的颜色（LineStyle）是config.colors数组里面的取的。面积部分（stack=true）的颜色是用的zrColor.alpha(color,0.5)的方式计算出来的。现在希望可以开放这个计算函数。

原因是这样的：用alpha 0.5的话，颜色是半透明的。多条数据重叠的时候，最下面那条数据的面积的颜色比较怪。他是所有上面数据面积背景色的混合。我现在如果修改源码，然后用d3库的HSL颜色，然后把L的值设置成95%，这个颜色就是数据线条颜色的非常浅的版本。看上去非常的顺眼。

希望echarts团队可以考虑给zrColor提供类似的颜色变换的函数，或者开放这个面积颜色的计算。
```
var lineColor = 'rgb(0,119,215)';
// echart的处理方式
var actualAreaColor = zrColor.alpha(lineColor, .5);

// 我的方式
var hsl = d3.rgb(lineColor).hsl();
var expectedAreaColor = d3.hsl(hsl.h, hsl.s, .95).toString();
```
![example](https://cloud.githubusercontent.com/assets/5162687/8435436/b6116760-1f83-11e5-8091-9471e85e5796.png)

以上图中的颜色的具体的值，我目前是用以下的代码设置出来的。计算公式就是上面我提到的。
```
var colors = [
      {line: 'rgb(0,119,215)', grid: 'rgba(0,119,215,.2)', area: '#ebf6ff'}, // blue
      {line: 'rgb(110,119,215)', grid: 'rgba(110,119,215,.2)', area: '#eff0fb'}, // purple
      {line: 'rgb(41,189,181)', grid: 'rgba(41,189,181,.2)', area: '#eefbfb'}, // green
      {line: 'rgb(212,102,138)', grid: 'rgba(212,102,138,.2)', area: '#fbeff3'}, // dark red
      {line: 'rgb(255,127,80)', grid: 'rgba(255,127,80,.2)', area: '#fff0eb'} // orange
];
```

顺便做一个小广告，以上截图是用我正在开发的一个基于angularjs的开源widget库**dashing**渲染出来的效果。目前还在alpha阶段。

**Comment by pissang** [comment]
`zrender/tool/color` 模块中有 toHSL 等颜色计算的方法

详见文档，http://ecomfe.github.io/zrender/doc/api/module-zrender_tool_color.html

**Comment by stanleyxu2005** [comment]
目前echarts是用的alpha（0.5）来计算的，这个算法是不能替换的，我只可以把计算好的颜色直接给chart。也就是说，这个计算得在外部完成。我很希望可以有一个一劳永逸的方法，这样的话，我直接给定20个颜色，和区域面积的计算公式，这20个颜色会根据公式去计算对应的颜色。从我的截图来看，只要颜色配好了，计算出来的样子不会太难看的。

这边我想延伸问个问题：我的项目如果只引用了echarts-all.js，可以直接使用zrender的函数吗？还是需要额外引入一下zrender。我现在是用echart-optimizer把需要的模块选好，自构建的一个echart-all.js

**Comment by hushicai** [comment]
alpha 0.5只是一个fallback，你如果想自定义区域面积颜色，需要自行计算后传入。

引入echarts-all.js后，你有两个global变量可以使用，echarts和zrender。

**Comment by stanleyxu2005** [comment]
@hushicai 原来如此，谢谢。
