### ISSUE TITLE
堆积面积图的Leagend在显示当前数据集的时候，数据不正确

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1756]
下图中，我有5根数据集。当我把鼠标一同到Leagend的数据Series 5的时候，我期待只显示最上面一条桔黄色的色块。但实际上，下面4条数据都会被隐去，这个桔黄色的色块高度是5个色块高度之和。如果要从图上读取数据的话，结果就不正确了。希望能予以改进。我是用最新的2.2.4测试的。

![example](https://cloud.githubusercontent.com/assets/5162687/8435621/ff46ce4c-1f84-11e5-8785-0ac5ef568c20.png)

**Comment by stanleyxu2005** [comment]
这个问题会修复吗？@pissang

**Comment by pissang** [comment]
会在 3.0 里修复

**Comment by stanleyxu2005** [comment]
ok。我昨天做梦echarts出了一个非常牛逼的新版本

**Comment by pissang** [comment]
哈哈可能没有你梦里那么牛逼，但是很多 Issue 里的问题都会在 3.0 中解决
