### ISSUE TITLE
自定义geo.json相关问题

### ISSUE THREAD

**Issue by oneroundseven** [ecomfe/echarts#1760]
你好~
我自己在网上找个了geoJson.json的世界地图文件，通过自定义地图方式加入到echarts里面，然后地图显示很小，并且滚轮缩放的时候地图会产生偏差。
有没有什么参数配置可以改变当前这种情况，比如设置当前地图的缩放级别等配置？求教

http://code.highcharts.com/mapdata/ 这里下载的世界地图
下图是在页面上显示的情况，实际区域其实很大，显示出来的时候地图很小。
![default](https://cloud.githubusercontent.com/assets/1825295/8448820/30fa99fe-1ffe-11e5-8b96-681743271dd6.JPG)

**Comment by hushicai** [comment]
echarts内置了世界地图，为啥要用highcharts上提供的数据？

**Comment by oneroundseven** [comment]
@hushicai 因为内置世界地图 数据不全 只有177个国家 实际世界上超过224个了

**Comment by IlovedJoey** [comment]
echarts提供打进包里的地图数据确实需要更新了，中国地图也有很多地级市取消改名了的，但现在用的还是老数据，也需要自己手动改。

**Comment by seifer08ms** [comment]
的确需要更新了

**Comment by pissang** [comment]
中国各省市的地图数据我们提供了下载工具 http://ecomfe.github.io/echarts-map-tool

**Comment by oneroundseven** [comment]
求世界地图打包。。。 哎 估计这个要等下个版本

**Comment by ginkosen** [comment]
@pissang [http://ecomfe.github.io/echarts-map-tool](http://ecomfe.github.io/echarts-map-tool) 中下载的有些geo地图是旧的，比如深圳市的，有一些新的区，下载的json数据里面暂时没有。

**Comment by seven6666** [comment]
深圳地图什么时候更新
