### ISSUE TITLE
画chord时报错“chord has not been required.”

### ISSUE THREAD

**Issue by gracelinmumu** [ecomfe/echarts#1762]
画chord时报错“chord has not been required.” 应该怎么添加chord呢？

**Comment by pissang** [comment]
require(['echarts', 'echarts/chart/chord'])

**Comment by gracelinmumu** [comment]
这个是添加的echarts/src中chart下的chord模块吗？

**Comment by hushicai** [comment]
@gracelinmumu echarts的发行包中，有两个文件，一个是echarts-all.js，一个是echarts.js和chart目录，前者包含了echarts的所有模块，后者把每个图表单独打包了，使用时需要动态加载。

**Comment by gracelinmumu** [comment]
所以说直接使用echarts-all全部引入也可以？

**Comment by gracelinmumu** [comment]
另外，使用require引入模块时的路径是和require.config中的path对应还是和package对应？

**Comment by gracelinmumu** [comment]
已做测试，直接引入echarts-all可以~
使用require按需加载时path一般设置为单个文件如jquery、d3的路径，package相当于包，为文件夹如echarts、zrender设置路径
