### ISSUE TITLE
forcelayout和chord中连线可以画成带箭头的效果吗？

### ISSUE THREAD

**Issue by gracelinmumu** [ecomfe/echarts#1767]
在forcelayout和chord中，节点间的连线可以画成带箭头的效果吗？

**Comment by gracelinmumu** [comment]
forcelayout 找到方法  series. linkSymbol: 'arrow' 设置连线带箭头，chord却不行，不太明白为什么。

**Comment by gracelinmumu** [comment]
还是没搞定，继续求方法！

**Comment by pissang** [comment]
chord 目前不行
