### ISSUE TITLE
renderAsImage怎么调整图片大小

### ISSUE THREAD

**Issue by wzpfish** [ecomfe/echarts#1769]
renderAsImage设为true后，图片会非常大，只能显示左上角的一块，请问如何解决？

**Comment by hushicai** [comment]
你是mac吧？retina屏幕下，在img没有进行缩放的情况下，只能看到图片的1/4。

你给img设置个宽度或者直接100%就行了。

**Comment by wzpfish** [comment]
@hushicai  是mac  是给什么设宽度啊？ renderAsImage的那个charts所在的标签吗？

**Comment by hushicai** [comment]
echarts图表标签主元素下的img标签设置个宽度
