### ISSUE TITLE
map 在长时间运行后会崩溃

### ISSUE THREAD

**Issue by zhaojun12** [ecomfe/echarts#1770]
* 我建立了一个世界地图，并在上面 markPoint 了若干个点，并在这些点之间建立 markLine
* 我需要动态的删除和增加 markPoint，动态的删除和增加 markLine
* 目前使用的 getOption 和 setOption 来达到上面的目的
* 但是通过这种方法发现内存会不断升高，在两个点一条边的情况下，每个小时删除两个点和一条边，再增加两个点和增加一条边，持续 20 个小时左右后浏览器就会崩溃
* 不知道这种情况如何解决？
* 另，addMarkPoint、delMarkPoint、delMarkLine 这几种方法和 setOption 这种方法有什么不同，是否会降低动态增删时 RAM 的占用

谢谢

**Comment by ZeeRoc** [comment]
及时的清理mappoint。 使用`delMarkPoint`。
