### ISSUE TITLE
echarts的legend比较长的时候，换行后挡住x轴

### ISSUE THREAD

**Issue by kellerkk** [ecomfe/echarts#1774]
当legend过长后，legend会进行换行，会挡住x轴，legend设置x为top仍然会有此问题，请教如何让legend自适应高度？
![qq 20150703115049](https://cloud.githubusercontent.com/assets/13160203/8492275/f948e1d2-2179-11e5-8ea4-c3ce1e2ad388.png)

**Comment by hushicai** [comment]
空间有限，不能自适应，只能自行用参数调整。

你这种情况，可以将坐标网上移一下，把grid.y2调大一点。
