### ISSUE TITLE
noDataLoadingOption 

### ISSUE THREAD

**Issue by zasqw2222** [ecomfe/echarts#1776]
noDataLoadingOption的effect这个属性的外部加载该如何使用？
想要不显示背景动画，只显示文字，有没有相关的属性可控制？
谢谢

**Comment by xfworld** [comment]
同问

**Comment by hushicai** [comment]
可以参考`zrender/src/loadingEffect`下的文件。

echarts内置了以下几种effect：

```javascript
var effectList = {
    bar: require('zrender/loadingEffect/Bar'),
    bubble: require('zrender/loadingEffect/Bubble'),
    dynamicLine: require('zrender/loadingEffect/DynamicLine'),
    ring: require('zrender/loadingEffect/Ring'),
    spin: require('zrender/loadingEffect/Spin'),
    whirling: require('zrender/loadingEffect/Whirling')
};
```

如果你想自定义加载，则需要自行实现一个Effect类（必须是个构造器），继承自`zrender/src/loadingEffect/Base`。

**Comment by luxu634** [comment]
noDataLoadingOption = {
	    text: '暂无数据',
	    effect:'bubble',
	    effectOption : {
            effect: {
                n: 0
            }
	    },
	    textStyle: {
	        fontSize: 32,
	        fontWeight: 'bold'
	    }
	}
自己写效果太麻烦，变通了一下，把bubble效果中圈圈数量改为0，可以满足需求

**Comment by qimengke** [comment]
noDataLoadingOption该怎么解决？
