### ISSUE TITLE
力学导向图和地图鼠标在tooltip的tip里移动会触发legend的hover事件

### ISSUE THREAD

**Issue by zhong9257** [ecomfe/echarts#1780]
2.2.1 百度版本
tooltip控件里的属性enterable：true；
鼠标在提示框里来回移动时，就会来回选中legend里的图例

![qq 20150706154437](https://cloud.githubusercontent.com/assets/13195068/8518250/de1d21b0-23fa-11e5-95dd-d3814251545f.png)

**Comment by pissang** [comment]
新版本已修复这个问题
