### ISSUE TITLE
柱状图宽度和间距设置失效

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1782]
加入我的图片大小是400x200。现在我要显示一个柱状图来显示一个小组里面每个人的生产效率。每一根柱子代表一个人。我希望每根柱子宽度是6px，间距是2px。如果一共有3个人，那么图片只需要占用22px（6x3+2x2）。但实际情况，echart画的时候，这3根柱子的粗细是正确的，但间距会自动拉伸开。其实这个非常的难看。不知道应该如何设置，或者是库本身的bug。

另外，当人数非常多，以至于400px不够显示的时候，我希望自动打开dataZoom，用左右滚动条来选择想显示一部分柱子，但他们的宽度和间距不要变化。这个貌似现在是做不到的。非常希望能完善这部分的功能。

**Comment by stanleyxu2005** [comment]
如果我能设定屏幕最多点的阀值（类似cropThreshold），那么每个点的间距就可以计算出来，就是说，添加第一根bar的时候，这个bar的位置是固定的，而不是根据bar的多少，动态在chart上计算bar的宽度。

我自己做的一个封装里面，是这样考虑的。设置一个barMaxWidth和barMinWidth。
1. 如果`bar.length * barMaxWidth`小于chart总宽度，我增加`grid.x2`的值使图缩小。
2. 如果`bar.length * barMinWidth`大于chart总宽度，我自动开启datazoom，并把end的值设置到能保证chart上可见的bar的宽度就是最小宽度。

**Comment by TakeMeToTheDistance** [comment]
OC最新的barchart的barWidth能不能设置固定宽度?
