### ISSUE TITLE
npm中找不到echarts

### ISSUE THREAD

**Issue by bshy522** [ecomfe/echarts#1784]
请问， 为什么没有选择将echarts发布到npm上呢？

谢谢。

**Comment by luqin** [comment]
[https://github.com/ecomfe/echarts/issues/1790](https://github.com/ecomfe/echarts/issues/1790)

**Comment by uooo** [comment]
@bshy522 已发布到npm，使用方式见https://github.com/uooo/echarts

**Comment by bshy522** [comment]
赞.
