### ISSUE TITLE
Log axis不能支持分段或者指定最大最小值吗？

### ISSUE THREAD

**Issue by free421xiaobai** [ecomfe/echarts#1785]

**Comment by hushicai** [comment]
log axis本质上也是个value axis，是可以设置相关属性的。

**Comment by free421xiaobai** [comment]
我发现我给log axis设置一个最大值是100，它会显示最大值是1000，设置最小值是0.1，它会显示最小值是0.01，是还要设置其他的属性吗？

**Comment by hushicai** [comment]
这是正常的，如果是100，刚好在一个logLabel上，就会向上扩大一个step；如果是99，就不会扩大到1000，0.1同理。

**Comment by free421xiaobai** [comment]
那我给axis设置了最大最小值了，它不应该应用我自己设置的最大最小值吗？
比如我设置最大值是100，它自己根据数据给我设置了其他的值合适吗？

**Comment by lolgolflol** [comment]
how can I use type is  "log" of Axis but  value is integer not float?
