### ISSUE TITLE
echart 地图选中问题

### ISSUE THREAD

**Issue by csucaifei** [ecomfe/echarts#1786]
如何利用js代码让地图中的某一个省或者某几个省处于选中状态？

**Comment by liekkas** [comment]
官网例子中就有，设置selected属性为true
```
option = {
    tooltip : {
        trigger: 'item',
        formatter: '{b}'
    },
    series : [
        {
            name: '中国',
            type: 'map',
            mapType: 'china',
            selectedMode : 'multiple',
            itemStyle:{
                normal:{label:{show:true}},
                emphasis:{label:{show:true}}
            },
            data:[
                {name:'广东',selected:true},
              {name:'北京',selected:true}
              
            ]
        }
    ]
};
var ecConfig = require('echarts/config');
myChart.on(ecConfig.EVENT.MAP_SELECTED, function (param){
    var selected = param.selected;
    var str = '当前选择： ';
    for (var p in selected) {
        if (selected[p]) {
            str += p + ' ';
        }
    }
    document.getElementById('wrong-message').innerHTML = str;
})
                    
```

**Comment by csucaifei** [comment]
非常感谢您的回答~
官网的例子只能是在设定series时，在数据中增加selected:true来确定，这种方式是在地图绘制之前就给定哪些处于选中状态，假设地图已经绘制出来了，其中地图上有markPoint元素，现在需要实现选择一个point，然后时高亮显示周围某几个省市（region）也处于选中状态，这种需要目前在官网上没有找到比较直接的api来直接指定元素处于选中状态，我的解决方法是：
var length = option.series[0].data.length;
for(var i=0; i<length; i++) {
	var name = option.series[0].data[i].name;
	if (region.indexOf(name) >=0 ) {
		option.series[0].data[i].selected = true;
	}
}
myChart.setOption(option);	

假设能有根据传入的name直接指定选中就好了。哈哈~
myChart.setSelected(name)

**Comment by github-arong** [comment]
用的也是楼上方法,最后再调用refresh方法.

**Comment by scgy5555** [comment]
@csucaifei 我的需求跟你差不多，我想问一下选中markPoint你是怎么实现的
似乎没有事件可以直接处理
