### ISSUE TITLE
地图API参数 nameMap 

### ISSUE THREAD

**Issue by oneroundseven** [ecomfe/echarts#1788]
您好~

      请问下 地图API中的nameMap映射只能用已经提供的name来做？ 不能指定ID的缩写字段来映射么？

**Comment by hushicai** [comment]
是的，目前只能用`series.data[i].name`来做映射。

**Comment by oneroundseven** [comment]
@hushicai  找到办法了  手动加载geo.json 然后循环数据把id 赋值给name 然后做映射 = =  
还是希望国产画图工具更好用! 谢谢回答
