### ISSUE TITLE
【npm】 echarts has been published to NPM 

### ISSUE THREAD

**Issue by luqin** [ecomfe/echarts#1790]
[![NPM](https://nodei.co/npm/echarts.png?downloads=true&stars=true)](https://nodei.co/npm/echarts/)

**Comment by luqin** [comment]
echarts has been published to NPM. But the version of zrender in npm is 2.0.5. We will fix zrender later.

**Comment by uooo** [comment]
echarts for webpack: https://github.com/uooo/echarts
