### ISSUE TITLE
在线人数统计地图点画到太平洋BUG

### ISSUE THREAD

**Issue by rockxsj** [ecomfe/echarts#1791]
http://echarts.baidu.com/doc/example/map15.html#blue

这个在线人数的地图貌似有些点画出国界了     请问会fix吗？

**Comment by XingdaLee** [comment]
坐标觉得 点 的位置。改坐标不就好了

**Comment by rockxsj** [comment]
明白了  没仔细看demo   那些点之所以画到了太平洋是因为随机散列过去的。。。        那么我想问下能不能保证散列到太平洋里面的点不会被显示出来？  或者我可以设置散列的边界为一组标识大陆的geo坐标值？

**Comment by XingdaLee** [comment]
geoCoord : [
                                geoCoord[0] + Math.random() * 5 - 2.5,
                                geoCoord[1] + Math.random() * 3 - 1.5
                     ]
你在他data.push前把这个坐标算法注释掉试试呢？一般的中国城市坐标点是不会出中国的（出去的也许都是沿海城市），如果有的话，单独的改一下应该没问题。

**Comment by rockxsj** [comment]
是的  这个去掉就不会了  但是画出来的效果就没这么绚丽了  所以我在考虑仍然随机一些点（比如1000个），但是判断每个点是否在中国大陆里面     只是不知道有没有比较高效的实现来做这件事？  否则只能每个点去判断是否在边界内了:(
