### ISSUE TITLE
地图的34个省份直辖市支持繁体中文

### ISSUE THREAD

**Issue by liminjun** [ecomfe/echarts#1796]
因为EChart里面本身内置了34个省份直辖市的围栏和坐标，如果在应用中要支持繁体中文。需要在http://ecomfe.github.io/echarts-map-tool/ 网站将34个省份直辖市的数据下载下来，然后合并成一个china.json，在绘制地图的时候引用吗?

echarts.util.mapData.params.params.chinaTW= {
			    getGeoJson: function (callback) {
			        $.getJSON('../Scripts/l10n/china_TW.json', function (data) {
			            // 压缩后的地图数据必须使用 decode 函数转换
			            callback(echarts.util.mapData.params.decode(data));
			        });
			    }
			};
还是有更简便的方法使用?

**Comment by liekkas** [comment]
你可以在series中加入名称映射，比如：
```
nameMap :{
              '山东':'山東',
              '广东':'廣東'
            } 
```

http://echarts.baidu.com/doc/example/map6.html  在线试试效果
