### ISSUE TITLE
带有timeline的图表,setOption(option,true)无法完全清除原来的数据

### ISSUE THREAD

**Issue by mirari** [ecomfe/echarts#1803]
比如我有一个带时间轴的折线图表,默认是按日-时统计,时间轴共7个点,X轴共24个点
切换到按年-月统计时,执行了setOption(option,true)方法,此时option中的时间轴是3个点,X轴12个点
然后问题来了,X轴的显示结果是:1月、2月、3月、4月……13：00、14:00、……24:00

换句话说，setOption中的nomerge没有生效，除非使用dispose和init重建图表。

这是BUG还是设计如此？

**Comment by mirari** [comment]
原来timeline还有个自己的notMerge属性，设置为true以后，多次执行setOption不会出现旧数据了。
但是，options下的多个option对象里，后面的option无法继承第一个option的属性了，必需全部显式指定，不得不存在大量冗余。
感觉这两种配置项还是应该区分开。否则要么只能对每个option都逐一指定配置项，要么每次图表切换时都要销毁和重建，对性能总是有影响的。

**Comment by hushicai** [comment]
只有merge和notMerge两种情况。

你想要去掉冗余，可以自己写option factory，复用代码。

**Comment by xfworld** [comment]
@hushicai  option factory咋写啊，有没有简单的示例

**Comment by mirari** [comment]
虽然可以复用代码，但实际传递给实例的参数还是没有必要地庞大了许多。

我只是想在传递一个新的option的时候能够忽略之前的旧数据，就像普通图表的setOption(option,true)一样，或者说，有没有什么方法能够让timeline实例恢复到init()方法刚执行后的状态。
我觉得这个问题值得改进。
毕竟，同样一组option，在第一次传递给实例的时候是有效的，第二次却出现了错乱，这现象很奇怪，处理起来也麻烦。
