### ISSUE TITLE
我想通过legend配置类控制数据的显示与否

### ISSUE THREAD

**Issue by wych1987** [ecomfe/echarts#1805]
·   
option = {
legend : {
    orient : 'horizontal', // 'vertical'
    x : 'right', // 'center' | 'left' | {number},
    y : 'top', // 'center' | 'bottom' | {number}
    backgroundColor : '#eee',
    borderColor : 'rgba(178,34,34,0.8)',
    borderWidth : 4,
    padding : 10, // [5, 10, 15, 20]
    itemGap : 20,
    textStyle : {
        color : 'red'
    },
    selected : {
        '降水量' : true
    },
    data : ['蒸发量','降水量', '最高气温' ]
},
xAxis : {
    data : ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
},
yAxis : [{
        type : 'value',
        axisLabel : {
            formatter : '{value} ml'
        }
    }, {
        type : 'value',
        axisLabel : {
            formatter : '{value} °C'
        },
        splitLine : {
            show : false
        }
    }
],
series : [{
        name : '蒸发量',
        type : 'bar',
        data : [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6]
    }, {
        name : '最高气温',
        type : 'line',
        yAxisIndex : 1,
        data : [11, 11, 15, 13, 12, 13, 10]
    }, {
        name : '降水量',
        type : 'bar',
        data : [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6]
    }
]
};
setTimeout(function () {
var p = {
legend : {
selected : {
"降水量" : false
}
}
}
myChart.setOption(p);

}, 5000)·
这样并没有刷新图表信息啊。。。求教。。。

**Comment by whidy** [comment]
@wych1987 请教如何解决的
