### ISSUE TITLE
svg扩展问题

### ISSUE THREAD

**Issue by suxuekun** [ecomfe/echarts#1806]
1 pull了heatmap之后svg扩展地图例子不好使了。

2 地图扩展可否用png等普通图片格式当作背景（不是<img>放在底层而是可以随其他mark一起支持滚轮缩放）

**Comment by pissang** [comment]
1. 我这没问题，你能具体描述下么？
2. 目前不行，以后可以考虑加入，谢谢建议

**Comment by suxuekun** [comment]
football example 球场不显示

require('echarts/util/mapData/params').params.football = {
    getGeoJson: function (callback) {
       alert('a');
        $.ajax({
            url: "svg/football.svg",
            dataType: 'xml',
            success: function(xml) {
               alert('b');
                callback(xml)
            }
        });
    }
}
没有显示球场，简单测试了一下 有 alert('a')没有alert('b');

系统：max os 浏览器：chrome

但是同系统safari可以跑起来

**Comment by pissang** [comment]
没有  alert('a')没有alert('b') 就是你获取数据失败了，跟 ECharts 并没有关系

**Comment by suxuekun** [comment]
ok  是chrome自身安全设置问题，我没在服务器环境启动，不让ajax本地文件
