### ISSUE TITLE
echarts是否可以在服务器端使用？ 诸如提供保存成图片等功能的api？

### ISSUE THREAD

**Issue by mystzhm** [ecomfe/echarts#1807]
如题

**Comment by xfworld** [comment]
关注，其实你就是想直接生成图片....

**Comment by hushicai** [comment]
如果你是用nodejs，可以配合phantomjs在服务端生成图片。

示例 hushicai/echarts-server-image@b5a6b0ee2e14286e78e39a24196594dc7c23adc5

**Comment by mystzhm** [comment]
多谢回复，我试试看，有问题再请教
