### ISSUE TITLE
在某些手机上（华为，oppo）浏览器上浏览线形图，会重复画线

### ISSUE THREAD

**Issue by sm0210** [ecomfe/echarts#1812]
在某些手机上（华为，oppo）浏览器上浏览线形图，会重复画线，比如画2条线，在华为手机上浏览就会有4条线。

HUAWEI MT2-L05 手机型号 就有这种效果。。。。。。

代码：

var myChart = echarts.init(document.getElementById('lineMain'));

var option = {
			    xAxis : [
			        {
			            type : 'category',
			            boundaryGap : false,
			            data : ['周一','周二','周三','周四','周五','周六','周日']
			        }
			    ],
			    yAxis : [
			        {
			            type : 'value',
			            axisLabel : {
			                formatter: '{value} °C'
			            }
			        }
			    ],
			    series : [
			        {
			            name:'最高气温',
			            type:'line',
			            data:[11, 11, 15, 13, 12, 13, 10],
			        },
			        {
			            name:'最低气温',
			            type:'line',
			            data:[1, -2, 2, 5, 3, 2, 0],
			        }
			    ]
			};

		myChart.setOption(option);

**Comment by sm0210** [comment]
HUAWEI MT2-L05  手机型号 就有这种效果

**Comment by wind-direction** [comment]
可以试试 
animation : false,	//关闭动画
