### ISSUE TITLE
EChart能否实现选择两个点，从而选中这一段曲线？

### ISSUE THREAD

**Issue by coderwar** [ecomfe/echarts#1816]
如题

**Comment by coderwar** [comment]
自己顶

**Comment by Ovilia** [comment]
一个思路是通过[点击事件](http://echarts.baidu.com/doc/example/event.html)获取选中点的数据，然后用[markLine](http://echarts.baidu.com/doc/doc.html#SeriesMarkLine)添加一个高亮样式的线段，通过调`smooth`可以变曲线，然而要和原来的曲线完全重合，我觉得还是比较困难的……
