### ISSUE TITLE
echarts line chart smooth instead of with breaks when no data is present

### ISSUE THREAD

**Issue by mohanh** [ecomfe/echarts#1817]
Hello,

We are using the series data line chart. Is there an option where the line can be smoothed rather than showing a break ? See screen grabs below as an example in jqplot there is no breakpoint visible when data is missing

Using Echarts :- 

![Rendering using echarts](https://cloud.githubusercontent.com/assets/13328479/10361269/914d132c-6dc4-11e5-93ef-546afee8ac33.png)

Using Jqplot http://www.jqplot.com/
 
![Rendering using jqplot](https://cloud.githubusercontent.com/assets/13328479/10361268/914c4046-6dc4-11e5-8d83-23ec70c1e7a6.png)

If there is no option is it possible to guide me on a possible approach ?

**Comment by guimingfu** [comment]
Why closed?

**Comment by mohanh** [comment]
@guimingfu - No idea it wasn't implemented, I'll message @pissang

**Comment by guimingfu** [comment]
Yeah, I find a solution. 
 ```
series: [
        { },
        { },
        { 
          ...
          data:[-2, 2.2, 3.3, '', 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, -6.2],
           **connectNulls:true**
        }
    ],
```

**Comment by mohanh** [comment]
Nice, Is this in git master or do you have a separate fork ?
