### ISSUE TITLE
tooltip能否对文字个性化处理。

### ISSUE THREAD

**Issue by panh** [ecomfe/echarts#1819]
比如描述里部分文字需要红色显示，目前只看到tooltip里的textStyle对整体的样式的调整

**Comment by stanleyxu2005** [comment]
你可以查看一下tooltipFormatter的相关介绍，这个函数会提供你params数组。里面当前的数据和颜色等等信息。然后你可以直接来创建一个html，达到任何效果。

以下截图是我给我的数据做的tooltip
![example](https://cloud.githubusercontent.com/assets/5162687/8765037/b6c8f0bc-2e2c-11e5-9411-6c26b942d5a2.png)

**Comment by panh** [comment]
3q，的确可以，加个font
