### ISSUE TITLE
legend 如何監聽點擊事件 

### ISSUE THREAD

**Issue by kingispeak** [ecomfe/echarts#1821]
請問有辦法去監聽 legend 點擊事件嗎

**Comment by pissang** [comment]
文档里搜索 LEGEND_SELECTED 事件

**Comment by kingispeak** [comment]
myChart.on(ecConfig.EVENT.LEGEND_SELECTED, function (param) {
        console.log(param.target);
    });

剛剛有找到方法了，這樣就能取得我點擊時的 legend 資料。

tks.
