### ISSUE TITLE
Why you don't dispose the chart when dispose the object

### ISSUE THREAD

**Issue by lishuode** [ecomfe/echarts#1823]
In the code echart.js, you make a function "_disposeChartList()", and then for a component, in component/base.js, it will run "dispose()" and "dispose()" use "clear()", "clear()" will use "zr.delShape()" to delete the shapeList. But for a chart, in chart/*.js (included base.js), it doesn't provide a function "dispose()", but I find there is a "shapeList". Should the shapeList be delShape? Is it a bug?

Comment: I'm using the echarts, and build a legend outside the canvas. Firstly I use setOption() and restore() to sync the states. But the program be much slower after I use a setOption(option,true) several times. I debt the bug is the problem I ask above. And I use _onlegendSelected() instead of setOption() and restore(), the program won't be slow any more.

**Comment by stanleyxu2005** [comment]
Could you please post your code to reproduce the case?
