### ISSUE TITLE
柱状图和X轴的空格 怎么取消

### ISSUE THREAD

**Issue by shengxinjing** [ecomfe/echarts#1824]
rt 官网的例子http://echarts.baidu.com/doc/example/bar1.html

有几个柱子和x轴之间，大概有1px的空白，请问这个怎么去掉

![image](https://cloud.githubusercontent.com/assets/1905176/8744269/75c4f852-2ca8-11e5-92b1-948482d7dcb9.png)

**Comment by tandaly** [comment]
同求答案
