### ISSUE TITLE
Tooltip有时候不会消失

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1831]
我的折线图的tooltip的现实方式是axis。当鼠标移动到数据上，会出现tooltip。
但我发现这样一个问题，假设我创建4x4，16个一样的折线图。然后鼠标飞快的从图上掠过，不少chart上的tooltip会停在在那边不消失。如果鼠标速度控制的非常慢，就没有这个问题。感觉是有这么一个bug在。

**Comment by Ovilia** [comment]
把代码贴上来看看

**Comment by stanleyxu2005** [comment]
我直接贴了完整的html，里面需要加载bootstrap和最新版本的echart。路径麻烦自行修改替换。
···
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"/>
  <link rel="stylesheet" href="vendors/bootstrap/3.3.5/css/bootstrap.min.css"/>
</head>
<body class="container">

<div class="row" style="padding-top:50px">
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-4">
        <div id="chart1"></div>
      </div>
      <div class="col-md-4">
        <div id="chart2"></div>
      </div>
      <div class="col-md-4">
        <div id="chart3"></div>
      </div>
      <div class="col-md-4">
        <div id="chart4"></div>
      </div>
      <div class="col-md-4">
        <div id="chart5"></div>
      </div>
      <div class="col-md-4">
        <div id="chart6"></div>
      </div>
    </div>
  </div>
</div>

<script src="vendors/echarts/2.2.6-mod/echarts-all.js"></script>
<script>
  var options = {
    tooltip: {
      trigger: 'axis',
      axisPointer: {type: 'none'},
      position: function(p) {
        return [p[0], 22];
      }
    },
    grid: {borderWidth: 0, x: 5, y: 5, x2: 5, y2: 0},
    xAxis: [{
      boundaryGap: false,
      axisLabel: false,
      splitLine: false,
      data: [1, 2, 3, 4, 5, 6]
    }],
    yAxis: [{show: false}],
    series: [{
      type: 'line',
      data: [100, 120, 110, 120, 110, 120]
    }]
  };

  [1, 2, 3, 4, 5, 6].map(function(i) {
    var container = document.getElementById('chart' + i);
    container.style.width = '100%';
    container.style.height = '64px';
    var chart = echarts.init(container);
    chart.setOption(options, true);
  });
</script>
</body>
</html>
···

![result](https://cloud.githubusercontent.com/assets/5162687/8938011/7bc087aa-358e-11e5-9f01-267d3ed9ac9a.png)

**Comment by stanleyxu2005** [comment]
@pissang 我对比了一下highchart，当鼠标移出chart之后，highchart会延时做一个检查，发现鼠标不再chart区域范围内，隐藏掉还残留的tooltip。希望echart可以借鉴这个做法，做一个后台检查，我觉得这样可以解决这个问题。

**Comment by pissang** [comment]
谢谢建议，我们会在新版本考虑这点

**Comment by stanleyxu2005** [comment]
找到原因了。`tooltip.js`里面
```
        self._onmousemove = function (param) {
            return self.__onmousemove(param);
        };
        self._onglobalout = function (param) {
            return self.__onglobalout(param);
        };
```
这里的globalout从来没有触发过。而这个chart对应的dom的onmouseout并没有注册过hideTooltip的方法，我现在改了一下就好了。具体参考pr。
```
        self.dom.onmouseout = function (param) {
            return self.__hideTooltip(param);
        };
...
        __onglobalout: function () {
            this.__hideTooltip();
        },

        __hideTooltip: function () {
            clearTimeout(this._hidingTicket);
            clearTimeout(this._showingTicket);
            this._hidingTicket = setTimeout(this._hide, this._hideDelay);
        },
```

**Comment by Hz-Raigor** [comment]
5.0.0版本，这个问题又出现了，滚动鼠标tooltip不会消失

**Comment by zmbxy95** [comment]
5.0.0版本中，我也遇到了相同的问题

**Comment by pissang** [comment]
5.0.1 中修复了这个问题

**Comment by chenghao94** [comment]
5.1.2版本中，我也遇到了相同的问题。多个图表，快速移动，有的时候tooltip不会消失

**Comment by chenghao94** [comment]
![image](https://user-images.githubusercontent.com/46017290/132605862-c0d060f4-106d-4bb1-a0f9-469a79cd8bcc.png)
