### ISSUE TITLE
after echart Instance invoke resize() method , dataloading size no change

### ISSUE THREAD

**Issue by ice0526** [ecomfe/echarts#1833]
resize之前
![before](https://cloud.githubusercontent.com/assets/13415001/8772803/be10a9de-2f01-11e5-8dd0-884946da15bf.png)
resize之后
![after](https://cloud.githubusercontent.com/assets/13415001/8772804/beafc690-2f01-11e5-971b-53656c042904.png)

**Comment by xfworld** [comment]
我也遇到过这样的问题，不知道有没有解决办法

**Comment by Z-starts** [comment]
+1024
