### ISSUE TITLE
chart.component.tooltip.showTip() not working when tooltip trigger is 'axis'

### ISSUE THREAD

**Issue by lhorak** [ecomfe/echarts#1835]
I am trying to display tooltip by using chart.component.tooltip.showTip({seriesIndex:"0", dataIndex:"0"}) but the function is not working when tooltip trigger option is set to 'axis'. 

The function returns on this condition(echarts-all: line 4338):

```javascript
if (this.component.polar == null || serie.data[0].value.length <= dataIndex) {
    return;
}
```

When I change the trigger option to 'item' everything is working fine. Is there any solution to this problem? Thank you

**Comment by kener** [comment]
I think it is a bug. @pissang @100pah

**Comment by lhorak** [comment]
Is there any hotfix for this that I could use? Or is it possible that it's going to be fixed in next version? Thank you

**Comment by zhump** [comment]
确实是bug

**Comment by aryakochukrishnan** [comment]
Hi All, I know this is an old bug post. But =, I still face the same problem. The tooltip is not triggered when  trigger:'axis'.  echarts v3.4.0
