### ISSUE TITLE
echarts是否存在dataZoom功能的回调函数功能

### ISSUE THREAD

**Issue by chenming142** [ecomfe/echarts#1842]
因为在移动端，所以想在dataZoom功能执行完成，能通过title或legend属性显示该时间段，如下图
![qq 20150722140903](https://cloud.githubusercontent.com/assets/653458/8819058/1dc21b36-307b-11e5-83df-8be008475208.png)

或有什么其他简便的方式能实现么？

**Comment by longFeiLi** [comment]
可以用拖动事件去做这件事、

**Comment by chenming142** [comment]
找到了事件，简单的实现了，不过里面有太多的坑了，有大神的话，希望可以优化下，代码如下：
![1](https://cloud.githubusercontent.com/assets/653458/8820993/a1794434-308c-11e5-8fb9-4f16e57c7c6d.png)

简单说明下：
1）第一个红框，是 echarts 的内置 dataZoom 事件，这里不得不说，不晓得事件回调的参数有啥用。
2）第二个红框，比较重要，是拿到xAxis轴范围的方法，看源代码发现的。
3）第三个红框，就是与业务有关了，需要更新问题中的右上框的 title 的text.刚开始没有调用 .refresh() 发现，每次都会延迟一次render,即第一次拖动时，不会改变显示，第二次显示的是第一次的值，后面增加refresh()方法后，没出现问题了。

可是这里有个疑虑，应该来说，每一个改变都会自动调用呀，为什么echarts开发者，没做这个操作呢？或者说，他们做了在改变之前，那调用两次会不会存在性能或其他问题呢？

大神，来看看吧！！！

**Comment by pissang** [comment]
因为你在 DATA_ZOOM 事件中又修改了图表上的东西，肯定要重新 refresh，可以改用自定义的 div 去显示这个 title

**Comment by lifeforfun** [comment]
e
