### ISSUE TITLE
echart svg extension can not show <image> tag in xxx.svg

### ISSUE THREAD

**Issue by suxuekun** [ecomfe/echarts#1843]
1 my svg file contains a image tag and some polygon tag
2 I load the svg in eChart
3 polygon shows but image not 

is eChart not support the image tag in svg?

**Comment by suxuekun** [comment]
my situation is that I have a map.jpg ,and i create a map.svg contains a image tag imported the map.jpg.
I draw some polygens on the map.svg.
The i import the svg in eChart
only the polygens shows in eChart but map.jpg is not.

**Comment by Ovilia** [comment]
Post your code here.

**Comment by pissang** [comment]
Not supported yet
