### ISSUE TITLE
tooltip 中 format 参数 params 显示线条颜色

### ISSUE THREAD

**Issue by yuanxiaolong** [ecomfe/echarts#1844]
能否在 tooltip 的 params 里 暴露出 lineColor 属性 ？

``` js
formatter: function(params, ticket, callback)
```

开发者可以获取到这个颜色自己format，这样提示的文字颜色 ，就可以和线条颜色保持一致，交互更友好了。

**Comment by fegg** [comment]
我也有这个需求。。。怎么没人回答呀

**Comment by pissang** [comment]
已在 commit https://github.com/ecomfe/echarts/commit/86bcb9a87bcc568d7ef6427aba45ec105f0d0bee 中加入
