### ISSUE TITLE
当有缩放时，tooltips 中的 dataIndex是当前显示的数据的index，而不是所有数据的

### ISSUE THREAD

**Issue by LeoZeda** [ecomfe/echarts#1846]
在下面这个例子中，添加tooltips hover 事件 可以看到。
http://echarts.baidu.com/doc/example/event.html

myChart.on(ecConfig.EVENT.TOOLTIP_HOVER, eConsole);

![2015-07-22 7 35 15](https://cloud.githubusercontent.com/assets/8565999/8824533/326191a6-30a9-11e5-847d-d75d39714aa1.png)

是在使用tooltip formatter 中的参数发现的
想问要怎么获取所有数据的index？

**Comment by Ovilia** [comment]
有点不明白你的问题是什么意思，`tooltip` 当然是当前高亮的对应的 `index`，所有数据的 `index` 不就是 `[0, 1, 2, 3, ...]` 这样？这有什么意义吗？你直接读 `option.series` 的数据不行么？

**Comment by LeoZeda** [comment]
假设折线图总共有100个数据，使用缩放(dataZoom)显示10个数据，其他数据通过拖动缩放条查看。TOOLTIP_HOVER事件返回的dataIndex是显示的这10个数据中的index，而不是100个数据的index。而其他事件，如click是返回100个数据的index。

http://echarts.baidu.com/doc/example/event.html
就用上面的例子说明，同样是将缩放条拖到最后，tooltip的dataindex是5，当前显示了6个数。而click事件的dataindex是29，所有数据的index。
![2015-07-29 5 07 58](https://cloud.githubusercontent.com/assets/8565999/8953949/cce17e4c-3614-11e5-9ae1-d7d95e8fa96d.png)

![2015-07-29 4 59 49](https://cloud.githubusercontent.com/assets/8565999/8953942/c27ecc52-3614-11e5-848d-804f978ec36e.png)

不知道这样说清不清楚。

**Comment by LeoZeda** [comment]
使用tooltips的时候有没有办法获取全局的index？

**Comment by Ovilia** [comment]
似乎是不能的，至少我没有发现，因为这两个实现的机制是不同的，调用方法也完全不一样。

Tooltip 的代码在[这里](https://github.com/ecomfe/echarts/blob/89969cb716218a721a8bc6982c94cf31d4e17630/src/component/tooltip.js#L677)，计算的时候就是只判断可视部分的。
一个可能的 ad hoc 办法是利用 `dataZoom` 的事件，读取当前缩放的起始位置，再加上当前 `tooltip` 获得的相对位置。
```
chart.on(config.COMPONENT_TYPE_DATAZOOM, function(e) {
    console.log(e.zoom.start);
});
```

但是这种办法只能在用户改变 `dataZoom` 的选择区域或者范围时才会触发。具体怎么解决你参考自己的需求再想想吧。

**Comment by LeoZeda** [comment]
主要是dataZoom的zoom.start是百分比，不是实际index的起始位置，不是很好换算

**Comment by kener** [comment]
try this
myChart.component.dataZoom.getRealDataIndex( sIdx, dIdx)  // sIdx for series index, dIdx for data index

http://echarts.baidu.com/doc/example/k1.html
myChart.component.dataZoom.getRealDataIndex(0, 2) == 46

**Comment by LeoZeda** [comment]
@kener, it worked, thank you very much.
