### ISSUE TITLE
dataView中的数据不可复制？

### ISSUE THREAD

**Issue by readyou** [ecomfe/echarts#1849]
http://echarts.baidu.com/doc/example/toolbox.html
这里查看数据时，发现不可复制。既然没有导出数据的功能，为什么还不能复制呢？

能不能加上复制，最好有导出数据的功能。

**Comment by pissang** [comment]
看其它有 toolbox 的示例

**Comment by sunlei99** [comment]
Hi, 我参照
http://echarts.baidu.com/doc/example/toolbox.html
中的例子重写了dataview的optionToContent函数，dataview显示的内容无法复制，为什么呢？
数据可以显示，但不能复制，以下为其他设置：
'dataView': {'show': true, 'readOnly': false, 'title': '详细数据'},

**Comment by alsotang** [comment]
我这也发现了，重写了 optionToContent 之后的 dataview 是没法复制的
