### ISSUE TITLE
宽度小于378的时候，x轴的竖线栅格会不见了好几个，是有什么参数设置吗？

### ISSUE THREAD

**Issue by 327326724** [ecomfe/echarts#1850]
本来x轴有9个数据7条竖线，宽度小于378后，只剩4条了。

**Comment by xfworld** [comment]
grid搞小点

**Comment by 327326724** [comment]
我没设置大小啊，这个不是自适应的么

**Comment by Ovilia** [comment]
`grid` 控制的是图表绘图区域的大小，并非是解决这个问题的正确方式。
这里的“栅格线”的术语是 [`splitLine`](http://echarts.baidu.com/doc/doc.html#AxisSplitline)

控制 `splitLine` 个数的源代码在 [src/component/categoryAxis.js](https://github.com/ecomfe/echarts/blob/21bb5cb718840f9f160642e98bdb522c5f0af7a7/src/component/categoryAxis.js)
`splitLine` 栅格线个数的计算方式在 [_getInterval()](https://github.com/ecomfe/echarts/blob/21bb5cb718840f9f160642e98bdb522c5f0af7a7/src/component/categoryAxis.js#L123)。

`gap` 是指每两条栅格线之间的像素数；`interval` 是指间隔多少个类别画栅格，为 0 时则每个数据都画，为 1 时间隔 1 个画，以此类推。
阅读了源码之后，我觉得这部分的实现还是挺精妙的。它会根据所有坐标轴文字是否排得下来调整 `interval` 从而调整 `gap`，如果排不下就不断增加 `interval`，直到 `interval` 等于数据个数时什么栅格线都不画。

===
以上懒得看也没关系，结论就是，以下是你可以在 option 中改变的（任选一种即可）：
1. 指定 `axisLabel.interval` 值，如设为 0 则强制显示所有栅格线
2. 减小 `axisLabel.textStyle.fontSize`：上面说过，能不能放得下是由文字占了多少像素决定的

通常情况下使用第一种方法比较合理，第二种方法有点走旁门左道了。

===
附 option 例子。
```
var option = {
    xAxis: [{
        type: 'category',
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"],
        axisLabel: {
            interval: 0
        }
    }],
    yAxis: [{
        type : 'value'
    }],
    series: [{
        name: 'test',
        type: 'bar',
        data: [100, 200, 120, 420]
    }]
};

**Comment by 327326724** [comment]
谢谢，解决了！

**Comment by xfworld** [comment]
这个回复给力；
