### ISSUE TITLE
如何设置图表的边距

### ISSUE THREAD

**Issue by gastrodia** [ecomfe/echarts#1851]
![9082f386-c06d-4159-8607-69ca405affc8](https://cloud.githubusercontent.com/assets/4869158/8875022/b269b216-3248-11e5-9fcf-c61865e97498.png)

感觉这些区域空白区域太大，很多图表在一个页面展示的适合，整体感觉很不美观，请问如何设置？

**Comment by 327326724** [comment]
配置gird参数：
gird:{
x:'0px',
y:'0px',
x2'0px',
y2:'0px'
}

**Comment by wych1987** [comment]
http://echarts.baidu.com/doc/doc.html#Grid 文档说明很清楚啊

**Comment by aufula** [comment]
设成0，Y轴的值就看不到了。Y轴的值的宽度不固定的。
