### ISSUE TITLE
堆积图不能跨越象限堆积

### ISSUE THREAD

**Issue by jiyujie880621** [ecomfe/echarts#1852]
画瀑布图的时候，总是在第一象限内进行的，因此正常情况下无论是正向增加还是反向增加，只要这条线段的起止点都位于第一象限，那么都可以使用一个透明的堆积块填充在前面进行堆积。但是，假如我有一条线段从第一象限跨越到第二象限，即从正值直接下降到一个负值，起始点为5，结束点为－5，那么好像目前的堆积图是无法实现的。
不知道我描述的场景是否是不支持还是我的理解不够。谢谢

**Comment by Ovilia** [comment]
我能大致理解你的需求，但是我不觉得用堆积图是一个比较好的实现方法，看起来太 ad hoc 了。我觉得倒是可以尝试一下用 K 线图，比如把开盘价和最低价设为同一个数，把收盘价和最高价设为同一个数。
