### ISSUE TITLE
绘制饼图或者玫瑰图的时候,如果数据项中的value都为0,那么图形该如何绘制？

### ISSUE THREAD

**Issue by zuoRambo** [ecomfe/echarts#1853]
现阶段的echarts的选择是不绘制饼图但是显示图例，我觉得应该换一种展示方式,比如还是绘制图 但是是空的或者饼图区域绘制bubble的effect

**Comment by pissang** [comment]
数据为 0 不代表没数据

**Comment by zuoRambo** [comment]
@pissang 但是现有的展现不太好～～

**Comment by pissang** [comment]
可以试下设置饼图的 minAngle

**Comment by LeoZeda** [comment]
设置minAngle好像还是没有用～ 
还是显示空白的图
