### ISSUE TITLE
力导向图links里的itemStyle无效问题

### ISSUE THREAD

**Issue by Jeepeng** [ecomfe/echarts#1854]
想设置每条link的颜色，看到文档上有 series[i](force).links.itemStyle：
itemStyle: {
    type: 'line',
    color: '#FF0000',
    width: 1
}
但是设置后无效

**Comment by pissang** [comment]
```javascript
itemStyle: {
       normal: {
              type: 'line'
        }
}
```

参考 force.html

**Comment by Jeepeng** [comment]
配置项查找工具里的结构有问题：http://echarts.baidu.com/doc/option.html#title~series-i(force).links.itemStyle
已解决！Thanks！
