### ISSUE TITLE
三星手机加载echarts出现图表重复问题

### ISSUE THREAD

**Issue by hypo1986** [ecomfe/echarts#1857]
三星手机加载echarts出现图表重复问题
不知道怎么解决 ？请教 ...

**Comment by Ovilia** [comment]
具体的 option 以及效果图贴出来

**Comment by SogoodQian** [comment]
是三星手机显示力导向图会出现图表重复问题，官网的力导向图示例在三星手机上就会出现重复，不知道怎么解决，你们那三星手机试试就知道了

**Comment by MOLVMIN** [comment]
希望问题能尽快解决，在三星跟华为的手机上都会出现重绘这样的问题，很困扰啊

**Comment by MOLVMIN** [comment]
希望问题能尽快解决，在三星跟华为的手机上都会出现重绘这样的问题，很困扰啊
