### ISSUE TITLE
setOption时，boundaryGap未起作用

### ISSUE THREAD

**Issue by visgoods** [ecomfe/echarts#1859]
同一个实例，使用setOption在三个数据源来回切换时， 除第一个boundaryGap有作用外，使用setOption创建的图两边没有空隙。

**Comment by Ovilia** [comment]
把具体的 option 贴出来

**Comment by visgoods** [comment]
又仔细看了几次，应该还是起了作用。
应该是数据太多，而x轴又是日期，会导致最右边的那个label会被遮盖住。
