### ISSUE TITLE
力导向图的迭代计算抖动效果十分浮夸

### ISSUE THREAD

**Issue by Ovilia** [ecomfe/echarts#1860]
在[这个例子](http://echarts.baidu.com/doc/example/webkit-dep.html)中，拖动一个点后的迭代计算过程中，全部的点都在抖动，效果实在太浮夸！
可以考虑在稳定前不更新位置，等迭代计算完，再用动画移到相应位置。

**Comment by pissang** [comment]
上次在算法上做过一次优化后确实发现速度变快了但是动画效果没以前好了=   =
