### ISSUE TITLE
没有数据时，markline会报错。

### ISSUE THREAD

**Issue by jeatime6** [ecomfe/echarts#1861]
markline在有数据的情况下正常，没有数据时会报异常；

option部分代码：
![image](https://cloud.githubusercontent.com/assets/6733968/8921719/5e2440e2-350c-11e5-93f7-042e2bd9fa40.png)
错误提示：
![image](https://cloud.githubusercontent.com/assets/6733968/8921746/9af9ebde-350c-11e5-9b96-d72530c070e5.png)

去掉markline选项，显示正常。
不知道是什么原因，还请帮忙，非常感谢。

**Comment by Ovilia** [comment]
授你以渔吧~
调试的时候就不要用压缩后的文件了，参见[模块化的调用方法](http://echarts.baidu.com/doc/start.html)，并且可以使用 src 下的文件而不是压缩后的 `dist` 下的文件。
```
<script type="text/javascript" src="../echarts/doc/asset/js/esl/esl.js"></script>
<script type="text/javascript" src="../echarts/src/echarts.js"></script>

然后根据报错的位置打断点，步入查看是什么原因。相信你会学到更多~（或者发现一个 bug）

**Comment by longFeiLi** [comment]
版本问题还是浏览器问题？谷歌浏览器官网例子没有发现问题
