### ISSUE TITLE
echarts 与 arcgis javascript 冲突

### ISSUE THREAD

**Issue by bsxsb** [ecomfe/echarts#1862]
按照  https://github.com/ecomfe/echarts/issues/1258
没能解决我的问题。
我在index.html页面中引入echarts 和 arcgis api，

    
    <script src="../bower_components/echarts/dist/echarts-all.js"></script>

    
    <link rel="stylesheet" href="http://js.arcgis.com/3.14/esri/css/esri.css">
    <script src="http://js.arcgis.com/3.14/"></script>

然后就出错了，如下图

![111](https://cloud.githubusercontent.com/assets/828964/8922316/ee9bc29c-3513-11e5-9425-3e4599ba94e0.png)

求应该怎么解决，先谢谢了。

**Comment by hushicai** [comment]
你这段代码在我这试用是没问题的，请仔细检查一下。

**Comment by bsxsb** [comment]
我这边还是不行，我是在没法解决这个问题，能不能把你的demo给我发一份，我看看，我的邮箱：112296629@qq.com ， 感谢。
