### ISSUE TITLE
how to draw graphs from dot files?

### ISSUE THREAD

**Issue by peng-zhao** [ecomfe/echarts#1863]
I want to visualize some dot files generated in my program. The dot files describe graphs.

Does echarts support this? Any document or links would be appreciated. Thanks a lot.

**Comment by Ovilia** [comment]
What is a dot file?

**Comment by peng-zhao** [comment]
https://en.wikipedia.org/wiki/DOT_(graph_description_language)

**Comment by Ovilia** [comment]
I don't think so. Maybe you should write a script to do this.
