### ISSUE TITLE
怎样模块化地在require()语句外引用echarts实例？

### ISSUE THREAD

**Issue by GeeBar** [ecomfe/echarts#1864]
// 不习惯模块化的你当然可以
var echarts;
require(['echarts'], function (ec){
    echarts = ec;
});
// 是的，把echarts加载后保存起来作为命名空间使用

除了以上非模块话的方法，有没有人能讲解下模块化的引用方法...
------------------------------------------------以上示例代码不是我想表达的，不好意思，让人误解了---------------
重新说：
var sexCompositionChart;
require(
    [
        'echarts',
        'echarts/chart/pie'
    ], function(ec) {
        // 基于准备好的dom，初始化echarts图表
        sexCompositionChart = ec.init($('#sexComposition .chart')[0]);
})
我是想问sexCompositionChart这个echarts的实例变量，有没有别的方法(除了以上)可以在require语句外使用...

**Comment by hushicai** [comment]
文档中不是有吗？

**Comment by GeeBar** [comment]
@hushicai 有吗？我没看到。我看到的就是我贴出来的“不习惯模块化”的卖萌语句

**Comment by GeeBar** [comment]
@pissang 麻烦老兄，你了解么

**Comment by pissang** [comment]
http://echarts.baidu.com/doc/doc.html#引入ECharts1 有介绍三种方式

**Comment by GeeBar** [comment]
@hushicai @pissang 抱歉，之前表达失误。

**Comment by hushicai** [comment]
当然可以，你只需要判断require什么时候完成就行。

**Comment by GeeBar** [comment]
@hushicai 是的。我这种做法需要检测require完成，有没有方法可以使用完成状态的实例？

**Comment by hushicai** [comment]
这取决于你是怎么组织你的代码。。。

你完全可以在require回调里面把echarts实例赋值给一个全局变量，然后再调用你的业务逻辑代码。

**Comment by GeeBar** [comment]
@hushicai  你说的不就是我贴的这个么？
	var sexCompositionChart;
	require(
	    [
	        'echarts',
	        'echarts/chart/pie'
	    ], function(ec) {
	        // 基于准备好的dom，初始化echarts图表
	        sexCompositionChart = ec.init($('#sexComposition .chart')[0]);
	})

这样做我没法确定require完成啊

**Comment by hushicai** [comment]
你在赋值的时候，同时调用你的业务代码的入口，不就能保证了吗？？？

```javascript
sexCompositionChart = ec.init($('#sexComposition .chart')[0]);

logicEntryFunction(); // 总有业务个入口吧？
```

**Comment by GeeBar** [comment]
@hushicai  我之所以把实例提出来，是为了加载新数据时，不再重复init  好吧，如果效率没什么影响，也可以。

**Comment by pissang** [comment]
需要模块化加载的前提是自己的代码也是模块化组织的，那不存在你说的这种情况，如果自己代码不是模块化组织的话可以使用 echarts-all.js，如果觉得 echarts-all.js 太大的话可以从 [echarts-builder-web](ecomfe.github.io/echarts-builder-web) 中打包。这个问题就到这里，close 了

**Comment by GeeBar** [comment]
@pissang  了解。 @hushicai 多谢
