### ISSUE TITLE
图表数据长度小于X轴长度时，拖动dataZoom，图表显示不完全

### ISSUE THREAD

**Issue by GeeBar** [ecomfe/echarts#1866]
<img width="732" alt="2015-07-29 5 56 37" src="https://cloud.githubusercontent.com/assets/1564444/8955208/4f374856-361d-11e5-9a49-8cef97a0cb4f.png">
如图，图表数据长度小于X轴长度，拖动dataZoom尾游标至7月，图表数据区域遮盖了5、6、7月的数据。
我猜：图表数据区域计算需更新吧

**Comment by Ovilia** [comment]
贴一下 option 代码

**Comment by GeeBar** [comment]
@Ovilia  很简单，就是去掉了样例中的几个数据而已。
option = {
    title : {
        text: '某地区蒸发量和降水量',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['蒸发量','降水量']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
  dataZoom: {
                    show: true,
                    realtime: true,
                    start: 0,
                    end: 100
                },
    series : [
        {
            name:'蒸发量',
            type:'bar',
            data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6],
          
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            }
        },
        {
            name:'降水量',
            type:'bar',
            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6],
           
            markLine : {
                data : [
                    {type : 'average', name : '平均值'}
                ]
            }
        }
    ]
};
