### ISSUE TITLE
折线图显示问题，看图

### ISSUE THREAD

**Issue by hail812** [ecomfe/echarts#1867]
### 纵坐标不对，如果把搜索引擎的data全部改为0的话，然后把鼠标放在“搜索引擎”，就乱了
![image](http://fa.hailog.com/static/images/echartsbug0.jpg)

**Comment by pissang** [comment]
这是开启堆叠后的效果，并不是乱了

**Comment by hail812** [comment]
原来在这，stack这个属性，谢谢
