### ISSUE TITLE
echarts 支持 requirejs吗

### ISSUE THREAD

**Issue by hqqxxf** [ecomfe/echarts#1869]
引入requirejs后echarts报错了，有什么解决办法吗

**Comment by Ovilia** [comment]
http://echarts.baidu.com/doc/start.html

注意路径。可以把具体的错误和代码贴上来。

**Comment by hqqxxf** [comment]
已解决，用了echarts-all.js这个是纯js写的，不是AMD模块化后的，所以不会冲突
