### ISSUE TITLE
能提供新手容易看懂的实例吗？

### ISSUE THREAD

**Issue by MingChuanSun** [ecomfe/echarts#1870]
作为一个刚接触html5 Canvas的新手，这个开源项目我下载后发现里面的实例效果很赞，可对我而言像是天书，这么酷酷的效果看得着，用不到，你们对新人太残忍了！

**Comment by Ovilia** [comment]
用 echarts 也基本不需要 Canvas 知识吧……实例不是写得挺清楚么，你具体的疑惑是什么，比如是不是例子的代码太长了，想知道使用某一功能所需要的最小例子这样？

**Comment by MingChuanSun** [comment]
刚才网上搜了个小例子，花半小时没有实现，下载别人的源代码一看。是因为定义的div没指定height的值，这不是让人搞不懂吗。而且这种纯js的写法，对新手来说伤害太大了。我在html和js里面都看不到canvas这个单词。用起来真是心里不踏实，可能我对不知道原理的东东比较抵触。

**Comment by Ovilia** [comment]
不要担心哦~ 学习新东西都会有这样的阶段的嘛，有具体的问题可以把代码贴到 issue 里来问，虽然我们精力比较有限，可能没法即使回复，但是会尽力帮助大家的~~
先好好看下[入门教程](http://echarts.baidu.com/doc/start.html)，尤其注意一下路径之类的。然后把[这么多实例](http://echarts.baidu.com/doc/example.html)的 `option` 替换掉看看结果，慢慢摸索一下，相信自己，坚持过这段启动期就会好哒~加油！:muscle:
有具体的问题再开新的 issue 吧，这个我先关了，另外可以看看[提问的技巧](https://lug.ustc.edu.cn/wiki/doc/smart-questions)。
