### ISSUE TITLE
饼图Pie(环形图)的鼠标悬停效果

### ISSUE THREAD

**Issue by gushitong** [ecomfe/echarts#1871]
能否实现鼠标悬停在饼图Pie(环形图)的扇形上,扇形向外突出一部分的动画效果?
查了Echarts的相关Config,好像没有 ...

**Comment by Ovilia** [comment]
并没有这样的功能。
而且鼠标悬停就突出的话，如果鼠标点在环形内部，环形往外突出后就不悬停了，导致又不突出了，然后就会抖啊抖……点击还是可以考虑的，但暂时没有实现。

**Comment by gushitong** [comment]
好的 谢了～
