### ISSUE TITLE
折线图部分虚线

### ISSUE THREAD

**Issue by Denis007** [ecomfe/echarts#1872]
折线图需要部分虚线表示，在data设置lineStyle没用，该怎么处理？

**Comment by Denis007** [comment]
![image](https://cloud.githubusercontent.com/assets/5285486/9000187/2303fae0-3776-11e5-8b1f-6e374eb298cc.png)

**Comment by longFeiLi** [comment]
option.series.symbolSize: 0  隐藏点。

**Comment by lsllsllsl** [comment]
请问部分虚线怎样实现

**Comment by xiang2026** [comment]
@guobingrong 请问下如何实现这种一半实线一半虚线的效果，方便给个例子吗？我这边尝试用两条线去叠加，但是因为选了平滑，去掉实线的最后一个点之后，看上去线条拟合的结果不太对了。
