### ISSUE TITLE
多层控制设计原则对树图的lineStyle属性无效，只能在option里设置lineStyle

### ISSUE THREAD

**Issue by wuhongjie89** [ecomfe/echarts#1873]
如标题所说。
以我的想法，应该是可以做到，任意两个节点间的个性化连线的。
但目前尝试下来，没法成功。
我的想法是，当我鼠标移动到某个节点，或者是选中某个节点时，此节点到根之间的路径连线会高亮，变红，变粗或者是其他个性化的做法。

**Comment by wuhongjie89** [comment]
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
</head>

<body>

<div id="main" style="height:400px"></div>

<script src="../build/dist/echarts.js"></script>
<script src="tree.js"></script>
</body>

**Comment by wuhongjie89** [comment]
// 路径配置
require.config({
    paths : {
        echarts : '../build/dist'
    }
});

var config, treeData = [];
require(['/echarts-2.2.7/src/config'], function (conf) {
    config = conf;
});

// 使用
require(
    [
        'echarts',
        'echarts/chart/tree', // 使用柱状图就加载bar模块，按需加载
        '/echarts-2.2.7/doc/example/theme/blue'
    ],
    function (ec, tree, blueTheme) {
        // 基于准备好的dom，初始化echarts图表
        var myChart = ec.init(document.getElementById('main'), blueTheme);

        var option = {
            title      : {
                text    : '树图',
                subtext : '虚构数据'
            },
            tooltip    : {
                show      : true,
                formatter : "{b}"
            },
            toolbox    : {
                show    : true,
                feature : {
                    mark        : {show : true},
                    dataView    : {show : true, readOnly : false},
                    restore     : {show : true},
                    saveAsImage : {show : true}
                }
            },
            calculable : true,

            series : [
                {
                    name         : '树图',
                    roam         : true,
                    type         : 'tree',
                    orient       : 'horizontal',  // vertical horizontal
                    direction    : '',
                    rootLocation : {x : 'left', y : 'center'}, // 根节点位置  {x: 100, y: 'center'}
                    nodePadding  : 3,
                    data : getRoot(),
                    symbol : 'circle',
                    itemStyle: {
                        normal: {
                            label: {
                                show: false
                            }
                        }
                    }
                }
            ]
        };

        // 为echarts对象加载数据
        myChart.setOption(option);
        myChart.on(config.EVENT.CLICK, function (node, tree) {
            console.log("1");
        });
        myChart.on(config.EVENT.DBLCLICK, function (node, tree) {
            if(node.data.children === undefined || node.data.children.length === 0){
                option.series[0].symbol = 'image://refresh_loading.gif';
                myChart.setOption(option);
                setTimeout(function(){
                    option.series[0].data = getData();
                    option.series[0].symbol = 'circle';
                    myChart.setOption(option);
                }, 1000);
            }
            else{
                option.series[0].data = getRoot();
                myChart.setOption(option, true);
            }
        });
    }
);

function getRoot() {
    return [{name : 'root', children : []}];
}

function getData() {
    return [
        {
            name     : 'root',
            value    : 6,

            children : [
                {
                    name     : 'node1',
                    value    : 4,
                    itemStyle: {
                        normal: {
                            label: {
                                show: false,
                                position: 'right',
                                formatter: "{b}"
                            },
                            color: 'blue',
                            borderWidth: 2,
                            borderColor: 'black',
                            lineStyle :{
                                color : 'red',
                                width : '5'
                            }

                        },
                        emphasis: {
                            color: 'red',
                            borderWidth: 0
                        }
                    }

                },
                {
                    name     : 'node2',
                    value    : 4,
                    itemStyle: {
                        normal: {
                            label: {
                                show: false,
                                position: 'right',
                                formatter: "{b}"
                            },
                            color: 'blue',
                            borderWidth: 2,
                            borderColor: 'black',
                            lineStyle :{
                                color : 'red',
                                width : '5'
                            }

                        },
                        emphasis: {
                            color: 'red',
                            borderWidth: 0
                        }
                    }
                }
            ],
            itemStyle: {
                normal: {
                    label: {
                        show: false,
                        position: 'right',
                        formatter: "{b}"
                    },
                    color: 'blue',
                    borderWidth: 2,
                    borderColor: 'black',
                    lineStyle :{
                        color : 'red',
                        width : '5'
                    }

                },
                emphasis: {
                    color: 'red',
                    borderWidth: 0
                }
            }
        }
    ];
}

**Comment by pissang** [comment]
谢谢反馈

**Comment by wuhongjie89** [comment]
@pissang 会什么时候修复呢？这个特性还蛮重要的，用了的话可以对树图上一些关键路径做出一些特殊标识
