### ISSUE TITLE
如何给markPoint添加事件？

### ISSUE THREAD

**Issue by scgy5555** [ecomfe/echarts#1875]
地图类型map 使用markPoint   
有看到clickable属性 但并没有教程或案例说明怎么添加事件   
在线等！急   
   
   
ps:文档写的太烂，是因为员工理解能力不足？！

**Comment by Ovilia** [comment]
事件处理的例子在 http://echarts.baidu.com/doc/example/event.html

文档在慢慢改进中，感谢亲的耐心支持~~（求客服奖金）

**Comment by scgy5555** [comment]
@Ovilia 非常感谢，但你并没有回答我的问题
这个案例我当然看了 首先这就不是个type:map的地图

因为地图类型如果监听click会发生点击区域和点击markpoint都会触发
而我只需要markpoint的触发，这就比较蛋疼
我知道这是一个shape但是我没有一个独特的参数来区分

所以不仅没有客服奖金，连问题都没看懂就乱答可能今年奖金都要扣光了

真正让我感到疑惑的是文档明显有一个clickable的属性
却没有区分地图区域和markpoint的办法
我这样说您能叫高级点的工程师回来解决我的问题吗？

**Comment by pissang** [comment]
好好描述问题谢谢

**Comment by scgy5555** [comment]
@pissang 问题：如何给markPoint添加事件？

**Comment by zhaojun12** [comment]
我似乎发现了 Github 邮件通知的一个 BUG？
* 邮件通知里只写了 “@pissang
问题：如何给markPoint添加事件？”
* 而没有后面的 “描述” 等内容

**Comment by Justineo** [comment]
@scgy5555 既然你谈到了尊重这个词，我建议你回顾一下自己创建的 issue 内容和自己的回复是否足够友善。说你没有好好描述问题，是因为你的态度并非常人可以理解的寻求帮助的态度。我想这是基本的礼貌问题。如果真心有问题需要帮助，欢迎你以更礼貌的方式重新发问。

**Comment by scgy5555** [comment]
@Justineo 所以我问 hi，海南大酒店怎么走？有人告诉我你坐110就能到重庆公园，还不允许我讽刺两句吗？哪来的文字狱？！

我的态度很明确，也并不是虚心请教的态度，因为这是百度的产品，我是产品的用户
我很客气的描述了我的问题 并且补充了文档写的太烂
Ovilia 同学很不负责的把跟问题几乎没有关系的地址发了过来
我也很友善的喷了回去 只加了一句 是因为员工理解能力不足？！

所以你又是哪位？能让你激发正义之心疯狂质疑一个普通用户在产品使用中遇到的问题
ps 非常欢迎您带队来争吵
