### ISSUE TITLE
实例中数据视图修改时，如果减少一列数据，刷新时不会列数不减少，显示值为空的列

### ISSUE THREAD

**Issue by flyingtimes** [ecomfe/echarts#1877]
在使用教学实例的适合，随便选取一个图标，然后点击“数据视图”，修改数值时显示正确，但企图减少一列数据的时，例如原来是“1-12月”总共12列数据，改成“1-11月”时，图仍然显示12列的数值，其中12月份的数值为空。

**Comment by Ovilia** [comment]
确实存在这个问题，应该是个 bug。
