### ISSUE TITLE
默认标志图形颜色是否可以自定义

### ISSUE THREAD

**Issue by myccnice** [ecomfe/echarts#1879]
symbolList可以自定义默认标志图形的形状，但我没有看见默认标志图形颜色相关的属性，请问这些图型的颜色可以自定义吗？

**Comment by Ovilia** [comment]
通过设置 `series` 的 `itemStyle.normal.color` 设置颜色：http://echarts.baidu.com/doc/example/line.html “直接访问”系列的例子。

**Comment by myccnice** [comment]
非常感谢你的回复
