### ISSUE TITLE
气泡图的气泡大小应该根据当前图表尺寸自动缩放

### ISSUE THREAD

**Issue by ohfang** [ecomfe/echarts#1880]
现在气泡图的series: symbolSize需要是一个函数，但是函数的参数只是当前点的value数组，无法实现根据图表大小自动缩放气泡大小。示例中除以固定的数值不是解决办法，数据是用户输入的，他可能输入1，2，3，4也可能输入1000，2000，3000。这样就不能使用一个固定的缩放比例。
要实现的结果就是，不管用户输入的气泡大小是1，2，3，4还是1000，2000，3000，4000，气泡都要能完整的显示出来。

**Comment by ohfang** [comment]
我目前使用的方法：
type: 'scatter',
symbolSize: function (value){
    var max = 0, width = parseInt($(myChart.getDom()).css('width'));
    $.each(myChart.getSeries(), function(i, v){
        $.each(v.data, function(ii, vv){
            if (vv[2] > max) {
                max = vv[2];
            };
        });
    });
    var rate = width/10/max;

    return parseInt(value[2]*rate);
}

**Comment by gushitong** [comment]
**任意数据集中的值不可能恰好与图表中的像素尺度, 
   所以这个问题的本质是把 : 把一组输入域映射为任意输出范围.**
在d3.js中有关于尺度的概念(d3.scale.linear), 专门用来解决这个问题, 你可以去参考一下相关实现 
[d3.linear.scale](https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear, "d3.scale.linear")...
