### ISSUE TITLE
legend的定位问题

### ISSUE THREAD

**Issue by wych1987** [ecomfe/echarts#1889]
legend的定位是不是有bug，比如我有个div ，里面是echart，legend选择top,center ;然后我把div旋转90deg; 图例显示旋转了。但是点击不上，按钮位置没旋转。。。。交互完全不对啊。。。

**Comment by Ovilia** [comment]
根据你的说法，我在[这个例子](http://echarts.baidu.com/doc/example/legend.html)中，把 `x` 改为 `'center'`，点击刷新。给 `<div id="main"></div>` 加上 CSS 属性 `transform: rotateZ(90deg);`，发现能够正确点击 legend，也正常旋转了。要不你把 option 和其他操作详细发上来？
