### ISSUE TITLE
echarts 长时间运行致浏览器崩溃

### ISSUE THREAD

**Issue by zhaojun12** [ecomfe/echarts#1897]
* 如果连续运行例子 http://echarts.baidu.com/doc/example/map11.html 18个小时以上，就会导致浏览器崩溃
* 有什么解决办法么？保留动画效果，并且可以连续运行若干天
* 万分感谢

**Comment by longFeiLi** [comment]
定时器（4个小时，时间可配置）清空下实例。然后重新生成下图表就可以了。

**Comment by zhaojun12** [comment]
* 调用 ```echarts. clear()``` 和 ```echarts.dispose()``` ？
* 是否还有其他需要释放的？

**Comment by longFeiLi** [comment]
不用，如果你用Angular.js 还可以用下``` $state.reload```

**Comment by zhaojun12** [comment]
OK，谢谢

**Comment by zhaojun12** [comment]
```javascript
myChart = echarts.init($("#mainMap")[0]);
myChart.setOption(option, true);
myChart.dispose();
```
* 我发现执行完 ```dispose()``` 后 ```CPU``` 占用降为 ```0```，但是内存并没有释放
* 导致再执行 ```setOption()``` 后内存持续上升，过了 ```18``` 个小时还是崩溃了
