### ISSUE TITLE
echarts 模块化单文件引入

### ISSUE THREAD

**Issue by kingispeak** [ecomfe/echarts#1902]
請問

我在參考文件使用 echarts 模块化单文件引入後，碰到一個問題

console log 會出現該錯誤訊息，不過似乎不影響圖表使用。

GET http://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.1.0-min.js.js 

但該錯誤會影響到頁面其他 jQuery 套件的使用。

**Comment by hushicai** [comment]
这个请求不是echarts发出的。

**Comment by kingispeak** [comment]
感謝！

我換成引用 echarts-all.js 就不會出現此問題。
