### ISSUE TITLE
一个图里的series可以有两个Force吗

### ISSUE THREAD

**Issue by gracelinmumu** [ecomfe/echarts#1908]
一个图里的series可以有两个Force吗？
series：[
{
type:force
},
{
type:force
}

]

**Comment by gracelinmumu** [comment]
我直接这样设置，只显示一个Force，是什么原因呢？

**Comment by Ovilia** [comment]
根据[这条注释](https://github.com/ecomfe/echarts/blob/a0d4da494a5d36db7be519783acc594abb56571e/src/chart/force.js#L212)，现在应该是还不支持多个 force 的。
