### ISSUE TITLE
在使用字符云的情况下，autoSize，数据value属性去自动调节大小问题

### ISSUE THREAD

**Issue by zasqw2222** [ecomfe/echarts#1909]
在使用字符云的情况下，autoSize，没有根据数据value属性去自动调节大小，而且 非常小？  
=======

    autoSize: {
	              enable: true,
	              minSize: 20
	           },
    data:[{name:'水电费',value:4},
                  {name:'范围为规范',value:3},
                  {name:'呵呵',value:2},
                  {name:'且个人',value:1}]  
谢谢！

**Comment by zasqw2222** [comment]
自己找到原因了，在chrome上正常显示，在firefox上有兼容性的BUG，希望各位大神，注意以下

**Comment by zasqw2222** [comment]
就是 value的值 小于10的情况下

**Comment by Dreamcatcher-GIS** [comment]
我在chrome下也不能正常显示呀
