### ISSUE TITLE
官网实例map3中，如果使省级地图和省内市级地图均有数据，会造成两级地图冲突，请问有解决方法吗？

### ISSUE THREAD

**Issue by LiangShuxian** [ecomfe/echarts#1911]
官网实例map3中，如果使省级地图和省内市级地图均有数据，会造成两级地图冲突，请问有解决方法吗？
http://echarts.baidu.com/doc/example/map3.html
我的想法是每个省均有数据（汇总省内各个城市），点击某一省后，如map3所示，进入某一个省的子地图，可以看到该省每个市的数据。现在问题是，我一旦赋予各个省数据（原本只有市有数据），则会出现：点击‘某省’后，省视图不消失，和市视图重叠在一起。
请问echart中有自带的属性可以解决该问题吗？谢谢各位大大。

**Comment by seifer08ms** [comment]
你把里面的前几行数据改成这样就知道了
```javascript
 data:[
                {name: '重庆',value: Math.round(Math.random()*1000)},
                {name: '北京',value: Math.round(Math.random()*1000)},
                {name: '天津',value: Math.round(Math.random()*1000)},
                {name: '上海',value: Math.round(Math.random()*1000)},

**Comment by LiangShuxian** [comment]
谢谢@seifer08ms，但我原来的代码与你建议的是一样的，问题在另一个地方。
解决的代码：
myChart.on(ecConfig.EVENT.MAP_SELECTED, function (param){
                    var len = mapType.length;
                    var mt = mapType[curIndx % len];
                    if (mt == 'china') {
                        // 全国选择时指定到选中的省份
                        var selected = param.selected;
                        for (var i in selected) {
                            //selected[i]true时
                            if (selected[i]) {
                                mt = i;
                                while (len--) {
                                    if (mapType[len] == mt) {
                                        curIndx = len;
                                    }
                                }
                                break;
                            }
                        }
                        option.tooltip.formatter = '滚轮切换省份或点击返回全国<br/>{b}';
                        option.series[0].mapType = 'none';
                        option.series[1].mapType = mt;
                        console.log(mt);
                    }
                    else {
                        curIndx = 0;
                        mt = 'china';
                        option.tooltip.formatter = '滚轮切换或点击进入该省<br/>{b}';
                        option.series[0].mapType = mt;
                        option.series[1].mapType = 'none';
                        console.log(mt);
                    }

                    option.title.subtext = mt + ' （滚轮或点击切换）';
                    myChart.setOption(option, true);
                });

**Comment by seifer08ms** [comment]
@LiangShuxian 学习了~  借鉴下

**Comment by qinshou** [comment]
series里mapType是控制当前区域，可以考虑在china级别只展示各省数据，切换到省级，再取市的数据并重新渲染，这样不冲突了。
