### ISSUE TITLE
MarkPoint遮挡的问题....

### ISSUE THREAD

**Issue by talentwing** [ecomfe/echarts#1912]
我在地图里有很多炫光特效的MarkPoint和一个不带特效的MarkPoint,但是发现不带特效的那个会被有特效的挡住,这个如何调整?

**Comment by longFeiLi** [comment]
把不带特效的MarkPoint  放后面试下

**Comment by talentwing** [comment]
//恢复MarkPoint效果
	myChart.addMarkPoint(0,option.series[0].markPoint);//有特效的
	myChart.refresh();
	myChart.addMarkPoint(0,provinceMark);//没特效的
和
	myChart.refresh();
	myChart.addMarkPoint(0,provinceMark);//没特效的
        myChart.addMarkPoint(0,option.series[0].markPoint);//有特效的
效果是一样的,都会被遮挡,
但是我发现当鼠标移到MarkPoint上面触发emphasis效果时就不会被遮挡了...那有什么办法默认一直触发emphasis么?

**Comment by Ovilia** [comment]
可以放在不同的 series 里，然后设置 `z` 值控制层，越大的越在上面。http://echarts.baidu.com/doc/option.html#title~series-i(line).z
