### ISSUE TITLE
请问一下，一张坐标系图重新设置legend，在视图上不起效果，但数据改掉了是怎么回事？

### ISSUE THREAD

**Issue by Rabbit0306** [ecomfe/echarts#1914]
![alt](https://raw.githubusercontent.com/Rabbit0306/123/master/img/Untitled.png)

如上图所示，是不是第二次设置this.setOption({legend:{ selected: {"2007": true} }});的时候视图不会刷新？

补充：后来在官方给的例子中也发现了这个问题([Link](http://echarts.baidu.com/doc/example/legend.html))。将左边js代码修改为

```
myChart.setOption({legend:{ selected: {"蒸发量": false} }});
```

![alt](https://raw.githubusercontent.com/Rabbit0306/123/master/img/QQ%E6%88%AA%E5%9B%BE20150814132849.png)

然后刷新一下数据，依旧能够看到"蒸发量"的折线图。

**Comment by pissang** [comment]
图中没看到你有 2007 年的系列数据

**Comment by Rabbit0306** [comment]
@pissang 我显示的是legend的参数，series的参数并没有显示在图中。好的，我去试一下这个方法，我感觉setOption()好像对legend.selected的设置视图上没发生效果。。

**Comment by Rabbit0306** [comment]
@pissang 好像不行，请问如何获取this.component下的legend？= =

**Comment by Rabbit0306** [comment]
@pissang 好的！谢谢指点！用 this.component.legend.setSelected 确实能够直接修改数据和视图。唯一要注意的是需要等待component下的legend的数据加载完才可以使用。
