### ISSUE TITLE
折线图少点

### ISSUE THREAD

**Issue by jackcaicn** [ecomfe/echarts#1915]
"type": "line",
数据有是全的，但线上没有点，x座标也不显示，隔一个少一个
啥问题？

**Comment by Rabbit0306** [comment]
把chart的series打开来，数据是怎么样的？

**Comment by jackcaicn** [comment]
series: [
                    {
                        "name": "Total Users",
                        "type": "line",
                        "data": [12429,12497,13306,13772,14119,14521,14739,14941,15139,15355,15521,15664,15796,15954,16130,16300,16464,16602,16765,16920,17077,17222,17374,17501,17633,17773,17907,18097,18236,18391]
                    }

**Comment by jackcaicn** [comment]
![qq 20150814135440](https://cloud.githubusercontent.com/assets/3733979/9268655/ee556ada-4293-11e5-9b21-3d65473e7112.png)

**Comment by jackcaicn** [comment]
解决了
boundaryGap:false,

那个x坐标密度是自动调节的
