### ISSUE TITLE
现在好像又有IE8兼容性的问题

### ISSUE THREAD

**Issue by z543jie** [ecomfe/echarts#1922]
问题是仅仅在一台机器上有问题(win7 32位)，图显示不出，tooltip有效，同#475一样。但是放大/缩小页面图还是出不来。
官网的例子也一样。
请问下，上次475解决的方法跟什么有关吗？
如果这个问题需要定位有什么方法可以指导一下吗？

**Comment by longFeiLi** [comment]
什么版本最新版么？

**Comment by z543jie** [comment]
用过2.0.0和2.2.0都有问题，访问官网的例子也是出不来图。
会不会是系统的VML支持有问题？

**Comment by longFeiLi** [comment]
最新版本试试。

**Comment by z543jie** [comment]
定位出问题了，系统的VML的相关注册表被其他软件修改，导致VML在IE8显示不了。
