### ISSUE TITLE
漏斗图建议：sort选项支持数据不排序

### ISSUE THREAD

**Issue by magicxie** [ecomfe/echarts#1923]
目前文档中写sort支持数据排序， 可以取ascending, descending，但没有”none不排序“这个选项，希望能支持不排序，数据按传入的数组下标大小从上到下排

**Comment by luozhihua** [comment]
有同样的需求+1

**Comment by 100pah** [comment]
Fixed in 6736f98aa51603d750f265e838651659d47786d6
