### ISSUE TITLE
怎么定制legend.data中的icon内容

### ISSUE THREAD

**Issue by cgfgithub** [ecomfe/echarts#1929]
我想要用css定义一个icon样式，例如<p style="backgound:red;width:2px;height:15px"></p>

但是并不能实现这样的样式，好像只能使用图表类型或者是图片作为参数
    legend: {
        orient : 'vertical',
        x : 'left',
      data:[
        {name:'直接访问',textStyle:{color:'red'} ,icon :'bar'}
      ]
       // data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    }
或者是icon: 'image://../asset/ico/favicon.png'

但是我想用icon:'<p style="backgound:red;width:2px;height:15px"></p>'  好像不行，这个是不支持还是我写的有问题

**Comment by cgfgithub** [comment]
![Uploading 捕获.PNG…]()

**Comment by cgfgithub** [comment]
如图，我想要做底部的那个效果

**Comment by cgfgithub** [comment]
![default](https://cloud.githubusercontent.com/assets/10369416/9323931/3bb8494c-45b8-11e5-88d0-731eb03bcf09.PNG)

**Comment by cgfgithub** [comment]
已经解决了，大致思路是设置icon的为bar，然后设置图例的宽高即可，代码如下
var a = {'邮件营销':100,'直接访问':50,'联盟广告':80,'视频广告':60,'搜索引擎':70};
option = {
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'horizontal',
        x : 'center',
      itemWidth:2,
      itemHeight:50,
      y:'bottom',textStyle:{color:'auto'},
        data:[
          {
            name: '直接访问',
            icon:'bar',
          }],
      formatter:function(name){
      	return "     "+a[name]+"\n" + name;
      }
      
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true, 
                type: ['pie', 'funnel'],
                option: {
                    funnel: {
                        x: '25%',
                        width: '50%',
                        funnelAlign: 'center',
                        max: 1548
                    }
                }
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    series : [
        {
            name:'访问来源',
            type:'pie',
            radius : ['50%', '70%'],
            itemStyle : {
                normal : {
                    label : {
                        show : false
                    },
                    labelLine : {
                        show : false
                    }
                },
                emphasis : {
                    label : {
                        show : true,
                        position : 'center',
                        textStyle : {
                            fontSize : '30',
                            fontWeight : 'bold'
                        }
                    }
                }
            },
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
};

**Comment by cqzuo** [comment]
icon的格式这样写就可以了：icon:'image://./image/xxx.png'
