### ISSUE TITLE
关于关闭title和toolkit的建议

### ISSUE THREAD

**Issue by Rabbit0306** [ecomfe/echarts#1932]
当关闭title和tooltip以后，希望能够将他们所留白的地方用图表去占满。或者建议开放能够平移整个图表的接口。

**Comment by stanleyxu2005** [comment]
可以啊，调整grid的x,x2,y,y2试试看

**Comment by xfworld** [comment]
Pie 好像调整这几个参数没啥用

**Comment by stanleyxu2005** [comment]
@xfworld 是你自己不会用。按照我说的，绝对是可以的，这个grid就是定义画布上什么区域用来画pie。你设置了x,x2,y,y2，就指定了画图区域。然后设置pie的内径外径，就指定了画的大小和位置了。

**Comment by stanleyxu2005** [comment]
@Rabbit0306 如果可以了，就把这个issue关掉吧。
