### ISSUE TITLE
如何让 xAxis 的时间显示在一行上？

### ISSUE THREAD

**Issue by zhaojun12** [ecomfe/echarts#1933]
如例 http://echarts.baidu.com/doc/example/scatter6.html 所示，我想让 x 轴的时间显示在同一行上，不分两行显示，有什么办法，需要修改哪个参数？

谢谢

**Comment by stanleyxu2005** [comment]
修改src/util/date.js里面的_timeGap，把'\n'统统删掉。
然后用echarts-optimizer自己构建一下。
