### ISSUE TITLE
希望title和subtitle支持html

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1937]
我想做类似截图里面的效果。
![ring-pie](https://cloud.githubusercontent.com/assets/5162687/9350645/1ca51dbe-4685-11e5-8352-eb8963455f8a.png)

我设置`title='16.0 GB'`的话，`GB`字样太大。所以希望title和subtitle支持html的话，就非常好办了。类似这样
```
title = {
  text: '<span class="large">16.0</span> <span class="small">GB</span>'
};
```

题外话，一模一样3行文字的legend的效果能做到吗？

我现在做出的实际效果差很多
![ring-pie2](https://cloud.githubusercontent.com/assets/5162687/9351048/8c06521a-4688-11e5-8a3f-c5117e3e419c.png)

**Comment by pissang** [comment]
这种非常个性化的样式可以直接用 html 写，Canvas 无法支持 html 的绘制。

**Comment by stanleyxu2005** [comment]
主要考虑到下面图例不是和环图对齐的。不然我就外面自己画了。

**Comment by pissang** [comment]
这个通过 css 定位很容易做啊，用 html 的问题主要是不能跟图表一起导出成图片。

**Comment by stanleyxu2005** [comment]
确实是，我怎么没想到用css做定位。亲测可行。

**Comment by stanleyxu2005** [comment]
没想到echarts成为apache 孵化项目了
