### ISSUE TITLE
dataZoom没有x2、y2这样的配置项，怎样给它设置一个靠底部的相对距离？

### ISSUE THREAD

**Issue by mirari** [ecomfe/echarts#1938]
比如一个带时间轴的图表，时间轴本身就在最底部，如果给图表加上了dataZoom，缩放块就会跟时间轴重叠。
我希望给缩放块一个相对距离，让它能跟时间轴区分开，但是图表本身的区域高度是不固定的，怎样才能给它设置一个靠底部的相对距离？

另外，右边的滑块竟然能拖到左边的滑块左边，此时虽然zoom的区域正常，但显示的标签却对调了，这个BUG在官方示例中也存在

**Comment by stanleyxu2005** [comment]
你可以计算出图的高度，然后设置dataZoom的高度，然后计算出dataZoom.y的值。
比如说图高200，dataZoom高20，底部希望留出5，那么dataZoom.y = 200 - 20  - 5;
