### ISSUE TITLE
柱状图是否可以添加滚动条？

### ISSUE THREAD

**Issue by decadef20** [ecomfe/echarts#1942]
当使用柱状图时，假使X轴规定宽度只能显示10条数据，但是现在有100条数据，我想使用滚动条查看数据。我怎样用echart实现这个功能呢？恳请分享个思路，谢谢。

**Comment by stanleyxu2005** [comment]
必须打开dataZoom选项。但他们的实现有问题，设置barWidth和barMaxWidth并不能保证理想效果。

我的angular库做了一层包装，你可以试试看
具体思路是，hook一下chart的resize时间，可以实时知道chart的宽度。然后根据给入的bar的数量和指定宽度，计算能显示的chart的宽度。然后打开datazoom，计算出start和end的位置，并锁定滚动条宽度，这样的话，bar的宽度就如你所希望了。

https://github.com/stanleyxu2005/dashing
https://github.com/stanleyxu2005/dashing-deps

html
```
<script src='vendor/underscore/underscore.js'></script>
<script src='vendor/dashing-deps/echarts/2.2.7-compact/echarts-all.min.js'></script>
<script src='vendor/dashing/dashing.js'></script>

  <h4>Bar Chart</h4>
  <bar-chart
    options-bind="::barChartOption"
    datasource-bind="barChartData">
  </bar-chart>
```
js
```
      $scope.barChartOption = {
        height: '160px',
        color: 'red',
        data: _.range(1000).map(function(i) {
          return {x: i, y: Math.random() * 1000 + 50};
        })
      };
```

以下是内测效果图
![untitled](https://cloud.githubusercontent.com/assets/5162687/9427813/8ce58362-49c2-11e5-8aaa-a7dc0c6a7713.png)

**Comment by stanleyxu2005** [comment]
我提过类似问题 https://github.com/ecomfe/echarts/issues/1782
