### ISSUE TITLE
地图类型 外发光

### ISSUE THREAD

**Issue by frogRen** [ecomfe/echarts#1943]
我看到百度迁移的图片，有些 中国地图 外边框是 发光效果的，
这是如何实现的呢

**Comment by Ovilia** [comment]
http://echarts.baidu.com/doc/example/map22.html

```
        itemStyle: {
            normal: {
                borderColor:'rgba(100,149,237,0.2)',
                borderWidth:0.5,
                areaStyle: {
                    color: '#1b1b1b'
                }
            }
        }
```

**Comment by frogRen** [comment]
感谢回复， 
我看了页面里的例子 是这样的：
http://cache.next.moxiu.com/temporary/4be8a8b4e5650d52bae645e1bb328ec12a77aaf2


我想要的是这样的效果： （效果图）
http://cache.next.moxiu.com/temporary/278e18cf1837842bef87dceab0e78c530bb444cc


目前实现的程度：
http://cache.next.moxiu.com/temporary/d3b8071f2bfbcb85e61d5672d86328cfc32f37d6


不知道怎么实现 效果图里的 类似外发光的地图

**Comment by Ovilia** [comment]
@frogRen 你想要的效果是在哪里看到的？

**Comment by frogRen** [comment]
百度图片搜索 百度迁移图 ，有类似的效果。

**Comment by Ovilia** [comment]
看了一下源码，似乎并不能给你提供帮助…
