### ISSUE TITLE
力导向图linkSymbol:'arrow'，linkSymbolSize数组第一值放大(>10)造成箭头位置不正确

### ISSUE THREAD

**Issue by rufushuang** [ecomfe/echarts#1947]

**Comment by rufushuang** [comment]
https://github.com/ecomfe/echarts/commit/8bf18b21da87dbe317ce4b02460e9a6a4e80e617
上述引入x: -5定义
https://github.com/ecomfe/echarts/commit/961fb9241fbca6f6db8d750496abfa9a1f956e8e
上述引入width: serie.linkSymbolSize[0]定义，但漏了同时应做的对应x,y偏移量修改，应做修改例如：
x: -0.5 * serie.linkSymbolSize[0]

建议修正目前的force.js L724
https://github.com/ecomfe/echarts/blob/a0d4da494a5d36db7be519783acc594abb56571e/src/chart/force.js#L724

arrow类型箭头测试通过，未测试arrow以外类型的箭头

@pissang

**Comment by stanleyxu2005** [comment]
力导向图我建议你直接去用另外一个库vis
