### ISSUE TITLE
每个颜色的图例可以自定义放到不同的位置吗？

### ISSUE THREAD

**Issue by FionaWong** [ecomfe/echarts#1951]
我想要把每个不同颜色的图例放到不同的位置？
## 目前可以做到吗？

lengend 目前是一个对象吗？
## 是不是只能把所有的图例放到一个块里面统一展示？

如果不是的话
我感觉Legend data可以自定义position坐标固定legend的每个位置。

**Comment by stanleyxu2005** [comment]
可以啊。
http://echarts.baidu.com/doc/doc.html#Legend

```
{string} orient	'horizontal'	布局方式，默认为水平布局，可选为：'horizontal' | 'vertical'
{string | number} x	'center'	水平安放位置，默认为全图居中，可选为：'center' | 'left' | 'right' | {number}（x坐标，单位px）
{string | number} y	'top'	垂直安放位置，默认为全图顶端，可选为：'top' | 'bottom' | 'center' | {number}（y坐标，单位px）
```

**Comment by FionaWong** [comment]
不是哦不是哦~我想要不同颜色代表的图例放到不同的位置。

**Comment by stanleyxu2005** [comment]
貌似不行

**Comment by FionaWong** [comment]
所以呢,lengend的data里面是否可以加个Position属性，定义每个图例的位置。

**Comment by ShaneKao** [comment]
legend.data可以塞 {'name': '\n'}, 不過只能控制左右或上下

**Comment by pissang** [comment]
3  里可以使用多个 legend 组件，可以试下每个组件一个数据然后分别放到不同位置

**Comment by baoyadong** [comment]
Legend可使用数组，来定义不同数据的不同位置
