### ISSUE TITLE
bug：ComponentClass is not a constructor（已查明原因）

### ISSUE THREAD

**Issue by chyingp** [ecomfe/echarts#1953]
**1、版本**：2.2.7
**2、问题**：通过echarts在线构建工具，生成单文件（比如bar，非AMD）。调用 setOption 方法，报错“ComponentClass is not a constructor”
**3、原因**：构建页面的bug导致。--> 见下面步骤三

### 步骤一：

进入构建页面，选择需要的图表类型。这里选择 `bar`，非AMD，不压缩

![image](https://cloud.githubusercontent.com/assets/2383346/9423476/1a8fd0a8-48f8-11e5-9c34-722bffece703.png)

![image](https://cloud.githubusercontent.com/assets/2383346/9423480/9a2a9942-48f8-11e5-9355-2d833ba57333.png)

### 步骤二：

点击生成按钮

![image](https://cloud.githubusercontent.com/assets/2383346/9423492/ad2d16d2-48f8-11e5-8cd2-0a2a70a26153.png)

跳到生成页面，地址是 http://ecomfe.github.io/echarts-builder-web/build.html?charts=&components=&source=true

机智的我一下子从`url`看出了问题所在：**charts 参数有问题**

### 步骤三

参看了构建页面的源码（只有几行），找到问题代码：此时 `charts` 数组是kong'shu'zu空数组。具体原因我就不继续查了

![image](https://cloud.githubusercontent.com/assets/2383346/9423499/f7ba9a9e-48f8-11e5-80c9-429a2b12afa5.png)

**Comment by pissang** [comment]
谢谢反馈：）已修复
