### ISSUE TITLE
时间轴版的Line chart渲染不对

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1954]
官网的这个例子http://echarts.baidu.com/doc/example/line8.html
我发现这么几个问题：
1. 如果`xAxis[0].boundaryGap = false`，完全无法显示数据。
2. Tooltip的`trigger`如果设置成`axis`，选择数据时，那根线不是垂直方向的，而是水平方向的。
3. 如果`showAllSymbol`设置成false，一个数据点也不会标出来。
4. 如果是多条数据(series)，然后大家都设置了`stack='1'`，图表上除了坐标轴，什么都显示不出来了。
5. xAxis的label数量不固定，他们的间距也一直在跳跃，无法固定下来。

高度欣赏echarts在动画方面的功力，但这个时间轴是基本功能啊，希望予以改进，不然这库真可能要放弃使用了...

**Comment by pissang** [comment]
谢谢建议，目前时间坐标轴属于数值轴，所以图表作为双数值轴就不具备 stack，axis trigger 这些功能，如果需要的话可以把 time 类型改成 category 然后配合 formatter 使用，不过这些问题会在新版本里改进：）

**Comment by stanleyxu2005** [comment]
@pissang 我暂时是用category来解决这个问题。唯一的瑕疵是：category的数据点的间隔是等距的。而基于time轴的点可以是非等距的。

**Comment by stanleyxu2005** [comment]
@pissang 请问新版预计多久时间会发？数天，数周，数月，还是...

**Comment by pissang** [comment]
@stanleyxu2005 这两个月内 : )

**Comment by xfworld** [comment]
坐等新版本阿...
