### ISSUE TITLE
Clear方法无法清除【暂无数据】提示

### ISSUE THREAD

**Issue by aaronuu** [ecomfe/echarts#1957]
第一次绘制图标不传递 数据 会渲染出一张 暂无数据 提示，我调用Clear无法清除这个提示，只能清除绘制好的图表

**Comment by longFeiLi** [comment]
hideLoading

**Comment by aaronuu** [comment]
那我岂不是每次渲染都要 clear + hideLoading ？

**Comment by longFeiLi** [comment]
只用hideLoading

**Comment by aaronuu** [comment]
Thanks！

**Comment by stanleyxu2005** [comment]
学习了！

**Comment by stanleyxu2005** [comment]
@pissang 顺便提一下，如果x轴是用的time，初始化chart时候没有数据，然后后期再传入数据，虽然用chart.hideLoading()可以显示数据，但是链接数据点的那条线不会画。我需要从legend上点击相关的数据图标，然后再点一下，chart才会画出那条线。

**Comment by longFeiLi** [comment]
能不能对数据判断一下，空加hideLoading，不空不做处理

**Comment by stanleyxu2005** [comment]
@longFeiLi 可以的，但没用。我判断数据是不是为空的标准是`chart.getOption().xAxis === undefined`。不管`xAxis.type`是`time`还是`category`，如果没有数据插入，`xAxis`始终不会被初始化。你可以验证一下。及时在我知道数据有没有被初始化的情况下，我上一个回复里面的问题，始终可以重现。

**Comment by longFeiLi** [comment]
恩```xAxis ``` 那就只能默认给min 和max 才可以
