### ISSUE TITLE
词云的字体如何设置？

### ISSUE THREAD

**Issue by Gwill** [ecomfe/echarts#1960]
#1765 这里的回答与文档中不一致，而且两种方式都无法设置。

**Comment by hushicai** [comment]
@pissang 

看实现，似乎目前只能设置series[i].itemStyle.normal.textStyle.fontFamily，而不能设置series[i].data[i].itemStyle.normal.textStyle.fontFamily。

**Comment by hushicai** [comment]
@Gwill  用`series[i].itemStyle.normal.textStyle.fontFamily`应该是可以正常设置字体的。

**Comment by pissang** [comment]
这块处理是有问题，fontFamily 是可以写成回调的

**Comment by Gwill** [comment]
@hushicai THX!
