### ISSUE TITLE
echarts支不支持这样的图呢？

### ISSUE THREAD

**Issue by zuoRambo** [ecomfe/echarts#1962]
在展现某序列的前n名的时候 除了使用饼图或者玫瑰图 使用下图感觉会更好些
![份额图](https://cloud.githubusercontent.com/assets/4715122/9459512/d8883bda-4b2e-11e5-9a6f-7b5391669d7a.jpg)

请问echarts支持这样的表现形式么？如果不 如何调用zRender可以实现这一目标呢？多谢echarts团队的回答～～

**Comment by pissang** [comment]
可以使用力导向
