### ISSUE TITLE
散点图上，拖动datazoom到无数据区域，不应该被noDataLoadingOption无数据提示动画覆盖！

### ISSUE THREAD

**Issue by mbcls** [ecomfe/echarts#1963]
RT

**Comment by Ovilia** [comment]
具体的代码是？在[这个例子](http://echarts.baidu.com/doc/example/scatter1.html)中没有问题。

**Comment by mbcls** [comment]
myChart.on(echarts.config.EVENT.DATA_ZOOM, JADATA_ZOOM);

//X区域选择变动后 重画线(只画能看见的点的线) 延时1秒
	function JADATA_ZOOM(param) {
		clearTimeout(_timeout);
		_timeout = setTimeout(function(){
			_xmin = param.zoom.start/100*(param.zoom.scatterMap['0'].x.max-param.zoom.scatterMap['0'].x.min)+param.zoom.scatterMap['0'].x.min;
			_xmax = param.zoom.end/100*(param.zoom.scatterMap['0'].x.max-param.zoom.scatterMap['0'].x.min)+param.zoom.scatterMap['0'].x.min;
			addAllMarkLine();
		},1000);		
	}


//全部画线
	function addAllMarkLine(){
		delAllMarkLine();
		if(!_isweiba){
			return;
		}
		//如果一根线都没有，就全部画线
		myChart.exLines = {};
		myChart.showLoading({
			text : '正在渲染图表...'//loading话术
		});
		
		myChart.setOption({
			series:[{
				markLine:{
					data:(function(){
						return _getAllMarkLineData();
						})()
				}
			}]
		});
		myChart.hideLoading();
		
	}


function delAllMarkLine(){
		//如果原来有线，这个动作就是是删除原来的线，全部画线 要再点一下
		var _option = myChart.getOption();
		myChart.setOption(_option,true);
	}



因为要拖动DataZOOM时候给散点画线，所以加了一个addAllMarkLine事件在Zoom里,
画当前场景显示的线时候，先删除原来的线，就出问题了...
拖动Data_ZOOM 到无数据区域 

问题出在delAllMarkLine()里

**Comment by mbcls** [comment]
当前界面无数据时候，触发setOption会出现这情况
