### ISSUE TITLE
数据重复2次出现 -安卓

### ISSUE THREAD

**Issue by moxiaoco** [ecomfe/echarts#1964]
图片上传成功，就是柱状图中的数据，会重复出现2次。请问如何解决

**Comment by MOLVMIN** [comment]
你用的是什么浏览器？

**Comment by moxiaoco** [comment]
使用的是三星 安卓4.3 系统   qq浏览器 @MOLVMIN

**Comment by kimyongyeon** [comment]
안녕하세요 어제 버그를 찾은 개발자 입니다.

내용은 아래와 같습니다.

legend : OCB의 경우 최대 max 값이 4489916 인데 차트 화면에 6,000,000 까지만 나와도 되나 8,000,000
까지 보이고 있음.
LEGEND_SELECTED 이벤트를 적용하여 option.yAxis[0].max의 값을 max 값으로 설정하여도 똑같이 나옴

해당 옵션 파일을 첨부해서 보내드립니다.

감사합니다.




2015-09-04 9:47 GMT+09:00 莫小熙 <notifications@github.com>:

> 使用的是三星 安卓4.3 系统 qq浏览器 @MOLVMIN <https://github.com/MOLVMIN>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ecomfe/echarts/issues/1964#issuecomment-137612511>.
>

option = {"calculable":true,"tooltip":{"trigger":"item","showDelay":0,"textStyle":{"align":"left"},"axisPointer":{"show":true,"type":"cross","lineStyle":{"type":"dashed","width":1}}},"legend":{"data":["Syrup","Tstore","OCB","Tmap","11번가","통합"],"selected":{"통합":false}},"xAxis":[{"type":"category","splitLine":{"show":false},"data":["음식점","카페/제과","주점","배달통","먹거리기타","유통점","식료품","의류직물","신변잡화","가전용품/통신기기","주유/자동차","인테리어/건축자재","서적/문구/인쇄/복사","컴퓨터사무용기기","화원/꽃집","오락/취미","쇼핑","의약품","가구/생활용품","살거리기타","임대/대여","수리","여행사","관광/숙박시설","병원","개인간병/유사서비스","이미용/욕탕/몸매관리","예식준비/예식관련","학원/교육","시장조사/여론조사","법무/회계관리","광고/이벤트","운송업(여객/화물)","생활서비스기타","영화/비디오","공연/전시","운동/여가시설","오락시설","유원지/놀이공원","놀거리기타","통신","은행/저축/투자기관","증권/선물중개","보험/연금","신용카드/할부금융","금융기타","포인트판매/충전","이벤트","살거리(온라인)","생활서비스(온라인)","놀거리(온라인)","금융(온라인)","포인트판매(온라인)","적립쇼핑_OK캐쉬백만이용","온라인가맹점_OK캐쉬백만이용","전자상거래(온라인)","기타","Tstore_FUN","Tstore_생활편의","중분류전체"]}],"yAxis":[{"type":"value","splitNumber":4,"scale":true}],"series":[{"name":"Syrup","type":"scatter","data":[["카페/제과",3163290,3163290,326557,2627487,2327708],["금융기타",616197,616197,80188,531780,490830],["먹거리기타",2246627,2246627,243693,1894150,1667757],["주점",12909,12909,2671,11403,10076],["유통점",3153877,3153877,326410,2614091,2324560],["의류직물",3035709,3035709,317367,2527370,2242401],["가전용품/통신기기",2803968,2803968,307580,2343264,2124130],["주유/자동차",2742995,2742995,298153,2308608,2046628],["신변잡화",2306514,2306514,279859,1951014,1830173],["서적/문구/인쇄/복사",2195889,2195889,272879,1868231,1747549],["화원/꽃집",1134969,1134969,165566,990356,969139],["가구/생활용품",213502,213502,27322,181880,170242],["인테리어/건축자재",133369,133369,25495,116473,113158],["생활서비스기타",3173202,3173202,327518,2632622,2335604],["관광/숙박시설",2877985,2877985,307591,2412898,2136943],["여행사",2657359,2657359,301764,2237257,2041539],["이미용/욕탕/몸매관리",2605611,2605611,285416,2198565,1949116],["학원/교육",2566592,2566592,281261,2166008,1920893],["운송업(여객/화물)",2483466,2483466,292828,2089611,1940730],["임대/대여",1888071,1888071,227384,1620116,1476655],["병원",986979,986979,108442,847718,736827],["수리",345166,345166,49727,302281,281222],["예식준비/예식관련",1726,1726,338,1508,1411],["영화/비디오",3050008,3050008,319578,2543091,2251543],["운동/여가시설",2324576,2324576,246453,1963209,1703350],["공연/전시",2246362,2246362,241646,1885126,1657394],["통신",1239543,1239543,166425,1067608,1027452],["신용카드/할부금융",1764866,1764866,216671,1506810,1381719],["보험/연금",1392472,1392472,172104,1192589,1087418],["음식점",3132787,3132787,324378,2604677,2307072]]},{"name":"Tstore","type":"scatter","data":[["카페/제과",29860,29860,828,9323,8737],["Tstore_FUN",2389247,2389247,84211,699004,677481],["먹거리기타",14216,14216,822,5943,5615],["유통점",2270146,2270146,89800,737271,713417],["오락/취미",1051032,1051032,43824,370969,356218],["서적/문구/인쇄/복사",389736,389736,26145,186608,177458],["살거리기타",168786,168786,2300,36325,36336],["가전용품/통신기기",19432,19432,1743,10731,10273],["신변잡화",8405,8405,256,2823,2643],["가구/생활용품",1239,1239,69,541,528],["화원/꽃집",187,187,7,90,89],["임대/대여",567227,567227,34306,269705,254959],["병원",54804,54804,5087,32194,30437],["여행사",1753,1753,91,601,597],["영화/비디오",2772687,2772687,109687,916935,881421],["오락시설",1205402,1205402,39089,379481,378463],["놀거리기타",549524,549524,20685,183445,173959],["공연/전시",3489,3489,116,1233,1162],["금융기타",1934678,1934678,80847,662911,649476],["Tstore_생활편의",3970459,3970459,151287,1162618,1127657],["음식점",18767,18767,357,5177,5002]]},{"name":"OCB","type":"scatter","data":[["카페/제과",654596,654596,29662,257133,235306],["보험/연금",3825,3825,671,3077,2935],["배달통",14192,14192,3504,13669,12900],["먹거리기타",1039,1039,24,361,316],["주점",237,237,20,104,90],["유통점",4489916,4489916,163556,1532644,1379757],["주유/자동차",3745779,3745779,122341,1077009,991703],["가전용품/통신기기",118791,118791,2265,41203,40325],["서적/문구/인쇄/복사",65127,65127,3457,29107,24947],["신변잡화",41340,41340,2152,20760,18646],["의류직물",17533,17533,976,7724,6955],["살거리기타",1330,1330,70,587,529],["화원/꽃집",1316,1316,60,504,457],["인테리어/건축자재",392,392,32,221,183],["오락/취미",218,218,6,59,57],["컴퓨터사무용기기",74,74,5,23,21],["가구/생활용품",12,12,0,6,5],["생활서비스기타",29006,29006,1508,12656,10932],["운송업(여객/화물)",25995,25995,2595,17210,15072],["관광/숙박시설",6424,6424,439,3147,2598],["이미용/욕탕/몸매관리",3857,3857,179,1434,1294],["수리",2862,2862,164,1096,999],["임대/대여",1445,1445,153,796,686],["광고/이벤트",697,697,122,613,587],["학원/교육",616,616,21,187,158],["병원",40,40,1,13,13],["예식준비/예식관련",3,3,0,1,0],["영화/비디오",203535,203535,12037,109859,95802],["공연/전시",751,751,34,394,340],["오락시설",125,125,2,43,44],["운동/여가시설",3,3,0,1,2],["통신",136,136,0,46,43],["신용카드/할부금융",839325,839325,39795,304713,274662],["음식점",480212,480212,34100,253818,225804]]},{"name":"Tmap","type":"scatter","data":[["음식점",2801972,2801972,114122,1025703,917249],["신용카드/할부금융",3120,3120,171,1262,1088],["주점",219921,219921,9084,83566,72274],["유통점",1844470,1844470,78967,687519,610433],["주유/자동차",766712,766712,33580,279739,247727],["의류직물",595473,595473,28559,245989,210360],["가구/생활용품",231084,231084,11318,91861,78721],["살거리기타",185506,185506,8149,68741,60803],["가전용품/통신기기",159458,159458,7408,62323,54397],["신변잡화",103942,103942,4790,42555,36929],["서적/문구/인쇄/복사",91729,91729,4251,35868,31267],["화원/꽃집",37414,37414,1705,15053,12860],["인테리어/건축자재",37226,37226,1371,12444,11277],["오락/취미",17418,17418,755,7068,6053],["컴퓨터사무용기기",4583,4583,222,1702,1470],["운송업(여객/화물)",1577693,1577693,57791,526566,470900],["병원",1496475,1496475,58892,519793,468072],["관광/숙박시설",1345579,1345579,56380,492994,435824],["생활서비스기타",990962,990962,40426,335611,301920],["임대/대여",732449,732449,35126,286038,248370],["예식준비/예식관련",624814,624814,25250,227551,200115],["수리",358459,358459,15728,134636,119614],["학원/교육",267661,267661,12015,99383,89675],["이미용/욕탕/몸매관리",262885,262885,11043,98973,86386],["개인간병/유사서비스",16857,16857,897,7672,6510],["법무/회계관리",8701,8701,399,3053,2725],["여행사",7559,7559,369,2864,2497],["광고/이벤트",3728,3728,160,1379,1174],["공연/전시",631590,631590,29355,242701,213953],["운동/여가시설",565537,565537,22940,176724,158972],["영화/비디오",268572,268572,12481,113367,95994],["오락시설",20233,20233,611,7042,6362],["은행/저축/투자기관",614411,614411,25045,212145,192878],["보험/연금",56273,56273,2544,20761,19007],["증권/선물중개",34372,34372,1842,13276,11741],["금융기타",5334,5334,243,1932,1673],["카페/제과",663800,663800,32314,285778,244221]]},{"name":"11번가","type":"scatter","data":[["먹거리기타",192353,192353,12287,104746,93111],["공연/전시",5731,5731,224,2191,1713],["가전용품/통신기기",1664251,1664251,60976,661572,560509],["가구/생활용품",1299760,1299760,52781,535758,470014],["유통점",926089,926089,42167,392801,351497],["의류직물",881589,881589,32110,354675,313762],["인테리어/건축자재",629581,629581,24028,253696,221088],["서적/문구/인쇄/복사",446689,446689,17727,182332,160750],["주유/자동차",429541,429541,16974,179330,156556],["살거리기타",284246,284246,18426,153370,136512],["오락/취미",155161,155161,5470,62619,54451],["관광/숙박시설",212347,212347,7791,82589,73552],["여행사",64713,64713,3594,30600,26127],["운동/여가시설",787527,787527,27135,293376,253980],["놀거리기타",230154,230154,9702,95898,85528],["신변잡화",1693706,1693706,59827,669855,575267]]},{"name":"통합","type":"scatter","data":[["음식점",5553273,5553273,358122,3141070,2795124],["카페/제과",4134792,4134792,341182,2859223,2533739],["먹거리기타",2401855,2401855,249041,1959794,1726802],["주점",232820,232820,11719,94841,82246],["배달통",14192,14192,3504,13669,12900],["유통점",9803932,9803932,399458,3893447,3503821],["주유/자동차",6670901,6670901,350174,3065790,2747409],["가전용품/통신기기",4327394,4327394,327460,2753691,2469334],["의류직물",4145672,4145672,332357,2810038,2491230],["신변잡화",3813570,3813570,301857,2395468,2198156],["서적/문구/인쇄/복사",2954152,2954152,288835,2100058,1955785],["가구/생활용품",1700612,1700612,85964,776239,689428],["오락/취미",1213310,1213310,49222,434287,410865],["화원/꽃집",1170041,1170041,166621,1002529,979207],["인테리어/건축자재",791720,791720,49213,375351,338727],["살거리기타",631319,631319,28065,253365,229180],["컴퓨터사무용기기",4657,4657,227,1725,1491],["관광/숙박시설",4075775,4075775,324417,2679515,2377767],["생활서비스기타",3971153,3971153,338202,2787409,2478771],["운송업(여객/화물)",3815135,3815135,312304,2394353,2205520],["임대/대여",2896003,2896003,253982,1929395,1757210],["이미용/욕탕/몸매관리",2814170,2814170,288668,2247676,1992697],["학원/교육",2777063,2777063,284968,2214578,1965569],["여행사",2712783,2712783,302851,2255082,2056391],["병원",2375441,2375441,149505,1257416,1110157],["수리",695987,695987,63649,428451,393056],["예식준비/예식관련",626438,626438,25566,228965,201439],["개인간병/유사서비스",16857,16857,897,7672,6510],["법무/회계관리",8701,8701,399,3053,2725],["광고/이벤트",4425,4425,282,1992,1761],["영화/비디오",5505810,5505810,350983,3020161,2718342],["운동/여가시설",3436060,3436060,265992,2232623,1944407],["공연/전시",2763418,2763418,253316,2022217,1779948],["오락시설",1223069,1223069,39582,385424,383767],["놀거리기타",774467,774467,29955,276144,256571],["통신",1239672,1239672,166425,1067647,1027488],["신용카드/할부금융",2504740,2504740,237425,1720327,1572390],["금융기타",2456349,2456349,146117,1107628,1059435],["보험/연금",1445518,1445518,173993,1209961,1103416],["은행/저축/투자기관",614411,614411,25045,212145,192878],["증권/선물중개",34372,34372,1842,13276,11741],["Tstore_생활편의",3970459,3970459,151287,1162618,1127657],["Tstore_FUN",2389247,2389247,84211,699004,677481]]}]};
