### ISSUE TITLE
堆积面积图如何使透明颜色不叠加

### ISSUE THREAD

**Issue by DebugFuture** [ecomfe/echarts#1965]
我知道将颜色设置为不透明后可以达到不叠加的效果，但是视觉效果觉得没有透明的好。请问有什么方法可以做到颜色透明且不会叠加？

**Comment by stanleyxu2005** [comment]
堆积图就是叠加的。stack不设置，就不叠加了。不知道是不是理解了你的意思。
下图是我做的效果，左边是不叠加，背景透明。右侧是叠加，颜色不透明。
![111](https://cloud.githubusercontent.com/assets/5162687/9487203/016d17fe-4c02-11e5-8dd5-6e46a2b7f9a4.png)

**Comment by DebugFuture** [comment]
我想要的是highcharts的堆积图的效果，下面是highcharts和echarts的对比，你选中和取消选中图例的时候可以看到区别，highcharts的面积颜色是不会变的。
http://www.highcharts.com/demo/area-stacked
http://echarts.baidu.com/doc/example/line4.html

另外说下这个需求的背景，因为我的项目对颜色要求比较高，希望出现的颜色都是预先选定的那几种。echarts叠加后的颜色，在我的系统里看上去会非常奇怪。。。我尝试设置叠加前的颜色以达到叠加后的颜色符合预期，但是非常不方便，而且选中和取消图例的时候颜色又变掉了。。。

**Comment by stanleyxu2005** [comment]
颜色会变是因为他的颜色是带透明度的，默认好像是`0.92`。他的实现类似是`rgba(22,33,44,0.92)`。源码你可以搜索一下zrender.tool.color.alpha(`，我当时也找了很久。

如果你要修改，就必须`options.itemStyle.normal.areaStyle.color`指定成你要的颜色。不要用`rgba`而用`rgb`就可以了。但鼠标放在图例上的时候，高亮的颜色确实比较恶心，而且高亮的区域也不对，我后来没有精力去找究竟是哪里。目前看下来，highcharts的处理更好。

**Comment by DebugFuture** [comment]
好的，多谢。我去研究一下。
