### ISSUE TITLE
echarts在三星和华为的手机上执行动画效果会出现重绘的问题

### ISSUE THREAD

**Issue by MOLVMIN** [ecomfe/echarts#1966]
echarts在三星华为等手机上面的动画效果会出现重归的现在，导致显示混乱，希望能尽快解决这一兼容性问题！

**Comment by gordonpro** [comment]
你们是使用自带浏览器测试的还是WebView

**Comment by MOLVMIN** [comment]
我这边是做WebApp开发的，用的是三星自带的浏览器

**Comment by gordonpro** [comment]
那这个确实很难调试，因为机器实在太多。如果是App开发，可以使用内嵌比较牛逼的浏览器内核来解决这些兼容bug.
