### ISSUE TITLE
label formatter not work with '<br/>'

### ISSUE THREAD

**Issue by ljlok** [ecomfe/echarts#1970]
In lable[formatter]:

```
 label : {
            formatter : function (params){
                return 100 - params.value + '%' + '<br/>'
            },
}

```

But '\n'  worked
In tooltip[formatter]:

```
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
```

It works well , but  '\n' not 

label formatter doc:
 {string | Function} formatter  null    文本格式器：{string}（Template） | {Function}，模板变量为'{name}'，函数回调参数为name

tooltop formatter doc: 
{string | Function} formatter   null    内容格式器：{string}（Template） | {Function}，支持异步回调见表格下方

What's the main purpose for this design ? Thanks~

**Comment by stanleyxu2005** [comment]
确实有不一致的地方。label那边只支持简单的样式，而tooltip是支持html的。
