### ISSUE TITLE
echarts的不足

### ISSUE THREAD

**Issue by MOLVMIN** [ecomfe/echarts#1974]
echarts很强大，效果也很理想，但是对移动端的支持力度似乎还有所不足，在小屏幕上的效果较差，希望能尽快优化，WebApp是当前的一个趋势，希望echarts能重视这一块

**Comment by stanleyxu2005** [comment]
echarts的库比较大的，我觉得一个图形库超过100k，移动端就有点吃不消了，更何况echarts压缩之后接近1MB!
