### ISSUE TITLE
X轴标题太长导致不能显示完整的数据信息

### ISSUE THREAD

**Issue by chenxh520** [ecomfe/echarts#1975]
我目前用了柱状图表，发现X轴标题不仅倾斜了-55度，还会有溢出隐藏数据信息情况，如果要用某方法来重新排版数据想让它换行的话工作量很大，可能也不能完全解决问题。

![3](https://cloud.githubusercontent.com/assets/14010504/9539643/e4375542-4d86-11e5-8f18-b705d0acf6db.png)

**Comment by longFeiLi** [comment]
```grid```

**Comment by chenxh520** [comment]
什么意思？

**Comment by Ovilia** [comment]
这样效果的根本原因是图表比较小，不够展现文字信息。所以，需要从根本上解决问题，最好的办法应该是扩大整个图表的大小。如果因为一些原因没法扩大，你又不想像现在这样旋转了的话，那就设置文字间隔（比如每隔四个柱状图显示一次名字），具体做法是设置 `xAxis.axisLabel.interval`，参见：http://echarts.baidu.com/doc/option.html#title~xAxis-i(category).axisLabel.interval

**Comment by stanleyxu2005** [comment]
@chenxh520 @longFeiLi 的意思是，你可以把图标的高度扩大，然后把grid.y2的值增大。y2是x轴和图底部的距离。距离大了，文字也就放的下了。你还可以考虑使用小一号的字体。

**Comment by zuibunan** [comment]
用formater格式化name，两个字符插入一个换行符，文字可以竖着显示
