### ISSUE TITLE
词云的 tooltip 与词不对应

### ISSUE THREAD

**Issue by Gwill** [ecomfe/echarts#1976]
如图：

![qq 20150828153015](https://cloud.githubusercontent.com/assets/692980/9541354/e377fad6-4d99-11e5-9d8f-7a9db5cf3f48.jpg)

这是 bug 吗？

**Comment by Gwill** [comment]
#1967

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-wordcloud
