### ISSUE TITLE
timeline 在firefox火狐中显示异常

### ISSUE THREAD

**Issue by baihuibo** [ecomfe/echarts#1977]
chrome 显示正常
![chrome](https://cloud.githubusercontent.com/assets/5130197/9542148/d78665c6-4da0-11e5-8661-8a51f2e75b93.png)

firefox 显示异常
![firefox](https://cloud.githubusercontent.com/assets/5130197/9542152/e39c1874-4da0-11e5-873f-424cea72e35d.png)

而且label不支持中文显示

**Comment by longFeiLi** [comment]
``` timeline ``` 配置发出来看看。估计是你配置没有正确

**Comment by baihuibo** [comment]
```js
var option = {
	timeline:{
        data:['201506','201507'],
        label : {
            formatter : function(s) {
                return s.slice(0, 6);
            }
        },
        autoPlay : true,
        playInterval : 1000
    },
    options : [...]
}
```

具体图表的配置就省略了啊

**Comment by longFeiLi** [comment]
``` type:'number'  ```  在配置中加上就可以输入中文

**Comment by baihuibo** [comment]
`type:'number'`原来有这个用途啊，文档里都没写
好了，问题解决了

**Comment by longFeiLi** [comment]
文档里面有的

**Comment by baihuibo** [comment]
![494cf95d-28fb-4d20-b32f-857586cb3291](https://cloud.githubusercontent.com/assets/5130197/9575544/2923485e-5003-11e5-9331-1f25837a93a3.png)
是有这个配置，但是并没有说明这个配置是神马作用 - -
