### ISSUE TITLE
xAxis和series之间的数据是否可以无关

### ISSUE THREAD

**Issue by xfworld** [ecomfe/echarts#1981]
比如，我在xAxis中设置的是data : ['1月','2月','3月','4月','5月','6月','7月']
series中则是，每个月中每天的数据对应为【yyyy-mm-dd】,data

我看了下大概xAxis为time类型时，可以满足我设置值的要求，但是能够自定义data?
或者让我来定义哪些日期属于那一月？

**Comment by xfworld** [comment]
貌似我采用function自己定义return 就可以了？ 求指导，我的思路是否正确。

**Comment by stanleyxu2005** [comment]
x轴有2种类型，一种是时间，一种叫类目(category)。
如果是时间，那么插入数据的时候，每条数据集都必须给Date作为xLabel，一个或一组y值。
如果是类目，x轴的label可以是任何东西，插入数据的时候，x给的不是时间，而是index。

**Comment by xfworld** [comment]
@stanleyxu2005 谢谢你的回复，我的数据是不连续的；可能A数据在某个时间点上有值，B数据在相同的时间点上无值。按照此种可能性，只能采用time类型；
如果采用类目的方式，必须是同一个时间点，A和B都要有值；这种方式和我需要的定义，差别太大了，没办法去考虑；除非在无值的情况下，给予数据为0；（实在不行在考虑这种方式了）

昨天我查了很多资料，貌似在Xaxis定义的时候，可以采用自己formatter的情况进行定义，不知道能不能实现；要是能定义时间间隔和展示方式，这个问题也迎刃而解了；

**Comment by jimyuan** [comment]
@xfworld 貌似无值的情况下，他们的API中说可以用"-"来代替，例如['第一个值', '-','第三个值','第四个值']

**Comment by xfworld** [comment]
@jimyuan 用"-" 代替，就会出现断线的情况了

**Comment by xfworld** [comment]
不管怎么样，好歹也有办法可以继续了，呵呵，多谢各位了

**Comment by stanleyxu2005** [comment]
@xfworld 你和我遇到的是一样的问题。echarts可以做到，就是有些瑕疵而已。
你按照文档的描述方式来添加点[time,value,ishead,grow]类似这样。每条series独立添加，或者试试看把value改成[value1,value2]。（我这几天几个库来回尝试，也有点搞糊涂了）
重要的是，每条series定义的是，showAllSymbol=true

**Comment by xfworld** [comment]
我想到的办法，就是统一时间戳；采用类目的方式进行处理；只能在数据上进行加工了；没办法；
要是时间类型允许自己定义时间间隔和显示方式，那就狠完美了；

这个问题可以关掉了，希望能给予其他的兄弟们参考的价值；
@kener  要是Time类型有啥进展，不妨更新下.....

**Comment by stanleyxu2005** [comment]
@xfworld 现在好像主要是@pissang在做这个项目
