### ISSUE TITLE
柱图及折线图是否可以在节点处增加值标签？

### ISSUE THREAD

**Issue by dlutls** [ecomfe/echarts#1982]
![1](https://cloud.githubusercontent.com/assets/8817369/9575574/6d14f5e4-5003-11e5-8677-49136c40c0f6.PNG)
类似以上的效果，echarts图表是否可能提供，谢谢。

**Comment by longFeiLi** [comment]
上面图用echarts 是总的来说可以做的，可能有些细节会有自己的实现。
1 图例要自定义图片
2 每个显示的点要自定义图片，默认是小圆点、
3  生成数据画图表 ，可能涉及在节点处显示值（例子：http://echarts.baidu.com/doc/example/bar7.html） ，个人其实是不推荐显示值的用法，除非数据量比较小，如果大了会挡住后面。
