### ISSUE TITLE
如何将动态数据放入图表

### ISSUE THREAD

**Issue by xcLtw** [ecomfe/echarts#1983]
如题，现在的情况是可以通过ajax取值，如何赋值给图表呢？这个很重要，我想其实它应该出现在使用帮助明显的位子

**Comment by stanleyxu2005** [comment]
入口点是`chart.addData(...)` 具体看文档和实例。
http://echarts.baidu.com/doc/example/dynamicLineBar.html

例子里面是随机生成的数据，你只要把你通过ajax读取到的数据，转换成相应格式即可。
自己研究一下，不难。

**Comment by xcLtw** [comment]
通过将整个图表放入ajax的回调函数方法取到了数据库中的值，这个方法我会尝试的~三克油
