### ISSUE TITLE
柱状图的y轴上数字很大的时候无法显示完全

### ISSUE THREAD

**Issue by woodafire** [ecomfe/echarts#1984]
十亿以上的数字首位会丢失
并且这个问题无法通过给div更大的宽度来解决。
![issue](https://cloud.githubusercontent.com/assets/7135282/9575922/05287d4a-5006-11e5-9fbe-6c4f92cbe510.png)

**Comment by stanleyxu2005** [comment]
有几个做法，一个是接管y轴的formatter，然后去网上找一个把000变化成k的函数。
```
{
  yAxis: {
    formatter: function(value) {
      return humanReadableValue(value);
    }
  }
}
```
还有一个办法就是设置grid.x，把左侧的距离留的更大。

**Comment by woodafire** [comment]
可以解决，谢谢:-)

**Comment by libillgithub** [comment]
正好遇到这个问题，Highcharts都自动处理了

**Comment by stanleyxu2005** [comment]
@libillgithub highcharts是收费的，质量高一些也不足为奇。
