### ISSUE TITLE
希望实现截图中的数据点样式

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1985]
我想问问看有什么简单的办法，能把数据点呈现出截图中的样式
![highchart-symbol](https://cloud.githubusercontent.com/assets/5162687/9580093/d6ebd17e-5029-11e5-9950-4758242e8868.png)

我找了半天文档，发现`symbol='emptyCircle'`比较接近，但是没有外圈半透明的光晕。
我有一个想法是预先准备一批各种颜色的图片，然后用图片来替换，但是觉得这个工程量太大，而且如果改变颜色，图片就要重新生成。
不知道有什么办法解决这个问题？

题外话：能不能数据点不显示，只在鼠标移动到对应位置才显示。

**Comment by longFeiLi** [comment]
``` itemStyle ```  里面的``` emphasis ``` 试一下吧

**Comment by stanleyxu2005** [comment]
@longFeiLi 成功了，谢谢！普通状态设置一个透明的borderColor，然后等高亮的时候把颜色改成希望的半透明色。


我会把这个特性加入到我的dashing库里面https://github.com/stanleyxu2005/dashing
