### ISSUE TITLE
markline上可以直接显示文字么，不用鼠标悬停或点击

### ISSUE THREAD

**Issue by junmingmiss** [ecomfe/echarts#1988]
我是想地图刚初始化出来时在每一个markline上都显示出我想显示的数据，这样就更直观。。。不用鼠标悬停或点击这样触发才显示出数据。。。ths

**Comment by Ovilia** [comment]
看了一下 markLine 的代码，似乎是不行的，里面根本就得不到标题文字。这部分信息是在 tooltip 中做的。所以我觉得应该做不了。

**Comment by longFeiLi** [comment]
可以搭配``` markPoint ``` 去显示文字还可以自定义``` formatter ```,你可以试一下

**Comment by junmingmiss** [comment]
我自己markline和markpoint都有通过formatter的方式定义提示的数据，但现阶段是都要通过鼠标悬停的方式来展示出tooltip。。。若无法在地图初始化出来时在所有markline上就显示出tooltip，可否提供下思路或方案轮循每个markline让他们依次获得焦点这样的方式来让tooltip展示出来。谢谢哈
