### ISSUE TITLE
饼图，在小于100px左右的适合，下列配置，会导致环形变成实心圆

### ISSUE THREAD

**Issue by liuyunwei** [ecomfe/echarts#1989]
var option =  {
   
                  
                    series : [
                        {
                            name:'访问来源',
                            type:'pie',
                            radius : ['50%', '70%'],
                            data:[
                                {value:1, name:'直接访问'},
                                {value:0, name:'邮件营销'}
                            ]
                        }
                    ]
                };

**Comment by Ovilia** [comment]
照你的说法试了一下，并没有复现。可以试试看把 ` ['50%', '70%']` 改成其他的值看看是不是真的有效设置了。

**Comment by liuyunwei** [comment]
我忘了写测试环境了。 在IE8下可以复现

**Comment by atlas1119** [comment]
我有复现，有解决办法么？
