### ISSUE TITLE
Rendering big geodata

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#1991]
I'm often struggling with performance over a large geojson file in ECharts (and any other library really). Usually, I have to simplify geojson to make it usable but then I'm loosing quality when zooming etc. 

Just found this post today which can be a rescue? - https://www.mapbox.com/blog/introducing-geojson-vt/

https://github.com/mapbox/geojson-vt

It's generating vector tiles on the fly so not sure whether it fits current EChart rendering. But can be potentially inspiration:)

**Comment by suwenxiong** [comment]
Study...

**Comment by jarben** [comment]
Just wondering if this can be a 5x feature? :)
