### ISSUE TITLE
map图的dataRange值可以从数据里面直接计算得出吗?

### ISSUE THREAD

**Issue by liminjun** [ecomfe/echarts#1995]
http://echarts.baidu.com/doc/example/map1.html dataRange需要设置min和max的值。因为地图的数据都是动态的，所以max的值都不能用给一个固定值。所以目前先获取数据里面的最大值和最小值。然后去设置min和max值。因为min的值也可能不是从0开始计算。

这个功能可以放到地图内部里面计算，还是开发人员自己在外层计算，然后手动设置min和max值呢?

**Comment by Ovilia** [comment]
需要自己计算然后设置 `min` 和 `max` 的

**Comment by liminjun** [comment]
@Ovilia 目前就是自己来计算，后面看一下源代码如何实现颜色的渐变。
