### ISSUE TITLE
x轴最右侧label可能会被切掉一半

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1996]
![barchart](https://cloud.githubusercontent.com/assets/5162687/9677061/ad42ba00-5307-11e5-9ba3-5e71a7ccc620.png)

如图所示，x轴最右侧的label应该是20K，但是因为他是和最右的那根axis line是对齐的，所以K就被遮挡住了。我现在的解决方法是把grid.x2设置的大一些。

我看了一下highchart，它会把最后一个label和axis line做成右对齐，第一个label和axis line是左对齐，其他都是居中对齐。echarts能这么做吗？

**Comment by pissang** [comment]
现在还没有类似的配置项，trick 点可以把最后一个 label format 加上相同字符的空格，居中显示后就看起来是右对齐了

**Comment by stanleyxu2005** [comment]
如果是case by case，那么通过特殊手段肯定是可以的。当然还想希望以后可以在程序里面自动布局。

**Comment by frustigor** [comment]
遇到同样问题，echarts 最好提供一个参数来控制最后一个刻度的对齐方式
