### ISSUE TITLE
axisTick的显示位置不对

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#1997]
随便打开一个官方的线图演示，如果所有的数据都是>0的，那么xAxis的Tick都能正常显示。
![1](https://cloud.githubusercontent.com/assets/5162687/9686596/4facef28-5357-11e5-9fe7-b26c3bc8ffd3.png)

但如果数据里面有负数，这个Tick会固定在x轴上，虽然从字面上理解是正确的，但实际上因为x轴已经不是最下面那一根线，所以看起来根本看不清楚。
![2](https://cloud.githubusercontent.com/assets/5162687/9686602/56431498-5357-11e5-9230-cb4967d609c8.png)

个人理解：画到最下面一根axisLine看起来会更自然一点。

**Comment by pissang** [comment]
tick 如果放在图中间的话会跟柱状图的图形混淆

**Comment by stanleyxu2005** [comment]
我截图2里面就是当前echart渲染的，tick没有画在最下面，感觉这样不好。最好重开并fix一下。

**Comment by pissang** [comment]
抱歉刚才没细看理解成了 label，tick 是跟在 axisLine 上的，如果要放到下面可以设置 `axisLine.onZero` 为 `false`。

**Comment by stanleyxu2005** [comment]
OK，搞定了。
