### ISSUE TITLE
相同配置下，树图在Chrome和IE下显示节点和字体大小不一致

### ISSUE THREAD

**Issue by yfgensi** [ecomfe/echarts#1998]
![_chrome](https://cloud.githubusercontent.com/assets/8507766/9701850/bd304cd6-5472-11e5-8df2-74185db6b747.png)

**Comment by yfgensi** [comment]
![Uploading 冰桶挑战_IE.png…]()

**Comment by yfgensi** [comment]
![_ie](https://cloud.githubusercontent.com/assets/8507766/9701859/6dfb362a-5473-11e5-829e-95f4f9f1d68b.png)

**Comment by stanleyxu2005** [comment]
如果名字都换成英文，字体大小还有区别吗？
麻烦贴一下配置看看，可能不同浏览器对字体名字的解析有一些不同。
