### ISSUE TITLE
echarts bar中当value值为0时，怎么设置能让它显示出来，而不是空白

### ISSUE THREAD

**Issue by 61-113** [ecomfe/echarts#2002]
echarts bar中当value值为0时，怎么设置能让它显示出来，而不是空白，那样不太好看

**Comment by visgoods** [comment]
本来就是0，在Y轴上表示出来的就是没有了。如果为了好看，你可以给0的数据设置成0.1这样的形式，或者其它的方案来，我想是可以的

**Comment by pissang** [comment]
你可以在为 0 的数据处放个 markPoint

**Comment by visgoods** [comment]
楼上的方案我用过，嘿嘿

**Comment by xfworld** [comment]
放个图看看

**Comment by stanleyxu2005** [comment]
没有特别好的方法，对0值加一个mark point觉得比较直观。
你也看看别的库怎么实现。
