### ISSUE TITLE
为什么我的axisLabel文字无法居中呢，却是左对齐的？axisLabel能否针对某些值给某些颜色

### ISSUE THREAD

**Issue by visgoods** [ecomfe/echarts#2003]
如图，官方的demo都是默认居中的，但我这却没有居中，不知何故。能否增加一个设置，可让axisLabel文字向左或向右位移？同时能否也给一个function的方式，针对某个x,y轴上的文字我设置不同的颜色？
![Uploading 460491E9-654D-44C2-AED5-C3DCF88EEBBF.png…]()

**Comment by stanleyxu2005** [comment]
图片没看到，请重新上传。

**Comment by visgoods** [comment]
![460491e9-654d-44c2-aed5-c3dcf88eebbf](https://cloud.githubusercontent.com/assets/12268452/9712002/21db2cca-557a-11e5-8767-4263fdaf5b4b.png)

**Comment by visgoods** [comment]
![7607affc-199d-45ed-be4c-9f4711d54e85](https://cloud.githubusercontent.com/assets/12268452/9712118/ff6e39ec-557a-11e5-8e4a-563fe2cf523c.png)

**Comment by visgoods** [comment]
Y轴加了名称后，最上面的值会被往下挤，这也是个小问题:)

**Comment by stanleyxu2005** [comment]
@visgoods 加了y轴之后，数据最大值和边界默认会算一个距离出来，好像默认是10%。
没有居中的问题要看你给入的到底是什么字符串了，还有就是用没有用过formatter。
你贴一下代码才能分析。

**Comment by visgoods** [comment]
对，使用了interval和formatter控制了只显示上面5个X轴标签

**Comment by R-River** [comment]
@stanleyxu2005 请问3.0里面是不是不会自动添加数据最大/最小值与边界之间的距离了？还是可以在哪里设置？谢谢！

**Comment by stanleyxu2005** [comment]
我不是开发团队的，不太清楚。交给@pissang 回答

**Comment by pissang** [comment]
这个跟数据最大最小值与边界的距离无关，是 echarts 对边界的 label 没处理好，目前可以通过设一个合适的 grid.y2 配合负 margin 进行 hack

**Comment by R-River** [comment]
@pissang 我去试试 非常感谢！

**Comment by visgoods** [comment]
@R-River 
x轴label的位置（y轴应该同理）可以在传入的数据里单独设置，如下dataArr是x轴数据
dataArr[0] = {
                value: dateArr[0],
                textStyle: {
                    align:"left"
                }
            };
dataArr[dataArr.length-1] = {
                value: dateArr[dataArr.length-1],
                textStyle: {
                    align:"right"
                }
            };
