### ISSUE TITLE
事件河流图数据都为同一天，会报错。

### ISSUE THREAD

**Issue by zhoulijie** [ecomfe/echarts#2004]
RT

**Comment by stanleyxu2005** [comment]
报什么错，贴一下错误信息。

**Comment by zhoulijie** [comment]
![eventriver](https://cloud.githubusercontent.com/assets/4424050/9709820/e44df8e8-5564-11e5-92dc-3e3d5437bbe9.png)

并且一直在累加。

**Comment by stanleyxu2005** [comment]
初看感觉是x轴没有正确初始化，数据没办法正确添加。
你最好整一份最小可运行代码放在jsbin或者其他地方，让大家来分析了。不然真的很难帮到你。

**Comment by zhoulijie** [comment]
地址：http://jsbin.com/puriwotosa/1/edit?html,output
先无视美观，3条数据都为同一天，导致报错。

**Comment by stanleyxu2005** [comment]
series里面time的值不能是string，应该是`"time": new Date("2014-05-01"),`

**Comment by zhoulijie** [comment]
目前，按您这边说的几条做，仍然在报错。
jsbin用的不多，不知道是不是会存在覆盖的可能。
您这边如果有什么解决方案或结果，方便发到我邮箱吗？ivanzhou1@vip.qq.com
麻烦了！

**Comment by stanleyxu2005** [comment]
@zhoulijie 我就把3个时间设置的不一样，图就可以出来了。

**Comment by zhoulijie** [comment]
@stanleyxu2005 是的。N条数据，只要有一条数据不为同一天，就不会报错。
不知道，这是事件河流图本身就是这样设计的，还是有bug。

**Comment by stanleyxu2005** [comment]
我感觉你应该创建一条时间流里面添加多条数据... 而不是创建多条时间流...

**Comment by zhoulijie** [comment]
http://echarts.baidu.com/doc/example/eventRiver1.html
我尝试着修改官网”财经事件“中的任意一条数据，为同一天，就会报错。
官网提供的数据符合您说的，一条时间流中多条数据（我也是无意中修改了一条数据发生在同一天才发现的- -#）。
我觉得一条时间流中，同一天发生2件或2件以上事件是正常的，所以向您这边提了一下。

**Comment by stanleyxu2005** [comment]
帮你@pissang 我不是开发团队的，我只是一个新来的用户。

**Comment by zhoulijie** [comment]
@stanleyxu2005 - -# 这样阿。还是多谢！我工作里面用到echarts的地方比较多。然后无意间碰到了这个问题。
