### ISSUE TITLE
[简单关系图]是否可以保存节点当前状态（包括位置和数据）并在下次打开时恢复当前状态

### ISSUE THREAD

**Issue by merow** [ecomfe/echarts#2007]
目前有个功能是要保存当前关系状态，并在关闭页面再次打开时还原上一次的状态，现在数据没问题，主要是位置恢复不了，请问echart中的关系图支持获取点的位置么？

**Comment by pissang** [comment]
保存和恢复只能自己使用 localStorage 或者存到服务器做，位置的回复可以设置每个节点的 `initial` 属性
