### ISSUE TITLE
treemap 矩形树图数据下钻过渡问题以及如何返回父节点数据

### ISSUE THREAD

**Issue by kevindu1993** [ecomfe/echarts#2008]
你好，我想了解下， 
1. treemap有没有可以设置treemap 数据下钻 动画过渡的属性？
2. 返回到上一层的时候，除了点下面的那个返回外，是否可以像从父节点到子节点一样 点一下子节点的一个区间返回到父节点呢？
感谢

**Comment by pissang** [comment]
目前无法做到这两点
