### ISSUE TITLE
图例添加tooltip 功能的需求

### ISSUE THREAD

**Issue by yuanrui** [ecomfe/echarts#2011]
图列 legend 的API中能否添加一个tooltip 用于显示对图例的备注说明呢，当鼠标移动到图例上时显示对图例的补充说明。

**Comment by yaoyu73100** [comment]
同求，我这几天也在找这个功能，貌似没有，不知道什么时候能出。

**Comment by stanleyxu2005** [comment]
自己找其他的解决方案，做一个chart以外的图例，这样就可以满足各种需求了。作为echarts，我感觉增强图例的这种需求的优先级是非常低的。

你可以看我之前在制作环图时候遇到的[一些问题](https://github.com/ecomfe/echarts/issues/1937)
在我感觉如果echarts举手之劳能实现，我可以省很多事情。
不过3个礼拜过去都没有人鸟，我就直接通过其他方式去实现了。
有的问题如果可以解决，我甚至可以直接提交一个PR，但看来开发团队对此也是兴趣寥寥。唉。
