### ISSUE TITLE
保存为图片与数据区域缩放效果不好

### ISSUE THREAD

**Issue by cyxsheep** [ecomfe/echarts#2014]
在一个使用了数据区域缩放的图表上，使用保存图片功能，他保存的是当前缩放状态下的图表，而不是完整的数据区域。能不能开放保存图片的API，这样就可以自己写保存图片时使用的option了。

**Comment by xfworld** [comment]
没玩过，不过关注下....看看解决方案是什么

**Comment by longFeiLi** [comment]
可以获取图片Base64去做

**Comment by xfworld** [comment]
@longFeiLi  有没有相关的介绍？ 发个链接参考下

**Comment by longFeiLi** [comment]
@xfworld   ![image](https://cloud.githubusercontent.com/assets/10267141/9805176/67a2eb44-5868-11e5-8705-06fb88ef31ff.png)

**Comment by xfworld** [comment]
@longFeiLi  谢谢了，另外有没有后端直接调用生成图的搞法？
