### ISSUE TITLE
legend 定位问题

### ISSUE THREAD

**Issue by gbk** [ecomfe/echarts#2016]
http://echarts.baidu.com/extension/BMap/doc/BMap.html

legend 按如下配置：

``` js
    legend: {
        orient: 'vertical',
        x:'right',
        padding: [20,20,20,20],
        backgroundColor: '#fff',
        data:['北京', '上海', '广州'],
        selectedMode: 'single',
        selected:{
            '上海' : false,
            '广州' : false
        }
    },
```

定位不对，期望紧靠右侧，实际距离右侧多了一个 padding 的距离。

![image](https://cloud.githubusercontent.com/assets/865717/9793651/1b07bfac-5819-11e5-93b4-d9a683eadca5.png)

**Comment by stanleyxu2005** [comment]
x可以指定具体的像素大小，通过这个来调整吧。

`x: 'right'` -> `x: '400px'`类似这样。需要一定的计算，必要时候还要hook页面宽度变化。
