### ISSUE TITLE
能否像基金实时估值样给Y轴样式定制

### ISSUE THREAD

**Issue by visgoods** [ecomfe/echarts#2017]
如下图，需要在指定Y轴不同值不同的颜色。X轴似乎能，Y轴没有。
![624788ff-47cf-41e7-b08a-8a6cbf9aeb7d](https://cloud.githubusercontent.com/assets/12268452/9807284/8e504776-5883-11e5-95ae-76767f024988.png)

**Comment by stanleyxu2005** [comment]
1. 不同颜色问题，参考这个实现https://github.com/ecomfe/echarts/issues/226，就是axisLabel的textStyle使用函数回调。
2. 右侧第二根数据轴，可以通过添加第二根yAxis来实现。http://echarts.baidu.com/doc/example/mix1.html

**Comment by visgoods** [comment]
额外增加了一组值来实现的这个需求

**Comment by fuligold** [comment]
@stanleyxu2005 问下，axisLabel的textStyle使用函数回调，具体应该怎么使用？#226这个例子没有看懂。

**Comment by stanleyxu2005** [comment]
@fuligold 我有一段时间没有碰这个库了，所以也记不清。主要是setOptions里面给入特定的配置json。
可以参考这个https://github.com/ecomfe/echarts/commit/9412e4ef157132d456486062c55b37d2d8502684

**Comment by fuligold** [comment]
@stanleyxu2005 感谢你的回复，找了很久也没有找到实例，9412e4e这个我看了，但是使用上还是有问题，  color : typeof textStyle.color == 'function'
           ? textStyle.color(data[i]) : textStyle.color,
主要还是这段没有太明白。

**Comment by visgoods** [comment]
@fuligold 文档里color是个function, 你可以通过调试，看看传入的参数，根据参数来个性化颜色

**Comment by fuligold** [comment]
@visgoods 感谢回复，这个问题已经修改好了。是之前的传入参数有问题，没有检查到。
