### ISSUE TITLE
关于example中的源码能否直接显示出来？方便借助案例学习！

### ISSUE THREAD

**Issue by KomaBeyond** [ecomfe/echarts#2019]
看了看这个库做的是很不错，但是比较操蛋的是案例里面的源码竟然藏那么深！！！真是受不了你，大家借助你给的案例学习起来不是更快些吗，给了些案例又把源码藏起来，有什么意思！

**Comment by xfworld** [comment]
@KomaBeyond  显然这么做是为了增加查找代码的能力 ^_^   有啥问题直接问吧，抱怨和埋怨都没啥用...

**Comment by hello2t** [comment]
赞楼上，有问题直接问就好。

**Comment by pissang** [comment]
代码都在那，什么叫把代码藏起来？

**Comment by suwenxiong** [comment]
本来就没啥代码啊，echarts很简单，就一个配置项，楼主如果想深入，就看下echarts源码吧
