### ISSUE TITLE
echarts 中自定义 legend 后颜色一直为灰色

### ISSUE THREAD

**Issue by scarletsky** [ecomfe/echarts#2020]
因为默认图例不符合我的要球，所以我自定义过图例。定义如下：

```js
{
    ....
    color: [
        'yellow',
        'orange',
        'pink',
        'red'
    ],
    legend: {
        data: [
            '正常',
            '轻度',
            '中度',
            '重度'
        ]
    }
}
```

这样是可以满足我的要球的，但这样自定义之后，只有在鼠标移到图例上面的时候才有颜色，其他时候都显示灰色的。

请问有什么办法可以让自定义的图例颜色显示正常吗？

**Comment by pissang** [comment]
我试了下并没有没这个问题，是否是不存在 “正常”，“轻度”  这些系列？

**Comment by scarletsky** [comment]
@pissang 是的，不存在这些系列的。有什么办法可以正常显示 legend 么？

**Comment by pissang** [comment]
legend 的作用就是选择系列的显示，如果不存在就会强制变成灰色

**Comment by scarletsky** [comment]
@pissang 有方法让它正常显示么？

**Comment by xfworld** [comment]
理解一下，你设置了legend，但是legend没有对应的data？

**Comment by scarletsky** [comment]
@xfworld 嗯，是的。legend是我自定义的

**Comment by xfworld** [comment]
你把数据加上去阿...

**Comment by scarletsky** [comment]
@xfworld 
我不是那个意思。看图吧。

![aec57e64-6fd1-4a41-8823-8c5fd0839a7f](https://cloud.githubusercontent.com/assets/2386165/9849774/7b03e962-5b20-11e5-8b2c-cbc597dff055.png)

这个图里面，我会按照特定的规则为每一个柱形上色，我希望图例显示的是某个颜色对应哪个状态，图例不需要和数据匹配上，不需要处理事件，只需要正常显示图例的颜色就可以了。

**Comment by suxuekun** [comment]
为啥是legend 不是datarange

**Comment by suxuekun** [comment]
或者你有10个bar 就10个Series可以重名用4个name，每个series一个bar

**Comment by scarletsky** [comment]
@suxuekun 感谢提示，我先研究以下 datarange

**Comment by xfworld** [comment]
@scarletsky 
datarang帮不了你吧，我理解你的数据构成是这样子的；

类型A {正常、轻度、中度、重度}
类型B {正常、轻度、中度、重度}
类型C {正常、轻度、中度、重度}

以上的数据，你可能还有其他的维度，年龄，性别什么什么等等，
可能需要降维处理，但是legend一般和Series是相关的，你需要自己定义每个Series的颜色，和legend中的颜色对应，这样子就ok了；

**Comment by scarletsky** [comment]
@xfworld 
我的数据是这样子的：

A: [11,22,33,44,55,66,77 ... ]
B: [22,33,44,55,66,77,88 ... ]

长度都不确定，但 `A.length === B.length`，我会按照一定的规则来让他们上色。
 
我看你的意思是让我重构数据结构？

**Comment by xfworld** [comment]
长度不确定不要紧，但是xAxis { data [] } 是约束Series { data[] }，基本上是配对的；你需要考虑这个。
类目类型的也只能这么干：） 可以赋值为 0 或者 为 '-'

**Comment by scarletsky** [comment]
@xfworld ok，我去试试

**Comment by scarletsky** [comment]
好吧，我放弃了。还是直接那 html+css 来模拟算了。
