### ISSUE TITLE
折线面积图，是否有选择面积的功能呢？

### ISSUE THREAD

**Issue by ioryloogh** [ecomfe/echarts#2023]
比如，一个折线面积图，我在某一位置开始，按下鼠标左键（根据点击位置，做一条竖线，暂时叫起始竖线），然后向左或者向右移动鼠标，以此来实现选择从起始竖线，到当前竖线之间的面积的功能，松开鼠标左键后，选择完成。所选择的部分是另外一种颜色。
请问是否有这种功能呢？
如果没有，如何能实现这种功能？

**Comment by pissang** [comment]
抱歉暂时还没有
