### ISSUE TITLE
饼图bug上报

### ISSUE THREAD

**Issue by suwenxiong** [ecomfe/echarts#2024]
当饼图有多个数据集中在某一小概率覆盖面时，引导线就会指到图表外面，无法看到此label

**Comment by suwenxiong** [comment]
![ebug](https://cloud.githubusercontent.com/assets/9148952/9835142/6944f928-5a0d-11e5-9472-61d64e62d875.png)

**Comment by suwenxiong** [comment]
此灰色部分的label跑到外面去，看不见了，请问有人知道怎么解决吗

**Comment by suwenxiong** [comment]
可以修改center配置解决

**Comment by vencher** [comment]
项目中也有遇到，我是这样子解决的。通过修改源码。
require([ 'echarts/chart/pie' ], function(pie) {
	// 重载getLabel方法
	pie.prototype.getLabelTemp = pie.prototype.getLabel;
	pie.prototype.getLabel = function (
            seriesIndex, dataIndex, percent,
            center, midAngle, defaultColor,
            isEmphasis
        ){
			defaultColor = "#999";	// add by caiwc 2015-10-20 原本是根据饼图颜色设置默认颜色,重叠时不能区分,默认为灰色
			return this.getLabelTemp(seriesIndex, dataIndex, percent,center, midAngle, defaultColor,isEmphasis);
	};
	
	pie.prototype._layoutCalculate =  function (tList, center, r, direction) {
        tList.sort(function (a, b) {
            return a._rect.y - b._rect.y;
        });
        function _changeDown(start, end, delta, direction) {
            for (var j = start; j < end; j++) {
                tList[j]._rect.y += delta;
                tList[j].style.y += delta;
                if (tList[j]._labelLine) {
                    tList[j]._labelLine.style.pointList[1][1] += delta;
                    tList[j]._labelLine.style.pointList[2][1] += delta;
                }
                if (j > start && j + 1 < end && tList[j + 1]._rect.y > tList[j]._rect.y + tList[j]._rect.height) {
                    _changeUp(j, delta / 2);
                    return;
                }
            }
            _changeUp(end - 1, delta / 2);
        }
        function _changeUp(end, delta) {
            for (var j = end; j >= 0; j--) {
                tList[j]._rect.y -= delta;
                tList[j].style.y -= delta;
                if (tList[j]._labelLine) {
                    tList[j]._labelLine.style.pointList[1][1] -= delta;
                    tList[j]._labelLine.style.pointList[2][1] -= delta;
                }
                if (j > 0 && tList[j]._rect.y > tList[j - 1]._rect.y + tList[j - 1]._rect.height) {
                    break;
                }
            }
        }
        function _changeX(sList, isDownList, center, r, direction, width) {
            var x = center[0];
            var y = center[1];
            var deltaX;
            var deltaY;
            var length;
            var lastDeltaX = direction > 0 ? isDownList ? Number.MAX_VALUE : 0 : isDownList ? Number.MAX_VALUE : 0;
            for (var i = 0, l = sList.length; i < l; i++) {
                deltaY = Math.abs(sList[i]._rect.y - y);
                length = sList[i]._radius - r;
                deltaX = deltaY < r + length ? Math.sqrt((r + length + 20) * (r + length + 20) - Math.pow(sList[i]._rect.y - y, 2)) : Math.abs(sList[i]._rect.x + (direction > 0 ? 0 : sList[i]._rect.width) - x);
                if (isDownList && deltaX >= lastDeltaX) {
                    deltaX = lastDeltaX - 10;
                }
                if (!isDownList && deltaX <= lastDeltaX) {
                    deltaX = lastDeltaX + 10;
                }
                // BEGIN add by caiwc 2015-10-20 解决饼图label超出图表区域
                if(x + deltaX * direction < sList[i]._rect.width) {
					deltaX = (sList[i]._rect.width - x)/direction;
				}else if(x + deltaX * direction + sList[i]._rect.width > width) {
					deltaX = (width - sList[i]._rect.width - x)/direction;
				}
                // END by caiwc 2015-10-20 
                
                sList[i]._rect.x = sList[i].style.x = x + deltaX * direction;
                if (sList[i]._labelLine) {
                    sList[i]._labelLine.style.pointList[2][0] = x + (deltaX - 5) * direction;
                    sList[i]._labelLine.style.pointList[1][0] = x + (deltaX - 20) * direction;
                }
                lastDeltaX = deltaX;
            }
        }
        var lastY = 0;
        var delta;
        var len = tList.length;
        var upList = [];
        var downList = [];
        for (var i = 0; i < len; i++) {
            delta = tList[i]._rect.y - lastY;
            if (delta < 0) {
                _changeDown(i, len, -delta, direction);
            }
            lastY = tList[i]._rect.y + tList[i]._rect.height;
        }
        if (this.zr.getHeight() - lastY < 0) {
            _changeUp(len - 1, lastY - this.zr.getHeight());
        }
        for (var i = 0; i < len; i++) {
            if (tList[i]._rect.y >= center[1]) {
                downList.push(tList[i]);
            } else {
                upList.push(tList[i]);
            }
        }
        _changeX(downList, true, center, r, direction, this.zr.getWidth());	// add by caiwc 2015-10-20 增加width参数
        _changeX(upList, false, center, r, direction, this.zr.getWidth());	// add by caiwc 2015-10-20 增加width参数
    }
});
