### ISSUE TITLE
能否把构建出来的文件从repo里面移除

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#2025]
最近不小心把echarts的repo从本地删除了，再次clone是个非常漫长的过程。ms有50mb的文件需要下载……

不知道贵团队怎么想，我使用一个项目的人群分2类：
1. 一类是使用者，他们只要下载打包之后的文件即可。源代码对其可有可无。
2. 一类是开发者，他们是来研究源码的，必要时会自己去构建代码。

再进一步考虑使用场景：
1. 对于使用者来说，使用`npm install echarts`的时候，他们恨不得只有build目录和必要的LICENSE和README，其他文件越少越好。
2. 对于开发者来说，既然他们会自己构建代码，那何必从repo里面下载可能接近10MB的构建文件呢？

我目前的经验是这样：
1. 在用git做版本控制的前提下，在.gitignore里面添加`build/`，这样本地构建的代码不会被提交到git里面。这样也使得跟踪改动的时候，不需要看build目录下面的diff。
2. 在用npm发布之前，修改package.json，在files这栏包含`build`。别人通过npm下载echarts的时候，肯定是有他们需要的文件的。
3. 像近40mb的docs目录也可以考虑瘦身或者变成独立的项目。

欢迎大家参与讨论。

**Comment by pissang** [comment]
谢谢建议，现在项目大是因为示例多，并不是因为有构建文件的原因。而且说实话使用 npm install 下载的是少数，我们没理由为了那些使用 npm 管理第三方库的开发者去掉构建文件。

不过现在整个项目包的体积确实太大了，前段时间也有想过把文档和示例挪出来，但是因为主要精力在开发 3.0，所以想趁 3.0 的时候把这个问题一并解决了

**Comment by uooo** [comment]
能提前透露下 3.0 中的新特性吗？ES6 还是 TypeScript 开发？

**Comment by stanleyxu2005** [comment]
嗯，多开几个项目就可以了。
