### ISSUE TITLE
Echarts datazoom 步进的拖动

### ISSUE THREAD

**Issue by wahaha04** [ecomfe/echarts#2026]
使用拖动事件会进入递归死循环，怎么能够让他拖动时候有步进的拖动，比如以天为单位。

**Comment by stanleyxu2005** [comment]
设置start和end的值，让选择的区间差不多维持在一天的范围。

**Comment by xfworld** [comment]
最好在数据上下功夫....只显示一天的平均值....

start和end 也是可以手动调整的....所以.....

**Comment by wahaha04** [comment]
我用toolbox中自定义工具按钮实现了这样的：
start_value = option.dataZoom.start;
end_value = option.dataZoom.end;
start_value -= 100/30;
option.dataZoom.start = start_value;
this.component.dataZoom.absoluteZoom({start:start_value, end: end_value});
这样可以做到，但是不是我想的在datazoom的缩放条上步进，在缩放条上使用datazoom事件上clear后使用setOption或者使用absoluteZoom，都会发生递归直至栈溢出的错误~

**Comment by wahaha04** [comment]
不知道有没有牛人愿意分享一下如何在http://echarts.baidu.com/doc/example/dataZoom1.html这个例子上，如何实现datazoom拖动条上的步进~以天为单位

**Comment by stanleyxu2005** [comment]
你锁一下不就好了？datazoom.lock=true
