### ISSUE TITLE
如何给x轴添加装饰性的文字

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#2027]
我现在的数据（一根数据）添加间隔是每分钟，但是希望x轴的label是每15秒更新一次，这个label上面没有数据。不知道能不能实现这样的情况。我看了文档似乎没有看见类似的介绍。

我现在想了一个办法：
1. x轴使用time为类型。
2. 添加第二根数据，每15秒更新一次，值始终是0。
3. 关闭图例。
但有一个问题是，第一根数据的tooltip我还是想看的。但第二根数据的tooltip似乎不能选择性关闭。

请问有什么办法可以搞定？

**Comment by xfworld** [comment]
好复杂的需求.....

需要time类型支持吧.....不支持就白搭了...

**Comment by stanleyxu2005** [comment]
@xfworld time类型的支持不是暂时有问题么...

**Comment by longFeiLi** [comment]
1.data 里面可以是{} 然后在对象里面关闭tooltip
还是不明白要做什么。我理解能力不好。

**Comment by stanleyxu2005** [comment]
@longFeiLi 是我不好，说的大家都听不明白。

现在简化成这样，假设我想在chart上显示40个点。但我现在只有5个点，于是我给前面35个点设置成`{x:'', y:'-'}`。现在的问题是，鼠标移动到图上的时候，tooltip指向那5个点是ok的，但是鼠标移动到前面35个点的时候，我希望不显示tooltip。能不能实现？

**Comment by longFeiLi** [comment]
可以，
![image](https://cloud.githubusercontent.com/assets/10267141/9851747/f2c50e84-5b2c-11e5-8936-668ba960f41d.png)

**Comment by stanleyxu2005** [comment]
赞 @longFeiLi
