### ISSUE TITLE
平均值的虚线显示错误

### ISSUE THREAD

**Issue by HADB** [ecomfe/echarts#2037]
对于数值很小的一堆点（数值都在1以下），平均值线条绘制不出来，却在图标左上角出现一个奇形怪状的小东西，鼠标放上去会加粗，感觉把平均值的虚线画到不该画的地方了。

**Comment by stanleyxu2005** [comment]
建议在jsbin提供以下可以复现问题的代码，或提供配置和截图。不然很难帮你。
