### ISSUE TITLE
[tooltip]详情dom上增加css类定义'echarts-tooltip'，可通过css附加样式

### ISSUE THREAD

**Issue by likunNet** [ecomfe/echarts#2039]
请问我在页面定义echarts-tooltip的样式为何对tooltip不起作用，如
     .echarts-tooltip {
                color: red;
             background-color: green;
            }

**Comment by likunNet** [comment]
调了下源码，发现 _defaultCssText与_gCssText会写上这些属性，那基本可扩展的属性也有限。。。自定义echarts-tooltip 样式与以下属性重复的，都会被覆盖
_defaultCssText:transition:left 0.4s,top 0.4s;-moz-transition:left 0.4s,top 0.4s;-webkit-transition:left 0.4s,top 0.4s;-o-transition:left 0.4s,top 0.4s;background-Color:#000000;filter:alpha(opacity=70);background-Color:rgba(0,0,0,0.7);border-width:0px;border-color:#333;border-radius:4px;-moz-border-radius:4px;-webkit-border-radius:4px;-o-border-radius:4px;color:#fff;padding:5px 5px 5px 5px;
_gCssText:position:absolute;display:block;border-style:solid;white-space:nowrap;

**Comment by stanleyxu2005** [comment]
通过tooltip的选项去定义样式。下图是我自定义的样式
![d6ebd17e-5029-11e5-9950-4758242e8868](https://cloud.githubusercontent.com/assets/5162687/9984775/ca78b7fe-6050-11e5-8791-37b9dd24d929.png)
可参考https://github.com/stanleyxu2005/dashing/blob/master/src/charts/echarts.js#L190

**Comment by xpbtmusic** [comment]
你好，tooltip怎么通过选项自定义css样式。[http://static.oschina.net/uploads/space/2015/0828/184332_GFJ2_2440437.png](url)
