### ISSUE TITLE
echarts主题词云问题

### ISSUE THREAD

**Issue by jiaolj** [ecomfe/echarts#2041]
您好，主题词云在使用中文时，鼠标移到某个词上，我鼠标移动到苹果上提示的是梨子，还有点击，悬浮事件也是跳出别的词了.. 
这个问题能修复吗？ 我的屏幕分辨率是1366X768.  生成图表区域的div大小是852X400.
![image](https://cloud.githubusercontent.com/assets/14029050/9983993/89b99134-6041-11e5-9062-f3ba1f4ced6e.png)

**Comment by pissang** [comment]
同 #2012
