### ISSUE TITLE
折线图中非连续的点能否连接起来？

### ISSUE THREAD

**Issue by ztmsimon** [ecomfe/echarts#2048]
在做折线图的时候，横轴是每个月30天，纵轴是数量，但是可能会某一天没有生产数量，这个时候点就断开了，能否将断开的点连接起来？

**Comment by pissang** [comment]
如果是空数据 `-` 的话不能，如果是生产数量是 0 的话没这个问题

**Comment by stanleyxu2005** [comment]
如果横轴是类目，那么就数量添加0，因为确实没有数字。如果是数据采集问题，那在画图之前先把数据补全。
如果横轴是时间，可以直接在这天不插入数据。折线图还是会根据趋势连起来，不会有断裂。
