### ISSUE TITLE
能否支持x轴是时间格式，可以无限缩放

### ISSUE THREAD

**Issue by HappyGod158** [ecomfe/echarts#2049]
在缩放的功能上，x轴能否做出类似jqplot和hcharts那种效果来，可以一直放大，从年到月到小时。

**Comment by xfworld** [comment]
不是有zoom么？

**Comment by HappyGod158** [comment]
你指的dataZoom么？ 那怎么设置x轴的data？

**Comment by HappyGod158** [comment]
你指的dataZoom么？ 那怎么设置x轴的data？比如放小时X轴显示为年，放到最大时可以精确到分钟甚至秒

**Comment by xfworld** [comment]
按照你说的数据格式，数据粒度精确到秒？那你的数据量会有多大阿？ 
你可以自己设定dataZoom的start和end，并且lock，拖动块就可以达到你要效果。

**Comment by HappyGod158** [comment]
恩，非常感谢您的耐心解答，如果数据量是1w折线图，我在dataZoom拖拽时会有卡顿，这个是我的原因还是本身的性能问题？

**Comment by HappyGod158** [comment]
换句话说，据我了解，ECharts当数据量较大时，就用取均值（或别的方法）的方法只显示部分数据。那么在数据驱动生成X坐标轴数据时你们有这方面的性能优化么？  谢谢！

**Comment by stanleyxu2005** [comment]
好像不支持拖拽选择缩放区域，得通过datazoom的控件来选择。

**Comment by xfworld** [comment]
貌似可以考虑多图联动的方式来完成，有点象简单的数据钻取...

**Comment by anneyangyue** [comment]
一直放大，坐标轴的起始坐标和终止坐标相同时，再次放大，坐标轴的刻度范围不在之前的范围内了
