### ISSUE TITLE
Echart设置时间轴的最大值最小值以及分割段不起作用，不知道是不是设置有问题?

### ISSUE THREAD

**Issue by free421xiaobai** [ecomfe/echarts#2050]
xAxis : [
        {
            type : 'time',
            splitNumber:10,
            max: new Date(2010/9/1),
            min: new Date(2010/0/1)
        }
    ],

**Comment by xfworld** [comment]
min: new Date(2010/0/1) 这个日期不对吧....

**Comment by free421xiaobai** [comment]
Sorry, new Date(2000/1/1)

**Comment by stanleyxu2005** [comment]
贴一个测试代码。从你给的数据来看。`new Date(2010/9/1)`是有语法错误的。至少是`new Date('2010/9/1')`.

**Comment by qingming418** [comment]
我也遇到这个问题，改成这个Date('2010/9/1')也一样。结果
![image](https://cloud.githubusercontent.com/assets/20061205/18612486/820c6190-7d8d-11e6-9039-58d0831c3852.png)
