### ISSUE TITLE
ECharts怎么实现上证指数K线鼠标滚动缩放和点击按住左右移动呢？

### ISSUE THREAD

**Issue by boypany** [ecomfe/echarts#2052]
ECharts怎么实现上证指数K线鼠标滚动缩放和点击按住左右移动呢？

就是：

```
    1.鼠标悬浮在k线图上时，k线图可以随鼠标滚动而缩放。


    2.鼠标点击按住，左右移动时，k线图可以左右移动。
```

可以实现吗，怎么实现呢，谁有类似例子分享个呀~谢谢。

**Comment by pissang** [comment]
3.0 开始通过 http://echarts.baidu.com/option.html#dataZoom-inside 组件支持
