### ISSUE TITLE
line 中的tooltip 的trigger属性为axis时，倒数第二个数据的气泡不准

### ISSUE THREAD

**Issue by bydeath** [ecomfe/echarts#2055]
我是在这里发现的，http://echarts.baidu.com/doc/example/line1.html
将鼠标移至横坐标为周六的刻度时，会显示周日的气泡提示，若是没出现，鼠标稍微往右边移一点就会出现。

**Comment by pissang** [comment]
没发现这个问题，看下 tooltip 的 line 是否在周日的数据上

**Comment by stanleyxu2005** [comment]
确实有点问题。
就是x轴周六刻度往右5px之后，就都属于周日范畴。而如果你参考周一到周五，应该还属于前一日的范畴。
