### ISSUE TITLE
关于地图geoCoord  ----- 县区怎么geoCoord从哪能得到？？？

### ISSUE THREAD

**Issue by whjadsj** [ecomfe/echarts#2057]
现在官网只有地市一级的geoCoord没有县（区）一级， 县区怎么geoCoord从哪能得到

**Comment by suwenxiong** [comment]
可以参考下util/mapData/geoJson 下的地图数据

**Comment by pissang** [comment]
http://ecomfe.github.io/echarts-builder-web/
