### ISSUE TITLE
echarts建议

### ISSUE THREAD

**Issue by suwenxiong** [ecomfe/echarts#2060]
1echarts应该做个插件机制,一些官方没有的功能可以通过插件机制实现.
2echarts虽然做的已经很不错了,但跟d3比起来本人觉得还是有些差距,希望未来echarts比d3更炫更酷.

**Comment by stanleyxu2005** [comment]
1. 你可以自己fork源码修改，我有时候会这么干。
2. d3好的特性，需要加入的特性，可以单独开issue提。你这么笼统的说，意义就不大了。
