### ISSUE TITLE
能否新增 严格意义上的 堆积图（Mountain图）

### ISSUE THREAD

**Issue by yongnny** [ecomfe/echarts#2062]
需求：
需要用 Mountain 图来展示数据，而且鼠标点击在 图块 上能触发事件（例如：让选中的图块高亮）

暂时的解决：
http://echarts.baidu.com/doc/example/line3.html   标准面积图
http://echarts.baidu.com/doc/example/line4.html   堆积面积图
这两种图都并不是严格意义上的 堆积图，都是基于 折线图的，是在折线图上加了 areaStyle  进行底部区域的填充，而且鼠标点击在填充区域上触发不了任何事件

**Comment by suwenxiong** [comment]
只有闭合曲线才能成图

**Comment by yongnny** [comment]
@suwenxiong 
http://echarts.baidu.com/doc/example/line3.html 标准面积图
http://echarts.baidu.com/doc/example/line4.html 堆积面积图
这2个 demo 里的 曲线和曲线之间（上下），第一个坐标轴和最后一个坐标轴（左右）难道不能构成闭合么？

**Comment by jsoncode** [comment]
每一条线都是独立的，他们没有交集，你要是深入的使用了，了解了它的参数结构，就不会有这个疑问了
