### ISSUE TITLE
safari上切换环形图动画完成时页面会卡死

### ISSUE THREAD

**Issue by Leavesye** [ecomfe/echarts#2067]
![default](https://cloud.githubusercontent.com/assets/13026609/10127597/f96fe3f8-65d6-11e5-8b19-db4b6872012c.gif)

当我切换到环形图运行动画时页面就会卡死，目前发现在苹果Safari浏览器上会有此现象

**Comment by emksaz** [comment]
好像是内存泄露。

**Comment by emksaz** [comment]
画布内存泄露！

**Comment by emksaz** [comment]
如果这样的问题不能解决，echart是很难作为商业用途。

**Comment by zhump** [comment]
这种切换类型的 方法 是自己重新组织option ？还是echarts提供的方法？ 求解

**Comment by zhump** [comment]
这切换数据 是动态改变了 series里面的type ?还是echarts有支持的方法 我没发现？

**Comment by zhump** [comment]
看一下 控制台有没有错误信息。。。

**Comment by Leavesye** [comment]
控制台没有错误信息，切换数据是动态载入require实现的
