### ISSUE TITLE
echarts产品是否有审图号

### ISSUE THREAD

**Issue by seifer08ms** [ecomfe/echarts#2068]
如题，使用了echarts产品的网站是否存在相关风险？

**Comment by dachuanz** [comment]
我看了地图应用，底层调用百度地图，应该有风险也是百度了，

**Comment by seifer08ms** [comment]
echarts是可以结合百度地图，但也有不是啊。比如例子里面那种分省的地图，底图和百度底图没有关系，就是直接显示压缩好的geojson。

**Comment by stanleyxu2005** [comment]
echarts是百度公司的产品，应该有的审批应该都有。
不知道国外大部分国家有没有要图审号这些手续。

**Comment by pissang** [comment]
如果担心的话可以从 http://ecomfe.github.io/echarts-map-tool 下载最新的地图轮廓数据，这些数据是从地图产品中取到的
