### ISSUE TITLE
动态数据时，【暂无数据】的 动态泡泡 去不掉

### ISSUE THREAD

**Issue by WeiFei365** [ecomfe/echarts#2069]
开始实例化时，传入的 series=[{}]， 页面显示那个【暂无数据】的 动态泡泡；

之后数据有了，通过 .setSeries(series)，可以看到数据被绘制出来了，但是之前的 【暂无数据】的 动态泡泡 还依然在，并且覆盖在数据图的上面， 即使在 .setSeries(series) 之前，使用 .clear() 也解决不了；

请问，是操作不对还是就是这样的？

**Comment by WeiFei365** [comment]
自己测了一下，如果 series=[{}] ，echart会忽略所有的配置，所以，如果还使用当前实例的 .setSeries(series) , 之前所有的配置都会无效，而是应该使用 .setOption(option) 重新配置并设置数据进去；

**Comment by pissang** [comment]
可以使用 hideLoading

**Comment by stanleyxu2005** [comment]
@pissang 你说的是正解。
但有一个疑问，这个难道不应该在得到合法数据的时候，自动消除吗？

**Comment by WeiFei365** [comment]
@pissang 太棒了，thanks :+1: 

@stanleyxu2005 不过幸好还有这个.hideLoading()接口


针对上面第二个问题，也延伸出来一个小细节，就是在使用.setData(data)前，有必要提前执行一次.setOption(option)，因为数据的更新可能也伴随着坐标系、legend等的更新；又或者直接只使用一次.setOption(option)同时更新配置和数据

**Comment by stanleyxu2005** [comment]
@WeiFei365 如果出现loading气泡，其实options没有被初始化，所以当你有完整数据的时候，必须重新设置一次options的。这个我以前遇到过。https://github.com/stanleyxu2005/dashing/blob/master/src/charts/echarts.js#L104

**Comment by pissang** [comment]
@stanleyxu2005 之前是有一个 commit 改成了如果有数据就会消除当前的 loading 效果，但是后来考虑有些 loading 效果是开发者手动调用的，所以后来又把这个逻辑给去掉了，可能把这两种 loading 逻辑分开来会更好点。

**Comment by stanleyxu2005** [comment]
我的同事有一次跑来和我说，如果没数据的时候出现loading，感觉是chart坏掉了，而不是没有数据。在我们项目的使用场景里，一开始没有数据的时候，是用很多个0来填充整个chart。这其实与你们最终的解决方案不谋而合了，嘿嘿。
