### ISSUE TITLE
Is ECharts still live? 

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#2070]
There are not many commits in this repository anymore so I wonder whether ECharts is still live?

**Comment by carlvlewis** [comment]
@jarben: Not sure if the primary developers are accepting/rejecting pull requests, but from looking at their docs and marketing site, it's definitely still a living project.

**Comment by pissang** [comment]
Hi @jarben . Yes it's still alive. We are working on ECharts Next. So version 2.x is freezed and there will be no more commits.  ECharts Next will have more features with smaller file size. And it is much much more mobile friendly.

**Comment by jarben** [comment]
Hi @pissang Thanks for your reply, that certainly good to hear:) I've seen your examples around echarts next and it looks great. One question on my mind is whether the API will be compatible with 2.x or if it's complete rewrite including new API?

**Comment by pissang** [comment]
Method `setOption` and the **option**, which is the key concept in ECharts will compatible with 2.x. Still some configurations may change and we will give an detail explanation about what will change and benefits after changed. Most parts in **option** will keep the same.

And in addition, more methods and modules will be introduced for more convenient **extension** developing. In 2.x many developers have been complained about the difficulty when they wan't to develop some new charts based on the ECharts.

**Comment by infacq** [comment]
look forward for newer version. Hope it small in size

**Comment by stanleyxu2005** [comment]
@infacq You'd better customize an echart build with your own configuration. Strip all modules you do not need. And enable gzip at your server side. For instance, I use bar/line/pie only, my build is only 384kb. As a gzipped download, it is nearly 100kb, which is fairly small.
