### ISSUE TITLE
建议支持y轴刻度反转的功能

### ISSUE THREAD

**Issue by keyingkai** [ecomfe/echarts#2073]
比如说现在要显示一名学生排名的变化，如果按照普通方式，那么排名最差（值最大的）就会最高。这明显不合适。一般在excel 中都用y轴刻度反转实现这种功能，如图

http://i13.tietuku.com/038fc54c66bcc749.png
希望echarts也能支持y轴反转

**Comment by stanleyxu2005** [comment]
对于这种特殊的需求，你可以自己改写一下数据，如果你不需要有tooltip的话。比如说有的数值都x-1，然后定义一个y轴的valueFormatter，把所有的数值再次x-1

**Comment by zuoRambo** [comment]
这种需求确实挺重要的  修改数据的做法比较繁琐 需要将数值遍历取反 各处的formatter也得取反

**Comment by pissang** [comment]
新版本里将支持 inverse 配置刻度的翻转

**Comment by zuoRambo** [comment]
@pissang 多谢回复 最终使用-1 *的方式解决需求 另外有些数据从后台获取并不都是有效的 有的列是‘-’ 这种情况下取反运算就多了判断
