### ISSUE TITLE
Showing tool tip on Y-axis labels.

### ISSUE THREAD

**Issue by gopalakrishnanreddy** [ecomfe/echarts#2074]
Please help. How can i show tool tips on Y-axis labels

**Comment by suxuekun** [comment]
Y is category x is value then can

**Comment by suxuekun** [comment]
O sry ,you mean on label?

**Comment by gopalakrishnanreddy** [comment]
Yes, The labels , Need to show tool-tip on the axis labels when mouse hovered.

**Comment by gopalakrishnanreddy** [comment]
?

**Comment by stanleyxu2005** [comment]
Standard tooltip interface works for plot area only. I found the `axisLabel` can be `clickable`. Maybe you can hook the `onclick` event and do something. But I doubt it is not documented.

**Comment by udareaniket** [comment]
clickable event is working fine on the labels without any hiccups. Is it possible that we can make the tooltip interface to be visible on the axisLabel?
