### ISSUE TITLE
How I can draw this chart correct:)

### ISSUE THREAD

**Issue by vuongtran** [ecomfe/echarts#2075]
![admin dashboard](https://cloud.githubusercontent.com/assets/2321710/10365482/de1d6908-6ded-11e5-9d88-2d208acd8c3b.png)

Hi guys,
I draw my chart, but Y col look like not good. What solution help me fix it.

Thanks guy!

**Comment by stanleyxu2005** [comment]
Add more width for the left margin, like this
```
chart.getOption().grid.x = 150;
```
