### ISSUE TITLE
能否开发支持多轴显示的？

### ISSUE THREAD

**Issue by mmzhi** [ecomfe/echarts#2078]
看到你们之前的说法
> 是的，很多支持多轴，但我们认为多轴同时显示并不是一个好的设计，甚至双轴时就已经需要作出轴颜色和数据的明确相关性指示，否则就很容易产生误解，多轴并不易于对数据解读，所以我们限制了最多两条。

 > 而且就百度这5年多来业务系统对于数据可视化的需求来说，我们从未出现过多轴的要求，也没见过我们的项目有这样的设计，甚至双轴也是极小的出现。建议重新整理下看看真实的需求，轴并不是越多越好，我们也知道很多时候是甲方提的需求，但说实话，很多时候他们也是拍脑袋的，并不专业，甚至你为他实现后他才发现这很难用。

但是，我想说，可能是百度涉及的领域还是不够多，我司是专门针对影院做数据分析的，根据客户的需求，我们的确需要在很多地方表示多维度影院的数据，使用联动并不能达到所需效果，所以我想echarts确实需要多轴功能

**Comment by stanleyxu2005** [comment]
你可以先贴一个截图看看，你说的是什么样的多轴效果。
我最近看了一个研究，还还是有其他一些展示数据的方式的，比如：
![1](https://cloud.githubusercontent.com/assets/5162687/10393912/42dd986c-6ec6-11e5-965e-4993f9b47442.png)

**Comment by mmzhi** [comment]
比如下面这个图，以往的图，我们都是使用echarts的多图联动功能实现的，但是这个的话，客户强烈要求我们把所有数据放在一个坐标图上展示，没有办法，我们也只能用highcharts去改，满足支持多轴显示功能

<img width="926" alt="2015-10-09 8 48 54" src="https://cloud.githubusercontent.com/assets/1845381/10394156/c633cbfe-6ec7-11e5-853d-6bce0a0b807c.png">

**Comment by stanleyxu2005** [comment]
你可以考虑还是用双轴，然后接管label的formatter。
比方说左上角2根轴的数据，你可以显示成这样一个值`"60            30"`。
记得label好像不能用html方式写，可考虑换成等宽字体，然后中间填入填充空格。

**Comment by suxuekun** [comment]
完全可坐啊5个echart一个一列就OK了

**Comment by mmzhi** [comment]
这个方法可以，只是要预先处理一下一些数据问题，加上有选择区域显示，这个也不是一个小问题

**Comment by stanleyxu2005** [comment]
@mmzhi 这个已经是相当小的问题了... 
1. 不同axis的label变化是等比的，可以推算。
2. tooltip的也是支持的formatter，如果pointer设置成axis，你可以获得鼠标所在垂直线上所有数据点的值。

**Comment by pissang** [comment]
刚 @stanleyxu2005 在 #2315 中提到这个帖子，ECharts 3 里新加入了 [平行坐标轴](http://echarts.baidu.com/gallery/editor.html?c=parallel-aqi)，应该能满足多维数据的展现。
