### ISSUE TITLE
动态数据如何不打断原有动画？

### ISSUE THREAD

**Issue by dreampuf** [ecomfe/echarts#2084]
按照文档重新设置Option，但是会打断原来进行到一般的动画效果，体验很差。有改进方法吗？

    EC.setOption(ChartOption)

**Comment by stanleyxu2005** [comment]
如果你仅仅是添加数据，你应该使用`addData`的接口而非`setOption`。

**Comment by dreampuf** [comment]
@stanleyxu2005 你好，谢谢回复。
我需要修改比如 markPoints 这样的属性有办法吗？

**Comment by White-Jiang** [comment]
addMarkPoint
