### ISSUE TITLE
Label formatter 不能格式化内容，如换行，输入HTML标签

### ISSUE THREAD

**Issue by MichaelM193** [ecomfe/echarts#2087]
Label 上的文字内容， 没有办法控制换行， 以及格式化，输入HTML无法生效， 请问是否有方法解决。

**Comment by stanleyxu2005** [comment]
好像是开发者说，label是基于canvas的，不支持html，只支持换行`\n`

**Comment by MichaelM193** [comment]
多谢, 刚尝试了一下, 正如你所说, 可以支持 \n 换行.
