### ISSUE TITLE
当数据为空时，怎么让它出现气泡？

### ISSUE THREAD

**Issue by rongxh** [ecomfe/echarts#2089]
记得之前如果数据为空数组时，会出现气泡，但现在不行了，而且控制台还报错。

**Comment by pissang** [comment]
现在也有的，贴下 option 和错误

**Comment by WeiFei365** [comment]
传个空数据进去，比如：
```js
option.series = [{}]
```
数组至少有一个元素就是{}

**Comment by alenX** [comment]
应该是echart的版本问题，旧的版本对于空数据的情况可能没有处理，导入最新的http://echarts.baidu.com/build/dist/echarts-all.js
版本应该能够解决问题，我也遇到了这个问题已经解决
