### ISSUE TITLE
Text alignment in Legend

### ISSUE THREAD

**Issue by WinnieK** [ecomfe/echarts#2093]
Hello there.

Is there a way to place a text before legend item, not after? This is needed for RTL layout, if i can reverse the whole chart, but legend doesn't work this way. I've tried to use "align" options in textStyle, but doesn't seems to work.

Thanks

**Comment by pissang** [comment]
Sorry, text is on the left of item only if 'x' is set 'right'

**Comment by parsidev** [comment]
Hello.

I have this problem too,
![echarts](https://cloud.githubusercontent.com/assets/11275201/10936739/b06ffbc6-8303-11e5-80a4-fa0fbdc7f88a.png)

i using this option
```
legend: {
                                    data: ['میانگین دما', 'میانگین رطوبت'],
                                    textStyle: {
                                        align: 'right',
                                        baseline: 'middle',
                                        fontFamily: 'IRANSans'
                                    }
                                },
```

please help me solve this problem.

**Comment by 100pah** [comment]
Check [this sample](http://gallery.echartsjs.com/editor.html?c=xBy18IeDlg) please. Is it solve your problem?
