### ISSUE TITLE
Show Category Title within Bar

### ISSUE THREAD

**Issue by happschinson** [ecomfe/echarts#2096]
Hi!
If i have a simple inverted Bar Chart (y-axis: category, x-axis: value) - is it possible to show the Category names inside the bars?

**Comment by WeiFei365** [comment]
yes, you can; the series should be like this:

```js
series: [{
	name: '2011年',
	type: 'bar',
	data: [18203, 23489, 29034, 104970, 131744, 630230],
	itemStyle: {
		normal: {
			label: {
				show: true,
				position: 'right'
			}
		}
	}
}]
```

the **position** also can be: left right insideLeft insideRight OR top bottom insideTop insideBottom

**Comment by happschinson** [comment]
Hi WeiFei365,

thanks for your answer.
When I do this, the data value is being shown within the bars - not the category title.

**Comment by WeiFei365** [comment]
@happschinson 

oh, i am sorry; please set the formatter for itemStyle.normal.label, like this:

```js
series: [{
    name: '2011年',
    type: 'bar',
    data: [18203, 23489, 29034, 104970, 131744, 630230],
    itemStyle: {
        normal: {
            label: {
                show: true,
                position: 'right',
                formatter: function (params) {
                	return params.name;
                }
            }
        }
    }
}]
```

if you are not sure:
```js
return params.name
```
please:
```js
console.log(params)
```
and pick out something to return

Also, see here: [http://echarts.baidu.com/doc/doc.html#ItemStyle](http://echarts.baidu.com/doc/doc.html#ItemStyle)
