### ISSUE TITLE
Div 高和宽不能设100%?? 是Bug吗? 还是设错了

### ISSUE THREAD

**Issue by kennethhutw** [ecomfe/echarts#2099]
![2015-10-15_131330](https://cloud.githubusercontent.com/assets/11795929/10505319/aef87748-733e-11e5-954d-939e97433355.png)

<div id="container" style="width: 100%; height: 100%; margin: 0 auto">
<script type="text/javascript">
var myChart = echarts.init(document.getElementById('container')); 
var option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data:['利润', '支出', '收入']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'value'
        }
    ],
    yAxis : [
        {
            type : 'category',
            axisTick : {show: false},
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    series : [
        {
            name:'利润',
            type:'bar',
            itemStyle : { normal: {label : {show: true, position: 'inside'}}},
            data:[200, 170, 240, 244, 200, 220, 210]
        },
        {
            name:'收入',
            type:'bar',
            stack: '总量',
            barWidth : 5,
            itemStyle: {normal: {
                label : {show: true}
            }},
            data:[320, 302, 341, 374, 390, 450, 420]
        },
        {
            name:'支出',
            type:'bar',
            stack: '总量',
            itemStyle: {normal: {
                label : {show: true, position: 'left'}
            }},
            data:[-120, -132, -101, -134, -190, -230, -210]
        }
    ]
};
                    
 
   myChart.setOption(option); 

		</script>

**Comment by kennethhutw** [comment]
<div id="container" style="width: 100%; height: 100%; margin: 0 auto"></div>
 	<script type="text/javascript">
  var myChart = echarts.init(document.getElementById('container')); 
 var option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data:['利润', '支出', '收入']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'value'
        }
    ],
    yAxis : [
        {
            type : 'category',
            axisTick : {show: false},
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    series : [
        {
            name:'利润',
            type:'bar',
            itemStyle : { normal: {label : {show: true, position: 'inside'}}},
            data:[200, 170, 240, 244, 200, 220, 210]
        },
        {
            name:'收入',
            type:'bar',
            stack: '总量',
            barWidth : 5,
            itemStyle: {normal: {
                label : {show: true}
            }},
            data:[320, 302, 341, 374, 390, 450, 420]
        },
        {
            name:'支出',
            type:'bar',
            stack: '总量',
            itemStyle: {normal: {
                label : {show: true, position: 'left'}
            }},
            data:[-120, -132, -101, -134, -190, -230, -210]
        }
    ]
};
                    
 
   myChart.setOption(option); 

		</script>

**Comment by pissang** [comment]
你看下 div 的实际高度，应该是 0

**Comment by kennethhutw** [comment]
解决了 谢谢您的回答。 建议:错误解释应该精确点。

**Comment by yanglihuiylh102** [comment]
@kennethhutw 不是，你解决了能不能发一下你是怎么解决的，大家有类似的问题也可以互相学习一下啊
