### ISSUE TITLE
How can I highlight some data?

### ISSUE THREAD

**Issue by happschinson** [ecomfe/echarts#2104]
Hi!

Let's say I have some data in a bar chart: [10,20,25,26,30]

Is it possible, to highlight data "26" after the chart has been renderer? For example I click on a button "highlight" and then the bar of data 26 gets a red border around the bar?

thanks a lot guys!!

**Comment by WeiFei365** [comment]
oh, yes! try this:

```js
series: [{
	name: '2011年',
	type: 'bar',
	data: [18203, 23489, 29034, 104970, 131744, 630230],
	itemStyle: {
		normal: {},
		//highlight
		emphasis: {
			barBorderColor: 'red',
			barBorderWidth: 1
		}

	}
}]
```

Also, see here: [http://echarts.baidu.com/doc/doc.html#ItemStyle](http://echarts.baidu.com/doc/doc.html#ItemStyle)

this is not click, the click event will more complex
