### ISSUE TITLE
如何将动态数据放入图表或只更新单一数值呢?

### ISSUE THREAD

**Issue by kennethhutw** [ecomfe/echarts#2107]
我知道有chart.addData入口，但是我不想由上往下或由左往右的更新，只想动态的重新画数据或单一数据而不要全部重新刷新，如图我只想更新B的数据。请问要该怎麽做呢?
![2015-10-16_111150](https://cloud.githubusercontent.com/assets/11795929/10533005/c6fa30a8-73f6-11e5-9d58-1a45b396b456.png)

**Comment by kennethhutw** [comment]
pissang 为什麽closed呢? 没有回答我的问题吧

**Comment by pissang** [comment]
我记得之前有其它地方回答过这个问题，可能记错了，可以使用 setOption

**Comment by kennethhutw** [comment]
pissang谢谢回复,不过可否麻烦先告知，突然就被关掉而且一句话都没有，觉得很怪。 
另外我还未验证。 如果还不行，是否要再开一个问题呢?

SetOption 会让整个chart全部重划， 是否可以针对单一数据更新呢? 例如 G的Waiting Time.
