### ISSUE TITLE
Echarts柱状图没有数据的时候会显示气泡，通过配置可以将气泡去掉，只留下“暂无数据”文字吗

### ISSUE THREAD

**Issue by nextdream** [ecomfe/echarts#2116]
使用柱状图，传入的数据为空时，会显示“暂无数据”，背景带气泡。有什么办法可以去掉气泡，只留下文字

**Comment by nextdream** [comment]
![9](https://cloud.githubusercontent.com/assets/9672023/10597928/80042216-7726-11e5-8c4d-c5bd2a9067d6.jpg)

**Comment by WeiFei365** [comment]
:jack_o_lantern:  参见官网文档：[http://echarts.baidu.com/doc/doc.html#NoDataLoadingOption](http://echarts.baidu.com/doc/doc.html#NoDataLoadingOption) :
