### ISSUE TITLE
请问动态数据如何设置splitNumber

### ISSUE THREAD

**Issue by unsee** [ecomfe/echarts#2121]
在option中设定x轴的splitNumber后，发现动态加载数据时，x轴总是默认的10，请问还需要在别的地方设置参数吗？

**Comment by pissang** [comment]
问题描述再具体一点，比如 x 轴的配置项，我试了下没什么问题

**Comment by unsee** [comment]
配置项如下：


	  option = {
	                    tooltip: {
	                        show: true
	                    },
	                    legend: {
	                        data:['度量']
	                    },
	                    xAxis : [
	                        {
	                            type : 'category',

                           splitNumber:20,  //在此添加splitnumber

	                            boundaryGap : false,
	                             axisTick : {    // 轴标记
		                show:true,
		                length: 5,
		                lineStyle: {
		                    color: 'red',
		                    type: 'solid',
		                    width: 2
		                }
		            },
	                            data : ['0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0']
	                        }
	                    ],
	                    yAxis : [
	                        {
	                            type : 'value',
	                            length: 1,
	                        }
	                    ],
	                    series : [
	                        {
	                            "name":"销量",
	                            "type":"line",
	                            "data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	                        }
	                    ]
	                };


初始图像如下，可以分割成二十：
![1](https://cloud.githubusercontent.com/assets/6889278/10629023/e9afdc14-77fd-11e5-8559-2649247c2626.png)

使用myChart.addData( [[0,data,true,false,axisData]]) 加载数据，data为动态获取的数据，axisData是动态获取的x轴标记;
加载动态数据以后，就变成十了：
![2](https://cloud.githubusercontent.com/assets/6889278/10629027/f166cdd2-77fd-11e5-9728-65f8e52ddd04.png)
