### ISSUE TITLE
这种样式的图表用什么实现，K线图？

### ISSUE THREAD

**Issue by zhoulvming** [ecomfe/echarts#2122]
![GitHub Logo](http://a3.qpic.cn/psb?/V13ztlFs3DWfBa/5wK2bA31mNne7w40sKLL3qFjBr*3I.R2rrWXt7Tv.aM!/b/dGUAAAAAAAAA&bo=qgbEAAAAAAADB0o!&rf=viewer_4)
Format: ![Alt Text](url)

<img src="http://a3.qpic.cn/psb?/V13ztlFs3DWfBa/5wK2bA31mNne7w40sKLL3qFjBr*3I.R2rrWXt7Tv.aM!/b/dGUAAAAAAAAA&bo=qgbEAAAAAAADB0o!&rf=viewer_4">

**Comment by pissang** [comment]
可以用散点图

**Comment by zhoulvming** [comment]
非常感谢！
