### ISSUE TITLE
axisLabel过长被截断 以及 axisTick的interval为function时参数bug?

### ISSUE THREAD

**Issue by zenxds** [ecomfe/echarts#2124]
一个[标准条形图](http://echarts.baidu.com/doc/example/bar3.html)，如果左边的label过长会被截断，有没有什么办法能定制左边部分的宽度的

另外对于interval传function时，不太明白为什么第一次传入的index为－1，对应的第二个参数是undefined，这是bug还是feature？

**Comment by WeiFei365** [comment]
**关于label过长：**
* 举个极端例子，如果那个label是一本圣经，不截断还能怎么显示？而且，并不是截断，只是被挡住了；
* 针对label，EChart是提供配置来格式化的：[axis.axisLabel.formatter](http://echarts.baidu.com/doc/doc.html#AxisAxislabel) 函数返回任何你想显示的文本都可以
* 坐标部分的宽度是可以定制的：[grid.x](http://echarts.baidu.com/doc/doc.html#Grid)，用你提供的例子可以这样配置：
```js
option = {
	grid: {
		x: 150
	}
};
```

**关于interval：**
不知你说的是哪边配置的interval，默认为你说的是axis.axisLabel.interval，其他部分的可能类似，如下：
```js
/**
 * @description 刻度值标签的显示策略; 仅适用于axis.type=category; 0表示强制全部显示, 可选值：
 *              'auto': 自动判断, 会遵从'大吃小' 的策略，也就是长刻度值标签导致两侧标签隐藏
 *              N
 *              	比如N=1, 那么第1个显示,第2个不显示,第3个显示,第4个不显示....
 *              	再比如N=2, 那么第1个显示,第2个不显示,第3个不显示,第4个显示....
 *              	也就是说, 显示一个 间隔 N 个, 再显示一个
 *              function (index, data) {}
 *              	@param {Number} index 标签索引，即第几个标签
 *              	@param {Object} data
 *              	@return {Boolean}	决定是否显示当前标签
 * @type {Number | String | Function}
 */
interval: 0,
```

**Comment by zenxds** [comment]
@WeiFei365  

    yAxis: [
        {
            type : 'category',
            axisTick: {
       
                interval: function(index, item) {
                    // index第一次是-1 而item是undefined   
                }
            }
        }
    ]

**Comment by WeiFei365** [comment]
@zenxds 

同样是这个条形图：[http://echarts.baidu.com/doc/example/bar3.html#](http://echarts.baidu.com/doc/example/bar3.html#)，但是 数一数y轴的tick和label的个数，你会发现tick的个数比label多一个
