### ISSUE TITLE
矩形图点击区域数据下钻，除了面包屑有其他回到上级的方式么？

### ISSUE THREAD

**Issue by hustcer** [ecomfe/echarts#2128]
矩形图点击区域数据下钻，除了面包屑有其他回到上级的方式么？为什么不能再点击下回到上层呢？或者可以设置“单击下钻，双击上返”之类的，操作方便啊，通过导航条鼠标还要移动，虽然可以但是真心不方便。我觉得矩形图还可以好好完善下哈。辛苦了，谢谢

**Comment by pissang** [comment]
目前没有，如果要扩展控制方式只能自己去监听事件重新 setOption，新版本里会对treemap做优化，谢谢建议

**Comment by hustcer** [comment]
嗯嗯，好的，谢谢，敬候佳音 :+1:
