### ISSUE TITLE
require 与 百度fis,fisp插件mod.js中的require冲突

### ISSUE THREAD

**Issue by glone008** [ecomfe/echarts#2129]
这是fisp自带的js文件
{%html framework="common:static/mod.js" class="expanded"%}

与
    require.config({
        paths: {
            echarts: 'http://static.7hu.cn/common/echarts'
        }
    });
两者都定义了require。报错：
Uncaught TypeError: require.config is not a function
应该是被mod.js下的require覆盖了。

请问怎么解决

**Comment by rufushuang** [comment]
可以用echarts-all.js这种引入方式来回避
但如果真遇到了echarts-all里面没有的，又需要引入的echarts模块，那就比较烦，得自己抽代码

还是希望能够echarts自己的require包装在自己的域下
