### ISSUE TITLE
监听地图缩放事件，得到缩放比例

### ISSUE THREAD

**Issue by qinghechaoge** [ecomfe/echarts#2131]
现在项目有个需求，缩小到一定比例，就不显示地区名称了。
还有缩小到一定比例，地图标注出现了重叠，就要将标注聚合。

所以，我想知道如何监听缩放事件，得到当前比例，然后如何将标注聚合。大家没有这个需求吗？我觉得应该是通用的需求吧

**Comment by baixuexiyang** [comment]
使用MAP_ROAM事件监听

**Comment by qinghechaoge** [comment]
怎么得到当前缩放的比例呢

**Comment by jnie666** [comment]
georoam 事件

**Comment by Quintalq** [comment]
echarts 4.0 georoam事件 获取到的放大缩小比例一直是1.1

**Comment by lin-123** [comment]
@Quintalq  对， 放大时 zoom=1.1  缩小时 zoom=0.9； 没有显示当前zoom 到底是多少

**Comment by qyfang** [comment]
可以这样：通过监听georoam事件，后获取地图option里的zoom属性。
chart.on("georoam", function (params) {
  console.log(chart.getOption()["geo"][0]["zoom"]);
})
