### ISSUE TITLE
动态为echart加载数据无效

### ISSUE THREAD

**Issue by DanaLee15** [ecomfe/echarts#2135]
刚刚转web,前端的东西外观确实惊艳,但半路出家的我用起来很吃力。
根据官网example,静态给option赋值后加载没有问题，eg:
 <script src="~/Content/EChart/echarts-all.js" type="text/javascript"></script>
  <script type="text/javascript">
        function clickme() {
            var myChart = echarts.init(document.getElementById('main'));
            var startdate = $("#StartDate").val();
            var endate = $("#EndDate").val();
            var svalue = $("#valuelist").val();
            myChart.showLoading({
                text: '正在努力的读取数据中...'    //loading话术
            });
           
            var option = {"title":{"text":"测试json结构类","subtext":"cs"},"tooltip":{"trigger":"axis","showDelay":0},"legend":{"data"
:["上限","下限","平均值","测量值"]},"xAxis":[{"boundaryGap":false,"type":"category","data":["2015-10-26","2015-10-27"
,"2015-10-28","2015-10-29","2015-10-30","2015-10-31","2015-11-01"]}],"yAxis":[{"type":"value","axisLabel"
:{"formatter":"{value}em"}}],"series":[{"name":"上限","type":"line","data":[10,10,10,10,10,10,10],"markPoint"
:null,"markLine":{"data":[{"type":"max","name":"上限"}]}},{"name":"下限","type":"line","data":[-10,-10,-10
,-10,-10,-10,-10],"markPoint":null,"markLine":{"data":[{"type":"min","name":"下限"}]}},{"name":"基准值","type"
:"line","data":[4,4,4,4,4,4,4],"markPoint":null,"markLine":{"data":[{"type":"average","name":"标准值"}]
}}]};

            myChart.setOption(option);
            myChart.hideLoading();
           </script>
是ok的,但是引入ajax后,代码如下
  <script type="text/javascript">
        function clickme() {
            var myChart = echarts.init(document.getElementById('main'));
            var startdate = $("#StartDate").val();
            var endate = $("#EndDate").val();
            var svalue = $("#valuelist").val();
            myChart.showLoading({
                text: '正在努力的读取数据中...'    //loading话术
            });
            $.ajax({
                type: "post",
                url: '/RTDC/QAChart/GenerateChart',
                data: { 'StartDate': startdate, 'EndDate': endate, 'svalue': svalue },
                dataType: "text",
                success: function (result) {
                    var option = result;
                    myChart.setOption(option);
                    myChart.hideLoading();
                },
                error: function (msg) { alert(msg); }
            });
        }
    </script>
无法展示数据，我讲ajax的result复制出来,检查后保证是无误的，是不是我哪里配置不对？
SOS~~

**Comment by White-Jiang** [comment]
ajax代码贴一下

**Comment by ManigandanS** [comment]
I am also facing same problem, kindly help URGENT
