### ISSUE TITLE
yAxis的数据存在浮点误差

### ISSUE THREAD

**Issue by free421xiaobai** [ecomfe/echarts#2136]
给Echart的yAxis设置max = 8.2, min = 6.4, splitNumber = 9, 存在浮点误差。
见附件。
![chart bug](https://cloud.githubusercontent.com/assets/12934054/10722612/eaf7ea74-7bec-11e5-81bd-1339c3563299.png)

**Comment by pissang** [comment]
precision 或者 formatter 转一下
