### ISSUE TITLE
地图缩放比例和viewport

### ISSUE THREAD

**Issue by qinghechaoge** [ecomfe/echarts#2139]
监听MAP_ROAM事件时，如何得到当前地图的缩放比例？

打开地图时，能不能实现自定义比例，自定义显示的viewport

**Comment by qinghechaoge** [comment]
没人用过吗，得到地图当前缩放比例

**Comment by 95kg** [comment]
同问

**Comment by seefcn** [comment]
http://echarts.baidu.com/option.html#series-map.zoom
