### ISSUE TITLE
请问chord和弦图那一圈文字的颜色是否可以定制？

### ISSUE THREAD

**Issue by xcf007** [ecomfe/echarts#2142]
请问chord和弦图那一圈文字的颜色是否可以定制？
设置的label的color等都无效，也未找到相关文献说明。

我的需求想把一些文字设置灰色。

**Comment by WeiFei365** [comment]
EChart 文档官网：[http://echarts.baidu.com/doc/doc.html](http://echarts.baidu.com/doc/doc.html)，所有的参数、函数应有尽有

可以自定义文本样式，参见：[http://echarts.baidu.com/doc/doc.html#ItemStyle](http://echarts.baidu.com/doc/doc.html#ItemStyle)，配置类似：

```js
option = {
	series: [
		{
			itemStyle: {
				normal: {
					label: {
						textStyle: {
							color: 'red'
						}
					}
				}
			}
		}
	]
}
```

**Comment by xcf007** [comment]
非常感谢，重新替换最新的chordjs就好了。
