### ISSUE TITLE
请问柱状图，如何调整横轴数据的显示高度

### ISSUE THREAD

**Issue by nextdream** [ecomfe/echarts#2143]
![qq 20151027162942](https://cloud.githubusercontent.com/assets/9672023/10752844/c9b2c24a-7cc7-11e5-8289-73e5246348aa.png)
如图，当数据比较长的时候，就会显示不全，请问该怎么设置
![qq 20151027163314](https://cloud.githubusercontent.com/assets/9672023/10752928/5231f71c-7cc8-11e5-9b66-9f7c683301f3.png)

**Comment by WeiFei365** [comment]
EChart 文档官网：[http://echarts.baidu.com/doc/doc.html](http://echarts.baidu.com/doc/doc.html)，所有的参数、函数应有尽有

这个问题，可以自己 formatter 要显示什么，参见：[http://echarts.baidu.com/doc/doc.html#AxisAxislabel](http://echarts.baidu.com/doc/doc.html#AxisAxislabel)
