### ISSUE TITLE
使用 natural earth 生成的geoJson，缩放地图时报错

### ISSUE THREAD

**Issue by xorms** [ecomfe/echarts#2145]
通过 gdal 将 natural earth 的shapefiles 文件转换成 geoJson 文件。在使用时如果缩放地图，geo2pos方法会报脚本错，跟踪进去发现是第二参数undefined。但是那个geoJson文件我看过了，文件结构和文档演示用的结构一样。不知道是什么原因

**Comment by pissang** [comment]
能不能把 geoJson 文件发给我们看下？

**Comment by xorms** [comment]
我不知道怎么上传，放在网盘里了 http://pan.baidu.com/s/11Dk2y  这个是被 mapshaper.org/ 简化后的。
