### ISSUE TITLE
折线图、K图刷新残留数据 ！求解！！！求救！！！

### ISSUE THREAD

**Issue by haoran10** [ecomfe/echarts#2147]
操作步骤是这样的：
1、先加载一个折线图，并初始加载数据[1,2,3,4]  命名为A
2、动态的加载折线图A的数据[5]，这时为[1,2,3,4,5]
3、重新绘制折线图A, 重新加载数据[6,7,8,9]，
4、奇迹出现了，按理说这时已经是重新绘制了，数据应该只有[6,7,8,9]，但是却有[6,7,8,9,5]!!!

K线图也是这样，求解！！！求救！！！

**Comment by haoran10** [comment]
5、重新绘制后，如果不在动态添加数据，一直是[6,7,8,9,5]，这时动态添加数据[10]，就变成了[6,7,8,9,10]，百思不得其解！！！

**Comment by White-Jiang** [comment]
数组没清空吧

**Comment by pissang** [comment]
数组数据是会 merge 的，如果不想 merge 可以在 setOption 第二个参数传入 false

**Comment by haoran10** [comment]
realChart.setOption(optionChart,false);
这样做了，还是不行，还是有残余数据，

**Comment by haoran10** [comment]
实在不行，我就换highcharts了。。。

**Comment by haoran10** [comment]
换成highcharts真的好了！！！大神，关注下这个问题吧

**Comment by pissang** [comment]
说错了，第二个参数 notMerge 传入 true 才是不合并

**Comment by haoran10** [comment]
我去。。。我折腾半天，我试试，要是再不行，我就对echarts死心了

**Comment by haoran10** [comment]
true!!!算了，看在echarts中文文档多的情况下，我还是用它吧
