### ISSUE TITLE
有木有 sparkline 这样的品种？

### ISSUE THREAD

**Issue by hustcer** [ecomfe/echarts#2148]
有木有 sparkline 这样的品种？类似[这样](https://github.com/gwatts/jquery.sparkline)的，不过这个库已经很久没有更新了。虽然也够用了，不过没准儿你们可以开辟个新品种，甚至做得更有创意。只是个小小的提议哈，也可以无视。

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=line-easing
