### ISSUE TITLE
请问动态数据如何设置splitNumber(这次附上了代码和截图）

### ISSUE THREAD

**Issue by unsee** [ecomfe/echarts#2150]
在option中设定x轴的splitNumber后，发现动态加载数据时，x轴总是默认的10，请问还需要在别的地方设置参数吗？
配置项如下：

                          option = {
                    tooltip: {
                        show: true
                    },
                    legend: {
                        data:['度量']
                    },
                    xAxis : [
                        {
                            type : 'category',
                       splitNumber:20,  //在此添加splitnumber
                              boundaryGap : false,
                             axisTick : {    // 轴标记
                    show:true,
                    length: 5,
                    lineStyle: {
                        color: 'red',
                        type: 'solid',
                        width: 2
                    }
                },
                            data : ['0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0']
                        }
                    ],
                    yAxis : [
                        {
                            type : 'value',
                            length: 1,
                        }
                    ],
                    series : [
                        {
                            "name":"销量",
                            "type":"line",
                            "data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
                        }
                    ]
                };

初始图像如下，可以分割成二十：
![1](https://cloud.githubusercontent.com/assets/6889278/10808338/1eae8104-7e25-11e5-9a47-0f3ac057528f.png)

使用myChart.addData( [[0,data,true,false,axisData]]) 加载数据，data为动态获取的数据，axisData是动态获取的x轴标记;
加载动态数据以后，就变成十了：
![2](https://cloud.githubusercontent.com/assets/6889278/10808342/26e80606-7e25-11e5-9cce-50a9c0b02561.png)

**Comment by WeiFei365** [comment]
首先，还是要多看看官网的文档：[http://echarts.baidu.com/doc/doc.html#Axis](http://echarts.baidu.com/doc/doc.html#Axis)

查看以上文档后，发现 splitNumber **只支持数值型、时间型**，你上面的配置是```type=category```，所以这里 splitNumber 是没有起效果的，但是观察图片x轴是出来对应的刻度，这其实是你设置的```data=[.....]``` 的作用效果， 而 ```type=category``` 本来就是需要你传入 data 的，刻度的个数也是由 data 数组的长度决定的，再一次否定 splitNumber 的适用性；错觉

**Comment by unsee** [comment]
感谢您的回答，我再仔细看看文档

**Comment by pissang** [comment]
看下 addData 各个参数的意思
