### ISSUE TITLE
echart中饼图的label

### ISSUE THREAD

**Issue by turs** [ecomfe/echarts#2153]
饼图中的 label能插入图片吗？有例子 吗？
![default](https://cloud.githubusercontent.com/assets/7262606/10819507/7127e61a-7e83-11e5-8a16-02a796b9aa90.jpg)

**Comment by White-Jiang** [comment]
用formatter
例子：http://www.cnblogs.com/wwlhome/p/4643525.html

**Comment by turs** [comment]
![qq](https://cloud.githubusercontent.com/assets/7262606/10840672/8efa65fc-7f1c-11e5-979a-8a8a67274df4.jpg)

label里面的formatter好像识别不了html标签

**Comment by White-Jiang** [comment]
确实，而且label不支持异步回调
好像低版本可以，你试一下

**Comment by turs** [comment]
恩，我去试下。谢谢你的帮助
