### ISSUE TITLE
动态控制dataZoom

### ISSUE THREAD

**Issue by Pluto-Y** [ecomfe/echarts#2154]
我是在App中加载Echarts的控件，而我希望添加手势进行缩放，Echarts中有没有自带的是被App中的手势？或者有没有办法通过调用javascript来进行修改dataZoom的start和end?

```
function iosDataZoom(start, end) {
        option.dataZoom.start = start;
        option.dataZoom.end = end;
        myChart.setOption(option);
    }
```
同通过后期调用这个方法好像没办法设置成功？求解

**Comment by pissang** [comment]
可以调用 absoluteZoom 方法

**Comment by Pluto-Y** [comment]
怎么调用？有代码可以看一下吗？

**Comment by pissang** [comment]
doc 里搜索有说明

**Comment by Pluto-Y** [comment]
求网址，我找了你们官网这个文档，可是没有看到Example。

**Comment by Pluto-Y** [comment]
我又看到文档说明，可是没有看到代码调用。
我通过下面这个代码调用也是没用的：
```
option.dataZoom.absoluteZoom(0,100);
```

**Comment by pissang** [comment]
`myChart.component.dataZoom.absoluteZoom(0, 100)`
