### ISSUE TITLE
x轴type为time而不是category,tooltip不能沿着x轴移动，只能沿着y轴移动

### ISSUE THREAD

**Issue by chenyi** [ecomfe/echarts#2155]
我现在有一个时间序列的图表，横轴type设定为time，但是这样tooltip trigger: axis的配置，沿x轴移动无效，变成了沿y轴有效

修改配置或者升级版本能解决问题么

**Comment by pissang** [comment]
这是个问题，如果能用 category 轴尽量用 category 轴吧

**Comment by chenyi** [comment]
修改成category解决了。
