### ISSUE TITLE
地图点击区域触发蒙层弹窗，弹窗关闭后区域的选中色去不掉

### ISSUE THREAD

**Issue by yaneryou** [ecomfe/echarts#2156]
我的需求是地图点击（click）任一区域会弹出一个带蒙层的弹窗进行其他操作，但是弹窗关闭之后被点击选中的区域一直显示emphasis设置的颜色无法变回正常的颜色

**Comment by baixuexiyang** [comment]
可以在关闭弹窗之后执行refresh方法
