### ISSUE TITLE
echart bmap扩展，设置地图颜色为dark时，能否只显示中国地图文字，其他国家label不显示，就和默认背景时一样

### ISSUE THREAD

**Issue by pymkernal** [ecomfe/echarts#2161]
echart bmap扩展，设置地图颜色为dark时，能否只显示中国地图文字，其他国家label不显示，就和默认背景时一样

**Comment by 0312birdzhang** [comment]
背景是黑色的话x轴y轴地图等字体颜色也是黑的，不能自适应
版本：echarts 3
![qq 20170302153445](https://cloud.githubusercontent.com/assets/1762041/23497387/caee704a-ff5d-11e6-929e-26e990d609d8.png)
