### ISSUE TITLE
x轴和y轴  的颜色如何更换

### ISSUE THREAD

**Issue by dingquantracy** [ecomfe/echarts#2167]
柱状图的颜色和图表背景颜色都可以修改，但是目前没发现怎么修改两个轴的颜色

**Comment by baixuexiyang** [comment]
x轴(y轴同理)：
xAxis: [
  {
    type : 'category',
    data : [],
    splitLine: false,
    nameTextStyle: {
      color: '' // x坐标轴名称文字样式
    },
    axisLine: {
      lineStyle: {
        color: '' //坐标轴线颜色
      }
    }
  }
]

**Comment by qingniao99** [comment]
部分特殊的数据，要设置额外的颜色那种，在坐标轴上如何设置呢？

**Comment by Jasonlee6789** [comment]
还是没看到设置两个纵轴不同颜色的方案啊？
