### ISSUE TITLE
Several items with the same name in Pie charts

### ISSUE THREAD

**Issue by ningirsu** [ecomfe/echarts#2168]
Hi!
When I have the same label for several items in the charts, if I specify the color of an item, the color in the legends aren't updated.

See in this example:
![echarts_labels](https://cloud.githubusercontent.com/assets/7975575/11035645/f841042e-86f3-11e5-87bb-798b0bf3364b.png)

Thanks a lot guys!!

**Comment by pissang** [comment]
Because you have all the data same name?

**Comment by ningirsu** [comment]
Yes exactly, it's when all the data have the same name, that the legend aren't correctly updated.

Is it possible to have the same name and different colors ?

**Comment by voxivoid** [comment]
Did you manage to solve this problem?
