### ISSUE TITLE
echarts是否能实现如图的滑块效果

### ISSUE THREAD

**Issue by liuzl0218** [ecomfe/echarts#2170]
![qq 20151110160057](https://cloud.githubusercontent.com/assets/8954664/11057293/bca7612a-87c4-11e5-994f-1e8c420e0384.png)

如图，滑动滑块，左侧显示图例名称，右侧显示对应x轴的数值；单击滑块切换图例

**Comment by pissang** [comment]
没有这种组件，只能自己写

**Comment by liuzl0218** [comment]
如何实现，有没有什么思路可以借鉴？另外，你们是否有打算内置这种控件呢？
