### ISSUE TITLE
为什么echart在图表内的字体分辨率很低，很模糊啊

### ISSUE THREAD

**Issue by jxffly** [ecomfe/echarts#2179]
我通过火狐和chrome的对比发现echart的字体在chrome里面发毛边，很模糊，但是图形没有区别，就是字体，哪怕自己设置字体也很模糊，很影响用户体验

**Comment by jxffly** [comment]
撤销这个问题啊，发现问题了，不是echart的问题，当chrome被放大或者缩小后字体就变模糊了，哪怕很小的放大或者缩小比列，比如1-5%，都会出现字体模糊的现象

**Comment by webJing** [comment]
我这边没有缩放的情况下也是模糊的。字体和图表都模糊

**Comment by webJing** [comment]
echarts.init(document.getElementById(id),'', {devicePixelRatio:2});这样的配置可以解决，设置像素比为2
