### ISSUE TITLE
请问ECharts支持x坐标数据翻转吗

### ISSUE THREAD

**Issue by zhangangs** [ecomfe/echarts#2180]
比如说原来的数据是10-1、10-2、10-3
我想实现的10-3、10-2、10-1
请问这种可以实现吗？

**Comment by pissang** [comment]
2.x 中坐标轴翻转得 formatter 配合数据翻转实现，参照 http://echarts.baidu.com/doc/example/line6.html，马上发布的 3.0 中支持使用 `inverse` 配置坐标轴翻转
