### ISSUE TITLE
暂无数据后再设置数据，就会出现bug~~

### ISSUE THREAD

**Issue by mmzhi** [ecomfe/echarts#2182]
先设置一个没有数据的图，会出现有一暂无数据的气泡图
此时再设置数据，先clean，再setOption，图就出现问题了
<img width="519" alt="2015-11-13 7 21 00" src="https://cloud.githubusercontent.com/assets/1845381/11144985/30d776ba-8a3c-11e5-9c49-a0063e39a58b.png">

**Comment by jxffly** [comment]
这个我也发现了，就是空白图然后动态添加数据，loading的图会很诡异的出现

**Comment by pissang** [comment]
需要手动调用一次 hideLoading

**Comment by stanleyxu2005** [comment]
顺便看看xAxis是不是真的被初始化了。

**Comment by wzshuang** [comment]
虽然hideLoading解决了，但是感觉有点奇怪。因为程序并没有主动调用showLoading，echarts为什么不考虑在添加数据后自动去掉“暂无数据”呢

**Comment by JayYounger** [comment]
遇见同样的问题,也是柱状图有这个问题,折线图就没有这个问题,hideLoading可以解决.明显是Echarts问题,希望早日解决.
