### ISSUE TITLE
dataview 不能复制和编辑

### ISSUE THREAD

**Issue by sunlei99** [ecomfe/echarts#2186]
Hi, 我参照
http://echarts.baidu.com/doc/example/toolbox.html
中的例子重写了dataview的optionToContent函数，dataview显示的内容无法复制，为什么呢？
数据和示例中一样可以显示，但不能复制，以下为其他设置：
'dataView': {'show': true, 'readOnly': false, 'title': '详细数据'},

**Comment by pissang** [comment]
这个示例的 dataView 是自定义生成的 table，所以不能设置成可编辑

**Comment by alsotang** [comment]
我并不想编辑啊。。只想圈选然后复制而已。我看这个覆写之后的结果已经是 html 而非 svg 了，但无法圈选。

**Comment by pissang** [comment]
这个不能复制是因为我们为了防止交互导致的意外选中关闭了容器的 `user-select`

**Comment by alsotang** [comment]
那请问现在如果我要复制的话，怎么样比较方便实现呢？

我想在图表中插入一个 button，但没找到相关api，就想着用 dataview 展示出来之后让用户复制。。。结果却没法复制。。。

或者 echart 在 toolbox 那里有没有类似的【copy】property可以选择？让我们用户可以自定义复制的内容？

**Comment by alsotang** [comment]
对了，我是在弄饼图的东西

**Comment by pissang** [comment]
像默认放在 textarea 里还是可以复制的吧

**Comment by alsotang** [comment]
你指的 textarea 是？

**Comment by alsotang** [comment]
如果不覆写 optionToContent 的话，是可以复制的。不过结果需要自定义一些东西嘛

**Comment by pissang** [comment]
如果是覆盖了 optionToContent，也可以自己创建一个容器外的 div 存放内容，再把这个 div 放到容器的上方，就不会被容器的样式影响选择了，toolbox 也可以自定义按钮，你可以把自定义按钮的 icon 设成跟 dataView 一样的，这个方案跟 optionToContent 相比多的工作量就是 div 的定位

**Comment by alsotang** [comment]
就现在来说，有现成的方案吗...实现复制需求的话。
图表里面如何加 button 希望能指导一下。。

**Comment by alsotang** [comment]
晕。这个定位可不是简单的问题啊

**Comment by pissang** [comment]
用绝对定位就行了啊

**Comment by alsotang** [comment]
话说你们在使用的时候，数据导出一般是怎么做呢？

**Comment by alsotang** [comment]
你说的自定义 toolbox 是需要 hack api？我在 http://echarts.baidu.com/echarts2/doc/doc.html#Toolbox 没有看到类似的选项。

**Comment by pissang** [comment]
数据导出看业务需求，因为本身数据都是开发者给的

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/16408575/02ab5a7c-3d4c-11e6-9bc0-88ea84d57808.png)

现在我就是这样一幅图表。。。然后希望用户能方便地把数据复制出去。。。

**Comment by alsotang** [comment]
看来我是需要在图表之外加 button 了

**Comment by pissang** [comment]
不需要 hack api
```js
feature: {
    myTool1: {
        show: true,
        title: '自定义扩展方法1',
        icon: 'path://M17.5,17.3H33 M17.5,17.3H33 M45.4,29.5h-28 M11.5,2v56H51V14.8L38.4,2H11.5z M38.4,2.2v12.7H51 M45.4,41.7h-28',
        onclick: function (){
            alert('myToolHandler1')
        }
    }
}
```

**Comment by alsotang** [comment]
我试试这个自定义 toolbox

**Comment by pissang** [comment]
你用的还是 2 ？那 icon 还不支持 path，只能用 image://

**Comment by alsotang** [comment]
这个项目大概是3月这样成立的。。所以当时还是用2。。

**Comment by alsotang** [comment]
我试试更新3看看

**Comment by pissang** [comment]
嗯，只是饼图的话变动不大

**Comment by alsotang** [comment]
只是这个页面是饼图。。。其他还有地图。。。还有折线图。。。。

**Comment by alsotang** [comment]
方便给我一个 2 的那个 feature 写法吗？

**Comment by pissang** [comment]
一样的，只是 icon 只能写成 'image://url'

**Comment by alsotang** [comment]
icon可以跟 base64的图片。。。还行。。

![image](https://cloud.githubusercontent.com/assets/1147375/16408974/d0fec3ea-3d4d-11e6-8b71-4d656938a69a.png)

**Comment by alsotang** [comment]
我现在的解决方案是，利用自定义 toolbox 按钮，加上全局的 modal 来实现。

**Comment by isee15** [comment]
把table的user-select设置了一下，也能复制了
<style>
        table {
            user-select: all;
        }
    </style>
