### ISSUE TITLE
时间坐标(timeline)折线图不支持断线

### ISSUE THREAD

**Issue by fqtrnt** [ecomfe/echarts#2190]
在文档里提示到在折线图中，可以使用  '-' 作为折线的断开点．
经测试在一般的折线图里是正常的，但在时间坐标折线图中，
无法显示　'-'　标记为继开的点

使用的版本为：2.2.7

**Comment by pissang** [comment]
因为时间坐标跟数值坐标一样，是连续的

**Comment by fqtrnt** [comment]
谢谢回复。
现在的场景主要是在时间轴上显示对设备状态采样，可能在某个采样时间点采集不到状态，需要在图表里显示一个断线的形式。

不知是否有什么办法可以在数值坐标里模拟时间坐标图里的时间型的 X 轴的相关功能？

**Comment by pissang** [comment]
可以使用 category 轴

**Comment by pissang** [comment]
可以使用 category 轴
