### ISSUE TITLE
在图表左上方显示一条文本

### ISSUE THREAD

**Issue by lanyudhy** [ecomfe/echarts#2194]
在图表左上方显示一条文本，如果没有hover的话，那么显示的是最新的数据，如果hover的话，那么类似于toolTip那样动态更新文本中的数据字段。
      一张图表既有K线图，又有折线图，toolTip用作K线图的显示。
      希望能够提供一种实现能够在左上角固定显示一些数据。
@林峰
能否在实现上提供一点思路？

**Comment by pissang** [comment]
可以自己放一个 div
