### ISSUE TITLE
echarts与百度地图 添加数据问题

### ISSUE THREAD

**Issue by xiao321** [ecomfe/echarts#2196]
series : [
                {
                    name:'北京',
                    type:'map',
                    mapType: 'none',
                    data:[],
                   
                    markPoint : {
                        symbol:'emptyCircle',
                        symbolSize : function (v){
                            return 10 + v/10
                        },
                        effect : {
                            show: true,
                            shadowBlur : 0
                        },
                        itemStyle:{
                            normal:{
                                label:{show:false}
                            }
                        },
                        data : [
                            {name:'上海',value:95,geoCoord:[121.4648,31.2891]}
                            
                        ]
                    }

                }
                
            ]

{name:'上海',value:95,geoCoord:[121.4648,31.2891]}
这样添加提示错误Uncaught TypeError: Cannot read property '0' of undefined
但在控制台上这么写就没有问题
求解答？？？

**Comment by wandergis** [comment]
你遇到的这个bug我在自己扩展里面自己修复的，是添加点的问题

**Comment by xiao321** [comment]
怎么修复的？？？
