### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by snowdream** [ecomfe/echarts#2203]
我尝试在expressjs中使用echarts，遇到一个问题。
在这个地方 require.config({ 提示错误：
Uncaught ReferenceError: require is not defined

代码网址：

https://github.com/snowdream/node-echart-demo/blob/master/views/index.jade

**Comment by snowdream** [comment]
网页代码如下：
```html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!--Bootstrap-->
    <link rel="stylesheet" href="css/bootstrap.min.css"><br/>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <div class="jumbotron">
            <h1>Hello, world!</h1>
          </div>
        </div>
        <div class="col-md-2"></div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div id="main" style="height:400px"></div>
          <script type="text/javascript">
            // 路径配置
            require.config({
              paths: {
                echarts: 'http://echarts.baidu.com/build/dist'
              }
            });
            
            // 使用
            require(
                    [
                      'echarts',
                      'echarts/chart/bar' // 使用柱状图就加载bar模块，按需加载
                    ],
                    function (ec) {
                      // 基于准备好的dom，初始化echarts图表
                      var myChart = ec.init(document.getElementById('main'));
            
                      var option = {
                        tooltip: {
                          show: true
                        },
                        legend: {
                          data: ['销量']
                        },
                        xAxis: [
                          {
                            type: 'category',
                            data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
                          }
                        ],
                        yAxis: [
                          {
                            type: 'value'
                          }
                        ],
                        series: [
                          {
                            "name": "销量",
                            "type": "bar",
                            "data": [5, 20, 40, 10, 10, 20]
                          }
                        ]
                      };
            
                      // 为echarts对象加载数据
                      myChart.setOption(option);
                    }
            );
          </script>
        </div>
        <div class="col-md-4">col-md-4</div>
      </div>
    </div>
    <h1>4975820800</h1>
    <h1>Welcome to 12760236032</h1><br/>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins)-->
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed-->
    <script src="./js/bootstrap.min.js"></script>
    <!-- ECharts单文件引-->
    <script src="./js/echarts.js"></script>
  </body>
</html>
```

**Comment by pissang** [comment]
需要先 script 引入 echarts 才能 require

**Comment by snowdream** [comment]
感谢，已经搞定。

**Comment by songxiaoyuan** [comment]
我也遇到了同样的问题，将echarts.js下到本地然后配置，显示require is not defined。请问你是怎么解决的？

**Comment by songxiaoyuan** [comment]
<head>
	<meta charset="utf-8">
	<title>RelationShap</title>
</head>
<body>
	<script type="text/javascript" src ="./echarts.js"></script>
	<div id="picturePlace" style="width:985px;height:335px;"></div>
	
    <script type="text/javascript">
     // 路径配置
    require.config({
        paths: {
            echarts: './'
        }
    });

    // 使用
    require(
        [
            'echarts',
            'echarts/chart/force',
        ],
        function (ec) {
            // 基于准备好的dom，初始化echarts图表
            var myChart = ec.init(document.getElementById('main')); 
            
            option = {
                title : {
                    text: '人物关系：乔布斯',
                    subtext: '数据来自人立方',
                    x:'right',
                    y:'bottom'
                },
                tooltip : {
                    trigger: 'item',
                    formatter: '{a} : {b}'
                },
                toolbox: {
                    show : true,
                    feature : {
                        restore : {show: true},
                        magicType: {show: true, type: ['force', 'chord']},
                        saveAsImage : {show: true}
                    }
                },
                legend: {
                    x: 'left',
                    data:['家人','朋友']
                },
                series : [
                    {
                        type:'force',
                        name : "人物关系",
                        ribbonType: false,
                        categories : [
                            {
                                name: '人物'
                            },
                            {
                                name: '家人'
                            },
                            {
                                name:'朋友'
                            }
                        ],
                        itemStyle: {
                            normal: {
                                label: {
                                    show: true,
                                    textStyle: {
                                        color: '#333'
                                    }
                                },
                                nodeStyle : {
                                    brushType : 'both',
                                    borderColor : 'rgba(255,215,0,0.4)',
                                    borderWidth : 1
                                },
                                linkStyle: {
                                    type: 'curve'
                                }
                            },
                            emphasis: {
                                label: {
                                    show: false
                                    // textStyle: null      // 默认使用全局文本样式，详见TEXTSTYLE
                                },
                                nodeStyle : {
                                    //r: 30
                                },
                                linkStyle : {}
                            }
                        },
                        useWorker: false,
                        minRadius : 15,
                        maxRadius : 25,
                        gravity: 1.1,
                        scaling: 1.1,
                        roam: 'move',
                        nodes:[
                            {category:0, name: '乔布斯', value : 10, label: '乔布斯\n（主要）'},
                            {category:1, name: '丽萨-乔布斯',value : 2},
                            {category:1, name: '保罗-乔布斯',value : 3},
                            {category:1, name: '克拉拉-乔布斯',value : 3},
                            {category:1, name: '劳伦-鲍威尔',value : 7},
                            {category:2, name: '史蒂夫-沃兹尼艾克',value : 5},
                            {category:2, name: '奥巴马',value : 8},
                            {category:2, name: '比尔-盖茨',value : 9},
                            {category:2, name: '乔纳森-艾夫',value : 4},
                            {category:2, name: '蒂姆-库克',value : 4},
                            {category:2, name: '龙-韦恩',value : 1},
                        ],
                        links : [
                            {source : '丽萨-乔布斯', target : '乔布斯', weight : 1, name: '女儿'},
                            {source : '保罗-乔布斯', target : '乔布斯', weight : 2, name: '父亲'},
                            {source : '克拉拉-乔布斯', target : '乔布斯', weight : 1, name: '母亲'},
                            {source : '劳伦-鲍威尔', target : '乔布斯', weight : 2},
                            {source : '史蒂夫-沃兹尼艾克', target : '乔布斯', weight : 3, name: '合伙人'},
                            {source : '奥巴马', target : '乔布斯', weight : 1},
                            {source : '比尔-盖茨', target : '乔布斯', weight : 6, name: '竞争对手'},
                            {source : '乔纳森-艾夫', target : '乔布斯', weight : 1, name: '爱将'},
                            {source : '蒂姆-库克', target : '乔布斯', weight : 1},
                            {source : '龙-韦恩', target : '乔布斯', weight : 1},
                            {source : '克拉拉-乔布斯', target : '保罗-乔布斯', weight : 1},
                            {source : '奥巴马', target : '保罗-乔布斯', weight : 1},
                            {source : '奥巴马', target : '克拉拉-乔布斯', weight : 1},
                            {source : '奥巴马', target : '劳伦-鲍威尔', weight : 1},
                            {source : '奥巴马', target : '史蒂夫-沃兹尼艾克', weight : 1},
                            {source : '比尔-盖茨', target : '奥巴马', weight : 6},
                            {source : '比尔-盖茨', target : '克拉拉-乔布斯', weight : 1},
                            {source : '蒂姆-库克', target : '奥巴马', weight : 1}
                        ]
                    }
                ]
            };

            // 为echarts对象加载数据 
            myChart.setOption(option); 
        }
    );
    </script>
</body>

**Comment by ybx13579** [comment]
@songxiaoyuan 还记得怎么解决的吗？ 我这是本地的文件  报的这个错误

**Comment by SunerIvy** [comment]
遇到同样的问题，不知怎么解决
