### ISSUE TITLE
折线图被x轴遮挡住了

### ISSUE THREAD

**Issue by DebugFuture** [ecomfe/echarts#2208]
如下图所示，x轴上的线部分被遮住了（在不显示x轴的情况下是正常的）。看文档，轴的z默认值为0，series为2，我的理解是线应该在轴的上方。请问有什么解决方案吗？

<img width="583" alt="2015-11-25 20 15 55" src="https://cloud.githubusercontent.com/assets/8135834/11397056/6fcec41c-93b1-11e5-9146-69a64d95a02f.png">

**Comment by stanleyxu2005** [comment]
x轴的颜色用半透明。
