### ISSUE TITLE
target.className.match 报错

### ISSUE THREAD

**Issue by kuangche** [ecomfe/echarts#2211]
从一个绑定鼠标事件对象上 快速移动到 echarts图上的时候， 会报 t.className.match is not a function 这个错误，前面应该在加一层判断吧
var isZRenderElement = function (event) {
            // 暂时忽略 IE8-
            if (window.G_vmlCanvasManager) {
                return true;
            }

            event = event || window.event;

            // 进入对象优先~
            var target = event.toElement
                          || event.relatedTarget
                          || event.srcElement
                          || event.target;

            return target && target.className.match && target.className.match(config.elementClassName)
        };

靠谱么

**Comment by flyher** [comment]
这个问题的解决可以参考1楼的方案:
#2266
