### ISSUE TITLE
echarts  部分Android手机出现重影

### ISSUE THREAD

**Issue by xujbOvO** [ecomfe/echarts#2214]
调用了 echarts柱形图，首次正常，重绘出现重影。已经animation:false。去掉还是会出现。
魅族手机 Android4.3版本  qq中打开界面出现重影。 自带浏览器打开未出现。
小米手机 Android4.1版本，未出现重影情况。

**Comment by 947288229** [comment]
help /(ㄒoㄒ)/~~

**Comment by linmuxi** [comment]
关注

**Comment by fungchou** [comment]
echarts 3 中也遇到了。
红米手机 HM1SC，Android版本4.3 JLS36C。

![screenshot_2016-05-16-17-57-43](https://cloud.githubusercontent.com/assets/4269867/15286485/f117bf40-1b8f-11e6-9670-e0e67a5e14d8.png)

**Comment by pissang** [comment]
试试 http://blog.csdn.net/lufy_legend/article/details/17498837
