### ISSUE TITLE
建议map类型markline的label可以设置显示位置

### ISSUE THREAD

**Issue by cooppor** [ecomfe/echarts#2216]
如题，因为在使用过程中会出现多个点指向同一个点，如果不显示label数据不直观，看到不具体值，如果显示的话所有点挤在一起，什么也看不出来。如果可以设置label的位置，比如设置到中间，名者发出点之类的。

**Comment by momo898821** [comment]
貌似设置下label的position:'start'就可以了，其实就是变相的把label标注放到markline的起点位置了
