### ISSUE TITLE
饼图移动端出现点击A扇形，最后显示B扇形的label的情况

### ISSUE THREAD

**Issue by vencher** [ecomfe/echarts#2222]
饼图移动端出现点击A扇形，最后显示B扇形的label的情况，请问有人有解决方案吗？经过代码调试，发现是移动端的区域触发算法导致，区域触发算法为画一个矩形框，手指点击，先触发A扇形，再触发B扇形。最后显示为B扇形。（2.2.7）

**Comment by vencher** [comment]
@kener

**Comment by pissang** [comment]
试下 ECharts 3 里有没有这个问题

**Comment by vencher** [comment]
@pissang thank you ! 我去试试

**Comment by vencher** [comment]
@pissang 
hello,我下载了dev-3.0,有改善了,但是仍然出现点击的时候tooltip不显示的情况。我看了源码，不理解的是为什么不在扇形图触发tooltip，而要根据点击的位置重新计算显示tooltip。附件为出现问题的json数据。
[singlePie.txt](https://github.com/ecomfe/echarts/files/75380/singlePie.txt)

**Comment by pissang** [comment]
3.0 的 tooltip.position 可以设置为 `inside`，这样会在扇形的中间显示 tooltip

**Comment by pissang** [comment]
3.0 的 tooltip.position 可以设置为 `inside`，这样会在扇形的中间固定显示 tooltip

**Comment by vencher** [comment]
@pissang 
现在是因为算法计算tooltip显示内容时，定位触发区域不准确，先显示了A扇形信息，又接着显示B扇形信息，导致最终显示B扇形信息，而不是显示位置导致的问题。
triggerOn:'click'，  alwaysShowContent: true这个我没有试，我想triggerOn或许能有效果的，如果triggerOn触发的是被点击饼图的信息。
我先试一下这个属性，稍后有问题再请求您。谢谢。
