### ISSUE TITLE
[bug] Tooltip 当右侧宽度不够时会频繁切入

### ISSUE THREAD

**Issue by huguangju** [ecomfe/echarts#2225]
![untitled3](https://cloud.githubusercontent.com/assets/6972433/11554313/e5672072-99d1-11e5-9c68-14480a7cdbae.gif)

**Comment by stanleyxu2005** [comment]
是的，这个问题很烦人，不知道3.0修复了没有

**Comment by coolzjy** [comment]
修改 tip 的 enterable 为 true 可以解决掉

**Comment by stanleyxu2005** [comment]
@coolzjy 试过了，没什么区别。

**Comment by 273539918** [comment]
@coolzjy 有用，谢谢
