### ISSUE TITLE
Echarts3.0无比绚丽，最重要的是移动体验非常完美，太赞了，但……没有K线图了？

### ISSUE THREAD

**Issue by nilin2015** [ecomfe/echarts#2228]
今天得知3.0测试版出来了，马上体验了下
效果简直完美，尤其是移动版本的体验很好，这对我们很重要
而且移动趋势是大未来

但我们项目中有K线的使用，在DEMO中没看到K线图了，是没有了么还是在完善中？
无比关心和期待啊！

求回复！更感谢！
这么好的产品，简直为全世界互联网做出重大贡献！叩谢！

**Comment by nilin2015** [comment]
另外Echarts有捐赠入口么，这么好的产品实在让人忍不住要付费啊！

**Comment by xfworld** [comment]
http://echarts.baidu.com/related/blog/ec3new/ec3new.html

这个和echarts2兼容不....

终于支持移动端了.... V587

**Comment by nilin2015** [comment]
恩恩，移动端支持是超大福利

兼容估计得有相关配套设施辅助，不过Echarts团队肯定会考虑到的

**Comment by pissang** [comment]
折柱饼散点等的基础图表的配置项是兼容的，力导向图，地图等在 3 里面有了较大的改动，但是我们会在代码里加上预处理器把 2 的option 转成 3 支持的，改动最大的是方法调用的接口，原先是通过 `echarts.component.foo.doBar` 这种形式调用，入口很深，而且涉及到内部组件的组织。

所以在 3 里面都统一改成了
```
myChart.dispatchAction({
       type: 'legendToggleSelect',
       seriesName: 'xxxx'
})
```
这种形式，开发者只需要知道自己要 ECharts 做什么，并不需要关心接口在哪，怎么去调用。

因为博客篇幅有限，这些高级接口的用法我们都没说明，正式版的文档中会有更详细的阐述。到时候 [Gallery](http://echarts.baidu.com/gallery/) 里的示例也会有高级接口的使用示例和自定义图表开发的示例

**Comment by nilin2015** [comment]
谢回复，两个问题：
1、K线图应用还有么？
2、正式版元旦推出还是？

**Comment by pissang** [comment]
K 线图正版发布前会加上，正式版暂定元旦发布

**Comment by mo0feng** [comment]
非常棒！感谢在Echarts3中作出贡献的所有人~~~
