### ISSUE TITLE
漏斗图不能显示百分比

### ISSUE THREAD

**Issue by Lurkerc** [ecomfe/echarts#2231]
漏斗图不能显示百分比么？

效果图：
![image](https://cloud.githubusercontent.com/assets/11989045/11583891/d70c3c24-9a99-11e5-83e9-9c994a66ce51.png)

代码：
![image](https://cloud.githubusercontent.com/assets/11989045/11583967/8c7e4e3a-9a9a-11e5-84cd-100ffb6bd52d.png)

----------------------------------

大家知道这是怎么回事么

**Comment by momo898821** [comment]
+1  
饼图、雷达图、仪表盘、漏斗图: a（系列名称），b（数据项名称），c（数值）, d（饼图：百分比 | 雷达图：指标名称）
API中写的很清楚，但是漏斗图就是不能显示百分比，只能显示数值。

**Comment by whqet** [comment]
+1

饼图、雷达图、仪表盘、漏斗图: a（系列名称），b（数据项名称），c（数值）, d（饼图：百分比 | 雷达图：指标名称）
API中写的很清楚，但是漏斗图就是不能显示百分比，只能显示数值。

**Comment by chenlb** [comment]
+1
