### ISSUE TITLE
可否设置X轴Y轴的背景色？

### ISSUE THREAD

**Issue by ihuguowei** [ecomfe/echarts#2233]
我使用`axisLine.lineStyle.width`变相实现了该需求但是，在`X``Y`交汇处不是很理想。
设计稿要求：
![1](https://cloud.githubusercontent.com/assets/3097742/11612260/b68fb4ea-9c2d-11e5-8ac4-003eba1567b1.png)
而用我的方式实现
![qq 20151206152253](https://cloud.githubusercontent.com/assets/3097742/11612261/bbe14cce-9c2d-11e5-81e4-e458b5ea36d1.png)

**Comment by pissang** [comment]
不行

**Comment by ihuguowei** [comment]
@pissang 这是设置很大的结果。

**Comment by RicoLiu** [comment]
@ihuguowei 这个问题解决了嘛？
