### ISSUE TITLE
issue 貌似有点多，444个，都不处理吗？

### ISSUE THREAD

**Issue by luqin** [ecomfe/echarts#2236]
這么多的 issue，不知道到底是质量有问题还是？能否来个 roadmap？

**Comment by pissang** [comment]
现在大部分 issue 都是有回复的，其中部分提到的 bug 会在 3 里修复，到时候会统一 close

**Comment by luqin** [comment]
提 issue 时能不能统一加 前缀之类便于区分和查找？例如：https://github.com/facebook/react-native/issues

**Comment by luqin** [comment]
另外希望 github 上能多一些 英文文档，便于国外朋友使用

**Comment by pissang** [comment]
Github 上的文档链接都是英文版本的，issue 标题前缀我们很难约定其他人提的时候加前缀，更多的是我们自己在 issue 上加 tag

**Comment by luqin** [comment]
最好是给大家建议下，形成习惯
