### ISSUE TITLE
地图迁徙的问题

### ISSUE THREAD

**Issue by Galen-Yip** [ecomfe/echarts#2238]
麻烦看看，发现地图只有开始的地方到各个目的地这种方式，并没有第一个目的地，各个来源地这种方式？？
还是我看漏了。。?

**Comment by momo898821** [comment]
貌似只能把markline的data中两个地名调换才能实现聚拢的效果。。。

**Comment by Galen-Yip** [comment]
@momo898821 可是animate的箭头方向。。。。

**Comment by momo898821** [comment]
箭头都指向汇聚的那个点了。。。重叠也没辙

**Comment by Galen-Yip** [comment]
@momo898821 不是。。。是两个地名换过来之后，还是认为是发散的， 就是说并不会箭头汇聚。。。
