### ISSUE TITLE
Echarts的热力图直角坐标系

### ISSUE THREAD

**Issue by phoema** [ecomfe/echarts#2239]
您好，我想应用Echarts的热力图在直接坐标系中和散点图混搭显示，但是发现热力图的位置和散点图的位置并不重合，浅浅分析了一下，好像是热力图的坐标是地理坐标，目前我的坐标可能存在300,500这样的数值，请问我该如何使用同样的数据，将热力图和散点图在直角坐标系中混搭，感谢各位工程师的贡献。

**Comment by pissang** [comment]
3 里的热力图会支持直角坐标系

**Comment by phoema** [comment]
好的，谢谢，各位辛苦。

**Comment by phoema** [comment]
您好,下载了最新的3.0，看了http://echarts.baidu.com/gallery/editor.html?c=heatmap-map提供的两个例子，还是对于直角坐标系显示以前的热力图形式有些疑惑。
目前两个例子，一个是新型网格图，一个是地理热力图，我尝试将coordinateSystem: 'geo'替换成grid、catesian都没有成功。
请问有类似直角坐标系热力图的例子吗？
我的需求是将散点显示到直角坐标系上，将散点的二维数组补充成三维，作为热力图显示到直角坐标系上。

**Comment by pissang** [comment]
目前直角坐标系只支持网格形式的热力图

**Comment by phoema** [comment]
正式版会在支持直角坐标系的原2.0类型热力图吗？
另外热力图X、Y必须是category类型啊，如果与散点图共用数据混搭的话，其实X、Y是value更合适。
