### ISSUE TITLE
一个由<!DOCTYPE html>引起的奇怪BUG

### ISSUE THREAD

**Issue by Aaron1992** [ecomfe/echarts#2242]
在测试地图案例的时候，发现在html文件开头添加`<!DOCTYPE html>`就会引起
`Dom’s width & height should be ready before init`错误

之前出错调试了好久才发现这么奇怪的原因。
测试文件如下，当没有注释掉`<!DOCTYPE html>`时就会出错。

不知道为什么又碰到github的bug了，上传zip文件失败。。txt上传失败，衰。传到gist上了

https://gist.github.com/Aaron1992/9cb73316baec65863e70

**Comment by s332401890** [comment]
http://my.oschina.net/liangrockman/blog/8220 是不是这个的问题？

**Comment by pissang** [comment]
div 高度为 0，echarts 初始化的时候得保证容器高宽不为 0
