### ISSUE TITLE
bar类型的柱状图的tooltip顺序是反的

### ISSUE THREAD

**Issue by KevinKW** [ecomfe/echarts#2249]
在柱状图中有多个数据堆积，然后tooltip的列表和legend里面的顺序刚好相反，请问有没有配置项可以选择？

搜到了一篇文章http://www.oschina.net/question/2243452_172885，应该和这个是一个问题，下面有回复说是2.0.4版本中已修复，在2.0.4的ChangeLog中也找到下面说法，但是目前我们用的2.1.8版本中仍然有此问题。

[^] [line][bar]横向布局的堆积图表tooltip数据默认翻转，support this »

**Comment by stanleyxu2005** [comment]
自定义tooltip的formatter，自己处理。我没发现有什么问题。
