### ISSUE TITLE
xAxis type 设置为time 多series数据重叠

### ISSUE THREAD

**Issue by lvdougongjue** [ecomfe/echarts#2250]
柱状图
xAxis type 设置为time 
多series数据重叠，而不是像普通柱状图每个series在同一个时间点有多个并列的图，而是都在一个位置上，数值大的就覆盖了数值小的。

**Comment by pissang** [comment]
柱状图表示的是类目数据，推荐使用 category 作为 x 轴，time 轴是连续的，更适合折线（趋势）图。
