### ISSUE TITLE
android 4.3兼容问题

### ISSUE THREAD

**Issue by dujiliangacd** [ecomfe/echarts#2251]
1、echarts-m-1.0.0纵轴数据显示在内侧，可有什么方式可以现在在外侧？
2、android 4.3以下部分机型会有重影，可有什么修复办法？

**Comment by brucecham** [comment]
@pissang    在红米  4.2.系统里面，拖动滚动条，图表新渲染出来的数据会与老数据重叠，滚动条拖动也很卡

**Comment by pissang** [comment]
用的 echarts 3？

**Comment by brucecham** [comment]
刚知道有个echarts3，明天试用下，目前是echarts-m-1.0.0

**Comment by dujiliangacd** [comment]
@pissang echarts3饼图怎么渲染有问题？可有什么解决方式
![image](https://cloud.githubusercontent.com/assets/5093740/12188987/1a1cb1a8-b5f5-11e5-9951-e35ff73f2038.png)

**Comment by pissang** [comment]
@dujiliangacd 能描述下问题的环境和如何复现么？

**Comment by dujiliangacd** [comment]
@pissang  
![image](https://cloud.githubusercontent.com/assets/5093740/12253288/d22ce494-b919-11e5-9937-58b3fe218a4e.png)
![image](https://cloud.githubusercontent.com/assets/5093740/12253298/e2aae3de-b919-11e5-9bcf-53c73851f305.png)
你优化后，饼图是出来了，不过legend 色块没有出来，还要修改下

**Comment by dujiliangacd** [comment]
BUG
![image](https://cloud.githubusercontent.com/assets/5093740/12256925/b8b0aa5a-b93c-11e5-9147-f1d4472b7e49.png)
![image](https://cloud.githubusercontent.com/assets/5093740/12256936/ca6f0b92-b93c-11e5-93a7-6793dc4fd6c3.png)
饼图data中，中间如果有其中一项值为0，tip提示错误，始终是0的哪项提示

**Comment by pissang** [comment]
谢谢反馈，应该是个 bug
