### ISSUE TITLE
多图例的折线图，数值少的折线会显示为灰点

### ISSUE THREAD

**Issue by bi-kai** [ecomfe/echarts#2253]
一个折线图中包含2个折线，比如第一条包含10个点，第二条包含2个点，那第二条的后8个位置会显示为灰点，这样合理么？类似于这样：
```js
xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],

...

 series : [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10]
        },
        {
            name:'最低气温',
            type:'line',
            data:[1, -2]
        }
    ]
```

**Comment by s332401890** [comment]
series : [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10]
        },
        {
            name:'最低气温',
            type:'line',
            data:[1, -2,'-','-','-','-','-']
           
        }
    ]
