### ISSUE TITLE
怎样能让饼图选中的时候缓慢的出来

### ISSUE THREAD

**Issue by lusiyong** [ecomfe/echarts#2256]
怎样能让饼图选中的时候缓慢的出来，能有一个类似于动画的效果，现在的效果太生硬。

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=pie-simple 3 中的饼图有选中的动画效果，同时还有 hover 的动画

**Comment by lusiyong** [comment]
好的，谢谢楼上，不过咨询下，这个也是免费的吗？

**Comment by pissang** [comment]
这个是 ECharts 3，授权跟 2 一样是免费的
