### ISSUE TITLE
English Translation of Read.Me or Wiki?

### ISSUE THREAD

**Issue by CreativelyMe** [ecomfe/echarts#2260]
I could use an English translation for the Read.Me. 

Do you have plans to provide an English Translation of the Read.me or build out the Wiki?

Please let me know if I can help.

Great job on eCharts

Thanks Joe(Creatively.Me)

**Comment by pissang** [comment]
The content of README is same with http://echarts.baidu.com/doc/feature-en.html

**Comment by CreativelyMe** [comment]
Yi Shen:

I understand and will close ticket if it is not closed.  (Allow me to suggest
that you provide that bit of information at the top of the read me)

English Translation available here or something like that.

> 
>     http://echarts.baidu.com/doc/feature-en.html
> 

If I can help, let me know.

Thank you

Joe (Creatively.Me)
