### ISSUE TITLE
饼图的中间位置怎么放总数

### ISSUE THREAD

**Issue by baiyygynui** [ecomfe/echarts#2262]
公司要的一个数据的总和，里面有三个值，打算用饼图，三个值分别的数量用饼图的环来显示，但是需要在环中间放三个值的总和，要怎么实现，谢谢

**Comment by stanleyxu2005** [comment]
通过series[0].data传入。我之前做过，但有点忘记了。https://github.com/stanleyxu2005/dashing/blob/master/src/charts/ring.js#L109
[Demo](http://mmjd.com/dashing/examples/#/charts/ring)

**Comment by pissang** [comment]
可以用 formatter
