### ISSUE TITLE
Data Zoom的缩略图是不是和数据不同步的？

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#2264]
我的数据源有大概100根柱子，数字都是10，但你datazoom里面阴影处，感觉山峰连绵起伏。

![untitled](https://cloud.githubusercontent.com/assets/5162687/11774220/bef9e6d2-a26d-11e5-805e-11d9ccc6358f.png)

我的datazoom的option里面，`realtime=true`

**Comment by pissang** [comment]
3 还是 2？我试了下都没这个问题。具体配置项是什么？

**Comment by stanleyxu2005** [comment]
我用的是2.2.7。配置项稍后奉上。

**Comment by stanleyxu2005** [comment]
Seems to be my problem. Sorry.
