### ISSUE TITLE
mix-zoom-on-value 左右移动时候 柱状图底部会超出X轴。

### ISSUE THREAD

**Issue by tvcg** [ecomfe/echarts#2270]
mix-zoom-on-value 左右移动时候 柱状图底部会超出X轴。
![mix-zoom-on-value](https://cloud.githubusercontent.com/assets/11804401/11829157/7397cc72-a3d5-11e5-86cb-16f84f5cbf7f.jpg)

**Comment by pissang** [comment]
这个问题已经修复了
