### ISSUE TITLE
dataZoom中showDetail显示的字体颜色是否可以改变？

### ISSUE THREAD

**Issue by tvcg** [ecomfe/echarts#2272]
dataZoom中showDetail显示的字体颜色是否可以改变？
如下图，字体黑色看不清。
![qq 20151216145519](https://cloud.githubusercontent.com/assets/11804401/11834219/38e46704-a405-11e5-9e24-1ac81dd2aee6.jpg)

**Comment by pissang** [comment]
2 里面不行，3.0 里可以使用 textStyle 配置颜色
