### ISSUE TITLE
折线图有断点能不能连接上

### ISSUE THREAD

**Issue by discovery10** [ecomfe/echarts#2275]
参考echarts的文档，当对应的数据不存在时，可以使用'-'进行代替，但是折线图中会出现断点，能不能让两点之间连接起来，不用出现断点，可以实现吗？

**Comment by pissang** [comment]
补数据，空数据就是不绘制的

**Comment by discovery10** [comment]
嗯，这个方法是好，用' '这样的空白字符串可以解决，但有一个问题就是没数据的地方会有小圆点，给人看起来像是有数据的一样。
