### ISSUE TITLE
echart 3.0直角坐标系grid的部分参数无效

### ISSUE THREAD

**Issue by fightKen** [ecomfe/echarts#2276]
如题，echart 3.0直角坐标系grid的backgroundColor和borderColor都没有效果？还有就是移动端设置datazoom的start和end无效？无论设置多少都是全部显示，我想试一下手势拖动和缩放，求指教

**Comment by pissang** [comment]
3 里默认关闭了 grid 的显示，需要设置 `show:true`

**Comment by fightKen** [comment]
好的，我刚测试了一下，是自己的失误。谢谢
