### ISSUE TITLE
Echarts散点图值域漫游

### ISSUE THREAD

**Issue by phoema** [ecomfe/echarts#2279]
关于值域漫游，我目前想使用这个功能进行根据散点的自定义属性如重要程度：高中低进行散点图上散点的颜色渲染；不依赖于数值；
请问我可以基于某些字符串数组[高：红色；中：黄色；低：绿色]使用值域漫游进行散点颜色渲染吗？如果不可以，有其他替代方案吗？

**Comment by phoema** [comment]
例如：Echarts3.0的散点示例中提供的数据： 
[3,83,60,84,1.09,73,27,"良"],
  [4,109,81,121,1.28,68,51,"轻度污染"],
dataRange功能是否可以使用源数据中的["良","轻度污染"]这一列作为过滤数据，进行颜色的显示？

**Comment by pissang** [comment]
dataRange 支持类目数据，具体参考 https://github.com/ecomfe/echarts/blob/dev-3.0.0/test/symbol-categories.html#L154，这个示例，这个例子里不同类目使用不同的 `symbol` 表示，你可以把 `symbol` 换成 `color`，例如

```js
dataRange: {
    inRange: {
        color: {
             {高': 'red', '中': 'blue', '低': 'red'}
        }
    }
}

当然这些只有在 3.0 里才支持

**Comment by phoema** [comment]
谢谢，我那个页面是黑的，没看到效果，我调整一下。

**Comment by phoema** [comment]
我调整后，感觉示例代码缺少一点东西似的，
好像没有发现示例代码里针对categories指定到源数据第8列的代码啊？
categories: ['优', '良', '轻度污染', '中度污染', '重度污染', '严重污染'],和源数据数组对应列的对应关系，导致颜色设置不起效果，结果都是绿色，

                            categories: ['优', '良', '轻度污染', '中度污染', '重度污染', '严重污染'],
                            calculable: true,
                            precision: 0.1,
                            textStyle: {
                                color: '#fff'
                            },
                            inRange: {
                                symbolSize: 30,
                                color: {
                                    '优': 'green',
                                    '重度污染': 'red',
                                    '': 'yellow'
                                }
                            },
                            outOfRange: {
                                //color: '#000',
                                symbolSize: 30,
                                color: {
                                    '优': 'green',
                                    '重度污染': 'red',
                                    '': 'yellow'
                                }
                            },

源数据：[1,55,9,56,0.46,18,6,"良"]

可能问题出在：https://github.com/ecomfe/echarts/blob/dev-3.0.0/src/chart/helper/createListFromArray.js
第51行：return val && +val[dimIndex];
针对测试数组到第8列非数字的情况下，一律返回NaN

**Comment by pissang** [comment]
dataRange 能指定 dimension 为 8

**Comment by phoema** [comment]
可能问题出在：https://github.com/ecomfe/echarts/blob/dev-3.0.0/src/chart/helper/createListFromArray.js
第51行：return val && +val[dimIndex];
针对测试数组到第8列非数字的情况下，一律返回NaN

**Comment by pissang** [comment]
谢谢，新代码中 fix 了。
