### ISSUE TITLE
支持复杂Gantt图

### ISSUE THREAD

**Issue by acaleph** [ecomfe/echarts#228]
![gantt](https://f.cloud.github.com/assets/1111830/2318513/5ed2100e-a369-11e3-917b-12bb8449b074.png)
echarts提供的图示中虽然可以完成简单的GANTT图，但对于复杂的GANTT图，就有些力不从心：
1）Y轴的数据有多项，且分组。
2）X轴为时间轴时，也需要分组：日期和每天时间分组
希望echarts团队能够尽快给予支持。

**Comment by sunchenguang** [comment]
?? 为什么直接关了？

**Comment by Ovilia** [comment]
@sunchenguang 没有计划支持甘特图，自己可以通过这种方式使用：http://gallery.echartsjs.com/editor.html?c=bar-waterfall2 当然，如果给我们提 PR 的话，是非常欢迎的~
