### ISSUE TITLE
不显示axisLabel，图表的高度可否调整

### ISSUE THREAD

**Issue by lanyudhy** [ecomfe/echarts#2281]
在显示图表时，横坐标的axisLabel设置为show:false，横坐标label所占的空间能否被释放，空出的高度应用在图表显示上？
       如果没有办法通过配置来实现，那么可否提供方向？
       @林峰

**Comment by stanleyxu2005** [comment]
可以grid: {y: ..., y2: ...}

**Comment by lanyudhy** [comment]
Oh，是的，3Q
