### ISSUE TITLE
请问src\util\mapData\geoJson下的地图JS是怎么生成的？

### ISSUE THREAD

**Issue by glpyh** [ecomfe/echarts#2282]
src\util\mapData\geoJson这下生成了全国市级的geoJosn的js，现在需要到县级的。请问是怎么生成的呢。。用了官网中提供的生成工具，但是，生成的是加密的json，不是js，谢谢。

**Comment by rodgeryuan163com** [comment]
根据官网提供的js文件，把生成的内容替换里面对应的内容，其实json就是一个js的object，替换一下，改个名字就可以用了。
