### ISSUE TITLE
Firefox下,至少两天长时间展示echarts并动态刷新数据内存崩溃问题.

### ISSUE THREAD

**Issue by jiawenjun1126** [ecomfe/echarts#2283]
Firefox下,至少两天长时间展示echarts并动态刷新数据内存崩溃问题.
有同胞们遇到这个问题吗?内存飙升,不释放,并且浏览器会自动死掉.
有没有好的结局方案?
执行clear,dispose没有效果,是哪执行的不对吗?
采用setSeries(obj,false);方式重新设计数据然后,refresh刷新图表.

**Comment by stanleyxu2005** [comment]
你有没有设置最多显示的点数？有个dataGrow设置成false可以限制一个chart画点的上限。我这边3秒画一个点，开个3-5天毫无压力。

**Comment by zqbxrambo** [comment]
我也遇到这种情况，一直没有解决，不知道楼主是否已经解决此问题？clear，dispose并没有作用

**Comment by stanleyxu2005** [comment]
你要打开chrome或者firefox调试的，看看Event Listener什么的，看看是不是越来越多的listener。

**Comment by tangniye** [comment]
楼主有没有解决这个问题呢？我现在也遇到了

**Comment by guolililili** [comment]
同问此问题
