### ISSUE TITLE
强烈建议加一个 echarts._require 方法

### ISSUE THREAD

**Issue by suwenxiong** [ecomfe/echarts#2296]
项目中某些功能用zrender二次开发了,但项目本身没有用requirejs加载,导致无法使用 require("zrender/shape/Circle")等功能

建议在echarts里面加一个接口方法比如echarts._require 调用模块

我现在这样改的
 var zrender = require('zrender');
zrender.tool = {
    color : require('zrender/tool/color'),
    math : require('zrender/tool/math'),
    util : require('zrender/tool/util'),
    vector : require('zrender/tool/vector'),
    area : require('zrender/tool/area'),
    event : require('zrender/tool/event'),
    require:require
}

在原有基础上加了一个require方法

每次调用功能只需要用 zrender.tool.require("moudleName")就行

**Comment by luqin** [comment]
用 webpack 构建吧

**Comment by naranakula** [comment]
还没改 这帮人！@
