### ISSUE TITLE
IE8 下背景色可以透明显示吗？

### ISSUE THREAD

**Issue by CoolView** [ecomfe/echarts#2297]
官方文档 默认是透明backgroundColor: 'rgba(0,0,0,0)'，但在IE8及以下版本背景是白色

**Comment by stanleyxu2005** [comment]
可以啊

http://blog.sina.com.cn/s/blog_74e0b8290100tza6.html
opacity: 0.0;
filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0); 
-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(opacity=0)";

**Comment by CoolView** [comment]
谢谢，但这样整个图都会透明

**Comment by pissang** [comment]
可以试下在图的容器下面放一层 div 显示背景色
