### ISSUE TITLE
iframe下嵌套的图表无法显示，all.js中报错Cannot call method 'showLoading' of undefined 

### ISSUE THREAD

**Issue by hzhtracy** [ecomfe/echarts#2298]
用的是jsp，单独一张jsp下图表显示正确，但将该jsp嵌套在另外的jsp的iframe中后，图表无法显示，而且all.js中报错Cannot call method 'showLoading' of undefined 。到底是哪里错了，跪求大神解答

**Comment by orange1438** [comment]
请问你解决了吗？我也是jsp里iframe中使用了echart

**Comment by orange1438** [comment]
请问你解决了吗？我也是jsp里iframe中使用了echart
