### ISSUE TITLE
k线图上叠加均线图

### ISSUE THREAD

**Issue by bagusflyer** [ecomfe/echarts#2302]
刚刚接触echarts，有两个问题想请教一下：
1. 能否在k线图上叠加多个均线图，比如5日均线，30日均线，60日均线等？
2. echarts是否有自动的均线图，还是要自己根据算法来画？

麻烦能提供一些指导。谢谢。

另外，有无计划将echarts加到npm和bower中？

**Comment by luqin** [comment]
没有计划 :sob: ，  [![NPM](https://nodei.co/npm/echarts.png?downloads=true&stars=true)](https://nodei.co/npm/echarts/)

**Comment by pissang** [comment]
3.0 正式版发布后我们会发到 npm 上，届时望 @luqin 能够把现在的 echarts 名字转回给我们。
