### ISSUE TITLE
右上角添加自定义tips

### ISSUE THREAD

**Issue by cpaull** [ecomfe/echarts#2303]
我想在每一个图表的右上角（toolbox的地方）添加一个tips，鼠标放上去或者点击可以显示一些提示信息，请问echarts支持吗？
另外，我希望有一个tips支持编辑，然后每个人都可以在里面编辑内容，将内容保存到数据库。这样每个人都可以看到其他人的备注或留言，请问echarts支持实现这个吗？
谢谢。

**Comment by pissang** [comment]
可以自己扩展
