### ISSUE TITLE
条状图其中一条数据为0的时候也能显示为barMinHeight的高度嘛

### ISSUE THREAD

**Issue by xfanz** [ecomfe/echarts#2306]
现状是条状图的一条数据为0的时候就消失了，现在也期望显示为barMinHeight的高度，
支持嘛？

**Comment by stanleyxu2005** [comment]
你试试看yAxis[0].boundaryGap[-0.5, 之类的东西

**Comment by xfanz** [comment]
看起来没啥效果

**Comment by pissang** [comment]
3.0 最新代码中不存在这个问题。

**Comment by stanleyxu2005** [comment]
@pissang 因为2.0和3.0的option选项不是非常兼容，而且现在文档也不知道在哪里。所以要大胆的迁移到3.0开发分支，对我来说会有不小风险。我一直在等3.0能比较好的支持time为x轴的数据，一方面是不必让数据等间隔了，另外一方面是现在的x轴在处理已经转换成string的时间显然不够智能。更确切的说，我已经有点抓狂了。如果能像Rickshaw或者Highchart那么智能，那就爽了。

下面是一张目前用2.2.7版echarts的截图，可以明显看见右侧label被切掉了一半，然后其实我只想显示整数分钟时候的label，而不是00:37:15之类的时间。用string做xlabel要过滤好这个，不太容易。我知道可以自定义xlabelformatter，但如果传入的是时间，而非string，echart肯定可以处理的很智能，我相信! （如有需要，我可以独立开一个问题描述）

![1](https://cloud.githubusercontent.com/assets/5162687/12121079/65a06180-b40e-11e5-87c3-c1f63dc92271.png)

**Comment by pissang** [comment]
新开一个问题描述时间轴相关的问题吧，谢谢，3.0 文档的话不出意外会在下周放出来。
