### ISSUE TITLE
bar之间的距离怎么设置呢？

### ISSUE THREAD

**Issue by liuyanlei** [ecomfe/echarts#2311]
如下图所示，我想让两个series之间的距离贴到一起，类似分组的概念，能实现吗？

![image](https://cloud.githubusercontent.com/assets/8318737/12031994/386237ae-ae4e-11e5-8c73-f2fe52d578e1.png)

**Comment by liuyanlei** [comment]
设置 barGap 和 barCategoryGap 为0 之后是
![image](https://cloud.githubusercontent.com/assets/8318737/12033628/fcccf71c-ae5f-11e5-8574-8e2fe0a95c78.png)
这种效果 感觉在一起的柱状图正好是反了。

**Comment by stanleyxu2005** [comment]
(*sorry cannot type in chinese now*)

The `barGap` seems to be calculated automatically. 
I've found a way by reducing the bar area width. 
E.g. you want `barWidth=10` and `barGap=2`, then `chartPlotAreaWidth = (barWidth + barGap) * numOfBars - barGap;`
If your chart has a fixed width, then 
```
chart.options.grid.x = Math.floor(chart.getWidth() - chartPlotAreaWidth) / 2);
chart.options.grid.x2 = chart.getWidth() - chartPlotAreaWidth;
```

**Comment by liuyanlei** [comment]
多谢多谢~
