### ISSUE TITLE
EChart分辨率比例的问题

### ISSUE THREAD

**Issue by lanyudhy** [ecomfe/echarts#2312]
EChart在移动设备上显示时，分辨率比例如何动态调整？
当前设备上是2倍的分辨率，canvas的宽高和style定义的宽高相差2倍。
请问这种情况，有对应方案吗？
@林峰

**Comment by pissang** [comment]
分辨率和实际高宽的比例由设备的 devicePixelRatio 决定， ECharts 3 中支持强制设定画布的 devicePixelRatio

**Comment by lanyudhy** [comment]
在ECharts2中init(dom)之后canvas的宽高和style定义的宽高相差2倍。
这是什么原因导致的呢？

**Comment by pissang** [comment]
这是对高分屏所做的优化，如果不是 2 倍的话显示的效果不会那么清晰

**Comment by lanyudhy** [comment]
OK！
在我的项目中，zrender的Painter和Layer都显示着canvas.height:200px（举个例子），dom.style.height:100px。
但是在实际画出来的图中，canvas.height:400px，dom.style.height:200px，和代码中打印出来的结果不一致，请问这是怎么回事？难道在后期还进行调整宽高的操作吗？亦或是本地使用的其他库对最后画出的图宽高产生影响？

**Comment by pissang** [comment]
不太清楚，如果容器高度确定只有 `100px` 是不会有这个问题的，你排除下是否是自己有调整容器大小。

**Comment by lanyudhy** [comment]
找到原因了，是因为之前require了hidpi-canvans，在this.dom.getContext('2d')时出现问题，导致渲染容器出错。
非常感谢@pissang
