### ISSUE TITLE
如何让数据为-时，不生成占据位置的空条形？

### ISSUE THREAD

**Issue by linayanse** [ecomfe/echarts#2313]
我的需求是某一列只会显示一个条形，但是数据给-时，其他series依然会在这列生成一个占据位置的空条形。

**Comment by pissang** [comment]
把数据去掉

**Comment by linayanse** [comment]
data数组如果少一个元素肯定会对不上，而且就算去掉了也会生成空条形

**Comment by pissang** [comment]
那得调整 category 的 data

**Comment by linayanse** [comment]
其他的series是要有数据的，就是第一个series没有

**Comment by pissang** [comment]
那肯定会多出一个空位啊

**Comment by R-River** [comment]
请问楼主解决了这个问题吗？

**Comment by linayanse** [comment]
@R-River 没有，如果没数据只能显示一个空的位置。

**Comment by R-River** [comment]
@linayanse 嗯 谢谢~
