### ISSUE TITLE
折线图-symbolsize在hover的时候改变大小

### ISSUE THREAD

**Issue by codergray** [ecomfe/echarts#2314]
需求是折线图默认状态symbolsize=0不显示，当鼠标hover上去的时候symbolsize = 2，鼠标移出的时候恢复到symbolsize = 0，怎么设置

**Comment by codergray** [comment]
myChart.on(echarts.config.EVENT.HOVER, function (e) {
                option.series[0]['symbolSize'] = 2;
                myChart.setOption(option);
            });

            myChart.on(echarts.config.EVENT.MOUSEOUT, function (E) {
                option.series[0]['symbolSize'] = 0;
                myChart.setOption(option);
            });
找到了以上事件能改变symbolsize大小，可是希望是目标点才改变symbol大小，其他的点不改变，有类似e.target的属性控制吗？

**Comment by pissang** [comment]
每个 data 都可以单独设置自己的 symbolSize

**Comment by codergray** [comment]
谢谢指点，我按下述方法对目标data设置了symbolsize后，mouseout事件无法将其symbolsize设置为 0，而且过一段时间，整个折线图斗消失掉了，但是hover的时候还能出现symbol圆点。

myChart.on(echarts.config.EVENT.HOVER, function (e) {
                var edataArr = option.series[e.seriesIndex].data;
                var evalue = edataArr[e.dataIndex];
                edataArr[e.dataIndex] = {value: evalue, symbolSize: 2};                         
                option.series[e.seriesIndex].data = edataArr;
                myChart.setOption(option);
 });

myChart.on(echarts.config.EVENT.MOUSEOUT, function (e) {
                var edataArr = option.series[e.seriesIndex].data;
                var evalue = edataArr[e.dataIndex].value;
                edataArr[e.dataIndex] = {value: evalue, symbolSize: 0};
                myChart.setOption(option);
});

**Comment by wsz7777** [comment]
hover的时候只能通过这种暴力方式修改吗？

**Comment by cooljser** [comment]
可以通过设置 opacity 实现，默认 itemStyle 的 opacity 为 0，emphasis.itemStyle 的 opacity 设置为 1

**Comment by gladcome** [comment]
> 可以通过设置 opacity 实现，默认 itemStyle 的 opacity 为 0，emphasis.itemStyle 的 opacity 设置为 1

opcity设置会出现由0-1变化的效果，是哪个配置可以去掉呢

**Comment by gladcome** [comment]
> > 可以通过设置 opacity 实现，默认 itemStyle 的 opacity 为 0，emphasis.itemStyle 的 opacity 设置为 1
> 
> opcity设置会出现由0-1变化的效果，是哪个配置可以去掉呢
已经可以了
