### ISSUE TITLE
Created English version of echarts-all.js file, would like to contribute file to ECharts

### ISSUE THREAD

**Issue by WebCodePro719** [ecomfe/echarts#2321]
Hello, I've created an English version of the echarts-all.js file and would like to contribute it to the ECharts GitHub repository. Using Google Translate, I've translated the chart tooltips and title tags to English. I've also included some additional themes in the echarts-all.js file (the original file only includes default, infographic and macarons themes). If you find that this updated echarts-all.js file is helpful, perhaps it could be made available for download along with the original Chinese version. I've also included a couple bar chart examples in the zip. I wasn't sure if I should make a pull request to submit this to ECharts since the changes are significant. I really like ECharts, thanks for making it open source. Hopefully this English version of echarts-all.js file is helpful.
[EChartsAll-English.zip](https://github.com/ecomfe/echarts/files/76426/EChartsAll-English.zip)

**Comment by adi76** [comment]
thanks

**Comment by Janaranga** [comment]
Thanks a lot

**Comment by oguzozgen** [comment]
ty

**Comment by markopill** [comment]
thanks, very helpful

**Comment by annjawn** [comment]
Is there a future roadmap to support multiple languages through global default options?

**Comment by KugonicU** [comment]
Thanks a lot. Save a lot of hours of work!

**Comment by dyve** [comment]
I would love multiple languages (translatable strings or a simple JS associative array).

**Comment by EgleKat** [comment]
How do I add it to the library, it doesn't seem to work for me

**Comment by WebCodePro719** [comment]
@EgleKat Copy the theme JS file(s) into the folder called "theme." Make sure the name of the theme is added to the chart code (2 places).

**Comment by zherman91** [comment]
Hello. I just tried this last night and its working however, my color scheme went away and was replaced with pinks and blues and I'm not sure how to adjust this. I'm new to echarts so i most likely missed something small. Can anyone help?

**Comment by WebCodePro719** [comment]
Hi @zherman91 - it's hard to figure out what is causing the problem without seeing your code. But it could be a problem with the line of JS code where you add the theme. For example the default code is this:

`	var myChart = echarts.init(document.getElementById('main')); 
        myChart.setOption({`

If you want to add a theme, then the code would be something like this:

`        var myChart = echarts.init(document.getElementById('main'), 'green');
	// Themes: dark, macarons, infographic, green, blue, roma, shine, sakura, macarons2, helianthus, default
        myChart.setOption({`

I'm assuming you're using ECharts version 2 in this case. The themes for ECharts 3.0 are installed differently. There are separate JS files for the themes in version 3.

**Comment by annjawn** [comment]
@zherman91 check what theme you are using. I am pretty sure it's the theme that is causing the colors.

**Comment by annjawn** [comment]
BTW @WebCodePro719 , we've been using your english version in our internal environments for almost a year now and it's still going strong. Thanks again!

**Comment by zherman91** [comment]
@WebCodePro719  - Thanks so much for the reply! I will give this a shot but I'm pretty sure that's what i was missing. Thanks again!

**Comment by zherman91** [comment]
@WebCodePro719  - Thanks so much for the reply! I will give this a shot but I'm pretty sure that's what i was missing. Thanks again!

**Comment by WebCodePro719** [comment]
@annjawn that's great to hear - I'm glad this file has been helpful.

**Comment by WebCodePro719** [comment]
@zherman91 No problem, I hope you figure it out.

**Comment by XargoNet** [comment]
Hi, many thanks for this file.
I'm facing an issue with Maps:
`TypeError: echarts.registerMap is not a function`

I'm loading the provinces of a country, to be drawn. It work with any other echarts.js file (non translated).

I tried to add the function with no luck.

Thanks!
