### ISSUE TITLE
IE8 缩小时，图上的shape行为不一致，有的缩小，有的隐藏

### ISSUE THREAD

**Issue by baweiji** [ecomfe/echarts#2332]
IE8 缩小时，图上的shape行为不一致，有的缩小，有的隐藏。 可有解决方案？

![qq 20160107143832](https://cloud.githubusercontent.com/assets/1695815/12163950/89788530-b54c-11e5-8c92-d75ec88af883.png)

**Comment by pissang** [comment]
这个是我们协助开发的百度产品，跟 ECharts 关系不大。
