### ISSUE TITLE
Echarts3.0饼图兼容问题

### ISSUE THREAD

**Issue by dujiliangacd** [ecomfe/echarts#2335]
在使用Echarts3.0开发饼图时发现，颜色都是黑色，有严重问题，可有优化后的版本？
![image](https://cloud.githubusercontent.com/assets/5093740/12188894/6af3ae66-b5f4-11e5-85dd-00308a4299f1.png)

**Comment by pissang** [comment]
能描述下问题的环境和如何复现么？

**Comment by dujiliangacd** [comment]
![image](https://cloud.githubusercontent.com/assets/5093740/12225548/dec0ac9a-b847-11e5-8a5f-c061da0b2d6d.png)
就从上面3.0测试版下载了js,替换了以前的一个饼图示例中的echarts js就这样了

**Comment by dujiliangacd** [comment]
@pissang  http://yunpan.cn/cu4aWXpc4ZTvz  访问密码 f761
360云盘上我分享了一个示例，你看下

**Comment by pissang** [comment]
解压不了，如果是 chrome 下有这个问题的话把 option 贴一下吧

**Comment by dujiliangacd** [comment]
myChart2.setOption({
			tooltip : {
				trigger: 'item',
				formatter: "{a} <br/>{b} : {c} ({d}%)"
			},
			legend: {
				orient : 'horizontal',
				x : 'center',
				y :'bottom',
				data:['拉萨','日喀泽','林芝','阿里','那曲','昌都','山南'],
			    textStyle :{
					 fontSize :10
				 },
				 itemWidth: 12,
				 itemHeight: 12
			},
			calculable : true,
			series : [
				{
					
					name:'访问来源',
					type:'pie',
					radius : '50%',
					center: ['50%', '45%'],
					itemStyle : {
						normal : {
							color: function(params) {
								var colorList = ['#2ec7c9', '#b6a2de', '#5ab1ef', '#ffb980', '#d87a80','#8d98b3','#e5cf0d']
								return colorList[params.dataIndex]
							},
							labelLine: {
								length : 8
							}
						},
					},

					data:[
						{value:150, name:'拉萨'},
						{value:110, name:'日喀泽'},
						{value:100, name:'林芝'},
						{value:90, name:'阿里'},
						{value:660, name:'那曲'},
						{value:110, name:'昌都'},
						{value:835, name:'山南'}
					]
				}
			]
        });

**Comment by dujiliangacd** [comment]
@pissang 试了几个机器，分享解压应该没有问题吧？

**Comment by pissang** [comment]
回调函数有 bug，修复了，想用调色盘的话可以直接设置 `option.color`，3 中也支持每个系列分别设置调色盘

**Comment by AnnieChen5542** [comment]
我也遇到了同样的问题 请问是怎么解决的

**Comment by ruantongtong** [comment]
我也遇到了这个问题，用的是3.3.2版本 chrome浏览器，不知怎么解决

**Comment by shenqihui** [comment]
+1

**Comment by pissang** [comment]
series 下的 color 不是数组类型的

**Comment by shenqihui** [comment]
经过尝试，发现应该是打包的问题造成的。

以前使用自己的配置使用 webpack 来 import 时候能正确渲染。

现在改用 cdn 或者直接 import echarts from 'echarts' ，就出现问题。

例如我使用 `https://cdn.bootcss.com/echarts/3.6.2/echarts.min.js` 的来渲染，会黑色。

但是如果我使用 `https://cdn.bootcss.com/echarts/3.6.2/echarts.common.min.js` 这个common版本，就能设置颜色。

希望能解决上面遇到的问题。
