### ISSUE TITLE
饼图单击事件重新setOption后图例又恢复成了原始样式

### ISSUE THREAD

**Issue by yy1002** [ecomfe/echarts#2336]
饼图单击事件中重新setOption后图例又恢复成了原始样式

效果是在点击饼图某一项，对应的模块推出，图例文字加粗。

一开始给图例设置了雅黑14号字体，结果单击后对应的图例虽然加粗了可是其它图例都变为了默认样式。

求解~

![image](https://cloud.githubusercontent.com/assets/16603113/12188977/0228e18e-b5f5-11e5-864e-e7c5c6e8e76b.png)

**Comment by shanjixiaboss** [comment]
option下的设置都会被渲染，像现在做的地图，一个有划线效果，一个是热力效果；如果热力切换后去渲染地图的话，划线效果也会被重置；所以解决办法是设置几个option单独去渲染

**Comment by yy1002** [comment]
问题是我这里已经对每个图例的样式重新设置了，没鸟用~
