### ISSUE TITLE
ECharts3.0的主题实在是太丑了，如何更换？

### ISSUE THREAD

**Issue by xingdongli** [ecomfe/echarts#2342]
ECharts3.0的主题实在是太丑了，如何更换？

**Comment by zhump** [comment]
同问是否有内置主题供用户切换？还是2.0的主题也能应用在3.0中？

**Comment by pissang** [comment]
http://echarts.baidu.com/echarts2/doc/example/theme.html 中的 2.0 的主题也可以在 3.0 里使用，后续在官网界面上会提供主题的下载界面。

**Comment by ekuwang** [comment]
我在3.0 init时传入了2.0的主题配置对象，但是并没有起作用。

**Comment by daleyjh** [comment]
我自己改写了个ec2的主题，给ec3用了，只需要按照https://github.com/ecomfe/echarts/tree/master/theme这里面的主题引用方式把ec2的theme对象穿进去，就可以在init的第二个参数穿进去已经定义好的字符串进去使之生效
