### ISSUE TITLE
[3.0.0] 柱状图绘图，尾部可能出现问题

### ISSUE THREAD

**Issue by amoydavid** [ecomfe/echarts#2343]
![image](https://cloud.githubusercontent.com/assets/734190/12252299/f16de05a-b910-11e5-8d28-b232a96eef66.png)

看尾部的几个，明显超过x轴了。2.7上不会这样。

**Comment by amoydavid** [comment]
echarts.min.js

**Comment by pissang** [comment]
能给下 option 么？谢谢

**Comment by amoydavid** [comment]
var option = {
            title:{
                text:"2016-01-12 00:00:00 - 2016-01-12 23:59:59"
            },
            tooltip: {
                show: true
            },
            toolbox: {
                show : true,
                feature : {
                    mark : {show: false},
                    dataView : {show: true, readOnly: false},
                    restore : {show: false},
                    saveAsImage : {show: true}
                }
            },
            legend: {
                data:['扫描量']

            },
            xAxis : [
                {
                    type : 'category',
                    data : ["纸箱1","红包2","红包3","红包4","红包5","红包6","红包7","红包8","红包9","纸箱10","纸箱11","红包12","红包13","红包14","红包15","纸箱16","红包17","纸箱18","纸箱19"],
                    axisLabel:{rotate:20,interval:false}
                }
            ],
            yAxis : [
                {
                    type : 'value'
                }
            ],
            series : [
                {
                    "name":"扫描量",
                    "type":"bar",
                    "data":[443,98,92,54,46,36,30,22,21,18,15,13,8,7,5,4,4,2,1],
                    itemStyle: {
                        normal: {
                            color: 'tomato',
                            barBorderColor: 'tomato',
                            barBorderWidth: 6,
                            barBorderRadius:0,
                            label : {
                                show: true, position: 'top'
                            }
                        }
                    }
                }
            ]
        };

**Comment by pissang** [comment]
看了下好像是加了边框的原因，你可以先把 barBorderWidth 设为 0，我们后续修复下这个问题。

**Comment by amoydavid** [comment]
//抱拳
