### ISSUE TITLE
力导向图无法关闭动画

### ISSUE THREAD

**Issue by Gyyi** [ecomfe/echarts#2346]
animation: false 
是否对力导向图动画无效呢？
尝试过将animationDuration的值设置为0也是无效的。
求解答 ~

**Comment by pissang** [comment]
在 ECharts 3 里力导向图改为了关系图，里面的力导向布局可以关闭动画，见 http://echarts.baidu.com/option.html#series-graph.force.layoutAnimation

**Comment by Gyyi** [comment]
2.0 里面可以吗，目前项目使用的是2.0版本的，短时间内无法升级到3.0

**Comment by pissang** [comment]
2.0 里不行

**Comment by Gyyi** [comment]
T＿T  
感谢解答
