### ISSUE TITLE
Cannot use 'in' operator to search for 'x' in ECharts 入门示例

### ISSUE THREAD

**Issue by hellorocky** [ecomfe/echarts#2347]
官方实例本地调试不通

**Comment by pissang** [comment]
是哪个示例？

**Comment by hellorocky** [comment]
http://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts

**Comment by pissang** [comment]
抱歉教程里手误，title 应该是一个对象 { text: '入门教程示例' }
