### ISSUE TITLE
什么是正确的删除数据点的方式

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#2348]
初始化一个line chart时插入了10个数据点。过了5分钟又插入了20个数据点。
我想要恢复到初始化状态（带10个点），是不是只能重新setOption()？
我尝试了clear()结果x轴y走轴统统没了。

**Comment by pissang** [comment]
只能重新 setOption

**Comment by stanleyxu2005** [comment]
Ok
