### ISSUE TITLE
Echarts ecomfe 触摸屏 touch 在IE10下无法显示悬浮框

### ISSUE THREAD

**Issue by 68681395** [ecomfe/echarts#2350]
Windows 8 IE10浏览http://echarts.baidu.com/doc/example/line2.html 时，鼠标放置在数据点上时无法显示悬浮框。
问题分析：
公司有各种型号电脑，X230，W530，X240,业务部门多使用x240， 这一款笔记本屏幕带有触摸屏功能，其他型号没有。所有操作系统都为win8，IE10小版本号也一致。
最初就将问题定位为触摸屏引起了这个问题，但一直无法找到具体原因。因为在chrome，firfox等浏览器没有问题，只有在IE上有问题

**Comment by 68681395** [comment]
解决办法有两个，我们采取了第一点：
1.	修改echarts.js文件，修改evn.os.tablet和evn.os.phone的取值代码，不在判断是否是touch。一直默认为false。
2.	修改echarts.js文件，去掉此判断if (env.os.tablet || env.os.phone)，无论任何情况都添加两种事件。当然如果此中办法，需要在detachEvent时也要去掉。

**Comment by 100pah** [comment]
fixed on <https://github.com/ecomfe/zrender/commit/0064c66955266dc3bec5ec0f0945b8c40ecabe84>

**Comment by 68681395** [comment]
thanks for the update, thank you.
