### ISSUE TITLE
type设置为time时，interval设置时间戳无效

### ISSUE THREAD

**Issue by pandaju** [ecomfe/echarts#2355]
希望能写详细些，interval要如何设置才能准确分割x轴。

我设置min是new Date(2016, 0, 1, 0, 0, 0)，max是new Date(2016, 0, 5, 0, 0, 0)时，希望能按照天分割x轴，但是设置splitNumber为4时不能平均分割x轴。
然后使用interval，无论是精确到秒的时间戳，还是精确到毫秒的时间戳，都无效。

**Comment by daoyuanjiao** [comment]
new Date('2016-7-3 8:40:52')

**Comment by JIANGQIAN3333** [comment]
最新版本：type设置为time时，interval设置时间戳无效
我想设置根据每个月进行分割x轴，但是无法实现，请问那里出现了问题
 `xAxis: { type: 'time', interval: 2592000000, min: new Date('2016-7-3 8:40:52'), max: new Date('2021-7-3 8:40:52'), axisLabel: { show: true, formatter: '{yyyy}.{MM}' }, splitNumber: false, splitLine: { show: true }, axisTick: { show: true }},`

**Comment by yjxhome** [comment]
option = {
    "animation": false,
    "grid": {
        "bottom": 0,
        "left": 0,
        "right": 0,
        "top": 0
    },
    "series": [
        {
            "S": 12,
            "animation": false,
            "color": "#E7086E",
            "colorDict": "#E7086E",
            "connectNulls": false,
            "data": [],
            "id": "白细胞计数__WN_ICIS_INSPECT_1011001__",
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "normal": {
                    "width": 1
                }
            },
            "lineTypeDict": "line",
            "max": 30,
            "maxValue": 1,
            "min": 8,
            "minValue": 0,
            "moniitemCode": "WN_ICIS_INSPECT_1011001",
            "moniitemDesc": "",
            "moniitemName": "白细胞计数",
            "name": "白细胞计数",
            "observeId": "100001",
            "smooth": 0,
            "statusDict": "1",
            "symbol": "path://M10.3,1.5c-4.7,0-8.5,3.8-8.5,8.5c0,4.7,3.8,8.5,8.5,8.5s8.5-3.8,8.5-8.5C18.8,5.3,14.9,1.5,10.3,1.5z M10.3,17.4 c-4.1,0-7.5-3.3-7.5-7.5s3.3-7.5,7.5-7.5c4.2,0,7.4,3.4,7.4,7.5S14.4,17.4,10.3,17.4z M12.1,6.1H8.4c-1.1,0-2,0.9-2,2v3.7 c0,1.1,0.9,2,2,2h3.7c1.1,0,2-0.9,2-2V8C14.1,7,13.2,6.1,12.1,6.1z",
            "symbolDict": "M10.3,1.5c-4.7,0-8.5,3.8-8.5,8.5c0,4.7,3.8,8.5,8.5,8.5s8.5-3.8,8.5-8.5C18.8,5.3,14.9,1.5,10.3,1.5z M10.3,17.4 c-4.1,0-7.5-3.3-7.5-7.5s3.3-7.5,7.5-7.5c4.2,0,7.4,3.4,7.4,7.5S14.4,17.4,10.3,17.4z M12.1,6.1H8.4c-1.1,0-2,0.9-2,2v3.7 c0,1.1,0.9,2,2,2h3.7c1.1,0,2-0.9,2-2V8C14.1,7,13.2,6.1,12.1,6.1z",
            "symbolSize": 8,
            "type": "line",
            "units": "bpm",
            "wardCode": "1876391",
            "yAxisIndex": 1,
            "yaxis": "1",
            "z": 3
        },
        {
            "S": 12,
            "animation": false,
            "color": "#E7086E",
            "colorDict": "#E7086E",
            "connectNulls": false,
            "data": [],
            "id": "体温__WN_ICIS_MONI_10010101__T",
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "normal": {
                    "width": 1
                }
            },
            "lineTypeDict": "line",
            "max": 30,
            "maxValue": 40,
            "min": 8,
            "minValue": 35,
            "moniitemCode": "WN_ICIS_MONI_10010101",
            "moniitemDesc": "T",
            "moniitemName": "体温",
            "name": "体温",
            "observeId": "100001",
            "smooth": 0,
            "statusDict": "1",
            "symbol": "path://M10.3,1.5c-4.7,0-8.5,3.8-8.5,8.5c0,4.7,3.8,8.5,8.5,8.5s8.5-3.8,8.5-8.5C18.8,5.3,14.9,1.5,10.3,1.5z M10.3,17.4 c-4.1,0-7.5-3.3-7.5-7.5s3.3-7.5,7.5-7.5c4.2,0,7.4,3.4,7.4,7.5S14.4,17.4,10.3,17.4z M12.1,6.1H8.4c-1.1,0-2,0.9-2,2v3.7 c0,1.1,0.9,2,2,2h3.7c1.1,0,2-0.9,2-2V8C14.1,7,13.2,6.1,12.1,6.1z",
            "symbolDict": "M10.3,1.5c-4.7,0-8.5,3.8-8.5,8.5c0,4.7,3.8,8.5,8.5,8.5s8.5-3.8,8.5-8.5C18.8,5.3,14.9,1.5,10.3,1.5z M10.3,17.4 c-4.1,0-7.5-3.3-7.5-7.5s3.3-7.5,7.5-7.5c4.2,0,7.4,3.4,7.4,7.5S14.4,17.4,10.3,17.4z M12.1,6.1H8.4c-1.1,0-2,0.9-2,2v3.7 c0,1.1,0.9,2,2,2h3.7c1.1,0,2-0.9,2-2V8C14.1,7,13.2,6.1,12.1,6.1z",
            "symbolSize": 8,
            "type": "line",
            "units": "bpm",
            "wardCode": "1876391",
            "yAxisIndex": 2,
            "yaxis": "1",
            "z": 3
        },
        {
            "S": 12,
            "animation": false,
            "color": "#FF8C00",
            "colorDict": "#FF8C00",
            "connectNulls": false,
            "data": [],
            "id": "收缩压__WN_ICIS_MONI_10010203__无创收缩压",
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "normal": {
                    "width": 1
                }
            },
            "lineTypeDict": "vLine",
            "max": 30,
            "maxValue": 200,
            "min": 8,
            "minValue": 70,
            "moniitemCode": "WN_ICIS_MONI_10010203",
            "moniitemDesc": "无创收缩压",
            "moniitemName": "收缩压",
            "name": "收缩压",
            "observeId": "100001",
            "smooth": 0,
            "statusDict": "1",
            "symbol": "path://M16.8,9.27v1.05L3.24,17.43V16.1L15.39,9.85V9.77L3.24,3.49V2.16Z",
            "symbolDict": "M16.8,9.27v1.05L3.24,17.43V16.1L15.39,9.85V9.77L3.24,3.49V2.16Z",
            "symbolSize": 8,
            "type": "line",
            "units": "bpm",
            "wardCode": "1876391",
            "yAxisIndex": 3,
            "yaxis": "1",
            "z": 3
        },
        {
            "S": 12,
            "animation": false,
            "color": "#EB7405",
            "colorDict": "#EB7405",
            "connectNulls": false,
            "data": [],
            "id": "舒张压__WN_ICIS_MONI_10010204__无创舒张压",
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "normal": {
                    "width": 1
                }
            },
            "lineTypeDict": "vLine",
            "max": 30,
            "maxValue": 120,
            "min": 8,
            "minValue": 40,
            "moniitemCode": "WN_ICIS_MONI_10010204",
            "moniitemDesc": "无创舒张压",
            "moniitemName": "舒张压",
            "name": "舒张压",
            "observeId": "100001",
            "smooth": 0,
            "statusDict": "1",
            "symbol": "path://M16.8,2.16V3.49L4.65,9.77v.08L16.8,16.1v1.33L3.24,10.32V9.27Z",
            "symbolDict": "M16.8,2.16V3.49L4.65,9.77v.08L16.8,16.1v1.33L3.24,10.32V9.27Z",
            "symbolSize": 8,
            "type": "line",
            "units": "bpm",
            "wardCode": "1876391",
            "yAxisIndex": 4,
            "yaxis": "1",
            "z": 3
        },
        {
            "S": 12,
            "animation": false,
            "color": "#7700B2",
            "colorDict": "#7700B2",
            "connectNulls": false,
            "data": [],
            "id": "呼吸__WN_ICIS_MONI_10010207__呼吸频率",
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "normal": {
                    "width": 1
                }
            },
            "lineTypeDict": "line",
            "max": 30,
            "maxValue": 25,
            "min": 8,
            "minValue": 10,
            "moniitemCode": "WN_ICIS_MONI_10010207",
            "moniitemDesc": "呼吸频率",
            "moniitemName": "呼吸",
            "name": "呼吸",
            "observeId": "100001",
            "smooth": 0,
            "statusDict": "1",
            "symbol": "path://M10.7,10.3l6.6,6.6c0.2,0.2,0.2,0.5,0,0.7c-0.2,0.2-0.5,0.2-0.7,0L10,11l-6.6,6.6c-0.2,0.2-0.5,0.2-0.7,0 c-0.2-0.2-0.2-0.5,0-0.7l6.6-6.6L2.7,3.7C2.5,3.5,2.5,3.2,2.7,3c0.2-0.2,0.5-0.2,0.7,0L10,9.6L16.6,3c0.2-0.2,0.5-0.2,0.7,0 c0.2,0.2,0.2,0.5,0,0.7L10.7,10.3z",
            "symbolDict": "M10.7,10.3l6.6,6.6c0.2,0.2,0.2,0.5,0,0.7c-0.2,0.2-0.5,0.2-0.7,0L10,11l-6.6,6.6c-0.2,0.2-0.5,0.2-0.7,0 c-0.2-0.2-0.2-0.5,0-0.7l6.6-6.6L2.7,3.7C2.5,3.5,2.5,3.2,2.7,3c0.2-0.2,0.5-0.2,0.7,0L10,9.6L16.6,3c0.2-0.2,0.5-0.2,0.7,0 c0.2,0.2,0.2,0.5,0,0.7L10.7,10.3z",
            "symbolSize": 8,
            "type": "line",
            "units": "bpm",
            "wardCode": "1876391",
            "yAxisIndex": 5,
            "yaxis": "1",
            "z": 3
        },
        {
            "S": 12,
            "animation": false,
            "color": "#E7086E",
            "colorDict": "#E7086E",
            "connectNulls": false,
            "data": [],
            "id": "血氧饱和度__WN_ICIS_MONI_10040110__SO2",
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "normal": {
                    "width": 1
                }
            },
            "lineTypeDict": "line",
            "max": 30,
            "maxValue": 1,
            "min": 8,
            "minValue": 0,
            "moniitemCode": "WN_ICIS_MONI_10040110",
            "moniitemDesc": "SO2",
            "moniitemName": "血氧饱和度",
            "name": "血氧饱和度",
            "observeId": "100001",
            "smooth": 0,
            "statusDict": "1",
            "symbol": "path://M10.4,1.5c-4.8,0-8.7,3.9-8.7,8.7s3.9,8.7,8.7,8.7c4.8,0,8.7-4,8.7-8.7C19.1,5.4,15.2,1.5,10.4,1.5z M10.5,2.5 c1.9,0,3.7,0.7,5,1.8l-5.1,5.1l-5-5C6.7,3.2,8.5,2.5,10.5,2.5z M2.8,10.2c0-1.9,0.7-3.7,1.9-5.1l5,5l-5,5 C3.5,13.8,2.8,12.1,2.8,10.2z M5.4,15.9l5-5l5.1,5.1c-1.4,1.1-3.1,1.8-5,1.8C8.6,17.8,6.8,17.1,5.4,15.9z M16.2,15.3l-5.1-5.1 L16.2,5c1.2,1.4,2,3.2,2,5.2C18.2,12.2,17.4,14,16.2,15.3z",
            "symbolDict": "M10.4,1.5c-4.8,0-8.7,3.9-8.7,8.7s3.9,8.7,8.7,8.7c4.8,0,8.7-4,8.7-8.7C19.1,5.4,15.2,1.5,10.4,1.5z M10.5,2.5 c1.9,0,3.7,0.7,5,1.8l-5.1,5.1l-5-5C6.7,3.2,8.5,2.5,10.5,2.5z M2.8,10.2c0-1.9,0.7-3.7,1.9-5.1l5,5l-5,5 C3.5,13.8,2.8,12.1,2.8,10.2z M5.4,15.9l5-5l5.1,5.1c-1.4,1.1-3.1,1.8-5,1.8C8.6,17.8,6.8,17.1,5.4,15.9z M16.2,15.3l-5.1-5.1 L16.2,5c1.2,1.4,2,3.2,2,5.2C18.2,12.2,17.4,14,16.2,15.3z",
            "symbolSize": 8,
            "type": "line",
            "units": "bpm",
            "wardCode": "1876391",
            "yAxisIndex": 6,
            "yaxis": "1",
            "z": 3
        },
        {
            "S": 12,
            "animation": false,
            "color": "#E7086E",
            "colorDict": "#E7086E",
            "connectNulls": false,
            "data": [],
            "id": "空腹血糖__WN_ICIS_MONI_10040202__GLU",
            "itemStyle": {
                "normal": {}
            },
            "lineStyle": {
                "normal": {
                    "width": 1
                }
            },
            "lineTypeDict": "point",
            "max": 30,
            "maxValue": 1,
            "min": 8,
            "minValue": 0,
            "moniitemCode": "WN_ICIS_MONI_10040202",
            "moniitemDesc": "GLU",
            "moniitemName": "空腹血糖",
            "name": "空腹血糖",
            "observeId": "100001",
            "smooth": 0,
            "statusDict": "1",
            "symbol": "path://M10.5,9.5L3.2,2.1L4,1.3l6.5,6.5L17,1.3l0.8,0.8L10.5,9.5z M3.2,17.9L4,18.8l6.5-6.5l6.5,6.5l0.8-0.8l-7.4-7.4L3.2,17.9z",
            "symbolDict": "M10.5,9.5L3.2,2.1L4,1.3l6.5,6.5L17,1.3l0.8,0.8L10.5,9.5z M3.2,17.9L4,18.8l6.5-6.5l6.5,6.5l0.8-0.8l-7.4-7.4L3.2,17.9z",
            "symbolSize": 8,
            "type": "line",
            "units": "bpm",
            "wardCode": "1876391",
            "yAxisIndex": 7,
            "yaxis": "1",
            "z": 3
        }
    ],
    "tooltip": {
        "trigger": "item"
    },
    "xAxis": [
        {
            "axisLabel": {
                "interval": 0,
                "rotate": 15,
                "show": false
            },
            "axisLine": {
                "onZero": false,
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "boundaryGap": false,
            "interval": 60,
            "max": 1665252420,
            "min": 1665251580,
            "splitLine": {
                "lineStyle": {
                    "color": "#000000",
                    "opacity": 1,
                    "type": "dotted"
                },
                "show": true
            },
            "type": "time"
        }
    ],
    "yAxis": [
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 21.818181818181817,
            "max": 240,
            "min": 0,
            "splitLine": {
                "lineStyle": {
                    "color": "#000000",
                    "opacity": 1,
                    "type": "dotted"
                },
                "show": true
            },
            "type": "value"
        },
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 1,
            "max": 1,
            "min": 0,
            "moniitemCode": "WN_ICIS_INSPECT_1011001",
            "moniitemName": "白细胞计数",
            "splitLine": {
                "show": false
            },
            "type": "value"
        },
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 1,
            "max": 40,
            "min": 35,
            "moniitemCode": "WN_ICIS_MONI_10010101",
            "moniitemName": "体温",
            "splitLine": {
                "show": false
            },
            "type": "value"
        },
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 1,
            "max": 200,
            "min": 70,
            "moniitemCode": "WN_ICIS_MONI_10010203",
            "moniitemName": "收缩压",
            "splitLine": {
                "show": false
            },
            "type": "value"
        },
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 1,
            "max": 120,
            "min": 40,
            "moniitemCode": "WN_ICIS_MONI_10010204",
            "moniitemName": "舒张压",
            "splitLine": {
                "show": false
            },
            "type": "value"
        },
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 1,
            "max": 25,
            "min": 10,
            "moniitemCode": "WN_ICIS_MONI_10010207",
            "moniitemName": "呼吸",
            "splitLine": {
                "show": false
            },
            "type": "value"
        },
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 1,
            "max": 1,
            "min": 0,
            "moniitemCode": "WN_ICIS_MONI_10040110",
            "moniitemName": "血氧饱和度",
            "splitLine": {
                "show": false
            },
            "type": "value"
        },
        {
            "axisLabel": {
                "show": false
            },
            "axisLine": {
                "show": false
            },
            "axisTick": {
                "show": false
            },
            "interval": 1,
            "max": 1,
            "min": 0,
            "moniitemCode": "WN_ICIS_MONI_10040202",
            "moniitemName": "空腹血糖",
            "splitLine": {
                "show": false
            },
            "type": "value"
        }
    ]
}


interval:60无效，v4没问题 v5.4.2不行
