### ISSUE TITLE
calculable : true,  可拖拽 从新加载图形的这个属性 不起做用了

### ISSUE THREAD

**Issue by ready360go** [ecomfe/echarts#2358]
![image](https://cloud.githubusercontent.com/assets/16661632/12258642/1bbfc780-b94b-11e5-8bd7-d0802796b85d.png)

**Comment by pissang** [comment]
3.0 里暂时不支持拖拽重计算。

**Comment by ready360go** [comment]
感谢 您的回复   请问这个功能后期是否会再加上呢

**Comment by ready360go** [comment]
@pissang  感谢 您的回复 请问这个功能后期是否会再加上呢
