### ISSUE TITLE
3.0地图数据没有各直辖市的数据

### ISSUE THREAD

**Issue by ahxukai** [ecomfe/echarts#2360]
热门城市的geojson数据没有提供下载，希望做个最新的各热门城市的地图数据，例如在2.0时期上海的行踪区划已经部署最新的了，现在上海好多区已经合并了，2.0上面还是老的，希望能重新做一个最新的行政区划版的地图数据提供给开发者下载

**Comment by yuu2lee4** [comment]
只能上2.0的官网下载了

**Comment by ahxukai** [comment]
2.0的数据是可以下载但是上海市的行政区划已经变了，好多区合并了，下载了也是错误数据，要手动更改底层geojson数据有困难啊

**Comment by liminjun** [comment]
@ahxukai  修改geoJson数据估计还得需要官方来修改，开发者不好修改吧。

**Comment by yuu2lee4** [comment]
http://geojson.org/   看看这个能不能帮助你

**Comment by pissang** [comment]
可以先从 http://ecomfe.github.io/echarts-map-tool/ 这边下

**Comment by ahxukai** [comment]
@pissang 谢了，你给我的网址上面的地图数据确实比官网的准确一点，例如官网的上海市崇明县本来的岛跟市区中间有江，你给我的版本的中间确实有江，官网的却是连在一起的，像一块大陆一样，但是，但是，但是，重要的来了，两个版本有同一个毛病就是现在上海市的行政区划已经变了，好多区合并了，在两个版本的数据里都没有体现出来，这个还是需要后期官网出面修改的，当然民间有大神能改底层json数据的话希望可以共享出来，我试过改，但是对geojson不熟没改成。最后还是谢了，先用这个过时版的行政区划凑合着用吧
