### ISSUE TITLE
echarts3.0带地图的散点图中，无法响应对地图区域的点击和选择事件。

### ISSUE THREAD

**Issue by Aaron1992** [ecomfe/echarts#2362]
echarts2中使用地图中的markpoint绘制分布图，map数据可以对地图的区域进行点击和选择。
在echarts3中，建议使用散点图绘制来取代markpoint, 但是散点图使用geo属性后，无法设置对地图区域的点击和选择，也就是没有selectedMode选项，也不能响应点击事件。
请问后期有加入这功能的考虑吗？或者有别的技巧完成这个工作？

**Comment by isosky** [comment]
哥们请教一个事情,我使用3.0的官方实例天气污染的那个热力图.本地打开默认居中的是南沙群岛,比例尺也不对..请问哥们你是怎么解决中心点和比例尺问题的?谢谢了

**Comment by pissang** [comment]
@Aaron1992 先可以放一个 map 系列用于选择，放一个 geo 然后 `show:false` 用于散点图的定位，不过感觉 geo 是可以有区域的点击选择。

@isosky 你没加载地图

**Comment by Aaron1992** [comment]
谢谢回复，我考虑过再使用一个map，但是貌似会影响缩放，我暂时先不做点击和选择事件。等你们出来了再加上。
@isosky 现在不内置地图了，你需要下载地图，然后加载地图。具体说明见http://echarts.baidu.com/option.html#series-map

**Comment by PandaDMurphy** [comment]
现在是否支持geo地图点击了呢？？？

**Comment by yxt518** [comment]
请问，有解决了这个不能点击的问题吗？选中了哪个省无法传值？我也用了geo ,map 使用china,想点击选中的省份传值无法办到啊？
还有如果使用map 再使用一个scatter 还是有问题，一个能缩放一个不能缩放

**Comment by zzone** [comment]
这个问题处理了吗
