### ISSUE TITLE
3.0折线图中如果数据值为0，会显示为'-'，且影响平均值计算

### ISSUE THREAD

**Issue by ekuwang** [ecomfe/echarts#2367]
我在折线图中设置了平均值线，当有数据点为0时，图表显示为'-'，且平均值线无法显示平均值。

**Comment by pissang** [comment]
我试了没啥问题，你给下 option 看看

**Comment by ekuwang** [comment]
{
		"tooltip": {
			"trigger": "axis"
		},
		"noDataLoadingOption": {
			"effect": "whirling"
		},
		"legend": {
			"data": ["接收消息数", "发送消息数"],
			"y": "bottom"
		},
		"toolbox": {
			"show": true,
			"orient": "vertical",
			"feature": {
				"dataView": {
					"show": true,
					"readOnly": false
				},
				"magicType": {
					"show": true,
					"type": ["line", "bar"]
				},
				"restore": {
					"show": true
				},
				"saveAsImage": {
					"show": true
				}
			}
		},
		"calculable": true,
		"xAxis": [{
			"type": "category",
			"data": ["12-30", "12-31", "01-01", "01-02", "01-03", "01-04", "01-05", "01-06", "01-07", "01-08", "01-09", "01-10", "01-11", "01-12", "01-13"]
		}],
		"yAxis": [{
			"type": "value"
		}],
		"series": [{
			"name": "接收消息数",
			"data": [71, 64, 10, 1, 6, 5, 75, 53, 32, 107, 15, 7, 43, 102, 5],
			"type": "line",
			"smooth": true,
			"itemStyle": {
				"normal": {
					"areaStyle": {
						"type": "default"
					}
				}
			},
			"markLine": {
				"precision": 0,
				"data": [{
					"type": "average",
					"name": "平均值"
				}]
			}
		}, {
			"name": "发送消息数",
			"data": [10, 27, 7, 0, 7, 7, 40, 40, 33, 104, 13, 1, 37, 85, 4],
			"type": "line",
			"smooth": true,
			"itemStyle": {
				"normal": {
					"areaStyle": {
						"type": "default"
					}
				}
			},
			"markLine": {
				"precision": 0,
				"data": [{
					"type": "average",
					"name": "平均值"
				}]
			}
		}]
	}

**Comment by pissang** [comment]
我这试了下可以的。

![echarts](https://cloud.githubusercontent.com/assets/841551/12285170/461db95e-b9f2-11e5-9564-64d753393021.png)

**Comment by ekuwang** [comment]
![2016-01-13 10 50 08](https://cloud.githubusercontent.com/assets/4213639/12285832/3ab02bfe-b9f9-11e5-9490-1ee09987ca0b.png)
3.0中的样子

![image](https://cloud.githubusercontent.com/assets/4213639/12285875/caa7c6f4-b9f9-11e5-87fa-5b4ca7c9db70.png)
2.0中的样子

请注意第二张图箭头指出的地方
