### ISSUE TITLE
http://echarts.baidu.com/doc/example.html下例子很多打不开

### ISSUE THREAD

**Issue by shanjixiaboss** [ecomfe/echarts#2369]
rt
貌似有几个可以打开，现在都是看本地的，跟3.0的路径没冲突，但好像3上线就变成这样的了

**Comment by pissang** [comment]
老的示例在 http://echarts.baidu.com/echarts2/doc/example.html，新的在 http://echarts.baidu.com/examples.html

**Comment by shanjixiaboss** [comment]
噢，但从http://echarts.baidu.com/进去的话，右上角菜单上的实例地址就不对了，我是这个意思的

**Comment by pissang** [comment]
你看到的应该还是缓存的老的页面

**Comment by shanjixiaboss** [comment]
redis，好吧
