### ISSUE TITLE
从echart2迁移至echart3有没有完整的变更文档？

### ISSUE THREAD

**Issue by zjjott** [ecomfe/echarts#2373]
心塞。。原来的图片各种乱。。。
grid恍惚没对齐。。。

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/wiki/ECharts-2-%E5%8D%87%E7%BA%A7%E5%88%B0-ECharts-3-%E7%9A%84%E6%94%B9%E5%8A%A8
