### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startAngle' of undefined 这是什么错误啊？

### ISSUE THREAD

**Issue by ooiikaka1** [ecomfe/echarts#2377]
在部署pie 图，js报错直接崩溃了 ，报了上面的错误

**Comment by ooiikaka1** [comment]
1.还有我设置了点击时间，点击饼图的扇面会跳转，显示新地数据，当我把鼠标放在图上时显示的是当前数据，拿走就显示上一个数据。
2. var myChart1 = echarts.init(document.getElementById('chart1')); 
myChart1 这个对象怎么清空内容啊？

**Comment by Hardworkingrookie** [comment]
请问一下   Cannot read property 'startAngle' of undefined   这个是怎么解决的

**Comment by eJayYoung** [comment]
同问，Cannot read property 'startAngle' of undefined 怎么解决，也不影响交互，就是会莫名其妙的报出好多条eror

**Comment by Hardworkingrookie** [comment]
不好意思，看了看文档，也没有找到问题，我的是在第一次加载的时候没有错误，后续对其进行修改删除的时候会报
你可以看下你有没有设置auto-resize这个属性，去掉一下试一试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-echarts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 上午9:47
收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;;
抄送:&nbsp;"王亚林"<1270620115@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-echarts] Uncaught TypeError: Cannot read property 'startAngle' of undefined 这是什么错误啊？ (#2377)





 
同问，Cannot read property 'startAngle' of undefined 怎么解决，也不影响交互，就是会莫名其妙的报出好多条eror

**Comment by eJayYoung** [comment]
> 不好意思，看了看文档，也没有找到问题，我的是在第一次加载的时候没有错误，后续对其进行修改删除的时候会报 你可以看下你有没有设置auto-resize这个属性，去掉一下试一试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/incubator-echarts" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月16日(星期三) 上午9:47 收件人:&nbsp;"apache/incubator-echarts"<incubator-echarts@noreply.github.com&gt;; 抄送:&nbsp;"王亚林"<1270620115@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [apache/incubator-echarts] Uncaught TypeError: Cannot read property 'startAngle' of undefined 这是什么错误啊？ (#2377) 同问，Cannot read property 'startAngle' of undefined 怎么解决，也不影响交互，就是会莫名其妙的报出好多条eror — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

确实，就是加了chartInstance.resize方法导致的，去掉了就没有这个报错了，谢谢
