### ISSUE TITLE
关于series[i]-lines.markLine.lineStyle.normal.width的问题

### ISSUE THREAD

**Issue by luqinghui** [ecomfe/echarts#2386]
宽度能不能自定义，根据不同的值现实不同的宽度？或是通过一个function指定？

**Comment by pissang** [comment]
暂时不行，可以设置每条 markLine 的 width，http://echarts.baidu.com/option.html#series-line.markLine.data.0.lineStyle.normal.width

**Comment by DorisOu** [comment]
@pissang 您好。线条颜色能否根据不同的value值给颜色，比如value最大的给红色，中等的给黄色，小的给蓝色这样？

**Comment by DorisOu** [comment]
@pissang 人口迁移用的lines如何设置每条线的width？

**Comment by cuijian-dexter** [comment]
@DorisOu `series.line.markLine.data.lineStyle.normal.width`
