### ISSUE TITLE
echart3没有clear方法么？

### ISSUE THREAD

**Issue by gleams** [ecomfe/echarts#2387]
echart2中可以使用clear() 清空绘画内容，清空后实例可用，请问echart3中有类似的方法吗？

**Comment by 100pah** [comment]
你们在什么场景下需要  clear  方法呢？

**Comment by gleams** [comment]
项目中：
1个饼图和2个柱图
点击饼图联动柱图（2个柱图的维度不一样）可能出现其中一个柱图没有数据的情况，这时需要把没有数据的图清空。

**Comment by pissang** [comment]
这个可以通过 notMerge 设置一个空 option 实现
```js
setOption({}, true)
```

**Comment by shanjixiaboss** [comment]
管他有没有数据都重新去setOption(option, true)
