### ISSUE TITLE
echarts 设定坐标轴0值位置

### ISSUE THREAD

**Issue by woodafire** [ecomfe/echarts#2388]
值有正有负，我希望0值在坐标轴中间，是否可能做到？

**Comment by 100pah** [comment]
可以设置 xAxis  （或yAxis）  的min, max 属性。

**Comment by woodafire** [comment]
数据是动态绑定的，之前并不知道最大/最小值范围。当然我也可以在绑定的时候自己计算出最大/最小值范围来实现，只是比较丑陋，有没有更简单的方法来做呢？

**Comment by pissang** [comment]
暂时没有更便捷的办法。
