### ISSUE TITLE
你们这个3.0 怎么连个事件处理都描述不清了?

### ISSUE THREAD

**Issue by keymao** [ecomfe/echarts#2390]
2.0好歹在犄角旮旯还算是有个示例, 这3.0 API里啥也不通的乱说一气, 示例也没有.

还怎么钻取啊?   就是光好看用的?

**Comment by pissang** [comment]
文档写的还不够清楚？

**Comment by suxuekun** [comment]
没人逼你用的

**Comment by yamakasiluke** [comment]
这个是文档问题，第一眼只能看到event，我来到git才能发现on

**Comment by finalxcode** [comment]
应该在event里面增加对于http://echarts.baidu.com/api.html#echartsInstance.on的描述，这样两部分才能关联，否则就要都浏览一遍才可以发现
