### ISSUE TITLE
请问echarts3可以添加拖动功能吗

### ISSUE THREAD

**Issue by xiedx** [ecomfe/echarts#2392]
就是可以拖动折线上面的点到图表内任意x轴和y轴的位置（上下左右的拖，但是是在轴线上面的），然后可以获取到该点的值，因为有个功能需要有拖动重计算的功能，但是echarts2的拖动重计算线会断掉而且太任意了，获取不到x，y的值。谢谢，不过我也只是问问而已啦，大大们不要在意，这种需求应该比较小吧。

**Comment by pissang** [comment]
暂时不会，谢谢建议
