### ISSUE TITLE
3.0 柱状图平均值不显示具体的数值了？

### ISSUE THREAD

**Issue by qgy18** [ecomfe/echarts#2393]
例如官网这个 demo：http://echarts.baidu.com/demo.html#bar1

<img width="258" alt="screen shot 2016-01-14 at 6 55 52 pm" src="https://cloud.githubusercontent.com/assets/285369/12322707/c461c572-baf0-11e5-97c8-15c4837a0a5d.png">

不显示平均值数值是多少了？

**Comment by pissang** [comment]
这个 bug 已经确认了，下周发的 3.0.1 中修复
