### ISSUE TITLE
charts 3 geo 显示省名问题

### ISSUE THREAD

**Issue by nipao** [ecomfe/echarts#2394]
GEO  全国地图上如何配置显示首名呀
其实我就是想用 markPoint 功能，功能全好，但就是省名 或 省会名无法显示

求解

**Comment by pissang** [comment]
配置 label

**Comment by nipao** [comment]
配置label无效，所以我才提问的

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=map-china 像这个例子？
