### ISSUE TITLE
3.0 的文档缺少对 legend.x 和 legend.y 的描述

### ISSUE THREAD

**Issue by shijialee** [ecomfe/echarts#2400]
2.0 文档里有 
http://echarts.baidu.com/echarts2/doc/option.html#title~legend.x
http://echarts.baidu.com/echarts2/doc/option.html#title~legend.y

但是 3.0 文档里没有。

**Comment by pissang** [comment]
3.0 里组件的定位统一使用 `left`, `top`, `right`, `bottom` 属性
