### ISSUE TITLE
Pie chart NaN 错误

### ISSUE THREAD

**Issue by ephoton** [ecomfe/echarts#2403]
Pie chart 当所有 series 值为零的时候，label显示NaN错误，而且图表显示不够友好（应该向V2那样是一个空心圆）。

**Comment by pissang** [comment]
V2 的空心圆不是因为没数据显示的，只要有拖拽重计算都会显示，实际上数据都为 0 的时候都是什么都不显示的，NaN 是百分比的显示吧？因为都是 0 也计算不出百分比，至于 0 数据也有 hover 的 bug 已经修复了

**Comment by ephoton** [comment]
刚刚测试的时候，master分支上的dist/echarts.js并未有所改善，截图如下：

<img width="637" alt="screen shot 2016-01-15 at 12 47 33" src="https://cloud.githubusercontent.com/assets/3739221/12345616/31e40d40-bb86-11e5-91b4-3876c3633578.png">

**Comment by ephoton** [comment]
虽然NaN可以使用回调处理一下，但是图表没有显示（像V2）有些不太友好，自己做的话，开发效率会低一些

**Comment by ephoton** [comment]
另外，部分数据值为空的时候，其他扇区的Hover的动作可能会收到影响，不太稳定。

**Comment by pissang** [comment]
hover 的问题源代码中修复了，可以等下周 release 新版本。全部为 0 的暂时定为均匀分布。

**Comment by ephoton** [comment]
@pissang 非常感谢～
