### ISSUE TITLE
官网实例那页右边图像和左边标题对应在地图之后全都错误了

### ISSUE THREAD

**Issue by chencl2bj** [ecomfe/echarts#2408]
官网实例那页右边图像和左边标题对应在地图之后全都错误了

**Comment by 100pah** [comment]
没有太理解，可以截个图么？

**Comment by chencl2bj** [comment]
你看下 我这网页都走到K线图了，网页左边栏才显示是饼图。


--
                         祝
                                                       顺利！
                                                                        陈亮

在 2016-01-17 00:00:36，"sushuang" <notifications@github.com> 写道：


没有太理解，可以截个图么？
