### ISSUE TITLE
[3.0]部分默认值可能失效

### ISSUE THREAD

**Issue by spheee** [ecomfe/echarts#2409]
RT，我遇到了一些默认值失效的问题。包括且不仅限于title的color，fontWeight等属性。

**Comment by pissang** [comment]
默认值失效指的是？

**Comment by spheee** [comment]
http://codepen.io/anon/pen/WrZXGj
如此例中，title默认加粗，字体颜色也不是#fff，是否http://echarts.baidu.com/option.html#title.textStyle.fontWeight有误

**Comment by 100pah** [comment]
多谢提醒，doc中title的默认值写得不太对，实际是：
