### ISSUE TITLE
请问3.0地图的showloading取消effect效果了吗？

### ISSUE THREAD

**Issue by shanjixiaboss** [ecomfe/echarts#2410]
RT，谢谢!

**Comment by pissang** [comment]
有 loading 效果，但是不再会有之前浮夸的气泡效果

**Comment by shanjixiaboss** [comment]
哦，后期会有吗，效果还是蛮炫的


来自 魅族小馒头

-------- 原始邮件 --------
发件人：Yi Shen <notifications@github.com>
时间：周六 1月16日 09:46
收件人：ecomfe/echarts <echarts@noreply.github.com>
抄送：shanjixiaboss <shanjixiaboss@163.com>
主题：Re: [echarts] 请问3.0地图的showloading取消effect效果了吗？ (#2410)

**Comment by axiu90** [comment]
@pissang 
你好，
想问下，现在的loading属性里，有对text字体或者大小上的设置属性吗

**Comment by shanjixiaboss** [comment]
http://echarts.baidu.com/api.html#echartsInstance.showLoading

**Comment by starplanet** [comment]
为什么取消了echarts2的effect效果，effect为bubble效果挺好的，为啥要取消？
