### ISSUE TITLE
如何获取图表中的配置(之前的getOption)数据（之前的getSeries）

### ISSUE THREAD

**Issue by bmrainc** [ecomfe/echarts#2411]
如何获取图表中的配置(之前的getOption)数据（之前的getSeries）

**Comment by 100pah** [comment]
可不可以说下，具体想用getOption取什么信息？

**Comment by bmrainc** [comment]
主要是想取得series中的data，我想知道data中点的个数

**Comment by pissang** [comment]
3.0.1 中加回了 getOption http://echarts.baidu.com/api.html#echartsInstance.getOption
