### ISSUE TITLE
建议3.0的文档里面把升级相关的内容写清楚

### ISSUE THREAD

**Issue by stanleyxu2005** [ecomfe/echarts#2415]
比如说，getOption，clear函数在3.0里面没有了，getZrender也没有了。这个在文档里面只字未提。

**Comment by pissang** [comment]
谢谢建议

**Comment by stanleyxu2005** [comment]
我昨天尝试了一下2.x升级到3.x，暂时觉得还是有挑战的。也不单单要补上说这些接口没有了，建议说一下，应该实现这些不再包含的功能。

**Comment by jijiwaiwai** [comment]
现在的getOption 换成什么了……

**Comment by daleyjh** [comment]
看来你们都不去探索一下的，在console里看一下结构体就知道，getOption()用这个方法就可以替代：myChart.getModel().option，其他的方法都可以这么去找到，文档完善需要时间的，现在优先把大bug修完吧，大bug修不完现在都没法升级，升级了还不如ec2的效果。

**Comment by stanleyxu2005** [comment]
@daleyjh 确实哦，你看的比较仔细。

**Comment by pissang** [comment]
getModel 这个方法可以获取到很多内部的信息，暂时没敢公开文档

**Comment by luqin** [comment]
建议多来点文档和 roadmap，发动社区的力量一起完善 echarts。
另外先把500个 issue 解决的差不多了，估计我才敢升级3.0 :joy:

**Comment by pissang** [comment]
@luqin 你别再 npm 上乱发版本，谢谢

**Comment by luqin** [comment]
@pissang 大神给点建议，npm 目录怎么样合适，要不这样？

```
echarts/
  dist
  lib
  src
```

**Comment by liekkas** [comment]
@pissang 怎么不在npm上发布个官方版的？

**Comment by pissang** [comment]
2.x 的时候 webpack，npm 还没现在这么火，echarts 作为一个纯浏览器端的项目就没发在 npm 上，现在 npm 上的 echarts package 是 @luqin 的项目在使用，导致 3.0 发布后无法同步发到 npm 上。

**Comment by stanleyxu2005** [comment]
Register another account e.g. baidu-echarts, echarts3

**Comment by kevinwon1985** [comment]
@luqin npm上原来是你传的。。快把权限转给官方吧。

**Comment by luqin** [comment]
@kevinwon1985 

支持国产开源，后续我会把名字转让给 ecomfe 官方的，最近太忙，后续会专门沟通下。

**Comment by kevinwon1985** [comment]
@luqin 也谢谢你之前的贡献

**Comment by luqin** [comment]
希望官方能够理解我们 npm/webpack 的使用者就好了
