### ISSUE TITLE
series[i]-lines.lineStyle.normal.color 回调函数无效

### ISSUE THREAD

**Issue by starrychan** [ecomfe/echarts#2417]
```js
lineStyle: {
	normal: {
		color: function() {
			return '#fff'
		}
}
```
回调无效，页面上始终显示黑色线条

**Comment by pissang** [comment]
`lineStyle` 是一个系列就一个颜色，所以不支持回调函数，直接设置成 `'#fff'`就行了，像 `itemStyle` 这种每个数据可能颜色会不一样的支持回调函数

**Comment by Galen-Yip** [comment]
@pissang 为啥itemStyle用function的时候只是那些锚点在改颜色，线不改颜色，如果设置成字符串，线的颜色也改动。

**Comment by Galen-Yip** [comment]
参考这两段 @pissang 
```js
itemStyle: {
          normal: {
            color: function(params) {
              return 'red'
            }
          }
        }

itemStyle: {
          normal: {
            color: 'red'
          }
        }
```

**Comment by FullOfVigour** [comment]
![image](https://user-images.githubusercontent.com/25943199/123731959-bfa2a480-d8cb-11eb-8d5e-0471c1c646e8.png)
您好我看文档现在更新说是支持linestyle了，但是为什么我使用之后无效？
使用回调函数的时候
![image](https://user-images.githubusercontent.com/25943199/123732013-d6e19200-d8cb-11eb-8b88-287299580e3f.png)
![image](https://user-images.githubusercontent.com/25943199/123732039-e3fe8100-d8cb-11eb-8a19-51c2653c4723.png)
不使用回调函数的时候
![image](https://user-images.githubusercontent.com/25943199/123732103-fbd60500-d8cb-11eb-8e1d-af2289517bf1.png)
![image](https://user-images.githubusercontent.com/25943199/123732113-fed0f580-d8cb-11eb-8a76-d3b32eff53ee.png)
