### ISSUE TITLE
3.0里map地图的textFixed属性没有用了吗？

### ISSUE THREAD

**Issue by Just-Rookie** [ecomfe/echarts#2418]
面积比较小的区域名字都挤在一起了。2.2.7版本里可以用textFixed来调整标签的位置，但是到了3.0.0里面就没有用了。

**Comment by pissang** [comment]
嗯暂时不支持。

**Comment by Just-Rookie** [comment]
好的。感觉3.0跟2.2.7版本差别挺大的。好多原有的属性都不支持了。

**Comment by pissang** [comment]
@zhump 这个也是可以的，geoJson 的格式也不复杂

**Comment by HelKyle** [comment]
除了修改地图json 还有其他方法吗？[中国地图标注重叠问题](https://github.com/ecomfe/echarts/issues/1535 ) 中提到的方法都失效了
