### ISSUE TITLE
关系图的滚轮缩放为什么反了

### ISSUE THREAD

**Issue by Wangable** [ecomfe/echarts#2419]
往前滚动是缩小，往后滚动是放大？有点儿违反用户习惯吧？而且用mac触控板是两个手指向外缩小，向内扩大，，，怎么改。。。

**Comment by SpiritBreaker** [comment]
鼠标滚轮缩放操作的确是反了，应该是bug

**Comment by pissang** [comment]
已经修复了，谢谢反馈
