### ISSUE TITLE
3.0例子呢

### ISSUE THREAD

**Issue by rabbit8ge** [ecomfe/echarts#2421]
对于像我这样刚刚自学js的来说怎么就没有doc目录了啊，在线的doc只有一个option根本不会啊。

**Comment by isosky** [comment]
初始化一个容器
把option前面加个var
然后echart.setoption(option)就可以了啊

**Comment by pissang** [comment]
入门可以看 http://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts ，原先 example 目录下的示例代码也不适合入门上手
