### ISSUE TITLE
力导向分布图节点大小

### ISSUE THREAD

**Issue by gitdust** [ecomfe/echarts#2422]
nodes 的 value 值决定节点大小，但是给 10000，还是有个固定大小。所以我强制设置  nodes 里面的每个项的 symbolsize 属性大小，但是圆点之间会重叠，如何解决？

**Comment by pissang** [comment]
有 `minRadius`, `maxRadius` 配置项

**Comment by gitdust** [comment]
我想解决是的节点重叠的问题，还有存在连线的两个节点有时靠的太近，连线基本不可见的问题。
