### ISSUE TITLE
请问3.0如何捕获折线图节点的点击事件？

### ISSUE THREAD

**Issue by Mapleaf-C** [ecomfe/echarts#2423]
2.0中src下有一个config文件提供了config.EVENT.CLICK，3.0文档我没有找到对应的条目，此处该如何升级？

**Comment by Mapleaf-C** [comment]
I find it

**Comment by R-River** [comment]
楼主你好，请问最后你是如何解决这个问题的？
2.27的时候我是直接引用
"http://echarts.baidu.com/build/dist/echarts.js" 从而可以按照官网例子配置require.config添加点击事件
3.0后我只找到了单文件引入(下载echarts.min.js到本地然后和html文件放在同个目录下)的方法，不知道如何添加点击事件。。麻烦指点一二，谢谢！

**Comment by pissang** [comment]
3.0 中不用引用这些模块，事件名称就是字符串，例如：

```js
myChart.on('click', function () {});
```

**Comment by R-River** [comment]
@pissang 谢谢！我也看到这项了 不过我之前2.27时实现的 “点击图中的数据点，根据不同的点在另一个div中显示不同的另一幅图” 的功能，我还没有在3.0中实现，感觉无法获取到params的属性一样。

我初学JS，之前的都是看着官网例子照猫画虎写的，勉强能用，升级到3.0以后有些功能找不到例子，就不会了，麻烦您再多指点一下。谢谢！图片还是上传不成功，希望描述的够清楚。

**Comment by Mapleaf-C** [comment]
``this.charts.main.on("click",function(params){
	_this.indexMinors(params.dataIndex);
});``
我这边是可以拿到params的啊

**Comment by R-River** [comment]
@Mapleaf-C 谢谢 应该是我没有整体学习过JS 全部都是照着官网demo模仿出来的 有些东西不了解。。。我再试试！

**Comment by R-River** [comment]
@Mapleaf-C  @pissang 多谢指点！我搞定了~

**Comment by sparkle777** [comment]
我也要实现 “点击图中的数据点，根据不同的点在另一个div中显示不同的另一幅图” 的功能。可是移动端上，数据点很难点。请问你有遇到这个问题吗？

**Comment by zchuhui** [comment]
试了试 `myChart.on('click', function () {});` 这个方法，饼形图是可以的，但折线图不行。

[ECharts 中的事件和行为](http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA)
看了上面的官方案例，好像也是只有饼形图可以。

对于折线图有解决方案吗？

@Mapleaf-C @pissang
