### ISSUE TITLE
echart3没有数据的提示动画实现

### ISSUE THREAD

**Issue by sunshine1987** [ecomfe/echarts#2424]
在echart2可以在初始化的时候设置noDataLoadingOption实现无数据提示动画，请问在echart3中怎么配置

**Comment by pissang** [comment]
3 中不再支持 noDataLoadingOption

**Comment by hardywen** [comment]
@pissang 我想问下，是不支持这个noDataLoadingOption配置项还是完全就放弃了【无数据状态】这种效果？现在没数据的话就一片白，很不好看啊
