### ISSUE TITLE
3.0 markLine ：average 算法错误，只计算(Max-Min)/2

### ISSUE THREAD

**Issue by dawei80** [ecomfe/echarts#2425]
3.0的markLine平均线算法错误

带入Demo页面：
http://echarts.baidu.com/demo.html#scatter-weight

带入值：

option = {

    title : {
        text: '平均值错误', 
    },
     
    tooltip : {
        trigger: 'axis',
        showDelay : 0,
 
    },
 
    xAxis : [
        {
            type : 'value',
            scale:true,
           
           
        }
    ],
    yAxis : [
        {
            type : 'value',
            scale:true,
        }
    ],
    series : [
       
        {
 
            type:'scatter',
            data: [[12,1], [13,2],[14,3],[15,4],[16,5],[17,6],[18,7],[19,8],[20,9],[30,100]
            ],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            }
        }
    ]
};

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/commit/ebdf6ad13505efebe4f5b450b3cc086c76099f4f 中修复了

**Comment by onlyfew** [comment]
请问能设置忽略掉部分0值计算平均值吗？ 部分业务上0值不应计算。  或者可以自己指定某个固定的值。 @pissang
