### ISSUE TITLE
X轴设置了interval,min,max之后最后一个刻度标签不显示

### ISSUE THREAD

**Issue by whahuzhihao** [ecomfe/echarts#2430]
设置 min:0 max:24 \* 3600 - 15 \* 60 + 1
设置label的format函数为格式化分钟，结果最后一个23:45只有刻度，没有标签，实际上format函数也运行到了

**Comment by pissang** [comment]
在设置 min(max) 的时候有可能产生 min(max) 刻度和倒数第二个刻度叠加的情况，这时候忽略 min(max) 刻度的显示。
