### ISSUE TITLE
所有地图实例代码拷贝到自己页面中都不能正确显示

### ISSUE THREAD

**Issue by QinW** [ecomfe/echarts#2432]
所有地图实例代码拷贝到自己页面中都不能正确显示：只能显示放大的部分地图，而且不显示地图边框。
![screenclip](https://cloud.githubusercontent.com/assets/1419498/12387138/5784eeb2-be05-11e5-8990-cce08a5a5e09.png)
![screenclip2](https://cloud.githubusercontent.com/assets/1419498/12387163/84fd59ce-be05-11e5-8fd1-d8ded559a093.png)

**Comment by pissang** [comment]
地图类型需要加载地图数据。http://echarts.baidu.com/api.html#echarts.registerMap
