### ISSUE TITLE
echarts3 设置theme为什么无效？

### ISSUE THREAD

**Issue by sunsnow8** [ecomfe/echarts#2441]
var myChart = echarts.init(document.getElementById('my_chart'),'macarons'); 这样设置theme为什么无效呢

**Comment by pissang** [comment]
echarts3 不再内置主题，需要传入主题对象或者先注册再使用。

```js
echarts.registerTheme('macarons', {
    color: ...,
    ...
});
var myChart = echarts.init(document.getElementById('my_chart'),'macarons');
```

**Comment by sunsnow8** [comment]
非常感谢你的回复！！

**Comment by Flourad** [comment]
@pissang 我在react里这么用了之后，主题还是没有生效~

**Comment by deathfang** [comment]
theme 里面能不能把
```javascript
 // CommonJS
        factory(exports, require('echarts'));
```
改成 `reuqire('echarts/lib/echarts')` 

以免使用一个主题会引入echarts全部组件

**Comment by phping1** [comment]
自己亲测是可以生效的，步骤如下：
1.去echarts官网：http://echarts.baidu.com/download-theme.html下载主题js:macarons.js
2.在view里把macarons.js加载进来
3.初始化mychart对象myChart = echarts.init(document.getElementById('main4'),'macarons')即可。

**Comment by mrerhuo** [comment]
vue项目第一次正常。第二次之后样式都不正常还是默认的。
