### ISSUE TITLE
3.0.1  更新后 饼图的自定义color顺序 被打乱

### ISSUE THREAD

**Issue by alanhoukj** [ecomfe/echarts#2442]
首先感谢开发人员那么迅速的更新了新版本 。
 #2372 修正之后，出现了另一个问题
在option中间定义了自己的color 顺序之后，显示时顺序被打乱，在3.0.0 时没有错误

color: [ '#473792','#8861A7','#BBA2CC', '#4CBCB8','#76C7CB','#C1E5E1'],

**Comment by pissang** [comment]
截图看下？

**Comment by alanhoukj** [comment]
您好,我用了你们的一个demo http://echarts.baidu.com/demo.html#pie-nest
做了测试 
在option 里面 添加  

```javascript
color: [ '#473792','#8861A7','#BBA2CC', '#4CBCB8','#76C7CB','#C1E5E1'],
```

您就可以看到效果了，因为之前没有上传过图片，所以不知道附件能不能看到。
![echarts](https://cloud.githubusercontent.com/assets/3330658/12413820/7a439594-becc-11e5-917a-5407f5772315.png)

图中明显内外环的颜色顺序不一样~ 麻烦啦

**Comment by pissang** [comment]
这个是 3.0.1 里改成跟 3.0 里一样的逻辑了，每个扇区会依次取全局的调色盘中的颜色，如果要内外环一样的话可以每个系列都设置自己的调色盘。

```js
series: [{
  type: 'pie',
  color: [ '#473792','#8861A7','#BBA2CC', '#4CBCB8','#76C7CB','#C1E5E1']
}, {
  type: 'pie',
  color: [ '#473792','#8861A7','#BBA2CC', '#4CBCB8','#76C7CB','#C1E5E1']
}]
```

**Comment by alanhoukj** [comment]
哦 好的~ 成功了~   非常感谢！！
