### ISSUE TITLE
BUG! 刚才下了Echarts3.01还是有联动问题  曲线图 tooltip.trigger设定为axis，进行多图联动时随动的图表坐标轴指示器定位错误 

### ISSUE THREAD

**Issue by HaiYuanQi** [ecomfe/echarts#2445]
bug重现条件
1、当被联动的图表宽度不等于触发图表的宽度
2、鼠标悬停点不要正好在数据点上

注：可以把鼠标从别的位置移动到数据点，看联动图表的tooltip的变化

![Uploading xx.png…]()

**Comment by Mapleaf-C** [comment]
我这边有类似问题，两张connect的表同时响应了对应位置的hover事件，包括toolBox
![image](https://cloud.githubusercontent.com/assets/8221466/12412228/16db887e-bec0-11e5-9952-7302040c5ee8.png)

**Comment by HaiYuanQi** [comment]
对没错，我还没看源码，估计是根据鼠标位置模拟触发了，关联图表的mousemove，却没有根据比例计算相对位置，
...为啥我上传不了图片了...

**Comment by Mapleaf-C** [comment]
你提交的太快了正在上传

**Comment by Dylaneal** [comment]
求助，要如何解决这个问题呢
