### ISSUE TITLE
echarts不支持cmd打包问题

### ISSUE THREAD

**Issue by brucecham** [ecomfe/echarts#2446]
# echarts不支持cmd打包问题  
#### echarts既然是开源的，为什么不更开放些呢，以commonjs格式书写，让用户自由构建，这样的话，不管项目中用的是哪种加载器，都能完美使用

**Comment by pissang** [comment]
想要用 CMD 的话用构建好的代码

**Comment by brucecham** [comment]
#### 构建好的代码不能适应场景，项目底层对id路径有映射，不如友好些，open为commonjs更开源

**Comment by luqin** [comment]
@brucecham 要不我们开干，整成 ES6 版？然后 Babel 转换为 AMD/commonJS/UMD 等各种格式？

**Comment by brucecham** [comment]
@luqin 这想法不错，自动转es6还是手工转，echarts3里面的bug还有很多，不健壮，有没有自动转换的思路？

**Comment by luqin** [comment]
@brucecham 

基本的语法是可以转换的，但是如果不从根本解决问题，可能达不到预期效果。比如 `for of` 各种语法没法自动转。
