### ISSUE TITLE
bug反馈：一个Echart实例多个饼图动态setOption报ID重复

### ISSUE THREAD

**Issue by adamed** [ecomfe/echarts#2452]
bug重现示例：
http://jsbin.com/kidificifi/1/edit?html,output

描述：
如果在初始化设置Option时在series数组中设置多个饼图实例，在结果中可以看到多个饼图。
但是如果是在异步等动态修改setOption设置series的值时，Echart报错，压缩文件内提示id重复。

**Comment by SuperZDev** [comment]
@adamed 

这个情况是因为添加多个序列，没有指定series序列每项的name值，造成的。因为name值是用来

> 系列名称，用于tooltip的显示，legend 的图例筛选，在 setOption 更新数据和配置项时用于指定对应的系列。

顺便给你看一个[https://jsfiddle.net/SuperZ/599ewvdg/](https://jsfiddle.net/SuperZ/599ewvdg/)

PS:**这种多序列情况下，如何处理好呢？**

**Comment by Dave-SEO** [comment]
谷歌浏览器最小化后再打开就显示空白,尤其做实时数据展示时

**Comment by Dave-SEO** [comment]
echart 谷歌浏览器最小化后再打开就显示空白，尤其是开定时实时获取数据，或者用socket.io，其他浏览器不会
