### ISSUE TITLE
改变所有data的颜色legend并没有改变

### ISSUE THREAD

**Issue by HanSon** [ecomfe/echarts#2459]
对每个data的颜色进行设置，然而legend上的颜色还是默认颜色，也没有改变颜色或者让其消失的接口

**Comment by Hanccc** [comment]
找到消失的接口，但没有找到改变颜色的方法

**Comment by Ttou** [comment]
同问，legend里每个data的颜色不会随着series颜色的改变而改变，也没有可配置的选项
