### ISSUE TITLE
toolbox点击还原，然后再进行line和bar之间的切换，lengend第一个会丢失

### ISSUE THREAD

**Issue by brucecham** [ecomfe/echarts#2470]
toolbox点击还原，然后再进行line和bar之间的切换，lengend第一个会丢失，点击还原会正常恢复，再点击切换，还是丢失

**Comment by SuperZDev** [comment]
lengend并没有丢啊，不过markLine和markPoint全丢失了。肯定是个BUG

**Comment by pissang** [comment]
已修复
