### ISSUE TITLE
echarts3.0，通过npm安装的的包，里面缺少lib

### ISSUE THREAD

**Issue by kevinwon1985** [ecomfe/echarts#2474]
echarts3.0，通过npm安装的的包，里面缺少lib。而package.json里配置的是"main": "lib/echarts"。所以一旦require('echarts'), 就会出错。

**Comment by SuperZDev** [comment]
@kevinwon1985 npm不是官方包，请不要从npm安装。

**Comment by kevinwon1985** [comment]
@SuperZDev 那么建议增加npm支持，目前webpack的出现，通过npm管理包，通过webpack打包的模式非常普遍了。

**Comment by SuperZDev** [comment]
@kevinwon1985 [请看pissang的回复](https://github.com/ecomfe/echarts/issues/2415)
