### ISSUE TITLE
在echarts3中实时渲染图表的同时，tooltip会隐藏一会再显示。

### ISSUE THREAD

**Issue by think2011** [ecomfe/echarts#2478]
在之前的版本中不存在这个问题。

我的需求是这样的，通过给tooltip插入一个input，用户change了input的时候，就会实时更新echarts3的设置，从而实时看到图表的变化。

但是在echarts3版本中，tooltip 会隐藏一会再重现。

比较困扰，求解答。:-)

![demo](https://cloud.githubusercontent.com/assets/3961388/12501938/31365664-c0fe-11e5-8a32-aef275c1b6ca.gif)

**Comment by pissang** [comment]
这个问题是因为刷新的时候 tooltip 会重置，然后需要鼠标移动才能触发，可以在 setOption 后再通过 dispatchAction 重新显示 tooltip，后续优化这个问题

**Comment by think2011** [comment]
嗯 谢谢

**Comment by think2011** [comment]
赞！
