### ISSUE TITLE
echarts 3.0.1 中 resize 方法对高度不管用

### ISSUE THREAD

**Issue by benleilei** [ecomfe/echarts#2479]
更改了 dom 的 style.height ，调用 chart.resize() 不管用，高度没有变（宽度变化了）

使用 jQuery 改的的 dom，大致代码如下
// 初始 element dom， height：100px width：100px
var chart = ECharts.init(element$[0]);
element$.css({ height: '200px', width:  '200px' });
chart.getHeigth() // 100
chart.resize()
chart.getHeight() // 200

getHeight 获取的值变化了，但是实际图表在页面上高度没有变化，查看它的 canvas 的 height 属性没有变，还是 100
<canvas width="200" height="100" .......

**Comment by SuperZDev** [comment]
@benleilei 并没有发现这样的问题啊，resize是正常反应的。

**Comment by Holybasil** [comment]
我也遇到这个问题了  "echarts": "^4.2.0-rc.2"
