### ISSUE TITLE
ECharts 3.0 没有对多地图进行支持？

### ISSUE THREAD

**Issue by TbeAst** [ecomfe/echarts#2488]
找了半天没找到3.0多地图，以前2.0上的多地图怎么可以更新到3.0版本？谢谢。

**Comment by pissang** [comment]
支持的，多个不同地图类型的地图系列可以实现多地图，如果要相同类型的显示多个，可以用 geo 组件，地图图表为了跟 2.x 保持相同暂时不支持

**Comment by TbeAst** [comment]
支持像2.0那样，点击省份直接出现全省地图吗？

**Comment by SuperZDev** [comment]
@TbeAst  随便写了一个，你看看[https://jsfiddle.net/SuperZ/redpp4fr/](https://jsfiddle.net/SuperZ/redpp4fr/)

@pissang  为什么mapselected事件不能触发呢？还有我用click事件代替之后，怎么选中例如：“新疆”呢？

**Comment by TbeAst** [comment]
@SuperZDev click事件确实没有效果，希望@pissang 可以fix这个bug。

**Comment by pissang** [comment]
@SuperZDev 3.0 中 map 点击事件改为 [mapselectchanged](http://echarts.baidu.com/api.html#events.mapselectchanged) 了

**Comment by superddr** [comment]
mapselectchanged 事件有示例代码么，目前无法触发。。。
