### ISSUE TITLE
3.0 版本之后不再提供 doc 了吗？

### ISSUE THREAD

**Issue by guiquanz** [ecomfe/echarts#2492]
Echarts 2.X 发行包中都提供了 doc，包含各类文档。请问 3.0 之后不再提供 doc 了吗？谢谢！

**Comment by SuperZDev** [comment]
我自己down了一个官网的文档，你可以看一下[echarts-doc-offline](https://github.com/SuperZDev/echarts-doc-offline)，和官网是一个结构。

以后可能会提供吧，现在fix bug,add feature为主的。

**Comment by guiquanz** [comment]
谢谢。我之前试了 wget 、SiteSucker 等工具进行镜像，不过文档不完整。如果有官方提供完整文档，那就最好了。期待……

**Comment by pissang** [comment]
@SuperZDev 提供的可以用
