### ISSUE TITLE
3.0 toolbox 切换图形类型时发现问题

### ISSUE THREAD

**Issue by zhump** [ecomfe/echarts#2493]
在点击toolbox  切换柱图时，legend由4个变成了3个，而且没有全部显示为柱图，还有个问题，就是在双击（故意）一个切换图形的图标（line）时，再点击另外一个图形的图标（bar），页面有js错误。。
错误如下：
Uncaught Error: id duplicates:  series.bar|太低气温|0   echarts.js?bust=1453654838575:3818
# 

另外想咨询一下，3.0有没有暴露的方法，直接切换图形类型，而不是一定要点击toolbox 按钮才可以。谢谢！

配置项如下

``` js
option = {
    "legend": {
        "data": ["最高气温", "最低气温", "超低气温", "超高气温"]
    },
    "toolbox": {
        "feature": {
            "magicType": {
                "type": ["line", "bar"]
            }
        }
    },
    "xAxis": [{
        "type": "category",
        "data": ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]
    }],
    "yAxis": {},
    "series": [{
        "name": "最高气温",
        "type": "line",
        "data": [31,35,41,42,11,17,18]
    }, {
        "name": "最低气温",
        "type": "bar",
        "data": [11,15,11,12,11,7,18]
    }, {
        "name": "超低气温",
        "type": "bar",
        "data": [21,15,21,22,12,7,12]
    }, {
        "name": "超高气温",
        "type": "line",
        "data": [21,15,21,22,12,7,12]
    }]
}
```

另外。。3.0很棒，66666

**Comment by SuperZDev** [comment]
[#2491](https://github.com/ecomfe/echarts/issues/2491)

切换有问题，toolbox的action现在文档上提供的只有restore，我看代码里已经加入了相关的action。

	chart.dispatchAction({
	      type: 'changeMagicType',
	      currentType: 'bar'
	  });
不过看来这块还是有问题的，跟跟代码吧。

**Comment by pissang** [comment]
还有一个 newOption 的参数，不过其实没必要了，setOption 能实现相同的功能
