### ISSUE TITLE
3.0版本目前是不是不适合在上线项目中用？

### ISSUE THREAD

**Issue by bi-kai** [ecomfe/echarts#2504]
官网文档还比较简单，还在频繁更新中，是不是项目中还是要用2.2.7版本的？
另外，文档中说3.0支持IE8，但用IE8又提示“请升级浏览器”，3.0到底兼不兼容IE8呢？

**Comment by pissang** [comment]
只是官网不支持 IE8，echarts 本身支持，官网文档简单确定有仔细看文档么？

**Comment by brucecham** [comment]
感觉还差点火候，小问题多多，还不健壮，过两个月再来看看
