### ISSUE TITLE
AMD build for ECharts 3.0

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#2505]
Hi ECharts! 
Awesome to see 3.0, demos look amazing!

One thing I'm interested to know is whether it is still possible to build Echarts with chart types as different modules (files). 

In 2.x, it is possible to load minimal echarts.js and then include chart types based on whether it was used or not. 

Your web based builder seems to always create one file with all selected features. However, it would be good to be able to load charts dynamically. The dist folder also doesn't seem to have charts subfolder anymore. Is there any reason for that? And is there any way to load minimal ECharts and then decide what other features to load in runtime? 

Thanks a lot, looking forward to use 3.0!

**Comment by pissang** [comment]
Hi Jarben, although 2.x support chart dynamic loading, the minimal echarts.js is still very large. The size is almost 400k. And I think it's difficult to achieve small core size after built, or we need to move common modules shared with several charts to each charts built, which will cause redundancy. So I suggest if you wan't to be able to load charts dynamically, load the source code with RequireJS, or any library else supporting loading AMD module.

Thanks for the support.

**Comment by jarben** [comment]
Hi Pissang, 
thanks for your answer - makes sense, will now jump into testing it:)
Thanks, 
Jaro
