### ISSUE TITLE
【请教/急】TreeMap 叶子节点的颜色能不能按照自定义的算法进行映射？

### ISSUE THREAD

**Issue by hustcer** [ecomfe/echarts#2509]
请教下`TreeMap` 叶子节点的颜色能不能按照自定义的算法进行映射？我想做一个类似于[这样](http://finviz.com/map.ashx)的矩形图, 叶子节点是股票，股票涨幅大于0时用红色，小于0时用绿色。但是做的时候发现渲染的颜色按照某种原则自动分配的，设置`colorMappingBy` `“value”`后发现好像没有地方改具体的股票颜色映射方式？文档看得也不是很明白，还是不支持自定义颜色映射方式？ 非常感谢！

**Comment by 100pah** [comment]
现在不能按照自定义算法映射，但是这个例子有意义，所以接下来计划加上这个功能

**Comment by hustcer** [comment]
敬候佳音

**Comment by hustcer** [comment]
@100pah 这个issue快一年了哦, 有啥进展么？

**Comment by wu11106** [comment]
谢谢你！


2016年11月5日星期六，Justin <notifications@github.com> 写道：

**Comment by wu11106** [comment]
请问他与郑晶兰有没有来往

2016年11月5日星期六，Justin <notifications@github.com> 写道：

**Comment by 100pah** [comment]
不好意思时间有点长。。

增加了个配置，参见这个例子：
<https://github.com/ecomfe/echarts/blob/master/test/treemap-visual.html>

**Comment by hustcer** [comment]
@100pah 看到了，谢谢，还有几个问题：

1. 我看文档中对于`colorMappingBy` 值映射的描述是"将节点的值映射到颜色列表中。这样得到的颜色，反应了节点值的大小。"， 不知道内在的机制是什么？如果值集合元素数目大于颜色集合元素数目的时候采用线性插值计算颜色么？
2. 由于“treemap中 color 属性可能在多处地方存在”，每个节点的itemStyle可以有特定设置，如果修改所有节点的itemStyle里面的color，是不是也可以达到个性化配置各个节点颜色的目的？后续数据如果发生变化我重新计算每个节点的颜色然后通过 `setOption`就可以了？
3. 我看你新增的例子中有`echarts.number.linearMap` / `echarts.format.addCommas`，这个官方文档库里面好像没有说明？

辛苦了~

**Comment by hustcer** [comment]
好的，非常感谢！
