### ISSUE TITLE
echarts.dataTool is undefined

### ISSUE THREAD

**Issue by zuoez02** [ecomfe/echarts#2511]
用的完整版的echarts.min.js,但是没有找到echarts.dataTool

**Comment by zuoez02** [comment]
刚把dataToool引进了,问题解决了

**Comment by quentinchen** [comment]
怎么解决的呢？ @ zuoez02

**Comment by zuoez02** [comment]
@quentinchen 在官方示例里面开开发者工具找到了这个dataqTool的js文件，下载下来引入就行了，没在官网里找到

**Comment by quentinchen** [comment]
@zuoez02 我也已经解决了。
我把解决方案写在知乎里面了，留给后来的人看吧，传送门：
[如何在Echarts的关系图中正确的引用dataTool而不报错？——知乎](https://www.zhihu.com/question/41690502/answer/94006620)
