### ISSUE TITLE
radar配置项series:[{type:'radar'},...]文档缺失

### ISSUE THREAD

**Issue by huangdeyun** [ecomfe/echarts#2514]
详见http://echarts.baidu.com.cn/option.html#series

麻烦补充一下radar的series说明

**Comment by pope12389** [comment]
3.0以上版本没有radar了？

**Comment by jialanmo** [comment]
源码里有radar的demo：https://github.com/ecomfe/echarts/blob/master/test/radar.html
但是网站里一直没有radar的实例，也没有文档，估计是还没完善好吧
我现在也是因为要用radar还在用2.0，没升上来
