### ISSUE TITLE
[dist/echarts.js] Uncaught TypeError: Cannot assign to read only property 'dataZoom' of dark

### ISSUE THREAD

**Issue by luqin** [ecomfe/echarts#2516]
```
    <script src="../dist/echarts.js"></script>
    <script src="../theme/dark.js"></script>
```

```
    var chart = echarts.init(document.getElementById('main'), 'dark');
```

**Comment by zuoRambo** [comment]
echarts版本是哪个 另外dark.js写法有问题吧

**Comment by luqin** [comment]
版本是3.0.2
`dark.js`是官方原版代码
浏览器为 Chrome

**Comment by zuoRambo** [comment]
@luqin 那应该是**bug**吧 我通过`npm install echarts`安装echarts 没有找到theme目录 却在package.json中看到了你的信息 还请解疑

**Comment by luqin** [comment]
暂时我维护的npm :joy:

**Comment by zuoRambo** [comment]
额 感谢你在npm上的publish zrender现在交由EFE团队后 更多的是为echarts提供底层绘制、操作canvas支持吧 估计作为一个类库已经很少被单独引入使用了吧～

**Comment by pissang** [comment]
@luqin 你这样不肯把 npm echarts package 转回给我们还自己瞎发版本号，我们就无法让其他人通过 npm 渠道安装 echarts，希望你能认识到这一点，谢谢
