### ISSUE TITLE
echarts2.x -->地图-->markPoint,

### ISSUE THREAD

**Issue by gaoyaxin** [ecomfe/echarts#2518]
refer to http://echarts.baidu.com/echarts2/doc/example/map9.html
问题：
1.鼠标放在拉萨上，显示拉萨的数值；当鼠标放在西藏时，能否也显示相关数值呢？不是 西藏:-
2.如果第一条实现由难度，能否鼠标放在西藏任何一个地点(拉萨除外)，只显示省份名称

**Comment by pissang** [comment]
在有数据的时候才会显示数值
