### ISSUE TITLE
echarts3 不支持jquery的id获取方式

### ISSUE THREAD

**Issue by nsnake** [ecomfe/echarts#2520]
初始的时候要指定容器
文档中使用
var myChart = echarts.init(document.getElementById('charts'));

通常情况下，如果项目使用了jquery的，会使用
var myChart = echarts.init($("#charts"));
但如果这样做，会出现问题
Object [object Object] has no method 'getContext' 
不知道是否可以解决

**Comment by zhump** [comment]
$("#xx")[0]

**Comment by nsnake** [comment]
非常感谢
