### ISSUE TITLE
怎么禁止例子中空气质量散点图的拖动？

### ISSUE THREAD

**Issue by hardenCN** [ecomfe/echarts#2524]
怎么禁止例子中空气质量散点图的拖动？

**Comment by zhump** [comment]
哪一个例子

**Comment by hardenCN** [comment]
@zhump  这个例子http://echarts.baidu.com/demo.html#effectScatter-map  这个中国地图能拖动，如果放到手机上拖动就很不爽了，我想去掉。

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#geo.roam>
