### ISSUE TITLE
Surface Pro3 win10 x64 Chrome 47/48 版本 echarts 3.0所有图形的鼠标交互无效

### ISSUE THREAD

**Issue by yangpu** [ecomfe/echarts#2528]
Win10 64位操作系统Chrome47/48版本上echarts 3.0的所有示例鼠标交互都无效（不能选择/缩放/拖动，无Tooltip，不能点击按钮）。控制台无错误输出，将实例下载到本地运行同样问题。

同一台电脑上IE/Firefox没有这个问题，将Chrome版本从47升级到48没有解决问题，苹果笔记本上的Chrome没有问题。

**Comment by hanhui** [comment]
我也是这个问题，IE、Firefox浏览器也是这样

**Comment by yangpu** [comment]
echarts 2.0在chrome上运行无问题，3.0出现异常，应该是普遍问题，请开发团队关注一下。

**Comment by pissang** [comment]
是不是带有触屏的电脑？

**Comment by yangpu** [comment]
我的环境是 Surface Pro 3，有触屏，我认为这个问题与#2569是同样的原因。

**Comment by iamziyue** [comment]
我也是跟楼主环境一样，现象一样，Chrome内核浏览器能显示图表，但是没有交互，就跟一张图片一样。自带Edge没有问题。
