### ISSUE TITLE
默认配色有重复颜色

### ISSUE THREAD

**Issue by wellyyang** [ecomfe/echarts#2530]
默认为：
['#c23531', '#314656', **'#61a0a8'**, '#dd8668', '#91c7ae', '#6e7074', **'#61a0a8'**, '#bda29a', '#44525d', '#c4ccd3']

[http://echarts.baidu.com/option.html#color](http://echarts.baidu.com/option.html#color)

**Comment by SuperZDev** [comment]
原以为是文档写错了，结果globe里果然写的也是重复滴。改成黑色吧，哈哈哈
