### ISSUE TITLE
echarts3.0里面 map地图 series中的nameMap 属性哪去了？相关API问题反馈

### ISSUE THREAD

**Issue by oneroundseven** [ecomfe/echarts#2543]
RT 在2.0时期的时候是有映射配置的，3.0中的映射配置哪去了？ 是删掉了吗？ 有没有其他代替方案

发现API漏了漏了一个东西，还有API里面好多东西不全。

![111](https://cloud.githubusercontent.com/assets/1825295/12665282/a4fcd992-c671-11e5-9582-c92f0a447b6e.jpg)

http://echarts.baidu.com/demo.html#map-world-dataRange 这个示例里面有个API在API文档中也没有提及，这个是2.0版本的 如果继承过来的话 新的API中最好体现，不然会误导用户。
![222](https://cloud.githubusercontent.com/assets/1825295/12665332/f80d3d2a-c671-11e5-906f-5bf3b8daa318.jpg)

**Comment by pissang** [comment]
nameMap 是有的，文档中遗漏了

**Comment by oneroundseven** [comment]
@pissang 谢谢回答，性能提高的同时，希望API也能越来越完善，支持国产！

**Comment by pissang** [comment]
谢谢建议
