### ISSUE TITLE
请问Echarts的柱状图有没有drilldown功能呢?

### ISSUE THREAD

**Issue by AnneWQ** [ecomfe/echarts#2545]
就是点击柱状图里面的某个柱子  会显示 另一个柱状图（关于这个柱子的细节内容）；
我看了bar chart的例子 没有找到类似功能

**Comment by R-River** [comment]
我是写了多个option 根据点击的dataName不同 在不同的div中切换 类似下面这样 希望有所帮助

`myChart.on('click', function(param){
			if (param.name == '基本情况') {
				showhidediv('id2');
			}
			else if (param.name == '人力资源规划') {
				showhidediv('id3');
			}
			else if (param.name == '招聘与配置') {
				showhidediv('id4');
			}  
			//else if (param.name == '绩效考核管理') {
				//showhidediv('id6');
			//}
			else if (param.name == '薪酬福利管理') {
				showhidediv('id6');
			}
			else if (param.name == '员工关系管理') {
				showhidediv('id7');
			}
			else if (param.name == undefined) {
				showhidediv('id1');
			}
		});
`
