### ISSUE TITLE
echarts3版本的精简版我要再加载map组件要怎么弄

### ISSUE THREAD

**Issue by chaegumi** [ecomfe/echarts#2548]
ECharts 3 开始不再强制使用 AMD 的方式按需引入，代码里也不再内置 AMD 加载器。因此引入方式简单了很多，只需要像普通的 JavaScript 库一样用 script 标签引入。

有没有使用示例

**Comment by chaegumi** [comment]
我现在用的是echarts-m版本的map组件出现以下所示错误，不会升级到echarts3
Uncaught TypeError: t.toFixed is not a function
e._textFormat	@	map.js:formatted:1787
e.__onhoverlink	@	map.js:formatted:1781
r._onhoverlink	@	map.js:formatted:1145
t.dispatchWithContext	@	VM967:formatted:5974
_messageCenter.dispatch	@	VM967:formatted:657
i._onmouseover	@	VM967:formatted:776
_onzrevent	@	VM967:formatted:671
t.dispatch	@	VM967:formatted:5945
f._dispatchAgency	@	VM967:formatted:6347
f._processOverShape	@	VM967:formatted:6325
s	@	VM967:formatted:6039
(anonymous function)	@	VM967:formatted:6015
(anonymous function)	@	VM967:formatted:6371
g.mousemove	@	VM967:formatted:6116
(anonymous function)	@	VM967:formatted:6010

**Comment by SuperZDev** [comment]
额。2.x也不是非需要amd方式引入。3.x没有打入esl，所以你可以用支持amd的javascript引入echarts。还有你要什么示例？

**Comment by chaegumi** [comment]
```javascript

require(
						[
							'echarts',
							'echarts/chart/line'
						],

```

像这样的组件要自己打包吗？还是直接引入 src中的路径？

**Comment by pissang** [comment]
3 里除了源代码都不再使用按需加载，不然要不就是像 2 一样将通用的模块打包到一个 core 里导致 core 体积很大，要不就是构建的组件之间会有很多冗余的代码。

可以在在线构建中 http://echarts.baidu.com/builder.html 选择需要的组件进行构建。
