### ISSUE TITLE
ECharts 3.0 Bar 圆角设置

### ISSUE THREAD

**Issue by macing** [ecomfe/echarts#2550]
上一版本可设，但是 3.0 似乎没有了。

**Comment by SuperZDev** [comment]
是的。这版木有圆角，最起码是目前没有。以后如果社区反应强烈，估计会加的。

**Comment by macing** [comment]
有了圆角外加设置bar的宽度，就可以做 iOS 进度条那种样式的bar。这个设计简洁，还是有很多人喜欢的。谢谢。

**Comment by SuperZDev** [comment]
@macing，加了圆角属性了。囧

**Comment by macing** [comment]
谢谢，你们的效率真高 😊 @SuperZDev 

![2016-02-03 20 17 45](https://cloud.githubusercontent.com/assets/14910958/12782299/2f5ec360-cab5-11e5-97d5-2006176cd242.png)

**Comment by SuperZDev** [comment]
不要误会，我不是他们团队的，只是看到有些小问题就帮忙回复一下，以后还是少帮忙回复了，以免误会。请感谢@pissang他们团队 
祝用的开心

**Comment by pissang** [comment]
@SuperZDev 也要感谢你帮我们给其他人答疑解惑。
