### ISSUE TITLE
关于 test/theme.html  的主题问题

### ISSUE THREAD

**Issue by zhaoyangsoft** [ecomfe/echarts#2563]
修改 theme/dark.js 中的 backgroundColor 属性值后没有效果，
是不是哪个逻辑没通?

**Comment by SuperZDev** [comment]
@zhaoyangsoft  
你没发现写错了吗？
去掉注册这句：
`echarts.registerTheme('dark', theme);`

**Comment by pissang** [comment]
test 下的 theme.html 确实写错没改过来，谢谢 @SuperZDev 指出

**Comment by zhaoyangsoft** [comment]
恩，谢谢 ， @SuperZDev 
发现了，但没想到是个错了， 还想着为啥写2便这么怪的设计呢
