### ISSUE TITLE
地图如何设置位置？

### ISSUE THREAD

**Issue by soapyu** [ecomfe/echarts#2564]
echarts2有个mapLocation的属性可以设置地图在图表中的位置。在echarts3中没有找到相关属性，地图只能在默认位置显示。

**Comment by pissang** [comment]
没有 mapLocation 了，统一使用 left, top, right, bottom, width, height 几个属性布局

**Comment by soapyu** [comment]
请教下，是在哪个配置项底下设置呢？

**Comment by pissang** [comment]
系列下
