### ISSUE TITLE
barGap配置不起作用

### ISSUE THREAD

**Issue by SpiritBreaker** [ecomfe/echarts#2565]
在barGird.js里，
var autoWidth = (remainedWidth - categoryGap)/ (autoWidthCount + (autoWidthCount - 1) \* barGapPercent); 
autoWidthCount 初始是1，导致barGapPercent没起作用啊这个公式。

``` js
option = {
    xAxis : [
        {
            type : 'category',
            data : ['总费用','房租','水电费']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'辅助',
            type:'bar',  
            barGap:'100%',   //不起作用
            data:[10, 1700, 1400]
        } 
    ]
}
```

**Comment by echoloyuk** [comment]
你的意思应该用barCategoryGap吧。另外，我用了barGap，只有写在最后一个series上才有效

**Comment by R-River** [comment]
即使把barGap设为0 当barGategoryGap不够大 不能和barWidth共同填满xAxis每个类目所分配的宽度时(即xAxis两个splitLine中间的宽度) barGap依然会有值 并不是0 

所以是barGap barCategoryGap和barWidth三者共同填满xAxis每个类目所分配的宽度(即xAxis两个splitLine中间的宽度) 所以可以设置barGap为0 barGategoryGap保持默认 让barWidth自适应剩下的宽度即可使每个xAxis类目中的柱形之间没有间隔 不过我这里看起来会有一点点重叠 还不知是什么情况
