### ISSUE TITLE
Tooltips and interactivity not available in Chrome 48 /Ubuntu but working in Firefox

### ISSUE THREAD

**Issue by devldevelopment** [ecomfe/echarts#2569]
Hello when using chrome Version 48.0.2564.97 (64-bit) and incognito window (no extensions)  to view http://echarts.baidu.com/demo.html#scatter-aqi-color

The charts are not interactive- no tool tips, sliders etc.

![image](https://cloud.githubusercontent.com/assets/10502319/12869379/aa5cbc68-cd15-11e5-9b18-65c9d7880605.png)

but in firefox 44.0 its fine:
 
![image](https://cloud.githubusercontent.com/assets/8416809/12869384/ed9fba48-cd15-11e5-843a-9297de8d83c2.png)

Using Ubuntu 15.10. Is there any guidance on this? Is there some setting which might be a problem in Chrome? There are also no errors in the console.

**Comment by 100pah** [comment]
But I am not able to reproduce that in Chrome 48, Ubuntu 15.10 (in virtualbox), everything seems like ok.
I am not sure there is any other factor cause that you can not see tooltip.

**Comment by devldevelopment** [comment]
Thanks for testing this out. For me it also works in Ubuntu 15.10 and chrome 48 (in virtualbox) but with a fresh clean Ubuntu 15.10 hardware install **and** in Windows 10 with chrome Version 48.0.2564.103 (64-bit) I see no interactivity tooltips and cannot select anything. Could this be related to canvas/graphics/hardware acceleration related issues?

**Comment by devldevelopment** [comment]
Just to add some more information, in chrome the div tag for the tooltip etc is different:

This is firefox:
![image](https://cloud.githubusercontent.com/assets/8416809/12984739/955f15da-d108-11e5-8fa6-18d423453b5f.png)

and this is chrome. 

![image](https://cloud.githubusercontent.com/assets/8416809/12984751/a54ba1c0-d108-11e5-96af-a0e9e9235639.png)

where the div style is none.

**Comment by 100pah** [comment]
Thanks for following that problem~
We have tested it on win10 / chrome 48.0.2564.109 but still could not rebuild that problem.
Which type of hardware do you use? Is it a touch device (like "Surface")?
Someone else have reported similar problem on "Microsoft Surface Pro 3".

**Comment by devldevelopment** [comment]
Hi I use a laptop with this graphics card: Intel Corporation Broadwell-U Integrated Graphics (rev 09). I tested this on my colleagues PC and it works but fails for me in both Windows and Ubuntu. Is there any debugging I can enable?

**Comment by devldevelopment** [comment]
Ok now re-testing http://echarts.baidu.com/demo.html#scatter-aqi-color it seems to work!
