### ISSUE TITLE
force中添加node时，会有结点消失

### ISSUE THREAD

**Issue by soloriensqiu** [ecomfe/echarts#2571]
http://echarts.baidu.com/echarts2/doc/example/force1.html
在上面的例子里，把focus函数改成如下，乔布斯的结点会消失，请问这个用法就是这样的么，谢谢。
```js
myChart.setSeries(
	[{
		nodes:[
			//{category:0, name: '乔布斯', value : 10, label: '乔布斯\n（主要）'},
			{category:2, name: 'soloriens', value : 7, label: 'qiu'},
		],
		links:[
			{source : '乔布斯', target : 'soloriens', weight : 1, name: '观众'}
		]
	}], false);
```

**Comment by soloriensqiu** [comment]
echarts.js第958行
`            if (!notMerge && this._option) {
                this._option = zrUtil.merge(
                    this.getOption(),
                    zrUtil.clone(option),
                    false
                );
            }`
zrender/tool/util.js
`        function mergeItem(target, source, key, overwrite) {
            if (source.hasOwnProperty(key)) {
                var targetProp = target[key];
                if (typeof targetProp == 'object'
                    && !BUILTIN_OBJECT[objToString.call(targetProp)]
                    // 是否为 dom 对象
                    && !isDom(targetProp)
                ) {
					// 如果目标属性为数组时
					if (targetProp instanceof Array) {
						if (overwrite){
							target[key] = source[key];
						}
						else{
							for (var i = 0, lens = source[key].length, lent = target[key].length; i < lens; i++) {
								target[key][lent + i] = source[key][i];
							}
						}
					}
                    // 如果需要递归覆盖，就递归调用merge
                    merge(
                        target[key],
                        source[key],
                        overwrite
                    );
                }
                else if (overwrite || !(key in target)) {
                    // 否则只处理overwrite为true，或者在目标对象中没有此属性的情况
                    target[key] = source[key];
                }
            }
        }`

**Comment by pissang** [comment]
谢谢反馈，2.x 不再单独维护
