### ISSUE TITLE
effectScatter太卡了

### ISSUE THREAD

**Issue by wangjiaji** [ecomfe/echarts#2577]
只要一打开页面刷新率就会远低于60fps，照理说这种简单动画不应该啊，感觉上是靠js在硬算？

**Comment by waterwoodwind** [comment]
我也碰到过，echarts 3 在7000个点的多条折线图，tooltip和dataroom卡顿严重，远没有echarts 2 流畅，所以我将动画和特效这些都关了。
option.animation:false
option.dataZoom.realtime:false

**Comment by pissang** [comment]
@wangjiaji 带有特效的那个系列可以单独设置 zlevel 为 1 或者其它值，具体见 http://echarts.baidu.com/option.html#title.zlevel

@waterwoodwind echarts 3 中对于 dataZoom 窗口移动的动画效果有优化，具体对比 2 可以看出来，但是计算开销也更大了，所以在显示数据（实际显示数据区别于传入数据，有可能传入数据量大但是显示的窗口很小）量大的时候会相比 2 显得更卡顿，这时候建议是关闭动画的。

**Comment by SuperZDev** [comment]
![q](https://cloud.githubusercontent.com/assets/7768611/13068126/082ff432-d4b3-11e5-86cb-f847cb1fe8f9.png)
我就过来逗逗密集恐惧症，关闭动画后，感觉还是操作卡顿。

**Comment by waterwoodwind** [comment]
哈哈哈， (＝^ω^＝)
密集恐惧症笑尿

**Comment by pissang** [comment]
@SuperZDev 好多=   =这么多点的瓶颈就是在 Canvas 绘制上了，特别是阴影绘制的开销非常大。

PS：还挺漂亮的...

**Comment by SuperZDev** [comment]
@pissang  哈哈哈，好多下面的优化毕竟是看不到的，给人最直接的感受就是比2.x卡了。
PS：回答的点赞，回头把issue里值得列出来的，我都加blog里，还有Github开issue成本太低，有没有办法管理一下，你这600多issue看都看不过来吧，当然还有一些比较蠢的问题。

**Comment by waterwoodwind** [comment]
@pissang 厉害，赞

**Comment by pissang** [comment]
@waterwoodwind 大数据量的折线图在 3.1.2 中已经优化，在数据量远大于像素宽度的时候可以使用 [sampling](http://echarts.baidu.com/option.html#series-line.sampling) 过滤点，动画的算法也进行了优化。

**Comment by waterwoodwind** [comment]
@pissang 厉害，试了下，7000多点的曲线滑动流畅多了
