### ISSUE TITLE
3里能不能让折线图断点连线

### ISSUE THREAD

**Issue by genius9316** [ecomfe/echarts#2579]
因为项目需要，ECharts 2的时候是自己改的源代码，当某一天无数据时 前一天与后一天数据连成线，而非断开。为什么ECharts 3里不加上这个功能呢？感觉很多人都需要吧。。。

**Comment by genius9316** [comment]
第一章是自己改的
![1](https://cloud.githubusercontent.com/assets/12251908/13040841/2faf3fd0-d3ec-11e5-97b2-31c5b9f41eb1.png)
![2](https://cloud.githubusercontent.com/assets/12251908/13040842/2ff30508-d3ec-11e5-9033-b593116453db.png)

**Comment by SuperZDev** [comment]
所以我觉得你这边有两种解决方案：
1：可以修改数据为‘-’或者空对象{}，这样连线会正常绘制
2：等待官方添加类似highcharts中的这样效果的属性

`        plotOptions: {
            series: {
                connectNulls: true
            }
        }
`

![h](https://cloud.githubusercontent.com/assets/7768611/13042359/90b2444a-d3fa-11e5-9eb2-7fd5dcb8918c.png)

**Comment by genius9316** [comment]
仅仅把数据改为‘-’也会断开。
我是通过改EC2里的源代码，把相关的注释掉来实现连接的。。。
![3](https://cloud.githubusercontent.com/assets/12251908/13042619/91988d40-d3fc-11e5-8390-3678c8ce220a.png)
![4](https://cloud.githubusercontent.com/assets/12251908/13042620/919b1678-d3fc-11e5-90c0-603a90aade56.png)

EC3里代码变化太大了，现在还没有找到相关的设置T.T

**Comment by genius9316** [comment]
设置为0的结果。。。极具误导性
![5](https://cloud.githubusercontent.com/assets/12251908/13042839/9e4b69de-d3fe-11e5-8d9e-90071716d2cc.png)

**Comment by SuperZDev** [comment]
@leeight 
如果你十分着急的话，请修改src/chart/line/poly.js->drawSegment函数
将源代码：
`if (idx >= allLen || idx < 0 || isNaN(p[0]) || isNaN(p[1])) {
                break;
  }`

修改为：
`		    if (idx >= allLen || idx < 0) {
		                break;
		            }
					if((isNaN(p[0]) || isNaN(p[1]))&&(idx+1)<=allLen)
					{
						p = points[idx+1];
					}`

-----------------------------------------------
数据：[1, '-', 15, 28, 16, 32, 64, 128, 256]
绘制情况：
![a](https://cloud.githubusercontent.com/assets/7768611/13043839/b63f9d7e-d405-11e5-9474-c491ef18e3ab.png)
------------------------------------------------
PS：Github的code为什么换行都没有，汗，难道姿势不对？

**Comment by SuperZDev** [comment]
@pissang 也建议可以加上类似的属性。

**Comment by pissang** [comment]
连起来就代表有数据，误导性更大，可以连带 category 把数据过滤掉

**Comment by genius9316** [comment]
@SuperZDev 改成功了~非常感谢！！

**Comment by SuperZDev** [comment]
客气了，还有就是。其实你这个线画不画或者归零都有一定的误导性，其实我倒是觉得断开可能还是逻辑很正确的，但是非常容易让人忽略那个前面点。看了半天图才发现你前面有个。。。。还有@pissang说处理数据来实现效果，也是一种方法。

**Comment by genius9316** [comment]
@pissang 有时候只需要看一下趋势，具体有没有数据并不在意。想看具体数 可以把鼠标移过去看啊~
![1](https://cloud.githubusercontent.com/assets/12251908/13063695/987e3be4-d485-11e5-9d42-56ce71b65808.png)
![2](https://cloud.githubusercontent.com/assets/12251908/13063699/a1b0b3fe-d485-11e5-820e-8def92cc58c4.png)
这是一个月的数据，再往后可能两个月才有一次数据，如果不连线只会看到n多个点，
很影响看趋势=。=
还有就是……用户多年养成的画图习惯，就喜欢连起来看……-。-！

**Comment by SuperZDev** [comment]
@genius9316  请原谅我春节综合征，改两句代码还错了一句，不能坑了你。我把数组边界判断错了，已更正。你也改下吧。。囧瑟夫

**Comment by genius9316** [comment]
@SuperZDev 好的好的！~~
确实断开的话逻辑上很正确，可是用户几十年的画图 读图习惯，不好改啊...

**Comment by SuperZDev** [comment]
看了你给的图，我倒是觉得你这个场景是很适合断线给连起来。

**Comment by pissang** [comment]
可以试下显示指定 X 轴的位置，默认 X 轴是类目轴的时候，系列的数据也是一个一维数组，并且跟类目一一对应，但是 3.0 开始数据可以如下显示指定类目的 index：
```js
// 跳过第三个类目
data: [[0, 10.5], [1, 2.3], [4, 2.2]]
```

具体参见 data 的格式： http://echarts.baidu.com/option.html#series-line.data

**Comment by SuperZDev** [comment]
@pissang 
可是这样就必须显示指定value对应的index序列，为了实现这种功能把复杂度嫁接给了上层的数据处理。
我倒是觉得这应该是在ECharts端一个的配置项，类似highcharts的connectNulls。
而且如果只看整体趋势的话，我觉得这个场景倒是很适合。尤其是大屏展示的时候，有时候你不需要看具体的数据。

**Comment by pissang** [comment]
嗯，后续可以加上，这是目前版本能实现的思路

**Comment by soindy** [comment]
@pissang 请问 echarts3.* 实现该功能没?

**Comment by xiguaxigua** [comment]
@soindy http://echarts.baidu.com/option.html#series-line.connectNulls
