### ISSUE TITLE
自己扩展的地图，地图一直显示在demo的右上角，怎么解决？

### ISSUE THREAD

**Issue by hongsmith** [ecomfe/echarts#2581]
[自己扩展的某市的地图，但是图形一直显示在网页的右上角，想弄到中间显示，请教如何解决？

**Comment by SuperZDev** [comment]
请默念咒语->“给点力，来中间”。。。
--------------------------------------
在3.x里，有left,top,right,bottom设置。
在2.x里，我记得有mapLocation，可以调整x,y。

改完之后别忘了念咒语。哈哈

**Comment by hongsmith** [comment]
@SuperZDev 默认不应该显示在中间吗？我用mapLocation设置了xy，地图被拉倒中间了，但是只显示了上半部分，下半部分有一个角被遮住。
还有扩展的地图感觉整体被纵向拉升了，很奇怪。
![image](https://cloud.githubusercontent.com/assets/17171023/13064189/7b32cb30-d48b-11e5-83d8-e7bfcab125d9.png)
