### ISSUE TITLE
授权问题，这个是BSD授权么

### ISSUE THREAD

**Issue by snowlin** [ecomfe/echarts#2592]
最后授权英语那句话的意思是：？
你所下载的软件（echart）和文档，虽然遵循的是bsd授权，但软件和文档中的观点和结论只是作者自己（百度）的，并不代表bsd project官方
还是指：
软件和文档中的观点和结论只是作者自己，不代表官方（百度）政策明示或暗示它是一个免费的BSD项目

**Comment by pissang** [comment]
是 BSD 授权
