### ISSUE TITLE
# treemap下label和itemStyle的emphasis属性设置后并没有效果

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#2597]
http://echarts.baidu.com/demo.html#treemap-disk
例如在这个例子里，在series里面的itemStyle里加入如下代码
```
normal: {
    borderColor: '#fff'
},
emphasis: {
    borderColor: '#000'
}
```
鼠标悬浮在元素上时border的颜色并不会发生变化。
是我用法有问题吗？

**Comment by 100pah** [comment]
暂时还没有支持 treemap 中鼠标悬浮的样式改变，后面会加上。

**Comment by iamwelk** [comment]
(⊙o⊙)哦，我看到文档里面有写，还以为已经就绪了~谢谢！
