### ISSUE TITLE
[建议]昨天刚吐槽开issue成本太低，今天官方就给了一个解决方案。

### ISSUE THREAD

**Issue by SuperZDev** [ecomfe/echarts#2602]
天了个噜的，是不是听到了我的呼声。

> It's hard to solve a problem when important details are missing. Now project maintainers can add templates for Issues and Pull Requests to projects, helping contributors add the right details at the start of a thread. This is the first of many improvements to Issues and Pull Requests that we're working on based on feedback from the community.

[Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates)

@100pah @pissang

**Comment by pissang** [comment]
简直太赞！

**Comment by SuperZDev** [comment]
哪里醒目放哪里，哪里醒目放哪里，哪里醒目放哪里。
重要的事情说三遍。
要不然等着煎熬吧，看你刚才close了好久前的几十个issue，你应该懂得痛【**此处应有掌声**】。

还有README要有中文吧，要不然好多人都不会看，例如【问你BSD协议？】这种。

**Comment by pissang** [comment]
现在可以在模板里放了

**Comment by SuperZDev** [comment]
哈哈哈，我理解错误。CLOSE了，坐等了。

**Comment by SuperZDev** [comment]
@pissang 
我这写了一个示例，你看看？PS:最近太闲

[ISSUE_TEMPLATE.md](https://github.com/SuperZDev/echarts/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by pissang** [comment]
好迅速，挺好的我们参考下，或者你提个 PR 我们合进来后再改下

**Comment by SuperZDev** [comment]
已推[PR](https://github.com/ecomfe/echarts/pull/2605)
请记得及时修改，要不然会导致，大家new issue的时候，出现示例。
