### ISSUE TITLE
x轴、y轴可否支持坐标原点自定义？

### ISSUE THREAD

**Issue by T25** [ecomfe/echarts#2606]
请问，想要实现 比如：
y轴的坐标原点在  x轴上 x=20 的位置，可以实现吗？

查了 3.0 中， axis 的position， 默认只能选 'top' 'left' 等。
有什么办法 可以支持 自定义吗？

主要是为了实现4象限的分割(x、y 都是正数)

**Comment by ummo** [comment]
遇到了同样的问题，请问有办法解决吗

**Comment by huanghugo** [comment]
遇到了同样的问题，请问有办法解决吗
