### ISSUE TITLE
请问Echarts3.0没有时间轴多图联动这块的Demo么，我们急需要啊！

### ISSUE THREAD

**Issue by nilin2015** [ecomfe/echarts#2608]

**Comment by SuperZDev** [comment]
时间轴的我这没有，不过原来我倒是写了一个地图下钻的例子。

你可以参考下，没有用到connect，用的是event。

点击新疆，西藏。
[地图下钻](https://jsfiddle.net/SuperZ/redpp4fr/)

![qq 20160218163104](https://cloud.githubusercontent.com/assets/7768611/13137600/01eb3040-d65d-11e5-9529-279c228922fd.jpg)
