### ISSUE TITLE
ECharts 2.x升级到3.x疑问

### ISSUE THREAD

**Issue by yuanrui** [ecomfe/echarts#2611]
2.x升级到3.x是否可以直接替换源代码呢。 有没有升级说明呢，看了下文档没找到。
另外能不能在每次发布的版本中添加对应的版本号呢？

**Comment by yuanrui** [comment]
也不给个回复 晕

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/wiki/ECharts-2-%E5%8D%87%E7%BA%A7%E5%88%B0-ECharts-3-%E7%9A%84%E6%94%B9%E5%8A%A8

**Comment by yuanrui** [comment]
@pissang 
thanks
