### ISSUE TITLE
treemap上鼠标滚轮滚动时整个界面无法滚动

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#2613]
## 当整个页面比较大，出现滚动条时

1.  鼠标滚轮在treemap外滚动时页面会随之滚动
2.  当鼠标放置到treemap之上时，鼠标滚轮就只能控制treemap的缩放，而无法影响整个页面
3.  如果不需要缩放功能时，有什么属性可以恢复滚轮正常的滚动页面的功能？

**Comment by pissang** [comment]
可以关闭鼠标漫游， `roam: false`

**Comment by iamwelk** [comment]
已经关闭了鼠标漫游，但是仍然无法使用正常的滚轮滚动页面功能

**Comment by iamwelk** [comment]
http://echarts.baidu.com/demo.html#treemap-disk
在上面的例子中设置roam为false，然后右键将页面的right-container类的高度设为200%，这样就会出现页面的滚动条。可以发现当鼠标放置在treemap上时，鼠标滚轮是无法带动页面的滚动的，而在treemap之外是可以的
