### ISSUE TITLE
echarts 自定义构建选择数据区域组件后的打包文件用不了

### ISSUE THREAD

**Issue by luxueyan** [ecomfe/echarts#2619]
![image](https://cloud.githubusercontent.com/assets/1555552/13194035/31e4147a-d7bf-11e5-86e6-f86f7fb7a153.png)
这一步报错了
![image](https://cloud.githubusercontent.com/assets/1555552/13194041/4509c7ac-d7bf-11e5-9a9d-626c4f7d99d9.png)
貌似是把主题名称当成了object?

-------
而且echarts3里面的配置项，涉及到位置坐标的 left,right,top,bottom貌似不太好用，我设置了bottom为一个具体数值时候，根本没有效果。不过用x，y height，width这些echarts2的属性还可以用，为什么文档里面不说明呢？

**Comment by pissang** [comment]
第二个问题可以给出详细的 option 么？

**Comment by luxueyan** [comment]
@pissang  被我换成y值加height设置了，我想的是可以实现这样的设置吗？例如：像css的position：absolute元素一样，可以用top控制上边距，bottom控制下边距，可以自然拉伸高度，如果top：10，bottom：10，并没有达到想要的效果！
ps：不过文档里面也没有包含height，width，x，y的设置，但是是支持的

**Comment by pissang** [comment]
可以这样设置

**Comment by luxueyan** [comment]
@pissang 
```javascript
dataZoom: [{
                    // show: true,
                    // realtime: true,
                    top: 48,
                    bottom: 60,
                    left: 78,
                    // height: 290,
                    // start: 30,
                    // end: 70,
                    backgroundColor: 'rgba(0,0,0,0)', // 背景颜色
                    dataBackgroundColor: 'rgba(0,0,0,0)', // 数据背景颜色
                    xAxisIndex: 1,
                    type: 'slider'
                }],
```
这样设置 不行

**Comment by 100pah** [comment]
这是个bug已经改了，下个版本就可以了
