### ISSUE TITLE
求各国的城市数据

### ISSUE THREAD

**Issue by dotku** [ecomfe/echarts#2622]
目前好像就 MaxMind 有公开数据的...

**Comment by pissang** [comment]
可以根据需要自行去各种平台查询，我们提供给开发者工具，但是数据因为精力有限暂时无法提供

**Comment by dotku** [comment]
@pissang 因为百度有地图服务的，不过只有中国的数据，希望能很快推出国际版；如果百度都无能为力，我们这些小公司就更是登天了~ 我们暂时用 MaxMind 和 OSM 的数据，不过精确度，实在是很凑合...
