### ISSUE TITLE
EChart3.0-> symbol为arrow，显示的位置跟EChart2.0不一样?

### ISSUE THREAD

**Issue by zhump** [ecomfe/echarts#2624]
![dddd](https://cloud.githubusercontent.com/assets/7962067/13201715/4d273574-d8b8-11e5-9fc0-c90f2d121c01.jpg)

![cccc](https://cloud.githubusercontent.com/assets/7962067/13201716/5430bf3e-d8b8-11e5-858d-6dc835458538.png)

之前的“arrow”箭头是上下居中在折点的。现在是显示在下方，一旋转起来，真心不好看，看下方。虽然可以调整symbolOffset，但是还得根据symbolSize去计算这个值，如果可以像'circle', 'rect', 'roundRect', 'triangle', 'diamond'一样居中在折点就跪谢了。

![fffff](https://cloud.githubusercontent.com/assets/7962067/13201772/39e9cb28-d8ba-11e5-93a8-ffc058401819.jpg)
![gggg](https://cloud.githubusercontent.com/assets/7962067/13201774/433a91e4-d8ba-11e5-8f84-a604fd88437b.png)

**Comment by pissang** [comment]
3.x 中箭头的端点指向了具体的点，想要实现 2.x 那种的可以通过 symbolOffset 加位移
