### ISSUE TITLE
bar柱状图，当xAxis的子元素超过一定长度会使下一个元素隐藏

### ISSUE THREAD

**Issue by dadiu** [ecomfe/echarts#2637]
当
xAxis : [
        {
            type : 'category',
            data : ['周一周周周周周周周周周','周二','周三','周四','周五','周六','周日']
        }
    ],

的时候，X轴上的周二会直接隐藏掉。
建议改成，超过长度之后以"..."形式显示，鼠标上去显示完整的文字？

**Comment by zhump** [comment]
xAxis->axisLabel->interval->设置成 0 强制显示所有标签
xAxis->axisLabel->rotate->可以通过旋转防止标签之间重叠。

**Comment by dadiu** [comment]
好的 谢谢
