### ISSUE TITLE
[Bug]echarts 3.1.1 柱状图无法从左到右边缘显示markLine

### ISSUE THREAD

**Issue by waynezzz** [ecomfe/echarts#2644]
http://echarts.baidu.com/demo.html#bar1
下面是按照以上link修改的。

`option = {
    title : {
        text: '某地区蒸发量和降水量',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['降水量']
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : ['1月','2月']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'降水量',
            type:'bar',
            data:[2.63,5],
            barMaxWidth: 50,
            markLine : {
                data: [[
                    {xAxis:-1, yAxis: 3}, 
                    {xAxis: 2, yAxis: 3}
                ]]
            }
        }
    ]
};`
按照[文档](https://ecomfe.github.io/echarts/doc/doc.html#SeriesMarkLine)，有如下说明
`data : [
    [
        {name: '标线1起点', value: 100, xAxis: 1, yAxis: 20},      // 当xAxis为类目轴时，数值1会被理解为类目轴的index，通过xAxis:-1|MAXNUMBER可以让线到达grid边缘
        {name: '标线1终点', xAxis: '周三', yAxis: 20},             // 当xAxis为类目轴时，字符串'周三'会被理解为与类目轴的文本进行匹配
    ],
    [
        {name: '标线2起点', value: 200, xAxis: 10, yAxis: 20},     // 当xAxis或yAxis为数值轴时，不管传入是什么，都被理解为数值后做空间位置换算
        {name: '标线2终点', xAxis: 270, yAxis: 190}
    ],
    ...
]`
去修改为：
`            markLine : {
                data: [[
                    {xAxis:-1, yAxis: 3}, 
                    {xAxis: 2, yAxis: 3}
                ]]
            }`
                
可是这样根本无法显示markLine.
只有改为 
`markLine : {
                data: [[
                    {xAxis:'1月', yAxis: 3}, 
                    {xAxis: '2月', yAxis: 3}
                ]]
            }`
才能显示markLine,可是无法从左边缘至右边缘。如下图：
![image](https://cloud.githubusercontent.com/assets/17430246/13252771/72eb03c8-da73-11e5-889d-7787ffad9f6d.png)

**Comment by waynezzz** [comment]
同样的代码在echats 2.0以下下链接中使用，可以实现如官方文档一致效果。
http://echarts.baidu.com/echarts2/doc/example/bar13.html

`option = {
    title : {
        text: '某地区蒸发量和降水量',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['降水量']
    },

    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : ['1月','2月']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'降水量',
            type:'bar',
            data:[2.63,5],
            barMaxWidth: 50,
            markLine : {
                data: [[
                    {xAxis:-1, yAxis: 3}, 
                    {xAxis: 2, yAxis: 3}
                ]]
            }
        }
    ]
};
`

![image](https://cloud.githubusercontent.com/assets/17430246/13273086/e43dfd10-dadb-11e5-9693-7f4159a2f6c7.png)

**Comment by waynezzz** [comment]
@pissang 
这个问题很容易复现，请关注下。

**Comment by waynezzz** [comment]
ping pissang.....
@pissang

**Comment by waynezzz** [comment]
能否看下这个问题？ @pissang

**Comment by waynezzz** [comment]
目前只好通过另外建一个类目轴（boundaryGap: false），在series使用空数据解决markLine无法到左右边缘的问题。

code如下：
`option = {
    title : {
        text: '某地区蒸发量和降水量',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'item',
        showContent: true
    },
    legend: {
        data:['降水量', '']
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : ['1月','2月'],
        },
        {
            type : 'category',
            data : ['1月','2月'],
            axisLabel: false,
            boundaryGap: false,
            axisLine:{
                show: false
            }
        }
    ],
    yAxis : [
        {
            type : 'value',
            boundaryGap: [0, 0.1]
        }
    ],
    series : [
        {
            name:'降水量',
            type:'bar',
            data:[2.63,5],
            barMaxWidth: 50,
            },
            {
            type:'bar',
            data:[0,0],
            xAxisIndex:1,
            markLine : {
                lineStyle: {
                    normal: {
                        width: 3,
                    //    type: "solid"
                    }
                },
                data: [[
                    {xAxis:0,yAxis:5},
                    {xAxis:'2月',yAxis:5}
                ]]
            }
        }
    ]
};
`

**Comment by pissang** [comment]
3 里面 markLine 位置是从数据位置到结束数据位置。

**Comment by waynezzz** [comment]
@pissang 
能不能像2那样增加markLine位置至左右边缘的选项？
因为如果在只有单柱情况下，markLine会跟柱子叠在一起。
