### ISSUE TITLE
饼图没办法给整个圆饼设置shadow么，只能给饼设置shadow？

### ISSUE THREAD

**Issue by xpacificsoda** [ecomfe/echarts#2647]
http://echarts.baidu.com/demo.html#pie-simple
这个例子里，给饼图加上
`itemStyle: {
        normal: {
            shadowBlur: 10,
            shadowColor: 'rgba(0, 0, 0, 0.5)',
            shadowOffsetX: 3,
            shadowOffsetY: 3,
        }
    },`

所有的pie，都有shadow了，有没有办法，给整个圆圈⭕️设置shadow，而每个pie没有shadow？

**Comment by pissang** [comment]
暂时没有

**Comment by xpacificsoda** [comment]
有什么办法能把shadow加上去么，丑一点的实现也可以 @pissang

**Comment by pissang** [comment]
可以另外加一个只有一个数据的饼图系列，这个系列里加上阴影，并且把这个系列的 z 设成 -1
