### ISSUE TITLE
图层遮挡同级的div

### ISSUE THREAD

**Issue by rickyzhuang** [ecomfe/echarts#2648]
如
<div id="conteng">
<div id="div4a">
<a href="https://github.com" >看得见，点不着</a>
</div>
<div id="div4Chart">这里是echarts图层，会遮挡上面的DIV</div>
</div>

请问如何处理

**Comment by zhump** [comment]
<a href="https://github.com">看得见，点不着</a>  你放的是什么？？

**Comment by rickyzhuang** [comment]
![qq 20160224140440](https://cloud.githubusercontent.com/assets/17446054/13278125/e892d12e-db08-11e5-9f6e-d2ab478db862.jpg)

**Comment by rickyzhuang** [comment]
图示的两个div，下面是echarts渲染的div，和它同级的div就是上面那个float：right内容含两a标签 1星期 1个月

**Comment by zhump** [comment]
噗。。设置A标签所在的div 绝对定位试试

**Comment by rickyzhuang** [comment]
绝对定位当然可以，但是最糟糕的方法。往上看，这个div应只在服务调用记录tab2中，绝对定位会在服务操作日志tab1中显示，

**Comment by zhump** [comment]
是你代码问题，自己慢慢调试吧

**Comment by sky185959** [comment]
同层级echart挡住div了，绝对定位也可以，但是挡住以后div里面的比如button无法点击，这个怎么调整echart层级比div低呢
