### ISSUE TITLE
柱状图怎么设置主图大小？

### ISSUE THREAD

**Issue by unknown-coder** [ecomfe/echarts#2649]
如图，外面div容器不是很大，里面主图好像默认会四周留白，该怎么设置主图大小？配置项里并没有找到参数。

![image](https://cloud.githubusercontent.com/assets/9328734/13278547/4efd416c-db0c-11e5-9c04-3b9bbba00042.png)

**Comment by zhump** [comment]
http://echarts.baidu.com/option.html#grid

**Comment by unknown-coder** [comment]
原来要自己画grid来实现，谢谢了 @zhump
