### ISSUE TITLE
echarts 3.0.2在三星s4 手机上面渲染缓慢

### ISSUE THREAD

**Issue by CaoLeilei** [ecomfe/echarts#2651]
echarts 3.0.2制作的柱形图，要等待很久才出现柱形图。

**Comment by zhump** [comment]
打开官网的示例也很慢吗？

**Comment by CaoLeilei** [comment]
其他的机子都还好，还有另外一个bug，就是环形图，data:[value:1,value:0]在安卓上面会变成饼图
