### ISSUE TITLE
symbolRotate

### ISSUE THREAD

**Issue by xavd** [ecomfe/echarts#2654]
Hello
For a chart:
  type: 'line'
  symbol: 'emptyArrow'
  symbolRotate : varied values
in echarts 3 the final position of the symbol symbol is no longer centered on the data as in echarts 2

**Comment by zhump** [comment]
#2624
调整symbolOffset

**Comment by zhump** [comment]
@pissang  "3.x 中箭头的端点指向了具体的点，想要实现 2.x 那种的可以通过 symbolOffset 加位移"

大神 我还是想建议一下，箭头的中心能在具体的点上，行不行呢。

**Comment by xavd** [comment]
I 've tested symbolOffset
for a similar graph to echarts2 I have to do:
symbol: 'emptyArrow' ,
symbolRotate : (0)   ,  symbolOffset : [ '0%'  , '-50%']
symbolRotate : (90)  , symbolOffset : [ '-50%',   '0%']
symbolRotate : (180) ,symbolOffset : [ '0%'  ,  '50%']
symbolRotate : (270) ,symbolOffset : [ '50%' ,   '0%']
symbolRotate : (360) ,symbolOffset : [ '0%'  , '-50%']

**Comment by zhump** [comment]
是的上面的哥们跟我想的一样，不知道他看到中文，会不会谷歌翻译一下，哈哈哈
