### ISSUE TITLE
Customizable Pie Label Content

### ISSUE THREAD

**Issue by ffcc** [ecomfe/echarts#2655]
Hi!

I want to add an image on the content of a pie chart and I wonder if there is a way for customizable the **series[_].itemStyle.label.formatter** to show an image? In concret I need to add a `<i/>` tag like this:

```
{
    //...
    series: [{
        type: 'pie',
        //...
        itemStyle: {
            normal: {
                label: {
                    position: 'inner',
                    formatter: function(params) {
                        return '<i class="c-icon"></i>' + params.name;
                    }
                }
            }
        }
    }]
}
```

**Comment by pissang** [comment]
Label do not support html content

**Comment by ffcc** [comment]
I saw the source and can be updated to support html content (`this._tDom.innerHTML = formatter`) but thanks anyway!
