### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by kentzhu** [ecomfe/echarts#2663]
建议在toolbox添加转换为占比堆积折现图、占比堆积条形图的功能

呈现堆积图的时候，发现如果能切换到占比堆积图，有利于对数据的理解。
数值模式下是对量的体现，占比模式下是对结构的体现。
添加按钮来回切换，用户体验提升很大。

ps:看好你们

**Comment by pissang** [comment]
谢谢建议，欢迎 Pull Request
