### ISSUE TITLE
数据更新后图表不刷新，点击图例才刷新

### ISSUE THREAD

**Issue by jackson203** [ecomfe/echarts#2669]
我的图表显示折线图，通过dataView查看到数据确实已经加载进来了，但是图上只显示一些圆点。点击第一个图例后，对应颜色的圆点会消失，其它折线会出现，再次点击第一图例，第一图例对应折线才会出现。而先点击第一图例后的其它图例，则对应颜色的圆点会消失，其它图例的折线也不会出现。再次点击这一图例，这一图例对应折线会出现。
请问这是个bug，还是我的配置有问题？
如果是bug，多久能fix

**Comment by jackson203** [comment]
浏览器测试了chrome和edge, 结果一样。echarts 版本3.1.1。系统win10.

**Comment by jackson203** [comment]
这个问题是数据初始化后，图表能正常显示，通过setOption方法清空数据后，再次重新加载数据后出现的刷新问题。

**Comment by pissang** [comment]
这个问题已经在 commit https://github.com/ecomfe/echarts/commit/fa58061eda502a42d41c9456dcf192fc38b97af8 中修复，可以在下周发布新版本后更新
