### ISSUE TITLE
echarts3.1.1 默认的悬浮（变大）效果如何取消？

### ISSUE THREAD

**Issue by rickyzhuang** [ecomfe/echarts#2685]
2.7.7没有此默认设置，升级到3.1.1时，全部加上了这个效果，请问如何取消
![default](https://cloud.githubusercontent.com/assets/17446054/13384177/265cd338-dece-11e5-866b-7391b7f75d50.jpg)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-pie.hoverAnimation

**Comment by rickyzhuang** [comment]
@pissang  Thank you  Very Much!

**Comment by mxy2316868975javascript** [comment]
如何默认悬浮状态 @pissang

**Comment by mxy2316868975javascript** [comment]
![image](https://user-images.githubusercontent.com/15233384/32318815-676fcc4c-bff3-11e7-8b02-42f410a9408e.png)

**Comment by mxy2316868975javascript** [comment]
@pissang

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#series-pie.data.selected>
