### ISSUE TITLE
echarts3版本里是否没有辅助线功能了？

### ISSUE THREAD

**Issue by OeinTwor** [ecomfe/echarts#2689]
在echarts2版本里有辅助线功能的：
toolbox->feature->mark

但是echarts3里似乎移除了？

**Comment by pissang** [comment]
是移除了

**Comment by HyramTang** [comment]
现在3.8.5版本辅助线加回来了，参考：[markLine](http://echarts.baidu.com/option.html#series-bar.markLine)
