### ISSUE TITLE
饼图值为0时，百分比显示为NaN%

### ISSUE THREAD

**Issue by Coffcer** [ecomfe/echarts#2690]
![image](https://cloud.githubusercontent.com/assets/12846955/13387097/2668fd14-deee-11e5-8b6c-a3064d10f810.png)

如图，假设两个值A为500， B为0，当把A的图例隐藏掉后，鼠标放上B，显示的是0 (NaN%)

**Comment by pissang** [comment]
因为 0 / 0 是没意义的

**Comment by Coffcer** [comment]
然而0%还是有几率出现的吧，echart是否该对0做特殊处理
