### ISSUE TITLE
echarts3 百度地图扩展什么时候发布？

### ISSUE THREAD

**Issue by ldllidonglin** [ecomfe/echarts#2692]
我尝试模仿echarts2 的百度地图扩展来写，但是发现工作量有点大。。大概什么时候能使用这个扩展呢？因为我看已经有commit是关于这个的，但是还没看到成品及实例

**Comment by pissang** [comment]
3.0 的百度地图扩展已经有了，但是还没写文档， script 引入 https://github.com/ecomfe/echarts/blob/master/dist/extension/bmap.js 这个文件后，照着 https://github.com/ecomfe/echarts/blob/master/test/bmap.html 这个示例写

**Comment by ldllidonglin** [comment]
好的，明白了，非常感谢

**Comment by liuzhihao1665** [comment]
bmap这个对象有哪些属性值呢，示例中只有四个属性值，我现在想把百度普通地图设置成卫星地图该设置bmap中的哪条属性啊
