### ISSUE TITLE
Line chart with vertical line

### ISSUE THREAD

**Issue by gabrielenosso** [ecomfe/echarts#2693]
Is it possible to have a line chart with a vertical line which shows a label?
Something like that:
http://www.fusioncharts.com/dev/assets/images/vertical_lines.png.pagespeed.ce.JPDT_Ecw2V.png

**Comment by pissang** [comment]
You can use a markLine to simulate it.

**Comment by gabrielenosso** [comment]
to have a vertical line I should specify 'indexValue: 0', right?
And anyway, how could I print a label?

**Comment by suxuekun** [comment]
markline not labelline

**Comment by sameer05k21a0440** [comment]
I'm also looking same result from you please let me know how to draw line with veritcal lines with labes either xAxis top or bottom ?
