### ISSUE TITLE
yAxis 想问一下在折线图中如何让y轴显示连续的整数

### ISSUE THREAD

**Issue by pihc** [ecomfe/echarts#2695]
折线图的y轴是自动计算的，但是里面会出现小数，在有些情况下显示小数是不合理的比如（人的数量）

**Comment by qingweibinary** [comment]
http://echarts.baidu.com/option.html#yAxis.axisLabel.formatter

用 formatter

**Comment by pihc** [comment]
谢谢，解决了！！
