### ISSUE TITLE
id duplicates 错误

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#2696]
1. 用echarts渲染了一个图表
2. 用echarts.getInstanceByDom获取到此图表chart
3. 用chart.getOption获取到此图表的配置option
4. 修改option的series的一个值
5. 调用chart.setOption(option)，报错`Uncaught Error: id duplicates: _ec_toolbox-dataZoom_xAxis0`

**Comment by zhump** [comment]
ECharts什么版本

**Comment by iamwelk** [comment]
3.1.1

**Comment by zhump** [comment]
具体代码贴上

**Comment by pissang** [comment]
这个问题已经修复，明天的新版本可以试试

**Comment by iamwelk** [comment]
OK,正准备贴代码呢。。谢谢各位大神~
