### ISSUE TITLE
echarts2-----无法动态改动datazoom

### ISSUE THREAD

**Issue by liulingmin** [ecomfe/echarts#2702]
option.dataZoom.start = 0;
	option.dataZoom.end = 50;
	
	myChart.setOption(option); 
	
	
	$("#chart1").click(function(){
		option.dataZoom.start = 50;
		option.dataZoom.end = 100;
		myChart.setOption(option);
	})
点击后 datazoom 没有改变

**Comment by pissang** [comment]
用 absoluteZoom 方法。
