### ISSUE TITLE
webview里图表100%无效，大神帮看下什么原因

### ISSUE THREAD

**Issue by zb188** [ecomfe/echarts#2704]
webview里图表100%无效，大神帮看下什么原因，chrome调试是正常的 ，就是的安卓webview里宽度没有适应
这个是页面代码 
http://res.xiaomaiketang.com/school_major/6237c5011312585aadf43c5e4ef2611e.html

**Comment by 100pah** [comment]
没有描述清楚您的问题，所以无法看出是什么原因
