### ISSUE TITLE
sankey图的node颜色无法设定，版本3.1.2

### ISSUE THREAD

**Issue by xuqing1989** [ecomfe/echarts#2705]
var myChart = echarts.init(document.getElementById('<?php echo $divId;?>'));
    nodes=[
      {"name": "Total",
                itemStyle: {
                    normal: {
                        color:"#f00",
                        borderColor:"#f00",
                    }
                },},
      {"name": "Environment"},
      {"name": "Land use"},
      {"name": "test3"},
      {"name": "test4"},
      {"name": "test5"},
      {"name": "test6"},
      {"name": "test7"},
      {"name": "test8"},
    ];
    links=[
      {"source": "Total", "target": "Environment", "value": 20},
      {"source": "Total", "target": "Land use", "value": 70},
      {"source": "Total", "target": "test3", "value": 10},
      {"source": "Environment", "target": "test4", "value": 15},
      {"source": "Environment", "target": "test5", "value": 5},
      {"source": "test3", "target": "test6", "value": 10},
      {"source": "Land use", "target": "test7", "value": 50,
        lineStyle:{
            normal: {
                color:'#f00',
                opacity:0.5,
            }
        },
      },
      {"source": "Land use", "target": "test8", "value": 20},
      ];
    var option = {
        title: {
            text: 'Sankey Diagram'
        },
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'sankey',
                layout:'none',
                data: nodes,
                links: links,
            }
        ],
    };
    myChart.setOption(option);

//可以看到边的颜色有改变，但是node的颜色没有变化
![qq 20160301213211](https://cloud.githubusercontent.com/assets/12749805/13448982/2a130f88-dff5-11e5-83b5-d1c86345730b.png)

**Comment by xuqing1989** [comment]
@SuperZDev I noticed your comment on issue#2738. In that issue color setting from series.itemStyle.normal is not working.
I want to let you know color setting from series.data.itemStyle.node is also not working in 3.1.2.
Thank you.

**Comment by SuperZDev** [comment]
Thx. :smiley: 
https://github.com/ecomfe/echarts/pull/2740 had solve the problem.
You can try it with this [branch](https://github.com/SuperZDev/echarts).
With your option:
![sankey](https://cloud.githubusercontent.com/assets/7768611/13546632/74f991e2-e2ee-11e5-8a10-8fcda21f66e9.jpg)
