### ISSUE TITLE
可以服务端生成图表png吗？

### ISSUE THREAD

**Issue by sunLeung** [ecomfe/echarts#2706]
如题，可以服务端生成图表png图片，用于发送email吗？

**Comment by pissang** [comment]
可以在 nodejs 用 node-canvas 生成图片，参考这个例子 https://tonicdev.com/56cb0fbc3a0cd70c0074022b/56cb0fbc3a0cd70c0074022c

**Comment by liege** [comment]
@pissang https://tonicdev.com/56cb0fbc3a0cd70c0074022b/56cb0fbc3a0cd70c0074022c 这个例子有个问题，不能够显示中文,有什么其他解决办法吗？

**Comment by suxiaoxin** [comment]
@liege  看看我写的这个，支持中文
https://github.com/suxiaoxin/node-echarts
