### ISSUE TITLE
Echart3在给容器注入图标时没有错误提示

### ISSUE THREAD

**Issue by SwordSealCity** [ecomfe/echarts#2708]
今天开发移动端的图表，看到Echart3有推出移动概念，于是打算试试，想从Echarts2转换到2，但是初步测试后发现Echart3在给容器注入图标时，如果容器没设定高度，容器就不会显示图表，而且也没有错误提示，这个体验让我很失望！！
而且Echart3的实例明显没Echarts2的实例详细和丰富！！我不知道这是百度团队故意为之，以展现团队的高超之处还是想通过简化实例为难用户以增加团队的业务？又或者百度团队偷懒了？如果是前一种的话，那这种行为让我对百度深深感到耻辱！不管是哪种，都让人感到失望。

Echarts2在容器没有设置尺寸时：Dom’s width & height should be ready before init.

**Comment by pissang** [comment]
这个难道不是常识？
