### ISSUE TITLE
dispose方法与对象重置为null的区别是什么？

### ISSUE THREAD

**Issue by gaoyaxin** [ecomfe/echarts#2713]
echart2.0 API里面有个方法是dispose，代表了回收这个echart对象。但是使用console.log看，该对象实体仍在。
如果将这个对象设置为null，不是更彻底？两者的区别是啥呢。
忘了说的问题了，我使用dispose后，在window.location.reload(true),提示某些对象未定义

**Comment by pissang** [comment]
这两个不想管，dispose 释放示例，包括里面用 requestAnimation 实现的动画循环，绑定的事件等等，在 dispose 后这个示例无法再被复用，所以你可以根据需要设成 null 让垃圾回收移除该示例占用的内存。

**Comment by gaoyaxin** [comment]
我使用的是echarts2.X,我在地图中使用了MarkPoint冒泡动画，按照pissang思路，我可以使用delMarkPoint()，一次删除地图中的冒泡。然后在window.location.reload(true),这样内存应该会下降一些吧。
------------
回复pissang的问题，我dispose后，执行window.location.reload(true);在我的firefox浏览器中（其他浏览器未发现）会偶尔报
TypeError: h is undefined
if (i !== h.zlevel && (n && (n.needTransform && o.restore(), o.flush && o.flush(...
我猜测dispose后，对象已经不可用，window.location.reload(true)，偶尔还会存在之前的对象。因为不可用，所以会提示TypeError。可以这么理解吗？

**Comment by gaoyaxin** [comment]
clear方法是否也可以释放实例中用 requestAnimation 实现的动画循环，绑定的事件呢？

**Comment by gaoyaxin** [comment]
![typeerror](https://cloud.githubusercontent.com/assets/15101333/13485787/34a4a22a-e146-11e5-8c63-806d8e85e835.jpg)

**Comment by gaoyaxin** [comment]
window.location.reload(true),会回收requestAnimation 动画循环和绑定的事件吗？
