### ISSUE TITLE
echart3 面积图/折线图 x轴显示不完全

### ISSUE THREAD

**Issue by Coffcer** [ecomfe/echarts#2714]
![image](https://cloud.githubusercontent.com/assets/12846955/13458335/96cb8512-e0a7-11e5-885f-bf70a3cadedd.png)

如图，已经预留了足够的Grid，x轴是02-19到02-26，总共8天。如果图够大，8天全部显示是可以的，但图表小的时候，echart会自动平均的隐藏中间的部分x轴，而像8这类的数没法整除出平均的分段值，导致最后一天显示不出来，这种情况可以通过配置来避免吗？

**Comment by zhump** [comment]
http://echarts.baidu.com/option.html#xAxis.axisLabel.interval

**Comment by Coffcer** [comment]
@zhump 这个似乎没用，遇到无法算出平均分段的值时，还是会像1楼的图一样显示不全。
我觉得理想情况应该是无论如何最后一格都强行闭合，像这样：
![image](https://cloud.githubusercontent.com/assets/12846955/13482097/5bf2f47e-e125-11e5-9cfb-adbd4f0a6c4d.png)

**Comment by lei1992** [comment]
在xAxis项加上axisLabel:{interval:0,rotate:45}试试

**Comment by yugasun** [comment]
@lei1992  @Coffcer ： lei1992的方法很不错，下面是我的解决方案。
axisLabel:{interval:0,rotate:45}中的rotate值可以根据图表x轴labels的长度来修改旋转角度，这样图标的显示会更灵活些。

**Comment by wm370857724** [comment]
@yugasun 旋转后文字被截掉了，有办法设置 x 轴 label 的高度吗？

**Comment by bambooom** [comment]
@wm370857724 可以试试在 grid 中设置一下 bottom
```js
grid: {
    bottom: '8%'
}
```

**Comment by Ovilia** [comment]
ECharts 3.5.2 版本起，支持 <a href="https://ecomfe.github.io/echarts-doc/public/cn/option.html#xAxis.axisLabel.showMinLabel">axisLabel.showMinLabel</a> 以及 <a href="https://ecomfe.github.io/echarts-doc/public/cn/option.html#xAxis.axisLabel.showMaxLabel">axisLabel.showMaxLabel</a>，分别用来控制第一个和最后一个标签是否强制显示，设为 <code>true</code> 则强制显示。

**Comment by Smile-lrn** [comment]
最后一个数据点也显示不出来 该怎么设置

**Comment by yugasun** [comment]
@Smile-lrn 可以使用 [series-line.showAllSymbol](https://ecomfe.github.io/echarts-doc/public/cn/option.html#series-line.showAllSymbol) 配置来显示所有数据点。

**Comment by Smile-lrn** [comment]
设置了 `   itemStyle : { normal: {label : {show: true}}},
            data: [],
            type: 'line',
            showAllSymbol: true, //标注所有数据点,`                                                   无效

**Comment by yugasun** [comment]
请点击上面的api链接，正确的进行配置。

**Comment by Smile-lrn** [comment]
在 2018-03-12 15:04:22，"Yuga Sun" <notifications@github.com> 写道：


请点击上面的api链接，正确的进行配置。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.










谢谢啦  已经解决了
