### ISSUE TITLE
折线图的x轴可否支持滚动

### ISSUE THREAD

**Issue by duanshanchong** [ecomfe/echarts#2715]
在移动端想使用折线图，但是屏幕不够宽，x轴的刻度数量多了会很挤，能否支持x轴左右拖拽的横向滚动呢，类似于滚动条，但是y轴刻度不动。
![fa8d141b-271e-4d28-be06-c8eb1999ddd8](https://cloud.githubusercontent.com/assets/1659271/13460904/1ce41928-e0b9-11e5-9629-e87083a237cc.png)

**Comment by pissang** [comment]
想要 y 轴刻度不动可以强制设置 min，max

**Comment by duanshanchong** [comment]
是这样，x轴的数据量很多，比如我想看90天的数据，x轴为时间已天为刻度，此时手机屏幕宽度放不下，如果我在外层套一个div，设置overflow:auto,这样在向左横向滑动图表的时候，y轴会跟着向左滚动，偏离到屏幕外，我期望是y轴保持不动，右侧的图表可以移动。

**Comment by KID-joker** [comment]
@duanshanchong 请问你有解决方案吗
