### ISSUE TITLE
当使用地图时，map和effectScatter格式，颜色问题

### ISSUE THREAD

**Issue by DRUNK2013** [ecomfe/echarts#2725]
当使用地图时，使用了两种数据：
1、map需要使用添加visualMap：图例http://echarts.baidu.com/demo.html#map-china-dataRange
2、当再次添加一层地图，格式为effectScatter：图例http://echarts.baidu.com/demo.html#effectScatter-map   发现effectScatter的颜色不能自定义，这样颜色和地图的颜色一致，无法辨别。请问，怎么修改呀？

**Comment by pissang** [comment]
visualMap 可以指定作用的系列 http://echarts.baidu.com/option.html#visualMap-continuous.seriesIndex

**Comment by zhongjyuan** [comment]
最后两层图层可以同步进行缩放嘛？
