### ISSUE TITLE
npm 安装 ，打开页面提示 Map  not exists 

### ISSUE THREAD

**Issue by HelKyle** [ecomfe/echarts#2726]
我需要绘制中国地图，但是打开页面提示 Map  not exits 是我漏了什么东西吗？

**Comment by pissang** [comment]
需要 `require('echarts/map/js/china');`

**Comment by HelKyle** [comment]
非常感谢，要是能在开发文档里面说明一下就更好了

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#geo.map
