### ISSUE TITLE
3.x bug: markLine.symbolOffset设置无效，曲度无效

### ISSUE THREAD

**Issue by 276509842** [ecomfe/echarts#2733]
想要实现效果：
    想用lines线集，串联组织结构，且组织间是有向的

1、lines的连线，不能加箭头，但是可以设置曲度
2、markline，可加箭头，但曲度设置无效

期望需求：
1、lines可设置symbol
2、可设置symbol的位置，比如在线中间显示
   

symbolOffset无效：
![qq 20160304105755](https://cloud.githubusercontent.com/assets/5961305/13516776/34900e16-e1f8-11e5-9222-33129eb0bf57.png)

markLine，data有一个设置symbol为none，报错：
![qq 20160304105803](https://cloud.githubusercontent.com/assets/5961305/13516775/348e8c08-e1f8-11e5-91cd-909e279e924d.png)

**Comment by qingweibinary** [comment]
我也面对同样问题

**Comment by pissang** [comment]
设置 symbol: 'none' 的 bug 已经在 https://github.com/ecomfe/echarts/commit/3b9497f554b55422cab1aa2c71e440cbd281db76 中修复

**Comment by 276509842** [comment]
@pissang markLine的曲度，能支持吗。
