### ISSUE TITLE
【建议】为什么不开issue template啊亲？

### ISSUE THREAD

**Issue by SuperZDev** [ecomfe/echarts#2734]
issue看着也是醉了，知道一直在努力迭代，但这可是一个一劳永逸的好事啊。

**Comment by 100pah** [comment]
开，马上就开~

**Comment by SuperZDev** [comment]
哈哈哈，好好好。还以为原来推PR给你们一直不接受，是因为不想开了。希望越来越好。

**Comment by pissang** [comment]
之前是因为还在斟酌

**Comment by SuperZDev** [comment]
嗯，我当时觉得可以先上，毕竟template如果不合适可以随时改，这对你们自己以及整个社区都是有好处的。
