### ISSUE TITLE
全局样式的textStyle属性无法设置X和Y轴样式

### ISSUE THREAD

**Issue by 95kg** [ecomfe/echarts#2736]
#### 问题简述 (One-line summary)
发现全局样式的textStyle属性根本没办法设置x和y轴的字体大小

#### 期望结果 (Expected behaviour)
全局可以设定横纵轴字体大小及其他样式，不然要在具体数据里塞样式就太头疼了。

#### ECharts配置项 (ECharts option) 
```javascript 
option = {
textStyle:{
fontSize:20
}
}

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#xAxis.axisLabel.textStyle
