### ISSUE TITLE
点击"区域缩放"，如果只选中一个系列的图形片段，会导致页面卡死。

### ISSUE THREAD

**Issue by laughing1** [ecomfe/echarts#2737]
#### 问题简述 (One-line summary)
在echarts官网，toolbox下的示例，点击"区域缩放"，如果选中区域中只包含一个系列的图形片段，会导致浏览器卡死。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts官网使用的版本
+ 浏览器类型和版本 (Browser version):chrome 48.0.2564.116 m
+ 操作系统类型和版本 (OS Version):windows 7

#### 重现步骤 (Steps to reproduce)
1.点击"区域缩放"按钮
2.只选中一条图线

#### 期望结果 (Expected behaviour)
对选中的图线缩放

#### 可能哪里有问题 (What went wrong)
可能区域缩放代码死循环了

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/17428656/13521961/6a1ff508-e227-11e5-89ae-577f30bd3d1b.png)

**Comment by pissang** [comment]
这个问题已修复。

**Comment by laughing1** [comment]
好的。
