### ISSUE TITLE
Sankey diagram, color option is not working 

### ISSUE THREAD

**Issue by sujith3g** [ecomfe/echarts#2738]
`color` option is not working with sankey diagram.
#### 版本及环境 (Version & Environment)
- ECharts 3.1.2 (ECharts version):
- Google Chrome Version 48.0.2564.116 (64-bit) (Browser version):
- OS X El Capitan (OS Version):
#### 重现步骤 (Steps to reproduce)
1. goto [this](http://echarts.baidu.com/demo.html#sankey-product) Sankey diagram example
2. use the following code

``` js
myChart.showLoading();
$.get('data/asset/data/product.json', function (data) {
    myChart.hideLoading();

    myChart.setOption(option = {
        title: {
            text: 'Sankey Diagram'
        },
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'

        },
        color:"green",
        series: [
            {
                type: 'sankey',
                layout:'none',
                data: data.nodes,
                links: data.links,
                itemStyle: {
                    normal: {
                        borderWidth: 1,
                        color:"green",
                        borderColor: '#aaa'
                    }
                },
                lineStyle: {
                    normal: {
                        curveness: 0.5
                    }
                }
            }
        ]
    });
});
```
#### Expected behaviour  && What went wrong

I'm expecting the items in Sankey diagram to be green coloured. But it uses the default color as below

<img width="662" alt="screen shot 2016-03-04 at 2 42 28 pm" src="https://cloud.githubusercontent.com/assets/1298779/13522924/5487dd0a-e218-11e5-9ee9-e53f9538aab3.png">

**Comment by SuperZDev** [comment]
Hi @sujith3g
Thx for the feedback.
**This is a Bug! Please wait for the fix.**

**Comment by SuperZDev** [comment]
**PR** is coming soon.
