### ISSUE TITLE
折线图， x， y 轴同时type设置为category 图表报错

### ISSUE THREAD

**Issue by xyxiao001** [ecomfe/echarts#2739]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.2
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): windows 8.1

#### 重现步骤 (Steps to reproduce)
1.  
2.

#### 期望结果 (Expected behaviour)
      
y轴显示等级 A，B,C

#### 可能哪里有问题 (What went wrong)

y轴设置为category会报错 ， value可以

#### ECharts配置项 (ECharts option)

```javascript
option = {
      tooltip: {
          trigger: 'axis',
          backgroundColor: 'rgba(0,0,0,0.5)',
          formatter: function (a) {
            var level
            switch (a[0].data) {
              case 1: level = 'A'; break
              case 2: level = 'B'; break
              case 3: level = 'C'; break
            }
            return a[0].name + '<br/>' + a[0].seriesName + ':' + level
          }
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: [{
          type: 'category',
          boundaryGap: false,
          data: this.labels,
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        yAxis: [{
          type: 'category',
          data: ['A', 'A', 'B', 'C'],
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        series: [{
          name: this.name,
          type: 'line',
          stack: '等级',
          smooth: false,
          data: datasets
        }],
        color: ['#8ad7da']
}

```

**Comment by pissang** [comment]
双类目轴见示例 http://echarts.baidu.com/gallery/editor.html?c=scatter-punchCard

**Comment by xyxiao001** [comment]
var datasets = []
      for (var i = 0; i < this.data.length; i++) {
        switch (this.data[i]) {
          case 'A': datasets[i] = 1; break
          case 'B': datasets[i] = 2; break
          case 'C': datasets[i] = 3; break
        }
      }

出现  Uncaught TypeError: Cannot read property 'type' of undefined  问题

**Comment by xyxiao001** [comment]
<template>
  <div id="{{ id }}" class="lineChart"></div>
</template>

<script>
  import echarts from 'echarts'

  export default {
    props: ['id', 'labels', 'data', 'name'],
    ready () {
      var myChart = echarts.init(document.getElementById(this.id))
      var datasets = []
      for (var i = 0; i < this.data.length; i++) {
        switch (this.data[i]) {
          case 'A': datasets[i] = 1; break
          case 'B': datasets[i] = 2; break
          case 'C': datasets[i] = 3; break
        }
      }
      myChart.setOption({
        tooltip: {
          trigger: 'axis',
          backgroundColor: 'rgba(0,0,0,0.5)',
          formatter: function (a) {
            var level
            switch (a[0].data) {
              case 1: level = 'A'; break
              case 2: level = 'B'; break
              case 3: level = 'C'; break
            }
            return a[0].name + '<br/>' + a[0].seriesName + ':' + level
          }
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: [{
          type: 'category',
          boundaryGap: false,
          data: this.labels,
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        yAxis: [{
          type: 'category',
          data: ['A', 'A', 'B', 'C'],
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        series: [{
          name: this.name,
          type: 'line',
          stack: '等级',
          smooth: false,
          data: datasets
        }],
        color: ['#8ad7da']
      })
    }
  }
</script>

**Comment by xyxiao001** [comment]
<template>
  <div id="{{ id }}" class="lineChart"></div>
</template>

<script>
  import echarts from 'echarts'

  export default {
    props: ['id', 'labels', 'data', 'name'],
    ready () {
      var myChart = echarts.init(document.getElementById(this.id))
      var datasets = []
      for (var i = 0; i < this.data.length; i++) {
        switch (this.data[i]) {
          case 'A': datasets[i] = 1; break
          case 'B': datasets[i] = 2; break
          case 'C': datasets[i] = 3; break
        }
      }
      myChart.setOption({
        tooltip: {
          trigger: 'axis',
          backgroundColor: 'rgba(0,0,0,0.5)',
          formatter: function (a) {
            var level
            switch (a[0].data) {
              case 1: level = 'A'; break
              case 2: level = 'B'; break
              case 3: level = 'C'; break
            }
            return a[0].name + '<br/>' + a[0].seriesName + ':' + level
          }
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: [{
          type: 'category',
          boundaryGap: false,
          data: this.labels,
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        yAxis: [{
          type: 'category',
          data: ['A', 'A', 'B', 'C'],
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        series: [{
          name: this.name,
          type: 'line',
          stack: '等级',
          smooth: false,
          data: datasets
        }],
        color: ['#8ad7da']
      })
    }
  }
</script>

**Comment by xyxiao001** [comment]
**<template>
  <div id="{{ id }}" class="lineChart"></div>
</template>

<script>
  import echarts from 'echarts'

  export default {
    props: ['id', 'labels', 'data', 'name'],
    ready () {
      var myChart = echarts.init(document.getElementById(this.id))
      var datasets = []
      for (var i = 0; i < this.data.length; i++) {
        switch (this.data[i]) {
          case 'A': datasets[i] = 1; break
          case 'B': datasets[i] = 2; break
          case 'C': datasets[i] = 3; break
        }
      }
      myChart.setOption({
        tooltip: {
          trigger: 'axis',
          backgroundColor: 'rgba(0,0,0,0.5)',
          formatter: function (a) {
            var level
            switch (a[0].data) {
              case 1: level = 'A'; break
              case 2: level = 'B'; break
              case 3: level = 'C'; break
            }
            return a[0].name + '<br/>' + a[0].seriesName + ':' + level
          }
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: [{
          type: 'category',
          boundaryGap: false,
          data: this.labels,
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        yAxis: [{
          type: 'category',
          data: ['A', 'A', 'B', 'C'],
          axisLine: {
            lineStyle: {
              color: '#6ca7dd'
            }
          },
          axisTick: {
            show: false
          }
        }],
        series: [{
          name: this.name,
          type: 'line',
          stack: '等级',
          smooth: false,
          data: datasets
        }],
        color: ['#8ad7da']
      })
    }
  }
</script>
**

**Comment by xyxiao001** [comment]
http://echarts.baidu.com/gallery/editor.html?c=scatter-punchCard
官网例子版本升级同样存在问题   3.1.2之前可以设置 双坐标轴type为category，  升级版本后无法正常显示

**Comment by WuLiuxi** [comment]
@pissang 3.1.2新 issue，麻烦 check 一下，谢谢。

**Comment by pissang** [comment]
怎么复现问题？

**Comment by WuLiuxi** [comment]
双类目轴见示例 http://echarts.baidu.com/gallery/editor.html?c=scatter-punchCard在3.1.2版本上报错：Cannot read property 'type' of undefined。

**Comment by pissang** [comment]
现在官方实力上运行的就是 3.1.2 版本

**Comment by WuLiuxi** [comment]
@pissang 对比了一下哈希值，官方实例引用的是3.1.2版本：http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js ，谢谢了。
