### ISSUE TITLE
map zoom event

### ISSUE THREAD

**Issue by ldllidonglin** [ecomfe/echarts#2741]
Hi, I want to bind some mousewheel events to the map,such as 'zoomend' or 'zoomstart'. but I look the  http://echarts.baidu.com/api.html#events, I didn't found that. so I want to know whether the echarts3 suppport these function

**Comment by ldllidonglin** [comment]
I look the source code ,found the 'bmapRoam' event but this event only have type attribute。

**Comment by ldllidonglin** [comment]
I add the 'level' attribute to the 'bmapRoam' in the source code.
`function zoomEndHandler() {
	 if (rendering) {
	      return;
	}
	 api.dispatchAction({
	          type: 'bmapRoam',
	          level: bmap.getZoom()
	 });
 }`
so I can get the map level.

**Comment by pissang** [comment]
`bmapRoam` is event of bmap extension, map event is `geoRoam`. It is event for inside usage, not suggest using it outside

**Comment by ldllidonglin** [comment]
OK,I get it,but I must  get the level of bmap in my application.
thank you
