### ISSUE TITLE
请问如何 多series时 timeline只改变其中一个的值

### ISSUE THREAD

**Issue by R-River** [ecomfe/echarts#2743]
#### 问题简述 (One-line summary)

请问多个series时 只有一个series和时间轴连接 另一个保持不变 可以设置吗？

比如一个柱状图旁边加一个饼图 表示某几个项的比例 会变化 而柱形图保持不变

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.2.7
+ 浏览器类型和版本 (Browser version): chrome+IE11
+ 操作系统类型和版本 (OS Version): window 7/10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by R-River** [comment]
ok 已解决

**Comment by ZhuGYao** [comment]
如何解决的，求解决方法，万分感谢
