### ISSUE TITLE
echarts3.0 折柱切换后，柱形图越界

### ISSUE THREAD

**Issue by xiao8cn** [ecomfe/echarts#2745]
#### 问题简述 (One-line summary)
echarts3.0 折柱切换后，柱形图越界。

描述：
在2.0 ，折柱切换，在xAix 中加上配置 boundaryGap:false ，能让折线图顶着边界，切换成柱形图，也是相同效果。
在3.0 中，使用这个属性后，折线图顶着边界了。但同时柱形图也产生了相同量的偏移，导致柱形图越界了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.在3.0，折柱图中，使用boundaryGap:false 参数 ，切换
2.

#### 期望结果 (Expected behaviour)
折线图和柱形图，都能顶着边界展示

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 2769842232** [comment]
原有的切换按钮  并且在原有的切换按钮上添加工具箱  点击切换折线图没有异常 但是在点击原有的切换柱形图的话就回柱形图的显示超出原有的边界
