### ISSUE TITLE
echarts3 myChart.on('legendselected',function(){}) 不起作用

### ISSUE THREAD

**Issue by IlovedJoey** [ecomfe/echarts#2749]
按照echarts3 文档新的触发事件应该是通过 on 直接注册事件名称，但是通过下面方式却发现不起作用。
直接绑定click 这种是可用的。
```js
//可用
myChart.on('click',function(){
	console.log("test click");
});

//不可用
myChart.on('legendselected',function(){
	console.log("test legendselected");
});
```

请问echarts 3 如何绑定触发 legendselected 的事件？

**Comment by IlovedJoey** [comment]
官网写的是通过dispatchAction ，但我忒笨，实在没找到 dispatchAction的配置里如何自定义function写自己逻辑代码。示例里目前也没针对这些 event 和 action的实现示例，请有用过朋友发个示例，tks

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#events.legendselectchanged 图例切换事件是这个

**Comment by insekkei** [comment]
@IlovedJoey 我也是看api也看不明白的...但是他们一句话就解释完了...

**Comment by IlovedJoey** [comment]
@insekkei  pissang提醒的是对的，我之前用的事件不对，图例转换用legendselectchanged 事件就可绑定成功了。不过官方例子目前确实没有echarts 2 时完善，希望后续能继续更新
myChart.on("legendselectchanged",function(){
    alert("legendselectchanged");
})
