### ISSUE TITLE
桑基图的json数据怎么下载下来，不然显示数据加载不出来

### ISSUE THREAD

**Issue by zhangxuanlin** [ecomfe/echarts#2750]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/17699676/13564825/64ec1802-e487-11e5-9018-675ec01b13d8.png)

**Comment by AsaZws** [comment]
同问
