### ISSUE TITLE
折线图当所有数值都相同并且设置展示最大值最小值标记时，最大值最小值都出现在最后一条数据上

### ISSUE THREAD

**Issue by EyrebaLeo** [ecomfe/echarts#2761]
#### 问题简述 (One-line summary)

折线图当所有数值都相同并且设置展示最大值最小值标记时，最大值最小值都出现在最后一条数据上
#### 版本及环境 (Version & Environment)
- ECharts 版本 (3.1.2):
- 浏览器类型和版本 (Chrome，版本 48.0.2564.116 m):
- 操作系统类型和版本 (windows7 专业版):
#### 重现步骤 (Steps to reproduce)

1.设置一组数据，每条数据的值都相等，并填充在series中的data里
2.设置series的type为‘line’，同时设置展示markPoint，其中的type为‘max’和‘min’
3.setOption，会发现最大值最小值都出现在最后一条数据上
#### 期望结果 (Expected behaviour)

1.最大值最小值的标记出现在第一条数据上
#### 可能哪里有问题 (What went wrong)

排序算法的问题
#### ECharts配置项 (ECharts option)

``` javascript
option = {
xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLabel : {
                formatter: '{value} °C'
            }
        }
    ],
    series : [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 11, 11, 11, 11, 11],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
        }
    ]
}

```

**Comment by pissang** [comment]
依据？

**Comment by EyrebaLeo** [comment]
@pissang 
![image](https://cloud.githubusercontent.com/assets/17735331/13626804/487dd3fc-e600-11e5-8ff7-4749ecd6bc6c.png)
echarts2.2.7上就是显示在第一条数据上的
