### ISSUE TITLE
当坐标轴为time轴时，柱状图无法绘制

### ISSUE THREAD

**Issue by EyrebaLeo** [ecomfe/echarts#2763]
#### 问题简述 (One-line summary)
当坐标轴为time轴时，柱状图无法绘制

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (3.1.2):
+ 浏览器类型和版本 (Chrome，版本 48.0.2564.116 m):
+ 操作系统类型和版本 (windows7 专业版):

#### 重现步骤 (Steps to reproduce)
1.将坐标轴设为time轴，series中的type改为’bar‘
2.setOption绘制图形

#### 期望结果 (Expected behaviour)
能够得到柱状图图形

#### 可能哪里有问题 (What went wrong)
对时间轴不支持

#### ECharts配置项 (ECharts option)

```javascript
option = {
tooltip:{
        show:true,
        trigger:'axis'
    },
    xAxis : [
        {
            type : 'time',
            boundaryGap : false,
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLabel : {
                formatter: '{value} °C'
            }
        }
    ],
    series : [
        {
            name:'最高气温',
            type:'bar',
            data:[['2016-03-09 10:00',11],['2016-03-09 11:00',15]],

            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            }
        }
    ]
}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/17735331/13624178/c4761de4-e5e6-11e5-896f-18671a21bb7c.png)

**Comment by pissang** [comment]
柱状图暂时不支持时间类型的坐标轴

**Comment by EyrebaLeo** [comment]
@pissang 大概什么时候会对柱状图的时间类型进行支持呢？

**Comment by pissang** [comment]
已提交柱状图支持 time 类型轴的代码，下个版本发布
