### ISSUE TITLE
多个柱子用stack的形式显示的时候，让label完全独立于各个bar，自定义？

### ISSUE THREAD

**Issue by xxlv** [ecomfe/echarts#2769]
#### 问题简述 (One-line summary)
对于单个bar的label可以使用formatter，但是，当用stack将bar累积在一个x的时候，有没有办法，支持，只显示一个label，这个label在该x的最上方显示（或者自定义的任何地方）？

点x1,和x2的bar1和bar2，在x1的点，bar1是高一点的，在x2的时候，bar2是高一点的，支持一种label显示，显示在最高处的那个位置，并且它的值时可以被定义的。

**Comment by stingh711** [comment]
why close it without any comment?
