### ISSUE TITLE
k线可不可以这样显示

### ISSUE THREAD

**Issue by baichi** [ecomfe/echarts#2770]
http://chuantu.biz/t2/30/1457509041x2016702815.jpg

如这个图所示，显示一半儿或者某一个x轴，而不是铺满，通过某一个事件后继续绘制后边的k线

**Comment by pissang** [comment]
数据设成 '-'

**Comment by baichi** [comment]
这是一个变通的方法。
我这么做了，实现了，但是我有交互需求：
此时我点击某条数据让他继续绘制呢，而不是重新全部绘制
我想到的做法是在init一个k线，起点在之前的终点。。。

我想问的是能不能只有一条k线，而不是开起来是一条，需要怎么做，谢谢。
