### ISSUE TITLE
求助T.T~~力导force节点，鼠标浮动上去后出现的黄颜色的轮廓，如何取消这个事件呢？

### ISSUE THREAD

**Issue by Yohann617** [ecomfe/echarts#2771]
如题，在官网给的几个力导向布局图中，当鼠标放在生成的节点上时，会出现一圈黄颜色的高亮样式，
现在想取消掉这个事件，不知道如何处理呢？
我之前感觉是itemStyle中的emphasis引起的，可是好像去掉之后并没有任何的反应，而且力导似乎没有提供类似“hoverable:false”，这样的做法。
上网查了很多资料也没用一点头绪。
所以实在是没办法了，在此请求看到的大神们能给我一点提示，真的十分感谢！！
图片上传不成功，这是力导的其中一个例子的网址：
http://echarts.baidu.com/echarts2/doc/example/force1.html

PS：我用的是echarts2.x的版本,3.0的由于一些问题，暂时用不上...

**Comment by BUT-HE** [comment]
这个问题解决了吗
