### ISSUE TITLE
建议折线图需要类似step line形式的扩展，即在X轴或者Y轴 直角转弯

### ISSUE THREAD

**Issue by Terry-Jiang** [ecomfe/echarts#2772]
#### 问题简述 (One-line summary)

建议折线图需要类似step line形式的扩展，即在X轴或者Y轴 直角转弯
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/12960627/13629107/c52622d6-e611-11e5-89be-cc75afd32aa0.png)

**Comment by ptma** [comment]
支持，一直在观望 ECharts 是否支持 Step Line

**Comment by vnnw** [comment]
顶！

**Comment by Shijihao** [comment]
能够直角转弯嘛？

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.step
