### ISSUE TITLE
移动端改变dataZoom 很卡

### ISSUE THREAD

**Issue by liulingmin** [ecomfe/echarts#2777]
你好

用absoluteZoom 在移动端滑动时，整个图表滑动会很卡，请问有什么解决方法嘛

**Comment by pissang** [comment]
用 echarts 3

**Comment by liulingmin** [comment]
用 3 也是很卡，而且K 线图的方块会在滑动中消失，滑动停止会显示出来。
用2 就不能解决嘛

**Comment by pissang** [comment]
k 线图？animation: false

**Comment by liulingmin** [comment]
用了这个之后，是有改进。但是还是挺卡的

**Comment by NeilJee** [comment]
我也遇到这个问题，安卓机上面，slider拖动有问题，向左滑slider，结果slider向右滑；点击倒是可以移动。
