### ISSUE TITLE
求助~~力导force，在移动端上，鼠标点击事件和拖动事件冲突了...应该怎么解决呢？

### ISSUE THREAD

**Issue by Yohann617** [ecomfe/echarts#2778]
大神，求助~~如题，力导force的例子，放在在移动端上，点击节点，鼠标点击事件和拖动事件冲突了...导致点击事件出不来，在series中设置“draggable: false”之后，点击事件触发了。
所以，应该怎么处理，才能使得这两个事件都能实现呢？

**Comment by 15670501230** [comment]
解决了吗？我也遇到了这个问题，求指导
