### ISSUE TITLE
tooltip通过click触发后怎样隐藏？

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#2779]
#### 问题简述 (One-line summary)
tooltip通过click触发后，怎样可以隐藏掉出现的tooltip？否则点击之后就会一直出现在那里

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
click
