### ISSUE TITLE
求问-visualMap可以设置x轴方向的视觉元素吗

### ISSUE THREAD

**Issue by luxueyan** [ecomfe/echarts#2786]
例如气泡图，我想让颜色随着x轴越来越深，能做到吗

**Comment by pissang** [comment]
能，visualMap 的 dimension 设置成 0

**Comment by luxueyan** [comment]
@pissang 试了一下可以！Thanks！

**Comment by weidadedawei** [comment]
visualMap[i]-continuous.orient string
[ default: 'vertical' ]
如何放置 visualMap 组件，水平（'horizontal'）或者竖直（'vertical'）。

我设置 orient: 'horizontal',  垂直变水平
