### ISSUE TITLE
tooltip溢出边界

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#2788]
#### 问题简述 (One-line summary)

当tooltip里面的内容较多时，会溢出浏览器边界。具体表现如图所示，tooltip是否应该加上浏览器边界检测功能，当遇到边界时保持位置不动？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/6983075/13664848/715eb9aa-e6e4-11e5-8fbe-60a68b63f6e2.png)

**Comment by pissang** [comment]
3.4.0 开始加入 http://echarts.baidu.com/option.html#tooltip.confine 配置项防止溢出
