### ISSUE TITLE
滚动 X轴，实现类似滚动条效果，而不是缩放

### ISSUE THREAD

**Issue by liupei2012** [ecomfe/echarts#2789]
#### 问题简述 (One-line summary)

 当 X轴数据很多的时候，滑动 X 轴的时候，不想要缩放效果，而是屏幕外侧右边的内容会跟随滚动屏幕视野中来，左侧的内容会自动滑到左边（隐藏），类似一个滚动条的效果，这个怎么弄？急求。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0

**Comment by pissang** [comment]
dataZoom

**Comment by liupei2012** [comment]
问题解决了，具体一点应该说是zoomLock：true;这个属性会实现只滚动不缩放；然后还可以更详细点来保证视野范围`dataZoom: [{
                    type: 'inside',
                    startValue: 0,
                    endValue: 7,
                    zoomLock: true
                }]`

**Comment by yhhwpp** [comment]
设置 `zoomLock` 后，移动端上下拖动，就不能滚动页面了，怎么破？

**Comment by liaoliaokl** [comment]
怎么显示滚动条呢，目前是不显示滚动条
