### ISSUE TITLE
当X轴为类目轴时inside型的datazoom放大缩小后的数据不太对劲

### ISSUE THREAD

**Issue by EyrebaLeo** [ecomfe/echarts#2793]
#### 问题简述 (One-line summary)
当X轴为类目轴时，inside型的datazoom在鼠标滚轮的作用下放大缩小，会出现部分数据显示不全的情况

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (3.1.3):
+ 浏览器类型和版本 (Chrome，版本 49.0.2623.87 m):
+ 操作系统类型和版本 (windows7专业版):

#### 重现步骤 (Steps to reproduce)
1.将X轴设置为类目轴，并且设置inside类型的datazoom
2.鼠标滚轮在图形内部滚动，会发现图形发生变化，但是有部分指标在当前类目轴坐标明明有数据，图上却没有画出来，而是断开了

#### 期望结果 (Expected behaviour)
有数据的部分能够正常展示

#### 可能哪里有问题 (What went wrong)
不太清楚

#### ECharts配置项 (ECharts option)

```javascript
option = {
    title : {
        text: '某站点用户访问来源',
        subtext: '纯属虚构',
        x:'center'
    },
    dataZoom:[{
        type:'inside',
        xAxisIndex:0,
    },
    {
        type:'inside',
        yAxisIndex:0
    }],
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        show:false,
        orient : 'vertical',
        x : 'left',
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    xAxis : [
        {
            type : 'category',
            data : ['周一','周二','周三','周四','周五','周六','周日'],
            boundaryGap:false
        }
    ],
    yAxis : [
        {
            type : 'value',
            splitArea : {show : true}
        }
    ],
    grid: {
        x2:40
    },
    series : [

        {
            name:'联盟广告',
            type:'line',
            data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
            name:'视频广告',
            type:'line',
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'搜索引擎',
            type:'line',
            data:[820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
};

```

#### 其他信息 (Other comments)

这是缩放前，每个指标在每个类目上都有数据：
![image](https://cloud.githubusercontent.com/assets/17735331/13691104/0b43533c-e771-11e5-8cb2-033a53f3a050.png)
缩放后，第一条绿色的线在周五周六是有数据的，但是没有画出来
![image](https://cloud.githubusercontent.com/assets/17735331/13691134/39e88b8a-e771-11e5-8ad5-e3b28026877a.png)

**Comment by pissang** [comment]
不要设置 yAxisIndex，那样会缩放 y 轴
