### ISSUE TITLE
在线构建的js，使用最简单的demo时报错。

### ISSUE THREAD

**Issue by xlkit456852** [ecomfe/echarts#2794]
#### 问题简述 (One-line summary)
在线构建的js，使用时报错。

#### 版本及环境 (Version & Environment)
+ ECharts3 (ECharts version):
+ 谷歌浏览器44.0.2403.157 (Browser version):
+ win7 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.在官网在线构造我想要的功能，然后下载js
2.使用最简单的demo时，报错：Uncaught TypeError: e.nice is not a function

#### 期望结果 (Expected behaviour)
至少最简单的demo能用上吧

#### 可能哪里有问题 (What went wrong)
由于我下载完整版的时候，是可以正常使用的，所以我觉得应该是构建代码的时候有问题。

#### ECharts配置项 (ECharts option)

```javascript
option = {
title: {
                    text: 'ECharts 入门示例'
                },
                tooltip: {},
                legend: {
                    data:['销量']
                },
                xAxis: {
                    data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                },
                yAxis: {},
                series: [{
                    name: '销量',
                    type: 'bar',
                    data: [5, 20, 36, 10, 10, 20]
                }]
}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/7323450/13691570/f71b942e-e774-11e5-9435-0362f5dce06f.png)

**Comment by pissang** [comment]
我这没问题，可能是因为缓存的原因

**Comment by xlkit456852** [comment]
但我这里用谷歌和火狐都试过，都是报这个错。有没可能是代码构建不完整？因为我这里访问官网都很慢，构建的时候很多时候等很久都没反应，然后弄了几次才成功下载了。
