### ISSUE TITLE
如何打包？

### ISSUE THREAD

**Issue by john-chow** [ecomfe/echarts#2795]
#### 问题简述 (One-line summary)

我修改了部分Echarts关于动画的代码。我想请教，你们是如何打包成最终的单个文件？

Echarts版本： 3.1.1

**Comment by pissang** [comment]
ECharts 3.1.3 开始使用 webpack 打包

1. 从 https://nodejs.org/en/ 下载安装 node.js
2. 在 echarts 目录下运行 `npm install` 安装依赖
3. 运行 `build/build.sh` 打包。

**Comment by pissang** [comment]
运行 build 目录下面的 build.sh，如果是 windows 的话也可以修改成相应的脚本
