### ISSUE TITLE
yaxis value not the expected value

### ISSUE THREAD

**Issue by fernandodbc** [ecomfe/echarts#2810]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.3

#### 可能哪里有问题 (What went wrong)

y axis value is not good in my project but also in echarts examples : http://echarts.baidu.com/echarts2/doc/example/line2.html#-en

the real value is 932 but the line is shown between 1500 and 2000

![capture_d ecran_2016-03-11_a_15_40_39](https://cloud.githubusercontent.com/assets/4182191/13705372/d8a351f4-e7a0-11e5-891f-933507196d2f.png)

but if we disable all the others lines the y axis value is good

![capture_d ecran_2016-03-11_a_15_46_18](https://cloud.githubusercontent.com/assets/4182191/13705386/e9984672-e7a0-11e5-8abc-5ee34e40c256.png)

**Comment by pissang** [comment]
It is because you set the stack in series. Which will cause value in series will be added value in previous series with same stack
