### ISSUE TITLE
IE8下缩放线条错乱并把显示信息给遮挡了

### ISSUE THREAD

**Issue by tandaly** [ecomfe/echarts#2812]
#### 问题简述 (One-line summary)

[
![qq 20160308171903](https://cloud.githubusercontent.com/assets/3762187/13720735/3ed1d4f0-e84b-11e5-8fdd-00594cddd9b3.png)
](url)

提示信息被线条遮住，当滚动缩放图表，线条出现混乱。在chrome下正常，IE8下出现了此问题。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.3
+ 浏览器类型和版本 (Browser version): IE8
+ 操作系统类型和版本 (OS Version): win7

#### 重现步骤 (Steps to reproduce)
1.鼠标移到图上，提示信息被线条挡住
2.当鼠标滚动缩放时，线条出现混乱

#### 期望结果 (Expected behaviour)
不要出现提示信息被挡住，线条不出现混乱

#### 可能哪里有问题 (What went wrong)
兼容性问题，在Chrome浏览器中正常，在IE8中就出现了问题

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
关闭动画试试

**Comment by tandaly** [comment]
还是没有用，我是这么设置的：

```js
tooltip : {
		        trigger: 'axis',
		        axisPointer:{
		    		animation: true
		    	}
		    }
```

**Comment by pissang** [comment]
新版本应该没这个问题了
