### ISSUE TITLE
xAxis.type的time时间轴最小间隔是不是不能达到秒？

### ISSUE THREAD

**Issue by wly2014** [ecomfe/echarts#2813]
#### 问题简述 (One-line summary)
xAxis.type的time时间轴最小间隔是不是不能达到秒？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
文档中：''time' 时间轴，适用于连续的时序数据，与数值轴相比时间轴带有时间的格式化，在刻度计算上也有所不同，例如会根据跨度的范围来决定使用月，星期，日还是小时范围的刻度。'
而且我在代码中这么写：
```js
return {
        name: now.toString(),
        value: [
            now.getHours()+":"+now.getMinutes()+":"+now.getSeconds(),
            Math.round(value)
        ]
    }
```
没有画出来任何的折线图
#### 可能哪里有问题 (What went wrong)
是不是最小间隔不能为秒？还是我的return格式写错了？

#### ECharts配置项 (ECharts option)

```javascript
option = {
跟官网上的一样
}

```

**Comment by pissang** [comment]
可以，看 http://echarts.baidu.com/gallery/editor.html?c=dynamic-data2 这个示例

**Comment by bestplay** [comment]
@pissang 
示例中，时间刻度是**天**

我错过了什么？？

**Comment by bestplay** [comment]
I think i fixed it.

`
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/') + " " + now.getHours()+":"+now.getMinutes()+":"+now.getSeconds(),
            Math.round(value)
        ]
    }`

**now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/') + " " + now.getHours()+":"+now.getMinutes()+":"+now.getSeconds()**
