### ISSUE TITLE
ipython notebook 无法引入 echarts

### ISSUE THREAD

**Issue by clarkchen** [ecomfe/echarts#2814]
#### 问题简述 (One-line summary)
是这样的，我之前在ipython notebook 中可以引入 d3.js，现在我想用同样的方法引入 echarts进行绘图

引入方法如下
```
%%html
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="http://echarts.baidu.com/dist/echarts.min.js"></script>
```
然后在chrome的console 中 输入 d3 能够正常显示, 但是输入 echarts 提示无法找到，如下图
![image](https://cloud.githubusercontent.com/assets/1352085/13721995/ed90dc36-e871-11e5-8666-7a5788eba840.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): echarts 3.1.3
+ 浏览器类型和版本 (Browser version): 版本 49.0.2623.87 (64-bit)
+ 操作系统类型和版本 (OS Version): mac osx 10.11.3

#### 重现步骤 (Steps to reproduce)
* 命令行执行 `ipython notebook `
* 新建一个notebook
*  输入 %%html 引入 js 如下
```
%%html
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="http://echarts.baidu.com/dist/echarts.min.js"></script>
```
* 打开chrome 元素检查 console Tab
* 输入 d3 (检查d3.js 是否成功加载)
* 输入 echarts (检查 echarts 是否成功加载)

#### 期望结果 (Expected behaviour)

![image](https://cloud.githubusercontent.com/assets/1352085/13722019/909d0530-e872-11e5-86f0-4e9b6df33d73.png)

#### 可能哪里有问题 (What went wrong)
最直接的问题是  echarts 无法引入
是不是ipython的内部机制和你们的实现有冲突

#### ECharts配置项 (ECharts option)

我用的就是范例的option，压根都没到这步就挂了，，，
```javascript
option = {
title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
}

```

**Comment by clarkchen** [comment]
很神奇，甚至都不需要执行 ipython 的任何代码，直接在congsole 中做如下测试

```
// echarts
 var jquery = document.createElement('script'); 
jquery.src = "http://echarts.baidu.com/dist/echarts.min.js";
document.head.appendChild(jquery);
// Console 中输入 echarts 报错没有Define

// d3
var jquery = document.createElement('script'); 
jquery.src = "http://d3js.org/d3.v3.min.js";
document.head.appendChild(jquery);
// Console 中输入 d3 正常

// hightcharts
var jquery = document.createElement('script'); 
jquery.src = "http://code.highcharts.com/highcharts.js";
document.head.appendChild(jquery);
// Console 中输入 Hightcharts 正常```

结果如下
![image](https://cloud.githubusercontent.com/assets/1352085/13722129/193b3248-e875-11e5-936f-a2f3ef619f61.png)

**Comment by pissang** [comment]
你看下环境，有没有 require，echarts 打包文件是 UMD(https://github.com/umdjs/umd) 的格式，多个环境的加载方式不太一样，有 require 的话得用 require 加载

**Comment by clarkchen** [comment]
您好，是有require的，我用require 加载的方式是可以使用的

但是貌似和 http://cdn.amazeui.org/require.js/2.1.16/require.js 这个最新版的require 不一样，不知道是否影响
notebook 中的 require
![image](https://cloud.githubusercontent.com/assets/1352085/13764678/edfe729c-ea8c-11e5-8192-719837b1298c.png)

最新版的 require
![image](https://cloud.githubusercontent.com/assets/1352085/13764736/7eb0d60e-ea8d-11e5-95a9-606587552fc1.png)

难道是同一份代码，做了代码混淆？

**Comment by pissang** [comment]
应该是
