### ISSUE TITLE
窗口大小变化后，调用resize（），dataZoom却没有被resize

### ISSUE THREAD

**Issue by nwuns** [ecomfe/echarts#2816]
#### 问题简述 (One-line summary)
窗口大小变化后，dataZoom 没有被resize
目前使用的auto resize 方法为：
```js
        window.onresize = function () {
            $(".section-chart").each(function () {
                var id = $(this).attr('_echarts_instance_');
                window.echarts.getInstanceById(id).resize();
            });
        };
```

2016-03 最新下载的echarts.min.js出现这个问题，可是曾经在1，2个月之前下载的，就没有这个问题
搜索了issues，发现曾经解决过，不知道为啥又出现了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): chrome， firefox
+ 操作系统类型和版本 (OS Version): windows10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by talatbaig** [comment]
datazoom on chrome still does not work for this
http://echarts.baidu.com/demo.html#area-simple

**Comment by pissang** [comment]
@talatbaig It's fixed just now in the source code and will be in the next release

**Comment by talatbaig** [comment]
thank you!
When is the next release coming out?

**Comment by pissang** [comment]
Next week.

**Comment by nwuns** [comment]
thank you~ all
