### ISSUE TITLE
多次对实例执行showLoading()方法后，再执行hideLoading()后失效

### ISSUE THREAD

**Issue by tongxuehello** [ecomfe/echarts#2821]
#### 问题简述 (One-line summary)
多次对实例执行showLoading()方法后，再执行hideLoading()后失效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.3
+ 浏览器类型和版本 (Browser version):版本 49.0.2623.75 m
+ 操作系统类型和版本 (OS Version):windows7

#### 重现步骤 (Steps to reproduce)
1.init方法生成实例
2.对实例执行showLoading()方法
3.对实例执行showLoading()方法（图形底色有变化）
4.对实例执行showLoading()方法（图形底色有变化）
5.悲剧了，再hideLoading()时无法隐藏

#### 期望结果 (Expected behaviour)
对实例多次执行showLoading()操作相当于执行一次，不应该每次都发生变化;hideLoading()方法也一样。

**Comment by cxytomo** [comment]
@tongxuehello @pissang "对实例执行showLoading()方法（图形底色有变化）"，请问如何对遮罩层进行操作，好像没有找到配置项
