### ISSUE TITLE
急：关于柱状图'-'无数据情况。

### ISSUE THREAD

**Issue by flower233** [ecomfe/echarts#2830]
现在情况：每个月份是不一样的名称和数据，红框里一些没数据的还占着一个空位置。
我想实现的效果是：柱状图无数据的情况下，不占位置。还需要每月里的数据排序。（e2或e3都可以，急求实现）
![_20160316104406](https://cloud.githubusercontent.com/assets/17867075/13800518/e5aac914-eb64-11e5-8957-90b741c4a07f.png)

**Comment by netwww1** [comment]
我觉得这个空白在有时是有用处的，它可能反应了数据提交来源，在那个时间段发生了异常中断，避免用户或维护人员错误认为查询到的数据完全正常。

**Comment by flower233** [comment]
@netwww1 但我需要的是前10的数据而已，后面还有10多20个数据不要的为空

**Comment by ziyouren** [comment]
我觉得你可以自己先把数据过滤一遍，没有的不要加进来
