### ISSUE TITLE
点击事件如何实现？

### ISSUE THREAD

**Issue by ps7** [ecomfe/echarts#2833]
API讲了一大堆，居然没有完整的事件相关代码
示例也是一大堆，居然也没有事件相关的示例
作为一个成熟的项目实在是不应该啊

**Comment by giscafer** [comment]
http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA
