### ISSUE TITLE
高分辨率下图例的方块和文字错位

### ISSUE THREAD

**Issue by liekkas** [ecomfe/echarts#2834]
高分辨率1920*1080下，图例的小方块和文字错位。
1366*768分辨率下是没问题的。

[附图](http://7xkjpz.com1.z0.glb.clouddn.com/%E5%9B%BE%E4%BE%8B%E9%94%99%E4%BD%8D.png)

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/2819

**Comment by liekkas** [comment]
y轴文字和刻度线也有这个问题
