### ISSUE TITLE
柱图不让点击怎么把鼠标手势从手状改为默认的箭头形状？

### ISSUE THREAD

**Issue by liekkas** [ecomfe/echarts#2837]
#### 问题简述 (One-line summary)
柱图不让点击怎么把鼠标手势从手状改为默认的箭头形状？避免产生可以点击的假象

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.13
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): Mac OS

**Comment by pissang** [comment]
silent: false
