### ISSUE TITLE
官方能快点出angularjs 版本echarts么

### ISSUE THREAD

**Issue by harryhan1989** [ecomfe/echarts#2838]
目前第三方出的echarts for angularjs 大多各种问题，很难使用，官方有计划出angular版本echarts么？

**Comment by jolin9822** [comment]
顶，我也需要，同问

**Comment by hanwsscan** [comment]
顶，我也需要

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts#angularjs-binding

**Comment by c429013730** [comment]
同求
