### ISSUE TITLE
setOption大约10次，背景grid和title消失

### ISSUE THREAD

**Issue by xubuild** [ecomfe/echarts#2839]
#### 问题简述 (One-line summary)
使用类似‘教程‘中的柱状图，如果重复执行setOption，大约在第十次的时候，背景grid和title会消失。如果快速重复执行，有时会得到错误‘Uncaught TypeError: Cannot read property '__ec_stack_0' of undefined’，有时得到错误‘Uncaught TypeError: Cannot read property 'getAxis' of undefined’

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.3
+ 浏览器类型和版本 (Browser version): Chrome 50.0.2661.26 beta (64-bit)
+ 操作系统类型和版本 (OS Version): OS X 10.11.3

#### 重现步骤 (Steps to reproduce)

http://codepen.io/xubuild/pen/aNpOyL

1. chart.setOption(option1); 

2. 间隔500ms

3. chart.setOption(option2); 

4. 间隔500ms

5. 重复上述步骤，出错

**Comment by pissang** [comment]
chrome canary 的bug，同 https://github.com/ecomfe/echarts/issues/2682#issuecomment-192105982

**Comment by niuchunling** [comment]
请问这个要怎么解决呢

**Comment by niuchunling** [comment]
@pissang     请问这个问题怎么解决

**Comment by 100pah** [comment]
用 chrome 稳定版。
