### ISSUE TITLE
请问市级地图里面的坐标是怎么编码的？

### ISSUE THREAD

**Issue by ziyouren** [ecomfe/echarts#2842]
请问市级地图里面的坐标是怎么编码的？
如下：“@@CHGD@CAAMDGB@BE@@AG@CEWB@IE@AKBC@IGAQB@EGA@MEAGC”

我想把县级数据放在全国的地图里显示县级轮廓，把市级的放入可以，县级的放入出不来

**Comment by R-River** [comment]
这是把地理坐标压缩后的编码 http://ecomfe.github.io/echarts-map-tool/这里可以得到不压缩的 精确到县级轮廓的json文件

**Comment by ziyouren** [comment]
多谢

**Comment by tommyjiang** [comment]
@R-River  您好，我想问下利用
http://ecomfe.github.io/echarts-map-tool/
能否实现只选择部分省份生成地图？例如生成一个包含京津冀的 JSON 文件，谢谢。

**Comment by R-River** [comment]
@tommyjiang 这个在线工具本身是不支持的 不过应该可以把京津冀的地图json下载下来后 手动把三个geojson拼接 然后手动注册一个地图类型 按理说是没什么问题的 不过我没有完整这么做过。。

**Comment by tommyjiang** [comment]
@R-River 好的，多谢，我自学下试试。
