### ISSUE TITLE
3.0中没有tree图，什么时候会有，还是说3中不会有

### ISSUE THREAD

**Issue by peggypan** [ecomfe/echarts#2848]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
短期内不会有
