### ISSUE TITLE
饼图 单数据下图不见了……

### ISSUE THREAD

**Issue by yuandluck** [ecomfe/echarts#2849]
IE8下单数据下不显示，关闭动画效果也一样，IE9下可以
图片传不上来郁闷、、

**Comment by jlfan99** [comment]
遇到同样的问题。另外，IE8下tooltip渲染在最底层，总是被数据图形遮挡。

**Comment by jlfan99** [comment]
遇到同样的问题。另外，IE8下tooltip渲染在最底层，总是被数据图形遮挡。

**Comment by pissang** [comment]
已修复。
