### ISSUE TITLE
请问在react里使用echarts有没有什么例子？

### ISSUE THREAD

**Issue by Flourad** [ecomfe/echarts#2850]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by HuanxinHu** [comment]
网上有很多例子，render() 里把echart container dom 写好， componentDidMount(), 就可以init echart, 和setOption了。

**Comment by Flourad** [comment]
@HuanxinHu 嗯嗯 昨天自己也是按照这种办法试了一下，谢谢你的回答~
