### ISSUE TITLE
在饼图上按弧线移动鼠标时，高亮效果很容易消失

### ISSUE THREAD

**Issue by hzmook** [ecomfe/echarts#2852]
#### 问题简述 (One-line summary)
在饼图上按弧线移动鼠标时，高亮效果很容易消失

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.2
+ 浏览器类型和版本 (Browser version): Chrome 47.0.x
+ 操作系统类型和版本 (OS Version): Windows 10 专业版

#### 重现步骤 (Steps to reproduce)
1.在浏览器中打开官网示例“http://echarts.baidu.com/demo.html#pie-simple”。
2.鼠标移到页面右侧饼图某一色块上，可以看到高亮效果。
3.如果在第2步时，鼠标在最大的那个色块("搜索引擎")沿外边沿移动鼠标(画弧线)，高亮效果很容易消失。

#### 期望结果 (Expected behaviour)
在饼图中同一色块内随意移动鼠标，该色块的高亮效果都不会消失。

#### 可能哪里有问题 (What went wrong)
不清楚

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/480729/13870965/97de3eec-ed1b-11e5-8815-ba3721c9a725.png)

**Comment by pissang** [comment]
不能复现你的问题，可能是因为移到 tooltip 上导致失去焦点了。
