### ISSUE TITLE
echarts3能否响应鼠标滚轮事件

### ISSUE THREAD

**Issue by bzcode** [ecomfe/echarts#2854]
使用 echarts3 在地图上显示内容的时候，希望能够捕捉到用户的滚轮动作，这样在地图放大缩小的时候能够进行响应。

目前好像不支持 onmousewheel 之类的事件。

**Comment by pissang** [comment]
可以使用 myChart.getZr() 获得的 zr 实例监听 mousewheel 事件
```js
myChart.getZr().on('mousewheel', function () {} )
```

**Comment by xiaoDC** [comment]
@pissang 事件响应函数里面，如何拿到 geo 当前的 scale ，为什么拿到的 zoom 不是 `0.9090909090909091` 就是 `1.1`

**Comment by ArrayZheng** [comment]
@xiaoDC 为什么拿到的zoom一直是1.1啊，怎么解决啊

**Comment by ArrayZheng** [comment]
算了，只能通过getOption().geo[0].zoom

**Comment by xiaoDC** [comment]
@ArrayZheng 放大的时候每次拿到的都是 1.1，这个是源码里面写死的，我是求累乘值。

**Comment by nooblyh** [comment]
@pissang bmap上的地图缩放不能响应 georoam 事件，有别的办法吗？

**Comment by songsgroup** [comment]
移动端如何监听缩放事件？

**Comment by songsgroup** [comment]
@pissang 请教一下，移动端如何监听缩放事件？

**Comment by Justpipidog** [comment]
目前我想在实现有dataroom 的折线图中可以通过滚轮的缩放，当放大到某一地步时，就能够触发比如markpoint，显示相关信息；当缩小某一地步时，又能隐藏相关信息。

类比生活中使用地图的行为：
当地图没有放大时，是不能显示某些细节的，只有当放大到某一个地步时，才能显示细节；同时当地图一缩小时，又能隐藏某些细节。

目前 myChart.getZr().on('mousewheel', function () {} ) 只能检测缩放事件，缺不能检测是缩小还是放大，以及放大，缩小的尺度。
