### ISSUE TITLE
echarts theme显示效果的问题

### ISSUE THREAD

**Issue by Flourad** [ecomfe/echarts#2858]
#### echarts theme使用的问题
为啥不把theme内置，用之前还要registerTheme一下呢？另外，我设置了主题之后，地图的颜色还是灰色，只是边界线什么的有了一些变化，没有官网各种主题的map那么好看？

#### 版本及环境 (Version & Environment)
+ echarts@3.1.3 
+ chrome；
+ mac osx；

**Comment by pissang** [comment]
你下载主题文件只要引入不需要 register 啊，不内置是因为主题是大家有需要才会引入，没必要内置增加代码体积

**Comment by Flourad** [comment]
@pissang 我是在 browserify下使用echarts，我看了theme文件的源码，里面根本没有export，所以在我的文件里，也没办法通过require引入呀？我重写了theme下的js文件，export了一下，引入到我的文件里，另外网上有很多人都有这些问题，建议完善一下你们的配置手册什么的~

**Comment by zhump** [comment]
试试 这个呢#2860

**Comment by pissang** [comment]
theme 模块是 UMD 规范，另外 require 后是自注册的，http://echarts.baidu.com/download-theme.html

**Comment by Flourad** [comment]
@pissang 是我弄错了，是有效果的，谢谢您的回答~
