### ISSUE TITLE
3.0官网下载的版本，无法在一个页面显示多个图，init之后的是只有最后一个生效

### ISSUE THREAD

**Issue by xnz0616** [ecomfe/echarts#2861]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by xnz0616** [comment]
在网上下载了别人改了的，可以在一个页面显示多个， 为啥官网的就不行呢？http://download.csdn.net/detail/qq_24435639/8927291#comment

**Comment by jolin9822** [comment]
一个页面可以多个图，只是一个容器里只能有一个图。
