### ISSUE TITLE
图形有多个series，且type不同，如地图，饼图混合，visualMap也控制了饼图，怎么让visualMap只对地图生效？

### ISSUE THREAD

**Issue by zhump** [ecomfe/echarts#2870]
如题。

**Comment by pissang** [comment]
设置 visualMap 的 [seriesIndex](http://echarts.baidu.com/option.html#visualMap-continuous.seriesIndex(number%7CArray.%3Cnumber%3E))

**Comment by zhump** [comment]
好了。。多谢多谢。。
