### ISSUE TITLE
ECharts3的饼状图支持3D效果吗？

### ISSUE THREAD

**Issue by lisgking** [ecomfe/echarts#2871]
#### 问题简述 (One-line summary)
ECharts3的饼状图支持3D效果吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):window

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不支持
