### ISSUE TITLE
下载了最新版，不能解析gexf

### ISSUE THREAD

**Issue by kisskevin** [ecomfe/echarts#2873]
#### 问题简述 (One-line summary)
var graph = echarts.dataTool.gexf.parse(xml); 执行到这句

浏览器报错：
Uncaught TypeError: Cannot read property 'gexf' of undefined

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3 ，3月21日通过主页下载的最新版http://echarts.baidu.com
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
1.下载官方例子及数据文件
2.在tomcat下运行

#### 期望结果 (Expected behaviour)
是不是版本的问题？

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
gexf 扩展需要引入 https://github.com/ecomfe/echarts/blob/master/dist/extension/dataTool.min.js
