### ISSUE TITLE
折线图的设置问题求助！

### ISSUE THREAD

**Issue by luxueyan** [ecomfe/echarts#2876]
#### 问题简述 (One-line summary)
```javascript
{
            name:'邮件营销',
            type:'line',
            //stack: '总量',
            // areaStyle: {normal: {}},
            data:[120, 132, null, 134, null, 230, 210]
        },
```
请问，折线图是否可以实现，虚线连接中间的断点。由于有null值得存在，导致折线不连续.如下图，想实现如图箭头方向的虚线连接。谢谢！

![image](https://cloud.githubusercontent.com/assets/1555552/13918704/ed4efb52-efa3-11e5-893f-1fa5aae8014c.png)

**Comment by luxueyan** [comment]
@pissang 直接关掉啥情况

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/2579

**Comment by luxueyan** [comment]
不好意思文档不熟， 我用markline 可以实现我的需求！ thanks！

**Comment by pissang** [comment]
赞，markLine 也是个思路
