### ISSUE TITLE
散点图地图，选中城市，显示的数据带有坐标的问题

### ISSUE THREAD

**Issue by focushxl** [ecomfe/echarts#2877]
#### 问题简述 (One-line summary)
散点图地图，选中城市，显示的数据带有坐标的问题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.14
+ 浏览器类型和版本 (Browser version):IE11
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.散点图地图中选中城市，显示的数值带有坐标，无法去除

#### 期望结果 (Expected behaviour)
散点图地图中城市显示的数据不带有坐标

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

你们的示例代码就看得到了。。
```

#### 其他信息 (Other comments)

![Uploading image.png…]()

**Comment by hanyaya** [comment]
这里应该显示的是对应的value值，不是坐标。
