### ISSUE TITLE
柱形图标label如何在当前y轴另外一个数据上方

### ISSUE THREAD

**Issue by wangpei123** [ecomfe/echarts#2884]
![1](https://cloud.githubusercontent.com/assets/16145512/13975069/9d2ec338-f0ec-11e5-9996-f2d4800403c2.png)
![2](https://cloud.githubusercontent.com/assets/16145512/13975072/a4b5d768-f0ec-11e5-81ab-a91b14ec8f38.png)
需要做成图1的样式，现在做到图2的样式。**label需要放到本列最上方。**
代码如下：
![3](https://cloud.githubusercontent.com/assets/16145512/13975146/5ee984b8-f0ed-11e5-82f5-6d2eb3385615.png)
![4](https://cloud.githubusercontent.com/assets/16145512/13975149/60e37576-f0ed-11e5-9b03-7987f633edf1.png)

**Comment by pissang** [comment]
显示另外一个系列的 label

**Comment by wangpei123** [comment]
另外一个系列label就是取反的值，比如20%另外一个label就是80%

**Comment by wangpei123** [comment]
可以了，谢谢
