### ISSUE TITLE
grid 配置backgroundColor无法生效

### ISSUE THREAD

**Issue by 947288229** [ecomfe/echarts#2887]
#### 问题简述 (One-line summary)
echarts3最新版   grid 配置backgroundColor无法生效

#### 版本及环境 (Version & Environment)
chrome浏览器 
Windows系统

#### 重现步骤 (Steps to reproduce)
1.访问http://echarts.baidu.com/demo.html#area-rainfall
2.grid里面添加backgroundColor:'#fff'

#### 期望结果 (Expected behaviour)

背景色边成白色

补充：希望markpoint显示的值可以自定义，最好支持html标签。

**Comment by pissang** [comment]
3 里 grid 默认不显示，需要设置成 show: true

**Comment by 947288229** [comment]
thx
