### ISSUE TITLE
undefined is not an object (evaluating 'echarts.dataTool.prepareBoxplotData')

### ISSUE THREAD

**Issue by dishui** [ecomfe/echarts#2890]
#### 问题简述 (One-line summary)

when trying to run the example box plot after download the example, it product the error that undefined is not an object (evaluating 'echarts.dataTool.prepareBoxplotData')
I am using echarts full version 3.1.4

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.4
+ 浏览器类型和版本 (Browser version):safari 9.0.1
+ 操作系统类型和版本 (OS Version): mac osx yosemite

#### 重现步骤 (Steps to reproduce)
1.download the example box plot from http://echarts.baidu.com/gallery/editor.html?c=boxplot-multi&edit=1&reset=1
2. either run as it is or change the echarts script to :  <script src="node_modules/echarts/dist/echarts.js"></script>

#### 期望结果 (Expected behaviour)

see the box plot render as per gallery example

#### 可能哪里有问题 (What went wrong)

???

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
You need to include https://github.com/ecomfe/echarts/blob/master/dist/extension/dataTool.min.js to use dataTool

**Comment by dishui** [comment]
Thanks.

**Comment by quentinchen** [comment]
@pissang  @dishui  引入dataTool还是不管用啊
