### ISSUE TITLE
还是toolbox的颜色设置问题，这次是MagicType

### ISSUE THREAD

**Issue by r4nqian** [ecomfe/echarts#2893]
我很奇怪，明明2中的toolbox设定很好，无论是图标样式还是颜色都很好，为什么要改成3这样的，而且还不允许使用多个颜色。

虽然发现了iconStyle可以设置颜色，其余的tool都还好设置，但是MagicType该怎么设置？
假如我有line和bar，我想颜色交替出现，该怎么设置呢？iconStyle只能给MagicType设置统一的颜色啊。。。。

2中toolbox.color=['#1e90ff','#22bb22','#4b0082','#d2691e'] 工具箱icon颜色序列，循环使用，同时支持在具体feature内指定color 
3中toolbox.iconStyle.normal.color自适应是什么鬼，给它一个颜色组，全部变黑色

help me

**Comment by pissang** [comment]
相同颜色是为了突出选中项的不同颜色

**Comment by manmanwu18** [comment]
我也遇到了，不应该区分选中和不选中的颜色吗

**Comment by manmanwu18** [comment]
请问怎么解决
