### ISSUE TITLE
关于原2.x中 和弦图 在3.x中的使用问题

### ISSUE THREAD

**Issue by R-River** [ecomfe/echarts#2894]
#### 问题简述 (One-line summary)
请问是不是目前3.x中还没有和弦图？在graph相关配置项中没有找到合适的内容

主要是看中了其鼠标移动在node上时突出与之有关系的node和link的特效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 期望结果 (Expected behaviour)

可达到鼠标移动在node上时突出与之有关系的node和link的特效

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

希望的是像下图展示的这种效果 谢谢！

![1](https://cloud.githubusercontent.com/assets/14121399/14008720/6852dde2-f1bf-11e5-9781-0d522c0d1842.gif)

**Comment by pissang** [comment]
暂时不支持

**Comment by HedyHan** [comment]
@pissang 希望迅速支持

**Comment by chengang0621** [comment]
@pissang 问一下这个和弦图在echarts3里面以后会有支持吗

**Comment by zhangqunshi** [comment]
请问根据3.x现有的和弦图可以改造成2.x的和弦图么（上面那种）？
