### ISSUE TITLE
控制台一直报错，type或getAxis不存在

### ISSUE THREAD

**Issue by brucecham** [ecomfe/echarts#2896]
![o1qzdpwa 7llu vxumd jo](https://cloud.githubusercontent.com/assets/7899194/14011882/f70b9336-f1dc-11e5-8d4c-ca466808edd4.png)
![官网例子都在报错，需要加强自测](http://echarts.baidu.com/demo.html#grid-multiple )

**Comment by pissang** [comment]
chrome canary 的bug，同 #2682 (comment)
