### ISSUE TITLE
标签覆盖图表

### ISSUE THREAD

**Issue by CptJason** [ecomfe/echarts#2909]
#### 标签覆盖图表
![image](https://cloud.githubusercontent.com/assets/397285/14059127/c2da7edc-f372-11e5-843d-689b493514d8.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts 3):
+ 浏览器类型和版本 (chrome 版本 49.0.2623.87 (64-bit)):
+ 操作系统类型和版本 (OS X 10.11.3 (15D21)):

#### 期望结果 (Expected behaviour)
标签不覆盖图表

#### 可能哪里有问题 (What went wrong)
是不是bug，还是其它问题？

**Comment by pissang** [comment]
不是bug，只是你的标签太多了，可以增加画布高度或者自己在外面用 html 写一个类似 legend 的组件
