### ISSUE TITLE
[3.1.4]饼图标签排布奇怪，引导线过长

### ISSUE THREAD

**Issue by horans** [ecomfe/echarts#2910]
#### 问题简述 (One-line summary)
从 3.1.3 升级至 3.1.4 后，饼图右边的标签挤到了一起，并且引导线不受设定控制，移动版甚至顶出了容器。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.14
+ 浏览器类型和版本 (Browser version):chrome 51
+ 操作系统类型和版本 (OS Version): win 7 x64

#### 重现步骤 (Steps to reproduce)
3.1.4 桌面
![echart-314-01](https://cloud.githubusercontent.com/assets/12060804/14059368/a0bdc154-f379-11e5-9fce-47eba1e6844a.png)

3.1.4 手机
![echart-314-02](https://cloud.githubusercontent.com/assets/12060804/14059369/a4cdae3a-f379-11e5-84ae-0322caa24bfb.png)

#### 期望结果 (Expected behaviour)
3.1.3 桌面
![echart-313-01](https://cloud.githubusercontent.com/assets/12060804/14059371/a8b52406-f379-11e5-8e8a-58603629d5d4.png)

3.1.3 手机
![echart-313-02](https://cloud.githubusercontent.com/assets/12060804/14059372/abba4cb2-f379-11e5-9316-2de43be6adff.png)

#### 可能哪里有问题 (What went wrong)
看了下版本更新，可能与 [commit 36c2b14](https://github.com/ecomfe/echarts/commit/36c2b141a0976a122c12d956cd1866bb2001a8c1) 有关。

#### ECharts配置项 (ECharts option)
桌面：

    optionMain.series[0].labelLine.normal.length = 20;
    optionMain.series[0].labelLine.normal.length2 = 20;

手机：

    optionMain.series[0].labelLine.normal.length = 3;
    optionMain.series[0].labelLine.normal.length2 = 2;

**Comment by pissang** [comment]
avoidLabelOverlap: false 试试
