### ISSUE TITLE
x轴设置areaStyle的color与grid设置的backgroundColor ，颜色差异很大

### ISSUE THREAD

**Issue by 947288229** [ecomfe/echarts#2912]
![image](https://cloud.githubusercontent.com/assets/4187351/14074846/b3cabd90-f506-11e5-8305-9603fd1073e4.png)

**Comment by pissang** [comment]
因为半透明的颜色会叠加

**Comment by 947288229** [comment]
![image](https://cloud.githubusercontent.com/assets/4187351/14075043/66a53692-f508-11e5-953f-07750a6cf3fe.png)
可以具体说明一下怎么叠加吗？ 我把grid颜色去掉了。看起来还是差别很大

**Comment by 947288229** [comment]
splitArea: {
            show:true,
            areaStyle: {color:['rgba(0,164,251,0.46)','rgba(0,164,251,0.25)']}
        }

**Comment by 947288229** [comment]
原来areaStyle的color值为空 会显示黑色
