### ISSUE TITLE
官方可否出TS版本

### ISSUE THREAD

**Issue by bobstar** [ecomfe/echarts#2918]

**Comment by txf7337** [comment]
顶顶顶

**Comment by txf7337** [comment]
chartjs和zingchart和d3都已经支持了
再不支持，想说爱你不容易啊

**Comment by pissang** [comment]
TypeScript 是 JavaScript 的超集，有啥不能用的呢？

**Comment by bobstar** [comment]
我的意思是官方不断的更新版本，能否随带释出 对应的d.ts 文件，这样就可以直接引入了。
不是说超集就能随便直接用，有那么简单就好了。






在 2016-03-30 12:19:05，"Yi Shen" <notifications@github.com> 写道：


TypeScript 是 JavaScript 的超集，有啥不能用的呢？

**Comment by pissang** [comment]
d.ts 只是一个描述文件为了方便智能提示和类型检查的，并不影响使用

**Comment by wesinfo** [comment]
angular2使用Systemjs包加载工具时候不能导入echarts

**Comment by hugcoday** [comment]
有什么办法，先用起来吗？

**Comment by nostubborn** [comment]
请问楼主知道怎么在angular2中引入echart吗？我现在还不知道怎么导入进来

**Comment by echoulen** [comment]
非常期待官方釋出`.d.ts`檔案

**Comment by lqm229026** [comment]
我的做法是这样的：
1. npm install echarts
2. 在需要使用的component中编写如下代码：
```
<div id='my-chart'></div>
```

```
import * as echarts from 'echarts';
const chart = echarts.init(document.getElementById('my-chart');
const option = {
  ...
}
chart.setOption(option);
```

**Comment by Galllas** [comment]
import * as echarts from 'echarts';
const chart = echarts.init(document.getElementById('my-chart');
const option = {
  ...
}
chart.setOption(option);

请问这段写在TS文件还是HTML文件里

**Comment by chfw** [comment]
TS

**Comment by ChenArno** [comment]
主题js文件是怎么引入的
