### ISSUE TITLE
字符云显示数据不准确。

### ISSUE THREAD

**Issue by xb9207** [ecomfe/echarts#2921]
#### 问题简述 (One-line summary)
字符云显示数据不准确。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.0
+ 浏览器类型和版本 (Browser version):Chrome
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
1.字符云显示数据不准确。

#### 可能哪里有问题 (What went wrong)
可能是由于数据过多导致间距太小。

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/2694#issuecomment-203394634
