### ISSUE TITLE
官网实例速度实在太慢

### ISSUE THREAD

**Issue by cnicy** [ecomfe/echarts#2927]
#### 问题简述 (One-line summary)

http://echarts.baidu.com/examples.html
官网实例速度实在太慢了，半天打不开！
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.打开谷歌浏览器
2.访问http://echarts.baidu.com/examples.html 选择实例栏目，发现里边的实例根本打不开啊，不是网速的原因！！
#### 期望结果 (Expected behaviour)

能不能把demo放到文件下载包里边，提供下载！
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by 100pah** [comment]
1. 可否详细说一下，如何判断出不是 `网速的原因` ？
2. 能否看看chrome控制台里有没有报错？
3. 能否看看chrome控制台中 `Network` 中，是否有哪些资源长时间获取不到？

![Network](https://cloud.githubusercontent.com/assets/1956569/14172568/3d0439cc-f76b-11e5-9cfa-408724d814dc.jpg)
