### ISSUE TITLE
当重设数据的数据，legend data 不能改变？？

### ISSUE THREAD

**Issue by JaneyWu** [ecomfe/echarts#2930]
#### 问题简述 (One-line summary)
ajax从后来获取新的数据，展示的时候，数据会发生变化，希望在legend data 里展示数量，所以每次legend data 都是变化的，然而重新setOption的时候，legend消失了

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): V3.1.5
+ 浏览器类型和版本 (Browser version):chrome 版本 49.0.2623.87 (64-bit)
+ 操作系统类型和版本 (OS Version):MAC

#### 重现步骤 (Steps to reproduce)
1. 首先设置legend:{
                        data:['aa(123)',  'bb(100)' ]
                    },
   然后setOption，
   legend显示
2.再次设置legend:{
                        data:['aa(143)',  'bb(160)' ]
                    },
   然后setOption，
   legend不显示

#### 期望结果 (Expected behaviour)

重新设置legend， 也显示

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
legend 的名称有跟 series name 对应么？

**Comment by JaneyWu** [comment]
是对应的，

**Comment by JaneyWu** [comment]
每次setOption的时候，legend的data 和 series的name 都是一一对应的

**Comment by gitspadark** [comment]
楼主，这个问题你后面解决了吗？我也遇到了

**Comment by pissang** [comment]
能否给出 option 方便我们复现

**Comment by gitspadark** [comment]
var option = {
        title: {
            text: 'test'
        },
        tooltip: {},
        legend: {
            data: []
        },
        xAxis: {
            type:'value'
        },
        yAxis: {},
        series: [{
            name: '',
            type: 'line',
            data: []
        }]
    };
chart.setOption(option);
然后再在与后台交互异步函数里，根据获取的数据赋新值
var option = energyChart.getOption();
option.legend.data = 赋新数据数组;  但是option.series 赋值后确实可以的

**Comment by gitspadark** [comment]
@pissang 您好，你是echarts的开发人员，对于这个问题能告诉我怎么解决吗。谢谢

**Comment by pissang** [comment]
麻烦给我下我这能复现的 option

**Comment by gitspadark** [comment]
你好，我上面贴出来得代码，你在本地不能复制吗？

**Comment by pissang** [comment]
你贴的这个什么都没有我复制后怎么运行？

**Comment by gitdust** [comment]
关注
