### ISSUE TITLE
堆叠图tooltip默认排序错误

### ISSUE THREAD

**Issue by huanlwd** [ecomfe/echarts#2931]
#### 问题简述 (One-line summary)

堆叠图tooltip默认排序和y轴的排序是相反的

#### 版本及环境 (Version & Environment)
+ 3.1.5 (ECharts version):
+Chrome (Browser version):
+ (Windows 10 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.创建好堆叠图，启用tooltip
2.鼠标移上去自己看，tooltip内的排序和堆叠图刚好相反

#### 期望结果 (Expected behaviour)

应该一致

**Comment by pissang** [comment]
可以根据自己需要通过 formatter 修改 tooltip 的显示
