### ISSUE TITLE
配置是直接引入echarts.min.js吗？还需要引入其他js吗？

### ISSUE THREAD

**Issue by Sunweal** [ecomfe/echarts#2933]
#### 问题简述 (One-line summary)
配置是直接引入echarts.min.js吗？还需要引入其他js吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by Sunweal** [comment]
多次点击，会遗失掉属性

**Comment by pissang** [comment]
？

**Comment by Sunweal** [comment]
echars3.0 多次点击查看单个line，会直接出现属性异常
