### ISSUE TITLE
加载data.json的例子中，json文件内容是什么？

### ISSUE THREAD

**Issue by qtbhappy** [ecomfe/echarts#2937]
#### 问题简述 (One-line summary)
在[加载json文件的例子中](http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0)，你们没有给出data.json文件的格式，无法测试。请给出data.json文件的内容，好让用户测试。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by bingwork** [comment]
同求~
