### ISSUE TITLE
echarts legend 可否加入鼠标移入事件，在该legend上弹入一个层，显示改legend的全长度内容

### ISSUE THREAD

**Issue by ready360go** [ecomfe/echarts#2942]
#### 问题简述 (One-line summary)

![image](https://cloud.githubusercontent.com/assets/16661632/14273710/2872d8f6-fb3f-11e5-89d4-6d81b1df42a8.png)

如图；现有这样一个问题，：
legend 的data值过长  会导致两列legend间距过大，从而覆盖到图形中，
有没有方法可以绑定鼠标移入事件。先将legend的data处理到合适长度后显示，将鼠标移入后弹出一个层显示data的全长度内容？

谢谢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
legend 移入有 highlight 事件
