### ISSUE TITLE
Option to make axisLabel clickable

### ISSUE THREAD

**Issue by fmal** [ecomfe/echarts#2943]
#### 问题简述 (One-line summary)
In echarts 2 there was an option to make axisLabels clickable. This option seems to be gone in version 3. 

#### 版本及环境 (Version & Environment) 
+ ECharts 版本 (ECharts version): 3.1.3
+ 浏览器类型和版本 (Browser version): Google Chrome 49.0.2623.110
+ 操作系统类型和版本 (OS Version): Windows 8

#### 期望结果 (Expected behaviour)

It would be great if `xAxis: [{
  axisLabel: {
     clickable: true
  }
}]` made the label clickable (as in version 2), so that I could capture clicks using `chart.on('click')`.

#### 可能哪里有问题 (What went wrong)

Unfortunately `xAxis: [{
  axisLabel: {
     clickable: true
  }
}]` has no effect in version 3 of the library.

**Comment by fmal** [comment]
Sorry for pushing the issue, but is there any plan for bringing back this feature? It is pretty critical to my use case. I would have reverted to version 2, but then I would miss a lot of good stuff in the latest echarts. Thanks!

**Comment by pissang** [comment]
Sorry for loosing this feature in the new ECharts 3. We will add it back in 3.1.7, which will be released in the next week.

**Comment by fmal** [comment]
Awesome news. Thank you @pissang!

**Comment by pissang** [comment]
Hi @fmal , axisLabel has been added in commit https://github.com/ecomfe/echarts/commit/a6f51b166d63987aa1148cd22af38f5d933c4c75

The usage is changed. `axisLabel.clickable` is replaced with `xAxis.silent` and the params of event is a bit different.

For example

```js
option: {
  xAxis: {
    silent: true
  }
}
...
chart.on('click', function (params) {
  // Make sure event from target axis
  if (params.componentType === 'xAxis' && params.xAxisIndex === 0) {
    // params.value is the axis label before formatted
    console.log(params.value);
  } 
});
```

**Comment by tmtron** [comment]
In version 4.1.0  I had to set [triggerEvent](https://ecomfe.github.io/echarts-doc/public/en/option.html#xAxis.triggerEvent) = true

**Comment by rotigithub** [comment]
Hi,
How to make clickable axisLabel?
With the solutions above if I click a "bar" in my bar chart it's working perfectly but when I click on the label it's doing nothing.

**Comment by beipiaoyu2011** [comment]
> In version 4.1.0 I had to set [triggerEvent](https://ecomfe.github.io/echarts-doc/public/en/option.html#xAxis.triggerEvent) = true

right,  version 4, need to set triggerEvent = true
