### ISSUE TITLE
lineStyle 设置emphasis的样式并不生效

### ISSUE THREAD

**Issue by luxueyan** [ecomfe/echarts#2948]
#### 问题简述 (One-line summary)

设置了折线图的lineStyle 结果emphasis样式并不生效，
```javascript
          lineStyle:{
                normal:{
                    width:1
                },
                emphasis: {
                    width:2,
                    shadowColor: 'rgba(0, 0, 0, 0.5)',
                    shadowBlur: 10,
                    color: 'red'
                }
            },
```

**Comment by pissang** [comment]
折线图无 emphasis 样式

**Comment by luxueyan** [comment]
@pissang  文档上面有这个配置啊，感觉也挺需要的

**Comment by pissang** [comment]
抱歉文档上有误，有高亮效果会让人误导这个是有 tooltip 的，实际上折线图上只有拐点有 tooltip

**Comment by luxueyan** [comment]
其实这个功能是不是挺需要的 我就是想移动到legend上的时候 突出这条线，可是现在只是点变大了，有点不明显

**Comment by pissang** [comment]
谢谢反馈，代码中已补上，文档上有问题的还请多多指出

**Comment by imust98** [comment]
我就是想移动到legend上的时候 突出这条线 这个功能是挺需要的

**Comment by imust98** [comment]
@pissang   如果更进一步的话，移动到legend附近的时候 就突出这条线  ，因为有好几条线叠在一起的时候 有这个功能 体验会更好一点

**Comment by nachao** [comment]
@pissang 期望加上lineStyle的emphasis。

**Comment by LanceXuGood** [comment]
@pissang 期望加上lineStyle的emphasis。

**Comment by zzhp** [comment]
@pissang 期望加上lineStyle的emphasis。

**Comment by zzhp** [comment]
自己写了个函数使得点击可以出现高亮样式 需要联系Q1147893434
