### ISSUE TITLE
配置参数的legend: data中, 如果有数字则无法显示

### ISSUE THREAD

**Issue by Vivomo** [ecomfe/echarts#2970]
#### 问题简述 (One-line summary)
配置参数的legend: data中, 如果有数字则无法显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): chrome49
+ 操作系统类型和版本 (OS Version): window7

#### 重现步骤 (Steps to reproduce)
1. option.legend.data[0] = '总数100' //字符串包含任意数字

#### ECharts配置项 (ECharts option)

```javascript
option = {
    title: {
        text: 'ECharts 入门示例'
    },
    tooltip: {},
    legend: {
        data:['销量10']
    },
    xAxis: {
        data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
    },
    yAxis: {},
    series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
    }]
};
```

#### 其他信息 (Other comments)

http://echarts.baidu.com/gallery/editor.html?c=doc-example/getting-started

**Comment by pissang** [comment]
legend.data必须要跟series.name一一对应

**Comment by Vivomo** [comment]
谢谢
