### ISSUE TITLE
echarts3在数据为空时的表现形式能否像旧版本一样设置为一堆气泡图？

### ISSUE THREAD

**Issue by QiXiaoyin** [ecomfe/echarts#2979]
问题简述 (One-line summary)
我一开始用的是旧版本的echarts，当获取不到数据时在显示图表的地方显示了一堆气泡，现在更换了了echarts后发现获取不到时图表显示了一个没有数据的坐标轴，请问能否将其修改为一堆气泡？
代码我就不贴了，因为我在网上的echarts的折线实例中也尝试过

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win7 64

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
3 不支持无数据显示气泡， 可以根据自己需求显示无数据的提示
