### ISSUE TITLE
bootstrap tab多个页签中绘图，tab切换，图总聚在一起，必须resize()才行

### ISSUE THREAD

**Issue by bi-kai** [ecomfe/echarts#2980]
#### 问题简述 (One-line summary)
bootstrap tab多个页签中绘图，tab切换，图总聚在一起，必须resize()才行，不美观，易用性也不好，该如何规避？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.2.7
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.bootstrap tab多个页签中绘图，切换页签。
2.图就聚在左侧，必须手动resize页面，能看到整个过程，不美观。

#### 期望结果 (Expected behaviour)
区域显示出来时，图能完整平铺。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
保证第一次 setOption 的时候大小是正确的

**Comment by bi-kai** [comment]
@pissang 是不是初始化echarts对象的时候，对应的div就要是可见的？
我测试，初始化时隐藏，setoptions前已经显示div，但是画图还是聚在一起的。

**Comment by pissang** [comment]
是的，必须要能够获取到 clientWidth, clientHeight，如果不是的话切换成可见的时候再 resize 一下
