### ISSUE TITLE
echarts 3.0 不显示县市级地图

### ISSUE THREAD

**Issue by 17khba** [ecomfe/echarts#2982]
#### 问题简述 (One-line summary)
echarts 3.0 不显示县市级地图

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): echarts3.0
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
<script src="http://echarts.baidu.com/build/dist/echarts-all.js"></script>
<script src="http://echarts.baidu.com/asset/map/js/province/hubei.js"></script>
<script>
    var myChart = echarts.init(document.getElementById('main'));
    var option = {
        title: {
            text : '武汉地图',
            subtext : '-。-'
        },
        tooltip : {
            trigger: 'item',
            formatter: function(a){
                return a[2];
            }
        },
        legend: {
            orient: 'vertical',
            x:'right',
            data:['数据名称']
        },
        dataRange: {
            min: 0,
            max: 1000,
            color:['orange','yellow'],
            text:['高','低'],           // 文本，默认为数值文本
            calculable : true
        },
        series : [
            {
                name: '数据名称',
                type: 'map',
                mapType: '湖北|武汉市',
                
                itemStyle:{
                    normal:{label:{show:true}},
                    emphasis:{label:{show:true}}
                },
                data:[
                    {name: '武昌区',value: Math.round(Math.random()*1000)},
                    {name: '洪山区',value: Math.round(Math.random()*1000)},
                    {name: '东西湖区',value: Math.round(Math.random()*1000)}
                ]
            }
        ]
    };
	myChart.on('click',function(obj){
		alert(obj.value);
	});
    myChart.setOption(option);
                     
</script>
只显示武汉地图，不显示下面的区县地图

#### ECharts配置项 (ECharts option)

```javascript
var option = {
        title: {
            text : '武汉地图',
            subtext : '-。-'
        },
        tooltip : {
            trigger: 'item',
            formatter: function(a){
                return a[2];
            }
        },
        legend: {
            orient: 'vertical',
            x:'right',
            data:['数据名称']
        },
        dataRange: {
            min: 0,
            max: 1000,
            color:['orange','yellow'],
            text:['高','低'],           // 文本，默认为数值文本
            calculable : true
        },
        series : [
            {
                name: '数据名称',
                type: 'map',
                mapType: '湖北|武汉市',
                
                itemStyle:{
                    normal:{label:{show:true}},
                    emphasis:{label:{show:true}}
                },
                data:[
                    {name: '武昌区',value: Math.round(Math.random()*1000)},
                    {name: '洪山区',value: Math.round(Math.random()*1000)},
                    {name: '东西湖区',value: Math.round(Math.random()*1000)}
                ]
            }
        ]
    };
	myChart.on('click',function(obj){
		alert(obj.value);
	});

```

**Comment by pissang** [comment]
http://ecomfe.github.io/echarts-map-tool/
