### ISSUE TITLE
Legend text is not correctly aligned with icon (solution)

### ISSUE THREAD

**Issue by JeffreyRoosendaal** [ecomfe/echarts#2983]
I noticed that the text align in the legend is not correct. It happens with every symbol type. See screenshots below.

![wrong-circle](https://cloud.githubusercontent.com/assets/6398059/14466427/1627521a-00d7-11e6-96dd-923f29ebce50.PNG)

![wrong-square](https://cloud.githubusercontent.com/assets/6398059/14466434/1c097398-00d7-11e6-8601-b07b24d0ec24.PNG)

This happens both on your website (http://echarts.baidu.com/demo.html#area-stack) as well as on my website.

-----

I've updated `line 41766` in echarts.js (3.1.6, not minimized) to:

`y: (itemHeight / 2) - 6` (I've added the `- 6` as a correction).

Now, they're perfectly aligned:

![correct-circle](https://cloud.githubusercontent.com/assets/6398059/14466533/8a11dec0-00d7-11e6-84f3-f2d86db106c0.PNG)

![correct-square](https://cloud.githubusercontent.com/assets/6398059/14466536/8c39ada4-00d7-11e6-8986-fb4a85ef71a6.PNG)

---

Greetings from an international user!

**Comment by pissang** [comment]
Hi Jeffrey, can you give us the fontFamily in your case. We noticed that it has the same problem when using Microsoft Yahei.

**Comment by JeffreyRoosendaal** [comment]
I'm using [Open Sans](https://www.google.com/fonts#UsePlace:use/Collection:Open+Sans) through Google Fonts.

Maybe the best solution here would be to add a `legend.textStyle.lineHeight` option. So people can adjust the vertical text alignment for other/custom fonts too.

**Comment by pissang** [comment]
It seems helpful. Considering adding it in the next release

**Comment by pissang** [comment]
Vertical align has been fixed in https://github.com/ecomfe/zrender/commit/65097a12fb43cd00a4567e946e584a3ab5219dcd. Tried Open Sans and it seems problem not exists anymore.

**Comment by Turing97** [comment]
> 5.2.1 存在同样问题，并且使用legend.textStyle. padding 控制不起作用 legend: { icon: "rect", itemWidth: 12, itemHeight: 12,
> 
> }
> 
> ![image](https://user-images.githubusercontent.com/18638401/139356997-0ebf006c-4c61-48d6-b303-298240b48806.png)

版本5.2.2 我也遇到了，用svg渲染就正常了，奇怪

**Comment by Raphyyy** [comment]
![image](https://user-images.githubusercontent.com/13983107/150857047-9d5e9268-47b5-43c0-aa1a-79e55929c42d.png)

I can't find a way to correctly align the legend text with Roboto font (Echarts 5.2.2 used)

**Comment by francisco-polaco** [comment]
> ![image](https://user-images.githubusercontent.com/13983107/150857047-9d5e9268-47b5-43c0-aa1a-79e55929c42d.png)
> 
> I can't find a way to correctly align the legend text with Roboto font (Echarts 5.2.2 used) Setting `legend.textStyle.lineHeight` doesn't change a thing

Hey there!
Did you find a way to workaround this?

**Comment by Raphyyy** [comment]
Hey! unfortunately no I am still having this issue.

**Comment by nguyenvu9405** [comment]
I am still having the issue. I'm using v5.4.2.

**Comment by shenxiang216** [comment]
我仍然遇到此问题。我使用的是 v5.5.0

**Comment by e-projectsrl** [comment]
I am also having this issue.

I've tried changing the `textStyle.lineHeight` and `textStyle.padding` properties but they seem to have no effect at all. Am I missing something?

EDIT: I've managed to solve this by using the "rich" text feature in the legend, and applying a padding to the rich text definition. This seems to work, where applying padding directly on textStyle doesn't for some reason.

**Comment by malekpour-mreza** [comment]
> I am also having this issue.
> 
> I've tried changing the `textStyle.lineHeight` and `textStyle.padding` properties but they seem to have no effect at all. Am I missing something?
> 
> EDIT: I've managed to solve this by using the "rich" text feature in the legend, and applying a padding to the rich text definition. This seems to work, where applying padding directly on textStyle doesn't for some reason.

Adding padding through `rich` feature works for me as well. I guess the padding not being applied through usual `textStyle.padding` can be labeled as a bug. @pissang
