### ISSUE TITLE
this.dom.getContext is not a function

### ISSUE THREAD

**Issue by t051506** [ecomfe/echarts#2984]
echarts 版本 3.1.6 引入 echarts.min.js.
当调用echarts.init($("#lineDiv"))时报错 this.dom.getContext is not a function  第24行

<script>
 var ssArr = $(".info-tr").children("ul");
		//横轴的数据
		var data1Arr = new Array();
		//压差的数据
		var data2Arr = new Array();
		for (var int = 0; int < ssArr.length; int++) {
			var data1 = ssArr.eq(int).children().eq(0).html();
			var data2 = ssArr.eq(int).children().eq(6).html();
			data1Arr.push(data1);
			data2Arr.push(data2);
		}
	    var myChart = echarts.init($("#lineDiv"));
	    option = {
	    	    tooltip: {
	    	        trigger: 'item'
	    	    },
	    	    legend: {
	    	        data:['压差']
	    	    },
	    	    toolbox: {
	    	        show: true,
	    	        feature: {
	    	            dataZoom: {},
	    	            dataView: {readOnly: false},
	    	            magicType: {type: ['line']},
	    	            restore: {},
	    	            saveAsImage: {}
	    	        }
	    	    },
	    	    xAxis:  {
	    	        type: 'category',
	    	        boundaryGap: false,
	    	        data: data1Arr
	    	    },
	    	    yAxis: {
	    	        type: 'value',
	    	        axisLabel: {
	    	            formatter: '{value} Mpa'
	    	        }
	    	    },
	    	    series: [ {
	    	            name:'压差',
	    	            type:'line',
	    	            data:data2Arr
	    	        }
	    	    ]
	    	};
	    myChart.setOption(option);

</script>

**Comment by pissang** [comment]
$("#lineDiv")[0]
