### ISSUE TITLE
echarts折线图，数据量比较大时(40001条)，在3.0上比2.0的版本渲染速度慢很多，页面卡顿，图形显示有问题

### ISSUE THREAD

**Issue by flyingQuQu** [ecomfe/echarts#2985]
#### 问题简述 (One-line summary)
echarts折线图，数据量比较大时(40001条)，在3.0上比2.0的版本渲染速度慢很多，页面卡顿，图形显示有问题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.6    2.2.7
+ 浏览器类型和版本 (Browser version): Chrome 49.0.2623.112 m
+ 操作系统类型和版本 (OS Version): Windows 10 企业版 64位
+CPU: Intel(R) Core(TM) i7-4790K CPU @4.00GHz 4.00GHz
+内存: 16GB RAM

#### 重现步骤 (Steps to reproduce)
1. 2.2.7版本，波形图显示正常
2. 3.1.6版本，波形图渲染很慢，显示异常

#### 期望结果 (Expected behaviour)
![image](https://cloud.githubusercontent.com/assets/12640805/14485566/68ee3172-018a-11e6-8ba2-955cb282951b.png)

#### ECharts配置项 (ECharts option)
-->
```javascript
option = {
    "title": { "text": "i1变化趋势" },
    "tooltip": { "trigger": "axis" },
    "legend": { "data": ["i1"] },
    "toolbox": {
        "show": false,
        "feature": {
            "mark": {
                "show": true
            },
            "dataView": { "show": true, "readOnly": false },
            "magicType": { "show": true, "type": ["line", "bar"] },
            "restore": { "show": true },
            "saveAsImage": { "show": true }
        }
    },
    "calculable": true,
    "xAxis": [{
        "type": "category",
        "boundaryGap": false,
        "data": [40001条数据]
    }],
    "yAxis": [{ "type": "value", "axisLabel": { "formatter": "{value} V" } }],
    "series": [{
        "name": "i1",
        "type": "line",
        "data": [40001条数据]
    }]
}
```

#### 其他信息 (Other comments)
3.0效果图
![image](https://cloud.githubusercontent.com/assets/12640805/14485545/563367f0-018a-11e6-8397-fccd55c61ce5.png)

2.0效果图
![image](https://cloud.githubusercontent.com/assets/12640805/14485558/60da4368-018a-11e6-8aa4-fe7411af85be.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.sampling

**Comment by flyingQuQu** [comment]
设置sampling，确实解决了问题，但是每一个的显示效果怎么都没有2.0的好，而且x轴的起点不是从0开始计算了，这个要怎么解决呢？

average
![image](https://cloud.githubusercontent.com/assets/12640805/14486069/9a0484b6-018d-11e6-8bda-a830ef38935b.png)


max
![image](https://cloud.githubusercontent.com/assets/12640805/14486028/677894f6-018d-11e6-835f-f64d69da05c5.png)

min
![image](https://cloud.githubusercontent.com/assets/12640805/14486049/7bfc131c-018d-11e6-9ee0-afbb2f643bc7.png)

sum
![image](https://cloud.githubusercontent.com/assets/12640805/14486057/8a315c3a-018d-11e6-8900-334fb9ee85f8.png)

**Comment by flyingQuQu** [comment]
@pissang 问题还未解决啊

**Comment by pissang** [comment]
2 里是取最近的值，你可以自定义 sampling 为函数：
```js
sampling: function (frame) {
    return frame[0];
}
```

**Comment by flyingQuQu** [comment]
@pissang 
那横坐标不是从0开始的问题怎么弄？

**Comment by pissang** [comment]
0 是数组 index，跟横坐标没关系

**Comment by flyingQuQu** [comment]
@pissang 
横坐标数组中第一个值option.xAxis[0].data[0]为下图数据
![image](https://cloud.githubusercontent.com/assets/12640805/14487207/e552f4ec-0193-11e6-971e-6fd5fc2b3a03.png)
那么横坐标的第一个刻度为什么不是0，而是
![image](https://cloud.githubusercontent.com/assets/12640805/14487549/bed282a4-0195-11e6-8f41-0012fa96a47c.png)
