### ISSUE TITLE
EChart3文档关于option中的标题或坐标轴文本的“fontFamily”的默认值“sans-serief”是不是有拼写错误？

### ISSUE THREAD

**Issue by hzmook** [ecomfe/echarts#2986]
#### 问题简述 (One-line summary)
EChart3文档关于option中的标题或坐标轴文本的“fontFamily”的默认值为“sans-serief”，是不是有拼写错误？
是不是指“sans-serif”？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/480729/14486890/10a4a160-0192-11e6-93a0-055701e62891.png)

**Comment by pissang** [comment]
谢谢反馈，是的
