### ISSUE TITLE
关于Group旋转的问题

### ISSUE THREAD

**Issue by ytwangw** [ecomfe/echarts#2990]
关于旋转单个Shape的旋转我通过rotation经实现，但是如果我将多个shape组合成一个Group，需要对这个Group进行旋转的时候，有两种情况：
1、孩子Shape不存在自身矩阵变换的情况下，可以通过设置Group的rotation实现旋转。
2、孩子Shape存在自身的矩阵变换的情况下，我就实现不了，我试着通过使用Matrix的rotate和translate来实现，但没能最终实现。
麻烦您给我个思路，谢谢。
@pissang

**Comment by pissang** [comment]
儿子节点的变换是在父节点变换的基础上的

**Comment by ytwangw** [comment]
这个我知道 可是当我同时设置了group与儿子的rotation的时候，并没有实现预期的效果
