### ISSUE TITLE
line图。都越界了。跑出了grid的范围。跟legend混到一块儿了。

### ISSUE THREAD

**Issue by helloweenpad** [ecomfe/echarts#2991]
#### 问题简述 (One-line summary)

line图。都越界了。跑出了grid的范围。

做了个demo页面。
http://crm.mrcrm.com/mrcrm/echarts/bad.html

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.0
+ 浏览器类型和版本 (Browser version): chrome最新版
+ 操作系统类型和版本 (OS Version): win 7

#### 重现步骤 (Steps to reproduce)
1. http://crm.mrcrm.com/mrcrm/echarts/bad.html
2. http://crm.mrcrm.com/mrcrm/echarts/bad.html

#### 可能哪里有问题 (What went wrong)

判断y轴的最大值有问题。你们只取了第一个data set的最大值，实际上第二个data set的最大值要超过y轴最大值，所以line就越界了。
你们的demo正常，是因为刚刚第一个data set的值都大于其他data set的值。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

http://crm.mrcrm.com/mrcrm/echarts/bad.html
http://crm.mrcrm.com/mrcrm/echarts/bad.html
http://crm.mrcrm.com/mrcrm/echarts/bad.html
http://crm.mrcrm.com/mrcrm/echarts/bad.html

```

#### 其他信息 (Other comments)

http://crm.mrcrm.com/mrcrm/echarts/bad.html

**Comment by pissang** [comment]
这个问题主要是因为你对 0 数据用了 log 轴

**Comment by helloweenpad** [comment]
@pissang 那应该用什么？ 不好意思，我新手

**Comment by pissang** [comment]
type: 'value'

**Comment by helloweenpad** [comment]
@pissang 查到了，多谢。现在好多了。时间轴还是很挤，有办法么？ 试过“time”，不好使。

http://crm.mrcrm.com/mrcrm/echarts/bad.html

可以取消"mem/used", "mem/total"看其他线。这两列值太大了。

**Comment by pissang** [comment]
设置 axisLabel.interval
