### ISSUE TITLE
echarts3中graph关系图series[i]-graph.data[i]中的x,y怎么定义，API中没有

### ISSUE THREAD

**Issue by agrimony** [ecomfe/echarts#2993]
```js
 series : [data: [{
		"id": "0",
		"name": "Myriel",
		"itemStyle": null,
		"symbolSize": 28.685715,
		"x": -266.82776,
		"y": 299.6904,
		"attributes": {
			"modularity_class": 0
		},
		"value": 28.685715,
		"label": {
			"normal": {
				"show": false
			}
		},
		"category": 0
	}]
]
```
series[i]-graph.data[i]中的x,y是怎么定义的？翻遍的API也没找到定义。

**Comment by pissang** [comment]
x, y 分别是节点位置的x，y坐标

**Comment by agrimony** [comment]
@pissang  我的意思是这个坐标是直接随机生成的吗？还是说要依据某个条件去生成呢？有没有最大或者最小值？

**Comment by pissang** [comment]
如果自己没有布局的数据的话可以用不提供 x，y，然后把 layout 设成 force。也可以通过 gephi 等软件离线布局得到 x，y 的值

**Comment by zjyExcelsior** [comment]
@pissang 如果要画有向图，使用force布局，会导致不平衡吧？

**Comment by marcusgao94** [comment]
用gephi布局好的图，里面包含了x，y坐标，放到echarts里坐标是不一样的。在gephi里用力矢量布局点是分散开的，但在echarts里很多点又挤在一起了

**Comment by sunscheung** [comment]
@pissang  在不使用force布局前提下，可以像d3那样支持通过layout 布局得到 x，y 的值吗

**Comment by lingfulu** [comment]
请问下,graph data中的x,y设定初始位置的单位是什么?还是相对的单位长度?我测试声明x=0,y=0时,graph的节点并没有移动到左上角的位置

**Comment by ArrayZheng** [comment]
@pissang 如何绝对定位x，y值啊

**Comment by vincent-pli** [comment]
@pissang 还是没有回答问题啊，X, Y的值到底是什么意思，相对左上角的值吗？

**Comment by yoyoyueer** [comment]
请问graph 中的点如何在地图上定位，设置了coordinateSystem:'geo',，但是不显示

**Comment by loooo-ns** [comment]
初始化时使用x,y值可以渲染在正确位置，但通过属性设置来修改option时，新的设置没有办法生效。设置过fixed=true;draggable=false; 还是不行。那么请问应该如何在graph已经展现的情况下，设置其中某个节点的坐标呢？（例如根据交互将某节点移动到画布中心）

**Comment by loooo-ns** [comment]
> @lingfulu 声明x=0,y=0时是有作用的，但是需要设置
> 
> "fixed":true，
> "draggable": false,
> 否则定位的节点就会被拖拽走，
> 但是通过把整体图拖走，可以移动节点位置；
> 单独拖动单个节点，是无法再拖拽了

初始化时可行的，请问如何在展示状态下将某节点移动到画布中心呢？

**Comment by wangguangyou** [comment]
声明x=0,y=0没有到预期位置，除非只有一个节点。各节点是否会互相影响

**Comment by ccksfh** [comment]
same issue fixed并不会固定位置，节点删减和位置移动都会影响其他节点的位置（感觉有斥力存在），文档上也没描述清楚坐标原点、默认坐标系等信息

**Comment by snokier** [comment]
所以 `y` 指的是什么？基于左上角坐标还是啥。。

**Comment by TargetCenter** [comment]
怎么获得一个空白点的x，y值。

**Comment by ccyccxcl** [comment]
> 请问graph 中的点如何在地图上定位，设置了coordinateSystem:'geo',，但是不显示

请问有解决办法了吗？我目前也需要在graph上添加地图底图，但是不知道怎么加上去

**Comment by coco723** [comment]
这问题有解决办法了吗？看关闭了，但是好像没有看到解决方案

**Comment by coco723** [comment]
@pissang 请问怎么固定通过指定x、y使节点位置之间不会互相影响

**Comment by candy4290** [comment]
同问
