### ISSUE TITLE
while node dragged,the links not redraw in graph

### ISSUE THREAD

**Issue by zhhb** [ecomfe/echarts#2995]
#### 问题简述 (One-line summary)
设置类型为graph，设置layout:none，同时设置节点为draggable，当节点移动后links没有重绘
（需要在移动时不影响其他节点，没有设置为force）

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.6
+ 浏览器类型和版本 (Browser version):Chrome/49.0.2623.87
+ 操作系统类型和版本 (OS Version):OS X darwin x64

#### 重现步骤 (Steps to reproduce)
1.移动节点
2.节点改变位置，对应的links没有改变，导致节点个link脱离

#### 期望结果 (Expected behaviour)
link可以在节点移动时始终保持和节点的联系

#### ECharts配置项 (ECharts option)

```javascript
option = {
        tooltip: {show: true},
            toolbox: {
                show   : true,
                feature: {
                    saveAsImage: {
                        name: 'demo'
                    }
                }
            },
            series : [{
                name      : '复杂网络',
                type      : 'graph',
                layout    : 'none',
                symbol    : 'circle',
                symbolSize: 50,
                roam      : true,
                draggable : true,
                data      : [{
                    name: 'node1',
                    x   : 100,
                    y   : 100,
                }, {
                    name: 'node2',
                    x   : 400,
                    y   : 200,

                }, {
                    name: 'node3',
                    x   : 300,
                    y   : 200,
                }, {
                    name: 'node4',
                    x   : 200,
                    y   : 400,
                }],
                links     : [
                    {
                        source: 'node1',
                        target: 'node2'
                    },
                    {
                        source: 'node3',
                        target: 'node2'
                    },
                    {
                        source: 'node3',
                        target: 'node4'
                    }
                ]
            }]
        };

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/2919086/14528196/ebfb3104-0280-11e6-9863-469ae36317c4.png)
After drag
![image](https://cloud.githubusercontent.com/assets/2919086/14528208/fd90c5e6-0280-11e6-8978-91e1c93d7a75.png)

设置为 `force` 后也会发生(删除了节点的x，y属性)
```javascript
               layout    : 'force',
                force     : {
                    gravity   : 0.4,
                    edgeLength: 100,
                    repulsion : 30
                },
```
![image](https://cloud.githubusercontent.com/assets/2919086/14528964/d3f9b9c8-0284-11e6-9dd6-b746c2843014.png)

**Comment by zhhb** [comment]
我是否可以在GraphView.js中对drag进行如下修改
![image](https://cloud.githubusercontent.com/assets/2919086/14550628/dc371a18-02fc-11e6-8452-e0f4c1af399d.png)

**Comment by zhhb** [comment]
感觉应该是要修改GraphView.js里面对draggable判断处理，看了下，不是forcelayout的话，就直接没有添加对应事件处理，是这样的吗？

**Comment by pissang** [comment]
目前只允许力引导布局的 graph 能够启用 draggable

**Comment by zzswang** [comment]
需求 +1
