### ISSUE TITLE
大背景渐变怎么做的啊？

### ISSUE THREAD

**Issue by zacard-orc** [ecomfe/echarts#2996]
#### 问题简述 (One-line summary)
如何做背景渐变，我虽然可以用div改但是保存的时候没有效果。如果按下述语法
 option = {
    backgroundColor:new echarts.graphic.LinearGradient(0,0,0,1,[{
          offset:0,
          color:'red'
        },{
          offset:1,
          color:'yellow'
        }]),。。。。。。，但是还是白色的

#### 版本及环境 (Version & Environment)
+ ECharts 版本3:
+ 浏览器类型和版本Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1:
+ 操作系统类型和版本 macos10.10.4:

#### 重现步骤 (Steps to reproduce)
1.如上
2.如上

#### 期望结果 (Expected behaviour)
如上

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
backgroundColor设置成 transparent，然后css设置容器为渐变色

**Comment by zacard-orc** [comment]
这个方法我试过的，没用的，看着是渐变用TOOLBOX下载后还是底色，因为你的容器是DIV，要DIV里面要套SVG才有可能。
