### ISSUE TITLE
EChats与百度地图结合报错BMapExtension is not defined

### ISSUE THREAD

**Issue by eguitarkchen** [ecomfe/echarts#2998]
#### 问题简述 (One-line summary)
套用test中Bmap.html实例后提示Uncaught ReferenceError: BMapExtension is not defined，后分析了一下两个实例应该是不通用的吧。求教如何解决该问题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echats2
+ 浏览器类型和版本 (Browser version):Chrome
+ 操作系统类型和版本 (OS Version):Mac os x

#### 期望结果 (Expected behaviour)
提供一个比较完整的实例

**Comment by eguitarkchen** [comment]
问题已解决http://www.oschina.net/question/2305015_220916?fromerr=4XwWZe7N，最下端有个百度云demo，一看就知道问题在哪了

**Comment by eguitarkchen** [comment]
问题已解决http://www.oschina.net/question/2305015_220916?fromerr=4XwWZe7N
回复中有个百度云demo，一看就知道问题在哪了。百度云地址就不发了，大家需要就支持一下作者到原地址去吧，他也挺幸苦的，尝试过的都懂的。
顺带吐槽一下echarts的技术支持实在是太忽悠了，邮件发了很多次都根本没解决实质性问题。文档也是写的太笼统，只告诉需要加入扩展，不废话嘛。实例只放一段option是几个意思，醉醉的。总的来说Echarts用起来很不错，但是echarts2的文档都比echarts3的好，文档实在是都有点不太可信，希望能够做好，这里表示支持

**Comment by pissang** [comment]
技术支持？我们乐意接受bug 的反馈和改进的建议，但是你自己在项目中碰到这种没头没脑的问题然后找我们帮你解决，对不起我们没这精力。

**Comment by eguitarkchen** [comment]
没头没脑？你好好摸摸自己良心说话，搜完整个github项目完全没找到BMapExtension这个方法，各种关于echarts的论坛到处在问关于BMapExtension的问题。行，你厉害，百度的人还真是厉害。请教竟然得到这样的答案，真不错。

**Comment by eguitarkchen** [comment]
情绪有点失控，抱歉。说了什么不应该说的话，对百度员工心灵造成了伤害，对这事也表示抱歉，对不起。提下个人感受吧，文档的混乱造成了一些不必要的麻烦，旧版本和新的版本修改幅度很大，但文档并没有改，或者没有文档，文档真的很差，这个我不想再争辩，看英文文档都没这么费劲。Echarts强大不容置疑，但是文档跟不上再强大也没多少人真的会用，不可能每来一个人都把扩展js都看一遍，看懂了再用吧。身在高位可能根本不知道黎明百姓的痛苦，我们用echarts根本不可能像你们一样什么都能看到，层次不一样，我们只能摸着走，有文档还好，能快点。要是像之前这样遇到了根本不存在的方法，你让我们怎么办？问你们，你们还这么高姿态，高攀不起。

**Comment by pissang** [comment]
你如果搜过 echarts 下载的包文件就会发现 BMapExtension 是百度地图示例里定义的一个变量。github 搜不到是因为 1. 现在新版本的代码都不一样了，包括示例。2. 没人之前有问过这个问题。说实话这个问题也没需要你把  js 都看一遍，你只要稍微仔细看一下示例的代码就知道问题出在哪了

**Comment by eguitarkchen** [comment]
不好意思，我就是想要作出echarts2那种效果没碍着你事吧，你不愿意帮忙直接说个方法已弃用，使用新版不就可以，为什么非要这样带嘲讽口气。
用echarts好像不是只能在github提问吧，我们高攀不起，找不到能帮忙的大家可以找别的大神帮忙啊。

**Comment by pissang** [comment]
我跟你说明问题又变成嘲讽口气了？是谁开始用不友善的语气说“太忽悠了”，“几个意思”，“醉醉的”。你要用 echarts 2 的扩展我有说不行么？示例都摆在那，自己要做伸手党还觉得我们高姿态？

**Comment by eguitarkchen** [comment]
抱歉，语气有问题，对不住，您是大爷，文档写的太好了，我自己下去需要多研究研究，我得捧着您。我自己解决，您忙您的，多有打扰

**Comment by kener** [comment]
楼上息怒，换位思考都能理解。

作为ec的用户，确实有很多可吐槽的，插件说明缺失，文档不完善，作为小白进来导航分类确实会很晕，无从下手，这也是真实的体会需要改进，研发团队对我们怒其不争一点用也没有，比我菜的人还大有人在，我在着急时也伸手，这是人“懒”的天性，技术改变世界最终也是让人可以越来越“懒”，这也是你们伟大的地方，更重要的是当我万分无助时其实作为研发团队的你们就是我最大的希望，寄予期待越大可能产生的失望也越大，不怕没问题，就怕没发现问题。

作为曾经的研发团队，我深有感触，并不是不愿意做或做不好，只是要做的事情确实太多了，他们每天也都加班加点，文档没跟上或者回复没即时响应这真的只能说抱歉，也许他们计划内还有更重要和紧急的事情要做，涉及的面可能更广，开发和支持的平衡我自问也做不好，以致于也曾经做过这个决定 http://www.oschina.net/news/57032/echarts-kener-retire?from=20141116 

我相信ec团队的每一位都是问心无悔的认真做事，相互理解，好好说话，有人用心做好产品的同时有人使用才能推动前进，缺一不可，相信ec会越来越好的~

**Comment by eguitarkchen** [comment]
峰哥无需担心，你对我们的帮助大家有目共睹，确实也没什么大事，只是单纯的咽不下这口气而已。
我的话语也确实不合适，也不恰当，用了不该用的词，这是我的问题，深刻检讨自己。当然了，问题也并没有描述清楚，这也是我的问题，造成了不必要的麻烦。
大家都是做开发的，都希望能互相鼓励我也觉得是必要的。同时ec够炫够酷也是大家用ec的理由，支持ec能做得更好，越来越多的人能够使用ec。

**Comment by cqzuo** [comment]
新版的文档和旧版确实差一大截。。
