### ISSUE TITLE
Android 4.3及以下版本无法显示图表

### ISSUE THREAD

**Issue by chrisArthas** [ecomfe/echarts#3001]
#### 问题简述 (One-line summary)
Android 4.3 及以下版本的webView 控件中显示图表，无法显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7
+ 浏览器类型和版本 (Browser version): Android webView控件中显示
+ 操作系统类型和版本 (OS Version):Android 4.3 或者以下

#### 重现步骤 (Steps to reproduce)
1.Android webView控件显示一个带有echarts 图表的本地网页
2.在Android4.3中运行

#### 期望结果 (Expected behaviour)
图表正常显示

#### 可能哪里有问题 (What went wrong)

无法显示

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
试一下 echarts 3
