### ISSUE TITLE
堆积折线图 有bug

### ISSUE THREAD

**Issue by giscafer** [ecomfe/echarts#3004]
#### 问题简述 (One-line summary)

堆积折线图 有bug。多条折线的时候，折线点的数据不对（Y轴不对，会被推上去）
http://echarts.baidu.com/demo.html#line-stack

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.X和3.X都有这个问题
+ 浏览器类型和版本 (Browser version):任何浏览器
+ 操作系统类型和版本 (OS Version):windows

#### 重现步骤 (Steps to reproduce)
1.直接看DEMO的数据和看折线的Y轴。
2.可以切换显示折线看效果，明显被推高了

#### 期望结果 (Expected behaviour)

正确的统计，haighchart效果是对的
http://www.hcharts.cn/demo/index.php?p=10

**Comment by pissang** [comment]
先去了解下什么是堆积折线图

**Comment by giscafer** [comment]
仔细看吧，highchart的堆积，Y轴数据变化后，各个折线Y值还是正确的。echart就错了。。。

版本2.x和3都是这个问题没注意吗？？？

**Comment by pissang** [comment]
你知道什么是堆积么？

**Comment by giscafer** [comment]
@pissang 那不是堆积图了，是多个折线图。用户提的bug。对比highchart发现没问题。echart效果确实和 highchart不一样。
http://www.hcharts.cn/demo/index.php?p=10
http://echarts.baidu.com/demo.html#line-stack（搜索引擎周一的数据是820，堆叠起来就在1500和2000之间了）

**Comment by pissang** [comment]
堆积就是后面一条的位置是叠加在前面一条之上的，我发你的第一个链接里 highcharts 的例子里也是，不要这效果可以把 stack 去掉，不明白你的点在哪里
