### ISSUE TITLE
legend的文字和图标不对齐啊

### ISSUE THREAD

**Issue by yuu2lee4** [ecomfe/echarts#3008]
#### 问题简述 (One-line summary)

legend的文字和图标不对齐

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.6
+ 浏览器类型和版本 (Browser version):qq浏览器9.4
+ 操作系统类型和版本 (OS Version):win10 64

#### 重现步骤 (Steps to reproduce)
1.添加legend
2.

#### 期望结果 (Expected behaviour)
legend的文字和图标对齐

#### 可能哪里有问题 (What went wrong)
新版本的问题  以前就是对齐的  而且你们线上的实例现在也是不对齐的了

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/8046366/14558569/bf17d308-0335-11e6-9be1-dc2875d9bf38.png)

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/2819
