### ISSUE TITLE
echarts如何解决series内data为null或者0所引起的图表线条断层问题

### ISSUE THREAD

**Issue by lhsai9** [ecomfe/echarts#3009]
#### 问题简述 (One-line summary)

echarts如何解决series内data为null或者0所引起的图表线条断层问题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3
+ 浏览器类型和版本 (Browser version): chrome9.0.2623.112 m (64-bit)
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
1.在折线图中，如果series.data出现NULL，那么echart似乎会按0处理

#### 期望结果 (Expected behaviour)

能否有一项设置，忽略过这个NULL数据，处理掉断层问题
heightCharts中有connectNulls这个配置项处理该问题，但是就是喜欢echarts，希望能改善。
希望echarts越来越优秀！

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢建议，同 https://github.com/ecomfe/echarts/issues/2579 ，后续会考虑加入
