### ISSUE TITLE
echarts3.0中的散点图，若xAxis的type设置为category,那么series里的data该是什么格式？

### ISSUE THREAD

**Issue by sin911** [ecomfe/echarts#3015]
#### 问题简述 (One-line summary)
求教如何在散点图里，可以使x轴显示时间(或者是字符串)而不是整型

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome最新版
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.请看下方的【ECharts配置项 (ECharts option)】

#### 期望结果 (Expected behaviour)
希望可以在散点图中的x轴使用时间

#### 可能哪里有问题 (What went wrong)
在echarts2.0中，我是成功把x轴显示字符串的，方法是把 
xAxis : [{type : 'value'}]改成xAxis : [{type : 'category'}]，具体请看下方的代码
(下方的代码无法正常画出散点图，但是在echart2.0的时候，是正常的)
(关于为何弃用2.0的原因：因为最近做的项目要用到移动端，2.0的散点图在华为机器上无法显示，3.0的可以，所以只能换成3.0了。)

#### ECharts配置项 (ECharts option)

```javascript
option = {
 tooltip : {
        trigger: 'axis',
        showDelay : 0,
    axisPointer:{
            show: true,
            type : 'line',
      lineStyle: {
        color: '#48b',
        width: 2,
        type: 'solid'
    }
        },
        zlevel: 1
    },
    legend: {
        data:['sin','cos']
    },
    xAxis : [
        {
            type : 'category',//把value改成了category
            scale:true,
  data: ['20160401','20160402','20160403','20160404']//时间格式，如2016年4月1日
  
        }
    ],
    yAxis : [
        {
            type : 'value',
            scale:true
        }
    ],
    series : [
        {
            name:'sin',
            type:'scatter',
            large: true,
            symbolSize: 12,
         data: [['20160401',3],['20160402',5],['20160403',7],['20160404',7]]
           // data: [[3,3],[4,5],[7,7]]
        },
        {
            name:'cos',
            type:'scatter',
            large: true,
            symbolSize: 12,
  data: [['20160401',6],['20160402',8],['20160403',11],['20160404',5]]
    //data: [[6,3],[11,5],[14,4]]
        }
    ]
}

```

#### 其他信息 (Other comments)

在echarts2.0的时候，以上方法可以正常出现散点图，可是换到了3.0，就不行了。不知道该怎么解决了，求帮助，谢谢。（我真的已经不断修改了10个小时了，还是无法解决，所以来请求帮助的，万分谢谢。）
大神可以在这里帮忙调试哈 http://echarts.baidu.com/demo.html#scatter-large

**Comment by pissang** [comment]
像 2.x 那样用类目数据应该是可以的，但是这个例子不行我还得找一下是什么原因。

有一个更稳妥的办法是数据改为类目的索引。参考双类目轴的散点图示例 http://echarts.baidu.com/gallery/editor.html?c=scatter-punchCard

```js
data: [[0, 3], [1, 5]...]
```

如果数据中的类目是顺序的话也可以把第一项忽略掉，跟柱状图的数据一样

```js
data: [3, 5, 7, 7]
```

**Comment by sin911** [comment]
谢谢大神帮助
