### ISSUE TITLE
echarts 补空点问题。

### ISSUE THREAD

**Issue by thehackercat** [ecomfe/echarts#3017]
#### 问题简述 (One-line summary)
在用 echarts 生成图标的时候遇到了无数据时补空点仍然显示有数据的问题。
以及从补空点到数据开始出现的点不是呈现平滑连接。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.4
+ 浏览器类型和版本 (Browser version): chrome 48
+ 操作系统类型和版本 (OS Version): windows 7

#### 重现步骤 (Steps to reproduce)
1.添加任意的一个补空点
2.在补空点后一段时间内添加数据
3.发现入问题简述所述 bug

#### 期望结果 (Expected behaviour)
平滑连接。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/search?q=connectNulls&type=Issues&utf8=%E2%9C%93
