### ISSUE TITLE
关系图layout:none时设置可移动draggable:true---点可以移动但是线不跟着走

### ISSUE THREAD

**Issue by wangxiaofeid** [ecomfe/echarts#3018]
#### 问题简述 (One-line summary)
关系图layout:none时设置可移动draggable:true---点可以移动但是线不跟着走

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.6
+ 浏览器类型和版本 (Browser version):safari 9.1
+ 操作系统类型和版本 (OS Version):OS X

#### 重现步骤 (Steps to reproduce)
http://echarts.baidu.com.cn/demo.html#graph
上面每个点上添加
draggable:true

#### 期望结果 (Expected behaviour)
期望可以跟着移动

#### 可能哪里有问题 (What went wrong)
src/chart/graph/forceLayout.js

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/2995
