### ISSUE TITLE
visualMap的seriesIndex使用无效

### ISSUE THREAD

**Issue by Godlinbupt** [ecomfe/echarts#3024]
有map 和 pie 两个series，只想对于map使用visualMap，按照配置手册中使用 seriesIndex=0，仅对map起作用，但是pie也被使用该visualMap。所以怎么样才能将map与pie的颜色分开呢？

源码：
```js
option = {

			geo: {
		        map: 'china',
		    },
			visualMap:[
			{
				show:true,
				type:'continuous',
                                seriesIndex:0,
				min:10,
				max:26,
				precision:2,

			},//地图上的颜色渐变
			],//end of visualMap

			series:[
			{
				type:'map',
				map:'china',
				name:"homeMap",
				label:{
					emphasis:{
						show:true,
					}
				},
				itemStyle:{
					emphasis:{
						areaColor: '#171716',
					},
				},
				data:provinceData,
			},//end of map sesries
			{
	            name:'面积模式',
	            type:'pie',
	            radius : [30, 110],
	            center : ['75%', 200],
	            roseType : 'area',
	            data:[
	                {value:10, name:'rose1'},
	                {value:5, name:'rose2'},
	                {value:15, name:'rose3'},
	                {value:25, name:'rose4'},
	                {value:20, name:'rose5'},
	                {value:35, name:'rose6'},
	                {value:30, name:'rose7'},
	                {value:40, name:'rose8'}
	            ]
	            
		    },//end of pie series
			],//end of series
	}//end of option
	mapChart.setOption(option);
```

**Comment by pissang** [comment]
我试了下是有效的

**Comment by Godlinbupt** [comment]
@pissang 嗯，我在 http://echarts.baidu.com/gallery/    试了，这样确实有效，谢谢

但其实我是想实现在点击map省份时，在点击省份上出现pie，但此时visualMap就会有问题，饼图颜色就会跟着map的visualMap：
option = {
			geo: {
		        map: 'china',
		    },
			visualMap:[
			{
				show:true,
				type:'continuous',
				seriesIndex:0,
				min:10,
				max:26,
				precision:2,

			},//地图上的颜色渐变
			
			],//end of visualMap

			series:[
			{
				type:'map',
				map:'china',
				name:"homeMap",
				label:{
					emphasis:{
						show:true,
					}
				},
				itemStyle:{
					emphasis:{
						areaColor: '#171716',
					},
				},
				data:provinceData,
			},//end of map sesries
			{
	            type:'pie',
	            radius : [30, 110],
	            roseType : 'area',

		    },//end of pie series
			],//end of series

	}//end of option



	mapChart.setOption(option);
	mapChart.on('click',function(params){
		var selectName = params.name;
		var seriesModel=mapChart.getModel().getSeriesByIndex(0);
		var coordSys=seriesModel.coordinateSystem;
		var coord= coordSys.dataToPoint(geoCoordMap[selectName]);//将坐标转换为经纬度

		mapChart.setOption({
			title:{text:selectName},
			series:[
			{},
			{
				center:coord,
				data:provinceStock[selectName],//绘制饼图
		    }],
		    });
	});

**Comment by pissang** [comment]
应该是第二次 setOption 的时候 seriesIndex 进行了错误的处理恢复成了默认值，你可以先每次 setOption 都强制设置 seriesIndex，我们下个版本修复

**Comment by Godlinbupt** [comment]
嗯，原来是这样，问题解决了。非常感谢~ @pissang
