### ISSUE TITLE
地图的最小缩放值大于 1 时，地图不居中画布，缩放后 coordinateSystem 计算出错

### ISSUE THREAD

**Issue by Cople** [ecomfe/echarts#3029]
#### 问题简述 (One-line summary)
地图设置最小缩放值大于 1 时：
1. 地图默认不会居中于画布
2. 缩放地图后，`coordinateSystem.dataToPoint` 计算不对

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.6
+ 浏览器类型和版本 (Browser version): Chrome 49
+ 操作系统类型和版本 (OS Version): OS X El Capitan

#### 重现步骤 (Steps to reproduce)
1. `scaleLimit.min` 设置为大于 1
2. `roam` 设置为 true
3. 使用 #2540 的方法转换经纬度为页面坐标
4. 缩放地图
5. 再次计算坐标

#### 期望结果 (Expected behaviour)
地图默认居中于画布；
缩放后，`coordinateSystem.dataToPoint` 返回正确的坐标

#### ECharts配置项 (ECharts option)

```javascript
option = {
    series: [{
        name: '地图',
        type: 'map',
        map: 'china',
        roam: true,
        scaleLimit: {
            min: 1.2,
            max: 3
        },
        data: [
            { name: '华北', lng: 120, lat: 44, value: 1500 }
        ]
    }]
}

```

#### 其他信息 (Other comments)
[JSFiddle](https://jsfiddle.net/ajevsL5w/)

**Comment by ustczy** [comment]
你好，请问后来问题解决了吗？我现在遇到同样的问题，没找到任何资料。。。

**Comment by Cople** [comment]
没解决，只能设置为 1 了。

**Comment by pissang** [comment]
最新版本没这个问题

**Comment by ustczy** [comment]
现在我只是在页面上有个饼图，然后浏览器不断刷新，也偶尔会出现饼图错位问题，这个在最新版本里也修复了吗？@pissang
