### ISSUE TITLE
Echarts3不能运行官方demo

### ISSUE THREAD

**Issue by zhang14725804** [ecomfe/echarts#3031]
Echarts2从github上下载源码解压后直接双击demo页面就可以显示效果
Echarts3从github上下载源码解压后运行官方demo报错，，显示路径不对，所有的demo都不能运行，怎么回事

我把源码解压到桌面，默认浏览器是chrome
报错： file:///C:/Users/zhangxh/Desktop/zrender/src/core/env.js net::ERR_FILE_NOT_FOUND

**Comment by pissang** [comment]
3 test 目录下是我们自己的测试示例，官方示例见 http://echarts.baidu.com/gallery/

**Comment by zhang14725804** [comment]
在线构建下载下来只是一个echarts.min.js，文件，怎么跑起来？？

    
    <script src="echarts.min.js"></script>
</head>
<body>
    
    <div id="main" style="width: 600px;height:400px;";></div>
    <script type="text/javascript">

// 指定图表的配置项和数据
        var option = {
                。。。。。
        };

之后呢？？再怎么做？不需要require了？

**Comment by zhang14725804** [comment]
好歹我也是用过Echarts2的人，现在连最起码的demo都跑不起来，，

**Comment by zhang14725804** [comment]
官方的例子我把这段复制的上去，报错
Cannot read property 'prepareBoxplotData' of undefined

data = [];
for (var seriesIndex = 0; seriesIndex < 5; seriesIndex++) {
    var seriesData = [];
    for (var i = 0; i < 18; i++) {
        var cate = [];
        for (var j = 0; j < 100; j++) {
            cate.push(Math.random() * 200);
        }
        seriesData.push(cate);
    }
    data.push(echarts.dataTool.prepareBoxplotData(seriesData));
}

**Comment by pissang** [comment]
有些示例引入了 https://github.com/ecomfe/echarts/blob/master/dist/extension/dataTool.min.js 扩展
