### ISSUE TITLE
页面button如何实现legendd点击隐藏功能？

### ISSUE THREAD

**Issue by chaozheng** [ecomfe/echarts#3032]
#### 问题简述 (One-line summary)
我想在页面上单独设置按钮实现，图例组件的点击功能。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts3

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#legend.selected

**Comment by wang-xinglei** [comment]
万能接口，配置图表实例任何可配置选项（详见option），多次调用时option选项默认是合并（merge）的，merge的设计可以让setOption很方便的成为更新任何属性的万能方法，比如你仅需要改title文字，则仅需要：
 setOption({title : {text : '新标题'}});

**Comment by chaozheng** [comment]
已经通过setOption实现
