### ISSUE TITLE
echarts3 图例(legend)不能手动换行

### ISSUE THREAD

**Issue by M1ns** [ecomfe/echarts#3039]
#### 问题简述 (One-line summary)
ECharts 3 是否不支持legend手动换行功能,若支持应如何操作?

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.5
+ 浏览器类型和版本 (Browser version):chrome 49.0.2623.87 m (64-bit)
+ 操作系统类型和版本 (OS Version):win8.1 专业版

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
legend手动换行

#### ECharts配置项 (ECharts option)

```javascript
option = {
			    tooltip : {
			        trigger: 'item',
			        formatter: "{b}</br>比例:{d}%"
			    },
			    legend: {
			        left: 'center',
			        bottom: '5%',
			        selectedMode: false,
			        data: ['a','b','','c']
			    },

			    series : [
			        {
			            type: 'pie',
			            radius : '50%',
			            center: ['50%', '30%'],
			            data:[{value:3,name:'a'},{value:2,name:'b'},{value:1,name:'c'},],
			            itemStyle: {
			            	normal:{
			            		label:{
			            			formatter:'{d}%',
								    textStyle:{
								    	fontFamily: '"Microsoft YaHei", Arial, Verdana, sans-serif'
								    }
			            		}
			            	}
			            }
			        }
			    ]
}

```

**Comment by pissang** [comment]
name: '\n' 可以换行

**Comment by M1ns** [comment]
抱歉可能表述得不清晰..
'\n'只是文字换行..我想表达的是[如图]的意思
![filehelper_1461219106225_14](https://cloud.githubusercontent.com/assets/8433774/14699700/76eed75c-07cc-11e6-9a12-b8951227a31a.jpg)
的效果

**Comment by pissang** [comment]
我指的就是这个，空格也可以，'\n' 换行是 3 中新加的

**Comment by M1ns** [comment]
啊,那这个地方可能bug了,饼图的legend 空字符和换行符都没有反应,其他图表我试过可以了

**Comment by pissang** [comment]
好像是的，谢谢反馈

**Comment by julien-joe** [comment]
图例中图片和文字不能够水平居中对齐

**Comment by CeleKing** [comment]
个性化图例样式 怎么传入空的字符串啊？
