### ISSUE TITLE
刷新，map  给data[]设置不同颜色

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#3042]
#### 问题简述 (One-line summary)
echart3 不能单独设置data 的颜色

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):google
+ 操作系统类型和版本 (OS Version): win7 

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 可能哪里有问题 (What went wrong)
option.series[0].data[i].itemStyle.emphasis.borderColor='#FFF';(不支持这样写，)

这里被选中的区域要设置不同颜色

#### ECharts配置项 (ECharts option)

```javascript
option = {

        
}
function UpdataMapData(){
  d=[{name:'新疆',color:'#41B348'},{name:'北京',color:'red'},{name:'四川',color:'yellow'}];
          for(var i=0; i<length;i++){
			var name =d[i].name;
			option.series[0].data[i].name=name;
			
			option.series[0].data[i].selected = true;
			option.series[0].itemStyle.emphasis.areaColor=d[i].color;
			option.series[0].itemStyle.emphasis.borderColor='#FFF';
			
			option.series[0].itemStyle.emphasis.borderWidth=3;
			option.series[0].itemStyle.emphasis.color="yellow";
		}
}
```

**Comment by pissang** [comment]
data 下 的 itemStyle.normal.areaColor

**Comment by chm74** [comment]
上面的被选中的区域，是要切换刷新的，option.series[0].itemStyle.emphasis.areaColor=d[i].color;
这样设置的话，他把这个data[]中的所有区域，都设置成了一个颜色，我想要给每个区域设置不同颜色怎么办
