### ISSUE TITLE
tooltip:{show:false} doesn't seem to have any effect

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3047]
version: 3.1.6

Trying to disable tooltip by tooltip:{show:false} but doesn't seem to have any effect:

![image](https://cloud.githubusercontent.com/assets/561365/14703314/936d4494-07af-11e6-843a-4e0b1c943a10.png)

**Comment by pissang** [comment]
`showContent: false`

**Comment by jarben** [comment]
I see - thank you
