### ISSUE TITLE
Is it possible to have custom button near legend in chart

### ISSUE THREAD

**Issue by ukris** [ecomfe/echarts#3050]
#### 问题简述 (One-line summary)
Is it possible to have custom button near legend in chart

#### 版本及环境 (Version & Environment)
3.1.6
+ ECharts 版本 (ECharts version):3.1.6
+ 浏览器类型和版本 (Browser version):NA
+ 操作系统类型和版本 (OS Version):NA

#### 重现步骤 (Steps to reproduce)
1.  I would like custom legend (button) such that when I click on it, I can enable disable  a group of data
2. For example, I have data showing revenue vs loss and let us say I have five products.
    I may want to toggle to show only revenue or only loss.
    Right now I have it as a stack bar for each product showing revenue and loss (with loss in -ve Y axis)

Th

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/3007#issuecomment-210398601
