### ISSUE TITLE
ItemStyle barBorderColor as function

### ISSUE THREAD

**Issue by karolszymczak** [ecomfe/echarts#3058]
Hi,

Would it be possible to add possiblity of defining barBorderColor as function of data? in the same way as we can define color?

Thanks

**Comment by pissang** [comment]
Currently you can only define barBorderColor in each data item like
```js
data: [{
  value: 10,
  itemStyle: {
    normal: {
       barBorderColor: ''
    }
  }
}]
```

Supporting callback has not been in the plan
