### ISSUE TITLE
How to use markline, with category X-axis ?

### ISSUE THREAD

**Issue by sujith3g** [ecomfe/echarts#3060]
#### 问题简述 (One-line summary)

How to draw a line using `markline` at specific Y-axis value in a line graph

#### 版本及环境 (Version & Environment)
+ ECharts 3.0 (ECharts version):
+ Google chrome (Browser version):
+ OS X (OS Version):

#### 重现步骤 (Steps to reproduce)
1. open [this](http://echarts.baidu.com/demo.html#line-marker) echarts example
2. use the below options

```javascript
option = {
    title: {
        text: '未来一周气温变化',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['最高气温','最低气温']
    },
    toolbox: {
        show: true,
        feature: {
            dataZoom: {},
            dataView: {readOnly: false},
            magicType: {type: ['line', 'bar']},
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis:  {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value',
        axisLabel: {
            formatter: '{value} °C'
        }
    },
    series: [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10],
            markPoint: {
                data: [
                    {type: 'max', name: '最大值'},
                    {type: 'min', name: '最小值'}
                ]
            },
            markLine: {
                data: [
                    {
                        name : "Test",
                        x : 0,
                        y : 11
                    },{
                        name :"Test",
                        x: MAXNUMBER,
                        y : 11
                    }
                ]
            }
        },
        {
            name:'最低气温',
            type:'line',
            data:[1, -2, 2, 5, 3, 2, 0],
            markPoint: {
                data: [
                    {name: '周最低', value: -2, xAxis: 1, yAxis: -1.5}
                ]
            },
            markLine: {
                data: [
                    {type: 'average', name: '平均值'}
                ]
            }
        }
    ]
};

```

#### 期望结果 (Expected behaviour)

```javascript
markLine: {
                data: [
                    {
                        name : "Test",
                        x : 0,
                        y : 11
                    },{
                        name :"Test",
                        x: MAXNUMBER,
                        y : 11
                    }
                ]
            }
```
`markline` should draw a line at Y-axis value `11`. But it is not working. It is not clear from the documentation about how to use the `markline` when X-axis is of category type.

#### ECharts配置项 (ECharts option)

Same as it is provided in steps-to-reproduce section.

**Comment by pissang** [comment]
Sorry I can't reproduce your problem.

**Comment by sujith3g** [comment]
@pissang Try with the json provided in steps-to-reproduce section of the issue, I'm trying to create line at Y-axis value 11, using the `markline`, and the X-axis of category type.

```javascript
markLine: {
                data: [
                    {
                        name : "Test",
                        x : 0,
                        y : 11
                    },{
                        name :"Test",
                        x: MAXNUMBER,
                        y : 11
                    }
                ]
            }
```

But when I use this it is not creating the line at Y=11

**Comment by pissang** [comment]
I know, you need to change `x` and `y` to `xAxis` and `yAxis`, or use `coord: [0, 11]`.

**Comment by sujith3g** [comment]
I've tried it not working, As I mentioned the X-axis of category type.
```javascript
 markLine: {
                data: [
                    {
                        name : "Test",
                        xAxis : 0,
                        yAxis : 11
                    },{
                        name :"Test",
                        xAxis: 7,
                        yAxis : 11
                    }
                ]
            }
```
This is not creating a line

**Comment by pissang** [comment]
Try
```js
markLine: {
    data: [[
        {
            name : "Test",
            xAxis : 0,
            yAxis : 11
        },{
            name :"Test",
            xAxis: 6,
            yAxis : 11
        }
    ]]
}
```

Data needs to be a 2d array, and xAxis must not exceeds the `xAxis.data.length`

**Comment by sujith3g** [comment]
thank you @pissang, It is not clear from the documentation(english translated version) [here](http://echarts.baidu.com/option.html#series-line.markLine.data)

**Comment by pissang** [comment]
Not a problem. English translated version is not ready yet. In that documentation `x`, `y` means pixel position on screen.

**Comment by lvca** [comment]
How can I display a vertical line from the top to the bottom of the chart? Can I use any keyword for it? I've seen that if values are out of the displayed range, the line is simply not displayed.

**Comment by homura** [comment]
Same problem as @lvca. The markline only relate to a category, but I still have to set yAxis for it. How could I implement it simply without get max and min value of yAxis

**Comment by homura** [comment]
> How can I display a vertical line from the top to the bottom of the chart? Can I use any keyword for it? I've seen that if values are out of the displayed range, the line is simply not displayed.



> Same problem as @lvca. The markline only relate to a category, but I still have to set yAxis for it. How could I implement it simply without get max and min value of yAxis

finally I found the solution https://github.com/apache/incubator-echarts/issues/3359#issuecomment-223866750

just set {xAxis: 'some category'}

**Comment by RaviKLoyi** [comment]
> thank you @pissang, It is not clear from the documentation(english translated version) [here](http://echarts.baidu.com/option.html#series-line.markLine.data)

Hi @sujith3g, Is this issue fixed? I tried this fix but can't see markLine. 
![Screenshot from 2020-09-27 21-38-45](https://user-images.githubusercontent.com/15179428/94369860-e0a25300-0109-11eb-801e-703cf219a20b.png)

**Comment by RaviKLoyi** [comment]
After searching the web, I found something, and it worked for me. We should import markLine in the component. The same for markPoint as well.

import 'echarts/lib/component/markLine'
import 'echarts/lib/component/markPoint'

**Comment by omkargodse** [comment]
Is there any way to add a markline on X-Axis not on series?
