### ISSUE TITLE
Font size of title should stay the same for different `fontWeight`

### ISSUE THREAD

**Issue by Ovilia** [ecomfe/echarts#3064]
## Summary

When `title.textStyle.fontWeight` is set to be values other than `'normal'`, font size seems to be much smaller than that of `'normal'`.
## Expection

Font size of title should stay the same for different `fontWeight`.
## Options and behavior

``` javascript
option = {
    series: [],
    title: {
        text: 'normal font',
        textStyle: {
            fontWeight: 'normal'
        }
    }
}
```

![normal](https://cloud.githubusercontent.com/assets/779050/14772719/17b2e52a-0ad4-11e6-9f94-de707cb35be1.png)

``` javascript
option = {
    series: [],
    title: {
        text: 'bold font',
        textStyle: {
            fontWeight: 'bold'
        }
    }
}
```

![bold](https://cloud.githubusercontent.com/assets/779050/14772727/1de7d6da-0ad4-11e6-8f00-5637678c6753.png)

``` javascript
option = {
    series: [],
    title: {
        text: 'bolder font',
        textStyle: {
            fontWeight: 'bolder'
        }
    }
}
```

![bolder](https://cloud.githubusercontent.com/assets/779050/14772793/b71bb93e-0ad4-11e6-9968-e468b4ab4ef5.png)

``` javascript
option = {
    series: [],
    title: {
        text: 'lighter font',
        textStyle: {
            fontWeight: 'lighter'
        }
    }
}
```

![lighter](https://cloud.githubusercontent.com/assets/779050/14772728/21fd2b80-0ad4-11e6-8b57-3a3fd9b53067.png)

``` javascript
option = {
    series: [],
    title: {
        text: 'font weight at 100',
        textStyle: {
            fontWeight: '100'
        }
    }
}
```

![100](https://cloud.githubusercontent.com/assets/779050/14772730/26ada47a-0ad4-11e6-96c6-0f5fd0915171.png)
## Test Environment

ECharts v3.1.7
Mac OS X 10.10.5
Chrome 50.0.2661.86 (64-bit)
Test cases at `./test/ut/ui.html?spec=title.textStyle%20textStyle.fontWeight`

**Comment by victoryboss** [comment]
Has this issue been tested on other browsers ?
