### ISSUE TITLE
echarts 3在关系图中，不支持箭头，但是echarts 2支持。希望能尽快支持 

### ISSUE THREAD

**Issue by sunshine91** [ecomfe/echarts#3068]
#### 问题简述 (One-line summary)

echarts 3在关系图中，不支持箭头，但是echarts 2支持。希望能尽快支持 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by sunshine91** [comment]
箭头指节点间的线上画箭头

**Comment by pissang** [comment]
已经在计划中

**Comment by wdd119** [comment]
请问箭头这个已经加上去了吗

**Comment by xmail978** [comment]
tree 图可以带箭头吗？
