### ISSUE TITLE
echarts 3是不是不支持树结构

### ISSUE THREAD

**Issue by rainwin** [ecomfe/echarts#3069]
#### 问题简述 (One-line summary)
echarts3 不支持树结构啊？echarts2中是支持的啊，为什么会这样啊

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 2 中的树图我们觉得还完善，所以先暂时移除了
