### ISSUE TITLE
Magic type not working in Pie Chart

### ISSUE THREAD

**Issue by thangbn** [ecomfe/echarts#3070]
#### 问题简述 (One-line summary)
magicType in toolbox is not working (http://echarts.baidu.com/demo.html#pie-roseType). It working before in Echarts 2 ( in example: https://ecomfe.github.io/echarts/doc/example/pie1.html#-en )

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.6
+ 浏览器类型和版本 (Browser version): Chrome 49
+ 操作系统类型和版本 (OS Version): Windows 10

#### 重现步骤 (Steps to reproduce)
1. Go here: http://echarts.baidu.com/demo.html#pie-roseType
2. look at the chart, other toolbox features are displayed, excepted magic type.

#### 期望结果 (Expected behaviour)

Display magic type.

#### 可能哪里有问题 (What went wrong)

Does not display magic type.

#### ECharts配置项 (ECharts option)

```javascript
 toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true,
                type: ['pie', 'funnel']
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },

```

**Comment by pissang** [comment]
Yes, we think switch between 'pie' and 'funnel' is meaningless. So we removed it

**Comment by thangbn** [comment]
OK. so i think we better removed it from the example to avoid the confusion.
Thanks.
