### ISSUE TITLE
当xAxis的position为top时，再设置yAxis的min，X轴线会移动到上方

### ISSUE THREAD

**Issue by zhump** [ecomfe/echarts#3071]
#### 问题简述 (One-line summary)

当xAxis的position为top时，再设置yAxis的min，X轴线会移动到上方

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.7
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.设置xAxis的position为top
2.再设置yAxis的min

#### 期望结果 (Expected behaviour)

X轴线不动

#### ECharts配置项 (ECharts option)

```javascript
option = {
    xAxis: {
        type : 'category',
        position:'top',
        data : ['总费用','房租','水电费','交通费','伙食费','日用品数']
    },
    yAxis: {
        type : 'value',
        //放开这里就会出现问题
        //min:1
    },
    series: [
        {
            name: '辅助',
            type: 'bar',
            stack:  '总量',
            data: [0, 1700, 1400, 1200, 300, 0]
        },
        {
            name: '生活费',
            type: 'bar',
            stack: '总量',
            data:[2900, 1200, 300, 200, 900, 300]
        }
    ]
};

```

#### 其他信息 (Other comments)

![a30e474a-202b-47b9-a406-46aebfcb7228](https://cloud.githubusercontent.com/assets/7962067/14778012/26cc7efc-0b03-11e6-99ac-758124868afe.png)
![c9ee8735-29bc-4e32-a95b-209947b6b866](https://cloud.githubusercontent.com/assets/7962067/14778023/3c57cfec-0b03-11e6-9853-ac98ad39c2be.png)

**Comment by pissang** [comment]
设置为 min 的时候会导致 `xAxis.axisLine.onZero` 失效，所以会按照 position 的配置显示在最上面
