### ISSUE TITLE
两组起始时间不同的时间序列，如何画在一张图上

### ISSUE THREAD

**Issue by xlgray** [ecomfe/echarts#3075]
#### 问题简述 (One-line summary)
两组时间序列数据，一个是从2000年到2016年，一个是从2006年到2016年，想将两者画在一张折线图上。但是画完以后，二条曲线都是从最左边开始，即都从2000年开始画。有什么办法可以控制第二条曲线，使其从2006年开始画么？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
前面的数据用 `'-'` 空数据表示
