### ISSUE TITLE
sandalone markLabel support

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3078]
I often want to show some custom text inside a chart. With ECharts 3.x, it's possible to create markPoint with a custom label, but wouldn't it be better to have a standalone markLabel:{} for that purpose? Something that would support rotate, text properties and so on. 

For instance, this chart: http://echarts.baidu.com/demo.html#scatter-life-expectancy-timeline

Would just use the markLabel instead of using chart's title.

**Comment by pissang** [comment]
Thanks for the suggestion. Currently you can use markPoint and set symbol: 'none' to achieve something like markLabel

**Comment by jarben** [comment]
I see - that works!
