### ISSUE TITLE
仪表盘如何设置只显示自定义的坐标值： 比如SplitNumber是10，坐标值是0、10...100，我只需要显示50和80，其它不显示，如何设置？

### ISSUE THREAD

**Issue by hcchappy** [ecomfe/echarts#3082]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by R-River** [comment]
formatter中用余数控制。。？

**Comment by wf123537200** [comment]
splitNumber：100，//你的最大值s
axisLabel: {
                    show: true,
                    distance: 1,
                    formatter: function (value) {
                        if ([你要过滤的数组].indexOf(value) !== -1) {
                            return value;
                        }
                        else return '';
                    }
                },
