### ISSUE TITLE
echart2.2.7 在IE8中背景色变为黑色

### ISSUE THREAD

**Issue by zpfeng** [ecomfe/echarts#3088]
#### 问题简述 (One-line summary)
用IE8使用IE=edge模式异步加载数据后图表区域的背景色显示黑色。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): echart2.2.7
+ 浏览器类型和版本 (Browser version):IE8-IE10
+ 操作系统类型和版本 (OS Version):WIN7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
已经加入兼容性视图，希望开发团队能给予解决，谢谢！

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
升级到 3
