### ISSUE TITLE
如何实现断点连接和屏幕外断点的连接

### ISSUE THREAD

**Issue by starmoon1216** [ecomfe/echarts#3091]
#### 问题简述 (One-line summary)
当前使用折线图，数据源有1个月的数据(横轴为日期，精确到Day。纵轴为数据值)，数据是断断续续的。在移动端可见范围为一周，可进行滑动。
目前遇到问题有两个：
1、断点无法连接
![6510260f-6c78-4c58-a081-f00ce8820004](https://cloud.githubusercontent.com/assets/18694741/14844124/cb87764c-0c87-11e6-9f84-5f8f32a4bdbf.png)
2、超出屏幕外的数据断点无法连接
![d522ecbd-46e8-4be6-bfd9-35d441f6ada5](https://cloud.githubusercontent.com/assets/18694741/14844130/dc62cff2-0c87-11e6-86c3-f895bf7c4007.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): 微信平台及Google浏览器
+ 操作系统类型和版本 (OS Version): iOS 及 Windows 7

#### 期望结果 (Expected behaviour)
1、断点间能够连接
2、屏幕外的点能够连续

**Comment by starmoon1216** [comment]
No one knows？？  ：（

**Comment by coderfamily** [comment]
同，我也遇到这个问题了。

**Comment by pissang** [comment]
connectNulls

**Comment by coderfamily** [comment]
@pissang 谢谢回复。我遇到的问题并不是没有值不显示，是有值的情况下会出现这种
![screen shot 2016-07-06 at 10 49 58 pm](https://cloud.githubusercontent.com/assets/15377718/16622252/0b71778c-43cc-11e6-974c-625cf167237b.png)

**Comment by pissang** [comment]
这种情况就是没值

**Comment by coderfamily** [comment]
这是个 bug，5月份的时候你们修复了，用最新的就没问题。

**Comment by dayday2** [comment]
@pissang @coderfamily超出屏幕外的数据断点无法连接解决了吗？我尝试过clipOverflow没有效果

**Comment by kivet-h** [comment]
好几年了，这问题还没解决吗？我找了好久也没找到解决办法
