### ISSUE TITLE
echarts3折线图加上datazoom功能后,默认会挡住X轴的数据

### ISSUE THREAD

**Issue by hellorocky** [ecomfe/echarts#3093]
#### 问题简述 (One-line summary)
echarts3折线图加上datazoom功能后,会挡住X轴的数据,调试参数y也不管用

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):chrome50
+ 操作系统类型和版本 (OS Version):mac10.11.4

#### ECharts配置项 (ECharts option)

```
toolbox: {
        feature: {
            dataZoom: {show: true}
        }
    },
    dataZoom: {
        show: true,
        realtime: true
    }

```

#### 其他信息 (Other comments)
![image](https://cloud.githubusercontent.com/assets/7486508/14845483/1561fd56-0c91-11e6-91be-d25f3e9b3803.png)

**Comment by pissang** [comment]
设置 grid.bottom
