### ISSUE TITLE
怎么实现折线图用虚线表示

### ISSUE THREAD

**Issue by jinrogejin** [ecomfe/echarts#3095]
#### 问题简述 (One-line summary)
折线图怎么实现虚线呢  加了ITEMSTYLE  LINSTYLE  改了TYPE 没有效果呀 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.lineStyle.normal.type
