### ISSUE TITLE
柱状图可以实现背景填充吗？

### ISSUE THREAD

**Issue by monicajes** [ecomfe/echarts#3100]
#### 问题简述 (One-line summary)
柱状图一直都是颜色，现在想在柱状图上添加斜线条。echart提供什么接口实现吗？
谢谢回答！

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
创建一个 canvas 的 pattern 然后设置到 `itemStyle.normal.color` 试试

关于 pattern 参见 https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern
