### ISSUE TITLE
请问下3.0怎么换主题，如2.0可提供多套主题

### ISSUE THREAD

**Issue by jinrogejin** [ecomfe/echarts#3105]
#### 问题简述 (One-line summary)

请问下3.0怎么换主题，如2.0可提供多套主题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/download-theme.html
