### ISSUE TITLE
Geo scaleLimit seems to be broken when zooming

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3110]
Version: 3.1.7

When scaleLimit is used: 
![image](https://cloud.githubusercontent.com/assets/561365/14882512/82bda05a-0d39-11e6-8b8c-474c2b2218e9.png)

Scatter on the map gets out of sync when zoomed: 
![image](https://cloud.githubusercontent.com/assets/561365/14882550/a6db89ca-0d39-11e6-853d-a5493ab2b353.png)

Reproducible on this sample: http://echarts.baidu.com/demo.html#scatter-world-population

**Comment by pissang** [comment]
I can't reproduce it on the example.
