### ISSUE TITLE
echarts3.0中，tooltip参数的formatter回调函数的形参与图形实例的option中的series及legend数据不一致

### ISSUE THREAD

**Issue by bo2337285** [ecomfe/echarts#3111]
#### 问题简述 (One-line summary)
echarts3.0中，tooltip参数的formatter回调函数的形参与图形实例的option中的series及legend数据不一致

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.2
+ 浏览器类型和版本 (Browser version): chrome 47.0.2526.106 m
+ 操作系统类型和版本 (OS Version): windows7

#### 重现步骤 (Steps to reproduce)
1. 创建图表参数，初始化折线图，此时参数中的series为[]
2. ajax获取数据后，把图表参数深拷贝成新对象，并且构建并插入legend和series
3. 获取图表实例，通过setOptions函数传入新图表参数，更新图表内容  ``p.s. 其中参数中的tooltip[0].formartter指向的是功能模块js中声明的一个函数``
4. 此时发现legend显示的个数与实例中option的legend[0].data长度不一致。``p.s. 少了第一项，其他项都存在并且与series一致``
5. 同时tooltips中返回的params(第一个形参)数据集合，其中的第0条数据的seriseName与原option.series[0].name也不一致。params[0].seriseName统一都变为'汇总'了。

#### 期望结果 (Expected behaviour)
tooltips中的params，option中的series及legend数据应该一致

#### 可能哪里有问题 (What went wrong)
1. legend数据不一致肯定问题出在legend渲染上了
2. tooltip中formatter形参不一致个人觉得问题出在形参上，tooltips中把第一项的seriesName替换成了'汇总'这点感觉很怪异，因为我们数据中并没有这个字符串。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

由于公司网络限制，图片上传不上去

**Comment by bo2337285** [comment]
出现频率为偶现

**Comment by bo2337285** [comment]
问题解决了，通过实例setOption()时方法并不会完全更新图表内容，必须得先clear()之后才把上次渲染内容清除干净

**Comment by ZiSeFeng** [comment]
heroLineData.clear();
option.xAxis[0].data = x_data;
option.legend[0].data = legend;
为什么option.legend[0].data读取不到这个值
