### ISSUE TITLE
请问下现在有没有关于3.0版的bmap部分文档

### ISSUE THREAD

**Issue by redrum1900** [ecomfe/echarts#3116]
#### 问题简述 (One-line summary)

请问下现在有没有关于3.0版的bmap部分文档，和相关配置项说明，我看例子上有bmap部分配置，是否还有其他参数

**Comment by pissang** [comment]
bmap主要配置就是 `center`, `zoom`, `mapStyle`。

更多自定义的可以通过 `chart.getModel().getComponent('bmap').getBMap()` 获取百度地图实例后设置

**Comment by redrum1900** [comment]
看了点资料，还有pissang的支持大概弄清楚了
1.首先引入echarts.js,bmap.js,百度api。前两个在dist中可以找到，api需要去百度申请key
2.option中加入bmap，设置一些参数，此时不需要再添加geo，然后series中的coordinateSystem设置为bmap，这样就可以生成地图
3.如果再添加其他方法就需要通过`chart.getModel().getComponent('bmap').getBMap()`获取百度地图实例，然后参考[百度api](http://developer.baidu.com/map/reference/index.php?title=Class:%E6%80%BB%E7%B1%BB/%E6%A0%B8%E5%BF%83%E7%B1%BB)

**Comment by zzswang** [comment]
@redrum1900 多谢

**Comment by HuanMeng0** [comment]
mapStyle.StyleJson 可以通过官方的工具生成，可以导入已有的官方模板。
http://lbsyun.baidu.com/custom/
