### ISSUE TITLE
导入china.js,实用中国地图，“南沙诸岛”四个字乱码。详情见如下，十万火急

### ISSUE THREAD

**Issue by likejian01** [ecomfe/echarts#3117]
head
<script type="text/javascript" src="echarts.js" charset="uft-8"></script>	   
<script type="text/javascript" src="china.js"  charset="utf-8"></script>	

in the body,there are  only one div 
<div id="container" ></div> 
show the place “南沙诸岛” with wrong words

who can tell me what's wrong with it? wait online ........
i guess that it maybe something wrong with china.js。 open china.js there are no “南沙诸岛”.where differe from others.

**Comment by pissang** [comment]
设置页面为 UTF-8 编码

**Comment by likejian01** [comment]
哥哥，改了也不行啊。能试过的都试过了
