### ISSUE TITLE
关系图layout设为none 不能拖动节点

### ISSUE THREAD

**Issue by jsyhj1234** [ecomfe/echarts#3121]
#### 问题简述 (One-line summary)

关系图layout设为none 能不能拖动节点

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by jsyhj1234** [comment]
怎么没人回答

**Comment by pissang** [comment]
draggable 是为力引导布局设的配置项
