### ISSUE TITLE
echart图表bug

### ISSUE THREAD

**Issue by xubing18611808315** [ecomfe/echarts#3122]
http://echarts.baidu.com/echarts2/doc/example/line6.html
此图使用了 以下函数进行数量单位的重新定义：
       formatter: function(params) {
            return params[0].name + '<br/>'
                   + params[0].seriesName + ' : ' + params[0].value + ' (m^3/s)<br/>'
                   + params[1].seriesName + ' : ' + -params[1].value + ' (mm)';
        }
但是如果将某一个legend项使用鼠标单击取掉之后，图表将不能使用，console报错；

**Comment by realeve** [comment]
```
formatter: function(params) {
              var len = params.length;
           if( 2 == len){
              return params[0].name + '<br/>'
                   + params[0].seriesName + ' : ' + params[0].value + ' (m^3/s)<br/>'
                   + params[1].seriesName + ' : ' + -params[1].value + ' (mm)';
           }else  if( 1 == len){
               return params[0].name + '<br/>'
                   + params[0].seriesName + ' : ' + params[0].value +( (params[0].seriesName == '流量') ? ' (mm)':' (m^3/s)')
           }
        }
```

这个是formatter没写好的问题，跟eCharts没关系。另外，eCharts3也是同样的问题：
[http://echarts.baidu.com/demo.html#area-rainfall](http://echarts.baidu.com/demo.html#area-rainfall)

**Comment by xubing18611808315** [comment]
好的，谢谢解决！
