### ISSUE TITLE
做饼图展示，饼图默认只展示value为0的那个数据项

### ISSUE THREAD

**Issue by yuzl919** [ecomfe/echarts#3128]
#### 问题简述 (One-line summary)
做饼图展示，当有数据项为0时，饼图默认只展示value为0的那个数据项，当鼠标移过的时候，才会显示value不为0的数据项，只有把value为0的数据项排在最前，才会正常展示。另外，直接把官网的实例搬到工程里面去也会出现这样的情况，不知道应该如何解决？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts3.1.7
+ 浏览器类型和版本 (Browser version):IE8
+ 操作系统类型和版本 (OS Version):WIN7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
tooltip : {
            trigger:'item',
            formatter:"{a}<br>{b}:{c}条({d}%)"
        },
        legend : {
            orient:'vertical',
            x:'left',
            data : [ '待许可','待终结','已终结']
        },
        series : [
            {
                name : '抢修单情况',
                type : 'pie',
                data :[{"name":"待许可","value":"1"},{"name":"已终结","value":"2"},{"name":"待终结","value":"0"}]
            }
        ]
}

```

#### 其他信息 (Other comments)

![1](https://cloud.githubusercontent.com/assets/16153932/14976888/34288e8e-1142-11e6-8bf8-d92ef31f0540.png)

**Comment by yuzl919** [comment]
圆环也会出现这个问题，能否尽快回复，项目急等

**Comment by pissang** [comment]
已提交修复，下周新版本不会再存在这个问题

**Comment by yuzl919** [comment]
新版本什么时候提供下载更新？

**Comment by atlas1119** [comment]
ie8 下这个问题还有啊，

- [ ] 
![57a91ebf46a93df2d11f24bf13f6c4c2](https://cloud.githubusercontent.com/assets/9478646/24576466/d977a80e-16ee-11e7-801e-bb4beeef9ccd.png)
