### ISSUE TITLE
仪表盘如何显示自己需要的数字？

### ISSUE THREAD

**Issue by sin911** [ecomfe/echarts#3131]
比如这个示例http://echarts.baidu.com/demo.html#gauge
现在是默认显示了0,10,20,30,40,50,60,70,80,90,100
但是我只想显示6,32,48,89这种自定义的数字，求教大神该怎么办呢？

我试过这个interval:0，但是无效的。我尝试下来，interval:0只能在有x轴的地方，像仪表盘这种没有x轴的，该怎么办？谢谢

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-gauge.axisLabel.formatter

**Comment by sin911** [comment]
多谢大神帮助

**Comment by QAQLiuCong** [comment]
怎么显示的自定义的数字？formatter 返回的都是固定的数字，我想直接显示几个数

**Comment by Sinosaurus** [comment]
```js
  axisLabel: {            
     formatter(value) {
	// 显示指定数字
         if (value === 1 || value === 2) return value
      }
   }
```
