### ISSUE TITLE
【建议】series[i]-line.sampling增添一个选项为极值，同时保留max和min的点

### ISSUE THREAD

**Issue by waterwoodwind** [ecomfe/echarts#3132]
#### 问题简述 (One-line summary)
在实际的设备监控中，运用传感器参数绘图，对于曲线在某个点的极大值和极小值，都是很重要的，而往往这种突变又只发生在极短的时间。
在采取sampling降采样后，
选项‘sum‘将值放大太多用不上
选项‘max’能画出极大值，但极小值就看不到了
选项‘min’能画出极小值，极大值又会隐藏很多
选项‘average’比较中庸，整体曲线变得扁平，也不利于观察某几个点的突变

故希望能增添一个选项，同时保留住最大值和最小值，保持曲线的极值特征

#### 版本信息

echarts： 3.1.2以上

**Comment by waterwoodwind** [comment]
不使用sampling：
![no sampling](https://cloud.githubusercontent.com/assets/10074233/14983106/952c4998-116d-11e6-8076-17a138e7cce5.png)

使用sampling：
'average'：
![avarge](https://cloud.githubusercontent.com/assets/10074233/14983129/c6c90392-116d-11e6-8e5d-1c6fbffae386.png)

'max':
![max](https://cloud.githubusercontent.com/assets/10074233/14983136/d7f2141a-116d-11e6-86fb-dfd38e05127e.png)

'min':
![min](https://cloud.githubusercontent.com/assets/10074233/14983143/e0eab32e-116d-11e6-9eaa-7cabe6d3d01b.png)

**Comment by pissang** [comment]
sampling 可以自定义为一个函数，
例如：
```js
sampling: function (frame) {
  // 返回最近一个值
  return frame[0]
}
```

**Comment by waterwoodwind** [comment]
@pissang 解决了，谢谢。
自己构造了个函数，以0为基准，返回与0的差值绝对值最大的一个点

**Comment by jccode** [comment]
@pissang 这个 `sampling` 的函数能返回两个值吗? 比如 min, max 都同时返回?
