### ISSUE TITLE
官网实例 3版本中坐标轴设定max失效

### ISSUE THREAD

**Issue by r4nqian** [ecomfe/echarts#3140]
http://echarts.baidu.com/demo.html#bar-stack 
给yAxis 设定最大值
yAxis : [
        {
            type : 'value',
            max:1500
        }
    ]
BUT，数据柱子冒出grid外面了什么鬼

**Comment by rikan** [comment]
确实有这问题. 折线图如果设置了最大值,超过最大值的都不显示了,鼠标放上去显示真实值.echart2 是显示在最大值上 .echart2 这种方式更适合

http://echarts.baidu.com/demo.html#dynamic-data2
yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        },
        max:1000
    },
