### ISSUE TITLE
Echarts实例中第三个嵌套饼图图例显示不正确

### ISSUE THREAD

**Issue by delication** [ecomfe/echarts#3143]
#### 问题简述 (One-line summary)

Echarts实例中第三个嵌套饼图图例显示不正确，第二个数据列的图例仅显示图例名字，不显示图例颜色。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

Echarts网站实例
#### 重现步骤 (Steps to reproduce)
1.
2.

#### 可能哪里有问题 (What went wrong)

是否是最近的升级调整导致出现的错误？

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
嗯，3.1.7 中出现的bug，已经修复
