### ISSUE TITLE
Echart2.2 多次setOption内存消耗持续上涨

### ISSUE THREAD

**Issue by lanyudhy** [ecomfe/echarts#3144]
在Echart使用过程中，需要多次重新根据最新数据重新渲染图表，那么在调用setOption时，图表所消耗的内存持续的增长，请问解决方案关键点在哪？

ECharts 版本 2.2
浏览器 Chrome 46.0.2490.80 /  IE8
Win7

同一数据，定时setOption()即可重现问题

@Kener-林峰

**Comment by arrinhzh** [comment]
请问这个问题解决了吗？用了dispose()方法，但是内存还是在上升，有办法稳定吗？
