### ISSUE TITLE
希望提供无数据提示

### ISSUE THREAD

**Issue by misszhangxy** [ecomfe/echarts#3145]
#### 问题简述 (One-line summary)

使用过程中发现echarts3将原先的无数据提示去掉了，替代的是一个空的坐标系。希望能够添加无数据提示的方法。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by yzxFox** [comment]
有提供吗？

**Comment by Professor-Z** [comment]
官方也太不关心诉求啦

**Comment by pissang** [comment]
可以自己判断场景中是否是无数据然后显示需要的无数据页面，我们觉得强制在 echarts 中判断并不合适所以去掉了
