### ISSUE TITLE
wkhtmltopdf导出网页为pdf时无法显示echarts图表

### ISSUE THREAD

**Issue by baisusua** [ecomfe/echarts#3146]
#### 问题简述 (One-line summary)
将一个带有echarts图表的网页使用wkhtnktopadf导出为pdf时图表不显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.7
+ 浏览器类型和版本 (Browser version):无浏览器（wkhtmltopdf：0.12.3）
+ 操作系统类型和版本 (OS Version):mac 10.11.4

#### 重现步骤 (Steps to reproduce)
1.wkhtmltopdf test.html test.pdf

**Comment by rikan** [comment]
html to pdf.  not javascript to pdf.

**Comment by helloworld0000** [comment]
我也是一样的问题，请问解决了么

**Comment by boolak** [comment]
请问有解决吗

**Comment by whapply** [comment]
请问解决了吗？

**Comment by RanX12** [comment]
> 请问解决了吗？

。。。请问有解决吗？

**Comment by marin1995** [comment]
> > 请问解决了吗？
> 
> 。。。请问有解决吗？

遇到了同样的问题，是wkhtmltopdf 不支持es6语法，模板中的let 语法需要改成var
