### ISSUE TITLE
图例无法对其文字问题

### ISSUE THREAD

**Issue by TonyXY** [ecomfe/echarts#3148]
#### 问题简述 (One-line summary)
图表的图例相对于文字都偏上使图表不够美观，求解决！！

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):windows

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
图表的图例相对于文字居中对齐

#### 可能哪里有问题 (What went wrong)
legend源码问题，此处直接除以2可能不妥
![image](https://cloud.githubusercontent.com/assets/5823959/15037426/853b7e1c-12cd-11e6-9872-d35f30b68aac.png)

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![qq 20160505140814](https://cloud.githubusercontent.com/assets/5823959/15037161/26949012-12cb-11e6-806f-cd0ee98fcd32.png)

**Comment by realeve** [comment]
还需要减去fontSize/2

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/2819
