### ISSUE TITLE
饼图类型过多时出现问题

### ISSUE THREAD

**Issue by happykou** [ecomfe/echarts#3149]
#### 问题简述 (One-line summary)
当类型为12个的时候，第12个类型始终为黑色并且点击事件无效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.5
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):mac os

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/19201167/15037441/aed335c6-12cd-11e6-8f94-9b3cf7e6a6df.png)

**Comment by realeve** [comment]
自定义option.color数组。或者在theme里面定义超过你可能的lengend的颜色

**Comment by netwww1** [comment]
> 自定义option.color数组。或者在theme里面定义超过你可能的lengend的颜色

legend不是在theme的color数组里循环取色么？
