### ISSUE TITLE
geojson相关问题

### ISSUE THREAD

**Issue by langzixin** [ecomfe/echarts#3150]
1、是否能提供带公路网和铁路主干网的中国geojson文件
2、通过http://geojson.io为相关区域着色，导出带颜色信息的geojson文件，在echarts加载后，为何未能显示颜色

谢谢

**Comment by pissang** [comment]
1. 我们只提供常用的geoJson文件，其它的可以自行寻找
2. 暂时不支持 geoJson 的颜色信息
