### ISSUE TITLE
requirejs 中使用中国地图map

### ISSUE THREAD

**Issue by xwillmadeit** [ecomfe/echarts#3154]
requirejs 中引入了两个版本的 echarts 2 和 3
2是通过package 引入的，3是通过  paths 引入
现在想在3中增加地图， 需引入 china.js
但引入后发现 china.js 中 ECharts Map is not loaded
echarts.js 中 Map  not exists
查看源码 echarts3 在 china 之前加载，请问这怎么处理

**Comment by pissang** [comment]
引入地图组件
