### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by tuntuntunwu** [ecomfe/echarts#3159]
#### 问题简述 (One-line summary)
关于echarts.dispose（）函数，echarts3相对于echarts2来说函数接口更简洁，也更单一，所以遵从这样的设计思想，个人感觉既然已经有了echartsInstance.dispose（）函数，那么echarts.dispose（）这个函数就有点多余...多余...多余...

**Comment by pissang** [comment]
`echarts.dispose`可以传入实例所在的 dom，实例的 id，在实例分散自己可能无法直接获取的时候使用会相对比较方便。
