### ISSUE TITLE
echarts3.0 geojson问题

### ISSUE THREAD

**Issue by langzixin** [ecomfe/echarts#3166]
请问除了echarts官网提供的geojson外，是否有工具能够制作出个性化的geojson地图，请指导一下，谢谢

例如：
![image](https://cloud.githubusercontent.com/assets/18409268/15108497/cef19ca6-1608-11e6-962e-eb2bb0238d4e.png)

**Comment by pissang** [comment]
可以自行寻找geoJson的编辑工具
