### ISSUE TITLE
Echars散点图在数据量为250多万时直接崩溃

### ISSUE THREAD

**Issue by xiaozhangbadao** [ecomfe/echarts#3167]
#### 问题简述 (One-line summary)
Echars散点图在数据量为250多万时直接崩溃，在charts.setOption(opt)时执行时间过长，浏览器崩溃

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.7
+ 浏览器类型和版本 (Browser version):Google Chrome 38.0.2125.104 m
+ 操作系统类型和版本 (OS Version):Windows10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
series:{'name':'','type':'scatter','data':[[],[],[],[]...250多万个]}
}

```

**Comment by pissang** [comment]
太多了，需要先过滤一下数据，建议把数据量控制在10w以内

**Comment by hurryzeng** [comment]
建议控制数量……这样也可以关bug？不用心啊
