### ISSUE TITLE
Issue when hovering over map region

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3171]
There is an issue when hovering over map that is contained inside another region. Seems like regression as it was working in ECharts 2.x.

Example (ECharts 3.1.7):
![map-hover](https://cloud.githubusercontent.com/assets/561365/15113549/4164e496-15f5-11e6-8db5-9687535ba534.gif)

Note that "Praha" region can't be selected on hover as soon as another region is already hovered. 

Example (ECharts 2.x)
![map-hover-echarts2](https://cloud.githubusercontent.com/assets/561365/15113582/7245196e-15f5-11e6-9b6f-e86ce321b6c6.gif)

This example works as expected. 

GeoJSON used: https://gist.githubusercontent.com/jarben/6fe145bc8db35063638060666a3118cf/raw/dba59a4e186ef54e97ae541e69ed276582d7a818/czech_geo_example

**Comment by jarben** [comment]
Any chance to fix this one @pissang?

**Comment by pissang** [comment]
Hi @jarben, I will try to locate the problem.

**Comment by jarben** [comment]
Thank you @pissang, looks like the mouseenter can't be triggered without mouseleave from previous region? Which happens when region is nested.. Thanks for looking at it..

**Comment by jarben** [comment]
Sorry @pissang, any update on this one?

**Comment by pissang** [comment]
Hi @jarben. It's a "point in path" bug in zrender. Fixed it and it will be right in next version. Sorry for the late replay

**Comment by jarben** [comment]
Hi @pissang , that's great this is fixed now, thanks heaps!
