### ISSUE TITLE
Emphasis style on map areas 

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3173]
Emphasis style on map areas is defined as color in the default theme. This means that I'm not able to change border color only and leave area color same as normal style. 

What would be great is having something similar to outRange/inRange where you can define changes such as hue, color apha etc. For example, it would be great if emphasis is defined as colorLightness + 10% of normal state. Something like inSelection/outSelection?

**Comment by pissang** [comment]
Default emphasis color can be removed by set it null. And echarts will use the color increased lightness as emphasis color.
```js
itemStyle: {
  emphasis: {
       areaColor: null
  }  
}
```

**Comment by jarben** [comment]
Nice! Thanks heaps!

**Comment by KrzysztofMadejski** [comment]
`areaColor: null` option should be documented in https://echarts.apache.org/en/option.html#series-map.emphasis.itemStyle.areaColor
