### ISSUE TITLE
建议扩展K线图功能，底部增加关于主力资金净流入的柱形图体现

### ISSUE THREAD

**Issue by 54zzb** [ecomfe/echarts#3175]
问题简述 (One-line summary)

建议扩展K线图功能，底部增加关于主力资金净流入的柱形图体现。

希望能够推出主力资金净流入和股价的柱形图和蜡烛图的整合，K线图只是体现了股价的蜡烛图呈现，但是缺乏了主力资金净流入底部柱形图体现，funsionchar就有这方面的功能，希望组件日后能够增加这个功能。例如http://www.fusioncharts.com/charts/candlestick-charts/

 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):Echart3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win10

**Comment by pissang** [comment]
echarts 支持混搭，你可以再加一个柱状图的 series
