### ISSUE TITLE
内容格式器，能不能自定义样式

### ISSUE THREAD

**Issue by jxffly** [ecomfe/echarts#3182]
就是
![image](https://cloud.githubusercontent.com/assets/13530640/15170058/ccbc87e4-1774-11e6-88f4-8ce2f6ee1a2c.png)
我可以让数字和上面的字的颜色和字体大小都不一样，可以吗，
但是我目前发现只能统一设定样式，
![image](https://cloud.githubusercontent.com/assets/13530640/15170096/33aacb64-1775-11e6-897b-e177314ff883.png)

能不能自己定义一段html样式，由echart代为转化

**Comment by pissang** [comment]
不能
