### ISSUE TITLE
Sankey node's color can't be changed

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3186]
Just noticed that color of a node inside sankey diagram can't be changed:

![image](https://cloud.githubusercontent.com/assets/561365/15184057/0de1974a-1794-11e6-99b1-46a4665887d2.png)

setting color:"#ffffff" doesn't have any effect as described in the docs.

**Comment by pissang** [comment]
Sankey diagram can't set a unique color in `series.itemStyle.normal.color` since each node needs to be encoded different color. Instead you can using a color palette like fowllowing

```js
series: [{
  type: 'sankey',
  color: ['#fff']
}]
```

**Comment by jarben** [comment]
I still think it should be possible to use colors for individual items (as defined in the docs). Using palette means that color order matches nodes order in the sankey diagram + number of colors would need the be the same as number of nodes (if we want to match exact color). 

In this example, each category (Business, Materials,.. ): 

![image](https://cloud.githubusercontent.com/assets/561365/15204657/01a905fe-1810-11e6-97a0-04c50e5e7a65.png)

has its own color which is hard to set using color palette, considering there are variable number of countries on the right. 

If color can be set on individual nodes, this should be easy + it would be consistent with other charts too. At least make this as enhancement?

**Comment by pissang** [comment]
Agree with that. Setting `itemStyle.normal.color` in each node has been supported in commit https://github.com/ecomfe/echarts/commit/d0a171ff2a94542bc95eb4e0785e1f3022c37549

**Comment by jarben** [comment]
This is awesome @pissang thanks heaps!
