### ISSUE TITLE
Sankey: custom tooltip formatter issue

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3194]
I'm getting incorrect tooltips when using custom formatters in sankey diagram, for example: 

![image](https://cloud.githubusercontent.com/assets/561365/15212862/9110214a-1843-11e6-8824-eb6d6ebb84db.png)

Shows "West Bank" where it show either "Mobility & Transportation" or "Austria". 
Similar issue happens when using function(){} as a formatter. 

What is also interesting and potentially related is that when I resize the viewport, countries get reverted: 
![image](https://cloud.githubusercontent.com/assets/561365/15213069/1d800b62-1845-11e6-99a7-9a8e642c21df.png)

If I sort links array in code, it shows issues when hovering over different links. 

Here is the testing code with my sample data: 
[sankey-tooltip-issues.zip](https://github.com/ecomfe/echarts/files/261165/sankey-tooltip-issues.zip)

**Comment by pissang** [comment]
It seems tooltip mistakenly use the node data instead of edge data.
