### ISSUE TITLE
请教：echarts-x 3d 地球 中国区域怎么区分中国台湾、中国香港、大陆？

### ISSUE THREAD

**Issue by BigBangG** [ecomfe/echarts#3198]
#### 问题简述 (One-line summary)
echarts-x 3d 地球 中国区域怎么区分中国台湾、中国香港、大陆？

#### 版本及环境 (Version & Environment)
echarts-x-0.2.0

**Comment by pissang** [comment]
使用自定义的  geoJson

**Comment by BigBangG** [comment]
@pissang 能具体点吗，感谢！

**Comment by phping1** [comment]
@BigBangG ,问题解决了没？我也遇到同样的问题，请教一下。
