### ISSUE TITLE
增加数据表格显示的功能建议

### ISSUE THREAD

**Issue by oxiao** [ecomfe/echarts#3204]
![image](https://cloud.githubusercontent.com/assets/10287324/15242660/08e40f74-192a-11e6-90a7-db09bc19676c.png)
客户在实际使用中要求打印图与表合并显示的情况，可否添加此功能？

**Comment by sevenvsky** [comment]
那么最后这里怎么做呢？

**Comment by chfw** [comment]
looks like a cool use case.

**Comment by alaahong** [comment]
大家怎么处理这种需求的呢？
只格式化横坐标的话，简单的内容还好，一旦加了首列和样式就繁琐了。手工控制一个平级div的话，处理样式也是问题。
