### ISSUE TITLE
使用dataZoom缩放时，markPoint会被挤到一边而不隐藏

### ISSUE THREAD

**Issue by plusice** [ecomfe/echarts#3205]
#### ECharts配置项 (ECharts option)
```javascript
option = {
    tooltip : {
        trigger: 'axis'
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataZoom : {show: true},
            dataView : {show: true},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    dataZoom : {
        show : true,
        realtime : true,
        y: 36,
        height: 20,
        start : 0,
        end : 30
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : function (){
                var list = [];
                var n = 0;
                while (n++ < 10) {
                    list.push(n);
                }
                return list;
            }()
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'dz',
            type:'line',
            data:function (){
                var list = [];
                for (var i = 1; i <= 10; i++) {
                    list.push(Math.round(Math.random()* 30));
                }
                return list;
            }(),
            markPoint: {
                data: [
                    {name: '标注1', value: 100, xAxis: 0, y: 120},
                    {name: '标注2', value: 200, xAxis: 1, y: 220},
                    {name: '标注1', value: 100, xAxis: 2, y: 300},
                    {name: '标注2', value: 200, xAxis: 3, y: 220},
                    {name: '标注1', value: 100, xAxis: 4, y: 120},
                    {name: '标注2', value: 200, xAxis: 5, y: 220},
                    {name: '标注1', value: 100, xAxis: 6, y: 300},
                    {name: '标注2', value: 200, xAxis: 7, y: 220},
                ]
            }
        }
    ],
    calculable:false
};

```

#### 其他信息 (Other comments)
![16xe3 m2v m6z4e 6 2zr5](https://cloud.githubusercontent.com/assets/3931895/15242670/1530378a-192a-11e6-8227-e716af663678.png)

**Comment by pissang** [comment]
使用 3

**Comment by Miller547719886** [comment]
想请问这个问题解决了吗？

**Comment by Miller547719886** [comment]
想请问这个问题解决了吗？

**Comment by Miller547719886** [comment]
想请问这个问题解决了吗？

**Comment by jackchoumine** [comment]
> #### 使用dataZoom缩放时，markPoint会被挤到一边
> #### 能不能让markPoint直接隐藏
> #### 版本ECharts 2
> #### ECharts配置项 (ECharts option)
> option = {
>     tooltip : {
>         trigger: 'axis'
>     },
>     toolbox: {
>         show : true,
>         feature : {
>             mark : {show: true},
>             dataZoom : {show: true},
>             dataView : {show: true},
>             magicType : {show: true, type: ['line', 'bar']},
>             restore : {show: true},
>             saveAsImage : {show: true}
>         }
>     },
>     dataZoom : {
>         show : true,
>         realtime : true,
>         y: 36,
>         height: 20,
>         start : 0,
>         end : 30
>     },
>     xAxis : [
>         {
>             type : 'category',
>             boundaryGap : false,
>             data : function (){
>                 var list = [];
>                 var n = 0;
>                 while (n++ < 10) {
>                     list.push(n);
>                 }
>                 return list;
>             }()
>         }
>     ],
>     yAxis : [
>         {
>             type : 'value'
>         }
>     ],
>     series : [
>         {
>             name:'dz',
>             type:'line',
>             data:function (){
>                 var list = [];
>                 for (var i = 1; i <= 10; i++) {
>                     list.push(Math.round(Math.random()* 30));
>                 }
>                 return list;
>             }(),
>             markPoint: {
>                 data: [
>                     {name: '标注1', value: 100, xAxis: 0, y: 120},
>                     {name: '标注2', value: 200, xAxis: 1, y: 220},
>                     {name: '标注1', value: 100, xAxis: 2, y: 300},
>                     {name: '标注2', value: 200, xAxis: 3, y: 220},
>                     {name: '标注1', value: 100, xAxis: 4, y: 120},
>                     {name: '标注2', value: 200, xAxis: 5, y: 220},
>                     {name: '标注1', value: 100, xAxis: 6, y: 300},
>                     {name: '标注2', value: 200, xAxis: 7, y: 220},
>                 ]
>             }
>         }
>     ],
>     calculable:false
> };
> #### 其他信息 (Other comments)
> ![16xe3 m2v m6z4e 6 2zr5](https://cloud.githubusercontent.com/assets/3931895/15242670/1530378a-192a-11e6-8227-e716af663678.png)

希望用户在滚动横坐标滑块的时，动态隐藏或者显示 markPoint，如何办到吗？
