### ISSUE TITLE
echarts的图例图标与文字不对齐

### ISSUE THREAD

**Issue by yuyanping39** [ecomfe/echarts#3214]
#### 问题简述 (One-line summary)
echarts的图例图标与文字不对齐

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts3所有版本
+ 浏览器类型和版本 (Browser version):chrome50.0.2661.102 m
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
直接看官网实例

#### 期望结果 (Expected behaviour)
图例图标与文字中间对齐

#### 可能哪里有问题 (What went wrong)
画图例文字时没有设置居中属性

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by yuyanping39** [comment]
为什么直接关闭了 至少给个回复吧

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/2819
