### ISSUE TITLE
3.0中如何获取地图中各市的数据？

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#3215]
#### 问题简述 (One-line summary)
在例子中 http://echarts.baidu.com/gallery/editor.html?c=scatter-map 使用了geoCordMap来映射某些市的地理位置，但是并不完整。从哪里可以获取到全部市的地理位置信息？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://ecomfe.github.io/echarts-map-tool/
