### ISSUE TITLE
请问graph图tooltip的formatter字符串模板是什么？

### ISSUE THREAD

**Issue by carl0224** [ecomfe/echarts#3216]
#### 问题简述 (One-line summary)
在graph图中设置option的tooltip为tooltip:{}可以正常显示节点信息和边界信息，但是我想个性化tooltip信息，如何通过formatter字符串模板设置边界信息？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.9
+ 浏览器类型和版本 (Browser version):Chrome 49.0.2623.110 m
+ 操作系统类型和版本 (OS Version):win7旗舰版

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
3.1.9 中 graph tooltip 的 formetter 有问题，无法获取边的数据，https://github.com/ecomfe/echarts/issues/3194 中已修复
