### ISSUE TITLE
graph图links文档错误

### ISSUE THREAD

**Issue by xubuild** [ecomfe/echarts#3222]
#### 问题简述 (One-line summary)
http://echarts.baidu.com/option.html#series-graph.links
```
links: [{
    source: 'n1',
    target: 'n2'
}, {
    source: 'n2',
    target: 'n3'
}]
```
文档描述source和target为边的源节点名称，但从实例可以看出，实际上需要源节点id。实际测试也是需要源节点id而不是name，且源节点id要为string而不是数字。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.9
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
这是 echarts 3 的文档，你用的还是 2.1.9 的版本

**Comment by xubuild** [comment]
不好意思打错了，用的是3.1.9

**Comment by pissang** [comment]
id 和 name 都是可以的，只不过有 id 的时候回优先取 id
