### ISSUE TITLE
直角坐标系的原点能否变换位置，比如从左上角开始

### ISSUE THREAD

**Issue by Jerry-goodboy** [ecomfe/echarts#3224]
#### 问题简述 (One-line summary)
直角坐标系的原点能否变换位置，比如从左上角开始，类似这种

////////////////////////////////////////////////////////////////////////////////////////////////////

0(坐标原点)   20                  40                  60
-------------------|------------------|------------------|------------------> （X轴）
|                
|
|
|
|
|
v
（Y轴）

////////////////////////////////////////////////////////////////////////////////////////////////////

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): OS X 10.11.4

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

////////////////////////////////////////////////////////////////////////////////////////////////////

0(坐标原点)   20                  40                  60
-------------------|------------------|------------------|------------------> （X轴）
|                
|
|
|
|
|
v
（Y轴）

////////////////////////////////////////////////////////////////////////////////////////////////////

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
```js
yAxis: { inverse: true }
```

**Comment by Jerry-goodboy** [comment]
@pissang 不管用，我在我自己的项目里测试了，echarts的文档关于这个选项的只有竖图中可以用这个一条，我感觉echarts的坐标系本身就不支持这个功能

**Comment by pissang** [comment]
echarts 3 支持

**Comment by Jerry-goodboy** [comment]
OK，谢谢@pissang ，我去试试
