### ISSUE TITLE
echart3在ie下内存溢出（发生在tooltip的type为dashed或dotted时）

### ISSUE THREAD

**Issue by colvv** [ecomfe/echarts#3225]
echarts3在ie下 tooltip 会存在一直内存溢出情况。 

+ ECharts 3.1.9
+ 浏览器类型 IE10，9:
+ 操作系统类型和版本 (OS Version): Win7 64以及32

经过检查验证确定问题是**lineStyle**，type为dashed和dotted均会触发内存溢出

错误提示为：SCRIPT14: 存储空间不足，无法完成此操作。

下附配置代码：
 ```
tooltip: {
                trigger: "axis",
                axisPointer: {
                    type: 'line',
                    lineStyle: {
                        type: 'dashed' //<<<----- this is the problem
                    }
                }
            }
```

**Comment by pissang** [comment]
可能是这个问题导致的 https://github.com/ecomfe/zrender/pull/194
