### ISSUE TITLE
修改线条颜色，legend线条以及详情中未同步修改颜色

### ISSUE THREAD

**Issue by alenyu** [ecomfe/echarts#3232]
![code](https://cloud.githubusercontent.com/assets/4666868/15346107/37ecf2a2-1ce7-11e6-9ad3-8cd057a63a0e.png)

![qq 20160518104232](https://cloud.githubusercontent.com/assets/4666868/15346109/40bb5afe-1ce7-11e6-8ba0-b3438c2b80d7.png)

![qq 20160517175210](https://cloud.githubusercontent.com/assets/4666868/15346111/47ce7df8-1ce7-11e6-9515-c976a34acb9e.png)

**Comment by alenyu** [comment]
能否给一个例子，改变线条颜色，同时图例的线条颜色和详情中圆点的颜色同时修改？

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/3227 不要重复开两个相同的问题

**Comment by alenyu** [comment]
能给个例子吗？

**Comment by alenyu** [comment]
itemStyle设置后并非我想要的结果

**Comment by alenyu** [comment]
你好，3227中解答说itemStyle可以设置，我试了之后是不行的，只能改变线条中圆圈的颜色，我需要同时改变三个地方的颜色，能给个例子吗？谢谢

**Comment by alenyu** [comment]
series中设置itemStyle已经ok，谢谢
