### ISSUE TITLE
折线图使用setOption时在IE8上会出现线条溢出的问题

### ISSUE THREAD

**Issue by chenboxin** [ecomfe/echarts#3236]
#### 问题简述 (One-line summary)
折线图使用setOption时在IE8上会出现线条溢出的问题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.9
+ 浏览器类型和版本 (Browser version):IE8
+ 操作系统类型和版本 (OS Version):Windows7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
IE8 下折线图建议关闭动画
