### ISSUE TITLE
markPoint  自定义数据带小数，但是图标显示整数

### ISSUE THREAD

**Issue by lixuda** [ecomfe/echarts#3237]
#### 问题简述 (One-line summary)
在k线图表里面，markPoint  自定义数据带小数，但是图标显示整数
在散点图标正常。
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by lixuda** [comment]
已解决

**Comment by lingjiaquan** [comment]
请问怎么解决的？
