### ISSUE TITLE
请问echarts 3.x 是否可以挪动Y轴显示数据的位置？

### ISSUE THREAD

**Issue by Jackie-Web** [ecomfe/echarts#3239]
请问如何把Y轴的数字部分挪到charts内侧来显示？ 在官方的API里没有找到可以挪动Y轴数据的方法。

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#yAxis.axisLabel.inside

**Comment by Jackie-Web** [comment]
谢谢~
