### ISSUE TITLE
请问 echarts 3 中的字符云图什么时候能添加上？

### ISSUE THREAD

**Issue by zhangjunah** [ecomfe/echarts#3241]
请问 echarts 3 中的字符云图什么时候能添加上？

**Comment by zhangjunah** [comment]
我们一个项目中用了 echarts 2，想升级 echarts 3，但是3中没有2中已有的字符云图， 急需啊！ 请问大概什么时候能够自持字符云？

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-wordcloud

**Comment by wang01ping** [comment]
echarts-wordcloud 的toolbox的dataView不能支持编辑词云的词汇刷新，只能编辑数值大小进行刷新显示，有什么办法吗？最近工作中客户要求有这个功能，急<-- -->
