### ISSUE TITLE
echarts 3.x 的中文文档中：options.radar.nameGap 的解释说明有误

### ISSUE THREAD

**Issue by WeiFei365** [ecomfe/echarts#3242]
#### 问题简述 (One-line summary)

echarts 3.x 的文档有点小问题；options.radar.splitNumber 和 options.radar.shape 的说明被错误的放到了 options.radar.nameGap 的子级了；

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.9
+ 浏览器类型和版本 (Browser version): Google Chrome 50.0.2661.86 (64-bit)
+ 操作系统类型和版本 (OS Version): OS X EI Capitan 10.11.4

#### 重现步骤 (Steps to reproduce)
1. 右键，在新标签页打开官网的文档页：[http://echarts.baidu.com/option.html#radar.nameGap](http://echarts.baidu.com/option.html#radar.nameGap)
2. 查看左侧导航及右侧的详情，在 options.radar.nameGap 的子级下有四个不存在的配置项：textStyle、splitNumber、shape、scale；

#### 期望结果 (Expected behaviour)

* options.radar.nameGap.splitNumber 应该改为 options.radar.splitNumber （在实例页已经可用，只是文档说明的不对）；
* options.radar.nameGap.shape 应该改为 options.radar.shape （在实例页已经可用，只是文档说明的不对）；
* options.radar.nameGap.scale 应该改为 options.radar.scale （在实例页已经可用，只是文档说明的不对）；
* options.radar.nameGap.textStyle 该参数的功能貌似在 options.radar.name.textStyle 已经实现了；

#### ECharts配置项 (ECharts option)

测试【期望结果】中提到的参数的效果，可以右键，在新标签页打开并粘贴以下配置：[http://echarts.baidu.com/gallery/editor.html?c=radar](http://echarts.baidu.com/gallery/editor.html?c=radar)
```javascript
option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        shape: 'circle',
        splitNumber: 5,
        scale: false,
        indicator: [
           { name: '销售（sales）'},
           { name: '管理（Administration）'},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ],
        axisLabel: {
            show: true
        }
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            },
             {
                value : [5000, 14000, 28000, 31000, 42000, 21000],
                name : '实际开销（Actual Spending）'
            }
        ]
    }]
};

```

**Comment by pissang** [comment]
谢谢反馈，确实有误。正确的结构应该是

```js
name: {
  show: true,
  textStyle: {},
  formatter
},
nameGap: 15,
splitNumber: 5,
scale: false
```
