### ISSUE TITLE
echart3.0 y坐标设置inside=true的label后，与splitLine重叠，请问这个怎么解决呀？谢谢~

### ISSUE THREAD

**Issue by yj20060714** [ecomfe/echarts#3247]
#### 问题简述 (One-line summary)
你好，我想将y轴的label显示在坐标轴内侧，但是设置inside=true后，这个label与splitLine重叠了，我试了文档里的很多字段，都没能解决这个问题。
请问怎么设置，才能让内侧的label显示在splitLine的上面或下面呀？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):所有浏览器
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.设置下面的yAxis
2.直接画图即可看到

#### 期望结果 (Expected behaviour)
希望y轴内侧的label与splitLine不重叠，而是显示在splitLine的上面或下面。

#### ECharts配置项 (ECharts option)

```javascript
option = {
...
yAxis: {
            axisLabel: {
                inside:true,
                formatter: function (val) {
                    return (val+1) * 100 + '亿元';
                }
            },
            splitNumber: 3,
            splitLine: {
                show: true
            }
        },
...
}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/9796366/15414650/471a3bfc-1e6f-11e6-9496-5d7af6c31c97.png)

**Comment by pissang** [comment]
axisLabel: {
  inside: true,
  textStyle: {
    baseline: 'bottom'
  }
}

**Comment by yj20060714** [comment]
谢谢，特别感谢！
