### ISSUE TITLE
散点图中当x轴y轴都是值轴时，在3.x中最大值最小值为undefined，但是切换回2.0一切显示正常

### ISSUE THREAD

**Issue by leeyuanhe** [ecomfe/echarts#3255]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.9完整版
+ 浏览器类型和版本 (Browser version):chrome  47.0.2526.106 m
+ 操作系统类型和版本 (OS Version):windows32位 

#### 重现步骤 (Steps to reproduce)
![feedback](http://7xqtjt.com1.z0.glb.clouddn.com/2222.png)

#### 期望结果 (Expected behaviour)
**当鼠标悬停到最大值或最小值上时显示最大最小数据，而不是undefined**

#### 可能哪里有问题 (What went wrong)

这个情况在2.0版本中不存在，在2.0中最大值最小值均可正常显示，都是一样的数据，但是切换到3.0就出现了上述问题。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
因为自定义了 tooltip，需要在 tooltip 中判断鼠标悬停的是 markPoint 还是气泡点
