### ISSUE TITLE
Echarts不支持在tablet上双指控制datazoom

### ISSUE THREAD

**Issue by lorcel** [ecomfe/echarts#3256]
我有一个折线图，设置了datazoom，在电脑浏览器上跑的时候， 通过鼠标滚轮可以放大缩小，不过在tablet跑的时候，想通过双指去操作， echarts没法做到放大缩小

请问是我哪里设置错了吗？ 还是目前echarts就是不支持

 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):  Chrome
+ 操作系统类型和版本 (OS Version): Android

**Comment by 100pah** [comment]
支持，参考 <http://echarts.baidu.com/option.html#dataZoom-inside>
