### ISSUE TITLE
数据视图显示问题

### ISSUE THREAD

**Issue by xklg309** [ecomfe/echarts#3258]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (3.1.10):
+ 浏览器类型和版本 (360se 8.1.1):
+ 操作系统类型和版本 (win Version):

#### 重现步骤 (Steps to reproduce)
1.数据视图，各列不对齐
2.官网上的示例也是这样
http://echarts.baidu.com/demo.html#line-marker

#### 期望结果 (Expected behaviour)
可以考虑做成表格模式，更美观。

####截图信息 (Other comments)

http://a1.qpic.cn/psb?/V1132tyr0kfokw/mvxUgnnvov2c0D.OHGeqQ8NpdbVxxzTBF1S3n7OjhR4!/b/dKsAAAAAAAAA&bo=VgVfAgAAAAAFAC0!&rf=viewer_4&t=5
http://a1.qpic.cn/psb?/V1132tyr0kfokw/*9ecJGEIlKicjY3FZTMl6Vy*pLh7kA*W4ui9UFtK120!/b/dK4AAAAAAAAA&bo=0QJYAQAAAAAFAKk!&rf=viewer_4&t=5

**Comment by pissang** [comment]
数据视图是 tsv 格式，显示成表格无法编辑，如果有需要可以使用 [optionToContent](http://echarts.baidu.com/option.html#toolbox.feature.dataView.optionToContent) 绘制成表格
