### ISSUE TITLE
echarts 画饼图的时候会会出现白边，两个色块之间会有缝隙

### ISSUE THREAD

**Issue by ShangXinbo** [ecomfe/echarts#3262]
两个扇形之间会有白色的间隙，就是背景色，，很难看，怎么样才能去掉之间的缝隙

**Comment by pissang** [comment]
请具体描述代码，环境，截图

**Comment by ShangXinbo** [comment]
官方的demo就有这种效果，随意找一个饼图，白背景不明显，把背景色改成黑色就会出现很清晰的黑边，这里不能上传截图

**Comment by Hongmei225** [comment]
series: [
                  {
                      type: "pie",
                      radius: "65%",
                      itemStyle: {
                          normal: {
                              borderColor: '#fff',
                              borderWidth: '1'
                          },
                          emphasis: {
                              borderColor: '#fff',
                              borderWidth: '1'
                          }
                      },
...
会出现白边，borderWidth:'0'， 就会消除白边。
