### ISSUE TITLE
关系图graph的symbol设置为图片时，如果定义了symbolSize，连线显示异常

### ISSUE THREAD

**Issue by feeee** [ecomfe/echarts#3267]
关系图graph的symbol设置为图片时，如果定义了symbolSize，线会显示空白
具体见图~  图一加上symbolSize，连线没了，图二去掉symbolSize线就正常了。。
![Uploading image.png…]()
![Uploading 2.png…]()

**Comment by feeee** [comment]
图1： http://m.pvgo.com/1.png
图2： http://m.pvgo.com/2.png
github这文件上传我也是醉了~

**Comment by luozhengxuan** [comment]
我也碰到这个问题了....

**Comment by pissang** [comment]
这个应该是 symbolSize 写成数组带来的问题，下个版本优化

**Comment by zjyExcelsior** [comment]
@pissang 我也遇到了将symbolSize设为数组后，连线显示异常的问题。看来已经被修复了👍
