### ISSUE TITLE
[疑问]map类型的不能动态或者全量更新数据

### ISSUE THREAD

**Issue by cc4dogman** [ecomfe/echarts#3268]
map类型的图，如何动态的更新，如果使用样例里面的refresh，则会还原一切设置

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0
