### ISSUE TITLE
echarts3.0 1)x轴的label字体最小是12吗？可以再小吗？2)tooltip的直线指示器能像浮层（alwaysShowContent）一样一直展示吗？

### ISSUE THREAD

**Issue by yj20060714** [ecomfe/echarts#3270]
#### 问题简述 (One-line summary)
你好，我有两个问题：
1.我在移动端用echarts3.0画图，x轴的label是自动显示的，我没有设置显示几个；发现小屏手机会出现label重叠，然后我想修改label的字体大小，发现比12大生效，但比12小字体不变。。。
请问，这个字体最小是12吗？如果是的话，我怎么解决重叠问题呢？（ps:echarts自动显示x轴label，不是应该考虑重叠问题吗？）

2. 我想让tooltip的直线指示器 能像浮层的（alwaysShowContent：true）一样，一直显示；请问，有这个字段吗？

谢谢啦~

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):所有
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
1. x轴的label字体大小设置比12小的时候，能生效。
2. 希望tooltip的直线指示器，在鼠标hover出画布后，也能一直显示。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/9796366/15526473/e54128f6-2264-11e6-8aef-9bf46d541450.png)

![image](https://cloud.githubusercontent.com/assets/9796366/15526484/fa00e8c6-2264-11e6-9ab8-94b530919802.png)

**Comment by pissang** [comment]
1. 浏览器中最小字体为 12
2. 暂时不行

**Comment by yj20060714** [comment]
好的，多谢啦~
