### ISSUE TITLE
legend和visualMap的默认样式有冲突吗？

### ISSUE THREAD

**Issue by rainryu** [ecomfe/echarts#3273]
#### 问题简述 (One-line summary)

geo的散点图，设了legend和visualmap，现象上看legend的样式被覆盖了，本来应该一个红一个黑，现在全按visualmap的颜色走了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
visualMap 的优先级更高
