### ISSUE TITLE
symbol   path://path.svg引入svg文件不起作用

### ISSUE THREAD

**Issue by believeZJP** [ecomfe/echarts#3278]
#### 问题简述 (One-line summary)
markPoint: 中设置symbol: 'path://path.svg'，不起作用，不能正常显示，但svg在单独在页面中引用可以正常显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):windows

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

svg文件的图标能正常显示

#### 可能哪里有问题 (What went wrong)

svg文件解析有问题

#### ECharts配置项 (ECharts option)

```javascript
option = {
color: ['#9dc6b3'],
			tooltip: {
				trigger: 'axis',
				axisPointer: { // 坐标轴指示器，坐标轴触发有效
					type: 'shadow' // 默认为直线，可选为：'line' | 'shadow'
				}
			},
			legend: {
				data: ['数据']
			},
			grid: {
				left: '3%',
				right: '4%',
				bottom: '3%',
				containLabel: true
			},
			xAxis: [{
				type: 'category',
				data: ['APP访问', '设备操作', '煮饭']
			}],
			yAxis: [{
				type: 'value'
			}],
			series: [
				{
					name: '数据',
					type: 'bar',
					barCategoryGap: '60%',
					data: [1570, 1018, 862],
					markPoint: {
						symbol: 'path://path.svg',
//						symbol: 'roundRect',
//						symbol: 'emptyRect',
						symbolSize: 90,
						symbolOffset: [0, -85],
						data: [
							{
								name: '两个坐标之间的标线',
								coord: [0, 500]
							}, {
								coord: [1, 500]
							}
						]
					}
				}
			]
}

```

#### 其他信息 (Other comments)

<?xml version="1.0" standalone="no"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg width="100%" height="100%" version="1.1"
xmlns="http://www.w3.org/2000/svg">

<circle cx="100" cy="50" r="40" stroke="black"
stroke-width="2" fill="red"/>

</svg>

**Comment by believeZJP** [comment]
<?xml version="1.0" standalone="no"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg width="100%" height="100%" version="1.1"
xmlns="http://www.w3.org/2000/svg">

<circle cx="100" cy="50" r="40" stroke="black"
stroke-width="2" fill="red"/>

</svg>

**Comment by believeZJP** [comment]
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100%" height="100%" version="1.1"
xmlns="http://www.w3.org/2000/svg">
<circle cx="100" cy="50" r="40" stroke="black"
stroke-width="2" fill="red"/>
</svg>

**Comment by believeZJP** [comment]
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" version="1.1" xmlns="http://www.w3.org/2000/svg"> <circle cx="100" cy="50" r="40" stroke="black"
stroke-width="2" fill="red"/></svg>

**Comment by believeZJP** [comment]
svg格式的提交不了，老是自动截取

**Comment by pissang** [comment]
'image://path.svg'

path 后面跟的应该是路径字符串

**Comment by maxio-yu** [comment]
path后边是路劲字符串，那颜色怎么配置？ 官方doc中写的是：
通过 'path://' 将图标设置为任意的矢量路径。这种方式相比于使用图片的方式，不用担心因为缩放而产生锯齿或模糊，而且可以设置为任意颜色。

**Comment by surplus-cat** [comment]
svg的路径字符串是要怎么生成？
