### ISSUE TITLE
图片如何保存到剪贴板？

### ISSUE THREAD

**Issue by bi-kai** [ecomfe/echarts#3281]
#### 问题简述 (One-line summary)
生成图片后，需要下载，或者通过截图工具，再保存到word中。
有没有简便的方法，可以直接复制到剪贴板，直接粘贴到word里？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.2.7
+ 浏览器类型和版本 (Browser version):IE9+,chrome,FF
+ 操作系统类型和版本 (OS Version):win

#### 重现步骤 (Steps to reproduce)
1.属于功能需求，不涉及
2.

#### 期望结果 (Expected behaviour)
提供按钮或者API，可以直接把图复制到剪贴板中，能够方便粘贴到word里。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
直接截图工具截图表？
