### ISSUE TITLE
IE8下使用getDataURL()方法导出图表图片失败

### ISSUE THREAD

**Issue by ArigoZhang** [ecomfe/echarts#3288]
#### 问题简述 (One-line summary)
IE8下使用getDataURL导出图表图片失败，控制台输出“SCRIPT5007: 无法获取未定义或 null 引用的属性“toDataURL””

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.8
+ 浏览器类型和版本 (Browser version): IE11下使用IE8文档模式
+ 操作系统类型和版本 (OS Version): Windows 7 旗舰版 64位

#### 重现步骤 (Steps to reproduce)
1. 使用该版本echarts绘制任意图表
2. 调用getDataURL()方法生成图表图片的base64 URL，不成功。控制台报错“SCRIPT5007: 无法获取未定义或 null 引用的属性“toDataURL””

#### 期望结果 (Expected behaviour)

希望能在IE8下成功生成图表图片的base64 URL

#### ECharts配置项 (ECharts option)

```javascript
option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'line',
                data: ['10', 20, 15, '25', '20', 30]
            }]
}

```

**Comment by pissang** [comment]
IE8 不支持导出成图片

**Comment by ArigoZhang** [comment]
噢！悲剧。
