### ISSUE TITLE
echarts 地图：例如北京   设置默认缩放级别   设置地图中心点   怎么做啊？

### ISSUE THREAD

**Issue by wastef** [ecomfe/echarts#3295]
#### 问题简述 (One-line summary)
后台 给一个坐标    将当前地图放大到足够的级别，在使当前的坐标居中。

应该怎么实现呢？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
参考这个示例 http://echarts.baidu.com/gallery/editor.html?c=map-locate

**Comment by wastef** [comment]
![image](https://cloud.githubusercontent.com/assets/13346477/15604804/cf308652-2434-11e6-85b3-d1b5b00df9be.png)
我用的 城市的 做的底图 ,  而且地图边界数据是自己生成的，示例上给的方法不生效，  而且这个页面我用echarts做了 折线图，雷达图，圆环图，会对这个产生影响吗？
![image](https://cloud.githubusercontent.com/assets/13346477/15604830/e6f50862-2434-11e6-901a-d8d8dbce91ec.png)
![image](https://cloud.githubusercontent.com/assets/13346477/15604837/ef843dfe-2434-11e6-8b18-e24e7c8b52f2.png)

**Comment by pissang** [comment]
echarts 版本是啥？

**Comment by wastef** [comment]
之前 用的2.0 。。

**Comment by wastef** [comment]
现在的 3.0版本 没用圆环图了吗？
![image](https://cloud.githubusercontent.com/assets/13346477/15638239/8eb20b82-2650-11e6-9a41-862538f63f3a.png)

**Comment by wastef** [comment]
没有 这个图了吗？

**Comment by wastef** [comment]
之前用的 2.0版本  
现在的3.0版本 没有圆环图了吗？
![image](https://cloud.githubusercontent.com/assets/13346477/15638255/bc150ee4-2650-11e6-9ed1-a37bfa51c78e.png)

**Comment by pissang** [comment]
这是用饼图模拟的，3 里也可以
