### ISSUE TITLE
Echar3.0图表缩小到一定尺寸后柱形图会错位

### ISSUE THREAD

**Issue by Lusice520** [ecomfe/echarts#3296]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

****

**Comment by pissang** [comment]
无法复现
