### ISSUE TITLE
在react中使用echarts绘制地图报错Uncaught TypeError: Cannot read property 'features' of undefined

### ISSUE THREAD

**Issue by rrandom** [ecomfe/echarts#3301]
#### 问题简述 (One-line summary)
在react中使用echarts绘制地图报错
firefox: `TypeError: geoJson is undefined`
chrome: `Uncaught TypeError: Cannot read property 'features' of undefined`

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): "echarts": "^3.1.10",
+ 浏览器类型和版本 (Browser version): chrome&firefox
+ 操作系统类型和版本 (OS Version): windows

#### 重现步骤 (Steps to reproduce)
1. `import echarts from 'echarts'`
2. 见下方codepen链接

#### 可能哪里有问题 (What went wrong)
`Uncaught TypeError: Cannot read property 'features' of undefinedgeoCreator.getFilledRegions @ geoCreator.js:187SeriesModel.extend._fillOption @ MapSeries.js:66SeriesModel.extend.init @ MapSeries.js:34Model @ Model.js:39ExtendedClass @ clazz.js:28ExtendedClass @ clazz.js:28(anonymous function) @ Global.js:182each @ util.js:231visitComponent @ Global.js:155entity.topologicalTravel @ component.js:89Model.extend.mergeOption @ Global.js:135initBase @ Global.js:599Model.extend.resetOption @ Global.js:80Model.extend.setOption @ Global.js:62echartsProto.setOption @ echarts.js:182componentDidMount @ Map.jsx:21proxiedComponentDidMount @ createPrototypeProxy.js:61invokeComponentDidMountWithTimer @ ReactCompositeComponent.js:63_assign.notifyAll @ CallbackQueue.js:66ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:79Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149batchedMountComponentIntoNode @ ReactMount.js:123Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98ReactMount._renderNewRootComponent @ ReactMount.js:286ReactMount._renderSubtreeIntoContainer @ ReactMount.js:365ReactMount.render @ ReactMount.js:386(anonymous function) @ index.js:8__webpack_require__ @ bootstrap 185ff57a9218dc4c029f:585fn @ bootstrap 185ff57a9218dc4c029f:109(anonymous function) @ index.js:6__webpack_require__ @ bootstrap 185ff57a9218dc4c029f:585webpackJsonpCallback @ bootstrap 185ff57a9218dc4c029f:21(anonymous function) @ index.js:1`

#### ECharts配置项 (ECharts option)

```javascript


```

#### 其他信息 (Other comments)

bug重现:   [http://codepen.io/rrandom/pen/dXyJVK](http://codepen.io/rrandom/pen/dXyJVK)

**Comment by rrandom** [comment]
不管是地图还是坐标为地图都会出现这个错误信息

**Comment by pissang** [comment]
没有加载地图数据吧

**Comment by rrandom** [comment]
多谢
