### ISSUE TITLE
设置backgroundcolor后splitLine被覆盖的问题

### ISSUE THREAD

**Issue by dreamcatcher081210** [ecomfe/echarts#3305]
如题，在我设置`grid: {
		    	//默认是不展现backgroundColor，要设置show为true才行
 		    	show:true,
		        left: '3%',
		        right: '4%',
		        bottom: '3%',
		        top:80,
		        borderWidth:0,
		        containLabel: true,
		        backgroundColor:'rgb(100, 107, 123)'
		    },`后，y轴的分割线被覆盖掉了，`yAxis : [
		        {
		            type : 'value',
		            splitLine :{
		            	lineStyle:{
		            		color:'#f39800'
		            	}
		            },
		            axisTick : {show: false}
		        }
		    ]`
以上请各位帮忙~

**Comment by pissang** [comment]
可以将 xAxis，yAxis 的 z 设置成 1

**Comment by dreamcatcher081210** [comment]
@pissang  谢谢！还是没有看好文档，以后会看仔细了再来问，不好意思！
