### ISSUE TITLE
柱状图放上鼠标放到柱子上后，只有柱子有:hover效果，而不是整个柱子区域都有阴影遮罩

### ISSUE THREAD

**Issue by believeZJP** [ecomfe/echarts#3310]
#### 问题简述 (One-line summary)
柱状图目前鼠标放上后会整个显示遮罩，只想柱子显示遮罩无法设置

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):所有
+ 操作系统类型和版本 (OS Version): windows

#### 重现步骤 (Steps to reproduce)
1.随便写个柱状图，
2.鼠标放到柱子上

#### 期望结果 (Expected behaviour)
只有柱子有阴影效果，而不要柱子所在区域都有阴影效果

#### 可能哪里有问题 (What went wrong)
鼠标移过对区域进行细致判断

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/15198091/15664869/f08ed9ae-2739-11e6-873e-251bcbacc07e.png)

**Comment by pissang** [comment]
tooltip.trigger 改成 item

**Comment by believeZJP** [comment]
可以了，多谢~~
