### ISSUE TITLE
滚轮放大后的map地图，能通过什么方法将地图重新复位到初始化的地方

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#3314]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by giscafer** [comment]
重新`setOption`就恢复原来的初始化位置了。另外options里边的参数`zoom`可以控制缩放记录

**Comment by chm74** [comment]
实验结果，地图并没有恢复到原来的位置，而是散点图重新渲染了一次。需求就是点击按钮，让地图恢复到没有滚轮放的时候（地图初始位置，初始大小）

**Comment by pissang** [comment]
重置的时候 center 设成 null, zoom 设成 1

**Comment by chm74** [comment]
$('').click(function(){
    option.series[0].center=null;
    option.series[0].zoom=1;
    chart.setOption(option);
})
没什么效果？ 谢谢

**Comment by pissang** [comment]
看下 echarts 版本， 3.1.8 开始支持

**Comment by AABig** [comment]
我也遇到了这样的问题，在尝试setOption(option, true)无效后，终于找到了一个方法：
`
chart.clear()
chart.setOption(option)
`
clear方法会清空当前实例，会移除实例中所有的组件和图表。清空后调用 getOption 方法返回一个{}空对象。
清空后通过调用setOption方法重新设置，自然就得到初始的图表了~
