### ISSUE TITLE
graph links的source和target有问题

### ISSUE THREAD

**Issue by feeee** [ecomfe/echarts#3317]
graph links的source和target有问题，现在source和target用的是node.data的数组key去连线的，而文档标的是graph.node 的 name，换成name后线出不来，建议用id来获取node。

建议src/data/Graph.js  129行改为：

        if (typeof n1 === 'number') {
            n1 = this.getNodeById(n1);
        }
        if (typeof n2 === 'number') {
            n2 = this.getNodeById(n2);
        }

**Comment by hbwhypw** [comment]
我刚提交了跟你相似的问题，才看到你的。用你的方式，直接解决了我的问题。

**Comment by pissang** [comment]
name 和 数组 index 都是可以的，如果有 id 优先取 id

**Comment by yinyihui** [comment]
![image](https://user-images.githubusercontent.com/13214503/27163560-d8ead684-51ba-11e7-96ed-d2b0c23f92d9.png)
貌似源码中是以index去拿的，并没有根据id去获取node
