### ISSUE TITLE
Uncaught TypeError: Cannot read property 'features' of undefined

### ISSUE THREAD

**Issue by leoguan88** [ecomfe/echarts#3323]
#### 问题简述 (One-line summary)
 option = {
		    tooltip: {
		        trigger: 'item',
		        formatter: '{b}'
		    },
		    series: [
		        {
		            name: '中国',
		            type: 'map',
		            mapType: 'china',
		            selectedMode : 'multiple',
		            label: {
		                normal: {
		                    show: true
		                },
		                emphasis: {
		                    show: true
		                }
		            },
		            data:[
		                {name:'广东', selected:true}
		            ]
		        }
		    ]
		};

这样的OPTION，一直报这个错：
Uncaught TypeError: Cannot read property 'features' of undefined

不知该如何处理。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3301
