### ISSUE TITLE
显示的中国地图中，南海诸岛的注记文字为乱码，其他没有问题，怎么解决？能够隐藏南海诸岛也行

### ISSUE THREAD

**Issue by 651778286** [ecomfe/echarts#3324]
#### 问题简述 (One-line summary)
显示的中国地图中，南海诸岛的注记文字为乱码，其他没有问题，怎么解决？能够隐藏南海诸岛也行

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):chrome版本 50.0.2661.102 m
+ 操作系统类型和版本 (OS Version):window10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

效果见此：http://www.hwasmart.com/#footprint-section

**Comment by pissang** [comment]
js 文件编码不对

**Comment by 651778286** [comment]
谢谢，从新下载echarts.min.js之后，乱码没有了，不过还想继续请教一下，南海诸岛有没有办法隐藏掉，有些时候确实有这种需求

**Comment by pissang** [comment]
registerMap 注册的时候不要注册成 china，可以改成 china2 等，如果是 china 的话会自动 hook 加上南海诸岛

**Comment by 651778286** [comment]
![Uploading 无标题.jpg…]()
我按照你说的方式试了一下，没有成功

**Comment by 651778286** [comment]
注册‘china2’也没有实现海南诸岛的隐藏，是不是还有其他设置项没有设置？

**Comment by pissang** [comment]
贴下具体的代码？

**Comment by 651778286** [comment]
var myChart = echarts.init(document.getElementById('map'));
myChart.showLoading();

$.get('data/china.json', function (geoJson) {
			color: ['orangered', 'white']
		},
		series: [{
			map: 'china',
			type: 'map',
			selectedMode : 'single',
			label: {
				normal: {
					show: true
				},
				emphasis: {
					show: false
				}
			},
			data: data
		}]
	});


	var province = null;
	myChart.on('click', function (params) {
		if(province == params.name){
			return;
		}

		province = params.name;

		$('.province').text(province);
		var list = listFootprint(province);
		if(!list || list.length <= 0){
			$('#footprint-list').empty();
			$('#no-footprint-tip').show();
			return;
		}

		$('#no-footprint-tip').hide();

		var render = template.compile(FootPrint);
		var html = render({
			list: list
		});

		$('#footprint-list').html(html);
	});
});

**Comment by 651778286** [comment]
var myChart = echarts.init(document.getElementById('map'));
myChart.showLoading();

$.get('data/china.json', function (geoJson) {
			color: ['orangered', 'white']
		},
		series: [{
			map: 'china',
			type: 'map',
			selectedMode : 'single',
			label: {
				normal: {
					show: true
				},
				emphasis: {
					show: false
				}
			},
			data: data
		}]
	});


	var province = null;
	myChart.on('click', function (params) {
		if(province == params.name){
			return;
		}

		province = params.name;

		$('.province').text(province);
		var list = listFootprint(province);
		if(!list || list.length <= 0){
			$('#footprint-list').empty();
			$('#no-footprint-tip').show();
			return;
		}

		$('#no-footprint-tip').hide();

		var render = template.compile(FootPrint);
		var html = render({
			list: list
		});

		$('#footprint-list').html(html);
	});
});

**Comment by pissang** [comment]
map: 'china' 改为新注册的 map:'china2'

**Comment by 651778286** [comment]
实现了，之前我理解错了，谢谢啊^_^

**Comment by mqliutie** [comment]
改成 `china2` 地图都不显示了

**Comment by chfw** [comment]
echarts.registerMap("china2", {...your china.json content...})
