### ISSUE TITLE
echart3绘制迁徙图问题

### ISSUE THREAD

**Issue by sanrudongfeng** [ecomfe/echarts#3325]
echart3之中无法使用echart2绘制迁徙图的炫光特效http://echarts.baidu.com/echarts2/doc/example/map11.html，有没有办法在echart3之中绘制出echart2的特效。试过option.series增加map或者scatter类型，得不到炫光效果

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=geo-lines

**Comment by sanrudongfeng** [comment]
这个效果不行啊，不支持炫光特效，效果一般，不好看呐

**Comment by pissang** [comment]
你换个颜色就是眩光特效了

**Comment by oneroundseven** [comment]
@sanrudongfeng  你说的应该是不能实现那个扩散的波纹效果吧, 那个line上面的炫光是可以的 
http://echarts.baidu.com/option.html#series-lines.effect
