### ISSUE TITLE
数组中有“”项，折线图中显示为0

### ISSUE THREAD

**Issue by lufangjun** [ecomfe/echarts#3326]
#### 问题简述 (One-line summary)
var axisArray =["11:50:58", "11:51:58", "11:52:58", "11:53:58", "11:54:58", "11:55:58", "11:56:58", "11:57:58", "11:58:58", "11:59:58", "12:00:58", "12:01:58", "12:02:58", "12:03:58", "12:04:58", "12:05:58", "12:06:58", "12:07:58", "12:08:58", "12:09:58", "12:10:58", "12:11:58", "12:12:58", "12:13:58", "12:14:58", "12:15:58", "12:16:58", "12:17:58", "12:18:58", "12:19:58", "12:20:58", "12:21:58", "12:22:58", "12:23:58", "12:24:58", "12:25:58", "12:26:58", "12:27:58", "12:28:58", "12:29:58", "12:30:58", "12:31:58", "12:32:58", "12:33:58", "12:34:58"]
var dataArray=["36.4", "26.2", "16.0", "6.7", "90.5", "80.3", "32.0", "22.7", "40.5", "30.3", "", "", "", "", "", "", "37.2", "27.0", "17.7", "7.5", "25.3", "15.1", "61.7", "51.5", "69.3", "59.1", "49.8", "39.6", "29.4", "20.5", "10.3", "94.1", "84.8", "74.6", "64.4", "54.2", "6.8", "90.6", "80.4", "70.2", "88.0", "11.6", "95.4", "47.1", "38.0"]
dataArray里面有几项是“”,在图中显示成了0

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.2.7
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
dataArray为空项在折线图中为断开，而不是0

#### ECharts配置项 (ECharts option)

```javascript
option = {
{
                        legend: {
                            data: ['probe1']
                        },
                        tooltip: {
                            trigger: 'axis'
                        },
                        toolbox: {
                            show: true,
                            feature: {
                                mark: {show: false},
                                dataView: {show: false, readOnly: false},
                                magicType: {show: false, type: ['line', 'bar', 'stack', 'tiled']},
                                restore: {show: false},
                                saveAsImage: {show: false}
                            }
                        },
                        calculable: true,
                        xAxis: [
                            {
                                type: 'category',
                                data: axisArray
                            }
                        ],
                        yAxis: [
                            {
                                type: 'value',
                                splitArea: {show: true}
                            }
                        ],
                        series: [
                            {
                                name: "abc",
                                type: 'line',
                                data: dataArray
                            }
                        ]
                    }
}

```

**Comment by PolanZ** [comment]
3.0上没有问题哦，可能你在""中加个-看看
