### ISSUE TITLE
能不能把echarts3添加到百度静态资源公共库呢？

### ISSUE THREAD

**Issue by sdhhqb** [ecomfe/echarts#3328]
echarts3已经发布有一段时间了，现在[百度公共cdn](http://cdn.code.baidu.com/)上还是只有echarts2的资源，希望什么时候可以把echarts3添加上去。

**Comment by pissang** [comment]
可以使用 cdnjs 作为 cdn，https://cdnjs.com/libraries/echarts，会跟 github 版本保持同步更新，国内也可以使用 [bootcdn](http://www.bootcdn.cn/echarts/)

**Comment by sdhhqb** [comment]
非常感谢！bootcdn速度挺快的。
