### ISSUE TITLE
能给label 字体设置background吗？ 

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#3329]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

http://echarts.baidu.com/gallery/editor.html?c=effectScatter-map
给大庆加backgroundImage

**Comment by pissang** [comment]
暂时不行
