### ISSUE TITLE
新打开的页面，有时候加载的地图是歪的

### ISSUE THREAD

**Issue by tianr1190** [ecomfe/echarts#3331]
#### 问题简述 (One-line summary)

新打开的页面，有时候加载的地图是歪的。刷新页面就回复正常了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): ie11
+ 操作系统类型和版本 (OS Version): win8.1

#### 重现步骤 (Steps to reproduce)
1. 新打开的页面有时候会出现地图歪一边， 而且容器样式上定义的宽带是1140px, 但是生成的canvas宽度却是1860px. 如图所示，蓝色区域是容器的大小和位置。地图超出了容器。
![image](https://cloud.githubusercontent.com/assets/19337143/15706585/f6dd5108-2826-11e6-8134-a2c2b6f5f639.png)

2. 要重新刷新页面，才能正常显示。如图是刷新页面后正常显示。
![image](https://cloud.githubusercontent.com/assets/19337143/15706628/2c3fc0ba-2827-11e6-9b8a-0a53eb02c42e.png)

#### 期望结果 (Expected behaviour)

希望打开的页面不会出现歪到一边。

#### 可能哪里有问题 (What went wrong)

我觉得可能是容器的css样式文件加载，和地图渲染在时间上的先后问题。

#### ECharts配置项 (ECharts option)

<div id='map' style='width:1140px;height:800px;margin:0 auto;'></div>

```javascript

var myChart = echarts.init(document.getElementById('map')); 
		
var option = {
	
	title : {
		text: '中国地图',
		subtext: '',
		x:'center'
	},
	tooltip : {
		trigger: 'item'
	},
	visualMap: {
		show: false,
		min: 0,
		max: 1000,
		x: 'left',
		y: 'bottom',
		text:['高','低'],           // 文本，默认为数值文本
		calculable : true,
		outOfRange:{
				color:['#bafff1','#168e76'],
				symbolSize: [30, 100]
			},
		inRange:{
				color:['#bafff1','#168e76'],
				symbolSize: [30, 100]
			},
	},
	series : [
		{
			name: '中国地图',
			type: 'map',
			mapType: 'china',
			selectedMode: false,
			roam: false,
			itemStyle:{
				normal:{label:{show:true},borderWidth:0},
				emphasis:{label:{show:true,borderWidth:0}}
			},
			data:[]
		}
	]
};

var url ='assets/js/map/json/china.json';
var name = 'china';

$(document).ready(function(e){
myChart.showLoading();
$.get(url, function (chinaJson) {
			echarts.registerMap(name, chinaJson);
			option.series[0].mapType = name;
			
			
			myChart.setOption(option); 
			myChart.hideLoading();

		});
});


```

**Comment by pissang** [comment]
等容器宽度确定好再 setOption 或者 resize

**Comment by tianr1190** [comment]
怎么才知道容器的宽度定好了呢， 前端页面用的是bootstrap3框架. 容器用的是前端框架的.container样式。
