### ISSUE TITLE
大神，帮帮忙，真的搞不出来，echart 2.0 怎样修改源码可以实现默认地图是放大？放大两倍就可以

### ISSUE THREAD

**Issue by wastef** [ecomfe/echarts#3333]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不要重复提 issue
