### ISSUE TITLE
中国地图里面能加上钓鱼岛吗？3Q

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#3334]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以自行寻找合适的 geoJson 数据

**Comment by chm74** [comment]
您给别的问题回复的，mapshaper里面，可以生成带有钓鱼岛的json地图数据吗？3Q

**Comment by pissang** [comment]
如果你找的数据里带钓鱼岛信息的就可以
