### ISSUE TITLE
官方文档无法访问，报ecLog错误

### ISSUE THREAD

**Issue by wefound** [ecomfe/echarts#3335]
#### 问题简述 (One-line summary)

官方文档完全访问不了？科学上网都不行啊

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以啊

**Comment by wefound** [comment]
@pissang 哦豁，访问的是2.0的文档，3.0可以……

**Comment by wefound** [comment]
![image](https://cloud.githubusercontent.com/assets/1245993/15736710/21843478-28d4-11e6-94a5-f420014ee87c.png)

**Comment by pissang** [comment]
有 js 文件没加载成功吧

**Comment by dev-techmoe** [comment]
**检查一下是不是和一些防跟踪或者广告拦截插件（比如隐私獾或者ADBlock）冲突了，把他们禁用试试**  
刚刚我也遇到了这样的问题，ADBlock关了立刻就好了。。
