### ISSUE TITLE
echart3.0 疑问

### ISSUE THREAD

**Issue by huoshidehua** [ecomfe/echarts#3339]
#### 问题简述 (One-line summary)
echart 3.0 当xAxis的type指定为‘categroy’的时候为什么一定要设置数据？而且为什么当不设置data属性且设定type为:'time' 或者 ‘log’ 或者 ‘value’时 会默认出现数据？当series中不设置data 且 xAxis中不设置数据时 想要的结果是显示 暂无数据 就想 echart2.0那样 出项气泡的效果一样

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):firefox 和 chrome
+ 操作系统类型和版本 (OS Version): win8

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
显示暂无数据而不是填充默认数据

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
没有数据可以自己根据需要显示暂无数据，数值轴能够根据数据自己计算出刻度，但是类目轴必须要指定类目（3 里面 data 传一个空的 [] 也能用）
