### ISSUE TITLE
可以兩張圖表用同一個缩放组件嗎? 

### ISSUE THREAD

**Issue by t5957810** [ecomfe/echarts#3342]
請問echart的dataZoom，
他是setOption裡的其中一個object, 
有辦法用兩張圖表,共用一個dataZoom嗎 ? 

就是在拖拉一個dataZoom，上下兩張圖表一起移動這樣，要怎麼做呢

**Comment by pissang** [comment]
单实例可以参考 http://echarts.baidu.com/gallery/editor.html?c=grid-multiple，多实例可以用 connect 实现联动
