### ISSUE TITLE
stack属性和yAxis max属性冲突

### ISSUE THREAD

**Issue by xubowenjx** [ecomfe/echarts#3345]
### 1.概述
   yAxis设置max属性时,series中对象设置相同stack，当堆积总和大于max值,导致图形溢出。

### 2.浏览器环境
   window7&Chrome 49
### 3.ECharts version
  3.1.10
### 4. code
    option = {
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['蒸发量','降水量','平均温度']
    },
    xAxis: [
        {
            type: 'category',
            data: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
        }
    ],
    yAxis: [
        {
            type: 'value',
            name: '水量',
            min: 0,
            max: 250,
            interval: 50,
            axisLabel: {
                formatter: '{value} ml'
            }
        },
        {
            type: 'value',
            name: '温度',
            min: 0,
            max: 25,
            interval: 5,
            axisLabel: {
                formatter: '{value} °C'
            }
        }
    ],
    series: [
        {
            name:'蒸发量',
            type:'bar',
            stack:'总蒸发',
            data:[3.0, 5.9, 7.0, 23.2, 25.6, 86.7, 145.6, 172.2, 42.6, 23.0, 7.4, 2.3]
        },
          {
            name:'蒸发量',
            type:'bar',
             stack:'总蒸发',
            data:[3.0, 5.9, 7.0, 23.2, 25.6, 86.7, 145.6, 172.2, 42.6, 23.0, 7.4, 2.3]
        },
        {
            name:'降水量',
            type:'bar',
            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
        },   
        {
            name:'平均温度',
            type:'line',
            yAxisIndex: 1,
            data:[2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]
        }
    ]};

**Comment by pissang** [comment]
max 需要考虑 stack 后的值
