### ISSUE TITLE
可否同时显示两个或以上的tooltip

### ISSUE THREAD

**Issue by AllyW** [ecomfe/echarts#3348]
#### 问题简述 (One-line summary)

可否在图上同时显示两个及以上的tooltip

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0.0
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): mac os

#### 重现步骤 (Steps to reproduce)
1.鼠标滑过一条有tooltip的axisline，对应tooltip显示
2.鼠标移开到另一条axisline，前一个tooltip消失，出现对应于后一条axisline的tooltip

#### 期望结果 (Expected behaviour)

希望前一个axisline和后一个axisline的tooltip可以同时存在

#### 可能哪里有问题 (What went wrong)

unknown

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行
