### ISSUE TITLE
【请教】echarts初始化后canvas里面的内容部分没有充分利用相应的高度

### ISSUE THREAD

**Issue by hustcer** [ecomfe/echarts#3351]
#### 问题简述 (One-line summary)

为什么给echarts设置指定的宽度和高度后，虽然 cavas 充分占用了相应的高度和宽度，但是里面的chart内容部分并没有占满相应的高度？比如绘制折线图的时候，我设置了 dom 元素 `width:200px;height:100px;` canvas的大小是200x100的，但是里面的绘图部分可能只有 200x50，感觉高度还有一半没有占满，有什么设置项可以解决这个问题么？谢谢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version): chrome最新版
+ 操作系统类型和版本 (OS Version): Mac OS 最新版

**Comment by jx-zhang** [comment]
同问！
echart绘制的内容是按比例来的么？
比如固定的宽度，按比例一个固定的高度。
我修改了canvas的高度后，出现失真和拉伸的现象。
请问可以让canvas跟着容器的宽高走么？

**Comment by Realzzz1874** [comment]
grid: {
					top: 30,
					bottom: 0,
					left: 20,
					right: 30,
					containLabel: true
				},

**Comment by zhanzhanxi** [comment]
4.9.0版本，我遇到了浏览器窗口先放大再缩小之后，canvas高度很低，不能适应外层div高度的问题(多个div,整体用flex布局)，最外层div指定了height=60vh,最后将height=60vh改成 min-height=60vh，该问题不再复现
