### ISSUE TITLE
scatter-life-expectancy-timeline

### ISSUE THREAD

**Issue by GZJackCai** [ecomfe/echarts#3352]
#### 问题简述 (One-line summary)
scatter-life-expectancy-timeline 散点图动态点如何显示文字

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):
++3.0
+chrome
+win 2007
#### 重现步骤 (Steps to reproduce)
1.无法再散点图添加文字，data设置是否有什么tip
2.

#### 期望结果 (Expected behaviour)
散点图动态点显示文字

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-scatter.label.normal.show

**Comment by GZJackCai** [comment]
Thanks ，可以了
