### ISSUE TITLE
仪表盘的指针样式能不能修改，例如一个箭头效果？

### ISSUE THREAD

**Issue by gaozhiwei123** [ecomfe/echarts#3353]
#### 问题简述 (One-line summary)

仪表盘的指针样式能不能修改，例如一个箭头效果？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome浏览器
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
目前不行
