### ISSUE TITLE
Echarts 3.1.10 所有类目的字体大小无法生效

### ISSUE THREAD

**Issue by qwm876677344** [ecomfe/echarts#3356]
#### 问题简述 (One-line summary)
Echarts 3.1.10 所有类目的字体大小无法生效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 :3.1.10
+ google:
+ windows7:

#### 期望结果 (Expected behaviour)
希望小字体自己也能设置

#### ECharts配置项 (ECharts option)
option = {
    title: {
        text: '深圳月最低生活费组成（单位:元）',
        subtext: 'From ExcelHome',
        sublink: 'http://e.weibo.com/1341556070/AjQH99che'
    },
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        },
        formatter: function (params) {
            var tar = params[1];
            return tar.name + '<br/>' + tar.seriesName + ' : ' + tar.value;
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type : 'category',
        splitLine: {show:false},
        data : ['总费用','房租','水电费','交通费','伙食费','日用品数'],
        axisLabel:{
            textStyle:{
                fontSize:2      //=====》》》小size无法生效
            }    
        }
        
        
        
    },
    yAxis: {
        type : 'value',
        boundaryGap: ['15%', '15%']
    },
    series: [
        {
            name: '辅助',
            type: 'bar',
            stack:  '总量',
            itemStyle: {
                normal: {
                    barBorderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                },
                emphasis: {
                    barBorderColor: 'rgba(0,0,0,0)',
                    color: 'rgba(0,0,0,0)'
                }
            },
            data: [0, 1700, 1400, 1200, 300, 0]
        },
        {
            name: '生活费',
            type: 'bar',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'inside'
                }
            },
            data:[2900, 1200, 300, 200, 900, 300]
        }
    ]
};

**Comment by pissang** [comment]
浏览器限制最小字体大小为 12
