### ISSUE TITLE
数据的显示进度如何设置呢

### ISSUE THREAD

**Issue by wucangeo** [ecomfe/echarts#3358]
#### 问题简述 (One-line summary)

在柱状图或饼状图中，显示的数据值想要以两位小数的形式展示，请问如何设置呢？

初次使用echarts，问题可能比较初级，多多包涵。不过在几个搜索引擎中也没有搜到相关问题。
API文档中有关于markLine的精度设置，数据精度设置没有发现。

**Comment by pissang** [comment]
formatter 里 toFixed

**Comment by wucangeo** [comment]
谢谢！@pissang

**Comment by wucangeo** [comment]
不过感觉没有提供一个统一设置的参数方便呢
