### ISSUE TITLE
ehcarts 3.0中地图的“MAP_ROAM”事件没有了吗？

### ISSUE THREAD

**Issue by adamsheng** [ecomfe/echarts#3360]
#### 问题简述 (One-line summary)
ehcarts 3.0中地图的“MAP_ROAM”事件没有了吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
有 'georoam' 事件
