### ISSUE TITLE
echarts3.0官网箱线图tooltip疑问

### ISSUE THREAD

**Issue by langman** [ecomfe/echarts#3361]
官网箱线图地址：
http://echarts.baidu.com.cn/demo.html#boxplot-light-velocity
tooltip截图：
![image](https://cloud.githubusercontent.com/assets/17428656/15813984/d9395cc8-2bf5-11e6-8b7a-289f53c41ea8.png)
请问这个提示中的upper和lower是不是搞反了。

**Comment by pissang** [comment]
是的谢谢建议，已修正
