### ISSUE TITLE
官网配置项手册中的一个小错误

### ISSUE THREAD

**Issue by LiangYe910** [ecomfe/echarts#3362]
#### 问题简述 (One-line summary)

您好，官网上 配置项手册中雷达图radar.name和radar.nameGap这两个配置项中有一些问题。比如textStyle是应该在name中的，而官网则写在了nameGap里面。别的配置项我没有试，不知是否还有其他错误。谢谢。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome 50.0.2661.75 m
+ 操作系统类型和版本 (OS Version):win10专业版

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

我是这样更改了雷达图指示器名称的字体颜色，官网上应该是有错误
```javascript
option = {
           radar: {
							// shape: 'circle',
							indicator: [
							   { name: '教育', max: 6500},
							   { name: '医疗', max: 16000},
							   { name: '购物', max: 30000},
							   { name: '公共场所', max: 38000},
							   { name: '其他', max: 52000},
							   
							],
							name:{textStyle:{color:'black'}}
						},
}

```

**Comment by pissang** [comment]
谢谢建议，下个版本修复
