### ISSUE TITLE
echarts 3官网的拖拽重计算不管用

### ISSUE THREAD

**Issue by ffio** [ecomfe/echarts#3363]
#### 问题简述 (One-line summary)
echarts 3拖拽重计算不管用

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts 3.0
+ 浏览器类型和版本 (Browser version): chrome 42.0.2311.135
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.官网http://echarts.baidu.com/demo.html#bar1  拖拽重计算不可用

#### 期望结果 (Expected behaviour)
拖拽重计算功能可用

#### 可能哪里有问题 (What went wrong)

  calculable : true,

#### ECharts配置项 (ECharts option)

```javascript
option = {
 title : {
        text: '某地区蒸发量和降水量',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['蒸发量','降水量']
    },
    toolbox: {
        show : true,
        feature : {
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
}

```

**Comment by zhouxinyong** [comment]
貌似echarts3拖拽重排功能不支持了，详见 https://github.com/ecomfe/echarts/issues/3322
