### ISSUE TITLE
dispatchAction  legendSelect无效

### ISSUE THREAD

**Issue by shikelong** [ecomfe/echarts#3364]
#### 问题简述 (One-line summary)

dispatchAction legendSelect事件。无反应。
dispatchAction highlight可以起作用。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version): chrome 50
+ 操作系统类型和版本 (OS Version): windows 10

#### 重现步骤 (Steps to reproduce)
1.  点击按钮 调用dispatchAction方法来dispatch legendSelect事件
2.  发现没有任何改变

#### 期望结果 (Expected behaviour)

1. 相应的legend被选中 显示出emphasis的样式

#### 可能哪里有问题 (What went wrong)

已经引入了legend组件并且使用了legend.

#### ECharts配置项 (ECharts option)

**请见下方jsbin**

#### 其他信息 (Other comments)

http://jsbin.com/tezevin/edit?html,js,output

Regards

**Comment by pissang** [comment]
legendSelect 是选中图例，如果要开关图例应该是 legendToggleSelect，如果是取消选中图例则是 legendUnSelect

**Comment by shikelong** [comment]
谢谢  legendSelect事件不触发emphasis的样式吗？ 鼠标hover legend上都会有 emphasis样式的。 选中不会有？

**Comment by pissang** [comment]
选中就是展示，跟 emphasis 无关

**Comment by shikelong** [comment]
恩 多谢了。了解。

实际上legend的事件只有legendSelect,legendUnSelect, legendToogleSelect是对这两个状态做切换的。 我jsbin中dispatchAction不起作用是因为我dispatch的legend已经是展示状态了。

legend的事件只关心legend本身。 如果要做legend对应的series的选中样式应该dispatch其他事件。
