### ISSUE TITLE
柱状图series的data里的label无法显示

### ISSUE THREAD

**Issue by jylzs369** [ecomfe/echarts#3365]
#### 问题简述 (One-line summary)
柱状图series的data里的label无法显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version): chrome 50
+ 操作系统类型和版本 (OS Version): window7

#### 重现步骤 (Steps to reproduce)
1.设置好label相应参数
2.打开浏览器无label出现

#### 期望结果 (Expected behaviour)
相应柱状图上方有label显示

#### 可能哪里有问题 (What went wrong)
与上级name属性设置有关？这里已经设置

#### ECharts配置项 (ECharts option)

```javascript
option = {
  tooltip : {
    trigger: 'item'
  },
  ...
  series: [
    {
      type: 'bar',
      data: [
        {
          name: '2016/02 收益:',
          value: 145,
          label: {
            show: true,
            textStyle: {
              color: '#646567'
           }
         },
       ],
     }
   ]
};

```

**Comment by pissang** [comment]
```js
{ label: normal: {show: true} }
```
