### ISSUE TITLE
请问 echarts3中如何去掉toolbox-feature-dataView中默认的"刷新"按钮

### ISSUE THREAD

**Issue by tianjianwei1990** [ecomfe/echarts#3366]
#### 问题简述 (One-line summary)
请问 echarts3中如何去掉toolbox-feature-dataView中默认的"刷新"按钮

**Comment by pissang** [comment]
[readOnly](http://echarts.baidu.com/option.html#toolbox.feature.dataView.readOnly) 设成 true
