### ISSUE TITLE
map图表省份名字显示的位置会显示在这个省份区域的外面

### ISSUE THREAD

**Issue by kakalotte** [ecomfe/echarts#3371]
map图表省份名字显示的位置会显示在这个省份区域的外面，例如黑龙江省的已经到了其区域外了。对比了下老版本的echarts(2.X)，倒没有这样地 问题

#### 版本及环境
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version):chrome 45
+ 操作系统类型和版本 (OS Version):win7 

#### 重现步骤 (Steps to reproduce)
1.

#### 期望结果 (Expected behaviour)

期望省份名字可以在图表相对居中的位置

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

问题在这个页面上：http://echarts.baidu.com/demo.html#map-china-dataRange

**Comment by pissang** [comment]
3 的地图中 symbol 的位置使用省会的位置，如果不需要可以将 geoJson 中 features[i].property.cp 设成 null
