### ISSUE TITLE
地图使用visualMap后鼠标悬浮可以沿用当前的颜色吗？

### ISSUE THREAD

**Issue by liyikai** [ecomfe/echarts#3372]
您好！
       地图使用visualMap后，可以按数值显示颜色深浅。鼠标移动后某个地域的颜色可以沿用当前颜色吗？现在鼠标悬浮某个地域只能通过emphasis.areaColor设置一个颜色。

**Comment by pissang** [comment]
可以将 emphasis.areaColor 设成 null，会自动在当前颜色基础上调高亮度作为高亮颜色
