### ISSUE TITLE
emptyCircle  不能实现透明圆波纹动画效果

### ISSUE THREAD

**Issue by oneroundseven** [ecomfe/echarts#3373]
#### 问题简述 (One-line summary)
请问echart最近版本下如果实现 emptyCircle 我画出来是一个白色背景的图 不是空心的

2.0 示例 http://echarts.baidu.com/echarts2/extension/BMap/doc/BMap.html

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):
win7  Chrome 版本 50.0.2661.102 m

#### 重现步骤 (Steps to reproduce)
1. 打开官方示例 http://echarts.baidu.com/gallery/editor.html?c=effectScatter-map
2. 修改series部分代码
`series : [
        {
            name: 'Top 5',
            type: 'effectScatter',
            coordinateSystem: 'geo',
            markPoint: {
                symbol: 'emptyCircle',
                symbolSize: 50,
                effect : {
                    show: true,
                    shadowBlur : 0
                },
                itemStyle: {
                    normal: {
                        label: {show: false}
                    },
                    emphasis: {
                        label: {position: 'top'}
                    }
                },
                data: [
                    { coord : [121.48, 31.22], value: 20 }
                ]
            }
        }
    ]`

#### 期望结果 (Expected behaviour)
空心的提示圆圈  http://echarts.baidu.com/echarts2/extension/BMap/doc/BMap.html

#### 其他信息 (Other comments)

![20160607102300](https://cloud.githubusercontent.com/assets/1825295/15844129/293b4d54-2c9a-11e6-8b2e-89ab13f24b13.jpg)

**Comment by pissang** [comment]
那不需要是 emptyCircle，可以设置为:

```js
symbol: 'circle',
itemStyle: {
  normal: {
     borderWidth: 2,
     borderColor: 'red',
     color: 'transparent'
  }
}
```

**Comment by oneroundseven** [comment]
问下如何实现那个动画呢，用你的代码可以实现空心圆了 不过没有动画效果

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-effectScatter.effectType

**Comment by hairichuhe** [comment]
这个我查了一下，好像2的炫光效果，有内存泄露的问题，3貌似还没有炫光的功能~不知道楼上的兄弟实现了没？ @pissang @oneroundseven

**Comment by wu11106** [comment]
仁兄所说的炫光不晓得是什么地方的玩意

2016年9月8日星期四，海日初禾 <notifications@github.com> 写道：

**Comment by wujianfei** [comment]
找到line.js第583行代码：
var itemShape = this.getSymbolShape(serie, seriesIndex, data, dataIndex, name, x, y, this._sIndex2ShapeMap[seriesIndex], this._sIndex2ColorMap[seriesIndex], '#fff, orient === 'vertical' ? 'horizontal' : 'vertical');
这里面的#fff改成rgba(0,0,0,0)就可以了
