### ISSUE TITLE
symbol为图片并设置了symbolSize，连线的长度没考虑symbolOffset属性

### ISSUE THREAD

**Issue by feeee** [ecomfe/echarts#3374]
symbolOffset设置为 [50%,50%]时，线明显不够长。

**Comment by pissang** [comment]
什么线?

**Comment by feeee** [comment]
graph两个节点之间的连线，symbol为图片，symbolOffset不设置的时候，节点标记默认是图片正中间，这时候线是正好的，但如果symbolOffset设置为 [50%,50%]时，节点标记在图片左上角，这时候连线长度不够。
![Uploading image.png…]()

**Comment by feeee** [comment]
graph两个节点之间的连线，symbol为图片，symbolOffset不设置的时候，节点标记默认是图片正中间，这时候线是正好的，但如果symbolOffset设置为 [50%,50%]时，节点标记在图片左上角，这时候连线长度不够。
![Uploading image.png…]()

**Comment by pissang** [comment]
symbolOffset 主要是为了配合调整像大头针这样的图片的尖头能够对准对应的端点，如果连线再调整端点位置，使用 symbolOffset 就没有意义了
