### ISSUE TITLE
echarts 3.0之前的版本支不支持世界地图初始化时，自定义缩放比例？

### ISSUE THREAD

**Issue by xushuo** [ecomfe/echarts#3376]
#### 问题简述 (One-line summary)

echarts 3.0之前的版本支不支持世界地图初始化时，自定义缩放比例？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0之前的版本，或者3.0也行。
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行
