### ISSUE TITLE
datazoom缩放的中间过程中,数据可能超出grid显示

### ISSUE THREAD

**Issue by shikelong** [ecomfe/echarts#3377]
#### 问题简述 (One-line summary)

datazoom缩放的中间过程中,数据可能超出grid显示。并遮挡title,legend等组件。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.x
+ 浏览器类型和版本 (Browser version): chrome 50
+ 操作系统类型和版本 (OS Version): windows 10

#### 重现步骤 (Steps to reproduce)
1. 点击下方jsbin链接
2. 用鼠标滚动滚动，使得datazoom从小到大。 发现在滚动过程中数据会超出grid显示。

#### 期望结果 (Expected behaviour)

数据不会超出grid显示。在使用过程中保持整洁和美观。

#### ECharts配置项 (ECharts option)

**请见下方jsbin链接**

#### 其他信息 (Other comments)

[jsbin example](http://jsbin.com/zibike/3/edit?js,output)

**Comment by pissang** [comment]
不建议对有 stack 的数据加上 Y 轴的 dataZoom

**Comment by shikelong** [comment]
thx.
