### ISSUE TITLE
关系图的连线显示文字怎么设置呢？

### ISSUE THREAD

**Issue by guopengno1** [ecomfe/echarts#3379]
#### 问题简述 (One-line summary)

关系图的连线显示文字怎么设置呢？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-graph.edgeLabel

**Comment by guopengno1** [comment]
您好，请问是 formatter 吗？我设置了不管用的:
edgeLabel: {
                normal: {
                    show: true,
                    formatter:'{a}{b}{c}',
                    textStyle: {
                        fontSize: 12
                    }
                }
            },

**Comment by pissang** [comment]
edgeLabel 从 3.1.8 才开始支持，先确认下版本是否高于 3.1.8

**Comment by guopengno1** [comment]
您好，我在网页编辑器中 直接改的，我也不知道 网页用的是哪个版本，是最新的吗？
