### ISSUE TITLE
能否给两条markLine之间设置填充色？ #1334

### ISSUE THREAD

**Issue by DXuYang** [ecomfe/echarts#3381]
有同学提出了这个问题，地址https://github.com/ecomfe/echarts/issues/1334
在新版本的3.1.10中可以实现在两条或多条markLine之间填充颜色么？按照作者的思路貌似不可以。

**Comment by pissang** [comment]
新版本将支持通过 markArea 标记整个区域

**Comment by DXuYang** [comment]
新版本什么时候发布？

**Comment by pissang** [comment]
本月月中

**Comment by DXuYang** [comment]
哦   那太好了，期待。

**Comment by reg21st** [comment]
可惜 新版本依然没有markArea

**Comment by pissang** [comment]
新版本就有了，下周初发布

**Comment by reg21st** [comment]
好的 热切期待。

**Comment by DXuYang** [comment]
markArea的用法我根据api写了下，我想实现在y 轴的两条标线之间填充颜色，我看了用法是指定data的左上角坐标和右下角坐标，但是拖动的时候markArea的效果不见了，有没有相关的演示来指定y轴两条横线之前的颜色填充？

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/gallery/editor.html?c=line-sections 也可以只设置 yAxis 设置 y 轴区域

**Comment by DXuYang** [comment]
秒回啊，太牛了，刚才找到了设置yAxis的代码，谢了。
