### ISSUE TITLE
应该将echarts.getMap接口在文档中写出来

### ISSUE THREAD

**Issue by rrandom** [ecomfe/echarts#3383]
既然代码里都把这个getMap这个函数暴露出来了， 
https://github.com/ecomfe/echarts/blob/master/src/coord/geo/geoCreator.js#L213
而文档中却没有 http://echarts.baidu.com/api.html#echarts
我认为事实上这个接口很有用，比如可以避免重复异步请求地图数据，那么在文档中也写出这个接口应该比较好吧？

**Comment by pissang** [comment]
谢谢建议，已加上
