### ISSUE TITLE
type:graph 且layout:force 的一些问题

### ISSUE THREAD

**Issue by guopengno1** [ecomfe/echarts#3384]
#### 问题简述 (One-line summary)

1、设置type：force 的时候，再设置 edgeSymbol: ['circle', 'arrow'], 所有节点会聚成一团，分离不开；
2、或者在单个links里设置edgeSymbol: ['circle', 'arrow'],无效果；
3、links中是否已经去掉了name的属性？
4、edgeLabel 的 formatter：'{a}{b}{c}', 都无反应，应该怎么设置线上面的文字？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts-master
+ 浏览器类型和版本 (Browser version):Firefox 46.0.1
+ 操作系统类型和版本 (OS Version):window10

#### 重现步骤 (Steps to reproduce)
1.打开http://echarts.baidu.com/demo.html#graph-simple
2.修改layout:force ，添加
force:{
        initLayout: 'force',
        repulsion: 200,
        gravity: 0.01,
        edgeLength: 200,
        layoutAnimation: false,
}, 
3.添加
edgeLabel: {
                normal: {
                    show: true,
                    formatter:'{a}{b}{c}',
                    textStyle: {
                        fontSize: 12
                    }
                }
            },

#### 期望结果 (Expected behaviour)
期望力导向图正常显示，并显示带箭头的连线，并能够自定义连线显示的文字；

#### 可能哪里有问题 (What went wrong)
I don't know

#### ECharts配置项 (ECharts option)

```javascript
option = {
    title: {
        text: 'Graph 简单示例'
    },
    tooltip: {},
    series : [
        {
            type: 'graph',
            layout: 'force',
            force:{
                initLayout: 'force',
                repulsion: 200,
                gravity: 0.01,
                edgeLength: 200,
                layoutAnimation: false,
                },  
            symbolSize: 50,
             edgeSymbol: ['circle', 'arrow'],
                edgeSymbolSize: [10, 20],
            draggable:true,
            roam: true,
            label: {
                normal: {
                    show: true
                }
            },
            data: [{
                name: '节点0'
            },{
                name: '节点1'
            }, {
                name: '节点2'
            }, {
                name: '节点3'
            }, {
                name: '节点4'
            }],
            // links: [],
            links: [{
                source: '节点0',
                target: '节点1',
                name:'123'
            }, {
                source: '节点0',
                target: '节点2'
            }, {
                source: '节点0',
                target: '节点3'
            }, {
                source: '节点0',
                target: '节点4',
               
            }],
            lineStyle: {
                normal: {
                    opacity: 0.5,
                    width: 1,
                    curveness: 0
                }
            },
            edgeLabel: {
                normal: {
                    show: true,
                    formatter:'{a}{b}{c}',
                    textStyle: {
                        fontSize: 12
                    }
                }
            },
        }
    ]
};

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3302

**Comment by guopengno1** [comment]
您好，我用在线编辑器能看效果吗？还是得下载最新代码，在本机看？谢谢你

**Comment by pissang** [comment]
得下载最新代码或者等下个版本（大概在这个月中发布

**Comment by guopengno1** [comment]
也就是我调试的时候，最好是在本机调试对吗？我不太会用这个github，我下载的时候 只知道可以选择版本，但不知道怎么下载最新的代码，我太笨了，谢谢你耐心解释
