### ISSUE TITLE
echarts3.0 option中的title 属性可否添加图片作为标题 

### ISSUE THREAD

**Issue by xhraymond** [ecomfe/echarts#3385]
#### 问题简述 (One-line summary)
如题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome  版本 45.0.2454.93 m
+ 操作系统类型和版本 (OS Version): windows 7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行
