### ISSUE TITLE
IE11下保存图片不是直接保存，是新打开标签页显示图片。

### ISSUE THREAD

**Issue by jeatime6** [ecomfe/echarts#3386]
IE11下saveAsImage不是直接弹出保存图片，是新打开标签页显示图片；
不知道能否修改，或者能否告知是什么原因？非常感谢。

![7ae3 tmp](https://cloud.githubusercontent.com/assets/6733968/15888799/ffc65412-2d9a-11e6-83ce-86218cdfa95c.jpg)

**Comment by pissang** [comment]
因为 IE11 不支持直接下载生成的图片

**Comment by Jonham** [comment]
不支持 download属性的缘故吗？
