### ISSUE TITLE
graph中force图问题

### ISSUE THREAD

**Issue by guopengno1** [ecomfe/echarts#3387]
#### 问题简述 (One-line summary)

现在版本中，是可以实现，一个节点拖动之后，其他节点保持不动，并且松开鼠标后，再拖动另一个节点，保持其他节点不动。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
force 不行
