### ISSUE TITLE
Support label formatter on sankey diagram

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3393]
Version: 3.1.10

There doesn't seem to be an option to support custom formatter on the sankey diagram. 

This would be really helpful as in some situations, I need two nodes with the same name to be present in one diagram:

![image](https://cloud.githubusercontent.com/assets/561365/15895456/b6d760ac-2d8b-11e6-9ea7-da89c659c920.png)

Note "Bulgaria -> Romania" and "Romania -> Bulgaria" link. This actually freezes when rendering so I need to add different name to nodes such as "source-Bulgaria", "target-Bulgaria" and then format differently when displayed. I've fixed this issue in this example by simply adding empty space before source nodes.

**Comment by 100pah** [comment]
(1) `label.normal.formatter` can be used to customize formatter, although it not occurs in doc, which is an omission.

```javascript
series: [{
    type: 'sankey',
    label: {
        normal: {
            formatter: '{b}'  // {b} is the node.name, or you can use a callback function here.
        }
    }
}]
```

(2) Besides `name`, each `node` in data can be identified by attribute `id`, for eg: 
```javascript
series: [{
    data: [
        {id: 'source - Romania', name: 'Romania'},
        {id: 'target - Romania', name: 'Romania'},
        ...
    ]
}]
```

**Comment by jarben** [comment]
Thanks so much for your reply @100pah , both options are very useful!
