### ISSUE TITLE
axisLabel使用rotate参数时文本颜色发生改变

### ISSUE THREAD

**Issue by AtlantisLeo** [ecomfe/echarts#3394]
#### 问题简述 (One-line summary)
axisLabel使用rotate参数时文本颜色发生改变，文字从设置好的颜色变回默认颜色

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.7
+ 浏览器类型和版本 (Browser version):chrome 50.0.2661.102 m (64-bit)
+ 操作系统类型和版本 (OS Version):windows 7

#### 重现步骤 (Steps to reproduce)
1.由于axisLabel.textStyle.color默认颜色为‘#333’，我更改为‘#000000’
2.当在axisLabel使用rotate参数时，发现文本颜色变回‘#333’

#### 期望结果 (Expected behaviour)
axisLabel使用rotate参数时文本颜色不要发生改变

#### ECharts配置项 (ECharts option)

```javascript
option = {
backgroundColor:'#FFFFFF',
      		  tooltip: {
  		        trigger: 'axis',
  			        axisPointer : {    
  			          type : 'shadow'     
  				      }
  		      },
  		      calculable: true,
  		      grid: {
              y2:120
      	    },
  		      xAxis: [{
      		    type: 'category',
      		    axisLabel: {
								rotate: 30,
								interval:0,
								textStyle:{
									color:'#000000'
								}
							},
							axisTick:{
								interval:0
							},
      		    data: []
      		  }],
      		  yAxis: [{
      		    type: 'value'
      		  }],
      		  series: [{
      		    type: 'bar',
      		    data: [32, 30, 30, 33, 39, 33, 32, 33, 39, 33]
      		  }]
}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/19500565/15953266/8b194d10-2efb-11e6-9d8c-9782bd31c5a7.png)
![image](https://cloud.githubusercontent.com/assets/19500565/15953268/8fc53dd8-2efb-11e6-82a6-8f29413834e9.png)

**Comment by 100pah** [comment]
可能是字体有点变虚，把字体调大些试试？
