### ISSUE TITLE
legend颜色和node.itemStyle.normal.color不匹配

### ISSUE THREAD

**Issue by stevenlcf** [ecomfe/echarts#3396]
#### 问题简述 (One-line summary)
在series-graph中，legend可以控制两类点的出现和隐藏，但是颜色与两类点不匹配。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version): Safari 9.1.1
+ 操作系统类型和版本 (OS Version): OS X EI Capitan 10.11.5

#### 重现步骤 (Steps to reproduce)
1. 基于官网的<a href="http://echarts.baidu.com/demo.html#graph">这个例子</a>，我把gexf文件换成我需要展现的网络信息（含有两类点），然后把categories数组的维度和每个维度的名字都换成对应的信息。
2. 然后用graph.nodes.forEach将每个点根据所属类别设置node.category和node.itemStyle.normal.color。
3. 效果是：两类点可以以我设置的两种颜色显示，两种legend可以分别控制两类点的出现和隐藏。但是legend的颜色还是<a href="http://echarts.baidu.com/demo.html#graph">这个例子</a>中的前两类的颜色，而不是我设置的每类点的颜色。

#### 期望结果 (Expected behaviour)
legend的颜色是对于类别点的颜色。

#### 可能哪里有问题 (What went wrong)
不知道在哪里设置legend的颜色，用color属性设置默认颜色也没有用。

**Comment by 100pah** [comment]
在 series 中设置 color list 即可。

```javascript
series: [{
    type: 'graph',
    color: ['red', 'blue'],
    ...
}]
```

**Comment by stevenlcf** [comment]
已解决。
解决方法：分别设置两类的series.categories[i].itemStyle.normal.color。
