### ISSUE TITLE
series.graph中能否实现长度为一跳的连通支的高亮显示？

### ISSUE THREAD

**Issue by stevenlcf** [ecomfe/echarts#3397]
#### 问题简述 (One-line summary)
series.graph中，如果选中一个节点，能否让{这个节点，这个节点连接的边，这个节点的邻居节点（距离这个节点一条边/一跳）}这三种元素一起高亮显示？即，当鼠标在一个点上悬停的时候，能否让除了它自己以及和它相连接的点和边，其他的点和边都变暗？

**Comment by pissang** [comment]
下个版本支持

**Comment by stevenlcf** [comment]
请问下一个版本什么时候release？
我现在想通过修改echarts库函数，自己实现这个功能。我的想法是通过改变判断emphasis状态的条件（从hover自己变成hover自己或者相邻的边或点）来实现。请问判断这个条件的函数是什么，或者有什么其他的建议？谢谢！

**Comment by pissang** [comment]
本周或下周初 release

**Comment by stevenlcf** [comment]
我在用echarts做个demo，但是这周六截止日期...我自己先尝试改改，持续关注echarts新版本的发布！😄

**Comment by pissang** [comment]
你可以看 github 上最新的代码 `src/chart/graph/GraphView.js`

**Comment by stevenlcf** [comment]
好的，O(∩_∩)O谢谢！

**Comment by stevenlcf** [comment]
是不是 **Graph add focusNodeAdjacency** 这个commit下的修改？
设置 **option.focusNodeAdjacency: true** ？

**Comment by pissang** [comment]
是的

**Comment by stevenlcf** [comment]
我按照<a href="https://github.com/ecomfe/echarts/commit/b6c83a04d0701a92b61d1c3c007d9170fec3b091">Graph add focusNodeAdjacency</a>这个commit把3.1.10版本的**echarts.js**对应位置替换了代码，并且设置 **option.focusNodeAdjacency: true**，可以单个emphasis效果但是还是没有一跳连通枝的高亮效果。请问这样操作存在什么问题吗？
另外，能不能直接使用master中的scr的**echarts.js**？我直接用scr/echarts.js有两条错误信息：
1. Can't find variable: define
2.  'echarts.init' is undefined

谢谢！

**Comment by pissang** [comment]
直接用源代码可以参考 test 下的示例配置环境

**Comment by stevenlcf** [comment]
发现一个possible bug：
我已经实现了**option.focusNodeAdjacency: true**的一跳连通支emphasis，但是如果鼠标hover在一个孤立点（没有入边，出边和临接点）上，这个孤立点不会被高亮，而是所有点都灰了。

**Comment by stevenlcf** [comment]
在点亮中心点的各条边的两个端点之前加一句`fadeInItem(node, nodeOpacityPath);`即可。
我提交了一个commit  `7c6e6b1`  来加这句话。

**Comment by pissang** [comment]
谢谢
