### ISSUE TITLE
echarts图像整体旋转

### ISSUE THREAD

**Issue by penweizgx** [ecomfe/echarts#3398]
在不同的浏览器下实现图像整体旋转，pc和手机的显示比例不一样，例如在pc上正常显示的图，在手机上最好就需要旋转90或-90度进行查看，安装官方的demo可以调换x，y轴的位置，也可以翻转，单显示出来的效果没有预期的图整体旋转效果。。

**Comment by 100pah** [comment]
或许可以考虑：
（1）在 echarts 之外解决，比如使用 css transform。或者，
（2）尝试 echarts 提供的 [media query](http://echarts.baidu.com/tutorial.html#%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%87%AA%E9%80%82%E5%BA%94)

**Comment by Guanyuhao** [comment]
使用css transform 之后 echart 图会失真

**Comment by Guanyuhao** [comment]
老哥解决这个问题了吗
