### ISSUE TITLE
如何禁止联动图表之间的tooltip联动？

### ISSUE THREAD

**Issue by shikelong** [ecomfe/echarts#3399]
#### 问题简述 (One-line summary)

现有一个pie chart和一个堆叠的bar chart，拥有相同的legend并联动。但是bar chart的y轴并不是legend.而是其他数据。  现在图表之间的tooltip联动默认是以数据在绑定的数据源数组中的序号来对应的。实际上这两个图表的数据源数据长度并不相同。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): v3.x.x

#### 期望结果 (Expected behaviour)

可以选择性的禁用两个联动图表之间tooltip的联动显示。

谢谢。

**Comment by 100pah** [comment]
可否提供下 option？

**Comment by shikelong** [comment]
恩 理解了 谢谢。
