### ISSUE TITLE
移动端 tooltip 能否实现手指抬起后自动消失

### ISSUE THREAD

**Issue by ifci** [ecomfe/echarts#3401]
#### 问题简述 (One-line summary)
移动端折线图的 tooltip，在点击后会一直显示，除非再点击周围别的地方才会消失，能否实现手指抬起后就自动隐藏

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  v3.x.x

**Comment by pissang** [comment]
不行，移动端原先就不合适 pc 端那种交互的 tooltip，建议一直固定在某个位置显示

**Comment by mangoZT** [comment]
自己定义touch事件  改变tooltip属性

**Comment by arssam** [comment]
@mangoZT 你好，具体怎么做啊？

**Comment by ellyliang** [comment]
这个支持点击其他地方隐藏吗
