### ISSUE TITLE
问题：如何实现多图例，不连续折线

### ISSUE THREAD

**Issue by KlausYork** [ecomfe/echarts#3402]
#### 问题简述 (One-line summary)
我现在有两个需要实现的折线。横坐标是时间 纵坐标是值
比如：
第一个折线是 1月1日-5,1月2日-3,1月5日-6，1月7日-9
第二个折线是 1月2日-3,1月3日-7,1月5日-12

我传过来的集合就是这样的。
我前端如何处理可以显示这样的两个不连续的折线

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):Echart2
+ 浏览器类型和版本 (Browser version):Chrome 51
+ 操作系统类型和版本 (OS Version):Windows 10

#### 期望结果 (Expected behaviour)
同时显示两条不连续的折线。

#### 可能哪里有问题 (What went wrong)
现在如果直接显示的话，时间轴会显示最长的时间轴，但是点都会因为无法对应都堆到前边

**Comment by pissang** [comment]
用空值，或者 x 轴用 time 类型
