### ISSUE TITLE
鼠标悬浮的时候可以同时设置几个地区同时高亮吗？（map）

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#3407]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以通过 dispatchAction 高亮需要的地区

**Comment by chm74** [comment]
恩，已经看着文档，写出来了，谢谢
