### ISSUE TITLE
[新手求助] echarts3和百度地图整合问题

### ISSUE THREAD

**Issue by fjhzxiao** [ecomfe/echarts#3408]
#### 问题简述 (One-line summary)

echarts2官方例子有例子整合，想在echarts3也尝试整合。
但是，地图模板不一致，坐标不能正确转换。

通过查看echarts2的例子中发现，series的data设置  type：‘map’，并且mapType设置：‘none’，
然后通过百度地图的API经纬度转换。

但是echarts3 mapType设置为none就会报错
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
参考 https://github.com/ecomfe/echarts/issues/3116 这个回答和 https://github.com/ecomfe/echarts/blob/master/test/bmap.html 这个示例
