### ISSUE TITLE
关于 Echarts 3.1.10 Pie Label 显示位置的 需求

### ISSUE THREAD

**Issue by zhaoyangsoft** [ecomfe/echarts#3409]
#### 问题简述 (One-line summary)

饼图 label 在设置 为 inside 的时候，
能否根据 字体的长度和 扇区的大小 判断 label是否能完全显示在扇区内，
可以 则显示，
不可以则 该扇区自动转换为 outside

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}


```

#### 其他信息 (Other comments)
如下图： 

 
![image](https://cloud.githubusercontent.com/assets/1456421/15995863/f22915ee-3153-11e6-87ef-0a644acba03b.png)

**Comment by pissang** [comment]
暂时不行

**Comment by zhaoyangsoft** [comment]
业务的需要， 我写了一个插件 ，支持了这种情况.
