### ISSUE TITLE
关于visualMap视觉映射组件的取值

### ISSUE THREAD

**Issue by halonemo** [ecomfe/echarts#3410]
echarts3

开发中需要用到bar 柱状图。
并且柱状图X轴为value轴，Y轴为category轴。

需求为：负数value显示绿色，正数value为红色。

发现【visualMap数据映射是以Y轴为数据轴】，导致无法跟踪X的value给bar对应的颜色。

**Comment by pissang** [comment]
可以设置 http://echarts.baidu.com/option.html#visualMap-continuous.dimension

**Comment by halonemo** [comment]
太感谢了。dimension:0 解决了我的问题

**Comment by fanhaipeng0403** [comment]
遇到了同样的问题,实在太感谢了 @halonemo @pissang
