### ISSUE TITLE
【新人求助】如何修改markline和markpoint的data而不重新绘制

### ISSUE THREAD

**Issue by sduxiaoxiang** [ecomfe/echarts#3411]
#### 问题简述 (One-line summary)
地图上绘制线的时候，当连线的数据发生变化时，使用delmarkline删除当前绘线，然后在addmarkline绘制一条新线，此时页面会有一个明显重新绘制的过程。如何能够直接更新markline和markpoint的值而不用重新绘制当前连线。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.0
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
换成 3
