### ISSUE TITLE
map Json方式引入提示错误

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#3413]
#### 问题简述 (One-line summary)
提示错误：
jquery-1.10.2.js:8706 XMLHttpRequest cannot load file:///E:/chm/em-map/em-map/json/china.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version): 
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

```js
$(function(){
		$.get('json/china.json', function (chinaJson) {
			echarts.registerMap('china', chinaJson);
			var chart = echarts.init(document.getElmentById('chart'));
			chart.setOption({
				series: [{
					type: 'map',
					map: 'china'
				}]
			});
		});
	})
```

**Comment by pissang** [comment]
跨域加载的错误

**Comment by chm74** [comment]
我用http://localhost/..,加载就请求不到我的json数据，
