### ISSUE TITLE
echarts markPoint 颜色显示不对

### ISSUE THREAD

**Issue by oneroundseven** [ecomfe/echarts#3418]
#### 问题简述 (One-line summary)
markPoint颜色为什么不是跟着dayaRange的范围取色的？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1. 打开 http://echarts.baidu.com/gallery/editor.html?c=effectScatter-map
2. 修改series代码
````javascript
    series : [ 
        { 
            name: 'Top 5', 
            type: 'effectScatter', 
            coordinateSystem: 'geo', 
            markPoint: { 
                symbol: 'circle', 
                symbolSize: 50, 
                effect : { 
                    show: true, 
                    shadowBlur : 0 
                }, 
                itemStyle: { 
                    normal: { label: {show: false} 
                }, 
                emphasis: { 
                    label: { position: 'top'} } 
                }, 
                data: [ 
                    { coord : [121.48, 31.22], value: 20 } 
                ] 
            } 
        } 
    ]
`````
3. 增加dataRange
````javascript
    dataRange: {
        min : 0,
        max : 100,
        x: 'right',
        calculable : true,
        color: ['#ff3333', 'orange', 'yellow','lime','aqua'],
        textStyle:{
            color:'#fff'
        }
    }
````

#### 期望结果 (Expected behaviour)
显示对应的vlaue对应dataRange上的数值的颜色
应该画出来是绿色的圈

**Comment by pissang** [comment]
3 中 markPoint 用来辅助标识，不支持 visualMap（dataRange）来编码颜色，需要编码颜色的用 geo 组件上的散点图

**Comment by oneroundseven** [comment]
@pissang  感谢回答 其实我就想实现2.0版本里面 http://echarts.baidu.com/echarts2/extension/BMap/doc/BMap.html 这个示例的效果 那个波纹的颜色和dataRange对应 并且波纹的效果可以定义成一样的 或者自定义动画  问下改选择那种类型呢？ 不是effectScatter么？ 通过data 不通过markPoint实现？

**Comment by pissang** [comment]
用 effectScatter

**Comment by oneroundseven** [comment]
@pissang  http://echarts.baidu.com/option.html#series-effectScatter.data   effectScatter貌似不支持经纬度方式？

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=effectScatter-map
