### ISSUE TITLE
折线图怎样画折线上点到X轴的竖线以及怎样有一点偏移？

### ISSUE THREAD

**Issue by kaixin3946** [ecomfe/echarts#3419]
①现在是这样的：
![image](https://cloud.githubusercontent.com/assets/13850484/16032908/7626d70e-323b-11e6-9f86-764c93a4144c.png)
我希望是这样的：
![image](https://cloud.githubusercontent.com/assets/13850484/16032936/b66e2cfe-323b-11e6-888f-2597e8c87b66.png)
但是目前没有找到这样的属性啊，有什么办法吗~
②我希望两条折线不完全重合，就是有一点偏移，现在这样：
![image](https://cloud.githubusercontent.com/assets/13850484/16033005/2981014e-323c-11e6-890f-5c61a1438785.png)
这里两条线第一段红黑两条线重合了，而我希望是这样：
![image](https://cloud.githubusercontent.com/assets/13850484/16033197/47e3aeb0-323d-11e6-91d1-125586aad82b.png)
就是两条线稍微有一点偏移

求教大神~~
我用的是echart v3.1.10 。

**Comment by jodo4x** [comment]
同问

**Comment by pissang** [comment]
1 不行，2 没懂

**Comment by kaixin3946** [comment]
好的，感谢回复~ 
关于问题一，我还想问下 series→{type:line}→data→itemStyle→normal→barBorderCorlor、barBorderWidth这两个属性是什么意思，柱条的描边颜色，说的不是单个点到X轴的柱条是什么呢？
![image](https://cloud.githubusercontent.com/assets/13850484/16065229/785b0dba-32db-11e6-9e15-1d6ac66b0d4a.png)
问题二：正常折线图的两份数据，即：series:{{name:"name1",data:[]},{name:"name2",data:[]}},这样写画出来的图形是
![image](https://cloud.githubusercontent.com/assets/13850484/16065320/41855f9c-32dc-11e6-882d-6365ff9cf41f.png)
在这里，周一和周二两天里这两条线重合了，我希望第二条线可以设置一个初始的X轴值，让他不是0，而是1或者1.1，这样避开第一条线的宽度让两条折线以及折线点到X轴折线都可以显示~

想要实现的效果图：
![image](https://cloud.githubusercontent.com/assets/13850484/16065481/bebf6966-32dd-11e6-94ef-842cc95bb9c9.png)

谢谢~

**Comment by pissang** [comment]
第一抱歉是文档错误，itemStyle 是折线图拐点的样式，配置项见 http://echarts.baidu.com/option.html#series-line.itemStyle.normal

第二点建议红色用一条更宽的折线防止被蓝色折线遮挡，具体可以设置 http://echarts.baidu.com/option.html#series-line.lineStyle.normal.width

**Comment by kaixin3946** [comment]
好哒，知道啦~非常感谢~~
