### ISSUE TITLE
动态刷新问题

### ISSUE THREAD

**Issue by tiant796180** [ecomfe/echarts#3420]
我原来在使用2.0版本时候 在刷新时候 
直接_chart.setOption(option) 全部属性 图形dataZoom和通过toolbox切换的图形 都会继续保持 只是数据更新了 这种效果很好 也许是误打误撞的功能

升级3.0后 _chart.setOption(option)会将图形的dataZoom和toolbox切换的图形全部重置 
这个倒也理解 只能更新data数组 但是当多线图时候 并不是很方便 只能解析结果集 然后按顺序一个一个更新data 这个只能这么做吗？
我本来打算
```js
	_chart.setOption({
				series: chart.series
			});
```
但是发现也不行 因为有"type":"line" 会覆盖toolbox切换的图形
求教下 有没有简单的方法

**Comment by tiant796180** [comment]
var series = [];
			for(var i=0;i<chart.series.length;i++){
				series.push({"data":chart.series[i].data});
			}
			_chart.setOption({series:series });

这样倒是可以 就是有点别扭

**Comment by pissang** [comment]
建议用回复中的方式，这是更合理的
