### ISSUE TITLE
在柱状堆积图中，关于trigger的item，和axis值 对tooltip 内容的影响的问题

### ISSUE THREAD

**Issue by ready360go** [ecomfe/echarts#3421]
#### 问题简述 (One-line summary)
官网demo：
http://echarts.baidu.com/demo.html#bar-stack
目前的
    若 trigger属性值设置为item： 则 鼠标移入后 tooltip 显示内容为每一个bar的seriesname  和 value 内容。
    若 trigger属性值设置为axis： 则鼠标移入后tooltip显示内容为全部bar的seriesname  和 value 内容。

可否增加一个属性 xxx: 鼠标移入后 tooltip显示内容为同属一个stack值得seriesname  和 value 
         如demo中 ：
![image](https://cloud.githubusercontent.com/assets/16661632/16034752/0b12b18a-3246-11e6-97ee-b73f6d0ebf34.png)

不知现有的内容是不是可以通过某些方式实现这样的效果，如果有烦请告诉我应该如何设置，如果没有后期是否可以增加此效果

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
目前不行，也暂时不会考虑加入这个
