### ISSUE TITLE
bar + 不是完整的一整高的小方块的bar

### ISSUE THREAD

**Issue by carly1987** [ecomfe/echarts#3426]
#### 问题简述 (One-line summary)
![image](https://cloud.githubusercontent.com/assets/4493524/16039270/605b9afc-325b-11e6-8433-9207e0e7666e.png)

这样的图标可以做到么？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行
