### ISSUE TITLE
点击legend中的一项，图标中 这个 series就会隐藏，再点击则会出现

### ISSUE THREAD

**Issue by carly1987** [ecomfe/echarts#3427]
#### 问题简述 (One-line summary)
![image](https://cloud.githubusercontent.com/assets/4493524/16039334/be267896-325b-11e6-8537-d24266057f3e.png)
点击legend中的一项，图标中 这个 series就会隐藏，再点击则会出现

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
这是 feature 不是 bug，想要关闭设置 selectedMode: false

**Comment by carly1987** [comment]
我知道这个不是bug。就是想要请教这样如何写。
但是，我想要的不仅仅是 隐藏图例选择。而是和图例中的每一项进行交互。比如，我点击图中的订阅，图表中对应的订阅（紫色）的线条就消失，响应的，刚才被触发点击的订阅的这个图例，会变灰。
