### ISSUE TITLE
axisTick和axisLabel的显示位置问题

### ISSUE THREAD

**Issue by skyitachi** [ecomfe/echarts#3428]
#### 问题简述 (One-line summary)
当类目轴有boundaryGap的时候，axisTick还是从坐标轴的一开始画，但是axisLabel是从一段偏移之后开始画的，会导致axisTick和axisLabel在显示上有偏差
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):v3.1.9
+ 浏览器类型和版本 (Browser version):  53.0.2766.0 canary (64-bit)
+ 操作系统类型和版本 (OS Version):mac os x

#### 重现步骤 (Steps to reproduce)
1.见option

#### 期望结果 (Expected behaviour)
**axisLabel有关于位置的选项**或者**axisTick绘制的时候就考虑到boundaryGap**

#### 可能哪里有问题 (What went wrong)

axisTick绘制的时候，*是否考虑过boundaryGap*

#### ECharts配置项 (ECharts option)

```javascript
option = {
     color: ["#0089cd", "#999999"],
     grid: { top: 30 },
     yAxis: {
           axisLine: { show: true, lineStyle: { color: "#eeeeee", width: 2 } },
           axisTick: { show: true, lineStyle: { color: "#eeeeee", width: 2 } },
           splitLine: { show: true, lineStyle: { color: '#e7e7e7', type: "dotted"} },
           type: "value",
           axisLabel: { textStyle:
                {
                    fontFamily: "Helvetica",
                    fontWeight: "lighter",
                    color: "#666"
                }
           },
           splitLine: { show: true, lineStyle: { color: '#e7e7e7' } }
      },
      xAxis: {
          type: "category",
          boundaryGap: false, // 改回true试试
          axisLine: { show: true, lineStyle: { color: "#eeeeee", width: 2 } },
          axisTick: { show: true, lineStyle: { color: "#eeeeee", width: 2 } },
          axisLabel: { show: true , textStyle:
                {
                    fontFamily: "Helvetica",
                    fontWeight: "lighter",
                    color: "#666"
                },
                interval: function (idx) { return idx % 2 === 0;}
          },
          data: ["00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"]
      },
      tooltip: {
           show: false
      },
      series: [
          {type: "line", data: (new Array(24)).fill(2)},
          {type: "line", data: (new Array(24)).fill(3)}
      ]
}

```

#### 其他信息 (Other comments)

boundaryGap为false的情况：
![qq20160614-1](https://cloud.githubusercontent.com/assets/3816806/16042348/e24c4820-326c-11e6-8689-6b56abe0cb95.png)

boundaryGap为true的情况
![qq20160614-0](https://cloud.githubusercontent.com/assets/3816806/16042364/eed62412-326c-11e6-97e4-c23a0773655c.png)

**Comment by skyitachi** [comment]
你的意思是说在boundaryGap:true的时候axisTick无法和axisLabel实际对应？

**Comment by pissang** [comment]
boundaryGap: true 的时候 label 在两个 tick 之间

**Comment by skyitachi** [comment]
柱状图这种情况看起来就很好，但是折线图的情况下这样axisLabel和axisTick错开的情况不是很直观，也可能是我对axisTick理解错了，希望axisLabel有针对显示位置的选项
