### ISSUE TITLE
希望echarts散点图可以画曲线，现在只可以用起止点画直线

### ISSUE THREAD

**Issue by cccccdn** [ecomfe/echarts#3429]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以使用 graph， http://echarts.baidu.com/gallery/editor.html?c=graph-life-expectancy

**Comment by cccccdn** [comment]
谢谢，发现也可以用这个模拟http://echarts.baidu.com/demo.html#line-easing

**Comment by guntertien** [comment]
希望可以画曲线，直角曲线
