### ISSUE TITLE
X轴 nameGap 在 nameLocation 为 'start'  'end' 并不是坐标轴名称与轴线之间的距离

### ISSUE THREAD

**Issue by TimCN** [ecomfe/echarts#3433]
#### 问题简述 (One-line summary)

将 X轴 nameLocation 设置为  'start'  'end'， 调整 nameGap 并不能得到理想效果，

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.将X轴 nameLocation 设置为  'start'  'end'
2.调整 nameGap 

#### 期望结果 (Expected behaviour)

和 nameLocation 设置为  'middle' 的结果一样

#### 可能哪里有问题 (What went wrong)

nameLocation 为  'start'  'end' 处理部分

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by zhouboluo** [comment]
nameGap能自动调整位置就好了，尤其是nameLocation=“middle”的时候，y轴数值太大就重合了

**Comment by TimCN** [comment]
@pissang ,你将 nameLocation 设置为  'end' 调整 nameGap ，看看name移动的方向 试试

**Comment by pissang** [comment]
标签在轴线的两端调整 nameGap 的时候像远离两端的防线移动是很自然的

**Comment by TimCN** [comment]
@pissang , 有时候，我需要的效果是要和middle 一样的，能不能和其他的属性一样，搞一个数组[x,y]，让我们自己决定偏移的方向
