### ISSUE TITLE
饼图（环图）label与title重叠

### ISSUE THREAD

**Issue by yuyanping39** [ecomfe/echarts#3434]
#### 问题简述 (One-line summary)
饼图的label是否可以设置与饼图的距离，现在遇到一个问题label与title重叠了

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
调整饼图或title位置
