### ISSUE TITLE
地图第2个系列的显示问题

### ISSUE THREAD

**Issue by wyw1101** [ecomfe/echarts#3436]
#### 问题简述 (One-line summary)
地图中：第二个系列的数据显示不正常，导致第一个系列的数据多显示了第二个系列的数据（实际上第一个系列是没有这些数据的）

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version):crome
+ 操作系统类型和版本 (OS Version):windows 7

#### 重现步骤 (Steps to reproduce)
1.http://echarts.baidu.com.cn/demo.html#map-china-dataRange
2.把第一个系列“iphone3” 的data 改为只含有北京或者无数据
3.第二个系列“iphone 4”重复显示了“iphone3”的系列

#### 期望结果 (Expected behaviour)

第一个系列不要显示第二个系列的数据

#### ECharts配置项 (ECharts option)

```javascript
option = {
	"series" : [{
		"name" : "系列0",
		"type" : "map",
		"mapType" : "china",
		"data" : [{
			"value" : 372,
			"name" : "北京"
		}, {
			"value" : 297,
			"name" : "天津"
		}, {
			"value" : 763,
			"name" : "上海"
		}, {
			"value" : 758,
			"name" : "重庆"
		}, {
			"value" : 246,
			"name" : "河北"
		}, {
			"value" : 681,
			"name" : "河南"
		}, {
			"value" : 541,
			"name" : "云南"
		}, {
			"value" : 376,
			"name" : "辽宁"
		}, {
			"value" : 731,
			"name" : "黑龙江"
		}, {
			"value" : 936,
			"name" : "湖南"
		}]
	}, {
		"name" : "系列1",
		"type" : "map",
		"mapType" : "china",
		"data" : [{
			"value" : 312,
			"name" : "安徽"
		}, {
			"value" : 955,
			"name" : "山东"
		}, {
			"value" : 747,
			"name" : "新疆"
		}, {
			"value" : 517,
			"name" : "江苏"
		}, {
			"value" : 335,
			"name" : "浙江"
		}, {
			"value" : 567,
			"name" : "江西"
		}, {
			"value" : 275,
			"name" : "湖北"
		}, {
			"value" : 95,
			"name" : "广西"
		}, {
			"value" : 122,
			"name" : "甘肃"
		}, {
			"value" : 805,
			"name" : "山西"
		}]
	}],
	"animation" : false,
	"legend" : {
		"data" : ["系列0", "系列1"]
	}
}

```

**Comment by wyw1101** [comment]
![1](https://cloud.githubusercontent.com/assets/12759975/16076582/8167b0e8-3326-11e6-904a-f4b78829dd70.png)
这是在线编辑的状况，也是这样

**Comment by GalinaGao123** [comment]
这个问题解决了吗？我刚刚试了下在线编辑的。还是有这样的问题。包括tooltip显示的也不对
![default](https://cloud.githubusercontent.com/assets/16570238/16369999/ca6c758e-3c6e-11e6-848a-794cae39695a.png)

**Comment by wyw1101** [comment]
我重新下了个试了下，地图的点好了，tooltip提示只要有点，所有系列名都出现了
![image](https://cloud.githubusercontent.com/assets/12759975/16484260/ee500938-3eea-11e6-81f1-0a027ea0483f.png)

**Comment by pissang** [comment]
@wyw1101 谢谢反馈，修复地图的点带来的 bug，已修复
