### ISSUE TITLE
ECharts后期有考虑图形颜色渐变和2.5D的伪立体视觉吗

### ISSUE THREAD

**Issue by Jack-93** [ecomfe/echarts#3437]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
颜色渐变见 http://echarts.baidu.com/gallery/editor.html?c=area-simple，伪立体没有

**Comment by Jack-93** [comment]
我想要的是饼图的颜色渐变，感觉echarts除了文档更习惯，与Highcharts的功能和细节差距开始拉大了。
