### ISSUE TITLE
effectScatter 动画相关问题请教

### ISSUE THREAD

**Issue by oneroundseven** [ecomfe/echarts#3439]
#### 问题简述 (One-line summary)
1、使用 effectScatter 画动态波纹效果；
2、我会动态修改 effectScatter 的data数据
3、显示出来的效果是上次波纹动画没有执行完，如果这个时候重置option的话，上次动画就消失了

#### 期望结果 (Expected behaviour)
上次动画没有执行结束的继续执行，不受setOption影响；

#### 其他信息 (Other comments)

![conver](https://cloud.githubusercontent.com/assets/1825295/16106600/636b253c-33c8-11e6-9505-30672ebee04d.gif)

图片希望能看懂，默认我每次点按钮都会往data里面加数据，然后过一会清除
后面点击变快很明显看到波纹没有执行完就跳走了

**Comment by oneroundseven** [comment]
@pissang  首页感谢这么快就修复了这个问题；动画没有执行完就消失的问题已经没有了，
还有动画执行完了数据更新的时候点会在页面上直接动画移动过去，这个动画是不是可以去掉？
或者有什么配置能够实现么？

![231](https://cloud.githubusercontent.com/assets/1825295/16112409/c39bf4b0-33e9-11e6-9c85-d1fe127c8f7c.gif)

**Comment by pissang** [comment]
`animation: false` 或者 `animationUpdateDuration: 0` 试试

**Comment by riskers** [comment]
@oneroundseven 也遇到了动画没结束就需要重新setOption动态加载数据的问题，请问怎么配置的？

**Comment by billfeller** [comment]
同问，这个问题解决了吗，使用echarts 3.8.4 遇到一样的问题

**Comment by billfeller** [comment]
@pissang 遇到了动画没结束就需要重新setOption动态加载数据的问题，请问怎么配置的？

**Comment by changy2013** [comment]
我现在用的4.0版本 重新setOption动画还是不连续

**Comment by fdjhcg** [comment]
可以清空数据在添加数据，就不会出现现在已经绘制的线在跟新是迁移过去的现象，而是重新绘制
