### ISSUE TITLE
ECharts v3.1.10 ‘click’ 事件

### ISSUE THREAD

**Issue by Sammi4fun** [ecomfe/echarts#3440]
#### 问题简述 (One-line summary)

点击图中灰色区域时，没有触发 ‘click’ 事件。
不知道点击该区域时是否会触发 ‘click’事件？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):chrome 50.0.2661.102
+ 操作系统类型和版本 (OS Version):OS X EI Capitan 10.11.5

#### 期望结果 (Expected behaviour)
期望能触发 ‘click’ 事件

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![2016-06-16 3 33 11](https://cloud.githubusercontent.com/assets/7160119/16108849/371e9b16-33d8-11e6-80cb-d84cd4be139c.png)

**Comment by pissang** [comment]
不会触发该事件

**Comment by Sammi4fun** [comment]
请问有什么办法可以触发 ‘click’ 事件呢？

**Comment by pissang** [comment]
`myChart.getZr().on('click')` 可以监听到整个画布的 click 事件

**Comment by Sammi4fun** [comment]
我其实是想在 click 事件中，获取到 tooltip 里面的信息，不知道有什么办法？

**Comment by pissang** [comment]
有 showtip 事件

**Comment by zombieJ** [comment]
@pissang ，在点击点的时候`getZr`的`click`事件和chart的`click`事件同时会触发。我尝试在chart的`click`中调用`stopPropagation`告知没有这个方法。

目前用一个boolean存储chart click，用setTimeout重置来阻止`getZr`同时触发`click`事件。我觉得这里可以enhance一下，加个stop方法。

**Comment by pissang** [comment]
@zombieJ 嗯可以考虑

**Comment by hustcc** [comment]
为什么都没没有理解issue楼主的意思呢？@pissang @zombieJ

**Comment by hustcc** [comment]
目前 echarts 的 events 中有 click 事件，楼主在一个 bar 图表中设置监听 click 事件之后，希望：

1. 点击图表中灰色区域也能响应 click 事件；
2. 可以获得点击点在 y 轴或者 x 轴的数据；

以上两点是 **与** 的关系。

echarts 的 click 事件可以获得 x，y数据，但是没有监控灰色区域，zr 的 click 可以监听灰色区域，但是不能或取点击点的数据。

----

我遇到同样的问题，搜索了 echarts 的 issue，几乎全部翻了一遍，很多类似的问题，但是官方都没有解答清楚，回复都是 使用 zr 监控 click。例如：#3853。

**Comment by leixu2txtek** [comment]
目前也遇到相同的问题，图表中数据差距太大导致小数据的图表显示很小，几乎不可能点击到。。。

**Comment by ZhuGYao** [comment]
这东西真的好气，关键时候了发现timeline的前进后退键无法被click事件捕获到。。
