### ISSUE TITLE
TypeError: echarts.registerMap is not a function.

### ISSUE THREAD

**Issue by RubyChou** [ecomfe/echarts#3442]
#### 问题简述 (One-line summary)
注册地图失败，报错如下：
TypeError: echarts.registerMap is not a function. (In 'echarts.registerMap('china', chinaJson)', 'echarts.registerMap' is undefined)
不知道是不是我的引用写错了。

用require引用的时候也是这个错误，如图二

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):latest
+ 浏览器类型和版本 (Browser version):safari
+ 操作系统类型和版本 (OS Version):os x

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

<img width="663" alt="2016-06-16 4 51 56" src="https://cloud.githubusercontent.com/assets/19970946/16110895/baa70518-33e2-11e6-9989-b96b663da285.png">

<img width="498" alt="2016-06-16 4 53 59" src="https://cloud.githubusercontent.com/assets/19970946/16110954/01c06cdc-33e3-11e6-8b1e-b64b2aaf3155.png">

**Comment by pissang** [comment]
你用的是 2 版本，这个方法是 3 的
