### ISSUE TITLE
当报表数据全为0时，Y轴自动划分5等分

### ISSUE THREAD

**Issue by fangfangyang** [ecomfe/echarts#3444]
#### 问题简述 (One-line summary)
当报表数据都是0的时候，Y轴自动划分为5分，依次为0,、0.2、0.4、0.6、0.8、1

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.6
+ 浏览器类型和版本 (Browser version):chrome45
+ 操作系统类型和版本 (OS Version):win2007

#### 重现步骤 (Steps to reproduce)
1.报表数据都是0的情况

#### 期望结果 (Expected behaviour)

Y轴不要划分多段，直接只显示0即可。（有时候统计的是人数等，不能出现小数情况）

#### ECharts配置项 (ECharts option)

```javascript
option = {
tooltip: {
        trigger: 'axis'
    },
    xAxis: {
        type: 'category',
        splitLine: {
            show: false
        },
        data:["k1"]
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: '模拟数据',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: [{name:"test",data:[0]}]
    }]
}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#xAxis.minInterval

**Comment by fangfangyang** [comment]
@pissang 设置了，无效

**Comment by pissang** [comment]
换成最新版本 3.1.10
