### ISSUE TITLE
echarts3.0 tooltip position function (point, params, dom) dom is null

### ISSUE THREAD

**Issue by mdreamloving** [ecomfe/echarts#3446]
#### 问题简述 (One-line summary)
echart3.0中,根据dom的宽度设置tooltip的位置,柱形图,
position中的function(point,params,dom)
在console中,dom=null..请问这是何解

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.tooltip.formatter = t
2.function t (params,id,ticket,callback){
return table;}
3.position function(point,params,dom){
}中的dom = null获取不到长度

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 什么版本？
