### ISSUE TITLE
markLine设置隐藏没有作用？normal、emphasis都设置了

### ISSUE THREAD

**Issue by kaixin3946** [ecomfe/echarts#3447]
使用版本：echarts   v3.1.10 。
设置了markline  的label却无效：
 
![image](https://cloud.githubusercontent.com/assets/13850484/16139794/a9862d86-347d-11e6-9380-218f99bdf11d.png)

这样设置了，可是鼠标悬浮还是显示这样：
![image](https://cloud.githubusercontent.com/assets/13850484/16139815/d63b1fc6-347d-11e6-871a-7ede87c4349f.png)
如果不是label，那这个标签在哪里设置呢？
谢谢~

**Comment by pissang** [comment]
这个是 tooltip，不是 label
