### ISSUE TITLE
批量删除图表不能删除图例

### ISSUE THREAD

**Issue by mazl** [ecomfe/echarts#3449]
#### 问题简述 (One-line summary)
批量删除图表时不能删除对应的图例，单个删除时没有该问题
[index.txt](https://github.com/ecomfe/echarts/files/319797/index.txt)

 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (3.0):
+ 浏览器类型和版本 (Chrome 50+):
+ 操作系统类型和版本 (windows7 64位):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
批量删除是可以删除图例
#### ECharts配置项 (ECharts option)

```javascript
    'use strict';
        var myChart = echarts.init(document.getElementById('main'));
        var dataSeries = {
            fv3244: [{
                name: '2016-06-13T10:00:00',
                value: 10
            }, {
                name: '2016-06-13T11:00:00',
                value: 13
            }, {
                name: '2016-06-13T12:00:00',
                value: 11
            }],
            fv3fee: [{
                name: '2016-06-13T10:00:00',
                value: 15
            }, {
                name: '2016-06-13T11:00:00',
                value: 10
            }, {
                name: '2016-06-13T12:00:00',
                value: 11
            }]
        }

        function setData(dataSeries) {
            let series = [];
            for (let line in dataSeries) {
                series.push({
                    name: line,
                    showSymbol: false,
                    hoverAnimation: false,
                    data: dataSeries[line].map(p => p.value), //map y
                    type: 'line',
                    itemStyle: {
                        normal: {
                            color: 'rgb(255,70,131)'
                        }
                    }
                })
            }
            let xAxisData = []
            for (let line in dataSeries) {
                xAxisData = dataSeries[line].map(p => p.name)
                break;
            }

            let legend = []
            for (let line in dataSeries) {
                if (dataSeries[line] !== []) {
                    legend.push(line);
                }
            }

            myChart.setOption({
                title: {
                    text: '趋势图'
                },
                legend: {
                    data: legend
                },
                tooltip: {
                    trigger: 'axis',
                },
                xAxis: {
                    type: 'category',
                    data: xAxisData,
                },
                yAxis: {
                    type: 'value',
                    boundaryGap: [0, '100%'],
                },
                series
            });
        }
        setData(dataSeries)

```

#### 其他信息 (Other comments)

<button onclick="setData({fv3244:[]});">Remove One</button>
    <button onclick="setData({fv3244:[],fv3fee:[]})">Remove All </button>
    <div id="main" style="width:600px;height:400px;" />
    <script>
    'use strict';
        var myChart = echarts.init(document.getElementById('main'));
        var dataSeries = {
            fv3244: [{
                name: '2016-06-13T10:00:00',
                value: 10
            }, {
                name: '2016-06-13T11:00:00',
                value: 13
            }, {
                name: '2016-06-13T12:00:00',
                value: 11
            }],
            fv3fee: [{
                name: '2016-06-13T10:00:00',
                value: 15
            }, {
                name: '2016-06-13T11:00:00',
                value: 10
            }, {
                name: '2016-06-13T12:00:00',
                value: 11
            }]
        }

        function setData(dataSeries) {
            let series = [];
            for (let line in dataSeries) {
                series.push({
                    name: line,
                    showSymbol: false,
                    hoverAnimation: false,
                    data: dataSeries[line].map(p => p.value), //map y
                    type: 'line',
                    itemStyle: {
                        normal: {
                            color: 'rgb(255,70,131)'
                        }
                    }
                })
            }
            let xAxisData = []
            for (let line in dataSeries) {
                xAxisData = dataSeries[line].map(p => p.name)
                break;
            }

            let legend = []
            for (let line in dataSeries) {
                if (dataSeries[line] !== []) {
                    legend.push(line);
                }
            }

            myChart.setOption({
                title: {
                    text: '趋势图'
                },
                legend: {
                    data: legend
                },
                tooltip: {
                    trigger: 'axis',
                },
                xAxis: {
                    type: 'category',
                    data: xAxisData,
                },
                yAxis: {
                    type: 'value',
                    boundaryGap: [0, '100%'],
                },
                series
            });
        }
        setData(dataSeries)
    </script>

**Comment by mazl** [comment]
@pissang  这个问题有没有修改啊还是在你们那边没有重现？

**Comment by pissang** [comment]
你给的代码无法重新啊

**Comment by mazl** [comment]
你可以用我上传的 index.txt里的代码 ，我才试过是可以重现的的

**Comment by mazl** [comment]
这是代码 你可以试试

2016-07-13 11:00 GMT+08:00 Yi Shen <notifications@github.com>:

**Comment by pissang** [comment]
没看到你说的“删除”相关的代码啊

**Comment by pissang** [comment]
删除系列的话需要 `setOption({xxx}, true)`，不然新设置的会跟原先的合并，而不会删除

**Comment by mazl** [comment]
<button onclick="setData({fv3244:[]});">Remove One</button>
    <button onclick="setData({fv3244:[],fv3fee:[]})">Remove All </button>
在这里意思是把series值为空

2016-07-13 14:26 GMT+08:00 Yi Shen <notifications@github.com>:
