### ISSUE TITLE
dataZoom labelFormatter doesn't get access to data inside handler

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3451]
Version: 3.1.10

If I run this code: 
![image](https://cloud.githubusercontent.com/assets/561365/16147988/fe2d7282-3486-11e6-9b27-78a28fb413b0.png)

It returns:

![image](https://cloud.githubusercontent.com/assets/561365/16148006/1763008c-3487-11e6-8199-97b6627a17ef.png)

Where this is shown without specifying formatter: 
![image](https://cloud.githubusercontent.com/assets/561365/16148085/8f684b50-3487-11e6-9e6b-5048eadec076.png)

It's reproducible in your example: 
http://echarts.baidu.com/demo.html#area-rainfall

Although it returns numbers such as 1847, instead of dates:
![image](https://cloud.githubusercontent.com/assets/561365/16148116/c5f10acc-3487-11e6-9281-1aaea56d3ddc.png)

**Comment by pissang** [comment]
The parameter is data index, so you can get the date or other useful stuff by this data index. Like:

```js
labelFormatter: function (dataIndex) {
  return dates[dataIndex];
}
```

**Comment by jarben** [comment]
Thanks @pissang for info
