### ISSUE TITLE
tooltip 设置trigger为axis，鼠标移动时触发一个新的函数

### ISSUE THREAD

**Issue by hongxiuzhe** [ecomfe/echarts#3452]
#### 问题简述 (One-line summary)

画了一个x轴为离散时间，y轴为value的折线图，想实验这样一个功能：鼠标在图上移动时，根据其所对应的x轴的时间值，触发一个函数，函数参数为当前对应x轴的时间值？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):
echat3 window7

**Comment by pissang** [comment]
有 showtip 事件
