### ISSUE TITLE
工具栏图标怎么使用bootstrap font awesome的icon

### ISSUE THREAD

**Issue by cfx2016** [ecomfe/echarts#3453]
#### 问题简述 (One-line summary)
myTool2: {
                show: true,
                title: '自定义扩展方法',
                icon: 'image://http://echarts.baidu.com/images/favicon.png',
                onclick: function (){
                    alert('myToolHandler2')
                }

这里的icon只能是图片或者path，怎么才能使用font swesome 文本图标
<i class="fa fa-envira" aria-hidden="true"></i>

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):ie10
+ 操作系统类型和版本 (OS Version):windows 10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不能用 iconfont，可以在 http://www.flaticon.com/packs/font-awesome 这种网站下载完 svg 后提取里面 path 的字符串然后前面加上 `path://`
