### ISSUE TITLE
Graph doesn't display into tabs

### ISSUE THREAD

**Issue by cghanassia** [ecomfe/echarts#3457]
#### 问题简述 (One-line summary)

The graph doesn't display into tabs : 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  2.2.7
+ 浏览器类型和版本 (Browser version): chrome 51.0.2704.103 m
+ 操作系统类型和版本 (OS Version): windows 10

#### 重现步骤 (Steps to reproduce)

												<div class="tabbable">
													<ul id="myTab5" class="nav nav-tabs tab-green">
														<li class="active"><a href="#panel_tab5_example1"
															data-toggle="tab"> <i class="pink fa fa-dashboard"></i>
																Global stat
														</a></li>
														<li class=""><a href="#panel_tab5_example2"
															data-toggle="tab"> <i class="blue fa fa-user"></i>
																Stat stat by month
														</a></li>
													</ul>
													<div class="tab-content">
														<div class="tab-pane active" id="panel_tab5_example1">
															<div class="panel-body">
																<div class="row">
																	<div class="col-sm-12">
																		<div id="main31" style="height: 300px;"></div>
																	</div>
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab5_example2">
															<div class="panel-body">
																<div class="row">
																	<div class="col-sm-12">
																		<div id="main32" style="height: 300px;"></div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>

#### 期望结果 (Expected behaviour)

graph can be displayed into tab

#### 可能哪里有问题 (What went wrong)
the graph doesn't display

#### ECharts配置项 (ECharts option)

```javascript
option = {

}
all graphs
```

#### 其他信息 (Other comments)

Thank you

**Comment by pissang** [comment]
Maybe it's because container doesn't have size

**Comment by cghanassia** [comment]
Hello,
when i inspect i have this generated html, with nothing displayed 
<div id="main31" style="height: 300px; -webkit-tap-highlight-color: transparent; -webkit-user-select: none; background-color: rgba(0, 0, 0, 0);" _echarts_instance_="1466446882348"><div style="position: relative; overflow: hidden; height: 300px;"><div data-zr-dom-id="bg" class="zr-element" style="position: absolute; left: 0px; top: 0px; height: 300px; -webkit-user-select: none;"></div><canvas width="0" height="300" data-zr-dom-id="0" class="zr-element" style="position: absolute; left: 0px; top: 0px; height: 300px; -webkit-user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas><canvas width="0" height="300" data-zr-dom-id="1" class="zr-element" style="position: absolute; left: 0px; top: 0px; height: 300px; -webkit-user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas><canvas width="0" height="300" data-zr-dom-id="_zrender_hover_" class="zr-element" style="position: absolute; left: 0px; top: 0px; height: 300px; -webkit-user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas><div class="echarts-dataview" style="position: absolute; display: block; overflow: hidden; transition: height 0.8s, background-color 1s; z-index: 1; left: 0px; top: 0px; height: 0px; background-color: rgb(240, 255, 255);"></div></div></div>
