### ISSUE TITLE
showLoading causing endless zrender refreshImmediately

### ISSUE THREAD

**Issue by sduffey** [ecomfe/echarts#3462]
#### 问题简述 (One-line summary)
If chart.showLoading() is used the zrender refreshImmediately() method is being called endlessly

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version): recent Chrome and FireFox
+ 操作系统类型和版本 (OS Version): Mac OSX

#### 重现步骤 (Steps to reproduce)
1. In lib/zrender.js in the refreshImmediately() method add a console.log or breakpoint to indicate the method has been called.
2. On any basic chart example set chart.showLoading() then chart.hideLoading()
3. observe that once chart has full drawn the refreshImmediately() is called continuously 
4. observe that CPU usage will rise especially if there are multiple charts per page

**Comment by pissang** [comment]
Can't reproduce your problem. Can you paste your code on your case?
