### ISSUE TITLE
可以更换loading的图吗？或者可以从哪里找一个一样的gif图吗？

### ISSUE THREAD

**Issue by fangfangyang** [ecomfe/echarts#3463]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

loading的时候，有个红色的转圈效果，有接口提供一张gif图更换吗？或者从哪里获取一张同样效果的gif图吗？（为了整个系统的其他地方的loading保持统一性）

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不支持 gif，可以自己 div 加个 mask 显示 loading 的 gif

**Comment by fangfangyang** [comment]
@pissang 这样的话，就相当于自己写loading，就用不了自带的了，是吧？

**Comment by fukai007** [comment]
有loading的监听事件吗？，我不想没有函数都写
