### ISSUE TITLE
柱状图能否实现选中状态

### ISSUE THREAD

**Issue by misszhangxy** [ecomfe/echarts#3468]
#### 问题简述 (One-line summary)

柱状图需要显示选中的状态，样式和hover相同，可有解决方法。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): echart3.1.3
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): win7

#### 重现步骤 (Steps to reproduce)
非bug

#### 期望结果 (Expected behaviour)

柱状图实现可以选中的状态

#### 可能哪里有问题 (What went wrong)

目前的柱状图无法选中，只有鼠标悬停样式。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
新版本有 brush 组件实现框选
