### ISSUE TITLE
toolbox区域缩放 线图会出现断开的现象

### ISSUE THREAD

**Issue by tiant796180** [ecomfe/echarts#3470]
给官方的demo加上toolbox也是 线图会出现断开的现象 
这个是bug吧

**Comment by tiant796180** [comment]
又测试了下 确实断开了 中间有点 是有数据的 但是缺没有连线

**Comment by tiant796180** [comment]
我查了文档 找到了 connectNulls:'true', 这个在2.0是不用单独设置的 所以3.0会出现问题 提醒大家注意
我看前面也有几个问题是关于这个 就是图形断开 因为没有设置connectNulls:'true',

**Comment by pissang** [comment]
2 里不支持 connectNulls 的，toolbox 线图断开是因为 y 轴超出范围的数据都被过滤变成了空数据，你可以设置 http://echarts.baidu.com/option.html#toolbox.feature.dataZoom.yAxisIndex 该属性不过滤 y 轴数据
