### ISSUE TITLE
可以画双坐标的折线图吗？

### ISSUE THREAD

**Issue by daoyuanjiao** [ecomfe/echarts#3471]
如，我有数据表格如下：
	        类目1	 类目2	类目3	类目4	类目5
系列1      1；2	         3；4	5；6	         7；8	9；10
系列2	11；12	13；14	15；16	17；18	19；20
可以将系列1用一条折线，画出来吗，Y轴为类目，X轴为数据！如果不可以的话，echarts提供自定义画线功能吗，比如，我直接设定坐标，系统自动画线？谢谢！

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=line-y-category

**Comment by daoyuanjiao** [comment]
非常感谢热心回答！我的意思不是您给出的示例中的图线！我是说，比如我的类目1在Y轴中的坐标为1，类目2的坐标为2，我现在有系列1中的数据坐标为：【1000，1】；【1200，1】；【1500，2】；【1800，2】，您给出的示例中，每系列中每类目的数据只能有一个，而我的是每系列中的每类目的数据为两个！

**Comment by pissang** [comment]
折线就支持显示一个数据，如果要显示两个数据建议两个系列，如果是范围数据的话可以两个系列加一个堆叠，然后下面那个系列显示为透明色

**Comment by daoyuanjiao** [comment]
谢谢您的热心回答！我现在是用坐标直接画的！
