### ISSUE TITLE
Can't use import echarts from GitHub

### ISSUE THREAD

**Issue by gabrielenosso** [ecomfe/echarts#3473]
Hi,
I am really interested in using the latest feature of eCharts, in particular the "markArea".

First, I would really like to have it published on npm (also tagged as a beta version, it could let more people test the new stuff).

Then, I tried to import it using the GitHub last commit, but it doesn't work at all: in the index.js file it uses a lot of "import './lib/...', but there is no 'lib' folder.

Is there a way to let it work?

**Comment by pissang** [comment]
Hi, @gabrielenosso.

lib folders are generated by npm script before publish. So if you wan't to use the latest code with import, following steps may be helpful.

1. Get the latest code from https://github.com/ecomfe/echarts and https://github.com/ecomfe/zrender and put the folders under node_modules.
2. run `npm run prepublish` in echarts folder and zrender folder respectively.
3. `import 'echart'`
