### ISSUE TITLE
只刷新数据内存不断增长

### ISSUE THREAD

**Issue by tiant796180** [ecomfe/echarts#3475]
我在使用3.0的时候发现一个问题
我设置全部Option  chart.setOption(option);
在设置前使用 chart.clear(); 然后刷新多次 用IE快照内存 没有发生内存或者对象增加

然后我只更新数据，别的不动 这个不呢个能调用clear IE快照发现对象和内存都在不断增长 而不释放
chart.setOption({
	animation: false,
	series: series//新数据
});
代码没什么特别 就是一个更新全部 一个更新数据 
因为使用了滚动条和工具栏 所以刷新时候 要保持更新前的状态 而且只刷新数据更合理些

**Comment by pissang** [comment]
有具体的例子么？

**Comment by tiant796180** [comment]
下面这个片段 我一会写一个简单的例子 放到云上 

	if (_isRefresh) {
				tlog('res');
				var series = [];
				for (var i = 0; i < chart.series.length; i++) {
					series.push({
						"data": chart.series[i].data
					});
				}
				//局部刷新 内存会增加
				_chart.setOption({
					animation: false,
					series: series
				});
				
				series = null;
				
				//没问题
//				_chart.clear();
//				_chart.setOption(____option);
			} else {
				tlog('init');
				var rotate = chart.views.rotate;
				if (!TTUndefined(rotate)) {
					____option.xAxis[0].axisLabel.rotate = rotate;
					____option.grid.y2 = 120;
					var interval = chart.views.interval;
					if (TTUndefined(interval)) {
						____option.xAxis[0].axisLabel.interval = 'auto';
					} else {
						____option.xAxis[0].axisLabel.interval = interval;
					}
				}
				var dataZoom = chart.views.dataZoom; //margin
				if (!TTUndefined(dataZoom)) {
					if (dataZoom == 'false') {
						____option.dataZoom.show = false;
					} else {
						____option.dataZoom.show = true;
					}
				}
				_chart.setOption(____option);

				_isRefresh = true;
			}

**Comment by tiant796180** [comment]
。。小例子测试了下 没问题 可能我代码有问题 我仔细检查下 谢谢
			$(document).ready(_ready);

			var c0 = null;
			var c1 = null;

			function _ready() {
//				c0 = echarts.init(document.getElementById('chart1'));
				c1 = echarts.init(document.getElementById('chart2'));
				c1.setOption(option2);
			}

		

			function cf() {
				var series = option2.series;
				c1.setOption({
					animation: false,
					series: series
				});
				
			}

**Comment by tiant796180** [comment]
写了个例子 结果完全没问题 我代码是后台java传过来的数据 可能是别的地方没处理好 我再检查下

非常感谢！！




Tiant
 
发件人： Yi Shen
发送时间： 2016-06-22 22:39
收件人： ecomfe/echarts
抄送： tiant796180; Author
主题： Re: [ecomfe/echarts] 只刷新数据内存不断增长 (#3475)
有具体的例子么？

**Comment by pissang** [comment]
ok 那我关闭该 issue 了

**Comment by tiant796180** [comment]
您好 我重现了这个问题 今天又测试了下

例子在附件
问题还原步骤：
1.建立10个图形 初始化 如图1
图1


2.点击下面的按钮C 点击10次后 内存平缓 没有增加 如图2
图2
初始化 和 刷新10次


3.将全部图形利用工具条 切换成柱状图 如图3

4.变成柱图后 再刷新10次图形 我只替换了data 按您说的局部增量变化

然后 内存和对象开始暴涨 如下图快照3

又刷新了10次 还在继续增长

不过我切换回线图 刷新10次 资源确实释放了




测试浏览器 IE11 顺带说下 2.0版本 我也用了类似功能 没有这种问题






















 
发件人： Yi Shen
发送时间： 2016-06-23 09:57
收件人： ecomfe/echarts
抄送： tiant796180; Author
主题： Re: [ecomfe/echarts] 只刷新数据内存不断增长 (#3475)
ok 那我关闭该 issue 了

**Comment by pissang** [comment]
看不到图片
