### ISSUE TITLE
执行action.dataZoom后，图形绘制不全

### ISSUE THREAD

**Issue by imhzx** [ecomfe/echarts#3481]
#### 问题简述 (One-line summary)
执行action.dataZoom后，图形绘制不全

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): v3.1.10
+ 浏览器类型和版本 (Browser version): 36.0.1985.125 m
+ 操作系统类型和版本 (OS Version): WIN7 旗舰版 SP1

#### 重现步骤 (Steps to reproduce)
1.
lineChart.dispatchAction({
	    type: 'dataZoom',
	    start: 87.67123287671232,
	    end: 100
	});

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/20101761/16291138/530d8d4c-3936-11e6-9d92-513b79cfe3a7.png)

![image](https://cloud.githubusercontent.com/assets/20101761/16290460/06fcacc2-3930-11e6-8ec7-7fcb96fd9d65.png)

**Comment by pissang** [comment]
需要制定 dataZoom 的 index

```js
lineChart.dispatchAction({
type: 'dataZoom',
dataZoomIndex: 0,
start: 87.67123287671232,
end: 100
});
```

另外折线图中建议 [toolbox.feature.dataZoom.yAxisIndex](http://localhost/echarts-doc/test/option.html#toolbox.feature.dataZoom.yAxisIndex) 设为 null，不然框选也会过滤 Y 轴的数据

**Comment by tiant796180** [comment]
还不行 试试 chart.series[i].connectNulls = true; 反正我是这么搞好的
