### ISSUE TITLE
桑基图提示错误：Cannot read property 'cloneShallow' of undefined

### ISSUE THREAD

**Issue by abenxian** [ecomfe/echarts#3482]
#### 问题简述 (One-line summary)
桑基图执行过程中报错：Cannot read property 'cloneShallow' of undefined

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome 51.7
+ 操作系统类型和版本 (OS Version):MAC OS X

#### 重现步骤 (Steps to reproduce)
1. 
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
        title: {
            text: 'Sankey Diagram'
        },
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        
        series: [
            {
                type: 'sankey',
                layout: 'none',
                data: data.nodes,
                links: data.links,
                itemStyle: {
                    normal: {
                        borderWidth: 1,
                        borderColor: '#aaa'
                    }
                },
                lineStyle: {
                    normal: {
                        curveness: 0.5
                    }
                }
            }
        ]
    };
```

#### 其他信息 (Other comments)

数据：
{"nodes": [
      {"name": "Total"},
      {"name": "Environment"},
      {"name": "Human rights"},
   ],
   "links": [
      {"source": "Total", "target": "Environment", "value": 0.342284047256003},
      {"source": "Total", "target": "Human rights", "value": 0.307574096993239}
   ]}
![image](https://cloud.githubusercontent.com/assets/20103405/16292611/ae45eff6-3945-11e6-9c1a-b61d40cbddcc.png)

**Comment by pissang** [comment]
桑基图模块没加载，echarts 的版本再高点会提示这个错误信息
