### ISSUE TITLE
怎么让坐标轴全部显示呢？

### ISSUE THREAD

**Issue by daoyuanjiao** [ecomfe/echarts#3485]
#### 问题简述 (One-line summary)
在折线图坐标中，比如我的X轴 dataObj2 = [0,1,2,3,4,5,6,7,8,9,10,11,12]; 在我加载数据的时候，X轴上的数字总是根据我的系列数据在变化。比如我的系列数据是data:[11, 11, 15, 13, 12, 13, 10,20,38], 那么我的X轴上显示的就是0,1,2,3,4,5,6,7,8。
另外：我也配置了	type:'cross'  ，但是鼠标移动的时候还是一根竖线。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
希望能够全部显示出来!X轴一直显示为0,1,2,3,4,5,6,7,8,9,10,11,12，Y轴也需要从零开始显示。鼠标移动到数据点时，显示的是十字光标。

#### ECharts配置项 (ECharts option)

```javascript
option = {
tooltip: {
				trigger: 'axis',
				type:'cross' 
				},
				toolbox: {
					show : true,
					feature : {
					mark : {show: true},
					dataZoom : {show: true},
					dataView : {show: true, readOnly: false},
					restore : {show: true},
					saveAsImage : {show: true}
					}
					},
				axisLine: {onZero: false},
			 xAxis:  {
					type: 'category',
					boundaryGap: false,
					data : [0,1,2,3,4,5,6,7,8,9,10,11,12]
				},
				yAxis: {
					type: 'category',
					boundaryGap: false,
					data : [0,1,2,3,4,5,6,7,8,9,10,11,12]
				},
            series: [{
                name: '0141301',
                type: 'line',
			 data: [[1,1], [2, 1], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]]
            }]
}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#xAxis.axisLabel.interval

**Comment by daoyuanjiao** [comment]
xAxis.axisLabel.interval number, Function 

[ default: 'auto' ] 

坐标轴刻度标签的显示间隔，在类目轴中有效。

默认会采用标签不重叠的策略间隔显示标签，可以设置成 0 强制显示所有标签。

可以用数值表示间隔的数据，也可以通过回调函数控制。回调函数格式如下：
(index:number, value: string) => boolean

第一个参数是类目的 index，第二个值是类目名称，如果跳过则返回 false。
我在配置里面这样写：
xAxis:  {
                    type: 'category',
                    boundaryGap: false,
                    axisLabel: {
                            interval:'0'
                },
                    data : [0,1,2,3,4,5,6,7,8,9,10,11,12]
                },
为什么还是显示不出来呢？

**Comment by daoyuanjiao** [comment]
就算是将interval:'0'改为interval:0 也还是不行呢？谢谢！

**Comment by dudj** [comment]
不加单引号的

**Comment by qiyangduan** [comment]
验证能解决问题，不用单引号
