### ISSUE TITLE
加载城市地图报错TypeError: o is undefined

### ISSUE THREAD

**Issue by 258255170** [ecomfe/echarts#3486]
#### 问题简述 (One-line summary)
从官网上下载上海的城市地图，按照官网上的说明写的代码，但老是报TypeError: o is undefined的错误，但是加载中国地图正常，请问如何定位问题

文件代码如下：
```js
<!DOCTYPE html>
<html>
<header>
    <meta charset="utf-8">
	<script src="jquery-1.9.1.min.js"></script>
    <script src="echarts.min.js"></script>
	<script src="dark.js"></script>
	<script src="map/xianggang.js"></script>
</header>
<body>
    <div id="main" style="width: 600px;height:400px;"></div>
	<script type="text/javascript">
		var myChart = echarts.init(document.getElementById('main'),"dark");
		myChart.setOption({
			series: [{
				type: 'map',
				map: 'xianggang'
			}]
		});
	</script>
</body>
</html>
```

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):firefox
+ 操作系统类型和版本 (OS Version):windows 8

#### 重现步骤 (Steps to reproduce)
1.
2.

**Comment by pissang** [comment]
具体的错误截图贴出来吧

**Comment by 258255170** [comment]
在firefox里报的是TypeError: o is undefined，如图：
![firefox](https://cloud.githubusercontent.com/assets/15768051/16326685/59e6091c-39fb-11e6-937c-252c2c8621c5.jpg)
在chrome里报的是别一个错，如图：

![chrome](https://cloud.githubusercontent.com/assets/15768051/16326747/e05ac988-39fb-11e6-8f4f-ab1b0931f2e8.jpg)

**Comment by pissang** [comment]
应该是 map 不存在，试试中文
