### ISSUE TITLE
graph类型图表同时设置series[i]-graph.layout: 'force' 和 series[i]-graph.edgeSymbol: ['circle', 'arrow'] 会导致无限鬼畜动画

### ISSUE THREAD

**Issue by ufohjl** [ecomfe/echarts#3488]
#### 问题简述 (One-line summary)
graph类型图表同时设置series[i]-graph.layout: 'force' 和 series[i]-graph.edgeSymbol: ['circle', 'arrow']
会导致无限鬼畜动画

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):火狐,IE等
+ 操作系统类型和版本 (OS Version):win8

#### 重现步骤 (Steps to reproduce)
1.graph类型图表同时设置series[i]-graph.layout: 'force'
2.graph类型图表同时设置series[i]-graph.edgeSymbol: ['circle', 'arrow']

#### 期望结果 (Expected behaviour)
自动布局, 并且带有箭头

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
代码中已经修复，下周的新版本不存在这个问题
