### ISSUE TITLE
Echart用于画自动更新图，会存在浏览器的内存泄露

### ISSUE THREAD

**Issue by beidouxinag** [ecomfe/echarts#3489]
#### 问题简述 (One-line summary)
我用echart画自动更新图，用setinterval方法周期的采集数据，先执行了clear 方法，然后再setOption画图，通过sIEve工具监测到，Memory Usage和DOM Usage都一直上涨，这样会造成游览器崩溃，请问有办法解决吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):IE8
+ 操作系统类型和版本 (OS Version):windows xp

#### 重现步骤 (Steps to reproduce)
我用echart画自动更新图，用setinterval方法周期的采集数据，先执行了clear 方法，然后再setOption画图，通过sIEve工具监测到，Memory Usage和DOM Usage都一直上涨，这样会造成游览器崩溃，请问有办法解决吗？

#### 期望结果 (Expected behaviour)
没有内存消耗

#### 可能哪里有问题 (What went wrong)
有DOM节点没有释放掉

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by beidouxinag** [comment]
其他游览器比firefox和chrome还没有测试，估计也存在内存泄露问题

**Comment by beidouxinag** [comment]
我画的是普通的折线图，每次setinterval函数中都会执行clear方法和setOption方法。

**Comment by pissang** [comment]
有没有具体例子

**Comment by beidouxinag** [comment]
<!DOCTYPE html>
<html style="height: 100%">
   <head>
       <meta charset="utf-8">
   </head>
   <body style="height: 100%; margin: 0">
       <div id="container" style="height: 100%"></div>
       <script type="text/javascript" src="echarts.common.min.js"></script>
       <script type="text/javascript">
var dom = document.getElementById("container");
var myChart = echarts.init(dom);
var app = {};
option = null;
var base = +new Date(2014, 9, 3);
var oneDay = 24 * 3600 * 1000;
var date = [];

var data = [Math.random() * 150];
var now = new Date(base);

function addData(shift) {
    now = [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('-');
    date.push(now);
    data.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
    if (shift) {
        date.shift();
        data.shift();
    }
    now = new Date(Date.parse(now) + 24 * 3600 * 1000);
}

for (var i = 1; i < 100; i++) {
    addData();
}

option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: date
    },
    yAxis: {
        boundaryGap: [0, '50%'],
        type: 'value'
    },
    series: [
        {
            name:'成交',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            areaStyle: {
                normal: {}
            },
            data: data
        }
    ]
};

app.timeTicket = setInterval(function () {
    addData(true);
    myChart.setOption({
        xAxis: {
            data: date
        },
        series: [{
            name:'成交',
            data: data
        }]
    });
}, 500);;
if (option && typeof option === "object") {
    var startTime = +new Date();
    myChart.setOption(option, true);
}
       </script>
   </body>
</html>

**Comment by beidouxinag** [comment]
<!DOCTYPE html>
<html style="height: 100%">
   <head>
       <meta charset="utf-8">
   </head>
   <body style="height: 100%; margin: 0">
       <div id="container" style="height: 100%"></div>
       <script type="text/javascript" src="echarts.common.min.js"></script>
       <script type="text/javascript">
var dom = document.getElementById("container");
var myChart = echarts.init(dom);
var app = {};
option = null;
var base = +new Date(2014, 9, 3);
var oneDay = 24 * 3600 * 1000;
var date = [];

var data = [Math.random() * 150];
var now = new Date(base);

function addData(shift) {
    now = [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('-');
    date.push(now);
    data.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
    if (shift) {
        date.shift();
        data.shift();
    }
    now = new Date(Date.parse(now) + 24 * 3600 * 1000);
}

for (var i = 1; i < 100; i++) {
    addData();
}

option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: date
    },
    yAxis: {
        boundaryGap: [0, '50%'],
        type: 'value'
    },
    series: [
        {
            name:'成交',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            areaStyle: {
                normal: {}
            },
            data: data
        }
    ]
};

app.timeTicket = setInterval(function () {
    addData(true);
    myChart.setOption({
        xAxis: {
            data: date
        },
        series: [{
            name:'成交',
            data: data
        }]
    });
}, 500);;
if (option && typeof option === "object") {
    var startTime = +new Date();
    myChart.setOption(option, true);
}
       </script>
   </body>
</html>

**Comment by beidouxinag** [comment]
<!DOCTYPE html>
<html style="height: 100%">
   <head>
       <meta charset="utf-8">
   </head>
   <body style="height: 100%; margin: 0">
       <div id="container" style="height: 100%"></div>
       <script type="text/javascript" src="echarts.common.min.js"></script>
       <script type="text/javascript">
var dom = document.getElementById("container");
var myChart = echarts.init(dom);
var app = {};
option = null;
var base = +new Date(2014, 9, 3);
var oneDay = 24 * 3600 * 1000;
var date = [];

var data = [Math.random() * 150];
var now = new Date(base);

function addData(shift) {
    now = [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('-');
    date.push(now);
    data.push((Math.random() - 0.4) * 10 + data[data.length - 1]);
    if (shift) {
        date.shift();
        data.shift();
    }
    now = new Date(Date.parse(now) + 24 * 3600 * 1000);
}

for (var i = 1; i < 100; i++) {
    addData();
}

option = {
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: date
    },
    yAxis: {
        boundaryGap: [0, '50%'],
        type: 'value'
    },
    series: [
        {
            name:'成交',
            type:'line',
            smooth:true,
            symbol: 'none',
            stack: 'a',
            areaStyle: {
                normal: {}
            },
            data: data
        }
    ]
};

app.timeTicket = setInterval(function () {
    addData(true);
    myChart.setOption({
        xAxis: {
            data: date
        },
        series: [{
            name:'成交',
            data: data
        }]
    });
}, 500);;
if (option && typeof option === "object") {
    var startTime = +new Date();
    myChart.setOption(option, true);
}
       </script>
   </body>
</html>

**Comment by beidouxinag** [comment]
好像贴不了代码；不过没有关系，用官网上面的这个例子也可以。
http://echarts.baidu.com/gallery/editor.html?c=doc-example/tutorial-dynamic-data
我本地用sIEve做了内存监控的，有截图的，但是没找到地方上传截图。

**Comment by pissang** [comment]
IE8 是有可能，但是 chrome 和 firefox 我们是测过这些例子的，并不会造成内存泄露

**Comment by beidouxinag** [comment]
你们firefox和chrome是用的什么工具测的，证明它是没有内存泄露的

**Comment by pissang** [comment]
chrome 有自带的堆快照工具以及内存的 timeline

**Comment by tiant796180** [comment]
这个问题我也发现了 可以交流下 qq246853
另外我的现在确定的问题是这样 你试试line图 内存是没问题的 如果你用bar 刷新时候c0.setOption 只更新data的话 内存是不会被释放的 上一次我以为是切换工具条 由线图转换到bar会发生泄漏
刚才我才确定 你用bar 就会泄漏 内存会一直增加 line没事 顺便说下2.0版本好像正常
我一会去发个帖子 会放例子
