### ISSUE TITLE
map执行action.tooltip.showTip时，tip出现位置没有定位指定区域

### ISSUE THREAD

**Issue by imhzx** [ecomfe/echarts#3490]
#### 问题简述 (One-line summary)
map执行action.tooltip.showTip时，tip出现位置没有定位指定区域

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): v3.1.10
+ 浏览器类型和版本 (Browser version): Chorme 36.0.1985.125 m
+ 操作系统类型和版本 (OS Version): win7 旗舰版 sp1

#### 重现步骤 (Steps to reproduce)
1.
mapChart.dispatchAction(
				{
				    type : 'showTip',
				    seriesIndex : 0,
				    name : ‘四川’
				}
			);
2.

#### 期望结果 (Expected behaviour)
希望tip能随不同区域移动

#### 可能哪里有问题 (What went wrong)
未设置tooltip.position前，执行action出现的tip层没有left、top属性

#### 其他信息 (Other comments)

![kwk jrp25h xxqyxo 7aq6](https://cloud.githubusercontent.com/assets/20101761/16297020/70fabeee-3961-11e6-96f9-8a94125dbfdb.png)

**Comment by mujing** [comment]
+1

**Comment by chengwubin** [comment]
+1

**Comment by chengwubin** [comment]
2.0都是正常的
