### ISSUE TITLE
快捷方式得到所有charts的句柄

### ISSUE THREAD

**Issue by AllyW** [ecomfe/echarts#3492]
#### 问题简述 (One-line summary)
单页面应用上有多个charts， 拥有不同的id，同样的class name，现准备对window.resize事件进行响应，有没有一个简便的方法可以获得之前所有已经初始化的chartsInstance句柄以供实施resize()呢？比如：
var chartsInstances = $(".class-name").attr("some property");
chartsInstance[0].resize(), chartsInstance[1].resize()...chartInstance[n].resize()

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.5
+ 浏览器类型和版本 (Browser version): chrome 
+ 操作系统类型和版本 (OS Version): mac os

#### 重现步骤 (Steps to reproduce)
1. 单页面包含多charts
2.拖放页面，响应window.resize()事件
3. 响应window.resize()事件，调用someChart.size() one by one

#### 期望结果 (Expected behaviour)
期望有一个快捷的方式得到所有当前页面上的charts句柄统一做resize()

#### 可能哪里有问题 (What went wrong)
unknown

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以自己管理

**Comment by AllyW** [comment]
那如何根据dom id获取实例呢？

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echarts.getInstanceByDom

**Comment by AllyW** [comment]
Thanks.
