### ISSUE TITLE
多个饼图颜色显示不正常

### ISSUE THREAD

**Issue by nighthun** [ecomfe/echarts#3496]
#### 问题简述 (One-line summary)
如果2个饼图同时显示，则它们的颜色序列是不一样的，正常应该是2个独立的指标，颜色序列从头开始

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.
默认问题如下：
![image](https://cloud.githubusercontent.com/assets/10071831/16332911/2846b750-3a2b-11e6-92a0-38f2da675c7f.png)

#### 期望结果 (Expected behaviour)
![image](https://cloud.githubusercontent.com/assets/10071831/16332923/333aa6b2-3a2b-11e6-90fd-abd6bb6fc97a.png)

#### 可能哪里有问题 (What went wrong)
饼图多个指标时，公用了颜色序列

#### ECharts配置项 (ECharts option)

```javascript
option = {
"legend": {
		"data": [
			"点心",
			"调味品"
		],
		"left": "center",
		"orient": "horizontal",
		"top": "top"
	},
	"series": [
		{
			"center": [
				"25%",
				"50%"
			],
			"data": [
				{
					"name": "点心",
					"value": 7927
				},
				{
					"name": "调味品",
					"value": 5276
				}
			],
			"name": "数量",
			"radius": [
				"0",
				"50%"
			],
			"type": "pie"
		},
		{
			"center": [
				"75%",
				"50%"
			],
			"data": [
				{
					"name": "点心",
					"value": 7602
				},
				{
					"name": "调味品",
					"value": 4548
				}
			],
			"name": "单价",
			"radius": [
				"0",
				"50%"
			],
			"type": "pie"
		}
	]
}

```

**Comment by pissang** [comment]
下周新版本已经修复这个问题
