### ISSUE TITLE
echarts 3.0中没有树图与字符云

### ISSUE THREAD

**Issue by langman** [ecomfe/echarts#3498]
所用echarts版本为：3.1.10，打算用树图与字符云时，发现该版本暂时还没有合入这个两个图形，不知后续版本是否还会增加。

**Comment by zxbin2000** [comment]
会支持数图吗？2.0有的功能，现在没有了，做组织架构图还是需要的。

**Comment by jackhu1990** [comment]
可否告知树图加入的时间?

**Comment by pissang** [comment]
树图不会再单独作为一个图表，以后可能会作为 graph 的 layout 扩展存在，字符云也会通过扩展实现
