### ISSUE TITLE
柱状图内存泄漏 有例子

### ISSUE THREAD

**Issue by tiant796180** [ecomfe/echarts#3500]
#### 问题简述 (One-line summary)
使用bar刷新数据 内存不会释放

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
3.0最新版

+ 浏览器类型和版本 (Browser version):
IE11

+ 操作系统类型和版本 (OS Version):
win10

#### 重现步骤 (Steps to reproduce)
云盘有例子
1.使用线图 刷新10次 内存平稳
2.使用柱图 刷新10次 内存和对象一直增长
另外 如果使用工具条的柱线切换也有同样问题

#### 可能哪里有问题 (What went wrong)
前几天我发现这个问题 以为是工具栏切换后造成 发了例子到邮箱
今天确认只要是柱图 就会出现这个问题

#### ECharts配置项 (ECharts option)

百度云 有例子和内存截图
我没用谷歌测试 行业大部分用IE浏览器还是比较多
http://pan.baidu.com/s/1i5rsy4t

**Comment by pissang** [comment]
我们定位了下确实在数据更新中存在事件绑定的内存泄露问题。已修复，谢谢反馈
