### ISSUE TITLE
如何修改坐标轴的样式，以及坐标值的位置

### ISSUE THREAD

**Issue by ASenBoy** [ecomfe/echarts#3501]
如何将x、y坐标轴的样式 变为终点为箭头状？

![qq 20160626220421](https://cloud.githubusercontent.com/assets/18394147/16362773/f8c3755c-3be9-11e6-933c-8fd46d4fbc69.png)

如何将当y轴有正负值时，x轴的label仍在x轴下方 而不是grid 的下方？

![qq 20160626220644](https://cloud.githubusercontent.com/assets/18394147/16362794/5c79d7f8-3bea-11e6-9171-72f7b87e6955.png)
![qq 20160626220711](https://cloud.githubusercontent.com/assets/18394147/16362795/6061491e-3bea-11e6-8756-85c38ae4b8e2.png)

**Comment by pissang** [comment]
1. 不行，2 xAxis.axisLine.onZero = true

**Comment by flyingfish3** [comment]
1、x轴：xAxis.axisLine.symbol=['none','arrow']，y轴同
