### ISSUE TITLE
map比例可以自适应吗？

### ISSUE THREAD

**Issue by layjump** [ecomfe/echarts#3504]
#### 问题简述 (One-line summary)
map图显示是根据canvas的width和height平铺显示的，导致比例不对。series的mapLocation，只给出height，不指定width，显示出来的地图是按照canvas的width显示。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 
3.0
+ 浏览器类型和版本 (Browser version):
chrome 51
+ 操作系统类型和版本 (OS Version):
win7

#### 重现步骤 (Steps to reproduce)
1.设置canvas的div的width:800px，height:700px;
2.设置地图为江苏
3.设置series的mapLocation的height为600。
结果江苏省地图宽度变成了800px，被拉伸了。

#### 期望结果 (Expected behaviour)
map的width按正确比例显示，而不是显示成800px。

#### 可能哪里有问题 (What went wrong)
是不是有参数设置？我找过没找到，还是地图本来就没有比例。

#### ECharts配置项 (ECharts option)
```javascript
option = {
    "series": [
        {
            "itemStyle": {
                "emphasis": {
                    "borderColor": "#424648",
                    "label": {
                        "show": false
                    },
                    "areaColor": "#58f4ff"
                },
                "normal": {
                    "borderColor": "#424648",
                    "areaColor": "#333739"
                }
            },
            "mapLocation": {
                "y": "center",
                "x": "center",
                "height": "600",
            },
            "type": "map",
            "name": "default",
            "map": "jiangsu",
            "selectedMode": "multiply"
        }
    ]
}
```

#### 其他信息 (Other comments)

被拉伸的地图。
![image](https://cloud.githubusercontent.com/assets/4541672/16374787/b4aa25f4-3c8a-11e6-9125-49d92081eb63.png)

正确比例的地图
![image](https://cloud.githubusercontent.com/assets/4541672/16374806/c8738b5c-3c8a-11e6-8df7-081367dcce86.png)

**Comment by pissang** [comment]
首先 3 里布局的配置是 left, top, right, bottom. 2 里 x 和 y 会转成 left 和 top，mapLocation 也不存在了，然后除非 width 和 height 都被明确指定，不然是会按比例缩放的

**Comment by layjump** [comment]
哦，我试了一下，原来是之前一直配了left,top,right,bottom导致被拉伸了，Thanks!
