### ISSUE TITLE
想要让值为0时不显示markpoin

### ISSUE THREAD

**Issue by carly1987** [ecomfe/echarts#3507]
#### 问题简述 (One-line summary)
![image](https://cloud.githubusercontent.com/assets/4493524/16401241/a666fe64-3d15-11e6-91d4-db2303849297.png)

我是这么写的，虽然0时，的确不显示了。但是，任何值都不显示markpoint了
symbolSize: function(value,{}){
			                	if (value == 0) {
			                		return 'auto';
			                	}
			                },
抱歉问我没有找到更好的方法，只能请教你了

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
markPoint 的 symbolSize 暂时不支持函数回调，你可以在 markPoint 的 data 里定义
```js
markPoint:  {
  data: [{
     value: 0,
     symbol: 'none'
  }]
}
```

**Comment by carly1987** [comment]
试过了 没有用

**Comment by pissang** [comment]
有用到

**Comment by pissang** [comment]
的
