### ISSUE TITLE
3.0关系网会缩到一起

### ISSUE THREAD

**Issue by feng5125214** [ecomfe/echarts#3508]
#### 问题简述 (One-line summary)
  edgeSymbol: ['circle', 'arrow'], 加上这个箭头方向后节点就会缩到一起无法显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts3.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):window 10 64位

#### 重现步骤 (Steps to reproduce)
1.获取json数据
{
     "type": "graph",
     "layout": "force",
    "categories": [
        {
            "name": "法人代表",
            "keyword": {},
            "base": "法人代表关系"
        },
        {
            "name": "股东",
            "keyword": {},
            "base": "股东关系"
        },
        {
            "name": "高管",
            "keyword": {},
            "base": "高管关系"
        }
    ],
    "nodes": [
       {"name":"孙高梁","category":1},
       {"corpid":"3301852003000699","name":"临安市金石大饭店有限公司","category":2},
       {"name":"陈枫","category":1},
       {"corpid":"3301850000088925","name":"杭州临安佰汇信息有限公司","category":0},
       {"corpid":"3301060001114195","name":"杭州树源贸易有限公司","category":2}
    ],
    "links": [
      
		    {"source":"陈枫","target":"孙高梁"},
		    
		     {"source":"临安市金石大饭店有限公司","target":"孙高梁"}
		     
    ]
}
2.ajax请求获取

#### 期望结果 (Expected behaviour)

希望获取像echarts2.0一样，显示带箭头关系图

#### 可能哪里有问题 (What went wrong)
结果是缩到一起了

#### ECharts配置项 (ECharts option)

```javascript
 option = {
                         legend: {
                             data: ['HTMLElement', 'WebGL', 'SVG', 'CSS', 'Other']
                         },
                         series: [{
                             type: 'graph',
                             layout: 'force',
                             edgeSymbol: ['circle', 'arrow'],
                             edgeSymbolSize: [4, 10],
                             roam: true,
                             animation: false,

                             label: {
                                 normal: {
                                   
                                     formatter: '{b}'
                                 }
                             },
                            
                           
                             draggable: true,
                             data: datajson.nodes.map(function (node, idx) {
                                // node.id = idx;  
                                  node.itemStyle = null;
							        node.symbolSize = 40;
							       
							        // Use random x, y
							        node.x = node.y = null;
							        node.draggable = true;
                                 return node;
                             }),
                             categories: datajson.categories,
                             force: {
                                 // initLayout: 'circular'
                                 // gravity: 0
                                 // repulsion: 20,
                                 edgeLength: 500,
                                 repulsion:800
                             },
                             edges: datajson.links
                         }]
                     };
            	  myChart.setOption(option);

```

#### 其他信息 (Other comments)

![Uploading QQ图片20160628101957.png…]()

**Comment by pissang** [comment]
这个问题最新的代码中已经修复
