### ISSUE TITLE
折线图实际数值与显示数值对不上

### ISSUE THREAD

**Issue by CHENGUANCHI** [ecomfe/echarts#3509]
#### 问题简述 (One-line summary)
折线图实际数值与显示数值对不上,官网例子:  http://echarts.baidu.com/demo.html#line-stack

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  3.1.10
+ 浏览器类型和版本 (Browser version):  google chrome 49.0.2623.110 m
+ 操作系统类型和版本 (OS Version):  win7 64bit 旗舰版

#### 重现步骤 (Steps to reproduce)
1.官网提供的例子就有问题，数据显示：http://echarts.baidu.com/demo.html#line-stack

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/12690135/16403356/d8d40e58-3d26-11e6-9a94-b47fb8091edc.png)
官网实例:  http://echarts.baidu.com/demo.html#line-stack

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/2760
