### ISSUE TITLE
markLine 的文本标签只能是能设置 start、middle、end么?

### ISSUE THREAD

**Issue by ryanypm** [ecomfe/echarts#3510]
#### 问题简述 (One-line summary)

markLine 的文本标签只能是能设置 start、middle、end么?
如果要自定义怎么办?
![3677cc04-d0b7-4eb6-8a8b-db609e46b2ec](https://cloud.githubusercontent.com/assets/7519919/16406820/0bed85aa-3d43-11e6-87b3-8b2b44a9f779.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):osx

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

可以自定义文本标签的偏移位置

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
想要自定义放哪？
