### ISSUE TITLE
echarts3里面力导向图怎么没有边的权重

### ISSUE THREAD

**Issue by jsyhj1234** [ecomfe/echarts#3512]
#### 问题简述 (One-line summary)
在echarts2里有weight这个属性 在3里面好像没有。那怎么设置边的权重

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
3 里的力引导布局去掉了这个属性

**Comment by steinsphang** [comment]
你好，请问有什么方法能实现weight的效果吗？在没有weight的状况下，力导向图点过于密集了。

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-graph.force.edgeLength

**Comment by steinsphang** [comment]
抱歉，没有说明白。用edgeLength的话的确可以调节点之间的距离，但是只能统一调节。我想实现的效果是：有些边的长度长，有些边的长度短。请问能做到吗？还是说只能放弃力导向图，全都手工布局。

**Comment by pissang** [comment]
@steinsphang https://github.com/ecomfe/echarts/commit/c4bf05eb2ca726fc1c674a9168ec19618d522d9c 中新支持 edgeLength 配置为数组，表示边的长度范围，这个长度范围从 edge 的值映射

**Comment by steinsphang** [comment]
@pissang 非常感谢！

**Comment by QinfengORqingfeng** [comment]
@steinsphang 你好， edgeLength 可以修改关系边的长度吗？为什么我设置的没有用
 force: {  
                        edgeLength: 105,//连线的长度  
                        repulsion: 100  //子节点之间的间距  
                    },

**Comment by steinsphang** [comment]
@QinfengORqingfeng [edgeLength](http://echarts.baidu.com/option.html#series-graph.force.edgeLength)的参数是 Array, number，如果你配置成数字的话那就是固定长度；
如果你配置成数组的话就会做一个映射，映射的依据是[links](http://echarts.baidu.com/option.html#series-graph.links)的value值
