### ISSUE TITLE
柱状图 标题是y轴，8个标题会出现两个标题字体比较模糊

### ISSUE THREAD

**Issue by zzone** [ecomfe/echarts#3514]
#### 问题简述 (One-line summary)

柱状图 标题是y轴，8个标题会出现两个标题，其中第4和第6两个标题字体特别模糊，
测试好几台机器，都不行。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome 50.0.2661.75 m  IE8也不行
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
字体清晰

#### 可能哪里有问题 (What went wrong)

渲染时有问题

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by webJing** [comment]
echarts.init(document.getElementById(id),'', {devicePixelRatio:2});这样的配置可以解决，设置像素比为2

**Comment by suifengfengye** [comment]
@webJing 设置了，没起作用
