### ISSUE TITLE
关系图中无法设置symbolSize为数组

### ISSUE THREAD

**Issue by joy20150805** [ecomfe/echarts#3516]
#### 问题简述 (One-line summary)
关系图里的symbolSize 无法设置成数组，设置成数组则箭头消失

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
title: {
        text: '程序：'+'xxx '+'血缘分析'
    },
    tooltip: {},
    animationDurationUpdate: 1500,
    animationEasingUpdate: 'quinticInOut',
    series : [
        {
            type: 'graph',
            layout: 'none',
            symbolSize: 50,
            symbol:'circle',

            roam: true,
            label: {
                normal: {
                    show: true
                }
            },
            edgeSymbol: ['circle', 'arrow'],
            edgeSymbolSize: [4, 10],
            edgeLabel: {
                normal: {
                    textStyle: {
                        fontSize: 20
                    }
                }
            },
            data: [{
                name: '节点1',
                x: 300,
                y: 300,
                itemStyle : { normal: {color:'#FF0000'}},
                 symbol:'rectangle',
                //  symbolSize: [50,20],
            }, {
                name: '节点2',
                x: 400,
                y: 100
            },{
                name: '节点3',
                x: 400,
                y: 200,
                symbol: 'image://../asset/ico/favicon.png//自定义图片|circle' | 'rectangle' | 'triangle' | 'diamond' |
'emptyCircle' | 'emptyRectangle' | 'emptyTriangle' | 'emptyDiamond|roundRect', 
            },{
                name: '节点4',
                x: 400,
                y: 300,
            }, {
                name: '节点5',
                x: 400,
                y: 400,
                symbol:'droplet',
            }, {
                name: '节点6',
                x: 400,
                y: 500
            },{
                name: '节点7',
                x: 500,
                y: 100
            }, {
                name: '节点8',
                x: 500,
                y: 200
            }, {
                name: '节点9',
                x: 500,
                y: 300
            }, {
                name: '节点10',
                x: 500,
                y: 400
            }, {
                name: '节点11',
                x: 600,
                y: 200
            }, {
                name: '节点12',
                x: 600,
                y: 300
            }, {
                name: '节点13',
                x: 600,
                y: 400
            }, {
                name: '节点14',
                x: 600,
                y: 500
            }, {
                name: '节点15',
                x: 700,
                y: 300,
                itemStyle : { normal: {color:'#FF0000'}}
            }],
            links: [{
                // source: 0,
                // target: 1,
                // symbolSize: [50, 20],//50表示点，20表示箭头
                label: {
                    normal: {
                        show: true
                    }
                },
                lineStyle: {
                    normal: {
                        width: 5,
                        curveness: 0.2
                    }
                }
            }, {
                source: '节点1',
                target: '节点2',
                // label: {
                //     normal: {
                //         show: true
                //     }
                // },
                // lineStyle: {
                //     normal: { curveness: 0.2 }
                // }
            }, {
                source: '节点1',
                target: '节点3'
            }, {
                source: '节点1',
                target: '节点4'
            }, {
                source: '节点1',
                target: '节点5'
            }, {
                source: '节点1',
                target: '节点6'
            }, {
                source: '节点4',
                target: '节点7'
            }, {
                source: '节点4',
                target: '节点8'
            }, {
                source: '节点4',
                target: '节点9'
            }, {
                source: '节点4',
                target: '节点10'
            }, {
                source: '节点8',
                target: '节点11'
            }, {
                source: '节点8',
                target: '节点12'
            }, {
                source: '节点10',
                target: '节点13'
            }, {
                source: '节点10',
                target: '节点14'
            }, {
                source: '节点11',
                target: '节点15'
            }, {
                source: '节点12',
                target: '节点15'
            }, {
                source: '节点13',
                target: '节点15'
            }, {
                source: '节点14',
                target: '节点15'
            }],
            lineStyle: {
                normal: {
                    opacity: 0.9,
                    width: 2,
                    shadowColor:'rgba(1,2,3,4)',
                    curveness: 0,
                    color:'#000'
                }
            },
            itemStyle: {
                normal: {
                    // borderWidth: 1,
                    // borderColor: '#333'
                    color:'#0072E3',
                    label:{show:true,textStyle:{fontSize:15,fontStyle:'bolder',color:'#000'}}
    //                 lineStyle : {
				// 			width : 2
				// 		},
                }
            },
        }
    ]
}

```

**Comment by pissang** [comment]
这个问题在下个版本中修复

**Comment by kimyengil** [comment]
@pissang 最新的3.2.2的版本依旧会有这个问题，请协助确认，多谢。
以官方提供的示例为例（无论在官方提供的示例的环境里测试，还是本地的chrome里测试，箭头都会消失）
`option = {
    title: {
        text: 'Graph 简单示例'
    },
    tooltip: {},
    animationDurationUpdate: 1500,
    animationEasingUpdate: 'quinticInOut',
    series : [
        {
            type: 'graph',
            layout: 'none',
            symbolSize: [50,50],
            roam: true,
            label: {
                normal: {
                    show: true
                }
            },
            edgeSymbol: ['circle', 'arrow'],
            edgeSymbolSize: [4, 10],
            edgeLabel: {
                normal: {
                    textStyle: {
                        fontSize: 20
                    }
                }
            },
            data: [{
                name: '节点1',
                x: 300,
                y: 300
            }, {
                name: '节点2',
                x: 800,
                y: 300
            }, {
                name: '节点3',
                x: 550,
                y: 100
            }, {
                name: '节点4',
                x: 550,
                y: 500
            }],
            // links: [],
            links: [{
                source: 0,
                target: 1,
                symbolSize: [5, 20],
                label: {
                    normal: {
                        show: true
                    }
                },
                lineStyle: {
                    normal: {
                        width: 5,
                        curveness: 0.2
                    }
                }
            }, {
                source: '节点2',
                target: '节点1',
                label: {
                    normal: {
                        show: true
                    }
                },
                lineStyle: {
                    normal: { curveness: 0.2 }
                }
            }, {
                source: '节点1',
                target: '节点3'
            }, {
                source: '节点2',
                target: '节点3'
            }, {
                source: '节点2',
                target: '节点4'
            }, {
                source: '节点1',
                target: '节点4'
            }],
            lineStyle: {
                normal: {
                    opacity: 0.9,
                    width: 2,
                    curveness: 0
                }
            }
        }
    ]
};`
官方示例链接。http://echarts.baidu.com/demo.html#graph-simple

**Comment by pissang** [comment]
是 edgeSymbolSize

**Comment by pissang** [comment]
@kimyengil 抱歉直线的边确实还存在这个问题，https://github.com/ecomfe/echarts/commit/7affe1255cbcb990f7868ae02eec5b5275ccdcc5 中已修复

**Comment by kimyengil** [comment]
@pissang 确认已修复，感谢及时响应，赞！

**Comment by kimyengil** [comment]
@pissang  提个小bug。symbol变更为【roundRect】,symbolSize变更为【100,30】后，由于宽度过宽的原因，箭头会被【节点标记的图形】覆盖掉。
或者说将symbol改为其他样式后（比如triangle等），箭头默认不会对齐到【节点标记的图形】的边上，要么有一定的距离，要么被覆盖，circle则正好。

**Comment by pissang** [comment]
@kimyengil 因为现在边线都只跟圆形求交，还没考虑其它形状，不同长宽的矩形也会取中间值作为半径，后面会优化这一块
