### ISSUE TITLE
关于主页的一个小建议

### ISSUE THREAD

**Issue by iny7** [ecomfe/echarts#3520]
#### 问题简述 (One-line summary)
Hi，ECharts很酷炫，但是主页 http://echarts.baidu.com/  Logo下面那个<img>做的阴影能被选中，很讨厌，为什么不用user-slect处理掉呢？ 另外，希望主页支持一下鼠标拖拽换页的手势，挺小的问题，加上就更完美啦

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢建议
