### ISSUE TITLE
Bug(Docs): A small error in the online documentation

### ISSUE THREAD

**Issue by gudh** [ecomfe/echarts#3521]
Thanks for building this gorgeous chart, really love it!

####  One-line summary

There is a small error in [the online documentation](http://echarts.baidu.com/option.html#radar.splitLine)

####  Details:

The configure docs on radar chart now is [like this]((http://echarts.baidu.com/option.html#radar.splitLine)):

```
splitLine: {
    show: { // <- this should be `lineStyle`
        color: ['#ccc'],
        width: 1,
        type: 'solid',
        shadowBlur: ...,
        shadowColor: ...,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        opacity: ...,
    },
},
```

In fact, it should be 

```
splitLine: {
    show: true,
    lineStyle: {
        color: ['#ccc'],
        width: 1,
        type: 'solid',
        shadowBlur: ...,
        shadowColor: ...,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        opacity: ...,
    },
},
```

so it should be `lineStyle`, instead of `show`

**Comment by pissang** [comment]
Thanks! And glad to hear you love it:)
