### ISSUE TITLE
tooltip.enterable文档默认值应是false，但文档中写成了true

### ISSUE THREAD

**Issue by Cheng007** [ecomfe/echarts#3523]
#### 问题简述 (One-line summary)
官方配置项页面关于tooltip.enterable的文档错误

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): win10 专业版

#### 重现步骤 (Steps to reproduce)
http://echarts.baidu.com/option.html#tooltip.enterable 
中写到“[ default: true ]，鼠标是否可进入提示框浮层中，默认为false，如需详情内交互，如添加链接，按钮，可设置为 true。"

#### 期望结果 (Expected behaviour)
[default: false]

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢反馈
