### ISSUE TITLE
echart with wkhtmltopdf

### ISSUE THREAD

**Issue by ChongyuE** [ecomfe/echarts#3525]
#### 问题简述 (One-line summary)
在用 wkhtmltopdf 对echart 图表进行格式转换的时候 对饼图转换会出现 只显示一半的图像 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10 完整
+ 浏览器类型和版本 (Browser version): chrome 
+ 操作系统类型和版本 (OS Version):osx 10.11.5

#### 重现步骤 (Steps to reproduce)
1.用echart demo 写一张 html静态页面 （饼图）
2，利用 wkhtmltopdf http://127.0.0.1:8080/static/temp/test.html xxx.pdf 进行导出 显示的饼图内容只有一半

#### 期望结果 (Expected behaviour)
导出的pdf 能显示全部html 上显示的内容

#### 可能哪里有问题 (What went wrong)
在经过对各种图表类型测试 发现只有饼图出现问题，其他图标均能完整导出到pdf

#### ECharts配置项 (ECharts option)

```javascript
option = {
          legend: {
              data: ['紧急','高危','中危','低危','信息']
          },
          color:["#961403","#FA3314","#E1C523","#3BB4C4","#26D926"],
          series : [
              {
                  name: '访问来源',
                  type: 'pie',
                  data:[
                      {value:1, name:'紧急'},
                      {value:1, name:'高位'},
                      {value:1, name:'中危'},
                      {value:1, name:'低危'},
                      {value:1, name:'信息'}
                  ]
              }
          ]
      };

```

**Comment by wuyq1986** [comment]
series里面加 animation:false,

**Comment by 1pavanb** [comment]
Setting the width of the chart solved it for me.

> The div that displays echarts needs to set a height and width, pay attention to both, the browser can see the picture without setting the width, but the pdf cannot be generated.
https://www.codetd.com/en/article/13879974

I had the chart with just the height.
