### ISSUE TITLE
Ability to change cursor on mark points

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3529]
Version 3.1.10

Would be great if cursors on mark points can be customized, for instance, showing default cursor on non-interactive mark points.

**Comment by pissang** [comment]
markPoint will add `silent` configuration to disable interaction in the new version. So the cursor will also be default

**Comment by jarben** [comment]
Nice, that sounds great! Any release date for the next version, 3.2.0? Can't wait:)

**Comment by pissang** [comment]
Tomorrow. If everything goes well.

**Comment by jarben** [comment]
Nice! Looking forward to test!

**Comment by pissang** [comment]
Hi @jarben . We just released v3.2.0. Hope you will like it

**Comment by jarben** [comment]
Awesome news @pissang! New examples look stunning! Going to give it a try now:)
