### ISSUE TITLE
当 timline.orient 为 'vertical' 时，timeline.label位置有误

### ISSUE THREAD

**Issue by imhzx** [ecomfe/echarts#3530]
#### 问题简述 (One-line summary)
当 timline.orient 为 'vertical' 时，timeline.label位置有误

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): v3.1.10
+ 浏览器类型和版本 (Browser version): Chrome 36
+ 操作系统类型和版本 (OS Version): win7

#### 重现步骤 (Steps to reproduce)
```js
timeline:{
		        data: timelist,
		        label : {
					normal: {
			            formatter: function (value, index) {
						    var date = new Date(value);
						    var texts = [(date.getMonth() + 1), date.getDate()];
						    if (index === 0) {
						        texts.unshift(date.getFullYear());
						    }
						    return texts.join('/');
						}
					}
		        },
		        autoPlay : true,
		        playInterval : 2000,
		        orient : 'vertical',
		        inverse : true,
		        top : '5%',
		        right : '2%',
		        bottom : '5%'
		    }
```

当指定label.position的配置方式为number时，label才会贴近timeline，不过timeline位置会转移到label那边去。仅当number为负数时，双方位置才正常

#### 期望结果 (Expected behaviour)
label能保持与timeline的相对位置

#### 其他信息 (Other comments)

![rbtr uyov bl 4s k7b7po](https://cloud.githubusercontent.com/assets/20101761/16479521/78d5eb1c-3ed3-11e6-82bd-59d5c57b3739.png)

另，发现doc一处小问题，这里条件应该写反了：
![klqjn 9soi1apn zw7e4 g](https://cloud.githubusercontent.com/assets/20101761/16479978/45edf5a2-3ed6-11e6-94ee-775f51ac224a.png)

**Comment by pissang** [comment]
你需要配置下 `width`
