### ISSUE TITLE
数据阴影showDataShadow中能否设置多个?

### ISSUE THREAD

**Issue by happyzhangwen** [ecomfe/echarts#3531]
#### 问题简述 (One-line summary)

一个图中有3条线,想在数据阴影showDataShadow也显示3个缩略图(最好是线,不行的话面积阴影也可以).有无好的建议?

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.1.10
+ 浏览器类型和版本 (Browser version): IE11
+ 操作系统类型和版本 (OS Version):windows 7

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行

**Comment by happyzhangwen** [comment]
了解.谢谢.
