### ISSUE TITLE
Map 悬浮到地区的时候不变色，通过设置highlight去指定对应的地区变色

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#3532]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时无法做到
