### ISSUE TITLE
TreeMap 系列根上的颜色设置问题（leafDepth: 1）

### ISSUE THREAD

**Issue by wyw1101** [ecomfe/echarts#3534]
#### 问题简述 (One-line summary)
树图只有一个层次时，或者 leafDepth: 1时，在series上设置颜色，第一层的颜色没有变化，第二层才开始起作用
 
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.1.10
+ 浏览器类型和版本 (Browser version):谷歌、ie等
+ 操作系统类型和版本 (OS Version):win7 64

#### 重现步骤 (Steps to reproduce)
1.http://echarts.baidu.com/demo.html#treemap-drill-down
2.color:['#FF7F50','#87CEFA','#DA70D6','#32CD32','#6495ED','#FF69B4','#BA55D3','#CD5C5C','#FFA500','#40E0D0']);拷贝入series[0]下，
**3.同时，leafDepth: 1，这时第一层的颜色没有变化**
4.与option上设置color效果是不一样的
#### ECharts配置项 (ECharts option)

```javascript
option ={
	"series": [{
		"name": "系列0",
		"type": "treemap",
		"color": ["#FF7F50", "#87CEFA", "#DA70D6", "#32CD32", "#6495ED", "#FF69B4", "#BA55D3", "#CD5C5C", "#FFA500", "#40E0D0"],
		"data": [{
			"value": 6,
			"name": "三星"
		}, {
			"value": 4,
			"name": "小米"
		}, {
			"value": 4,
			"name": "苹果"
		}, {
			"value": 2,
			"name": "华为"
		}, {
			"value": 2,
			"name": "联想"
		}, {
			"value": 1,
			"name": "魅族"
		}, {
			"value": 1,
			"name": "中兴"
		}]
	}]
}

```

#### 其他信息 (Other comments)

线上：http://echarts.baidu.com/demo.html#treemap-drill-down，按重现步骤，ps：不知是否问题，强迫症

**Comment by 100pah** [comment]
如果想设置 第一层的颜色，请设置 levels[0].color ：

```javascript
levels: [
    {
        color: ['#FF7F50','#87CEFA','#DA70D6','#32CD32','#6495ED','#FF69B4','#BA55D3','#CD5C5C','#FFA500','#40E0D0']
    },
    { ... },
    { ... },
    { ... }
]
```

别设置 treemap 的 series.color。这个我在文档上再说明一下。

**Comment by aFcFzF** [comment]
如何渐变呢？设置在第一层，colorSaturation: [.9, .45] 无效了
