### ISSUE TITLE
折线图的平均标线计算方式不合理

### ISSUE THREAD

**Issue by lead210** [ecomfe/echarts#3536]
#### 问题简述 (One-line summary)
     **折线图的markline中的average标线类型，计算方式不合理：**对于空值，也就是系统标记为NaN的值，这些是不应该计算数量的，因为这些数据基本是暂时没有统计进去，是待录入的数据。
     此情况，在2.0版本中不存在，都是扣除空值后计算的；3.0目前存在此问题。
     我目前的解决办法是：自己计算平均值averageClmb，然后按Y轴显示一条平均线，希望后续能更正过来。
     后面又进行了更多的测试，在存在多条折线时，好像算法错误的情况不仅仅是把空值当成0的问题，应该还存在其他错误算法，详细请使用本文的代码测试即可。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):v3.1.10
+ 浏览器类型和版本 (Browser version):IE9.0
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
有空值时，每次均出现结果不合理情况。

#### 期望结果 (Expected behaviour)
计算平均值线，区别对待0和空值。空值只是暂时没有数据，不能纳入平均计算范围。

#### 可能哪里有问题 (What went wrong)
算法。

#### ECharts配置项 (ECharts option)

```javascript
option = {
    title: {
        text: '堆叠区域图'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'line',
            stack: '总量',
            areaStyle: {normal: {}},
            data:[320, 332, 301, 334, 390, 330, 320],
            markLine : {
                data : [
                {type : 'average', name : '平均值'} // 有bug，计算有误
                ]
             }
        },
        {
            name:'搜索引擎',
            type:'line',
            stack: '总量',
            label: {
                normal: {
                    show: true,
                    position: 'top'
                }
            },
            areaStyle: {normal: {}},
            data:[820, 932, 901, , , , ],
            markLine : {
                data : [
                {type : 'average', name : '平均值'} // 有bug，计算有误
                ]
             }
        }
    ]
};

**Comment by pissang** [comment]
3.2.0 已经排除空值了，还有哪里有误？

**Comment by lead210** [comment]
http://echarts.baidu.com/demo.html#area-stack
后面的echart引用应该是最新的3.2.0了吧？把我上面的代码复制进去了。820、932、901 三个数据的平均线是1202  请看下。

**Comment by lead210** [comment]
删除901置为空，保留前面的820和932  平均线还是1202

**Comment by pissang** [comment]
这是因为 markLine 统计的是 stack 后的值

**Comment by lead210** [comment]
"是 stack  #后的值"这个不懂啊，我理解不了，水平不够啊。
我只是感觉，按平常的理解，平均值，应该是某个数据序列本身的非空的数值累加和  除于 非空值的个数，这个平均数才有参考意义。对于平均数，本序列数据平均数，不应该和其他序列数据有任何关联性。echart2.0 对于  折线图，我使用发现好像完全按这个算法来的。
