### ISSUE TITLE
树图中无法对color设置回调函数

### ISSUE THREAD

**Issue by xhzh** [ecomfe/echarts#3538]
#### 问题简述 (One-line summary)
使用的2.2.7版本  <script type="text/javascript" src="static/js/common/echarts-all.js"></script>
需要对tree中的
        series : [ {
			itemStyle : {
				normal : {
					color : function(params) {
						alert("smt!");
					},
回调函数无法被调用

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):
2.2.7
chrome  51.0.2704.103 (64-bit)
mac os
  10.11
#### 重现步骤 (Steps to reproduce)
1.对tree的color设置function，无法被调用
2. 直接设置颜色，没有问题

#### 期望结果 (Expected behaviour)
调用回调函数

#### 可能哪里有问题 (What went wrong)

1.是被禁用了？
2.我引用的js不对？
3.需要手动对每个节点设置color？

#### ECharts配置项 (ECharts option)

```javascript
option = {
		series : [ {
			name : '树图',
			type : 'tree',
			orient : 'horizontal', // vertical horizontal
			rootLocation : {
				x : 100,
				y : 200
			}, // 根节点位置 {x: 100, y: 'center'}
			nodePadding : 8,
			layerPadding : 200,
			hoverable : false,
			roam : true,
			symbol : 'circle',
			symbolSize : 16,
			itemStyle : {
				normal : {
					color : function(params) {
						alert("smt!");
					},
					label : {
						show : true,
						position : 'right',
						formatter : '{b}',
						textStyle : {
							color : '#000',
							fontSize : 5
						}
					},
					lineStyle : {
						color : '#ccc',
						type : 'curve' // 'curve'|'broken'|'solid'|'dotted'|'dashed'

					}
				},
				emphasis : {
					color : '#4883b4',
					label : {
						show : false
					},
					borderWidth : 0
				}
			},
			data : data
		} ]
	}

```

**Comment by pissang** [comment]
你可以单独设置每个数据的 itemStyle.normal.color

**Comment by pyzheng** [comment]
希望有回调，才能动态配置颜色
