### ISSUE TITLE
Default visual map colors work differently in 3.2.0

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3540]
Version: 3.2.0

Not sure if this is an issue or feature but in 3.1.x, visual map gets default theme colors if colors are not specified: 

![image](https://cloud.githubusercontent.com/assets/561365/16516351/ecf450ca-3f77-11e6-994c-2cc9d64abbfd.png)

![image](https://cloud.githubusercontent.com/assets/561365/16516371/03b4eacc-3f78-11e6-82a9-035fd2ae58d7.png)

Where in 3.2.0, this renders as: 

![image](https://cloud.githubusercontent.com/assets/561365/16516384/133631fe-3f78-11e6-89b2-139f4c938c78.png)

If "color" is added, everything is fine: 
![image](https://cloud.githubusercontent.com/assets/561365/16516410/43e5684c-3f78-11e6-9659-17d3e891d0eb.png)

![image](https://cloud.githubusercontent.com/assets/561365/16516455/756da974-3f78-11e6-84e3-29be68c35d1a.png)

Is this intended? 

Anyway, I'm so impressed with new features, the brush feature is awesome!

**Comment by pissang** [comment]
Yes the default value logic is a bit different with 3.1.x. In the new version color property will be adopted only when no visual property is given.

**Comment by jarben** [comment]
Thanks @pissang, will update my charts..
