### ISSUE TITLE
在线构建下载出现问题

### ISSUE THREAD

**Issue by cyxtj** [ecomfe/echarts#3541]
#### 问题简述 (One-line summary)
使用“在线构建”进行下载时出现问题。
下载地址：
http://echarts.baidu.com.cn/builder/echarts.html?charts=bar,line,scatter,heatmap&components=grid,title,legend,tooltip,brush,visualMap,toolbox&version=3
卡在：

Loaded module: "echarts/component/dataZoom/DataZoomModel"
Loaded module: "echarts/component/visualMap/PiecewiseModel"
Loaded module: "echarts/component/visualMap/PiecewiseView"
Loaded module: "echarts/component/dataZoom/AxisProxy"
之后无反应。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):   3
+ 浏览器类型和版本 (Browser version): chrome 或 firefox
+ 操作系统类型和版本 (OS Version): win10

#### 重现步骤 (Steps to reproduce)
1. 直接从浏览器进入http://echarts.baidu.com.cn/builder/echarts.html?charts=bar,line,scatter,heatmap&components=grid,title,legend,tooltip,brush,visualMap,toolbox&version=3

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
这是因为某个文件名不对无法加载，已修复
