### ISSUE TITLE
brushAction.js与brush.js中require('./brush/BrushAction')不一致，导致linux下打包失败

### ISSUE THREAD

**Issue by euphratica** [ecomfe/echarts#3542]
#### 问题简述 (One-line summary)
linux下和mac OS webpack打包时找不到BrushAction
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):linux系统
#### 重现步骤 (Steps to reproduce)
1.
2.
#### 期望结果 (Expected behaviour)
解决该问题
#### 可能哪里有问题 (What went wrong)
brush 文件中是require('./brush/BrushAction');
实际文件名为brushAction，不一致

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢反馈 https://github.com/ecomfe/echarts/commit/04b0f427a98a5ddd16f19600530d64d4480817a5  已修复，下周一新版本
