### ISSUE TITLE
visualMap issues when map and line series are used together 

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3544]
Version: 3.2.0

One of these errors are shown when defining multiple visual maps as visualMap:[..] 

![image](https://cloud.githubusercontent.com/assets/561365/16523535/4e3ce744-3fa4-11e6-9e1e-4959ab793305.png)

I've reproduced this on this example: http://echarts.baidu.com/demo.html#map-china-dataRange

when using multiple map series + **line series** (visual-map-error.js attached inside 
[visual-map-issue.zip](https://github.com/ecomfe/echarts/files/343577/visual-map-issue.zip))

![image](https://cloud.githubusercontent.com/assets/561365/16523571/7891f3ae-3fa4-11e6-9773-5297ee836f2d.png)

I'm defining multiple visual maps so I can style them differenlty: 
![image](https://cloud.githubusercontent.com/assets/561365/16523711/15e0830a-3fa5-11e6-889f-802b74e543e9.png)

However, If I add the line series, the error occurs. 

It can be fixed by defining one visual map only (visual-map-working.js attached inside 
[visual-map-issue.zip](https://github.com/ecomfe/echarts/files/343577/visual-map-issue.zip))

![image](https://cloud.githubusercontent.com/assets/561365/16523752/4967f26c-3fa5-11e6-9530-78094887cb81.png)

However, the line gets also styled as per visualMap settings: 

![image](https://cloud.githubusercontent.com/assets/561365/16523776/67e018c8-3fa5-11e6-8a81-7a77712d05b9.png)

In 3.1.x, it was possible to define visual maps for specific series where undefined series worked as when visual map is not supported (can style them)

**Comment by HydeSong** [comment]
我也遇到类似的问题
