### ISSUE TITLE
scatter-anscombe-quartet question

### ISSUE THREAD

**Issue by GZJackCai** [ecomfe/echarts#3550]
#### 问题简述 (One-line summary)
scatter-anscombe-quartet demo 里的markLineOpt---->data---->coord 是否有相关的api。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

+ echarts V3.0
+chrome the latest
+win 7 home version
#### 重现步骤 (Steps to reproduce)
1.scatter-anscombe-quartet demo 里的markLineOpt---->data---->coord 是否有相关的api,如何设置直线的参数

#### 期望结果 (Expected behaviour)

能提供设置函数图像的Api

#### 可能哪里有问题 (What went wrong)
文档全文搜索找不到，希望能找到相应的文档

#### ECharts配置项 (ECharts option)

```javascript
var markLineOpt = {
    animation: false,
    label: {
        normal: {
            formatter: 'y = 0.5 * x + 3',
            textStyle: {
                align: 'right'
            }
        }
    },
    lineStyle: {
        normal: {
            type: 'solid'
        }
    },
    tooltip: {
        formatter: 'y = 0.5 * x + 3'
    },
    data: [[{
        coord: [0, 3],
        symbol: 'none'
    }, {
        coord: [20, 13],
        symbol: 'none'
    }]]
};

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-scatter.markLine.data
