### ISSUE TITLE
[enhancement 需求] graph 非force layout布局时，允许节点拖动

### ISSUE THREAD

**Issue by zzswang** [ecomfe/echarts#3553]
当下只有 force 布局时，节点可以拖动

希望其他布局，尤其是none 时，可以拖动节点。

**Comment by zzswang** [comment]
这个有计划不？

**Comment by feeee** [comment]
+1

**Comment by carly1987** [comment]
我看http://echarts.baidu.com/echarts2/doc/example/force1.html#blue  2.0 的拖动不会缩回来，但是3.0的会缩回来。如何配置才能像2.0那样，拖动到某一点就停留呢
