### ISSUE TITLE
请问ECharts是否支持动态增加曲线

### ISSUE THREAD

**Issue by LeoLai930603** [ecomfe/echarts#3554]
#### 问题简述 (One-line summary)
如题，详细点说就是，可不可以通过动态修改legend和series参数达到增加或减少图中曲线（并不是通过图例按钮显示或隐藏，而是动态增加或减少）。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): Chrome 51.0.2704.103 m
+ 操作系统类型和版本 (OS Version): Windows 10 64-bits

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以。http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0

**Comment by LeoLai930603** [comment]
是的，我知道异步加载没问题，但是假如我已经有了几条线之后再更新呢？我发现echarts是会报错的。echarts.js:3756 Uncaught Error: Component series. not exists. Load it first.（行数不对请往前看几行，我之前在源码里加了断点看数据）。
![4 6f9i84 mfhw 1z jn q](https://cloud.githubusercontent.com/assets/15106070/16555443/43b1e030-4207-11e6-864e-0fe2969f75dd.png)

**Comment by pissang** [comment]
你没写 type

**Comment by LeoLai930603** [comment]
懂了，谢谢！
