### ISSUE TITLE
3.2.0 版本的路径名问题

### ISSUE THREAD

**Issue by saiyagg** [ecomfe/echarts#3555]
#### 问题简述 (One-line summary)
在 linux 下报找不到 BrushAction

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.0
+ 浏览器类型和版本 (Browser version): 
+ 操作系统类型和版本 (OS Version): linux  2.6.32

#### 可能哪里有问题 (What went wrong)
 https://github.com/ecomfe/echarts/blob/3.2.0/src/component/brush.js#L13
这里 require 的文件名是大写：BrushAction， 而实际文件名为小写：brushAction， linux 下路径名区分大小写，所以找不到报错。

**Comment by pissang** [comment]
已经修复，今天上新版本
