### ISSUE TITLE
图例区域可否出现滚动条？

### ISSUE THREAD

**Issue by LeoLai930603** [ecomfe/echarts#3557]
#### 问题简述 (One-line summary)
我设置了图例区域的宽跟高，但是发现并没有什么用，图例还是无视高度继续向下扩展。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): Chrome
+ 操作系统类型和版本 (OS Version): Windows 10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
legend: {
                    width: '1200px',
                    height: '50px',
                    left: '200px',
                    data: legendData
                }
}

```

#### 其他信息 (Other comments)

![r fdpih qhob6i__1jzv7mf](https://cloud.githubusercontent.com/assets/15106070/16556678/f4200766-420d-11e6-920d-e4a351528531.png)

**Comment by pissang** [comment]
不行，可以自己用 html 自定义图例

**Comment by LeoLai930603** [comment]
那线段的隐藏和显示接口有吗？难道只能自己每次都先用clear清掉实例再手动载入新的option？

**Comment by pissang** [comment]
可以 setOption 第二个参数为 true，也可以通过 dipatchAction({ type: 'http://echarts.baidu.com/api.html#action.legend.legendToggleSelect' }) 见 http://echarts.baidu.com/api.html#action.legend.legendToggleSelect

**Comment by LeoLai930603** [comment]
有更详细的dispatchAction的指引吗？我在button上注册了这样一个事件，但是并没有作用。

`
function legendTest() {
    reviewCharts.dispatchAction({
        type: 'legendToggleSelected',
        name: '日活guid（全量）'
    })
}
`

![w 9ez84iuty9j3 262 dxwf](https://cloud.githubusercontent.com/assets/15106070/16574253/6142a08c-42af-11e6-93e4-56673dd4fcbd.png)

**Comment by pissang** [comment]
是 legendToggleSelect
