### ISSUE TITLE
折线图y坐标的数据可不可以包含空值？

### ISSUE THREAD

**Issue by chenyuzhuang** [ecomfe/echarts#3559]
#### 问题简述 (One-line summary)
我想展现一条折线图，但是有的点可能没有数据，所以我给它赋值为空，怎么样让echart可以绕过这个点去连接这个点左右俩边的线呢？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by chenyuzhuang** [comment]
折线图y坐标的数据可不可以包含空值？

**Comment by otom31** [comment]
我也有同样的问题，一直没有得到解决
