### ISSUE TITLE
折线图y坐标的数据可不可以包含空值？

### ISSUE THREAD

**Issue by chenyuzhuang** [ecomfe/echarts#3560]
#### 问题简述 (One-line summary)

我想画一条折线图，但有的值可能为空，怎么样可以绕过这个空值去连接其他的点？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以，connectNulls
