### ISSUE TITLE
[求助]如何实现鼠标移动到  legend 上触发事件

### ISSUE THREAD

**Issue by mosence** [ecomfe/echarts#3563]
#### 问题简述 (One-line summary)
现在想实现鼠标移动到legend上实时变换选中legend效果。
或者是移动到legend上弹出提示框效果
EC3文档中没有相关接口。我该如何实现或者能不能添加一个MouseOver事件？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts 3

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/3564 欢饮讨论
