### ISSUE TITLE
x轴为time类， series的type能否设置为bar？

### ISSUE THREAD

**Issue by tlemar** [ecomfe/echarts#3565]
#### 问题简述 (One-line summary)
x轴为time类， series的type能否设置为bar？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.X
+ 浏览器类型和版本 (Browser version): chrome 50
+ 操作系统类型和版本 (OS Version): windows 7

#### 重现步骤 (Steps to reproduce)
1. 设置为line的时候可以正常显示
2. 设置为bar的时候无法显示 

#### 期望结果 (Expected behaviour)

希望在设置为bar的时候也能正常显示 

#### ECharts配置项 (ECharts option)

```javascript
        var data = []
        for (i = 0; i < 10; i += 1) {
            data.push([(new Date()).setHours(i, 0, 0), 1])
        }

        for (i = 10; i < 11; i += 1) {
            data.push([(new Date()).setHours(i, 0, 0), 2])
        }
        
        option = {
            xAxis: {
                type: 'time',
                min: (new Date()).setHours(0, 0, 0),
                max: (new Date()).setHours(28, 0, 0),
            },
            yAxis: {
            },
            series: [{
                type:"bar",
                name: '每周统计',
                data: data,
            }]
        };

```

**Comment by pissang** [comment]
暂时不行

**Comment by tlemar** [comment]
现在通过多设几个拐点来完成了 bar绘制。 不过图会比较丑。。。  

还有一个问题时，使用的坐标轴上的时间显示的是 local的时间，可不可以显示为utc的时间？  
如何设置？ 谢谢！
                            console.log("local", time_set.toLocaleString())
                            console.log("utc", time_set.toUTCString())

**Comment by pissang** [comment]
可以通过 formatter 设置
