### ISSUE TITLE
time类型的轴设置min 和max 时候直接使用timestamp生成date时图像错误 

### ISSUE THREAD

**Issue by tlemar** [ecomfe/echarts#3568]
#### 问题简述 (One-line summary)
time类型的轴设置min 和max 时候直接使用timestamp生成date时图像错误 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1. 设置min max值
2. 直接使用timestamp生成的date对象  

#### ECharts配置项 (ECharts option)

```javascript
option = {
                            xAxis: {
                                type: 'time',
                                min: new Date(1463961600000)
                                max: new Date(1463961600000 + 24 * 60 * 60 * 1000)

                            },

}

```

#### 其他信息 (Other comments)

修改成这个样子就是可以的                               
min: new Date(1463961600000).setHours(0,0,0),
max: new Date(1463961600000 + 24 * 60 * 60 * 1000).setHours(0,0,0),

**Comment by pissang** [comment]
min, max 需要是数值，`min: + new Date(1463961600000)`
