### ISSUE TITLE
当Echarts3在Tab切换时，除了第一页签之外的其他页签内容百分比宽度均无效

### ISSUE THREAD

**Issue by tabooblood** [ecomfe/echarts#3569]
#### 问题简述 (One-line summary)
在使用Echarts3在Tab切换时，除了第一页签之外的其他页签内容百分比宽度均无效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.1
+ 浏览器类型和版本 (Browser version):chrome,ie
+ 操作系统类型和版本 (OS Version):win7旗舰

#### 重现步骤 (Steps to reproduce)
1.嵌入Tab之后，切换页签，图表宽度百分比无法实现
2.用js判断后赋予宽度，window onresize将无法自适应宽度

#### 期望结果 (Expected behaviour)
可以获取到百分比，不许另行判断宽度，使其正常实现resize

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
切换 tab 后调用 resize
