### ISSUE TITLE
echars3.0怎么获取到legend对象color属性？

### ISSUE THREAD

**Issue by raly** [ecomfe/echarts#3571]
#### 问题简述 (One-line summary)
在2.0时代，可以通过echars. component.legend获取到图表的实例对象，进而获取到当前图表的颜色。。
但是3.0貌似屏蔽了这些属性。也没提供相关的方法来获取到？

**Comment by pissang** [comment]
可以获取系列的颜色，
```js
myChart.getModel().getSeriesByIndex(0).getData().getVisual('color')
```

**Comment by raly** [comment]
好的。十分感谢

**Comment by newenter** [comment]
“myChart.getModel().getSeriesByIndex(0).getData().getVisual('color')”这个在折线图例中有效，在饼状图是无效，是不是又是不另外一个方法获取了？

**Comment by martin-liu** [comment]
饼图里似乎可以用`chart.getModel().getItemStyle().fill[i]`来拿color
