### ISSUE TITLE
echarts柱状图显示统计值的问题

### ISSUE THREAD

**Issue by sendUbullet** [ecomfe/echarts#3572]
问题简述 (One-line summary)

我现在项目上要用echarts做个柱状图,但是我看了官网的实例没有统计各项的值 然后显示在界面上的效果.你们有什么办法把纵坐标对应的各项值累计显示在右边吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (chrome):
+ 操作系统类型和版本 (OS Version):

#### 期望结果 (Expected behaviour)
![image](https://cloud.githubusercontent.com/assets/18730205/16641126/34bc6836-4430-11e6-8ae3-f2606d2a6c73.png)

**Comment by pissang** [comment]
可以在 formatter 中求和显示

**Comment by sendUbullet** [comment]
您说的formatter中求和显示是当鼠标挨近每个柱状图显示的内容吧？我现在项目上的需求是把年度累计固定在右上方.
![image](https://cloud.githubusercontent.com/assets/18730205/16643761/1dd7310e-444a-11e6-95e9-d9dcc8e17dd7.png)

**Comment by pissang** [comment]
就是年度累计，你拿到数据后就求个和通过 formatter 显示到 legend 上

**Comment by sendUbullet** [comment]
我试了下还是不行.我把我的代码贴出来吧.还有效果图.帮忙看下，十分感谢!
   var  totalData = [234234,423423423];
    var myCharts_bar = echarts.init(document.getElementById('bar_2'));
    option = {
        tooltip: {
            trigger: 'axis'
        },
        legend: {
            data:['实际','预算','实际累计','预算累计'],
            formatter:function (totalData) {
                var res = [];
               for(var i = 0;i<totalData.length;i++ ){
                   res.push(totalData[i]);
               }
                return res;
            }

        },
        xAxis: [
            {
                type: 'category',
                data: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
            }
        ],
        yAxis: [
            {
                type: 'value',
                name: '单位(元)',
                min: 0,
                max: 250,
                interval: 50,
                splitArea: {show: true},
                axisLabel: {
                    formatter: '{value} '
                }
            }

        ],
        series: [
            {
                name:'实际',
                type:'bar',
                itemStyle: {
                    normal: {
                        color: function(params) {
                            // build a color map as your need.
                            var colorList = [
                                '#C1232B','#B5C334','#FCCE10','#E87C25','#27727B',
                                '#FE8463','#9BCA63','#FAD860','#F3A43B','#60C0DD',
                                '#D7504B','#C6E579','#F4E001','#F0805A','#26C0C0'
                            ];
                            return colorList[params.dataIndex]
                        },
                        label: {
                            show: true,
                            position: 'top',
                            formatter: '{b}\n{c}'
                        }
                    }
                },
                data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
                markPoint: {
                    data: [
                        {type: 'max', name: '最大值'}
                    ]
                }
            },
            {
                name:'预算',
                type:'line',
//                yAxisIndex: 1,
                data:[0, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
                markPoint: {
                    data: [
                        {type: 'max', name: '最大值'}
                    ]
                }
            }
        ]
    };
    myCharts_bar.setOption(option);
![image](https://cloud.githubusercontent.com/assets/18730205/16644411/60bc261e-444f-11e6-8589-9803dadeb65b.png)

**Comment by sendUbullet** [comment]
我试了在legend的那写formatter但是还是没效果,我把我代码贴出来和效果图发出来，希望能帮忙看看，感恩不尽了。
< script type = "text/javascript" >
    var totalData = [234234, 423423423];
var myCharts_bar = echarts.init(document.getElementById('bar_2'));
option = {
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data: ['实际', '预算', '实际累计', '预算累计'],
        formatter: function(totalData) {
            var res = [];
            for (var i = 0; i < totalData.length; i++) {
                res.push(totalData[i]);
            }
            return res;
        }

    },
    xAxis: [{
        type: 'category',
        data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
    }],
    yAxis: [{
            type: 'value',
            name: '单位(元)',
            min: 0,
            max: 250,
            interval: 50,
            splitArea: {
                show: true
            },
            axisLabel: {
                formatter: '{value} '
            }
        }

    ],
    series: [{
        name: '实际',
        type: 'bar',
        itemStyle: {
            normal: {
                color: function(params) {
                    // build a color map as your need.
                    var colorList = [
                        '#C1232B', '#B5C334', '#FCCE10', '#E87C25', '#27727B',
                        '#FE8463', '#9BCA63', '#FAD860', '#F3A43B', '#60C0DD',
                        '#D7504B', '#C6E579', '#F4E001', '#F0805A', '#26C0C0'
                    ];
                    return colorList[params.dataIndex]
                },
                label: {
                    show: true,
                    position: 'top',
                    formatter: '{b}\n{c}'
                }
            }
        },
        data: [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
        markPoint: {
            data: [{
                type: 'max',
                name: '最大值'
            }]
        }
    }, {
        name: '预算',
        type: 'line',
        //                yAxisIndex: 1,
        data: [0, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
        markPoint: {
            data: [{
                type: 'max',
                name: '最大值'
            }]
        }
    }]
};
myCharts_bar.setOption(option); 
< /script>
![image](https://cloud.githubusercontent.com/assets/18730205/16644470/e1534e2e-444f-11e6-898a-2ce863b2588e.png)

**Comment by pissang** [comment]
```js
formatter: function () {
// 这里求下面数组的和得到 sum 数值
// [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
   return sum
}
```
