### ISSUE TITLE
给坐标轴的axisLine.lineStyle.color设置渐变颜色报错

### ISSUE THREAD

**Issue by Greenmzc** [ecomfe/echarts#3577]
#### 问题简述 (One-line summary)
给坐标轴的axisLine.lineStyle.color设置渐变颜色，官方例子如下
```javascript
color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
  offset: 0, color: 'red' // 0% 处的颜色
}, {
  offset: 1, color: 'blue' // 100% 处的颜色
}], false)
```
当最后一行true是可以的，false就会报错，无论x轴还是y轴都是如此

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.1
+ 浏览器类型和版本 (Browser version): chrome 51
+ 操作系统类型和版本 (OS Version): OS X 10.11 5

#### 期望结果 (Expected behaviour)
出现渐变颜色

#### 可能哪里有问题 (What went wrong)
绘制canvas时起始坐标和终止坐标类型错误，解析为NaN

#### ECharts配置项 (ECharts option)

```javascript
option = {
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: date,
    axisLine: {
      lineStyle: {
        color: new echarts.graphic.LinearGradient(0, 0, 1, 1, [
          {
            offset: 0,
            color: '#000'
          }, {
            offset: 1,
            color: '#f00'
          },
        ], false)
      }
    }
  },
}

```

#### 其他信息 (Other comments)

报错信息
![2016-07-07 5 42 36](https://cloud.githubusercontent.com/assets/10066358/16649220/794deeae-446a-11e6-8179-d921a423f2f5.png)
![2016-07-07 5 51 51](https://cloud.githubusercontent.com/assets/10066358/16649434/8a8ef7f2-446b-11e6-9826-eb777c00d8fe.png)

**Comment by zhaozhuoboy** [comment]
How is this problem solved？
