### ISSUE TITLE
echarts柱状图折线显示面积的问题

### ISSUE THREAD

**Issue by sendUbullet** [ecomfe/echarts#3579]
#### 问题简述 (One-line summary)
我想实现折线下面的面积效果，但是看官方文档没看到有配置。
希望github上的小伙伴能帮忙看下。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts 3.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
![image](https://cloud.githubusercontent.com/assets/18730205/16676664/4f8be0d6-44ff-11e6-8a9e-2b21f0bfbea4.png)

#### 期望结果 (Expected behaviour)
![image](https://cloud.githubusercontent.com/assets/18730205/16676635/fc7fce5c-44fe-11e6-8e0c-09c6370a1fbf.png)

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
设置 areaStyle: { normal: {} }
