### ISSUE TITLE
x轴坐标显示不全的问题

### ISSUE THREAD

**Issue by longboy** [ecomfe/echarts#3583]
如图，我想全部的都显示，但是在小屏手机显示不完整，这个怎么解决，我都设置了一个斜角。
![00](https://cloud.githubusercontent.com/assets/6941888/16679730/6cf4811a-451c-11e6-8208-6efa27f2b9e2.png)

我想要的效果是：
![111](https://cloud.githubusercontent.com/assets/6941888/16679740/77dfd2d2-451c-11e6-9cc3-0abf0e209ab0.png)

**Comment by pissang** [comment]
调整 grid.bottom

**Comment by longboy** [comment]
你理解错我的意思了，我意思不是说那数字与坐标的距离问题，我是意思是，小屏手机的时候，有些X轴的值没显示出来（如图一），  在大屏手机上它就可以显示出来（如图二）

**Comment by pissang** [comment]
那可以设置 http://echarts.baidu.com/option.html#xAxis.axisLabel.interval

**Comment by gongph** [comment]
@pissang 你好，除非设置 `interval: 0 ` ，否则 x 轴最后一个刻度如果是偶数的话是不显示的。有什么方法可以控制最后一个刻度显示吗？
