### ISSUE TITLE
保存为图片功能在Microsoft Edge下无效

### ISSUE THREAD

**Issue by daoyuanjiao** [ecomfe/echarts#3586]
#### 问题简述 (One-line summary)

官网上示例的保存为图片功能在Microsoft Edge下无效！
http://echarts.baidu.com/demo.html#line-marker
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

能够可以正常截图
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by RicoLiu** [comment]
同样遇到了这个问题，希望能够尽快兼容Edge
