### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by WayneVN** [ecomfe/echarts#3589]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (  "echarts": "^3.2.1", "zrender": "^3.1.1"):
+ 操作系统类型和版本 (osx 10.11.5):
+ node v5.1.0
+ npm 3.3.12

#### 重现步骤 (Steps to reproduce)
1. webpack打包，直接报错
  ``` javascript

ERROR in ./~/echarts/src/coord/axisDefault.js
Module not found: Error: Cannot resolve module 'zrender/core/util' in /Users/mac/Pro/node_modules/echarts/src/coord 
```

 echarts/src/echarts.js 文件中 line:45 var zrUtil = require('zrender/core/util');  但是zrender目录下没有core目录，core目录在src下存在；

#### 期望结果 (Expected behaviour)
统一require路径，或者其他方案

**Comment by pissang** [comment]
是 npm install 安装的吗？有没有安装 zrender 依赖

**Comment by WayneVN** [comment]
嗯，是的，因为是从2升到3的，所以保持了项目内老的 require，应用的还是src内的路径；
多谢解答;
