### ISSUE TITLE
echarts折线图areaStyle面积显示把柱状图覆盖

### ISSUE THREAD

**Issue by sendUbullet** [ecomfe/echarts#3590]
#### 问题简述 (One-line summary)
我的折线图的areaStyle面积显示把红色柱状图覆盖了.

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

下图是我要的areaStyle效果:
![image](https://cloud.githubusercontent.com/assets/18730205/16705583/96c81390-45c0-11e6-8c1b-a9edbd47643d.png)

下图是我现在错误的效果图：
![image](https://cloud.githubusercontent.com/assets/18730205/16705588/eea786b8-45c0-11e6-99dd-591c76f5a632.png)

**Comment by pissang** [comment]
柱状图系列放在面积图后，或者调整 z
