### ISSUE TITLE
数据视图建议添加滚动条

### ISSUE THREAD

**Issue by antorman** [ecomfe/echarts#3591]
#### 问题简述 (One-line summary)

   数据量比较多的情况下，点击数据视图，数据显示不全，建议数据视图表格DIV 添加滚动条
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.0
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):win7
#### 重现步骤 (Steps to reproduce)

1.点击数据视图
#### 期望结果 (Expected behaviour)

源码echarts.js 第 60935行 `viewMain.style.cssText = 'display:block;width:100%;overflow:hidden;';` 
                              修改为: `viewMain.style.cssText = 'display:block;width:100%;overflow:auto;';` 
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by onionch** [comment]
没有滚动条了

**Comment by mirari** [comment]
我也遇到了同样问题，这么久居然还在……
默认的数据视图使用了textarea自带滚动条，所以父节点div禁用了滚动条。但是现在我想用table展现数据时，却发现超出视域的内容没法显示了。虽然这个功能用得不多，但真碰上了还是很纠结啊，不想在源码上改。

**Comment by mirari** [comment]
已解决，套一层div就好了
···
<div style="width: 100%;height: 100%;overflow: auto">
···
