### ISSUE TITLE
建议坐标轴为时间轴时lable的显示

### ISSUE THREAD

**Issue by daoyuanjiao** [ecomfe/echarts#3594]
#### 问题简述 (One-line summary)
目前，类目轴的lable是可以间隔几个显示的，是否可以在坐标轴为time时，也可以这样设定呢？现在的版本里面的设定只是在类目轴时有效！

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
time 轴自动划分刻度

**Comment by daoyuanjiao** [comment]
我的意思是比如我有划分为20个刻度，但是刻度的标签，我不想全部显示出来，只显示0，5，10，15，20，其余小刻度不显示。就像我们平时用的直尺一样！

**Comment by daoyuanjiao** [comment]
刻度线是要画出来的，只是它的数值不全部显示出来
