### ISSUE TITLE
官方配置项手册径向渐变示例有误

### ISSUE THREAD

**Issue by Greenmzc** [ecomfe/echarts#3595]
#### 问题简述 (One-line summary)
项目中要用到很多径向渐变，郁闷的是给color设置径向渐变总是不成功，现在终于找出问题了，原来是官方的文档写错了，误导人啊
<img width="520" alt="2016-07-10 11 54 50" src="https://cloud.githubusercontent.com/assets/10066358/16714596/e2044834-46fa-11e6-8799-ecb55ad6849f.png">
应该是**RadialGradient**，不是RadianGradient，几乎每个渐变实例都写错了，编辑的人有点马虎了

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
  color: new echarts.graphic.RadialGradient(0.5, 0.5, 0.5, [{
    offset: 0,
    color: 'red',
  }, {
    offset: 1,
    color: 'blue',
  }])
}

```

**Comment by Ovilia** [comment]
已修复，线上文档将在下个迭代更新，非常感谢！

**Comment by gitXiaoQing** [comment]
@Ovilia ，您好，现在的线上文档里面好像没有了有关“RadialGradient”的文档说明，可不可以更新，谢谢！

**Comment by 100pah** [comment]
可以参见：<http://echarts.baidu.com/option.html#series-line.itemStyle.normal.color>

**Comment by bcyunbi** [comment]
同踩坑～更新一下
https://echarts.apache.org/v4/zh/option.html#series-radar.areaStyle.color
