### ISSUE TITLE
柱状图X轴月份只显示奇数

### ISSUE THREAD

**Issue by sendUbullet** [ecomfe/echarts#3596]
#### 问题简述 (One-line summary)
我的柱状图X轴月份只显示奇数.

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

 我的代码 ：
    var myCharts_bar = echarts.init(document.getElementById('bar'));
    option = {
        tooltip: {
            trigger: 'axis'
        },
        toolbox: {
            feature: {
                saveAsImage: {show: true}
            },
            left:'90%',
            top:'90%'
        },
        legend: {
            data:['主营业务收入','毛利润','利润比率']
        },
        xAxis: [
            {
                type: 'category',
                data: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
            }
        ],
        yAxis: [
            {
                type: 'value',
                name: '单位(万)',
                min: 0,
                max: 250,
                interval: 50,
                splitArea: {
                    show: true,
                    areaStyle:{
                        opacity:0.3
                    }
                },
                axisLabel: {
                    formatter: '{value} ',
                    margin:2
                }
            },
            {
                type: 'value',
                name: '利润比率',
                min: 0,
                max: 100,
                interval: 20,
                axisLabel: {
                    formatter: '{value} %',
                    textStyle:{
                        fontSize:5
                    },
                    margin:3
                }
            }

        ],
        series: [
            {
                name:'主营业务收入',
                type:'bar',
                z:100,

                data:[0, 5.9, 9.0, 22, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]

            },
            {
                name:'毛利润',
                type:'line',
                z:1,
                data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
                areaStyle: {normal: {
                    color:'#ddf6e8'
                }}

            },
            {
                name:'利润比率',
                type:'line',
                yAxisIndex: 1,
                data:[2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]
            }
        ]
    };
    myCharts_bar.setOption(option);

我的错误图：
![image](https://cloud.githubusercontent.com/assets/18730205/16721563/d8b18abc-4772-11e6-9be9-0ee573e0fc14.png)

#### 期望结果 (Expected behaviour)
![image](https://cloud.githubusercontent.com/assets/18730205/16721587/047e27b8-4773-11e6-9c37-8742739f1da8.png)

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3583#issuecomment-231329379
