### ISSUE TITLE
radar雷达图能否只显示一个轴的标注？

### ISSUE THREAD

**Issue by whucj** [ecomfe/echarts#3599]
#### 问题简述 (One-line summary)
radar雷达图能否只显示一个轴的标注？
当设置radar的axisLabel  show等于true时，会显示所有轴上的标注。
我只想设置某一个轴上的标注

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
只想设置某一个轴上的标注

#### ECharts配置项 (ECharts option)

```javascript
option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        indicator: [
           { name: '销售（sales）', max: 6500},
           { name: '管理（Administration）', max: 16000},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ],
        axisLabel:{show:true}
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4300, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            },
             {
                value : [5000, 14000, 28000, 31000, 42000, 21000],
                name : '实际开销（Actual Spending）'
            }
        ]
    }]
};

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/15603414/16723913/72d6960a-4782-11e6-9c83-66a49a109b66.png)
如上图，我只想显示销售 该轴的labels

**Comment by pissang** [comment]
可以在单个 indicator 上设置 `axisLabel: { show: true }`

**Comment by whucj** [comment]
@pissang  谢谢

**Comment by whucj** [comment]
@pissang  我在echarts  indicator 的配置项里面没有找到 axisLabel 啊？ 请问从哪里可以看出 indicator 下面有这个属性？

**Comment by closertb** [comment]
echarts indicator 的配置项里确实没有这个属性，只有name,min,max

**Comment by zhangsundf** [comment]
@pissang echarts4中雷达图设置axisLabel会报错，这是什么问题？
