### ISSUE TITLE
希望能呈现 柱状图跟表格组合的图表

### ISSUE THREAD

**Issue by 1538986328** [ecomfe/echarts#3601]
[
#### 问题简述 (One-line summary)
有一个需求，柱状图跟表格组合的图表呈现。
其中
柱状图以(0,80)画x轴，x轴跟表格border-top重合，坐标刻度为表格的td，其中（0,80）以2003年这个td顶格，请问如何才能实现？
<table border="1" cellspacing="0" cellpadding="0">
			<tbody><tr>
				<td style="visibility: hidden"></td>
				<td>2003年</td>
				<td>2004年</td>
				<td>2005年</td>
			</tr>
			<tr>
				<td><span style="display:inline-block;width: 20px;height: 15px;background: #87cefa;margin-right: 5px;vertical-align: middle;color: black;"></span>产量</td>
				<td>100</td>
				<td>200</td>
				<td>300</td>
			</tr>
			<tr>
				<td><span style="display:inline-block;width: 20px;height:0;border: 1px dashed #ff7f50;margin-right: 5px;vertical-align: middle;color: black;"></span>收益</td>
				<td>20</td>
				<td>35</td>
				<td>301</td>
			</tr>
		</tbody>
</table>

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
图表呈现 柱图+折线+表格数据的三种组合形式

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以自己寻找合适的表格组件，echarts短期内不会考虑集成

**Comment by luckymore** [comment]
google can do it, but too ugly...
https://developers.google.com/chart/interactive/docs/gallery/table
