### ISSUE TITLE
我想问一下，折线图的x轴label，想根据label的数量来动态显示label，详细描述见下文。

### ISSUE THREAD

**Issue by yipanbo** [ecomfe/echarts#3602]
#### 问题简述 (One-line summary)
详细描述：现在有echarts3的折线图，x轴label个数不一定，可能有30个，也可能有1个。现在想实现的需求是这样的，假如label的数量是1-10个，那么x轴的间隔是2；假如label的数量是1-20个，那么x轴的间隔是4；假如label的数量是1-30个，那么x轴的间隔是5；

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts3
+ 浏览器类型和版本 (Browser version):最好是chrome，最新版的
+ 操作系统类型和版本 (OS Version):windows10

#### 重现步骤 (Steps to reproduce)
1.详见上面的描述

#### 期望结果 (Expected behaviour)
详见上面的描述

#### 可能哪里有问题 (What went wrong)
感觉是可以通过formatter之类的函数来控制的，但是看了 axisLabel的formatter方法，感觉参数不太好实现，希望大神指点一下，谢谢！

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
axisLabel.interval 可以是一个回调函数

**Comment by yipanbo** [comment]
你好，这个回调函数我也注意到了，但是他的参数感觉不太好用啊，是不是还需要和x轴的label个数配合使用呢？

**Comment by yipanbo** [comment]
确实，axisLabel.interval 的回调函数结合x轴的数量可以解决这个问题。下面附上我的代码，可以结贴了。
`xAxis : {
								type : 'category',
								boundaryGap : false,
								data : data.xAxisData,
								axisLabel:{
									interval:function(index, value){
										//显示起始位置的数据
										if(index == 0){
											return true;
										}else if(data.xAxisData.length-1 == index){
											return true;
										}else if( data.xAxisData.length > 0 && data.xAxisData.length < 10){
											if(index % 2 == 0){
												return true;
											}
										}else if( data.xAxisData.length > 0 && data.xAxisData.length < 20){
											if(index % 4 == 0){
												return true;
											}
										}else if( data.xAxisData.length > 0 && data.xAxisData.length < 30){
											if(index % 5 == 0){
												return true;
											}
										}
										
									}
								}
							},`

**Comment by yipanbo** [comment]
@pissang  非常感谢！
