### ISSUE TITLE
【bug】3.2.x,  __DEV__未定义

### ISSUE THREAD

**Issue by kevinwon1985** [ecomfe/echarts#3606]
#### 问题简述 (One-line summary)
某些情况下，3.2.x中新增的__DEV__会导致脚本错误，报__DEV__未定义。最终定位到以下这一行，
https://github.com/ecomfe/echarts/blob/master/src/util/clazz.js#L89。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.x
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
非必现，在我的工程中，有个页面a是毕现的，如果手动进入另外一个页面b在链接页面a则无问题。

**Comment by pissang** [comment]
这是宏定义，你是怎么引入的？

**Comment by kevinwon1985** [comment]
import 'echarts/lib/chart/bar'
import 'echarts/lib/component/grid'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/title'
import 'echarts/lib/component/legend'
import 'echarts/lib/component/dataZoom'
大概就是这样引用的。创建一个react component。
其他地方引用这个component

**Comment by pissang** [comment]
必须要引入模块 import 'charts/lib/echarts'

**Comment by kevinwon1985** [comment]
哦，引入了。因为我是的import 'charts/lib/echarts'在基类组件类中，所以写漏了。用3.1.x代码都是正常的，所以引入上是没问题的。就是换了3.2.x的版本才有着bug

**Comment by kevinwon1985** [comment]
我觉得__DEV__这东西还是有一定危险。。最好还是typeof 判断下。

**Comment by pissang** [comment]
嗯，__DEV__  在 https://github.com/ecomfe/echarts/blob/master/webpack.config.js#L6 宏定义中，为了防止像你这样的场景在 https://github.com/ecomfe/echarts/blob/master/src/echarts.js#L4 额外定义了。如果不 import 'echarts/lib/echarts' 模块整个图表是跑不起来的。

**Comment by lulu3976003** [comment]
![image](https://user-images.githubusercontent.com/24666199/27788041-a10643d0-6019-11e7-9770-6a7fc01ad62f.png)
请问用webpack引入 页面第一次引入没问题  刷新就会报错怎么回事
