### ISSUE TITLE
你们好！请问3.0能提供一个离线的完整api文档么？

### ISSUE THREAD

**Issue by yang3350380** [ecomfe/echarts#3608]
#### 问题简述 (One-line summary)

如题，在没有外网的环境使用简直痛不欲生，而且贵网站的api在手机浏览器上并不能正确显示。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  3.0
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-doc
