### ISSUE TITLE
【咨询】echarts 2.X与echarts 3.0接口向前兼容吗？ 我们一直用的echarts 2.x版本，现在想升级得到echarts3.0，两个版本之间接口有多少一样。要根据这个评估升级风险。接口太多了，不好逐个对比。希望能给个升级建议，感谢！！！

### ISSUE THREAD

**Issue by zhaoweikai** [ecomfe/echarts#3610]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/3322#issuecomment-222884451 ，3 比 2 多了很多功能，而且 2 是不再维护了的，所以建议能升就升
