### ISSUE TITLE
【请教】关于鼠标点击柱状图获得该图的title的问题

### ISSUE THREAD

**Issue by joyceqiao** [ecomfe/echarts#3615]
hi，

在一个页面上有很多柱状图，
鼠标点击某个柱状图（比如说第一个）上的数据，怎么获得该图的title？ params里头没有title， getOption获得的title也不是这个图的title。请问一下有办法能获得吗？

BR
Joyce

**Comment by pissang** [comment]
title 是你自己定义的啊，getOption 也能获取 title

**Comment by joyceqiao** [comment]
getOption的title是最后一个图的title，不是我点击的这个图的title，不知道为什么

**Comment by pissang** [comment]
那你看看调用的实例是不是不正确

**Comment by joyceqiao** [comment]
搞定了，多谢提醒
