### ISSUE TITLE
echarts2中的tree图可以设置线段的长度吗？

### ISSUE THREAD

**Issue by xhzh** [ecomfe/echarts#3616]
#### 问题简述 (One-line summary)
使用tree图的过程中，如果label过长，则不同层的数据会重叠。
能不能设置节点间线段的长度？我看了一下doc，没有找到使线段边长的方法。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by xhzh** [comment]
看到了，layerPadding可以设置。 
谢谢你们的开源组件^_^

**Comment by dxdleikai** [comment]
> layerPadding



> 看到了，layerPadding可以设置。 谢谢你们的开源组件^_^

你好layerPadding有官网吗，我遇到了类似的问题，想看一下怎么用的
