### ISSUE TITLE
Bar Charts with axisLabel.inside = true draw behind bars

### ISSUE THREAD

**Issue by psumstr** [ecomfe/echarts#3621]
#### 问题简述 (One-line summary)
When I place axis labels inside of the bars, the labels draw behind the bars and are not visible.

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version): Chrome 51
+ 操作系统类型和版本 (OS Version): OSX Yosemite

#### 重现步骤 (Steps to reproduce)
1. Open http://echarts.baidu.com/demo.html#bar-tick-align
2. Set xAxis.axisLabel.inside = true

#### 期望结果 (Expected behaviour)
Labels should draw on top of the bars

#### 可能哪里有问题 (What went wrong)
Labels are shown behind the bars

#### ECharts配置项 (ECharts option)

```javascript
option = {
    color: ['#3398DB'],
    tooltip : {
        show: true,
        showContent: true,
        trigger: 'item',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            },
            axisLabel: {
                rotate: 90,
                inside: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '30%',
            data:[10, 52, 200, 334, 390, 330, 220]
        }
    ],
    animationEasing: 'cubicInOut',
    animationEasingUpdate: 'cubicInOut',
    animationDurationUpdate: 1000
};

```

**Comment by pissang** [comment]
xAxis  can have larger z like following:

```js
xAxis: {
  z: 10
}
```

**Comment by psumstr** [comment]
Thanks, I didn't think to try that. The documentation does not show `z` as an option for xAxis, so I'm not sure if it's supposed to be implied for all components.. If it's added in the docs, it will be clearer.

**Comment by pissang** [comment]
Sorry for the doc missing it. All components and series can config z and zlevel.
