### ISSUE TITLE
lines是否可以单独画出来，还是必须与地图配合使用？

### ISSUE THREAD

**Issue by daoyuanjiao** [ecomfe/echarts#3633]
#### 问题简述 (One-line summary)
我在文档里没有看到使用要求，但是我怎么也单独画不出来！

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
可以单独根据坐标画出lines

#### ECharts配置项 (ECharts option)

```javascript
app.title = '世界人口总量 - 条形图';

option = {
    title: {
        text: '世界人口总量',
        subtext: '数据来自网络'
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type: 'value',
        axisTick: {
alignWithLabel: true,
},
    },
    yAxis: {
        type: 'value',
         axisTick: {
alignWithLabel: true,
},
    },
    series: [
        {
            name: '2018年',
            type: 'lines',
            data:[{
                   coords: [[0.2,0.6],[0.4,0.8]]
                    }]
        },
    ]
};


```

**Comment by pissang** [comment]
得设置系列的坐标系

```js
coordinateSystem: 'cartesian2d'
```

**Comment by daoyuanjiao** [comment]
不好意思！坐标支持类目轴吗？我下面这样为什么不行呢？
app.title = '世界人口总量 - 条形图';

option = {
    title: {
        text: '世界人口总量',
        subtext: '数据来自网络'
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type: 'category',
        axisTick: {alignWithLabel: true},
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'category',
         axisTick: {alignWithLabel: true},
        data:['店一','店二','店三','店四']
    },
    series: [
        {
            name: '2018年',
            type: 'lines',
            coordinateSystem: 'cartesian2d',
            data:[{
                   coords:[['周一','店一'],['周三','店四']]
                    }]
        },
    ]
};

**Comment by pissang** [comment]
暂时不支持
