### ISSUE TITLE
当echarts图表transform进行scale缩放时，出现鼠标焦点偏移的问题。

### ISSUE THREAD

**Issue by NameBU** [ecomfe/echarts#3635]
#### 问题简述 (One-line summary)
当echarts图表通过css3 transform属性进行scale缩放时，出现鼠标焦点偏移的问题。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version): Chrome 45、47、48、51等
+ 操作系统类型和版本 (OS Version): windows 7

#### 重现步骤 (Steps to reproduce)
1.在Echarts图表的DOM节点上添加CSS属性    transform:scale(0.7);
2.重新刷新页面后会发现，鼠标焦点出现偏移。（可用地图、柱状图进行测试）

#### 期望结果 (Expected behaviour)
鼠标焦点不会发生偏移。

#### ECharts配置项 (ECharts option)

```javascript
option = {
   
}

```

**Comment by addedjacky** [comment]
同求

**Comment by naeem-accessgroup** [comment]
This issue stops tool-tips and mouse-over effects from working correctly when transform is applied to charts. Transform works perfectly in eCharts 2 so this looks like a bug in mouse co-ordinate calculations for eCharts 3. Can someone advise on whether a fix will be made?

**Comment by 100pah** [comment]
Fixed on <https://github.com/ecomfe/zrender/commit/2c667fd1bd39a4e435a1e38a6824d43c32ffa541>

**Comment by cn-xufei** [comment]
这个问题在最新的版本中还是存在
