### ISSUE TITLE
自定义geojson地图绘制变形

### ISSUE THREAD

**Issue by eddiey233** [ecomfe/echarts#3636]
#### 问题简述 (One-line summary)
用mapshaper导出来的geojson数据用echarts3.2.2绘制之后地图变形

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version): Chrome 51.0.2704.106 m
+ 操作系统类型和版本 (OS Version): Windows 7 旗舰版 SP1

#### 重现步骤 (Steps to reproduce)
1.ajax引入json文件
2.echarts.registerMap注册geojson地图
3.setOption 显示地图

#### 期望结果 (Expected behaviour)
在mapshaper里面地图形状是这样的：
![mapshaper](https://cloud.githubusercontent.com/assets/15482474/16831921/49cd008c-49da-11e6-9636-55efa8ef3740.png)

但是用echarts绘制出来就变细长了：
![image](https://cloud.githubusercontent.com/assets/15482474/16831879/0940c9c2-49da-11e6-8198-54bf86c993e5.png)

#### ECharts配置项 (ECharts option)

```javascript
option = {
    "title": {
        "text": "白云示意图"
    },
    "tooltip": {
        "trigger": "item"
    },
    "toolbox": {
        "show": true,
        "orient": "vertical",
        "left": "right",
        "top": "center",
        "feature": {
            "restore": {},
            "saveAsImage": {}
        }
    },
    "geo": {
        "map": "baiyun",
        "roam": true,
        "label": {
            "emphasis": {
                "show": true,
                "textStyle": {
                    "color": "#000"
                }
            }
        },
        "itemStyle": {
            "normal": {
                "areaColor": "#293C55",
                "borderColor": "#fff"
            },
            "emphasis": {
                "areaColor": "yellow"
            }
        }
    }
}

```

#### 其他信息 (Other comments)
geojson文件
https://drive.google.com/open?id=0B4U-ajjesrrjYTgwbWJIVmV2UGs
或
链接：http://pan.baidu.com/s/1bo0cPQZ 密码：bdkz

**Comment by pissang** [comment]
aspectScale 设成 1 试试

**Comment by eddiey233** [comment]
@pissang 可以了，geo下面aspectScale设置成1就没有变形了。感谢！
但是我在option文档里面怎么没有找到aspectScale这个参数
http://echarts.baidu.com/option.html#geo

**Comment by pissang** [comment]
因为暂时还没开放

**Comment by eddiey233** [comment]
好吧，我一直查API和文档就是没找到到底哪里设置出了问题，现在终于解决了。非常感谢！
