### ISSUE TITLE
how to use svg in echarts3 

### ISSUE THREAD

**Issue by mkaser** [ecomfe/echarts#3642]
#### 问题简述 (One-line summary)
i want to use svg map in echarts3 .but when i use it,error in console.
not Support???

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
SVG support is currently not supported yet in 3

**Comment by freedomlang** [comment]
可以尝试将[svg转成geojson](https://github.com/yuhonyon/svg2geojson)
