### ISSUE TITLE
柱状图X轴的数据过多时label显示不正确

### ISSUE THREAD

**Issue by guozhen168** [ecomfe/echarts#3643]
#### 问题简述 (One-line summary)
>v3.x版本中，柱状图X轴数据过多时，显示的表情不正常，即使用了xAxis.axisLabel.rotate=45也没有效果。

>同样的配置，在v2.2.x下没有问题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): v7
+ 浏览器类型和版本 (Browser version): ie8+,chrome v50
+ 操作系统类型和版本 (OS Version): win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
   ……
  xAxis: [{
    type: 'category',
    boundaryGap: true,
    axisLabel: {
      interval: 'auto',
                            rotate: 45
                        },
      data: ["aaaa","bbbb","cccc","dddd","eeeee","ffff","gggg","hhhh","iiii","jjjj","kkkk","llll","mmmm","nnnn","oooo","pppp","qqqq","rrrr","ssss","tttt","uuuu","vvvv"]
  }],
  ……
}

```

#### 其他信息 (Other comments)

    <script type="text/javascript">
    var myChart = echarts.init(document.getElementById('main'));

    var option = {
        tooltip: {
            show: true
        },
        calculable: true,
        legend: {
            show: true,
            data: [{
                name: '得分'
            }, {
                name: '失分'
            }]
        },
        xAxis: [{
            type: 'category',
            boundaryGap: true,
            axisLabel: {
                interval: 'auto',
                rotate: 45
            },
            data: ["aaaa","bbbb","cccc","dddd","eeeee","ffff","gggg","hhhh","iiii","jjjj","kkkk","llll","mmmm","nnnn","oooo","pppp","qqqq","rrrr","ssss","tttt","uuuu","vvvv"]
        }],
        yAxis: [{
            type: 'value'
        }],
        series: [{
            name: '得分',
            type: 'bar',
            "itemStyle": {
                "normal": {
                    "color": "#55AEBD"
                }
            },
            data: [{
                value: 20
            }, {
                value: 25
            }, {
                value: 22
            }, {
                value: 23
            }, {
                value: 21
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 26.5
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 22.3
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 26
            }, {
                value: 27
            }, {
                value: 27
            }, {
                value: 21
            }]
        }]
    };

    myChart.setOption(option);
    </script>

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#xAxis.axisLabel.interval

**Comment by guozhen168** [comment]
原来是这个属性，那我放心向v3迁移了
