### ISSUE TITLE
myChart.component.grid 在echart3中的代替方式

### ISSUE THREAD

**Issue by dhysf** [ecomfe/echarts#3644]
#### 问题简述 (One-line summary)
1.myChart.component.grid.getWidth() 这个在2中可以使用，在3中好像没有对应的方式获取到了？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3

**Comment by pissang** [comment]
```js
myChart.getModel().getComponent('grid').coordinateSystem.getRect().width
```
