### ISSUE TITLE
【请教】关于柱状图浮层内容的问题

### ISSUE THREAD

**Issue by joyceqiao** [ecomfe/echarts#3648]
hi,

http://echarts.baidu.com/demo.html#bar-negative 
这个实例中鼠标放在具体图上显示的内容为：Y轴的值 加上legead的值。
请问一下在Y轴值不变的情况下，这个浮层的第一行的值能不能变成其他的值？
就图中红色圈起来的那一部分--“周日”， 能够自定义吗？
![1](https://cloud.githubusercontent.com/assets/13128564/16868428/22534fcc-4aaa-11e6-9f35-4df2205214c7.PNG)

谢谢

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#legend.formatter
