### ISSUE TITLE
echarts3.0 where is the loader to handle 'svg' file type ?

### ISSUE THREAD

**Issue by chenjsh36** [ecomfe/echarts#3650]
#### 问题简述 (One-line summary)
echarts3.0新增的可以使用引入模块的方法来加载需要的图表组件，想使用svg的dastapath来作为symbol的时候提示说需要一个loader来处理这种类型，但是找不到相关的模块，有没有关于各个模块对应功能的文档可以让我们开发者参考呢。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):Chrome  51.0.2704.103 m
+ 操作系统类型和版本 (OS Version): win10 64bit

#### 重现步骤 (Steps to reproduce)
1. 类似官网上的[示例](http://echarts.baidu.com/demo.html#geo-lines)，设置了planepath
2. 然后在effect.symbol = planepath

#### 期望结果 (Expected behaviour)
1. 编译的时候提示：Module parse failed: XXX.js Unexpected token (870:8)
You may need an appropriate loader to handle this file type.
报错行就是symbol附近，而且只要将symbol换成‘circle’就可以了

#### ECharts配置项 (ECharts option)

```javascript
var echarts = require('echarts/lib/echarts');

// 引入柱状图
require('echarts/lib/chart/bar');
require('echarts/lib/chart/lines');
require('echarts/lib/chart/scatter');
require('echarts/lib/chart/effectScatter');
// 引入提示框和标题组件
require('echarts/lib/component/tooltip');
require('echarts/lib/component/title');
require('echarts/lib/component/geo'); // for registermap
require('echarts/lib/component/timeline');
require('echarts/lib/component/visualMap');
```

#### 其他信息 (Other comments)

![el1 h nx4ygqp74nie7b7o](https://cloud.githubusercontent.com/assets/11667095/16871123/a0a0972e-4ab7-11e6-9bc2-6f367202c563.png)

**Comment by KevinDeveloper** [comment]
求助，请问你是怎么解决？
echarts3 里面怎么才能加载本地的svg文件呀？

**Comment by KevinDeveloper** [comment]
我现在遇到了这种需求，找了好多资料都没有找到解决方案，找到最相似的是你的这个问题，能帮下忙吗？

**Comment by KevinDeveloper** [comment]
在这里也看到你的问题了，https://segmentfault.com/q/1010000005978959

**Comment by freedomlang** [comment]
可以尝试将[svg转geojson](https://github.com/yuhonyon/svg2geojson)
