### ISSUE TITLE
Symbol 可否 自定义 css 样式

### ISSUE THREAD

**Issue by LeoZeda** [ecomfe/echarts#3652]
现在折线图的symbol可以使用内置的样式 如‘pin’，‘circle’， 或者使用图片 ‘image://url’, 但是这些感觉都不太好，可否使用自己定义的css样式？

**Comment by pissang** [comment]
不行

**Comment by ChenYCL** [comment]
ecahrts是否有接口，在绘制之前对部分样式进行修改
