### ISSUE TITLE
折线图中可以设置终点的式样吗？

### ISSUE THREAD

**Issue by daoyuanjiao** [ecomfe/echarts#3655]
#### 问题简述 (One-line summary)
我想在我的折线图中的某系列的终点处加上一个箭头，表示折线的方向。看到文档中的symbol设定似乎是针对所有的点的。可以指定哪一个点吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
能够指定某点的symbol式样

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以设置单个数据的样式

**Comment by daoyuanjiao** [comment]
可以具体一点吗？我看了文档没有发现！

**Comment by daoyuanjiao** [comment]
谢谢，是在data[i].symbol中吧
