### ISSUE TITLE
多图例性能问题

### ISSUE THREAD

**Issue by qinshenghechu** [ecomfe/echarts#3664]
#### 问题简述 (One-line summary)
单一页面放置8张图例以上，并且每张数据点比较多。访问的时候不一会机器就会发烫，浏览器出现卡顿，
浏览器的cpu消耗蹭蹭往上窜~

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.0
+ 浏览器类型和版本 (Browser version):chrome 50.0.2661.86 (64-bit)
+ 操作系统类型和版本 (OS Version):OS Yosemite 10.10.5

#### 重现步骤 (Steps to reproduce)
1.单一页面创建8张图以上，每张图数据点100以上
2.浏览多图例的网页

#### 期望结果 (Expected behaviour)
期望不会出现明显的网页卡顿现象和发热现象

#### 可能哪里有问题 (What went wrong)
_update:function(){
var time = new Date().getTime();
……
}

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
用 3 试试

**Comment by qinshenghechu** [comment]
看了一下。里面主要是每一个图例都启动了一个定时update。很多图就会很多定时一直在update图例。动态地图是需要动画特效，可能需要刷新，但是如果是折线、饼状图这种一旦画好还需要这个定时update吗？
