### ISSUE TITLE
折线图多数据lable部分不显示

### ISSUE THREAD

**Issue by wpf1994** [ecomfe/echarts#3665]
#### 问题简述 (One-line summary)
折线图中如果一条线的数据量达到30左右，那么有部分的点的lable会不显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 源代码3.2.2
+ 浏览器类型和版本 (Browser version):Chrome
+ 操作系统类型和版本 (OS Version):MAC

#### 期望结果 (Expected behaviour)
希望能够所有不为0的点的lable显示出来

#### 方案
官网的我也尝试了，也不会显示全部，请问有什么办法解决吗

#### 其他信息 (Other comments)
![image](https://cloud.githubusercontent.com/assets/10007650/16910492/9134950a-4d0b-11e6-85c6-69418745a678.png)

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/3643

**Comment by wpf1994** [comment]
谢谢，不过如果
axisLabel: {
                    interval: 0
                }
显示的X轴就太密集了
