### ISSUE TITLE
如何实现多色渐变的仪表盘？(如图)

### ISSUE THREAD

**Issue by xianghongai** [ecomfe/echarts#3668]
官方demo都是比较单调的纯色仪表盘。
不知道如何做下图这种多色渐变的效果？

![demo](https://cloud.githubusercontent.com/assets/2075006/16911048/e4cf55ee-4d0e-11e6-99bd-5bb10d3f2dcb.jpg)

**Comment by Sammiu** [comment]
有人实现了吗？
