### ISSUE TITLE
图例能不能实现分页

### ISSUE THREAD

**Issue by sparkzwx** [ecomfe/echarts#3670]
#### 问题简述 (One-line summary)
当图例过多的时候会出现遮挡，或者图例与图表挤压到一起，能不能做翻页呢？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不能，可以自己用 html 和 css 扩展
