### ISSUE TITLE
基于地图的散点图是否可自定义标记点图标

### ISSUE THREAD

**Issue by HuberyLee** [ecomfe/echarts#3671]
#### 问题简述 (One-line summary)
EChatrs 3 中基于地图的散点图目前存在 静态圆点标注和涟漪圆点标注两种方式，能不能自定义标注点的图标？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by HuberyLee** [comment]
找到了

**Comment by tommyxst** [comment]
请问在哪找到的啊？
