### ISSUE TITLE
X轴为类目轴时显示全【最后的值没有显示出来】

### ISSUE THREAD

**Issue by fukai007** [ecomfe/echarts#3674]
#### 问题简述 (One-line summary)
var xdList = ["0时","1时","2时","3时","4时","5时","6时","7时","8时","9时","10时","11时"];
charts.setoptions({
        xAxis: {
          type: 'category',
          boundaryGap: false,
          data: [],
          // axisLabel: {
          //   interval: 1,   不能写死 因为 数据会变，所以没写
          //   rotate : -90
          // },
          //interval : 'auto'
          //interval : 1
        },
})

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  [3.x.x]
+ 浏览器类型和版本 (Browser version): 53.0.2785.8 dev (64-bit) [都是一样的基本排除 和浏览器有关]
+ 操作系统类型和版本 (OS Version):  mac  10.11.5 【和操作系统也没有什么关系，window ，android, iphone都一样】

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}



#### 其他信息 (Other comments)
我的邮箱 ： 123588195@qq.com  ；手机号 : 134-2634-0847

**Comment by pissang** [comment]
设置 interval 就会出现这个情况，要全部显示把 interval 设为 0

**Comment by fukai007** [comment]
当屏幕宽小于 384 px（移动端） 时 ， interval 设置为0 ， 刻度会出现覆盖的现象。
