### ISSUE TITLE
地图不显示，例子正常工作

### ISSUE THREAD

**Issue by lalahahaane** [ecomfe/echarts#3675]
#### 问题简述 (One-line summary)
加载浙江地图的时候**控制台**出现：
"Map zhejiang not exists. You can download map file on http://echarts.baidu.com/download-map.html" geoCreator.js:47:13

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.1
+ 浏览器类型和版本 (Browser version):火狐
+ 操作系统类型和版本 (OS Version):ubuntu 14.04

#### 重现步骤 (Steps to reproduce)
1.使用webpack,从git下载下来的zrender和echarts放在同一个文件夹下面，`echarts\test`文件夹下面的例子都能正常工作
文件结构为：
```
.
├── echarts
│   ├── asset
│   ├── build
│   ├── dist
│   ├── extension
│   ├── index.common.js
│   ├── index.js
│   ├── index.simple.js
│   ├── lib
│   ├── LICENSE
│   ├── map
│   ├── node_modules
│   ├── package.json
│   ├── README.md
│   ├── src
│   ├── test  # 在这个文件夹下面创建了 hangzhou.html
│   ├── theme
│   └── webpack.config.js
└── zrender
    ├── build
    ├── doc
    ├── jsdoc.json
    ├── lib
    ├── node_modules
    ├── package.json
    ├── README.md
    ├── src
    └── test
```
我想显示浙江地图，除了自己在echarts\test文件夹下面创建的html文件，其他文件均未改动。test\hangzhou.html的代码如下：

```
<html>
    <head>
        <meta charset='utf-8'>
        <script src='esl.js'></script>
        <script src='config.js'></script>
        <script src='../src/echarts.js'></script>
        <script src='../map/js/province/zhejiang.js'></script>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
    </head>
    <body>
        <style>
            html, body, #main {
                width: 100%;
                height: 100%;
                margin: 0;
            }
        </style>
        <div id='main'></div>
        <script>

            require([
                'echarts',

                'echarts/chart/map',
                'echarts/component/title',
                'echarts/component/legend',
                'echarts/component/visualMap',
                'echarts/component/geo'

            ], function (echarts) {
                var myChart = echarts.init(document.getElementById('main'));
                    myChart.setOption({
                        series: [{
                            type: 'map',
                            map: 'zhejiang'
                        }]
                    });

                });
        </script>
    </body>
</html>
```
加载浙江地图的时候**控制台**出现：
"Map zhejiang not exists. You can download map file on http://echarts.baidu.com/download-map.html" geoCreator.js:47:13
2.

#### 期望结果 (Expected behaviour)

说明为何显示不了地图

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不已经提示了去链接处相应的下载地图文件了么

**Comment by lalahahaane** [comment]
我是直接用git clone的echarts,原本git上的echarts下面就有map文件夹，里面全部是各省份的地图js和json,已经下载过了地图文件啊，

map文件夹结构：

`
.
├── js
│   ├── china-contour.js
│   ├── china.js
│   ├── province
│   │   └── zhejiang.js
│   └── world.js
└── json
    ├── china-contour.json
    ├── china.json
    ├── province
    │   └── zhejiang.json
    └── world.json

`

代码这句话：
`<script src='../map/js/province/zhejiang.js'></script>`就是要载入地图

`.
├── echarts
│   ├── asset
│   ├── build
│   ├── dist
│   ├── extension
│   ├── index.common.js
│   ├── index.js
│   ├── index.simple.js
│   ├── lib
│   ├── LICENSE
│   ├── map   # 地图就在这个文件夹下面
│   ├── node_modules
│   ├── package.json
│   ├── README.md
│   ├── src
│   ├── test  # 在这个文件夹下面创建了 hangzhou.html
│   ├── theme
│   └── webpack.config.js
└── zrender
    ├── build
    ├── doc
    ├── jsdoc.json
    ├── lib
    ├── node_modules
    ├── package.json
    ├── README.md
    ├── src
    └── test
`

**Comment by lalahahaane** [comment]
载入json文件可以显示，不知道为什么载入js文件显示不了。用载入地图js文件的方法的时候，所有文件包括地图的js文件都能成功载入，最后出现bug:

加载浙江地图的时候控制台出现：
"Map zhejiang not exists. You can download map file on http://echarts.baidu.com/download-map.html" geoCreator.js:47:13

对应就是：
/echarts/lib/coord/geo/geoCreator.js里的这句话报错

 `console.error('Map ' + name + ' not exists. You can download map file on http://echarts.baidu.com/download-map.html');`

**Comment by wcyong** [comment]
我也载入json文件可以正常显示出地图，但是一直会报console.error('Map ' + name + ' not exists. You can download map file on http://echarts.baidu.com/download-map.html')这个错误，这个问题要怎么解决？

**Comment by zhe-he** [comment]
`import echarts from 'echarts'`  
`import 'echarts/map/js/china'`   
`import 'echarts/map/js/china-contour'` 
`import 'echarts/map/js/province/zhejiang'`
