### ISSUE TITLE
如何在X轴把每月第一天作为刻度点

### ISSUE THREAD

**Issue by qiqiaoshi** [ecomfe/echarts#3676]
#### 问题简述 (One-line summary)
现有每天24条数据记录，要在折线图中显示多个月的数据，要求在X轴把每月第一天作为刻度点。

如何实现在X轴把每月第一天作为刻度点？ 谢谢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (3.2.2):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 期望结果 (Expected behaviour)

如何实现在X轴把每月第一天作为刻度点？ 谢谢

**Comment by pissang** [comment]
如果是 category 的话 interval 可以是一个函数

**Comment by qiqiaoshi** [comment]
给一个示例吧

**Comment by qiqiaoshi** [comment]
问题已解决，感谢
 xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日'],
             axisLabel:{
                 //X轴刻度配置
                 //interval:3 //0：表示全部显示不间隔；auto:表示自动根据刻度个数和宽度自动设置间隔个数
            	interval:function(index,data){alert(data);return true;}
             }
        }
    ],
