### ISSUE TITLE
在空的Chart上调用clear方法产生错误

### ISSUE THREAD

**Issue by JexCheng** [ecomfe/echarts#3677]
#### 问题简述 (One-line summary)
在一个空的Chart上调用clear方法产生错误

#### 重现步骤 (Steps to reproduce)
就下面这样的代码：
```
window.onload = function () {
    var chart = echarts.init(document.getElementById('chartCt'));
    chart.clear();
};
```
会抛出错误：“Uncaught Error: Series has not been initialized yet.”

#### 期望结果 (Expected behaviour)
不应该产生错误

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version): "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
+ 操作系统类型和版本 (OS Version): Win 10

**Comment by pissang** [comment]
这个问题已经提交修复，下个版本 3.2.3 修复

**Comment by hustcc** [comment]
貌似我在 react 中使用 `3.2.3`，webpack 打包出来，依然出现这个问题，退回到 `echarts@3.1.10` 解决。
