### ISSUE TITLE
配置项手册 timeline.label.normal.formatter 示例代码有误

### ISSUE THREAD

**Issue by QinW** [ecomfe/echarts#3680]
配置项手册 timeline.label.normal.formatter 示例代码有误

    if (idx === 0) {
        texts.unshift(date.getYear());
    }

应该改为

    if (index === 0) {
        texts.unshift(date.getFullYear());
    }

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3625
