### ISSUE TITLE
tooltip formatter

### ISSUE THREAD

**Issue by wangjunling** [ecomfe/echarts#3681]
#### 问题简述 (One-line summary)
折线图有多条线，tooltip默认显示时会在每一项前边加上带颜色的圈圈，当我用formatter的时候，这个圆圈怎么加呢？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):windows

#### ECharts配置项 (ECharts option)

```javascript
option = {
  tooltip:{
          formatter:'{b0}<br>{a0}: {c0}家<br />{b1}: {c1}家<br />{b2}: {c2}家<br />{b3}: {c3}家'
      }
}

```

**Comment by pissang** [comment]
用 div 加，formatter需要是函数

**Comment by chenxia123** [comment]
如果让{b1}显示的值为{c1}和{c2}的和，而不是仅仅是{c1}呢？急！！！

**Comment by peterchealse** [comment]
what if the formatter is function? I need to process data with complex proceedures.

**Comment by pissang** [comment]
@peterchealse Formatter can be a function
