### ISSUE TITLE
force 图例里，俩个node节点symbolsize不一样大时，连线的edgesymbol与node之间有间隔或者被遮盖。并且，line设置的edgesymbol不能覆盖series的edgesymbol设置。

### ISSUE THREAD

**Issue by zouljisi** [ecomfe/echarts#3682]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/commit/80254f181848d1b346cef5cc54f3dd91fd660fa1 中已修复

**Comment by zouljisi** [comment]
间隔和遮盖的问题解决了！非常感谢~
但是links里面link对edgeSymbol的配置无法覆盖series对edgeSymbol的配置，即不能做到某条特定的连线的个性化设置。文档中links是有edgeSymbol和edgeSymbolSize的设置，我设置了，但无效，依然取的series中的全局设置。

**Comment by pissang** [comment]
单个 link 的设置应该是 symbol 和 symbolSize，文档中有误，抱歉

**Comment by zouljisi** [comment]
OK,解决了~谢谢！
