### ISSUE TITLE
ECharts#setTheme() is DEPRECATED in ECharts 3.0

### ISSUE THREAD

**Issue by ice0526** [ecomfe/echarts#3685]
为啥取消掉这个方法，2.0的时候有的，换成3.0不支持了，我这边有场景需要用到

**Comment by pissang** [comment]
setTheme 因为切换主题的时候存在配置项泄露的问题所以弃用了，需要改主题的话 dispose 后重新 init

**Comment by JackDan9** [comment]
那现在在init的时候怎么设置主题啊?
