### ISSUE TITLE
webpack + vuejs 使用AMD异步加载组件，运行报错

### ISSUE THREAD

**Issue by GaryDeng629** [ecomfe/echarts#3688]
#### 问题简述 (One-line summary)
webpack + vuejs 使用webpack 自带的AMD异步加载组件，运行报错
error：Invalid data.

传入的数据是正常的

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version): chrome 51.0.2704.103
+ 操作系统类型和版本 (OS Version): mac os

#### 重现步骤 (Steps to reproduce)
1.搭建个webpack ＋ vuejs项目
2.异步加载个组件，这个组建当中引用echart即可重现

#### 期望结果 (Expected behaviour)
异步加载组建正常

#### 可能哪里有问题 (What went wrong)
series传入的是arra，判断的时候确是非数组。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
请给出更详细的代码谢谢
