### ISSUE TITLE
与环信同时使用时 报错： Uncaught Error: Circle dependency may exists

### ISSUE THREAD

**Issue by dsjtlmy** [ecomfe/echarts#3689]
#### 问题简述 (One-line summary)

与环信API（easemob）同时使用时 报错： Uncaught Error: Circle dependency may exists**

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):    3.2.2
+ 浏览器类型和版本 (Browser version):这不重要
+ 操作系统类型和版本 (OS Version):这不重要
环信版本 3.1.1

#### 重现步骤 (Steps to reproduce)
1.  引入jquery、环信官方demo 1.1.1、echarts-3.2.2
2. 初始化饼图demo

#### 可能哪里有问题 (What went wrong)
与环信API兼容问题。

#### ECharts配置项 (ECharts option)

```javascript

//这不重要
option = {
    title : {
        text: '饼图程序调用高亮示例',
        x: 'center'
    },
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        left: 'left',
        data: ['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series : [
        {
            name: '访问来源',
            type: 'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};


```

#### 其他信息 (Other comments)

环信官方demo下载地址
http://docs.easemob.com/start/400webimintegration/10webimintro

引入的js文件
<script src="../assets/global/plugins/jquery-1.11.2.min.js"></script>

<script src="../assets/global/plugins/web-im/static/sdk/strophe.js"></script>
<script src="../assets/global/plugins/web-im/static/sdk/easemob.im-1.1.js"></script>
<script src="../assets/global/plugins/web-im/static/sdk/easemob.im-1.1.shim.js"></script>
<script src="../assets/global/plugins/web-im/static/js/easemob.im.config.js"></script>

<script src="../assets/global/plugins/web-im/static/js/webim-1.1.1.js"></script>

<script type="text/javascript" src="../assets/global/plugins/echarts/echarts-3.2.2.min.js"></script>

**Comment by anming-john** [comment]
我也遇到这个问题， 怎么解决啊， 都没有说出解决方案？？？
