### ISSUE TITLE
legend中的data切换不显示

### ISSUE THREAD

**Issue by zhangsai521314** [ecomfe/echarts#3690]
#### 问题简述 (One-line summary)
图表正中间的上方的数据类型切换的话会不显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version):谷歌 51.0.2704.106 m，火狐47.0
+ 操作系统类型和版本 (OS Version):
win7，旗舰

#### 重现步骤 (Steps to reproduce)
1.定义两个legend的下data数组。
2.切换这两个数组的值，此时在鼠标放上显示的提示div中正常显示但是图表正中间的上方的数据类型提示不显示。同种切换数据单位和yAxis中的name显示正常。
3：错误提示：总定单数量 series not exists. Legend data should be same with series name or data name.

#### 期望结果 (Expected behaviour)
和数据单位和yAxis中的name一样好使。

#### 可能哪里有问题 (What went wrong)
我比较笨。。。。。。

#### ECharts配置项 (ECharts option)

- 

- ```javascript

option = {

}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>张赛</title>
    <style type="text/css">
        #div_main
        {
            width: 1500px;
            height: 800px;
            margin-left: 15%;
        }

        #div_select
        {
            width: 1500px;
            margin-left: 15%;
            padding: 15px 0 30px 0;
        }

            #div_select div
            {
                float: left;
                margin-left: 3px;
            }

        #div_Area
        {
            display: block;
        }

        #div_date
        {
            display: none;
        }

        #div_Empty
        {
            text-align: center;
            width: 1500px;
            height: 800px;
            line-height: 20px;
            position: absolute;
            z-index: 10;
            left: 15%;
            top: 77px;
            display: none;
            color: red;
            font-size: 30px;
        }
    </style>
</head>
<body>
    <input type="button" id="buttion_select" value="查询" />
    <div id="div_main"></div>
    <div id="div_Empty">
        数据为空！
    </div>
    <script src="../js/echarts/echarts3.2.2.js" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        //刷新时重置下拉框
        var myChart = echarts.init(document.getElementById("div_main"));
        //点击查询
        document.getElementById("buttion_select").onclick = function () {
            DataHandle("数量查询");
        };
        //数据处理
        function DataHandle(sourceType) {
            var orderY = [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3], contrasY = [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3], xAxisData = ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'], danWei = "个", showData = ['总定单金额', '总合同金额'], danWeiArry = ['定单金额', '合同金额'];
            if (sourceType == "数量查询") {
                showData = ['总定单数量', '总合同数量'];
                danWeiArry = ['定单数量', '合同数量'];
            } else {
                danWei = "元";
                //showData = ['总定单金额', '总合同金额'];
                // danWeiArry = ['定单金额', '合同金额'];
            }
            var colors = ['#5793f3', '#d14a61', '#675bba'];
            // 指定图表的配置项和数据
            var option = {
                title: {
                    //标题
                    text: '订单-合同统计',
                    subtext: '张赛'
                },
                toolbox: {
                    //设置右上角的图标（切换折线图，下载什么的）
                    show: true,
                    feature: {
                        mark: { show: true },
                        dataView: { show: true, readOnly: false },
                        magicType: { show: true, type: ['line', 'bar'] },
                        restore: { show: true },
                        saveAsImage: { show: true }
                    }
                },
                tooltip: {
                    trigger: 'axis',//当显示的信息需要综合的时候需添加
                    showDelay: 0, // 显示延迟，添加显示延迟可以避免频繁切换，单位ms
                    axisPointer: {            // 坐标轴指示器，坐标轴触发有效
                        type: 'shadow'        // 默认为直线，可选为：‘line‘ | ‘shadow‘,鼠标放上时候的样式
                    }
                },
                legend: {
                    //提示内容
                    data: showData
                },
                dataZoom: [
                        //放大
                            {
                                show: true,
                                start: 94,
                                end: 100
                            },
                            {
                                type: 'inside',
                                start: 94,
                                end: 100
                            },
                            {
                                show: true,
                                yAxisIndex: 0,
                                filterMode: 'empty',
                                width: 30,
                                height: '80%',
                                showDataShadow: false,
                                left: '93%'//设置竖排放大轴
                            }
                ],
                //calculable: false,
                grid: { // 控制图的大小，调整下面这些值就可以，
                    x: 120,
                    x2: 170,
                    y2: 200,// y2可以控制 X轴跟Zoom控件之间的间隔，避免以为倾斜后造成 label重叠到zoom上
                },
                xAxis: {
                    //x轴相关设置
                    //每个柱体的名称
                    data: xAxisData,
                    type: 'category',
                    axisLabel: {
                        interval: 0,//坐标轴刻度标签的显示间隔，在类目轴中有效。默认会采用标签不重叠的策略间隔显示标签。可以设置成 0 强制显示所有标签。如果设置为 1，表示『隔一个标签显示一个标签』，如果值为 2，表示隔两个标签显示一个标签，以此类推。
                        rotate: 45,//柱体名字偏移的角度数
                        margin: 10,//柱体名字往下的距离,刻度标签与轴线之间的距离。
                        textStyle: {
                            color: "red"
                        }
                        //,
                        //formatter: function (val) {
                        //    //文字格式化
                        //    return val.split("").join("\n");//使用这个可以是文字竖排放置，但是使用dataZoom的时候会报错
                        //}
                    },
                },
                yAxis: [
                    {
                        //y轴设置
                        //设置最大最小和平均值时需要添加
                        type: 'value',
                        name: danWeiArry[0],
                        //position: 'right',//让y轴在右边
                        //offset: 80, //如果右边有两个y轴，之间的距离
                        axisLine: {
                            lineStyle: {
                                color: colors[0]
                            }
                        },
                        axisLabel: {
                            formatter: '{value}' + danWei
                        }
                    },
                    {
                        //y轴设置
                        //设置最大最小和平均值时需要添加
                        type: 'value',
                        name: danWeiArry[1],
                        //position: 'right',//让y轴在右边
                        //offset: 80, //如果右边有两个y轴，之间的距离
                        axisLine: {
                            lineStyle: {
                                color: colors[1]
                            }
                        },
                        axisLabel: {
                            formatter: '{value}' + danWei
                        }
                    },
                ],
                series: [
                    {
                        //数据配置
                        name: showData[0],
                        type: 'bar',//数据样式：bar（柱状），line（折线）
                        data: orderY,//数据数组[1,2 ,3 ,4 ,5]
                        markPoint: {
                            //显示最大最小值
                            data: [
                                { type: 'max', name: '最大值' },
                                { type: 'min', name: '最小值' }
                            ]
                        },
                        markLine: {
                            //显示平均值
                            data: [
                                { type: 'average', name: '平均值' }
                            ]
                        }
                    }
                    ,
                     {
                         //数据配置
                         name: showData[1],
                         type: 'bar',//数据样式：bar（柱状），line（折线）
                         yAxisIndex: 1,
                         data: contrasY,//数据数组[1,2 ,3 ,4 ,5]
                         markPoint: {
                             //显示最大最小值
                             data: [
                                 { type: 'max', name: '最大值' },
                                 { type: 'min', name: '最小值' }
                             ]
                         },
                         markLine: {
                             //显示平均值
                             data: [
                                 { type: 'average', name: '平均值' }
                             ]
                         }
                     }
                ]
            };
            // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
        };
        DataHandle("金额查询");
    </script>
</body>
</html>

```


#### 其他信息 (Other comments)
![1](https://cloud.githubusercontent.com/assets/14134256/17017555/5dbf9d52-4f66-11e6-94d3-13bc0479e1b6.png)
![2](https://cloud.githubusercontent.com/assets/14134256/17017562/63d5637a-4f66-11e6-85f9-de2afffd5d8d.png)

**Comment by pissang** [comment]
如错误提示所说，就是因为 legend data 的名字跟系列名字没对应
