### ISSUE TITLE
series中支持可以传一些非配置项要求的参数 吗？

### ISSUE THREAD

**Issue by liumanwei** [ecomfe/echarts#3697]
#### 问题简述 (One-line summary)

series中支持可以传一些非配置项要求的参数 吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以

**Comment by liumanwei** [comment]
那在tooltip里怎么取到传的这些呢

**Comment by liumanwei** [comment]
想在tooltip里的formatter里做一些自定义的东西

**Comment by pissang** [comment]
param.data 里就是传入的具体数据项
