### ISSUE TITLE
Unable to remove boundaryGap in time axis

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3699]
Version: 3.2.2

I can't find a way to remove boundaryGap when xAxis is type of time. Here is an example: 

![boundarygapissue](https://cloud.githubusercontent.com/assets/561365/17050498/72bda00e-4ff3-11e6-838d-9fdc2b709b78.gif)

Notice that when zoom is changed, beginning of the line doesn't start at the beginning of the chart. 

I've tried boundaryGap:["0%","0%"] and other combinations but nothing seems to work. 

If I use 'category' type, it works as expected: 
![boundarygapissue2](https://cloud.githubusercontent.com/assets/561365/17050525/a1b4614a-4ff3-11e6-98be-b96a9e97b4ea.gif)

Real-world example:
![boundarygapissue3](https://cloud.githubusercontent.com/assets/561365/17050708/b5c4806a-4ff4-11e6-9903-31abb43f2b07.gif)

Is this something that can be done with numeric or time types? 

Thanks as usually!

**Comment by jarben** [comment]
+ sample code:

[boundaryGapTime.zip](https://github.com/ecomfe/echarts/files/377765/boundaryGapTime.zip)

**Comment by pissang** [comment]
It's not because of the boundaryGap. Same issue with https://github.com/ecomfe/echarts/issues/3637.

**Comment by jarben** [comment]
Oh, didn't notice that one, thanks for linking it.
