### ISSUE TITLE
force图例能否有node selected状态，目前的需求是需要对选中的节点做一些业务操作。

### ISSUE THREAD

**Issue by zouljisi** [ecomfe/echarts#3705]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没有

**Comment by zouljisi** [comment]
那有没有右键菜单操作呢？
