### ISSUE TITLE
echarts3中怎么用zrender，引入addshape无效

### ISSUE THREAD

**Issue by lufeng0614** [ecomfe/echarts#3708]
#### 问题简述 (One-line summary)
echarts3中怎么用zrender，引入addshape无效

echarts2中就可以用zrender。。。。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): echarts3
+ 浏览器类型和版本 (Browser version):  all
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.    var _ZR = myChart.getZr();
2.    _ZR.addShape("ok");//wrong

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
3 里的图形相关的方法都在 echarts.graphic 命名空间下， zrender 不再直接暴露，添加图形使用
```js
chart.getZr().add(shape)
```

**Comment by lufeng0614** [comment]
请问这个shape 怎么用，按照下面的调用方式报 echarts中t.dirty is not a function
在echarts的官网配置手册里也没找到echarts.graphic() 

                    var shape = {
                        style: {
                            x: 300,
                            y: 10,
                            brushType: 'fill',
                            color: 'yellow',
                            text: '日志汇报统计',
                            textAlign: 'left',
                            textFont: 'normal 8px 微软雅黑'
                        }
                    };
                    var zrender1 = myChart_3.getZr().add(shape);
//                    zrender1.clear();
//                    var TextShape = myChart_3.graphic.Rect ;
                    zrender1.refresh();

**Comment by pissang** [comment]
还没有文档，可以参考 http://echarts.baidu.com/gallery/editor.html?c=map-province这个例子
