### ISSUE TITLE
echarts 2.0里force图例节点的ignore属性在echarts3里可以怎样实现啊？

### ISSUE THREAD

**Issue by zouljisi** [ecomfe/echarts#3710]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
传入的时候做 filter

**Comment by zouljisi** [comment]
我做filter后，前2次点击事件没问题，第三次toogle的时候就报echarts的异常了。setOptions后，nodes可以随便调整嘛？links是不是不用做处理啊。

**Comment by pissang** [comment]
嗯，links 不用做处理

**Comment by zouljisi** [comment]
filter节点后，不会导致内部代码类似于dataIndex出错嘛？

**Comment by pissang** [comment]
厄，好像是可能会有问题

**Comment by zouljisi** [comment]
如果是这样的话，那是不是对data的修改，只能增和改，不能删啊

**Comment by pissang** [comment]
已修复过滤节点后边无法对应的问题，下个版本可以试下
