### ISSUE TITLE
如何绘制国外的详细地图？数据怎么整理？比如绘制印度的地图数据

### ISSUE THREAD

**Issue by zhaozhihao59** [ecomfe/echarts#3712]
#### 问题简述 (One-line summary)
怎样使用echarts 绘制印度地图。。如果没有现成的，如何去整理

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/pissang/starbucks/tree/gh-pages/json

**Comment by xiabai84** [comment]
Hi, it's really nice to use your json map! Could you tell me, how do you gernerate / build the map.json files? I have some geojson data and I'd like to convert to echarts format... please help lol
