### ISSUE TITLE
如何查看echarts的版本，

### ISSUE THREAD

**Issue by fukai007** [ecomfe/echarts#3720]
#### 问题简述 (One-line summary)
1、是否提供静态属性查看Version
2、是否提供对象属性查看Version

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
`echarts.version`
