### ISSUE TITLE
向您咨询下，echarts实现不同区域面积用不同颜色表示么？具体见下

### ISSUE THREAD

**Issue by lsy-scott** [ecomfe/echarts#3723]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win7 

#### 重现步骤 (Steps to reproduce)
不同的数据范围用不同的颜色表示，如下
![image](https://cloud.githubusercontent.com/assets/11308263/17161848/601e6034-53e3-11e6-8a7b-3dc0c925ccaa.png)
谢谢！

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/gallery/editor.html?c=line-aqi
