### ISSUE TITLE
Function Requests: 能否支持批量保存文件，以生成PDF格式报告？

### ISSUE THREAD

**Issue by wangjun-sh** [ecomfe/echarts#3726]
#### 问题简述 (One-line summary)
单个的eCharts都可以点击保存图片。

现在我们需要把很多图，保存到一份PDF报告中去。能否开放一个后台接口，让我们可以方便地保存每张图片，这样我们就可以把多张图片添加到PDF的报告中去了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  3.0
+ 浏览器类型和版本 (Browser version): Chrome 50.0.2661.94 m
+ 操作系统类型和版本 (OS Version): Windows 7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
每个图形对象都能有个SAVEASIMAGE的Method。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
有getDataURL 方法在绘制后生成图片
