### ISSUE TITLE
github->download zip ->echarts-master 3.2.2 中test文件夹里边的例子都看不了

### ISSUE THREAD

**Issue by Jonson9808** [ecomfe/echarts#3730]
#### 问题简述 (One-line summary)
在github上download zip ->echarts-master3.2.2 中test文件夹里边的例子都看不了?

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.2
+ 浏览器类型和版本 (Browser version):google firefox ie opera ...
+ 操作系统类型和版本 (OS Version):windows 7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

1.期望3.2.2可以做到之前2.x的版本一样的功能，在github上下载的源代码例子可以直接打开直观显示，

#### 可能哪里有问题 (What went wrong)
不清楚，已经打包下载最新的版本了

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
需要下载 [zrender](https://github.com/ecomfe/zrender) 放到同级目录下

**Comment by git237491-dd** [comment]
下载了zrender，分别在echarts的同级目录和test文件夹都放了一个，但是还是不行
