### ISSUE TITLE
force图的data可以提供多个维度的数据嘛？

### ISSUE THREAD

**Issue by zouljisi** [ecomfe/echarts#3731]
#### 问题简述 (One-line summary)
force图的data可以提供多个维度的数据嘛？通过visualMap映射多个视觉图

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

"data":[
	    [{"category":0, "name": "A","value" : 0,"account":{"accName":"A"}},{"category":0,"name": "A","value" : 0}],
        [{"category":1, "name": "A1","value" : 1,"account":{"accName":"A1"},"parent":"A"},{"category":1,"name": "A1","value" : 1}],
        [{"category":1, "name": "A2","value" : 1,"account":{"accName":"A2"},"parent":"A"},{"name": "A2","value" : 1}],
        [{"category":1, "name": "A3","value" : 1,"account":{"accName":"A3"},"parent":"A"},{"name": "A3","value" : 1}],
        [{"category":2, "name": "A4","value" : 1,"account":{"accName":"A4"},"parent":"A"},{"name": "A4","value" : 1}],
        [{"category":3, "name": "A5","value" : 1,"account":{"accName":"A5"},"parent":"A"},{"name": "A5","value" : 1}],
        [{"category":0, "name": "B","value" : 0,"account":{"accName":"B"}},{"name": "B","value" : 0}],
        [{"category":1, "name": "B1","value" : 1,"account":{"accName":"B1"},"parent":"B"},{"name": "B1","value" : 1}],
        [{"category":1, "name": "B2","value" : 1,"account":{"accName":"B2"},"parent":"B"},{"name": "B2","value" : 1}],
        [{"category":1, "name": "B3","value" : 1,"account":{"accName":"B3"},"parent":"B"},{"name": "B3","value" : 1}],
        [{"category":1, "name": "B4","value" : 1,"account":{"accName":"B4"},"parent":"B"},{"name": "B4","value" : 1}],
        [{"category":1, "name": "B5","value" : 1,"account":{"accName":"B5"},"parent":"B"},{"name": "B5","value" : 1}],
        [{"category":5, "name": "M1","value" : -1},{"name": "M1","value" : -1}],
        [{"category":0, "name": "C","value" : 0,"account":{"accName":"C"}},{"name": "C","value" : 0}],
        [{"category":1, "name": "C1","value" : 1,"account":{"accName":"C1"}},{"name": "C1","value" : 1}],
        [{"category":1, "name": "C2","value" : 1,"account":{"accName":"C2"}},{"name": "C2","value" : 1}],
        [{"category":1, "name": "C3","value" : 1,"account":{"accName":"C3"}},{"name": "C3","value" : 1}],
        [{"category":1, "name": "C4","value" : 1,"account":{"accName":"C4"}},{"name": "C4","value" : 1}],
        [{"category":1, "name": "C5","value" : 1,"account":{"accName":"C5"}},{"name": "C5","value" : 1}],
        [{"category":4, "name": "M2","value" : -1},{"name": "M2","value" : -1}],
        [{"category":1, "name": "D1","value" : 2,"account":{"accName":"D1"}},{"name": "D1","value" : 2}],
        [{"category":1, "name": "D2","value" : 2,"account":{"accName":"D2"}},{"name": "D2","value" : 2}],
        [{"category":1, "name": "E1","value" : 3,"account":{"accName":"E1"}},{"name": "E1","value" : 3}],
        [{"category":6, "name": "M3","value" : -1},{"name": "M3","value" : -1}]
	],

```


#### 其他信息 (Other comments)
<!-- 例如，截图或线上实例 (JSFiddle/JSBin/Codepen) (For example: Screenshot or Online demo) -->

**Comment by pissang** [comment]
可以的

**Comment by zouljisi** [comment]
我的数据格式如上面描述的有问题嘛？我这里显示好像有点问题

**Comment by zouljisi** [comment]
data多维的数据格式必须为[[1,2],[1,2]]这样的嘛，不能为[[{name:'xx',value:1},{name:'xxx',value:111}],[{name:'xx',value:1},{name:'xxx',value:111}]]嘛？

**Comment by pissang** [comment]
如果要多维度，必须得是 value 项里用数组描述

**Comment by zouljisi** [comment]
如下这种写法嘛？我试了几种都不行哦
{"category":0, "name": "A","value" : [0,100],"account":{"accName":"A"}}

**Comment by zouljisi** [comment]
不好意思，上述写法是OK的。3Q
