### ISSUE TITLE
graph的lineStyle属性不起作用吗？

### ISSUE THREAD

**Issue by lissic** [ecomfe/echarts#3732]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![a](https://cloud.githubusercontent.com/assets/17635743/17201749/fdabbd70-54c3-11e6-9499-b7212ac2980b.png)

**Comment by pissang** [comment]
是在 series 里设置
