### ISSUE TITLE
coordSys.getOtherAxis is not a function

### ISSUE THREAD

**Issue by anke1460** [ecomfe/echarts#3741]
#### 问题简述 (One-line summary)

```
import echarts from 'echarts';
import "echarts/lib/chart/map.js";
import "echarts/map/js/china.js";
let map = echarts.init(document.getElementById('map'), 'macarons');
map.setOption({
  tooltip : {
    show: false
  },
  series : [
    {
      name: '中国地图',
      type: 'map',
      mapType: 'china',
      hoverable :false,
      itemStyle:{
        normal:{label:{show:false},areaStyle:{color:'#ffffff'},borderWidth:1,borderColor:'#a8c1cc'},
        emphasis:{label:{show:false}, color:'#4ddd36'}
      },
      data:[
        {name:'河南',selected:true},
        {name:'湖南',selected:true},
        {name:'浙江',selected:true}
      ],
      markPoint : {
        itemStyle : {
          normal:{
            color:'skyblue'
          }
        },
        data : [
          {name : '天津', symbol: 'image://../assets/images/dian.png'},
          {name : '上海', symbol: 'image://../assets/images/dian.png'}
        ]
      },
      geoCoord: {
        '上海': [121.4648,31.2891],
        '天津': [117.4219,39.4189]
      }
    }
  ]
});
```
显示map会报错
提示，markerHelper.js?fe54:146 Uncaught TypeError: coordSys.getOtherAxis is not a function
把markPoint的配置去掉地图会显示正常。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): osx

#### 重现步骤 (Steps to reproduce)
1. 
2.

#### 可能哪里有问题 (What went wrong)

查看了源码，geo缺少一个getOtherAxis方法。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
markPoint 的 data 需要提供一个 coord

**Comment by ericWenjp** [comment]
我也出现这个问题，在makPoint的data中加了coord，也不行，希望官方能给个demo出来，万分感谢！！！！！！

**Comment by chaixiaofei** [comment]
同问啊，打包完报错

**Comment by evgeny-s** [comment]
Same problem here. Can anybody provide example and explain in English? I've moved from 2nd version to 3rd and this error occurred. Thank you.

**Comment by SilnaJem** [comment]
你好，问题是怎样解决的

**Comment by anasanzari** [comment]
Same issue

**Comment by mying01** [comment]
在makPoint的data中加了geoCoord，也不行

**Comment by mistyrain98** [comment]
for example
      markPoint: {
          data: [{
            name: '上海',
            coord: [121.4648, 31.2891]
          }]
        }

**Comment by Rush-YL** [comment]
`markPoint: {
            symbol: 'emptyCircle',
            symbolSize: function(v) {
              return 10 + v / 10;
            },
            effect: {
              show: true,
              shadowBlur: 0
            },
            itemStyle: {
              normal: {
                label: { show: false }
              },
              emphasis: {
                label: { position: 'top' }
              }
            },
            data: [
              { name: '上海', value: 95, coord: this.mpc.getCoord('上海') },
              { name: '广州', value: 90, coord: this.mpc.getCoord('广州') },
              { name: '大连', value: 80, coord: this.mpc.getCoord('大连') },
              { name: '南宁', value: 70, coord: this.mpc.getCoord('南宁') },
              { name: '南昌', value: 60, coord: this.mpc.getCoord('南昌') },
              { name: '拉萨', value: 50, coord: this.mpc.getCoord('拉萨') },
              { name: '长春', value: 40, coord: this.mpc.getCoord('长春') },
              { name: '包头', value: 30, coord: this.mpc.getCoord('包头') },
              { name: '重庆', value: 20, coord: this.mpc.getCoord('重庆') },
              { name: '常州', value: 10, coord: this.mpc.getCoord('常州') }
            ]
          }`
version: 4.1.0,
environment: angular6,
chrome console.log(markPoint) => data: Array(10)
0:
coord: (2) [121.48, 31.22]
name: "上海"
value: 95
__proto__: Object
1: {name: "广州", value: 90, coord: Array(2)}
2: {name: "大连", value: 80, coord: Array(2)}
3: {name: "南宁", value: 70, coord: Array(2)}
4: {name: "南昌", value: 60, coord: Array(2)}
5: {name: "拉萨", value: 50, coord: Array(2)}
6: {name: "长春", value: 40, coord: Array(2)}
7: {name: "包头", value: 30, coord: Array(2)}
8: {name: "重庆", value: 20, coord: Array(2)}
9: {name: "常州", value: 10, coord: Array(2)}],
effect: {show: true, shadowBlur: 0},
itemStyle: {normal: {…}, emphasis: {…}},
symbol: "emptyCircle",
symbolSize: ƒ (v)
result: coordSys.getOtherAxis is not a function

**Comment by Ende93** [comment]
maybe the `coord` in some `markPoint.data` is not array
