### ISSUE TITLE
Chrome右键“复制图片”，粘贴出来全是黑的，FF也有类似问题

### ISSUE THREAD

**Issue by bi-kai** [ecomfe/echarts#3742]
#### 问题简述 (One-line summary)
一、echarts 2.2.7
1、Chrome右键“复制图片”，粘贴出来__全是黑的__；
2、FF右键“查看图像”，就__没图__，“复制图像”，粘贴出来__全是黑的__；
二、echarts 3.x
1、Chrome右键“复制图片”，粘贴出来有图，但__背景也是黑的__；
2、FF右键“查看图像”，有图，“复制图像”，粘贴出来有图，但__背景也是黑的__；

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7 ，3.x
+ 浏览器类型和版本 (Browser version): FF最新版，CHrome最新版
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.Chrome右键“复制图片”
2.、FF右键“查看图像”，“复制图像”

#### 期望结果 (Expected behaviour)
1、如果能直接复制，粘贴到word或画图中最好；
2、让浏览器不认为canvas是图片；
3、如果无法实现1和2，在图的区域上屏蔽浏览器右键菜单也可以。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不要直接复制图片，有些例子复制的话只有部分，最好是 toolbox 中下载，或者直接用截图工具截图

**Comment by bi-kai** [comment]
@pissang 是的，我也一直用toolbox中的下载图片。但是有些用户的使用习惯问题，我也知道这是浏览器的行为了，但是客户投诉了，这个问题就要想办法规避。
你看这三种方式，那种可行：
1、如果能直接复制，粘贴到word或画图中最好；
2、让浏览器不认为canvas是图片；
3、如果无法实现1和2，在图的区域上屏蔽浏览器右键菜单也可以。

或者有什么更好的建议么？

**Comment by pissang** [comment]
屏蔽右键菜单可以你们自己实现，如果只有一层 canvas，你可以设置 `backgroundColor: 'white'` 保证白色背景

**Comment by bi-kai** [comment]
@pissang 3.x版本右键能复制出图来，但背景是黑的，可以尝试你说的设置白的背景色。
但2.x版本复制出来只有黑色，估计改背景色是不行的了。

**Comment by pissang** [comment]
一般背景应该是透明色，2 的因为最上面有个默认什么都不显示的 hover 层 canvas 所以复制可能都是黑色

**Comment by bi-kai** [comment]
@pissang 我目前用的就是2.2.7，你说的最上边覆盖了hover层，是不是我描述的右键问题，这个版本上就无法解决了？我只能换3.x了，是吧？

**Comment by pissang** [comment]
嗯用3，2不再更新了
