### ISSUE TITLE
Instance Method

### ISSUE THREAD

**Issue by coskuntekin** [ecomfe/echarts#3745]
#### Question:

In version 2 echart has [instance method](http://echarts.baidu.com/echarts2/doc/doc-en.html#Instance-Methods) But in version 3 i can't find instance method. 
So do you have any alternative method as like instance method in version 3.

**Comment by pissang** [comment]
https://ecomfe.github.io/echarts-doc/public/api-en.html#echartsInstance

**Comment by coskuntekin** [comment]
@pissang thank you for quickly reply me. 
I have one more question. In version 2 i can use  legend `getColor`. But seems like version 3 has no `getColor`. 
Do you have any idea?

**Comment by pissang** [comment]
Yes it has been removed.

Instead you can use
```js
myChart.getModel().getSeriesByName(someSeriesName).getVisual('color')
```

**Comment by coskuntekin** [comment]
@pissang ok thank you. Let me try.

**Comment by coskuntekin** [comment]
@pissang hi again;
 would you check this pen what i am missing?
http://codepen.io/coskuntekin/pen/LkBaRq

i am getting this error.
```
Uncaught TypeError: myChart.getModel(...).getSeriesByName(...).getVisual is not a function
```

**Comment by pissang** [comment]
Sorry my fault. It should be 
```js
myChart.getModel().getSeriesByName('销量')[0].getData().getVisual('color')
```

**Comment by coskuntekin** [comment]
@pissang it's fine. so i have one more question. 
In version 2 legend has `setSelected` method, how about in version 3. How can i use?

**Comment by coskuntekin** [comment]
i searched in documents but i can't find, seems like removed and i didn't see any other alternative method in documents (or missed)

**Comment by pissang** [comment]
You can use `dispatchAction` to have legend selected, dataZoom changed actions.

Like:

dispatchAction({
   type: 'legendSelect',
   name: 'someLegend'
});

See more at https://ecomfe.github.io/echarts-doc/public/api-en.html#action.legend

**Comment by coskuntekin** [comment]
Thank you. 
Here is my pen about `getVisual` and `setSelected` legend, maybe someone need it, later.
http://codepen.io/coskuntekin/pen/LkBaRq

**Comment by pissang** [comment]
Great! Thanks for sharing it!

**Comment by coskuntekin** [comment]
@pissang i bother you again sorry.
`dispatchAction` is only working with `selectedMode:single` or i missed something? 
Would you check this pen?
http://codepen.io/coskuntekin/pen/LkBaRq

**Comment by pissang** [comment]
`legendSelect` is for **select** the legend. If you wan't to toggle the selected status you should dispatch `legendToggleSelect` action

**Comment by coskuntekin** [comment]
@pissang don't mention it. i used `legendToggleSelect` then it is done.

**Comment by coskuntekin** [comment]
Hi again;

How can i set legend color?

`initChart.getModel().getSeriesByName("Cluster")[0].getData().setVisual('#000');`

Can i do like that?

**Comment by pissang** [comment]
I suggest not setting color like that. `setVisual` is used in the visual encoding stage before rendering after setOption.

Insead you should always use `setOption` or `dispatchAction` if you wan't to change the view. In this case `setOption` is the only way

**Comment by coskuntekin** [comment]
ok, thank you for your suggestion, i will try.
