### ISSUE TITLE
Pie图的标签能否自定义

### ISSUE THREAD

**Issue by visgoods** [ecomfe/echarts#3746]
#### 问题简述 (One-line summary)

Pie图的标签样式现在不是很好，在页面中不是很好布局，影响美观。
比如我想把所有标签的视觉引导线都朝向左边，或者右边，而不是现在的360度方向，朝向一个方向对页面布局很有好处，且美观。
还有，标签文字和值能不能在视觉线的上下，这样可以节省空间。
如下图

谢谢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![Uploading 8A0AC1E5-8AD2-4B28-ADA1-B354C4D4323E.png…]()

**Comment by visgoods** [comment]
![Uploading 8A0AC1E5-8AD2-4B28-ADA1-B354C4D4323E.png…]()
![Uploading 8A0AC1E5-8AD2-4B28-ADA1-B354C4D4323E.png…]()

**Comment by pissang** [comment]
暂时不行
