### ISSUE TITLE
Chart Resize

### ISSUE THREAD

**Issue by SofiaGR** [ecomfe/echarts#3747]
Sorry for not using the format given, but I just have a quick question. Is the function echartsInstance.resize supposed to change just the width of the chart? The height remains unchanged in all the resize attempts I tried, much like the one below:
https://jsfiddle.net/a4d8xcxu/

Is there any way to update the height also?

**Comment by pissang** [comment]
Because you have fixed the height to 600px.

**Comment by SofiaGR** [comment]
I can't remove the height though or I get an error. How do I get the resize to work for height and width then?

**Comment by pissang** [comment]
You can have percent height if you wan't to resize when window is resized.

The only thing you need to make sure is echarts can get clientWidth and clientHeight of dom when `init` an instance

**Comment by SofiaGR** [comment]
I figured out what the issue was, in that jsfiddle I posted for example: if I put 100% height in body, I can't forget to apply it to its parent (html) as well so that it has a value when the chart is initialized.

Thanks!
