### ISSUE TITLE
xAxis 横坐标增加点击事件

### ISSUE THREAD

**Issue by liubinwang2009** [ecomfe/echarts#3750]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version):QQ浏览器chrome 内核
+ 操作系统类型和版本 (OS Version):windows

#### 重现步骤 (Steps to reproduce)
1. series  data数据相差比较大 ，比如 data:[320, 332, 301, 334, 390, 330, 320,100,200,400,100,2],  柱状图展示2的数据柱条显示特别矮，柱条太小鼠标要精确移动才能点击到。

#### 期望结果 (Expected behaviour)
xAxis  data 增加同样点击事件

#### ECharts配置项 (ECharts option)

```javascript
option = {
     tooltip : {
            trigger: 'axis',
            axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
            }
        },
        legend: {
            data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis : [
            {
                type : 'category',
                data : ['1','2','3','4','5','6','7','8','9','10','11','12']     //这里增加点击事件
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
         /*toolbox: {
            show : true,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },*/
        series : [
            {
                name:'直接访问',
                type:'bar',
                stack: '广告',
                data:[320, 332, 301, 334, 390, 330, 320,100,200,400,100,2]  //2的柱条显示太小点击不到
            }
            
        ]
}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#xAxis.triggerEvent

**Comment by liubinwang2009** [comment]
xAxis.triggerEvent  设为true   点击并无触发
myChart.on("click", function (param) {  
		alert(param.dataIndex);   
 });

**Comment by pissang** [comment]
有效果的

**Comment by liubinwang2009** [comment]
经测试，没有触发，xAxis , yAxis  都加了  triggerEvent       都无效果，下面是代码
还有一个需求，单个类型统计柱条只显示一个颜色，客户看了觉得我们用的是老技术，不够绚丽好看，实际上我们用的是最新版echarts，现在要求柱条能显示不同颜色，看了源码，还是无从下手，希望你们能提供修改方法

// 指定图表的配置项和数据
   option = {
	
        tooltip : {
            trigger: 'axis',
            axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
            }
        },
        legend: {
            data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis : [
            {
                type : 'category',
                data : ['1','2','3','4','5','6','7','8','9','10','11','12'],
				triggerEvent:true
            }
        ],
        yAxis : [
            {
                type : 'value',
				triggerEvent:true
            }
        ],
         /*toolbox: {
            show : true,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },*/
        series : [
            {
                name:'直接访问',
                type:'bar',
                stack: '广告',
                data:[233, 332, 301, 334, 390, 330, 320,100,200,400,100,2]
            }
            
        ]
    };
    myChart.setOption(option);
	
    myChart.on("click", function (param) {  
		console.log(param);
	 });

**Comment by F-manew2** [comment]
@liubinwang2009 这个问题你有没有解决？和你同样的问题

**Comment by liubinwang2009** [comment]
@F-manew2    解决了，是我没有更新到最新版本，最新版本是可以的  xAxis.triggerEvent 设为true

**Comment by wu11106** [comment]
是的！用雪豹做，雪豹在谷歌浏览器上翻译插件很难翻译过来，这并不是困难，做多几次，熟练了就很操作很快。最后认定了雪豹就雪豹，不要再考虑别一种，要你我合拍不容易。

2016年8月24日星期三，liubinwang2009 <notifications@github.com> 写道：

**Comment by F-manew2** [comment]
@liubinwang2009 请问你升级到哪个版本了？
 我用的版本是 3.1.10，估计不支持，关键是3.1和3.2 还是有区别的，升级可能会影响到其他功能，我先试试升级吧，哎。。。

**Comment by liubinwang2009** [comment]
@F-manew2   升级到v3.2.2   看下更新日志  这个版本才有 这个属性 http://echarts.baidu.com/changelog.html

**Comment by F-manew2** [comment]
@liubinwang2009  好的， 多谢， 我升级一下 试试

**Comment by x4storm** [comment]
雷达图的 triggerEvent 还是无效

**Comment by F-manew2** [comment]
@x4storm 我的柱状图升级后可以了，可以把你的option贴出来，让大伙看看

**Comment by x4storm** [comment]
@F-manew2 我试了下，确实无效。可能目前还只修复了横纵坐标的点击问题吧。
```javascript
{
      radar: {
        xAxis:{
          triggerEvent:true
        },
        name:{
          textStyle:{
            color:'#333'
          }
        },
        silent:false,
        triggerEvent:true,
        indicator: [{
          name: 'MBB Penetration',
          max: 5
        }, {
          name: 'EBITDA Marign',
          max: 5
        }, {
          name: 'LTE FDD \n Average Rate',
          max: 5
        }, {
          name: 'UMTS Average Rate',
          max: 5
        }, {
          name: 'Smart Phone Ratio',
          max: 5
        }, {
          name: 'Video OTT \n Cooperation',
          max: 5
        }, {
          name: 'Pric Per GB',
          max: 5
        }, ]
      },
      series: [{
        name: '',
        type: 'radar',
        itemStyle: {
          normal: {
            color: '#3ba0ff'
          }
        },
        lineStyle: {
          normal: {
            color: '#3ba0ff'
          }
        },
        data: [{
          value: [5, 3, 4, 3, 4, 3, 3],
          name: 'xxx',
          symbol: 'circle',
          symbolSize: 6,
          areaStyle: {
            normal: {
              opacity: 0.45,
              color: '#58aeff'
            }
          }
        }]
      }]
    };
```

**Comment by F-manew2** [comment]
@x4storm 刚试了一下，确实不行
