### ISSUE TITLE
如何在同一个图像中清除上一次加载的series数据！

### ISSUE THREAD

**Issue by daoyuanjiao** [ecomfe/echarts#3752]
#### 问题简述 (One-line summary)
我用一个下拉框选择加载不同的时间的数据，下拉框绑定了一个xialakuang()函数，里面用$.post和 myChart.setOption(option)更新不同的数据。但是发现每次都是在原来的series基础上加载数据。比如我连续选择下拉框中同样的选项10次，似乎会加载10次数据，严重拖慢响应速度。我用myChart.setOption(option,true);让它（可选，是否不跟之前设置的option进行合并，默认为false，即合并。），但是没有效果。我在myChart.setOption(option)之前加上myChart.clear也没有效果！
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
每次在加载series数据时，可以配置清楚之前的series。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
setOption({}, true)

**Comment by daoyuanjiao** [comment]
setOption(option, true)，我是在xialakuang()里面添加了series数据，其它的X轴等信息全部是在另一个地方设置的，导致用这个setOption(option, true)不成功，现在全部的设置都放在xialakuang()这个函数下面就可以了！但是我的想法只是更新series数据，保留其余的设置的。否则每次从新选择时间时，都要重新设置一遍所有的设置！

**Comment by bobowei** [comment]
我试了这个方法也不行呢
