### ISSUE TITLE
mapLocation中同时设置宽和高，只有其中一个生效

### ISSUE THREAD

**Issue by ww156** [ecomfe/echarts#3754]
#### 问题简述 (One-line summary)
地图比例保持不变，设置宽和高，只有其中相对小的会生效，另一个值是按照一定比例计算出来的

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.0
+ 浏览器类型和版本 (Browser version):360安全浏览器8.1.1.210
+ 操作系统类型和版本 (OS Version):windows10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
自己设置的宽和高能够同时生效

#### 可能哪里有问题 (What went wrong)
设置地图宽高比的属性

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

http://echarts.baidu.com/echarts2/doc/example/map.html#

**Comment by pissang** [comment]
3 里可以设置 left，top，width，height 强制拉伸
