### ISSUE TITLE
关系图如何自动撑满整个画板？

### ISSUE THREAD

**Issue by jadyyang** [ecomfe/echarts#3755]
#### 问题简述 (One-line summary)
关系图如何自动撑满整个画板？因为划出的节点可能多可能少，多的时候问题不大，但是少的时候，画出的图形只占了很小的一部分区域，而且也看不太清楚。不知道能否自适应，撑满整个画板？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.1
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
}

```

**Comment by pissang** [comment]
`left: 0, right: 0, top: 0, bottom: 0` 但是如果是 `layout: 'force'` 还会受布局参数的影响

**Comment by jadyyang** [comment]
@pissang layout就是force，canvas的大小也是比较大的（500*500像素），但是节点少的时候，绘制出来估计仅仅占据了100*100的范围。我是想，节点少的话，自动放大到充满整个canvas

**Comment by shangxinbo** [comment]
我也有这个需求，为什么关掉这个问题
