### ISSUE TITLE
3.x在Chrome右键“复制图片”，粘贴到“画图”中背景是黑色的，并且无法粘贴到word中

### ISSUE THREAD

**Issue by bi-kai** [ecomfe/echarts#3759]
#### 问题简述 (One-line summary)
3.x版本在Chrome右键“复制图片”，粘贴到Windows自带的“画图”中背景是黑色的，如何变成透明的或者白色的也行；
右键复制后，无法粘贴到word中，有什么办法能实现呢。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.x
+ 浏览器类型和版本 (Browser version):Chrome 51
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.图上右键“复制图片”。

#### 期望结果 (Expected behaviour)
粘贴到“画图”工具中背景是透明的或者白色的，跟导出的图片一样。
可以复制到“画图”工具中，也希望能复制到word中。

#### 其他信息 (Other comments)

公司内，无法上传截图。

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3742

**Comment by bi-kai** [comment]
@pissang 问题有相似处，但不一样，更具体，并且这个问题是必现的，应该想办法处理或者规避一下。

**Comment by bi-kai** [comment]
@pissang 两个issue都关了，这问题又没有解决啊

**Comment by pissang** [comment]
我这无法复现你的问题，而且我说的设置 `backgroundColor: 'white'` 你试了？试了什么效果？

**Comment by bi-kai** [comment]
@pissang backgroundColor: 'white'只能设置网页上的背景颜色，粘贴出来的，背景颜色还是黑的。
我试了其他工具canvas画的图，复制到画图工具或者ps中，背景颜色也是黑的，应该是canvas的公共问题了。

复现步骤：
1. Chrome上，echarts图上右键，复制图片；
2. 打开photoshop或者win的画图工具；
2. 粘贴进去，图是有的，但是原本应该透明的背景色，是黑的。

**Comment by pissang** [comment]
有可能是 win 下面 canvas 才有的问题，我在 mac 下没问题

那你试下像下面这样设置 canvas 的背景：
```js
myChart.getZr().configLayer(0, {
  clearColor: '#fff'
});
```

**Comment by bi-kai** [comment]
@pissang 太棒了，解决了我的问题，非常感谢。

**Comment by yakoye** [comment]
图片直接另存到本地，保存为png格式，

然后可以通过“文件”>“打开”来导入PNG文件，确保所有透明信息被正确读取。
