### ISSUE TITLE
旋风条形图 怎么能使左右轴对称，而不是交错呢

### ISSUE THREAD

**Issue by dearxiong** [ecomfe/echarts#3764]
#### 问题简述 (One-line summary)

旋风条形图 怎么能使左右轴对称，而不是交错呢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.function GetWeightBloodOption() {

    option = {
        tooltip: {
            trigger: 'axis',
            axisPointer: {            // 坐标轴指示器，坐标轴触发有效
                type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
            }
        },
        legend: {
            data: ['2014年血红蛋白', '2015年血红蛋白','2014年血浆','2015年血浆']
        },
        //        toolbox: {
        //            show: true,
        //            feature: {
        //                mark: { show: true },
        //                dataView: { show: true, readOnly: false },
        //                magicType: { show: true, type: ['line', 'bar'] },
        //                restore: { show: true },
        //                saveAsImage: { show: true }
        //            }
        //        },
        calculable: true,
        xAxis: [
        {
            type: 'value'
           

        }
    ],
        yAxis: [
        {
            name: '血浆        血红细胞',
            type: 'category',
            axisTick: { show: false },
            data: ['>15kg', '<=15&\n>10', '<=10\nkg']
        }
    ],
        series: [
        {
            name: '2014年血红蛋白',
            type: 'bar',
            data: [1.0, 0.8, 2.4]
        },
        {
            name: '2015年血红蛋白',
            type: 'bar',
            data: [1.0, 0.5, 2.3]
        },

        {
            name: '2014年血浆',
            type: 'bar',
            data: [-1.0, -0.8, -2.4]
        },
        {
            name: '2015年血浆',
            type: 'bar',
            data: [-1.0, -0.5, -2.0]
        }
    ]
    };
    return option;
}

2.

#### 期望结果 (Expected behaviour)
四个柱形左右两两对称

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
设置 [stack](http://echarts.baidu.com/option.html#series-bar.stack)
