### ISSUE TITLE
Cannot add captions/labels to multiple charts respectively

### ISSUE THREAD

**Issue by shujuwen2013** [ecomfe/echarts#3769]
#### 问题简述 (One-line summary)

When multiple radar charts (and other kinds of chart, like pie chart) are drawn in the same frame, a separated caption/label for each chart is usually needed to tell things apart.

For example, this is what we have:
<img src=http://imgur.com/6zbfNZw.png>

Expected:
<img src=http://imgur.com/upt7LXP.png>

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.1.10
+ 浏览器类型和版本 (Browser version): Chrome Version 51.0.2704.103 (64-bit)
+ 操作系统类型和版本 (OS Version): OS X Yosemite 10.10.5 

#### 可能哪里有问题 (What went wrong)
Suggestions
1. add `caption` object to `polar`, including properties like `caption text`, `show`, `formatter`, `position`, etc.
2. consider the same functionality for other kinds of chart, like funnel chart and etc.

#### ECharts配置项 (ECharts option)

```javascript
option = {
...
 polar : [
        {
            indicator : [
                {text : 'Bronx', max : 100},
                {text : 'Manhattan', max  : 100},
                {text : 'Brooklyn', max  : 100},
                {text : 'Staten Island', max  : 100},
                {text : 'Queens', max  : 100}
            ],
            center : ['20%','33%'],
            radius : '38%'
        },
        {
           indicator : [
                {text : 'Bronx', max : 100},
                {text : 'Manhattan', max  : 100},
                {text : 'Brooklyn', max  : 100},
                {text : 'Staten Island', max  : 100},
                {text : 'Queens', max  : 100}
            ],
            center : ['40%','33%'],
            radius : '38%'
        },
        ...
...
}

```

**Comment by pissang** [comment]
You can have multiple `title`. Like [this example](http://echarts.baidu.com/gallery/editor.html?c=line-easing)

**Comment by shujuwen2013** [comment]
But `grid` and multiple `title` are supported by Echarts 3 rather than Echarts 2 right?

**Comment by pissang** [comment]
I'm afraid there are no way to do it in ECharts 2 unless you use dom to show the captions

**Comment by shujuwen2013** [comment]
Got you, thank you @pissang
