### ISSUE TITLE
ECHARTS X轴能分组显示吗

### ISSUE THREAD

**Issue by xionglang921** [ecomfe/echarts#3771]
#### 问题简述 (One-line summary)
X轴上面能给分组的显示标题吗
 function  init4()
        {
        
         var myChart = echarts.init($("#Div4").get(0));
        
        option = {
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    toolbox: {

                show: true //是否显示工具栏             

            },
    legend: {
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['周一','周二','周三','周四','周五','周六','周日'],
             axisTick:{
                show:true,
                inside:true
            
            }
        }
       
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        
        {
            name:'直接访问',
            type:'bar',
            data:[320, 332, 301, 334, 390, 330, 320],
            itemStyle: {
                normal: {                   // 系列级个性化，横向渐变填充
                  borderRadius: 5,
                    
                    label : {
                        show : true,
                        textStyle : {
                            fontSize : '10',
                            fontFamily : '微软雅黑',
                            fontWeight : 'bold'
                        },
                         position: 'top'
                    }
                }       
                }    
            
        },
        {
            name:'邮件营销',
            type:'bar',
            stack: '广告',
            data:[120, 132, 101, 134, 90, 230, 210]
           
        },
        {
            name:'联盟广告',
            type:'bar',
            stack: '广告',
            data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
            name:'视频广告',
            type:'bar',
            stack: '广告',
            data:[150, 232, 201, 154, 190, 330, 410],
            itemStyle: {
                normal: {                   // 系列级个性化，横向渐变填充
                 
                    label : {
                        show : true,
                        textStyle : {
                            fontSize : '10',
                            fontFamily : '微软雅黑',
                            fontWeight : 'bold'
                        }
                    }
                }       
                }    
        },
        {
            name:'搜索引擎',
            type:'bar',
            data:[862, 1018, 964, 1026, 1679, 1600, 1570],
            markLine : {
                lineStyle: {
                    normal: {
                        type: 'dashed'
                    }
                },
                data : [
                    [{type : 'min'}, {type : 'max'}]
                ]
            }
        },
        {
            name:'百度',
            type:'bar',
            barWidth : 5,
            stack: '搜索引擎',
            data:[620, 732, 701, 734, 1090, 1130, 1120]
        },
        {
            name:'谷歌',
            type:'bar',
            stack: '搜索引擎',
            data:[120, 132, 101, 134, 290, 230, 220]
        },
        {
            name:'必应',
            type:'bar',
            stack: '搜索引擎',
            data:[60, 72, 71, 74, 190, 130, 110]
        },
        {
            name:'其他',
            type:'bar',
            stack: '搜索引擎',
            data:[62, 82, 91, 84, 109, 110, 120]
        }
    ]
};

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3770

**Comment by deleezhang** [comment]
同#3770
