### ISSUE TITLE
请问有日本、韩国的详细地图包吗？

### ISSUE THREAD

**Issue by huashengnp** [ecomfe/echarts#3772]
#### 问题简述 (One-line summary)
请问有日本、韩国的详细地图包吗？
我查看到该链接是美国的地图http://echarts.baidu.com/data/asset/geo/USA.json，不知有没有日本、韩国的？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/pissang/starbucks/blob/gh-pages/json/South_Korea.json
