### ISSUE TITLE
我想不固定宽度，想距离左右两边10%怎么弄，现在不写宽高就不显示

### ISSUE THREAD

**Issue by whpanda** [ecomfe/echarts#3775]
#### 问题简述 (One-line summary)
在css里面这样写
charts{height: 400px;width:500px;position:absolute;top: 20%;}
charts{height: 400px;position:absolute;top: 20%;left:10%,right:10%}不行啊

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
css 的问题去网上查相应的资料
