### ISSUE TITLE
柱状图 subtitle和y轴name重叠

### ISSUE THREAD

**Issue by yrpting** [ecomfe/echarts#3776]
#### 问题简述 (One-line summary)
柱状图设置title和subtitle及y轴的name属性后，y轴name和subtitle重叠，根据配置项手册没发现有属性可以设置，echarts2中没有这种情况，
echarts3中有属性可以设置吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): Echarts3.1.0
+ 浏览器类型和版本 (Browser version):firefox 47.0
+ 操作系统类型和版本 (OS Version): window7

#### 重现步骤 (Steps to reproduce)
1.设置柱状图title和subtitle
2.设置y轴name

#### 期望结果 (Expected behaviour)
subtitle和y轴name不重叠

#### 可能哪里有问题 (What went wrong)
渲染画布的时候没有设置subtitle和y轴的间距

#### ECharts配置项 (ECharts option)

```javascript
app.title = '堆叠柱状图';

option = {
    title: {
     	        text: '访问量分析',
     	        subtext: '主要维度：时间'
     	    },
    legend: {
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            name:"访问量",
            type : 'value'
        }
    ]
};


```

#### 其他信息 (Other comments)

![default](https://cloud.githubusercontent.com/assets/7277187/17356893/892315b6-598c-11e6-8a8a-07df07c87b8e.png)

**Comment by pissang** [comment]
[grid.top](http://echarts.baidu.com/option.html#grid.top)

**Comment by yrpting** [comment]
多谢 @pissang
