### ISSUE TITLE
echart3.x for angularJs2 有吗？大神们要能出一个就好了，

### ISSUE THREAD

**Issue by fssgh** [ecomfe/echarts#3777]
#### 问题简述 (One-line summary)
echart3.x for angularJs2 有吗？大神们要能出一个就好了！

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

发布 echart3.x for angularJs2 版本

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
欢迎贡献
