### ISSUE TITLE
2.2.7事件河流eventRiver.js:1 Uncaught Error: x0 is equal with x1!!!

### ISSUE THREAD

**Issue by acking** [ecomfe/echarts#3779]
#### 问题简述 (One-line summary)
事件河流eventRiver.js:1 Uncaught Error: x0 is equal with x1!!!

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7

时间到了秒，没有重复，报错

**Comment by 86XIng** [comment]
时间距离太短了
