### ISSUE TITLE
希望世界地图支持ISO3166国家码

### ISSUE THREAD

**Issue by CherishIt** [ecomfe/echarts#3784]
#### 问题简述 (One-line summary)
做world map，但是我拿到的数据只给了国家码而不是名称（如US，CN）。
网上找到一些ISO3166的country code转name的库，但是发现有些名字和echarts的名字不一样导致显示不了。
比如：
“United States”  <-> “United States of America”
“Russian Fereration” <-> “Russia”
“Viet Nam” <-> “Vietnam”
等等。

#### 期望结果 (Expected behaviour)
1. map的data可以直接使用国家码（毕竟比较标准化）；
2. 或者提供一个 从国家码转换成echarts使用的国家名字的工具或者文件

**Comment by pissang** [comment]
欢迎使用 http://echarts.baidu.com/spreadsheet.html 中的转换工具

**Comment by erjun** [comment]
@pissang 这个转换后的数据怎么使用呢？
