### ISSUE TITLE
地图自定义的问题

### ISSUE THREAD

**Issue by SilenceL0822** [ecomfe/echarts#3786]
#### 问题简述 (One-line summary)
你好，请问一下地图支持自定义吗？我现在的问题是有些地图的行政区域图中没有区分功能行政区，比如A区包含B区，现在的地图只显示A区，不显示B区，我们想在地图中将A、B区都显示出来，不知道现在提供这个服务吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以找个 geoJson 编辑器编辑后再导入 echarts

**Comment by SilenceL0822** [comment]
感谢大神的回复~~~请问楼上的大神，可不可以推荐一款geoJson 编辑器哇？在百度上都找不到相关的信息，好多都是编辑json的，不知大神说的geojson编辑器可否实现我在某一个地市的geojson地图数据中在画几条区域线，把原本大区中包含的小区区域线显示出来？
