### ISSUE TITLE
箱线图对比的问题

### ISSUE THREAD

**Issue by coskuntekin** [ecomfe/echarts#3789]
在demo里面展示了三种箱线图。第三种是对比箱线图。我认为这个非常有价值，可以对比同多个数据指标在多个时间段里面的数据分布情况。但相比第一种和第二种，对比箱线图缺少了异常值的展示（Outliers)。
可以异常值的展示加入到对比箱线图里面吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): Echarts3.0

![image](https://cloud.githubusercontent.com/assets/871345/17392532/936e6330-5a50-11e6-9692-3070db0a883f.png)

**Comment by pissang** [comment]
异常值需要自己用散点图加，参考 http://echarts.baidu.com/gallery/editor.html?c=boxplot-light-velocity 这个例子

**Comment by coskuntekin** [comment]
@pissang 你的意思是demo里面没有出现，是因为demo 里面的示例没有异常值？只要数据里面有异常值就会展示出来？还是要用你给出来的那个demo的代码啊？

**Comment by realeve** [comment]
echarts提供的dataTool中处理数据的部分输出了数据的分位点和异常值，分位点用来画箱线，异常值画散点，这些需要你自己来单独处理。
下面这样你可能看上去更直观
```
var data = echarts.dataTool.prepareBoxplotData([
    [850, 740, 900, 1070, 930, 850, 950, 980, 980, 880, 1000, 980, 930, 650, 760, 810, 1000, 1000, 960, 960],
    [960, 940, 960, 940, 880, 800, 850, 880, 900, 840, 830, 790, 810, 880, 880, 830, 800, 790, 760, 800],
    [880, 880, 880, 860, 720, 720, 620, 860, 970, 950, 880, 910, 850, 870, 840, 840, 850, 840, 840, 840],
    [890, 810, 810, 820, 800, 770, 760, 740, 750, 760, 910, 920, 890, 860, 880, 720, 840, 850, 850, 780],
    [890, 840, 780, 810, 760, 810, 790, 810, 820, 850, 870, 870, 810, 740, 810, 940, 950, 800, 810, 870]
]);

option = {
    title: [
        {
            text: 'Michelson-Morley Experiment',
            left: 'center',
        },
        {
            text: 'upper: Q3 + 1.5 * IRQ \nlower: Q1 - 1.5 * IRQ',
            borderColor: '#999',
            borderWidth: 1,
            textStyle: {
                fontSize: 14
            },
            left: '10%',
            top: '90%'
        }
    ],
    tooltip: {
        trigger: 'item',
        axisPointer: {
            type: 'shadow'
        }
    },
    grid: {
        left: '10%',
        right: '10%',
        bottom: '15%'
    },
    xAxis: {
        type: 'category',
        data: data.axisData,
        boundaryGap: true,
        nameGap: 30,
        splitArea: {
            show: false
        },
        axisLabel: {
            formatter: 'expr {value}'
        },
        splitLine: {
            show: false
        }
    },
    yAxis: {
        type: 'value',
        name: 'km/s minus 299,000',
        splitArea: {
            show: true
        }
    },
    legend:{
        data:['boxplot','outlier'],
        x:'left'
    },
    series: [
        {
            name: 'boxplot',
            type: 'boxplot',
            data: data.boxData,
            tooltip: {
                formatter: function (param) {
                    return [
                        'Experiment ' + param.name + ': ',
                        'upper: ' + param.data[4],
                        'Q3: ' + param.data[3],
                        'median: ' + param.data[2],
                        'Q1: ' + param.data[1],
                        'lower: ' + param.data[0]
                    ].join('<br/>')
                }
            }
        },
        {
            name: 'outlier',
            type: 'scatter',
            data: data.outliers
        }
    ]
};
```

**Comment by wu11106** [comment]
好時光酒店在七夕情人節：
恭祝Google支持團隊：有情人終成眷屬！闔家幸福！


2016年8月9日星期二，realeve <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DK1qqRYs2MKIeS92Cp51jJU7EZLjI5IK%252FmJM7MkCkye0%253D%26token%3DnjJuoWCvreemST6U2X0%252FGyZazVmnAVtfS8BT2fa5BKyNfBut%252FCNUAqju%252BiHxXLBN9PRP0ZJ2%252BSzHq7wXwN79jPmkk45G4uVNiQ0OUcG7lwZRsmr8zHDtpS2xRiN%252BpMRPu7ZMnDKL%252FkbjZUbf9v2I2Q%253D%253D&tc_serial=26370183291&tc_rand=942703725&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26370183291&tc_rand=942703725&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>


-- 
http://plus.google.com

**Comment by temberature** [comment]
#5509
