### ISSUE TITLE
横轴区间选择

### ISSUE THREAD

**Issue by liumanwei** [ecomfe/echarts#3791]
#### 问题简述 (One-line summary)
假如横轴表示的是日期，我可以选择一个起点，一个终点后，去和后端做一个交互吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以监听 dataZoom 的时间后请求数据再重新 setOption
