### ISSUE TITLE
折线图能否显示值为0的点？

### ISSUE THREAD

**Issue by zhangbing609** [ecomfe/echarts#3792]
如图，红色框内的数据为0与x轴重合，能否显示出来？
[http://ac-dwhkbfjm.clouddn.com/10053a65bb9262f1.png](http://ac-dwhkbfjm.clouddn.com/10053a65bb9262f1.png)

**Comment by pissang** [comment]
这个下个版本中修复，已提交修复的代码，谢谢反馈

**Comment by lppsucess** [comment]
现在是什么效果，能看下效果嘛
