### ISSUE TITLE
force图例中的line有类似于visualMap的组件来做个性化设置嘛；另外，节点和link可以实现类似于散点图和涟漪效果以及line的迁徙效果嘛

### ISSUE THREAD

**Issue by zouljisi** [ecomfe/echarts#3793]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
this.chart.echart.setOption({
                series:[{
                    data:newlinks,
                    links:newData
                }]
            });

```

**Comment by pissang** [comment]
不行

**Comment by wu11106** [comment]
国际劳工组织（维矶），我将会尽快去做，但系，个用户名同个密码？我之前未曾注册过储皇，为什么可以登基？谢谢哦！

2016年8月4日星期四，Yi Shen <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3D7NVTvXx5oa9SDnW5vKKQYqYv84U4ejdelL8DtrmjS1Y%253D%26token%3D4COHa7rYkpmd2f%252BGTGO9F8Ez55PyITBmnbX3hSNfLyIEnnUzxsOLPw8tDV4AZwj8wjOl9EcytamWQOKjbH4Z6Kw3QmX7JaPpc%252BbRFqPJJLOaTaDB86tsjuKXY2HTxQDYCFltvcd%252FeLg9SWy1qWH6iw%253D%253D&tc_serial=26319330299&tc_rand=1756881927&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26319330299&tc_rand=1756881927&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>


-- 
http://plus.google.com
