### ISSUE TITLE
Echarts 在设置了GRID 布局后 X 轴显示不完整2500 就只显示了2.5 后面的隐藏掉了

### ISSUE THREAD

**Issue by xionglang921** [ecomfe/echarts#3799]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.
 myChart = echarts.init($("#Div6").get(0));

        
        option = {
//    tooltip : {
//        trigger: 'axis',
//        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
//            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
//        }
//    },
    legend: {
        data:['机种A', '机种B','机种C','机种D','机种E']
    },
//    toolbox: {
//        show : true,
//        feature : {
//            mark : {show: true},
//            dataView : {show: true, readOnly: false},
//            magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
//            restore : {show: true},
//            saveAsImage : {show: true}
//        }
//    },
    calculable : false,
    grid: {
                    left: '0',
                    right: '0',
                    bottom: '200',
                    top: '15',
                    containLable: false
              },
    xAxis : [
        {
              type : 'value',
              axisLabel : {
                show:true,
               interval: 0  // {number}
             
                },           
                splitLine:{
                   show:false
                }
            
//            max:8000,
//            splitNumber:4
        }
    ],
    yAxis : [
        {
            type : 'category',
            data : ['周一','周二','周三','周四','周五','周六','周日'],
             splitLine:{
                   show:false
                }
        }
    ],
    series : [
        {
            name:'机种A',
            type:'bar',
            stack: '总量',
            itemStyle : { normal: {label : {show: true, position: 'insideRight'}}},
            data:[320, 302, 301, 334, 390, 330, 320]
        },
        {
            name:'机种B',
            type:'bar',
            stack: '总量',
            itemStyle : { normal: {label : {show: true, position: 'insideRight'}}},
            data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'机种C',
            type:'bar',
            stack: '总量',
            itemStyle : { normal: {label : {show: true, position: 'insideRight'}}},
            data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
            name:'机种D',
            type:'bar',
            stack: '总量',
            itemStyle : { normal: {label : {show: true, position: 'insideRight'}}},
            data:[150, 212, 201, 154, 190, 330, 410]
        },
        {
            name:'机种E',
            type:'bar',
            stack: '总量',
            itemStyle : { normal: {label : {show: true, position: 'insideRight'}}},
            data:[820, 832, 901, 934, 500, 700, 800]
        }
    ]
};

        myChart.setOption(option);

        myChart.resize();

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![234](https://cloud.githubusercontent.com/assets/20806349/17424372/d3b297b8-5af5-11e6-9bbb-a90d7fc8a8ee.jpg)

**Comment by xionglang921** [comment]
![234](https://cloud.githubusercontent.com/assets/20806349/17424421/5e173e18-5af6-11e6-996d-52be2b50d0ac.jpg)

**Comment by pissang** [comment]
设置 grid.right
