### ISSUE TITLE
关系图如何显示自身关系

### ISSUE THREAD

**Issue by wdanqiong** [ecomfe/echarts#3800]
#### 问题简述 (One-line summary)
关系图可以显示如A-B的关系，但是A自身的关系不能显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 期望结果 (Expected behaviour)
如果存在A-A的相互关系，在A结点处显示一个到自身的半圆形连线

**Comment by pissang** [comment]
暂时不行
