### ISSUE TITLE
雷达图逆时针旋转怎么改成顺时针的？

### ISSUE THREAD

**Issue by liuqz** [ecomfe/echarts#3802]
#### 问题简述 (One-line summary)
饼图是顺时针排列的，雷达图是逆时针排列的，怎么改成顺时针的？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7
+ 浏览器类型和版本 (Browser version): Chrome 50
+ 操作系统类型和版本 (OS Version): Win 10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by ivanberry** [comment]
文档里面有个参数可以直接更改呀！http://echarts.baidu.com/option.html#series-pie.clockwise

**Comment by liuqz** [comment]
请看清楚，**雷达图**，你找个饼图的设置给我能用么？3.0和2.2.7先分清楚再说好吧？

**Comment by vxhly** [comment]
大哥，请问解决了吗，具体是那个配置项，把数据改成逆时针的也是醉了，正常不都顺时针？
