### ISSUE TITLE
请问graph图中的series.data.symbol若指向一个图片，如何设置圆角？

### ISSUE THREAD

**Issue by guojindai** [ecomfe/echarts#3803]
#### 问题简述 (One-line summary)
请问graph图中的series.data.symbol若指向一个图片，如何设置圆角？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version): Chrome Version 51.0.2704.103 (64-bit)
+ 操作系统类型和版本 (OS Version):OS X EI Capitan 10.11.6 (15G31)

**Comment by pissang** [comment]
无法设置

**Comment by guojindai** [comment]
多谢！
