### ISSUE TITLE
城市地图不是最新的

### ISSUE THREAD

**Issue by xz0907zx** [ecomfe/echarts#3804]
#### 问题简述 (One-line summary)
1、江苏常州市：戚墅堰区已经被合并了，需要调整武进区、钟楼区、新北区、天宁区
2、安徽合肥：巢湖区已经被合并，需要调整合肥市

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.0
+ 浏览器类型和版本 (Browser version):IE8
+ 操作系统类型和版本 (OS Version):windows 7

#### 重现步骤 (Steps to reproduce)
1.加载安徽地图，不能出现巢湖市
2.加载常州地图，不能出现戚墅堰区

#### 期望结果 (Expected behaviour)
相关的json文件进行更新

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/download-map.html

**Comment by xz0907zx** [comment]
江苏省常州市明细区域地图没有进行更新

**Comment by wu11106** [comment]
無以為報以心相許！！！
想描述感激你們，不是丝貴網奉送那份厚禮，影射出背後我能獲取重大利益。
之前不時進入了你們關聯的網站，捐贈的計劃…，我底下頭離開，跟你們交往中，我提出的要求都是利益，你們給予我的免費又免費…，現在又給予我的……。
我與谷歌一來一往之間，露出我是一個利益之徒。去年之前，我是一個當地慈善活動的帶頭領隊，在困難加重中，才停止一切公益活動。
記得，盲人學校校長通過翻譯告訴我，為我的活動準備了一個好聽名字，我要求用[中國人]。她們沒有去問原因，我主動解釋：中國人在外面名聲不好，讓大家知道[中國人]也分類別，用實際看人。
每每去一次救助中心，就暗下決心賺多點錢，救助活動需要現金，而不是眼淚。
喜歡谷歌網絡，喜迎自己去一面學習一面創建谷歌給予的成人網，希望是網絡的追逐，如果立足不下緬甸，只能回國。猛然發現！希望在酒店基礎上生存，
看到員工的責任感，對企業的誠信，我繼續下去，才是對好員工的最好敬禮！
至於收回投資？為求不死而是謝天謝地了！為求收支平衡。但今年，看似朝陽實際是焦急。
正是如此！才起到不應該的渴求，得到貴網的協助。
您們的一次一次出手相助，………怎樣寫才表達？
除了緊張事情，下決心！盡快學會和掌握地圖的概念使用，先不去考慮廣告，用實際行動來表示自己珍惜這份厚禮，用行動來回報，除外，還能回報什麼？
前二個月，一個熟客和屬下聊天中發現……，見我就一手拉著我說：輝哥！該您發財的，原來您是默默無聞地做慈善，天真有眼光，讓您在緬甸賺錢！
我一下茫然，熟客好像取笑我？又不是，熟客的話是普世真理：好人有好報！
呵呵！倒閉我不會怨天怨地！走回原來的自己，社會最底層民眾。
天！！冥冥中自有安排，在困難的時候，在看不到光明的隧道里，不斷地換取方式幫助。
「有限公司」不管結局如何？不變的結局：谷歌+我心中的網神！

吳英輝，中國.北京
（公開、私聊發表決定，由您們自定義）

2016年8月16日星期二，xz0907zx <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DV3xVBIDT3lmv63v2ADv79kMj5sp%252FwT6o9wz8m0WFb0I%253D%26token%3Da5DtRC8ZKWBiTSxrEsClcyY9YADzbgKy8GPVfZ0r31%252FpOr9%252Fm0gUpZx1tEEcQ4TtZ66e3Sa83F%252FAttWedWa4VzGw11njKB2qLBTQU4QIsgEIsamXoqxqXI21Gw%252BfwqAN7dVovmcCoGwJXyp0N49Zww%253D%253D&tc_serial=26445444554&tc_rand=1511827769&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26445444554&tc_rand=1511827769&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>
