### ISSUE TITLE
eCharts 3.x 添加线、点addMarkLine、addMarkPoint都移除了吗？

### ISSUE THREAD

**Issue by wn0112** [ecomfe/echarts#3807]
#### 问题简述 (One-line summary)
eCharts 3.x 添加线、点addMarkLine、addMarkPoint都移除了吗？我看eCharts 2.x里面有的，现在3.x用不了了。辅助线工具3.x 也无法显示。

我想通过鼠标点击，来画一条线，eCharts3.x 现在能做到吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.x
+ 浏览器类型和版本 (Browser version): Chrome
+ 操作系统类型和版本 (OS Version): Windows 7 x64

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
3 里修改数据只有一个统一的 setOption 入口
