### ISSUE TITLE
折线图Y轴刻度不正确

### ISSUE THREAD

**Issue by peiyc** [ecomfe/echarts#3808]
#### 问题简述 (One-line summary)
最近在用Echarts做折线图，发现个问题，单组数据时显示是正常的，但是当我在一个坐标系内画多条折线的时候就出现问题了。
1。Y轴刻度会把两组数据的值相加到一起，而不是取两组数据中最大值去决定Y轴的最大刻度
2。当有两组数据时两条折线的起始点是重合的，这个没问题，但是其他点会出现问题，本来相差不多 的两个点在图上变现会差很多，几乎两倍。给我的感觉好像是一个点的Y轴原点在另一个Y轴刻度的终点。而相差很多的数据两条线会基本重合到一起一个是900左右，另一组数据的点是50左右，两条线几乎重合
3。官网的demo也有这个问题（折线图第三个）

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):   2.0
+ 浏览器类型和版本 (Browser version):  chrome最新版本
+ 操作系统类型和版本 (OS Version): windows10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 可能哪里有问题 (What went wrong)
Y轴刻度计算的时候可能没取多组数据中的最大值  而是在每种数据中取了一个最大值加到了一起

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![v _as8 e j6v9 b69 yf](https://cloud.githubusercontent.com/assets/15152562/17470359/2bf38d36-5d6e-11e6-9628-338432bbb705.png)
![iw m17dg m9of8 z5 e7](https://cloud.githubusercontent.com/assets/15152562/17470370/4baf0d3a-5d6e-11e6-9e06-78ba1a9dfaea.png)
![x pug1opxdsa5vu3ae 3jq](https://cloud.githubusercontent.com/assets/15152562/17470382/63fb9930-5d6e-11e6-8778-0661279f00ea.png)
![graq7 jtcd q vuxj654saf](https://cloud.githubusercontent.com/assets/15152562/17470400/889d065c-5d6e-11e6-8dd8-51bade012f7b.png)

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/3509

**Comment by phpuser2017** [comment]
参考链接http://gallery.echartsjs.com/editor.html?c=xHkImGABwg
可解决此问题

**Comment by Crow75** [comment]
我也遇到了同样的问题，检查代码后发现是设置了series下stack参数,默认是null. 数据堆叠，series[i]-line.stack string
[ default: null ]同个类目轴上系列配置相同的stack值后，后一个系列的值会在前一个系列的值上相加。
参考链接：https://www.echartsjs.com/zh/option.html#series-line.stack
