### ISSUE TITLE
使用两个x轴时，柱形图只是显示一个数值较大的柱形

### ISSUE THREAD

**Issue by dearxiong** [ecomfe/echarts#3809]
#### 问题简述 (One-line summary)
利用两个x轴实现层叠，只能显示一个柱形的数据。不能实现鼠标移动数据变换。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1. option = {
        title: {
            text: '两种手术关联',
            subtext: '纯属虚构'
           
        },
        tooltip: {
            
            trigger: 'axis'
           
        },
        legend: {
            data: ['心脏病','糖尿病']
        },
        
        calculable: true,
        xAxis: [
        {
            type: 'category',
            data: ['2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
        },
         {
             type: 'category',
          
             data: ['2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
         },

    ],
        yAxis: [
        {
            type: 'value'
           
        }
    ],
        series: [
        {
            name: '心脏病',
            type: 'bar',
            itemStyle: {
                normal: {
                    color: 'tomato',
                    barBorderColor: 'tomato',
                    label: { show: true ,position:'top'}

                }
            },
            data: [1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300]
        },
        {
            name: '糖尿病',
            type: 'bar',
            xAxisIndex: 1,
            itemStyle: {
                normal: {
                    color: '#4DFFFF',
                    barBorderColor: 'tomato',
                    barBorderWidth: 6,
                    barBorderRadius: 0,
                    label: { show: true, position: 'top' }
                    }
                },
         
            data: [650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150]
        }
        
    ]
    };
                    
2.

#### 可能哪里有问题 (What went wrong)
tooltip显示问题

#### ECharts配置项 (ECharts option)

```javascript
 option = {
        title: {
            text: '两种手术关联',
            subtext: '纯属虚构'
           
        },
        tooltip: {
            
            trigger: 'axis'
           
        },
        legend: {
            data: ['心脏病','糖尿病']
        },
        
        calculable: true,
        xAxis: [
        {
            type: 'category',
            data: ['2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
        },
         {
             type: 'category',
          
             data: ['2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
         },

    ],
        yAxis: [
        {
            type: 'value'
           
        }
    ],
        series: [
        {
            name: '心脏病',
            type: 'bar',
            itemStyle: {
                normal: {
                    color: 'tomato',
                    barBorderColor: 'tomato',
                    label: { show: true ,position:'top'}

                }
            },
            data: [1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300]
        },
        {
            name: '糖尿病',
            type: 'bar',
            xAxisIndex: 1,
            itemStyle: {
                normal: {
                    color: '#4DFFFF',
                    barBorderColor: 'tomato',
                    barBorderWidth: 6,
                    barBorderRadius: 0,
                    label: { show: true, position: 'top' }
                    }
                },
         
            data: [650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150]
        }
        
    ]
    };
                    

```

**Comment by pissang** [comment]
因为被覆盖了吧

**Comment by dearxiong** [comment]
可是我就是想做成一样的宽度，，，因为想让数据看起来是包含关系
