### ISSUE TITLE
大量series的速度优化

### ISSUE THREAD

**Issue by orisnas** [ecomfe/echarts#3815]
#### 问题简述 (One-line summary)
echarts对于大数据的散点图可以优化，但是对于因series过多导致的缓慢不知道有没有方法优化？
现在我需要在一个图中绘制700多个样本的散点图，每个样本3000个点，设置每个series的large为true没有效果，打开还是很慢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):v3.0
+ 浏览器类型和版本 (Browser version):Chrome 52
+ 操作系统类型和版本 (OS Version):windows 10

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/17471583/17511241/a23cd10a-5e54-11e6-8620-3b7a38304de2.png)

**Comment by pissang** [comment]
暂时没有，不建议显示这么多系列

**Comment by wu11106** [comment]
好時光酒店在七夕情人節：
恭祝Google支持團隊：有情人終成眷屬！闔家幸福！


2016年8月9日星期二，Yi Shen <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DV9SdEgvcfxPuC%252BaqADhwtcFAF423u%252FQsqQjimm8E4Dw%253D%26token%3DBoGkxpeL3w4DU21nEMR7Fw7pbZCmanNl8zkhGjD9Z7l4iIFjxD2E4jpw1nBI0A7Fy0eh%252F%252BqLSgfczZ1AYCYDodvLjUkQcbvBn2nwIX4bXTv3fl%252BDJEik%252F9Jm4f03i7xWmIxspImQnS7cYf0DsUPFDw%253D%253D&tc_serial=26372691496&tc_rand=1767358213&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26372691496&tc_rand=1767358213&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>


-- 
http://plus.google.com

**Comment by zhang122622623** [comment]
@pissang   我的图里有7个Series,,每个里面有720个点，在chrome中完全加载出来要差不多3、4秒，初始化时候更慢，这还是把动画关掉的结果，我测试setOption的过程大概都在2.3秒左右，而且有时间会卡住，浏览器会崩溃，我想问这应该怎么优化呢？
