### ISSUE TITLE
轴类型为time时，boundaryGap不起作用

### ISSUE THREAD

**Issue by DebugFuture** [ecomfe/echarts#3817]
#### 问题简述

轴类型为time时，boundaryGap不起作用
#### 版本及环境
- ECharts 版本 (ECharts version): 官网DEMO（http://echarts.baidu.com/demo.html#dynamic-data2）
- 浏览器类型和版本 (Browser version): Chrome
- 操作系统类型和版本 (OS Version): Mac OS
#### 重现步骤 (Steps to reproduce)
1. 打开官网，在time轴中添加 boundaryGap: ['20%', '20%']
#### 期望结果 (Expected behaviour)

折线起止位置距离坐标轴有间隙
#### 可能哪里有问题 (What went wrong)

折线起止位置距离坐标轴没有间隙

**Comment by bengle** [comment]
我也碰到这个问题，折线图还好，但是柱状图问题就比较明显

**Comment by littlekkk** [comment]
碰到了同样的问题

**Comment by DebugFuture** [comment]
@pissang 有没有临时解决方案？Echarts2时间轴类型boundaryGap是起作用的。

**Comment by akansal1** [comment]
any update ?

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/4532#issuecomment-267804213
