### ISSUE TITLE
Uncaught TypeError: data.map is not a function

### ISSUE THREAD

**Issue by lucifer1024** [ecomfe/echarts#3821]
#### 问题简述：
$.get('data/lines-bus.json', function(data) {
		var hStep = 300 / (data.length - 1);
		var busLines = [].concat.apply([], data.map(function(busLine,idx) {}
浏览器抛出异常： Uncaught TypeError: data.map is not a function

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version):  Chrome 52.0.2743.82 m (64-bit)
+ 操作系统类型和版本 (OS Version):  Win7 64bit
 

#### 重现步骤 (Steps to reproduce)
1.参照 https://github.com/ecomfe/echarts/blob/master/test/lines-bus.html 实现

#### 期望结果 (Expected behaviour)
实例中的 北京公交路线 - 百度地图 http://echarts.baidu.com/demo.html#lines-bmap-bus

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
改成 $.getJSON

**Comment by lucifer1024** [comment]
可以了，多谢！

**Comment by jk245967661** [comment]
用$.getJSON，报错了：Cannot read property 'dataToPoint' of null
