### ISSUE TITLE
页面图表数量上限问题

### ISSUE THREAD

**Issue by Miss1White** [ecomfe/echarts#3826]
#### 在一个页面内echarts 绘制图表数量有限制么？

因为项目需求，可能会在一个页面内绘制上百张图表，不知echarts能否支持。

Hope to receive your reply soon,
Thanks!

**Comment by pissang** [comment]
没有限制，PC 上没什么问题，mobile 上小内存的手机可能会因为内存不够导致页面崩溃

**Comment by Miss1White** [comment]
好的，谢谢，有问题我们会和您反馈。
