### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by goldenbull** [ecomfe/echarts#3831]
AngularJS 2已经基于typescript开发了，可见typescript还是很受欢迎的，希望echarts能提供官方的`echarts.d.ts`文件支持。

**Comment by pissang** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/echarts/echarts.d.ts 有简版的，更详细的 Option 的形状描述很好依赖 tagged union 特性，而 typescript 1.x 并不支持，所以有何没有其实效果差不多

**Comment by goldenbull** [comment]
👍

**Comment by c429013730** [comment]
大神AngularJS 2如何使用echarts

**Comment by Jack-Works** [comment]
@pissang Typescript 2.0 开始已经有了 tagged union，请问有没有什么打算，那个在 DefinitelyTyped 上的描述文件效果太差了
