### ISSUE TITLE
ECHART 能自定义标注吗

### ISSUE THREAD

**Issue by xionglang921** [ecomfe/echarts#3839]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
能

**Comment by xionglang921** [comment]
有例子可以参考吗 就好像你们显示的那个最大最小值得标注  我现在需要每个柱子都显示这个标注
