### ISSUE TITLE
官网平行坐标的tooltip属性不好使

### ISSUE THREAD

**Issue by onlyajy521** [ecomfe/echarts#3840]
#### 问题简述 (One-line summary)
平行坐标的tooltip属性不好使
官网例子就不好用  ie 火狐 谷歌都试用过
三十多条线一起放在那都不知道什么意思 球修改

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
官网例子
+ 浏览器类型和版本 (Browser version):
ie 11 谷歌版本 52.0.2743.82 m   火狐
+ 操作系统类型和版本 (OS Version):
win 8.1

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

功能实现就行

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
平行坐标暂时不支持 tooltip

**Comment by es3154** [comment]
搞半天不支持啊，官方demo上都放了tooltip相关的设置，以为支持呢
