### ISSUE TITLE
echart3  标题显示咨询&建议

### ISSUE THREAD

**Issue by publisherfk** [ecomfe/echarts#3845]
#### 问题简述 (One-line summary)

1.echarts3已经支持存在任意多个标题组件，但是标题好像不支持纵向显示，
2.如果标题能纵向显示，就能将tittle作为坐标轴的名称，居中显示，尽管目前坐标轴支持name，但是显示位置约束在start和end,
3.后面的版本中，title能否支持纵向显示，类似于提供一个orient属性，可选为'horizontal'、'vertical'？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
纵向显示可以考虑。
<http://echarts.baidu.com/option.html#xAxis.nameLocation>
坐标轴名称能支持 `middle`。

**Comment by publisherfk** [comment]
但是文字是横向排列，这样在y轴上面就比较难看了
