### ISSUE TITLE
地图怎么实现各省各系列值的展示

### ISSUE THREAD

**Issue by zhouboluo** [ecomfe/echarts#3848]
#### 问题简述 (One-line summary)
现在地图计算的是统计值，如果我想实现tooltip显示如：
北京 
iphone：销售值
小米：销售值 
华为：销售值
这样的数据，data和tooltip应该怎么修改？
另外地图现在单独加上 {name:'广东', value:'阴'}是无法显示的，data要怎么拼才能显示如：
北京
天气：阴
温度：25
这样的数据

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
可以显示
北京 
iphone：销售值
小米：销售值 
华为：销售值
这样的数据
以及
北京
天气：阴
温度：25
这样的数据

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以自定义 tooltip.formatter 通过 dataIndex 或者 name 分别索引和组装数据
