### ISSUE TITLE
普通的柱状图运用了值域，系列颜色并没有随之变化

### ISSUE THREAD

**Issue by Shlpeng** [ecomfe/echarts#3850]
问题简述 (One-line summary)

想问下普通的柱状图运用了值域，柱状图的系列颜色能不能随值域的颜色而变？

版本及环境 (Version & Environment)

ECharts 版本 (ECharts version): 2.2.7
浏览器类型和版本 (Browser version): firefox
操作系统类型和版本 (OS Version): win8
重现步骤 (Steps to reproduce)

期望结果 (Expected behaviour)
普通的柱状图运用了值域，柱状图的系列颜色能随值域的颜色而变，提供下option的写法

可能哪里有问题 (What went wrong)

ECharts配置项 (ECharts option)

**Comment by pissang** [comment]
请用 ECharts 3
