### ISSUE TITLE
引入 ECharts问题，报错Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by xushuo** [ecomfe/echarts#3851]
根据官网上说，通过 npm 上安装的 ECharts 和 zrender 会放在node_modules目录下。可以直接在项目代码中 require('echarts') 得到 ECharts。

在编码过程中，
var echarts = require('echarts');  require报错。
Uncaught ReferenceError: require is not defined

战友们。这是什么问题？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.2
+ 浏览器类型和版本 (Browser version): chrome 49
+ 操作系统类型和版本 (OS Version):win7

**Comment by xushuo** [comment]
额，代码的话就是 通过NPM安装echarts，之后再页面只写了一句var echarts = require('echarts'); 
没有任何其他的引用或者代码了。。

**Comment by pissang** [comment]
npm 安装引入需要配合 webpack 等打包工具，http://echarts.baidu.com/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts

**Comment by theonels** [comment]
解决了吗？？求解决方法……一模一样的遭遇。。

**Comment by LW728** [comment]
新手，遇到跟你一样的问题，求解，谢谢~

**Comment by pyjack** [comment]
@LW728 @theonels 解决了吗？

**Comment by pyjack** [comment]
@pissang 请问必须用 webpack 吗？我用的 gulp 。
