### ISSUE TITLE
ECharts 3 官网 builder 页面不能下载

### ISSUE THREAD

**Issue by ifelsee** [ecomfe/echarts#3852]
#### 问题简述 (One-line summary)
[ECharts 3 官网 builder 页面](http://echarts.baidu.com/builder.html)控制台报错

>Uncaught ReferenceError: ecLog is not defined     
```
//builder.html  line:78
    ecLog({
        'page': 'builder',
        'version': '3.2.2',
        'build-parameters-3': log
    });
```
不能正常下载

**Comment by baichi** [comment]
我也是，而且实例页面 下载页面的图都看不了，需要刷新才行

**Comment by pissang** [comment]
这个应该是因为adblock的原因

**Comment by baichi** [comment]
这个插件是禁用的，估计是别的引起的，隐身模式确实没问题
