### ISSUE TITLE
echart3  API参数改进

### ISSUE THREAD

**Issue by publisherfk** [ecomfe/echarts#3854]
#### 问题简述 (One-line summary)
关于Echarts3的鼠标事件问题：
如果需要使用使用鼠标事件，就必须开始相关事件，然后我看到http://echarts.baidu.com/option.html#series-line.silent  这里面说：图形是否响应和触发鼠标事件，给我的感觉就是silent 设置为true，就是开启事件，设置为false就是关闭事件，实际上的效果正好相反。鉴于此，这块的api最后会修改吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
我修改下文档
