### ISSUE TITLE
想要实现点击图例，该图例不置灰，该类型不消失。但是不是要把selectedMode改成false

### ISSUE THREAD

**Issue by carly1987** [ecomfe/echarts#3855]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行
