### ISSUE TITLE
Error: t.coordinateSystem.getOtherAxis is not a function

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#3856]
Version: 3.2.3

I'm getting this error in one of existing charts:

![image](https://cloud.githubusercontent.com/assets/561365/17729180/41ca1a20-6463-11e6-8d71-1a7400995e6c.png)

![image](https://cloud.githubusercontent.com/assets/561365/17729166/2bbd7434-6463-11e6-88f2-02523a241db8.png)

It was ok in 3.2.2

It's a combination of map and line charts: 

![image](https://cloud.githubusercontent.com/assets/561365/17729538/fa0af14e-6464-11e6-9a32-d2afd0256751.png)

Source code [attached](https://github.com/ecomfe/echarts/files/422060/echarts-3.2.3-error.zip). 

Should I try to isolate this issue and provide a simpler example?

**Comment by jarben** [comment]
Wow, that was quick - thanks heaps @pissang!

**Comment by pissang** [comment]
It is a stupid bug 😜 Thanks for the quick feedback

**Comment by jarben** [comment]
Any idea when the release is going out? Thanks!
