### ISSUE TITLE
一个曲线图中多条曲线的时候有个bug

### ISSUE THREAD

**Issue by raffeale** [ecomfe/echarts#3868]
#### 问题简述 (One-line summary)
当一个曲线图中有多条曲线的时候，其中一条曲线的长度要短与其他的曲线的时候，x轴tooltip显示的x对应的数值不正确，tooltip中一直以最短的那条曲线的最后的那个点作为tooltip对应x轴的值。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.添加多条曲线，其中一条曲线的数据要少于其他的曲线长度，并且小于x轴的长度。
2.把鼠标放到最短那条曲线的的点上，看tooltip的x轴的值，在一道最短曲线最后面一个点后一个x轴点上看tooltipx轴的值，tooltip x轴对应tooltip还是最短曲线的最后一个点的tooltip

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
更新到最新版本
