### ISSUE TITLE
noDataLoadingOption not working in echarts 3.*

### ISSUE THREAD

**Issue by HedCET** [ecomfe/echarts#3869]
var i_pie = echarts.init(DOM element),
        opt = {
          noDataLoadingOption: {
            text: "Insufficient data to show the analysis",
            effect: "bubble",
          },
          series: [{
            data: [],
            name: "Year",
            radius: [0, 150],
            selectedMode: false,
            type: 'pie',
          }],
          title: {
            show: false,
          },
        };

  i_pie.setOption(opt);

noDataLoadingOption not working for me, pls help me to solve this

is there any doc available for noDataLoadingOption ?

**Comment by pissang** [comment]
noDataLoadingOption has been removed in ECharts 3
