### ISSUE TITLE
桑基图：修改透明度导致文字显示不理想

### ISSUE THREAD

**Issue by tomwang-wc** [ecomfe/echarts#3870]
#### 问题简述 (One-line summary)

sankey的itemStyle.normal.opacity控制结点矩形包括结点文字的透明度，默认为1，即完全不透明。
lineStyle.normal.opacity控制结点之间连线的透明度，默认0.2，通常这时文字显示像网站示例一样不会明显受影响。
**但时，当不断提高lineStyle.normal.opacity时，结点文字被遮盖的效果越明显。**

![screenshot-echarts baidu com 2016-08-17 19-22-07](https://cloud.githubusercontent.com/assets/20624187/17761409/805ed9ca-6539-11e6-8774-947ed5abe50c.png)

当opacity提高为1时，与edge重叠的文字被完全覆盖。

![screenshot-echarts baidu com 2016-08-17 19-23-14](https://cloud.githubusercontent.com/assets/20624187/17761421/98125cfe-6539-11e6-9f01-00354a911013.png)

如果修改itemStyle.normal.opacity，同时也会改变文字的透明度，这应该算是feature不是bug，但往往不是我想要的：修改透明度是为了获得更好的显示效果，但文字传递信息的效果也受到了折损。

![screenshot-echarts baidu com 2016-08-18 12-12-40](https://cloud.githubusercontent.com/assets/20624187/17761816/26c21efa-653d-11e6-80e1-79f58567cf75.png)
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): http://echarts.baidu.com/demo.html
- 浏览器类型和版本 (Browser version): firefox 47
- 操作系统类型和版本 (OS Version): linux; fedora 24
#### 重现步骤 (Steps to reproduce)

1.http://echarts.baidu.com/demo.html#sankey-energy
2.配置itemStyle.normal.opacity或lineStyle.normal.opacity的值
#### 期望结果 (Expected behaviour)

1.文字浮于图像之上
2.itemStyle.normal.opacity不改变文字的透明度，文字透明度有独立配置项
#### ECharts配置项 (ECharts option)

``` javascript
myChart.showLoading();
$.get('data/asset/data/energy.json', function (data) {
    myChart.hideLoading();

    myChart.setOption(option = {
        title: {
            text: 'Sankey Diagram'
        },
        tooltip: {
            trigger: 'item',
            triggerOn: 'mousemove'
        },
        series: [
            {
                type: 'sankey',
                layout: 'none',
                data: data.nodes,
                links: data.links,
                itemStyle: {
                    normal: {
                        borderWidth: 1,
                        borderColor: '#aaa'
                    }
                },
                lineStyle: {
                    normal: {
                        color: 'source',
                        curveness: 0.5,
                        opacity:1
                    }
                }
            }
        ]
    });
});
```

**Comment by wu11106** [comment]
谷歌支持团队；您们好！

在缅甸仰光国际机场，一号与二号航站楼的谷歌地图定位上，我能否对机场描述？
机场是缅甸的重要港口，书写有误的话，有损缅甸和谷歌声誉。那怕我对仰光机场资料来自权威的，书写英文流畅的无误，都不代表我有这个权限，请指示我能否描述？
第二个问题，还是仰光国际机场二个航站楼，谷歌“我的商家”里，己经显示Google+信息页接连航站台的地图，我想把相联航站楼的Google+信息页编辑旅游版的Google+信息页，每一信息页一个主要旅游景点。但是，我可用谷歌来做第一人称呼吗？比如在地图旅游介绍上：“Google
maps meets you in
Yangon”，我心里感觉Google+与我距离就如是0般，书写上是美好的赞颂向往。但是，我知道这是商业性的公开，有疑借别人之名抬举自己，请指示！

YINGHUI WU
wu11106025@gmail.com

2016年8月18日星期四，wangchao95 <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DjXbYyjpuLPC7FMGeN0pjWcqKxppgXo86vWhen1%252FKSzY%253D%26token%3DlZypyv6%252Bc%252Bd0sQIks0CO%252FUXFAsUNxS0LYLw4O8ncdRit2rIN7nsdGDXUvbeBRBb3%252FpJX76ZTyiUiWyc3BYlJgzL1AJmlaUDjV2f39M4jhCmw2BsPff884vHWY6w1bYbzsaF485YUqJlx0BnXkWP8%252Fg%253D%253D&tc_serial=26471455863&tc_rand=147237907&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26471455863&tc_rand=147237907&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>

**Comment by wu11106** [comment]
㊞㊞把信任收藏！

通过对邮件的扫描，这是用扫描出来的自信制作的图片。
图片专门用于谷歌“我的商家”的仰光国际机场航站楼信息页主图，除此以外，不会再用别处。
图片永久收藏留念，不管日后与谷歌关系去到哪里，图片代表的是，谷歌在虚幻世界里给我的一份信任，我示意奇迹般的，一种无价之宝的珍藏。
毫无准备下接收了航站楼“拥有者”身份，至今没有考虑过点滴的广告问题，至于广告怎样设计、广告位置在哪里、广告受众的问题，全部空白？我只一心想………
地图GPS定位是网络上喜爱之一。一份不辜负您们的支持和喜欢的工作，构思如何做得更加出位。我很明白，越是这样越会出现乐极生悲，站在谷歌立场思考，用词上自然流露出的意思，很容易怀疑：借谷歌之名谋取自己的利益，这种只知道追求利益的人会有损谷歌的声誉。
成功的企业一定有超群的哲学思想，您们相信了我！您们的胸怀装入全球的五大洲。
您们知道，对谷歌品牌的爱护并非只是谷歌团队内部独有，用户中也有……。
何为爱护谷歌的反应？在地图上的位置描述、景点描述、历史遗迹描述上，爱护谷歌的思考来书写，必须不能虚假，还有词汇用法？缅北（金三角）十多个华人领导的武装贩毒问题怎样描述？。比如维基百科里注释缅甸英殖民时期为【英属缅甸】，词语非常之正确，当时英殖民统治者把缅甸列入印度一个省，缅甸实为亡国近百年，在人们的心中是痛苦的，如果用【英属缅甸】就如揭开了痛苦的记忆。
我认为谷歌地图上描述，不能用有伤缅甸人民感情的词汇，我们带着--谷歌地图复盖缅甸大地上，免费受益缅甸人民，谷歌在亲吻着这遍热土。
心得论述！

YINGHUI WU
sogood@goodtimehotel.com

2016年8月18日星期四，wangchao95 <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DjXbYyjpuLPC7FMGeN0pjWcqKxppgXo86vWhen1%252FKSzY%253D%26token%3DlZypyv6%252Bc%252Bd0sQIks0CO%252FUXFAsUNxS0LYLw4O8ncdRit2rIN7nsdGDXUvbeBRBb3%252FpJX76ZTyiUiWyc3BYlJgzL1AJmlaUDjV2f39M4jhCmw2BsPff884vHWY6w1bYbzsaF485YUqJlx0BnXkWP8%252Fg%253D%253D&tc_serial=26471455863&tc_rand=147237907&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26471455863&tc_rand=147237907&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>

**Comment by jhr621** [comment]
楼主，请问你上面的图，link的颜色送source到target的渐变是怎么实现的呀
