### ISSUE TITLE
目前能否支持副图功能？

### ISSUE THREAD

**Issue by twoeo** [ecomfe/echarts#3873]
想要实现副图功能，如：

**纵向副图**
如多个折线图纵向排列，公用一个最底部的X轴。

**横向副图**
如度个折线图横向排列，公用一个最左或最右的Y轴。

其实类似这样的：
http://echarts.baidu.com/demo.html#scatter-single-axis

但是想让所有的图公用一个X轴 （或者让无关的X轴隐藏）

没有找到好的办法

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/gallery/editor.html?c=scatter-matrix 这个有散点矩阵的示例
