### ISSUE TITLE
dataZoom竖直方向滚动条里的滚轴默认在下面，应该默认在上面

### ISSUE THREAD

**Issue by cag2050** [ecomfe/echarts#3875]
这个例子，http://echarts.baidu.com/demo.html#bar-negative2
我加了代码：
dataZoom: [
                {
                    type:'slider',
                    show: true,
                    startValue: 0,
                    endValue: 5,
                    orient: 'vertical',
                    showDetail: false,
                    showDataShadow: false,
                    zoomLock: true,
                    backgroundColor: '#EDF0F7',
                    fillerColor: '#25a4fb',
                    handleSize: '0',
                    x2: 20,
                    width: 9
                }
            ],
dataZoom竖直方向滚动条里的滚轴默认在下面，我觉得应该默认在上面，才对。
在这个网址也提了这个问题，上面有图示：http://www.oschina.net/question/2888940_2192237

**Comment by pissang** [comment]
因为 y 轴默认就是从下往上的，你要从上往下的话设置 `inverse: true`
