### ISSUE TITLE
需求：定时给客户发送带echarts图片的邮件，怎么在后台生成这个图片？ 

### ISSUE THREAD

**Issue by ma929226676** [ecomfe/echarts#3879]
需求：定时给客户发送带echarts图片的邮件，怎么在后台生成这个图片？

**Comment by lzc-alioo** [comment]
这是非常好的一个问题，我百度了一下，很多人都面临了这个问题，求解决。

**Comment by mqliutie** [comment]
同问 有啥技巧么

**Comment by chfw** [comment]
https://github.com/ecomfe/echarts/issues/6939

**Comment by lzc-alioo** [comment]
这个后来我换技术组件了，改用jfreechart了


=========================
柳志崇

**Comment by alanhg** [comment]
jfreechart很丑,不如用highcharts+PhantomJS。

关于highcharts的服务端图表生成，看这里
https://www.highcharts.com/component/content/article/2-news/52-serverside-generated-charts

**Comment by endypark** [comment]
> 
> 
> jfreechart很丑,不如用highcharts+PhantomJS。
> 
> 关于highcharts的服务端图表生成，看这里
> https://www.highcharts.com/component/content/article/2-news/52-serverside-generated-charts

highcharts是商业的，不能用。（开源版，不得用于商业目的）
