### ISSUE TITLE
设置yAxis axisLabel的font-size后containLabel: true失效, 文字被切

### ISSUE THREAD

**Issue by suinia** [ecomfe/echarts#3880]
#### 问题简述 (One-line summary)
设置Y坐标的刻度文字大小后，就算containLabel:设置为true, 计算宽度不够 文字会被且

#### 我的解决办法是：通过数据大小设置right值，其实也有问题。

grid: {
	        		left: 0,
	        		top: '20%',
	        		right: rightPx+'%',
	        		bottom: '10%',
	        		containLabel: true
	        },

**Comment by flybrotheryao** [comment]
what

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3805
