### ISSUE TITLE
柱状图容器宽度溢出问题

### ISSUE THREAD

**Issue by meiyouqing** [ecomfe/echarts#3881]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.3
+ 浏览器类型和版本 (Browser version):chrome52.0.2743.116 m
+ 操作系统类型和版本 (OS Version):win10 64位

#### 重现步骤 (Steps to reproduce)
首次渲染，柱状图容器宽度溢出，压住了y轴上的标识文字
点击切换到折线图，再切换回柱状图，宽度就是正常的了

#### 可能哪里有问题 (What went wrong)
首次渲染柱状图容器宽度计算

#### ECharts配置项 (ECharts option)

```javascript
 options = {
	    			title:{
	    				text:'累计用户'
	    			},
	    			tooltip:{
	    				trigger:'axis'
	    			},
	    			legend:{},
	    			toolbox:{
	    				show:'true',
	    				feature:{
	    					magicType:{type:['line','bar']}
	    				}
	    			},
	    			xAxis:{
	    				type:'category',
	    				boundaryGap:false,
	    				data:['8-12','8-13','8-14','8-15','8-16','8-17','8-18']
	    			},
	    			yAxis:{
	    				type:'value'
	    			},
	    			series:[{
	    				name:'新增用户',
	    				type:'bar',
	    				data:[5,22,35,11,15,22],
	    			}]
	    		};

```

#### 截图

![qq 20160819115106](https://cloud.githubusercontent.com/assets/6309684/17800610/376e546e-6617-11e6-93a7-911304c76754.jpg)

 ##线上实例
[https://jsfiddle.net/e9vecoga/4/](https://jsfiddle.net/e9vecoga/4/)

**Comment by realeve** [comment]
xAxis:{
                type:'category',
                boundaryGap:true,
                data:['8-12','8-13','8-14','8-15','8-16','8-17','8-18']
            },
