### ISSUE TITLE
【建议】series[i]-pie.data[i].label.normal.position位置控制不灵活

### ISSUE THREAD

**Issue by semmy2010** [ecomfe/echarts#3888]
#### 问题简述 (One-line summary)
目前series[i]-pie.data[i].label.normal.position只接受几个string类型参数("outside","inside","inner","center")，建议增加一种类型，比如number，用于控制label离圆心的距离。
比如这种需求：不能把label放在外面“outside”,只能放里面"inside"，但是“inside”又太里面，放的位置要稍微比“inside”更外面一些，也就是离圆心更远些，这时候就不能控制了。像柱形图series[i]-bar.label.normal.position还可以接受一个Array的类型，可以灵活控制位置就比较好。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
设置成 outside 之后可以通过 labelLine 设置视觉引导线的距离达到这个效果

**Comment by liucien** [comment]
![image](https://user-images.githubusercontent.com/32785166/64593341-82141500-d3e0-11e9-882f-cc8a01e18619.png)
你好，请问文字能否控制偏移 @pissang

**Comment by namelysweet** [comment]
不知道最新版解决这个问题没，确实有这个需求~
