### ISSUE TITLE
【建议】建议有屏蔽echarts自带的hover事件开关

### ISSUE THREAD

**Issue by semmy2010** [ecomfe/echarts#3889]
#### 问题简述 (One-line summary)
建议有屏蔽echarts自带的hover事件开关，也就是mouseover和mouseout，就是鼠标移过柱形图有高亮的效果，但不能设置silent为true，因为还要响应鼠标点击其他事件。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以把 emphasis 的样式设置成跟 normal 一样

**Comment by wuzinong** [comment]
想请问下如何控制hover的时候图表不产生高亮效果

**Comment by iHTCboy** [comment]
@wuzinong  关闭hover时的高亮:

```ts

option = {
  series: [
    {
      emphasis: {
        disabled: true,
        focus: 'none'
      },

    }

```
