### ISSUE TITLE
echarts  容器width:100%有问题。

### ISSUE THREAD

**Issue by JSlife23** [ecomfe/echarts#3894]
#### 问题简述 (One-line summary)

我的echarts容器 是放在一个tab选项卡里面的 初始化echarts容器 display:none; 我给echarts容器设置的width:100%height:xxpx; 。但是当我帮数据填充进去切换选项卡到echarts的时候生成的图标width是100px,如果我初始化echarts  width：xxxpx就是正常的。也就是说echarts初始化要是设置display:none;的时候获取dom的width:100%有问题。
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  3.2.1
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
在容器从不可间切换成可见的时候需要调用一次 resize 保证 echarts 取到正确的 clientWidth 和 clientHeight

**Comment by liuchyi** [comment]
tabs处于非active状态就会出现你这样的问题，把tab设为active状态即可

**Comment by vicvinc** [comment]
可以这样，在mounted hook里
```javascript
window.requestAnimationFrame(()=>{ 
 // echarts init etc
})
```
