### ISSUE TITLE
[建议] 组件布局自适应

### ISSUE THREAD

**Issue by guhuajun** [ecomfe/echarts#3896]
#### 问题简述 (One-line summary)
目前我正在使用django-cms开发内部管理系统，eCharts作为绘图组件提供了非常强大的功能，也非常方便开发成django-cms的插件。但是当前版本中组件布局自适应的不足，因此需要管理员设置很多和布局有关的参数，增加了管理负担。

比如图例过多，过长时需要管理员手动设置位置。
又比如标签位置过长，需要手动调整Grid的Left值

希望eCharts的下个大版本中能缓解这一块的问题。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)
![echarts01](https://cloud.githubusercontent.com/assets/14121694/17843142/25eb63ba-685d-11e6-8c15-7b51076e3125.png)

**Comment by Wall-ee** [comment]
我们现在是这样解决的：用的是bootstrap3框架 先用js获取宽度，然后乘以固定的长宽比例，算出画布大小，算是一个折中的办法，缺点就是改变屏幕大小后需要重新刷新

**Comment by yelingfeng** [comment]
label宽度是不固定的啊 你怎么动态算宽度？ @Wall-ee

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#grid.containLabel

**Comment by guhuajun** [comment]
@pissang 谢谢。
