### ISSUE TITLE
方法名冲突会导致自动适应图表颜色错误

### ISSUE THREAD

**Issue by brooks-li** [ecomfe/echarts#3901]
#### 问题简述 (One-line summary)
方法名冲突会导致自动适应图表颜色错误

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.存在冲突的方法名，导致myChart.resize();执行后饼图的颜色全部错误

#### 可能哪里有问题 (What went wrong)
Array.prototype.indexOf方法为自己封装的common方法，用于基本的array判断。建议调整一下方法名，此方法很可能会有冲突

#### ECharts配置项 (ECharts option)

```javascript

下面是冲突的方法
/**
 * 获取指定元素的下标，如果不存在该元素则返回-1
 */
Array.prototype.indexOf = function (e) {
	for (i = 0; i < this.length && this[i] != e; i++) {
	}
	return (i == this.length)? -1 : --i;
};

```

**Comment by pissang** [comment]
不要修改 prototype 中的内置方法
