### ISSUE TITLE
以时间为X轴的折线图中，X轴上的点和实际折线上的点差8个小时。是哪里需要特别设置吗

### ISSUE THREAD

**Issue by harryhan** [ecomfe/echarts#3904]
#### 问题简述 (One-line summary)
以时间为X轴的折线图中，X轴上的点和实际折线上的点差8个小时。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version): chrome51 (64-bit) 
+ 操作系统类型和版本 (OS Version):win10 64位

#### 重现步骤 (Steps to reproduce)
1.定义一个div，div id="divRight" style="width:100%;height:400px;"

2.SetOption，加载数据。
图中数据的时间是2:30，对应的X轴坐标时间速度10:30

![x 8](https://cloud.githubusercontent.com/assets/3314258/17879934/38237ac4-6928-11e6-9f21-f034071ec98a.png)

#### 期望结果 (Expected behaviour)
期望X轴上的时间能和折线的时间对应上

#### 可能哪里有问题 (What went wrong)
不清楚，猜测是不是和时区有关，因为刚好差8个小时

#### ECharts配置项 (ECharts option)

```javascript
 option = {
        title : {
            text : '电表历史总有功功率曲线',
            subtext : '2016.7.13--2016.7.19'
        },
        tooltip : {
            trigger: 'item',
            formatter : function (params) {
                return params.value[0] + '<br/>'
                       + params.value[1]
            }
        },
        toolbox: {
            show : true,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        // dataZoom: {
        //     show: true,
        //     start : 70
        // },
        legend : {
            data : ['A车间2#变压器']
        },
        grid: {
            y2: 80
        },
        xAxis : [
            {
                type : 'time',
                splitNumber:10
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : [
            {
                name: 'A车间2#变压器',
                type: 'line',
                showAllSymbol: true,
                data: [['2016/07/18 0:2:55',0.2479],['2016/07/18 0:47:55',0.2172],['2016/07/18 1:5:59',0.2532],['2016/07/18 1:12:55',0.2376],['2016/07/18 1:37:56',0.2541],['2016/07/18 1:48:55',0.2274],['2016/07/18 2:0:0',0.2421],['2016/07/18 2:30:0',0.2173],['2016/07/18 2:32:58',0.26],['2016/07/18 3:0:0',0.2406],['2016/07/18 3:11:19',0.2634],['2016/07/18 3:19:17',0.2182],['2016/07/18 3:28:10',0.2395]]
            },
           
        ]
    };

```

**Comment by harryhan** [comment]
我用在线构建http://echarts.baidu.com/builder.html，只选择列折线图，加载后画出的折线图X轴坐标寺OK的。
[echarts-SelfBuild.zip](https://github.com/ecomfe/echarts/files/431652/echarts-SelfBuild.zip)

**Comment by harryhan** [comment]
还是上面提的问题，当为把本地电脑时间设置为 **UTC协调世界时** 时，X轴的时间每天从00：00开始，
![utc -x 00 00](https://cloud.githubusercontent.com/assets/3314258/17882116/0a9db046-693d-11e6-8c8d-32b668902c30.PNG)
当为把时间设置为 **北京时间UTC+08：00**时，X轴的时间每天从08：00开始，
![utc 08 00 -x 08 00](https://cloud.githubusercontent.com/assets/3314258/17882120/1094ba62-693d-11e6-9a8a-39ffb59c0078.PNG)
此时当xAxis中的splitNumber设置比较小时，X轴只能看到年月日，按照一般用户感觉，肯定以为是从00:00开始的（但实际上是08：00开始），此时就觉得曲线的峰值和业务不符。
![utc 08 00 -xaxis splitnumber 10 -x 08 00](https://cloud.githubusercontent.com/assets/3314258/17882127/17300c46-693d-11e6-8a30-1fc41fe98f26.PNG)

**希望X轴的开始时间能不和本地时区相关，都从00：00开始，已符合一般用户认知。*

**Comment by pissang** [comment]
试一下用时间戳

**Comment by wu11106** [comment]
我原本就不想说，我到今晚有些扫描的、翻译的字，我不知道该说什么？
当我接到机场的拥有者后，开心使我忘记了隐藏背后的危机，昨天早上前台说吴总您的电话，一听是房东的电话，一股空前危机感……。
我很多的遗憾！对不起好员工，对不起家人，对不起自己几年的心血。现在又多了对不起谷歌的用心良苦，我的心很痛很痛。对于亏损我只是一笑而过，亏损算什么？
成人网我一直挂在心里，地图的编制就更加珍惜，还有…等等渴望，都是等走过这二个多月不到的淡季，旺季的季节风就吹到了，盼望到时候，我佣有一个IT房，组合一个多种网络行为的小部门，我还……
怎么挺过这一难关？我不想离开这里，不想回到中国。在提心吊胆的地方，好像有一条无影的绳索捆绑着手脚。
我尽量把心拉回来，按照您们的意图去完成，我真的不知道怎样做？晚饭后，九点开始查找资料、图片，除了扫视挑选图片……，但是，一想到在最后为谷歌做多一点事，我很宽心，就这样做了几个小时，做着做着抱着ipad睡觉了。
发表后，有点感觉到您们的不满，对不起！我不想的，有什么比企业在曙光来临之前倒闭更难受？虽然，我还没见到房东，电话打了很多次都没人接，但我知道，等待着我是什么？
当然，我有一分可能，会用十分来争取！
2016-08-22晚敬上!
 （昨晚就随意下写完，感得自已的事不合时宜跟您们说）
Yinghui Wu
wu11106025@gmail.com

2016年8月23日星期二，HanZhao <notifications@github.com> 写道：
