### ISSUE TITLE
echarts3.0关于维恩图的使用问题

### ISSUE THREAD

**Issue by lgbcscs** [ecomfe/echarts#3905]
#### 问题简述 (One-line summary)
echarts3.0中维恩图为什么不要了呢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): 谷歌51
+ 操作系统类型和版本 (OS Version): window

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
希望还是可以使用

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
2 里的韦恩图很不完善，3 里先去掉了，后面会跟 wordCloud 一样以插件形式推出

**Comment by ritawr** [comment]
那我如果需要在3.0 里面使用韦恩图，现在除了降级到2.0 版本，还有其他方式吗？

**Comment by ritawr** [comment]
那我如果需要在3.0 里面使用韦恩图，现在除了降级到2.0 版本，还有其他方式吗？

**Comment by ritawr** [comment]
那我如果需要在3.0 里面使用韦恩图，现在除了降级到2.0 版本，还有其他方式吗？

**Comment by ritawr** [comment]
那我如果需要在3.0 里面使用韦恩图，现在除了降级到2.0 版本，还有其他方式吗？

**Comment by ritawr** [comment]
那我如果需要在3.0 里面使用韦恩图，现在除了降级到2.0 版本，还有其他方式吗？

**Comment by ritawr** [comment]
那我如果需要在3.0 里面使用韦恩图，现在除了降级到2.0 版本，还有其他方式吗？

**Comment by ritawr** [comment]
那我如果需要在3.0 里面使用韦恩图，现在除了降级到2.0 版本，还有其他方式吗？

**Comment by lgbcscs** [comment]
请问一下，3.0已经一年过去了，现在维恩图是否已经添加进去了，或者有插件可以补充进来用了呢

**Comment by yuanyayi** [comment]
同问，我觉得能支持4组数据就够用了

**Comment by Lume98** [comment]
> 2 里的韦恩图很不完善，3 里先去掉了，后面会跟 wordCloud 一样以插件形式推出

现在有插件可以用了么？
