### ISSUE TITLE
EChart 3.0 折线图堆叠展示错误

### ISSUE THREAD

**Issue by luke0922** [ecomfe/echarts#3909]
#### 问题简述 (One-line summary)

展示多组数据，折线图的坐标关系错误，数量多的坐标反而低，图片：

![chrome_2016-08-23_23-58-38.png](https://ooo.0o0.ooo/2016/08/23/57bc732eca2b7.png)

图片中的这个可以看到昨天的数量应该是 28，而图片中显示的坐标却与今天的 194 相差无几，这个应该有问题。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): https://cdnjs.cloudflare.com/ajax/libs/echarts/3.2.3/echarts.js
+ 浏览器类型和版本 (Browser version): Google Chrome 版本 52.0.2743.116 m
+ 操作系统类型和版本 (OS Version): Windows7 64bit

#### 重现步骤 (Steps to reproduce)
1. 
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
这就是为什么叫“堆叠”
