### ISSUE TITLE
How to Label last value of series only, 线条图只标记最后一个点。以及data和value的冲突。

### ISSUE THREAD

**Issue by igsoap** [ecomfe/echarts#3910]
#### 问题简述 (One-line summary)

How to Label last value of series only,
 线形图只标记最后一个点。以及data和value， array 和 string的冲突。

#### 版本及环境 (Version & Environment)
Echart 3.0
chrome
windows

#### 重现步骤 (Steps to reproduce)

1.我要画一条横线，总共5个点，但是我只要标记最后一个点。所以我用
 data: [ 100，100，100，100
       , {
           value: 100
           , label: {
               normal: {
                   show: true
                   , position: [-30, -35]
                   , formatter: 'cost' + '${c}'
               , }
           }
                                  , }
                                  ]
以上没问题。

但是当我开始用variable带入数据时就有问题，见下

x =[100,100,100,100,100]； //这应该是array 但是typeof说他是object 
y = 100；
data: [ x,
       , {
           value: y
           , label: {
               normal: {
                   show: true
                   , position: [-30, -35]
                   , formatter: 'cost' + '${c}'
               , }
           }
                                  , }
                                  ]
以上code画出来图像扭曲。不正确了

那我觉得把x变成string
x =[100,100,100,100,100]； 
x2 = x.toString();
y = 100；
data: [ x2,
       , {
           value: y
           , label: {
               normal: {
                   show: true
                   , position: [-30, -35]
                   , formatter: '开销 ' + '${c}'
               , }
           }
                                  , }
                                  ]
以上图片Echart把 x2 整个数据看成一个点。相当于 "100,100,100,100" 
#### 期望结果 (Expected behaviour)

见jsfiddle

#### 可能哪里有问题 (What went wrong)

见jsfiddle

#### ECharts配置项 (ECharts option)

```javascript

see jsfiddle

```

#### 其他信息 (Other comments)

https://jsfiddle.net/anc5agvw/

**Comment by pissang** [comment]
你这格式不正确啊，数组需要是一维的

**Comment by igsoap** [comment]
那如果我只想一条线最后一个点被label 其他都不label能如何实现

**Comment by wu11106** [comment]
有多少爱可以重来？
中午睡醒，看到几天里的酒店订房和地图定位相关的网站资料，邮件大部分都不是谷歌的来信，我知道后面是谷歌主导下的程序，心里有说不出的感概。
很想通过您们的帮助，获得小许信贷，救回濒临绝境的客栈。但找不到在哪里的情况下，也产生了自卑感，资助总是尴尬的事情。
因为有了钱财的利益，才建立起友谊！因为友谊的继续，才需要起钱财！
我的需求的钱财属于后一句，客栈早己经打定了血本无归，在经济不振和淡季都是亏损很多。这不是我救酒店的主要原因……
我梦想…！把仰光国际机场地图定位做得更好后，再把火车站、唐人街、大金塔、昂山翡翠珠宝木雕市场、旭斯勒批发市场，都在谷歌地图上注册定位，并且成为拥有人，再做一个相连谷歌地图的网站。
网站攻略：
第一个，以旅游资讯为主打，奖励我酒店住客去注册我的网站，并且发表他们在缅甸的旅游心得和图片视频，旅游栏目尽量让旅游者去互动。
第二个，由我来主导的仰光人文风情、仰光历史遗迹。
第三个，还是由我主导仰光景点资讯、美食仰光城，旅游天气。
第四个，就是交通信息，仰光与第二大城市曼德勒机场的国际航班与国内航班信息（最好是网站内，有航空机票销售公司驻点，由他们提供），通往各大城市和旅游景点的交通状况。
第五，广告计划，必须在谷歌企业指导下进行，在必要时才自行联系商家广告。
第六，在不影响网站的筹建中上，成人网也要进行筹建。
以上是初步的计划，那是我热爱的谷歌地图定位，背后还有一个受到尊崇的友谊的后盾支持我，我的希望不是梦……
展开的工作：
需要聘请翻译一位，懂点电脑知识、懂缅文、中文和英文，几名懂英、缅文的TI工作人员，申请办理新的wifi来提高网速，购买电脑和办公用品，酒店设立--酒店网络销售与地图定位相关网站的“欧共体”IT部门。
虽然起步低，但他是一改往日的行为，什么都是自己做。我必须要利用团队合作精神，借用外面的技术合作，把网站交给专业网络技术来做，用商业行为结合互联网特性来操作，争取最大的利益。
美丽憧憬，必须二个条件，第一是谷歌的有力支持，第二个就是酒店不能现在倒闭，成功的网站，酒店喜欢倒闭就倒闭吧！
亲爱的谷歌，人与人之间的距离，没有西雅图与仰光距离大，它是一幅无影的墙！跨越不过的只尺天涯，如种族隔离一样，把互信隔开在墙的两端。
我以前说过的“感恩”“我是谷歌人”，随着时间和友情的发展来更新的。
感恩！感恩是有等级之分：
如果获得谷歌帮助下的信贷，内心起了贪婪的收获，又或者是收获了可以不负责任的借款。关键时刻的相助，我不认为是举手之劳的解释，正是他的及时举手，才把我从深海拉上岸来……，拉上的那怕不是黄金海岸，这样感激心态，会不会对相助者有不轨截图？答案是显然的
就算没有感恩，用在商言商的思维，也会诚恳面对谷歌的友情。获得谷歌信任的资助，就是钻石般闪耀的价值，比“人民大会堂指定饮品”还有市场效应。贪婪地把借助示为无需负责任的款项，其款项就是原来的价值，升值来自于珍惜谷歌的友谊！天价来自于感恩谷歌的提携！
我是一个贪得无厌的奸商，不求给予我的衣食住行，梦寐以求得到您们网络帝国的相助，助我的小帆船--平稳航道在网网之海。
起锚的帆船叫～感恩！
航程目的地叫--共赢！
我是什么人新解释：
感恩里添加上带信仰、效忠、崇拜，感恩就会出现中国的成语：“滴水之恩，滴水之恩涌泉相报”。
比如：我是百度人！当然百度危难，我舍命也救不到百度中的一度，但是，百度存在心里，自然流露出维护百度爱护百度。前期，百度给陷害成中国医学排名丑闻事件，百度有事如同是我，在征得百度同意。我公开排名是我偷取搞出来的，已任何人无关。
现实上百度与我无半点关系，用广东话说：人家百度识你系老鼠？。我当然不是老鼠，真正的老鼠是，玩弄排名又没有这个本事，把行为封存在百度之内？搞到像过街老鼠，人人喊打。
祝我们在友谊的纽带上，阻隔互信的墙壁，随着时间消逝在互联网上。

YINGHUI WU
wu11106025@gmail.com

2016年8月24日星期三，igsoap <notifications@github.com> 写道：

**Comment by igsoap** [comment]
晕 楼上是啥
