### ISSUE TITLE
大数据加载,导致崩溃

### ISSUE THREAD

**Issue by sliverxxm** [ecomfe/echarts#3915]
#### 问题简述 (One-line summary)
页面显示一个折线图，大概有30条线，每条线大概50万个点。
后台完成数据查询后，返回给jsp，但是页面总是加载不了，就像死机了一样，有时浏览器提示崩溃。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7
+ 浏览器类型和版本 (Browser version):Google Chrome  52.0.2743.116 m (64-bit)
+ 操作系统类型和版本 (OS Version):win7旗舰版

#### 重现步骤 (Steps to reproduce)
1. 模拟30条线,每条线50万个数据点
2. 构建一个折现图，装入步骤1的数据

#### 期望结果 (Expected behaviour)
图形能够正常显示

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by sliverxxm** [comment]
option = {
    title : {
        text: '动态数据',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['上证指数']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    dataZoom : {
        show : true,
        realtime: true,
        start : 50,
        end : 100
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : true,
            data : data1 // 后台返回的大数据,x轴
        }
    ],
    yAxis : [
        {
            type : 'value',
            scale:true,
            splitNumber: 5,
            boundaryGap: [0.05, 0.05]
        }
    ],
    series : [
        {
            name:'上证指数',
            type:'k',
            data: data2 // 后台返回的大数据,y轴
        }
    ]
};

**Comment by pissang** [comment]
数据太多了，精简一下

**Comment by sliverxxm** [comment]
那就是不能支持大数据量的图形展示吗?
实际业务就是,在线的大数据量分析.
两年的数据进行同比,每年的数据基本都在百万左右,这种情况下,echarts是否能从技术方面进行解决???

**Comment by pissang** [comment]
建议后台过滤后传到前端，直接传 50w 的没什么意义

ps: echarts 的折线图在开启 sampling 的时候是能够展现 100w 左右的数据的，但是如果好几百万的话浏览器内存会容易不够
