### ISSUE TITLE
关于自适应问题

### ISSUE THREAD

**Issue by wushuang5112** [ecomfe/echarts#3918]
#### 问题简述 (One-line summary)
你好，我用Echarts在展示报表时发现其图形变小后文字却不变小，这样会导致图形在小屏时会出现异常。能不能通过自定义字体大小，通过类似em的机制来配置。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): All
+ 浏览器类型和版本 (Browser version): All
+ 操作系统类型和版本 (OS Version): All

#### 重现步骤 (Steps to reproduce)
1. 如饼图条目过多时会出现文字遮挡图形的问题。

#### 期望结果 (Expected behaviour)
图形能按比例展现出来。

#### 可能哪里有问题 (What went wrong)
文字大小缩放问题。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
字体暂时不支持 em
