### ISSUE TITLE
支持多种图例类型吗？

### ISSUE THREAD

**Issue by manks0127** [ecomfe/echarts#3919]
echarts支持多种图例类型吗？比如说有商户图例和客户端图例

在一个图中哦，文档中说是3版本的支持多图例，但是只有这一句话的概述，没有细述，没有example，怎么处理？

**Comment by pissang** [comment]
声明多个 legend 组件就行了

**Comment by manks0127** [comment]
@pissang 
Like this?

`legend: {
        orient: 'vertical',
        left: 'left',
        data: ['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    legend: {
        orient: 'vertical',
        left: 'left',
        data: ['aaa','bbb']
    },`

但是这样会报错：Duplicate key 'legend'
