### ISSUE TITLE
折线饼图混搭，数据含有小数点，结果会出现十几位小数

### ISSUE THREAD

**Issue by liuv1118** [ecomfe/echarts#3921]
#### 问题简述 (One-line summary)
折线饼图混搭，数据含有小数点，结果会出现十几位小数

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/19453091/17924940/6066b17c-6a1d-11e6-8f86-f86711187bb9.png)

**Comment by pissang** [comment]
formatter 里 toFixed  保证精度
