### ISSUE TITLE
修改柱状图里的一组柱形图的背景颜色

### ISSUE THREAD

**Issue by lisgking** [ecomfe/echarts#3922]
#### 问题简述 (One-line summary)
如何修改例子
http://echarts.baidu.com/demo.html#bar-stack
一组柱形图的背景颜色如何修改

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.http://echarts.baidu.com/demo.html#bar-stack
2.一组柱形图的背景颜色如何修改

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-bar.itemStyle.normal.color

**Comment by zhengtulymGh** [comment]
itemStyle.normal.color 设置的是柱状图的颜色，不是背景色 @pissang
