### ISSUE TITLE
showTip()无效

### ISSUE THREAD

**Issue by ChristianShuai** [ecomfe/echarts#3924]
#### 问题简述 (One-line summary)

想实现这样一个效果;
![0c0nys71b 6fd3m_ d_ 85](https://cloud.githubusercontent.com/assets/15918039/17927313/a38f0d6e-6a27-11e6-8607-c5782a0a3224.png)

测试代码如下：
![image](https://cloud.githubusercontent.com/assets/15918039/17927291/8886410e-6a27-11e6-8e87-b11499b66ff5.png)
但是tooltip一直显示不出来

求帮助啊 ，折腾了一个下午了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by wu11106** [comment]
您们好！怎么下午我登陆不进去，登陆CC，请求帮助！谢谢！盼望着……

2016年8月24日星期三，ChristianShuai <notifications@github.com> 写道：

**Comment by pissang** [comment]
showTIp 需要传入 `seriesIndex`
