### ISSUE TITLE
360和IE浏览器，动态生成的数据，刷新页面时不更新，好像是有缓存

### ISSUE THREAD

**Issue by chenghyer** [ecomfe/echarts#3929]
#### 问题简述 (One-line summary)
我的图表数据是动态绑定的，但是在360和IE浏览器下，刷新页面时在数据库数据发生变化的情况下，图表数据是不更新的，不知道是echarts中是否存在缓存，该如何清除？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):360浏览器兼容模式和IE浏览器
+ 操作系统类型和版本 (OS Version):Windows 7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
在360和IE浏览器下，图表数据跟随数据库数据的变化而更新

#### 可能哪里有问题 (What went wrong)
echart缓存

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
缓存跟 echarts 没关系
