### ISSUE TITLE
【建议】饼图不灵活，没办法控制每个扇形区域的半径

### ISSUE THREAD

**Issue by semmy2010** [ecomfe/echarts#3931]
#### 问题简述 (One-line summary)

饼不灵活没办法控制各个扇形区域的半径，不是南丁格尔图那样自动根据数值控制半径。需要手动控制各个扇形的半径。比如点击高亮，然后让被点击的扇形图变大，如图所示，就没办法做到。通过设置series[i]-pie.selectedOffset会偏移圆心，没办法与原来的圆形粘在一起
![123](https://cloud.githubusercontent.com/assets/4402907/17958347/a863167e-6acb-11e6-9cce-3628214a71cb.jpg)
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by chordmo** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Ovilia** [comment]
重复问题 #3857 ，我先关闭这个 issue，会提高这个需求的优先级
