### ISSUE TITLE
大数据在线分析,折线图加载失败

### ISSUE THREAD

**Issue by sliverxxm** [ecomfe/echarts#3932]
#### 问题简述 (One-line summary)

实际业务是在线的大数据量分析.页面显示一个折线图，大概有30条线，每条线大概50万个点。
后台完成数据查询后，jieg返回给jsp，但是页面总是加载不了，就像死机了一样，有时浏览器提示崩溃。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.2.7
+ 浏览器类型和版本 (Browser version):Google Chrome 52.0.2743.116 m (64-bit)
+ 操作系统类型和版本 (OS Version):win7旗舰版

#### 重现步骤 (Steps to reproduce)
1. 模拟30条线,每条线50万个数据点
2. 构建一个折现图，装入步骤1的数据

#### 期望结果 (Expected behaviour)

目前业务就是大数据在线分析,两年的数据进行对比,每年的数据最少都在百万左右.在这个数据量级下,是否能够通过技术手段解决图标加载的问题.同时echarts支持的最大数据量级是多少???

#### ECharts配置项 (ECharts option)

```javascript
option = {
title : {
text: '动态数据',
subtext: '纯属虚构'
},
tooltip : {
trigger: 'axis'
},
legend: {
data:['上证指数']
},
toolbox: {
show : true,
feature : {
mark : {show: true},
dataView : {show: true, readOnly: false},
restore : {show: true},
saveAsImage : {show: true}
}
},
dataZoom : {
show : true,
realtime: true,
start : 50,
end : 100
},
xAxis : [
{
type : 'category',
boundaryGap : true,
data : data1 // 后台返回的大数据,x轴
}
],
yAxis : [
{
type : 'value',
scale:true,
splitNumber: 5,
boundaryGap: [0.05, 0.05]
}
],
series : [
{
name:'上证指数',
type:'k',
data: data2 // 后台返回的大数据,y轴
}
]
};

```

**Comment by pissang** [comment]
统一在 https://github.com/ecomfe/echarts/issues/3915 下回复
