### ISSUE TITLE
radar.triggerEvent无效

### ISSUE THREAD

**Issue by yoyo007007007** [ecomfe/echarts#3934]
#### 问题简述 (One-line summary)
radar.triggerEvent没有作用。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.2
+ 浏览器类型和版本 (Browser version):chrome 5
+ 操作系统类型和版本 (OS Version):win7 64

#### 重现步骤 (Steps to reproduce)
1.xAxis.triggerEvent有作用
2.radar.triggerEvent 点击radar.name 或者 indicator.name没有作用

#### 期望结果 (Expected behaviour)

期望能点击并且获得indicator 的值（雷达维度）

#### ECharts配置项 (ECharts option)

option = {

tooltip : {
					        trigger: 'item'
					    },
					    legend: {
							orient:'vertical',

							x : 'right',
					        data:['CN101886586B','CN2668873V']
					    },
					    radar :{

								triggerEvent:true,
								name: {
									show:true,
									textStyle:{color:'#333'}

								},
					           indicator : [
					               { text: '专利保护范围', max: 100},
					               { text: '专利保护强度', max: 100},
					               { text: '专利技术质量', max: 100}
							   ],
							   center : ['50%','70%'],
							   radius:'95%'

						   },
					    calculable : true,
					    series : [
					        {
					            name: 'CN101886586B vs CN2668873V',
					            type: 'radar',
					            data : [
					                {
					                    value : [30, 40, 50],
										itemStyle: {normal: {color:'rgba(193,35,43,1)'}},

										name : 'CN101886586B',
					                  
					                  
					                },
					                 {
					                    value : [20, 50, 40],
										 itemStyle: {normal: {color:'rgba(181,195,52,1)'}},

										 name : 'CN2668873V'
					                }
					            ]
					        }
					    ]
					};

				myChart.setOption(option);

}

```


#### 其他信息 (Other comments)
<!-- 例如，截图或线上实例 (JSFiddle/JSBin/Codepen) (For example: Screenshot or Online demo) -->

**Comment by yoyo007007007** [comment]
大哥，我咨询您一个问题：如果我想实现一个可交互的 “产业链” 控件，有比较好的控件推荐吗。

**Comment by songkai2012** [comment]
确实无效，今天看了别人做出来的可能是用了echarts2.0吧
