### ISSUE TITLE
希望echarts graph可以画直角折线，现在只可以用起止点画直线和起止点画曲线。没有带直角的折线

### ISSUE THREAD

**Issue by guntertien** [ecomfe/echarts#3935]
#### 问题简述 (One-line summary)

希望echarts graph可以画直角折线，现在只可以用起止点画直线和起止点画曲线。没有带直角的折线

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

比如实现这的效果图

![image](https://cloud.githubusercontent.com/assets/21062327/17965874/5da8d634-6af1-11e6-9c25-9648f970f0fc.png)

**Comment by pissang** [comment]
暂时没有这个计划
