### ISSUE TITLE
平均值数据没办法格式化,导致小数位后很长,很难看

### ISSUE THREAD

**Issue by zfh424** [ecomfe/echarts#3936]
#### 问题简述 (One-line summary)

图形中使用使用自动计算的 平均值。但是均值没有办法格式化,导致小数点后很多位、很长 很难看。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):最新3.0
+ 浏览器类型和版本 (Browser version):Chorme
+ 操作系统类型和版本 (OS Version):MacOS

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

数据能够支持格式定义或小数位的定义。

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
formatter 里 toFixed
