### ISSUE TITLE
用setOption()更新已有图表后，无法显示legend。

### ISSUE THREAD

**Issue by animalize** [ecomfe/echarts#3937]
请把文件解压，然后把echarts.js文件放在同一目录，就可以看到演示了， 内有详细的问题说明。

提示：
甲 series not exists. Legend data should be same with series name or data name.  echarts.js:47156:26
乙 series not exists. Legend data should be same with series name or data name.  echarts.js:47156:26
丙 series not exists. Legend data should be same with series name or data name.  echarts.js:47156:26

测试于3.2.3。

[chart.zip](https://github.com/ecomfe/echarts/files/438200/chart.zip)

**Comment by pissang** [comment]
都有提示了，系列名字必须要跟 legend data 对应

**Comment by raymondjhs** [comment]
我也遇到这问题，系列名字跟legend datas是对应啊。

**Comment by raymondjhs** [comment]
第一次的时候可以，但是第二次同时更改legend.data各系列的name、series的各系列的name，重新再setOption后，legend就不能显示了（数据图标可以正常显示，就是legend不能）

**Comment by animalize** [comment]
@raymondjhs 
可能就这么设计的吧：**series改变了**就不能复用已有的对象，只能echarts.init()一个新对象。
倒也不是什么大问题，就是极个别浏览器在echarts.init()时会闪一下。

**Comment by Shany100** [comment]
@animalize   只能先按你说的这么搞了，性能上没什么问题吧

**Comment by animalize** [comment]
@Shany100  性能没问题，挺好的

**Comment by huaishan** [comment]
@Shany100 我是先clear清空实例，再setOption

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/commit/fbc81cbe26e7686b3532b7dc873608b684553eaa
