### ISSUE TITLE
仪表盘颜色不能定制

### ISSUE THREAD

**Issue by qingmeizhujiufan** [ecomfe/echarts#3939]
#### 问题简述 (One-line summary)
颜色数组自定义后无法生效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): google浏览器、版本 52.0.2743.116 m
+ 操作系统类型和版本 (OS Version): win7旗舰版

#### 重现步骤 (Steps to reproduce)
1.仪表盘demo中加入  ['#ff0000','#00ff00', '#0000fff']
2.点击刷新

#### 期望结果 (Expected behaviour)
颜色重置

#### ECharts配置项 (ECharts option)

```javascript
option = {
    tooltip : {
        formatter: "{a} <br/>{b} : {c}%"
    },
    color: ['#ff0000','#00ff00', '#0000ff'],
    series: [
        {
            name: '业务指标',
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50, name: '完成率'}]
        }
    ]
};

app.timeTicket = setInterval(function () {
    option.series[0].data[0].value = (Math.random() * 100).toFixed(2) - 0;
    myChart.setOption(option, true);
},2000);


```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-gauge.axisLine.lineStyle.color
