### ISSUE TITLE
echarts+bmap+热力图，怎么使用timeline？

### ISSUE THREAD

**Issue by wangbingxu** [ecomfe/echarts#3940]
#### 问题简述 (One-line summary)
echarts+bmap+热力图，能否使用timeline？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts-all-3.js
+ 浏览器类型和版本 (Browser version):Chrome for mac 版本52
+ 操作系统类型和版本 (OS Version):macOS Sierra

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
使用timeline来切换热力图

#### 可能哪里有问题 (What went wrong)
据说你们echarts无法再地图上渲染timeline？

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)
貌似百度地图也没有提供使用timeline的方法

**Comment by pissang** [comment]
跟其它图表 timeline 的用法一样
