### ISSUE TITLE
Baidu Echart 速度好慢。打不开页面。可不可以把教程那些在github放一个文本版的。

### ISSUE THREAD

**Issue by igsoap** [ecomfe/echarts#3945]
如题。

有些option忘记了。在美国baidu这一个星期都好慢。打不开。
在github放一个文本的备份吧。这样起码可以查得到资料。

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-doc

**Comment by wu11106** [comment]
亲爱的团队：
二个小时前睡醒时候，有一种预感，几天来的事情，是不存在的事实，回到现实上吗？抓紧时间转让企业，把亏损控制在最小吧？
前后几十小时的“用户名或密码错误”，正常的网站都解决了。怎么会……？
突然感叹自己…，我不是在做捐款，这种有意义活动，是筹款，是在企业危难时刻随时倒闭下，没有时间过多考虑情况下，会做成自尊心的伤害，对前景凄怆的心态。
您们对我的惠及受益，使我感动中对未来充满期望，坚持下去是我的性格，不管给冷水泼多少次？因为还有一种信念和追求，是来自谷歌的。

Yinghui Wu
wu11106025@gmail.com

2016年8月27日星期六，Yi Shen <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3D1AnPWzj%252BMbaYPchuglD4T3zSzhUC5FDfTAW6YrCdskE%253D%26token%3DtklJTauEYKAKEsXdZC3I2inM2%252BLb0KoCU9vK%252BUT2iIP24ivgDDGNBtMpszkW9mNCe5UraC8BBW4eYNLFJl8RZUxylMakhbnHbwy1psuYwo5u3CUAWOpL2ZlclYBKhfzW4pBo7Sgyos6CZ39Ba62c%252Fw%253D%253D&tc_serial=26582107645&tc_rand=1747090142&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26582107645&tc_rand=1747090142&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>
