### ISSUE TITLE
如何实现太平洋版地图

### ISSUE THREAD

**Issue by lwy92** [ecomfe/echarts#3946]
#### 问题简述 (One-line summary)
如何实现太平洋版地图？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
http://bl.ocks.org/d3noob/5189184

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3899，不要提重复的 issue

**Comment by luowengang** [comment]
这个问题解决了吗
