### ISSUE TITLE
散点图能每个点一种颜色吗？

### ISSUE THREAD

**Issue by cag2050** [ecomfe/echarts#3947]
这个例子：http://echarts.baidu.com/demo.html#scatter-weight，我加了如下代码：
visualMap: [
                        {
                            show: false,
                            inRange: {
                                color: (function () {
                                    var colors = ['#26A4FB', '#66c457', '#FF6158', '#965100', '#d87a80',
                                        '#8d98b3', '#B8B815', '#97b552', '#95706d', '#8F22AA',
                                        '#07a2a4', '#9a7fd1', '#588dd5', '#1B93B1', '#c05050',
                                        '#59678c', '#c9ab00', '#7eb00a', '#6f5553', '#c14089'];
                                    return colors.concat(colors);
                                })()
                            }
                        }
                    ],
我想让，散点图每个点一种颜色，或是点的颜色按照颜色组来循环。
有什么参数能做到吗？
谢谢，辛苦

**Comment by pissang** [comment]
[itemStyle.normal.color](http://echarts.baidu.com/option.html#series-scatter.itemStyle.normal.color) 可以是回调函数，每个数据也可以定义 itemStyle.normal.color
