### ISSUE TITLE
雷达图的 指标的 触发事件还是无效

### ISSUE THREAD

**Issue by x4storm** [ecomfe/echarts#3949]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/3934

**Comment by EnhengBenben** [comment]
解决了说一下
