### ISSUE TITLE
关系图中当links的target和source设置为node的name时，无法显示node之间的连线

### ISSUE THREAD

**Issue by fanjie81** [ecomfe/echarts#3951]
#### 问题简述 (One-line summary)
关系图中当links的target和source设置为node的name时，无法显示node之间的连线
{"categories":[],"links":[{"source":"4218514636","target":"1","value":0}],"nodes":[{"name":"4218514636","seq":0,"value":0},{"name":"1","seq":0,"value":0}]}
此时节点4218514636和1之间的连接线无法显示。
需要改为
{"categories":[],"links":[{"source":0,"target":1,"value":0}],"nodes":[{"name":"4218514636","seq":0,"value":0},{"name":"1","seq":0,"value":0}]}

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.3
+ 浏览器类型和版本 (Browser version): chrome  51.0.2704.106 (64-bit)
+ 操作系统类型和版本 (OS Version): windows 7 企业版 64bit

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by wu11106** [comment]
您们好！（试想！只是试试想想，不要见笑）
刚刚您们给我一个购物网站http://palletidea.com/，他们的“创新思路DIY的制作托盘家具”。使我想到盘活存货的更大思路……
近期过来缅甸找门路的中国工商人士，没有以前的工商贸易推销，而是厂家业主。都是建材行业、电视接收设备、各种家具等等的厂家。以前除了中国饱和产品，外国还有市场的出路，比如充电宝厂家才出国推销，一般用途广泛的产品生产商，很少千万里远行。
厂家是来缅甸找出路，想把厂设在这里，证明中国最基础的产能经济受到空前的困境，“世界工厂”也要世界闯闯！
他们来到，大部分都回去了，惊吓乌鸦一般黑，难道高度依赖中国的东南亚会好吗？不要说亚太地区，就是欧洲也好不到哪里去？
正是这样，原材料商家、厂家、批发商、贸易伙伴、销售方、甚至是机构用户和家庭用户，都有囤积货物，或者半加工材料的囤积，以前购买的产品，由于市场变坏，只能原版连包装盒封存。
厂家、商家等贸易公司，都有一个通病，缺乏资金，盼望囤积货物出手，如果欠财务公司或者银行借贷的话，商家只有大幅度降价出手，别无选择。
市场各种物资的需求者，存在着缺少资金购买，在计划购买物品时，能便宜就购买便宜的品种。
囤积物品出手，和贪婪低价收购的现象，就像经济飞速发展时期，也照常存在。
囤积货物多！资金周转少！这二个是经济低迷的必然出现的双胞胎，现在双胞胎横空出世！问题是双胞胎由一个父亲二个母亲生下，互不相认。需求者找不到方向（也不知道），出售者同样找不到门路。
网购市场有“二手车交易”“二手家电家具”“二手房出售”等等低价的成交网站。
互联网没有倒闭物流，如没有“二手新娘出售”一样的。
互联网一个创新的互相携手获胜的：【倒闭走路厂家货物，二手价格一手新娘般的产品】
夸地区的谷歌加互相携手平台，专供濒临绝境商家清仓，专门惠及创业者缺乏资金。
谷歌加在经济低谷之际，盘活市场资金周转，拉动沉积物资弥补失调社会。
谷歌加---做福人民！做福社会！做福工商惠千家！

YINGHUI WU
wu11106025@gmail.com


2016年8月29日星期一，fanjie81 <notifications@github.com> 写道：

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>) Add cleanup
> rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DhhZh5SkwHAh%252Fv66LGVBsdoNbFaYgZ3xjz3eNrnSb9NA%253D%26token%3DOLFQ5kYYRPB7oGdXB3W%252FxynSWCaRlRGbeT4GanZ7zV1pKMzpJYQShA2NALeTetcSzGfDHzgpH3Y%252BtcX2DC8WgtNB0dcTMUc956B0vAy3TcDmg7q1UFJh6orpMYNOLKu2M7xp1QcgLd8fbS2OggDGeA%253D%253D&tc_serial=26596987497&tc_rand=2124059455&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=26596987497&tc_rand=2124059455&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>
