### ISSUE TITLE
echarts3中legend的selected变量name问题

### ISSUE THREAD

**Issue by Qziyang** [ecomfe/echarts#3960]
#### 问题简述 (One-line summary)
echarts3中legend.selected图例选中状态表的name名无法使用函数中的形参变量吗？

详细代码如图，将变量名改成name名的字符串格式可以使用，但是为了复用性写了个方法，这样传进去的参数并不会被识别为相应的字符串。
求解是写的姿势有问题还是目前无法这么做。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts3.0
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 可能哪里有问题 (What went wrong)
legend的selected无法使用形参做name

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/21325608/18074414/f7961530-6e9e-11e6-82a5-f0e671e550f5.png)

**Comment by pissang** [comment]
看你这个函数写的姿势了啊，跟 echarts 没关系

**Comment by Qziyang** [comment]
那如果要实现这种效果必须要使用固定的字符串来做name吗 
没有方法来将selected放到legend.data里面吗
