### ISSUE TITLE
使用getDataUrl()方法导出图片能否忽略工具栏

### ISSUE THREAD

**Issue by zhangjunxia** [ecomfe/echarts#3962]
#### 问题简述 (One-line summary)

使用getDataUrl()方法导出图片能否忽略工具栏

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2
+ 浏览器类型和版本 (Browser version):IE9+
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
忽略工具栏

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
```js
getDataURL({
  excludeComponents: ['toolbox']
})
```
