### ISSUE TITLE
迁徙图设置出发地点lines是否能够像到达地点的圆圈显示出来。

### ISSUE THREAD

**Issue by lengziyu** [ecomfe/echarts#3964]
#### 问题简述 (One-line summary)
迁徙图 lines 的出发地点圆圈是否能够像到达地点那样显示出来？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):v3
+ 浏览器类型和版本 (Browser version):all
+ 操作系统类型和版本 (OS Version):all

#### 重现步骤 (Steps to reproduce)
出发地点设置：type: 'lines'
到达地点设置：type: 'effectScatter'
[geo-lines](http://echarts.baidu.com/demo.html#geo-lines)

#### 期望结果 (Expected behaviour)
出发地点圆圈能够像到达地点那样显示出来

#### 可能哪里有问题 (What went wrong)
感觉是我需要type 为 lines类型的同时，也可以设置effectScatter里面的某些属性？
朋友说可以设置markPoint属性，但是我设置了无效。姿势不对？

#### ECharts配置项 (ECharts option)
```javascript
option = {
  backgroundColor: '#404a59',
  title : {
      text: '北京到广州',
      subtext: '可否显示北京这个出发地点？',
      left: 'center',
      textStyle : {
          color: '#fff'
      }
  },
  tooltip : {
      trigger: 'item'
  },
  legend: {
      orient: 'vertical',
      top: 'bottom',
      left: 'right',
      data:['广州 Top10'],
      textStyle: {
          color: '#fff'
      },
      selectedMode: 'single'
  },
  geo: {
      map: 'china',
      //鼠标移入是否显示省份
      label: {
          emphasis: {
              show: true
          }
      },
      roam: true,
      itemStyle: {
          normal: {
              areaColor: '#323c48',
              borderColor: '#404a59'
          },
          emphasis: {
              areaColor: '#2a333d'
          }
      }
  }

```

#### 其他信息 (Other comments)

[Codepen-demo](http://codepen.io/lengziyu/pen/xEKGPq)

**Comment by pissang** [comment]
这个点是单独一个 `scatter` 或者 `effectScatter` 系列显示的，示例中只显示了终点，你可以根据自己需要显示起点

**Comment by lengziyu** [comment]
明白了，具体怎么加呢？
```
      data: item[1].map(function (dataItem, index) {
          return {
              //出发地点
              // name: dataItem[0].name,
              // value: geoCoordMap[dataItem[0].name].concat([dataItem[0].value])
              
              // 目的地
              name: dataItem[1].name,
              value: geoCoordMap[dataItem[1].name].concat([dataItem[1].value])
          };
      })
```

上面【目的地】会覆盖【出发地点】，怎么让两者共存呢？还是有另外的方法？

**Comment by lengziyu** [comment]
谢谢~OK了，不过出现其他名称重叠问题，我再看看api，如果解决不了再提下issues，感谢您的回复。

**Comment by yangguoe** [comment]
您好，请问解决了吗？
