### ISSUE TITLE
3.x版本中的世界地图把俄罗斯分成两块，能不能像之前版本一样，如果是要更换geo文件的话，请问那边能下到

### ISSUE THREAD

**Issue by ZeroBinbin** [ecomfe/echarts#3966]
echarts-3.1.9[http://echarts.baidu.com/demo.html#map-world-dataRange](url)
echarts-2.2.7 [http://echarts.baidu.com/echarts2/doc/example/map4.html](url)
我想要的就是下面那个地图

**Comment by realeve** [comment]
[http://echarts.baidu.com/demo.html#map-usa](http://echarts.baidu.com/demo.html#map-usa)

**Comment by ZeroBinbin** [comment]
要整体移动坐标的话怎么写

**Comment by fuxiao82** [comment]
const regisOption: RegisOption = {
    type: 'FeatureCollection',
    crs,
    features: world.map((item) => {
          if (item.properties.name !== '俄罗斯') {
            return item
          }
          item.geometry.coordinates.forEach((detail) => {
            detail[0].forEach((itemDetail) => {
              //地图坐标需要转换，经过分析，经度小于-20度的加上360就可以了！
              if (itemDetail[0] < -20) {
                itemDetail[0] += 360
              }
            })
          })
          return item
        })
  }


world like:
[{
  "geometry": {
      "type": "Polygon",
      "coordinates":[...]
  },
  "properties": {
      "name": "俄罗斯",
      "childNum": 1
  }
},{},{},...]
