### ISSUE TITLE
求助echarts.min.js:10 Uncaught RangeError: toFixed() digits argument must be between 0 and 20

### ISSUE THREAD

**Issue by jingling0101** [ecomfe/echarts#3969]
#### 问题简述 (One-line summary)

在本地windows 上正常 
**上线出现
echarts.min.js:10 Uncaught RangeError: toFixed() digits argument must be between 0 and 20**  这样的报错
).toFixed(e)},n.asc=function(t){return t.sort(function(t,e){return t-e}),t},n.getPrecision=function(t){if(t=+t,isNaN(t))return 0;for

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  http://cdn.bootcss.com/echarts/3.2.3/echarts.min.js
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version): 本地win7  线上服务器linux

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
 function setOptionDate(dataNew,categoryDat,seriesNew) {
            option = {
                title: {
                    text: '定单多日堆叠图'
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: dataNew
                },
                toolbox: {
                    show: true,
                    feature: {
                        dataZoom: {
                            yAxisIndex: 'none'
                        },
                        dataView: {readOnly: false},
                        magicType: {type: ['line', 'bar']},
                        restore: {},
                        saveAsImage: {}
                    }
                },
                grid: {
                    left: '10%',
                    right: '10%',
                    bottom: '12%',
                    containLabel: true
                },
                xAxis: [
                    {
                        type: 'category',
                        boundaryGap: false,
                        data: categoryDat
                    }
                ],
                yAxis: [
                    {
                        type: 'value'
                    }
                ],
                dataZoom: [
                    {
                        show: true,
                        type: 'slider',
                        y: '90%',
                        handleSize: 8,
                        start: 90,
                        end: 100
                    }
                ],
                series: seriesNew
            };
        }


```

#### 其他信息 (Other comments)

http://a1.qpic.cn/psb?/V10H5PD21MgNMm/CDKCyYmDEegJ1Lk8X5.zeD1mte5Z8wD.XBw3Hr9Rwe4!/b/dAIBAAAAAAAA&bo=MgJ8AgAAAAADB2w!&rf=viewer_4

http://a2.qpic.cn/psb?/V10H5PD21MgNMm/kmH1jtRH7pS24GhCBGy3QQTILSJzM7iRIcH8B74iU4A!/b/dKwAAAAAAAAA&bo=KQLCAgAAAAADB8k!&rf=viewer_4

Object {categoryData: Array[1196], values: Array[1196]}categoryData: Array[1196][0 … 99][100 … 199][200 … 299][300 … 399][400 … 499][500 … 599][600 … 699][700 … 799][800 … 899][900 … 999][1000 … 1099][1100 … 1195]length: 1196__proto__: Array[0]values: Array[1196][0 … 99]0: Array[2]1: Array[2]2: Array[2]3: Array[2]4: Array[2]5: Array[2]6: Array[2]7: Array[2]8: Array[2]9: Array[2]10: Array[2]11: Array[2]12: Array[2]13: Array[2]14: Array[2]15: Array[2]16: Array[2]17: Array[2]18: Array[2]19: Array[2]20: Array[2]21: Array[2]22: Array[2]23: Array[2]24: Array[2]25: Array[2]26: Array[2]27: Array[2]28: Array[2]29: Array[2]30: Array[2]31: Array[2]32: Array[2]33: Array[2]34: Array[2]35: Array[2]36: Array[2]37: Array[2]38: Array[2]39: Array[2]40: Array[2]41: Array[2]42: Array[2]43: Array[2]44: Array[2]45: Array[2]46: Array[2]47: Array[2]48: Array[2]49: Array[2]50: Array[2]51: Array[2]52: Array[2]53: Array[2]54: Array[2]55: Array[2]56: Array[2]57: Array[2]58: Array[2]59: Array[2]60: Array[2]61: Array[2]62: Array[2]63: Array[2]64: Array[2]65: Array[2]66: Array[2]67: Array[2]68: Array[2]69: Array[2]70: Array[2]71: Array[2]72: Array[2]73: Array[2]74: Array[2]75: Array[2]76: Array[2]77: Array[2]78: Array[2]79: Array[2]80: Array[2]81: Array[2]82: Array[2]83: Array[2]84: Array[2]85: Array[2]86: Array[2]87: Array[2]88: Array[2]89: Array[2]90: Array[2]91: Array[2]92: Array[2]93: Array[2]94: Array[2]95: Array[2]96: Array[2]97: Array[2]98: Array[2]99: Array[2][100 … 199][200 … 299][300 … 399][400 … 499][500 … 599][600 … 699][700 … 799][800 … 899][900 … 999][1000 … 1099][1100 … 1195]length: 1196__proto__: Array[0]__proto__: Object
cat_order_trend_daily_stack:211 Object {data: Array[2]}
cat_order_trend_daily_stack:212 ["15:00", "15:01", "15:02", "15:03", "15:04", "15:05", "15:06", "15:07", "15:08", "15:09", "15:10", "15:11", "15:12", "15:13", "15:14", "15:15", "15:16", "15:17", "15:18", "15:19", "15:20", "15:21", "15:22", "15:23", "15:24", "15:25", "15:26", "15:27", "15:28", "15:29", "15:30", "15:31", "15:32", "15:33", "15:34", "15:35", "15:36", "15:37", "15:38", "15:39", "15:40", "15:41", "15:42", "15:43", "15:44", "15:45", "15:46", "15:47", "15:48", "15:49", "15:50", "15:51", "15:52", "15:53", "15:54", "15:55", "15:56", "15:57", "15:58", "15:59", "16:00", "16:01", "16:02", "16:03", "16:04", "16:05", "16:06", "16:07", "16:08", "16:09", "16:10", "16:11", "16:12", "16:13", "16:14", "16:15", "16:16", "16:17", "16:18", "16:19", "16:20", "16:21", "16:22", "16:23", "16:24", "16:25", "16:26", "16:27", "16:28", "16:29", "16:30", "16:31", "16:32", "16:33", "16:34", "16:35", "16:36", "16:37", "16:38", "16:39"…]
cat_order_trend_daily_stack:213 [Object, Object]0: ObjectareaStyle: Objectdata: Array[1196]name: "2016-08-30"stack: "总量"type: "line"__proto__: Object1: ObjectareaStyle: Objectdata: Array[1196]label: Objectname: "2016-08-31"stack: "总量"type: "line"__proto__: Objectlength: 2__proto__: Array[0]

**Comment by pissang** [comment]
具体配置项？

**Comment by jingling0101** [comment]
function setOptionDate(dataNew,categoryDat,seriesNew) {
            option = {
                title: {
                    text: '定单多日堆叠图'
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: dataNew
                },
                toolbox: {
                    show: true,
                    feature: {
                        dataZoom: {
                            yAxisIndex: 'none'
                        },
                        dataView: {readOnly: false},
                        magicType: {type: ['line', 'bar']},
                        restore: {},
                        saveAsImage: {}
                    }
                },
                grid: {
                    left: '10%',
                    right: '10%',
                    bottom: '12%',
                    containLabel: true
                },
                xAxis: [
                    {
                        type: 'category',
                        boundaryGap: false,
                        data: categoryDat
                    }
                ],
                yAxis: [
                    {
                        type: 'value'
                    }
                ],
                dataZoom: [
                    {
                        show: true,
                        type: 'slider',
                        y: '90%',
                        handleSize: 8,
                        start: 90,
                        end: 100
                    }
                ],
                series: seriesNew
            };
        }

**Comment by jingling0101** [comment]
解决了。  数据传入格式不对

**Comment by wind108369** [comment]
这里确实会有这个问题，代码niceTicks方法给精度加了个2，如果默认传入的数据没有做过fix限定小数位，这里加2就超过20了，系统就会报错。这里加个最大限制就没问题了。

对于echrts使用者，这里的解决方法就是手动加一个逻辑，限制一下小数位数
