### ISSUE TITLE
热力图、散点图不显示全？

### ISSUE THREAD

**Issue by zombieJ** [ecomfe/echarts#3972]
#### 问题简述 (One-line summary)
热力图/散点图无论有没有设置x/y axis scale为true/false的情况下，如果部分点没有数据，热力图/散点图会被缩放掉。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.2
+ 浏览器类型和版本 (Browser version):chrome latest
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.打开http://echarts.baidu.com/demo.html#heatmap-cartesian
2.将series的data改为`[[0,0,5]]`

#### 期望结果 (Expected behaviour)
不缩放

#### 可能哪里有问题 (What went wrong)
x/y axis scale 属性在type为scatter / heatmap时内置永远为true？

#### ECharts配置项 (ECharts option)
见上方，直接修改官方实例即可。

**Comment by pissang** [comment]
只有有数值的类目才会显示出来
