### ISSUE TITLE
移动应用，手机垂直放置，echarts横屏渲染

### ISSUE THREAD

**Issue by ReasonYuan** [ecomfe/echarts#3973]
#### 问题简述 (One-line summary)
关于横屏时echarts的显示问题

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): 移动app->webView
+ 操作系统类型和版本 (OS Version):  iOS and android

#### 重现步骤 (Steps to reproduce)
1. 移动应用限制竖屏，手机垂直放置；
2. 点击按钮跳转到echarts页面；
3. 需要旋转webview页面才能让echarts横屏渲染。

#### 期望结果 (Expected behaviour)
手机仍然垂直放置，也不需要旋转app页面，但echarts可以横屏渲染（即x轴在高上，y轴在宽上）。

#### 可能哪里有问题 (What went wrong)
不知道能否自定义echarts的x轴，y轴为移动手机的哪一边，或者自定义坐标的原点。

#### ECharts配置项 (ECharts option)

```javascript
option = {
     ....
}
```

#### 其他信息 (Other comments)

<img width="272" alt="f56ac10b-50a6-4bd6-901b-49063dcabbbc" src="https://cloud.githubusercontent.com/assets/5669911/18091453/4125bf00-6efb-11e6-8f8d-dcb05338e957.png">

手机垂直放置，echarts可以横屏渲染。

**Comment by pissang** [comment]
这跟 echarts 有啥关系

**Comment by wu11106** [comment]
我在维基是用粤语写的

2016年8月30日星期二，reason <notifications@github.com> 写道：
