### ISSUE TITLE
能否自定义坐标位置

### ISSUE THREAD

**Issue by ReasonYuan** [ecomfe/echarts#3974]
即使可以自定义坐标原点以及x轴，y轴的位置，
通常如下：
<img width="358" alt="71bca4e5-4807-4a58-8a9e-9f9f4cfdf043" src="https://cloud.githubusercontent.com/assets/5669911/18113557/73373c04-6f63-11e6-9749-bb48ef22195c.png">

希望在不旋转手机的情况下改变x轴，y轴的位置，使得图表可以水平渲染，如下图：
<img width="340" alt="606b896b-a018-46a3-9fec-3f5041d4a967" src="https://cloud.githubusercontent.com/assets/5669911/18113571/9813ac42-6f63-11e6-9880-e9d59dacf783.png">

**Comment by wqf1992wqf** [comment]
我遇到了这样的问题，利用rotate旋转之后touch的x，y坐标就不太正确了

**Comment by 100pah** [comment]
> 利用rotate旋转之后touch的x，y坐标就不太正确了
假如你说的是 css-transfrom 的 rotate，3.3.1 中改过这个问题。
