### ISSUE TITLE
地图geo文件(js, json)缺少台湾

### ISSUE THREAD

**Issue by nvrdawn** [ecomfe/echarts#3979]
#### 问题简述 (One-line summary)

中国的geo信息缺少台湾

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by ppker** [comment]
Even less Taiwan

**Comment by occultskyrong** [comment]
![image](https://cloud.githubusercontent.com/assets/8370006/18190360/e8c31bd6-70f4-11e6-8ea1-1a676bde5938.png)
....我也是很无奈啊
