### ISSUE TITLE
toolbox是否支持自定义工具

### ISSUE THREAD

**Issue by DarkRake** [ecomfe/echarts#3993]
#### 问题简述 (One-line summary)
我想把toolbox中的下载的那个按钮，替换一个，并且点击事件自定义，是否支持呢？
我们项目上，需要针对仪表盘，管理层如果觉得数据有问题，需要自动把图片发送到指定的邮件里面去，但是我现在在toolbox里面缺少一个触发位置。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
支持
```js
feature: {
    myTool2: {
        show: true,
        title: '自定义扩展方法2',
        icon: 'image://http://echarts.baidu.com/images/favicon.png',
        onclick: function (){
            alert('myToolHandler2')
        }
    }
}
```
