### ISSUE TITLE
柱状图设置渐变色时鼠标提示中的小圆点无法显示

### ISSUE THREAD

**Issue by stevobm** [ecomfe/echarts#3994]
#### 问题简述 (One-line summary)

柱状图设置渐变色时提示框中的小圆点无法显示
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.3
- 浏览器类型和版本 (Browser version):Chrome 48.0.2547.0
- 操作系统类型和版本 (OS Version):Windows 7 64bit
#### 重现步骤 (Steps to reproduce)

1.设置option中的itemStyle为渐变色
2.移上鼠标，提示框中的小圆点消失
#### 期望结果 (Expected behaviour)

柱状图设置渐变色时提示框中的小圆点也呈现为渐变色，或者能够提供单独指定小圆点样式的api
#### 可能哪里有问题 (What went wrong)

柱状图颜色设置选项与提示框(tooltip)的颜色设置选项正好都是itemStyle，没有像折线图(颜色设置选项是lineStyle)那样错开，因此只能一起设置。当柱状图设置渐变时，提示框却并不支持，因此出现无法显示的情况。
#### ECharts配置项 (ECharts option)

``` javascript

option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    itemStyle:{
        normal: {
            color:new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                offset: 0,
                color: 'rgb(141,181,96)',
            }, {
                offset: 1,
                color: 'rgb(45,170,197)',
            }]),
            opacity: 0.8
        }
    },
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220]
        }
    ]
};

```
#### 其他信息 (Other comments)

![bug](https://cloud.githubusercontent.com/assets/5198256/18162625/bc22a9ce-7069-11e6-8d95-837239efbf7c.jpg)

**Comment by pissang** [comment]
嗯，小圆点是用 dom 画的，暂时不支持渐变色

**Comment by stevobm** [comment]
小圆点没必要画成渐变的，只需要取柱状图渐变色的底部颜色进行绘制即可（像渐变折线图那样），因为这总比现在完全显示不出来好。

**Comment by stevobm** [comment]
小圆点没必要画成渐变的，只需要取柱状图渐变色的底部颜色进行绘制即可（像渐变折线图那样），因为这总比现在完全显示不出来好。

**Comment by amazing416** [comment]
还没解决
