### ISSUE TITLE
echarts-v3.2.1中【type=map】时，省、市名称偏移出该省、市

### ISSUE THREAD

**Issue by occultskyrong** [ecomfe/echarts#3997]
#### 问题简述 (One-line summary)
1.  原echarts-v2版本中，省下市的名称会正合适的显示在市区域的中间，[全国34个省市自治区](http://echarts.baidu.com/echarts2/doc/example/map3.html#)，如下图所示：
![image](https://cloud.githubusercontent.com/assets/8370006/18189943/8da0454c-70f1-11e6-96f1-ace8883c7b14.png)
2. 在v3.2.1中，下载jiangsu.json后，包括[在线预览](http://echarts.baidu.com/demo.html#map-province)，展示的省市有部分已经超出所属位置，而该市的空白空间还很大，如下图所示：
![image](https://cloud.githubusercontent.com/assets/8370006/18190001/dd7fac24-70f1-11e6-9946-2df3b41378a1.png)
3. 是否可以进行省市名称显示时进行微调？未发现有相关参数。
4. 另v2版本可以给某市增加markpoint，类似于[怎么才能把标有数字的地点名称在地图上显示出来](http://www.oschina.net/question/2003075_166190)
v3版本的Markpoint只提供了基于坐标和(x,y)的设置。。莫非要我一个城市一个城市的去写位置？
还有label中未提供formatter配置项，如何直接显示城市的数据，而不是需要鼠标动作？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):`3.2.1`
+ 浏览器类型和版本 (Browser version):`chrome`
+ 操作系统类型和版本 (OS Version):`windows 7`

#### 重现步骤 (Steps to reproduce)
见上[问题描述]

#### 期望结果 (Expected behaviour)
1. 市名称可恰当的存在市中心位置，市略小时可超出，但应相对居中。
2. 直接显示某市的数据，而不是鼠标放上才显示。

#### 可能哪里有问题 (What went wrong)
不知道。。

#### ECharts配置项 (ECharts option)

# 以下代码可直接运行
```javascript

(function() {

    $.get('vendors/echarts/map/json/province/jiangsu.json', function (geoJson) {

        // myChart.hideLoading();

        echarts.registerMap('jiangsu', geoJson);

        myChart.setOption({
                title: {
                    text: '江苏省'
                }, tooltip: {
                    trigger: 'item',
                    formatter: '{b}:<br>{a}:{c}'
                }, dataRange: {
                    min: 0,
                    max: 1000,
                    color: ['red', 'yellow'],
                    text: ['高', '低'],           // 文本，默认为数值文本
                    calculable: true
                }, series: [{
                    name: 'GMV'
                    , type: 'map'
                    , map: 'jiangsu'
                    , label: {
                        normal: {
                            show: true
                            ,textStyle:{
                                fontSize:12
                                ,fontFamily:'Micro YaHei'
                            }
                        },emphasis:{
                            show: true
                            ,textStyle:{
                                fontSize:13
                                ,fontFamily:'Micro YaHei'
                            }
                        }
                    }, data: [
                        {name: '南京市', value: 125}
                    ], markPoint: {
                        label: {
                            normal: {
                                show: true
                                ,formatter:"{c}"
                            }
                        }, data: [//data数据每个城市都有，一个一个去定义xy?
                            {name: '南京市', x: 100, y: 100,value:'测试'}
                            ,{name: '如何把这个游标放在城市的位置', x: 200, y: 200,value:'测试'}
                        ]
                    }
                }]
            });
    });
}());
```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/8370006/18190242/c6889772-70f3-11e6-8c88-548100fae0c9.png)

**Comment by philoyang** [comment]
同求啊！！！关于label显示数据我知道可以加formatter把name和value都显示出来，但是不支持br等html标签。另外我是想要展示两个数据在label里面……

**Comment by occultskyrong** [comment]
已解决。

1、可修正json文件中对应xy信息，将城市名称居中
2、使用`scatter`，代码如下
```
 {
                    name: '数据'
                    , type: 'scatter'
                    , coordinateSystem: 'geo'
                    , zlevel: 6
                    , z: 6
                    , animation: false
                    , data: data['scatter']
                    , symbolSize: 85
                    , label: {
                        normal: {
                            formatter: function (params) {
                                return params['value'][2] + '万\n' + params['value'][3] + '家';
                            }, position: 'inside'
                            , show: true
                            , textStyle: {
                                color: '#fff'
                                , fontSize: 13
                                , fontStyle: 1 //fixme 一个bug，导致行间距扩大
                            }
                        }
                    }, itemStyle: {
                        normal: {
                            color: '#0cf'
                        }
                    }
                }
```
3、发现一个bug，因为[`textStyle`](http://echarts.baidu.com/option.html#series-scatter.label.normal.textStyle)中无法调整行间距，我设置了一个错误的数值，导致了`行间距`扩大了。。。。

**Comment by occultskyrong** [comment]
@philoyang 他这个因为是基于canvas的，所以本身不能可能支持html标记。。
但是可以用`\n`来进行换行，同时`formatter`可以写回调函数，里面有参数来进行多数据。
当然，抛入数据的时候你需要用数组的数组抛入数据`[[1,2,3],[3,4,5]]`，一次是x、y、数据0、数据1、数据……
just like this
```
[{"name":"常州市","value":[119.95,31.79,0.27,2],"symbol":"pin"},{"name":"苏州市","value":[120.92,31.32,30.12,1],"symbol":"pin"}]
```
然后`formatter`中就可以使用回调的params中value来进行选取，具体看上边的代码。

**Comment by occultskyrong** [comment]
@philoyang 也可以直接把`formatter`回调函数里面`args`全部打出来看看，[echarts官方说明中formatter貌似失效了](http://echarts.baidu.com/option.html#series-scatter.label.normal.formatter)

**Comment by occultskyrong** [comment]
我close issue了，有问题可以跟issue，力所能及的回答。

for 开源~

**Comment by chen20050124** [comment]
请问最近使用 echarts 3   世界地图，我通过使用nameMap 改成中文后 ， 国家名字 发生偏移了。怎么解决呢？

**Comment by occultskyrong** [comment]
@chen20050124 应该是名字超长了。。改一下国家的中心经纬度试试。。上边有说明。。我城市是这么调整的。。

**Comment by occultskyrong** [comment]
@chen20050124 不对。。应该是有语言包的。。国际化。。不需要你手动去改。。

**Comment by occultskyrong** [comment]
@chen20050124 http://echarts.baidu.com/echarts2/doc/example/map5.html 看下这个

**Comment by AsceticBoy** [comment]
请问最近使用 echarts 3 世界地图，我通过使用nameMap 改成中文后 ， 国家名字 发生偏移了。怎么解决呢？@ghost,，我也遇到一样的问题你是怎么解决的

**Comment by 7neves** [comment]
通过自行调整label.position可以进行调整，另外可以结合调整下geojson里面的cp坐标位置来更精确的调整
