### ISSUE TITLE
省地图不能使用effectScatter效果

### ISSUE THREAD

**Issue by hnxwl** [ecomfe/echarts#3999]
#### 问题简述 (One-line summary)
我调用省地图是这样调用的
在series 里增加type: 'map', map: '海南' 两个值
而effectScatter中的coordinateSystem只有geo 这种，是不是series 里的 type:map 不能使用effectScatter，而geo类型的地图才能使用effectScatter呢？但是我geo 没能调用海南省地图，只能调用china 地图，请麻烦解答一下好吗？ 
        

 {
            name: 'Top 5',
            type: 'effectScatter',
            coordinateSystem: 'geo',
            data: [
                {
                    name:'海口市',
                    value:[110.35,20.02,279]
                }
                ],
            symbolSize: function (val) {
                return val[2] / 10;
            },
            showEffectOn: 'render',
            rippleEffect: {
                brushType: 'stroke'
            },
            hoverAnimation: true,
            label: {
                normal: {
                    formatter: '{b}',
                    position: 'right',
                    show: true
                }
            },
            itemStyle: {
                normal: {
                    color: '#f4e925',
                    shadowBlur: 10,
                    shadowColor: '#333'
                }
            },
            zlevel: 1
        }

我设置 effectScatter的data 为这个，没有任何用啊，我看事例是根据坐标输出effectScatter 效果，以下的data设置在geo china地图上面是有显示的，而在series里type:map 这种图标不能显示
data: [
                {
                    name:'海口市',
                    value:[110.35,20.02,279]
                }
                ],
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {
        series: [ {
                    type: 'map',
                     map: '海南',
                    label: {
        normal:{
                show: true,
                textStyle:{
            color:'#1b1b1b'
        }
            },
            emphasis: {
                show: false
            }
        },
                     data:[
     
     {name: '海口', value: 279}
],
                    center:[109.7,19.3],
                    zoom:8,
                    itemStyle: {
                    	
         normal:{areaColor:'#ffffff',
         borderColor:'rgba(100,149,237,1)',
                    borderWidth:0.5},
          
                   
					label:{show:true}
        }

                },
 {
            name: 'Top 5',
            type: 'effectScatter',
            coordinateSystem: 'geo',
            data: [
                {
                    name:'海口市',
                    value:[110.35,20.02,279]
                }
                ],
            symbolSize: function (val) {
                return val[2] / 10;
            },
            showEffectOn: 'render',
            rippleEffect: {
                brushType: 'stroke'
            },
            hoverAnimation: true,
            label: {
                normal: {
                    formatter: '{b}',
                    position: 'right',
                    show: true
                }
            },
            itemStyle: {
                normal: {
                    color: '#f4e925',
                    shadowBlur: 10,
                    shadowColor: '#333'
                }
            },
            zlevel: 1
        }
]
}

```

**Comment by pissang** [comment]
可以的
