### ISSUE TITLE
3.2.3版本多图联动效果bug

### ISSUE THREAD

**Issue by xsh0616** [ecomfe/echarts#4000]
#### 问题简述 (One-line summary)
在使用最新版本的(3.2.3)，用到了多图联动功能，发现报错myChart connect is not a function.
调试了很久没结果，然后回退到2.2.7版本后正常

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.3
+ 浏览器类型和版本 (Browser version):Chrome 52.0.2743.82 m (64-bit)
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

代码用的是官网的sample

```


#### 其他信息 (Other comments)
<!-- 例如，截图或线上实例 (JSFiddle/JSBin/Codepen) (For example: Screenshot or Online demo) -->

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echarts.connect
