### ISSUE TITLE
地图：地图现在只有世界地图、全国地图、各省地图，能添加一个俄罗斯地图吗？或者给个其他国家地图的制作方法

### ISSUE THREAD

**Issue by yunqingChang** [ecomfe/echarts#4007]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/pissang/starbucks/tree/gh-pages/json
