### ISSUE TITLE
使用自定义GeoJSON时渲染Chrome问题

### ISSUE THREAD

**Issue by ektx** [ecomfe/echarts#4019]
#### 问题简述 (One-line summary)
使用自己定义的数据时，只有chrome上部分数据无法正常显示颜色，在FireFox，IE和Safari(Mac)上都正常显示（如下图）
 ![正常](https://raw.githubusercontent.com/ektx/Canvas/master/Echarts/Maps/ErrBox/%E8%87%AA%E5%AE%9A%E4%B9%89GeoJSON%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%98/001.png)
__IE && FirFox 正常状况__

 ![非正常](https://raw.githubusercontent.com/ektx/Canvas/master/Echarts/Maps/ErrBox/%E8%87%AA%E5%AE%9A%E4%B9%89GeoJSON%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%98/002.png)
__FireFox 和Chrome对比， Chrome下非正常状况__

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 最新版本 
+ 浏览器类型和版本 (Browser version): Chrome 53.0.2785.89 (正式版本) （64 位）
+ 操作系统类型和版本 (OS Version): Win7, Win10, Mac OS X El Capitan

#### 重现步骤 (Steps to reproduce)
1. 您可在 [香港18区人口密度](http://echarts.baidu.com/demo.html#map-HK) 示例中添加以下数据 
2. 我的示例 [数据](https://raw.githubusercontent.com/ektx/Canvas/master/Echarts/Maps/ErrBox/%E8%87%AA%E5%AE%9A%E4%B9%89GeoJSON%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%98/myJson.json)  
3..将示例中的数据全替换为我的数据

#### 期望结果 (Expected behaviour)
都可以正常显示颜色

#### 可能哪里有问题 (What went wrong)
可能是绘制的问题，个人将数据提取，使用Canvas来绘制时，json内容可以在Chrome下正常绘制

#### ECharts配置项 (ECharts option)

```javascript
// 参考重现步骤
option = {

}

```

**Comment by weiletian28** [comment]
你这个问题和我提的可能是同一个问题：
https://github.com/ecomfe/echarts/issues/4017

**Comment by pissang** [comment]
@weiletian28 嗯，这个我先关闭了，统一在那个 issue 下回复
