### ISSUE TITLE
关于svg图文字颜色

### ISSUE THREAD

**Issue by cainooo** [ecomfe/echarts#4026]
#### 问题简述 (One-line summary)
在echart中导入svg图，svg图里的text标签无法使用，只能通过使用rect标签的name属性添加文字，但是文字无法改变颜色。想请问一下，能不能在svg里面使用text标签，或者修改rect标签name属性里面文字的颜色？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):      ECharts2.27
+ 浏览器类型和版本 (Browser version):      chorme/firefox
+ 操作系统类型和版本 (OS Version):       windows10/linux/windows8

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
svg里面的text标签能够在页面里显示，
或者
svg里rect标签name属性里的文字可以修改颜色

#### 可能哪里有问题 (What went wrong)
可能ECharts对svg的支持不是很好

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
2 的 svg 不支持 text 标签
