### ISSUE TITLE
K线图的成交量部分，itemstyle读取不了series么？

### ISSUE THREAD

**Issue by firstsko** [ecomfe/echarts#4027]
成交量只能一个颜色，如果需要像蜡烛图一样根据涨跌改变颜色，似乎无法设置
       name: '成交量',
              type: 'bar',
              xAxisIndex: 1,
              yAxisIndex: 1,
              data: data.volumns,
              itemStyle: {
                  normal: {
                      color:data.color,
                      //color0:'#1AB667',
                      borderColor: null,
                      borderColor0: null
                  }
              },

**Comment by pissang** [comment]
可以设置 data 里每一项的 itemStyle
