### ISSUE TITLE
一个图表中的两个Y轴，能否把其中一根轴和其图表高度变成原高度的1/4？

### ISSUE THREAD

**Issue by Nataila** [ecomfe/echarts#4032]
例如： http://echarts.baidu.com/demo.html#mix-line-bar
我想把左边的轴和其数据显示出来的图表高度变成原来的四分之一，或者其他高度，有什么解决办法吗

**Comment by pissang** [comment]
暂时不行

**Comment by Nataila** [comment]
@pissang  thanks!
