### ISSUE TITLE
动态改变series的bug

### ISSUE THREAD

**Issue by zombieJ** [ecomfe/echarts#4033]
#### 问题简述 (One-line summary)
动态改变line chart的series会出现显示错误

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.3
+ 浏览器类型和版本 (Browser version):chrome latest
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
* 生成一个line chart，随后改变series的name无效（改变series的data有效）
* 生成一个line chart，seires的array设置成[] (空数组)无效

#### 期望结果 (Expected behaviour)
可以动态改变series的name，删除series时chart也会动态删除

#### 可能哪里有问题 (What went wrong)
第一次生成chart后series被cache住了。以至于更新series后按照原来的顺序生成。

#### ECharts配置项 (ECharts option)
```javascript
option = {
					tooltip: {trigger: 'axis'},
					legend: [{
						data: ["aaa", "bbb", "ccc"]
					}],
					xAxis: {
						type: 'category',
						data: ["1", "2", "3"]
					},
					yAxis: {
						type: "value"
					},
					series: [
						{
							name: "aaa",
							type: "line",
							stack: "job",
							areaStyle: {normal: {}},
							data: [1, 1, 1]
						},
						{
							name: "bbb",
							type: "line",
							stack: "job",
							areaStyle: {normal: {}},
							data: [1, 1, 1]
						},
						{
							name: "ccc",
							type: "line",
							stack: "job",
							areaStyle: {normal: {}},
							data: [1, 1, 1]
						}
					]
				};

```

#### 其他信息 (Other comments)
jsfiddle地址： https://jsfiddle.net/q69ph4ze/
* 点击Change1测试动态更改series name
* 点击Change2测试动态更改series list

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/3937#issuecomment-244532055

**Comment by animalize** [comment]
好！回头试试

**Comment by zombieJ** [comment]
@100pah ，何时上3.2.4？

**Comment by zombieJ** [comment]
@pissang ，jsfiddle里的第二个例子还是没有修复。
减少series数量时，会有残留，导致图形显示不改变。

**Comment by hanxiansen** [comment]
@zombieJ @pissang  在type: 'bar'的情况下，如果动态减少series的数量，会有残留无法动态更新减少后的series数据，这个问题还没有解决吗？我用的react版本的echart，一直存在这个问题。

**Comment by syhyz1990** [comment]
是你的用法不对

setOption有3个属性，setOption(option,notMerge,lazyUpdate);

第二个notMerge默认为false,即默认合并两个数据

解决：设置为true

myChart.setOption(option,true);
