### ISSUE TITLE
线状的图表中如何在X轴下面添加对应的markPoint？

### ISSUE THREAD

**Issue by sadydai** [ecomfe/echarts#4039]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
参见<http://echarts.baidu.com/option.html#series-line.markPoint.data>
