### ISSUE TITLE
异步加载数据时不能更新series.name

### ISSUE THREAD

**Issue by sinprog** [ecomfe/echarts#4042]
#### 问题简述 (One-line summary)
异步加载数据时不能更新series.name

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.3
+ 浏览器类型和版本 (Browser version):全版本
+ 操作系统类型和版本 (OS Version):全系统

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
setTimeout(function(){
    myChart.setOption({
        series: [{
            // 根据名字对应到相应的系列
            name: '呵呵',
            data: [1,1,1,2,3,4]
        }]
    });
}, 1000);
```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/5990865/18342150/e6f08024-75df-11e6-9d35-027c60db10f9.png)

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/4033
