### ISSUE TITLE
请问十字光标的提示文字（x, y）能否格式化？ 好像不可以加formatter 

### ISSUE THREAD

**Issue by wn0112** [ecomfe/echarts#4043]
#### 问题简述 (One-line summary)

请问十字光标的提示文字（x, y）能否格式化？ 好像不可以加formatter 

就是设置 tooltip.axisPointer.type = 'cross'后，出现的十字光标。伴移动会出现x, y提示，好像不可以格式化？

**Comment by pissang** [comment]
暂时不行
