### ISSUE TITLE
能否提供echarts默认图标集？

### ISSUE THREAD

**Issue by wn0112** [ecomfe/echarts#4046]
#### 问题简述 (One-line summary)

我添加了几个自定义工具，请美工做了SVG图标，SVG图标用浏览器打开看是好的，但一放到echarts上就变粗，出现锯齿。
请问哪里可以找到eCharts的默认图标？或者 默认图标的 svg path字符串？ 我想还是使用echarts的自带图标显示效果会好些

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-scatter.symbol

**Comment by wn0112** [comment]
@pissang 哪里可以拿到 echarts toolbox 中的那些默认图标？我想用这些图标作为 自定义工具的图标使用

**Comment by wn0112** [comment]
以下这个svg图标，放到echarts上完全变形了
[method-draw-image.zip](https://github.com/ecomfe/echarts/files/463014/method-draw-image.zip)
如图：
![image](https://cloud.githubusercontent.com/assets/14155504/18372574/46c97c90-7670-11e6-986b-7d70182a1807.png)
