### ISSUE TITLE
echart建议

### ISSUE THREAD

**Issue by mtsee** [ecomfe/echarts#4048]
在绘制图表的时候，只能对颜色进行修改，建议加入图片，这样更灵活，图片可设置拉伸，平铺，缩放，位移，旋转。

**Comment by pissang** [comment]
谢谢建议，图片可以自己用 dom 放，散点图也设置 symbol 为图片

**Comment by mtsee** [comment]
条形图貌似不可以设置成图片，比如我想把条形图的条形显示带花纹的图片，这个怎么做呢

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/gallery/editor.html?c=pie-pattern

**Comment by mtsee** [comment]
color: new echarts.graphic.Pattern(
  imageDom, // 支持为 HTMLImageElement, HTMLCanvasElement，不支持路径字符串
  'repeat' // 是否平铺, 可以是 repeat-x, repeat-y, no-repeat
)
echarts下面没找到这个Pattern方法

**Comment by mtsee** [comment]
3Q~
