### ISSUE TITLE
[error] webpack & echarts & IE/Edge 初始化失败

### ISSUE THREAD

**Issue by joe223** [ecomfe/echarts#4058]
#### 问题简述 (One-line summary)

使用Vue.js构建单页面时，webpack引入的echarts.init()方法异常
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):    "echarts": "^3.2.2",
- 浏览器类型和版本 (Browser version):    Edge、IE11/IE10/..均出现异常。chrome/fireFox/opera/safari正常
- 操作系统类型和版本 (OS Version):    Windows10
#### 重现步骤 (Steps to reproduce)
1.  使用vue-cli初始化项目；
2. 引入 echarts ，`let echarts = require('echarts');`
3. 初始化echarts 

```
<template>
  <div class="dchart-container">
      <div class="dchart" v-el:dcharthr id="dcharthr"></div>
  </div>
</template>

<script>
let echarts = require('echarts');
export default {
  data() {
    return {
    }
  },
  ready: function () {
    let myChart = echarts.init(document.getElementById("dcharthr"));
    myChart.setOption({
      title: { text: 'ECharts 入门示例' },
      tooltip: {},
      xAxis: {
        data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
      },
      yAxis: {},
      series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
      }]
    });
  }
}
</script>
}
```
#### 期望结果 (Expected behaviour)

初始化完成，显示图表。`<div class="dchart" v-el:dcharthr id="dcharthr"></div>`中包涵一个`canvas`元素。
#### 可能哪里有问题 (What went wrong)

`let myChart = echarts.init(document.getElementById("dcharthr"));`
浏览器报错：`SCRIPT65535:调用的对象无效`
#### ECharts配置项 (ECharts option)

``` javascript
option = {
title: { text: 'ECharts 入门示例' },
      tooltip: {},
      xAxis: {
        data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
      },
      yAxis: {},
      series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
      }]
}

```
#### 其他信息 (Other comments)

期望：
![image](https://cloud.githubusercontent.com/assets/10026019/18387310/8581f648-76ce-11e6-990e-2b01979b8ec8.png)
异常结果（为突出结果，爹元素添加了border样式）：
![image](https://cloud.githubusercontent.com/assets/10026019/18387341/b4c3f794-76ce-11e6-8454-b9c7b698ffc7.png)

**Comment by edwardfhsiao** [comment]
"echarts": "^3.2.3"
出问题
let myChart = echarts.init(document.getElementById('id'));
浏览器报错：SCRIPT65535:调用的对象无效

**Comment by billcz** [comment]
me too .ie9正常，而ie10\11\Edge都报错。
SCRIPT65535:调用的对象无效

**Comment by pissang** [comment]
见 https://github.com/ecomfe/zrender/issues/189
