### ISSUE TITLE
平行坐标第一个例子中的tooltip无法显示

### ISSUE THREAD

**Issue by wade0817wang** [ecomfe/echarts#4061]
#### 问题简述 (One-line summary)
平行坐标第一个例子中的tooltip无法显示

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):v3.2.3
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
http://echarts.baidu.com/demo.html#parallel-aqi这个例子鼠标移到坐标轴上，tooltip没有显示

#### 期望结果 (Expected behaviour)

鼠标移动到坐标轴上显示tooltip

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
平行坐标轴暂时没有支持 tooltip

**Comment by wade0817wang** [comment]
ok，谢谢

**Comment by es3154** [comment]
这都快一年了，还没加上吗？

**Comment by kuige** [comment]
因为某些原因没加上可以理解，但是既然不支持，为什么示例里面要加上 tooltip 的选项，文档里面也没有说明一下？

**Comment by kurryluo** [comment]
同样遇到 tooltip 不能用，但是示例中存在的问题，不能用就去掉吧

**Comment by mainlove** [comment]
都两年了 
为什么别人就行？？
 https://www.hcharts.cn/demo/highcharts/parallel-coordinates

**Comment by woshidasusu** [comment]
都三年了！！
还不支持 tooltip
