### ISSUE TITLE
如何能让toolbox默认开启某个功能?比如默认开启brush

### ISSUE THREAD

**Issue by ruizhen** [ecomfe/echarts#4063]
目前toolbox的所有功能都必须用户鼠标亲自去点击了才能开启
现在我有个需求就是必须初始化echart的时候,默认是开启brush刷子功能的
而不是要用户去点击了刷子按钮才开启刷子.
这个echarts似乎不能做到?

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=candlestick-brush

**Comment by ruizhen** [comment]
你这个例子是默认brush一片区域啊,并没有开启刷子功能啊...
默认brush一片区域有demo的...

**Comment by ruizhen** [comment]
@pissang 你这个例子是默认brush一片区域啊,并没有开启刷子功能啊...
默认brush一片区域有demo的...

**Comment by ruizhen** [comment]
@pissang 什么意思啊?问题没解决两边都关闭了?

**Comment by 100pah** [comment]
参见 <http://gallery.echartsjs.com/editor.html?c=xS1_qghj2&v=2>

```js
    myChart.dispatchAction({
        type: 'takeGlobalCursor',
        key: 'brush',
        brushOption: {
            brushType: 'polygon',
            brushMode: 'multiple'
        }
    });
```

**Comment by ruizhen** [comment]
@100pah 谢谢,正确答案

**Comment by Anyway521** [comment]
有没有完整代码，只设置这个dispatchAction没生效啊
