### ISSUE TITLE
饼图样式问题

### ISSUE THREAD

**Issue by convertzl** [ecomfe/echarts#4066]
问题简述 
  这样的饼图样式可以做出来吗

版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):Echarts3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):windows7

其他信息 (Other comments)

![pie](https://cloud.githubusercontent.com/assets/21234912/18424013/8f6eb91e-78dd-11e6-8ad4-777cd15cb12a.png)

**Comment by pissang** [comment]
用两个叠加的饼图

**Comment by convertzl** [comment]
好的,谢谢
