### ISSUE TITLE
echarts如何让地图map不同区块颜色不同

### ISSUE THREAD

**Issue by Andy178** [ecomfe/echarts#4067]
#### 问题简述 (One-line summary)
1、echarts有没有设置让地图上相邻区域颜色不同？
2、echarts有没有办法让平面地图显示的有些立体效果？

**Comment by pissang** [comment]
1. 设置 [regions](http://echarts.baidu.com/option.html#geo.regions) 或者 [data](http://echarts.baidu.com/option.html#series-map.data) 单个的 `itemStyle.normal.color`
2. 暂时不行，后续会在 echarts-x 的扩展中加入
