### ISSUE TITLE
柱状图数据绑定问题

### ISSUE THREAD

**Issue by Iwantlooktheworld** [ecomfe/echarts#4068]
#### 问题简述 (One-line summary)
绑定数据x轴为日期，在每一天显示多个员工的数据，员工数量是动态的怎么绑定啊？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/22144448/18428580/5105ed36-7901-11e6-9e57-d21e7a978341.png)
类似于这种但是每天的柱子是个数是动态的。

**Comment by pissang** [comment]
动态与否是由你的代码决定的，你要是有 1s 间隔的数据更新就每隔 1s setOption 更新数据，其它事情会由 echarts 帮你做
