### ISSUE TITLE
关于360加速球的效果实现

### ISSUE THREAD

**Issue by dailc** [ecomfe/echarts#4071]
#### 问题简述 (One-line summary)

如下图1,目前发现这种类似于360加速球的效果还是挺常用的。
但是目前好像echarts并没有这个功能。
所以目前如果要用到这种功能只能自己去额外实现,这样就感觉没有那种大而全的感觉了
(目前echarts中的类似效果是图2,但仍感觉相距甚远)
#### 期望结果 (Expected behaviour)

请问,echarts是否后续版本会有这个功能？
请问,是否有第三方人封装过这种功能？
#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/6134890/18429184/c015c306-7904-11e6-9d22-c0ee4dc0e034.png)

图2:
![image](https://cloud.githubusercontent.com/assets/6134890/18429432/d30767de-7905-11e6-88a6-2bdb6a28e65d.png)

**Comment by pissang** [comment]
echarts 不会内置这种特殊的水球图，后面会通过扩展加入，欢迎贡献

**Comment by Ovilia** [comment]
ECharts 插件已支持水球图 https://github.com/ecomfe/echarts-liquidfill
