### ISSUE TITLE
各个大洲的问题

### ISSUE THREAD

**Issue by kindLee-alasikoo** [ecomfe/echarts#4078]
#### 问题简述 (One-line summary)
我想做一个亚洲的地图，一个非洲的地图。导入世界地图的json，mapType的值应该写入什么？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
registerMap 的时候需要传入名称，mapType 就写这个名称。见 http://echarts.baidu.com/download-map.html

**Comment by kindLee-alasikoo** [comment]
可以详细说下么，我想要画的是整个的大洲，比如亚洲，非洲，欧洲，是独立出来的，网上没有相关的数据文件。

**Comment by jiw0220** [comment]
@kindLee-alasikoo  
后来解决了吗?洲数据 json 有吗?求帮忙~~~

**Comment by kindLee-alasikoo** [comment]
没

**Comment by chfw** [comment]
我在这注册一下兴趣。这样有更新，我能收到。
