### ISSUE TITLE
请问关系图是否支持两个节点显示多条关系线?

### ISSUE THREAD

**Issue by lastmayday** [ecomfe/echarts#4079]
#### 问题简述 (One-line summary)
类似下图效果:
![links](http://i.imgur.com/k3G9pDe.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.3
+ 浏览器类型和版本 (Browser version): Chrome
+ 操作系统类型和版本 (OS Version): MacOS

**Comment by pissang** [comment]
目前最多只支持两条

**Comment by singlelonghair** [comment]
请问最新版本有解决这个问题么？2019年9月27日
