### ISSUE TITLE
坐标轴标签设置fontWeight无效

### ISSUE THREAD

**Issue by LeoZeda** [ecomfe/echarts#4083]
如下设置坐标轴标签的fontWeight，不能加粗字体， 设成“bolder”也一样。
            axisLabel: {
                textStyle: {
                  color: '#000000',
                  fontSize: 14,
                  fontWeight: 'bold'
                }
              }

[http://echarts.baidu.com/demo.html#bar-tick-align](http://echarts.baidu.com/demo.html#bar-tick-align)
api 文档:
[http://echarts.baidu.com/option.html#xAxis.axisLabel.textStyle.fontWeight](http://echarts.baidu.com/option.html#xAxis.axisLabel.textStyle.fontWeight)

完整xAxis  option
xAxis : [
        {
            type : 'category',
            boundaryGap: false,
            offset: 1,
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            },
            axisLabel: {
                textStyle: {
                  color: '#000000',
                  fontSize: 14,
                  fontWeight: 'bold'
                }
              }
        }
    ],

**Comment by pissang** [comment]
换个字体试下，有些字体是不支持
