### ISSUE TITLE
饼图能不能在扇区上显示数字？

### ISSUE THREAD

**Issue by yipanbo** [ecomfe/echarts#4086]
#### 问题简述 (One-line summary)
今天使用饼图遇到个问题，我想让饼图显示label的同时，在扇区上显示数值，不知道怎么实现了，附上效果图，求帮助，谢谢！
![image](https://cloud.githubusercontent.com/assets/8718011/18505552/5a063388-7a9a-11e6-8784-31219a8ef718.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以用两个系列，一个系列的饼图颜色设置成全透明的

**Comment by yipanbo** [comment]
非常感谢！
可以试试。不过，感觉这样有点复杂，最好是能通过配置直接显示。

**Comment by pissang** [comment]
没有那么复杂，因为这种需求比较特殊所以暂时不会考虑加入

**Comment by 3xxx** [comment]
这样很直观啊，不算特殊吧。谢谢。只能用透明了，好主意。
