### ISSUE TITLE
极坐标缩放问题

### ISSUE THREAD

**Issue by gghyoo** [ecomfe/echarts#4087]
#### 问题简述 (One-line summary)

文档里面提到了DataZoom支持极坐标，但是貌似没有看到里程，也不知道怎么使用，求指出。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
已加入支持

**Comment by 100pah** [comment]
刚加入的，下个版本会看到。

**Comment by windyliupei** [comment]
如何设置呢？
