### ISSUE TITLE
图例legend的点击交互行为能否去掉，有没有参数设置

### ISSUE THREAD

**Issue by ShangXinbo** [ecomfe/echarts#4089]
比如饼图，如果点击图例是取消该图例响应的占比，我不想要这个交互如何屏蔽掉

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#legend.selectedMode

**Comment by qv1256** [comment]
比如我想取消默认的响应事件，添加一个自定义的一个事件，怎么解？

**Comment by forevezxx** [comment]
画出的饼图，鼠标移上去，的hover事件能不能禁止掉？selectedMode 设置为false以后，鼠标移上去，饼图块颜色还是会改变

**Comment by qv1256** [comment]
selectedMode 设置为false这个是让legend点击失效的，你这个是饼图失效是在series里加配置项 silent:true就可以了。



--

All the best wishes for you！
黄   强
—————————————————————————
上海屹通信息科技发展有限公司
地址：上海市海宁路269号森林湾大厦B栋601室
邮编：200080
手机：+86 185 2152 2249
电话：+86 21 6309 3688, 6309 3686  传真：6309 3687
Mail ： hq@yitong.com.cn
网站： http://www.yitong.com.cn 
—————————————————————————

在 2016-10-12 20:26:16，"Mr.不高兴" <notifications@github.com> 写道：


画出的饼图，鼠标移上去，的hover事件能不能禁止掉？selectedMode 设置为false以后，鼠标移上去，饼图块颜色还是会改变

**Comment by forevezxx** [comment]
已解决多谢

**Comment by NangeGao** [comment]
现在配置了selectedMode:false，不仅仅让legend点击失效，hover的时候相应的饼图也不高亮了，感觉这个是个bug吧？

**Comment by xcs-go** [comment]
@NangeGao 我想要实现取消legend的点击事件，保留hover事件，有办法实现吗。查看配置设置selectedMode:false的时候hover也没有作用了

**Comment by NangeGao** [comment]
> @NangeGao 我想要实现取消legend的点击事件，保留hover事件，有办法实现吗。查看配置设置selectedMode:false的时候hover也没有作用了

我那是17年回复的，不知道官方有没有修过这里

**Comment by SheepHan** [comment]
现在貌似还是存在的
