### ISSUE TITLE
inside模式的datazoom不支持极坐标系的缩放

### ISSUE THREAD

**Issue by gghyoo** [ecomfe/echarts#4090]
#### 问题简述 (One-line summary)

现在源码里面，inside模式的datazoom貌似还没有支持极坐标系的缩放，不知道什么时候可以支持到。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
想问一下，您们是有现实场景，需要用到极坐标的 dataZoom 支持么？

**Comment by gghyoo** [comment]
是的，我这边有一个雷达的数据，是极坐标系的，360°范围内，有很大的值，也有很小的值，如果没有缩放，局部的信息，就看不清楚。

**Comment by gghyoo** [comment]
不知道你们那边是否有开发该功能的计划？

**Comment by 100pah** [comment]
恩接下来可以加上 inside 的 dataZoom。

**Comment by gghyoo** [comment]
多谢，不知道时间上的安排是什么？估计什么时候可以搞定？
