### ISSUE TITLE
关系图示例中的数据如何读取

### ISSUE THREAD

**Issue by Jason0830** [ecomfe/echarts#4091]
#### 问题简述 (One-line summary)
下载了关系图示例的html文件和相关的数据文件，但在本地跑时就一直停留在loading的状态，数据没有读取出来，

$.get('data/asset/data/les-miserables.gexf', function (xml) {

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0 
+ 浏览器类型和版本 (Browser version): Firefox 48.0.2
+ 操作系统类型和版本 (OS Version): Win 10 

#### 重现步骤 (Steps to reproduce)
1. 从http://echarts.baidu.com/gallery/editor.html?c=graph-circular-layout 下载示例
2. 从http://echarts.baidu.com/data/asset/data/les-miserables.gexf 下载数据文件

本地用firefox 打开graph-circular-layout文件，运行停止在myChart.showLoading() ， 就一直在loading

#### 期望结果 (Expected behaviour)
和网上示例运行的结果一直

#### 可能哪里有问题 (What went wrong)
$.get('data/asset/data/les-miserables.gexf', function (xml) {

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
加载失败，跨域或者路径不对

**Comment by Jason0830** [comment]
谢谢！

我已经将数据文件放到本地了，放在html的同一个目录下，并且把代码从原来的：
$.get('data/asset/data/les-miserables.gexf', function (xml)

改成了：
$.get('les-miserables.gexf', function (xml)

运行结果还是没有出来，请问该如何调整？

再次感谢！

**Comment by wnismiddle** [comment]
也遇到了同样的问题，报错 Uncaught ReferenceError: $ is not defined。
除了题主所做的步骤外，我还在下载数据中的<script>部分添加了以下几行，
<script type="text/javascript" src="http://echarts.baidu.com/examples/vendors/jquery/jquery.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/examples/vendors/bootstrap/js/bootstrap.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/examples/vendors/lodash.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/examples/vendors/dat.gui.min.js"></script>
成功显示。
