### ISSUE TITLE
求教关于echart2的地图下钻引用问题  question

### ISSUE THREAD

**Issue by gssgch** [ecomfe/echarts#4093]
http://echarts.baidu.com/echarts2/doc/example/map3.html 这个实例中引用的：
var ecConfig = require('echarts/config');
var zrEvent = require('zrender/tool/event');

下载的echarts版本是2.2.7，zrender版本是zrender-2.1.0
在zrender-2.1.0/src/tool/下找到event
但是没有在echart的build\dist目录下找到config,请问这个config到底是哪一个。

**Comment by pissang** [comment]
引用 echarts 后就可以 `require('echarts/config')` 了，或者如果引用的是 echarts-all 的话是 `echarts.config`
