### ISSUE TITLE
漏斗图添加dynamic height

### ISSUE THREAD

**Issue by yihengli** [ecomfe/echarts#4094]
#### 问题简述 (One-line summary)

希望漏斗图能够实现dynamic height的视觉效果。具体可参考以下项目
http://jakezatecky.github.io/d3-funnel/

**Comment by wu11106** [comment]
2016年9月16日星期五，Banabanana <notifications@github.com> 写道：

**Comment by hecomzhangzhiguo** [comment]
同求啊。

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/7076，已列入计划中

**Comment by Ovilia** [comment]
已支持，见 #7076
