### ISSUE TITLE
TypeError: Cannot read property 'prepareBoxplotData' of undefined

### ISSUE THREAD

**Issue by tianxuzhang** [ecomfe/echarts#4096]
#### 问题简述 (One-line summary)

npm 安装的echarts没有dataTools.js

#### 版本及环境 (Version & Environment)
+ ECharts 3.1.1

#### 重现步骤 (Steps to reproduce)
1. npm install echarts
2. new webpack.ProvidePlugin({echarts: "echarts", "window.echarts": "echarts"}),
3. 使用案例http://echarts.baidu.com/demo.html#boxplot-light-velocity

#### 期望结果 (Expected behaviour)

正常画箱线图

#### 可能哪里有问题 (What went wrong)

echarts.dataTool.prepareBoxplotData中的dataTool是undefined的

**Comment by tianxuzhang** [comment]
貌似比较简单，自己实现了：

```js
getBoxData: function(d){
        let Q1  = d3.quantile(d, .25),
          Q2    = d3.quantile(d, .5),
          Q3    = d3.quantile(d, .75),
          IQR   = Q3 - Q1,
          upper = Q1 - IQR * 1.5,
          lower = Q3 + IQR * 1.5;
        
        return [upper,Q1,Q2,Q3,lower];
      },
```

**Comment by lyltj2010** [comment]
可以在官方代码找到[dataTool](https://github.com/ecomfe/echarts/blob/master/dist/extension/dataTool.min.js)这个插件，单独引入可以解决这个问题。
