### ISSUE TITLE
Echars在普元中可以实现大部分功能吗

### ISSUE THREAD

**Issue by doublelinchina** [ecomfe/echarts#4099]
#### 问题简述 (One-line summary)
项目要求使用普元7.5版本开发，地图用Echars3.0开发

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):Echars3.0
+ 浏览器类型和版本 (Browser version):Chrome
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
试下呗
