### ISSUE TITLE
多分组类别的坐标轴显示

### ISSUE THREAD

**Issue by bigjoy** [ecomfe/echarts#4100]
#### 问题简述 (One-line summary)
echarts当前仅支持两个横坐标轴，请问如何实现3个以上类别作为横坐标轴？
如 国家/省/市这三个分组类别同时显示在坐标轴上？
![image](https://cloud.githubusercontent.com/assets/7991240/18612751/e72e2a02-7d94-11e6-9c46-1e29a4e72a97.png)

**Comment by 100pah** [comment]
使用颜色来区分更高层的类别行么？
