### ISSUE TITLE
如何能让toolbox默认开启某个功能?比如默认开启brush,是默认启用该功能,不是默认brush一段区域

### ISSUE THREAD

**Issue by ruizhen** [ecomfe/echarts#4101]
目前toolbox的所有功能都必须用户鼠标亲自去点击了才能开启
现在我有个需求就是必须初始化echart的时候,默认是开启brush刷子功能的
而不是要用户去点击了刷子按钮才开启刷子.
这个echarts似乎不能做到?
注意:是默认开启这个功能,不是默认brush一片区域.
也就是初始化echart后,直接拖动绘制区域就是brush,而不是用户要去点toolbox的横向选择等按钮才开启这个功能

**Comment by pissang** [comment]
不要重复开issue https://github.com/ecomfe/echarts/issues/4063
