### ISSUE TITLE
地图漫游组件roamController  echarts3.0

### ISSUE THREAD

**Issue by lwy92** [ecomfe/echarts#4109]
#### 问题简述 (One-line summary)

地图漫游组件roamController  echarts3.0  如何使用

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
echarts 3 里现在没有 roamController
