### ISSUE TITLE
IE8热力图不支持吗？

### ISSUE THREAD

**Issue by elelvenliu** [ecomfe/echarts#4112]
#### 问题简述 (One-line summary)
IE8下热力图加载不了，是echart本身不支持吗？请问能让IE8支持吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.0
+ 浏览器类型和版本 (Browser version): IE8
+ 操作系统类型和版本 (OS Version): WIN7

IE8下热力图加载不了, 而且报js错

官网例子： http://echarts.baidu.com/echarts2/doc/example/heatmap_map.html

**Comment by elelvenliu** [comment]
![11](https://cloud.githubusercontent.com/assets/10057093/18628821/abe43e40-7e94-11e6-9793-2714cc8eb176.png)

**Comment by pissang** [comment]
不支持

**Comment by elelvenliu** [comment]
那项目一定要支持，怎么办有别的插件推荐吗

**Comment by pissang** [comment]
IE8 中是没办法搬到的，要不就是去掉 IE8 显示的需求，要不浏览器渲染输出图片
