### ISSUE TITLE
Disable Scroll Wheel on WorldMap ?

### ISSUE THREAD

**Issue by hiddenpearls** [ecomfe/echarts#4113]
Hello,

I have integrated eCharts and this looks awesome. Great Work!

I included WorldMap and when I scroll down my mouse It stucks on the map. I want to disable zooming/scroll wheel on WorldMap.

How I can do that ?

**Comment by pissang** [comment]
```js
series: [{
  ...
  // Only enable pan
  roam: 'move'
}]

**Comment by hiddenpearls** [comment]
Thank you - This worked like a charm.

**Comment by ahmadordi** [comment]
The same problem with bar3D
