### ISSUE TITLE
横坐标或者纵坐标显示的文字旁可以附加图片吗？

### ISSUE THREAD

**Issue by darknessjs** [ecomfe/echarts#4116]
#### 问题简述 (One-line summary)

http://echarts.baidu.com/demo.html#heatmap-cartesian
比如这个的Y坐标，
Monday到Sunday左侧都有不同的图片可以做到吗
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.3
- 浏览器类型和版本 (Browser version):任意
- 操作系统类型和版本 (OS Version):任意
#### 期望结果 (Expected behaviour)

如问题简述
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by yinfxs** [comment]
请问你解决了吗

**Comment by 100pah** [comment]
3.7.1 版本已支持。参见：<http://echarts.baidu.com/gallery/editor.html?c=bar-rich-text>
