### ISSUE TITLE
柱状图中区分空值和0

### ISSUE THREAD

**Issue by ZhangXuedong** [ecomfe/echarts#4117]
#### 问题简述 (One-line summary)
echarts2里面设置了calculable=true，那么柱状图的'-'值会显示为较矮的白色柱子。echarts3里面取消了calculable属性，虽然可以设置tooltip.trigger='axis'，然后鼠标移动到对应的x轴显示值是'-'还是0，但不是很直观。
能不能增加增加一个选项为柱状图设置空值的高度和样式。

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#series-bar.barMinHeight> 这个属性能达到效果么？
如果仍然想要『空值有特殊的样式』，那么对于空值的柱子，可以自己设置它的 `itemStyle`。

**Comment by ZhangXuedong** [comment]
谢谢。barMinHeight和itemStyle可以设置0值的高度和样式，如果是空值的话柱子是不存在的，barMinHeight和itemStyle也不起作用。
0值有特定的高度和样式，空值表现为不存在柱子，这样也能区分柱状图的0值和空值了。
