### ISSUE TITLE
韦恩图后续还会支持吗？目前除了降级到2.0 版本还有其他方式使用吗？

### ISSUE THREAD

**Issue by ritawr** [ecomfe/echarts#4118]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

使用韦恩图

#### 可能哪里有问题 (What went wrong)

3.0 版本已不再支持 韦恩图

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
后续会跟 wordCloud 一样以插件形式提供

**Comment by zhouboluo** [comment]
wordCloud 插件已经有了么

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-wordcloud
