### ISSUE TITLE
设置symbol:‘image://xxx.png’,设置itemStyle.normal.borderWidth, itemStyle.normal.borderColor无效 

### ISSUE THREAD

**Issue by 276509842** [ecomfe/echarts#4119]
#### 问题简述 (One-line summary)

设置symbol:‘image://xxx.png’,设置itemStyle.normal.borderWidth, itemStyle.normal.borderColor无效 

sData.push({value: [i, 1, '商品'+(i+1) + '\n\n类目xx', ], 
    			symbolSize: 80, symbol: 'image://' + products[i], 
    			
    			itemStyle: {
    				normal: {
    					//color: i == 5 ? '#f00' : '#000',
    					borderWidth: 10,
    					shadowColor: i == 5 ? '#F00' : '#ccc',
    					shadowBlur: 5,
    				}
    			}
    		});

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):
V3.2.2

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
图片不支持 border，border 只能对矢量图形使用
