### ISSUE TITLE
Tooltip message for each bar.

### ISSUE THREAD

**Issue by burhandodhy** [ecomfe/echarts#4121]
Hi,

I'm creating Barchart and i Want custom tooltip message for each bar. Is it possible to pass data in such format 
`data: [ ['custom tooltip',1804], ['custom tooltip',1689], ['custom tooltip',1689] , ['custom tooltip',1689] ]`

or is anyother way through which i can set tooltip message for each bar

**Comment by pissang** [comment]
Yes it is possible in the latest version 3.2.3
```js
data: [{
  value: 1804,
  tooltip: 'Custom tooltip'
}, {
  value: 1689,
  tooltip: 'Custom tooltip2'
}]
```
