### ISSUE TITLE
legend 能否设置width 和 height

### ISSUE THREAD

**Issue by huangqianying** [ecomfe/echarts#4123]
#### 问题简述 (One-line summary)

legend width 和 height 设置无效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): google chrome
+ 操作系统类型和版本 (OS Version): win10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
设置宽度或高度后，legend中超出的文字部分直接不显示

#### ECharts配置项 (ECharts option)

```javascript
option = {
legend: {data:['xxxxxxx系统'],width: '15%',right: '5px',orient: 'vertical',bottom: '12px',itemWidth: 10,itemHeight: 10},
}

```

**Comment by pissang** [comment]
itemWidth 和 itemHeight

**Comment by XiaoweiLiu0812** [comment]
itemWidth是设置 图例标记的图形宽度。希望的是 图例 + 文字 的宽度超出后的部分直接不显示。
