### ISSUE TITLE
如何在legend中显示value值？

### ISSUE THREAD

**Issue by jaune001** [ecomfe/echarts#4125]
#### 问题简述 (One-line summary)
legend中如何显示value值，现在只能显示name???

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):echarts2.0
+ 浏览器类型和版本 (Browser version):chrome 53.0.2785.116 m
+ 操作系统类型和版本 (OS Version):windows7

#### 重现步骤 (Steps to reproduce)
1. legend写法如下：

legend: {

        orient: 'vertical',

        x: 'left',

        data:[

                {value:335, name:'直达', selected:true},

                {value:679, name:'营销广告'},

                {value:1548, name:'搜索引擎'}

            ]

    },

2.在name后面加value，应如何加？

#### 期望legend显示结果 (Expected behaviour)
直达 335 (13.08%)
营销广告 679(26.5%)
搜索引擎 (1548)(60.42%)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#legend.formatter

**Comment by jaune001** [comment]
可否给个例子。我这样传value是undefined
app.title = '嵌套环形图';

option = {
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        x: 'left',
        data:[
                {value:335, name:'直达', selected:true},
                {value:679, name:'营销广告'},
                {value:1548, name:'搜索引擎'}
        ],
        formatter: function (name,value) {
        return value + name;
}
        
    },
    series: [
        {
            name:'访问来源',
            type:'pie',
            selectedMode: 'single',
            radius: [0, '30%'],

            label: {
                normal: {
                    position: 'inner'
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:335, name:'直达', selected:true},
                {value:679, name:'营销广告'},
                {value:1548, name:'搜索引擎'}
            ]
        },
        {
            name:'访问来源',
            type:'pie',
            radius: ['40%', '55%'],

            data:[
                {value:335, name:'直达'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1048, name:'百度'},
                {value:251, name:'谷歌'},
                {value:147, name:'必应'},
                {value:102, name:'其他'}
            ]
        }
    ]
};

**Comment by emitle** [comment]
@jaune001  搞定了吗？我也遇到这个问题，看文档里面 legend 的 formatter，传入的值始终是个 name

**Comment by bjchenxn** [comment]
@jaune001 @emitle 你好，请问两位解决这个问题了吗？同样的在formatter中不知怎样获取value值
@pissang

**Comment by jaune001** [comment]
formatter:function(params){
                  return  params.name + ' (哈哈：' + Number(params.value).toFixed(2) + ')';
 }, 
please try
@bjchenxn @emitle

**Comment by ZiSeFeng** [comment]
你们这个问题解决了吗？
formatter:function(params){
    console.log(params,params.value)
    return params.name + ' (哈哈：' + Number(params.value).toFixed(2) + ')';
 },
打印出来的legend的name和一个undefined
legend= [ 
 {
                    name:'星期一',
                    textStyle: {
                        fontSize:16,
                        color:'#333'
                    },
                    selected:true,
                    value:12556
                },
                {
                    name:'星期二',
                    textStyle: {
                        fontSize:16,
                        color:'#333'
                    },
                    value:56456
                },
                {
                    name:'星期三',
                    textStyle: {
                        fontSize:16,
                        color:'#333'
                    },
                    value:5454
                }
]
series=[{
     data= [
             {value: 12556,name: '星期一'},
             {value: 56456,name: '星期二'},
             {value: 5454,name: '星期三'},
    ]
}]
能够传入的值都是name

**Comment by Btista** [comment]
无法解决，文档上也描述为params传进去是name，没法在此获得value

**Comment by Btista** [comment]
不过我找了一种新思路，分享给需要的人：
因为问题的关键在于formatter回调函数里取不到value， 但是echarts提供的api里可以通过echartsInstance.getOption 得到option配置，则可以顺着拿到echartsInstance.getOption().series[0].data , 完了再通过这个回调函数里能取到的name来遍历echartsInstance.getOption().series[0].data最终取到value。

虽然比较绕，但是也能最后拿到哈

**Comment by MissLlq** [comment]
用了楼上的方法，已解决。
代码如下：
`legend: { //控制图例
                    orient: 'vertical',
                    top: '30%',
                    right: '7px',
                    selectedMode: false,
                    formatter: (name) => {
                        const data = myChart.getOption().series[0].data
                        const getValues = data.find(v => { if (v.name === name) { return v.value } })
                        console.log(name + ' ' + getValues.value + '%')
                        return name + ':' + getValues.value + '%'
                    },
                    data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎'],
                },`

**Comment by linxinemily** [comment]
另外一種方法可以透過訪問 this （需使用 arrow function）獲取vue component實例
就能拿到 this.options.series[0].data

```
formatter: name => {
            const data = this.options.series[0].data
            const totalValue = data.reduce((acc, item) => { 
               acc += item.value;
               return acc;
             }, 0)
            let targetValue
            data.forEach(item => {
              if (item.name === name) {
                targetValue = item.value
              }
            })
           	const p = (targetValue / totalValue * 100).toFixed(2);
            return name + ' ' +  p + '%'
          }
```

**Comment by xxxs** [comment]
var datas = [
                {value: 335, name: '直接访问'},
                {value: 310, name: '邮件营销'},
                {value: 234, name: '联盟广告'},
                {value: 135, name: '视频广告'},
                {value: 1548, name: '搜索引擎'}
            ]
option = {
    tooltip: {
        trigger: 'item',
        formatter: '{a} <br/>{b}: {c} ({d}%)'
    },
    legend: {
        orient: 'vertical',
        left: 10,
        data:datas,
       formatter:function(name){
            let singleData = datas.filter(function(item){
                return item.name == name
            })
            return  name + '  ' + singleData[0].value;
        }
    },
    series: [
        {
            name: '访问来源',
            type: 'pie',
            radius: ['50%', '70%'],
            avoidLabelOverlap: false,
            label: {
                show: false,
                position: 'center'
            },
            emphasis: {
                label: {
                    show: true,
                    fontSize: '30',
                    fontWeight: 'bold'
                }
            },
            labelLine: {
                show: false
            },
            data: [
                {value: 335, name: '直接访问'},
                {value: 310, name: '邮件营销'},
                {value: 234, name: '联盟广告'},
                {value: 135, name: '视频广告'},
                {value: 1548, name: '搜索引擎'}
            ]
        }
    ]
};

**Comment by aboutcroon** [comment]
> var datas = [
> {value: 335, name: '直接访问'},
> {value: 310, name: '邮件营销'},
> {value: 234, name: '联盟广告'},
> {value: 135, name: '视频广告'},
> {value: 1548, name: '搜索引擎'}
> ]
> 
> ```
> legend: {
>     orient: 'vertical',
>     left: 10,
>     data:datas,
>    formatter:function(name){
>         let singleData = datas.filter(function(item){
>             return item.name == name
>         })
>         return  name + '  ' + singleData[0].value;
>     }
> }
> ```

this way do make effects, thanks !

**Comment by aboutcroon** [comment]
> var datas = [
> {value: 335, name: '直接访问'},
> {value: 310, name: '邮件营销'},
> {value: 234, name: '联盟广告'},
> {value: 135, name: '视频广告'},
> {value: 1548, name: '搜索引擎'}
> ]
> 
> ```
> legend: {
>     orient: 'vertical',
>     left: 10,
>     data:datas,
>    formatter:function(name){
>         let singleData = datas.filter(function(item){
>             return item.name == name
>         })
>         return  name + '  ' + singleData[0].value;
>     }
> }
> ```

@xxxs this way do make effects, thanks !!
