### ISSUE TITLE
当legend较多时，能否增加一个legend　用来控制所有legend的全选／全不选

### ISSUE THREAD

**Issue by zjfromzero** [ecomfe/echarts#4127]
#### 问题简述 (One-line summary)
　　　当前需要做的基础图表line/bar/pie
　　在legend.data里面增加一个　'全选’
　　但是这个图标并不会显示，而是在console里面打印了
　　“全选　series not exists. Legend data should be same with series name or data name.”

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):最新版本echarts 3.2.3
+ 浏览器类型和版本 (Browser version):Google Chrome 版本 53.0.2785.116 (64-bit)
+ 操作系统类型和版本 (OS Version): Ubuntu 14.04

#### 重现步骤 (Steps to reproduce)
1. 在legend里面增加一个series里面没有的
legend: {
            show:true,
            data:['直接访问','访问','全选']
        }
2. 打开下面的option后　legend里面没有全选

#### 期望结果 (Expected behaviour)
我尝试了通过修改echarts.js来直接渲染一个图标，但是有没有办法可以不修改echarts文件的
在legend.data里面增加内容可以渲染出对应的legend图标

#### ECharts配置项 (ECharts option)

```javascript
option = {
        title : {
            text: '未来一周气温变化',
            subtext: '纯属虚构'
        },
        tooltip : {
            trigger: 'axis',
            axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
            }
        },
        legend: {
            show:true,
            selected:{
                '直接访问':false
            },
            data:['直接访问','访问','全选']
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis : [
            {
                type : 'category',
                boundaryGap : true,
                data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
                axisTick: {
                    alignWithLabel: true
                }
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : [
            {
                name:'直接访问',
                type:'bar',
                data:[10, 52, 200, 334, 390, 330, 220]
            },
            {
                name:'访问',
                type:'bar',
                data:[100, 520, 2000, 3340, 3090, 3300, 2200]
            }
        ]
    }

```

**Comment by Ovilia** [comment]
建议在 series 中加一个没有数据的 `name: '全选'`，然后通过监听该 legend 的选中事件（见 [events API](http://echarts.baidu.com/api.html#events.legendselectchanged)）处理。

**Comment by zjfromzero** [comment]
试了一下直接添加一个series里面　name:'全选' ,然后console报了个错误Uncaught Error: Component series. not exists. Load it first. 并且没有图表生成
改成
{
                name:'全选',
                type:'line'
            },
试着在添加name的同时加了一下type：'line'　这样可以line图和bar图都可以正常使用了
pie图如果在series.data只添加name:'全选', 整个图初始化的时候是异常的，饼图默认不会显示，点击全选后能够控制整个图表是否显示 @Ovilia

**Comment by Ovilia** [comment]
有点费解……把有疑惑的代码贴到 [gallery](http://gallery.echartsjs.com/explore.html) 我看下~

**Comment by zjfromzero** [comment]
line 设置成功：http://gallery.echartsjs.com/editor.html?c=xSJ3fpfG6
pie 有问题：http://gallery.echartsjs.com/editor.html?c=xH1Z0hfMT
pie:成功 ：http://gallery.echartsjs.com/editor.html?c=xHkNJWXz6&v=4
Thanks@Ovilia
