### ISSUE TITLE
Echarts 默认动态生成的JS 连接协议问题

### ISSUE THREAD

**Issue by cd-smallBear** [ecomfe/echarts#4128]
问题简述 (One-line summary)

Echarts 默认动态生成的JS 连接协议是 http  可以配置生成 https协议的吗？

#### 重现步骤 (Steps to reproduce)
1.&lt; script data-require-id="echarts/chart/bar" src="http://echarts.baidu.com/build/dist/chart/bar.js" async=&gt;&lt;/script&gt;

#### 期望结果 (Expected behaviour)
1.&lt; script data-require-id="echarts/chart/bar" src="https://echarts.baidu.com/build/dist/chart/bar.js" async=&gt;&lt;/script&gt;

**Comment by pissang** [comment]
用 cdn，http://www.bootcdn.cn/echarts/
