### ISSUE TITLE
上海热力图显示问题

### ISSUE THREAD

**Issue by chenxiwei7** [ecomfe/echarts#4130]
#### 问题简述 (One-line summary)
把杭州热力图换成上海热力图
杭州热力图：http://echarts.baidu.com/gallery/editor.html?c=heatmap-bmap
请问，有上海热力图的例子吗？没找到上海热力图的json

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
没有上海热力图的json

#### 期望结果 (Expected behaviour)
上海热力图的示例

#### 可能哪里有问题 (What went wrong)
无上海热力图json

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
使用方式一样的啊，只是需要数据换成上海的

**Comment by chenxiwei7** [comment]
有没有上海的数据呢？
