### ISSUE TITLE
热力图不能显示

### ISSUE THREAD

**Issue by Muyuze** [ecomfe/echarts#4131]
#### 问题简述 (One-line summary)

var points = [].concat.apply([], data.map(function (track) {
        return track.map(function (seg) {
            return seg.coord.concat([1]);
        });
    }));

错误提示  data.map is not a function 
         

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
浏览器版本？

**Comment by Muyuze** [comment]
版本及环境 (Version & Environment)

ECharts 版本 (ECharts version): Echarts 3
浏览器类型和版本 (Browser version): Google 
操作系统类型和版本 (OS Version): win 7
