### ISSUE TITLE
折线图显示有问题

### ISSUE THREAD

**Issue by sunyt** [ecomfe/echarts#4132]
#### 问题简述 (One-line summary)

在百度echarts实例网站上亲测
http://echarts.baidu.com/echarts2/doc/example/line2.html

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (版本 52.0.2743.116 m (64-bit)):
+ 操作系统类型和版本 (windows7):

#### 重现步骤 (Steps to reproduce)
1.登录http://echarts.baidu.com/echarts2/doc/example/line2.html
2.复制option
option = {
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告']
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[555, 210]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[0, 310]
        }
    ]
};
3.点刷新即可

#### 期望结果 (Expected behaviour)

“联盟广告”这条线起始点是0位置

#### ECharts配置项 (ECharts option)

option = {
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告']
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[555, 210]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[0, 310]
        }
    ]
};

**Comment by herrdu** [comment]
stack: '总量' 
是不是用它的问题
