### ISSUE TITLE
给多个雷达图显示标题的问题

### ISSUE THREAD

**Issue by chenxiwei7** [ecomfe/echarts#4139]
#### 问题简述 (One-line summary)
多个雷达图不显示标题，希望每个雷达图上有个小标题，如：雷达1，雷达2，雷达3

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
1.页面上添加3个雷达图

#### 期望结果 (Expected behaviour)
希望每个雷达图上有个小标题，如：雷达1，雷达2，雷达3

#### ECharts配置项 (ECharts option)

option = {
			    title: {
			        text: '基站天线状态视图'
			    },
			    legend: {
			        data: ['天线1监测值','天线1基准值','天线2监测值','天线2基准值','天线3监测值','天线3基准值']
			    },
			    tooltip : {
		               trigger: 'item'
		           },
			    radar: [
			        {
			        	indicator: [
			                { text: '温度' },
			                { text: '湿度' },
			                { text: '倾角' },
			                { text: '大气压' },
			                { text: '高度' }
			            ],
			            center: ['15%', '50%'],
			            radius: 120,
			            startAngle: 90,
			            splitNumber: 4,
			            shape: 'circle',
			            name: {
			                formatter:'【{value}】',
			                textStyle: {
			                    color:'#72ACD1'
			                }
			            },
			            splitArea: {
			                areaStyle: {
			                    color: ['rgba(114, 172, 209, 0.2)',
			                    'rgba(114, 172, 209, 0.4)', 'rgba(114, 172, 209, 0.6)',
			                    'rgba(114, 172, 209, 0.8)', 'rgba(114, 172, 209, 1)'],
			                    shadowColor: 'rgba(0, 0, 0, 0.3)',
			                    shadowBlur: 10
			                }
			            },
			            axisLine: {
			                lineStyle: {
			                    color: 'rgba(255, 255, 255, 0.5)'
			                }
			            },
			            splitLine: {
			                lineStyle: {
			                    color: 'rgba(255, 255, 255, 0.5)'
			                }
			            }
			        },
			        {
			            indicator: [
			                { text: '温度' },
			                { text: '湿度' },
			                { text: '倾角' },
			                { text: '大气压' },
			                { text: '高度' }
			            ],
			            center: ['50%', '50%'],
			            radius: 120,
			            startAngle: 90,
			            splitNumber: 4,
			            shape: 'circle',
			            name: {
			                formatter:'【{value}】',
			                textStyle: {
			                    color:'#72ACD1'
			                }
			            },
			            splitArea: {
			                areaStyle: {
			                    color: ['rgba(114, 172, 209, 0.2)',
			                    'rgba(114, 172, 209, 0.4)', 'rgba(114, 172, 209, 0.6)',
			                    'rgba(114, 172, 209, 0.8)', 'rgba(114, 172, 209, 1)'],
			                    shadowColor: 'rgba(0, 0, 0, 0.3)',
			                    shadowBlur: 10
			                }
			            },
			            axisLine: {
			                lineStyle: {
			                    color: 'rgba(255, 255, 255, 0.5)'
			                }
			            },
			            splitLine: {
			                lineStyle: {
			                    color: 'rgba(255, 255, 255, 0.5)'
			                }
			            }
			        },
			        {
			            indicator: [
			                { text: '温度' },
			                { text: '湿度' },
			                { text: '倾角' },
			                { text: '大气压' },
			                { text: '高度' }
			            ],
			            center: ['85%', '50%'],
			            radius: 120,
			            startAngle: 90,
			            splitNumber: 4,
			            shape: 'circle',
			            name: {
			                formatter:'【{value}】',
			                textStyle: {
			                    color:'#72ACD1'
			                }
			            },
			            splitArea: {
			                areaStyle: {
			                    color: ['rgba(114, 172, 209, 0.2)',
			                    'rgba(114, 172, 209, 0.4)', 'rgba(114, 172, 209, 0.6)',
			                    'rgba(114, 172, 209, 0.8)', 'rgba(114, 172, 209, 1)'],
			                    shadowColor: 'rgba(0, 0, 0, 0.3)',
			                    shadowBlur: 10
			                }
			            },
			            axisLine: {
			                lineStyle: {
			                    color: 'rgba(255, 255, 255, 0.5)'
			                }
			            },
			            splitLine: {
			                lineStyle: {
			                    color: 'rgba(255, 255, 255, 0.5)'
			                }
			            }
			        }
			    ],
			    series: [
			        {
			            name: '雷达图',
			            type: 'radar',
			            itemStyle: {
			            	emphasis: {
			                    // color: 各异,
			                    lineStyle: {
			                        width: 4
			                    }
			                }
			            },
			            data: [
			                {
			                    value: [80, 50, 55, 80, 70],
			                    name: '天线1监测值',
			                    symbol: 'rect',
			                    symbolSize: 5,
			                    lineStyle: {
			                        normal: {
			                            type: 'dashed'
			                        }
			                    }
			                },
			                {
			                    value: [60, 60, 60, 60, 60],
			                    name: '天线1基准值',
			                    areaStyle: {
			                        normal: {
			                            color: 'rgba(255, 255, 255, 0.5)'
			                        }
			                    }
			                }
			            ]
			        },
			        {
			            name: '雷达图',
			            type: 'radar',
			            radarIndex: 1,
			            itemStyle: {
			                emphasis: {
			                    // color: 各异,
			                    lineStyle: {
			                        width: 4
			                    }
			                }
			            },
			            data: [
			                {
			                    value: [50, 55, 90, 100, 50],
			                    name: '天线2监测值',
			                    symbol: 'rect',
			                    symbolSize: 5,
			                    lineStyle: {
			                        normal: {
			                            type: 'dashed'
			                        }
			                    }
			                },
			                {
			                    value: [60, 60, 60, 60, 60],
			                    name: '天线2基准值',
			                    areaStyle: {
			                        normal: {
			                            color: 'rgba(255, 255, 255, 0.5)'
			                        }
			                    }
			                }
			            ]
			        },
			        {
			            name: '雷达图',
			            type: 'radar',
			            radarIndex: 2,
			            itemStyle: {
			                emphasis: {
			                    // color: 各异,
			                    lineStyle: {
			                        width: 4
			                    }
			                }
			            },
			            data: [
			                {
			                    value: [85, 90, 100, 90, 80],
			                    name: '天线3监测值',
			                    symbol: 'rect',
			                    symbolSize: 5,
			                    lineStyle: {
			                        normal: {
			                            type: 'dashed'
			                        }
			                    }
			                },
			                {
			                    value: [60, 60, 60, 60, 60],
			                    name: '天线3基准值',
			                    areaStyle: {
			                        normal: {
			                            color: 'rgba(255, 255, 255, 0.5)'
			                        }
			                    }
			                }
			            ]
			        }
			    ]
			};

#### 其他信息 (Other comments)

现在是这样的：
![image](https://cloud.githubusercontent.com/assets/22286044/18774231/b6658c28-8189-11e6-999a-88c5c568ee97.png)
希望成这样的，给每个图显示个标题：
![image](https://cloud.githubusercontent.com/assets/22286044/18774274/0ddd1aa2-818a-11e6-9534-279d9b6026d4.png)

**Comment by teapot-4l8** [comment]
我有同样的问题，请问是怎么解决的？
