### ISSUE TITLE
chrome浏览器50版本中，图表有时不显示

### ISSUE THREAD

**Issue by niuchunling** [ecomfe/echarts#4141]
#### 问题简述 (One-line summary)
在chrome 50版本中测试，图表有时候显示不出来，

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3
+ 浏览器类型和版本 (Browser version): google chrome  50.0.2661.26
+ 操作系统类型和版本 (OS Version):  win7

#### 重现步骤 (Steps to reproduce)
1. 刷新或者首次进页面
2.

#### 期望结果 (Expected behaviour)
图表都展现

#### ECharts配置项 (ECharts option)

```javascript
var dataArray = [1,2,3,4,5]
option = {
 title : {
       show:false
       
    },
    
    legend: {
       show:false,
       
    },
    series : [
        {
            name: '资源',
            type: 'pie',
            radius : [30,110],
            center: ['50%', '60%'],
            roseType: 'area',
            data: dataArray,
           
        }
    ]
}

```

**Comment by 100pah** [comment]
没提供option
