### ISSUE TITLE
每个图表都要指定像素单位，不能用百分比，如果写百分比，会被认为是像素

### ISSUE THREAD

**Issue by itcongaili** [ecomfe/echarts#4145]
#### 问题简述 (One-line summary)
每个图表都要指定像素单位，不能用百分比，如果写百分比，会被认为是像素

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
最好可以自动放大到父级大小，而不用指定像素大小

#### 可能哪里有问题 (What went wrong)
初始化设置宽高的方法里面

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 是使用容器的 clientWidth 和 clientHeight 获取高宽的，写百分比也可以，但是在元素准备好（能够获取 clientWidth 和 clientHeight）之后再 setOption 或者 resize

**Comment by itcongaili** [comment]
我用的bootstrap布局的，没有指定父级容器的宽高

**Comment by 100pah** [comment]
父容器显示出来后，再初始化 echarts，才能获得父容器的 clientWidth/Height（从而才能支持百分比）

**Comment by itcongaili** [comment]
@100pah 下次试试
