### ISSUE TITLE
就一个数据时能不能显示为单点，而非一条线

### ISSUE THREAD

**Issue by Shlpeng** [ecomfe/echarts#4146]
#### 问题简述 (One-line summary)
标准折线图的系列数据data为［0，0，2，0］的时候，能不能就显示一个单点，而不是一条从横坐标连到“2”那个点，再落回到横坐标的折线。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7
+ 浏览器类型和版本 (Browser version): Firefox 31.0
+ 操作系统类型和版本 (OS Version): Win7

#### 期望结果 (Expected behaviour)
如果系列data属性为［0，0，2，0］只显示一个单点，而非一条折线

#### ECharts配置项 (ECharts option)

```javascript
option = {
series:[{
data:[0,0,2,0]
}]
}

```

**Comment by 100pah** [comment]
显示单点请用  `['-'，'-'，2，'-']`
给了 0 值则不应不画 0 值。
