### ISSUE TITLE
使用arcgis地图来替换百度地图

### ISSUE THREAD

**Issue by huanghongping1017** [ecomfe/echarts#4151]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
欢迎参照 <https://github.com/ecomfe/echarts/tree/master/extension/bmap> 实现基于 `arcgis` 的扩展。

**Comment by BarryLiu1995** [comment]
请问如何让echarts使用arcgis的地图
