### ISSUE TITLE
请问地图模块可以滑过某个城市弹出div吗?

### ISSUE THREAD

**Issue by Realybig** [ecomfe/echarts#4156]
请问地图模块可以滑过某个城市弹出div吗?

**Comment by 100pah** [comment]
可以监听事件，自己绘制 div。

**Comment by Realybig** [comment]
求指教   如何监听   貌似地图是canvas的   可以简单讲述一下吗   谢谢

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echartsInstance.on
