### ISSUE TITLE
地图文字重叠

### ISSUE THREAD

**Issue by 20080808** [ecomfe/echarts#4167]
#### 问题简述 (One-line summary)

地图上显示省份的文字，重叠
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):echart3
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):window
#### 重现步骤 (Steps to reproduce)

1.官网的例子：http://echarts.baidu.com/demo.html#map-china-dataRange
2.安徽省和江苏省的文字重叠
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by MShineRay** [comment]
找到了笨办法：直接修改china.js中
"properties":{"cp":[119.767413,33.041544],"name":"江苏","childNum":1}
cp的值，根据调试结果来看，cp应该代表x,y轴定位相关信息。修改副作用未知。。。。。。。
