### ISSUE TITLE
echart3中设置了xAxis.axisLabel.rotate以后，明明可以完整显示的刻度却由于interval而间隔显示了

### ISSUE THREAD

**Issue by jayfansdongdong** [ecomfe/echarts#4170]
#### 问题简述 (One-line summary)

当xAxis->axisLabel->interval为auto时，由于label长度过长会导致间隔显示。为了尽量显示所有Label，我们设置了xAxis->axisLabel->rotate。在echarts2里可以完美显示，echarts3里则不起作用。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.3   VS   2.2.7
- 浏览器类型和版本 (Browser version): chrome 
- 操作系统类型和版本 (OS Version): WIN10 、 OS
#### 重现步骤 (Steps to reproduce)

升级echarts 2 ->3
#### 期望结果 (Expected behaviour)

升级为echarts3以后显示如下：
![image](https://cloud.githubusercontent.com/assets/13114946/18939882/6caa8532-8636-11e6-82e6-8b6390e52433.png)

期望显示和echarts2里面一样：
![image](https://cloud.githubusercontent.com/assets/13114946/18939893/7b55cb3c-8636-11e6-83d9-898b46826c18.png)
#### 可能哪里有问题 (What went wrong)

当xAxis->axisLabel->interval 设置为true时，期望能最大限度显示所有刻度文字。
当xAxis->axisLabel->rotate 设置一定角度旋转后，原本水平距离不够显示的文字，应该能够显示出来。
在echarts2里面，貌似是先旋转，再计算能不能显示完全。而echarts3里面则变成了先按照文字水平放置的宽度计算，然后再旋转，导致echarts2里面显示的刻度文字远远多于echarts3里面的。

**Comment by 241382976** [comment]
遇到同样的问题，求大神解决

**Comment by 18262282746** [comment]
interval设为0就行，看API
