### ISSUE TITLE
地图里的省份包里面没有台湾省，【不谈政治】

### ISSUE THREAD

**Issue by silencelyn** [ecomfe/echarts#4173]
http://echarts.baidu.com/download-map.html

**Comment by wangboshun** [comment]
确实没有

**Comment by hiyangguo** [comment]
以前2.x版本的时候 是有台湾省地图的( 虽然没有详细到省下的市)。我看源码里的地图的注册配置是加密的。难道官方不能提供一个台湾的json文件么

**Comment by silencelyn** [comment]
@hiyangguo 是的，我也是2.x升上来，做地图联动，无意点到台湾省，

**Comment by hiyangguo** [comment]
@silencelyn 我目前的做法是 判断 如果是台湾省直接`return`  还有南海  也要`return`

**Comment by pissang** [comment]
@hiyangguo 2 里的地图文件也是能用的

**Comment by wu11106** [comment]
我一人去吧

2016年9月29日星期四，Gray <notifications@github.com> 写道：

**Comment by hiyangguo** [comment]
@pissang 我没找到 没加密的地图文件，v2仓库里的json 都是加密的。 麻烦给个地址 好么

**Comment by pissang** [comment]
不是加密，就是用 UTF-8 压缩了一下，3 也可以使用

**Comment by wu11106** [comment]
难道一个员工开车都不行，开到就近都行？

2016年9月29日星期四，Gray <notifications@github.com> 写道：

**Comment by wu11106** [comment]
他过来也可以

2016年9月29日星期四，Gray <notifications@github.com> 写道：

**Comment by wu11106** [comment]
亲爱的，我们这里，是共众场所，每天很多人来人往，以前人山人海

2016年10月12日星期三，YINGHUI WU <wu11106025@gmail.com> 写道：

**Comment by wu11106** [comment]
我去他们都不会给，又不懂路，站都站不起来

2016年10月12日星期三，Yi Shen <notifications@github.com> 写道：

**Comment by hiyangguo** [comment]
@pissang 好的 谢谢

**Comment by ppker** [comment]
哈哈哈 我也来了
