### ISSUE TITLE
Line data中有null值时，Line不连线

### ISSUE THREAD

**Issue by xiaogaobo** [ecomfe/echarts#4176]
#### 问题简述 (One-line summary)
配置：
series: [
         {
                    name: 'Attempted Target%',
                    data: data.attempted_target,
                    type: 'line',
                    yAxisIndex: 1,
                    symbol:'triangle',
                    symbolSize: 10,
                    itemStyle:{
                      normal:{color:'#2b28fa'}
                    }
                }
   ......
]
data.attempted_target = [20, null, null, null, null, null, null, null, null, 60, null, null, null, null, null, null, null, null, null, 80, null, null, null, null, null, null, null, null, null, null, null, 100, null, null, null, null, null, 100]

render后效果如：
![line](https://cloud.githubusercontent.com/assets/7420321/18979911/a0df6dce-8701-11e6-838b-937b1b3c33c7.png)

**几个没有连接起来！**
是有其他配置项？还是echarts的bug？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.3
+ 浏览器类型和版本 (Browser version): Google Chrome 53.0.2785.116 (64-bit)
+ 操作系统类型和版本 (OS Version): Ubuntu 14.04 LTS

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.connectNulls
