### ISSUE TITLE
無法更新同類型的series name

### ISSUE THREAD

**Issue by zerowhz** [ecomfe/echarts#4177]
#### 问题简述 (One-line summary)
執行：
myChart.setOption({ series:[{ name:'xxx' ,data:[1,2,3,4,5]}] });
從console 裏面看到
![image](https://cloud.githubusercontent.com/assets/22536858/18981085/87ab7198-870d-11e6-9fcf-6d49c93d8bb5.png) seriesname 沒有改變。如果把type 換成其他類型，如bar就改了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option ={
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {
                formatter:function(p){ console.log(p); }
            },
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'line',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

```

**Comment by 100pah** [comment]
Fixed by <https://github.com/ecomfe/echarts/commit/fbc81cbe26e7686b3532b7dc873608b684553eaa>
