### ISSUE TITLE
is it possible to add an hyperlink in one element of Sankey data??

### ISSUE THREAD

**Issue by emilioag** [ecomfe/echarts#4179]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
Yes you can add a link by event handling.
```js
myChart.on('click', function (e) { window.open(...); })
```

**Comment by derbestederbesten** [comment]
Is it also possible to add a link for some yAxis (category) values?
Like in:
`yAxis : [ { data: [
    'Jav', 'Feb', 'Mar',
     {
        value:'Apr',        //Text content, if the split name formatter is specified, this value will be passed in as a template variable value ​​or parameter.
        textStyle:{                 //see textStyle
            color : 'red'
            ...
        }
     },
    'May', '...'
]}]
`
??
