### ISSUE TITLE
echarts中有谁有全国高速公路路线的数据吗？

### ISSUE THREAD

**Issue by qingchengfanfan** [ecomfe/echarts#4184]
#### 问题简述 (One-line summary)
有人有全国高速公路的数据，想实现跟实例中 北京公交路线类似的效果，但是没有高速公路路线数据。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):osx10.11.6

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
能够提供一个全国高速公路路线数据

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
没有
