### ISSUE TITLE
Echarts2.0在IE8下面没有过渡动画效果了

### ISSUE THREAD

**Issue by yyang5** [ecomfe/echarts#4187]
#### 问题简述 (One-line summary)
Echart2.0在IE8下没有过渡动画效果了。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 2.2.7
+ 浏览器类型和版本 (Browser version): IE8
+ 操作系统类型和版本 (OS Version): Windows  XP

#### 重现步骤 (Steps to reproduce)
1. 在IE8下运行Echarts官方

#### 期望结果 (Expected behaviour)
有像chrome浏览器一样的过渡动画效果。

#### 可能哪里有问题 (What went wrong)
由于IE8性能限制，无法支持过渡动画效果。

**Comment by pissang** [comment]
echarts 2 在 IE8 中会强制关闭动画，echarts 3 对 IE8 的动画性能做了优化所以可以选择开启
