### ISSUE TITLE
echarts3如何在坐标轴上添加点击事件

### ISSUE THREAD

**Issue by lizhx123** [ecomfe/echarts#4201]
#### 问题简述 (One-line summary)
应用echarts3制作的简单柱状图，在图形上添加了点击事件，我现在需要在x坐标轴上也添加点击事件，echarts2上有 axisLabel : {clickable:true}事件，升级后是不是去掉了，还有就是在同一个图表中可以加多个点击事件吗？？
不胜感激！！！！

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by yadongxie150** [comment]
triggerEvent: true,
