### ISSUE TITLE
div高度初始化必须指定不能使用百分比？

### ISSUE THREAD

**Issue by lingbage** [ecomfe/echarts#4202]
我想让图表根据浏览器的大小进行自动调整，所以将div的高度设置成了50%
div id="main" style="height:100%"></div>”
然后就收到错误提示：Dom’s width & height should be ready before init.
这里必须要指定数值，而不能使用百分比吗？
如果想使用百分比有什么解决方法吗？

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/4145
