### ISSUE TITLE
桑基图想实现roam参数的滚动效果

### ISSUE THREAD

**Issue by huyongdi** [ecomfe/echarts#4208]
![image](https://cloud.githubusercontent.com/assets/16769181/19232353/d012e086-8f11-11e6-80e6-520df5abca38.png)

roam在配置项API里面只有四种情况能用？
要是桑基图（sankey）也想实现类似的效果能通过本插件简单的实现？
麻烦解答一下~

**Comment by pissang** [comment]
暂时不行

**Comment by huyongdi** [comment]
还想请问一个简单的问题，麻烦有空的时候解答一下
![image](https://cloud.githubusercontent.com/assets/16769181/19259764/0edca1da-8fb7-11e6-9f16-16d928e712f9.png)
图中节点的顺序可以改变吗？
