### ISSUE TITLE
轴类型为time的拆线图，怎么用visualMap去按时间段进行折线配色？

### ISSUE THREAD

**Issue by warlock-lv** [ecomfe/echarts#4225]
x轴类型为time， series 下 data 但是这样 [['2016-08-11 06:55:12', '2', 1470869712] , ……后面的数据略……]
其中 第三个值 1470869712， 为第一个值的转换结果
http://echarts.baidu.com/option.html#series-line.data
上边链接 文档中写到：每一项数值数组从第三个值开始可以表示数据的其它维度，配合 visualMap 组件可以将指定的一个或多个维度映射到颜色。
那么 我配置我的visualMap如下：
visualMap : {
        type : 'piecewise',
        dimension : 2,
        pieces : [
                {max: 1470869712, min: 1470869699},
                {max: 1470869699, min: 1470869681}, 
                {max: 1470869681, min: 1470869669},
                {max: 1470869669, min: 1470869618}],
        color : ['red', 'blue', 'red', 'blue'],
}
以上的方式，并没有得到  我想要的 红蓝 交替的折线效果图。
请问 要怎么做才能得到想要的图形呢？

**Comment by 100pah** [comment]
在折线图中，只能在 x、y 两个维度（即 dimension 为 0 或 1）上做 visualMap。
参见：<http://echarts.baidu.com/demo.html#line-aqi>

**Comment by warlock-lv** [comment]
![image](https://cloud.githubusercontent.com/assets/19185428/19427453/9cbcdf56-9476-11e6-93f8-405c0f0354de.png)
按照官方文档上的说法，应该不只两个维度吧

**Comment by 100pah** [comment]
折线图比较特殊，只能两个维度。而且折线图，如何在第三个维度上映射呢？
