### ISSUE TITLE
请教一下，桑吉图links的排序问题

### ISSUE THREAD

**Issue by huyongdi** [ecomfe/echarts#4228]
![image](https://cloud.githubusercontent.com/assets/16769181/19294402/c1ecc424-905e-11e6-8bed-ae09b1adb6ed.png)
如图中，我想让TMA150和TMA500的节点处于同一垂直线，但是由于TMA150没有后续，TMA500有后续，导致TMA500处于第二层级，TMA150和TEL处于同一层级了。

**Comment by 100pah** [comment]
请提供完整的 option
