### ISSUE TITLE
请问能否通过代码触发类似鼠标悬停在折线图上时，出现的那条竖线？

### ISSUE THREAD

**Issue by Kupid** [ecomfe/echarts#4231]
折线图，鼠标悬停时，会有tooltip,并且tooltip旁边会有一条垂直于x轴的标记线。
请问，能否通过代码让该线标记在某位置？

场景：
以官网的一周温度折线图为例，y轴气温，x轴星期。
当用户在某系统中操作和周三相关的数据时，图例自动就把竖线绘在周三处。
（类似于模拟鼠标悬停在图标周三的位置）

望指教。

**Comment by 100pah** [comment]
参见：<http://echarts.baidu.com/api.html#action.tooltip>

**Comment by Kupid** [comment]
懂了，非常感谢。 All in best.
