### ISSUE TITLE
请教如何去掉鼠标悬浮事件（如图）

### ISSUE THREAD

**Issue by huyongdi** [ecomfe/echarts#4232]
![image](https://cloud.githubusercontent.com/assets/16769181/19299068/adf799b4-9084-11e6-8248-b45890651d3a.png)
![image](https://cloud.githubusercontent.com/assets/16769181/19299073/b3a86ee2-9084-11e6-9701-640d05bc2171.png)

如图 放在连接线上（第一个图）和放在节点上（第二个图），都会出现悬浮的灰色背景框，如何去掉这个框，悬浮什么也不显示？

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#tooltip
