### ISSUE TITLE
鼠标进入提示框浮层中进行交互，如何添加事件？比如点击弹出另外一个div?

### ISSUE THREAD

**Issue by sadydai** [ecomfe/echarts#4234]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#tooltip.formatter>

浮层中自己定制 html 即可。
