### ISSUE TITLE
【BUG】JS触发饼图的pieUnSelect，pieSelect无效

### ISSUE THREAD

**Issue by evilbdef** [ecomfe/echarts#4242]
#### 问题简述 (One-line summary)

通过dispatchAction方式触发饼图选中、取消选中指定的扇形，完全没有发应，
myChart.dispatchAction({
    type: 'pieUnSelect'
});
myChart..dispatchAction({
    type: 'pieSelect',
    dataIndex : 0,
    //dataIndex : [0]
});
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3.2.3
- 浏览器类型和版本 (Browser version):chrome 51
- 操作系统类型和版本 (OS Version): win10
#### 重现步骤 (Steps to reproduce)

1.请看简述
#### 期望结果 (Expected behaviour)

可以选中指定扇形
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by evilbdef** [comment]
什么时候能发下个版本修复一下呢？大大

**Comment by 100pah** [comment]
暂时可先用 name 来索引，会有效果：

```js
chart.dispatchAction({type: 'pieSelect', name: 'xxx'});
```

**Comment by hyy1115** [comment]
我也遇到这种不能触发的情况，似乎这是一个无效的配置。

**Comment by runfan** [comment]
```  javascript
 series: [
            {
                // name: '访问来源',
                type: 'pie',
                selectedMode:'single',//这个很重要，如果不设置，定义要选中关闭，会导致pieselectedchange事件无效
        }
]

```
其实这个不BUG，而是文档没有说明清楚
这个问题同样出现在其他的图表中

**Comment by gbyuxia** [comment]
selectedMode:'single',  和name都分别试过，并没有起作用

**Comment by rancui** [comment]
问题简述 (One-line summary)

通过dispatchAction方式触发饼图选中、取消选中指定的扇形，完全没有发应，

myChart..dispatchAction({
     type: 'pieselected',
     seriesName:'累积客户签约量',
     dataIndex : 0,

});

版本及环境 (Version & Environment)

ECharts 版本 (ECharts version): 3.6.1
浏览器类型和版本 (Browser version):chrome  55.0.2883.87
操作系统类型和版本 (OS Version): win7
重现步骤 (Steps to reproduce)

1.请看简述

期望结果 (Expected behaviour)

可以选中指定扇形

**Comment by eaminhu** [comment]
遇到同样的问题，上面几个同学有没有解决呀？

**Comment by Ovilia** [comment]
@eaminhu 看 @runfan 的解决方案

**Comment by mengxy** [comment]
正好处理这个问题看到这个issue，把测试好的 demo 分享给大家。
问题就是文档不准确，name 可用，dataIndex 不可用。
```javascript
myChart.dispatchAction({
  type: 'pieSelect',
  seriesIndex: 0,
  name: option.series[0].data[app.currentIndex].name,
});
```
https://gist.github.com/mengxy/3b6027030fe2d0eefd808a91497346ef

**Comment by rancui** [comment]
你好，链接打不开，请问示例中的app指的是啥？

**Comment by mengxy** [comment]
@rancui 修改了一下，就是 data 的 index

gist 可能需要翻墙才能打开

**Comment by Ovilia** [comment]
Bug 已修复：https://github.com/ecomfe/echarts/commit/3461395795329fa6964649333211cc5e73f02189

从下一个版本起，可以使用 `dataIndex` 或 `name` 来索引，如果两个同时设置，`name` 将被忽略。

**Comment by rancui** [comment]
你好，请问下个版本啥时候发布呀？

**Comment by Ovilia** [comment]
下周
