### ISSUE TITLE
legend[data]为数组时报错

### ISSUE THREAD

**Issue by Shellbye** [ecomfe/echarts#4244]
#### 问题简述 (One-line summary)
我的legend里面的data是一个数组[20,50,100,........]，执行时报错：
`20 series not exists. Legend data should be same with series name or data name.`

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 可能哪里有问题 (What went wrong)
将数字全部转化为字符串就可以了

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
用字符串不要用数字

**Comment by Shellbye** [comment]
@pissang 这是必须用字符串是出于什么考虑呢？

**Comment by pissang** [comment]
因为系列的名字必须是字符串，如果要兼容非字符串格式的处理会比较麻烦

**Comment by Shellbye** [comment]
如果是这样是不是需要一个正确的错误提示？目前如果使用的不是字符串，报错并没有说明这一点。

**Comment by pissang** [comment]
确实，其实我们是一直想要做一个整个 option 的 validator 的，但是因为优先级比较低所以暂时还没做

**Comment by Shellbye** [comment]
辛苦了。echarts确实是非常好用的
