### ISSUE TITLE
在极坐标中，希望实现从外围向中心半径轴的坐标值递减，请问怎么实现？设置了radiusAxis.inverse=true无效

### ISSUE THREAD

**Issue by 651778286** [ecomfe/echarts#4253]
在极坐标中，希望实现从外围向中心半径轴的坐标值递减，请问怎么实现？设置了radiusAxis.inverse=true无效

**Comment by 651778286** [comment]
就是半径轴坐标值反转，请问能够通过配置直接实现吗？

**Comment by 100pah** [comment]
polar 暂时没有支持 inverse。

可以尝试使用 radius.formatter = function () { ... 修改 label 显示的值 }
来 hack 一下。

**Comment by 651778286** [comment]
好的，谢谢
