### ISSUE TITLE
Is it possible to create a 'step line chart' with echarts?

### ISSUE THREAD

**Issue by mrcybermac** [ecomfe/echarts#4259]
#### 问题简述 (One-line summary)
Is it possible to create a 'step line chart' with echarts?

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 期望结果 (Expected behaviour)
I can't find any documentation or examples for a step line area chart that would look something like this:
<img width="611" alt="screen shot 2016-10-14 at 4 18 01 pm" src="https://cloud.githubusercontent.com/assets/6118944/19404254/d6edb280-9229-11e6-9536-80523edd748c.png">

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
FYI <http://echarts.baidu.com/demo.html#line-step>

**Comment by evan-coygo** [comment]
that linked example solves for if your x-axis is of type "category", what about if your x-axis is of type "value" and your series data looks something like this?

```js
xAxis : [
        {
            type : 'value',
            scale: true
        }
    ],
    yAxis : [
        {
            type : 'value',
            scale: true
        }
    ],
series: {
            type:'line',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data: [
                [90,45],
                [92,40],
                [94,25],
                [97,20],
                [98,17],
                [98.5,13],
                [99,4],
                [99.5, 1],
                [100,0],
                [100.5, 1],
                [101, 3],
                [102,5],
                [102.5, 8],
                [103,18],
                [104,23],
                [105,29],
                [107,34],
                [108,39]
            ]
        }
```
