### ISSUE TITLE
tooltip 里面如何设置链接或者载入有链接的指示图跳到另一个页面

### ISSUE THREAD

**Issue by shoneSolomon** [ecomfe/echarts#4268]
#### 问题简述 (One-line summary)
tooltip可以一直显示了，但是想要点击tooltip 跳转列表，出现数据列表， 里面如何设置链接或者载入有链接的指示图跳到另一个页面

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):all
+ 操作系统类型和版本 (OS Version):windows

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/4234
