### ISSUE TITLE
Echart3  symbol能否用emptyCircle

### ISSUE THREAD

**Issue by chm74** [ecomfe/echarts#4271]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以

**Comment by chm74** [comment]
{
						name: 'Top',
						type: 'effectScatter',
						coordinateSystem: 'geo',
						data: convertIOCData(this.props.data.ioc),
						markPoint:{
						    symbol:'emptyCircle',
							symbolSize : 10,
							effect : {
								show: true,
								type: 'scale',
								shadowBlur : 0
							}
						},
						hoverAnimation: true,
						label: {
							normal: {
								formatter: '{b}',
								position: 'right',
								show: false,
								textStyle:{
									color:'#000000'
								}
							}
						},
						itemStyle: {
							normal: {
								color: '#f4e925',
								shadowBlur: 10,
								shadowColor: '#333'
							}
						},
						zlevel: 1
				   }

**Comment by chm74** [comment]
效果不对呀，echart3 doc里面symbol 没有支持这个emptyCircle的效果。我要怎么写
