### ISSUE TITLE
地图相关问题

### ISSUE THREAD

**Issue by gongchao** [ecomfe/echarts#4275]
echarts 3 
1、地图 label 设置为 show ，位置偏离，尤其是一些省级地图，字和字已经重叠。

2、echarts 3 地图下钻，china点击后事件传入的是中文，打包下载来的却是拼音，还要一个一个的人工去改，好麻烦啊，我现在要下钻到 地级市，简直麻烦死了，地级市地图下载不方便，需要一个一个的下载。。。

不知道有没有其它解决方法？

**Comment by freelabel** [comment]
同求。

**Comment by gongchao** [comment]
@freelabel 数据在高德拿到了，但是文字偏移严重～求解

**Comment by shibandae** [comment]
同样问题，导致很多地市名称叠加。目测应该是将省会城市名字放到实际地图的位置了，而不是该区域的中间。echarts2中 没有出现这样的情况，3中比较严重地图看起来很糙！

**Comment by pissang** [comment]
把 geoJson 中每个省份的 center 去掉就会自动取中心位置了
