### ISSUE TITLE
线图中，并未按照手册中写的能自动计算设置Y轴的最小值

### ISSUE THREAD

**Issue by Rilee** [ecomfe/echarts#4279]
#### 问题简述 (One-line summary)
以下是线图中，官方对于Y轴的设置描述

yAxis.min number, string
[ default: 'auto' ]
坐标轴刻度最小值，在类目轴中无效。
可以设置成特殊值 'dataMin'，此时取数据在该轴上的最小值作为最小刻度。
**_不设置时会自动计算最小值保证坐标轴刻度的均匀分布。_**

其中说不设置时是自动计算最小值，但是现在实际情况都是从0开始的，这样就导致如果数据值都较大而且差距不大时，就会导致线飘在最上面，下面都是空，很不均匀

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):Google chrome 53.0.2785.143 m
+ 操作系统类型和版本 (OS Version):windows 10

#### 重现步骤 (Steps to reproduce)
1.打开线图http://echarts.baidu.com/demo.html#line-stack
2.设置一个序列，而且值都在2000-2500之间
3.保持yAxis的默认设置
4.重现

#### 期望结果 (Expected behaviour)

应该如官方描述的那样自动计算最小值作为y轴的最小值，从而使整图更均匀

#### 可能哪里有问题 (What went wrong)

没有计算吧

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#yAxis.scale>
设为 true 就不会默认包含零了。
