### ISSUE TITLE
新手提问:怎么让饼图的一块保持选中状态，撤去选中状态？

### ISSUE THREAD

**Issue by xx1595140265** [ecomfe/echarts#4283]
如题，想做这样的效果，点击某个区块后让其保持选中凸起的状态，再次点击别的区块切换选中状态。版本3.1.0。

**Comment by 100pah** [comment]
<http://echarts.baidu.com/demo.html#pie-pattern>

**Comment by xx1595140265** [comment]
@100pah 请问我想实现饼图渲染出来时有一个默认的选中区域能实现吗？

**Comment by xx1595140265** [comment]
我自己找到了，在data里面selected: true
