### ISSUE TITLE
请问官网中的例子里的app是什么？

### ISSUE THREAD

**Issue by adamcavendish** [ecomfe/echarts#4284]
请问官网中的例子里的app是什么？谢谢！

**Comment by chaegumi** [comment]
鬼看得懂你说的是啥

**Comment by adamcavendish** [comment]
@chaegumi 你说的有道理

**Comment by adamcavendish** [comment]
例如：
http://echarts.baidu.com/demo.html#bubble-gradient

代码范例 `app.title = '气泡图';` 其中的app是指的什么呢？

**Comment by chaegumi** [comment]
无用数据

**Comment by adamcavendish** [comment]
http://echarts.baidu.com/demo.html#scatter-nutrients

貌似这个是使用app来控制xAxis和yAxis选择了什么类型的数据，即schema

**Comment by chaegumi** [comment]
只是一个js变量而已呀，你想太多了。

**Comment by adamcavendish** [comment]
对了，有没有echarts官网的源码可以看看？

**Comment by chaegumi** [comment]
https://github.com/ecomfe?utf8=%E2%9C%93&query=echarts

**Comment by adamcavendish** [comment]
你给我一个搜索链接没有用啊。。。我想知道那个官网的examples里的那个scatter-nutrients的全部源码诶。。。

**Comment by chaegumi** [comment]
回家学好js再说，他里边的例子都是可以直接运行的。那里边的代码就是options而已。

发自我的 iPhone

**Comment by pissang** [comment]
app 是官方示例的环境变量，自己例子里不需要用到，删除就行

**Comment by cehceh1** [comment]
您好，scatter nutrients的example全部源代码您那里有了吗？
