### ISSUE TITLE
在父级元素使用了transform: scale后,导致鼠标移至图表上不能正确响应鼠标事件

### ISSUE THREAD

**Issue by cui13aiwang** [ecomfe/echarts#4292]
鼠标移至图表上,会根据transform: scale值的大小不同发生不同程度的偏移,无法正确响应

**Comment by pissang** [comment]
新版本修复这个问题

**Comment by HeGanjie** [comment]
我使用了 [zoomooz.js](http://jaukia.github.io/zoomooz/) 来放大 echarts 图表，遇到了同样的问题

**Comment by pissang** [comment]
最新版本 3.3.1 已修复

**Comment by HeGanjie** [comment]
@pissang 图表放大后会变得模糊，有 API 来调整 dpi 吗？或者其他类似的解决办法也可以

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echarts.init 可以设置更大的 devicePixelRatio
