### ISSUE TITLE
官网实例是如何实现图表宽高随浏览器窗口变化而自适应的？

### ISSUE THREAD

**Issue by maoyr** [ecomfe/echarts#4295]
#### 问题简述 (One-line summary)
官网实例是如何实现图表随浏览器窗口变化而自适应的？
DOM宽高设置为百分比？
浏览器窗口变化时调用resize？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win7  64位

**Comment by pissang** [comment]
监听浏览器的 resize 事件然后调用 `myChart.resize()`

**Comment by maoyr** [comment]
最初指定DOM：<div id="main" style="height:300px;"></div>，添加监听后调用 myChart.resize()，宽度可以随之正常变化，但高度始终是300px，是在bootstrap布局里放置的图表，百分比似乎不适用？

如果获取浏览器变化后的高度再赋值给DOM，就会重新初始化生成一遍图表，大小是正确的，但是效果不如官网好。

请问这样的话该怎么解决？

**Comment by maoyr** [comment]
<div id="main" style="height:300px;"></div>
<div id="main" style="height:300px;"></div>

**Comment by maoyr** [comment]
`<div id="main" style="height:300px;"></div>`

**Comment by pissang** [comment]
百分比怎么不适用了，写死高度是没法自适应的

**Comment by maoyr** [comment]
在bootstrap里，row没有固定高度···
`height:100%`  撑起的高度太小，图表不能正常展示
`height:0px;padding-bottom:100%`  报错找不到Dom的width、height

**Comment by warlock-lv** [comment]
类似的问题，两个实例，为什么只有一个实例随着浏览器窗口的变化而变化，而另一个不变。要怎么写？
myChart.setOption(option);
myChart2.setOption(option2);
window.onresize = myChart.resize;
window2.onresize = myChart2.resize;

**Comment by pissang** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by 1304800050** [comment]
我是用过修改css中的zoom 来控制页面缩放的、但是放大后  图表功能区错位，重新调用myChart.resize依旧无效如何解决代码如下：


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="echarts.js"></script>
	<script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
    
    <div id="main" style="width:600px;height:400px;"></div>
	<input id="11" onclick="zoomout()">
	<input id="22" onclick="zoomin()">
	
    <script type="text/javascript">
		var myChart = null;
		$(document).ready(function(){
			cart();
		});
		
		$(window).resize(function () {          //当浏览器大小变化时
			myChart.resize;
		});
	
		var size = 1.0;  
		function zoomout() {  
			size = size + 0.1;  
			set(); 
		}  

		function zoomin() {  
			size = size - 0.1;  
			set();  
		}  

		function set() {
			document.body.style.zoom = size;
			myChart.resize;
		} 
	
		function cart(){
			// 基于准备好的dom，初始化echarts实例
			myChart = echarts.init(document.getElementById('main'));

			// 指定图表的配置项和数据
			var option = {
				title: {
					text: 'ECharts 入门示例'
				},
				toolbox: {
					show : true,
					feature : {
						dataView : {show: true, readOnly: false},
						magicType : {show: true, type: ['line', 'bar']},
						restore : {show: true},
						saveAsImage : {show: true}
					}
				},
				tooltip: {},
				legend: {
					data:['销量']
				},
				xAxis: {
					data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
				},
				yAxis: {},
				series: [{
					name: '销量',
					type: 'bar',
					data: [5, 20, 36, 10, 10, 20]
				}]
			};

			// 使用刚指定的配置项和数据显示图表。
			myChart.setOption(option);
		}
        
    </script>
</body>
</html>

**Comment by mxy2316868975javascript** [comment]
![tim 20170630211715](https://user-images.githubusercontent.com/15233384/27737132-9aca5566-5dd9-11e7-95e9-5a8f4c62eb05.png)


请问这是什么原因导致的
