### ISSUE TITLE
坐标轴是否可以进行定制？

### ISSUE THREAD

**Issue by QiXiaoyin** [ecomfe/echarts#4302]
问题简述 (One-line summary)

就是x坐标轴（time型坐标轴）是否可以设置只显示开始和结束的两个标签？如果x坐标轴本身不能实现，有其他方法可以实现吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):android,ios
+ 操作系统类型和版本 (OS Version):android,ios

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#xAxis.splitNumber

**Comment by QiXiaoyin** [comment]
谢谢你，问题可以解决了
