### ISSUE TITLE
Echarts 是否支持对数据进行多次group后绘图

### ISSUE THREAD

**Issue by ybbdaidai** [ecomfe/echarts#4305]
#### 问题简述 (One-line summary)
Echarts 是否支持如Excel的pivot-chart里，对数据进行多次group后绘图，如下图示：

![userstorycountbystatus](https://cloud.githubusercontent.com/assets/13548983/19588181/a21b3dee-9796-11e6-894a-0aca8d9b864d.jpg)

**Comment by pissang** [comment]
你可以对数据预处理做 group

**Comment by ybbdaidai** [comment]
**多次**group的数据不是**一维**的，如图示这样的效果能配置出来么？

**Comment by pissang** [comment]
数据上你可以用三个系列，然后用空数据填满保证三个系列数据对齐，坐标轴暂时没法实现分类

**Comment by ybbdaidai** [comment]
谢了，请关。
