### ISSUE TITLE
两个option,两个myChart图例的话，浏览器窗口调整大小时，要怎么同时resize呢？

### ISSUE THREAD

**Issue by warlock-lv** [ecomfe/echarts#4309]
如题，我有两个chart图例在同一页面上，浏览器窗口调整大小时，要怎么同时resize呢？
myChart.setOption(option);
myChart2.setOption(option2);
window.onresize = myChart.resize;
window2.onresize = myChart2.resize;

**Comment by waitinghope** [comment]
你这是一个js的问题和echart关系不大啊。你要做的就是把每个echart的resize事件绑定到windows.resize就可以了。

**Comment by AndrewZheng** [comment]
window2.onresize  这是什么鬼 0.0
