### ISSUE TITLE
关于echart3 官网动画

### ISSUE THREAD

**Issue by NumerHero** [ecomfe/echarts#4311]
我是一个在校生，想研究图像的间补动画

看到[你们做的](http://echarts.baidu.com/index.html) 文字轨迹动画 很好看，想试着做出来

如果方便，不知道是否能给出源代码~ 
如不方便,能否给出学习资料(如何顺逆时针获取图形轨迹点集) ...etc

拜谢

**Comment by pissang** [comment]
可以参考 https://maxwellito.github.io/vivus/

**Comment by NumerHero** [comment]
感谢沈大侠 指点
