### ISSUE TITLE
如何设置极坐标边缘线的颜色？

### ISSUE THREAD

**Issue by 651778286** [ecomfe/echarts#4312]
如何设置极坐标边缘线的颜色？

![default](https://cloud.githubusercontent.com/assets/7576363/19634722/e14ac952-99ef-11e6-94af-dd802ff39a19.JPG)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#angleAxis.axisLine

**Comment by 651778286** [comment]
谢谢
