### ISSUE TITLE
在IE上热力图数值为0时label上的数字无法显示

### ISSUE THREAD

**Issue by ChandaZhou** [ecomfe/echarts#4315]
#### 问题简述 (One-line summary)

在IE上热力图数值为0时label上的数字无法显示，由于项目中head里加了“<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8"/>”用来兼容IE8的html
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):3.2.3
- 浏览器类型和版本 (Browser version):IE 10
- 操作系统类型和版本 (OS Version):windows 7
#### ECharts配置项 (ECharts option)

```
    var option = {
        tooltip: {
            position: 'top'
        },
        animation: false,
        grid: {
            height: '50%',
            y: '10%'
        },
        xAxis: {
            type: 'category',
            data: [1,2,3,4],
            splitArea: {
                show: true
            }
        },
        yAxis: {
            type: 'category',
            data: [1,2,3,4],
            splitArea: {
                show: true
            }
        },
        visualMap: {
            min: 0,
            max: 10,
            calculable: true,
            orient: 'horizontal',
            left: 'center',
            bottom: '15%'
        },
        series: [{
            name: 'Punch Card',
            type: 'heatmap',
            data: [[0,0,6],[0,1,0]],
            label: {
                normal: {
                    show: true,
                    textStyle: {
                        color: 'rgb(0,0,0)'
                    }
                }
            },
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }]
    };
```
#### 实例 (Other comments)

![1](https://cloud.githubusercontent.com/assets/17309468/19642929/49420262-9a1a-11e6-88a3-e2be6027bb22.PNG)

![default](https://cloud.githubusercontent.com/assets/17309468/19642501/3a8ee764-9a18-11e6-8c59-a25e3516cde9.PNG)

**Comment by ChandaZhou** [comment]
原因是在Path.prototype.brushVML方法里，
![default](https://cloud.githubusercontent.com/assets/17309468/20051399/c8f4e9d0-a509-11e6-928b-e22062a44777.PNG)当style.text=0时，判断后执行removeRectText而不是drawRectText，因此需要在if判断时再加一个条件
![default](https://cloud.githubusercontent.com/assets/17309468/20051464/19220f46-a50a-11e6-9676-a0bb39b5ed1b.PNG)。并且需要在drawRectText方法里将if (!text) {return;}改为if (text<0) {return;}不让0被过滤掉

**Comment by 100pah** [comment]
Fixed by <https://github.com/ecomfe/zrender/commit/8184344573ab4d697dd7b6133fad2c8521655c19>

**Comment by yelingfeng** [comment]
这bug貌似还有啊
官网例子chrome浏览器
![image](https://cloud.githubusercontent.com/assets/1932350/21558765/45ac8ade-ce7a-11e6-8274-898daa4003a0.png)
