### ISSUE TITLE
柱状图每个柱状显示不同的颜色？？

### ISSUE THREAD

**Issue by xunzhe12138** [ecomfe/echarts#4319]
#### 问题简述 (One-line summary)
5条数据，5条柱子显示不同的颜色

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![qq 20161025112930](https://cloud.githubusercontent.com/assets/23045277/19672099/63cf3d70-9aa6-11e6-912c-7acaf22f7806.png)

**Comment by pissang** [comment]
参考 http://gallery.echartsjs.com/editor.html?c=xB1_UkbAP，也可以专门设置 data 里的 itemStyle

**Comment by DanielWLam** [comment]
@pissang 有什么方法可以使用主题里面legend指定的颜色吗？而且这样hardcode有点不优雅，因为实际上并不知道会有多少条数据
