### ISSUE TITLE
仪表盘 能不能控制周边留白多少？

### ISSUE THREAD

**Issue by hanhui** [ecomfe/echarts#4320]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-gauge.radius

**Comment by zombieJ** [comment]
@pissang 如果startAngle和endAngle过小。比如半圆，表盘下面一大半都是空的。能否对grid进行支持？

**Comment by hanhui** [comment]
我使用ECHARTS感觉真是不错，但是你的这个问题我没有搞明白，好像是两个问题。最后一个问题我在一个图中使用过多个grid（如下图所示），但是没有使用仪表盘，

**Comment by hanhui** [comment]
我使用ECHARTS感觉真是不错，但是你的这个问题我没有搞明白，好像是两个问题。最后一个问题我在一个图中使用过多个grid（如下图所示），但是没有使用仪表盘，
