### ISSUE TITLE
What is the license of this solution?

### ISSUE THREAD

**Issue by drscg** [ecomfe/echarts#4322]
hi,
echart is wonderful.
I want to use it in my project.
What is the license of this solution?
thank you...

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/blob/master/LICENSE

You can free to use echarts in your project, including commercial project

**Comment by devldevelopment** [comment]
Is there any source code available for this: http://echarts.baidu.com/gallery/editor.html I want to perform java or javascript validation on the json just like the editor does.

**Comment by pissang** [comment]
We haven't  add the validation of JSON. Editor just try to run the javascript code, and throw an error if it fails.

**Comment by devldevelopment** [comment]
Thanks Yi, but can we download the source code for this
http://echarts.baidu.com/demo.html#bar-animation-delay? I want to also use
the examples json without having to copy-paste everything. Is this
website's source on github anywhere?
