### ISSUE TITLE
echarts3.0 的地图扩展,是否可以添加事件

### ISSUE THREAD

**Issue by isosky** [ecomfe/echarts#4323]
在echarts2.0的时候，可以通过扩展来获取echarts声明的bmap对象，添加marker或者line，然后直接对这些marker，line添加addEventListener，这样，展现的时候，有酷炫的marker和line，同时，单击这些marker和line也会有交互效果，想知道3.0是否可以实现这样的效果。

**Comment by pissang** [comment]
可以
