### ISSUE TITLE
axisLabel定义了formatter后，如果data为空数组，会输出undefined字符串到chart上

### ISSUE THREAD

**Issue by mirari** [ecomfe/echarts#4328]
#### 问题简述 (One-line summary)

根据用户查询动态生成chart时，有可能会出现无数据的情况，此时若data为空数组，只要axisLabel定义了formatter，就会输出undefined字符串到chart上；如果formatter没有定义，则可以按照预期显示空白。
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):v3.2.3
- 浏览器类型和版本 (Browser version):全部
- 操作系统类型和版本 (OS Version):全部
#### 重现步骤 (Steps to reproduce)

1.定义xAxis.axisLabel.formatter：
2.定义option.xAxis.data和option.series[0].data为空数组：
#### 期望结果 (Expected behaviour)

X轴显示空白
#### 可能哪里有问题 (What went wrong)

数组为空时axisLabel仍试图取值并显示一条数据
#### ECharts配置项 (ECharts option)

``` javascript
option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : [],
            axisTick: {
                alignWithLabel: true
            },
            axisLabel: {
                    formatter: '{value} 啦啦啦'
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[]
        }
    ]
};

```

**Comment by wuruihua** [comment]
formatter: function (params, ticket, callback) {
return 自定义；
}

**Comment by mirari** [comment]
如果要靠用函数写formatter来规避这个问题，那就意味着占位符的这种写法压根没法实用啊
