### ISSUE TITLE
echarts3 可以实现echarts2 markPoint 的闪动效果么？

### ISSUE THREAD

**Issue by xhusky** [ecomfe/echarts#4329]
echarts3 可以实现echarts2 markPoint 的闪动效果么？还是说只能用effectScatter 的唯一一个涟漪效果。。。

echarts2闪动效果实例：
http://echarts.baidu.com/echarts2/doc/example/map15.html

**Comment by pissang** [comment]
3 里暂时只有涟漪效果

**Comment by xhusky** [comment]
@pissang 感谢，那准备在后续版本中添加么？

**Comment by pissang** [comment]
会考虑加上

**Comment by evolutionjay** [comment]
同求，需求很高的。

**Comment by as13579e** [comment]
同求
