### ISSUE TITLE
symbol显示数量问题

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#4334]
#### 问题简述 (One-line summary)
现在的配置只有 showAllSymbol这一个选择，要不就是全部显示，要不就是跟随X轴的坐标的数量显示。能否，但是当X轴坐标较少而又想多显示几个symbol的时候就办不到了。这个有什么办法可以实现或者支持吗

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以单独设置每个数据的 symbol 是否显示

**Comment by iamwelk** [comment]
OK，明白了，谢谢~~

**Comment by qpxtWhite** [comment]
@pissang 
```
showAllSymbol: false,  //随主轴标签间隔隐藏策略。
data: [
    {value: 2, symbol: 'none'},
    {value: 3, symbol: 'emptyCircle'},
    ........
]
```
有一条数据我希望展示symbol，但是被主轴隐藏了，如何处理？
问题链接：[http://gallery.echartsjs.com/editor.html?c=xS1qdFCKQQ&v=1](http://gallery.echartsjs.com/editor.html?c=xS1qdFCKQQ&v=1)
