### ISSUE TITLE
饼图labelLine length 设置无效

### ISSUE THREAD

**Issue by fuacici** [ecomfe/echarts#4335]
#### 问题简述 (One-line summary)

饼图labelLine length 设置无效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.3
+ 浏览器类型和版本 (Browser version): chrome Version 54.0.2840.5
+ 操作系统类型和版本 (OS Version):mac 10.12

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
labelLine: {
	    normal: {
	        lineStyle: {
	            color: 'rgba(0, 0, 0, 1)',
	            width: 20,
	        },
	        length: 5000,
	        length2: 30,
	    }
	},

```

**Comment by pissang** [comment]
怎么设置的？

**Comment by fuacici** [comment]
labelLine: {
	    normal: {
	        lineStyle: {
	            color: 'rgba(0, 0, 0, 1)',
	            width: 20,
	        },
	        length: 5000,
	        length2: 30,
	    }
	},  谢谢！

**Comment by pissang** [comment]
我试了有效的

**Comment by fuacici** [comment]
这个实例里设置貌似都没有用，  http://echarts.baidu.com/gallery/editor.html?c=doc-example/pie-media ：  {
                    name:'面积模式',
                    type:'pie',
                    roseType : 'area',
                    lableLine: {
                        normal: {
                            show: false,
                            length: 1,
                            length2: 20,
                        },
                        emphasis: {
                            show: true
                        }
                    },
                    data:[
                        {value:10, name:'rose1'},
                        {value:5, name:'rose2'},
                        {value:15, name:'rose3'},
                        {value:25, name:'rose4'},
                        {value:20, name:'rose5'},
                        {value:35, name:'rose6'},
                        {value:30, name:'rose7'},
                        {value:40, name:'rose8'}
                    ]
                   
                }

**Comment by pissang** [comment]
是 labelLine 不是 lableLine

**Comment by fuacici** [comment]
额 抱歉。。 汗！。。 😅

**Comment by nickwang94** [comment]
如果是旭日图，配置labelLine会生效么
