### ISSUE TITLE
2张图表嵌入两个标签页中出现问题

### ISSUE THREAD

**Issue by BluesMardrid** [ecomfe/echarts#4336]
#### 问题简述 (One-line summary)
2张图表嵌入标签页中，初始化时第一张显示正常，第二张100%被压缩到100px，所以显示不正常，但选中第二个标签页时，放大缩小浏览器大小，第一个标签页的图表又不能正常显示。还有个问题是不能实时resize，resize总比鼠标慢一拍。看了之前有人问过此问题，API里面resize函数也说过：
echartsInstance.resize Function 
改变图表尺寸，在容器大小发生改变时需要手动调用。
Tip: 有时候图表会放在多个标签页里，那些初始隐藏的标签在初始化图表的时候应为获取不到容器的实际高宽，可能会绘制失败，因此在切换到该标签页时需要手动调用 resize 方法获取正确的高宽并且刷新画布。
但并没给出事例，所以还是无从下手。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.2.7
+ 浏览器类型和版本 (Browser version):IE11
+ 操作系统类型和版本 (OS Version):WINDOWS 10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 可能哪里有问题 (What went wrong)
切换标签页时需重新resize

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by mirari** [comment]
这不算BUG吧，window.resize肯定是要绑的，但是任何container只要是不可见的状态，执行resize时获取到的长宽为0，就会把chart的长宽也置为最小值.
我的解决办法是监听标签页切换事件，切换时手动调用resize再把长宽为0,0的chart重新放大到正常大小。
但是标签切换后能看到chart从左上角变大的这个动画效果是没法变了。
