### ISSUE TITLE
http://echarts.baidu.com/option.html无法访问

### ISSUE THREAD

**Issue by shikelong** [ecomfe/echarts#4341]
Echart 3文档的配置项手册在 ie11和最新
![2016-10-28_091849](https://cloud.githubusercontent.com/assets/4499997/19790971/9d3e729c-9cef-11e6-9460-3a8ba8a9398f.png)
版本chrome下均无法访问。  内容区域显示一片空白。

**Comment by pissang** [comment]
看下是否有报错

**Comment by shikelong** [comment]
抱歉 突然又好了 可能是网络问题。  console中一直都没有error.
