### ISSUE TITLE
一次画多个饼图或者漏斗图的是候好像没有办法区分每个饼图所属序列

### ISSUE THREAD

**Issue by yzhang921** [ecomfe/echarts#4342]
![image](https://cloud.githubusercontent.com/assets/6037522/19791113/b6706954-9cf0-11e6-857f-d23a1f2fe59b.png)

期望有办法在每个饼图下面加一个小标题

**Comment by pissang** [comment]
可以用多个标题组件，参考 http://echarts.baidu.com/gallery/editor.html?c=line-easing

**Comment by yzhang921** [comment]
@pissang 谢谢答复，这个方案暂时可以解决问题，以后EChart的多图表布局能够做成自动调整的会更加好，现在多图通过自己调节偏移有点痛苦
