### ISSUE TITLE
怎么上中下放三个图，共用一个x轴

### ISSUE THREAD

**Issue by shengxinjing** [ecomfe/echarts#4343]
#### 问题简述 (One-line summary)

怎么上中下放三个图，共用一个x轴
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 3
- 浏览器类型和版本 (Browser version): chrome
- 操作系统类型和版本 (OS Version): 
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
可以放三个轴后隐藏另外两个

**Comment by 9590** [comment]
可是，如果三个x轴是不对齐的，还有包含关系的呢？
