### ISSUE TITLE
echart3有透视图表的功能么？

### ISSUE THREAD

**Issue by limaozhan** [ecomfe/echarts#4349]
#### 问题简述 (One-line summary)

echart3有透视图表的功能么？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): echart3
- 浏览器类型和版本 (Browser version): ie8,ie9,ie10及以上 ,chrome
- 操作系统类型和版本 (OS Version): windows, linux 
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```
#### 其他信息 (Other comments)

看echarts的官方介绍，都是图形化的内容，有数据表格、数据透视图表的功能么？
例如有没有类似excel的表格功能，然后可以设置统计项，聚合之类的。

数据透视图表能和echarts3现有的统计图形联动么？

**Comment by pissang** [comment]
没有，echarts 本身不负责数据的处理，不过日后会推出有相关的插件做这件事
