### ISSUE TITLE
echarts3中柱状图 柱子颜色怎么用渐变色？

### ISSUE THREAD

**Issue by 771752687** [ecomfe/echarts#4351]
#### 问题简述 (One-line summary)

echarts3中柱状图 柱子颜色怎么用渐变色？
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):
- 浏览器类型和版本 (Browser version):
- 操作系统类型和版本 (OS Version):
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by Carol1992** [comment]
// 线性渐变，前四个参数分别是 x0, y0, x2, y2, 范围从 0 - 1，相当于在图形包围盒中的百分比，如果最后一个参数传 `true`，则该四个值是绝对的像素位置
color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
  offset: 0, color: 'red' // 0% 处的颜色
}, {
  offset: 1, color: 'blue' // 100% 处的颜色
}], false)
// 径向渐变，前三个参数分别是圆心 x, y 和半径，取值同线性渐变
color: new echarts.graphic.RadialGradient(0.5, 0.5, 0.5, [...], false)
// 纹理填充
color: new echarts.graphic.Pattern(
  imageDom, // 支持为 HTMLImageElement, HTMLCanvasElement，不支持路径字符串
  'repeat' // 是否平铺, 可以是 repeat-x, repeat-y, no-repeat
)

**Comment by 100pah** [comment]
<http://echarts.baidu.com/demo.html#bar-gradient>

**Comment by shady7shen** [comment]
echarts.graphic.Pattern  什么时候可以支持？
