### ISSUE TITLE
在Android页面中如何传省市值数组给essets里的map.html?

### ISSUE THREAD

**Issue by xubuhang** [ecomfe/echarts#4358]
可以调用函数变更js内显示的区域，怎么传入数组list给map显示呀
<img width="552" alt="qq20161030-0 2x" src="https://cloud.githubusercontent.com/assets/4189632/19833873/55fb2b78-9e84-11e6-9097-0f0aece79573.png">
<img width="513" alt="qq20161030-1 2x" src="https://cloud.githubusercontent.com/assets/4189632/19833874/56e7bc54-9e84-11e6-92cb-18556a55ac79.png">

，请教一下。

**Comment by pissang** [comment]
非 echarts 相关问题
