### ISSUE TITLE
echarts2每秒addMarkLine动态添加线超级卡顿的原因是什么呢

### ISSUE THREAD

**Issue by zkdo** [ecomfe/echarts#4361]
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version):echarts2
- 浏览器类型和版本 (Browser version):chrome
- 操作系统类型和版本 (OS Version):win10
#### 重现步骤 (Steps to reproduce)

1.
2.
#### ECharts配置项 (ECharts option)

``` javascript
option = {

}

```

**Comment by pissang** [comment]
性能不够，要不减少标线数量，要不增加添加标线的间隔时间
