### ISSUE TITLE
echarts 折线图 数据量很少时 展示错误

### ISSUE THREAD

**Issue by DFreeMind** [ecomfe/echarts#4364]
#### 问题简述 (One-line summary)
折线图在数据量较少的情况下 数据展示是正确的 但折线图显示确实错去的

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): chrome 45.0
+ 操作系统类型和版本 (OS Version): win10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![qq 20161031145439](https://cloud.githubusercontent.com/assets/5103338/19846475/9544b582-9f7a-11e6-9c5b-c17ec227488a.png)

**Comment by DFreeMind** [comment]
![qq 20161031145439](https://cloud.githubusercontent.com/assets/5103338/19846454/5b740344-9f7a-11e6-8a15-3120d9af4ab5.png)

**Comment by pissang** [comment]
跟数据量没关系，因为你加了 stack 属性
