### ISSUE TITLE
地图中怎么设置lines中线的样式

### ISSUE THREAD

**Issue by newEchartster** [ecomfe/echarts#4366]
#### 问题简述 (One-line summary)
我想让两个坐标点的连线显示出铁路那样的样式，怎么设置呢？
color: new echarts.graphic.LinearGradient感觉这个可以实现，但是不知道这个方法怎么用的

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.3
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

**Comment by pissang** [comment]
暂时没有办法
