### ISSUE TITLE
多饼图添加title

### ISSUE THREAD

**Issue by convertzl** [ecomfe/echarts#4367]
问题简述 (One-line summary)

一个echarts实例中的series中设置多个饼图(center位置不一样),如何给每一个饼图添加一个title

版本及环境 (Version & Environment)

ECharts 版本 (ECharts version): 3.2.3
浏览器类型和版本 (Browser version): Chrome 53.0.2785.143
操作系统类型和版本 (OS Version): Win7

![image](https://cloud.githubusercontent.com/assets/21234912/19880493/a532457c-a038-11e6-946e-4b781511d307.png)

- [ ]

**Comment by pissang** [comment]
同 http://echarts.baidu.com/gallery/editor.html?c=line-easing
