### ISSUE TITLE
echarts legend文字如何换行

### ISSUE THREAD

**Issue by MrChanLi2013** [ecomfe/echarts#4369]
#### 问题简述 (One-line summary)
我想让我的legend换行：比如legend（销量：1000台），我想将1000台在销量下显示，
legend中formatter函数不支持使用“br”，请问应该怎么办？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): echart3
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version):

**Comment by pissang** [comment]
`\n` 换行
