### ISSUE TITLE
关于折线图非节点的点击事件

### ISSUE THREAD

**Issue by xb9207** [ecomfe/echarts#4375]
echarts3的点击事件是:

```
mychart.on('click',function(params){
    alert("点我干什么！")!
})
```

在折线图图，这个是获取节点的点击事件，如果节点太小，在非节点区域该如何触发点击事件呢？

**Comment by pissang** [comment]
如果要扩大节点可点击区域，可以加一个透明的比较宽的边，例如
```js
borderWidth: 10,
borderColor: 'transparent'
```

**Comment by xb9207** [comment]
en ,这样是一个解决方法。可是如果点很多，这样貌似就不太好

**Comment by xb9207** [comment]
在非折线区域点击难道不能触发点击事件吗？鼠标在图上不都有一条垂直x轴的指示线

**Comment by 100pah** [comment]
myChart.getZr().on('click', ...) 是在任意区域的点击事件。只不过里面没有节点信息。

**Comment by alsotang** [comment]
我也觉得这里有点奇怪。。在折线图任意地点hover竟然能出来tooltip，那么是应该有一个 y 轴概念的。如果让y轴上的任意点击等同于点击节点呢？

**Comment by alsotang** [comment]
有个绕过办法，实验成功了。

1. 通过 `myChart.getZr().on('click', ...)` 检测整个图表的点击事件
2. 在 tooltip 的 formatter 中，每次调用都记录下需要的参数，然后在 1 中的回调中使用。

**Comment by techbirds** [comment]
如何监听折线的hover事件？
