### ISSUE TITLE
Ubuntu 14.04系统Firefox浏览器打不开示例

### ISSUE THREAD

**Issue by photino** [ecomfe/echarts#4376]
#### 问题简述 (One-line summary)

http://echarts.baidu.com/demo.html 页面所有的示例都打不开，换成Chrome浏览器就可以。

截图如下：

![ubuntu](https://cloud.githubusercontent.com/assets/3446306/19894472/2666e1c6-a088-11e6-8e95-452cc6e6a40c.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 最新版
+ 浏览器类型和版本 (Browser version): Firefox 49
+ 操作系统类型和版本 (OS Version): Ubuntu 14.04

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
看一下有没有报错

**Comment by photino** [comment]
看了控制台没有任何输出。更诡异的是，我在虚拟机里用Ubuntu 16.04带的Firefox就能打开示例，用Windows 10下的Firefox也能

**Comment by pissang** [comment]
有可能是 ubuntu 的 firefox 对 canvas 的支持有问题，如果是这个原因暂时也没什么解决办法

**Comment by photino** [comment]
找到原因了！我停用了加载页面上的自定义样式它就可以显示了，貌似哪个插件为了阻拦广告把baidu.com域名下的iframe都设置成display: none了。不好意思啊，是我自己浏览器的问题。
