### ISSUE TITLE
eclipse js验证 echarts.min.js 报错

### ISSUE THREAD

**Issue by weianzi** [ecomfe/echarts#4378]
#### 问题简述 (One-line summary)
eclipse js验证 echarts.min.js 报错：

![image](https://cloud.githubusercontent.com/assets/5836900/19914030/647cd93e-a0e2-11e6-9c8a-5634855f668f.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.3.0
+ 浏览器类型和版本 (Browser version): chrome 54
+ 操作系统类型和版本 (OS Version): win10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
忽略
