### ISSUE TITLE
echarts3.0在iOS触发touch事件时报错

### ISSUE THREAD

**Issue by CurtisCBS** [ecomfe/echarts#4384]
#### 问题简述 (One-line summary)

在iOS10 点击图表的时候会报错

TypeError: undefined is not an object (evaluating 'u.zrX')

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.3
+ 浏览器类型和版本 (Browser version):iOS 10 所有浏览器
+ 操作系统类型和版本 (OS Version):iOS10

#### 重现步骤 (Steps to reproduce)
1.touch图表就会报错

#### 期望结果 (Expected behaviour)
跟随鼠标显示当前touch位置的图表信息

#### 可能哪里有问题 (What went wrong)
获取touch事件位置有错？

**Comment by jarben** [comment]
Can confirm this on all touch devices, throws this: 
![image](https://cloud.githubusercontent.com/assets/561365/19927913/53f6e4f0-a0fc-11e6-90ea-9270d42aea97.png)

![image](https://cloud.githubusercontent.com/assets/561365/19927919/5fd822d4-a0fc-11e6-9bf1-8a6c47a5cd97.png)

Demo: https://echarts-3-3issue.hyperdev.space (run this on mobile or Chrome / dev tools / mobile emulation)

Could this be looked at with priority @pissang ?

**Comment by pissang** [comment]
Sorry about that. Already fixed https://github.com/ecomfe/zrender/commit/3e1bcda9414c8de7df992eeed770c6a6344c136e

**Comment by jarben** [comment]
Thanks heaps @pissang! Are you planning to make a new release sometimes soon?

**Comment by pissang** [comment]
Yes we will release a quickfix version a few hours later

**Comment by jarben** [comment]
Great to hear this, many thanks!

**Comment by meakchen** [comment]
我也遇到这个问题，新版本已经发布了么？

**Comment by pissang** [comment]
v3.3.1 released https://github.com/ecomfe/echarts/releases/tag/3.3.1

**Comment by jarben** [comment]
Awesome, thanks @pissang , will test asap!
