### ISSUE TITLE
我想用echarts3在es6项目里用webpack+babel打包，如何做

### ISSUE THREAD

**Issue by ShangXinbo** [ecomfe/echarts#4386]
用es6语法， import echarts from 'src/services/echarts.min';
我在用webpack 打包时 ，会报解析错误，是有什么原因么，我该如何操作

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts
