### ISSUE TITLE
连续setOption导致报错 

### ISSUE THREAD

**Issue by Jeffy2012** [ecomfe/echarts#4387]
#### 问题简述 (One-line summary)
1. setOption 有问题
2. 实例resize会导致报错或者无效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2
+ 浏览器类型和版本 (Browser version): chrome 50
+ 操作系统类型和版本 (OS Version): macpro

#### 重现步骤 (Steps to reproduce)
1. setOption 连续(setInterval，4次以上)设置不同的属性(noMerge) 会导致问题。 坐标轴不见了
2. 接着循环会导致报错

#### 期望结果 (Expected behaviour)

能解决掉这个问题
#### 可能哪里有问题 (What went wrong)

![image](https://cloud.githubusercontent.com/assets/2225478/19954697/61609352-a1b5-11e6-85ad-b5413470425a.png)

**Comment by 100pah** [comment]
能不能麻烦提供您的 option？

**Comment by Jeffy2012** [comment]
option 是变化的，随便一个简单的折线图 都这样的 只改变data的值 每隔2秒改变一次，大概到10次左右，坐标轴和grid就不显示了 然后再等等 就会报错了

**Comment by Jeffy2012** [comment]
最新chrome浏览器没有这个bug

**Comment by Jeffy2012** [comment]
![image](https://cloud.githubusercontent.com/assets/2225478/19957374/30ff6672-a1d1-11e6-9cc2-aea711d6cbbd.png)
```javascript
const chart = echarts.init(document.getElementById('test'));

setInterval(() => {
  console.count('times');
  chart.setOption({
    title: {
      text: 'ECharts 入门示例'
    },
    tooltip: {},
    legend: {
      data: ['销量']
    },
    xAxis: {
      data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
    },
    yAxis: {},
    series: [{
      name: '销量',
      type: 'bar',
      data: [Math.random() * 1000, Math.random() * 1000, Math.random() * 1000, Math.random() * 1000, Math.random() * 1000, Math.random() * 1000]
    }]
  }, true)
}, 1500);
```

**Comment by Jeffy2012** [comment]
希望能尽快解决  -_-

**Comment by pissang** [comment]
这个 bug 之前有人反馈过类似的，应该是 chrome 某几个开发者版本 JIT 优化导致的 bug

**Comment by Jeffy2012** [comment]
开发者版本？？ 我们这边用户反馈的， 并不是开发者版本

**Comment by Jeffy2012** [comment]
这个可以解决么？

**Comment by pissang** [comment]
暂时解决不了
