### ISSUE TITLE
前天起在线文件改动导致有些功能失效

### ISSUE THREAD

**Issue by Erimus-Koo** [ecomfe/echarts#4391]
#### 问题简述 (One-line summary)
之前直接引用的官方在线文件，前天起发现问题，是以下文件。
/vendors/echarts/echarts-all-3.js（估计是这个文件的问题）
换成下载的文件之后问题解决。

问题包括：
前天发生问题的是关系图，点击点无法显示高亮的关系线（大前天可以）。
今天试treemap，在线案例的drill down功能失效。
下载范例换成下载的文件是好的。

所以估计是那个在线文件更新的版本有问题，导致在线案例也有些的问题。
没测到的案例估计还有。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
**Chrome可以，手机不行。safari ios9。**
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by Erimus-Koo** [comment]
好像修复了

**Comment by pissang** [comment]
不建议引用示例里的 echarts 文件，可以下载后部署到自己服务器或者使用 cdn，例如 http://www.bootcdn.cn/echarts/
