### ISSUE TITLE
toolbox图标设置透明度

### ISSUE THREAD

**Issue by code-learner** [ecomfe/echarts#4392]
#### 问题简述 (One-line summary)
toolbox中的图标能设置透明度吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.2
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以

**Comment by code-learner** [comment]
可以？怎么设置啊？不是toolbox设置透明度，而是给toolbox的icon设置透明度dataview中直接写opacity吗？
