### ISSUE TITLE
希望能改进echart3在移动端的拨动效果

### ISSUE THREAD

**Issue by maomi20150102** [ecomfe/echarts#4393]
#### 问题简述 (One-line summary)
在移动端网页上，如果手指在echart图表范围内上下拨动页面，页面不会移动。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3

#### 其他信息 (Other comments)
![1](https://cloud.githubusercontent.com/assets/15665502/19959579/cdffa55c-a1e2-11e6-919c-16b0cd7398bb.JPG)

**Comment by tlfu12344** [comment]
3.2版本说这个改了，为什么我这边还是这样，我是折线图

**Comment by tlfu12344** [comment]
对了是3.3.2
