### ISSUE TITLE
toolbox中诸如saveAsImage, dataview等图标如何设置透明度

### ISSUE THREAD

**Issue by code-learner** [ecomfe/echarts#4399]
#### 问题简述 (One-line summary)

saveAsImage, dataview等图标如何设置透明度

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.2.2
+ 浏览器类型和版本 (Browser version):chorme
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)

图标设置透明度0.3，鼠标移到图标上透明度为1

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#toolbox.iconStyle.normal.opacity
