### ISSUE TITLE
echarts在服务端运行的问题

### ISSUE THREAD

**Issue by kimyengil** [ecomfe/echarts#4400]
目前需要在通过echarts生成大量的图片然后发送邮件，生成pdf之类的。
麻烦请问一下，目前echarts支持在node或其他server端跑起来么?主要用于在后端API生成数据后直接在后端通过echarts生成图片，最终发送邮件或吐给前端一个图片。
先谢过了。

**Comment by 100pah** [comment]
可以用 node-canvas 之类在 node 端跑。
参见：<https://tonicdev.com/56cb0fbc3a0cd70c0074022b/56cb0fbc3a0cd70c0074022c>

**Comment by endypark** [comment]
> 
> 
> 目前需要在通过echarts生成大量的图片然后发送邮件，生成pdf之类的。
> 麻烦请问一下，目前echarts支持在node或其他server端跑起来么?主要用于在后端API生成数据后直接在后端通过echarts生成图片，最终发送邮件或吐给前端一个图片。
> 先谢过了。

大侠，最终怎么实现的，给个分享呗，谢谢。

**Comment by lemonnoodle** [comment]
> > 目前需要在通过echarts生成大量的图片然后发送邮件，生成pdf之类的。
> > 麻烦请问一下，目前echarts支持在node或其他server端跑起来么?主要用于在后端API生成数据后直接在后端通过echarts生成图片，最终发送邮件或吐给前端一个图片。
> > 先谢过了。
> 
> 大侠，最终怎么实现的，给个分享呗，谢谢。

可以参考PhantomJS，搜索echarts  phantomjs，会出现诸多相关文章
