### ISSUE TITLE
怎么给图表加标注？

### ISSUE THREAD

**Issue by cqcn1991** [ecomfe/echarts#4401]
![qq](https://cloud.githubusercontent.com/assets/2425141/19991505/cdf118b4-a270-11e6-9472-531de1badcdd.png)
比如上图这种，可以在任意位置加文字，作为图表说明，来源等等

**Comment by pissang** [comment]
这种文字建议用 html

**Comment by cqcn1991** [comment]
好像已经发布了新版本，可以用了 @pissang

**Comment by cqcn1991** [comment]
好像已经发布了新版本，可以用了 @pissang
