### ISSUE TITLE
echarts在移动端页面上影响页面滚动

### ISSUE THREAD

**Issue by meakchen** [ecomfe/echarts#4402]
手指到图表上往下滚动的时候，就触发图表的效果了，页面不会滚动

**Comment by 100pah** [comment]
图表效果和默认的页面滚动二选一

**Comment by aufula** [comment]
@100pah 为何是2选1？ 同样用canvas的chartjs没这个问题。
第一感觉是echarts的touch事件处理的比较简陋，没有区分出来swipe和touch。偶还没看源码。

**Comment by pissang** [comment]
@aufula  这个是 3.3.0 和 3.3.1 中新引入的 bug，老版本没这个问题，新的代码也已经修复，下个版本发布新版本

**Comment by aufula** [comment]
@pissang 下个版本预计什么时候会发布？

**Comment by hisofter** [comment]
正在为这个问题头疼，有没有临时解决办法？新版本下载后还是这样。旧版虽然不存在此问题，但是折线的时候 数据为0时 不显示symbol 也不显示 label。求解大神。 @pissang  我只需要用折线图、柱状图和markpoint

**Comment by shikelong** [comment]
+1

**Comment by yuxingxin** [comment]
最新的版本3.3.2这个问题已经修复了

**Comment by fanmanman** [comment]
最新版本3.3.2什么时候发布？修复了移动端页面上手指滚动及缩放吗？

**Comment by pissang** [comment]
http://echarts.baidu.com/changelog.html
