### ISSUE TITLE
如何让getDataURL()获得的编码不含有有toolbox的图标

### ISSUE THREAD

**Issue by code-learner** [ecomfe/echarts#4403]
#### 问题简述 (One-line summary)
用echarts生成折线图，toolbox有dataview feature，利用getDataURL方法获取图片的编码信息，转成图片含有dataview图标。但是saveAsImage保存的图片就没有toolbox图标。请问我怎么去除toolbox图标啊

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.2
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.var url = myChart.getDataURL()
2.将url转码发现图片有dataview图标

#### 期望结果 (Expected behaviour)
获得的图片没有dataview图标

#### ECharts配置项 (ECharts option)

```javascript
option = {
  color: ['#29b6f6', '#FF6600', '#66CC66', '#a0a7e6', '#c4ebad', '#96dee8', '#6e7074', '#546570', '#c4ccd3'],
      tooltip: {
        trigger: 'axis'
      },
      legend: {
        x: 'center',
        data: type,
        show: true
      },
      toolbox: {
         feature: {
            dataView: { },
        }
      },
  xAxis: {
        boundaryGap: false,
        data: xdata
      },
      yAxis: yaxis,
      series: yseries
    }

}

```

**Comment by pissang** [comment]
```js
myChart.getDataURL({
  excludeComponents: ['toolbox']
});
```

**Comment by hugeorange** [comment]
> ```js
> myChart.getDataURL({
>   excludeComponents: ['toolbox']
> });
> ```

如果想要包含 tooltip 里面的内容要怎么做？
现在的情况很尴尬，如下图所示：tooltip的内容不展示但那个 点突出了，有时候那个标识线也会出现，但提示问题不出现，如下图所示：
![image](https://user-images.githubusercontent.com/18440746/84975820-00180000-b159-11ea-9d0f-ab203c25ac5e.png)

期望截出来的图是这个样子的：
![image](https://user-images.githubusercontent.com/18440746/84975878-1faf2880-b159-11ea-9b73-ff42a0abdf4c.png)
