### ISSUE TITLE
请问Treemap的叶子节点里面的 label 可不可以分成两行？能否旋转90度垂直呈现？

### ISSUE THREAD

**Issue by hustcer** [ecomfe/echarts#4408]
#### 问题简述 (One-line summary)

请问Treemap的叶子节点里面的 label 可不可以分成两行？能否旋转90度垂直呈现？
1. 分成两行的需求场景应该还挺多的：比如第一行显示`增长率`第二行显示`12.5%`, 等等，虽然tooltip上可以显示更详细的信息，可是毕竟要将鼠标移到每一个节点上看详情，还是不够直观。
2. 垂直呈现：当矩形的宽度不够但是高度足够的话可以将文字垂直完整呈现。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.3.1
+ 浏览器类型和版本 (Browser version): Chrome v54
+ 操作系统类型和版本 (OS Version): macOS 10.12

**Comment by 100pah** [comment]
1. 使用 `'\n'` 可以在label换行。
2. 可能是有些矩形宽>高，有些高>宽，那么有些垂直有些水平，感觉效果可能不会太好

**Comment by hustcer** [comment]
BTW: 还有一个问题——点击矩形区域进行数据下钻的时候，子节点的字能不能放大？这样看得更清楚些。

**Comment by 100pah** [comment]
试试不同的 [层级](http://echarts.baidu.com/option.html#series-treemap.levels) 分别设置字体的大小？
