### ISSUE TITLE
地图.json中coordinates字段乱码

### ISSUE THREAD

**Issue by KeZhimin** [ecomfe/echarts#4411]
当前在官网使用地图构建工具下载的*.json文件中，coordinates字段都是一些奇怪的字段，请问这是正常现象还是乱码了？

![image](https://cloud.githubusercontent.com/assets/7068010/20044220/df7e9e2c-a4d1-11e6-8cb2-e0ab227f9ec3.png)

**Comment by chengjianhua** [comment]
@KeZhimin 想问下你是解决了这个乱码问题吗 ? 我也碰到这样的问题, 我使用 d3 来解析这样的 json 会报错

**Comment by 100pah** [comment]
@chengjianhua 这是正常的，是压缩过的 GeoJSON
