### ISSUE TITLE
自定义toolbox图标选中状态

### ISSUE THREAD

**Issue by Suier** [ecomfe/echarts#4416]
#### 问题简述 (One-line summary)

自定义toolbox图标能否做到与自带的区域选择等组件一样，有选中与取消的状态？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2.3
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
点击后产生选中效果，再次点击后取消

#### ECharts配置项 (ECharts option)

```javascript
option = {
toolbox:{               
                feature:{
                    myScale:{
                        show: true,
                        title: '地图缩放',
                        icon:'path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444z M421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876z M421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062,591.891,421.146,591.891L421.146,591.891zM421.146,591.891',
                        onclick: function (params){                                                 
                        }
                    }
                }
            }
}

```

**Comment by Suier** [comment]
找到了替代的方法，点击后改变icon的颜色，虽然麻烦了点，但是还是可以实现的

**Comment by Seven4X** [comment]
icon:'path://M432.45,595.444c0,2.177-4.661,6.82-11.305,6.82c-6.475,0-11.306-4.567-11.306-6.82s4.852-6.812,11.306-6.812C427.841,588.632,432.452,593.191,432.45,595.444L432.45,595.444z M421.155,589.876c-3.009,0-5.448,2.495-5.448,5.572s2.439,5.572,5.448,5.572c3.01,0,5.449-2.495,5.449-5.572C426.604,592.371,424.165,589.876,421.155,589.876L421.155,589.876z M421.146,591.891c-1.916,0-3.47,1.589-3.47,3.549c0,1.959,1.554,3.548,3.47,3.548s3.469-1.589,3.469-3.548C424.614,593.479,423.062,591.891,421.146,591.891L421.146,591.891zM421.146,591.891',


path://这后面的是什么？有人知道吗
