### ISSUE TITLE
如果series的data包含null或者无法绘制的数据，brush的时候会出错

### ISSUE THREAD

**Issue by zmiemie** [ecomfe/echarts#4428]
#### 问题简述 (One-line summary)
如果series的data包含null或者无法绘制的数据，brush的时候会出错

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.3.0
+ 浏览器类型和版本 (Browser version): Chrome 51.0.2704.103
+ 操作系统类型和版本 (OS Version): Windows 7

#### 重现步骤 (Steps to reproduce)
1. series的data属性包含null
2. 开启brush，绘制完成后选择rect brush，在图上进行框选brush

#### 期望结果 (Expected behaviour)
可以通过brush来筛选数据

#### 可能哪里有问题 (What went wrong)
包含null的数据无法被绘制，其itemLayout对象是undefined，因此在makeBoundingRect里面出错

#### ECharts配置项 (ECharts option)

```javascript
option = {

    backgroundColor: '#eee',
    brush: {
        toolbox: ['rect', 'polygon', 'lineX', 'lineY', 'keep', 'clear'],
        xAxisIndex: 0
    },
    tooltip: {},
    xAxis: {
        data: [1,2,3,4,5,6,7,8,9,0],
        name: 'X Axis',
    },
    yAxis: {
        splitArea: {show: false}
    },
    grid: {
        left: 100
    },
    series: [
        {
            name: 'bar',
            type: 'bar',
            stack: 'one',
            data: [1,2,3,4,5,null,7,8,9,10]
        }
    ]
}

```

**Comment by yaunyu** [comment]
这个问题依然存在
