### ISSUE TITLE
ECharts 地图数据在线生成工具 无法生成广东东莞及中山的地图

### ISSUE THREAD

**Issue by dinsy008** [ecomfe/echarts#4429]
#### 问题简述 (One-line summary)

ECharts 地图数据在线生成工具(http://ecomfe.github.io/echarts-map-tool/) 
无法生成广东省东莞市、中山市 包含子区域的地图数据

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrom 50
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
1.打开http://ecomfe.github.io/echarts-map-tool/
2.选择广东省-东莞市，勾选包含子区域

#### 期望结果 (Expected behaviour)
正常生成东莞市、中山市的子区域地图

#### 可能哪里有问题 (What went wrong)
未知

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
东莞和中山市是中国五个不含县级单位的城市，所以没有子区域。在 https://github.com/ecomfe/echarts-map-tool/commit/83bb9e63889aa4a0d2ba39a0a29a3e0fc4d55f21 中已修复，现在选择这两个城市后，子区域的按钮变成不可选的。
