### ISSUE TITLE
如何在折线图中动态添加多组数据

### ISSUE THREAD

**Issue by zhaoxueyin000** [ecomfe/echarts#4430]
#### 问题简述 (One-line summary)

![image](https://cloud.githubusercontent.com/assets/17424860/20095141/3d7cd95e-a5df-11e6-8976-6dbe8047e68a.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0

**Comment by zhaoxueyin000** [comment]
谢谢，如果是同时添加多组数据呢，应该怎么处理
