### ISSUE TITLE
请教3版本后的components实例化后获取为空的问题

### ISSUE THREAD

**Issue by zacard-orc** [ecomfe/echarts#4433]
#### 问题简述 (One-line summary)
请问ec3后取component对象为空，即便从实例绕进去通过getModel或者_componentsMap找到xAxis或者yAxis依旧拿不到getAxis方法，是不是ec3后方法开始变了？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3+
+ 浏览器类型和版本 (Browser version)：chrome
+ 操作系统类型和版本 (OS Version): m11.04

#### 重现步骤 (Steps to reproduce)
用3版本跑2的饼散实例 http://echarts.baidu.com/echarts2/doc/example/mix7.html，问题焦点在于拿坐标转换函数失败，实例已经setOption化。

#### 期望结果 (Expected behaviour)
大神，给条路

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![snip20161108_22](https://cloud.githubusercontent.com/assets/6058537/20101363/a8aee2a4-a5fc-11e6-8d07-f16852429a73.png)

**Comment by zacard-orc** [comment]
找到原因了，原来是两周前bower时装的是3.2.3，convertPixel到了3.3.0+才有  ^_^

**Comment by pissang** [comment]
是的，那我 close 了
