### ISSUE TITLE
Would it be possible to update zoom slider labels while dragging without realtime chart updates?

### ISSUE THREAD

**Issue by fmal** [ecomfe/echarts#4434]
When i set `dataZoom: { realtime: false }`, the chart updates only when user has stopped dragging which is perfect behavior for me, as I experienced some serious performance issues with `realtime` enabled. I would love to have realtime chart updates disabled but allow zoom slider labels to update independently while user drags the slider?

![cavywehosb](https://cloud.githubusercontent.com/assets/927591/20102436/64d9928a-a5c6-11e6-83af-26d26cc3b72a.gif)

As you can see currently slider labels are static while it's being dragged. It would be great if the values updated before ending the drag operation. Is that possible to achieve?

Thanks

**Comment by pissang** [comment]
Yes i thinks it will be useful and currently not supported. Thanks for the advise
