### ISSUE TITLE
legend 中的icon和文案能分别设置大小和颜色吗

### ISSUE THREAD

**Issue by zhaoxueyin000** [ecomfe/echarts#4448]
#### 问题简述 (One-line summary)

![image](https://cloud.githubusercontent.com/assets/17424860/20169455/a5cc4e3e-a762-11e6-8149-8f5eee18f3cf.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by zhaoxueyin000** [comment]
已解决，谢谢

**Comment by mqliutie** [comment]
@zhaoxueyin000 没找到相关配置项啊

**Comment by CR7LOVE** [comment]
itemWidth works！Thank you! @mqliutie
