### ISSUE TITLE
在线构建包含dataZoom后，页面就无法滑动了

### ISSUE THREAD

**Issue by Coffcer** [ecomfe/echarts#4450]
#### 问题简述 (One-line summary)
移动端引进了dataZoom组件后，就无法在图表上滚动页面了，即使图表里没有配dataZoom也不行。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.3.1
+ 浏览器类型和版本 (Browser version): Android Webview
+ 操作系统类型和版本 (OS Version): 

#### 可能哪里有问题 (What went wrong)
是否touchStart事件被preventDefault了？

**Comment by pissang** [comment]
这是 3.3.0 里引入的 bug，最新的代码里已修复

**Comment by Coffcer** [comment]
我是在3.3.1下出现这个问题的，明天回公司再试一次~

**Comment by pissang** [comment]
嗯 3.3.0 和 3.3.1 都有这个问题，修复的代码还没 release

**Comment by SkyMonkya** [comment]
@pissang 请问代码这个星期几能发行?手机上用的太尴尬了

**Comment by pissang** [comment]
下周一

**Comment by Coffcer** [comment]
已经周三啦，这个BUG比较严重，希望感觉修复，或者在线构建可以提供版本选择，以便让人选择之前的版本

**Comment by pissang** [comment]
@Coffcer 抱歉拖了几天，着急的话可以从 github 最新代码构建。

**Comment by tlfu12344** [comment]
3.3.2的这个修改了嘛，我这边看还是不行哈，引用了dataroom后还是不行，    dataZoom: {
                show: false,
                realtime: true,
                zoomLock: 'false',
                height: 20,
                type: 'inside',
                startValue: query.startDate,
                endValue: query.endDate
            },
是我配置有问题？手机端放在图上还是不能滑动，
