### ISSUE TITLE
Legend 图例是否支持气泡 effectScatter

### ISSUE THREAD

**Issue by EllaZhao** [ecomfe/echarts#4451]
#### 问题简述 (One-line summary)

我想定制 legend 样式， 类似 起泡的效果，http://echarts.baidu.com/gallery/editor.html?c=effectScatter-map， 想请教下是否可以做到？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
无
#### 期望结果 (Expected behaviour)
无

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不支持

**Comment by EllaZhao** [comment]
@pissang  多谢回复
