### ISSUE TITLE
地图区划调整

### ISSUE THREAD

**Issue by zhuzhuzhumop** [ecomfe/echarts#4460]
#### 问题简述 (One-line summary)
希望用echarts的地图组件做一个地市的地图，地市里面展示各个区县的行政划分。由于地市的辖区做了区划调整，原先两个彼此接壤的区县合并成一个区县了，这种情况应该怎么去实现，期待回复。谢谢

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by mingjunyang** [comment]
也许可以试试在线geojson编辑工具。
