### ISSUE TITLE
怎么给echarts的文字设置渐变色呀？？？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#4465]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
文字不支持渐变色

**Comment by chenxia123** [comment]
@pissang 那请问饼图（确切地说是圆环图）可以设置渐变色吗？不是径向渐变，是从12点方向顺时针渐变的效果。

**Comment by pissang** [comment]
@chenxia123 这个受 canvas 的接口限制也不能实现

**Comment by 100pah** [comment]
只能这么 hack，不知道有没有意义
<http://gallery.echartsjs.com/editor.html?c=xHknbRf3We&v=1>
