### ISSUE TITLE
鼠标事件参数中获取的dataIndex与action中的dataIndex不对应，导致改变图形行为出错

### ISSUE THREAD

**Issue by rickysang** [ecomfe/echarts#4466]
#### 问题简述 (One-line summary)
鼠标事件参数中获取的dataIndex为数据点的实际索引，而action属性中的dataIndex图中实际显示数据的索引。dataIndex不对应导致图形出错或JavaScript报错。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): v3.2.3
+ 浏览器类型和版本 (Browser version): Chrome 54.0.2840.71 m
+ 操作系统类型和版本 (OS Version): WIN10

#### 重现步骤 (Steps to reproduce)
在一个ECharts绘制三个grid，每个grid都是折线图，且横坐标一样纵坐标不一样。要求当鼠标移到其中一个折线图，高亮其他两个图中相同横坐标对应的点；当鼠标移开时，取消高亮，实现代码请看后面。

1.  将鼠标移动到第三个点，高亮显示正常
![step1](https://cloud.githubusercontent.com/assets/19810448/20255933/5f1ae40c-aa7b-11e6-963b-69f2cbc0726c.png)
2.  缩放区域至隐藏第一个点，将鼠标移动至显示区域的第一个点（即所有数据的第二点），高亮显示了显示区域中的第二个点（即所有数据的第三个点）
![step2](https://cloud.githubusercontent.com/assets/19810448/20255935/61f50ec8-aa7b-11e6-8bf0-d083907c67d9.png)
3.  继续缩放区域直至显示最后两个点，将鼠标移动到显示区域的第一个点（即所有数据的第四点），显示区域中无任何点高亮显示，JavaScript报错
![step3](https://cloud.githubusercontent.com/assets/19810448/20255936/63856fda-aa7b-11e6-83f6-0698d4bacb4c.png)

#### 期望结果 (Expected behaviour)
将鼠标移动至一个点时，应高亮显示其他两个图相同横坐标对应的点。

#### 可能哪里有问题 (What went wrong)
mousemove事件中参数的dataIndex为所有数据的dataIndex，而highlight action中参数的dataIndex为图形中可是区域数据的dataIndex。两个参数中的dataIndex不对应。

API中也没有提供获取当前可视数据的方法，目前只能通过datazoom事件处理函数获取缩放开始和结束位置自己重新计算index：
``` javascript
{
    type: 'datazoom',
    // 缩放的开始位置的百分比，0 - 100
    start: number
    // 缩放的结束位置的百分比，0 - 100
    end: number
    // 缩放的开始位置的数值，只有在工具栏的缩放行为的事件中存在。
    startValue?: number
    // 缩放的结束位置的数值，只有在工具栏的缩放行为的事件中存在。
    endValue?: number
}
```

希望可以统一事件中的dataIndex和action中的dataIndex

#### ECharts配置项 (ECharts option)

```javascript
var option = {
    tooltip: {},
    grid: [
        { show: true, height: '20%', top: '10%' },
        { show: true, height: '20%', top: '40%' },
        { show: true, height: '20%', top: '70%' }
    ],
    dataZoom: [
        { type: 'slider', show: true, xAxisIndex: [0, 1, 2], labelPrecision: '0' },
        { type: 'inside', xAxisIndex: [0, 1, 2] }
    ],
    xAxis: [
        { type: 'value', name: 'km', show: true, gridIndex: 0 },
        { type: 'value', name: 'km', show: true, gridIndex: 1 },
        { type: 'value', name: 'km', show: true, gridIndex: 2 }
    ],
    yAxis: [
        { type: 'value', name: 'km/h', show: true, gridIndex: 0 },
        { type: 'value', name: 'wh', show: true, gridIndex: 1 },
        { type: 'value', name: '%', show: true, gridIndex: 2 }
    ],
    series: [
        { name: 'speed', type: 'line', xAxisIndex: 0, yAxisIndex: 0, data: [[0, 10], [1, 5], [4, 9], [5, 6], [6, 9]] },
        { name: 'ee', type: 'line', xAxisIndex: 1, yAxisIndex: 1, data: [[0, 2], [1, 4], [4, 6], [5, 8], [6, 3]] },
        { name: 'ree', type: 'line', xAxisIndex: 2, yAxisIndex: 2, data: [[0, 1], [1, 7], [4, 9], [5, 3], [6, 1]] }
    ]
};
```

#### ECharts事件脚本
``` javascript
chart.on('mousemove', function (params) {
    chart.dispatchAction({
        type: 'highlight',
        seriesIndex: [0, 1, 2],
        dataIndex: params.dataIndex
    });
});

chart.on('mouseout', function (params) {
    chart.dispatchAction({
        type: 'downplay',
        seriesIndex: [0, 1, 2],
        dataIndex: params.dataIndex
    });
});
```

**Comment by 100pah** [comment]
好详细的描述，太感动了！

这个问题在 3.3.1 中有修复过，可以升级看看还有没有这个问题。

**Comment by rickysang** [comment]
@100pah , Yes it's fixed! Thanks!

**Comment by 799677446** [comment]
如何能精确拿到dataIndex，直接用chart.on('mousemove')需要鼠标移动到对应光标，用chart.getZr().on('mousemove')却拿不到dataIndex，请问要如何拿到
