### ISSUE TITLE
echart3官网示例中，平行坐标图的tooltip均无效

### ISSUE THREAD

**Issue by xiaotianlongxing** [ecomfe/echarts#4468]
#### 问题简述 (One-line summary)

echart3中，平行坐标的tooltip无效

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts 3
+ 浏览器类型和版本 (Browser version):chrome 56.0.2896.3
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by es3154** [comment]
官方demo tooltip没出来  [](http://echarts.baidu.com/demo.html#parallel-aqi)
