### ISSUE TITLE
echarts如何在dojo环境中集成

### ISSUE THREAD

**Issue by LancerSung** [ecomfe/echarts#4469]
#### 问题简述 (One-line summary)
我的web应用程序是基于dojo开发的，现在想集成echarts，但是里面都有require这个关键字，请问如何在dojo中集成

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2.27
+ 浏览器类型和版本 (Browser version):chrome51
+ 操作系统类型和版本 (OS Version):windows8.1

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
用 echarts 3
