### ISSUE TITLE
饼图的label会超出容器

### ISSUE THREAD

**Issue by aufula** [ecomfe/echarts#4470]
饼图的label会超出容器。在移动端特别明显
![image](https://cloud.githubusercontent.com/assets/544442/20260329/1866a910-aa94-11e6-9380-4febe0590729.png)

**Comment by wu11106** [comment]
九月三十日白金支出八百是不是不属于我的，我就拿这个来说事，我怕搞错了

巫月 <notifications@github.com>于2016年11月14日 周一16:32写道：

**Comment by pissang** [comment]
把 radius 设置得小一点

**Comment by Kris-Lee-SH** [comment]
这样岂不是要根据label的不同动态调整radius。。。
没有自适应么，像直角坐标系中的grid

**Comment by TonyTwist** [comment]
> 这样岂不是要根据label的不同动态调整radius。。。
> 没有自适应么，像直角坐标系中的grid

你可以判断最小宽度能容纳几个字, 然后自己插入换行符
