### ISSUE TITLE
DataZoom moves axis with different speeds desynchronizing different series

### ISSUE THREAD

**Issue by jkkrefta** [ecomfe/echarts#4471]
When using dataZoom slider multiple axis they appear to progress thru data in desynchronized manner.

+ ECharts 版本 (ECharts version): 3.3.1
+ 浏览器类型和版本 (Browser version): Google Chrome 54.0.2840.87
+ 操作系统类型和版本 (OS Version): Windows 10

#### 重现步骤 (Steps to reproduce)
1. Go to: https://jsbin.com/qidida/12/edit?js,output
2. On output window click Run with JS.
3. Grab slider and slowly move to the right.
4. Observe line series as you move slider.

#### 期望结果 (Expected behaviour)
I expected that both bar and line series will progress in synch.

#### 可能哪里有问题 (What went wrong)
Due to how axis are set line series has smaller step on slider than bar series. Both series traverse chart with different speed. I understand that data slider works per axis. When you include more than one axis they will just slide data with different speeds that is relative to ammount of data in series. Hovewer it would be awesome if there was option to bind synch movement of all axis to 'main axis' that would be set in dataZoom options. For example:

```javascript
option = {
  dataZoom: {
    xAxisIndex: [0, 1],
    xAxisSyncToIndex: 0
  }
}

```

**Comment by wu11106** [comment]
翻译过来，怕消息丢失，提款消息的价值在于款项给偷提，接收信息原收件人，能够收到，您们百分之百知道。
问题是提款人的真假，您们怕美国总统给冒充已不怕我给冒充，总统先生都没有每分每秒的跟班，安全从何而来……

Jarosław Krefta <notifications@github.com>于2016年11月14日 周一19:43写道：

**Comment by 100pah** [comment]
The dataZoom slider axes by *percent of the extent*. So if we want multiple axes to be slid in the same speed, data length of them should be the same.
I've modified a little in your example: <https://jsbin.com/razobabepi/1/edit?js,output>.

**Comment by jkkrefta** [comment]
Yeah. I know. I just have a case that would require more static approach where everything slides with one speed. But then again we are about to solve it with our own custom slider. I was just wondering if it would be easy to add this behavior on your side. Thanks @100pah for the replay.
