### ISSUE TITLE
饼图 在安卓端微信浏览器内显示，name和指示线重叠，如下图

### ISSUE THREAD

**Issue by xpf7** [ecomfe/echarts#4474]
#### 问题简述 (One-line summary)
饼图 在安卓端微信浏览器内显示，name和指示线重叠，如下图

![11](https://cloud.githubusercontent.com/assets/23467866/20292112/e8d2818c-ab25-11e6-902a-032800928cff.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
跟其他浏览器显示相同效果

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by nicky132** [comment]
你好，你解决了没？我也有这种问题
