### ISSUE TITLE
各省地图只能单独下载吗？

### ISSUE THREAD

**Issue by ysysdzz** [ecomfe/echarts#4477]
做全国地图点击某个省显示某个省地图的功能，请问各省地图只能单独下载吗？
我在地图构建那里打包下载的地图文件 在webpack中不能用，只有单独下载的才能用

**Comment by pissang** [comment]
一个 json 文件 webpack 里为啥不能用？

**Comment by ysysdzz** [comment]
@pissang js文件

**Comment by Ovilia** [comment]
你在 webpack 打包的时候，有没有在 `externals` 里写 `echarts`？我这边试了一下，没有发现问题，附上我的 `webpack.config.js`。

```js
module.exports = {
    entry: {
        'hebei': './test.js'
    },
    output: {
        libraryTarget: 'umd',
        library: ['hebei'],
        path: __dirname + '/dist',
        filename: '[name].js'
    },
    externals: {
        'echarts': 'echarts'
    }
};
```

`test.js` 文件：
```js
var echarts = require('echarts');
require('./hebei.js');

var chart = echarts.init(document.getElementById('map'));
chart.setOption({
    series: [{
        type: 'map',
        map: '河北'
    }]
});
```

**Comment by ysysdzz** [comment]
@Ovilia 这样是没有问题的，在官网 构建地图那里把所有的地区构建在一个js里 使用就有问题了

**Comment by Ovilia** [comment]
@ysysdzz 你是怎么“把所有的地区构建在一个js里”的？

**Comment by ysysdzz** [comment]
@Ovilia 官网---下载---地图构建啊

**Comment by pissang** [comment]
@ysysdzz 请描述清楚你的问题，我们这没法根据你的描述复现

**Comment by ysysdzz** [comment]
@pissang 呃 我整理整理

**Comment by Ovilia** [comment]
@ysysdzz 我明白你的意思了，你要用中国地图的话，在[这里](http://echarts.baidu.com/download-map.html)下载，地图构建里的全国地图不能用，我会禁掉的。

**Comment by ysysdzz** [comment]
@Ovilia 不是， 各省份的地图可以合成一个吗？我要实现的功能是 点击全国地图上的某一个省，显示对应省的地图。   而各省的地图有33个

**Comment by Ovilia** [comment]
@pissang 印象中看到过，点击中国的一个省，加载该省的地图？

**Comment by ysysdzz** [comment]
@Ovilia 对啊

**Comment by ColinCLL** [comment]
十分感谢，关了一扇门，留了一扇窗
