### ISSUE TITLE
echats3 地图ie8兼容问题（地图高亮显示、tooltip、单击事件）

### ISSUE THREAD

**Issue by 125690086** [ecomfe/echarts#4479]
#### 问题简述 (One-line summary)
echats3 地图模块在ie8下，高亮显示失效，tooltip失效，单击没有反应

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):ie8
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
ie8下访问echats3

#### 期望结果 (Expected behaviour)
在ie8下鼠标滑过地图区域能正常显示tooltip，地图单击事件能够正常使用

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by 100pah** [comment]
建议先看一下自己代码有没有报错
