### ISSUE TITLE
地图中示例【北京公交线路图】json文件格式参数

### ISSUE THREAD

**Issue by Jackielzq** [ecomfe/echarts#4481]
#### 问题简述 (One-line summary)

http://echarts.baidu.com/demo.html#lines-bmap-effect  
这个图对应的数据源：
http://echarts.baidu.com/data/asset/data/lines-bus.json

其中数据
[[1164383,401471,-11,-13,1,-49,-26,-14,99,-170,4,-36,87,-2,16,-141,-2,-15,-47,-6,-168,-9,-2,22,-74,-4,-138,10,12,-152,9,-55,-17,-111,13,-176,-20,-38,1,-57,31,-54,28,-85,-5,-126,-13,-62,1,-34,-84,1,-3,-218,15,6,78,2,4,-52,70,1,7,-142,99,2,21,-5,229,-150,16,-23,0,-180,168,1,-4,-257,82,0,33,-22,78,20],

参数过多，不知道是什么意思，请问有文档注释提供吗，我们手中有其他地方的数据想做展示但是不清楚这个怎么调

**Comment by pissang** [comment]
数据长这样是为了减小文件体积， 实际上 echarts 使用的数据格式见  http://echarts.baidu.com/option.html#series-lines.data 示例里也有数据转换的代码。
 
http://echarts.baidu.com/demo.html#lines-bmap 这个示例的数据可能更清晰。

**Comment by Jackielzq** [comment]
@pissang 回复好快，懂了，非常感谢！！

**Comment by SynChron1zed** [comment]
@Jackielzq  你好 问下 你们展示其它地方的 json 是怎么写的 手动写入的么 ？

**Comment by JackieLuo** [comment]
直接替换上去就好了，换成Echarts规定的格式

**Comment by SynChron1zed** [comment]
@JackieLuo  其它城市街道都不一样吧 替换上去 还是之前城市的

**Comment by JackieLuo** [comment]
数据源是吗  我们合作方提供的其他城市的数据源，上面的数据其实就是初始的经纬度坐标和偏移度，你如果需要数据源的话 可以找下百度高德地图看他们有没有开源的数据

**Comment by SynChron1zed** [comment]
是的 数据源 我这边不知道偏移度

**Comment by honeyjie** [comment]
其中数据
[1164383,401471,-11,-13,1,-49,-26,-14,99,-170,4,-36,87,-2,16,-141,-2,-15,-47,-6,-168,-9,-2,22,-74,-4,-138,10,12,-152,9,-55,-17,-111,13,-176,-20,-38,1,-57,31,-54,28,-85,-5,-126,-13,-62,1,-34,-84,1,-3,-218,15,6,78,2,4,-52,70,1,7,-142,99,2,21,-5,229,-150,16,-23,0,-180,168,1,-4,-257,82,0,33,-22,78,20]

这里应该是坐标成对出现，第一个定义基准经度、第二个基准维度，后面也是成对出现，分别是经纬度上的偏移。
