### ISSUE TITLE
Component series.radar not exists. Load it first.

### ISSUE THREAD

**Issue by tenonersoft** [ecomfe/echarts#4487]
基础雷达图，将官方的例子完成复制都仍然显示这个错误

**Comment by pissang** [comment]
没加载雷达图组件，使用 `echarts.min.js` 或者[在线构建](http://echarts.baidu.com/builder.html) 选择雷达图后下载

**Comment by PaoziSiyangyuan** [comment]
引入echarts.min.js之后还是报这个错

**Comment by PaoziSiyangyuan** [comment]
> 没加载雷达图组件，使用 `echarts.min.js` 或者[在线构建](http://echarts.baidu.com/builder.html) 选择雷达图后下载

引入了‘echarts.min.js’，还是报这个错呀
