### ISSUE TITLE
请教一个问题，关于条形图的

### ISSUE THREAD

**Issue by blazert** [ecomfe/echarts#4488]
刚刚接触echarts，感觉很不错，但是使用还不是特别的属性，所以想问下
![image](https://cloud.githubusercontent.com/assets/15223520/20339468/70917a28-ac17-11e6-90b9-3d34ce6ecead.png)这种要怎么实现啊？

**Comment by pissang** [comment]
这种建议用 html...

**Comment by blazert** [comment]
嗯  我找了下资料 好像html更容易实现
