### ISSUE TITLE
Can we Have Export To Excel Or CSV finctionality in echarts?

### ISSUE THREAD

**Issue by neetin1809** [ecomfe/echarts#4490]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by haji1202** [comment]
@pissang 
Why is this issue closed?
I think Excel export function is necessary in echarts.

**Comment by 100pah** [comment]
I have no idea how to implement it, considering complexity and compatibility. Do you have any suggestion about it?

**Comment by haji1202** [comment]
The datatable has been developed this way.
https://datatables.net/extensions/buttons/examples/initialisation/export.html
I think we can develop similar.

**Comment by sjcobb** [comment]
@100pah Could this feature be implemented in cases where a chart uses [dataset](https://echarts.apache.org/en/option.html#dataset.source) structured as a 2d array? Then the mapping to CSV would be straightforward using [an approach like this arrayToCSV](https://gist.github.com/yangshun/01b81762e8d30f0d7f8f) example.

**Comment by missZhang-code** [comment]
@100pah,我们现在业务也需要导出echarts图表到excel,尤其是常规的柱状图,折线图和饼图,在不请求后端的情况下无法做到啊,请问什么时候能出一个导出echarts图表到excel的功能啊

**Comment by yuanly** [comment]
> @100pah,我们现在业务也需要导出echarts图表到excel,尤其是常规的柱状图,折线图和饼图,在不请求后端的情况下无法做到啊,请问什么时候能出一个导出echarts图表到excel的功能啊

直接前端（不经过后端）下载是可以的，网上不难找到示例。但不知道如何从图中获取到数据（不是原始的option里的数据，而是经过各种处理后最终展示的数据）。

We can download with backend, but can't get the final data(after transform) from canvas.

**Comment by yuanly** [comment]
> @100pah,我们现在业务也需要导出echarts图表到excel,尤其是常规的柱状图,折线图和饼图,在不请求后端的情况下无法做到啊,请问什么时候能出一个导出echarts图表到excel的功能啊

直接前端（不经过后端）下载是可以的，网上不难找到示例。但不知道如何从图中获取到数据（不是原始的option里的数据，而是经过各种处理后最终展示的数据）。

We can download with backend, but can't get the final data(after transform) from canvas.
