### ISSUE TITLE
官方文档疏漏及期望更新

### ISSUE THREAD

**Issue by sjsdfg** [ecomfe/echarts#4493]
#### 问题简述 (One-line summary)
希望文档进行一下更新。
在series[i]-map下对地图的引用属性为map
但是在官方示例的多处地方仍旧引用的是mapType。
虽然在使用上面两个属性并没有差别，还是希望官方可以更新一下

http://echarts.baidu.com/demo.html#map-province
并且在以上的示例中使用了多个文档API没有提供的功能，希望能给予相应的文档说明
例如：
var zr = myChart.getZr();
var icon1 = new echarts.graphic.Circle({
var group = new echarts.graphic.Group();
在对应的echarts或者echartsInstance中都没有找到对应的文档，希望能给予更新
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3

**Comment by pissang** [comment]
谢谢建议
