### ISSUE TITLE
桑基图顶部无法对齐

### ISSUE THREAD

**Issue by pzljp** [ecomfe/echarts#4495]
#### 问题简述 (One-line summary)
按照http://echarts.baidu.com/demo.html#sankey-product上的demo写的，为什么顶部无法对齐呢？这个效果是由用户配置的呢，还是由echarts自动设置的？官网上同样配置的两个demo，一个对齐，一个不能对齐。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 上贴个示例看看

**Comment by AprilTong** [comment]
没有顶部对齐的布局

**Comment by AprilTong** [comment]
有左右对齐布局，建议出一个顶部对齐的布局

看到示例有一个顶部对齐，但似乎没看到有相应的属性设置，不知道是不是和value有关
