### ISSUE TITLE
力图动画时长

### ISSUE THREAD

**Issue by songshuzhong** [ecomfe/echarts#4497]
#### 问题简述 (One-line summary)

力图加载的动画时长没办法控制

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
是的，这个动画是布局的迭代演示，并不是跟其它图表一样的初始动画
