### ISSUE TITLE
使用echart CDN  在require怎么配置路径

### ISSUE THREAD

**Issue by liyanyan1994** [ecomfe/echarts#4499]
#### 问题简述 (One-line summary)
使用Echart时 加载echart.js 太慢 调cdn后 应该怎么配置require的路径？？

#### 期望结果 (Expected behaviour)
访问速度加快 能够正常的运行echart 得到图表

#### 可能哪里有问题 (What went wrong)
这个是我直接调用CDN的js 然后报错   ReferenceError: require is not defined

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

这是js引用和配置
<script src="https://cdn.bootcss.com/echarts/3.3.1/echarts.min.js"></script>
require.config({
    paths: {
        echarts: './build/dist'//引用资源文件夹路径，注意路径
    }
});

**Comment by pissang** [comment]
CDN 不支持按需加载
