### ISSUE TITLE
地图数据格式修改后visualMap的使用

### ISSUE THREAD

**Issue by zhouboluo** [ecomfe/echarts#4500]
#### 问题简述 (One-line summary)
因为功能需求，将地图中的data改为了如下形式：
{"name": "北京","value": [{"name": "SUMddd","value": 13777}]}；
设置tooltip，使用function重新拼了显示标签；
现在又有新需求要加上visualMap，可是基本属性设置无效：
{"min": 0,"max": 147503,"show": false}

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
部分data如下：
"data": [{"name": "上海","value": [{"name": "SUMddd","value": 13931}]},{"name": "云南","value": [{"name": "SUMddd","value": 99318}]},{"name": "内蒙古","value": [{"name": "SUMddd","value": 82486}]},{"name": "北京","value": [{"name": "SUMddd","value": 13777}]},{"name": "吉林","value": [{"name": "SUMddd","value": 49339}]},{"name": "四川","value": [{"name": "SUMddd","value": 147503}]},{"name": "天津","value": [{"name": "SUMddd","value": 13084}]},{"name": "宁夏","value": [{"name": "SUMddd","value": 19784}]},{"name": "安徽","value": [{"name": "SUMddd","value": 89853}]},{"name": "山东","value": [{"name": "SUMddd","value": 117528}]},{"name": "山西","value": [{"name": "SUMddd","value": 96404}]}]

#### 期望结果 (Expected behaviour)
产生不同颜色的视觉映射

#### 可能哪里有问题 (What went wrong)
是不是这样找不到value值

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
不支持这种格式
