### ISSUE TITLE
echarts组合柱状图（分别朝向y轴相反的两个方向），现想给朝向y轴负方向的柱状图背景设置透明度，该怎么做到？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#4501]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by partical** [comment]
每一个柱子是可以单独设置样式的，如果需要给y轴负方向的添加透明度，那么可以给每一个y轴负方向的柱子单独加上样式

**Comment by chenxia123** [comment]
好的 用这种方法已经解决了！谢谢！
