### ISSUE TITLE
请求增加 echart2 地图的 effect 效果

### ISSUE THREAD

**Issue by evolutionjay** [ecomfe/echarts#4503]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.x
+ 浏览器类型和版本 (Browser version):Chrome 
+ 操作系统类型和版本 (OS Version): mac OS

#### 期望结果 (Expected behaviour)
Echart3 的地图有 echart2 的 闪烁效果。

#### 其他信息 (Other comments)
看升级echart3 了，非常兴奋跟着升级，最后发现效果都改了。， 不，是砍了。我先不管你们优化了什么， 这样升级项目之后，上头一看，你改我效果了？ 被喷一顿之后 降级2.x 版本。。。你们的API又变了很多， 你们能理解为了适配 3.x 改了一大堆API 之后因为砍了效果， 又要改回去的感受么？ 别提 版本控制。。。没这个。

**Comment by zhump** [comment]
选择一个技术方案的时候，不是应该先好好了解清楚，再实践吗？你没版本控制，先不提，哪怕备份代码你都不会做吗，  再说3比2优秀很多地方，你直接忽略了，真是让我想到一句话，，斗米养恩 担米养仇

**Comment by evolutionjay** [comment]
楼上的哥们，我得罪你了？说话那么难听你这又是何苦？ 都是码农，自己人喷自己的的劣根性你从哪学来的？ 就事论事是会怎么样？
