### ISSUE TITLE
Component series.wordCloud not exists.

### ISSUE THREAD

**Issue by songshuzhong** [ecomfe/echarts#4504]
#### 问题简述 (One-line summary)

字符图使用报错，什么鬼？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by zhump** [comment]
https://github.com/ecomfe/echarts/search?utf8=%E2%9C%93&q=wordCloud
