### ISSUE TITLE
怎么单单给y轴负半轴的背景设置透明度？？？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#4509]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以尝试用 [markArea](http://echarts.baidu.com/option.html#series-line.markArea)
