### ISSUE TITLE
我的天,这是真垃圾啊，动不动就报错。我说为什么echart比chartjs星星少呢。不敢相信这个项目的稳健性

### ISSUE THREAD

**Issue by eGirlAsm** [ecomfe/echarts#4510]
百度的一群饭桶

对不起啊，我太凶你们了。但确实我复制粘贴 然后发现总出错。
就像我进一个门，跨一步就摔倒，跨一步就摔倒。谅谁也是不想再进去这个门了吧。

http://echarts.baidu.com/demo.html#dynamic-data2

就这个例子，我复制粘贴到项目 一直提示 not found 啊,console log 打出来一排错误 。
我懒得再弄了。就你们官方的demo复制过来 一开始出错，不是垃圾是啥。

你们肯定会说，啊你都没仔细弄啥啥啥的。
我确实就是拿来主义者，拿来用不了,我还得各种调试找原因，浪费时间的项目，就是垃圾。

**Comment by mirari** [comment]
难得看到知道自己蠢还这么优越的

**Comment by banterise** [comment]
难得看到知道自己蠢还这么优越的

**Comment by zhump** [comment]
难得看到知道自己蠢还这么优越的

**Comment by pissang** [comment]
谢谢楼主让我认识到这个林子有多大

**Comment by kocokolo** [comment]
这货哪个公司的？感觉这货不适合搞技术

**Comment by eGirlAsm** [comment]
产品做得不好，还不让人说了？
苏格拉底说：“我比别人聪明是因为我知道我自己无知”，所以在你们看来我是愚蠢的，所以可笑的，我真心为你们的浅薄和无知感到悲伤。
百度就一个盈利性垃圾公司,看百度和谷歌的差距就能看出来，特别是那些假医院推广技术辣么厉害，害了多少人。
我不知道你们在维护什么，是你们就百度的员工还是因为你们也都是同百度一样没良心的垃圾啊？
毕竟自古都是物以类聚，人以群分。垃圾和垃圾在一块说一个不认识的人是垃圾一样，是多么可笑啊。
有人质疑我是外国人，在外国工作就是外国人了？
有人说我不适合搞技术，我就质疑产品问题很多，稳健性很差，所以就不适合搞技术了？
这是哪门子道理,是你们爹妈教你们的，还是你们的体育老师教你们的这种逻辑?
虽然我早已知道，就如伏尔泰说的：“世界是愚蠢和邪恶的”，叔本华说：“人类是愚蠢的”。
但未曾如此刻一样让我这样的震惊，因为我真实的见到了一群傻逼一样的中国人。
作为一个同样的中国人，我是多么恨，多么痛!
但我无法责怪你们的愚蠢，因为这是你们父母的错，是你们学校教育的错，是我们国家的错！

**Comment by SkillyZ** [comment]
哗众取宠
我感觉是高级黑

**Comment by TonyWuLihu** [comment]
请先让自己成为一个 contributor 再来喷，既然不好，那何不你贡献一份力量让他更好？莫非喷就可以让产品更好？

2017-03-14 14:39 GMT+08:00 Skilly <notifications@github.com>:

**Comment by errorrik** [comment]
test
