### ISSUE TITLE
echarts 有没有接口可以操作canvas？

### ISSUE THREAD

**Issue by plftzk** [ecomfe/echarts#4517]
使用echarts 3最新版本，请问echarts有没有接口可以操作canvas， 在ehcarts里添加图片及自定义表格的功能？

**Comment by pissang** [comment]
有接口，但是暂时没开放，@100pah 正在开发一个组件能够添加自定义的图形，具体见 https://github.com/ecomfe/echarts/issues/3620 这个 issue
