### ISSUE TITLE
ECharts3.0在移动端页面影响滑动。手指放在图表上无法拖动页面

### ISSUE THREAD

**Issue by Bruce6** [ecomfe/echarts#4518]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
3.3.0 和 3.3.1 中引入的 bug，下周一发布的新版本会修复这个问题

**Comment by Bruce6** [comment]
------------------ 原始邮件 ------------------
发件人: "Yi Shen";<notifications@github.com>;
发送时间: 2016年11月19日(星期六) 凌晨0:46
收件人: "ecomfe/echarts"<echarts@noreply.github.com>; 
抄送: "杨树丛"<2514628336@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ecomfe/echarts] ECharts3.0在移动端页面影响滑动。手指放在图表上无法拖动页面 (#4518)




3.3.0 和 3.3.1 中引入的 bug，下周一发布的新版本会修复这个问题

**Comment by shikelong** [comment]
额。。等待3.3.2修复 遇到同样的问题。
