### ISSUE TITLE
echarts实现barWidth自适应的源码

### ISSUE THREAD

**Issue by wdnlwzd** [ecomfe/echarts#4519]
#### 问题简述 (One-line summary)
想了解学习，echarts实现barWidth自适应的源码，可是我并不能找到具体实现位置，请问有人知道吗？谢谢！

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):
无

#### 重现步骤 (Steps to reproduce)
1.无
2.

#### 期望结果 (Expected behaviour)

告知echarts实现barWidth自适应的源码位置

#### 可能哪里有问题 (What went wrong)

无

#### ECharts配置项 (ECharts option)

```javascript
option = {
无
}

```

#### 其他信息 (Other comments)

无

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/blob/master/src/layout/barGrid.js 文件主要负责柱状图的布局
