### ISSUE TITLE
如何使用K线图与等距折线图进行混搭？

### ISSUE THREAD

**Issue by yongyaoli** [ecomfe/echarts#4520]
#### 问题简述 (One-line summary)
我使用K线图与等距折线图进行混搭不起效果
如何使用K线图与等距折线图进行混搭？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.3.1
+ 浏览器类型和版本 (Browser version):谷歌
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.K线图与等距折线图混搭
2.

#### 期望结果 (Expected behaviour)
K线图与等距折线图混搭

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/explore.html#sort=star~timeframe=all 贴个例子？
