### ISSUE TITLE
力导向图布局图的连接线能不能统一更改颜色

### ISSUE THREAD

**Issue by Shlpeng** [ecomfe/echarts#4525]
#### 问题简述 (One-line summary)
力导向图布局图的连接线能不能统一更改颜色，demo里面是蓝色，我想统一更改为红色是更改哪个属性

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):2
+ 浏览器类型和版本 (Browser version):firefox
+ 操作系统类型和版本 (OS Version):win7

#### 期望结果 (Expected behaviour)
力导向图布局图的连接线可以统一更改颜色

#### ECharts配置项 (ECharts option)
```javascript
option = {

}

```

**Comment by pissang** [comment]
`itemStyle.normal.linkStyle.color`
