### ISSUE TITLE
echarts的默认行为能否被监听到？能否监听画布的点击事件？

### ISSUE THREAD

**Issue by GloriaCHL** [ecomfe/echarts#4527]
#### 问题简述 (One-line summary)
echarts的默认行为能否被监听到？能否监听画布的点击事件？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 3.0
+ 浏览器类型和版本 (Browser version): chrome
+ 操作系统类型和版本 (OS Version):

#### 期望结果 (Expected behaviour)
比如饼状图，在手机浏览器上点击图形某一扇区默认是张开此扇区，这一张开事件能否被监听到？或者是否有回调？然后，点击画布空白区域，张开的扇区就会缩回原形，这个缩回的动作也是否可以监听或者有回调？我想监听这两个动作，做回调操作。有什么思路吗？

**Comment by pissang** [comment]
myChart.getZr().on( 'click', function (e) {} )

**Comment by GloriaCHL** [comment]
感谢回答。可能是我表达的不够清楚，实际上我想监听的是扇区的张开与缩回的事件，想借此知道是否有扇区被点击选中、取消选中的情景。大神的.getZr()方法可以监听到点击画布的事件，但点击扇区时候也会触发，这样我就不知道用户是选择了此扇区还是取消选择此扇区了。
或者，有什么其他的办法来实现我这个通过点击图形、画布来选择或取消选择扇区？

**Comment by pissang** [comment]
可以通过 ` if (e.target && e.target.dataIndex)` 判断是否选中了扇区

**Comment by GloriaCHL** [comment]
好的，非常感激，问题解决了

**Comment by PHenryy** [comment]
> 可以通过 ` if (e.target && e.target.dataIndex)` 判断是否选中了扇区

e.target.dataIndex 可能为 0 哦
