### ISSUE TITLE
增加地图蒙板

### ISSUE THREAD

**Issue by chenxiwei7** [ecomfe/echarts#4529]
#### 问题简述 (One-line summary)
增加地图蒙版，形成多个小块，显示不同颜色，有类似例子吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win10

#### 重现步骤 (Steps to reproduce)
1.增加地图蒙版，形成多个小块，显示不同颜色
2.

#### 期望结果 (Expected behaviour)
增加地图蒙版，形成多个小块，显示不同颜色

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

想显示成这样的：
![image](https://cloud.githubusercontent.com/assets/22286044/20470613/2bda7958-afe5-11e6-81f0-5a85b03023ab.png)

**Comment by zhump** [comment]
自己用div实现下呢？

**Comment by wuruihua** [comment]
可以调用zr.add()方法 添加矩形排列铺满屏幕就可以
