### ISSUE TITLE
地图中能监听缩放的事件吗？

### ISSUE THREAD

**Issue by newEchartster** [ecomfe/echarts#4530]
#### 问题简述 (One-line summary)
地图中能监听缩放的事件吗？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.2
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

**Comment by jnie666** [comment]
有个geoRoam事件

**Comment by Quintalq** [comment]
@jnie666  找遍了所有api 都没有这个事件

**Comment by qyfang** [comment]
georoam事件
