### ISSUE TITLE
echarts 3.0版本失去了对标注动画的支持？

### ISSUE THREAD

**Issue by qq420243952** [ecomfe/echarts#4533]
#### 重现步骤 (Steps to reproduce)
1.在2.0的配置项文档中series.type = map的情况下具有 markPoint.effect对象配置项，而在3.0中却没有

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-effectScatter

**Comment by qq420243952** [comment]
上下跳动的动画没有了？
