### ISSUE TITLE
父容器为section时，图表间歇性报获取不到宽和高的错误

### ISSUE THREAD

**Issue by liwenyongHust** [ecomfe/echarts#4534]
#### 问题简述 (One-line summary)
父容器为section时，echarts间歇性获取不到宽和高，图表无法显示
而且延迟加载后又可以获取到宽高
将section改为div后又可以获取到宽高

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.父容器标签设为section
2.百分比指定echarts的宽高

#### 期望结果 (Expected behaviour)
图表能够显示出来

#### 可能哪里有问题 (What went wrong)
echars解析dom的时候可能有问题

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
取不到就是 dom 还没准备好，最新版本支持初始化的时候传入宽高，http://echarts.baidu.com/api.html#echarts.init
