### ISSUE TITLE
visualMap支持对阴影颜色的设置吗？

### ISSUE THREAD

**Issue by twoeo** [ecomfe/echarts#4535]
#### 问题简述 (One-line summary)
在金融行业的图表中，大量出现带正负的阴影折线图。
如折线在0点上方时，阴影为红色；在0点下方时，阴影为绿色。
目前在文档中，没有发现能实现这样功能的设置。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
3.3.1
+ 浏览器类型和版本 (Browser version):
Chrome
+ 操作系统类型和版本 (OS Version):
Win7

**Comment by pissang** [comment]
暂时不支持

**Comment by twoeo** [comment]
了解~ 建议纳入考虑，金融行业大量此类图表。

**Comment by pissang** [comment]
谢谢建议，有参考的例子或者图片么？

**Comment by twoeo** [comment]
如图，同时建议如图右侧轴上的指示标记，如此可以便于多条线使用同一根轴。
目前EChart仅通过颜色区分，则不便多根线使用一根轴。
![](http://p1.bpimg.com/567571/b89f67d2eb8da0b1.png)

**Comment by pissang** [comment]
哦你发的这种表现形式用 visualMap 是可以实现的，我写了个例子你参考下 http://gallery.echartsjs.com/editor.html?c=xHkzsfNZMg

**Comment by twoeo** [comment]
原来如此，只要有areaStyle，那么visualMap中的color就会同时对areaStyle的color生效。

**Comment by twoeo** [comment]
@pissang 这个例子在最新的dist中运行良好。
但如果使用最新Git中的代码编译，则画出来的阴影都是黑的。
Debug发现是 `LineView.js` 239行处 `visualMeta.stops` 为 `[]`。

在pieces中加入一个value=0的点才正常。
```javascript
pieces: [{
  lt: 0,
  color: 'red'
},
{
  value: 0,
  color: 'black'
},
{
  gt: 0,
  color: 'green'
}]
```

**Comment by twoeo** [comment]
@pissang 另外这个有办法可以只根据VisualMap修改Area的颜色，而不改变Symbol的颜色吗？
查找了文档似乎没见到说明，itemStyle中的color会被覆盖，borderColor不会。
