### ISSUE TITLE
如何添加水印

### ISSUE THREAD

**Issue by Warriorsliuzhu** [ecomfe/echarts#4536]
#### 问题简述 (One-line summary)
echarts 图表如何添加水印？看了api接口，没有提供。能提供一个基础的思路么？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

Echarts 3.x   
Chrome  54.0.2840.99 m (64-bit)   
win7系统

**Comment by zhump** [comment]
1.加背景图片，但是这样下载的时候 ，水印下载不下来
2.改源码？drawImage的时候放进去？ @pissang

**Comment by Warriorsliuzhu** [comment]
@zhump 是的，你提的这个问题非常好。 你改源码了？

**Comment by zhump** [comment]
@Warriorsliuzhu 搞错了。。。我很久以前用echarts干的事。。当时改了一下源码。为了应付需求，换了工作，有段时间没搞图表了，，最近因为工作需要，又回头学习echarts了，，，，发现 halloween.js这个主题，是有背景图片的 并且可以导出，，， backgroundColor->image 这个属性 ，我试了一下 是可以的。你试试看呢

**Comment by Warriorsliuzhu** [comment]
@zhump 嗯嗯，谢谢了。你说的这个，我有空再试试，我手动操作dom，实现了水印功能，但是导出的时候是看不到水印的，官方说现在有直接操作canvas的接口，不过暂时未开放，后期会开放，期待。highchart是有接口的，直接传参数就可以轻松完成水印功能，而且导出也是没问题的。

**Comment by zhump** [comment]
额 echarts现在 也是设置 backgroundColor ->image  直接传参数就可以轻松完成水印功能，而且导出也是没问题的 ：）

**Comment by Warriorsliuzhu** [comment]
啊，这么666666666666，我有空试下。

**Comment by qianduan-duanwei** [comment]
我试了一下backgroundColor->image方法但是报错，说找不到new echarts.graphic.Pattern方法用的是echarts3.3.1版本

**Comment by zhump** [comment]
感觉更吊了 http://echarts.baidu.com/gallery/editor.html?c=line-y-category

**Comment by qianduan-duanwei** [comment]
@zhump 厉害官网今天新更新的，增加了这个功能

**Comment by Warriorsliuzhu** [comment]
@zhump  哈哈哈哈哈，这个确实很6666666666666666666666666

**Comment by 100pah** [comment]
另外可参见这个：<http://echarts.baidu.com/option.html#graphic>
