### ISSUE TITLE
echarts3.x 还能像echarts2.x那样，支持svg的地图扩展吗？

### ISSUE THREAD

**Issue by gjn0314** [ecomfe/echarts#4537]
#### 问题简述 (One-line summary)
echarts3.x 还能像echarts2.x那样，支持svg的地图扩展吗？
例如2.x中的人体图，足球场的svg扩展

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.x
+ 浏览器类型和版本 (Browser version):IE
+ 操作系统类型和版本 (OS Version):windowsXP

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by partical** [comment]
我们公司有时候需要定制一些地图，比如包括一些经济开发区的，现在的解决办法是自己写了一个工具，将svg的图片转成echarts支持的地图json.你可以参考这个思路自定义地图。

**Comment by pissang** [comment]
@partical 方便的话可否贡献转换工具供其他人使用？

**Comment by partical** [comment]
@pissang OK,有时间将这个工具剥离，公布出来。

**Comment by stsshenwei** [comment]
@pissang 现在这个工具剥离出来了吗？能方便贡献一下怎么将svg图片转换为echarts支持的json吗

**Comment by webLoginjun** [comment]
请问能方便贡献一下怎么将SVG图片转换成json么？

**Comment by plainheart** [comment]
目前似乎可以通过 `echarts.registerMap` 注册所需的 svg 扩展地图，然后在 `series.map` 中使用即可。

```js
$.get('football.svg', function (svg) {
  echarts.registerMap('football', {
     svg: svg
  }
});
```

mapbox 也提供了一个 svg 转 geoJSON 的插件：[svg-to-geojson](https://github.com/mapbox/svg-to-geojson)
不过转换出来只是结构，不包含样式。
