### ISSUE TITLE
如何绘制证券行情图形

### ISSUE THREAD

**Issue by bys** [ecomfe/echarts#4541]
关于证券行情，想用echarts 3绘制。但是交易中间是有休市的情况。比如11:30 到 13:00之间是没有行情的，如何让两个点折叠在一起？

**Comment by pissang** [comment]
把这个时间过滤了？

**Comment by LiuXiaoJie** [comment]
@pissang 横坐标轴type=time，不知道这里说的把时间过滤了是怎么实现，希望得到你的解答。
