### ISSUE TITLE
急，为什么我想切换到市级地图，而不得已，json数据，注册都已经搞好了，

### ISSUE THREAD

**Issue by twolun** [ecomfe/echarts#4548]
#### 问题简述 (One-line summary)
想要显示城市地图，注册已经成功，只是显示一个很小的图块

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.0
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):window7 64

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
<script type="text/javascript" src="/node_modules/echarts/dist/echarts.min.js"></script>
<script type="text/javascript" src="/assets/chengdu.js"></script>
<script type="text/javascript">
   var chart = echarts.init(document.getElementById('index'));
    chart.setOption({
        series: [{
            type: 'map',
            name: 'chengdu',
            map: 'chengdu',
        }]
    });
	</script>

```

**Comment by Gyyi** [comment]
是不是div的长宽没有定义，貌似曾经遇到一样的问题，地图缩挤成了一团，就是div长宽未定义引起的
