### ISSUE TITLE
现在多个grid时，series中的markLine是画在整个图上，而不是对应的grid上的

### ISSUE THREAD

**Issue by zjjott** [ecomfe/echarts#4552]
#### 问题简述 (One-line summary)
指定markLine的X、Y为百分比时，最后画的标记线是整个图的标记线，而不是series里的标记线

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
echarts@3.2.3
+ 浏览器类型和版本 (Browser version):
Chrome 版本 54.0.2840.98
+ 操作系统类型和版本 (OS Version):
OSX 10.12

#### 重现步骤 (Steps to reproduce)
1.setOption

#### 期望结果 (Expected behaviour)
期待结果是每个series绘的markLine应当绘在对应的grid内

#### ECharts配置项 (ECharts option)

```javascript
var dataAll = [
];

var markLineOpt = {
    animation: false,
    data: [[{
        x:0,
        y:"0%"
    }, {
        x:"50%",
        y:"100%"
    }]]
};

option = {
    grid: [
        {x: '7%', y: '7%', width: '38%', height: '38%'},
        {x2: '7%', y2: '7%', width: '38%', height: '38%'},
    ],
    xAxis: [
        {gridIndex: 0, min: 0, max: 20},
        {gridIndex: 1, min: 0, max: 20},
    ],
    yAxis: [
        {gridIndex: 0, min: 0, max: 15},
        {gridIndex: 1, min: 0, max: 15},
    ],
    series: [
        {
            name: 'I',
            type: 'scatter',
            xAxisIndex: 0,
            yAxisIndex: 0,
            data: dataAll[0],
            markLine: markLineOpt
        },
        {
            name: 'II',
            type: 'scatter',
            xAxisIndex: 1,
            yAxisIndex: 1,
            data: dataAll[1],
            markLine: markLineOpt
        }
    ]
};

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/3733548/20593016/89bd989c-b26b-11e6-8b6c-d17e37cd5ee5.png)
实际上应当是图片上对应的红线，而不是现在的虚线

**Comment by pissang** [comment]
x, y 就是用来表示 `像素 / 屏幕百分比` 值的

**Comment by zjjott** [comment]
@pissang 
哦~理解错了，看来coord才是我要的，只是coord不支持百分比，得自己算。。。get了~
