### ISSUE TITLE
echart3地图点击事件问题

### ISSUE THREAD

**Issue by cxkobe** [ecomfe/echarts#4558]
您们好,地图的点击事件中我是这样写的:
单文件引入的3.3.2版本的echarts.js
 var ecConfig = echarts.config;
		 var zrEvent = zrender.tool.color;
 myChart.on(ecConfig.EVENT.MAP_SELECTED, function (param){   })；
但是发现 没有echarts.config
如图:![image](https://cloud.githubusercontent.com/assets/23737315/20620945/3cdc39da-b337-11e6-8171-1e82daf8f277.png)

在2.几版本的时候是可以用echarts.config的 ，请问我改如何解决

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.3.2
+ 浏览器类型和版本 (Browser version):ie9
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
跟 dom 事件一样用字符串，chart.on('click', function () {})

**Comment by cxkobe** [comment]
你好 我试过你说的方式，会提示对象不支持on属性或方法

**Comment by xiaoguxg** [comment]
如果我想获得外面这些区域的点击事件怎么办
![image](https://cloud.githubusercontent.com/assets/8435230/21419511/03c8c1c2-c863-11e6-9383-137d5106c887.png)

**Comment by 100pah** [comment]
chart.getZr().on('click', function () { ... });
