### ISSUE TITLE
自定义geogson 县级地图，导入echart之后 发现地图变形了，怎么回事

### ISSUE THREAD

**Issue by wanglk** [ecomfe/echarts#4559]
#### 问题简述 (One-line summary)
 #自定义了geogson县级地图，导入echart之后显示出来是变形的

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):  3.0
+ 浏览器类型和版本 (Browser version):  所有浏览器
+ 操作系统类型和版本 (OS Version): Mac

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
 期望显示的地图和我画的地图一样，不要变形

#### 可能哪里有问题 (What went wrong)
echart是否有地图比例的设置，我画的地图是正常的，导出geogson之后引入到echart就被压挤得有点变形了

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

我自定义的geogson：

{"type":"FeatureCollection","features":[
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[470.45814800000005,777.80337],[480.613797,778.3887],[497.380753,767.340128],[517.715144,752.371097],[530.201175,725.284281],[543.043944,720.2946019999999],[548.751844,706.394788],[553.746261,695.346216],[564.091826,691.425758],[581.357414,668.96001],[581.357414,657.499498],[569.4217480000001,657.499498],[537.671564,657.499498],[494.148825,661.063554],[474.52791799999994,663.201988],[445.98842199999996,673.1813400000001],[438.496808,680.665855],[415.66520499999996,684.586317],[389.99080499999997,685.792951],[388.965802,689.7427799999999],[393.651522,698.812759],[405.07297400000004,715.197237],[432.894446,743.577493],[456.32305099999996,752.94005],[463.429565,760.102283],[468.99386100000004,773.268381],[470.45814800000005,777.80337]]]},"properties":{"FID_":0,"´åÃñ":"庄房村民委员会"}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[470.45814800000005,777.80337],[471.92243600000006,782.338359],[470.75100599999996,796.382196],[471.92243600000006,805.452175],[478.75932400000005,824.914716],[478.173609,834.277273],[476.41646399999996,847.73595],[479.930754,865.5833279999999],[483.15219,870.8497689999999],[493.109344,877.286527],[521.809392,874.945885],[537.037988,869.386866],[552.852299,869.0942869999999],[573.645184,869.6794480000001],[590.04521,879.919747],[598.5380809999999,881.675225],[610.252387,870.264608],[627.823843,876.701366],[633.973854,876.701366],[637.780997,874.653306],[639.831004,870.5571869999999],[642.759578,865.5833279999999],[643.345293,859.7317300000001],[641.295295,847.4433710000001],[644.5167230000001,835.155012],[652.186001,814.66545],[651.976995,809.236474],[650.095947,795.455221],[647.58789,789.399824],[642.571768,776.662606],[643.616795,769.1455589999999],[644.266912,769.0914349999999],[644.00242,765.914509],[644.715904,762.3504519999999],[646.142879,748.4506389999999],[637.937774,739.540501],[633.656849,733.125202],[635.4405690000001,726.709901],[627.476637,712.631563],[623.065233,705.820403],[614.242425,699.009243],[607.023761,695.803994],[596.997844,678.175109],[589.378146,672.565917],[581.357414,668.96001],[564.091826,691.425758],[553.746261,695.346216],[548.751844,706.394788],[543.043944,720.2946019999999],[530.201175,725.284281],[517.715144,752.371097],[497.380753,767.340128],[480.613797,778.3887],[470.45814800000005,777.80337]]]},"properties":{"FID_":0,"´åÃñ":"发古苴村民委员会"}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[644.266912,769.0914349999999],[648.632917,768.7279480000001],[654.02415,774.7864950000001],[657.457796,780.591771],[659.834932,786.3970469999999],[661.155565,790.091314],[676.7390389999999,797.21597],[684.134586,800.118608],[702.095195,807.771018],[706.057089,798.799228],[707.377722,791.674569],[712.1320019999999,784.8137889999999],[712.9243809999999,773.467112],[718.9992940000001,768.981219],[725.866587,766.6063320000001],[734.3186360000001,768.717341],[741.4500519999999,773.730991],[748.845599,773.2032370000001],[762.580184,768.981219],[770.76811,763.967569],[779.7484139999999,764.231447],[788.200464,765.5508269999999],[791.141002,764.089435],[787.443225,745.881978],[783.2172,739.812827],[773.444517,737.4379389999999],[766.313101,727.410646],[766.313101,720.5498650000001],[773.444517,713.95296],[780.311809,716.063969],[787.179101,716.8555980000001],[795.6311509999999,714.216835],[800.121307,713.1613309999999],[800.121307,707.61993],[798.272418,706.564426],[791.9333809999999,705.508921],[780.311809,701.550779],[776.349908,694.6899980000001],[776.878163,669.621761],[785.5943440000001,663.552606],[788.1972519999999,654.605001],[783.257601,640.30653],[777.193157,634.247841],[779.108242,622.768213],[778.150703,615.752889],[771.447895,611.6074679999999],[768.575264,611.6074679999999],[757.403931,606.505413],[745.901549,588.218893],[743.667282,586.305624],[736.326118,580.246932],[736.166527,576.898708],[708.832474,564.975348],[708.832474,568.430924],[709.4613519999999,576.284506],[708.5180280000001,582.567369],[705.6880570000001,584.766373],[696.25482,585.3946599999999],[690.2804309999999,581.939083],[682.100881,586.194339],[672.273327,594.673728],[667.359546,603.5994019999999],[657.978696,604.49197],[652.1715009999999,606.277104],[649.491259,617.88048],[638.770291,635.731825],[606.1663570000001,645.738118],[581.357414,657.499498],[581.357414,668.96001],[589.378146,672.565917],[596.997844,678.175109],[607.023761,695.803994],[614.242425,699.009243],[623.065233,705.820403],[627.476637,712.631563],[635.4405690000001,726.709901],[633.656849,733.125202],[637.937774,739.540501],[646.142879,748.4506389999999],[644.715904,762.3504519999999],[644.00242,765.914509],[644.266912,769.0914349999999]]]},"properties":{"FID_":0,"´åÃñ":"酒洲村民委员会"}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[389.99080499999997,685.792951],[415.66520499999996,684.586317],[438.496808,680.665855],[445.98842199999996,673.1813400000001],[474.52791799999994,663.201988],[494.148825,661.063554],[537.671564,657.499498],[569.4217480000001,657.499498],[581.357414,657.499498],[581.357414,652.132438],[582.428545,632.422289],[576.52595,632.1015179999999],[560.919631,626.07752],[557.3727389999999,627.140577],[552.761786,627.140577],[544.958623,620.7622269999999],[531.12575,607.29682],[522.613209,600.918472],[511.61785,600.918472],[495.65684100000004,596.311884],[480.050522,595.603179],[458.05979699999995,592.414002],[450.96602,586.035651],[441.7441,574.696363],[426.49247,570.7984809999999],[420.81744199999997,567.96366],[413.368976,567.96366],[400.60017,560.522251],[391.732939,568.318013],[380.028202,572.924597],[376.835999,573.278953],[370.096903,560.522251],[346.519897,555.573367],[344.686349,559.603355],[341.752663,564.366071],[339.919115,572.792411],[338.818985,577.188763],[335.51858599999997,583.050564],[329.651222,588.912365],[327.450962,592.942353],[328.184387,602.101418],[325.617414,606.864133],[325.617414,609.062308],[330.017935,613.82502],[332.951621,616.755923],[333.68503799999996,622.6177240000001],[332.951621,629.944975],[332.584908,633.974966],[334.785169,639.836767],[335.51858599999997,637.272229],[339.18568999999997,632.143152],[340.652533,630.6777030000001],[342.119376,631.0440639999999],[341.019246,647.1640179999999],[352.753974,651.9267309999999],[377.25150299999996,659.607046],[381.058646,661.947688],[381.058646,662.5328450000001],[379.008648,668.677025],[379.594363,671.895405],[386.330088,672.187984],[391.015808,681.843123],[389.99080499999997,685.792951]]]},"properties":{"FID_":0,"´åÃñ":"必达村民委员会"}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[581.357414,657.499498],[606.1663570000001,645.738118],[638.770291,635.731825],[649.491259,617.88048],[652.1715009999999,606.277104],[657.978696,604.49197],[667.359546,603.5994019999999],[672.273327,594.673728],[682.100881,586.194339],[690.2804309999999,581.939083],[696.25482,585.3946599999999],[705.6880570000001,584.766373],[708.5180280000001,582.567369],[709.4613519999999,576.284506],[708.832474,568.430924],[708.832474,564.975348],[690.909316,561.833916],[687.4504599999999,559.634912],[684.934928,556.49348],[682.104956,551.153045],[680.8471940000001,550.524758],[671.09951,551.153045],[666.382884,550.210613],[663.552913,548.639899],[661.037381,542.985319],[662.6095889999999,536.702455],[662.6095889999999,530.419588],[658.8362950000001,522.2518650000001],[652.973299,509.290858],[649.823402,503.390401],[647.460976,501.423583],[634.073921,495.52312699999993],[627.774129,488.44258099999996],[636.4363400000001,482.542125],[638.011288,479.39521500000006],[630.924025,470.741212],[617.143231,469.16775700000005],[610.055961,467.20093899999995],[600.606272,463.660667],[592.7315309999999,453.433208],[588.4004259999999,439.27211500000004],[577.782637,418.016368],[574.669879,419.57127],[570.83971,413.51257999999996],[568.6054429999999,399.163046],[563.179363,391.828842],[521.664046,361.646993],[472.637958,327.89885],[463.77955599999996,336.826555],[461.84908600000006,341.005276],[463.77955599999996,346.46975699999996],[498.84978,400.793129],[497.884541,423.936817],[504.955075,451.554344],[522.5374059999999,476.77683099999996],[533.357308,483.53285300000005],[539.218082,488.937674],[543.726371,497.044901],[556.349582,504.251325],[557.251245,510.55695],[553.193779,526.7714070000001],[554.9970959999999,538.481846],[561.3087019999999,552.444296],[576.186062,567.75795],[582.160488,581.095267],[580.556337,611.1445],[582.561522,627.170759],[582.561522,629.975353],[582.428545,632.422289],[581.357414,652.132438],[581.357414,657.499498]]]},"properties":{"FID_":0,"´åÃñ":"大麦村民委员会"}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[582.428545,632.422289],[582.561522,629.975353],[582.561522,627.170759],[580.556337,611.1445],[582.160488,581.095267],[576.186062,567.75795],[561.3087019999999,552.444296],[554.9970959999999,538.481846],[553.193779,526.7714070000001],[557.251245,510.55695],[556.349582,504.251325],[543.726371,497.044901],[539.218082,488.937674],[533.357308,483.53285300000005],[522.5374059999999,476.77683099999996],[504.955075,451.554344],[497.884541,423.936817],[498.84978,400.793129],[463.77955599999996,346.46975699999996],[461.84908600000006,341.005276],[463.77955599999996,336.826555],[472.637958,327.89885],[447.29978700000004,310.456785],[444.57914400000004,297.319478],[440.751001,299.137834],[443.36262300000004,304.935934],[443.072441,308.41479100000004],[442.782259,318.27156],[441.331358,324.649468],[440.751001,332.476903],[442.49207699999994,342.623577],[448.58585899999997,358.27844300000004],[450.311114,372.88852099999997],[440.444991,386.224147],[435.511929,390.862627],[424.775268,394.051581],[407.654643,406.517496],[401.560861,409.126639],[392.855465,409.126639],[385.891138,409.126639],[374.864302,424.78150700000003],[369.060695,433.768559],[361.516019,438.696945],[355.422237,441.01618499999995],[353.461468,453.618595],[356.723553,473.17255],[357.049767,484.253128],[357.049767,491.748809],[353.135261,497.61499699999996],[345.306258,498.91859500000004],[343.586211,508.312593],[342.486081,524.066183],[346.153184,539.087052],[346.153184,546.780667],[346.519897,555.573367],[370.096903,560.522251],[376.835999,573.278953],[380.028202,572.924597],[391.732939,568.318013],[400.60017,560.522251],[413.368976,567.96366],[420.81744199999997,567.96366],[426.49247,570.7984809999999],[441.7441,574.696363],[450.96602,586.035651],[458.05979699999995,592.414002],[480.050522,595.603179],[495.65684100000004,596.311884],[511.61785,600.918472],[522.613209,600.918472],[531.12575,607.29682],[544.958623,620.7622269999999],[552.761786,627.140577],[557.3727389999999,627.140577],[560.919631,626.07752],[576.52595,632.1015179999999],[582.428545,632.422289]]]},"properties":{"FID_":0,"´åÃñ":"八角村民委员会"}},
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[736.166527,576.898708],[736.006936,573.550485],[743.028918,569.086187],[776.5429349999999,552.185627],[787.075904,552.185627],[791.86362,550.272355],[789.310171,544.85142],[779.415558,534.96619],[777.808052,517.6300769999999],[783.234132,493.395313],[784.191678,476.81363],[786.7451269999999,463.420733],[784.51086,451.941108],[784.51086,443.96914699999996],[783.872496,435.99718600000006],[769.773931,413.863172],[758.602597,399.832518],[753.814881,398.238127],[734.983194,423.429525],[725.407762,428.531583],[714.874785,429.16934100000003],[699.554092,425.02392000000003],[657.7413730000001,403.021305],[646.8892139999999,397.281492],[635.71788,396.00597799999997],[614.24834,406.497253],[598.927647,406.81613],[590.6289360000001,406.81613],[582.0110440000001,408.091645],[579.7767769999999,417.020244],[577.782637,418.016368],[588.4004259999999,439.27211500000004],[592.7315309999999,453.433208],[600.606272,463.660667],[610.055961,467.20093899999995],[617.143231,469.16775700000005],[630.924025,470.741212],[638.011288,479.39521500000006],[636.4363400000001,482.542125],[627.774129,488.44258099999996],[634.073921,495.52312699999993],[647.460976,501.423583],[649.823402,503.390401],[652.973299,509.290858],[658.8362950000001,522.2518650000001],[662.6095889999999,530.419588],[662.6095889999999,536.702455],[661.037381,542.985319],[663.552913,548.639899],[666.382884,550.210613],[671.09951,551.153045],[680.8471940000001,550.524758],[682.104956,551.153045],[684.934928,556.49348],[687.4504599999999,559.634912],[690.909316,561.833916],[708.832474,564.975348],[736.166527,576.898708]]]},"properties":{"FID_":0,"´åÃñ":"扎郎村民委员会"}}
]}

**Comment by pissang** [comment]
`aspectScale: 1`

**Comment by wanglk** [comment]
aspectScale 这个属性加在什么地方啊？

**Comment by wanglk** [comment]
你好，这个属性该加在上面地方呢？试过加在几个地方没有作用

**Comment by 100pah** [comment]
```js
geo: {
    aspectScale: 1
}
```
