### ISSUE TITLE
symbolRotate的问题

### ISSUE THREAD

**Issue by SCREENPILOT** [ecomfe/echarts#4560]
我最近在做一个图表，主要是展现气象要素的变化，有一个是风向风速的，折线为风速，想利用symbol为‘arrow’的标示按照我的数组相应旋转，从而表现出风向的变化，请问这个有什么办法吗？

**Comment by pissang** [comment]
说一下你碰到的问题？

**Comment by SCREENPILOT** [comment]
series : [
          {
              name:'降水量（mm）',
              type:'bar',
              symbol: 'arrow',
              symbolRotate:[],//中括号处我想以data中数组来做出相应的旋转，从而表示风向，不知怎么才能正              确识别出来
              data:[],
          }
      ]

**Comment by SCREENPILOT** [comment]
series : [
          {
              name:'风向风速',
              type:'line',
              symbol: 'arrow',
              symbolRotate：[]，/,/中括号处我想让箭头按照data中数组相应的旋转，从而表示风向的变化，不知如何才能正确识别出来。
              data:[]
              
          }
      ]

**Comment by SCREENPILOT** [comment]
如果json.data的每个元素写为[2,120],如何把第二个值赋给symbolRotate,第一个值给data

**Comment by kener** [comment]
应该还支持data级的定义吧？ @pissang

**Comment by pissang** [comment]
@kener 嗯支持，可以每个数据都设定 symbolRotate

**Comment by SCREENPILOT** [comment]
"chart3data":[
[value:1,symbolRotate:-90],[value:2,symbolRotate:-100],[value:1,symbolRotate:-80]
]
是这样在data里赋值吗？但是怎么传回到series里呢？

**Comment by pissang** [comment]
是的，直接赋值到 `series.data` 就行了，什么是传回 series 里？

**Comment by SCREENPILOT** [comment]
myChart3.setOption({
series : [
          {
              name:'风向风速（deg|m/s）',
              type:'line',
              smooth:'true',
              symbol: 'image://img/LocationArrow.png',
              symbolOffset :[0,-3.5],
              symbolSize: 20,
              symbolRotate:[],
              data:[],
              markLine : {
                  symbol : 'none',
                  itemStyle : {
                      normal : {
                          color:'#1e90ff',
                          label : {
                              show:false
                          }
                      }
                  },
                  data : [
                      {type : 'average', name: '平均值'}
                  ]
                  
              }
          }
      ]
）}；
$.get('charts/data2.json').done(function (data) {
myChart3.setOption({  
                          xAxis: {  
                              data: data.axisData  
                          },  
                          series: [{  
                              name: '风向风速（deg|m/s）',  
                              data: data.chart3data
                          }]  
                      });
}
这样不行，是哪里需要改一下？

**Comment by pissang** [comment]
能否在 http://gallery.echartsjs.com/explore.html 建个例子我们看下？

**Comment by SCREENPILOT** [comment]
http://gallery.echartsjs.com/editor.html?c=xB1zJoQFMl&v=3

**Comment by pissang** [comment]
代码跑不起来，你要觉得数据没法贴到公共场合，可以放几个假数据

**Comment by SCREENPILOT** [comment]
数据都是我自己顺便设来测试的，可以放进去，我是从json数据里面读取的，我再把数据贴上去看看，其实格式就是data=[ [150,1],[140,2],......    ]这样的

**Comment by SCREENPILOT** [comment]
http://gallery.echartsjs.com/editor.html?c=xB1zJoQFMl&v=4

**Comment by SCREENPILOT** [comment]
请跳到最新版本查看代码，但是还是无法调通

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=xrJI0BoqMe
