### ISSUE TITLE
地图宽度问题

### ISSUE THREAD

**Issue by cxkobe** [ecomfe/echarts#4561]
#### 问题简述 (One-line summary)
您好,请问地图怎么设置宽度呢？如图，太窄了，汉字展示不全，想高度不变，变宽一点
![image](https://cloud.githubusercontent.com/assets/23737315/20638206/dc133c94-b3da-11e6-9e48-39100a054bc5.png)

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-map.width
