### ISSUE TITLE
3.0中的地图mapselectchanged事件捕获不到 

### ISSUE THREAD

**Issue by hezhongfeng** [ecomfe/echarts#4563]
现在只能使用鼠标的`click`事件代替
还有个问题就是
我的series中有几组数据
`click`事件中的‘params’里面的value是几组数据之和
怎么才能分别读取到地图里面的`name`和`value`？
[根据这个实例做的](http://echarts.baidu.com/demo.html#map-china-dataRange)

**Comment by pissang** [comment]
我试了可以的

**Comment by hezhongfeng** [comment]
[这里](http://codepen.io/hezf/pen/QGMzEG)有个例子
感觉我哪里理解的不对
`mapselectchanged`被我注释了

**Comment by pissang** [comment]
你需要用 [selectedMode](http://echarts.baidu.com/option.html#series-map.selectedMode) 开启选择的功能

**Comment by hezhongfeng** [comment]
get
