### ISSUE TITLE
地图事件中的参数，怎么能包含series中的几组数据

### ISSUE THREAD

**Issue by hezhongfeng** [ecomfe/echarts#4564]
地图series中有几组数据
`click`事件中的‘params’里面的value是几组数据之和
怎么才能分别读取到地图里面的`name`和`value`？
[根据这个实例做的](http://echarts.baidu.com/demo.html#map-china-dataRange)

**Comment by pissang** [comment]
可以通过  dataIndex 索引自己传进去的原始数据

**Comment by hezhongfeng** [comment]
我想我没描述清楚
我的意思是和这个实例一样的
比如新疆这个省份，分别有iphone3和iphone4的销量
我点击新疆这个省份，`params`里怎么才能够分别获得iphone3和iphone的销量？
现在的`value`是一个总数
```
$vars:Array[3]
color:"#c23531"
componentSubType:"map"
componentType:"series"
data:Object
dataIndex:2
dataType:undefined
event:Object
name:"白城市"
seriesIndex:0
seriesName:"服务电话"
seriesType:"map"
type:"click"
value:1606
__proto__:Object
```

**Comment by pissang** [comment]
现在没有直接的办法，param 里有 `name` 和 `dataIndex`，你可以根据这两个属性从你传入的数据中分别索引每个系列的值（比如 iphone 3 和 iphone

**Comment by hezhongfeng** [comment]
谢谢回答
看来还得去访问数据源，直接读取`name:"白城市"`就可以了

**Comment by pissang** [comment]
嗯，会稍微麻烦点😁
