### ISSUE TITLE
如何让上下排列的多个grid中的y轴坐标上下对齐呢？面前界面如图所示。

### ISSUE THREAD

**Issue by hanhui** [ecomfe/echarts#4565]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

#### 其他信息 (Other comments)

![image](https://cloud.githubusercontent.com/assets/1829623/20645898/abdb9f1c-b4a7-11e6-813b-2a0f89749b2e.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#grid.containLabel 设成false
