### ISSUE TITLE
2.0的chord怎么用3.0实现

### ISSUE THREAD

**Issue by mcgradyzhu** [ecomfe/echarts#4566]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/demo.html#graph-circular-layout 用这个替代可以不？

**Comment by mcgradyzhu** [comment]
可以用这个代替，但是怎么设置颜色以及怎么碰到圆圈让只显示和他有关系的图http://echarts.baidu.com/echarts2/doc/example/chord2.html我指的是和这个例子的效果差不多如何制作

**Comment by mcgradyzhu** [comment]
http://echarts.baidu.com/echarts2/doc/example/chord2.html

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-graph.focusNodeAdjacency

**Comment by mcgradyzhu** [comment]
http://echarts.baidu.com/demo.html#graph-circular-layout     的legend    data如何修改啊，大神。。我改了半天还是类目1 2 3 4 5 6 7 8
