### ISSUE TITLE
天呀，能否bower版本只保留基础的信息就行呀

### ISSUE THREAD

**Issue by cipchk** [ecomfe/echarts#4568]
#### 问题简述 (One-line summary)

百度，你知道吗？bower只是一个为了解决类库依赖，并没有必要把整个git库全放到bower里面。
百度，你知道吗？用了三个小时，只下载14%。
百度，你知道吗？我已经用梯子了。
百度，你知道吗？当我看到 4.0KiB/s 相死的心都有。
百度，你知道吗？我突然有种想出国去下载个 `echarts` 然后再回国。
你知道吗？好累、心累……

**Comment by pissang** [comment]
我们不提供 bower 包的维护
