### ISSUE TITLE
dom 定义了宽度和高度 为什么还是会提示Can't get dom width or height

### ISSUE THREAD

**Issue by blazert** [ecomfe/echarts#4569]
已经定了div的宽和高了  控制台还是提示Can't get dom width or height

**Comment by pissang** [comment]
初始化的时候无法获取 dom 的 clientWidth 和 clientHeight，新版本支持初始化的时候指定高宽，http://echarts.baidu.com/api.html#echarts.init

**Comment by codering** [comment]
@pissang 新版本初始化时指定heigth, width， 也会有警告有同样的警告信息。

**Comment by weieh** [comment]
遇到同样的问题，页面初始化时定义了div的宽和高了 控制台还是提示Can't get dom width or height

**Comment by keyiis** [comment]
@pissang 希望ts文件能更新到最新版，0.0.5版本中 init 没有width和height

**Comment by keyiis** [comment]
@pissang 的确加了width和height 还是报同样的错误 Can't get dom width or height

**Comment by Shane1121** [comment]
@pissang  echarts 3.5.1版本依然还是warning提示Can't get dom width or height

**Comment by hithto** [comment]
一樣有問題 echarts.js:1618 Can't get dom width or height
