### ISSUE TITLE
地图地区汉字位置

### ISSUE THREAD

**Issue by cxkobe** [ecomfe/echarts#4570]
您好,请问地图中如何设置地区汉字位置呢?
目前默认的不是居中；（p.s：上传不了图片了,不知道我描述的是否清楚）

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by earthpea** [comment]
根据我的观察，汉字的位置是在行政中心的地点，全国地图，省名就在省会的位置，省级地图，地市名在所在区市的位置，市级地图，县名在该县驻地所在镇的位置，并不是在地图的正中间。

**Comment by 100pah** [comment]
在 geoJson 中，可以修改 `cp` 字段的经纬度，则能调整名字位置
