### ISSUE TITLE
关系图表，能否鼠标不移上去也能控制hover的状态？

### ISSUE THREAD

**Issue by zhangdaren** [ecomfe/echarts#4573]
关系图表，能否鼠标不移上去也能控制hover的状态？

正常情况下，启动focusNodeAdjacency，然后鼠标放到图表上显示包含所有关系的图形，现在有个需要求是能不能鼠标不放上去，也能“突出显示”某组关系的所有图形？谢谢~

![image](https://cloud.githubusercontent.com/assets/5440532/20665651/6914b386-b59b-11e6-9dc6-3ad3624bdd40.png)

**Comment by 100pah** [comment]
暂时没有直接支持。但是可以试试使用 <http://echarts.baidu.com/api.html#action.highlight> 来实现。

**Comment by zhangdaren** [comment]
感谢回答。

然而，，加上了以下代码（仅测试）：

app.currentIndex = -1;
setInterval(function () {
    var dataLen = option.series[0].data.length;
    // 取消之前高亮的图形
    myChart.dispatchAction({
        type: 'downplay',
        seriesIndex: 0,
        dataIndex: app.currentIndex
    });
    app.currentIndex = (app.currentIndex + 1) % dataLen;
    // 高亮当前图形
    myChart.dispatchAction({
        type: 'highlight',
        seriesIndex: 0,
        dataIndex: app.currentIndex
    });
    // 显示 tooltip
    myChart.dispatchAction({
        type: 'showTip',
        seriesIndex: 0,
        dataIndex: app.currentIndex
    });
}, 1000);


并没有鼠标hover的那种遮罩效果。

**Comment by pissang** [comment]
新版本可以加上这个效果 action

**Comment by zhangdaren** [comment]
感谢~~~
