### ISSUE TITLE
lines-bus.json 文件描述

### ISSUE THREAD

**Issue by WalkerLu** [ecomfe/echarts#4589]
#### 问题简述 (One-line summary)
想要自定义lines-bus.json 想知道其格式是如何定义的，目前只知道前两个。

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):all
+ 浏览器类型和版本 (Browser version):chrome
+ 操作系统类型和版本 (OS Version):win 10

#### 重现步骤 (Steps to reproduce)
1.
2.

#### 期望结果 (Expected behaviour)
了解lines-bus.json 的定义格式

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
为了压缩数据我们把经纬度的数组摊平了，然后做了点变换保证每个经纬度占的字符串比较小。
可以参考 http://echarts.baidu.com/gallery/editor.html?c=lines-bmap-bus 里的解码方法可以反推一下。

你也可以不压缩，直接用 echarts 的输入格式，http://echarts.baidu.com/option.html#series-lines.data

**Comment by WalkerLu** [comment]
ths

**Comment by SynChron1zed** [comment]
@pissang 你好 问下 这个json 能自动生成么 比如我想要长沙的 难道还有一个个写？
