### ISSUE TITLE
Echarts and Google Chrome compatibility

### ISSUE THREAD

**Issue by amutisya** [ecomfe/echarts#4593]
Hello, 

There is something I have noted with echarts and my Google Chrome Version 54.0.2840.98 (64-bit) browser on a MacBook.. The moment I open a page I created that has echart graphs my computer fans kick into action and have way increased activity.. wondering if there's a compatibility issue.. 
Thanks in advance.. great charts.. 

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
What's your option and graph look like ?
