### ISSUE TITLE
与百度地图结合怎么用？

### ISSUE THREAD

**Issue by Mr-O2** [ecomfe/echarts#4594]
#### 问题简述 (One-line summary)
请问echarts与百度地图结合怎么用？我看到有的例子在setOption中设置bmap属性，可是bMap属性中具体参数怎么设置？ 参考文档中怎么没有这一块的帮助？

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):ECharts3

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/tree/master/extension/bmap
