### ISSUE TITLE
xAxis指定type为time、yAxis为value时：series的data数据长度小于3个时，x轴时间数据显示错误

### ISSUE THREAD

**Issue by caiya** [ecomfe/echarts#4595]
#### 问题简述 (One-line summary)

我的data直接使用ms级别的时间戳，xAxis指定type为time，yAxis的type为value，当我的series中的data数据较少时（我的只有三四个左右），xAxis的时间戳数据格式化错误

**Comment by caiya** [comment]
我的echarts版本是3.0的

**Comment by pissang** [comment]
3.几？
