### ISSUE TITLE
echarts折线图:可以给symbol设置不同于折线的颜色吗？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#4596]
#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):

#### 重现步骤 (Steps to reproduce)
1.
2.

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by partical** [comment]
itemStyle.normal.color 不是可以设置折线拐点的颜色吗

**Comment by pissang** [comment]
可以，分别设置 `itemStyle.normal.color` 和 `lineStyle.normal.color`
