### ISSUE TITLE
Datazoom problem with missing data

### ISSUE THREAD

**Issue by derbestederbesten** [ecomfe/echarts#4597]
#### 问题简述 (One-line summary)

When data does not exist for full scale, zooming does not work correctly

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version): 
+ 浏览器类型和版本 (Browser version):
+ 操作系统类型和版本 (OS Version):
Echarts online example: 
https://ecomfe.github.io/echarts/doc/example/dataZoom1.html

#### 重现步骤 (Steps to reproduce)
1. 
![echart1](https://cloud.githubusercontent.com/assets/24266326/20744482/87bb9498-b6dc-11e6-9cd4-34b2959523c4.png)

2.
![echart2](https://cloud.githubusercontent.com/assets/24266326/20744489/9031d11e-b6dc-11e6-9f05-25af1aeff177.png)

#### 期望结果 (Expected behaviour)
in the second picture the line should end at 2013-03-15, not at 2013-03-22, as there is no data!

#### 其他信息 (Other comments)
Setting missing values to 0 is not a solution, because we have to see that there is NO data (missing values)

**Comment by 100pah** [comment]
Your example is running on echarts 2.x, which will not update any more. 
Try echarts 3.x please :)

<https://ecomfe.github.io/echarts-examples/public/index.html>

**Comment by derbestederbesten** [comment]
unfortunaltely we need "datazoom" AND "calculated". Can you tell when "calculated" will work in echarts 3xx?

**Comment by 100pah** [comment]
Do "calculated" means <http://echarts.baidu.com/echarts2/doc/option-en.html#calculable> or something others?
If so, could you tell me what chart do you need that [calculable](http://echarts.baidu.com/echarts2/doc/option-en.html#calculable) works on?

**Comment by derbestederbesten** [comment]
yes I meant calculabe, I'm sorry for my mistake.
I deed it on simple bar charts in echarts-3, in combination with datazoom.
