### ISSUE TITLE
关系图graph的symbol颜色无法改变？

### ISSUE THREAD

**Issue by ZoeHuang13** [ecomfe/echarts#4601]
#### 问题简述 (One-line summary)
关系图graph的symbol颜色无法改变？
官方示例：http://echarts.baidu.com/demo.html#graph-life-expectancy

#### 版本及环境 (Version & Environment)
+ ECharts 版本 (ECharts version):3.3.2
+ 浏览器类型和版本 (Browser version):chrome50
+ 操作系统类型和版本 (OS Version):win7

#### 重现步骤 (Steps to reproduce)
在得到data部分，增加了itemStyle部分
```
var data = series.map(function (yearData) {
            var item = yearData.filter(function (item) {
                return item[3] === country;
            })[0];
            return {
                label: {
                    normal: {
                        show: item[4] % 20 === 0 && item[4] > 1940
                    },
                    emphasis: {
                        position: 'top',
                        show: true
                    }
                },
                name: item[4],
                value: item,
                itemStyle: {
                    normal: {
                        color: "#000fff",
                        opacity:0.3
                    }
                }
            };
        });
```

#### 期望结果 (Expected behaviour)
symbol的颜色应该改变。我想给symbol分别设不同的颜色，但是发现无效。

#### 可能哪里有问题 (What went wrong)
设置的itemStyle，opacity属性有效，而设置color无效

#### ECharts配置项 (ECharts option)

```javascript
option = {

}

```

**Comment by pissang** [comment]
因为这个例子里有用到 visualMap，visualMap 的优先级是最高的，所以会被覆盖
