### ISSUE TITLE
关系图中，将coordinateSystem 设置为'geo'

### ISSUE THREAD

**Issue by Mr-O2** [ecomfe/echarts#4604]
如题，在关系图中，一旦将coordinateSystem 设置为'geo'，就会报错 

echarts.js?ver=1.0:39082  Uncaught TypeError: Cannot read property 'type' of undefined(…) 
 --位置：39082行

如http://echarts.baidu.com/demo.html#graph-simple的例子，一旦添加coordinateSystem :'geo'就会报错。 
地理坐标到底要怎么用呢？
![image](https://cloud.githubusercontent.com/assets/24261434/20780133/e2879606-b7b3-11e6-8843-e445014f8de5.png)

**Comment by pissang** [comment]
你没定义 geo 组件啊，跟散点图用法类似

**Comment by ihepta** [comment]
@pissang 您好，请问effectScatter的图是依赖coordinateSystem : 'cartesian2d'的吗？我的series数组中有这两种类型的图，graph的图好像不能增加coordinateSystem : 'cartesian2d',两者都加了这句代码就只显示effectScatter，两者都不加就只显示graph，这是一个bug吗？希望能帮我解答一下，谢谢！

**Comment by yoyoyueer** [comment]
您好！请问您的这个问题解决了吗？我也是遇到这个问题，加了coordinateSystem:'geo',后就报错

**Comment by GaoJuqian** [comment]
项目中确认是否引入了 geo，还有配置项也要有geo。
