### ISSUE TITLE
搭配bmap时使用的性能问题

### ISSUE THREAD

**Issue by ylc395** [ecomfe/echarts#4606]
在官方实例<http://echarts.baidu.com/gallery/editor.html?c=lines-bmap-effect>中，我注意到一旦拖拽地图，卡顿将非常明显。考虑到文档中将“拖拽”、“缩放”等功能归入inside的dataZoom组件，故尝试添加以下选项：
```
dataZoom: {
    type: 'inside',
    throttle: 500
}
```
不过得到的是一个错误。

那么搭配bmap使用时，图表随拖拽、缩放而进行的重绘该如何设定呢？

**Comment by ylc395** [comment]
![image](https://cloud.githubusercontent.com/assets/12264626/20789552/ce2a4ce4-b7ef-11e6-88d6-8581baa950c9.png)

使用性能分析工具后可以发现拖动地图时坐标转换函数调用得太多了。有规避的方法么

**Comment by pissang** [comment]
暂时没办法，坐标必须得经过百度地图的转换

**Comment by ylc395** [comment]
多谢
