### ISSUE TITLE
想实现ECharts图表的下载

### ISSUE THREAD

**Issue by binbinles** [ecomfe/echarts#4611]
#### One-line summary [问题简述]

想实现ECharts图表的下载。

#### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

ECharts 3.0

#### ECharts option [ECharts配置项]

```javascript
option = {

}

```

#### Other comments [其他信息]

![qq 20161202083158](https://cloud.githubusercontent.com/assets/17252571/20818708/543841fe-b86a-11e6-85c6-f90ffbff5f7d.png)

**Comment by pissang** [comment]
？

**Comment by binbinles** [comment]
已解决，谢谢
