### ISSUE TITLE
echarts使用tab效果切换时,除了第一个图表，其他图表都不显示

### ISSUE THREAD

**Issue by binbinles** [ecomfe/echarts#4612]
#### One-line summary [问题简述]

ECharts使用tab效果切换时,除了第一个图表，其他图表都不显示

#### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

ECharts 3.0

#### Expected behaviour [期望结果]

希望可以在echarts使用tab效果切换时显示图表

#### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
tab 切换后调用 resize

**Comment by binbinles** [comment]
@pissang  您好，请问有example么，不知道在哪里调用哦。

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echartsInstance.resize

**Comment by binbinles** [comment]
$(window).resize(career2Chart.resize);
我在最后调用了这个了，切换到tab2选项卡之后之后没效果。 @pissang

**Comment by liudianliang** [comment]
问题还没有解决怎么就关闭了？

**Comment by iceleeyo** [comment]
先调用resize，再渲染图表
