### ISSUE TITLE
数字太大时最大值、最小值标签数值显示错误（只能显示一部分数据）

### ISSUE THREAD

**Issue by tlemar** [ecomfe/echarts#4613]
#### One-line summary [问题简述]

数字太大时最大值、最小值标签数值显示错误（只能显示一部分数据）

#### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echart 3.3.2
chrome 54.0.2840.99 m 
windows 7 

#### Expected behaviour [期望结果]

正常显示

#### ECharts option [ECharts配置项]

```javascript
option = {

}

```
            value_array = data_array.map(function (ele) {
                console.log(ele)
                return ele[field_name]
            })
            console.log(value_array)

            myChart.setOption({
                series: [
                    {
                        name: '最高气温',
                        type: 'line',
                        data: value_array,
                        markPoint: {
                            data: [
                                {type: 'max', name: '最大值'},
                                {type: 'min', name: '最小值'}
                            ]
                        },
                        markLine: {
                            data: [
                                {type: 'average', name: '平均值'}
                            ]
                        }
                    }]
            })

#### Other comments [其他信息]

![default](https://cloud.githubusercontent.com/assets/3806478/20819398/fdf068f8-b86e-11e6-8984-f23f0df6c545.PNG)

**Comment by pissang** [comment]
不是只显示一部分，是超出部分因为是白色所以跟背景混在一起了，设置 `label.normal.position: top`  就行
