### ISSUE TITLE
可以添加一个甘特图图表么

### ISSUE THREAD

**Issue by TonyYule** [ecomfe/echarts#4614]
#### One-line summary [问题简述]
可以添加一个甘特图 图表么，左侧编辑显示颜色。右侧展示数据 可以左右滚动查看进度

类似酱紫http://www.jq22.com/jquery-info4989

#### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

#### Expected behaviour [期望结果]

类似酱紫http://www.jq22.com/jquery-info4989
还有这样的http://www.jq22.com/yanshi488

#### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没这个计划，谢谢建议
