### ISSUE TITLE
对于visualMap min max的疑惑，不知道是不是bug

### ISSUE THREAD

**Issue by 392468072** [ecomfe/echarts#4615]
#### One-line summary [问题简述]
API中说min max总是对应于series.data中的dataMin dataMax
但是操作过程中发现min max实际上对应的是柱状图的数量？
设置成series.data中的dataMin dataMax根本不起作用
具体请看例子：http://gallery.echartsjs.com/editor.html?c=xS11_MDAMg&comment=0

**Comment by pissang** [comment]
因为你设置了 `dimension: 0` 所以使用的是横轴的值，应该设置成 1 使用纵轴值

**Comment by 392468072** [comment]
非常感谢！
