### ISSUE TITLE
Gauge min/max issue when values are strings

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#4617]
Version: 3.3.2

Just found a little issue when using min/max as strings, maximum is set to 1000 when min is "0":

![image](https://cloud.githubusercontent.com/assets/561365/20824563/1bcaf020-b85e-11e6-9b72-1f9bb6bbeba6.png)

Not sure whether this a bug since it works ok with numbers.. Anyway, might give someone like me a surprise:)

**Comment by pissang** [comment]
I think it's bug, not a feature😝

**Comment by pissang** [comment]
Fixed https://github.com/ecomfe/echarts/commit/db55a084e0cb18d7a4761e9beb6fc044d2cdc6e6
