### ISSUE TITLE
Echart 有专门为手机 做的优化的包吗？

### ISSUE THREAD

**Issue by stephenzhao** [ecomfe/echarts#462]
就是一个简化版的echart  在手机上性能 好一点的。。

**Comment by zhump** [comment]
同求

**Comment by Garrylin** [comment]
为何我在浏览器（使用Chrome）测试时，比如说我用线图，总共有3条线，都穿有参数，在浏览器上显示良好，但是，问题来了，当我把echart放到android项目里用webview显示出来时，每条线都有一条水平线（从那条线的起点水平延伸至终点的水平位置），这是为何！！！！！我看图表选项也好，各种选项也好都找不到问题，是手机浏览器和Chrome 不同吗？

**Comment by xiaoweiqb** [comment]
+1

**Comment by yuanrui** [comment]
同求 期待
