### ISSUE TITLE
这样才能保存背景透明的图片？

### ISSUE THREAD

**Issue by HANKS1123** [ecomfe/echarts#4625]
echarts3.0,官方实例里面的饼图，加了toolbox之后，下载的图片虽然是.png格式，但是背景并不是透明的，怎样设置才能保存透明背景的图片？
 toolbox: {
        show : true,
        backgroundColor:'rgba(255,255,255,0)',
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true,
                type: ['pie', 'funnel']
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#toolbox.feature.saveAsImage.backgroundColor

**Comment by HANKS1123** [comment]
请问具体怎么输代码，我不会搞，谢谢

**Comment by pissang** [comment]
你先在 http://gallery.echartsjs.com/ 贴上你的例子，我帮你加上

**Comment by HANKS1123** [comment]
已经贴上了，ID是a_1995322,问题题名是怎样保存透明背景的图片

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=xSyoZY8ZXg&v=2

**Comment by HANKS1123** [comment]
谢谢

**Comment by liuliangsir** [comment]
谢谢，thx
