### ISSUE TITLE
ECharts3.0 地图数据在线生成工具的一个问题？？

### ISSUE THREAD

**Issue by pq771271668** [ecomfe/echarts#4628]
(对于 "区县" 粒度的区域, 默认仅生成外轮廓。这里的“默认”，难道还有不认的情况？如果有怎么设置区县下一级乡镇的轮廓？如果没有，又怎么设置呢？急需乡镇的轮廓 谢谢

**Comment by pissang** [comment]
如果没法设置就是没有下一级了
