### ISSUE TITLE
地图变型了是为什么呢?

### ISSUE THREAD

**Issue by Realybig** [ecomfe/echarts#4631]
地图变成折纸是的   这是为什么呢?还有地图文件在本地好用   上传到服务器上以后就不显示地图了   是为什么呢?
![qq 20161205160401](https://cloud.githubusercontent.com/assets/10878451/20877548/760732f8-bb04-11e6-8aa2-6733335cb1b9.png)

**Comment by Ovilia** [comment]
你需要 `<meta charset="utf-8">`。
话说“地图变成折纸”的说法太逗了哈哈~:joy:

**Comment by since91** [comment]
应该是地图数据不对，用getMap方法，看看geoJSON数据
