### ISSUE TITLE
地图上的省份 汉字位置怎么调成居中

### ISSUE THREAD

**Issue by cxkobe** [ecomfe/echarts#4635]
你们好,
  请问地图上的省份 汉字位置怎么调成居中；

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by earthpea** [comment]
打开js或Json文件，找到地图描述的的（"properties":{"name":"XX省","cp":[101.04524,23.062507],"childNum":1},）内容，将（"cp":[xx,xx]）内容删除，省名就会自动在该省的地图中间了，否则会默认在省会或首府位置显示

**Comment by 100pah** [comment]
参考：<http://gallery.echartsjs.com/editor.html?c=xHyPl7vyu>

**Comment by hanasakari** [comment]
"cp":\[[1-9]\d*.\d*,[1-9]\d*.\d*], 正则附上
