### ISSUE TITLE
How to zoom gauge charts

### ISSUE THREAD

**Issue by aruntk** [ecomfe/echarts#4638]
### One-line summary [问题简述]

How to add zoom option in gauge chart. dataZoom option does not work.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: Google Chrome Version 54.0.2840.98 (64-bit)
+ OS Version [操作系统类型和版本]: mac osx sierra

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip : {
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            restore: {},
            saveAsImage: {}
        }
    },
    dataZoom: [
        {type:'inside'},
        ],
    series: [
        {
            name: '业务指标',
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: 50, name: '完成率'}]
        }
    ]
};

```

**Comment by pissang** [comment]
Sorry but gauge series not support dataZoom component
