### ISSUE TITLE
Echart饼状图在IE下设置阴影效果提示出错，无法绘制饼状图

### ISSUE THREAD

**Issue by lsh179** [ecomfe/echarts#4640]
### One-line summary [问题简述]

Echart饼状图在IE下设置阴影效果提示出错，无法绘制饼状图，Chrome和firefox是可以的,官方编辑器中，IE打开，直接在饼状图添加属性是可以显示的，如果点击“运行”按钮，则和本地运行一样提示出错，无法绘制。

### Version & Environment [版本及环境]
+ ECharts version :
官方下载的最新版本3.3.2
+ Browser version :
IEEdge，IE11
+ OS Version:
 Windows8 64位

### Expected behaviour [期望结果]
能够像chrome一样正常显示如下图所示

![image](https://cloud.githubusercontent.com/assets/5876408/20915357/4d8b2408-bbc0-11e6-880f-5c0b5017a129.png)

### ECharts option [ECharts配置项]

var gwopts = {

        tooltip: {
            trigger: 'item',
            formatter: "{a} <br/>{b}: {c} ({d}%)"
        },
        legend: {
            show: false
        },
        series: [
            {
                name: '管网长度占比',
                type: 'pie',
                radius: ['40%', '60%'],
                label: {
                    normal: {
                        show: true,
                        position: 'outside'
                    },
                    emphasis: {
                        show: true,
                        textStyle: {
                            fontSize: '12',
                            fontWeight: 'bold'
                        }
                    }
                },
                itemStyle: {
                    normal: {
                        shadowColor: 'rgba(236, 236,236, 0.37)',
                        shadowBlur: 20
                    }
                },
                labelLine: {
                    normal: {
                        show: true
                    }
                },
                data: [
                    { value: 1548.68, name: 'DN100以下' },
                    { value: 535.57, name: 'DN100-300' },
                    { value: 235.62, name: 'DN300-600' },
                    { value: 210.33, name: 'DN600以上' }
                ]
            }
        ],
        color: ['#7facff', '#36e15b', "#ffa81e", "#fa433a"]
    };

**Comment by pissang** [comment]
新版本修复这个问题
