### ISSUE TITLE
如何获取dataZoom的startValue和endValue

### ISSUE THREAD

**Issue by hibehero** [ecomfe/echarts#4641]
### One-line summary [问题简述]
myChart.on('dataZoom', function (params) {
    
});
如何获取dataZoom的startValue和endValue！！！不是start和end的百分比是坐标轴上的值

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by arrinhzh** [comment]
亲，这个问题你解决了吗？
