### ISSUE TITLE
请问echarts 2.0 map 支持addData接口吗

### ISSUE THREAD

**Issue by zzbutcher** [ecomfe/echarts#4644]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不支持

**Comment by zzbutcher** [comment]
请问，如果想给某个省份着色，但不刷新echats实例，有什么办法么。🙂
