### ISSUE TITLE
xticks zoom limit for chart type "time"

### ISSUE THREAD

**Issue by akansal1** [ecomfe/echarts#4663]
Hi,

I have hourly spaced data for which, I am trying to plot chart using **```type: 'time'```** on x-axis. Chart renders well, but during data zoom, I want to limit zoom level to **```hour```** from default **```second or micro-second (not sure)```** 

I would like to know, if there is a solution to go around this issue ?

thanks

**Comment by 100pah** [comment]
Now [dataZoom.minSpan](https://ecomfe.github.io/echarts-doc/public/en/option.html#dataZoom-slider.minSpan) and [dataZoom.minValueSpan](https://ecomfe.github.io/echarts-doc/public/en/option.html#dataZoom-slider.minValueSpan) have been available.
