### ISSUE TITLE
拆线图y轴出现小数

### ISSUE THREAD

**Issue by wangguangis** [ecomfe/echarts#4665]
### One-line summary [问题简述]
主题中设置min: 0, minInterval: 10，当数据都为0时，y轴刻度值出现小数

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: firefox 50.0.2, chrome 54.0.2840.87 (64-bit)
+ OS Version [操作系统类型和版本]: windows 10 x64

### Expected behaviour [期望结果]
y轴刻度为0, 10, 20, 30

### ECharts option [ECharts配置项]

```javascript
option = {
    valueAxis: {
        min: 0,
        minInterval: 10,
        axisLine: { // 坐标轴线
            show: true,
            lineStyle: {
                color: '#4488bb',
                width: 2,
                opacity: 1
            }
        },
        axisLabel: {
            show: true,
            textStyle: {
                color: "#333"
            }
        },
        // 刻度标签
        axisTick: {
            show: false
        },
        splitArea: {
            show: false
        },
        // 分隔线
        splitLine: {
            lineStyle: { // 属性lineStyle（详见lineStyle）控制线条样式
                color: ['#ccc'],
                type: 'dashed',
                width: 1
            }
        }
    }
}

```

### Other comments [其他信息]

[http://pan.baidu.com/s/1kVQ9hTd](图片地址)

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/4665，这个先 close 了
