### ISSUE TITLE
echarts动态加载数据库，最多支持多大的数据量？

### ISSUE THREAD

**Issue by EasinYao** [ecomfe/echarts#4666]
### One-line summary [问题简述]
echarts动态加载数据库，最多支持多大的数据量？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0

**Comment by pissang** [comment]
能否具体描述你的环境

**Comment by EasinYao** [comment]
比如我现在要做折线图，后台产生的数据量从1万到10万不等，甚至更多，echarts图表能否渲染出来？
或者echarts目前最大能支持多大的数据一次性渲染？

**Comment by pissang** [comment]
能

**Comment by ntfs32** [comment]
十万正常，再多偶尔浏览器好像会死掉我测试

**Comment by pissang** [comment]
折线图加上 sampling 后数据量十万是没问题的
