### ISSUE TITLE
legend不显示

### ISSUE THREAD

**Issue by erguotou520** [ecomfe/echarts#4669]
### One-line summary [问题简述]
我在vue2中结合echarts写的组件[EcharBar.vue](https://gist.github.com/erguotou520/32f82d5b32317dd2f3076277538f2681)

我在组件中传的option中包含 legend，但是页面中就是不显示
![image](https://cloud.githubusercontent.com/assets/7945757/21042248/41f15820-be2b-11e6-9a5a-d059d0a822e0.png)
但我把我的option复制到官网example中确实有 legend

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Win10

### Expected behaviour [期望结果]
展示出legend

### ECharts option [ECharts配置项]
```javascript
option = {
  {
  "title": {
    "text": "CPU使用率"
  },
  "tooltip": {
    "trigger": "axis"
  },
  "legend": {
    "data": [
      "CPU使用率"
    ]
  },
  "xAxis": {
    "type": "category",
    "boundaryGap": false,
    "data": [
      "2005-02-25 10:58:43",
      "2010-02-06 11:07:03",
      "2001-11-10 11:35:42",
      "1985-05-17 00:02:32",
      "2004-07-10 04:53:56",
      "1992-05-04 00:56:21",
      "2004-02-27 03:12:20"
    ]
  },
  "yAxis": {
    "type": "value",
    "max": 100,
    "axisLabel": {
      "formatter": "{value} %"
    }
  },
  "series": [
    {
      "name": "CPU使用率",
      "type": "line",
      "data": [
        16,
        73,
        70,
        64,
        49,
        71,
        51
      ]
    }
  ]
}
```

**Comment by geekSnails** [comment]
how to add legent model

**Comment by QinZonger** [comment]
我也遇到这种问题了，把echarts版本降为3.3.2可以解决问题吗
