### ISSUE TITLE
怎么修改图例大小？

### ISSUE THREAD

**Issue by cqcn1991** [ecomfe/echarts#4671]
比如，想要做到这种效果
![default](https://cloud.githubusercontent.com/assets/2425141/21046728/01ff3dca-be41-11e6-9718-2a1c259de495.png)

但是echarts目前的图例会比较大
![default](https://cloud.githubusercontent.com/assets/2425141/21046748/231536c2-be41-11e6-91cd-014f1491d84b.png)

**Comment by CynthiaLea** [comment]
lengend 里的 itemWidth跟itemHeight 就可以修改图例的高度，宽度

**Comment by fufenghua** [comment]
> lengend 里的 itemWidth跟itemHeight 就可以修改图例的高度，宽度

每个图例的大小不一样应该怎么设置呢？
