### ISSUE TITLE
图例怎么修改成checked选项框的形式？

### ISSUE THREAD

**Issue by CynthiaLea** [ecomfe/echarts#4672]
![tk f0j2i o4 imx 39 8](https://cloud.githubusercontent.com/assets/17582460/21071055/b410376a-becf-11e6-83e1-3f6ddd6c6f79.png)

把图例改成checked的选择方式，因为legend 的icon只能是默认或者自定义图片，但是考虑到每个图例的颜色不一样，所以逗哥图例都设定自定义图片很麻烦，还有没有更好的方式？

**Comment by pissang** [comment]
需要自定义图例的扩展
