### ISSUE TITLE
希望echarts可以有拓扑图的官方示例

### ISSUE THREAD

**Issue by divspandiv** [ecomfe/echarts#4677]
同上_(:з」∠)_

**Comment by pissang** [comment]
比如怎么样的拓扑图？

**Comment by divspandiv** [comment]
![qq 20161212125843](https://cloud.githubusercontent.com/assets/22000038/21088534/bc13e87a-c06a-11e6-9fd2-e196ec218eaf.png)
比如这种树图，官方示例貌似只有表格的

**Comment by pissang** [comment]
echarts 2 中有树图 http://echarts.baidu.com/echarts2/doc/example/tree2.html ，3 中暂时不支持
