### ISSUE TITLE
去除高亮效果

### ISSUE THREAD

**Issue by wuzinong** [ecomfe/echarts#4680]
问题简述 (One-line summary)

PC环形图悬浮在图标上的时候会产生高亮效果

版本及环境 (Version & Environment)

ECharts 版本 (ECharts version): 3.3
浏览器类型和版本 (Browser version): -webkit内核
操作系统类型和版本 (OS Version): windows

期望结果 (Expected behaviour)

希望悬浮上去的时候不产生高亮效果，尝试了  legendHoverLink:false无效

**Comment by iceuncle** [comment]
我也遇到了legendHoverLink:false无效的问题，是怎么解决的呢？
