### ISSUE TITLE
Echart示例页面编辑器在高分屏下光标位置不对

### ISSUE THREAD

**Issue by Cacivy** [ecomfe/echarts#4684]
### One-line summary [问题简述]
[示例url](http://echarts.baidu.com/demo.html#pie-custom)

在高分屏下，光标的位置和实际位置不匹配，电脑是xps13，3200*1800分辨率
![echart](https://cloud.githubusercontent.com/assets/8381177/21095410/33b0898a-c096-11e6-88c6-3072c73e922d.png)
如图所示，选中文字其实是“直接访问”，但是光标不对。
不仅是选中，普通文字编辑同理

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 2.0
+ Browser version [浏览器类型和版本]: chrome 55
+ OS Version [操作系统类型和版本]: windows 10

### Expected behaviour [期望结果]
正常匹配光标

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢反馈，目前使用的 ace 编辑器的问题
