### ISSUE TITLE
angularjs2使用问题

### ISSUE THREAD

**Issue by ntfs32** [ecomfe/echarts#4687]
### One-line summary [问题简述]
在angularjs2项目中，使用systemjs打包，引入echarts无法编译通过，出现`error TS2307: Cannot find module 'echarts.`问题。
引入代码：` import * as echarts from 'echarts'`
图可以正常出来，但是出现找不到模块问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.2
+ Browser version [浏览器类型和版本]:chrome 54
+ OS Version [操作系统类型和版本]:MacOS

### Expected behaviour [期望结果]
支持typescript引入使用

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/echarts
