### ISSUE TITLE
设置两个x轴的情况下，其中一个x轴的数据类目显示不全

### ISSUE THREAD

**Issue by ailinjia** [ecomfe/echarts#4689]
One-line summary [问题简述]
设置两个x轴的情况下，其中一个x轴的数据类目显示不全;
只显示了一个类目

Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.1
+ Browser version [浏览器类型和版本]:Chrome 54.0.2840.99
+ OS Version [操作系统类型和版本]:win 8.1 64位

 Expected behaviour [期望结果]
设置多个x轴情况下，能正常显示每个x轴的数据

ECharts option [ECharts配置项]
var  option = {
        title : {
        },
        legend: {
            data:[]
        },
        calculable : true,
        xAxis : [
            {
                position: 'top',
                type : 'category',
                boundaryGap : false,
                data : ['12/1','12/2','12/3','12/4','12/5'],
                axisLine : {
                    show: false
                },
                //x轴的分隔线，平行于Y轴
                splitLine: {
                    show: true
                }
            },
            {   
                type : 'category',
                boundaryGap : false,
                data : ['周一','周二','周三','周四','周五'],
                axisLine : {
                    show: false
                },
                axisTick: {
                    show: false
                }
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    show: false,
                    formatter: '{value} °C'
                },
                axisLine : {
                    show: false
                },
                //y轴上的分隔线
                splitLine: {
                    show: false
                },
                //y轴上的刻度
                axisTick: {
                    show: false
                }
            }
        ],
        series : [
            {
                name:'最高气温',
                type:'line',
                //圆点大小
                symbol: 'circle',
                symbolSize: 14,
                data:[],
                color: '#FF6666',
                //折点
                itemStyle: {
                    normal: {
                        color: '#FF6666',
                    }
                },
                //线条样式
                lineStyle: {
                    normal: {
                        width: 3,
                        opacity: 0.6
                    }
                },
                //折点数值
                label: {
                    normal: {
                        show: true,
                        formatter: '{c} ℃',
                        textStyle: {
                            fontSize: 20
                      }
                 }
              }
            },
            {
                name:'最低气温',
                type:'line',
                symbol: 'circle',
                symbolSize: '14',
                data:[],
                color: '#666699',
                //折点
                itemStyle: {
                    normal: {
                        color: '#FF6666',
                    }
                },
                //线条样式
                lineStyle: {
                    normal: {
                        width: 3,
                        opacity: 0.6
                    }
                },
                //折点数值
                label: {
                    normal: {
                        show: true,
                        formatter: '{c} ℃',
                        position: 'bottom',
                        textStyle: {
                            fontSize: 20
                      }
                 }
              }
            }
        ]
    };

```javascript
option = {
 title : {
        },
        legend: {
            data:[]
        },
        calculable : true,
        xAxis : [
            {
                position: 'top',
                type : 'category',
                boundaryGap : false,
                data : ['12/1','12/2','12/3','12/4','12/5'],
                axisLine : {
                    show: false
                },
                //x轴的分隔线，平行于Y轴
                splitLine: {
                    show: true
                }
            },
            {   
                type : 'category',
                boundaryGap : false,
                data : ['周一','周二','周三','周四','周五'],
                axisLine : {
                    show: false
                },
                axisTick: {
                    show: false
                }
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    show: false,
                    formatter: '{value} °C'
                },
                axisLine : {
                    show: false
                },
                //y轴上的分隔线
                splitLine: {
                    show: false
                },
                //y轴上的刻度
                axisTick: {
                    show: false
                }
            }
        ],
        series : [
            {
                name:'最高气温',
                type:'line',
                //圆点大小
                symbol: 'circle',
                symbolSize: 14,
                data:[],
                color: '#FF6666',
                //折点
                itemStyle: {
                    normal: {
                        color: '#FF6666',
                    }
                },
                //线条样式
                lineStyle: {
                    normal: {
                        width: 3,
                        opacity: 0.6
                    }
                },
                //折点数值
                label: {
                    normal: {
                        show: true,
                        formatter: '{c} ℃',
                        textStyle: {
                            fontSize: 20
                      }
                 }
              }
            },
            {
                name:'最低气温',
                type:'line',
                symbol: 'circle',
                symbolSize: '14',
                data:[],
                color: '#666699',
                //折点
                itemStyle: {
                    normal: {
                        color: '#FF6666',
                    }
                },
                //线条样式
                lineStyle: {
                    normal: {
                        width: 3,
                        opacity: 0.6
                    }
                },
                //折点数值
                label: {
                    normal: {
                        show: true,
                        formatter: '{c} ℃',
                        position: 'bottom',
                        textStyle: {
                            fontSize: 20
                      }
                 }
              }
            }
        ]
}

```

Other comments [其他信息]
![default](https://cloud.githubusercontent.com/assets/23077107/21125568/aeb59f90-c121-11e6-9341-589b65c07c55.png)

**Comment by pissang** [comment]
没有系列用到这个类目轴的时候会这样，下个版本优化

**Comment by xuanmiao-zero** [comment]
e,一年了,还没有修复吗...
