### ISSUE TITLE
echarts 实时航线动画效果突然失效问题

### ISSUE THREAD

**Issue by sunshinev** [ecomfe/echarts#4692]
### 错误演示地址
[http://gallery.echartsjs.com/editor.html?c=xS1fGdRyNe&v=1](http://gallery.echartsjs.com/editor.html?c=xS1fGdRyNe&v=1)
![image](https://raw.githubusercontent.com/sunshinev/laravel/master/public/cut.gif)
### One-line summary [问题简述]

实时航线图仿照柱形图的实时过程，将多条数据push到一个array中，达到array的长度阈值后，进行array.shift()，将过时的数据从array中删除掉，然后再重新setOption。这样会在阈值的范围内进行正常的绘制，但是超过阈值后，使用动画效果的话，会出现变形绘制（这个动画效果很让我纠结）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: mac os sierra

### Expected behaviour [期望结果]

1.  websocket接入数据后，实时绘制曲线，曲线要有动画效果，慢慢变长
2. 曲线绘制完成后可以超时慢慢消失，可以从出发点到目标点慢慢消失的效果
3. 线条数量达到数组长度阈值后，不会发生动画效果消失的情况

### ECharts option [ECharts配置项]

```javascript
series: [{
    type: 'lines',
    coordinateSystem: 'geo',
    data: lines,
    zlevel:10,
    animation:true,
    // animationThreshold:2,
    animationDurationUpdate:0,
    effect: {
        show: false,
        period: 1,
        trailLength: 0.2,
        // constantSpeed: 20,
        color: '#fff',
        loop:false,
        symbolSize: 0.5,
        //symbol:'',
    },
    large: true,
    largeThreshold: 100,
    lineStyle: {
        normal: {
            // opacity: 0.05,
            width: 2,
            curveness: 0.3
        }
    },
    // 设置混合模式为叠加
    blendMode: 'lighter'
}]
```
### ECharts 生成动态数据的过程
```javascript
var lines = [];
setInterval(function() {
    var index = parseInt(Math.random()*1000);
    // 从data.routes中随机选取一条航线记录
    lines.push(routes[index]);
    if(lines.length > 10) { // 如果超出阈值，删除第一个元素，保证地图中只展示10条航线
        lines.shift();
    }
    myChart.setOption(options());
},1000);
```

### Other comments [其他信息]
从下面的gif图，可以看出 前面的线条可以正常绘制，但是到后面动画效果就消失了。

![image](https://raw.githubusercontent.com/sunshinev/laravel/master/public/cut.gif)

**Comment by pissang** [comment]
能否 http://gallery.echartsjs.com/explore.html 贴一下例子？

**Comment by underway2014** [comment]
请问下楼主需要引入那些js，麻烦告知下 ，谢谢 @sunshinev

**Comment by sunshinev** [comment]
http://gallery.echartsjs.com/editor.html?c=xS1fGdRyNe&v=1  这是演示的地址

**Comment by pissang** [comment]
这个例子里 echarts 在后面会判断数据是在更新（因为在数据没有 id 或者 name 的时候，echarts 是根据 dataIndex 跟之前数据作对比，如果一样则执行更新动画）。恰好你又把 animationDurationUpdate 设成 0 了，所以就没动画效果了。

建议你给每个数据指明 id

**Comment by sunshinev** [comment]
@pissang 非常感谢，这个如果自己看真的是解决不了~ another question：将尾迹特效打开后，前期执行ok但是到后面执行动画就会出现残影效果，是不是单个canvas层绘制次数过多导致的，按照wiki里面说的，应该每个带特效的动画都要单独写一个zlevel么

**Comment by sunshinev** [comment]
@pissang 实际上关掉特效也会出现这个问题

**Comment by sunshinev** [comment]
@underway2014 这个从控制台抓一下newwork就好，我加载了world地图的js和echarts的js和jquery。另外自己整合使用了require

**Comment by sunshinev** [comment]
@pissang  已找到问题~感谢~^^
