### ISSUE TITLE
热力图中怎么显示地名

### ISSUE THREAD

**Issue by kiscod** [ecomfe/echarts#4694]
### One-line summary [问题简述]

比如在
http://echarts.baidu.com/demo.html#heatmap-map
中，怎么显示出各个省份的地名？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: OS X & Win

### Expected behaviour [期望结果]

能显示出地名。
目前在做某市内各辖区的热力图，无法显示出各区域地名。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
跟 http://echarts.baidu.com/gallery/editor.html?c=map-china 一样

**Comment by kiscod** [comment]
`label: {
                normal: {
                    show: true
                },
                emphasis: {
                    show: true
                }
            },`
并没有效果。

**Comment by kiscod** [comment]
<img width="1110" alt="2016-12-14 11 59 25" src="https://cloud.githubusercontent.com/assets/10594713/21169166/cd20ec04-c1f4-11e6-9f1a-6bd7eedfac01.png">

show：true 放错了位置，放在geo上才对，谢谢pissang的解答。

**Comment by sakishen** [comment]
THX~ 很有帮助
