### ISSUE TITLE
官方DEMO步行线路图实现报错，请问是什么原因？

### ISSUE THREAD

**Issue by underway2014** [ecomfe/echarts#4699]
@chriswong 
### One-line summary [问题简述]
我这边是想按照地图DEMO 如：[官方demo](http://echarts.baidu.com/demo.html#lines-bmap)  做（但是柱状图，折线图都没有问题）

echart我用下载的压缩包/bower 安装到本地/csdn的连接都报相同的错误， 如下：

Error: Component series.lines not exists. Load it first.

### Version & Environment [版本及环境]
+ echart 3.3.2 
+ firefox, chrome
+ windows

### Expected behaviour [期望结果]
正常显示地图及添加的线路线路

### ECharts option [ECharts配置项]

var myChart = echarts.init(document.getElementById('main'));
var lines = paths.map(function (track) {//path 类似于DEMO中获取JOSON的数据
        return {
            coords: track.map(function (seg, idx) {
                return seg.coord;
            })
        };
    });
myChart.setOption({
        bmap: {
            center: [120.13066322374, 30.240018034923],
            zoom: 14,
            roam: true,
            mapStyle: {
                styleJson: [{
                    'featureType': 'water',
                    'elementType': 'all',
                    'stylers': {
                        'color': '#d1d1d1'
                    }
                }, {
                    'featureType': 'land',
                    'elementType': 'all',
                    'stylers': {
                        'color': '#f3f3f3'
                    }
                }, {
                    'featureType': 'railway',
                    'elementType': 'all',
                    'stylers': {
                        'visibility': 'off'
                    }
                }, {
                    'featureType': 'highway',
                    'elementType': 'all',
                    'stylers': {
                        'color': '#fdfdfd'
                    }
                }, {
                    'featureType': 'highway',
                    'elementType': 'labels',
                    'stylers': {
                        'visibility': 'off'
                    }
                }, {
                    'featureType': 'arterial',
                    'elementType': 'geometry',
                    'stylers': {
                        'color': '#fefefe'
                    }
                }, {
                    'featureType': 'arterial',
                    'elementType': 'geometry.fill',
                    'stylers': {
                        'color': '#fefefe'
                    }
                }, {
                    'featureType': 'poi',
                    'elementType': 'all',
                    'stylers': {
                        'visibility': 'off'
                    }
                }, {
                    'featureType': 'green',
                    'elementType': 'all',
                    'stylers': {
                        'visibility': 'off'
                    }
                }, {
                    'featureType': 'subway',
                    'elementType': 'all',
                    'stylers': {
                        'visibility': 'off'
                    }
                }, {
                    'featureType': 'manmade',
                    'elementType': 'all',
                    'stylers': {
                        'color': '#d1d1d1'
                    }
                }, {
                    'featureType': 'local',
                    'elementType': 'all',
                    'stylers': {
                        'color': '#d1d1d1'
                    }
                }, {
                    'featureType': 'arterial',
                    'elementType': 'labels',
                    'stylers': {
                        'visibility': 'off'
                    }
                }, {
                    'featureType': 'boundary',
                    'elementType': 'all',
                    'stylers': {
                        'color': '#fefefe'
                    }
                }, {
                    'featureType': 'building',
                    'elementType': 'all',
                    'stylers': {
                        'color': '#d1d1d1'
                    }
                }, {
                    'featureType': 'label',
                    'elementType': 'labels.text.fill',
                    'stylers': {
                        'color': '#999999'
                    }
                }]
            }
        },
        series: [{
            type: 'lines',
            coordinateSystem: 'bmap',
            data: lines,
            polyline: true,
            lineStyle: {
                normal: {
                    color: 'purple',
                    opacity: 0.6,
                    width: 1
                }
            }
        }]
    });

### Other comments [其他信息]
就只有用地图这个报错，折线图，饼状，柱状图都没问题

**Comment by pissang** [comment]
不知道你用的是哪个版本，这个问题是 lines 组件没加载，如果你用完整版是没这个问题的
