### ISSUE TITLE
请问ECharts支持自定义 折线图指定点 的背景色吗？

### ISSUE THREAD

**Issue by NEtOrnANtHeR** [ecomfe/echarts#4702]
像图中的效果，在执行区域里面设置高亮背景

![lalojm7udm0dwm0eyq_1121_856 png_620x10000q90g](https://cloud.githubusercontent.com/assets/11695765/21209554/016531d0-c2b0-11e6-9655-bbd5444ee5ab.jpg)

在文档中没有类似的效果

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.markArea

**Comment by NEtOrnANtHeR** [comment]
谢谢，抱歉做了伸手党。
