### ISSUE TITLE
2.0中的 tree 中如何动态的添加节点

### ISSUE THREAD

**Issue by 790396054** [ecomfe/echarts#4703]
### One-line summary [问题简述]

2.0中的 tree 中如何动态的添加节点，比如，单击小米，小米的孩子有小米1，小米2等，单击小米2，又出来下一级的节点

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
更新数据后重新 setOption

**Comment by gaoshijun1993** [comment]
@pissang 请问如何更新当前选中节点的数据呢?只能通过一层一层的遍历series找到当前节点做修改吗?有没有相关的api?
