### ISSUE TITLE
title配置项下的x,y

### ISSUE THREAD

**Issue by alensiri** [ecomfe/echarts#4707]
### One-line summary [问题简述]看示例时发现title组件下定义了x,y属性，但是我在配置项
title下并没有找到。而且定义x,y对title起作用

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echarts3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7 

### Expected behaviour [期望结果]
不太确定是不是echart2的配置项API，如果有用希望更新到3的配置项里。

### ECharts option [ECharts配置项]

```javascript
option = {
       title:{
          text:'你好，明天',
          x:'center',
          y:0
       }
}

```

**Comment by pissang** [comment]
x, y 是 2.0 里的属性，3.0 开始推荐使用 left, top, right, bottom 定位
