### ISSUE TITLE
markLine如何将文字显示在标线右上方

### ISSUE THREAD

**Issue by MrChanLi2013** [ecomfe/echarts#4708]
### One-line summary [问题简述]

标线上的文字被隐藏了，如果设置gird的left的则可以显示出来，**但是这样看到的表格就不美观**，请问有什么办法可以将文字显示在标线的右上方吗？

![d f bl f 5c6 4 6 dhob4](https://cloud.githubusercontent.com/assets/4556138/21248770/465d0e06-c374-11e6-8c82-4388b77053fe.png)

**Comment by pissang** [comment]
暂时没办法
