### ISSUE TITLE
百度地图扩展，另存为图片

### ISSUE THREAD

**Issue by lbbc1117** [ecomfe/echarts#4710]
### One-line summary [问题简述]
使用百度地图扩展时，将图表实例另存为图片，图片只包含了绘制在canvas上的元素，而百度地图的背景tiles消失

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: Chrome 53.0
+ OS Version [操作系统类型和版本]: Mac OS X

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
百度地图有它自己的绘制逻辑，echarts 没法一块保存成图片
