### ISSUE TITLE
toolbox按钮颜色

### ISSUE THREAD

**Issue by hfutzhu** [ecomfe/echarts#4714]
我用的echarts版本是3,toolbox里面的功能按钮都是灰色,没有颜色,怎么设置,让功能按钮有颜色?

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#toolbox.feature.saveAsImage.iconStyle.normal.color

**Comment by hfutzhu** [comment]
feature: {
			            mark: {
			                show: true
			            },
			            dataView: {
			                show: true,
			                readOnly: true
			            },
			            magicType: {
			                show: true,
			                type: ["line", "bar"]
			            },
			            iconStyle: {
			                normal: {
			                    borderColor: '#00ff00'
			                },
			                emphasis: {
			                    borderColor: '#3E98C5'
			                }
			            },
			            dataZoom : {
							yAxisIndex : 'none'
						},
						restore : {},
						saveAsImage : {}
			        }


指定了bordercolor没用啊 ,color也没有用呢,还是灰色的,怎么为每个功能指定颜色
