### ISSUE TITLE
当用toolbox的dataZoom时，如何refetch数据？

### ISSUE THREAD

**Issue by connorTang** [ecomfe/echarts#4728]
### One-line summary [问题简述]
我有一个月的数据，每五分钟一个data point,如果一次性render成线图，浏览器内存会超过1G。所以想第一次提取数据按每天或每小时，然后当用户缩放的时候再callback 提取更小时间的数据（每十分钟或每一分钟）。但是看了一下dataZoom好像没有任何可以用来callback的API.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.3.2
+ Browser version [浏览器类型和版本]: chrome evergreen
+ OS Version [操作系统类型和版本]: mac os/windows

### Expected behaviour [期望结果]
希望toolbox的dataZoom可以有一个用来callback的API.

### ECharts option [ECharts配置项]

```javascript
option = {
    toolbox: {
        show: true,
        feature: {
            dataZoom: {
                yAxisIndex: 'none',
                callback: Function() // callback function to refetch data
            },
            magicType: {type: ['line', 'bar']}
        }
    },
    xAxis:  {
        type: 'category',
        data: ['1','2','3','4','5','6','7'],
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'a',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10]
        },
        {
            name:'b',
            type:'line',
            data:[1, -2, 2, 5, 3, 2, 0]
        }
    ]
}

```

**Comment by connorTang** [comment]
尝试了用datazoom event 运行一个callback function，但是取回新数据后echarts会抛出一个```'findHover' of null``` 错误在TooltipView.js 425行。

**Comment by pissang** [comment]
贴一下完整的代码？

**Comment by connorTang** [comment]
代码量太大，我截取相关的部分，这个EchartsBaseChart 是个echarts wrapper.
```
      <EchartsBaseChart
        title={this.props.title}
        echartsProps={{
          onEvents: {
            click : this.props.onClick,
            datazoom: this.handleZoom
          },
          option: this.getEchartsOptions()
        }}
      />
```

```
    handleZoom = (batch, instance) => {
      instance.dispatchAction({ type: 'hideTip' });
      // fetch data
      this.setState(newData);
    }
```
batch 包含start/end values， instance返回echartsInstance。目前发现这个问题由tooltip引起，在重新render之前需要隐藏tooltip。

**Comment by pissang** [comment]
是不是 dispose 后再 dispatchAction 了？

**Comment by connorTang** [comment]
dispose后dispatchAction会出现这种情况么？应该没有，用的是https://github.com/hustcc/echarts-for-react. 这个就是直接用的这个react wrapper，然后直接传入的上面的option，只不过我的数据量比较大，在Zoom之后需要refetch新的数据rerender了。看了代码之后发现TooltipView里好像每次Zoom后会rerender tooltip，但是在422行，`api.getZr().handler`，这个handler是null 。

**Comment by pissang** [comment]
嗯，只有 dispose 后才会出现 handler 为 null 的情况

**Comment by connorTang** [comment]
哈哈，还真是。。。仔细看了一下那个react wrapper，每次有新的数据传入都会dispose。谢谢啦。

**Comment by pissang** [comment]
;)
