### ISSUE TITLE
cnpm install echarts --save  报错: download ShasumNotMatchError

### ISSUE THREAD

**Issue by linzhishuai** [ecomfe/echarts#4729]
在使用Cnpm安装Echarts的时候，出现 download ShasumNotMatchError（最近三天，100%复现）。

+ ECharts version [ECharts 版本]: echarts@3.3.2
+ Browser version [浏览器类型和版本]:Chrome 55.02883.87 m
+ OS Version [操作系统类型和版本]:Win7 64bit旗舰版

**Comment by haochengxu** [comment]
cnpm install --no-cache试试

**Comment by zcl20131002578** [comment]
i have a same problem,have a try but no use

**Comment by linzhishuai** [comment]
You can use the follow command:
npm install --no-cache --save echarts
