### ISSUE TITLE
echarts2的树图无法在边上添加label

### ISSUE THREAD

**Issue by AllenFee** [ecomfe/echarts#4732]
### One-line summary [问题简述]
当前业务需求想应用echarts2的树图，但是还想在树图的边上添加label标签(类似echarts3中的graph的边可以添加label一样)，可是貌似不行。
如果改用echarts3中的graph，虽然可以在边上添加label，但是连线的样式没有echarts2中的树图那样美观，只能支持直线或一定曲率的曲线(并且曲线无法设定向内弯曲还是向外弯曲)。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts2or3
+ Browser version [浏览器类型和版本]:chrome版本 55.0.2883.87 m
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

不知是否有综合两者优点的解决方案

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没办法，3 后续会出树图的扩展

**Comment by AllenFee** [comment]
会出现在下一个版本中吗？

**Comment by AllenFee** [comment]
@pissang，会出现在下一个版本中吗？

**Comment by pissang** [comment]
@AllenFee 不会，目前打算写成插件

**Comment by liubinchu** [comment]
where is the plug-in?
Or which version support this feature, add labels on edges in a tree?

**Comment by lsd1** [comment]
@pissang,树形图怎样才能像关系图一样支持边线上插入文字，这个插件出来了吗？或者哪个版本支持？
