### ISSUE TITLE
如何利用别塞尔曲线绘制一个椭圆呢

### ISSUE THREAD

**Issue by DarkRake** [ecomfe/echarts#4737]
### One-line summary [问题简述]
刚看到可以绘制别塞尔曲线，但是在echarts中如何绘制一个椭圆出来呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以参考 http://www.spaceroots.org/documents/ellipse/
