### ISSUE TITLE
echarts 对数展示叠加柱状图的时候 数字为0 有一个bug 

### ISSUE THREAD

**Issue by snowlin** [ecomfe/echarts#4743]
### One-line summary [问题简述] 看图  

![image](https://cloud.githubusercontent.com/assets/3838290/21376175/d67b7764-c76d-11e6-92a7-5e046b52fe5e.png)

### Version & Environment [版本及环境]  
+ ECharts version [ECharts 版本]:3.2.3
+ Browser version [浏览器类型和版本]: 谷歌浏览器  54.0.2840.99 m
+ OS Version [操作系统类型和版本]:win7

### ECharts option [ECharts配置项]

```javascript
 option = {
    title: {
        text: '对数轴示例',
        left: 'center'
    },
    tooltip: {
        trigger: 'axis'
       
    },
    legend: {
        left: 'left',
        data: ['2的指数', '3的指数']
    },
    xAxis: {
        type: 'category',
        name: 'x',
        splitLine: {show: false},
        data: ['一', '二', '三', '四', '五', '六', '七', '八', '九']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    yAxis: {
        type: 'log',
        name: 'y'
    },
    series: [
        {
            name: '3的指数',
            type: 'bar',
             stack: '总量',
            data: [0, 3, 9, 0, 81, 247, 741, 2223, 6669]
        },
        {
            name: '2的指数',
            type: 'bar',
             stack: '总量',
            data: [1, 2, 4, 8, 16, 0, 64, 128, 256]
        },
        {
            name: '1/2的指数',
            type: 'bar',
             stack: '总量',
            data: [1/2, 1/4, 1/8, 1/16, 1/32, 1/64, 1/128, 1/256, 1/512]
        }
    ]
};
```

**Comment by pissang** [comment]
log 轴不支持 stack

**Comment by liubei1** [comment]
根stack没有关系吧，只要数字为0的时候，log类型图表就会出现问题了
`option = {
    legend: {
        data:['critical']
    },
    xAxis: {
        type: 'category',
        
        data: ["一", "二", "三", "四", "五", "六", "七", "八", "九"]
    
    },
    yAxis: {
        type: 'log'
    },
    series: [{
            name:'critical',
            type:'line',
            data: [0, 10, 6,10, 60,90,8,66,100]
        }
    ]
}`

**Comment by 100pah** [comment]
log 0 没有意义。对轴的最大值影响倒是可以改进下。
