### ISSUE TITLE
可以在x轴或者y轴显示文字和图片么

### ISSUE THREAD

**Issue by dreamyi71** [ecomfe/echarts#4747]
### One-line summary [问题简述]

可以在x轴或者y轴显示文字和图片么？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没有直接的办法，可以尝试用 markPoint 加图片
