### ISSUE TITLE
请问bar图怎么能显示data的name属性

### ISSUE THREAD

**Issue by hezhongfeng** [ecomfe/echarts#4750]
想同时显示value和name,没找到控制这个的属性
其实就是想在标签上面显示一点字符串，和数值同时显示，有什么办法吗？
```
{
name:'hezf',
value:123
}
```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-bar.label.normal.formatter

**Comment by hezhongfeng** [comment]
谢谢

**Comment by hezhongfeng** [comment]
你好，我试了下还是不行。
这个显示的是x轴上的name和数据
我想要显示的是series中data数组中的name
