### ISSUE TITLE
如何自动化的实例化一组ECharts

### ISSUE THREAD

**Issue by mashuangshuang** [ecomfe/echarts#4752]
### One-line summary [问题简述]
现在项目中想实现一个页面中一组echarts图的实例化，而不是用dom id 手动一个一个去实例化；

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
写程序本来就是一件自动化的事
