### ISSUE TITLE
echarts中的canvas画布如何设置width,height属性跟其style中的width、height分离

### ISSUE THREAD

**Issue by 1538986328** [ecomfe/echarts#4756]
### One-line summary [问题简述]
echarts中画图的时候，能控制画布面板做出下面的这种设置不？
<canvas ref="canvas" style={{width:200,height:200}} width="400" height="400"/>
zrender画图也是~
请问该如何配置，我用echarts.init 设置感觉参数没给进去，谁有范例代码不，麻烦发我一下，谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 1538986328** [comment]
http://www.cnblogs.com/fireyjy/p/5789376.html?utm_source=itdadao&utm_medium=referral  这是canvas画布绘制清晰的问题。

**Comment by 1538986328** [comment]
我的画布在1920*1080情况下不够清晰。我想试验一个 宽高属性 比它的样式宽高大2倍的 比例。

**Comment by pissang** [comment]
有 devicePixelRatio 属性

**Comment by 1538986328** [comment]
转成base64的图片的时候，有没有办法去除图的虚线边框呢？ 实验次数过多，不太记得之前配置，大概情况：  1920*1080px下，一行大概占用1332px宽度，并排两个饼图，我给对应的div设置的宽度样式为50%；高度样式为720px;
