### ISSUE TITLE
Dashing 的coffee script怎么初始化 EChart3

### ISSUE THREAD

**Issue by duanshuaimin** [ecomfe/echarts#4758]
Dashing的dashboard中使用 EChart，Dashing 的coffee script怎么初始化 EChart3

**Comment by pissang** [comment]
按 coffee script 的语法来呗

**Comment by duanshuaimin** [comment]
自己尝试写了，但图没有显示，能帮忙看一下吗？
class Dashing.Echart1 extends Dashing.Widget
  ready: ->
    echartTest = $(@node).find(".echarts-test")
    @myechart = echarts.init(echartTest)
    @myechart.setOption
  title: text: 'ECharts 入门示例'
  tooltip: {}
  legend: data: [ '销量' ]
  xAxis: data: [
    '衬衫'
    '羊毛衫'
    '雪纺衫'
    '裤子'
    '高跟鞋'
    '袜子'
  ]
  yAxis: {}
  series: [ {
    name: '销量'
    type: 'bar'
    data: [
      5
      20
      36
      10
      10
      20
    ]
  } ]
onData: (data) ->
  @myechart.setOption data

**Comment by stanleyxu2005** [comment]
@duanshuaimin Dashing.Echart1 在哪里？

**Comment by luotuocao2008** [comment]
@stanleyxu2005 Dashing.Echart1是div对象。
 <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="echart1" data-view="Echart1" data-title="Hello" ></div>
    </li>
