### ISSUE TITLE
3.2.2版本不支持无数据时给出提示信息吗？

### ISSUE THREAD

**Issue by luyankui** [ecomfe/echarts#4759]
### One-line summary [问题简述]
3.2.2版本不支持无数据时给出提示信息吗？类似noDataText的配置

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.2.2
+ Browser version [浏览器类型和版本]:IE11
+ OS Version [操作系统类型和版本]:WIN7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不支持
