### ISSUE TITLE
echarts2 添加自定义标注

### ISSUE THREAD

**Issue by wdnlwzd** [ecomfe/echarts#4760]
### One-line summary [问题简述]
我现在的需求是想在echarts2图表上的任意位置添加自定义标注，
可以提供点途径或思路吗？ 谢谢。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 2.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
图表上的任意位置添加自定义标注

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/17924984/21421839/efa7032c-c86f-11e6-811b-7dc3b52fbbba.png)

**Comment by pissang** [comment]
可以设置 x，y

**Comment by wdnlwzd** [comment]
@pissang  你好，我不太明白你说的意思。可以设置x，y是设置标注的位置？ 可是我要用什么来显示标注？ markPoint 不能显示中文，只能显示value值。
