### ISSUE TITLE
地图里各市的名字位置不准确，有重合现象

### ISSUE THREAD

**Issue by lcxlhjy** [ecomfe/echarts#4764]
### One-line summary 
在使用四川省地图的时候，有些市的名字跑出相应市的范围，与其它市名重合，界面不太好看

+ ECharts version [ECharts 版本]:Echarts 3.0
+ Browser version [浏览器类型和版本]:谷歌浏览器，360浏览器
+ OS Version [操作系统类型和版本]:windows7

### ECharts option [ECharts配置项]

```javascript
option = {
series: [{
        type: 'map',
        map: '四川',
        top: 120,
        itemStyle:{
        	emphasis:{
        		areaColor:'#09F738'//高亮状态的颜色
        	}
        },
        label: {
            normal: {
                show: true
            },
            emphasis: {
                show: true
            }
        }
    }]

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/24386157/21445111/01014148-c8f0-11e6-965b-1f4a88bc3e75.png)

**Comment by lcxlhjy** [comment]
已解决~~

**Comment by MarkNC007** [comment]
我也遇到需要调整位置的问题，请问怎么解决的？
