### ISSUE TITLE
echarts 柱状图可以实现虚点的样式吗？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#4773]
### One-line summary [问题简述]
echarts2.0版本下的折柱混搭图例子中（http://echarts.baidu.com/echarts2/doc/example/mix6.html）,中间黄色的堆积柱状图可以实现虚点的样式吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![image](https://cloud.githubusercontent.com/assets/22878190/21448559/221b5682-c91f-11e6-962f-c90633088c5d.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
echarts 3 下个版升级后可以做这个效果

**Comment by partical** [comment]
有个虚点图片填充

**Comment by chenxia123** [comment]
@partical 你好，请问怎么用图片填充呢？可以说的详细点吗？因为每个x轴标签所对应的line值与bar值得差是不一样的，那如何确定图片的高呢？
