### ISSUE TITLE
IE8 datazoom里面莫名其妙多了一根线

### ISSUE THREAD

**Issue by cdoneshot** [ecomfe/echarts#4774]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.X
+ Browser version [浏览器类型和版本]:
IE8 18514
+ OS Version [操作系统类型和版本]:
WIN7 UTLIMATE SP1 X64

### Expected behaviour [期望结果]

和其他浏览器表现一致，没有多余的线条

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![_20161223150400](https://cloud.githubusercontent.com/assets/20412044/21448868/3de9841c-c922-11e6-9173-e462be1bafa5.png)
![_20161223145635](https://cloud.githubusercontent.com/assets/20412044/21448870/3f69bfe6-c922-11e6-81ad-cefc6597996c.png)

**Comment by cdoneshot** [comment]
另外，IE8下可不可以修改VML的Z-INDEX.

**Comment by 100pah** [comment]
<https://ecomfe.github.io/echarts-doc/public/en/option.html#dataZoom-slider.showDataShadow> 设成  `false` ？

**Comment by cdoneshot** [comment]
@100pah 配成false确实好了。顺便问下，IE8下生成的VML的Z-INDEX可以在哪批量修改吗，现在改一个老系统，里面大量把z-index内联在元素的style里面了，加上echarts，好多地方的层级都不对~该原来的系统要改的地方就太多了。。。。

**Comment by cdoneshot** [comment]
可以了
