### ISSUE TITLE
Dashing 集成echart图不显示

### ISSUE THREAD

**Issue by luotuocao2008** [ecomfe/echarts#4776]
coffee script 脚本如下：
class Dashing.Echart1 extends Dashing.Widget
ready: ->
echartTest = $(@node).find(".echarts-test")
@myechart = echarts.init(echartTest)
@myechart.setOption
title: text: 'ECharts 入门示例'
tooltip: {}
legend: data: [ '销量' ]
xAxis: data: [
'衬衫'
'羊毛衫'
'雪纺衫'
'裤子'
'高跟鞋'
'袜子'
]
yAxis: {}
series: [ {
name: '销量'
type: 'bar'
data: [
5
20
36
10
10
20
]
} ]
onData: (data) ->
@myechart.setOption data

如果脚本有错误请指出，或者给一个例子。谢谢

**Comment by pissang** [comment]
与 https://github.com/ecomfe/echarts/issues/4758#issuecomment-268946383 重复
