### ISSUE TITLE
Formmatting Legends / 格式化圖例

### ISSUE THREAD

**Issue by DinisFigueira** [ecomfe/echarts#4777]
Hi guy's,

I wanted to know how can I cut part of the legends without affecting the graphics.
Since I have title's that are way more bigger than they should be, I wanted to only show 30 characters maximum on the legends but on the graphic's themselves, I want to show the full title. 

Is it possible?

Thank you!

Translated to chinese

翻譯成中文

嗨，大家好，

我想知道如何在不影響圖形的情況下剪切部分圖例。
由於我有標題的方式比他們應該更大，我想只顯示最多30個字符的圖例，但在圖形的本身，我想顯示完整的標題。

是否可以？

謝謝！

**Comment by 100pah** [comment]
Hopefully <https://ecomfe.github.io/echarts-doc/public/en/option.html#legend.formatter> will be helpful to you.
