### ISSUE TITLE
dataZoom设为inside zoomLock 设为true后，移动端跟原生向上拖动冲突

### ISSUE THREAD

**Issue by yhhwpp** [ecomfe/echarts#4784]
我现在的一个需求是图表的可以在X轴方向上可以拖动，在Y轴不可以。

我的dataZoom事件设置‘inside’（因为项目需求，只能用inside，不能用slider），设置了zoomLock 为true后，现在我发现在移动端，Y轴方向拖动屏幕时，dataZoom事件会跟原生的拖动事件冲突，造成在图表区域内Y轴方向拖动时，不能拖动屏幕。我想取消dataZoom在Y轴上的事件，请问我改怎么做呢。
盼回复，谢谢！！

**Comment by pissang** [comment]
这个跟 zoomLock 没关系，如果你设置了拖拽移动，我们就会阻止浏览器默认的滑动，如果两个都生效体验会很不好

**Comment by yhhwpp** [comment]
@pissang 但是我希望x轴可以内部左右滑动，Y轴不能上下滑动，只希望调用原生的滚动，改怎么弄呢？

**Comment by pissang** [comment]
没法做到

**Comment by yhhwpp** [comment]
好吧

**Comment by charish00** [comment]
可以根据自己的情况除去冒泡事件，但是比较危险

**Comment by yhhwpp** [comment]
@charish00 具体如何实现？

**Comment by jingxiawl** [comment]
@yhhwpp 请问你解决了么。我觉得这个体验太差了，页面无法滑动

**Comment by yhhwpp** [comment]
@jingxiawl 暂时没有好的办法解决，在移动端体验确实有点儿问题。

**Comment by dayday2** [comment]
请问这个问题解决了吗？我也遇见了这样的问题，在移动端要实现折线图的左右滑动，dataZoom设为inside后没办法上下滚动了。
