### ISSUE TITLE
如何画出不连续的线段，如图

### ISSUE THREAD

**Issue by warlock-lv** [ecomfe/echarts#4786]
怎么能在坐标系中画出如图所示紫色的不连续的线段呢？ x轴为time类型。
在一个series 一个 {  } 的一个data里， 不要用折分成多个 { } 的方法。
![image](https://cloud.githubusercontent.com/assets/19185428/21477070/4a4e0486-cb79-11e6-8866-52751cba1e5b.png)

如果没有的话，能不能请官方考虑增加一种 绘线支持，如下
series : [
            {
                name: 'newLine',
                type: 'newLineType',
                lineStyle:{normal:{color:'Magenta', width:2,}},
                data: [  [['2016-11-15 21:07:51.000', 5000], ['2016-11-15 21:07:55.000', 5544]], //一段线
                         [['2016-11-15 21:08:01.000', 4253], ['2016-11-15 21:08:11.000', 6566]], //一段线
                         [['2016-11-15 21:08:21.000', 5040], ['2016-11-15 21:08:32.000', 3526]], //一段线
                      ],
            },
         ],
绘图效果，如紫色线：
![image](https://cloud.githubusercontent.com/assets/19185428/21477341/c412cb7e-cb7b-11e6-8d9e-1fa0c058b46b.png)

**Comment by pissang** [comment]
参考 http://gallery.echartsjs.com/editor.html?c=xBJlBWoD4x 这个例子的实现

**Comment by warlock-lv** [comment]
@pissang 
感谢，这么快回复， 可是 参考例子中的情况，与我的情况 完全不符， 
我的前提是 1. x轴为time类型；   2. series中只用一个 { } 就可以画出我图例中的紫色线， 而不是用多个 { }。

**Comment by pissang** [comment]
它有一个系列就是通过 visualMap 组件去实现部分线段不显示

**Comment by warlock-lv** [comment]
原来如此，明白了， 多谢。
