### ISSUE TITLE
IE8下仪表盘自动更新闪烁

### ISSUE THREAD

**Issue by cdoneshot** [ecomfe/echarts#4789]
### One-line summary [问题简述]

仪表盘每隔3s通过setOption更新数据，在IE8下图表会闪烁。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.X
+ Browser version [浏览器类型和版本]:
ie8
+ OS Version [操作系统类型和版本]:
win7 x64

### Expected behaviour [期望结果]

不会出现闪烁，和其他浏览器表现一致。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
因为需要重绘所以无法避免，建议 IE8 降级处理

**Comment by cdoneshot** [comment]
是指echarts的版本降级吗？ @pissang

**Comment by pissang** [comment]
效果降级
