### ISSUE TITLE
在2.2.7版本如何实现在x轴上实现双x轴，两条都在底部，还有就是：如果项目中把echarts的版本换成3.X版本，echart是否会向前兼容。

### ISSUE THREAD

**Issue by chenxiangguicxg** [ecomfe/echarts#4791]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/wiki/ECharts-2-%E5%8D%87%E7%BA%A7%E5%88%B0-ECharts-3-%E7%9A%84%E6%94%B9%E5%8A%A8
