### ISSUE TITLE
Miss files when build codes

### ISSUE THREAD

**Issue by linuxpham** [ecomfe/echarts#4804]
I notice that there is missing these files (after git pull Echarts 3.0 source):
- lib/coord/axisModelZoomMixin
- lib/chart/graph/roamAction

Is there any wrong?

Please support me !

Thanks !

**Comment by pissang** [comment]
How did you build codes?

**Comment by linuxpham** [comment]
Hi admin,
I had a mistake when compiled Echarts.
Thanks for supporting!
