### ISSUE TITLE
有没有局部刷新的解决方案

### ISSUE THREAD

**Issue by wind108369** [ecomfe/echarts#4808]
有一种场景，在k线图中，数据量很大，在交易时间只有最后一项数据会发生频繁的改变。用现在的刷新方法，在数据量比较大、刷新频率比较高的情况下，页面就会出现卡顿。

请问，有没有相关的解决方案，以后有没有相关的计划？

**Comment by pissang** [comment]
暂时没有解决方案，短期内也想不到太好的方法，因为那样很难保证数据的一致性

**Comment by 13560280319** [comment]
你好，我同样遇到这个问题，请问最后是怎么解决的呢
