### ISSUE TITLE
dashing 与echart集成时，数据更新时获取不到echart

### ISSUE THREAD

**Issue by luotuocao2008** [ecomfe/echarts#4811]
### One-line summary [问题简述]
在更新数据时，获取不到已经初始化过的对象。
https://github.com/luotuocao2008/dashing-echart/blob/master/bar_echart.coffee

### Expected behaviour [期望结果]
能够通过this获取，不用重新初始化。

**Comment by pissang** [comment]
这个跟 echarts 没关系吧？
