### ISSUE TITLE
virtualMap 隐藏 item 的时候还会触发 tooltip

### ISSUE THREAD

**Issue by iamcc** [ecomfe/echarts#4815]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
嗯，因为 visualMap 改的只是透明度
