### ISSUE TITLE
echarts.graphic.LinearGradient

### ISSUE THREAD

**Issue by ll232489865** [ecomfe/echarts#4817]
我在文档当中，关于设置渐变色经常看到如下代码 : new echarts.graphic.LinearGradient

但是我在API当中看不到接口，因此并不清楚参数是申明意思

+ ECharts version [echarts@3.3.2]:

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.areaStyle.normal.color

**Comment by wangmeijian** [comment]
@pissang 链接过去是空白的

**Comment by biaji** [comment]
https://echarts.baidu.com/option.html#series-line.areaStyle.color

**Comment by oakland** [comment]
这个 api 应该没有了，在 [官方文档](https://www.echartsjs.com/api.html#echarts) 中左上角的模糊搜索框中搜不到任何关于 linear 或者 gradient 相关的配置项。可以参考 @biaji 的链接配置

**Comment by bilibiliou** [comment]
文档搜不到呀，啥时候可以更新呀

**Comment by tianleiyiji123** [comment]
> http://echarts.baidu.com/option.html#series-line.areaStyle.normal.color

这个里面的color如何进行按需加载，我试了下如果用type: 'linear'那种配置，还是需要全局引入echarts,就达不到按需加载的效果了
