### ISSUE TITLE
移动端的这个例子，手指在数据上滑动时，会连dataZoom一起拖动，怎么分离呢？

### ISSUE THREAD

**Issue by sin911** [ecomfe/echarts#4822]
### One-line summary [问题简述]
用手机访问echarts的这个例子
http://echarts.baidu.com/gallery/editor.html?c=candlestick-sh
当手指在数据上滑动时，的确是希望显示tooltips的文字，但因为同时用了dataZoom,所以连总数据一起拖动了，
如图所示：
http://ww4.sinaimg.cn/large/9ed5c127gw1fb8mt9aa85j20u20ms430.jpg

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:iPhone iOS10.2

### Expected behaviour [期望结果]
希望手指在数据上滑动时，dataZoom不移动，只有拖动图表上的空白区域时，dataZoom才会进行变化，万分感谢。

### ECharts option [ECharts配置项]
请用手机访问http://www.acai188.cn/test/ech/ech.html
拖动一下啦。
数据及格式都是直接粘贴的http://echarts.baidu.com/gallery/editor.html?c=candlestick-sh

**Comment by pissang** [comment]
可以去掉 `dataZoom: { type: 'inside' } ` 组件
