### ISSUE TITLE
咨询交通路线图的展示

### ISSUE THREAD

**Issue by hezhongfeng** [ecomfe/echarts#4823]
想在省内，展示一些主要交通路线的拥堵情况
必须使用路线图，但是这个系统不能连接互联网，所以用不了百度地图
像咱们地图的中的`visualMap`那样，利用颜色深浅来标识路线的具体情况
请问有什么办法吗？

**Comment by pissang** [comment]
用 [lines](http://echarts.baidu.com/option.html#series-lines)

**Comment by hezhongfeng** [comment]
谢谢。我研究下
