### ISSUE TITLE
纵轴自适应问题

### ISSUE THREAD

**Issue by amei1234** [ecomfe/echarts#4826]
### One-line summary [问题简述]

echarts3 可实现横轴自适应，但是纵轴还实现不了。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts 3 
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

纵轴也可以实现自适应

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有啥实现不了的？

**Comment by amei1234** [comment]
@pissang 您好，使用 window.onresize = myChart.resize;  图形只能实现浏览器横向大小改变时的自适应。浏览器纵向拉伸时，只能看到图形的局部，图形无法根据浏览器的缩放进行缩放。请问有什么方法可以实现浏览器纵向拉伸时的图形自适应，以便看到图形全局。
