### ISSUE TITLE
echarts3中base64图片导出问题（图例自定义为本地图片（有转base64）时，下载图中图例未出现）

### ISSUE THREAD

**Issue by 1538986328** [ecomfe/echarts#4827]
### One-line summary [问题简述]
  我使用Echarts画了一个 双y轴的组合图（柱子+折线（虚线、实线都有））的情况， 其中 虚线图例 我用了一个本地的png小图片， setOption之后直接转成base64的图片，下载的图片未达到理想状态。
   
 网络调整试验的时候，发现下面的情况，下载的base64图片中会没有包含图例 。
  
        网络一开始 0kb/s ->  切换到 50kb/s 等待本地缓存加载出来后 ->切换到 250kb/s 等待7s -> 切换到 4MB/s 出现发送的xhr请求后 立马->切换到 1.5MB/s 结束。 

请问： 我该如何做，才能保证图表中的图例画出一根虚线； 或者如何保证下载的base64图片中自定义的legend能下载成功？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
自定义图片建议转成 base64，不用远程加载的

**Comment by 1538986328** [comment]
我本身是这样处理的，代码如下：
var ResourcesPath = "";//资源IP地址

function getBase64Image(img) {
	var canvas = document.createElement("canvas");
	canvas.width = img.width;
	canvas.height = img.height;
	var ctx = canvas.getContext("2d");
	ctx.drawImage(img, 0, 0, img.width, img.height);
	var ext = img.src.substring(img.src.lastIndexOf(".")+1).toLowerCase();
	var dataURL = canvas.toDataURL("image/"+ext);
	return dataURL;
}


var buleLineItem = ResourcesPath+"static/resources/front/imgs/report/lineImg/buleLine.png";
var buleLineimage = new Image();
buleLineimage.src = buleLineItem;
buleLineimage.crossOrigin = '';
buleLineimage.onload = function () {
	var blueLine = getBase64Image(buleLineimage);
	localStorage.blueLine = blueLine;
};

**Comment by 1538986328** [comment]
是因为我本地缓存存了base64的这图导致的么
