### ISSUE TITLE
柱状图堆叠显示，水平滑动柱状图的时候，上边的柱子的数值会出现错位！http://121.42.201.123:8888/chartformobile/chart.html?X-Token=a21f7f39a5a98dc7957d147d4fd93cc4&X-Client-Id=android.38433999-ddd2-44c6-8a91-0f54da19f872%20OPPO.OPPO%20R9m.api22%205.1&role=chief_manager

### ISSUE THREAD

**Issue by wuxia510** [ecomfe/echarts#4831]
### One-line summary [问题简述]
http://121.42.201.123:8888/chartformobile/chart.html?X-Token=a21f7f39a5a98dc7957d147d4fd93cc4&X-Client-Id=android.38433999-ddd2-44c6-8a91-0f54da19f872%20OPPO.OPPO%20R9m.api22%205.1&role=chief_manager

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/4825 不要重复提 issue
