### ISSUE TITLE
Load local csv file

### ISSUE THREAD

**Issue by amyjia** [ecomfe/echarts#4834]
### One-line summary [问题简述]
请提供一个load本地csv file的案例。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Windows

### Expected behaviour [期望结果]

Load local csv file

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

我尝试复制下例官方案例，但无法load json file。
http://echarts.baidu.com/demo.html#candlestick-brush

另，如可，请提供load csv 范例。多谢

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=xrJDKzwZQ

**Comment by amyjia** [comment]
谢谢您的回复。我尝试了您的范例，但没有成功。
我尝试的TSLA.csv源文件的格式为：date, open price, close price, low, high.
代码如下：
`<!doctype html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    
    <script src="echarts.min.js"></script>
</head>
<body>
 
<script type="text/javascript" src="https://cdn.bootcss.com/PapaParse/4.1.2/papaparse.min.js"></script>
<script type="text/javascript">
 
var uploadedDataURL = "TSLA.csv";

function calculateMA(dayCount, data) {
    var result = [];
    for (var i = 0, len = data.length; i < len; i++) {
        if (i < dayCount) {
            result.push('-');
            continue;
        }
        var sum = 0;
        for (var j = 0; j < dayCount; j++) {
            sum += data[i - j][1];
        }
        result.push(sum / dayCount);
    }
    return result;
}

myChart.showLoading();
$.get(uploadedDataURL, function(csvStr) {
    myChart.hideLoading();

    var res = Papa.parse(csvStr).data.slice(2);

    console.log(Papa.parse(csvStr));

    res = res.reverse();

    var dates = res.map(function(item) {
        return item[0];
    });

    var data = res.map(function(item) {
        return [+item[1], +item[2], +item[3], +item[4]];
    });

    myChart.setOption(option = {
        legend: {
            data: ['日K', 'MA5', 'MA10', 'MA20', 'MA30']
        },
        tooltip: {
            trigger: 'axis'
        },
        xAxis: {
            type: 'category',
            data: dates
        },
        yAxis: {
            scale: true,
            scale: true
        },
        dataZoom: [{

        }, {
            type: 'inside'
        }],
        animation: false,
        series: [{
            type: 'candlestick',
            name: '日K',
            data: data
        }, {
            name: 'MA5',
            type: 'line',
            data: calculateMA(5, data),
            smooth: true,
            lineStyle: {
                normal: {
                    width: 1
                }
            }
        }, {
            name: 'MA10',
            type: 'line',
            data: calculateMA(10, data),
            smooth: true,
            lineStyle: {
                normal: {
                    width: 1
                }
            }
        }, {
            name: 'MA20',
            type: 'line',
            data: calculateMA(20, data),
            smooth: true,
            lineStyle: {
                normal: {
                    width: 1
                }
            }
        }, {
            name: 'MA30',
            type: 'line',
            data: calculateMA(30, data),
            smooth: true,
            lineStyle: {
                normal: {
                    width: 1
                }
            }
        }]
    });
});
</script>


</body>  
</html>
`

**Comment by amyjia** [comment]
我唯一改动的地方为：
`var data = res.map(function(item) {
    return [+item[1], +item[2], +item[3], +item[4]];
});`

**Comment by amyjia** [comment]
求大神指点><

**Comment by 100pah** [comment]
浏览器不能做到 load 本地文件，除非开 server。这是浏览器的安全机制决定的。
