### ISSUE TITLE
本人小白，下载源代码版本解压后发现test文件的例子都无法显示

### ISSUE THREAD

**Issue by git237491-dd** [ecomfe/echarts#4835]
### One-line summary [问题简述]

我从 https://github.com/ecomfe/echarts  下载了zip到本机解压，
然后按照    http://echarts.baidu.com/tutorial.html#%E5%9C%A8%20webpack%20%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts  的提示一步步操作，npm install echarts --save也成功了，但是test文件的例子在浏览器中还是白茫茫的页面，不知是啥问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:edge、chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
希望能在本机直接双击运行test中的例子

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/3730
