### ISSUE TITLE
如何获取像原生tooltip里面的时间

### ISSUE THREAD

**Issue by amei1234** [ecomfe/echarts#4841]
### One-line summary [问题简述]

想实现自己的tooltip，其中时间希望获得像原生tooltip里面鼠标滑过时的横轴时间，不知道如何实现。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:chrome 50.0.2661.102 m
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

获得像原生tooltip里面鼠标滑动时的横轴时间

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
formatter 里可以获取，或者有 showtip 事件

**Comment by amei1234** [comment]
@pissang  您好，官方文档上，tooltip的formatter如下：formatter: '{b0}: {c0}<br />{b1}: {c1}' 。我研究了一下，还是不知道如何获取鼠标滑过时的横轴时间，麻烦大神不吝赐教 。

**Comment by pissang** [comment]
formatter 可以是函数

**Comment by amei1234** [comment]
@pissang您好， 其实我用的是函数，但是params参数里面并没有x 轴的时间呀。。。我不是要取数据里面的x坐标。我想要鼠标滑动时，x轴的实际时间。。。

**Comment by pissang** [comment]
你的横轴是 category 还是 time 类型的？

**Comment by amei1234** [comment]
@pissang 您好，横轴是time类型。

**Comment by pissang** [comment]
可以试一下用 http://echarts.baidu.com/api.html#echartsInstance.convertFromPixel 这个接口
