### ISSUE TITLE
echart2.0和echart3.0同事引用会冲突

### ISSUE THREAD

**Issue by oczjack** [ecomfe/echarts#4842]
### One-line summary [问题简述]
您好，
我之前一直使用的事echart2.0，后台由于客户需求的变更，我们需要更换成echart3.0的力导向图，但是在3.0中的树图并不是我们需要的，所有智能沿用2.0中的树图，结果发现两个图都出不来

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

浏览器，我们是以IE为主的，但是这个情况我们在火狐，chrome下都进行了测试，

### Expected behaviour [期望结果]

echart3.0里是否能够改变树图呢？或者是怎样才能使2.0.和3.0可以同时使用呢？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
是否有报错？

**Comment by oczjack** [comment]
会报错，如下图

另外，在echarts3.0里面是否能实现这样的图


365570664@qq.com
 
发件人： Yi Shen
发送时间： 2017-01-03 10:49
收件人： ecomfe/echarts
抄送： oczjack; Author
主题： Re: [ecomfe/echarts] echart2.0和echart3.0同事引用会冲突 (#4842)
是否有报错？

**Comment by 100pah** [comment]
没有图片

**Comment by oczjack** [comment]
请问关于冲突的问题是否存在呢？
