### ISSUE TITLE
关于“台湾地图文件”的问题

### ISSUE THREAD

**Issue by cor7ona** [ecomfe/echarts#4844]
### One-line summary [问题简述]

台湾地图文件的注册名为什么是：beijing？不是应该是“台湾” 吗？

文件地址：https://github.com/ecomfe/echarts/blob/master/map/js/province/taiwan.js

截图如下：

![wechatimg51](https://cloud.githubusercontent.com/assets/8801894/21599301/8866604c-d1a5-11e6-9f73-6625ead6d0fa.jpeg)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.3.2
+ Browser version [浏览器类型和版本]: *
+ OS Version [操作系统类型和版本]: *

### Expected behaviour [期望结果]

请解释一下这个问题？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
Sorry 手误

**Comment by cor7ona** [comment]
好吧
