### ISSUE TITLE
编译完成后，引入文件报错“Uncaught TypeError: zrUtil.eqNaN is not a function”

### ISSUE THREAD

**Issue by zerogog** [ecomfe/echarts#4850]
### One-line summary [问题简述]
之前提到过无法控制K线图的柱宽，详情可查看问题[#4783 ](https://github.com/ecomfe/echarts/issues/4783)
问题修改后，我下载整个项目，试图在本地重新编译生成最新版本。
成功生成之后，在html上直接引入文件时，报错：`Uncaught TypeError: zrUtil.eqNaN is not a function`。
尝试查找问题原因，发现在引用` echarts\node_modules\zrender\lib\core\util.js` 后，并没有在该文件中找到`eqNaN`这个函数的定义。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:当前项目最新版本，克隆时间2017/1/3 17:56
+ Browser version [浏览器类型和版本]:chrome 55
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

编译后的文件能正式运行

### ECharts option [出错位置]

```javascript
//zrUtil.eqNaN is not a functuion
if (baseAxis.isBlank() || zrUtil.eqNaN(point[0]) || zrUtil.eqNaN(point[1])) {
	this._hideAxisPointer(coordSys.name);
	return;
}
```

**Comment by pissang** [comment]
echarts 的代码版本跟 zrender 不同步，如果 echarts 的代码是 github 上最新的，zrender 也需要是

**Comment by zerogog** [comment]
## 谢谢，问题已解决

本地zrender模块是通过npm安装的，根据配置项，安装的是`3.2.2`。`echarts\node_modules\zrender\lib\core\util.js`文件中本没有`eqNaN`函数的定义，下载zrender模块master分支之后，比对这两个版本的`util.js`文件，确实存在差异。将echarts中的zrender替换为该版本之后，问题得到解决。
