### ISSUE TITLE
堆叠条形图某一段数字太小，显示的数字显示不完全的问题怎么解决

### ISSUE THREAD

**Issue by jasminecjc** [ecomfe/echarts#4852]
官方示例： http://echarts.baidu.com/demo.html#bar-y-category-stack
如果把其中一段的某些值设置成比较小的值，显示的数字就会显示不完全，比如把直接访问的data设置成`data: [20, 302, 301, 34, 390, 330, 320]`,
这样的体验不太好，这个问题怎么解决

**Comment by Ovilia** [comment]
你期望得到什么样的效果？

**Comment by 100pah** [comment]
可参见：
<http://echarts.baidu.com/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE>
<http://www.echartsjs.com/gallery/editor.html?c=bar-label-rotation>
