### ISSUE TITLE
按钮显示问题

### ISSUE THREAD

**Issue by liqiang-fit2cloud** [ecomfe/echarts#4854]
hi
如果title比较长，btn也比较多的时候，title会盖住btn。
比方说会变成[这样](https://s3.cn-north-1.amazonaws.com.cn/tempfiles/a.jpg)

有没有什么方法能变成那种，就是只在右上角放一个一个按钮，这个按钮上边有三个纵向排列的点，点击按钮之后出来下拉框，下拉框里列出来需要的btn。

谢谢

**Comment by liqiang-fit2cloud** [comment]
期望是这样的
https://s3.cn-north-1.amazonaws.com.cn/tempfiles/b.jpg

**Comment by 100pah** [comment]
『这个按钮上边有三个纵向排列的点，点击按钮之后出来下拉框』这种个性化的功能要自己实现了。
