### ISSUE TITLE
series.data中的dataMax和dataMin

### ISSUE THREAD

**Issue by jamln** [ecomfe/echarts#4857]
### One-line summary [问题简述]
visualMap中的max 和 min 能否设置为series.data中的dataMax和dataMin?
配置项中没有找到哪里能获取dataMax 和 dataMin.

主要是想获取这两个值来设置气泡的symbolSize最大最小值, 防止过大遮盖住x轴.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.2.3
+ Browser version [浏览器类型和版本]:Chrome 54
+ OS Version [操作系统类型和版本]:Windows 7 64位

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

限制图元大小,防止出现下图情况

![2017-01-04_143613](https://cloud.githubusercontent.com/assets/23024273/21633604/9c696170-d28b-11e6-82c6-b0f207a87f65.png)

**Comment by 100pah** [comment]
暂时只能自己用数据计算出 min max 赋值给 visualMap。
后面会考虑这个需求。

**Comment by jamln** [comment]
了解,谢谢
