### ISSUE TITLE
echart渲染多个图表

### ISSUE THREAD

**Issue by evaxyd** [ecomfe/echarts#4859]
function _showCharts(type) {
        var showChart = echarts.init(document.getElementById('showChart')),
              clickChart = echarts.init(document.getElementById('clickChart'));
        var option = {};
        
        if(type == 'show'){
          showChart.setOption(option);
        }else{
          clickChart.setOption(option);
        }
    };

根据type不同想在一个方法里渲染2个图表，只能显示一个，不能这么写么？option传过来的数据都是一样的，不想分2个方法写啊。

**Comment by pissang** [comment]
echarts 可以渲染多个图表，你看看自己代码逻辑是否有问题

**Comment by evaxyd** [comment]
if(type == 'show'){
          showChart = echarts.init(document.getElementById('main'));
          showChart.setOption(option);
        }else{
          clickChart = echarts.init(document.getElementById('clickChart'));
          clickChart.setOption(option);
        }

这么写就可以，不能提前声明。
