### ISSUE TITLE
地图区域的label 文字显示在区域边界上了，如何调整label的位置

### ISSUE THREAD

**Issue by MarkNC007** [ecomfe/echarts#4866]
### One-line summary [问题简述]
有些地图区域形状比较奇特，label 文字显示在区域边界上

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
显示在区域范围内，或者可以人为调整

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by MarkNC007** [comment]
已解决：

**Comment by MarkNC007** [comment]
已解决：
打开js或Json文件，找到地图描述的的（"properties":{"name":"XX省","cp":[101.04524,23.062507],"childNum":1},）内容，将（"cp":[xx,xx]）内容删除，省名就会自动在该省的地图中间了，否则会默认在省会或首府位置显示
来自 @earthpea：
https://github.com/ecomfe/echarts/issues/4635

**Comment by ClarenceC** [comment]
这都行学习了
