### ISSUE TITLE
Bug in legend Height and Container?

### ISSUE THREAD

**Issue by vij1ay** [ecomfe/echarts#4871]
### One-line summary [问题简述]
Not able to control legend height / container. Getting problems if more than five legends are there. Legends are getting overlapped with the chart. If top option is used for setting legend position then the legends are getting chopped off. The canvas height of the char is playing here i guess. Please refer screen shot

Overlapped
![throughput in 1](https://cloud.githubusercontent.com/assets/3069381/21674584/56a92732-d354-11e6-855b-bb9d9da5ebfa.png)

Chopped Off
![throughput in 2](https://cloud.githubusercontent.com/assets/3069381/21674595/64d358dc-d354-11e6-8253-56a11ec09f26.png)

### Version & Environment [版本及环境]
+ ECharts version: latest
+ Browser version: Mozilla
+ OS Version: Windows 10

**Comment by 100pah** [comment]
I am afraid that it may be not a good way that displaying long text in legend labels.
May be you can use [legend.formatter](http://echarts.baidu.com/option.html#legend.formatter) to cut that lang text. Or you can enlarge the height of the chart to give enough space to contain those legend text.

**Comment by vij1ay** [comment]
Hi . Thanks for your time. Increasing the height is no help as it increases the canvas height ad graph inside. 

Currently I used a div outside the graph and extend the legends outside the canvas using. The chart api chart.dispatchAction ( which saved d day) for my custom  legends. Since it is in a seperate div, I able to control it. (attached d output)
![index](https://cloud.githubusercontent.com/assets/3069381/22012597/e51fa576-dcba-11e6-9ea2-3b4121ba844d.png)

Anyways, thanks for the help. And thanks a lot for keeping this graph as open source.

**Comment by 100pah** [comment]
I am glad that you have found a solution. 

BTW, by adjusting the attribute [grid.bottom](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.bottom) (or [grid.top](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.top), [grid.left](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.left), [grid.right](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.right)) you can modify the size and position of the cartesian in the whole canvas.

**Comment by epworkplace** [comment]
> Hi . Thanks for your time. Increasing the height is no help as it increases the canvas height ad graph inside.
> 
> Currently I used a div outside the graph and extend the legends outside the canvas using. The chart api chart.dispatchAction ( which saved d day) for my custom legends. Since it is in a seperate div, I able to control it. (attached d output)
> ![index](https://cloud.githubusercontent.com/assets/3069381/22012597/e51fa576-dcba-11e6-9ea2-3b4121ba844d.png)
> 
> Anyways, thanks for the help. And thanks a lot for keeping this graph as open source.

Hi,

Could you please provide code sample.

Thank you.

**Comment by apurv-thakur** [comment]
Hi @vij1ay,

Please provide sample code for the same. I am facing the same issues.

Thanks

**Comment by futaz** [comment]
As @100pah mentioned, ```grid.top``` and ```grid.bottom``` can be used to set the chart area's distance from the border of the canvas. So ```grid.top: 200``` will leave 200 pixels for the legend on the bottom.

See the [docs](https://echarts.apache.org/v4/en/option.html#grid.top) for details.
