### ISSUE TITLE
展示地图时可以同时内部使用图例和时间轴吗？有没有代码举例

### ISSUE THREAD

**Issue by caoxiaoye** [ecomfe/echarts#4872]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
图例时间轴都能用。<http://gallery.echartsjs.com/explore.html#components=timeline~sort=rank~timeframe=all~author=all>
