### ISSUE TITLE
candlestick不支持connectNulls

### ISSUE THREAD

**Issue by whanshisb** [ecomfe/echarts#4875]
candlestick不支持connectNulls，停牌的处理就很蛋疼了

**Comment by 100pah** [comment]
没有理解，`connectNulls` 是链接两点，candlestick 是一个个独立的点并不需要连接。

**Comment by whanshisb** [comment]
啊 谢谢告知connectNulls的具体功能点，我原以为是显示值为null的点，原来是用来连接的。

然后candlestick在展现中间有一段停牌的股票日k的时候，停牌的天对应的开收高低的数组的0到3位是给null么
