### ISSUE TITLE
echarts 柱状图中，三个柱子只显示一个x轴标签，怎么做到？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#4877]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![image](https://cloud.githubusercontent.com/assets/22878190/21709259/9bd1a9bc-d41a-11e6-9ebd-a90433c173ea.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
三个系列

**Comment by chenxia123** [comment]
但是这样组合的折线图点的个数也需要相应的缩少三分之一才行吧？如果我折线图的data个数不能减少呢？

**Comment by pissang** [comment]
那设置 xAxis.axisLabel.interval  为 2 试试
