### ISSUE TITLE
折线图显示英文修改中文

### ISSUE THREAD

**Issue by 18740283329** [ecomfe/echarts#4878]
### One-line summary [问题简述
滑动到折线图时，如何使显示的英文修改成中文

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
？哪里有英文？
