### ISSUE TITLE
我觉得既然是数据，那么就少了表格

### ISSUE THREAD

**Issue by icode** [ecomfe/echarts#488]
恩，我说的表格不是我们的html table，而是像新版的google docs那样，看下就知道了，数据加载呈现很快，因为那是canvas画的，一个excel的容量，这个数据量虽然不是特别大，几万到几十万条数据量，不算列，这是excel单页最大容量，但是乘以列数也不是小数目，对于大数据的微分析是相当有用的。

望echarts团队采纳

**Comment by icode** [comment]
@hushicai 关闭是啥意思？是有了还是啥 ？

**Comment by icode** [comment]
这个需求不是单纯的表格，而是用图表的方式绘制，参考google的spreadsheets

**Comment by hushicai** [comment]
有想法可以发pr。

**Comment by icode** [comment]
有想法没实现咋pull request？

**Comment by YuanZhencai** [comment]
我也想要 类似spreadsheets  的表格
