### ISSUE TITLE
如何给dataZoom组件的手柄设置背景图片？

### ISSUE THREAD

**Issue by hollowtree** [ecomfe/echarts#4881]
### One-line summary [问题简述]
官方文档在配置项手册的 dataZoom[i]-slider.handleStyle.color 处写道：
```
颜色可以使用 RGB 表示，比如 'rgb(128, 128, 128)'，如果想要加上 alpha 通道表示不透明度，可以使用 RGBA，比如 'rgba(128, 128, 128, 0.5)'，也可以使用十六进制格式，比如 '#ccc'。除了纯色之外颜色也支持渐变色和纹理填充
// 线性渐变，前四个参数分别是 x0, y0, x2, y2, 范围从 0 - 1，相当于在图形包围盒中的百分比，如果最后一个参数传 `true`，则该四个值是绝对的像素位置
color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
  offset: 0, color: 'red' // 0% 处的颜色
}, {
  offset: 1, color: 'blue' // 100% 处的颜色
}], false)
// 径向渐变，前三个参数分别是圆心 x, y 和半径，取值同线性渐变
color: new echarts.graphic.RadialGradient(0.5, 0.5, 0.5, [...], false)
// 纹理填充
color: new echarts.graphic.Pattern(
  imageDom, // 支持为 HTMLImageElement, HTMLCanvasElement，不支持路径字符串
  'repeat' // 是否平铺, 可以是 repeat-x, repeat-y, no-repeat
)
```
但是现在最新版本的echarts好像已经不支持echarts.graphic.Pattern了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: Google Chrome， 版本 57.0.2956.0 canary (64-bit)
+ OS Version [操作系统类型和版本]: Win 7 专业版

### Expected behaviour [期望结果]

我想将一张图片作为dataZoom手柄的背景，同时设置图片为 no-repeat，但是echarts.graphic.Pattern好像不可用了。我看到了另外一个函数echarts.graphic.Image似乎可用，但是我不知道这个函数可不可用以及这个函数需要的参数。

**Comment by pissang** [comment]
应该支持的吧？但是用 Pattern 显示背景图片问题很多
