### ISSUE TITLE
toolbox如何实现排序功能

### ISSUE THREAD

**Issue by HeroadZ** [ecomfe/echarts#4883]
### One-line summary [问题简述]

我在toolbox里面添加了自定义的排序功能，但是目前只能通过先在外面排序好数据，然后在点击事件里面setOption已经排好序的新生成的option。
这样有个问题，就是不能复用，我理想的情况是使用类似this这种功能。

### Version & Environment [版本及环境]
+ ECharts version [3.3.2]:
+ Browser version [chrome 最新版本]:
+ OS Version [win10];:

### Expected behaviour [期望结果]
将被点击的toolbox的被实例化的chart，里面的数据，对应排序。
也就是说一句this.chart.sort就可以，当然这只是理想化的情况

### ECharts option [ECharts配置项]

```javascript
option = {
    toolbox: {
        feature: {
            // dataView: {readOnly: false},
            // restore: {},
            // saveAsImage: {},
            myTool1: {
                show: true,
                title: '排序',
                icon: 'path://M733.396 1015.554h-39.557c-15.442 0-27.975-12.533-27.975-27.975v-979.131h55.95v939.575l230.6-230.6 39.557 39.557-258.575 258.575zM302.186 75.979l-230.6 230.6-39.557-39.557 258.575-258.575h39.557c15.442 0 27.975 12.533 27.975 27.975v979.131h-55.95v-939.575z',
                onclick: function () {
                    wholesaleModule.wholesaleArea.setOption(wholesaleAreaSortedOption);
                }
            }
        }
    }
}
```

**Comment by HeroadZ** [comment]
现在我可以获取到chart的option，但是获取不到chart的实例。
```js
feature: {
        // dataView: {readOnly: false},
        // restore: {},
        // saveAsImage: {},
        myTool1: {
            show: true,
            title: '排序',
            icon: 'path://M733.396 1015.554h-39.557c-15.442 0-27.975-12.533-27.975-27.975v-979.131h55.95v939.575l230.6-230.6 39.557 39.557-258.575 258.575zM302.186 75.979l-230.6 230.6-39.557-39.557 258.575-258.575h39.557c15.442 0 27.975 12.533 27.975 27.975v979.131h-55.95v-939.575z',
            onclick: function () {
                console.log(arguments);
                //获取当前chart的option
                var thisOptionArr = arguments[0].option.series;
                //重新排序
                var sortedArr = commonService.sortBLOption(thisOptionArr);
                //覆盖
                for(var i=0;i<sortedArr.length;i++) {
                    thisOptionArr[i].data = sortedArr[i];
                }
                //重新渲染
                wholesaleModule.wholesaleArea.setOption(thisOptionArr);
            }
        }
    }
```

当我使用
```js
arguments[0].setOption(thisOptionArr);
```
会出现错误
···
Uncaught TypeError: t.split is not a function
    at a.parseClassType (http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:11:27198)
    at Function.t.hasClass (http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:11:28102)
    at http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:25:4382
    at Array.forEach (native)
    at f (http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:1:2050)
    at l (http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:25:4336)
    at n.setOption (http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:25:4812)
    at i.setOption (http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:24:31361)
    at Object.onclick (http://localhost:63347/skr-web/lib/elibs/eOption/mixBL.js:139:30)
    at n.<anonymous> (http://cdn.bootcss.com/echarts/3.3.2/echarts.min.js:1:2795)
```

请问我如何获取当前实例呢？？ 万分感谢！

**Comment by pissang** [comment]
chart 示例可以你自己管理

**Comment by HeroadZ** [comment]
@pissang 也就是说 我自能通过传参的方式吗？
