### ISSUE TITLE
showSymbol为false的series，如何实现mouseover事件

### ISSUE THREAD

**Issue by twoeo** [ecomfe/echarts#4884]
### One-line summary [问题简述]

showSymbol为false时， mouseover事件无法触发。
想要实现，鼠标在折线上移动时，获取到经过的点。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.x
+ Browser version [浏览器类型和版本]:Chrome
+ OS Version [操作系统类型和版本]:Win7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
设成

```
tooltip: {
    trigger: 'axis'
}
```

可以解决你问题么？

**Comment by twoeo** [comment]
@100pah 如此设置，虽然鼠标移动到图上会触发tooltip，但EChart实例的mouseover事件还是只有鼠标移动到数据点上才会触发。

```javascript
var chart= ECharts.init('#xxx');

chart.on('mouseover', function(params){
  //只有鼠标移动到点上才会触发，即便设置了trigger：axis
})
```

**Comment by twoeo** [comment]
使用 highlight 事件可解决此问题，关单。

**Comment by kyriejoshua** [comment]
请问楼主是用 action 的 highlight 来实现的吗。

**Comment by k8w** [comment]
echartInstance.on('highlight', function(params){ ... })
