### ISSUE TITLE
折线图是否可以手动触发折点处的click事件

### ISSUE THREAD

**Issue by JSW5297** [ecomfe/echarts#4885]
### One-line summary [问题简述]

折线图是否可以手动触发折点处的click事件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: Chrome  54.0.2840.87 m (64-bit)
+ OS Version [操作系统类型和版本]: Windows 7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
现在不行，为什么要这么做？

**Comment by JSW5297** [comment]
![image](https://cloud.githubusercontent.com/assets/12059800/21741866/568ace84-d51d-11e6-839c-97d10dd0fda8.png)
如上图，我点击折点的时候需要从折点连线到上面的星期上面，然后在折点处放一个自定义的div，同样需要在点击上面的星期的时候需要同样的效果，但是单击上面的星期的时候我是无法拿到下面对应的折点的offsetX和offsetY的值的，所以没法确定连线的高度和自定义div的位置。当然这个不属于echarts 功能的范畴啦，只不过想通过在单击星期的时候手动触发下面折点的click事件

**Comment by 100pah** [comment]
如果想得到折点对应的 x y 像素值，可以使用：
