### ISSUE TITLE
echarts title 中text和subtext不支持html

### ISSUE THREAD

**Issue by HarveyJiang** [ecomfe/echarts#4892]
echarts title 中text和subtext不支持html，这样一些icon，图片等就无法加上去。发现echarts中很多都是不支持html的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
现在不支持 html。

图片可以通过 <http://echarts.baidu.com/option.html#graphic> 或者 <http://echarts.baidu.com/option.html#series-scatter.symbol> 添加。
