### ISSUE TITLE
地图下载中台湾地图有问题

### ISSUE THREAD

**Issue by fyyyr** [ecomfe/echarts#4895]
### One-line summary [问题简述]
从ECharts3.0官网下载的台湾地图js文件中，echarts.registerMap()这个函数的第一个参数应该是中文的"台湾"，然而却是个拼音"beijing"。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/4844，谢谢反馈
