### ISSUE TITLE
webpack封装后为何文件如此之大

### ISSUE THREAD

**Issue by banterise** [ecomfe/echarts#4899]
打包之后的bundle.js达到了5.7M!!!能告诉我为什么这么大吗,就算是按需引入也是一样的大小,发现bundle.js甚至打包了Zrender的所有组件!!!
难不成是因为我用cnpm安装导致的问题吗?

**Comment by pissang** [comment]
5.7M 肯定是因为你自己把地图数据都打包进去了，或者打包了其它的东西，我们打包后的完整的源代码版本也才 1.8 M
