### ISSUE TITLE
echarts3.3.2版本有bug

### ISSUE THREAD

**Issue by xxoome** [ecomfe/echarts#4903]
地址：http://echarts.baidu.com/download.html
所有的echarts3.3.2（包含常用，精简，完整，源代码），当同时定义两个xaxis时显示异常

**Comment by xxoome** [comment]
希望能够尽快修复

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 贴下复现代码

**Comment by xxoome** [comment]
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ECharts</title>
        <script src="echarts.js"></script>
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    </head>
    <body>
        <div id="main" style="height:350px;"></div>
    </body>
    <script>
        $(function() {
            var myChart = echarts.init(document.getElementById('main'));
            var option = {
                xAxis: [{
                    data: [11, 22, 33]
                }, {
                    data: [44, 55, 66]
                }],
                yAxis: {
                    name: "流量",
                },
                series: [{
                    name: '系统监控',
                    type: 'line',
                    data: [1, 2, 3]
                }, {
                    name: '今天数据',
                    type: 'line',
                    data: [4, 5, 6]
                }]
            };
            myChart.setOption(option);
        })
    </script>
</html>

**Comment by 100pah** [comment]
```js
{
        name: '今天数据',
        type: 'line',
        xAxisIndex: 1, // 如果要使用第二个轴，应如此设置。
        data: [4, 5, 6]
}
```

**Comment by xxoome** [comment]
谢谢，知道了
