### ISSUE TITLE
echart3 迁徙图  里面的  线是不是不支持设置显示箭头

### ISSUE THREAD

**Issue by wdd119** [ecomfe/echarts#4907]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
马上发布的新版本会支持

**Comment by wdd119** [comment]
谢谢
