### ISSUE TITLE
ECharts地图数据乱码

### ISSUE THREAD

**Issue by photino** [ecomfe/echarts#4908]
看文件编码应该是utf8的，不知道是不是因为设置了`"encodeOffsets":[[116285,22746]]}`？

![china-map](https://cloud.githubusercontent.com/assets/3446306/21874067/a25166aa-d8ad-11e6-8287-a3ac4e038c0c.png)

**Comment by newEchartster** [comment]
直接引用数据文件吧

**Comment by pissang** [comment]
这是压缩过后的地图文件

**Comment by rushmc** [comment]
@pissang 是用什么工具压缩的？
