### ISSUE TITLE
echarts在移动端如果设置了dataZoom,手指放在图表上就不能滚动页面了

### ISSUE THREAD

**Issue by Jabbar2010** [ecomfe/echarts#4910]
这个问题，我看很多人都已经问了，到底该怎么解决？？这个严重影响用户的体验，能不能退而求其次的：把dataZoom事件变换下，开放其他的api来模拟dataZoom事件左右滑动，从而避免手指触摸的交互，避免和系统触摸滚动事件冲突？？？

希望能有答复，谢谢  @100pah @pissang

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Jabbar2010** [comment]
补充下：dataZoom 设置inside为disabled，启用下面的slider，为什么上下滑动图标也不能滚动？
按理说此时图表的交互事件已经没有了，全在slider上  @100pah @pissang

**Comment by PhilYue** [comment]
同求方案

**Comment by 100pah** [comment]
@Jabbar2010 什么版本的 echarts ？

**Comment by Jabbar2010** [comment]
@100pah 最新版本的echarts 还是不能滚动@pissang 干嘛close

**Comment by xpbtmusic** [comment]
这个echarts，处理事件能否触摸到echarts时，拦截父view事件，自己处理。这样和系统事件不冲突。

**Comment by techistoner** [comment]
不知道这个问题解决了没有
