### ISSUE TITLE
k线图如何和下方的柱状图数据联动

### ISSUE THREAD

**Issue by qianduanMortal** [ecomfe/echarts#4914]
正常股票的k线图，上方的k图和下方的柱状图是共用一个tooltip的。
请问如何实现。

**Comment by xiaoma0105** [comment]
如果是不同echart图表下的话可以用connect方法试试，同一个的话目前没有特别好的办法

**Comment by qianduanMortal** [comment]
是一个echarts实例，但是是两个坐标系。 上下两个对齐的坐标系。
如果不能的话， 能否实现，同一个坐标系，分别有k线和柱状图？

**Comment by xiaoma0105** [comment]
一个echarts实例看了好久都没有实现方法，试着分成两个实例去做看看咯。因为connect联动挺强大的，我们使用鼠标事件或者手势都能做到联动的效果

**Comment by qianduanMortal** [comment]
也就是说，我需要两个canvas了？

**Comment by xiaoma0105** [comment]
是的，一个canvas目前做不到
