### ISSUE TITLE
地图上名字重合有解决办法没有啊？

### ISSUE THREAD

**Issue by newEchartster** [ecomfe/echarts#4918]
### One-line summary [问题简述]
地图上点坐标距离很近时，显示的名字重叠了，有没有不让他们显示重叠的办法？？

![qq 20170112173931](https://cloud.githubusercontent.com/assets/23163953/21884404/20446cde-d8ee-11e6-8e34-8a1d0ca6cd6a.jpg)

**Comment by wwwsssqqq** [comment]
你解决了没有？

**Comment by newEchartster** [comment]
没有。
