### ISSUE TITLE
能不能给tooltip弹层绑定事件，实现点击tooltip，弹层消失的功能

### ISSUE THREAD

**Issue by pzljp** [ecomfe/echarts#4924]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

能不能给tooltip弹层绑定事件，实现点击tooltip，弹层消失的功能。现在获取不到tooltip，不知道怎么给他绑定事件。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by For-me** [comment]
可以通过 action.tooltip.hideTip和 action.tooltip.showTip来控制显示隐藏

**Comment by pzljp** [comment]
@For-me  我需要先捕获点击弹层的事件，才能用action来控制显示和隐藏。现在问题时能不能给action绑定事件。

**Comment by 100pah** [comment]
tooltip 中的弹出层的内容可以自己定制 html，可以绑定事件。
