### ISSUE TITLE
label的formatter不支持HTML

### ISSUE THREAD

**Issue by cwtuan** [ecomfe/echarts#4930]
### One-line summary [问题简述]
tooltip的formatter可以返回HTML，但是label的formatter不支持HTML

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Mac

### Expected behaviour [期望结果]
期望label的formatter支持HTML

### ECharts option [ECharts配置项]

```javascript
option = {
  "series": [
    {
      "type": "pie",
      "itemStyle": {
        "normal": {
          "label": {
            "formatter": "任务:<BR/>{b}", // 不能用HTML
          }
        }
      },
      "data": [
        {
          "value": 5,
          "name": "成功任务"
        },
        {
          "value": 3,
          "name": "失败任务"
        }
      ]
    }
  ],
  "tooltip": {
    "trigger": "item",
    "formatter": "{b}<BR/>{c}个({d}%)" // 可以用HTML
  }
}
```

**Comment by 100pah** [comment]
暂时还不能支持，换行可以使用 `'\n'`，如 `"{b}\n{c}个({d}%)"`

**Comment by muzishuiji** [comment]
现在还不能只是label的formatter渲染html

**Comment by mqliutie** [comment]
2019年了, 这个功能如何了

**Comment by cwtuan** [comment]
@100pah 
能不能把这个issue打开，暂时不支持，以后能支持吗？

**Comment by jackbai233** [comment]
啥时候能支持html啊。刚需，这个功能，求添加啊

**Comment by naziD** [comment]
这产品简直服了，17年的需求 issue到现在也不支持

**Comment by cwtuan** [comment]
@100pah 求支持～～

**Comment by feaswcy** [comment]
求支持

**Comment by cwtuan** [comment]
@100pah 
Please open this issue, even if this not supported currently.

**Comment by GraceLyen** [comment]
这个功能好实用啊 如果label文字过长 通过css还可以解决缩写问题 求资瓷～

**Comment by aloneWang** [comment]
请问啥时候支持。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by Alfxjx** [comment]
貌似现在还是不支持呀 tooltip是支持的，希望label也可以支持

**Comment by cwtuan** [comment]
is this project dead?

**Comment by Rabbitzzc** [comment]
可能已经死了？
这个功能还是挺重要的吧

**Comment by cwtuan** [comment]
why this issue is closed???

**Comment by Rabbitzzc** [comment]
可能得直接提交 PR 了，按理说实现上不难吧

**Comment by cwtuan** [comment]
@100pah @Ovilia

**Comment by Susa3n** [comment]
2022年了
