### ISSUE TITLE
图表div被隐藏（hidden）之后渲染，显示不了

### ISSUE THREAD

**Issue by wangbo593599657** [ecomfe/echarts#4931]
图表div被隐藏（hidden=true）之后渲染，然后我通过一个操作（didden=false）让他显示则显示不出来，重新setOption后又可以显示出来

**Comment by 100pah** [comment]
渲染的时候需要高宽，如果隐藏导致取不到高宽则渲染不出来。如果一定要在隐藏的时候渲染图表，则可在 [echarts.init](http://echarts.baidu.com/api.html#echarts.init) 的时候传入 `width/height`.

**Comment by wangbo593599657** [comment]
怎么传入呢，能具体说下吗，谢谢

**Comment by Justineo** [comment]
@wangbo593599657 上面 @100pah 给的链接里不是已经有了么？

**Comment by wangbo593599657** [comment]
表示看了那个还是用不来，，能具体指教一下吗？QQ593599657

**Comment by wangbo593599657** [comment]
感谢大神的耐心指导。。。

**Comment by wangbo593599657** [comment]
明天就要交项目了 有点急。。

**Comment by visgoods** [comment]
你先把div show出来，再去渲染echart
