### ISSUE TITLE
echarts横坐标type=value时，由于数字比较大重叠的问题。

### ISSUE THREAD

**Issue by xushaocong** [ecomfe/echarts#4936]
### ECharts option [ECharts配置项]

```javascript
option = {
   xAxis: [
         {
               type: 'value',
               axisTick: {
                    show: false
               },
               axisLine: {
                    show: false
              }
       }
   ]
}

```

### Other comments [其他信息]
- 图表宽度比较小的情况。
![image](https://cloud.githubusercontent.com/assets/22735791/21968915/da4356ca-dbd4-11e6-8828-6279b1cedc75.png)
- 图表宽度较大的情况下才不会重叠。
![image](https://cloud.githubusercontent.com/assets/22735791/21968922/ee536132-dbd4-11e6-8edd-c44ad4afdd77.png)

**Comment by sevenen** [comment]
http://echarts.baidu.com/demo.html#mix-timeline-finance可以做成这种效果？这个里面用的是类目轴。类目轴也可以让这些数据倾斜角度，以全部显示，可见xAxis里面的axisLabel的rotate和interval。
如果你不是类目轴的话，用xAxis里面的axisLabel的formatter，每到第二个就加一个\n，应该是可以的

**Comment by sevenen** [comment]
貌似链接打不开，就是echarts3--作品--官方示例--柱状图--2002全国经济宏观指标
