### ISSUE TITLE
坐标轴为小数时存在bug

### ISSUE THREAD

**Issue by swxs** [ecomfe/echarts#4939]
### One-line summary [问题简述]

坐标轴为小数时存在float相关问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
            yAxis: {
                type: 'value',
                boundaryGap: [0, '20%'],
                axisTick:{
                    show:false
                },
                axisLine:{
                    show:false
                },
            },
}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/18203761/21972424/72ba6820-dbf4-11e6-813c-13b6011e7988.png)

**Comment by basequatro** [comment]
can we use price on yAxis?
with float type: 9.999,99

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#xAxis.axisLabel.formatter
