### ISSUE TITLE
Bar width rendered differently in the 3.4.0 release

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#4943]
Seems like bar width is rendered differently in the 3.4.0 release, I'm using this sample code: 

```
{
    color: ['#3398DB'],
    grid: {
        width:100,
        height:100
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            type:'bar',
            barWidth: '100%',
            data:[10]
        }
    ]
}
```

which renders differently in 3.3.2 & 3.4.0:
![image](https://cloud.githubusercontent.com/assets/561365/21982706/f2156dba-dbed-11e6-8f3e-1c9b4580b0de.png)

Is this a bug or feature?

**Comment by psumstr** [comment]
@jarben Looks like they changed the rendering of the category axis. From the changelog:
**[+] category axis has been changed to show all categories by default, in spite of whether there is data in categories. In the past, categories in the end that has no data will not be displayed.**

**Comment by jarben** [comment]
Thanks @psumstr for pointing out this change. Makes sense, might be useful to have a setting for this so the old behavior can be used as well?

**Comment by psumstr** [comment]
@jarben Yes, I think it would be useful to have both options. The new default is good for time series data where you may want to show all axis labels for say, Month names, but there may be months with no data. I've seen cases where users want to omit those null categories, so having both would be great.

**Comment by 100pah** [comment]
@jarben @psumstr The old behavior can be obtained by setting like this:

```js
xAxis: {
    type: 'category',
    data: [ ... ],
    min: 'dataMin',
    max: 'dataMax'
}
```

**Comment by jarben** [comment]
Sounds good, thanks @100pah !
