### ISSUE TITLE
Error: Cannot read property 'eachItemGraphicEl' of undefined 

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#4944]
Version: 3.4.0

This error shows when pointer:{show:false} is used: 

```
option = {
    series: [
        {
            type: 'gauge',
            pointer:{
                show:false
            },
            detail: {formatter:'{value}%'},
            data: [{value: 50, name: '完成率'}]
        }
    ]
};
```
![image](https://cloud.githubusercontent.com/assets/561365/21983268/b21ff718-dbf0-11e6-93f8-026241efbb97.png)

**Comment by xuchaobei** [comment]
I also meet this issue after upgrading to version 3.4.0.
