### ISSUE TITLE
Load csv file Example

### ISSUE THREAD

**Issue by suntong** [ecomfe/echarts#4945]
Can't reopen 

- https://github.com/ecomfe/echarts/issues/2271
- or https://github.com/ecomfe/echarts/issues/4834

So I'm opening another one. 

I know the answer to them is http://gallery.echartsjs.com/editor.html?c=xrJDKzwZQ, however there are several problems with it. 

First, I can't duplicate that example into my own environment. Please take a look at the file (and its history) https://github.com/suntong/lang/blob/master/lang/Charts/ECharts/echarts_LoadCSV_1.html, 

I'm getting the following error:

echarts_LoadCSV_1.html:37 Uncaught ReferenceError: $ is not defined(anonymous function) @ echarts_LoadCSV_1.html:37

So it only works in gallery.echartsjs.com but not in my own environment. How can I fix it? 

Second, I'm still not quite sure how to use the csv file loading function, because I'm not a JavaScript programmer. For e.g., I'm trying to convert [this echarts_Multiple-Sub-Groups-Bar-Chart_1 file](https://github.com/suntong/lang/blob/master/lang/Charts/ECharts/echarts_Multiple-Sub-Groups-Bar-Chart_1.html) to [echarts_Multiple-Sub-Groups-Bar-Chart_2](https://github.com/suntong/lang/blob/master/lang/Charts/ECharts/echarts_Multiple-Sub-Groups-Bar-Chart_2.html), but got really stuck. 

I.e., could you show us how to load csv file into a variable please? I.e., fixing the following line:

`var dummy = GetFromCVS(dataURL)
`

PS. I appreciate if you can make [echarts_Multiple-Sub-Groups-Bar-Chart_2](https://github.com/suntong/lang/blob/master/lang/Charts/ECharts/echarts_Multiple-Sub-Groups-Bar-Chart_2.html) a fully working example as I'm not a JavaScript programmer so it's very hard for me to do it. Also, the code currently only handle two columns/bars, however the csv files has more. if you can make it dynamic according to the data available in the csv files, that'd be even more appreciated.

And finally, the reason I'm asking to make  [echarts_Multiple-Sub-Groups-Bar-Chart_2](https://github.com/suntong/lang/blob/master/lang/Charts/ECharts/echarts_Multiple-Sub-Groups-Bar-Chart_2.html) a fully working example, is because normally we would uses csv columns as-is. I.e., I know the following is very advanced and useful, 

`data: calculateMA(5, data),
`

however, when it comes to using csv columns as-is, the mostly widely use case, I still have no idea. 

Thanks a lot

**Comment by suntong** [comment]
PS. 

Knowing how to load csv file into a variable is vitally important to me, as most examples in  http://echarts.baidu.com/demo.html are _not_ written in same the way as using `$.get()`. I.e., it seems to me that they need rather major overhaul to make them working with `$.get()` than to deal with local data, populated from csv file.

**Comment by 100pah** [comment]
`$` represents [jQuery](http://jquery.com/). Because using global variable `$` to represent `jQuery` is a well-known habit among JavaScript programmers in the past, we do not make explanation for that. 

About <https://github.com/suntong/lang/blob/master/lang/Charts/ECharts/echarts_LoadCSV_1.html>, I think you need to import `jQuery` for using AJAX, and import [papaparse](http://papaparse.com/) to parse CSV to JavaScript Object. Both `jQuery` and `papaparse` is used in <http://gallery.echartsjs.com/editor.html?c=xrJDKzwZQ>.

**Comment by suntong** [comment]
Yep, that works. Thanks!
