### ISSUE TITLE
Adding dataZoom to the 蒸发量和降水量 demo

### ISSUE THREAD

**Issue by suntong** [ecomfe/echarts#4946]
I am trying to add dataZoom to the [蒸发量和降水量 demo](http://echarts.baidu.com/demo.html#bar1)
http://echarts.baidu.com/demo.html#bar1

I just put the following after `yAxis: {},`
```
        dataZoom: [
            {
                show: true
            },
            {
                type: 'inside'
            },

```

and the chart stops working, with the many errors including:

```
SyntaxError: Invalid or unexpected token(…)run @ editor.js:346
editor.js:346 SyntaxError: Unexpected token :(…)run @ editor.js:346
```

etc. 

How to make it works, adding dataZoom to bar charts? 

Thanks

**Comment by pissang** [comment]
I think error is from your code.

Maybe you forgot to add `]`, like following:

```js
dataZoom: [
            {
                show: true
            },
            {
                type: 'inside'
            }
```

**Comment by suntong** [comment]
Ops, sorry, my bad. Yep, that works.
