### ISSUE TITLE
tooltip not show in parallel

### ISSUE THREAD

**Issue by Asens** [ecomfe/echarts#4955]
http://echarts.baidu.com/demo.html#parallel-aqi

i see you write tooltip in option,but when i put my mouse on it,it doesn't show,
is that a problem
hope for a response

**Comment by 100pah** [comment]
`parallel series` does not support `tooltip` currently. We have not thought it completely through how to trigger tooltip when mouse on it, considering there are so many "thin" lines. But we have planned to make it clear and add support for tooltip soon.

**Comment by Asens** [comment]
thanks,i'm looking forward to it,you did exellent work of echart 
@100pah
