### ISSUE TITLE
IE8下使用缩放功能，折线图超出图表区域

### ISSUE THREAD

**Issue by cdoneshot** [ecomfe/echarts#4958]
### One-line summary [问题简述]

IE8下初始展示正常，拖动X轴缩放，折线图超出图表区域

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.x
+ Browser version [浏览器类型和版本]:
 ie8
+ OS Version [操作系统类型和版本]:

win7x64

### Expected behaviour [期望结果]

正常展示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/20412044/22047190/71f27460-dd60-11e6-8604-7b00b178b837.png)

![image](https://cloud.githubusercontent.com/assets/20412044/22047210/952cb332-dd60-11e6-9dfd-1ddfb28898d5.png)

**Comment by pissang** [comment]
可以设置 `animation: false` 关闭动画
