### ISSUE TITLE
技术文档中关于 legend 的配置是一个描述问题

### ISSUE THREAD

**Issue by RRDAWLX** [ecomfe/echarts#4959]
![image](https://cloud.githubusercontent.com/assets/8463678/22049958/d8d8715a-dd71-11e6-9f64-18c5124e3032.png)
图中红框里的说明有语病，没有准确描述相关配置，会给人造成误解，至少我在开发过程中被坑了。
个人认为更好的描述应该是这样的：图例组件会自动根据对应系列的图形标记（symbol）来绘制自己的颜色和标记。

**Comment by pissang** [comment]
赞！谢谢建议
