### ISSUE TITLE
Tooltip multiple X-axis 

### ISSUE THREAD

**Issue by akansal1** [ecomfe/echarts#4963]
Tooltip only showing option for base x-axis and not the secondary x-axis

**Comment by piyushgupta1** [comment]
+1

**Comment by lvming0535** [comment]
+1

**Comment by linweiwei123** [comment]
Echarts do not support more than 2 x-axis.  but Highcharts did .see this [http://fiddle.jshell.net/v7hj14pu/1/](url)

**Comment by pissang** [comment]
@linweiwei123 ECharts supported more than 2 xAxis and yAxis since 3.2.0

**Comment by linweiwei123** [comment]
@pissang Thank you very much! It's very helpful for me!
