### ISSUE TITLE
漏斗图问题，sort排序问题，可不可以不排序，按照data数据先后排序？

### ISSUE THREAD

**Issue by sptrs** [ecomfe/echarts#4966]
我们的数据展示是按照data数据先后排序的，但是echarts是按照数据量正序或倒序排序，怎么改进？

**Comment by sptrs** [comment]
查看hcharts漏斗图是可以按照data数据排序的，echarts啥时候改进呀

**Comment by 100pah** [comment]
Fixed in 6736f98aa51603d750f265e838651659d47786d6
