### ISSUE TITLE
echarts柱状图的柱子可以自定义成一株小草吗？

### ISSUE THREAD

**Issue by FrankKai** [ecomfe/echarts#4967]
### One-line summary [问题简述]
柱状图目前只是单一的柱子，我想把它换成一些其他形状的图案可以吗？比如说小麦穗，小草等等

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
最新版本可以使用象形柱图，参考 http://echarts.baidu.com/demo.html#pictorialBar-forest
