### ISSUE TITLE
resize调用报错

### ISSUE THREAD

**Issue by baolong520** [ecomfe/echarts#4973]
### One-line summary [问题简述]

在chrome 下， 使用react parent resize的时候使用 echarts.resize()报错

### Version & Environment [版本及环境]
+ ECharts version [3.4.0]:
+ Browser version [chrome-55]:
+ OS Version [windows]:

### ECharts option [ECharts配置项]

```javascript
option ={
"grid":[
{
"left":52,
"right":52,
"bottom":10,
"top":15
}
],
"tooltip":{
"show":true,
"triggerOn":"none",
"trigger":"axis",
"axisPointer":{
"animation":true,
"type":"cross",
"axis":"x",
"crossStyle":{
"width":1,
"color":"transparent",
"type":"solid",
"textStyle":{
"color":"transparent"
}
}
}
},
"xAxis":{
"type":"category",
"scale":true,
"max":"15:15",
"min":"09:15",
"axisTick":{
"show":false
},
"axisLabel":{
"show":false,
"textStyle":{
"color":"#ffebc8"
}
},
"data":[
"09:15",
"09:16",
"09:17",
"09:18",
"09:19",
"09:20",
"09:21",
"09:22",
"09:23",
"09:24",
"09:25",
"09:26",
"09:27",
"09:28",
"09:29",
"09:30",
"09:31",
"09:32",
"09:33",
"09:34",
"09:35",
"09:36",
"09:37",
"09:38",
"09:39",
"09:40",
"09:41",
"09:42",
"09:43",
"09:44",
"09:45",
"09:46",
"09:47",
"09:48",
"09:49",
"09:50",
"09:51",
"09:52",
"09:53",
"09:54",
"09:55",
"09:56",
"09:57",
"09:58",
"09:59",
"10:00",
"10:01",
"10:02",
"10:03",
"10:04",
"10:05",
"10:06",
"10:07",
"10:08",
"10:09",
"10:10",
"10:11",
"10:12",
"10:13",
"10:14",
"10:15",
"10:16",
"10:17",
"10:18",
"10:19",
"10:20",
"10:21",
"10:22",
"10:23",
"10:24",
"10:25",
"10:26",
"10:27",
"10:28",
"10:29",
"10:30",
"10:31",
"10:32",
"10:33",
"10:34",
"10:35",
"10:36",
"10:37",
"10:38",
"10:39",
"10:40",
"10:41",
"10:42",
"10:43",
"10:44",
"10:45",
"10:46",
"10:47",
"10:48",
"10:49",
"10:50",
"10:51",
"10:52",
"10:53",
"10:54",
"10:55",
"10:56",
"10:57",
"10:58",
"10:59",
"11:00",
"11:01",
"11:02",
"11:03",
"11:04",
"11:05",
"11:06",
"11:07",
"11:08",
"11:09",
"11:10",
"11:11",
"11:12",
"11:13",
"11:14",
"11:15",
"11:16",
"11:17",
"11:18",
"11:19",
"11:20",
"11:21",
"11:22",
"11:23",
"11:24",
"11:25",
"11:26",
"11:27",
"11:28",
"11:29",
"11:30",
"13:00",
"13:01",
"13:02",
"13:03",
"13:04",
"13:05",
"13:06",
"13:07",
"13:08",
"13:09",
"13:10",
"13:11",
"13:12",
"13:13",
"13:14",
"13:15",
"13:16",
"13:17",
"13:18",
"13:19",
"13:20",
"13:21",
"13:22",
"13:23",
"13:24",
"13:25",
"13:26",
"13:27",
"13:28",
"13:29",
"13:30",
"13:31",
"13:32",
"13:33",
"13:34",
"13:35",
"13:36",
"13:37",
"13:38",
"13:39",
"13:40",
"13:41",
"13:42",
"13:43",
"13:44",
"13:45",
"13:46",
"13:47",
"13:48",
"13:49",
"13:50",
"13:51",
"13:52",
"13:53",
"13:54",
"13:55",
"13:56",
"13:57",
"13:58",
"13:59",
"14:00",
"14:01",
"14:02",
"14:03",
"14:04",
"14:05",
"14:06",
"14:07",
"14:08",
"14:09",
"14:10",
"14:11",
"14:12",
"14:13",
"14:14",
"14:15",
"14:16",
"14:17",
"14:18",
"14:19",
"14:20",
"14:21",
"14:22",
"14:23",
"14:24",
"14:25",
"14:26",
"14:27",
"14:28",
"14:29",
"14:30",
"14:31",
"14:32",
"14:33",
"14:34",
"14:35",
"14:36",
"14:37",
"14:38",
"14:39",
"14:40",
"14:41",
"14:42",
"14:43",
"14:44",
"14:45",
"14:46",
"14:47",
"14:48",
"14:49",
"14:50",
"14:51",
"14:52",
"14:53",
"14:54",
"14:55",
"14:56",
"14:57",
"14:58",
"14:59",
"15:00",
"15:01",
"15:02",
"15:03",
"15:04",
"15:05",
"15:06",
"15:07",
"15:08",
"15:09",
"15:10",
"15:11",
"15:12",
"15:13",
"15:15"
],
"splitLine":{
"show":true,
"lineStyle":{
"color":"rgba(255, 255, 255, 0.1)"
}
}
},
"yAxis":[
{
"type":"value",
"name":"",
"min":99.335,
"splitNumber":9,
"nameTextStyle":{
"color":"#ccc5b7"
},
"axisTick":{
"show":false
},
"axisLabel":{
"textStyle":{
"fontSize":12,
"fontWeight":100
}
},
"splitLine":{
"show":true,
"lineStyle":{
"color":"rgba(255, 255, 255, 0.1)"
}
},
"max":99.745,
"interval":0.041,
"data":[
99.335,
99.37599999999999,
99.41699999999999,
99.458,
99.499,
99.53999999999999,
99.58099999999999,
99.622,
99.663
]
},
{
"type":"value",
"name":"",
"min":-0.205,
"splitNumber":9,
"nameTextStyle":{
"color":"#ccc5b7"
},
"axisTick":{
"show":false
},
"axisLine":{
"show":false
},
"axisLabel":{
"textStyle":{
"fontSize":12,
"fontWeight":100
}
},
"splitLine":{
"show":false,
"lineStyle":{
"color":"rgba(255, 255, 255, 0.1)"
}
},
"max":0.205,
"interval":0.041,
"data":[
-0.20594735784610457,
-0.16475788627688936,
-0.12356841470767417,
-0.08237894313844468,
-0.04118947156922948,
-1.4276526738197712e-14,
0.04118947156920093,
0.0823789431384304,
0.12356841470764561
]
}
],
"series":[
{
"name":"成交价格",
"type":"line",
"showSymbol":false,
"connectNulls":true,
"clipOverflow":false,
"animation":false,
"areaStyle":{
"normal":{
"color":{
"x":0,
"y":0,
"x2":0,
"y2":1,
"type":"linear",
"global":false,
"colorStops":[
{
"offset":0,
"color":"rgba(5, 62, 88, 1)"
},
{
"offset":1,
"color":"rgba(5, 30, 30, 0.1)"
}
]
}
}
},
"lineStyle":{
"normal":{
"width":1,
"color":"#7b8082"
}
},
"data":[
99.505,
99.505,
99.495,
99.495,
99.535,
99.53,
99.53,
99.535,
99.52,
99.485,
99.485,
99.48,
99.475,
99.47,
99.475,
99.45,
99.44,
99.425,
99.44,
99.425,
99.45,
99.455,
99.455,
99.44,
99.43,
99.445,
99.445,
99.445,
99.45,
99.47,
99.455,
99.46,
99.445,
99.445,
99.445,
99.44,
99.445,
99.445,
99.465,
99.475,
99.455,
99.45,
99.455,
99.46,
99.46,
99.46,
99.455,
99.44,
99.425,
99.425,
99.425,
99.43,
99.415,
99.395,
99.4,
99.4,
99.415,
99.41,
99.425,
99.42,
99.415,
99.425,
99.435,
99.425,
99.42,
99.42,
99.415,
99.405,
99.395,
99.395,
99.395,
99.405,
99.405,
99.395,
99.395,
99.39,
99.385,
99.4,
99.4,
99.405,
99.43,
99.435,
99.43,
99.435,
99.445,
99.46,
99.455,
99.445,
99.45,
99.45,
99.455,
99.45,
99.445,
99.45,
99.475,
99.46,
99.46,
99.465,
99.49,
99.485,
99.5,
99.5,
99.485,
99.47,
99.465,
99.47,
99.46,
99.455,
99.465,
99.465,
99.46,
99.455,
99.455,
99.465,
99.46,
99.46,
99.46,
99.47,
99.48,
99.455,
99.455,
99.465,
99.485,
99.475,
99.485,
99.485,
99.48,
99.47,
99.46,
99.47,
99.475,
99.485,
99.48,
99.48,
99.49,
99.49,
99.475,
99.47,
99.465,
99.47,
99.47,
99.47,
99.47,
99.48,
99.49,
99.485,
99.455,
99.445,
99.455,
99.455,
99.455,
99.46,
99.46,
99.46,
99.46,
99.465,
99.46,
99.455,
99.455,
99.465,
99.46,
99.465,
99.47,
99.47,
99.47,
99.47,
99.48,
99.48,
99.47,
99.465,
99.47,
99.465,
99.465,
99.465,
99.47,
99.47,
99.47,
99.475,
99.47,
99.47,
99.46,
99.45,
99.445,
99.45,
99.46,
99.45,
99.45,
99.455,
99.425,
99.445,
99.445,
99.445,
99.43,
99.435,
99.44,
99.43,
99.43,
99.435,
99.435,
99.455,
99.455,
99.47,
99.465,
99.465,
99.47,
99.46,
99.455,
99.455,
99.46,
99.46,
99.465,
99.455,
99.46,
99.46,
99.445,
99.445,
99.45,
99.45,
99.455,
99.455,
99.445,
99.445,
99.45,
99.465,
99.47,
99.465,
99.46,
99.45,
99.44,
99.445,
99.45,
99.45,
99.45,
99.45,
99.45,
99.455,
99.455,
99.46,
99.455,
99.45,
99.445,
99.44,
99.44,
99.435,
99.445,
99.45,
99.45,
99.44,
99.445,
99.44,
99.45,
99.445,
99.45,
99.445,
99.465,
99.455,
99.455,
99.465,
99.465,
99.46,
99.475,
99.465,
99.47,
99.47,
99.47,
99.465,
99.46,
99.465,
99.47,
99.465,
99.425
]
},
{
"name":"均线",
"type":"line",
"showSymbol":false,
"connectNulls":true,
"clipOverflow":false,
"animation":false,
"lineStyle":{
"normal":{
"width":1,
"color":"#ffc96c"
}
},
"data":[
99.4806,
99.4833908045977,
99.4844387755102,
99.48495145631068,
99.49406896551724,
99.5,
99.503925,
99.51226235741444,
99.51392491467577,
99.51103988603988,
99.50702702702702,
99.50371710526316,
99.50359170305677,
99.50295503211991,
99.50189834024896,
99.49910112359551,
99.49733212341198,
99.49378216123499,
99.49112479474549,
99.489704,
99.48804482225657,
99.48794298921418,
99.48771406727829,
99.48482319660538,
99.48405988857938,
99.48313351498638,
99.48291327913279,
99.4828108108108,
99.48200792602378,
99.48115728900255,
99.48080503144654,
99.4806625,
99.4795476477684,
99.47942908653846,
99.4792413381123,
99.477966396292,
99.4775114416476,
99.47725312145289,
99.47690423162584,
99.4766830601093,
99.47602212855638,
99.47581504702194,
99.47570166320166,
99.47535132382892,
99.47521717171718,
99.47521717171718,
99.47502,
99.47460137795275,
99.47218105065666,
99.4714404432133,
99.4714404432133,
99.47117889908257,
99.47007637017072,
99.46743534482759,
99.46621083827264,
99.4658207070707,
99.46484297520661,
99.46445036915505,
99.46381376518218,
99.46371163166397,
99.46253949447078,
99.46141321044547,
99.46045724907063,
99.46036323202372,
99.45915290739411,
99.45859319631467,
99.45811360448808,
99.45768080667594,
99.45731859018659,
99.45689087165408,
99.456448534424,
99.45572629455279,
99.45539438502674,
99.4548080741231,
99.45429461942257,
99.45374837451236,
99.4523518164436,
99.45188685208596,
99.45165512901195,
99.45145050125313,
99.4505749235474,
99.45018540669857,
99.4500742721331,
99.4497691408533,
99.44965222348917,
99.44978260869566,
99.44982271468145,
99.44987424822307,
99.44985838779957,
99.44986133768353,
99.44987804878049,
99.44988095238095,
99.44987041036717,
99.44987055016182,
99.45000267094017,
99.45016483516484,
99.45018537859008,
99.45019311064718,
99.45136868686869,
99.45154348919054,
99.45200895077076,
99.4523877651702,
99.45296350364964,
99.45317808880309,
99.45331578947368,
99.45339523809524,
99.45342267552182,
99.45343160377358,
99.45344941176471,
99.45349391955098,
99.4535229911751,
99.45356581986144,
99.45356912442396,
99.45358030372756,
99.4535979807251,
99.4535979807251,
99.4535979807251,
99.45365692096848,
99.45384841628959,
99.45390085240018,
99.45391867739053,
99.45396850044365,
99.4542247043364,
99.45470461405779,
99.45482632933104,
99.45490162532079,
99.45491235570756,
99.45502547770701,
99.45513689974726,
99.45518479630407,
99.45532554257095,
99.45543830494391,
99.45558192323566,
99.45559199669967,
99.45578278688525,
99.45578278688525,
99.45590538336052,
99.4559593495935,
99.45598377281948,
99.45602387697288,
99.45602387697288,
99.45604082457558,
99.45606176826807,
99.45607906413876,
99.45623595505619,
99.45673930269413,
99.45681960784314,
99.45680631332814,
99.45679681429681,
99.4567947225456,
99.45678281068525,
99.45678778507924,
99.45678902627512,
99.45678902627512,
99.45679026651217,
99.45679976851852,
99.45680592991914,
99.45680161166538,
99.45680390654921,
99.45681331293038,
99.45668615616748,
99.45669053901244,
99.45672057164347,
99.45672556390977,
99.45672556390977,
99.4567305524239,
99.45686519790888,
99.45686519790888,
99.45688362551287,
99.45688665175243,
99.45689153932166,
99.45690360997395,
99.45690662202381,
99.4569126394052,
99.45691750278706,
99.45691750278706,
99.4569272187152,
99.4569673953316,
99.4569770455387,
99.4569770455387,
99.45698336414048,
99.4568526622903,
99.45683970856102,
99.45676778620441,
99.45675062972292,
99.45674209770115,
99.45673967684021,
99.45673780487805,
99.45628969654199,
99.45617997198879,
99.45614659685864,
99.45613509749303,
99.45602772963605,
99.45595369730476,
99.45589876033058,
99.45588265657261,
99.4557938957476,
99.45571233344721,
99.45566927792916,
99.45561590524535,
99.45561086736416,
99.45572381587725,
99.45588507265522,
99.4558880818752,
99.45590774299835,
99.45592950819672,
99.45592768324607,
99.45592616791897,
99.45593983739838,
99.45594774423888,
99.45595724003887,
99.45595954692557,
99.45595961227787,
99.45596352485474,
99.45586664534697,
99.45585062240664,
99.45582457815982,
99.45582087177856,
99.45582061068703,
99.45582061068703,
99.45581162642948,
99.45580133291018,
99.45579765302887,
99.45580537974683,
99.4558322804801,
99.45583806818182,
99.45584200567644,
99.45583071113909,
99.45576862867877,
99.45569492053599,
99.45566480273376,
99.45566128531512,
99.45565075921908,
99.45564565956133,
99.45563213074314,
99.45561635413465,
99.4556110260337,
99.45561162079511,
99.45561031431187,
99.45560310691441,
99.45558376406203,
99.45542293798917,
99.45532745215311,
99.4552728899493,
99.4552561811141,
99.45524546265992,
99.45524546265992,
99.45523639607494,
99.45520919881305,
99.45516233766234,
99.45508031542056,
99.45505096097845,
99.45502898550724,
99.45501876985273,
99.4550401836969,
99.4550414997138,
99.4550414641121,
99.45508250355618,
99.45510085227272,
99.45511611441518,
99.45523729289525,
99.45536541143655,
99.45539393095768,
99.4554602162462,
99.45549060254284,
99.45563461538461,
99.4556471072114,
99.45564967105263,
99.45567076502732,
99.45575889220744,
99.45578444564048
]
}
]
}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/4034957/22098774/1baedf18-de63-11e6-9af1-e6922ac32dcd.png)

**Comment by pissang** [comment]
有具体的复现代码么？

**Comment by baolong520** [comment]
{
"grid":[
{
"left":52,
"right":52,
"bottom":10,
"top":15
}
],
"tooltip":{
"show":true,
"triggerOn":"none",
"trigger":"axis",
"axisPointer":{
"animation":true,
"type":"cross",
"axis":"x",
"crossStyle":{
"width":1,
"color":"transparent",
"type":"solid",
"textStyle":{
"color":"transparent"
}
}
}
},
"xAxis":{
"type":"category",
"scale":true,
"max":"15:15",
"min":"09:15",
"axisTick":{
"show":false
},
"axisLabel":{
"show":false,
"textStyle":{
"color":"#ffebc8"
}
},
"data":[
"09:15",
"09:16",
"09:17",
"09:18",
"09:19",
"09:20",
"09:21",
"09:22",
"09:23",
"09:24",
"09:25",
"09:26",
"09:27",
"09:28",
"09:29",
"09:30",
"09:31",
"09:32",
"09:33",
"09:34",
"09:35",
"09:36",
"09:37",
"09:38",
"09:39",
"09:40",
"09:41",
"09:42",
"09:43",
"09:44",
"09:45",
"09:46",
"09:47",
"09:48",
"09:49",
"09:50",
"09:51",
"09:52",
"09:53",
"09:54",
"09:55",
"09:56",
"09:57",
"09:58",
"09:59",
"10:00",
"10:01",
"10:02",
"10:03",
"10:04",
"10:05",
"10:06",
"10:07",
"10:08",
"10:09",
"10:10",
"10:11",
"10:12",
"10:13",
"10:14",
"10:15",
"10:16",
"10:17",
"10:18",
"10:19",
"10:20",
"10:21",
"10:22",
"10:23",
"10:24",
"10:25",
"10:26",
"10:27",
"10:28",
"10:29",
"10:30",
"10:31",
"10:32",
"10:33",
"10:34",
"10:35",
"10:36",
"10:37",
"10:38",
"10:39",
"10:40",
"10:41",
"10:42",
"10:43",
"10:44",
"10:45",
"10:46",
"10:47",
"10:48",
"10:49",
"10:50",
"10:51",
"10:52",
"10:53",
"10:54",
"10:55",
"10:56",
"10:57",
"10:58",
"10:59",
"11:00",
"11:01",
"11:02",
"11:03",
"11:04",
"11:05",
"11:06",
"11:07",
"11:08",
"11:09",
"11:10",
"11:11",
"11:12",
"11:13",
"11:14",
"11:15",
"11:16",
"11:17",
"11:18",
"11:19",
"11:20",
"11:21",
"11:22",
"11:23",
"11:24",
"11:25",
"11:26",
"11:27",
"11:28",
"11:29",
"11:30",
"13:00",
"13:01",
"13:02",
"13:03",
"13:04",
"13:05",
"13:06",
"13:07",
"13:08",
"13:09",
"13:10",
"13:11",
"13:12",
"13:13",
"13:14",
"13:15",
"13:16",
"13:17",
"13:18",
"13:19",
"13:20",
"13:21",
"13:22",
"13:23",
"13:24",
"13:25",
"13:26",
"13:27",
"13:28",
"13:29",
"13:30",
"13:31",
"13:32",
"13:33",
"13:34",
"13:35",
"13:36",
"13:37",
"13:38",
"13:39",
"13:40",
"13:41",
"13:42",
"13:43",
"13:44",
"13:45",
"13:46",
"13:47",
"13:48",
"13:49",
"13:50",
"13:51",
"13:52",
"13:53",
"13:54",
"13:55",
"13:56",
"13:57",
"13:58",
"13:59",
"14:00",
"14:01",
"14:02",
"14:03",
"14:04",
"14:05",
"14:06",
"14:07",
"14:08",
"14:09",
"14:10",
"14:11",
"14:12",
"14:13",
"14:14",
"14:15",
"14:16",
"14:17",
"14:18",
"14:19",
"14:20",
"14:21",
"14:22",
"14:23",
"14:24",
"14:25",
"14:26",
"14:27",
"14:28",
"14:29",
"14:30",
"14:31",
"14:32",
"14:33",
"14:34",
"14:35",
"14:36",
"14:37",
"14:38",
"14:39",
"14:40",
"14:41",
"14:42",
"14:43",
"14:44",
"14:45",
"14:46",
"14:47",
"14:48",
"14:49",
"14:50",
"14:51",
"14:52",
"14:53",
"14:54",
"14:55",
"14:56",
"14:57",
"14:58",
"14:59",
"15:00",
"15:01",
"15:02",
"15:03",
"15:04",
"15:05",
"15:06",
"15:07",
"15:08",
"15:09",
"15:10",
"15:11",
"15:12",
"15:13",
"15:15"
],
"splitLine":{
"show":true,
"lineStyle":{
"color":"rgba(255, 255, 255, 0.1)"
}
}
},
"yAxis":[
{
"type":"value",
"name":"",
"min":99.335,
"splitNumber":9,
"nameTextStyle":{
"color":"#ccc5b7"
},
"axisTick":{
"show":false
},
"axisLabel":{
"textStyle":{
"fontSize":12,
"fontWeight":100
}
},
"splitLine":{
"show":true,
"lineStyle":{
"color":"rgba(255, 255, 255, 0.1)"
}
},
"max":99.745,
"interval":0.041,
"data":[
99.335,
99.37599999999999,
99.41699999999999,
99.458,
99.499,
99.53999999999999,
99.58099999999999,
99.622,
99.663
]
},
{
"type":"value",
"name":"",
"min":-0.205,
"splitNumber":9,
"nameTextStyle":{
"color":"#ccc5b7"
},
"axisTick":{
"show":false
},
"axisLine":{
"show":false
},
"axisLabel":{
"textStyle":{
"fontSize":12,
"fontWeight":100
}
},
"splitLine":{
"show":false,
"lineStyle":{
"color":"rgba(255, 255, 255, 0.1)"
}
},
"max":0.205,
"interval":0.041,
"data":[
-0.20594735784610457,
-0.16475788627688936,
-0.12356841470767417,
-0.08237894313844468,
-0.04118947156922948,
-1.4276526738197712e-14,
0.04118947156920093,
0.0823789431384304,
0.12356841470764561
]
}
],
"series":[
{
"name":"成交价格",
"type":"line",
"showSymbol":false,
"connectNulls":true,
"clipOverflow":false,
"animation":false,
"areaStyle":{
"normal":{
"color":{
"x":0,
"y":0,
"x2":0,
"y2":1,
"type":"linear",
"global":false,
"colorStops":[
{
"offset":0,
"color":"rgba(5, 62, 88, 1)"
},
{
"offset":1,
"color":"rgba(5, 30, 30, 0.1)"
}
]
}
}
},
"lineStyle":{
"normal":{
"width":1,
"color":"#7b8082"
}
},
"data":[
99.505,
99.505,
99.495,
99.495,
99.535,
99.53,
99.53,
99.535,
99.52,
99.485,
99.485,
99.48,
99.475,
99.47,
99.475,
99.45,
99.44,
99.425,
99.44,
99.425,
99.45,
99.455,
99.455,
99.44,
99.43,
99.445,
99.445,
99.445,
99.45,
99.47,
99.455,
99.46,
99.445,
99.445,
99.445,
99.44,
99.445,
99.445,
99.465,
99.475,
99.455,
99.45,
99.455,
99.46,
99.46,
99.46,
99.455,
99.44,
99.425,
99.425,
99.425,
99.43,
99.415,
99.395,
99.4,
99.4,
99.415,
99.41,
99.425,
99.42,
99.415,
99.425,
99.435,
99.425,
99.42,
99.42,
99.415,
99.405,
99.395,
99.395,
99.395,
99.405,
99.405,
99.395,
99.395,
99.39,
99.385,
99.4,
99.4,
99.405,
99.43,
99.435,
99.43,
99.435,
99.445,
99.46,
99.455,
99.445,
99.45,
99.45,
99.455,
99.45,
99.445,
99.45,
99.475,
99.46,
99.46,
99.465,
99.49,
99.485,
99.5,
99.5,
99.485,
99.47,
99.465,
99.47,
99.46,
99.455,
99.465,
99.465,
99.46,
99.455,
99.455,
99.465,
99.46,
99.46,
99.46,
99.47,
99.48,
99.455,
99.455,
99.465,
99.485,
99.475,
99.485,
99.485,
99.48,
99.47,
99.46,
99.47,
99.475,
99.485,
99.48,
99.48,
99.49,
99.49,
99.475,
99.47,
99.465,
99.47,
99.47,
99.47,
99.47,
99.48,
99.49,
99.485,
99.455,
99.445,
99.455,
99.455,
99.455,
99.46,
99.46,
99.46,
99.46,
99.465,
99.46,
99.455,
99.455,
99.465,
99.46,
99.465,
99.47,
99.47,
99.47,
99.47,
99.48,
99.48,
99.47,
99.465,
99.47,
99.465,
99.465,
99.465,
99.47,
99.47,
99.47,
99.475,
99.47,
99.47,
99.46,
99.45,
99.445,
99.45,
99.46,
99.45,
99.45,
99.455,
99.425,
99.445,
99.445,
99.445,
99.43,
99.435,
99.44,
99.43,
99.43,
99.435,
99.435,
99.455,
99.455,
99.47,
99.465,
99.465,
99.47,
99.46,
99.455,
99.455,
99.46,
99.46,
99.465,
99.455,
99.46,
99.46,
99.445,
99.445,
99.45,
99.45,
99.455,
99.455,
99.445,
99.445,
99.45,
99.465,
99.47,
99.465,
99.46,
99.45,
99.44,
99.445,
99.45,
99.45,
99.45,
99.45,
99.45,
99.455,
99.455,
99.46,
99.455,
99.45,
99.445,
99.44,
99.44,
99.435,
99.445,
99.45,
99.45,
99.44,
99.445,
99.44,
99.45,
99.445,
99.45,
99.445,
99.465,
99.455,
99.455,
99.465,
99.465,
99.46,
99.475,
99.465,
99.47,
99.47,
99.47,
99.465,
99.46,
99.465,
99.47,
99.465,
99.425
]
},
{
"name":"均线",
"type":"line",
"showSymbol":false,
"connectNulls":true,
"clipOverflow":false,
"animation":false,
"lineStyle":{
"normal":{
"width":1,
"color":"#ffc96c"
}
},
"data":[
99.4806,
99.4833908045977,
99.4844387755102,
99.48495145631068,
99.49406896551724,
99.5,
99.503925,
99.51226235741444,
99.51392491467577,
99.51103988603988,
99.50702702702702,
99.50371710526316,
99.50359170305677,
99.50295503211991,
99.50189834024896,
99.49910112359551,
99.49733212341198,
99.49378216123499,
99.49112479474549,
99.489704,
99.48804482225657,
99.48794298921418,
99.48771406727829,
99.48482319660538,
99.48405988857938,
99.48313351498638,
99.48291327913279,
99.4828108108108,
99.48200792602378,
99.48115728900255,
99.48080503144654,
99.4806625,
99.4795476477684,
99.47942908653846,
99.4792413381123,
99.477966396292,
99.4775114416476,
99.47725312145289,
99.47690423162584,
99.4766830601093,
99.47602212855638,
99.47581504702194,
99.47570166320166,
99.47535132382892,
99.47521717171718,
99.47521717171718,
99.47502,
99.47460137795275,
99.47218105065666,
99.4714404432133,
99.4714404432133,
99.47117889908257,
99.47007637017072,
99.46743534482759,
99.46621083827264,
99.4658207070707,
99.46484297520661,
99.46445036915505,
99.46381376518218,
99.46371163166397,
99.46253949447078,
99.46141321044547,
99.46045724907063,
99.46036323202372,
99.45915290739411,
99.45859319631467,
99.45811360448808,
99.45768080667594,
99.45731859018659,
99.45689087165408,
99.456448534424,
99.45572629455279,
99.45539438502674,
99.4548080741231,
99.45429461942257,
99.45374837451236,
99.4523518164436,
99.45188685208596,
99.45165512901195,
99.45145050125313,
99.4505749235474,
99.45018540669857,
99.4500742721331,
99.4497691408533,
99.44965222348917,
99.44978260869566,
99.44982271468145,
99.44987424822307,
99.44985838779957,
99.44986133768353,
99.44987804878049,
99.44988095238095,
99.44987041036717,
99.44987055016182,
99.45000267094017,
99.45016483516484,
99.45018537859008,
99.45019311064718,
99.45136868686869,
99.45154348919054,
99.45200895077076,
99.4523877651702,
99.45296350364964,
99.45317808880309,
99.45331578947368,
99.45339523809524,
99.45342267552182,
99.45343160377358,
99.45344941176471,
99.45349391955098,
99.4535229911751,
99.45356581986144,
99.45356912442396,
99.45358030372756,
99.4535979807251,
99.4535979807251,
99.4535979807251,
99.45365692096848,
99.45384841628959,
99.45390085240018,
99.45391867739053,
99.45396850044365,
99.4542247043364,
99.45470461405779,
99.45482632933104,
99.45490162532079,
99.45491235570756,
99.45502547770701,
99.45513689974726,
99.45518479630407,
99.45532554257095,
99.45543830494391,
99.45558192323566,
99.45559199669967,
99.45578278688525,
99.45578278688525,
99.45590538336052,
99.4559593495935,
99.45598377281948,
99.45602387697288,
99.45602387697288,
99.45604082457558,
99.45606176826807,
99.45607906413876,
99.45623595505619,
99.45673930269413,
99.45681960784314,
99.45680631332814,
99.45679681429681,
99.4567947225456,
99.45678281068525,
99.45678778507924,
99.45678902627512,
99.45678902627512,
99.45679026651217,
99.45679976851852,
99.45680592991914,
99.45680161166538,
99.45680390654921,
99.45681331293038,
99.45668615616748,
99.45669053901244,
99.45672057164347,
99.45672556390977,
99.45672556390977,
99.4567305524239,
99.45686519790888,
99.45686519790888,
99.45688362551287,
99.45688665175243,
99.45689153932166,
99.45690360997395,
99.45690662202381,
99.4569126394052,
99.45691750278706,
99.45691750278706,
99.4569272187152,
99.4569673953316,
99.4569770455387,
99.4569770455387,
99.45698336414048,
99.4568526622903,
99.45683970856102,
99.45676778620441,
99.45675062972292,
99.45674209770115,
99.45673967684021,
99.45673780487805,
99.45628969654199,
99.45617997198879,
99.45614659685864,
99.45613509749303,
99.45602772963605,
99.45595369730476,
99.45589876033058,
99.45588265657261,
99.4557938957476,
99.45571233344721,
99.45566927792916,
99.45561590524535,
99.45561086736416,
99.45572381587725,
99.45588507265522,
99.4558880818752,
99.45590774299835,
99.45592950819672,
99.45592768324607,
99.45592616791897,
99.45593983739838,
99.45594774423888,
99.45595724003887,
99.45595954692557,
99.45595961227787,
99.45596352485474,
99.45586664534697,
99.45585062240664,
99.45582457815982,
99.45582087177856,
99.45582061068703,
99.45582061068703,
99.45581162642948,
99.45580133291018,
99.45579765302887,
99.45580537974683,
99.4558322804801,
99.45583806818182,
99.45584200567644,
99.45583071113909,
99.45576862867877,
99.45569492053599,
99.45566480273376,
99.45566128531512,
99.45565075921908,
99.45564565956133,
99.45563213074314,
99.45561635413465,
99.4556110260337,
99.45561162079511,
99.45561031431187,
99.45560310691441,
99.45558376406203,
99.45542293798917,
99.45532745215311,
99.4552728899493,
99.4552561811141,
99.45524546265992,
99.45524546265992,
99.45523639607494,
99.45520919881305,
99.45516233766234,
99.45508031542056,
99.45505096097845,
99.45502898550724,
99.45501876985273,
99.4550401836969,
99.4550414997138,
99.4550414641121,
99.45508250355618,
99.45510085227272,
99.45511611441518,
99.45523729289525,
99.45536541143655,
99.45539393095768,
99.4554602162462,
99.45549060254284,
99.45563461538461,
99.4556471072114,
99.45564967105263,
99.45567076502732,
99.45575889220744,
99.45578444564048
]
}
]
}

**Comment by baolong520** [comment]
option

**Comment by hb-bobo** [comment]
不要刚render就立马resize， 我加了个定时器就没问题，componentDidMount 调用就会报这个错
