### ISSUE TITLE
Echarts 2 - Legends overalp chart on resize

### ISSUE THREAD

**Issue by hsouto** [ecomfe/echarts#4976]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts2
+ Browser version [浏览器类型和版本]: Google Chrome Version 55.0.2883.87/ Firefox Version 50.1.0
+ OS Version [操作系统类型和版本]: -

Good Afternoon,
We are using echarts2 js to show a dashboard with multiple charts.
On our charts we are displaying the legend for the chart series docked on top left:

`legend: {
      x: 'left',
      y: 'top',
      orient: 'vertical',
      data: dataArr
     },`

Our expected behavior was that when the window was resized both legends and chart resized correctly.
When we resize the window, the legends will overlap the chart as seen below:
![image](https://cloud.githubusercontent.com/assets/25079527/22122143/671a2a64-de4c-11e6-8937-19e9d1c93678.png)

What can we do to prevent/solve this without having legends and charts on different containers?

**Comment by 100pah** [comment]
"Responsive" is not supported in echarts2. I hope <https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Responsive%20Mobile-End> can help you, if echarts3 can be used in  your application.
