### ISSUE TITLE
[改进建议]数据视图里textarea框，文本内容的位置没法控制

### ISSUE THREAD

**Issue by Thstone37** [ecomfe/echarts#4981]
文本位置无法精确控制，readonly:true的情况,能否改为表格形式！！！
![image](https://cloud.githubusercontent.com/assets/11756943/22140069/26871960-df25-11e6-8c00-c25cf76c668c.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#toolbox.feature.dataView.optionToContent

**Comment by duxy2002** [comment]
@pissang 假如用了optionToContent就不能拷贝里面的内容了？
