### ISSUE TITLE
echarts 重新加载,原数据还保留

### ISSUE THREAD

**Issue by lgh611** [ecomfe/echarts#4983]
### One-line summary [问题简述]

使用echarts插件,渲染到页面上,然后通过选项使图形重新发送ajax接口,但原数据还保留,无法渲染新的数据,使用了clear方法,以及设置setOption第二个参数为true都不起作用

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

能够渲染到新的数据

### ECharts option [ECharts配置项]

firstOption里面有配置option内容.
```javascript
var myChartsOne = echarts.init(document.getElementById('asset-chart'));
			myChartsOne.showLoading({text: 'loading...'});
			myChartsOne.clear();
			myChartsOne.setOption(firstOption,true);
			myChartsOne.hideLoading();
			window.onresize = myChartsOne.resize;
}




### Other comments [其他信息]
<!-- For example: Screenshot or Online demo -->
<!-- [例如，截图或线上实例 (JSFiddle/JSBin/Codepen)] -->

**Comment by pissang** [comment]
你确定不是你新设置的数据还保留了原先的数据？
