### ISSUE TITLE
用meteor开发，引用china.js,不知道路径怎么写。

### ISSUE THREAD

**Issue by jsspace** [ecomfe/echarts#4985]
用meteor开发，引用china.js,不知道路径怎么写。

已知，const echarts = require('echarts');

那么china.js怎么引用啊。。。求解，谢谢

**Comment by pissang** [comment]
`require('echarts/map/js/china')` ？

**Comment by jsspace** [comment]
恩，对着呢，谢谢啦。

**Comment by ppker** [comment]
666
