### ISSUE TITLE
树图中itemStyle>label>formatter无效

### ISSUE THREAD

**Issue by siliu3** [ecomfe/echarts#4988]
### One-line summary [问题简述]
树图中itemStyle>label>formatter好像没用，
在官网给的例子中：
http://echarts.baidu.com/echarts2/doc/example/tree1.html
【小米2】节点，修改formatter，没有任何效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts-2.2.7
+ Browser version [浏览器类型和版本]: 
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
echarts 2 不继续升级了。可以尝试 echarts 3 里的 treemap.
