### ISSUE TITLE
textStyle中设置fontSize参数小于12时无效

### ISSUE THREAD

**Issue by pslean** [ecomfe/echarts#4991]
### One-line summary [问题简述]
textStyle中设置fontSize参数小于12时无效

### Version & Environment [版本及环境]
+ECharts version：3.4.0
+Browser version：55.0.2883.87 m (64-bit)
+OS Version：windows10

### ECharts option [ECharts配置项]
tooltip: {
      trigger: 'axis',
      textStyle: {
        fontSize: 8
      }
    }

```




### Other comments [其他信息]
8px的字体，实际是12px

**Comment by pissang** [comment]
chrome 限制最小字体为 12px
