### ISSUE TITLE
seriesIndex in showtip event not correct

### ISSUE THREAD

**Issue by zombieJ** [ecomfe/echarts#4999]
### One-line summary [问题简述]
为stack area图注册showtip事件，获取的seriesIndex永远为固定值。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: chrome 55
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
seriesIndex为对应series的Index

### ECharts option [ECharts配置项]
Ref: [jsfiddle](https://jsfiddle.net/26g1h27k/)

**Comment by zombieJ** [comment]
@pissang, pls take a look

**Comment by pissang** [comment]
嗯，因为 trigger 是 axis，所以显示的所有系列合并的 tooltip，至于 seriesIndex 这里取得是其中最后一个系列的 index，所以每次都是相同的

**Comment by zombieJ** [comment]
@pissang 那现行的配置中有什么办法可以获取到hover的series，还是说自己实现一个tooltip模拟合并的数据展示？
