### ISSUE TITLE
关于echarts map中，县级地图乡镇区域的制作问题

### ISSUE THREAD

**Issue by 28033692** [ecomfe/echarts#5002]
你们好！
1、我想制作一个县级地图，里面有乡镇街道的区域，但是echarts官网上只有分区域到县级的地图，没有到乡镇街道的地图，我要怎么去制作呢？
2、我观察了官网的源码，地图JS文件里面控制地图区域的是coordinates里面的内容，如果我要自己制作里面的内容，完借助什么工具？

**Comment by pissang** [comment]
echarts 地图支持 geoJSON 的格式，你只要能导出这个格式的地图文件就行了

**Comment by 28033692** [comment]
@pissang 你好，谢谢的回复。我要怎么到处这个格式的地图文件呢？？？用什么软件可以办到？？？我现在找了好多，网络上都没有乡镇地图数据。
