### ISSUE TITLE
类目y轴排序不正常？

### ISSUE THREAD

**Issue by pangniur** [ecomfe/echarts#5010]
echarts 3  学习例子是
http://gallery.echartsjs.com/editor.html?c=xSyKKAw97l
学习过程中遇到的问题在柱状图从上到下由多到少排列

![image](https://cloud.githubusercontent.com/assets/21232662/22593458/813c983c-ea59-11e6-8e52-e1ac2ce42721.png)

//data格式如下
var data = [
{
    "name": "United States of America",
    "value": [1025000, 31.222, "美国"]
}, {
    "name": "Russia",
    "value": [433412, 13.202, "俄国"]
}]

//按照官网例子中option做法

yAxis: {

        type: 'category',

        data: data.map(function(ele) {
            return ele.value[2]
        }).reverse()
    }
    
series:{

        id: 'bar',
        type: 'bar',

        data: data.map(function(ele) {
            return ele.value[0]
        }).sort(function(a, b) {
            return a > b
        })
    }
    

个人理解上述函数是，对类目数组进行了reverse，对类目数值进行了sort排序，但是两者好像无法对应？

反复观察官网例子的效果，可以排序正常
可是我本地测试的时候，
地图上数据正常
柱状图的值从上到下也从多到少排列正常
但是类目和值对应不上

///////////////
再次说明一下问题

问题1，官网例子有错没？
问题2，
柱状图，类目轴是动态获得的，类目和数值如何一起排序
不是类目写死，然后只排序数值 

//////////////////
是不是只能我排好序赋值给y轴 ？！

**Comment by pissang** [comment]
1. 官网例子没问题
2. 保证排序的时候类目和数值一一对应就行，这个做法有很多，可以找相关的 js 代码
