### ISSUE TITLE
echarts3中能不能实现Force-directed tree这种布局？应该怎么做？

### ISSUE THREAD

**Issue by cheechow** [ecomfe/echarts#5011]
### One-line summary [问题简述]
echarts3中能不能实现Force-directed tree这种布局？应该怎么做？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  echarts3.4.0
+ Browser version [浏览器类型和版本]:  chrome
+ OS Version [操作系统类型和版本]:  win8.1

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![force tree](https://cloud.githubusercontent.com/assets/20678798/22614799/7fe12016-eac2-11e6-9623-32e04fb5c199.JPG)

**Comment by sevenen** [comment]
可以用关系图实现。但是需要使用直角坐标系并给出每个点的坐标。不用坐标系的话，所有的点根据层次会形成一层一层的圆环形状，而不是现在的每一层都几乎在一条水平线上。http://echarts.baidu.com/option.html#series-graph

**Comment by fantaishao** [comment]
请问每个点的坐标系要做怎么计算出来才比较好看，目前是用的随机数，但是图的形状不固定，不大美观
