### ISSUE TITLE
visualMap 如何同时控制地图，柱状图，饼图三个图？

### ISSUE THREAD

**Issue by pangniur** [ecomfe/echarts#5014]
ECharts 3

![h8u3 _ lsgpstk 1 i f](https://cloud.githubusercontent.com/assets/21232662/22622914/fac213dc-eb83-11e6-8faf-64fb0828e2c2.png)

我有三个图，地图，柱状图和饼图 ， 因为地图和其他两个数据维度不同(柱状图和饼图是一维的)
所以visualMap  只能关联柱状图和饼图 ， 请问有什么方法可以同时让visual 同时控制三个图？

//data格式如下
var data=  [
    {
        "name": "United States",
        "value": [-95.712891,37.09024，1025000, "美国"]
    }, {
        "name": "Russia",
        "value": [105.318756,61.52401，433412, "俄国"]
    }]

series: [
         {  
            type:'scatter',
            coordinateSystem:'geo',
            data: data         //地图
          },
        {
            type: 'bar',
           data: data.map(function(ele) {
                return ele.value[2]     //柱状图
            })
        },
        {
            type: 'pie',
            data: data.map(function(ele) {
                return {
                    name: ele.value[4],
                    value: ele.value[2]          //饼图
                }
             }),
        }
]

**Comment by sevenen** [comment]
把你data里面的美国和1025000交换位置。然后visualMap里面的dimension不要赋值。就可以了

**Comment by pangniur** [comment]
@sevenen    按照你的说的试了试，地图和饼图可以控制了，但是柱状图还不行

![image](https://cloud.githubusercontent.com/assets/21232662/22633306/40a577c2-ec5b-11e6-80ab-40a59bd44aaa.png)

![image](https://cloud.githubusercontent.com/assets/21232662/22633335/7065d8f8-ec5b-11e6-9176-00d5b716d377.png)

**Comment by pangniur** [comment]
![image](https://cloud.githubusercontent.com/assets/21232662/22633381/d78a1454-ec5b-11e6-9028-f684b6b3c967.png)
![image](https://cloud.githubusercontent.com/assets/21232662/22633383/dc7390a8-ec5b-11e6-9b84-163afdbbbaf5.png)

**Comment by sevenen** [comment]
bar -- data 改为 [[1025000,'美国',1025000],[433412,'俄国',433412]] 这种格式

**Comment by pangniur** [comment]
sevenen  我qq是 2905185673     我们能不能直接聊下
