### ISSUE TITLE
echarts 图表pictorialBar报错问题

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#5016]
### One-line summary [问题简述]
根据echarts官网案例（http://gallery.echartsjs.com/editor.html?c=pictorialBar-dotted）改编的图表，直接在网上原代码上修改时，可以出现效果，但是自己引入react时，显示以下报错。
![image](https://cloud.githubusercontent.com/assets/22878190/22636452/3802d00e-ec76-11e6-8d9e-663dcf07bad1.png)

在网上原代码基础上修改版：
option = {
    backgroundColor: '#0f375f',
    tooltip: {
    },
    legend: {
      data: ['line', 'bar'],
      textStyle: {
        color: '#ccc',
      },
    },
    xAxis: {
      data: 'category',
      axisLine: {
        lineStyle: {
          color: '#ccc',
        },
      },
    },
    yAxis: {
      splitLine: { show: false },
      axisLine: {
        lineStyle: {
          color: '#ccc',
        },
      },
    },
    series: [{
      name: 'line',
      type: 'line',
      smooth: true,
      showAllSymbol: true,
      symbol: 'emptyCircle',
      symbolSize: 15,
      data: [4900000, 3700000, 4500000, 5200000, 4800000, 4200000, 5000000, 6000000, 5500000, 4600000, 4000000, 5600000],
    }, {
      name: 'bar',
      type: 'bar',
      barWidth: 10,
      itemStyle: {
        normal: {
          barBorderRadius: 5,
          color: new echarts.graphic.LinearGradient(
                    0, 0, 0, 1,
            [
                        { offset: 0, color: '#14c8d4' },
                        { offset: 1, color: '#43eec6' },
            ]
                ),
        },
      },
      data: [3300000, 2500000, 3000000, 1900000, 4200000, 3300000, 1600000, 800000, 3300000, 2800000, 1900000, 2200000],
    }, {
      name: 'line',
      type: 'bar',
      barGap: '-100%',
      barWidth: 10,
      itemStyle: {
        normal: {
          color: new echarts.graphic.LinearGradient(
                    0, 0, 0, 1,
            [
                        { offset: 0, color: 'rgba(20,200,212,0.5)' },
                        { offset: 0.2, color: 'rgba(20,200,212,0.2)' },
                        { offset: 1, color: 'rgba(20,200,212,0)' },
            ]
                ),
        },
      },
      z: -12,
      data: [4900000, 3700000, 4500000, 5200000, 4800000, 4200000, 5000000, 6000000, 5500000, 4600000, 4000000, 5600000],
    }, {
      name: 'dotted',
      type: 'pictorialBar',
      symbol: 'rect',
      itemStyle: {
        normal: {
          color: '#0f375f',
        },
      },
      symbolRepeat: true,
      symbolSize: [12, 4],
      symbolMargin: 1,
      z: -10,
      data: [4900000, 3700000, 4500000, 5200000, 4800000, 4200000, 5000000, 6000000, 5500000, 4600000, 4000000, 5600000],
    }],
  };

引入react时代码：
import echarts from 'echarts';

export default function quotaObservation() {
  const option = {
    backgroundColor: '#0f375f',
    tooltip: {
    },
    legend: {
      data: ['line', 'bar'],
      textStyle: {
        color: '#ccc',
      },
    },
    xAxis: {
      data: 'category',
      axisLine: {
        lineStyle: {
          color: '#ccc',
        },
      },
    },
    yAxis: {
      splitLine: { show: false },
      axisLine: {
        lineStyle: {
          color: '#ccc',
        },
      },
    },
    series: [{
      name: 'line',
      type: 'line',
      smooth: true,
      showAllSymbol: true,
      symbol: 'emptyCircle',
      symbolSize: 15,
      data: [4900000, 3700000, 4500000, 5200000, 4800000, 4200000, 5000000, 6000000, 5500000, 4600000, 4000000, 5600000],
    }, {
      name: 'bar',
      type: 'bar',
      barWidth: 10,
      itemStyle: {
        normal: {
          barBorderRadius: 5,
          color: new echarts.graphic.LinearGradient(
                    0, 0, 0, 1,
            [
                        { offset: 0, color: '#14c8d4' },
                        { offset: 1, color: '#43eec6' },
            ]
                ),
        },
      },
      data: [3300000, 2500000, 3000000, 1900000, 4200000, 3300000, 1600000, 800000, 3300000, 2800000, 1900000, 2200000],
    }, {
      name: 'line',
      type: 'bar',
      barGap: '-100%',
      barWidth: 10,
      itemStyle: {
        normal: {
          color: new echarts.graphic.LinearGradient(
                    0, 0, 0, 1,
            [
                        { offset: 0, color: 'rgba(20,200,212,0.5)' },
                        { offset: 0.2, color: 'rgba(20,200,212,0.2)' },
                        { offset: 1, color: 'rgba(20,200,212,0)' },
            ]
                ),
        },
      },
      z: -12,
      data: [4900000, 3700000, 4500000, 5200000, 4800000, 4200000, 5000000, 6000000, 5500000, 4600000, 4000000, 5600000],
    }, {
      name: 'dotted',
      type: 'pictorialBar',
      symbol: 'rect',
      itemStyle: {
        normal: {
          color: '#0f375f',
        },
      },
      symbolRepeat: true,
      symbolSize: [12, 4],
      symbolMargin: 1,
      z: -10,
      data: [4900000, 3700000, 4500000, 5200000, 4800000, 4200000, 5000000, 6000000, 5500000, 4600000, 4000000, 5600000],
    }],
  };
  return { option };
}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by SpiritBoys** [comment]
这问题解决了没？什么原因引起的？
