### ISSUE TITLE
tooltip 格式化后 在对应图例前显示 图例颜色

### ISSUE THREAD

**Issue by zfczoe** [ecomfe/echarts#5017]
现在是这样
![image](https://cloud.githubusercontent.com/assets/7411450/22639429/04fc0bcc-ec89-11e6-9dc0-0f7f64a47983.png)

希望这样 
![image](https://cloud.githubusercontent.com/assets/7411450/22639450/22af5674-ec89-11e6-96b8-ac6032995ed7.png)

**Comment by pissang** [comment]
这个颜色需要在 formatter 里用一个 div 去展示
