### ISSUE TITLE
echarts的模拟迁徙在IE8上的兼容性

### ISSUE THREAD

**Issue by genggs** [ecomfe/echarts#5023]
### One-line summary [问题简述]

echarts有个模拟迁徙的功能，但是我在IE8使用这个功能的时候出现了一点问题。那就是地图能显示出来，但是迁徙的路线显示不出来。并且在echarts文件的第47685行报了错。我想请问一下  这个功能是不是在IE8下有兼容性的问题还是其他的？谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

IE8下

### Expected behaviour [期望结果]

希望能有一个解决方案

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/11642621/22676510/de2e1118-ed26-11e6-9919-87ed054e7bc8.png)

**Comment by pissang** [comment]
该功能不支持 IE8
