### ISSUE TITLE
echarts3 扩展svg,移动后SVG后，如何获取当前的坐标？？？

### ISSUE THREAD

**Issue by jsrgwjj** [ecomfe/echarts#5025]

**Comment by pissang** [comment]
问题描述能否具体点？

**Comment by jsrgwjj** [comment]
series: [
                        {
                            name: 'xxxxxxxxx',
                            type: 'map',
                            mapType: 'ship',
                            mapLocation: { x: '0px', y: '0px', width: '40px', height: '40px' },
                            roam: true,
                            ....
                        }
         ]
可以进行放大缩小拖拽，想得到拖拽后所在的坐标

**Comment by 100pah** [comment]
不知这是否能满足：<http://echarts.baidu.com/api.html#echartsInstance.convertToPixel>

**Comment by lixuejiang** [comment]
@jsrgwjj 问下你们echarts是怎么扩展svg的

**Comment by stsshenwei** [comment]
echarts3.0怎么扩展svg图片的，我想做一个迁徙图，底图是svg格式
