### ISSUE TITLE
Unable to apply separate line color for each category in Parallel coordinate chart

### ISSUE THREAD

**Issue by srivignes** [ecomfe/echarts#5027]
I've created a Parallel coordinate chart in my html page and had 2 queries in it.

1) I've to apply different colors for lines based on the category of data. 

2) Is there any option available to pass the time values like a 'timeline'  rather than string ?

### One-line summary [问题简述]

Please help me resolve those 2 issues that are mentioned above by referring the screenshot attached below

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: Google Chrome Version 56.0.2924.87
+ OS Version [操作系统类型和版本]: Windows 7 Professional Service Pack 1

### Expected behaviour [期望结果]

1) I've to apply different colors for lines based on the category. For ex in the screenshot attached below: The lines passing through project 'projectNaveen' should have Blue color , the lines passing through project 'Common' should have Red color and the lines passing through project 'TestRam' should have Yellow color. So, is there any option to do it ?

2) Secondly, I've currently passed the time data under 'RunTime' as a string. So, is there any option available to pass the time values like a 'timeline' rather than string ?

### ECharts option [ECharts配置项]

```javascript
option = {

backgroundColor: '#fff',
            legend: {
                bottom: 0,
                data: [],
                itemGap: 20,
                textStyle: {
                    color: '#73879C',
                    fontSize: 14
                }
            },
            toolbox: {
	            show: true,
	            feature: {
	                magicType: {
	                    show: true,
	                    type: ['pie', 'funnel'],
	                    option: {
	                        funnel: {
	                            x: '25%',
	                            width: '50%',
	                            funnelAlign: 'left',	                            
	                        }
	                    }
	                },
	                restore: {
	                    show: true,
	                    title: "Refresh"
	                },
	                saveAsImage: {
	                    show: true,
	                    title: "Save Image"
	                }
	            }
	        },
            parallelAxis: [
				{dim: 0, name: schema[0].text,
				type: 'category', data: jQuery.parseJSON('{% raw dates %}')},
                {dim: 1, name: schema[1].text, type: 'category', data: jQuery.parseJSON('{% raw projects %}')},                 
                {dim: 2, name: schema[2].text,                    
                type: 'category', data: jQuery.parseJSON('{% raw event_type %}')},                                                            
                {dim: 3, name: schema[3].text, type: 'category', data: jQuery.parseJSON('{% raw bot_id %}')},                
                {dim: 4, name: schema[4].text},
                {dim: 5, name: schema[5].text, type: 'category', data: jQuery.parseJSON('{% raw event_result %}')}
            ],            
            visualMap: {
                show: false,
                min: 0,
                max: 150,
                dimension: 2,
                inRange: {
                    color: ['#489B4A'].reverse()                    
                }
            },
            parallel: {
                left: '5%',
                right: '18%',
                bottom: 100,
                parallelAxisDefault: {
                    type: 'value',
                    name: 'Status',
                    nameLocation: 'end',
                    nameGap: 20,
                    nameTextStyle: {
                        color: '#73879C',
                        fontSize: 12
                    },
                    axisLine: {
                        lineStyle: {
                            color: '#73879C'
                        }
                    },
                    axisTick: {
                        lineStyle: {
                            color: '#489B4A'
                        }
                    },
                    splitLine: {
                        show: false
                    },
                    axisLabel: {
                        textStyle: {
                            color: '#73879C'
                        }
                    }
                }
            },
            series: [
                {
                    name: 'Project History',
                    type: 'parallel',
                    lineStyle: lineStyle,
                    data: dataBJ
                }
            ]

}

```

### Other comments [其他信息]

![parallel_chart](https://cloud.githubusercontent.com/assets/17283869/22681307/7d4cdf8a-ed32-11e6-8ca5-e7b48022a290.png)

**Comment by 100pah** [comment]
About question 1,  yes you can put different categories in different series respectively, like, 

```js
option = {
    legend: {
        data: ['category 0', 'category 1']
    },
    series: [{
        name: 'category 0',
        type: 'parallel',
        data: data0
    }, {
        name: 'category 1',
        type: 'parallel',
        data: data1
    }]
}
```

About question 2, you've mentioned 
> pass the time values like a 'timeline' rather than string
But sorry I am not sure what `'timeline'` exactly is, could explain it in detail?
In category axis (`axis.type` is `'category'`), only string value can be accepted.
In time axis (`axis.type` is `'time'`), both time string (like `'2012-12-12'`), JavaScript Date Object, or timestamp (like 1486563839702) can be accepted.

**Comment by srivignes** [comment]
Thanks a lot @100pah. Appreciate your timely help. I'm now able to apply different separate line color for each category and also modified the time range under RunTime. The 'timeline' , I mentioned the time range, which I'm getting it now.
