### ISSUE TITLE
当datapoint 超过20,000之后，line明显变慢变卡

### ISSUE THREAD

**Issue by connorTang** [ecomfe/echarts#5029]
### One-line summary [问题简述]
当使用line chart， datapoint超过2万之后，render时间超过3秒，并且整个browser开始变卡。
当datapoint超过10万之后，浏览器开始崩溃。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: latest chrome & firefox
+ OS Version [操作系统类型和版本]: Mac OS

### Expected behaviour [期望结果]
希望echart有内部优化，当使用大量数据是，可以流畅的render line chart。

**Comment by 100pah** [comment]
可使用 <http://echarts.baidu.com/option.html#series-line.sampling> 优化。

**Comment by connorTang** [comment]
@100pah 我没看懂这个怎么用 有没有example啊？

**Comment by voidsteed** [comment]
在源码里面有例子：https://github.com/ecomfe/echarts/blob/c7b62850ef9efa928415a91ae77b42928b823be6/test/largeLine.html

**Comment by connorTang** [comment]
大数据量时，用tooltip特别卡， 有什么解决办法么？而且更大量的数据呢？我的数据峰值可以达到600万。
