### ISSUE TITLE
hk map

### ISSUE THREAD

**Issue by shenmegui9** [ecomfe/echarts#5035]
### One-line summary [问题简述]
下载的香港地图js或json与官网demo不一样，官网demo中港岛与九龙间有海的，而下载下来是直接连在一起，想知道demo用的js或json是否和官网提供的下载版本不一致？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   3.0
+ Browser version [浏览器类型和版本]:   ie11
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
实际香港地图应该和官网demo一样在九龙和港岛之间有海。可否提供官网demo用的库。
![default](https://cloud.githubusercontent.com/assets/25633098/22729724/f1f3df54-ee1e-11e6-8de4-a8ffb3991659.PNG)
![demo](https://cloud.githubusercontent.com/assets/25633098/22729757/19c6a0c0-ee1f-11e6-959c-8fd2d7459603.PNG)

### ECharts option [ECharts配置项]
与官网配置一致
```




### Other comments [其他信息]
<!-- For example: Screenshot or Online demo -->
<!-- [例如，截图或线上实例 (JSFiddle/JSBin/Codepen)] -->

**Comment by 100pah** [comment]
官网 demo 使用的香港 geoJson 是 <http://echarts.baidu.com/data/asset/geo/HK.json>

**Comment by shenmegui9** [comment]
就是这个！太感谢啦大神！！

**Comment by ppker** [comment]
echarts 越来越好了  nice
