### ISSUE TITLE
echart工具栏乱码问题！！！

### ISSUE THREAD

**Issue by liuhaosheng** [ecomfe/echarts#5036]
就是这个工具栏添加上去注释乱码，其他文字都是中文。

### One-line summary [问题简述]

我的chrome 最新的 在mac上
求大神指导一下！

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by kocokolo** [comment]
你就不能按规范提交一下问题说明啊

**Comment by voidsteed** [comment]
检查一下你chrome的encoding吧，设置成utf-8

**Comment by kocokolo** [comment]
看来框架的使用还是有起点的，起码初中毕业才行
