### ISSUE TITLE
echarts 的series的type为'lines'时，怎么让tooltip显示出该图表的数据？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#5037]
### One-line summary [问题简述]
series的type为'lines'时，鼠标移动到相应点时，tooltip没有数据，如何让其显示？
图标如下（折线图的type为'lines'）：
![image](https://cloud.githubusercontent.com/assets/22878190/22770828/3087d0cc-eece-11e6-98cb-5b876a19d337.png)
通过
![image](https://cloud.githubusercontent.com/assets/22878190/22770932/ceb9ff04-eece-11e6-93ae-2ebe893847d0.png)打印出来的value值为undefined。

![image](https://cloud.githubusercontent.com/assets/22878190/22770812/18976c0c-eece-11e6-8a22-1fb56624ce5a.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
你的type为什么不用line而用lines？用line可以达到你想要的效果。

**Comment by chenxia123** [comment]
@sevenen  因为我的折线图是有动态效果的,类似这个例子（http://gallery.echartsjs.com/editor.html?c=xBJ-5qzRP），只有type为’lines‘时才能实现的。

**Comment by sevenen** [comment]
1、再添加一个series为line，让lines覆盖line。或者将其中之一颜色改为透明色。tooltip响应line的数据。
2、用你原来的方式。但是你要的数据在data里面，不在value里面。不过你的data也是undefined。希望能提供一下完整的代码。

**Comment by mqliutie** [comment]
http://www.echartsjs.com/gallery/editor.html?c=geo-lines

这个例子能实现 `tooltip` 嘛

**Comment by passioncsu** [comment]
> http://www.echartsjs.com/gallery/editor.html?c=geo-lines
> 
> 这个例子能实现 `tooltip (value)` 嘛
> 
> ------------分割线----------------
> 
> ```
> tooltip: {
>     trigger: 'item',
>     formatter: (data) => {
>         return data.data.value
>     },
>     textStyle: {
>         fontSize: 24,
>         color: 'red'
>     }
> }
> ```
我很好奇这些官方网站里面隐藏的这些例子你怎么找到的,

https://www.echartsjs.com/examples/zh/index.html
我常看的是这个,并没有你给的这个例子啊
