### ISSUE TITLE
IE8浏览器，toolbox中的saveAsImage图标不显示，如何兼容

### ISSUE THREAD

**Issue by nanning106** [ecomfe/echarts#5042]
### One-line summary [问题简述]

目前在做折线图， toolbox中的saveAsImage图标在IE8中不显示，如何兼容IE8？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4.0
+ Browser version [浏览器类型和版本]:IE8
+ OS Version [操作系统类型和版本]:win10,winXP

### Expected behaviour [期望结果]
希望oolbox中的saveAsImage图标在IE8中可以显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
ie8 不支持图片导出
