### ISSUE TITLE
箱线图的echarts.dataTool.prepareBoxplotData返回结果是否正确？

### ISSUE THREAD

**Issue by gjn0314** [ecomfe/echarts#5043]
### One-line summary [问题简述]
用数据[1,2,3,4,5,6,7,8,9,10,11]，调用，返回的boxdata是[-4,3.5,6,8.5,16]，但是感觉1/4数据应该是3，3/4数据是9啊

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

返回boxData为：[-6, 3, 6, 9, 18]

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
百度百科说：
确定四分位数的位置：
Q1的位置= (n+1) × 0.25
Q2的位置= (n+1) × 0.5
Q3的位置= (n+1) × 0.75
n表示项数
对于四分位数的确定，有不同的方法，另外一种方法基于N-1 基础。即
Q1的位置=1+（n-1）x 0.25
Q2的位置=1+（n-1）x 0.5
Q3的位置=1+（n-1）x 0.75

这里计算采用的是第二种方法。

**Comment by gjn0314** [comment]
感谢
