### ISSUE TITLE
IE8，toolbox中的restore等按钮点击后，导致IE停止工作

### ISSUE THREAD

**Issue by nanning106** [ecomfe/echarts#5044]
### One-line summary [问题简述]
IE8，折线图，toolbox中的restore,magicType等按钮点击后，导致IE停止工作

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4.0
+ Browser version [浏览器类型和版本]:IE8
+ OS Version [操作系统类型和版本]:win xp,win10

### Expected behaviour [期望结果]

期望是可以点击切换的

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
没有能复现出这个问题。是否能提供你的 option？
