### ISSUE TITLE
如何防止渐变色阴影柱状图的鼠标滚动事件触发？

### ISSUE THREAD

**Issue by FANUP** [ecomfe/echarts#5047]
### One-line summary [问题简述]
如何防止渐变色阴影柱状图的鼠标滚动事件触发？
http://echarts.baidu.com/demo.html#bar-gradient

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
鼠标滚动时，柱状图的柱状不会放大

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://echarts.baidu.com/demo.html#bar-gradient

**Comment by 100pah** [comment]
去掉这段即可：

```
    dataZoom: [
        {
            type: 'inside'
        }
    ],
```
