### ISSUE TITLE
类目轴数组288个元素时柱状图不显示

### ISSUE THREAD

**Issue by pangniur** [ecomfe/echarts#5048]
echart3

我从后台获得数据，自己处理成数组，然后赋值给x轴类目轴，和y轴数值轴

当我获得60条时可以展示 
获得288时就展示不了，一样的算法
控制台没有报错
f12调试也看到288个元素的数组都是正常的
不知道问题出在了哪里

这是x轴

![Uploading x轴.png…]()
![Uploading y轴.png…]()
![Uploading 柱状图.png…]()

这是y轴之一

这是60条时候正常

多个y轴，设置stack属性堆叠

**Comment by 100pah** [comment]
看不到你的图片。另外是否能提供你的 option？

**Comment by pangniur** [comment]
是我option写错了，配置了 barCategoryGap:10  ，当数据少的时候可以展示，数据多的时候就展示不了
