### ISSUE TITLE
散点图每个散点的label不可以显示一部分值

### ISSUE THREAD

**Issue by tsauliu** [ecomfe/echarts#5051]
### One-line summary [问题简述]
散点图每个散点的label不可以显示一部分值

### Expected behaviour [期望结果]

在一个x,y轴均为字符串的散点图中，无法使得标签只显示一部分字符串

### ECharts option [ECharts配置项]
series:[{'data': [['2017-02-19',
                       'Finance',
                       '制定金融学习计划']],
             'label': {'normal': {formatter: '{c}',
                                  'position': 'top',
                                  'show': 'true',
                                  'textStyle': {'fontSize': 8,
                                                'fontWeight': 'bold'}}},
             'name': 'Finance',
             'type': 'scatter'},]

这么配置散点图的series选项，只能得到下面的结果：

![screenshot from 2017-02-10 22 13 31](https://cloud.githubusercontent.com/assets/10590746/22829601/53be6e8c-efde-11e6-8cc3-dbcc9a7c1326.png)

如何只得到‘制定金融学习计划’为label?

我试过{c2}这种，但是完全不行。

万分感谢！

**Comment by 100pah** [comment]
参见：<http://echarts.baidu.com/option.html#series-scatter.label.normal.formatter>
可用回调函数自己定制。

**Comment by tsauliu** [comment]
感谢回复！
