### ISSUE TITLE
Windrose plot

### ISSUE THREAD

**Issue by akansal1** [ecomfe/echarts#5054]
I am trying to plot stacked bar chart in a ***rose*** type pie chart, but I am not able to achieve the desired output. 

Polar coordinate ***bar*** chart may give similar results 

I am looking for something like:

![image](https://cloud.githubusercontent.com/assets/8511760/22862769/094c9bfc-f15b-11e6-8ce1-a3c8ea02991c.png)

**Comment by pissang** [comment]
Currently bar series on polar coordinate system is not supported yet, but it's in the plan, thanks for the suggestion

**Comment by Ovilia** [comment]
Bar chart is now supported. See [example 1](http://echarts.baidu.com/demo.html#bar-polar-stack) and [example 2](http://echarts.baidu.com/demo.html#bar-polar-stack-radial)

**Comment by dongli** [comment]
> Bar chart is now supported. See [example 1](http://echarts.baidu.com/demo.html#bar-polar-stack) and [example 2](http://echarts.baidu.com/demo.html#bar-polar-stack-radial)

The links are broken.
