### ISSUE TITLE
bmap.js 与 series.map 冲突

### ISSUE THREAD

**Issue by MeteorInfinity** [ecomfe/echarts#5055]
### One-line summary [问题简述]

在使用bmap扩展时
添加series.map元素后，如果指定 [coordinateSystem: 'bmap']
会出现geo.getZoom is not a function错误

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: Chrome 57.0.2987.37(beta) 64
+ OS Version [操作系统类型和版本]: macOS Sierra 10.12.3 64

### Expected behaviour [期望结果]

找到错误原因

### ECharts option [ECharts配置项]

```javascript
option = {
bmap: {
                    center: [120.871592, 32.022942],
                    zoom: 14,
                    roam: true
                },
                series: [{
                    name: 'cityArea',
                    type: 'map',
                    map: 'nantongQ',
                    coordinateSystem: 'bmap'
                }]
}

```

### Other comments [其他信息]

`<!DOCTYPE html>
<html style="height: 100%">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <title>ECharts</title>

        
        <link href="./frame/bootstrap-3.3.7/css/bootstrap.css" rel="stylesheet">

         
        <script src="./frame/echarts.js"></script>
        <script src="./frame/bmap.js"></script>
        <script src="./frame/jquery-3.1.1.js"></script>
        <script src="./frame/bootstrap-3.3.7/js/bootstrap.js"></script>
        <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=27puF9VLwi4QAg2QdSqQyImCxzp4NK9U"></script>

        <script type="text/javascript" src="data/js/nantongQ.js"></script>

        

        <style type="text/css">
            body {
                height: 100%;
                margin: 0;
            }
        </style>

    </head>
    <body>
        <div id="mapview" style="height: 100%"></div>

         
        <script type="text/javascript">
            // 基于准备好的dom，初始化echarts实例
            var myChart = echarts.init(document.getElementById("mapview"));

            var option = {
                bmap: {
                    center: [120.871592, 32.022942],
                    zoom: 14,
                    roam: true
                },
                series: [{
                    name: 'cityArea',
                    type: 'map',
                    map: 'nantongQ',
                    coordinateSystem: 'bmap'
                }]
            };

            myChart.setOption(option);

            var bmap = myChart.getModel().getComponent('bmap').getBMap();
            bmap.addControl(new BMap.MapTypeControl());

        </script>
        
    </body>
</html>
`
<img width="1279" alt="qq20170213-012607 2x" src="https://cloud.githubusercontent.com/assets/14803701/22864384/6dc04c0c-f18b-11e6-941a-76011790185e.png">

**Comment by pissang** [comment]
map 系列暂时还不支持坐标系为 bmap
