### ISSUE TITLE
使用线图时，当数据量特别大，tooltip十分卡，没法正常使用

### ISSUE THREAD

**Issue by connorTang** [ecomfe/echarts#5056]
One-line summary [问题简述]

当使用line chart， 我的datapoint最大峰值可以达到60万。发现数据量超过5/6千后，tooltip就无法正常使用，当鼠标移动到一个点后，要等待好几秒才能显示tooltip。

Version & Environment [版本及环境]

    ECharts version [ECharts 版本]: 3.3.2
    Browser version [浏览器类型和版本]: latest chrome & firefox
    OS Version [操作系统类型和版本]: Mac OS

Expected behaviour [期望结果]
有没有什么除sampling之外更好的优化方案？ 希望有针对tooltip的优化。

**Comment by 100pah** [comment]
我测试时候，60万数据，开启 sampling 后，tooltip 并没有很慢。是否方便提供你的 option？

**Comment by connorTang** [comment]
@100pah 发现了是和`Symbol` setting有关系； 加上下面的setting之后，tooltip就卡的用不了...
```
showAllSymbol: true,
symbol: 'emptyCircle',
symbolSize: 0.1
```

**Comment by 100pah** [comment]
@connorTang 我设置这三个 setting 后，仍然并没有觉得卡。没有想出你的问题原因是什么。

**Comment by connorTang** [comment]
@100pah 我有一个[demo](https://github.com/connorTang/react-echarts)你试一下，用了`echarts-for-react` 这个lib，然后用的`echarts@3.3.2`. 
这个[21-23](https://github.com/connorTang/react-echarts/blob/master/src/App.js#L21)这几行comment掉就不卡，加上就特别卡。

**Comment by pissang** [comment]
不要加 showAllSymbol，这个会把所有拐点图形绘制出来

**Comment by connorTang** [comment]
@pissang 这个花了我好长时间才发现问题在哪…要不要在文档里加个warning提示一下其他人？
