### ISSUE TITLE
请问在echarts 3.x中，如何设置柱状图的柱子不可点击？

### ISSUE THREAD

**Issue by zrwlc2008** [ecomfe/echarts#5061]
### One-line summary [问题简述]
请问在echarts 3.x中，如何设置柱状图的柱子不可点击？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: ECharts 3.4.0
+ Browser version [浏览器类型和版本]: chrome 54.0.2840.99 m
+ OS Version [操作系统类型和版本]: win 7

### Expected behaviour [期望结果]
能够设置柱状图的柱子不可点击，就像echarts 2.x中，series可以设置clickable一样。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#series-bar.silent>

**Comment by zrwlc2008** [comment]
非常感谢！
