### ISSUE TITLE
echarts3.0 动态更换主题接口

### ISSUE THREAD

**Issue by wdnlwzd** [ecomfe/echarts#5063]
### One-line summary [问题简述]

请问echarts3.0 在第一次echarts.init()初始化主题后，是否有接口可以实现类似于echarts2.0的setTheme(动态更换主题)。
如果3.0只能用setOption()来实现，请问setOption()需要怎么更换内置主题（传入的参数）？
谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
暂时不会实现动态更换主题的接口。如果需要更换主题，可先 `dispose` 后重新创建。

**Comment by wdnlwzd** [comment]
@100pah  好的，谢谢。
