### ISSUE TITLE
循环调用setOptions设置map大量散点图数据 存在内存泄漏

### ISSUE THREAD

**Issue by OckhamRazor** [ecomfe/echarts#5066]
### One-line summary [问题简述]

假设我有五组散点数据，需要轮播。在定时器内setOption刷新数据，发现内存泄漏（散点数据大时，内存上涨很快5分钟50M左右）。已知dispose可以销毁实例，然后重新实例化，实现内存的释放。实际情况是，重新实例化时会导致画面卡顿、存在loading时间，且为此还要存储geoJson、nameMap数据到内存（重复发起请求）。我想知道是什么导致了内存泄漏，能从echart.js库里解决这个问题么？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: chrome 56
+ OS Version [操作系统类型和版本]: ubuntu16.04

### Expected behaviour [期望结果]

得到内存泄漏的原因。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有具体例子么？

**Comment by voidsteed** [comment]
你好，我也遇到了这种问题，也是散点图，而且setOption的notMerge选项没有效果，一次读取40万的点。三次load浏览器就崩溃了。

我今天找到一个可行的方法：
如果第一次新建图表，创建一个新的option。如果在图表存在的情况下， 用getOption取到已经存在的option, 重新set option.series = new series. 然后用chartInstance.clear()，清空option，最后setOption(option, false, false)。这个选项会merge一起清空的data series。我的内存指标也下降不少，再也没有浏览器崩溃的情况了。

**Comment by OckhamRazor** [comment]
@voidsteed 多谢提供思路。确实能解决该问题。

**Comment by fhlsteven** [comment]
@OckhamRazor 为什么会造成内存泄露呢，到底是那块儿的问题

**Comment by ZhuGYao** [comment]
我直接clear，然后再setOption(),为什么还是会造成内存泄漏，上升的很快？？必须得merge吗？？谢谢
