### ISSUE TITLE
双轴，y轴设置了min之后，柱形图如果有负数，显示有问题

### ISSUE THREAD

**Issue by fsx379** [ecomfe/echarts#5069]
### One-line summary [问题简述]
双轴，
左边轴，用于显示柱状图，其中数据有负数；
右边轴显示其他数据。由于右边轴显示数据波动范围小，故需要设置min、max。

如果min设置为 0或负数，左轴的柱状图显示没问题；
如果min设置为正数，左轴的柱状图显示有问题，不是从0开始的，而是从最下方开始。详细见代码；

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: window

### Expected behaviour [期望结果]

即使设置了min，柱状图也能正常显示（从0开始显示）

### ECharts option [ECharts配置项]

```javascript
option = {
color: ['#3398DB'],
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        }
    ],
    yAxis : [
        {
            type : 'value'
        },
        {
            type: 'value',
            axisLabel: {
                formatter: '{value} %'
            },
            min: 0, max: 80
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            // barWidth: '60%',
            data:[1000, -520, -2000, -3340, 3900, -330, -5220]
        }
    ]
}

```

### Other comments [其他信息]

正确的：
![image](https://cloud.githubusercontent.com/assets/25763541/22919242/ab8da0fe-f2c9-11e6-9dd0-2eb0e78e6e2d.png)

有问题的：
![image](https://cloud.githubusercontent.com/assets/25763541/22919250/bc52b6e0-f2c9-11e6-80cf-a76f66d3303e.png)

**Comment by johnhuang669** [comment]
請問這個bug甚麼時候可以修正??已經過很久了  而且是很常發生的bug

**Comment by johnhuang669** [comment]
請問有看到嗎???

**Comment by chisuru** [comment]
这个问题我也碰到了, 3.5.4版还有这个问题
看起来像是设定双轴的时候, 0以下的柱状图没有弄成相反顯示.
例如第1, 第5根0以下是全满的柱状图, 把它消掉 就正常了
其它根柱状图 把0以下 没图的部份画上正常的柱状图, 有图的部份 消掉  也正常了

**Comment by jsiwa** [comment]
@chisuru 已经解决了？

**Comment by 100pah** [comment]
在当前版本 3.6.x 看起来已经没有这个问题了。

**Comment by chisuru** [comment]
我去下載了3.6.2,  看起來還是有問題, 沒解決

2017-07-14 16:58 GMT+08:00 百变茄 <notifications@github.com>:
