### ISSUE TITLE
渐变色阴影柱形图的柱状宽度和间距可不可以改变

### ISSUE THREAD

**Issue by FANUP** [ecomfe/echarts#5074]
### One-line summary [问题简述]
渐变色阴影柱形图的柱状宽度和间距可不可以改变
http://echarts.baidu.com/demo.html#bar-gradient

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望渐变色阴影柱形图的柱状宽度和间距都可以改变

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://echarts.baidu.com/demo.html#bar-gradient

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-bar.barWidth ，http://echarts.baidu.com/option.html#series-bar.barCategoryGap
