### ISSUE TITLE
delMarkPoint和delMarkLine删除时的effect炫光特效的问题

### ISSUE THREAD

**Issue by tianqiL** [ecomfe/echarts#5075]
### One-line summary [问题简述]
在地图上用delMarkLine和delMarkPoint 删除线和标记点的时候炫光特效删除不掉会有残留，这是怎么回事

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.2.7
+ Browser version [浏览器类型和版本]:FireFox51.0.1
+ OS Version [操作系统类型和版本]:win7旗舰版

### Expected behaviour [期望结果]

求解

### ECharts option [ECharts配置项]

```javascript
option = {

}
```

### Other comments [其他信息]

删除前
![default](https://cloud.githubusercontent.com/assets/21257811/22958972/abf95426-f36d-11e6-9d38-2a9503ff0757.png)
删除后
![default](https://cloud.githubusercontent.com/assets/21257811/22958989/c4957bc2-f36d-11e6-9547-f322a96df0d8.png)
添加线和标记点的代码
![default](https://cloud.githubusercontent.com/assets/21257811/22959011/ea5c4b56-f36d-11e6-9fb7-c6ef607a4714.png)
删除代码
![default](https://cloud.githubusercontent.com/assets/21257811/22959029/038bf720-f36e-11e6-9523-1b7c155a7aa8.png)

**Comment by pissang** [comment]
这个问题是 canvas 尾迹带来的残影效果，暂时无法去掉
