### ISSUE TITLE
你们官网上的官方实例代码在哪里能下载到

### ISSUE THREAD

**Issue by leinov** [ecomfe/echarts#5077]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by cangxin** [comment]
官方的示例其实很容易下载的，直接在 示例 中粘贴给出的代码，然后自己初始化以下，最后再setoption 一下就可以直接运行了，前提是html写好了。您可以参考一下我的方法，谢谢。

**Comment by leinov** [comment]
我现在要做一个类似与http://echarts.baidu.com/demo.html#scatter-weibo 这个的功能，这里使用了一个接口 http://echarts.baidu.com/gallery/data/asset/data/weibo.json 我打开看了下 密密麻麻的数据 想下源码看下 可是下不到 这个接口的数据也不知道是什么意思 怎么对应到相应的经纬度上

**Comment by cangxin** [comment]
您可以直接在代码中console 出它：‘http://echarts.baidu.com/gallery/data/asset/data/weibo.json’，然后看它的数据格式，自己写个类似的格式，然后调用就可以在本地运行了，我刚刚console了一下，它是一个多维数组，至于怎么对应到经纬度，那么您就得研究一下源码中 ‘weiboData.map’这个函数是如何解析的了，所有 ‘series’ 中的 ‘data’ 数据都是经过它解析然后加载到 ‘data’ 中的。在下现在比较忙，没时间研究，只能给你参考。
