### ISSUE TITLE
怎样在鼠标点击位置画线，并能取到该位置的x和y的值

### ISSUE THREAD

**Issue by ZeyZhang** [ecomfe/echarts#5079]
### One-line summary [问题简述]
在ng2的项目中，如何利用鼠标点击事件触发在点击位置画线并能取到当前位置x和y的值？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
x, y 指的是像素还是数据？

**Comment by ZeyZhang** [comment]
这个点的坐标，就是data

**Comment by 100pah** [comment]
可参见 
<http://echarts.baidu.com/demo.html#line-pen> <br>
<http://echarts.baidu.com/api.html#echartsInstance.convertFromPixel>

**Comment by ZeyZhang** [comment]
谢谢
