### ISSUE TITLE
散点图添加 ‘图例’ 实现切换功能

### ISSUE THREAD

**Issue by cangxin** [ecomfe/echarts#5081]
### One-line summary [问题简述]
如何在官方散点图示例 ‘Scatter Map Brush’ 中添加 示例  ‘模拟迁徙’ 的图例做为切换按钮，可以切换显示不同的数据？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  echarts 3.4.0
+ Browser version [浏览器类型和版本]: chrome55
+ OS Version [操作系统类型和版本]:windows10 x64

### Expected behaviour [期望结果]

实现 ‘模拟迁徙’ 示例中的 ‘图例’ 切换效果,谢谢!

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
用 http://echarts.baidu.com/option.html#legend 组件

**Comment by cangxin** [comment]
谢谢您的回答。
