### ISSUE TITLE
在力引导图中，点击node和link的时候是否可以拿到上面的数据？

### ISSUE THREAD

**Issue by jx-zhang** [ecomfe/echarts#5083]
### One-line summary [问题简述]
在力引导图中，点击node和link的时候是否可以拿到上面的数据？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.4
+ Browser version [浏览器类型和版本]: chrome 版本 55.0.2883.87
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]
希望点击node的时候拿到node上的数据，并且进行直接修改，
link同上。
```javascript
mychart.getZr().on('click', function (evt) {
    console.log(evt.target);
});

```
evt.target上希望可以带上数据。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
```js
myChart.on('click', function (e) { console.log(e) });
```
