### ISSUE TITLE
官网微博点亮中国这个事例里面的json数据是什么意思 ？

### ISSUE THREAD

**Issue by leinov** [ecomfe/echarts#5084]
我现在要做一个类似与http://echarts.baidu.com/demo.html#scatter-weibo 这个的功能，这里使用了一个接口 http://echarts.baidu.com/gallery/data/asset/data/weibo.json 我打开看了下 密密麻麻的数据 想下源码看下 可是下不到源码  这个接口的数据也不知道是什么意思 怎么对应到相应的经纬度上

**Comment by pissang** [comment]
把转换的代码去掉然后直接按散点图的数据格式来就行， 如下
```js
[ [lng, lat, val], [lng, lat, val] ]
```

**Comment by kouguopeng** [comment]
用[ [lng, lat, val], [lng, lat, val] ]这样的格式，
           symbolSize: function (val) {
                console.log(val);
                return val[2] / 10;
            },
这里的val就无效了，怎么解决。
