### ISSUE TITLE
关于Echarts的api查询问题

### ISSUE THREAD

**Issue by jundangguntianqu** [ecomfe/echarts#5095]
### One-line summary [问题简述]

有时候我需要一个功能但是不知道它的接口  我要怎么从api里面查到它？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
比如说？

**Comment by jundangguntianqu** [comment]
我想创建一个可以保存为图片的功能 或者想知道echarts里面有没有饼图形/

**Comment by 100pah** [comment]
『功能』和『文档』的关联确实是个可以深思的问题。
以前做过这种尝试：<http://echarts.baidu.com/echarts2/doc/option.html#title~title.itemGap> （点击图形能对应到 option）。

你觉得这种方式，能解决这个问题吗？或者，不知有没有什么其他好的建议 ~
