### ISSUE TITLE
节点显示文字是否可以加入html的<img>标签？

### ISSUE THREAD

**Issue by Leung0423** [ecomfe/echarts#5096]
![qq 20170217151424](https://cloud.githubusercontent.com/assets/25632883/23056100/938a3d5c-f524-11e6-8b8f-838e21af193d.png)

[问题简述]
如图，因项目需要，要求在节点上显示一些生僻字，相关生僻字已整理为单个的图片；
想请问，在节点上可不可以，如果可以，怎样用html的img标签显示图片？

```javascript
nodes: data.nodes.map(
	function(element) {
		return {
			name : element.name,	// 节点文字，这里是否可以加入<img>标签？
			value : element.value,
			code : element.code,
			category : element.category
		}
	}
),

**Comment by 100pah** [comment]
label 中图片现在倒是不支持。

但是这个子我可以打得出来哎：『㕮』。

其实很多生僻字在 unicode 中都是有的。你们或许可以看看这些生僻字是否真的超出 unicode 的范围。
