### ISSUE TITLE
Vue2+webpack中使用tooltip时，formatter回调函数中params识别不了

### ISSUE THREAD

**Issue by wolfzhaoshuai** [ecomfe/echarts#5099]
### One-line summary [问题简述]

当前使用的是Vue2，使用Webpack打包，然后在做关系图即series的type设置为graph时，此时使用tooltip中的formatter回调自定义悬浮框信息样式，但提示Uncaught TypeError: Cannot read property 'params' of undefined

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]:Chrome: 56.0.2924.87 (64-bit)
+ OS Version [操作系统类型和版本]: OS X EI Capitan，版本10.11.4

### Expected behaviour [期望结果]

console中应该可以看到params的信息

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
          text: this.graphTitle
        },
        tooltip: {
          show: true,
          formatter: function (params, ticket, callback) {
            console.log(params)
          }
        },
series: [
  type:graph,
  ...
]
}

```

**Comment by 100pah** [comment]
应该是 `console.log(params)`。

**Comment by wolfzhaoshuai** [comment]
@100pah ,谢谢啦，范2了，
