### ISSUE TITLE
如何实现点击散点图里的散点，跳转到某个url？

### ISSUE THREAD

**Issue by tsauliu** [ecomfe/echarts#5100]
### One-line summary [问题简述]
如何实现点击散点图里的散点，跳转到某个url？

### Expected behaviour [期望结果]

点击散点图里的散点，直接跳转到某个url。

### Other comments [其他信息]

目前我只能实现点击tooltip 里url跳转，不过这样实在是不方便啊，求问能否能实现点击散点图中的点跳转，谢谢！

![screen shot 2017-02-18 at 14 11 35](https://cloud.githubusercontent.com/assets/10590746/23090900/3e13b6c6-f5e4-11e6-8e08-706b55fbdcb1.png)

**Comment by pissang** [comment]
参见 http://echarts.baidu.com/tutorial.html#ECharts%20中的事件和行为 中的实现
