### ISSUE TITLE
Echarts图表在移动端会影响页面的滚动

### ISSUE THREAD

**Issue by wangyichen1064431086** [ecomfe/echarts#5101]
### One-line summary [问题简述]
在移动端使用Echarts图表，当指头移到图表上，页面就无法滚动了。
如果页面Echarts图表就一个，面积又不大，则带来的问题还不是很明显。如果页面Echarts图表又多又大，那就相当悲剧了，页面跟卡住了似的。请问有没有解决的办法？非常感谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.1
+ Browser version [浏览器类型和版本]:Safari
+ OS Version [操作系统类型和版本]:iOS10.2.1

### Expected behaviour [期望结果]
手指放在移动端页面上的Echarts图表上时，依然可以自由地滚动页面。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
3.3.1 有这个 bug，升级到 3.3.2 以上的版本试试

**Comment by wangyichen1064431086** [comment]
果然我升级到3.4.0了，问题完美地没有了！！！太感谢了！！！

**Comment by zhangsanshi** [comment]
@pissang 问题有点诡异，我用webpack打包引用 `require('echarts');`，表现和上面的是一样的。引用 `require('echarts/dist/echarts.js')`时，表现就正常了，使用版本是 3.4.0。
