### ISSUE TITLE
xy轴不显示

### ISSUE THREAD

**Issue by jsshizhan** [ecomfe/echarts#5103]
### One-line summary [问题简述]
我用的是echarts-3.4.0  再项目中使用的时候xy轴无法显示,是不是和其他框架有冲突导致的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'line',
                data: [5, 20, 36, 10, 10, 20]
            }]
}

```

### Other comments [其他信息]

![qq 20170220115005](https://cloud.githubusercontent.com/assets/8943661/23111203/f6b7a448-f761-11e6-9811-9a219e253c93.png)

**Comment by pissang** [comment]
你把背景换成白色看看

**Comment by jsshizhan** [comment]
@pissang  谢谢
