### ISSUE TITLE
line类型是否支持分段填充颜色？

### ISSUE THREAD

**Issue by zhangchenyue** [ecomfe/echarts#5105]
### One-line summary [问题简述]
line可设置areaStyle填充颜色，能否根据X轴的区间进行填充？
比如 X为时间轴，（00：00：00 - 23：59：59），能否设置0：00 - 1：00 填充红色，1：00- 4：00 填充蓝色等，该如何实现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/demo.html#line-sections
