### ISSUE TITLE
折线图上的每个折点都显示数值？

### ISSUE THREAD

**Issue by jsshizhan** [ecomfe/echarts#5107]
### One-line summary [问题简述]
只有鼠标放在当前位置时才会显示折点的数据，能不能直接显示数值？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
`series:[{
type:'line',
label:{
normal:{show:true}
}
}]`
设置成这样你试一下
