### ISSUE TITLE
echarts 折线图线条样式能不能有渐变颜色

### ISSUE THREAD

**Issue by teng2015** [ecomfe/echarts#5111]
### One-line summary [问题简述]
echarts 折线图线条样式能不能有渐变颜色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
参见：<http://gallery.echartsjs.com/editor.html?c=xByOl2q_tg&v=1>
