### ISSUE TITLE
HideLoading 无效 

### ISSUE THREAD

**Issue by Jeffy2012** [ecomfe/echarts#5112]
### One-line summary [问题简述]

![image](https://cloud.githubusercontent.com/assets/2225478/23121634/202f15e2-f79c-11e6-934c-7577b68ce45f.png)

![image](https://cloud.githubusercontent.com/assets/2225478/23121761/92de94f0-f79c-11e6-83cd-066291c38c25.png)

调用hideLoading无效
并且如果不显示loading的话 图表的 spitLine的层级(z)比series高(从图二可以看出来)， 我并没有设置 z 或者 zlevel

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: chrome 
+ OS Version [操作系统类型和版本]: oppo find7 android5.0

### Expected behaviour [期望结果]
hideLoading 能正常工作
层级能够正常

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
splitLine 的层级可以在  `yAxis.z` 中设置。

**Comment by Jeffy2012** [comment]
没有报错，而且执行了hideLoading  spiltLine的层级就没设置过，所有元素的z都没有设置过。 而且在其他平台显示是ok的 ， hideLoading 调用后 loading的那个层是没有消失的，看到中间那个点了么？ 那个是图表最终状态。 我只是把loading 的maskColor 设置为透明啦。

**Comment by fionagithub** [comment]
想请问下showloading会在canvas上创建新的层级么，有相关说明文档？ @100pah

**Comment by pissang** [comment]
@fionagithub 不会

**Comment by fionagithub** [comment]
@pissang 下面是有存在疑问的代码，echart的showloading和clear方法为什么不可以调换执行的顺序，一定要如下所示，不然无法显示loading？
 `  
   setInterval(fetchData, 3000);

        function fetchData(data) {
            myChart.showLoading(); // ???
            myChart.clear(); // ???
            option = {
                "graphic": [{
                    type: 'text',
                    left: 'center',
                    top: 'middle',
                    style: {
                        fill: '#333',
                        text: 'hello!!!',
                        font: '26px Microsoft YaHei'
                    }
                }]
            }
            if (option && typeof option === "object") {
                myChart.hideLoading();
                myChart.setOption(option, false);
            }
        }
`
