### ISSUE TITLE
官方示例中“单轴散点图”，加入title运行报错，其他示例没问及

### ISSUE THREAD

**Issue by minyiran** [ecomfe/echarts#5116]
![image](https://cloud.githubusercontent.com/assets/25916816/23148955/bc24d2b6-f823-11e6-91ae-ebae08cf4981.png)
![image](https://cloud.githubusercontent.com/assets/25916816/23148985/d7b471bc-f823-11e6-9b6d-4363a8d07c34.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
因为
![image](https://cloud.githubusercontent.com/assets/23046337/23154238/c022f5cc-f847-11e6-912f-0e6571851b3c.png)
title 这里是一个数组，才可以使用push方法，而你把他定义成了一个对象，所以会报错。
