### ISSUE TITLE
如何控制tooltip 的内容？

### ISSUE THREAD

**Issue by ruofeng086** [ecomfe/echarts#5117]
### One-line summary [问题简述]

希望实现类似这样的样式，但在官网文档中找不到相应配置项

![image](https://cloud.githubusercontent.com/assets/14192308/23150100/ba86968a-f82b-11e6-8934-7c020f6c84e2.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: chrome 54
+ OS Version [操作系统类型和版本]: mac os

### Expected behaviour [期望结果]

告知如何实现这样的样式，如，时间是怎么添加上去的？是那个字段控制的

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
显示tooltip时，默认的显示是这样的
![image](https://cloud.githubusercontent.com/assets/23046337/23153865/c93289d6-f845-11e6-8b36-0acb4f7f4900.png)
横轴显示在最上面，这个图里就是周二，纵轴依次显示在下面，就是下面的一排的显示。和你的给的不太一样。
如果你要控制其中的内容，比如让周二不显示，就用tooltip--formatter来控制。但是想要这种彩色的效果就难了。api为http://echarts.baidu.com/option.html#tooltip.formatter

**Comment by ruofeng086** [comment]
例子中使用的也是echart，那他是怎么实现的？

**Comment by ruofeng086** [comment]
![image](https://cloud.githubusercontent.com/assets/14192308/23154207/96b21e52-f847-11e6-9e8c-176f2b315a59.png)
目前已实现90%，剩余这个提示框没有找到相应文档。

**Comment by sevenen** [comment]
不知道啊，能不能看一下他的源码啊。。。你试试graphic？不过这个东西好麻烦http://echarts.baidu.com/option.html#graphic

**Comment by iamwelk** [comment]
使用formatter控制显示，自定义里面的样式就可以了吧

**Comment by sevenen** [comment]
时间下面的那条横杠是怎么显示的呢？

**Comment by iamwelk** [comment]
http://echarts.baidu.com/demo.html#line-sections
```
tooltip: {
    trigger: 'axis',
    formatter: function (obj) {
        return '<div style="border-bottom:1px solid #eee">' + obj[0].name + '</div>';
    }
}
```
![image](https://cloud.githubusercontent.com/assets/6983075/23194463/3896db80-f8e9-11e6-99c5-1bd0f7737cf5.png)

**Comment by zhangsanmu** [comment]
formatter:'{b}<br />'+
 '<div style="display: inline-block;width: 10px;height: 10px;background: #cccccc;border-radius: 50%;"></div>  {a}:{c}'

**Comment by zhangsanmu** [comment]
formatter:'{b}<br />'+
						        		  '<div style="display: inline-block;width: 10px;height: 10px;background: #008000;border-radius: 50%;"></div>  {a3}:{c3}<br />'+
						        		  '<div style="display: inline-block;width: 10px;height: 10px;background: #FF0000;border-radius: 50%;"></div>  {a2}:{c2}<br />'+
						        		  '<div style="display: inline-block;width: 10px;height: 10px;background: #FFFF00;border-radius: 50%;"></div>  {a1}:{c1}<br />'+
						        		  '<div style="display: inline-block;width: 10px;height: 10px;background: #cccccc;border-radius: 50%;"></div>  {a0}:{c0}'
