### ISSUE TITLE
饼图功能增强

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts#5118]
能否像excel一样提供类似下图的功能，感觉这种图对于分析数据比较有作用

![image](https://cloud.githubusercontent.com/assets/6983075/23154120/21721f8e-f847-11e6-8f3b-2ffaa90f7577.png)

**Comment by iamwanming** [comment]
这种使用treemap也很合适

**Comment by iamwelk** [comment]
@iamwanming treemap是可以的，感觉饼图效果可能会更好点

**Comment by pissang** [comment]
试试用自定义图形的 graphic 组件去画这些东西

**Comment by iamwelk** [comment]
@pissang 嗯，多谢，我研究一下
