### ISSUE TITLE
如何监听鼠标悬浮在数据点上时触发强调效果的事件

### ISSUE THREAD

**Issue by wangyichen1064431086** [ecomfe/echarts#5121]
### One-line summary [问题简述]
我想要监听鼠标在echarts图表的数据点上的悬浮次数。我觉得，既然每次悬浮在数据点上都会出现强调效果（也可以触发tooltip的显示），那么这一定是触发了某个事件。请问应该怎样监听这个事件呢？ 这个事件又应该绑定到什么元素上呢？直接把mousemove绑定到外层div肯定是不行的，我只想监控悬浮在数据点上出现强调效果这个事件。

另外，在鼠标移动至数据点上触发强调效果后，光标形状会变为pointer，那么如果我想保持鼠标形状为default，请问该怎么设置呢？

非常感谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Win7

### Expected behaviour [期望结果]
可以监听鼠标移动到数据点上触发强调效果的事件。也可以改变光标悬浮于数据点上时的光标形状。

非常感谢！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sevenen** [comment]
API里面有鼠标事件。myChart.on('mousemove',function(){})。
http://echarts.baidu.com/api.html#echartsInstance.on
http://echarts.baidu.com/api.html#events.%E9%BC%A0%E6%A0%87%E4%BA%8B%E4%BB%B6
如何改变光标形状，我也不清楚。
