### ISSUE TITLE
echarts3 和微信分享冲突

### ISSUE THREAD

**Issue by Lee-biao** [ecomfe/echarts#5122]
### One-line summary [问题简述]
echarts图表地图使用页面和微信分享冲突  引入echarts文件微信分享js就会报wx.config undefined

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:微信内置浏览器
+ OS Version [操作系统类型和版本]:安卓和iOS

### Expected behaviour [期望结果]
查找冲突原因

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
跟 echarts 没有关系吧？再排查下？
