### ISSUE TITLE
关于地图是否可以实现多维

### ISSUE THREAD

**Issue by shenmegui9** [ecomfe/echarts#5126]
### One-line summary [问题简述]

想知道echarts map能不能实现多维，像bar chart那样比较不同维度的值。
不是像2.0官网iPhone销量的例子，同一个省同时销量iPhone3，4会把两个销量值叠加。我知道可以配置取最大最小平均，可是我想要的结果是两个值独立开来，就是tooltip显示iPhone3的销量值同时显示iPhone4的销量值，不知道echarts3.0可以实现吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以自定义 tooltip 的 formatter

**Comment by shenmegui9** [comment]
是喔！谢谢大神！

**Comment by wxxcarl** [comment]
然而我还是没有解决，formatter回调函数里面params参数里面的值，并没有多维的数据，只有value字段总和。不知道你是怎么解决的 @shenmegui9
