### ISSUE TITLE
Help event click

### ISSUE THREAD

**Issue by lyuzcrow** [ecomfe/echarts#5127]
I have a question I could not find on the echarts website. I have a bar graph, where I can generate an alert when I click on 
Code: 
myChart9.on('click', function (params) {
                                   alert('The user selected ');
                        });

But I wanted to see the name of the axis of the bar that I clicked, would it be possible to recover the value of xAxis in the click? 

Very Best Regards

**Comment by pissang** [comment]
You can indexing from `xAxis.data` with `params.dataIndex`
