### ISSUE TITLE
echarts3 地图怎么实现省市三级联动效果？

### ISSUE THREAD

**Issue by qiantoutou** [ecomfe/echarts#5128]
echarts3 地图怎么实现省市三级联动效果？ 有这样的例子吗

**Comment by pissang** [comment]
跟二级联动方式是一样的

**Comment by qiantoutou** [comment]
我之前是用的echarts2写的联动效果  引用文件不太一样

**Comment by zds-xiaoxianyu** [comment]
@pissang #5124 麻烦确认下该问题，制作地图级联时，发现部分省份的部分地区数据异常，json数据是在官方网站下载的，谢谢！

**Comment by qiantoutou** [comment]
@zds-xiaoxianyu  可以发给我下你的地图联动demo吗？ 谢谢！
