### ISSUE TITLE
关于EChart Licience

### ISSUE THREAD

**Issue by zhangchenyue** [ecomfe/echarts#5129]
### One-line summary [问题简述]

请问EChart是遵循什么Licience？ 从LICIENCE描述看不太出来，是MIT还是GPL？可以免费商用吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
BSD
