### ISSUE TITLE
关于SetOption的best practice

### ISSUE THREAD

**Issue by zhangchenyue** [ecomfe/echarts#5130]
### One-line summary [问题简述]

文档中经常提到不推荐下面的做法
var option = myChart.getOption();
option.visualMap[0].inRange.color = ...;
myChart.setOption(option);
希望用这种方式
myChart.setOption({
    visualMap: {
        inRange: {
            color: ...
        }
    }
})
请问是因为性能的原因吗？
另外，通常情况下Series里面的data属性设置是通过ajax之类的动态获得，如果只改变series数组中一个series的data属性，按照推荐的方式需要从新设置全部的series数组的全部属性吗？
比如初始：
 series: [
            {
                gridIndex: 0,
                xAxisIndex: 0,
                yAxisIndex: 0,
                name: 'AAA',
                type: 'scatter',
                symbolSize: 6
            },
            {
                gridIndex: 0,
                xAxisIndex: 0,
                yAxisIndex: 1,
                name: 'BBB',
                type: 'line',
                showSymbol: false,
                itemStyle: {
                    normal: {
                        color: '#f44336',
                        width: 1
                    }
                }
            }
]
现在需要根据ajax请求结果设置series[0].data,和series[1].data, 该如何做比较好？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
不是因为性能的问题，而是因为 getOption 得到的内容非常多，某些特殊场景下不完全保证再 setOption 回去和直观预期相同。

setOption 默认是 merge 的模式，所以不需要重新设置全部的属性。
