### ISSUE TITLE
toolbox的showTitle不起作用

### ISSUE THREAD

**Issue by zhangchenyue** [ecomfe/echarts#5134]
### One-line summary [问题简述]
toolbox的showTitle不起作用， 设置false后，鼠标hover工具图标时还会有中文提示

http://echarts.baidu.com/gallery/editor.html?c=line-marker
可在示例代码里加showTitle:false 重现

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
我这是可以的，你是不是加错地方了
