### ISSUE TITLE
作品中地图模块， iphone销量图例中，某些省份的字都不在省份范围中了，api中没有相关解决。

### ISSUE THREAD

**Issue by 18109423185** [ecomfe/echarts#5136]
[

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mangoZT** [comment]
字是以省会城市为坐标  可在源码中调节
