### ISSUE TITLE
echarts提供的矢量地图资源是用什么工具制作的，想自定义map

### ISSUE THREAD

**Issue by zds-xiaoxianyu** [ecomfe/echarts#5137]
可以通过网站http://geojson.io/#map=8/29.011/117.169制作Map geojson吗，还是用arcmap生成？新手求教
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
从地图服务商抓取边界数据后脚本生成的

**Comment by fancylife** [comment]
> 从地图服务商抓取边界数据后脚本生成的

你好，这个脚本能够开源一下吗？我们想更新数据
