### ISSUE TITLE
表头的下拉框被echarts的div遮挡住了

### ISSUE THREAD

**Issue by ChanLight** [ecomfe/echarts#5146]
### One-line summary [问题简述]

在最近做的项目中 用了easy-ui的easyui-layout布局，文件类型为jsp，在easyui-layout的north中引入了表头文件<jsp:include page="/www/head/head1_selfs.jsp" />
然后在easyui-layout的center中引入了主体，但是主体的echarts遮挡住了表头的select下拉框，虽然遮挡住了却依然可以点击。我们没有找到解决方法

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]:谷歌 最新版
+ OS Version [操作系统类型和版本]:window 10

### Expected behaviour [期望结果]

不要覆盖select下拉框

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: '',
        subtext: ''
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            type: 'shadow'
        }
    },
    legend: {
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type: 'value',
        boundaryGap: [0, 0.01],
          axisLine: {
                lineStyle: {
                    color:"#1c1e20"
                }
            },
    },
    yAxis: {
        type: 'category',
        data: [],
         axisLine: {
                lineStyle: {
                    color:"#1f83e0"
                }
            },
    },
    series: [
    
        {
            name: 'number',
            type: 'bar',
            data: [],
                   itemStyle:{  
                                    normal:{color:'#43d3ff'}  
                                },
                                barMaxWidth:17,
        },
		
    ]
};

	myChart.setOption(option);


```

### Other comments [其他信息]

![git](https://cloud.githubusercontent.com/assets/26055697/23352571/e6c0e1d4-fd02-11e6-9f39-57c12d767d80.png)
![Uploading git.png…]()

**Comment by pissang** [comment]
这个问题跟 echarts 没有关系
