### ISSUE TITLE
license 问题

### ISSUE THREAD

**Issue by myzhan** [ecomfe/echarts#5151]
### One-line summary [问题简述]
你好，我在 locust 项目里面提交了一个 [PR](https://github.com/locustio/locust/pull/509/commits/6b4889e7515c53fdd39f1e415672a1bf49090562)，使用了 echarts 的源码。

发现两者的 LICENSE 并不兼容，locust 使用的是 MIT，请问这种情况下，可以继续使用 echarts 吗？

**Comment by pissang** [comment]
可以的

**Comment by myzhan** [comment]
@pissang thx～
