### ISSUE TITLE
柱状图的样式能不能自定义，有没有留配置接口

### ISSUE THREAD

**Issue by Shiwei-Zhang** [ecomfe/echarts#5156]
### One-line summary [问题简述]

柱状图的样式能不能自定义，有没有留配置接口

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:

+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![qq 20170228162910](https://cloud.githubusercontent.com/assets/19873166/23397392/4868bc42-fdd3-11e6-818b-052984902c9c.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
抱歉看不到你的图片。

**Comment by pissang** [comment]
可以把颜色设置成渐变

**Comment by Shiwei-Zhang** [comment]
柱状的样式可以自定义吗，在哪定义

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-bar.data.itemStyle
