### ISSUE TITLE
如何实现点击中国的某一个省，显示tooltip组件以及鼠标进入tooltip组件中点击？求实例

### ISSUE THREAD

**Issue by Fdango** [ecomfe/echarts#5164]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
tooltip.triggerOn 配置成click
