### ISSUE TITLE
运行源码中的test目录中的例子时报错：zrUtil.setAsPrimitive is not a function

### ISSUE THREAD

**Issue by gleams** [ecomfe/echarts#5170]
### One-line summary [问题简述]
clone 源码后，不能运行

`Uncaught TypeError: zrUtil.setAsPrimitive is not a function`，
我在zrender中没有找到`setAsPrimitive()`这个方法，把echart.js的207行`zrUtil.setAsPrimitive(this);`注释后才能正常显示。

### Expected behaviour [期望结果]
这是源码问题还是我的操作方式不对，请指教！谢谢

**Comment by pissang** [comment]
zrender 需要更新下
