### ISSUE TITLE
e3引入百度地图，bmap设置的参数能调出百度地图放大缩小的控件吗？

### ISSUE THREAD

**Issue by SynChron1zed** [ecomfe/echarts#5172]
![image](https://cloud.githubusercontent.com/assets/18717051/23500499/4c4c04b0-ff6b-11e6-9e40-4178ac33d198.png)

### One-line summary [问题简述]

![image](https://cloud.githubusercontent.com/assets/18717051/23500527/67c53bb2-ff6b-11e6-8874-0d8944cab471.png)
代码如上 怎么样才能消失控件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by SynChron1zed** [comment]
显示控件

**Comment by sevenen** [comment]
貌似不能，不过你可以去看百度地图的API，是可以做到的。
https://github.com/ecomfe/echarts/blob/c7b62850ef9efa928415a91ae77b42928b823be6/extension/bmap/README.md
http://developer.baidu.com/map/jsdemo.htm#b0_2

**Comment by SynChron1zed** [comment]
@sevenen 看了 可以调出来 但是没有效果 功能失效

**Comment by sevenen** [comment]
http://gallery.echartsjs.com/editor.html?c=xH1vI4KUqg 看这个示例

**Comment by SynChron1zed** [comment]
@sevenen  问题的关键应该是这个方法根本找不到 
![Uploading image.png…]()

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/23611417/2ef13e7c-02b2-11e7-9808-5af6417a93aa.png)
![image](https://cloud.githubusercontent.com/assets/18717051/23611443/5fc7dc4a-02b2-11e7-8c35-ac8171940db8.png)

**Comment by pissang** [comment]
需要在 setOption 之后才能 getModel()

**Comment by SynChron1zed** [comment]
@pissang  give you  100 points  tanks ！
