### ISSUE TITLE
tooltip能不能显示更详细的信息

### ISSUE THREAD

**Issue by kouguopeng** [ecomfe/echarts#5175]
### One-line summary [问题简述]
散点图
![image](https://cloud.githubusercontent.com/assets/22540859/23535596/43f0ac0a-fffa-11e6-8b6c-90c22d59d684.png)有没有办法在tooltips上显示更详细的信息

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以自定义 formatter
