### ISSUE TITLE
折线图，使用 setOption 更新数据，init 一次，发现如果是增加数据的话，线可以画出来。减少数据，相应的那个线并没有去掉

### ISSUE THREAD

**Issue by lansefengxinzi** [ecomfe/echarts#5180]
if (!myChart) {
            myChart = echarts.init(this.references.myRef);
        }
        const options = this.setLineBarOption();
        myChart.setOption(options);

**Comment by pissang** [comment]
默认 setOption 是合并的，如果需要删除系列或者组件，使用非合并的方式 `setOption(options, true)`
