### ISSUE TITLE
echart在一个100%宽度div中显示的是100px而div的实际比这大很多

### ISSUE THREAD

**Issue by Robinlight** [ecomfe/echarts#5186]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
弹出的响应echart

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
需要在 div 准备好（能获取到 clientWidth 和 clientHeight）后才能 init，或者在 div 高宽发生改变时调用 resize
