### ISSUE TITLE
echarts初始化后canvas没有充满外部容器，如何自定义宽高

### ISSUE THREAD

**Issue by jx-zhang** [ecomfe/echarts#5187]
### One-line summary [问题简述]
echarts初始化后canvas没有充满外部容器
比如说宽度沾满了，但是高度还有很多留白
手动修改高度之后，出现了拉伸失真的现象

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望canvas可以充满外部容器，宽高可以自定义。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
请提供代码

**Comment by zhuhuiwen** [comment]
> 功能说明：
>>可视区的宽度-侧边栏的宽度；
>>可视区的高度-头部的高度；这边的值按需求进行设置
>>调用jq的css进行相应的设置即可；
```js
     var mainId = document.getElementById("main");
	//根据可视区进行自适应宽高
     var myChartContainer = function () {
	var rightW = Number($(window).width())-Number($(".leftbar").width());
	var topH = Number($(window).height())-190;
	$(mainId).css({
		"width":rightW,
		"height":topH
	 });
    };
    myChartContainer();
```

**Comment by navono** [comment]
我也遇到同样的问题。echart外层的DOM节点的高度与echart显示的_echarts_instance_的div高度差了很多。在option.grid中配置height也不对，会导致坐标偏移不正确，zoom的偏移也不正确。
