### ISSUE TITLE
echarts3地图下钻

### ISSUE THREAD

**Issue by zxy12666** [ecomfe/echarts#5188]
### One-line summary [问题简述]
1.请问echarts3想做一个全国下钻到省份的功能需要下载全部的省份的地图文件吗，有没有一个合并的js文件下载。
2.地图上的坐标点是否可以根据省份筛选，点击进省份后只展示该省份内的数据点。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
1. 没有合并的文件
2. 自行筛选

**Comment by Eric611** [comment]
类似的需求有很多，咱们不能提供一个合并的js简单版本供大家使用吗？多为这些使用者考虑，才能扩大咱们产品的使用范围啊！
