### ISSUE TITLE
echarts table 对safari不兼容吗？设置的宽度不能正常显示

### ISSUE THREAD

**Issue by jowang2016** [ecomfe/echarts#5192]
设置了echarts table列的宽度，但是safari中样式显示错误，是不兼容吗？

**Comment by pissang** [comment]
能具体描述么？

**Comment by jowang2016** [comment]
表头和对应的列错位

**Comment by jowang2016** [comment]
我的这个问题就是这种情况，https://github.com/ElemeFE/element/pull/2207 但是没有理解她的解决办法，她的colgroup好像是在源码中改的，所以我不知道在页面中应该调用什么命令，这个问题应该是一个bug，我的element table不仅表头和列在safari中不对应，底边滚动条也是失灵的，但是在chrome中一切都正常，，希望能够尽快修补这个bug！

**Comment by pissang** [comment]
element 的 table 跟 echarts 有啥关系？

**Comment by jowang2016** [comment]
写错了，和echarts没有关系，element table在Safari 中表头和对应的列错位，下滚动条失灵，是代码bug吗？应该如何解决？

**Comment by pissang** [comment]
建议去 https://github.com/ElemeFE/element 反馈

**Comment by jowang2016** [comment]
哦！！！刚发现是echarts！sorry！！

**Comment by jowang2016** [comment]
顺便问一下，vue项目中的echarts怎么实现响应式呢？
页面中有几个echarts表格，对其中一个调用window.onresize=function(){mychart.resize()}，是可以的，但是这个页面上的几张表如果都使用这个函数，就无法实现响应式了。
我想正确的思路应该是在页面上同时对这几个表格进行resize，可是这几张表都是通过组件形式调用的，如何在主页面上获得这些表的实例呢？
之前有推荐过vue-echarts，我试了一下，并不能用。
如果方便的话，希望能给点建议。

**Comment by pissang** [comment]
总的来说就是有发生容器大小发生改变的时候就调用 `chart.resize()` 更新
