### ISSUE TITLE
已经构建了echarts的工程，如何运行测试用例？

### ISSUE THREAD

**Issue by logicouter** [ecomfe/echarts#5194]
### One-line summary [问题简述]
我改了点代码，想看看效果。已经npm install和webpack构建了工程，如何执行/test/下的测试html？打开这些html显示文件404:
Failed to load resource: net::ERR_FILE_NOT_FOUND
path.js Failed to load resource: net::ERR_FILE_NOT_FOUND
Path.js Failed to load resource: net::ERR_FILE_NOT_FOUND
Image.js Failed to load resource: net::ERR_FILE_NOT_FOUND
Text.js Failed to load resource: net::ERR_FILE_NOT_FOUND

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
下载 https://github.com/ecomfe/zrender 到 echarts 的同级目录
