### ISSUE TITLE
如何绘制不关心大小，只关心有无的饼图？

### ISSUE THREAD

**Issue by retsyo** [ecomfe/echarts#5196]
每一个同心圆环，表示的是一种水果，如果有（数据表里面是1）则用颜色填充，如果没有该水果保留黑色

所有人均分360度

这种图叫什么呢？如果是饼图，可以做出来吗？

谢谢
![default](https://cloud.githubusercontent.com/assets/7960913/23603484/6e0cb2b6-0290-11e7-9c4b-3347a06af52a.png)
![default](https://cloud.githubusercontent.com/assets/7960913/23603482/6b759658-0290-11e7-930f-349e3c7cf303.png)

**Comment by pissang** [comment]
可以用饼图模拟，把 0 数据的扇形颜色设成 transparent 就行了
