### ISSUE TITLE
坐标轴标签axisLable无法自定义样式

### ISSUE THREAD

**Issue by candylcbi** [ecomfe/echarts#5204]
### One-line summary [问题简述]
坐标轴标签axisLable无法自定义样式，我要做一个横向的条形图，左侧的坐标轴是说明，坐标轴说明文字上有一定的样式要求，目前axisLable提供了formatter自定义内容，但内容无法像tooltips的formatter一样可以添加html标签，导致只能简单的设置字体、颜色、字号，不能进行个性化的样式设置

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新版本
+ Browser version [浏览器类型和版本]:所有
+ OS Version [操作系统类型和版本]:所有

### Expected behaviour [期望结果]
axisLable能像tooltips的formatter一样可以添加html标签设置样式

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
除了 tooltip 其它的 label 目前都不支持 html

**Comment by candylcbi** [comment]
axisLable什么时候能支持html标签？目前项目做条形图需要
