### ISSUE TITLE
echarts+liquidFill插件导致cpu占用率过高问题

### ISSUE THREAD

**Issue by weizhxa** [ecomfe/echarts#5205]
###  [问题简述]
echarts+liquidFill结合时，cpu占用过高，尤其是每增加一个水球，占用率上升5%左右。使用最新的echarts+liquidFill仍然如此。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts 3
+ Browser version [浏览器类型和版本]:chrome 45.0，firefox 18+，ie10+
+ OS Version [操作系统类型和版本]:win xp，win 10， win 8.1

### Expected behaviour [期望结果]
希望得到关于此bug的改进建议。

### ECharts option [ECharts配置项]

```javascript
option = {
        正常配置即可
}

```

**Comment by pissang** [comment]
这个不是 bug， cpu 占用率升高是因为 liquidfill 有动画，动画关闭就可以了

**Comment by weizhxa** [comment]
这个是个bug，echarts关于动画的代码是使用的这段代码：
_startLoop: function () {
	            var self = this;

	            this._running = true;

	            function step() {
	                if (self._running) {

	                    requestAnimationFrame(step);

	                    !self._paused && self._update();
	                }
	            }

	            requestAnimationFrame(step);
	        },
而这段代码就会造成cpu过高问题。可以使用chrome的profile分析定位。
而具体解决办法可以google：requestAnimationFram cpu high
解决方法例如：http://code.bytespider.eu/post/20484989272/requestanimationframe-and-html5-game-loops
或者：http://code.bytespider.eu/post/20484989272/requestanimationframe-and-html5-game-loops
代码基本如下：
var skipTicks = 1000 / 30, nextTick = new Date().getTime();
function run(time) {
    while (time > nextTick) {
        update();
        draw();
 
        nextTick += skipTicks;
    }
};
