### ISSUE TITLE
echarts3 如何固定Y轴分割段数

### ISSUE THREAD

**Issue by licc779885** [ecomfe/echarts#5209]
不管数据如何变化，Y轴分割段数强制为5

**Comment by freegg** [comment]
chart.setOption({yAxis:[{max:leftY.max,min:leftY.min,interval:5}]});   根据返回数据的最大值，最小值，重新生成 最大值，最小值，分段数

**Comment by licc779885** [comment]
恩，好的，非常感谢您的讲解
