### ISSUE TITLE
能不能所有的formatter都能解析html标签？

### ISSUE THREAD

**Issue by yummy201111** [ecomfe/echarts#5212]
### One-line summary [问题简述]

tooltip里formatter能解析html标签，很方便自定义样式。但是legend xAxis yAxis等到其它里的formatter不行。能不能formatter都可以解析呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行，未来会考虑支持

**Comment by git-Where** [comment]
什么时候能支持所有的formatter解析html标签呢，不能个性化定制，模板太生硬。
