### ISSUE TITLE
自定义symbol时引入透明svg文件，如何支持颜色的配置？

### ISSUE THREAD

**Issue by lefreet** [ecomfe/echarts#5213]
### One-line summary [问题简述]
自定义symbol时引入透明svg文件，如何支持颜色的配置？

正常引用`'rect'`能添加背景色。自定义的话不行。能否支持在svg底部定义颜色背景？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
series: {
symbol: 'image://./static/1.svg'
itemStyle: {
  normal: {
   color: '#000'
 }
}
}
}

```

**Comment by pissang** [comment]
直接引用 1.svg 相当于引用了一张图片，是无法修改颜色的，可以把 1.svg 的 path 提取出来把 symbol 设成 `path://xxxxx`

**Comment by lefreet** [comment]
明白了，多谢。

**Comment by maxio-yu** [comment]
path后边怎么配置颜色？

**Comment by AllanSmithX** [comment]
@pissang @lefreet  同楼上，想问下指定symbol为svg，path中如何设置颜色相关属性啊？能否给个小例子啊？

**Comment by chengmin** [comment]
> path后边怎么配置颜色？

颜色不需要在path后面配置，直接设置 markPoint.itemStyle.color 的颜色就可以了
参考：[http://www.echartsjs.com/option.html#series-bar.markPoint.itemStyle.color](url)

**Comment by YingML** [comment]
path是透明空心圆的情况下，线的端点会出现在icon中心位置，如何设置线的端点不出现在icon的中心位置
