### ISSUE TITLE
多图布局怎么玩，没有效果啊

### ISSUE THREAD

**Issue by iamziyue** [ecomfe/echarts#5216]
### One-line summary [问题简述]
这个页面：http://gallery.echartsjs.com/editor.html
有一个多图布局。但我试了一下并没有效果，不知道是不是我那儿操作不对。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
在一个容器里面放多个图表，现在暂时采用的是多个容器自己布局的。我看Echarts有现成的多图布局，但是并不成功。

### ECharts option [ECharts配置项]

```javascript
option = [{
    xAxis: {
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
    },
    yAxis: {},
    series: [{
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
    }]
}, {
    xAxis: {
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
    },
    yAxis: {},
    series: [{
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
    }]
}];
```

**Comment by pissang** [comment]
是 options = [{ ... }, { ... }]
