### ISSUE TITLE
请问China.js文件如何像echarts似的引入cdn版本，目前只发现有http协议的

### ISSUE THREAD

**Issue by 5abc** [ecomfe/echarts#5220]
### One-line summary [问题简述]

cdn引入China.js

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
http://echarts.baidu.com/asset/map/js/china.js

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没有

**Comment by 5abc** [comment]
嗯嗯。
