### ISSUE TITLE
echarts 3 官方网站Gallery 页面经常打不开

### ISSUE THREAD

**Issue by yangqiang5156** [ecomfe/echarts#5221]
### One-line summary [问题简述]

echarts 3 官方网站Gallery 页面经常打不开；

console
ownload the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
explore.html#sort=rank~timeframe=all~author=all:1 XMLHttpRequest cannot load http://static.tieba.baidu.com/tb/error.html?tc=17086473450473613066030816. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gallery.echartsjs.com' is therefore not allowed access.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢反馈，我们会修复这个问题
