### ISSUE TITLE
我想用js将echarts生成的图形变成base64 怎么实现那 

### ISSUE THREAD

**Issue by jindada** [ecomfe/echarts#5224]
### One-line summary [问题简述]
我想用js将echarts生成的图形变成base64 怎么实现那 

我的做法是将canvas变成图片 然后转成base64 但是转成的图片都是纯黑色的填充
我看了一下这部分的源码 还是没看懂如何实现的

**Comment by pissang** [comment]
chart.getDataURL()

**Comment by jindada** [comment]
谢谢 我现在用的react-echarts 获取不到chart这个对象 从dom层面能实现吗

**Comment by pissang** [comment]
不建议从 dom 层面实现，你可以跟 react-echarts 的作者提这个 feature request
