### ISSUE TITLE
示例gallery页面无法访问

### ISSUE THREAD

**Issue by jinghun1999** [ecomfe/echarts#5232]
### One-line summary [问题简述]

**# http://gallery.echartsjs.com/explore.html 资源无法访问了。JS错误。。。。。**

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/5221
