### ISSUE TITLE
echarts3在绘制南丁格尔玫瑰图能把外圆的线条显示出来吗，echarts2是绘制出现就默认显示出来了

### ISSUE THREAD

**Issue by hpxmk** [ecomfe/echarts#5233]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以常使用 http://echarts.baidu.com/option.html#graphic.elements-circle 添加圆
