### ISSUE TITLE
颜色渐变问题

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#5236]
### One-line summary [问题简述]
![image](https://cloud.githubusercontent.com/assets/22878190/23778872/d7e028aa-0577-11e7-9cb1-641b2afd6628.png)

![image](https://cloud.githubusercontent.com/assets/22878190/23778843/a77968ac-0577-11e7-8c3e-0b12f9549a15.png)

线性颜色渐变中有一句话，“相当于在图形包围盒中的百分比”指的是上图中的div的宽高还是pie本身的宽高？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
是扇形的宽高

**Comment by chingyaochan** [comment]
感觉对于扇形从圆心沿半径往外的径向渐变变得好难做，每个扇区都有自己的包围盒，起点还不一样。echarts2就很容实现了，请问echarts3有什么好的解决方案？
