### ISSUE TITLE
echarts3.0 曲线图，当纵轴数据突然变大，线条往回走

### ISSUE THREAD

**Issue by wayss000** [ecomfe/echarts#5239]
### One-line summary [问题简述]

曲线图，纵轴数据点的值大部分是0，突然一个点的纵轴的值是17306.画图出现问题了。

![1](https://cloud.githubusercontent.com/assets/21314261/23785518/082d18bc-05a3-11e7-8ef4-2fea8a9978d9.png)

数据是这样的，横轴是时间，纵轴是当前时间的值。
![2](https://cloud.githubusercontent.com/assets/21314261/23785555/3d8a9fd4-05a3-11e7-9b23-797aae3be3d5.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: Echarts 3.0
+ Browser version [浏览器类型和版本]: chrome 45
+ OS Version [操作系统类型和版本]:Windows XP SP3

### Expected behaviour [期望结果]
1. 我想知道这个是我的问题，还是目前现有的bug。
2. 有什么办法解决吗？

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.smoothMonotone

**Comment by wayss000** [comment]
OK，已经解决。谢谢。
