### ISSUE TITLE
Javascript调用echart在服务器端运行的问题

### ISSUE THREAD

**Issue by sayhier** [ecomfe/echarts#5240]
### One-line summary [问题简述]

我将HTML和echarts.min.js放在本机同一个文件夹下，双击HTML就可以显示运行了。但如果把这两个放到服务器端，通过返回HTML来访问这个页面Echart却不能显示？请问如何做才能正常显示呢

服务器端我使用的web.py, HTML和echart.mini.js放在template文件夹下，通过image方法返回，代码如下

`import web

urls = (
    '/img', 'image'
)

render = web.template.render('templates')

class image:
    def GET(self):
        return render.image()

class index:
    def GET(self):
        return "Hello, world!"

if __name__ == "__main__":
    app = web.application(urls, globals())
    app.run()`

### Version & Environment [版本及环境]
这里没问题，最简单的例子

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

第一图访问HTML不显示echart，而第二图在本地直接双击运行可以显示
![1](https://cloud.githubusercontent.com/assets/21240790/23787029/fecb501a-05aa-11e7-8d99-8885b590b5ca.JPG)
![2](https://cloud.githubusercontent.com/assets/21240790/23787036/04aa8f3c-05ab-11e7-8bb7-85ef801a3512.JPG)

**Comment by pissang** [comment]
非 echarts 问题
