### ISSUE TITLE
echarts3笛卡尔热力图数据量超过3000个点的时候，刷新很慢

### ISSUE THREAD

**Issue by xiejian-sword** [ecomfe/echarts#5241]
### One-line summary [问题简述]
笛卡尔热力图： x轴200+，y轴60+。
逐行添加数据，到15行左右。。。重绘数据有明显的延迟感，从空白到绘制完成大概1秒钟。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: 版本 53.0.2785.116 m (64-bit)
+ OS Version [操作系统类型和版本]: win7 64位

### Expected behaviour [期望结果]
是否能通过设置或者优化提高性能？还是性能问题？

### ECharts option [ECharts配置项]

```javascript
option = {
					tooltip: {
						show: false
					},
					xAxis: {
						type: 'category',
						data: frequency,
						splitArea: {
							show: false
						}
					},
					yAxis: {
						type: 'category',
						data: time,
						splitArea: {
							show: false
						}
					},
					visualMap: {
				        min: -100,
				        max: 0,
				        hoverLink: false,
				        calculable: true,
				        orient: 'horizontal',
				        left: 'right',
				        top: 'top',
				        color: ['#B00000', '#FF5000', '#D8FF00', '#00FEE5', '#0055FF', '#00009C'],
				        text: ['0dBm', '-100dBm']
					},
					series: [{
						name: 'Punch Card',
						type: 'heatmap',
						data: finalData,
						silent: true
					}]
				};

```

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=heatmap-large-piecewise 这个例子里已经有 2w 条数据了

**Comment by xiejian-sword** [comment]
感谢您的答复，上面2w条的数据并不能满足对性能的要求。因为本地需要持续的刷新数据。我目前采用原生canvas进行绘制没有问题。  可能是echarts绑定了太多的鼠标事件等等导致的某些问题吧，本地项目不需要知道每个点的信息。
