### ISSUE TITLE
地图dispatchAction跳动

### ISSUE THREAD

**Issue by shenmegui9** [ecomfe/echarts#5243]
### One-line summary [问题简述]
地图用dispatchAction每个区域循环不断跳动1小时浏览器就自动关闭，显示如下
![capture](https://cloud.githubusercontent.com/assets/25633098/23790452/0ec1c79c-05ba-11e7-8ad1-46b3dffc6f02.PNG)

不知道有没有方法可以解决？
另外，这是用ng-echarts封装在angularjs里用的不知道这有没有影响？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: ie11
+ OS Version [操作系统类型和版本]: win7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Cryice** [comment]
@shenmegui9 大神，请教，能否共享一下地图跳动的写法
