### ISSUE TITLE
y轴从36-37.2，36与37是整数，想保留一位小数

### ISSUE THREAD

**Issue by xiefangzhenz** [ecomfe/echarts#5244]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
`axisLabel.formatter`
