### ISSUE TITLE
双类目轴如何创建

### ISSUE THREAD

**Issue by qinlaodexiaosan** [ecomfe/echarts#5248]
### One-line summary [问题简述]
柱状图 如何实现 y轴 双类目轴，共用x轴作为数据轴

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
参考 http://echarts.baidu.com/gallery/editor.html?c=scatter-punchCard
