### ISSUE TITLE
生成柱状图,如何针对每一个bar设置一个颜色.求大神解答

### ISSUE THREAD

**Issue by ashuai5061** [ecomfe/echarts#5249]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-bar.data.itemStyle.normal.color
