### ISSUE TITLE
曲线图的位置问题

### ISSUE THREAD

**Issue by tianr1190** [ecomfe/echarts#5253]
当标题和图例比较长时，图例会盖住部分坐标区内。
如图：
![image](https://cloud.githubusercontent.com/assets/19337143/23846543/e4172d60-0808-11e7-959d-ff1fbd6d2baf.png)

请问如何修改曲线图坐标系在canvas 的上下位置

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
grid.top 设置得大点

**Comment by tianr1190** [comment]
谢谢，用grid.top设置了就好了。
