### ISSUE TITLE
map的tooltip轮播，自动跳动显示有玩的么？

### ISSUE THREAD

**Issue by SynChron1zed** [ecomfe/echarts#5255]
### One-line summary [问题简述]

有大神玩过么

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=map-locate

**Comment by SynChron1zed** [comment]
感谢 参考了下 弄出来 但是体验效果很差

**Comment by shenggen1987** [comment]
自己解决了，谢谢，有需求的同学可以见的我demo https://shenggen1987.github.io/echarts-demo/#/ vue2.0+webpack+echarts @SynChron1zed

**Comment by pissang** [comment]
@shenggen1987 很赞！

**Comment by SynChron1zed** [comment]
@shenggen1987 很早就搞出来了 😄
