### ISSUE TITLE
如何实现图表部分背景变色

### ISSUE THREAD

**Issue by dengdairiluo** [ecomfe/echarts#5256]
### One-line summary [问题简述]

![image](https://cloud.githubusercontent.com/assets/10458959/23847831/37202f7e-080f-11e7-98ce-d9f872bde31c.png)

如图所示，如何让部分变灰

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.markArea
