### ISSUE TITLE
markPoint的文档错误

### ISSUE THREAD

**Issue by weconquered** [ecomfe/echarts#5258]
data: [
    {
        name: '最大值',
        type: 'max'
    }, 
    {
        name: '某个坐标',
        coord: [10, 20]
    }, {
        name: '固定 x 像素位置',
        yAxis: 10,
        x: '90%'
    }, 
    {
        name: '某个屏幕坐标',
        x: 100,
        y: 100
    }
]

### Version & Environment [版本及环境]
+ ECharts version [3]:
+ Browser version [chrome]:
+ OS Version [Mac os]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
错误的地方是？
