### ISSUE TITLE
关于bmap的选项查看

### ISSUE THREAD

**Issue by sjsdfg** [ecomfe/echarts#5261]
### One-line summary [问题简述]
我想在echarts中使用百度地图，
在里面有多个示例都使用了bmap的属性，
但是配置项文档中没有对该属性的文档说明，
如果我想查阅对应的文档我应该去哪里查阅呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/tree/master/extension/bmap
