### ISSUE TITLE
Is there any way to define multiple tooltips? 

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#5262]
Version: 3.4.0

I have a chart with multiple series types: 
![image](https://cloud.githubusercontent.com/assets/561365/23859285/6d95cbd8-0803-11e7-9473-106bbf9f6220.png)

The issue is that I'd like to use "axis" type of tooltip for the bottom line chart and "item" type for the top bar chart. Is there any way to do this? I've tried using [] in tooltips but that doesn't seem to work. Using formatter function works to customize tooltip content, however, it doesn't allow to customize tooltip type such as axis, item, shadow, line,.. 

Thanks!

**Comment by kener** [comment]
Is it possible to use 2 charts to make it ? 2 charts up and down, and connect them together to share the same legend event ？@pissang @100pah 
[http://echarts.baidu.com/api.html#echarts.connect](http://echarts.baidu.com/api.html#echarts.connect)

**Comment by jarben** [comment]
Good point @kener! Also made me do a bit of experimentation and then I noticed in one of the examples that it is actually possible to define different tooltips for different series! That solves my issue, it would be great if this is part  of docs:)

**Comment by 100pah** [comment]
This feature has been supported in v3.5.

See <https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-brush>.

**Comment by lyz19890927** [comment]
I tried a lot, found tooltip in series only works when the global tooltip object is set(even if empty).

See [http://gallery.echartsjs.com/editor.html?c=xr1ZLORolM&v=1](url)
