### ISSUE TITLE
折线图纵坐标的刻度和数据不匹配

### ISSUE THREAD

**Issue by hengheng0haha** [ecomfe/echarts#5264]
### One-line summary [问题简述]
官方示例里截的图(http://echarts.baidu.com/demo.html#line-stack)
![image](https://cloud.githubusercontent.com/assets/8019065/23882633/e97e0eb0-089c-11e7-9e8c-af1934db921d.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:Chrome 56.0.2924.87 (64-bit)
+ OS Version [操作系统类型和版本]:Mac OS10.12.3

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
去掉stack
