### ISSUE TITLE
在2.x版本中可用，升级成3.x版本后出现的默认值问题

### ISSUE THREAD

**Issue by lampsonlong** [ecomfe/echarts#5266]
### One-line summary [问题简述]
往option的yAxis的max写入默认值'auto'时，2.x版本会执行默认'auto'效果，但是在3.x版本中y轴刻度会消失。

option={
yAxis: {
            max: 'auto'
          },
}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.x（最新版也不行）
+ Browser version [浏览器类型和版本]:chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
填写默认值也能达到默认值的效果。

### ECharts option [ECharts配置项]

```javascript
option = {
yAxis: {
            max: 'auto'
          },
}

```

**Comment by pissang** [comment]
max 取成 null 就行
