### ISSUE TITLE
饼图中的扇形描述可以添加对应项的具体数值吗？即图例与扇形描述不一致

### ISSUE THREAD

**Issue by wpp5354** [ecomfe/echarts#5269]
### One-line summary [问题简述]

饼图中的文字后面可以加具体项对应的数值吗？
如下图红色框中类似，谢谢！

![default](https://cloud.githubusercontent.com/assets/9841553/23893690/6f1f0730-08da-11e7-966e-2211fd4bed20.png)

**Comment by pissang** [comment]
用 `label.normal.formatter` 就行

**Comment by wpp5354** [comment]
@pissang Thanks
