### ISSUE TITLE
setOption第二个参数 notMerge 合并与不合并有什么区别，如果不合并 getOption是获取新的setOption还是历史的setOption值

### ISSUE THREAD

**Issue by soulyale** [ecomfe/echarts#5273]
setOption第二个参数 notMerge 合并与不合并有什么区别，

如果不合并 getOption是获取新的setOption还是历史的setOption值

**Comment by pissang** [comment]
合并时在之前的 option 基础上更新，不合并是直接替换

**Comment by huainanhai** [comment]
@pissang 为什么写了ontMerge : true (echart3.0)没有用。并且我删除了series里面的数据 图竟然没有更新呢
