### ISSUE TITLE
大神，您好，请问关于地图坐标是怎么取的，我用百度地图的坐标不对呀？

### ISSUE THREAD

**Issue by hcweb** [ecomfe/echarts#5277]
如果用平台的坐标是对的，但是我用百度地图取得坐标就不对了，`
'长治': [112.8625,36.4746],
				    '阳泉': [113.4778,38.0951],
				    '青岛': [120.4651,36.3373],
				    '韶关': [113.7964,24.7028],
				    '毕节': [27.4085,105.3333230000],
				    '定西': [35.5860,104.6266380000],
				    '阜阳': [32.8958,115.8213890000],`后面这几个就不对 跑到地图外面去了！

**Comment by pissang** [comment]
第一个数值是经度，第二个数值是纬度，不知道为什么你后面几个翻了
