### ISSUE TITLE
如何让热点图上每个格子里显示字符串

### ISSUE THREAD

**Issue by Freewayy** [ecomfe/echarts#5279]
### One-line summary [问题简述]

热点图传入数据时的格式是
var data = [[0,0,5],[0,1,1],[0,2,5],[0,3,0],[0,4,0]]
这样的格式，数组里每个元素是3个数字，前两个是坐标，第三个是值，怎么把文字当作第三个值传入，并且显示在热点格子里呢，或者能否通过判断传入的数字来显示文字到热点格子里

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以设置 label.normal.formatter

**Comment by Freewayy** [comment]
你好Yi Shen，那个我用过，只能把所有格子的文字都设置成统一的文字吧，能够根据数值的不同显示不同的文字么

**Comment by pissang** [comment]
formatter  的用处就是根据不同的数据生成不同的文字啊
