### ISSUE TITLE
echarts下拉框插件

### ISSUE THREAD

**Issue by qinlaodexiaosan** [ecomfe/echarts#5281]
### One-line summary [问题简述]
我的图表现在需要一些下拉框作为查询条件，来改变视图数据显示，请问现在有这样的例子？？？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liaohui1080** [comment]
你确定需要图表来生成 下拉菜单吗, 感觉这样得不偿失

**Comment by pissang** [comment]
没有，建议根据自己业务需求实现

**Comment by qinlaodexiaosan** [comment]
感谢您的回信，前段时间业务需求是要针对（柱状图数据量大，且有下拉框）添加搜索条件 来帅选数据，但是用户希望可以将图列放在条件后面，可是那样一个是搜索条件div+html构建的，而用echarts的柱状图，会出现在柱状图下拉框移动时，而搜索条件没有跟着动，而出现了搜索条件在柱状图下面，影响显示！

在 2017-03-19 14:10:37，"Yi Shen" <notifications@github.com> 写道：


没有，建议根据自己业务需求实现

**Comment by liaohui1080** [comment]
@qinlaodexiaosan这个太简单了, 获取图表区域的大小, 在获取下拉菜单的 宽度,  用图表宽度 减去 下拉菜单的宽度, 这样就获取 下拉菜单的 偏移距离了

**Comment by qinlaodexiaosan** [comment]
谢谢您的回信！

在 2017-03-26 13:42:26，"liaohui" <notifications@github.com> 写道：


@qinlaodexiaosan这个太简单了, 获取图表区域的大小, 在获取下拉菜单的 宽度, 用图表宽度 减去 下拉菜单的宽度, 这样就获取 下拉菜单的 偏移距离了
