### ISSUE TITLE
怎么配置echarts的dataZoom的高度

### ISSUE THREAD

**Issue by Cyycl** [ecomfe/echarts#5284]
### One-line summary [问题简述]
想将echarts的dataZoom的高度调低，效果如下：
![image](https://cloud.githubusercontent.com/assets/9523185/23989994/939d619c-0a6f-11e7-9db5-b645e26c4658.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts@3.3.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![image](https://cloud.githubusercontent.com/assets/9523185/23989994/939d619c-0a6f-11e7-9db5-b645e26c4658.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by MoonBall** [comment]
```
option = {
    dataZoom: {
          top: 1000,
          bottom: 20,
    },
}
```
就是需要先计算好位置

**Comment by pissang** [comment]
可以设置 height 吧？

**Comment by MoonBall** [comment]
可以的！文档《配置项手册》里没有 width/height；在《教程-ECharts组件的定位和布局》里有一般规则。
