### ISSUE TITLE
bmap.js加载失败

### ISSUE THREAD

**Issue by tonyguan1981** [ecomfe/echarts#5293]
### One-line summary [问题简述]
在加载bmap.js时出错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0 
+ Browser version [浏览器类型和版本]:chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]:window 7

### Expected behaviour [期望结果]
能引入bmap.js正常

### ECharts option [ECharts配置项]

```javascript
option = {
  // 加载 bmap 组件
    bmap: {
        // 百度地图中心经纬度
        center: [120.13066322374, 30.240018034923],
        // 百度地图缩放
        zoom: 14,
        // 是否开启拖拽缩放，可以只设置 'scale' 或者 'move'
        roam: true,
        // 百度地图的自定义样式，见 http://developer.baidu.com/map/jsdevelop-11.htm
        mapStyle: {}
    },
    series: [{
        type: 'scatter',
        // 使用百度地图坐标系
        coordinateSystem: 'bmap',
        // 数据格式跟在 geo 坐标系上一样，每一项都是 [经度，纬度，数值大小，其它维度...]
        data: [ [120, 30, 1] ]
    }]
}

```

### Other comments [其他信息]

线上实例http://oneview.sanfi.com/general/wxview/customer/Echarts/example2.php
![image](https://cloud.githubusercontent.com/assets/24726553/24068464/4221fb96-0bca-11e7-97c7-c8d8861186b3.png)

**Comment by pissang** [comment]
加载 https://github.com/ecomfe/echarts/blob/master/dist/extension/bmap.js 这个打包后的文件

**Comment by tonyguan1981** [comment]
还是不行呀。
