### ISSUE TITLE
多个(三个)pie  其中data有重名时 颜色无法正常获取

### ISSUE THREAD

**Issue by n59yl** [ecomfe/echarts#5294]
### One-line summary [问题简述]

多个(三个)pie  其中data有重名时 颜色无法正常获取

### ECharts option [ECharts配置项]
在gallery上写了个栗子
http://gallery.echartsjs.com/editor.html?c=xB1nf3vcol&v=1

**Comment by n59yl** [comment]
对了 增加到  4个 5个 6个 7个 pie的时候 也都是第三个的颜色获取不对....本以为第六个也会出问题..

**Comment by pissang** [comment]
你调色盘总共给了两个颜色，有四个不同的名字，肯定会有多个名字颜色重复，我们又不知道你到底什么数据是“不同”，什么数据是“相同”

**Comment by changbb** [comment]
请问楼主解决了吗？
