### ISSUE TITLE
想让漏斗图 图表填满整个canvas，需要怎么做？

### ISSUE THREAD

**Issue by zhoulinxiang** [ecomfe/echarts#5295]
如下图，想要漏斗图图表 顶住canvas上下左右的边 需要怎么做？在文档中找不到相关的配置项。。
![image](https://cloud.githubusercontent.com/assets/4335918/24078837/b3aed22c-0cb3-11e7-8a03-725a3bb39709.png)

**Comment by CeleKing** [comment]
http://echarts.baidu.com/demo.html#funnel
看这个例子里 设置series里的 top bottom 以及 width的百分比就可以填满了

**Comment by zhoulinxiang** [comment]
抱歉了，当时在配置文档里没找到有这个配置项，还以为没有这个配置项，麻烦你了

![image](https://cloud.githubusercontent.com/assets/4335918/24080362/9ec225e2-0cd8-11e7-8c70-481f8e2c4570.png)
