### ISSUE TITLE
环形Graph图表里，怎么设置鼠标悬停在连线上时突显示这个连线和节点？

### ISSUE THREAD

**Issue by CeleKing** [ecomfe/echarts#5296]
### One-line summary [问题简述]
环形Graph图表里，怎么设置鼠标悬停在连线上时这个连线以及连线两端对应的节点保留颜色，其他连线以及节点颜色变暗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-graph.focusNodeAdjacency

**Comment by CeleKing** [comment]
@pissang 我想要的效果是悬停到连线时候的效果不是focusNodeAdjacency这种悬停到nodes节点上的效果
