### ISSUE TITLE
请问如何去除中国地图上各省份之间的边框线，只留大公鸡

### ISSUE THREAD

**Issue by TJ-strange** [ecomfe/echarts#5298]
### One-line summary [问题简述]
想只要大公鸡的轮廓，但是各省份直接有边框线，把borderWidth设置为0之后不行，查了下官方文档没看到解决方法。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4
+ Browser version [浏览器类型和版本]:谷歌浏览器
+ OS Version [操作系统类型和版本]:Windows10

### Expected behaviour [期望结果]

 求大神告知如何去掉省份之间的边框线

### ECharts option [ECharts配置项]

```javascript
option = {
   tooltip: {
            trigger: 'item',
            formatter: '{b}'
        },
        series: [
            {
                name: '中国',
                type: 'map',
                mapType: 'china',
                label: {
                    normal: {
                        show: false
                    },
                    emphasis: {
                        show: false
                    }
                },
                itemStyle: {
                    normal: {
                        areaColor: '#56ADA4',
//                        color:'#ccc',
//                        borderColor: '#ccc',
                        borderWidth:1
                    },
                    emphasis: {
                        show:false
                    }
                },
                data:[
                    {name:'广东'}
                ]
            }
        ]
}

```

**Comment by TJ-strange** [comment]
对不住各位大神了，新人的问题没有含金量。不能设置边框的话，我把边框颜色和地图区域颜色设置成一样，边框宽度设为1就行了。
itemStyle: {
                    normal: {
                        areaColor: '#56ADA4',
                        borderColor: '#56ADA4',
                        borderWidth:1
                    },
                    emphasis: {
                        show:false
                    }
                },

**Comment by mangoZT** [comment]
这个问题还是有含义的  如果地图不是色块而是纹理背景的话  就达不到去除边框的效果
