### ISSUE TITLE
tooltip 想要制作悬浮窗y一直在position 0%, x希望和鼠标一样

### ISSUE THREAD

**Issue by AntiMoron** [ecomfe/echarts#5300]
### One-line summary [问题简述]

tooltip 想要制作悬浮窗y一直在position 0%, x希望和鼠标一样.

目前我知道的配置项是
```
tooltip: {
    trigger: 'axis',
    position: [x, '0%']
}
```
但是那个x值我不知道怎么获取，
还有就是可不可以达到效果：

```
tooltip: {
    trigger: 'axis',
    position: [undefined, '0%'] // <---- undefined就是default值？
}
```

还有我现在
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by AntiMoron** [comment]
类似物： https://github.com/ecomfe/echarts/issues/5318

**Comment by pissang** [comment]
position 可以是一个回调函数，这个函数第一个参数就是默认的 x，y

**Comment by AntiMoron** [comment]
@pissang  多谢。
```
tooltip : {
                trigger: 'axis',
                position: (point, params, dom) => {
                    this.selectEvent.emit(params);
                    return [point[0] - (0.5 * dom.offsetWidth), 0];
                },
            },
```
