### ISSUE TITLE
平行坐标图支持单击事件吗

### ISSUE THREAD

**Issue by genggs** [ecomfe/echarts#5301]
### One-line summary [问题简述]

平行坐标图支持单击事件吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

简单介绍，快速回复

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂不支持
