### ISSUE TITLE
目前版本能否支持折线图brush组件

### ISSUE THREAD

**Issue by smcdl** [ecomfe/echarts#5303]
### One-line summary [问题简述]

目前版本能否支持折线图brush组件。目前的结果是可以显示brush组件，也可以做选择，但'brushSelected'事件无法将选择的数据传回来。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Ubuntu 16.04

### Expected behaviour [期望结果]

 折线图也能支持brush组件选取数据。

### ECharts option [ECharts配置项]

```javascript
option = {
            title: {
                text: 'ECharts取坐标'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ['周一','周二','周三','周四','周五','周六','周日']
            },
            yAxis: {},
            series: {
                name: '销量',
                type: 'line',
                data: [820, 932, 901, 934, 1290, 1330, 1320]
            },

            brush: {
		 toolbox: ['rect','lineX', 'lineY', 'clear'],
		 // xAxisIndex: '0',
                 brushMode :'single',
		 throttleType : 'debounce',
		 throttleDelay : 2000
 	    }
}

```

**Comment by pissang** [comment]
暂时不支持

**Comment by wm370857724** [comment]
我这可以返回，coordRange的值可以取到
`
    myChart.on('brushSelected', renderBrushed);
    function renderBrushed(params) {
        console.log(params);
    }
`

**Comment by smcdl** [comment]
@wm370857724 你的方法不行，我试过了，bar图可以，但line图就不行，我修改了echarts源码，在line里添加了刷子类型，现在可以实现了，但不知道如何编译打包echarts

**Comment by smcdl** [comment]
@pissang 我修改了源码，给line图添加了brushSelector: 'point'，目前看来是可以支持刷子筛选的，但我不知道这里会有什么风险，能否说明一下，谢谢。

**Comment by hyb508** [comment]
请问你是怎么解决的呢？能否告知具体细节？ @smcdl

**Comment by wuxianliang** [comment]
@smcdl 可以分享一下怎么修改源码吗？谢谢。

**Comment by wuxianliang** [comment]
@smcdl 我直接在 LineSeries.js 里添加了
```
brushSelector: 'point'
```
没有起作用。

**Comment by xiaobao66** [comment]
@smcdl 我想问一下，是对哪个文件进行了修改，能否告知详细步骤，谢谢

**Comment by xiaobao66** [comment]
**smcdl** 提供的方案可行，在echarts\src\chart\line\LineSeries.js文件里加入
`brushSelector: 'point'`
重新构建可以使用，但是有没有其他风险并不清楚

**Comment by onionnet606** [comment]
你好，我对这个不是很熟悉，具体是怎么操作能否告知详情？谢谢！

**Comment by yedongze** [comment]
mark
