### ISSUE TITLE
zrender最新版本中Polyline是否还有 isCover(x, y)这个函数

### ISSUE THREAD

**Issue by tonyhao01** [ecomfe/echarts#5306]
### One-line summary [问题简述]
如题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
改成 .contain(x, y) 了
