### ISSUE TITLE
Rotate any text

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#5309]
Version: 3.4.0

It would be nice if any text can be rotated similarly to  axis label. This would ideally apply to all labels and graphic:text. 

This would be helpful for adapting longer texts to chart layout, example:
![image](https://cloud.githubusercontent.com/assets/561365/24109350/ad70a81c-0d90-11e7-9ad6-eaaf22994e70.png)

Currently shows as:
![image](https://cloud.githubusercontent.com/assets/561365/24109404/d3966004-0d90-11e7-96e3-6a46ec7a6054.png)

**Comment by psumstr** [comment]
@jarben I had requested this for the bar charts a while back: https://github.com/ecomfe/echarts/issues/1346#issuecomment-78251683

As you suggested, it would be even better if it's available to all text. Additionally, it would be great to expose the methods that can calculate the text length and bar length in px. With that info, you can add logic to either place the labels inside or outside of the bars, for instances where the label is longer than the bar length.

**Comment by jarben** [comment]
Awesome thanks!
