### ISSUE TITLE
echarts3中 地图各个省份位置不正确

### ISSUE THREAD

**Issue by yellowStar1992** [ecomfe/echarts#5312]
### One-line summary [问题简述]
为什么在echarts3 中，中国地图的 各个省份的位置都是不对的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts3

### Expected behaviour [期望结果]
希望可以位置 正确

> 

> 

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by yellowStar1992** [comment]
echarts3中 地图 各个省份位置不正确，求助

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=xHyPl7vyu

**Comment by yellowStar1992** [comment]
谢谢
