### ISSUE TITLE
echarts 世界地图

### ISSUE THREAD

**Issue by shengdaojin** [ecomfe/echarts#5320]
### One-line summary [问题简述]
echarts 3世界地图，首次加载地图的时候，高亮显示部分设置好的国家，并且自动根据国家的位置，显示缩放比例，把这些国家显示在地图的中心位置

### Version & Environment [版本及环境]
+ ECharts version [3.00]:
+ Browser version [360极速浏览器]:
+ OS Version [win 7]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=map-locate

**Comment by shengdaojin** [comment]
缩放比例没有发生变化啊，一直是4

**Comment by yogge-qq** [comment]
![502](https://user-images.githubusercontent.com/24315022/32259219-e647123c-bef9-11e7-816f-44adc6e4e92d.png)
我想打开世界地图试试，怎么挂了？
