### ISSUE TITLE
Changing series type from area to line doesn't work

### ISSUE THREAD

**Issue by bluestreak01** [ecomfe/echarts#5323]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

version 3.4.0
Chrome

### Expected behaviour [期望结果]

Replacing options on existing chart changing series from area to line doesn't work. Chart still renders areas. Two set of options below. Render first set, then call chart.setOption() with second set.

### ECharts option [ECharts配置项]

Option 1:

```javascript
{"legend":{"data":["dude 1","dude 2"]},"series":[{"name":"dude 1","stack":"x","type":"line","itemStyle":{"normal":{"areaStyle":{"type":"default"}}},"data":[442333,442333,442334,1062500,2162500,3112500,4362500,22000000,22000000,22000000,22000000,26000000,21680727,22708525,28000000,33000000,33000000,32000000,30000000,29000000]},{"name":"dude 2","stack":"x","type":"line","itemStyle":{"normal":{"areaStyle":{"type":"default"}}},"data":[109000,109000,187500,350000,1500000,3000000,3600000,4850000,6375000,6725000,6975000,316000,850000,1500000]}],"yAxis":[{"name":"Salary","type":"value"}],"xAxis":[{"name":"Year","type":"category","data":[1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013]}]}```

```javascript
{"legend":{"data":["dude 1","dude 2"]},"series":[{"name":"dude 1","stack":"x","type":"line","itemStyle":{"normal":{"lineStyle":{"type":"solid"}}},"data":[442333,442333,442334,1062500,2162500,3112500,4362500,22000000,22000000,22000000,22000000,26000000,21680727,22708525,28000000,33000000,33000000,32000000,30000000,29000000]},{"name":"dude 2","stack":"x","type":"line","itemStyle":{"normal":{"lineStyle":{"type":"solid"}}},"data":[109000,109000,187500,350000,1500000,3000000,3600000,4850000,6375000,6725000,6975000,316000,850000,1500000]}],"yAxis":[{"name":"Salary","type":"value"}],"xAxis":[{"name":"Year","type":"category","data":[1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013]}]}
```

**Comment by pissang** [comment]
You need to remove `areasStyle`, in ECharts, line series with areaStyle will be drawn as a area chart

**Comment by bluestreak01** [comment]
i don't think i'm making it clear

i have `chart` instance and i call `chart.setOption(option1)`, the intent is to display area chart, which it does

next i call `chart.setOption(option2)` with intent to display line chart. As you can see `areaStyle` is not set on `option2` but chart still renders area.

it would work as expected if i call `chart.clear()` before `chart.setOption(option2)` but this does complete re-render.

**Comment by pissang** [comment]
Sorry for mistaken it. You don't need to clear the chart. Try
```js
chart.setOption(option2, true)
```

the second parameter means whether to replace the previous option. If it is false, which is default value, new option will be merged. And the areaStyle will also be kept.

**Comment by bluestreak01** [comment]
Perfect, this worked! Thanks for your help!
