### ISSUE TITLE
建议添加图例标记圆角itemRadius，这样就可以设置图例标记为圆形。

### ISSUE THREAD

**Issue by LastQuarterMoon** [ecomfe/echarts#5325]
The title,The image.
如题，如图！

![360](https://cloud.githubusercontent.com/assets/22828247/24180502/3d6ba33a-0ef0-11e7-9ec9-51f13a6bf352.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#legend.data.icon
