### ISSUE TITLE
建议对地名的识别稍微智能一些

### ISSUE THREAD

**Issue by stereoF** [ecomfe/echarts#5327]
### One-line summary [问题简述]

在使用Echarts的地图时，是否可以支持模糊度高一些的地名识别。比如，现在地名的name传“武汉市”就可以识别，如果是“武汉”就无法识别。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: Ubuntu 16.04 LTS

### Expected behaviour [期望结果]

对类似“北京市”和“北京”这样的省市名称都能正确识别。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个建议自己处理和转换
