### ISSUE TITLE
如何给散点，气泡图的区域块设置单独的背景色

### ISSUE THREAD

**Issue by Freewayy** [ecomfe/echarts#5328]
[

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![apanda1985_1490167828277_37](https://cloud.githubusercontent.com/assets/23501672/24186723/88aafd86-0f14-11e7-8121-2a9fade5aabc.png)

**Comment by pissang** [comment]
3 可以使用 markArea 设置， 2 不行
