### ISSUE TITLE
为什么gird中的left,top,right,bottom这些属性对饼图无效

### ISSUE THREAD

**Issue by xuJianH** [ecomfe/echarts#5332]
echarts  3.4.0
ios  windows10
chrome  56

grid中调整距离的属性对饼图无效，其它图都是好的

**Comment by pissang** [comment]
饼图通过 center 和 radius 定位

**Comment by Huauauaa** [comment]
@pissang 雷达图呢

**Comment by Huauauaa** [comment]
> [@pissang](https://github.com/pissang) 雷达图呢

忽略，已处理
