### ISSUE TITLE
提示框格式化

### ISSUE THREAD

**Issue by qinlaodexiaosan** [ecomfe/echarts#5340]
### One-line summary [问题简述]
默认的提示框，在数据前都有和图列颜色一样的小圆点，可是自己的系列名称需要进行格式化，这时候小圆点就不见了，如果还想要这样的小圆点该怎么设置？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echart3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
可以自定义提示框格式，而且在数据前面有图列颜色一样的小圆点，实现与默认一样的格式。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
默认的小圆点是用 div 实现的，你也可以在 formatter 里自己加上带有颜色的 div
