### ISSUE TITLE
折线图的标签能否一上一下交错显示

### ISSUE THREAD

**Issue by xuJianH** [ecomfe/echarts#5343]
echarts 3.4.0
windosw10
chrome57
因为图比较小，所以都挤在了一起，如果能交错显示就好了。
看文档上
`label:{
      normal:{
          offset:{},
          position:{}
      }
}`
offset和position这两个属性似乎都满足不了要求，不知道是否有办法实现，谢谢。
ps：数据为93%，89%这样的，所以不能将其截断

**Comment by pissang** [comment]
每个数据项都支持设置标签，所以你可以设置成一个在上面一个在下面
