### ISSUE TITLE
roam:false,关闭滚轮缩放和拖拽漫游,如何实现缩放但禁止拖动呢,大神们有知道的麽,求助

### ISSUE THREAD

**Issue by fanguangjian** [ecomfe/echarts#5348]
eries: [
{
name: "",
type: 'map',
roam: true,
map: 'china',
graph:{
       roam:false;
       scaleLimit:{min:0.7,max:1} 

},
]

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#geo.roam
roam: 'scale''

**Comment by zhangdaba** [comment]
试过了 还是不行哦  页面上还是可以拖拽，还有别的办法么？
roam：false  也试过了 不行哦，
