### ISSUE TITLE
为什么没有mousein事件？我需要用这个事件，但不会改源码，有会的吗。

### ISSUE THREAD

**Issue by 853591143** [ecomfe/echarts#5351]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有 mouseover
