### ISSUE TITLE
为什么一直显示南沙群岛？

### ISSUE THREAD

**Issue by hanasakari** [ecomfe/echarts#5353]
我在加载地图时候一直显示南沙群岛，无论是什么地方的地图

###  版本及环境
+ ECharts 3.1.5[ECharts 版本]:
+ Browser 酷容浏览器（chrome）56.0.2924.87 (64-bit):
+ OS Version Win10:

### 期望结果
显示正常省级地图

###  ECharts配置项
```javascript
  var option = {
            title: {
                text: '代理商分布图',
                left: 'center'
            },
            legend: {
                orient: 'vertical',
                left: 'left'
                //data:['']
            },
            toolbox: {
                show: false
            },
            series: [
                {
                    itemStyle: {
                        normal: {
                            areaColor: ['#ffe113']
                        }
                    },
                    name: '数量',
                    type: 'map',
                    mapType: 'china',
                    roam: false,

                    label: {
                        normal: {
                            show: true
                        }
                        ,
                        emphasis: {
                            show: true
                        }
                    },
                    data: []
                }
            ]
        };
```
引入json部分

require.async("echarts.min", function () {
            getMid(mapId);
            function getMid(mapId) {
                $.ajax({
                    'url': "../map/" + mapId + ".json",
                    "success": function (geoJson) {
                        charts(geoJson);
                    }
                });
            }

            function charts(geoJson) {
                echarts.registerMap('china', geoJson);
                myChart = echarts.init(document.getElementById('chart'));
                //3.x修改为了点击事件
                myChart.on('click', function (param) {
                    regionName = param.name;
                    mapId = param.data.regionId;
                    districtCode = "city";
                    dataTable.draw();
                    // myChart.setOption(option);
                    getMid(mapId);
                });
                $(".re").click(function () {
                    mapId = 1;
                    getMid(mapId)
                } );
                myChart.setOption(option);
            }

**Comment by pissang** [comment]
mapType 不要是 china 就行了

**Comment by Nicole0320** [comment]
原来是一定要‘china'这样全都是小写的会默认添加南海诸岛，这倒是解决了我这边南海诸岛出不来的问题，感谢

**Comment by Leesson** [comment]
@pissang 可以单独对南海诸岛设置样式吗？
