### ISSUE TITLE
新版本平行坐标点击图例parallelAxis怎么不跟着变化了

### ISSUE THREAD

**Issue by llsshh1985** [ecomfe/echarts#5357]
### One-line summary [问题简述]

之前legend中设置selectedMode为single的时候，点击图例坐标轴中的线和label都会跟着变化，现在轴线在点击事件中变化，但是label没有变化，是data数据中的一大堆

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新版本
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
> [+] category axis 默认情况会显示所有的类目，不论是否有类目中没有数据（原先两端的没有数据的类目不会被显示）。

可以设置 min: dataMin，max: dataMax 变成原来的样子

**Comment by llsshh1985** [comment]
好的，可以了。有data的那一项设置了min: 'dataMin', max: 'dataMax'谢谢
