### ISSUE TITLE
legend不支持数字

### ISSUE THREAD

**Issue by huanggm** [ecomfe/echarts#5358]
### One-line summary [问题简述]
series的name属性是数字的时候，就算legend设置为series的name数组，也不会显示legend。
如果将数字转为字符串，则是可以显示legend。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.4.0
+ Browser version [浏览器类型和版本]:
chrome 猜测和浏览器无关
+ OS Version [操作系统类型和版本]:
macos 猜测和操作系统无关

### Expected behaviour [期望结果]

不确定是否为bug，倒也影响不大。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by huanggm** [comment]
准确的描述是只要legend不是数字就可以，比如series的某个name是数字123，但是legend设置为字符串123，也是可以显示legend出来的。但是legend设置为数字123，则就显示不出来了

**Comment by pissang** [comment]
name 的类型就是字符串，尽管有些情况我们可能会有容错处理，但是还是建议写成字符串
