### ISSUE TITLE
堆叠图中，点击事件必须点击小圆点才触发，点击辅助线不行？

### ISSUE THREAD

**Issue by gongzhw** [ecomfe/echarts#5361]
### One-line summary [问题简述]

[堆叠图中，点击事件必须点击小圆点才触发，点击辅助线不行。在移动端屏幕太小太不好点击了。什么时候能修复这个bug？我是点击后，触发饼图的。这样太难受了，在移动端哪个小圆点太难点击到了。点击辅助线能触发？？](看这个图：http://pic.yijiaowu.cn/Photos/2017_3_27/636262084089705995_o.jpg)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

堆叠图中点击辅助线触发事件。现在必须点击小圆点
[http://pic.yijiaowu.cn/Photos/2017_3_27/636262084089705995_o.jpg](http://pic.yijiaowu.cn/Photos/2017_3_27/636262084089705995_o.jpg)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你可以监听 showtip 事件

**Comment by gongzhw** [comment]
没找到这个事件啊。亲
