### ISSUE TITLE
html引入bmap.js,提示define is not defined

### ISSUE THREAD

**Issue by vikky-lynn** [ecomfe/echarts#5362]
### One-line summary [问题简述]
在echarts中想导入百度地图插件做热力图，
html引入bmap.js,提示define is not defined

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3.0
+ Browser version [浏览器类型和版本]:chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]: win7 64

### Expected behaviour [期望结果]
显示百度地图

### ECharts option [ECharts配置项]

```javascript
option = {
       bmap:{
		center:[113.52, 22.3],
		zoom:13.5,
		roam:true
	},
	series:[{
		type: 'scatter',
        coordinateSystem: 'bmap',
	}]
}

```

### Other comments [其他信息]

![Uploading 39)3~K$07T(I]1](9S0QOGQ.png…]()
![Uploading O}5AO4P9{JTC5UW$7({%BD7.png…]()
![Uploading S4RJE0P25J0M5KV~6[5~P4B.png…]()

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/tree/master/extension/bmap

**Comment by vikky-lynn** [comment]
引入

可以直接引入打包好的扩展文件和百度地图的 jssdk


<script src="http://api.map.baidu.com/api?v=2.0&ak="></script>

<script src="dist/echarts.min.js"></script>

<script src="dist/extension/bmap.min.js"></script>

ak我之前已经申请了，我复制了链接里的bmap代码，作为bmap.js引入，提示的就是上面描述的问题。
请问bmap.min.js这个文件是链接里的bmap单个文件吗？不好意思，刚入门，烦请大神解答 @pissang

**Comment by pissang** [comment]
不是，在 dist 目录的 extension 下面

**Comment by vikky-lynn** [comment]
可以引入了，thank you
