### ISSUE TITLE
请问echarts是否支持在服务端导出静态html页面中的图片？

### ISSUE THREAD

**Issue by liuspringcs** [ecomfe/echarts#5369]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liuspringcs** [comment]
由于需要在服务端定时生成图片，必须绕过浏览器

**Comment by liuspringcs** [comment]
有大神遇到过这个问题吗？

**Comment by pissang** [comment]
试试这个 https://github.com/suxiaoxin/node-echarts
