### ISSUE TITLE
折线图标数据和折线不一致

### ISSUE THREAD

**Issue by elinxer** [ecomfe/echarts#5375]
### 折线图标数据和折线不一致
图表地址：http://echarts.baidu.com/demo.html#line-stack

我更改了这个配置中的数据
![image](https://cloud.githubusercontent.com/assets/7327251/24388836/dc574e4a-13af-11e7-9c93-87de6dda8269.png)

但右边折线图表为
![image](https://cloud.githubusercontent.com/assets/7327251/24388866/0d43689a-13b0-11e7-99d5-c4d6a19b32c8.png)

设置1和0的折线显示与设置222的重叠，图线错误

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:线上测试页面
+ Browser version [浏览器类型和版本]: 谷歌最新版
+ OS Version [操作系统类型和版本]: win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
去掉 stack
