### ISSUE TITLE
怎么下载全国省市的json格式的地图

### ISSUE THREAD

**Issue by lerambo** [ecomfe/echarts#5378]
### One-line summary [问题简述]
我们项目现在需求比较特别，需要下载全国省市区的json数据，但是从官网没有找到下载市和区的接口，官方能不能提供相应的json包

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望可以得到全国省市区的json包

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liangmucat** [comment]
[地图构建](http://ecomfe.github.io/echarts-map-tool/)

**Comment by lerambo** [comment]
这个不行，全国所有市区那得下载到什么时候啊。谢谢。

**Comment by pissang** [comment]
因为 api 接口调用次数限制，暂不支持批量下载

**Comment by Ppsj** [comment]
@lerambo  你好，我现在也遇到这个问题，你在哪里获得这个包0 0.

**Comment by lerambo** [comment]
@Ppsj 我还没有下载，只是下载了一些必须的。后期准备让公司的人去下载这个json包。你现在有了吗
