### ISSUE TITLE
不知道echarts有没有计划加入等值线图功能？

### ISSUE THREAD

**Issue by snowccca** [ecomfe/echarts#5381]
### One-line summary [问题简述]
不知道echarts有没有计划加入等值线图功能？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时还没列入计划内
