### ISSUE TITLE
将echarts放在react-slick中，图表加载不出来！

### ISSUE THREAD

**Issue by SynChron1zed** [ecomfe/echarts#5390]
### One-line summary [问题简述]

大概是什么原因呢，可以获取到dom的宽和高

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不知道啥原因

**Comment by SynChron1zed** [comment]
@pissang  https://github.com/ant-design/ant-design/issues/5555
