### ISSUE TITLE
数据包含时间戳，精确到毫秒，为何少了8小时？

### ISSUE THREAD

**Issue by wangbingxu** [ecomfe/echarts#5393]
时间戳少了8小时，时区问题？ 之前都正常的，今天突然发现出错了，核实了下跟后台没关系

option = {
    title: {
        text: "4343",
        textStyle: {
            fontSize: 23
        },
        x: "center",
        top: 10,
    },
    tooltip: {
        trigger: 'axis',
        formatter: function (params) {
            var date = new Date(params[0].data.value[0]);
            var returnHtml = "test<br />"
                    + echarts.format.formatTime("YYYY-MM-dd HH:mm:ss", date)+"<br />"
                    + params[0].data.value[1];
            return returnHtml;
        },
        axisPointer: {
            animation: true
        }
    },
    xAxis: {
        type: 'time',
        splitLine: {
            show: false
        },
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: '',
        type: 'line',
        data: [
        {
            name:65,
            value:{
                0:1490749200000,
                1:"67.7"
            }
        },{
            name:65,
            value:{
                0:1490745600000,
                1:"86.8"
            }
        },{
            name:65,
            value:{
                0:1490742000000,
                1:"98"
            }
        },{
            name:65,
            value:{
                0:1490738400000,
                1:"97.1"
            }
        },{
            name:65,
            value:{
                0:1490734800000,
                1:"90.2"
            }
        }
        ],
        lineStyle: {
          normal: {
              width: 3
          }
        }
    }]
};

我已将代码放在你们ECharts Gallery上：
http://gallery.echartsjs.com/editor.html?c=xS1HkJoO2e&comment=0
可直接点击浏览。

**Comment by wangbingxu** [comment]
有木有人？？难道ECharts团队老大带着小姨子走了么？？？

**Comment by chyfreefly** [comment]
检查一下是不是UTC时区的问题，转换成你想要的时区。
