### ISSUE TITLE
visualMap类型问题

### ISSUE THREAD

**Issue by twp0217** [ecomfe/echarts#5397]
visualMap类型在配置项文档中为数组类型，但是在很多例子中是Object类型

![image](https://cloud.githubusercontent.com/assets/26423963/24494362/99249bee-1564-11e7-9c45-3be3ffee1677.png)
例子：http://echarts.baidu.com/demo.html#calendar-lunar

**Comment by pissang** [comment]
单个 visualMap 组件可以直接写成 object，多个 visualMap 组件用数组

**Comment by twp0217** [comment]
@pissang 那是不是应该改下文档呢？
