### ISSUE TITLE
官网示例-象形柱图报错

### ISSUE THREAD

**Issue by 298029lkk** [ecomfe/echarts#5400]
### One-line summary [问题简述]
官网示例-象形柱图报错（应该是resize导致的错误）
![image](https://cloud.githubusercontent.com/assets/25260495/24497728/f7d8dd4e-156e-11e7-8841-7e86ce158bc5.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.0
+ Browser version [浏览器类型和版本]:Chrome 版本 56.0.2924.87
+ OS Version [操作系统类型和版本]: window 10企业版

### Expected behaviour [期望结果]
这个chart的自适应效果能正确

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能具体说下怎么复现这个错误么？

**Comment by 298029lkk** [comment]
打开这个demo的页面，然后改变浏览器窗口的大小，触发resize事件。应该是这样的。
