### ISSUE TITLE
地图数据在线生成工具——四川省成都市---简阳市地图有问题，地图空白。

### ISSUE THREAD

**Issue by yllbeckham23** [ecomfe/echarts#5409]
### One-line summary [问题简述]
地图数据在线生成工具——四川省成都市---简阳市地图有问题，地图上空白。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.0
+ Browser version [浏览器类型和版本]:chrome 57.0.2987.110
+ OS Version [操作系统类型和版本]:windows10 企业版

### Expected behaviour [期望结果]

四川成都市地图上要补充一下简阳市的地图数据，能够生成简阳市——一个独立的地图数据。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/11514787/24543153/1c660e9e-1631-11e7-8c07-5d6ceb3cf956.png)
![Uploading image.png…]()

**Comment by pissang** [comment]
在线地图构建使用的是第三方的地图数据，我们只是提供工具
