### ISSUE TITLE
Any chance to officially release 3.5.1?

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#5412]
Any chance to officially release 3.5.1 so it gets to cdnjs.com? :)

**Comment by pissang** [comment]
Sorry, we will have another recovery build 3.5.2 soon (maybe tomorrow), you can use this version then

**Comment by jarben** [comment]
Sounds good, thanks for letting me know @pissang !

**Comment by pissang** [comment]
Hi @jarben , we have just released 3.5.2 .

**Comment by jarben** [comment]
Awesome, thanks @pissang !
