### ISSUE TITLE
柱图默认选择位置希望配置项加上、

### ISSUE THREAD

**Issue by AntiMoron** [ecomfe/echarts#5416]
### One-line summary [问题简述]

希望 xAxis有新的配置项```selectIndexOnOptionReset: 1``` 表示每次重设默认选择位置为1。因为无线端很常见这样的需求。

**Comment by pissang** [comment]
选择位置是什么意思？

**Comment by AntiMoron** [comment]
@pissang  就是说tooltip的那根线嘛、默认标记在哪里。
