### ISSUE TITLE
series not exists. Legend data should be same with series name or data name

### ISSUE THREAD

**Issue by fanguangjian** [ecomfe/echarts#5418]
### One-line summary [问题简述]  
**series not exists. Legend data should be same with series name or data name**

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by CD-UNCC** [comment]
What was the solution?

**Comment by JohnKu2020** [comment]
I have the same problem. Is there correct solution?
