### ISSUE TITLE
dispatchAction showTip is not working with version 3.5.1

### ISSUE THREAD

**Issue by z827101859** [ecomfe/echarts#5423]
### One-line summary [问题简述]
echarts3.5版本，dispatchAction方法，参数type为showTip时不能显示tooltip。
在echarts3.4版本中正常。
参见：https://codepen.io/sweetyx/pen/ryPamX

### Version & Environment [版本及环境]
+ ECharts version [3.5.1]:
+ Browser version [chorme lastest]:
+ OS Version [windows7]:

### ECharts option [ECharts配置项]
```javascript
var myChart = echarts.init(document.getElementById('main'));
        option = {
            title : {
                text: '未来一周气温变化',
            },
            tooltip: {
                trigger: 'axis'
            },
            xAxis : [
                {
                    type : 'category',
                    boundaryGap : false,
                    data : ['周一','周二','周三','周四','周五','周六','周日']
                }
            ],
            yAxis : [
                {
                    type : 'value'
                }
            ],
            series : [
                {
                    name:'xxx',
                    type:'line',
                    smooth:0.2,
                    data:[11, 11, 11, 5, 12, 13, 10]
                }
                ,{
                    name:'yyy',
                    type:'line',
                    smooth:0.2,
                    data:[13, 9, 2, 1, 5, 6, 7]
                }
            ]
        };
        myChart.setOption(option);
        myChart.dispatchAction({
            type: 'showTip',
            dataIndex: 1
        });

```

**Comment by TrassonBoss** [comment]
升级到了3.5.2，还是不行：
两个echarts，mainChart的ToolTip触发otherChart的ToolTip，完全没反应。


 function onshowTip(params) {
        if (typeof params.dataIndex === 'undefined') 
        {
            return;
        }
　　 otherChart.dispatchAction({
                        type: 'showTip',
                        dataIndex: params.dataIndex+1
        });
    }
mainChart.on('showTip', onshowTip);

两个chart的范围不同，还可以怎么玩？

**Comment by duxinxiao** [comment]
3.5.2 still have this bug
