### ISSUE TITLE
当曲线图中间某个点数据缺失时，现在只能留空，曲线会断掉，能否有个开关，自动将空值的前后两点连起来？

### ISSUE THREAD

**Issue by otom31** [ecomfe/echarts#5425]
### One-line summary [问题简述]

当曲线图中间某个点数据缺失时，现在只能留空，曲线会断掉，能否有个开关，自动将空值的前后两点连起来？

### Expected behaviour [期望结果]

设置一个参数，让我决定缺失的数据是连线还是空缺

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.connectNulls
