### ISSUE TITLE
官网的地图构建山东省东营市 数据区域包含所选区的轮廓少了一个区。

### ISSUE THREAD

**Issue by qiuyuwu** [ecomfe/echarts#5435]
### One-line summary [问题简述]

官网的地图构建山东省东营市 数据区域包含所选区的轮廓少了一个区。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 的地图构建数据来自第三方服务

**Comment by nancybaby002** [comment]
http://ecomfe.github.io/echarts-map-tool/

这里现在有完整的东营地图啦
