### ISSUE TITLE
ECharts 地图数据在线生成工具没有贵州省遵义市播州区的数据

### ISSUE THREAD

**Issue by rql1986** [ecomfe/echarts#5438]
### One-line summary [问题简述]
地图数据在线生成工具生成的遵义市行政区划太老，而且没有遵义市播州区的行政区划数据。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.2
+ Browser version [浏览器类型和版本]: chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]: Microsoft Windows 10 专业版 10.0.14393

### Expected behaviour [期望结果]
1、能通过地图数据在线生成工具生成播州区的地图数据。
2、在遵义市的地图数据能看到遵义市的最新行政区划版图。

### ECharts option [ECharts配置项]

```javascript
option = {
series: [{
        type: 'map',
        map: 'zunyi'
    }]
}

```

**Comment by pissang** [comment]
echarts 的地图构建数据都是来自第三方服务。

**Comment by rql1986** [comment]
> echarts 的地图构建数据来自第三方地图服务。

来源的第三方地图服务是哪里？百度，高德？
