### ISSUE TITLE
柱状图 X轴上的列名称过长，怎么做用省略的方式显示。

### ISSUE THREAD

**Issue by junlinzhan** [ecomfe/echarts#5448]
### One-line summary [问题简述]
> 
> 柱状图 X轴上的列名称过长，怎么做用省略的方式显示。
>

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mangoZT** [comment]
是否可以生成options时候JS处理一下呢
