### ISSUE TITLE
如何获取 "英国" 的各地区地图数据包?

### ISSUE THREAD

**Issue by jerryzhong001** [ecomfe/echarts#5471]
有没有提供英国的各地区地图数据包？类似USA: http://echarts.baidu.com/gallery/data/asset/geo/USA.json

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wankaiss** [comment]
这个需要geojson的！你在网络上找一下geojson然后放到地图就可以了

**Comment by jerryzhong001** [comment]
你好，我现在用百度的api：http://api.map.baidu.com/geocoder/v2/?ak=3aLOvkHPRdR7oWZYy0FY07W73069cyZa&location=57.370053,-3.498389&output=json&qq-pf-to=pcqq.temporaryc2c   获取英国各个地区的信息，发现是分成了4个country，是以什么标准来分的？

然后我在网上找的geojson英国的地图划分，没有具体到所有郡的。有没有相应的来源？

**Comment by wankaiss** [comment]
我收藏的只有中国以及下面县市的。你上csdn找找看

**Comment by wankaiss** [comment]
http://pan.baidu.com/share/link?shareid=1530061487&uk=3892777837

**Comment by pissang** [comment]
http://www.statsilk.com/maps/download-free-shapefile-maps

**Comment by wangchong19940101** [comment]
@pissang 这个网址打不开，有中国json包吗？例如https://echarts.baidu.com/examples/editor.html?c=map-usa例子里$.get()

**Comment by Mr-try** [comment]
https://code.highcharts.com.cn/mapdata/index.html
