### ISSUE TITLE
ECharts3.0 最大值最小值小数位设置

### ISSUE THREAD

**Issue by xue560** [ecomfe/echarts#5474]
Echarts3.0最大值最小值小数位可否设置

**Comment by pissang** [comment]
什么意思？

**Comment by xue560** [comment]
var xAxisData = [];
var data1 = [];
var data2 = [];
for (var i = 0; i < 100; i++) {
    xAxisData.push('类目' + i);
    data1.push((Math.sin(i / 5) * (i / 5 -10) + i / 6) * 5);
    data2.push((Math.cos(i / 5) * (i / 5 -10) + i / 6) * 5);
}

option = {
    title: {
        text: '柱状图动画延迟'
    },
    backgroundColor:'#ccc',
    legend: {
        data: ['bar', 'bar2'],
        align: 'left'
    },
    toolbox: {
        // y: 'bottom',
        feature: {
            magicType: {
                type: ['stack', 'tiled']
            },
            dataView: {},
            saveAsImage: {
                pixelRatio: 2
            }
        }
    },
    tooltip: {},
    xAxis: {
        data: xAxisData,
        silent: false,
        splitLine: {
            show: false
        }
    },
    yAxis: {
    },
    series: [{
        name: 'bar',
        type: 'bar',
        markPoint:{data: [
    {
        name: '最大值',
        type: 'max'
    }, 
    {
       name: '最小值',
        type: 'min'
    } 
    ]},
        data: data1,
        animationDelay: function (idx) {
            return idx * 10;
        }
    }, {
        name: 'bar2',
        type: 'bar',
        data: data2,
        animationDelay: function (idx) {
            return idx * 10 + 100;
        }
    }],
    animationEasing: 'elasticOut',
    animationDelayUpdate: function (idx) {
        return idx * 5;
    }
};

注: markPoint中的max,min 最大值和最小值目前没有设置显示小数位数的地方

**Comment by pissang** [comment]
用 formatter

**Comment by zuoanCo** [comment]
> 用 formatter

你好，请问怎么把 设置过formatter的 option数据保存到后台呢， 前台获取option可以直接绘制图表
