### ISSUE TITLE
echarts和bootstrap如何集成

### ISSUE THREAD

**Issue by wangshiyougithub** [ecomfe/echarts#5478]
### Version & Environment [版本及环境]  windows+idea+ie8+chrome
+ ECharts version [ECharts 版本]: 3+
+ Browser version [浏览器类型和版本]: ie8/9/10/11  chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]:windows 10  64位

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不管是不是 bootstrap，实现自适应的方法就是 div 尺寸发生改变时调用 myChart.resize

**Comment by wangshiyougithub** [comment]
谢谢
