### ISSUE TITLE
折线图获取所有节点的位置信息(offsetX,offsetY)

### ISSUE THREAD

**Issue by techbirds** [ecomfe/echarts#5480]
### One-line summary [问题简述]

目标:

鼠标在图形区域hover能够智能判断最近节点位置，并能够自动触发节点的高亮行为。

方案:

利用getZr()的`mouseover`事件获取鼠标位置信息，然后计算与节点之间的距离并决定触发(dispatch)节点的高亮行为。

难点:

能否在图形实例化后，获取所有节点的位置信息(offsetX,offsetY)，现在必须通过节点的鼠标事件来获取对应节点的位置信息(event.offsetX,event.offsetY).

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: Chrome 57.0.2987.133 (64-bit) 
+ OS Version [操作系统类型和版本]: Mac 10.11.6

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by techbirds** [comment]
已解决。

**Comment by some-code** [comment]
请问是如何解决的？我需要获取tree下面全部子节点的坐标

**Comment by wangmerry** [comment]
求问解决方案
