### ISSUE TITLE
多Y轴设置偏移量问题。

### ISSUE THREAD

**Issue by WangDianwu** [ecomfe/echarts#5486]
### One-line summary [问题简述]
X轴是时间轴，会有多条Y轴的情况。如何去自动匹配offset的值，来适应刷新时Y轴数据的变化，不影响展示效果。（Y轴值变化，offset值也跟匹配）。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没办法自动匹配
