### ISSUE TITLE
Y轴数值保证为正整数

### ISSUE THREAD

**Issue by HealerJTF** [ecomfe/echarts#5490]
### One-line summary [问题简述]
给Y轴设置minInterval之后会有负数出现，可是不设置minInterval会出现小数的情况，

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.2.2
+ Browser version [浏览器类型和版本]:all
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
Y轴数值为正整数

### ECharts option [ECharts配置项]

```javascript
option = {
var option = {
	        tooltip : {
	            trigger: 'axis',
				axisPointer:{
					type:"line",
					color:"#e5e5e5"
				}
	        },
	        legend: {
	            data:cdata.legend,
	            x:"right",

	        },    
	        grid: {
	            left: '3%',
	            right: '6%',
	            bottom: '12%',
	            containLabel: true
	        },
	        xAxis : [
	            {
	                type : 'category',
	                data : cdata.x,
	                axisLine:{
						lineStyle:{
							color:["#e5e5e5"]
						}
					},
					axisLabel:{
						textStyle:{
							color:["#999999"]
						}
					},
					axisTick:{
						lineStyle:{
							color:["#e5e5e5"]
						},
						show:false
					},
					splitLine:{
						show:false
					}
	            }
	        ],
	        yAxis : [
	            {
	                type : 'value', 
	                data:cdata.y,  
	                // min:0,
	                // max:cdata.max,  
	                minInterval:1,           
	                axisLine:{
						show:false,
						lineStyle:{
							color:["#999999"],
							opacity:0.8
						}
					},
					axisLabel:{
						textStyle:{
							color:["#999999"],
						}
					},
					axisTick:{
						lineStyle:{
							color:["#e5e5e5"]
						},
						show:true
					},
					splitLine:{
						lineStyle:{
							color:["#e5e5e5"]
						}
					}
	            }
	        ],
	        color:[cdata.color],
	        series : cdata.series
	    }
}

```

### Other comments [其他信息]

图一为设置minInterval的效果；
图二为不设置minInterval的效果
![image](https://cloud.githubusercontent.com/assets/24707837/24950369/70e8407e-1fa3-11e7-973c-e96a71df8095.png)
![image](https://cloud.githubusercontent.com/assets/24707837/24950398/84055ab6-1fa3-11e7-81a4-5aa16aefb143.png)

**Comment by mangoZT** [comment]
minInterval+splitNumber,其中splitNumber为最大值的正整数 是否可以适用这种情况

**Comment by HealerJTF** [comment]
我刚试了一下，这样还是会出现负数的情况。我昨天给设置了最大值和最小值。是可以解决的。但是我觉得在数据量比较大的时候用最大值和最小值可能也会有问题。

**Comment by mangoZT** [comment]
再加上min给0   出现负数和小数基本都是你的值都比较小了  这种情况还算好控制

**Comment by HealerJTF** [comment]
加上min等于0，minInterval就不管用了

**Comment by mangoZT** [comment]
能否贴出具体数据  我这里没发现那种问题
![image](https://cloud.githubusercontent.com/assets/26948222/24989383/dcd86fca-203e-11e7-8bb6-e7113571d066.png)

**Comment by HealerJTF** [comment]
我这个是一个折线图和柱状图拼在一起的……改起来挺费劲的

**Comment by HealerJTF** [comment]
稍等，我上传图片

**Comment by HealerJTF** [comment]
![b 9i yjrn741 ki_ _zrry](https://cloud.githubusercontent.com/assets/24707837/24990406/5779335c-2046-11e7-82aa-6025a98fc511.png)

**Comment by mangoZT** [comment]
splitNumber这个属性用了？

**Comment by mangoZT** [comment]
splitNumber：2  应该不会分为0.5啊

**Comment by HealerJTF** [comment]
我不明白“splitNumber为最大值的正整数” 这句话是什么意思,是先获取它的最大值然后设置这个选项吗

**Comment by mangoZT** [comment]
splitNumber差不多一个意思  不过只会在你的值都比较小的情况下才会用到   值一般超过5  基本就不会有小数  你就当特殊情况处理好了

**Comment by HealerJTF** [comment]
为什么不直接设置成5呢？设置成最大值的正整数划分的不就不一样了吗

**Comment by HealerJTF** [comment]
我的传不了图片了，我设置了splitNumber为最大值的正整数之后，只划分了2个……

**Comment by mangoZT** [comment]
看你怎么用了  灵活点的话最好不要写死  视情况而定  如果能解决你的问题的话 给个好评

**Comment by mangoZT** [comment]
那没错啊  你的值最大为2  从0开始 那只有0 1 2  没毛病 老铁

**Comment by HealerJTF** [comment]
但是它划分的有点少哇……怎么好评？

**Comment by mangoZT** [comment]
那你告诉我  2怎么分成5份  还保证每个数字都是正整数  华罗庚都做不到

**Comment by HealerJTF** [comment]
可以让它的最大值不是2啊，设置最大值

**Comment by mangoZT** [comment]
OK的话我去看其他的问题了哦

**Comment by HealerJTF** [comment]
告诉我怎么好评啊

**Comment by mangoZT** [comment]
就说说的   没有什么好评   能解决问题就行

**Comment by HealerJTF** [comment]
好吧。谢谢你。对了右上角那个表情是什么意思？

**Comment by huangchaofei** [comment]
楼主现在解决问题了吗?，给个代码参考一下 和你的遇到的一样，本来换个4.0可以解决，但是页面中有个地图换了还要改太麻烦了
