### ISSUE TITLE
How can I display tooltip with RTL language(e.g. ar) for radar chart?

### ISSUE THREAD

**Issue by Mignon-han** [ecomfe/echarts#5493]
### One-line summary 
How can I display tooltip with RTL language(e.g. ar) for radar chart?

### Version & Environment 
Echarts 3.5
chrome 57
win 10

### Expected behaviour
 Display tooltip with RTL language(e.g. ar) for radar chart success.

**Comment by Mignon-han** [comment]
I can do it by formatter now, so close it.

**Comment by rahimramezanian** [comment]
Hi @Mignon-han , Could you please tell us how you do that?
Thanks.

**Comment by Mignon-han** [comment]
@rahimramezanian  https://echarts.baidu.com/option.html#tooltip.formatter
