### ISSUE TITLE
是否可能在一张图上同时存在以axis和item触发的两个tooltip?如何实现？

### ISSUE THREAD

**Issue by FrankChen1992** [ecomfe/echarts#5496]
### One-line summary [问题简述]

是否可能在一张图上同时存在以axis和item触发的两个tooltip?如何实现？

以官网堆积柱状图为例，是否可能在选中某一项时显示该项信息(item)，在选中空白处时显示该列所有项的信息(axis)?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 2.2.7
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
<http://gallery.echartsjs.com/editor.html?c=xH1-bHpy0l&v=1>
这样可以么
