### ISSUE TITLE
There is no possibility to draw oscillograph kind of charts

### ISSUE THREAD

**Issue by CasperReduct** [ecomfe/echarts#5499]
yAxis - time [0.01, 0.02,0.03...]
Data [0,1,1,0,0,...](true/false)
Can't find possibility to draw like this:
<img src="https://cdn.instructables.com/FKL/D7KT/IL5I1IGP/FKLD7KTIL5I1IGP.MEDIUM.jpg" />

**Comment by 100pah** [comment]
Is it possible to draw like this:
<https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-step>
