### ISSUE TITLE
【求助】如何使用Echarts3.0实现阈值线上下的折线图的线条粗细不同？希望能指点迷经，非常感谢！！！

### ISSUE THREAD

**Issue by zhaoweikai** [ecomfe/echarts#5500]
### 如何使用Echarts3.0实现阈值线上下的折线图的线条粗细不同？
像如下效果（下图是高保真图，还没有实现）：
![image](https://cloud.githubusercontent.com/assets/10459842/25007384/e83ede4a-2092-11e7-8526-edba8eb91737.png)

目前已经实现效果：
![image](https://cloud.githubusercontent.com/assets/10459842/25007339/b26ad9d6-2092-11e7-97df-6f7e5ed727aa.png)

研究了好久，没有找到如何实现阈值线上边的折线粗度变大。
问题1：不修改Echart3.0源码情况下，如何实现该效果？
问题2：如果通过接口无法实现该效果，如何修改源码实现？希望能帮忙指导下，给个大体方案。
非常感谢！！！！

### 版本：
+ ECharts version [ECharts 版本]: Echarts 3.0最新版本
+ Browser version [浏览器类型和版本]: IE9+、chrome、Firefox
+ OS Version [操作系统类型和版本]:Windows

### Expected behaviour [期望结果]
![image](https://cloud.githubusercontent.com/assets/10459842/25007384/e83ede4a-2092-11e7-8526-edba8eb91737.png)

### ECharts option [ECharts配置项]

```javascript
option = {
           title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                show: true,
                data: ["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月","13月"]
            },
            yAxis: {
                show: true
            },

            // 配合设置阈值线
            visualMap: {
                show: false,
                type: 'piecewise',
                dimension: 1,
                borderWidth: 3,
                pieces: [{
                    max: 500,
                    min: 100,
                    color: 'red'
                },{
                    min: 0,
                    max: 100,
                    color: 'blue'
                }]
            },
            series: [{
                name: '销量',
                type: 'line',
                lineStyle: {
                    normal: {
                        width: 3
                        //color: 'yellow'
                    }

                },
                // 阈值线设置 http://echarts.baidu.com/option.html#series-line.markLine
                markLine: {
                    animation: true, //动画
                    symbol: '',
                    precision: 3, 
                    data: [
                        {
                            name: 'max', 
                            yAxis: 100,
                            symbol: '',
                            lineStyle: { // 标线的样式
                                normal: {
                                    color: 'red',
                                    width: 1, // 线宽
                                    type: 'dashed'
                                }
                            },
                            label: { // 标线的文本。
                                normal: {
                                    show: false,
                                    position: 'middle', 
                                    formatter: '{b}: {c}'
                                }
                            }
                        }
                    ]
                },
                data: [5, 20, 36, 10, 10, 200, 120, 40, 230, 420, 330, 210, 330]
            }]
}

```

**Comment by pissang** [comment]
visualMap piecies 设成三段就行了

**Comment by Erimus-Koo** [comment]
刚好看到，又刚巧试到一个思路，用visualMap。

    visualMap: [{
        dimension: 0[1],
        type: 'piecewise',
        pieces: [{
            max: 3
        }, {
            min: 3,
            max: 3.2,
            label: '< 3.2'
        }, {
            min: 3.2,
            max: 3.4,
            label: '< 3.4'
        }, {
            min: 3.4,
            max: 3.6,
            label: '< 3.6'
        }, {
            min: 3.6,
            label: '> 3.6'
        }],
        color: ['red', 'yellow', 'green', 'blue', 'purple'],
        orient: 'horizontal',
    }],
    series: [{type: 'line',data:[[1,2],[3,5]]},{type: 'line',data:[[4,5],[5,1]]}]
