### ISSUE TITLE
vue中怎么使用主题文件

### ISSUE THREAD

**Issue by guopengno1** [ecomfe/echarts#5504]
### One-line summary [问题简述]
最近使用vue开发移动端页面，echarts图都显示出来了，想使用其中的一个主题，但突然不知道怎么使用了，和正常的开发方式不一样。希望可以帮我解决一下，谢谢啦。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
最新版本

### Expected behaviour [期望结果]
期望可以使用主题文件

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Myqilixiang** [comment]
insert this code into your <script>tag ahead of your Vue component and then you will find it works~
`import echarts from 'echarts';`
`require('echarts/theme/macarons');`

use instance:
`let cpuChart = echarts.init(document.getElementById('pie_cpu'), 'macarons');`
