### ISSUE TITLE
柱状图 y轴axisLabel 左对齐问题

### ISSUE THREAD

**Issue by LIANGKUNYAO** [ecomfe/echarts#5507]
### One-line summary [问题简述]

柱状图 y轴axisLabel 
当坐标轴在左侧时 左对齐显示有误，当坐标轴在右侧时 右对齐显示有误

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.2
+ Browser version [浏览器类型和版本]:Chrome 50.0
+ OS Version [操作系统类型和版本]:Windows 10

### ECharts option [ECharts配置项]

```javascript

option = {
 tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    legend: {
        data:['利润', '支出', '收入']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'value'
        }
    ],
    yAxis : [
        {
            type : 'category',
            axisTick : {show: false},
            axisLabel:{
              textStyle:{
                  align:'left'
              }  
            },
            data : ['123周一','3周二','周3453545三','5周四']
        }
    ],
    series : [
        {
            name:'利润',
            type:'bar',
            label: {
                normal: {
                    show: true,
                    position: 'inside'
                }
            },
            data:[{
                value:200,
                itemStyle:{
                    normal:{
                        opacity:0.5
                    }
                }
            },{
                value:200,
                itemStyle:{
                    normal:{
                        opacity:0.5
                    }
                }
            },{
                value:200,
                itemStyle:{
                    normal:{
                        opacity:0.5
                    }
                }
            },{
                value:200,
                itemStyle:{
                    normal:{
                        opacity:0.5
                    }
                }
            }]
        }
    ]
};

```

### Other comments [其他信息]

<img width="634" alt="2017-04-14 19 13 30" src="https://cloud.githubusercontent.com/assets/9531855/25041937/76530946-2146-11e7-8475-9191bec2bde3.png">

**Comment by LIANGKUNYAO** [comment]
通过增加offset属性可以解决该问题：
    yAxis : [
        {
            type : 'category',
            axisTick : {show: false},
            **offset:80,**
            axisLabel:{
              textStyle:{
                  align:'left'
              }  
            },
            data : ['123周一','3周二','周3453545三','5周四']
        }
    ],

<img width="710" alt="2017-04-15 12 40 53" src="https://cloud.githubusercontent.com/assets/9531855/25060807/c840aabe-21d8-11e7-8621-7ff8ce35d80d.png">

**Comment by ellyliang** [comment]
感觉设置offset不可取....
我的y轴axisLabel的值是动态的，不同手机下边会有展示不全的问题，咋整呢

**Comment by DukeGJ** [comment]
那你只能合理调整图表的大小，比方说Y轴比较多的时候图表适当缩小

**Comment by ellyliang** [comment]
![image](https://user-images.githubusercontent.com/4658035/30689015-4b14afb2-9ef2-11e7-9116-face3c2b54b3.png)

**Comment by ellyliang** [comment]
我设置的是grid width为100%

**Comment by DukeGJ** [comment]
你把图表的高度调低试试

**Comment by Rhuaer** [comment]
@ellyliang 有一种方案是可以根据文字字数乘以字号大小，把这个结果设置到offset上，然后再设置一下margin，在全汉字、微软雅黑字体下的效果还可以，但如果有英文和数字、或者其他字体，这个就不好说，需要再具体调整

**Comment by yunfeibair** [comment]
你这个问题是怎么解决的？

**Comment by Woomay** [comment]
@ellyliang 请问最后是怎么解决的呢？我也是动态标签长短不一，会展示不全。

**Comment by lliiuu** [comment]
> @ellyliang 请问最后是怎么解决的呢？我也是动态标签长短不一，会展示不全。

你好，你这问题解决了吗，我也有相同的问题。

**Comment by chenjiaj** [comment]
请问这个问题有人解决了吗？

**Comment by heboliufengjie** [comment]
我也碰到这个问题，有人解决不？最后的结果呢

**Comment by heboliufengjie** [comment]
![image](https://user-images.githubusercontent.com/10194974/196331428-779e4a7e-6d14-44d9-b613-897cfb242699.png)

借鉴的这个
https://www.jianshu.com/p/b153a3214179
