### ISSUE TITLE
箱线图对系列outliers如何与对应系列纵向对齐

### ISSUE THREAD

**Issue by genggs** [ecomfe/echarts#5509]
### One-line summary [问题简述]
箱线图多系列时，异常值outliers如何与对应的系列纵向对齐

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

官网箱线图demo

### Expected behaviour [期望结果]

箱线图多系列时，异常值outliers与对应的系列纵向对齐

### ECharts option [ECharts配置项]

```javascript

```

**Comment by 100pah** [comment]
这样可以么？
<http://gallery.echartsjs.com/editor.html?c=boxplot-multi&v=2>

**Comment by genggs** [comment]
可以，非常感谢

**Comment by mxismean** [comment]
> 这样可以么？ http://gallery.echartsjs.com/editor.html?c=boxplot-multi&v=2

您好，链接访问不了，请问纵行对齐这个问题怎么处理？

**Comment by mxismean** [comment]
> 

您好，链接访问不了，请问纵行对齐这个问题怎么处理？

**Comment by AmorDiamond** [comment]
> > 这样可以么？ http://gallery.echartsjs.com/editor.html?c=boxplot-multi&v=2
> 
> 您好，链接访问不了，请问纵行对齐这个问题怎么处理？

可以参考这个案例
https://www.makeapie.cn/echarts_content/boxplot-multi.html
