### ISSUE TITLE
3D echarts GL 默认角度怎么配置 是那一个配置属性

### ISSUE THREAD

**Issue by shenjingxin** [ecomfe/echarts#5510]
3D echarts GL 默认角度怎么配置 是那一个配置属性

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.2
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:mac

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 https://ecomfe.github.io/echarts-doc/public/cn/option-gl.html#grid3D.viewControl.alpha ，可以通过 alpha 和 beta 两个参数控制
