### ISSUE TITLE
treemap 怎么禁止缩放，还有点击时候会移动位置

### ISSUE THREAD

**Issue by lansefengxinzi** [ecomfe/echarts#5511]

**Comment by lansefengxinzi** [comment]
![4 -15-2017 08-29-48](https://cloud.githubusercontent.com/assets/12048313/25059269/da19ad3a-21b5-11e7-8c48-0f5d313a9c00.gif)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-treemap.roam

**Comment by lansefengxinzi** [comment]
ok l ,谢谢哈！

**Comment by itwhat126** [comment]
设置了并没有效果
