### ISSUE TITLE
在vue2的line图形中，在动态改变option时，series没响应，其它有响应，场景是，series的data减少一条数据后，line不会减少

### ISSUE THREAD

**Issue by doufugeshihua** [ecomfe/echarts#5523]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by doufugeshihua** [comment]
？？？？

**Comment by mangoZT** [comment]
setOption（option，true）这样可否

**Comment by pissang** [comment]
@mangoZT 正解
