### ISSUE TITLE
connectNulls这个选项存在bug

### ISSUE THREAD

**Issue by yuboyonghehe** [ecomfe/echarts#5524]
### One-line summary [问题简述]
connectNulls这个选项存在bug，我用line画出一个矩形填充颜色，显示为一个面，connectNulls会在我这个不规则的多边形的右侧响应，但是左侧的点还是会出现断层的问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
	for(var i = 0; i < 1; i++) {
				var item = [{ 
					name: i,
//					symbolSize: 0,
					lineStyle: {
						normal: {
							width: 0
						}
					},
					areaStyle: {
						normal: {
							color: oilid[i][0]
						}
					},
//					sampling:'average',
					connectNulls:true,
					clipOverflow:false,
					type: 'line',
					data: oliZ[i]
				}];
				seric = seric.concat(item);
			}

```

**Comment by pissang** [comment]
截个图？或者 http://gallery.echartsjs.com/ 贴个示例
