### ISSUE TITLE
Echarts3构建AMD

### ISSUE THREAD

**Issue by jiangxuzh** [ecomfe/echarts#5525]
![image](https://cloud.githubusercontent.com/assets/22673000/25119108/814cd478-244b-11e7-8214-d16cf5fa7673.png)

echarts3没办法像echarts2一样在线构建的时候就直接生成AMD标准的模块么

**Comment by pissang** [comment]
不行了，这种打包会把所有模块都暴露出来，并不是我们想要的方式。

ECharts 3 你也可以用 AMD 的方式加载，就是只能加载 echarts 主模块

```js
require('echarts')
```
