### ISSUE TITLE
echarts是否能让后端生成图片，解决前端大规模数据时的性能缺陷？

### ISSUE THREAD

**Issue by bi-kai** [ecomfe/echarts#5526]
大规模数据的场景，比如几十条曲线，页面会很卡，甚至崩溃，我想这样：
后端通过一些库，能够将数据直接生成图片，样式风格与echarts一致，这样前端只加载这个图片。
这种方式是否可行？

**Comment by pissang** [comment]
可以试一下，echarts 是支持使用 node 生成图片的。见 https://github.com/suxiaoxin/node-echarts

**Comment by wqj97** [comment]
支持的, 用node canvas

**Comment by bi-kai** [comment]
@pissang @wqj97 感谢，我也发现了这个模块，不过尚未配置成功，我再研究研究。
