### ISSUE TITLE
Y值量级差距过大

### ISSUE THREAD

**Issue by countryer** [ecomfe/echarts#5528]
Y值量级相差过大时，如[10,30,300000,200]，会造成10 30这种较小的数值对应的图形很小。有没有办法设置一个间隔，处理一下较大数据的图形，使得过大或过小的数据都能较为美观的进行展示？

**Comment by pissang** [comment]
试一下 log 轴？http://echarts.baidu.com/option.html#yAxis.type

**Comment by countryer** [comment]
貌似不可以，数据是离散的，比如农场一各类面积x,y,z，农场二各类面积x,y,z。然后x,y,z之间的差距可能会很大

**Comment by pissang** [comment]
那暂时也没什么其它办法
