### ISSUE TITLE
zrender某一个元素如何添加双击事件

### ISSUE THREAD

**Issue by tonyhao01** [ecomfe/echarts#5533]
### One-line summary [问题简述]

var text = new TextShape({
			id : ‘1’,
            position : [100,100],
            scale: [2, 2],
            style: {
               x: 0,
               y: 0,
               text: ‘test’,
               fill: txtfill,
               textFont: txtFont,
               textBaseline: 'top',
				
           },
           draggable: true,
           dblclick: txtdblclick,
       });
       zr.add(text);

function txtdblclick(params) {
	//do something
}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

双击text对象起效

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
el.on('dblclick', function () {});

**Comment by tonyhao01** [comment]
你好，再问下我在zrender绘制了很多点同时给image对象一个图片地址，想把它们最后都转成一个图片，但是image的图片却没有，是什么原因？
