### ISSUE TITLE
设置splitNumber之后图表数字过小时axisLabel数值分配会有问题

### ISSUE THREAD

**Issue by jiangxuzh** [ecomfe/echarts#5537]
下图为echarts2升级为3以后的对比，请问是需要其他新的写法还是要单独写axisLabel的数值，还是什么问题？
![image](https://cloud.githubusercontent.com/assets/22673000/25172909/fdbf54c0-2524-11e7-9e31-b78bd0e24f34.png)

![image](https://cloud.githubusercontent.com/assets/22673000/25172773/95dc2ffe-2524-11e7-9a0f-3a9c93d7c880.png)
splitNumber 设置的是5，最大值 小于5的话都会有这个问题

**Comment by pissang** [comment]
有具体代码没？

**Comment by jiangxuzh** [comment]
设置了axisLabel的formatter
![image](https://cloud.githubusercontent.com/assets/22673000/25213015/896153fc-25c0-11e7-8d46-1a2e6a8e89da.png)

去掉以后的效果是这样
![image](https://cloud.githubusercontent.com/assets/22673000/25213063/c5acb752-25c0-11e7-9655-61352bf9ea78.png)
![image](https://cloud.githubusercontent.com/assets/22673000/25213110/e35b8bde-25c0-11e7-9a7a-1e69fefe723f.png)
