### ISSUE TITLE
图例中的元素大小和图上展示的圆大小不一致！！！

### ISSUE THREAD

**Issue by brainsz** [ecomfe/echarts#5539]
### One-line summary [问题简述]

我在地图上面画了5种不同大小的气泡，类型是：scatter,而且5种圆圈的大小都是不同的，但是我在设置图例的时候，把这5种类型的都设置了图例，最后图例中的结果，圆圈的大小都是一样的，不会和图中的symbolSize对应上，为什么呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3.5.2
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]

图例中的圆圈的大小和图中的的一致！！

![Uploading 22222.png…]()

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![Uploading 22222.png…]()

**Comment by mangoZT** [comment]
![image](https://cloud.githubusercontent.com/assets/26948222/25209114/7bf295f6-25ab-11e7-8855-038a75f10131.png)
是这个意思么

**Comment by pissang** [comment]
图例不负责表示圆的大小

**Comment by mangoZT** [comment]
之前看错意思了   图例不一样大小的话是好像可以根据icon  自己作图  虽然麻烦点 但是可以实现效果

**Comment by mangoZT** [comment]
@brainsz   如果一定要实现该效果可以尝试一下

**Comment by brainsz** [comment]
可以从源代码中去修改图例中的圆圈的大小么？

**Comment by brainsz** [comment]
@mangoZT 我看到那里写了icon，不过就是感觉自己去做不同的图太麻烦了，下次如果有新的需求，又得自己做图，所以想问问不知能否加上这个小功能
