### ISSUE TITLE
使用官方的实例，tooltip不展示，请问怎么解决？

### ISSUE THREAD

**Issue by evilemon** [ecomfe/echarts#5540]
### One-line summary [问题简述]
http://echarts.baidu.com/demo.html#treemap-disk

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  "echarts": "^3.1.7", 最新版本也不行
+ Browser version [浏览器类型和版本]:  所有浏览器
+ OS Version [操作系统类型和版本]:MacBook Pro (Retina, 13-inch, Early 2015)    OS X EI 10.11.4

### Expected behaviour [期望结果]
希望出现tooltip

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

![image](https://cloud.githubusercontent.com/assets/13042865/25189028/8e2a8c34-255a-11e7-8ae7-5074a586bde9.png)

**Comment by mangoZT** [comment]
![image](https://cloud.githubusercontent.com/assets/26948222/25209150/ad01c324-25ab-11e7-820d-b9edcdf1d908.png)
是这个么

**Comment by evilemon** [comment]
是这个，怎么配置的老铁

**Comment by mangoZT** [comment]
老铁 官网就这个样子啊

**Comment by evilemon** [comment]
我npm  装的echart3 ，本地测试官方实例，所有的tooltip都不显示你知道是什么原因吗？

**Comment by mangoZT** [comment]
会不会你装的是简化版  手动下载个全版试试

**Comment by evilemon** [comment]
npm i echarts 都是简版了？你别蒙我

**Comment by pissang** [comment]
@evilemon 建议详细描述你的环境，代码，echarts 版本

**Comment by evilemon** [comment]
"webpack": "^1.12.16",
"echarts": "^3.1.7",

code 官方实例  http://echarts.baidu.com/demo.html#area-simple

**Comment by evilemon** [comment]
没人知道吗？？？？？

**Comment by evilemon** [comment]
我自己看了下这次的项目和之前的有什么区别，发现
这次我仔细看了官方文档   
http://echarts.baidu.com/api.html#echarts    如下：

ECharts 3 中支持直接使用canvas元素作为容器，这样绘制完图表可以直接将 canvas 作为图片应用到其它地方，例如在 WebGL 中作为贴图，这跟使用 echartsInstance.getDataURL 生成图片链接相比可以支持图表的实时刷新。   

之前我都是直接用div做容器，这次直接使用canvas做标签，发现渲染tooltip无法生成，这个地方可能是个bug，希望官方能修改吧。

浪费了一天找这种问题，蛋疼。
