### ISSUE TITLE
仪表盘设置markarea报错

### ISSUE THREAD

**Issue by mangoZT** [ecomfe/echarts#5544]
### One-line summary [问题简述]
仪表盘无法设置markarea
按照API设置后报错  

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
![image](https://cloud.githubusercontent.com/assets/26948222/25212170/7aee23fe-25bb-11e7-9c1d-b4d4b4ed62cc.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
仪表盘不支持 markArea
