### ISSUE TITLE
折线图分区段填充颜色

### ISSUE THREAD

**Issue by jingxiawl** [ecomfe/echarts#5545]
我想问echarts的折线图能实现分区段填充颜色么，现在看到的都是整体填充颜色，不能够分区段去显示颜色，类似下面这种情况
![qq 20170420122833](https://cloud.githubusercontent.com/assets/11657532/25214029/76249770-25c7-11e7-9d92-38554ca08c0f.png)

**Comment by mangoZT** [comment]
![image](https://cloud.githubusercontent.com/assets/26948222/25215766/fc31246e-25d1-11e7-9f42-ceef2f41347c.png)
应该算是可以做的

**Comment by jingxiawl** [comment]
@mangoZT  你这个是怎么实现的，有具体代码么。你这个是根据x轴的区间段来区分颜色的么？我想做的是根据值来控制颜色，

**Comment by mangoZT** [comment]
areaStyle来设置，具体的可以看下API   至于颜色你可以判断值再传进来你要的颜色  不影响

**Comment by jingxiawl** [comment]
areaStyle是位于哪个下面的呢？而且你这个是按x轴标注来划分区间，我想表达的是根据曲线所处的段来展示不同的颜色
大概意思就是这个
http://echarts.baidu.com/demo.html#line-aqi  
类似这个范例，我想做的是不同颜色段的线条下面的区域填充不同的颜色

**Comment by mangoZT** [comment]
曲线图 不是面积图啊

**Comment by jingxiawl** [comment]
@mangoZT  恩。但是效果展示出来跟面积图相似，就是在刚才那个折线图的基础上，每个区间段的线条颜色是不同的，我想做的是在不同颜色线条下面的区域也填充上对应线条的颜色，

**Comment by mangoZT** [comment]
我不太清楚你的效果是撒   可否发个示意图   我晚点帮你看下

**Comment by jingxiawl** [comment]
我也想发图片可以github现在上传不了图片了。我也很懵逼。有什么方式可以吧图片发给你么

**Comment by jingxiawl** [comment]
![p70420-142616_](https://cloud.githubusercontent.com/assets/11657532/25217939/6750872c-25db-11e7-80e9-10f121939c12.jpg)

终于上传图片成功了，我自己画了个示意图，就是类似这个意思

**Comment by mangoZT** [comment]
图呢，没看到啊  我明天帮你看

**Comment by jingxiawl** [comment]
@mangoZT 没看到吗？我这边都看到了。你要不要留个qq我加你

**Comment by mangoZT** [comment]
看到了  但是你这个图  我看不懂啊  尴尬

**Comment by mangoZT** [comment]
![image](https://cloud.githubusercontent.com/assets/26948222/25260164/e24fefde-267c-11e7-99ca-47725179651e.png)
是这个效果么

**Comment by jingxiawl** [comment]
@mangoZT  不是这个。色段是竖着的，我处理了个图片你再看看
![qq 20170421102801](https://cloud.githubusercontent.com/assets/11657532/25260327/1473edc0-267e-11e7-80af-0bebee881956.png)

**Comment by mangoZT** [comment]
不就是这个图嘛

**Comment by mangoZT** [comment]
看二楼的图

**Comment by jingxiawl** [comment]
不是的，你看到分割虚线了么，色块是根据那个分割虚线来确定的，而不是根据x轴来确定的

**Comment by jingxiawl** [comment]
不知道我表达清楚没有

**Comment by mangoZT** [comment]
好像不太能达到你要的实现方法  但是实现结果是一样的   不需要分段

**Comment by jingxiawl** [comment]
有具体代码么？我要做的就是要根据数据来分段填充颜色，看了很久文档都没看到

**Comment by mangoZT** [comment]
自己设置图例和分割线  通过判断值传入不同的颜色值  目前我是这么实现的   直接API实现的我就不太清楚了

**Comment by jingxiawl** [comment]
不是很懂。可以吧实现结果一样的代码发我看看么？我参考参考

**Comment by mangoZT** [comment]
app.title = '坐标轴刻度与标签对齐';

option = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
 visualMap: {
        top: 10,
        right: 10,
        pieces: [{
            gt: 0,
            lte: 50,
            color: '#096'
        }, {
            gt: 50,
            lte: 100,
            color: '#ffde33'
        }, {
            gt: 100,
            lte: 150,
            color: '#ff9933'
        }, {
            gt: 150,
            lte: 200,
            color: '#cc0033'
        }, {
            gt: 200,
            lte: 300,
            color: '#660099'
        }, {
            gt: 300,
            color: '#7e0023'
        }],
        outOfRange: {
            color: '#999'
        }
    },
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220]
        }
    ]
};

**Comment by mangoZT** [comment]
分割线自己加一下代码即可

**Comment by jingxiawl** [comment]
这个做出来是柱状图了。哎。看来这个效果不能实现了呢。哀伤

**Comment by mangoZT** [comment]
折线图不能通过visualMap实现好像   要变通一下  2楼那样   另外自己加分割线  加图例  把图例做成visualMap

**Comment by jingxiawl** [comment]
2 楼那种我看了哈基本属于在x轴上面分段，分割线和图例其实我不需要的，只是为了跟你说明效果添加的。对了2楼的代码可以分享一下么。我看看能不能再那个基础上改一下

**Comment by mangoZT** [comment]
木有保存   多列几个数据项即可 设置areaStyle

**Comment by jingxiawl** [comment]
哦。这样做的。那样也不好处理。之前我也做过这个样子。问题是我的那种效果会在刻度中间出现分段。基本上好像没找到方法

**Comment by mangoZT** [comment]
分段？我的图也分段了么

**Comment by jingxiawl** [comment]
不是。你那个始终是在x轴的刻度点进行的分段。但是，我那个需求并不一定是在刻度点分段。可能是刻度点中间分开

**Comment by mangoZT** [comment]
好吧 我尽力了 你再看看

**Comment by jingxiawl** [comment]
恩。好的。谢谢你了。帮我看了那么久

**Comment by zhangyile** [comment]
@jingxiawl  楼主这个问题是怎么解决的呀？我也遇到和你描述一样的需求了。。。

**Comment by kimmyXu** [comment]
> ![image](https://cloud.githubusercontent.com/assets/26948222/25215766/fc31246e-25d1-11e7-9f42-ceef2f41347c.png)
> 应该算是可以做的

@mangoZT  你好，二楼的这种图表代码可以贴出来下吗

**Comment by liubobuzhidao** [comment]
不知道这个答案对于上面的提问还有没有意义，不过我还是想贴上链接https://gallery.echartsjs.com/editor.html?c=xH1As1PegW

**Comment by kimmyXu** [comment]
你发的这个柱状图的高度都一样的，跟我的效果不太一样，不过还是非常感谢

**Comment by Alice-hhu** [comment]
请问大佬们解决了嘛？要是解决了的话可以共享下代码瞅瞅嘛？ @jingxiawl @zhangyile

**Comment by acguokailin** [comment]
> ![image](https://cloud.githubusercontent.com/assets/26948222/25260164/e24fefde-267c-11e7-99ca-47725179651e.png)
> 是这个效果么

请问下能共享一下你这个效果图的代码实现吗，非常感谢

**Comment by amelieykw** [comment]
我也遇到跟各位一样的需求，我找到一个链接，虽然不完全匹配竖着分段颜色的需求，但是可以供参考 https://www.makeapie.com/editor.html?c=x9BToI_0y

**Comment by amelieykw** [comment]
> 我也遇到跟各位一样的需求，我找到一个链接，虽然不完全匹配竖着分段颜色的需求，但是可以供参考 https://www.makeapie.com/editor.html?c=x9BToI_0y

还有 https://www.makeapie.com/editor.html?c=xB9i7zW6lu

**Comment by GTR-YY** [comment]
楼主有解决这个问题吗？我也遇到了这个问题，想请教一下

**Comment by GTR-YY** [comment]
> 楼主有解决这个问题吗？我也遇到了这个问题，想请教一下

![image](https://user-images.githubusercontent.com/58431814/114647805-4b1a8980-9d10-11eb-85d3-67ed9eb7d73d.png)

**Comment by GTR-YY** [comment]
> > 楼主有解决这个问题吗？我也遇到了这个问题，想请教一下
> 
> ![image](https://user-images.githubusercontent.com/58431814/114647805-4b1a8980-9d10-11eb-85d3-67ed9eb7d73d.png)

这个需求

**Comment by xinagcai** [comment]
啊俺也一样解决了吗？？？、

**Comment by xinagcai** [comment]
老铁们我解决了
`  var option = {

        tooltip:{
            show:false,
        },
        grid:{
            rigth:0,
            top:'10',
            left:"20",
        },
        yAxis:

            {	show:true,
                splitNumber: 4,
                splitLine: {
                    show: true
                },
                axisLine:{
                    show:false
                },
                axisTick: {

                    show:false //y轴坐标点消失

                },
                axisLabel: {
                    formatter:function(){
                        return ""
                    }
                },
            },
        xAxis: {
            axisLine:{
                show:false //y轴线消失
            },
            axisLabel: {
                formatter: function (value) {
                    if(value==xdata[4] || value==xdata[0]){
                        return "";
                    }else{
                        return value+'岁'
                    }

                }
            },
            axisTick: {show:false},
            type: 'category',
            boundaryGap: false,
            data: xdata,
        },
        series:[

            {
                smooth: true,
                symbol: 'none',
                type: 'line',
                color:'rgba(24, 144, 255, 0.3)',
                areaStyle: {
                    color:'rgba(24, 144, 255, 0.1)'
                },
                data:[0,1,'-','-','-']

            },
            {
                smooth: true,
                symbol: 'none',
                type: 'line',
                color:'rgba(24, 144, 255, 0.3)',
                areaStyle: {
                    color:'rgba(24, 144, 255, 1)'
                },
                data:['-',1,3,'-','-']

            },
            {
                smooth: true,
                symbol: 'none',
                type: 'line',
                color:'rgba(24, 144, 255, 0.3)',
                areaStyle: {
                    color:'rgba(24, 144, 255, 0.7)'
                },
                data:['-','-',3,3,'-']

            },
            {
                smooth: true,
                symbol: 'none',
                type: 'line',
                color:'rgba(24, 144, 255, 0.3)',
                areaStyle: {
                    color:'rgba(24, 144, 255, 0.3)'
                },
                data:['-','-','-',3,0]

            },

        ]

    };`
![image](https://user-images.githubusercontent.com/66870330/131476593-b6dffd43-088a-4330-adb7-37d6ae02d96e.png)
主要就是series

**Comment by Zhongxiangyun** [comment]
> ![image](https://cloud.githubusercontent.com/assets/26948222/25260164/e24fefde-267c-11e7-99ca-47725179651e.png) 是这个效果么

你好,请问这个效果图的是怎么实现的呢?麻烦分享一下代码

**Comment by zhumadian123** [comment]
**you  can use echart visualMap** 

`option = {
  xAxis: {
    type: 'category',
    boundaryGap: false,
  },
  yAxis: {
    type: 'value',
    boundaryGap: [0, '30%']
  },
  visualMap: {
    seriesIndex:1,
    type: 'piecewise',
    show: false,
    dimension: 0,
    // seriesIndex: 0,
    pieces: [
      {
        gt: 1,
        lt: 3,
        color: 'red'
      },
      {
        gt: 5,
        lt: 7,
        color: 'rgba(0, 0, 180, 0.4)'
      }
    ]
  },
  series: [
    {
      type: 'line',
      smooth: 0.6,
      symbol: 'none',
      lineStyle: {
        color: '#5470C6',
        width: 5
      },
      areaStyle: {
      },
      data: [
        100,200,300,400,500,300,150,420
      ]
    },
        {
      type: 'line',
      smooth: 0.6,
      symbol: 'none',
      lineStyle: {
        color: '#5470C6',
        width: 5
      },
      areaStyle: {
      },
      data: [
        10,20,30,40,50,30,15,42
      ]
    }
  ]
};`
![image](https://github.com/user-attachments/assets/e3b43eb1-4ae9-4d1f-9ed0-450f402858f6)
