### ISSUE TITLE
对不存在的属性进行错误提示

### ISSUE THREAD

**Issue by ihtml5** [ecomfe/echarts#5553]
**问题复现**
![image](https://cloud.githubusercontent.com/assets/6822604/25221041/4ce48180-25e6-11e7-95f2-d2fc7ef29ee8.png)
 > 开发的时候一不小心输错了某个字段名比如type输成tyep，此时echarts会按照默认的方式显示，而不会给予错误信息

**建议**
 能否像react那样，对echarts的配置属性进行检测比对，如果不存在这个属性或者用户配置的属性和要求配置的属性有轻微差异的时候（比如‘type’写成‘tyep’）能给予提醒，而不是直接忽略，走echarts的默认值

**Comment by pissang** [comment]
谢谢建议，我们会考虑出一个属性检查工具
