### ISSUE TITLE
Echarts饼图可以自己设置每个小扇形的半径大小吗？

### ISSUE THREAD

**Issue by 749145134** [ecomfe/echarts#5558]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mangoZT** [comment]
![image](https://cloud.githubusercontent.com/assets/26948222/25260200/289cac70-267d-11e7-866c-f10bfdc229be.png)

**Comment by 749145134** [comment]
这个南丁格尔图的半径大小是随着数据量成正比的，我想要固定每一个扇形的半径大小

**Comment by mangoZT** [comment]
有什么不一样么

**Comment by 749145134** [comment]
南丁格尔图是
    'radius' 面积展现数据的百分比，半径展现数据的大小。
    'area' 所有扇区面积相同，仅通过半径展现数据大小。

**Comment by 749145134** [comment]
他们半径都是随数据变化而变化的，但是我想要固定每一个半径大小，您有什么建议或者想法实现吗？

**Comment by 749145134** [comment]
我想要面积展现数据的百分比，每个扇形半径不同但是不展示数据的大小

**Comment by mangoZT** [comment]
是不是你把数据交换一下 就是你想要的呢

**Comment by 749145134** [comment]
什么意思呢？

**Comment by mangoZT** [comment]
是不是他这个图形是你想要的 只是你理解的数据意义不同罢了   换位思考下是否能使用

**Comment by 749145134** [comment]
额。我明白您的意思，通过改变数据形式去实现需求，但是数据不同的话，它的半径就会变化，因为API说这个半径大小会跟着数据变动的，所以我没想到有什么好的办法

**Comment by mangoZT** [comment]
我的意思是本来数据的地方你写死  把面积地方传入你的数据

**Comment by 749145134** [comment]
额。。。问题数据它都统一管理了半径和面积，没法写死。没法区分半径的数据，和面积的数据

**Comment by 749145134** [comment]
框架应该是把数据拿过来计算半径和面积百分比了，但是我不知道如何去把数据分开，因为api它无法分开。这也是我比较懵比的问题

**Comment by 749145134** [comment]
我的一个想法是写四个扇形饼图，在拼凑成一个圆形，但是我的饼图是实时去数据了，数据改变害怕四个饼图拼凑不成一个圆形。

**Comment by mangoZT** [comment]
我明白你的意思了  我看看啊

**Comment by 749145134** [comment]
恩恩，真是个蛋疼的问题，很感谢您牺牲您的宝贵时间了。

**Comment by mangoZT** [comment]
是均分么  他有一个属性可以均分角度  不会凑不成一个圆

**Comment by 749145134** [comment]
不均分

**Comment by 749145134** [comment]
其实它的图就是南丁格尔图，但是半径我想自己控制

**Comment by 749145134** [comment]
扇形的面积大小是随着数据改动的。

**Comment by 749145134** [comment]
如果分成四个做，我感觉不好实现。

**Comment by mangoZT** [comment]
确实不好弄  我要是搞出来会给你留言的

**Comment by 749145134** [comment]
恩恩，好的谢谢您。

**Comment by Anjiula** [comment]
同问，我这里也有这个需求，面积的数据，和半径的数据没法分开

**Comment by zhangxinjie2017** [comment]
因为roseType 设置为radius，会导致一个问题就是，有一个数据占比非常小，图显示的就会非常小，如果可以设置每个扇区的半径，就可以解决这个问题。

**Comment by DevilHe** [comment]
怎么解决的啊

**Comment by DevilHe** [comment]
请问怎么解决的

**Comment by JohnnyZhang0628** [comment]
我也遇到这个问题了吗，请问有什么方法可以自定义半径

**Comment by lianduy** [comment]
我也遇到这个问题了，请问有什么方法可以自定义半径？

**Comment by JohnnyZhang0628** [comment]
@lianduy 我是通过自定义自己画的扇形，目前Echarts不支持，只能自定义，自己画了。

**Comment by xushenkun** [comment]
也有这个需求，比如：一列数据表达在分类总和中的占比，一列数据表达分类另外维度的大小程度。
南丁格尔图各扇形中心角表达占比，各扇形半径表达另外维度大小。

**Comment by Shzhuoyu** [comment]
2022年前来考古，请问解决了吗

**Comment by drinkwd** [comment]
> 2022古代来考古，求解答
我找了很多方案都是不能设置扇形半径的大小我的解决方案是
可以找出最大值，然后每个数据增加一定的比例，让最小值和最大值的倍数差别没有那么大，然后在根据放大的比例在tooltip展示正确的数据
