### ISSUE TITLE
series中包含空数据时tooltip无法正确联动

### ISSUE THREAD

**Issue by flyfly6** [ecomfe/echarts#5563]
### One-line summary [问题简述]
series中包含空数据时tooltip无法正确联动

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.0及以上
+ Browser version [浏览器类型和版本]:Chrome 59.0.3071.9
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
tooltip在两个connect的图表中可以正确的实现联动

### ECharts option [ECharts配置项]

```javascript
var option1 = {
  title: {
    text: 'chart1'
  },
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: ['今天',
      '昨天', '上周'
    ]
  },
  xAxis: {
    data: ["8:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00"]
  },
  yAxis: {},
  series: [{
    name: '今天',
    type: 'line',
    data: [14, 31, 21, 25]
  }, {
    name: '昨天',
    type: 'line',
    data: [14, 23, 31, 32, 12, 32, 29]
  }, {
    name: '上周',
    type: 'line',
    data: [10, 35, 20, 13, 16, 18, 41]
  }]
};

var option2 = {
  title: {
    text: 'chart2'
  },
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    data: ['今天',
      '昨天', '上周'
    ]
  },
  xAxis: {
    data: ["8:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00"]
  },
  yAxis: {},
  series: [{
    name: '今天',
    type: 'line',
    data: [14, 31, 21, 27]
  }, {
    name: '昨天',
    type: 'line',
    data: [14, 23, 31, 32, 16, 32, 29]
  }, {
    name: '上周',
    type: 'line',
    data: [10, 35, 20, 13, 12, 18, 41]
  }]
};

```

### Other comments [其他信息]

https://codepen.io/flyfly6/pen/vmGzgq
鼠标在图表中移动时，当进入右边包含空数据的区域时tooltip联动会失效，
3.5.0版本引入axisPointer后开始出现该问题，3.4.0版本tooltip可正确联动。

**Comment by 100pah** [comment]
我在 3.5.3 中试验，是正常的。

**Comment by mangoZT** [comment]
空数据用'-'替代一下

**Comment by flyfly6** [comment]
更新了一下，鼠标放到右边没有数据的区域中时， 上下两张图的tooltip无法正确联动
![image](https://cloud.githubusercontent.com/assets/2952657/25480394/34228ee0-2b7b-11e7-8568-521f3e0923f6.png)

**Comment by rascaler** [comment]
> 更新了一下，鼠标放到右边没有数据的区域中时， 上下两张图的tooltip无法正确联动
> ![image](https://cloud.githubusercontent.com/assets/2952657/25480394/34228ee0-2b7b-11e7-8568-521f3e0923f6.png)

兄弟这个解决了吗？我在5.0里仍然是有问题的，这个怎么关闭了

**Comment by rascaler** [comment]
@flyfly6 兄弟这个解决了吗？我在5.0里用的时候还是有问题的，为何这个issue关闭了
