### ISSUE TITLE
时间轴,定义dataZoom拖拽后，被过滤掉的数据点，折线能不能不消失(2)

### ISSUE THREAD

**Issue by MrsKey** [ecomfe/echarts#5564]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

![Uploading 34.png…]()

### ECharts option [ECharts配置项]

`	var main = document.getElementById("main")
			var Mychart = echarts.init(main);
			var data = [
				{ name: '2016/12/18 6:38:08', value: ['2016/12/18 6:38:08', 80]}, 
				{ name: '2016/12/19 9:18:18', value: ['2016/12/19 9:18:18', 60]},
				{ name: '2016/12/20 12:18:18', value: ['2016/12/20 12:18:18', 90]},
				{ name: '2016/12/21 14:38:08', value: ['2016/12/21 14:38:08', 80]}, 
				{ name: '2016/12/22 16:18:18', value: ['2016/12/22 16:18:18', 60]},
				{ name: '2016/12/23 19:18:18', value: ['2016/12/23 19:18:18', 90]},
				{ name: '2016/12/24 19:18:18', value: ['2016/12/24 19:18:18', 90]},
				{ name: '2016/12/25 14:38:08', value: ['2016/12/25 14:38:08', 80]}, 
				{ name: '2016/12/26 16:18:18', value: ['2016/12/26 16:18:18', 60]},
				{ name: '2016/12/27 19:18:18', value: ['2016/12/27 19:18:18', 90]},
				{ name: '2016/12/28 19:18:18', value: ['2016/12/28 19:18:18', 90]}
			];
			var anchor = [
				{ name: '2016/12/18 00:00:00', value: ['2016/12/18 00:00:00']},
				{ name: '2016/12/19 00:00:00', value: ['2016/12/19 00:00:00']},
				{ name: '2016/12/20 00:00:00', value: ['2016/12/20 00:00:00']},
				{ name: '2016/12/21 00:00:00', value: ['2016/12/21 00:00:00']},
				{ name: '2016/12/22 00:00:00', value: ['2016/12/22 00:00:00']},
				{ name: '2016/12/23 00:00:00', value: ['2016/12/23 00:00:00']},
				{ name: '2016/12/24 00:00:00', value: ['2016/12/24 00:00:00']},
				{ name: '2016/12/25 00:00:00', value: ['2016/12/25 00:00:00']}, 
				{ name: '2016/12/26 00:00:00', value: ['2016/12/26 00:00:00']},
				{ name: '2016/12/27 00:00:00', value: ['2016/12/27 00:00:00']},
				{ name: '2016/12/28 00:00:00', value: ['2016/12/28 00:00:00']},
				{ name: '2016/12/29 00:00:00', value: ['2016/12/29 00:00:00']}
			];
			
var startValue = data[data.length-5].name;
			option = {
				title: { text: '动态数据 + 时间坐标轴' },
//				tooltip: {
//					trigger: 'axis',
//					formatter: function(params) {
//						params = params[0];
//						var date = new Date(params.name);
//						return date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + params.value[1];
//					}
//				},
				grid: {
					show: true,
					containLabel: false,
				},
				xAxis: {
					type: 'time',
					splitLine: { show: false },
//					interval: 2,
					//是否显示刻度线
					axisTick:{
//						show:false
					},
					animation:false,
						axisLabel:{
						textStyle:{
							color:'green'
						}
					},
				},
				yAxis: {
					type: 'value',
					boundaryGap: [0, '100%'],
					splitLine: { show: false }
				},
				dataZoom: [{
						xAxisIndex: 0,
						show: false,
						animation:false,
						startValue: startValue
//						},
						//隐藏掉滚动条
						
						
					},
					{
						xAxisIndex: 0,
						type: 'inside',
						show: false,
						//是否锁定选择区域（或叫做数据窗口）的大小。
						zoomLock: true,
						//是否显示滚动条的控制手柄
						calculable: false,
						animation:false,
						throttle:0
					},
				],
				series: [{
//						name: '模拟数据',
						type: 'line',
						showSymbol: true,
						smooth: true,
//						symbol: 'roundRect',
						symbolSize: 10,
						hoverAnimation: false,
						animation:false,
						animationThreshold:false,
						data: data,
//						show:false,
					},
					{
						name: '.anchor',
						type: 'line',
						showSymbol: true,
//						symbol: 'roundRect',
						symbolSize: 10,
						data: anchor,
//						axisLabel:{
//							show:false
//						},
//						show:false,
						animation:false,
						itemStyle: {
//							normal: { opacity: 0 }
						},
						lineStyle: {
//							normal: { opacity: 0 }

						}
					}
				]
			};
			Mychart.setOption(option);

**Comment by 100pah** [comment]
看不到图片，不知道你的期望是什么样的。

**Comment by MrsKey** [comment]
@100pah 
![6](https://cloud.githubusercontent.com/assets/27321463/25649954/0f8b6058-300c-11e7-9289-bd844aa7c63b.png)

**Comment by MrsKey** [comment]
@100pah 要的是这种效果
![2](https://cloud.githubusercontent.com/assets/27321463/25649968/2dda8b42-300c-11e7-83af-73f3e21e6bf4.png)
