### ISSUE TITLE
同一个xAxis轴，能不能同时显示两个handle？

### ISSUE THREAD

**Issue by Sapphire2k** [ecomfe/echarts#5565]
### xAxis能否支持同时显示两个handle
现有的demo
<img width="755" alt="wx20170421-182935 2x" src="https://cloud.githubusercontent.com/assets/17328005/25276767/52efa35a-26ce-11e7-8907-b623acbe3cc5.png">

### Expected behaviour [期望结果]
<img width="755" alt="wx20170421-182935 2x" src="https://cloud.githubusercontent.com/assets/17328005/25276699/f652ba4c-26cd-11e7-86ee-f2e981b8cb63.png">

感谢🙏！

**Comment by 100pah** [comment]
你的这个场景，似乎并不需要 handle？（因为 handle 是能拖动的，一拖动，就不是『卓越』『优秀』的位置了，不知我理解的对不对）
你的场景，可以用 markLine。

现在一个轴只能一个handle，如果要强制实现这个效果，可以用两个重合的 x 轴。
