### ISSUE TITLE
如何禁用地图高亮样式呢？

### ISSUE THREAD

**Issue by yangzhennupt** [ecomfe/echarts#5570]
### One-line summary [问题简述]
我在echarts中用了地图，但是想去掉hover时 地图高亮的颜色，现实地图本身渲染的颜色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mangoZT** [comment]
emphasis设置成一样的即可

**Comment by stzhongjie** [comment]
我的地图用了inRange颜色，emphasis要怎么设置为一样的呢？

**Comment by 7neves** [comment]
地图使用了visualMap进行了视觉映射，如何设置呢
