### ISSUE TITLE
flex布局嵌入echarts bug

### ISSUE THREAD

**Issue by archerLj** [ecomfe/echarts#5572]
### One-line summary [问题简述]
网页布局采用flex布局，这时候嵌入的echarts图表出不来，如果把flex容器内的div给个高度，就能出来了，但是布局就不对了。难道echarts和flex布局不能同时使用？？？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版本
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mangoZT** [comment]
贴下代码看下

**Comment by HeavenZhangHr** [comment]
有没有试试给父容器高度

**Comment by archerLj** [comment]
迫于项目进度，后来把flex全部替换掉了，太久远也没法重现问题了!_!
