### ISSUE TITLE
中国地图数据部分地区缺失

### ISSUE THREAD

**Issue by troy351** [ecomfe/echarts#5573]
### One-line summary [问题简述]

map tools 里面，获取地图数据时有2个市的数据缺失（轮廓数据正确）
http://ecomfe.github.io/echarts-map-tool/
1.  西藏自治区 -> 山南市
2. 新疆维吾尔自治区 -> 哈密市
3. 新疆维吾尔自治区 -> 昆玉市
4. 重庆市市辖区 -> 开州区

**导致原因：行政区划的名称变动，而数据源名称未变**
**建议统一检查一遍所有地图数据是否存在**

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.3
+ Browser version [浏览器类型和版本]: Chrome 58
+ OS Version [操作系统类型和版本]: Windows 19

### Expected behaviour [期望结果]

请尽快恢复这些地区的地图数据

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
西藏山南区：https://github.com/ecomfe/echarts/pull/7020
