### ISSUE TITLE
官方事例中 graph-npm 部分在火狐中报错

### ISSUE THREAD

**Issue by Se7enGo** [ecomfe/echarts#5576]
### One-line summary [问题简述]
http://echarts.baidu.com/demo.html#graph-npm 
以上是官方 图关系中的Npm事例，用火狐浏览器打不开，报出 TypeError: e.inEdges is undefined    echarts-all-3.js:37:890  错误
但是以上页面，用360安全浏览器 8.0打开是没有问题的。
自己模仿官方事例，抽出json数据从后台发出，拿到前台页面中也是只能够在360浏览器中展示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: Echarts 3.5.3
+ Browser version [浏览器类型和版本]:firefox 52.0.2 (64 位)，360安全浏览器 8.1.1.158|内核版本45.0.2454.101
+ OS Version [操作系统类型和版本]:window 10 64位

### Expected behaviour [期望结果]
希望官方人员能排查一下，或者能给出最适宜调试的浏览器建议。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![default](https://cloud.githubusercontent.com/assets/20393300/25329615/146f9bb0-290f-11e7-8895-b1cafa63ded3.png)

**Comment by Ovilia** [comment]
这一问题是由于在检查是否插入节点的时候，会检查是否存在该节点，原来带来些的是 `if (nodesMap[id])`，而图中有 id 是 `"watch"`，`Object.watch` 是一个内置方法，因此误以为已存在该节点。用 `hasOwnProperty` 可以避免检查继承来的方法。
