### ISSUE TITLE
手机端内存占用问题

### ISSUE THREAD

**Issue by hnu0416** [ecomfe/echarts#5578]
### One-line summary [问题简述]

为手机端实现报表时，存在内存消耗大，导致app闪退，请问有解决办法么，提供的注销实例办法不给力

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by mangoZT** [comment]
关闭动画
