### ISSUE TITLE
折线图如何在鼠标经过其中的某一条折线的时候，让对应的折线变粗

### ISSUE THREAD

**Issue by HeWenKe** [ecomfe/echarts#5582]
问题：
折线图  这里设置emphasis高亮时候的lineStyle样式，不起作用，Echerts2.0里面的参数说明：指的是高亮时候线条的样式，但是具体测试它是高亮时候每个折线转折点的样式。这个在3.0里面有说明。
```js
series: [
{
     type: 'line',
     name: null,
     tooltip: { ... },
    clickable: true,
    itemStyle: {
         normal: { ... },
         emphasis: {
         color: <图表各异>,
         lineStyle: {
         color: <各异>,
         type: 'solid',
         width: <各异>,
          shadowColor: 'rgba(0,0,0,0)',
        shadowBlur: 5,
        shadowOffsetX: 3,
          shadowOffsetY: 3,
},...}
```

期望结果：
版本：Echarts2.0:
折线图图中：当鼠标滑过每一条折线的时候，可以设置当前折线的样式，比如当前折线变粗，变颜色。

### ECharts option [ECharts配置项]
```js
option = {
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
      
        {
            name:'邮件营销',
            type:'line',
           itemStyle: {
			emphasis: {//这里设置高亮时候的样式
                          color: "#ccc",
                          lineStyle: {
                              color: "#ccc",
                              type: 'solid',
                              width:20
                          }
                   }
           
           },
            stack: '总量',
            data:[120, 132, 101, 134, 90, 230, 210]
        }
    ]
};
```

**Comment by pissang** [comment]
这个支持已经在计划中

**Comment by aqiongbei** [comment]
@pissang 改项功能是不是还没支持呢？我看当前版本(`4.2.1`)文档中还没有关于line的配置项
![image](https://user-images.githubusercontent.com/20841215/75090052-e9421200-5599-11ea-8208-3c09873c455c.png)

**Comment by jiankang-wang** [comment]
可以利用事件监听：

`
let currentEcharts = null;

const onEvents = {
  mouseover: (e) => {
    currentEcharts.getEchartsInstance().setOption({
      series: {
        name: e.seriesName,
        symbolSize: 6,
        lineStyle: {
          width: 6,
        },
      },
    });
  },
  mouseout: (e) => {
    currentEcharts.getEchartsInstance().setOption({
      series: {
        name: e.seriesName,
        symbolSize: 4,
        lineStyle: {
          width: 2,
        },
      },
    });
  },
};

             <ReactEcharts
               style={{ minHeight: '500px' }}
               theme={echartsTheme.themeName}
               option={this.getOption()}
               ref={(e) => { currentEcharts = e; }}
               onEvents={onEvents}
             />
`

**Comment by hgrourou** [comment]
> 是不是还没支持呢？我看当前版

这个在v5版本中支持了
