### ISSUE TITLE
v3的中国地图名字没有居中，v2的好多了

### ISSUE THREAD

**Issue by benweizhu** [ecomfe/echarts#5586]
### One-line summary [问题简述]

V3
![image](https://cloud.githubusercontent.com/assets/5471228/25369221/fb624c70-29b4-11e7-8bb4-4c92ff2fa5ba.png)

V2
![image](https://cloud.githubusercontent.com/assets/5471228/25369236/150573d2-29b5-11e7-9404-c4253f726f16.png)

### Version & Environment [版本及环境]
echart v3
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
期望能够像v2那样，否则，省份的名字都挤在一起去了

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=xHyPl7vyu

**Comment by benweizhu** [comment]
是让我用这个数据吗？

/asset/get/s/data-1469178154210-H1GNZvkO.json

**Comment by benweizhu** [comment]
![image](https://cloud.githubusercontent.com/assets/5471228/25369568/70aeded8-29b7-11e7-89e0-33914fcec7d1.png)
澳门h和香港又挤在一起了

**Comment by benweizhu** [comment]
原来修改cp即可，感谢
```
"properties": {
                "cp": [
                    121.509062,
                    25.044332
                ],
                "name": "台湾",
                "childNum": 6
            }
```

**Comment by benweizhu** [comment]
http://gallery.echartsjs.com/editor.html?c=xHkYNEd2Rx&v=1
