### ISSUE TITLE
npm install echarts 的包中没有echarts-all-3.js文件，导致字符云图没法扩展

### ISSUE THREAD

**Issue by wjtGitHub** [ecomfe/echarts#5590]
### One-line summary [问题简述]

npm install echarts 的包中没有echarts-all-3.js文件，导致字符云图没法扩展，会报错

Component series.wordCloud not exists. Load it first.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

希望在npm包中加入全部图形的文件

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这两个没关系，使用字符云请引入 https://github.com/ecomfe/echarts-wordcloud
