### ISSUE TITLE
集成百度地图, 如何监听地图鼠标缩放事件?

### ISSUE THREAD

**Issue by avkojwer1** [ecomfe/echarts#5597]
### One-line summary [问题简述]
集成百度地图, 如何监听地图鼠标缩放事件?

集成百度地图, 如何监听地图鼠标缩放事件?
  bmap: { }里设置?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
`bmaproam` 事件
