### ISSUE TITLE
定制化折线图的tooltip（如图）

### ISSUE THREAD

**Issue by benweizhu** [ecomfe/echarts#5599]
### One-line summary [问题简述]

![image](https://cloud.githubusercontent.com/assets/5471228/25419251/1c101752-2a84-11e7-8661-b99ee717f02d.png)
需要自定义折线图的tooltip

但是tooltip的formatter上说，必须是item才能用，有什么办法可以破？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
3.4

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这种也是能用 formatter 的

**Comment by benweizhu** [comment]
```
axisPointer: {
            label: {
              formatter: function (params) {
                console.log(params)
                return `降水量 ${params.value}`;
              }
            }
          }
```
我发现其实我想要的是这个~
PS：@pissang，你回复的好看

**Comment by pissang** [comment]
那是不行的

**Comment by benweizhu** [comment]
我想要的正好是这个效果

![image](https://cloud.githubusercontent.com/assets/5471228/25429387/5fb63fbe-2aab-11e7-8eb2-8785f07499f3.png)
