### ISSUE TITLE
有办法下载ECharts官网上範例代碼內的json档案吗

### ISSUE THREAD

**Issue by RoxetteI** [ecomfe/echarts#5603]
### One-line summary [问题简述]

有办法下载ECharts官网上的json档案吗，
例如我在 
http://echarts.baidu.com/gallery/editor.html?c=doc-example/bar-dataZoom-filterMode
下载了一个范例，並且在本机执行，但其中有段代码为:
..
$.get('data/asset/data/obama_budget_proposal_2012.list.json', function (obama_budget_2012) {
    myChart.hideLoading();
..

因为需要get json，所以导致范例在本机端无法执行，请问有办法下载到json的代码档吗，谢谢。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.3
+ Browser version [浏览器类型和版本]:  IE11, Chrome
+ OS Version [操作系统类型和版本]: win 7,10

### ECharts option [ECharts配置项]

``

`javascriptmyChart.showLoading();
$.get('data/asset/data/obama_budget_proposal_2012.list.json', function (obama_budget_2012) {
    myChart.hideLoading();

    option = {
        tooltip : {
            trigger: 'item'
        },
        legend: {
            data: ['Growth', 'Budget 2011', 'Budget 2012'],
            itemGap: 5
        },
        grid: {
            top: '12%',
            left: '1%',
            right: '10%',
            containLabel: true
        },
        xAxis: [
            {
                type : 'category',
                data : obama_budget_2012.names
            }
        ],
        yAxis: [
            {
                type : 'value',
                name : 'Budget (million USD)',
                axisLabel: {
                    formatter: function (a) {
                        a = +a;
                        return isFinite(a)
                            ? echarts.format.addCommas(+a / 1000)
                            : '';
                    }
                }
            }
        ],
        dataZoom: [
            {
                type: 'slider',
                show: true,
                start: 94,
                end: 100,
                handleSize: 8
            },
            {
                type: 'inside',
                start: 94,
                end: 100
            },
            {
                type: 'slider',
                show: true,
                yAxisIndex: 0,
                filterMode: 'empty',
                width: 12,
                height: '70%',
                handleSize: 8,
                showDataShadow: false,
                left: '93%'
            }
        ],
        series : [
            {
                name: 'Budget 2011',
                type: 'bar',
                data: obama_budget_2012.budget2011List
            },
            {
                name: 'Budget 2012',
                type: 'bar',
                data: obama_budget_2012.budget2012List
            }
        ]
    };

    myChart.setOption(option);

});

```




### Other comments [其他信息]
<!-- For example: Screenshot or Online demo -->
<!-- [例如，截图或线上实例 (JSFiddle/JSBin/Codepen)] -->

**Comment by pissang** [comment]
chrome 开发者工具里可以看到这个链接

**Comment by RoxetteI** [comment]
@pissang  , thanks, 我在Chrome 开发工具\Network看到了，谢谢。

**Comment by muzi-8** [comment]
@RoxetteI @pissang 你好，我也遇到这个问题，但是在chrome开发工具中的\network中并没有看到相应的json文件，请问怎么获得呢？谢谢
