### ISSUE TITLE
饼图hover到每一项的label时，可以也让饼图弹出吗？

### ISSUE THREAD

**Issue by benweizhu** [ecomfe/echarts#5605]
### One-line summary [问题简述]

当鼠标hover到label上时，
![image](https://cloud.githubusercontent.com/assets/5471228/25429547/f4dc892c-2aab-11e7-8f0e-b06e1c600d04.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

3.4

### Expected behaviour [期望结果]
弹出半径圆

![image](https://cloud.githubusercontent.com/assets/5471228/25429534/e86f3248-2aab-11e7-8bea-a92d931f71c8.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时不行
