### ISSUE TITLE
series name colliding with data point name, affects emphasis when hovering over legend

### ISSUE THREAD

**Issue by something3** [ecomfe/echarts#5606]
### One-line summary [问题简述]
series name colliding with data point name, affects emphasis when hovering over legend

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
When mouse is over legend item, corresponding data should be emphasized. For the item that shares the name with the series, all data is emphasized instead. Hovering over the graph item works as expected.

See pictures to understand more.

Reproducable in the editor of echarts-examples https://ecomfe.github.io/echarts-examples/public/editor.html?c=pie-simple

(just change the name of a ~~data item~~ series)
![echarts_bug](https://cloud.githubusercontent.com/assets/10012815/25433842/35f1ce08-2a8a-11e7-872d-42542f77f798.png)
![echarts_bug_2](https://cloud.githubusercontent.com/assets/10012815/25434012/ef51e680-2a8a-11e7-9710-1de027c89bc6.png)
![echarts_bug_3](https://cloud.githubusercontent.com/assets/10012815/25434011/ef51fb84-2a8a-11e7-922b-39c834d213fa.png)

### ECharts option [ECharts配置项]

```javascript
option = {
    title : {
        text: '某站点用户访问来源',
        subtext: '纯属虚构',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        left: 'left',
        data: ['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series : [
        {
            name: '直接访问',
            type: 'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ],
            itemStyle: {
				emphasis: {
					show: true,
					textStyle: {
						fontSize: '30',
						fontWeigth: 'bold',
					}
				}
            }
        }
    ]
};

```

**Comment by pissang** [comment]
In this case I suggest data name not be same with series name.
