### ISSUE TITLE
echart2和echarts3在一个页面使用，不用iframe嵌套，求大神给支招，求思路

### ISSUE THREAD

**Issue by xingfeng1234** [ecomfe/echarts#5608]
### One-line summary [问题简述]

在同一个页面同时使用2和3肯定有兼容性问题，但是我试着画不同图，才开始引用对应的js，加载完后再去除js，还是相互影响。（因为项目用echarts2很多，要都升级为echarts3工作量很大，现在只是引入少量echarts3以及echarts2的升级）。
另外，页面没有分模块，只是一个页面多个布局。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
ECharts3的引入和部分echarts2的升级。
测试用chrome浏览器
win10 64位

### Expected behaviour [期望结果]
2和3在同一页面不相互影响。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by xingfeng1234** [comment]
2用require AMD模式，3用script标签模式，做的demo上能共同展现。问题是，要把项目的2改成require模式代码量很大，以前都是用的script标签模式引入。现在的想法是，2的引入方式保持不变，把3改成require模式，但是3的require模式看echarts问题，好像不支持了。继续探究中……（也求大拿帮忙指指路）

**Comment by xingfeng1234** [comment]
已解决，奋斗不已，学习不止。

**Comment by gufeng20081010** [comment]
怎么解决的呢？

**Comment by wangtun** [comment]
@xingfeng1234 同问，怎么整的呢？

**Comment by xingfeng1234** [comment]
用require.js引入3，2正常引入
