### ISSUE TITLE
有没有C++的接口扩展？

### ISSUE THREAD

**Issue by smartseal** [ecomfe/echarts#5609]
### 如何在C++程序中使用ECharts，或者说有C++接口扩展吗？
用MFC做的桌面应用，想要展示图标，心怡ECharts，但是不知道怎么用在C++工程里。
网上搜到QT5使用ECharts的文章，可我是MFC啊。

可不可以提供一个C++下面使用ECharts的思路？
C++有json和javascript的扩展包，可不可以通过这个扩展包调用？

是不是Echarts一定依赖于浏览器展示？这样的话可不可以通过一个IE的Com控件？或者Chromium/CEF？

### Expected behaviour [期望结果]
在MFC工程里展示Echarts图表

**Comment by pissang** [comment]
嗯依赖浏览器

**Comment by smartseal** [comment]
那是不是说，只要我C++工程里通过某种方式调用了浏览器控件，就可以展现ECharts了？
