### ISSUE TITLE
关于地图的问题

### ISSUE THREAD

**Issue by jnie666** [ecomfe/echarts#5612]
### One-line summary [问题简述]
你好，最近有一个需求：需要展示🇦🇷阿根廷，🇧🇷巴西的地图。地图有中国、世界和美国的绘制，请问，我想构建巴西的图，阿根廷等其他国家的要如何绘制？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome57，360最新版本
+ OS Version [操作系统类型和版本]:windows 、mac

### Expected behaviour [期望结果]
希望展示🇦🇷阿根廷，🇧🇷巴西等echarts没有展示的地图
跪求。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by JoelsZhou** [comment]
跪求英国和澳大利亚的地图json数据

**Comment by pissang** [comment]
https://github.com/pissang/starbucks/tree/gh-pages/json

**Comment by jnie666** [comment]
<img width="788" alt="map" src="https://cloud.githubusercontent.com/assets/19723678/25492272/1c223d98-2ba5-11e7-9dee-df2d1ded0ec5.png">
<img width="560" alt="code" src="https://cloud.githubusercontent.com/assets/19723678/25492306/3d56fd1e-2ba5-11e7-93e2-116d57cf7432.png">
下载了Brazil.json，构建了如图，求解。

**Comment by jnie666** [comment]
巴西🇧🇷请问有按照身份分布的地图麽？
<img width="371" alt="bar" src="https://cloud.githubusercontent.com/assets/19723678/25513192/f2b2f0d6-2c05-11e7-967c-b7f2810e8d87.png">
