### ISSUE TITLE
建议支持拓扑图

### ISSUE THREAD

**Issue by sdhulijun** [ecomfe/echarts#5613]
### One-line summary [问题简述]

建议支持拓扑图显示，比如网络拓扑图

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by feliving** [comment]
是的，力引导布局图是不是可以用来布局网络拓扑图？
