### ISSUE TITLE
请教：绘制完成后是否有api获取所有节点和节点的坐标

### ISSUE THREAD

**Issue by feliving** [ecomfe/echarts#5614]
请教个问题：
比如力引导布局图，我们传入的参数是节点和链接关系，并不需要计算坐标。echart绘制完之后是否有回调，或者其它api可以获取到当前绘图结果后的所有点，和点的坐标值。 或者请教有什么其它纯粹的计算出这个布局坐标的js库

**Comment by pissang** [comment]
getOption 得到的 option 里每个节点都有 `x`, `y`

**Comment by aaron18106** [comment]
力引导布局产生的关系图中，使用 getOption 获取到的 option 中节点并没有 `x`,`y` 属性。是我获取的方式不对还是我没找对位置呢？

我查找的位置:option.series[0].data。

我现在做的产品需要一起生成多个关系图，它们使用的节点和连线都是相同的。我们希望可以保证多个关系图中的节点位置一致。我想到的方法就是先使用力引导布局生成一个关系图，获取到节点位置。剩下的关系图使用得到的位置信息生成。我遇到的困难是如何获取到节点位置。所以我搜索到了这个 issue，但是我实验得到的结果如开始所说。希望得到指点。

**Comment by pissang** [comment]
@aaron18106 @feliving 抱歉搞错了，布局的位置并没有存在节点的 `x`, `y` 属性中。而是统一存放在了一个 Object 中，可以通过下面这个方法访问到这个 Object，属性是节点名，值是节点位置

```js
myChart.getModel().getSeriesByIndex(seriesIndex).preservedPoints
```

**Comment by aaron18106** [comment]
多谢指教！

按照您的方法，已经尝试成功。

**Comment by some-code** [comment]
你好，在echarts3.8和4.0版本中，已经没有preservedPoints方法，请问该如何实现该需求呢？

**Comment by happyeverday** [comment]
你好，在echarts3.8和4.0版本中，已经没有preservedPoints方法，请问该如何实现该需求呢？

**Comment by Freddoctor** [comment]
同求  已经没有这个api了

**Comment by krislee94** [comment]
### 解决方案

1.
``` 
      var model  = myChart.getModel().getSeriesByIndex(seriesIndex);
```

2. 
```
    var info  = model.getData();
```

然后在返回的信息里，_itemLayouts 就是返回的坐标位置， 如果想得到像素点，可以使用[convertToPixel](https://www.echartsjs.com/zh/api.html#echartsInstance.convertToPixel)
