### ISSUE TITLE
如何控制饼图容器的width和height

### ISSUE THREAD

**Issue by benweizhu** [ecomfe/echarts#5618]
### One-line summary [问题简述]

![image](https://cloud.githubusercontent.com/assets/5471228/25513664/70592e30-2c09-11e7-8021-2bab2c5ff726.png)

饼图自动计算出来一个400 * 300的大小

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

3.4 
Chrome

### Expected behaviour [期望结果]

期待，能够减少Canvas中的padding，让它的canvas大小和实际饼图大小更接近

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-pie.radius

**Comment by benweizhu** [comment]
```
this.state = {
      option: {
        title: {
          text: props.title,
          x: 'center',
          textStyle: {
            color: '#465261',
            fontSize: 16
          },
          top: 50,
        },
        tooltip: {
          show: false,
          trigger: 'item',
          formatter: '{b}: {d}% ({c})'
        },
        series: [
          {
            legendHoverLink: false,
            legendAnimation: false,
            hoverAnimation: false,
            selectedOffset: 0,
            type: 'pie',
            radius: ['25%', '32%'],
            data: props.data
          }
        ]
      }
    };
```
radius已经调小为UX给的那个大小，但是还是画图太大，导致外部容器大小太大了

**Comment by benweizhu** [comment]
![image](https://cloud.githubusercontent.com/assets/5471228/25514135/2ebd0bb4-2c0d-11e7-9949-614f292d5156.png)

两边的空白太多了，饼图大小就要这么大的

**Comment by pissang** [comment]
那把容器尺寸调小呗

**Comment by benweizhu** [comment]
嗯，找到原因了，因为用的echart react，那个作者自己在它的最外层div加了一个style，我没法只能用important去复写了~哎
