### ISSUE TITLE
Map 图通过 setOption 更新 title 无效。

### ISSUE THREAD

**Issue by hustcc** [ecomfe/echarts#5622]
Hello，我这边 [echarts-for-react](https://github.com/hustcc/echarts-for-react) 有用户提出 issue，地址在这里：https://github.com/hustcc/echarts-for-react/issues/52

具体是每次变化 option 中的 title 之后，再 setOption，Map 地图的 title 不会变化。具体见下面的描述和重现方式。

### One-line summary [问题简述]

echarts 的 Map 图表可能存在 setOption 之后，没有更新 title 字段（**不排除还有其他字段没有更新**）。个人测试柱形图是可以动态更新 title 的。

有两个简单的 demo 可以查看效果：

[动态柱形图](http://git.hust.cc/echarts-for-react/#/echarts/dynamic)
[动态 china 地图](http://git.hust.cc/echarts-for-react/#/echarts/map)

这两个图都使用了定时器，每隔 1 秒钟更新一下数据（包括 title）然后在 setState，组件会自动执行 setOption。

**柱形图会自动更新 title，china 地图不会自动更新。**

具体代码这里：https://github.com/hustcc/echarts-for-react/blob/master/demo/MapChartComponent.jsx#L14-L18

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:"3.5.3"
+ Browser version [浏览器类型和版本]:Chrome  57.0.2987.133 (64-bit)
+ OS Version [操作系统类型和版本]: Mac 10.11.6

### Expected behaviour [期望结果]

China 地图应该和柱形图一样，可以自动更新 title。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

在线实例：http://git.hust.cc/echarts-for-react/#/echarts/map?_k=7duy8u

**除了option 中的 title 字段，有可能还有其他字段不能动态更新，建议检查。**

**Comment by 100pah** [comment]
我在你的这个例子 [动态 china 地图](http://git.hust.cc/echarts-for-react/#/echarts/map) 的如下截图中`setOption` 处打了个断点，发现传入 echarts 的 `option.title.text` 一直是 `'iphone销量'` 没变过。

所以我感觉这可能是 echarts 外的问题。

![image](https://cloud.githubusercontent.com/assets/1956569/25556813/83293888-2d36-11e7-9679-43126608edb0.png)

**Comment by hustcc** [comment]
恩，确认了，是提 issue 的同学代码问题。

**Comment by zhoufanglu** [comment]
请问解决了吗 确实有这个问题
