### ISSUE TITLE
Echarts中app.config问题

### ISSUE THREAD

**Issue by ZCForFree** [ecomfe/echarts#5627]
### One-line summary [问题简述]
(index):780 Uncaught ReferenceError: app is not defined

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个是示例里面的环境变量，放到自己应用里的时候请去掉

**Comment by ZCForFree** [comment]
您这里所说的去掉，是把app.config={}中的所有内容都去掉吗？全去掉的话，那个下拉框选择框便不能使用，不能进行维度选择，便不能与散点图坐标系中的维度进行交互。

**Comment by pissang** [comment]
这个是示例页面提供的功能，不是 echarts 的，单纯拷贝代码没法使用这个功能

**Comment by ZCForFree** [comment]
这个功能是哪个js插件提供的呢？和hm.js与dat.gui.min.js有没有关系？

**Comment by pissang** [comment]
是 [dat.GUI](https://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage)

**Comment by ZCForFree** [comment]
您那里有脱离官网的散点图示例吗？脱离网站http://echarts.baidu.com/demo.html#scatter-nutrients。
我不清楚您是怎样在示例中重写dat.gui.min.js的。
需要您给指导一下。

**Comment by cehceh1** [comment]
你好，你的问题解决了吗？

**Comment by mwj2011** [comment]
问题解决了吗

**Comment by feichaohao** [comment]
问题咋解决
