### ISSUE TITLE
饼图如何实现缝隙？

### ISSUE THREAD

**Issue by AntiMoron** [ecomfe/echarts#5629]
### One-line summary [问题简述]：
我想要实现如下图的效果，有什么办法吗？

![image](https://cloud.githubusercontent.com/assets/6587734/25603407/fe370804-2f2d-11e7-839d-94efa1d462dc.png)

**Comment by AntiMoron** [comment]
目前主要是缝隙的配置项找不到

**Comment by 3020658** [comment]
series->itemStyle->normal  设置  borderWidth 和 borderColor 就可以实现了

下面是例子：
series : [
        {
            name: '访问来源',
            type: 'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[..... ],
            itemStyle: {
                normal:{
                        borderWidth:1,
                        borderColor:"#fff"
                }
            }
        }
    ]

**Comment by AntiMoron** [comment]
@3020658  感谢。
