### ISSUE TITLE
如何制作地图json数据

### ISSUE THREAD

**Issue by qryt520** [ecomfe/echarts#5632]
### One-line summary [问题简述]
网站只有地级市的地图json数据，我需要县级市这一层的地图json数据
不知道如何制作地图json数据。我需要义乌市的地图json数据，thks
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]:
Firefox 52
+ OS Version [操作系统类型和版本]:
win7 64位
### Expected behaviour [期望结果]
给我一个义乌市的地图json数据
或者教下我怎么制作地图json数据

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://ecomfe.github.io/echarts-map-tool/
