### ISSUE TITLE
"coordinates":["@@AHV@BDCPEPLENFHCJHFBNCAGBGXWFIBGCGMUKKCCcGCDGBALCPIAAPGR"]

### ISSUE THREAD

**Issue by 18671459332** [ecomfe/echarts#5640]
"coordinates":["@@AHV@BDCPEPLENFHCJHFBNCAGBGXWFIBGCGMUKKCCcGCDGBALCPIAAPGR"]，字符串与坐标数组是什么对应关系，坐标数组压缩规则是什么？我需要修改某些坐标数组，上海市静安区和闸北区已经合并，我需要把这两个区的坐标数组合并。

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-map-tool/tree/gh-pages/maker/raw 这里有原始的 GeoJSON

**Comment by 18671459332** [comment]
这个原始数据也有问题，没有崇明区，宝山区还少一部分。
