### ISSUE TITLE
支持打印，导出csv和pdf

### ISSUE THREAD

**Issue by wei-hai** [ecomfe/echarts#5644]
### One-line summary [问题简述]
菜单支持打印，导出csv和pdf功能

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: Mac OSX

### Expected behaviour [期望结果]
菜单支持打印，导出csv和pdf

### ECharts option [ECharts配置项]

```javascript
option = {
showPrint: true,
saveAsPDF: true,
saveAsCSV: true
}

```

**Comment by pissang** [comment]
暂时没这个计划，欢迎帮忙贡献
