### ISSUE TITLE
tooltip在小屏幕的情况下，显示位置有问题

### ISSUE THREAD

**Issue by semdy** [ecomfe/echarts#5645]
### One-line summary [问题简述]
tooltip在小屏幕的情况下，显示位置有问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: chrome 58
+ OS Version [操作系统类型和版本]: windows 10

### Expected behaviour [期望结果]
tooltip在左边显示空间不够的情况下，往右飘

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/9401913/25645975/24812338-2fe6-11e7-93eb-271d8756ccea.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#tooltip.confine
