### ISSUE TITLE
散点（气泡）图 支持同时显示多个tooltip那?

### ISSUE THREAD

**Issue by zhuwei** [ecomfe/echarts#5646]
我在文档中没有查到相关配置呢?   比如说多个散点（气泡）重合在一起,  鼠标经过时, 怎么同时显示出多个tooltip?

**Comment by pissang** [comment]
tooltip.trigger 改为 'axis' 试试

**Comment by zhuwei** [comment]
这个是根据x或y轴, 直线来的
有没有只根据重合部分?  就是说  仅仅是两个圆重叠了. 鼠标放上去 同时显示两个tooltip..

**Comment by pissang** [comment]
暂时还没有这样的功能

**Comment by zhuwei** [comment]
明白了, 谢谢
