### ISSUE TITLE
图表在不显示坐标轴的情况下，整体偏右

### ISSUE THREAD

**Issue by semdy** [ecomfe/echarts#5647]
### One-line summary [问题简述]
图表在不显示坐标轴的情况下，整体偏右

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.3.2
+ Browser version [浏览器类型和版本]: chrome 58
+ OS Version [操作系统类型和版本]: windows 10

### Expected behaviour [期望结果]
图表在不显示坐标轴的情况下，居中

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/9401913/25646546/0afd20dc-2fec-11e7-8caa-fb8c724c7d78.png)

**Comment by semdy** [comment]
目前的做法是通过css整体往左移20px，有没有内置接口让它整体居中

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#grid.containLabel 这个设为 false 试试？
