### ISSUE TITLE
visualMap[i]-piecewise分段型视觉映射组件中的pieces[{ gt: 10, lte: 15, label: '危险',symbol: 'emptycircle',symbolSize:5,color:'red'}],修改图元类型出现的 问题

### ISSUE THREAD

**Issue by MrsKey** [ecomfe/echarts#5649]
visualMap[i]-piecewise分段型视觉映射组件中的pieces[{ gt: 10, lte: 15, label: '危险',symbol: 'emptycircle',symbolSize:5,color:'red'}],修改图元类型出现的问题

注意：当我修改pieces[{ gt: 10, lte: 15, label: '危险',symbol: 'emptycircle',symbolSize:5,color:'red'} ]中一定范围内的图元类型时（现在修改成了空心圆emptycircle）出现了问题，，修改完成后，我点击‘危险’字体时，小圆圈会消失，并且整个visualMap视觉组件都会向左或向右移动，而我不修改symbol类型时，即是默认情况下，，点击危险，这时图元不会消失，图元和字体（危险）一样变成灰色状态

### One-line summary [问题简述]

修改图元 类型后的效果
![1](https://cloud.githubusercontent.com/assets/27321463/25650288/62b3d0d8-300e-11e7-9cc4-76d0312b670c.png)

不修改图元类型的效果

![3](https://cloud.githubusercontent.com/assets/27321463/25650318/92a408a8-300e-11e7-9eb3-22835bb460ae.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by MrsKey** [comment]
还有，上图中的红色箭头处，即图元，怎么改变它的大小，，视乎在pieces[ ]中使用symbolSize:5，属性改变的是折线上面的图元大小 ，这个怎么解决？

**Comment by MrsKey** [comment]
核心代码是：
![9](https://cloud.githubusercontent.com/assets/27321463/25651758/469462ec-3017-11e7-8d11-db8624c30222.png)

**Comment by 100pah** [comment]
加上这个设置就应该正常了：

```js
visualMap: {
    type: 'piecewise',
    ...
    pieces: [
        ...
    ],
    outOfRange: {
        color: '#ccc',
        symbol: 'emptyCircle'
    }
},
```
