### ISSUE TITLE
有没有什么方法可以调整漏斗图每层的高度呢

### ISSUE THREAD

**Issue by hecomzhangzhiguo** [ecomfe/echarts#5653]
因为我们的每个阶段是固定的一个流程，比如A->B->C,只能最上面是A,最下面是C，A有可能数据是20%，B可能是10%，C可能是70%，看A到B到C的转化率，那么数据的多少只能靠高度来标记，跪求解决方案。

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/7076 ，已列入计划中

**Comment by hecomzhangzhiguo** [comment]
已经自己改源码实现了。

**Comment by Ovilia** [comment]
已支持，见 #7076
