### ISSUE TITLE
一个serie只能设置一种类型的markPoint?

### ISSUE THREAD

**Issue by jimliang** [ecomfe/echarts#5660]
### One-line summary [问题简述]

```javascript
series[i].markPoint | Object
```

文档说明每个serie的markPoint是一个对象，也就是说一个serie只能设置一种类型的markPoint（即使可以是多个标注，但也是同一个 symbol？）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

serie与markPoint是一对多，也就是一个serie可以支持多个类型的markPoint

**Comment by pissang** [comment]
没理解你的意思

**Comment by jimliang** [comment]
```javascript
series: [{
    name: 'serieName',
    type: 'bar',
    data: [...],
    markPoint: {
        symbol: 'circle',
        symbolSize: 20,
        data: [...]
    }
}]
```

@pissang 如代码那样，`serieName`只设置了circle的标注，如果我想针对`serieName`再加其他类型（如rect、arrow）的标注，该怎么做？

**Comment by pissang** [comment]
markPoint.data 每一项都可以单独设置 symbol, symbolSize

**Comment by jimliang** [comment]
OK了，不过建议更新一下文档，没找到相关说明（或者说写得比较隐蔽） @pissang

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-bar.markPoint.data.symbol
