### ISSUE TITLE
legend icon 被压扁了

### ISSUE THREAD

**Issue by benweizhu** [ecomfe/echarts#5662]
### One-line summary [问题简述]

![image](https://cloud.githubusercontent.com/assets/5471228/25688908/9bfe7ed6-30b5-11e7-85d7-7f48b1d4c2ac.png)
Legend icon无论设置为image//还是rect都是被压扁了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

Echart 3.4
Chrome
MacOS

### Expected behaviour [期望结果]
正方形的

![image](https://cloud.githubusercontent.com/assets/5471228/25688927/cf7f47ae-30b5-11e7-9f15-ed7d13a2c556.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#legend.itemWidth
