### ISSUE TITLE
官方实例-multiple-x-axis  bug

### ISSUE THREAD

**Issue by cn-cuss** [ecomfe/echarts#5668]
### One-line summary [问题简述]

官方实例-multiple-x-axis 中,点击legend,鼠标在图标区中移动导致图标崩溃，不能进行后续的操作。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]: chrome 55.0.2883.87
+ OS Version [操作系统类型和版本]: win7 x64

### Expected behaviour [期望结果]
期望实例不要出现问题,目前出现问题,正好项目需要一个图标要实现类似的效果,实列有问题可以推到出实际使用也有问题。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
崩溃指的是什么？
