### ISSUE TITLE
Dot matrix chart? 

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#5675]
Would be nice to have a dot matrix chart similar to this one: 
![image](https://cloud.githubusercontent.com/assets/561365/25739518/83d7759c-3182-11e7-82d3-c60030918f6c.png)

Ideally, dots could be replaced by svg symbols such as this: 
![image](https://cloud.githubusercontent.com/assets/561365/25739541/9749373c-3182-11e7-9c35-e1504ce4342c.png)

The layout should be vertical as well as horizontal. Maybe even radial so it is possible to  generate parliament maps such as this one: 

![image](https://cloud.githubusercontent.com/assets/561365/25739670/28480c72-3183-11e7-862f-f3f00f422032.png)

Thoughts? :)

**Comment by Ovilia** [comment]
@jarben These kinds of charts can be achieved by either [scatter series](http://gallery.echartsjs.com/editor.html?c=xSy6oGlXOW), [pictorial bar series](http://echarts.baidu.com/demo.html#pictorialBar-spirit), or more universally, [custom series](http://echarts.baidu.com/demo.html#custom-hexbin).

**Comment by jarben** [comment]
Hi @Ovilia , yeah, that's a good point. Although layout would need to be computed manually which is probably fine for the parliament map. I think the dot matrix chart is pretty general and could be in theory shipped out of the box? Anyway, thanks for your answer, the recent custom series is definitely so powerful!

**Comment by Ovilia** [comment]
@jarben Thanks for your advice!
