### ISSUE TITLE
能否控制legend的长度和宽度

### ISSUE THREAD

**Issue by huchhong** [ecomfe/echarts#5677]
### One-line summary [问题简述]
legend 的长度和宽度不能自由设置

### Version & Environment [版本及环境]
+ ECharts version [3]:
+ Browser version [chrome]:
+ OS Version [OSX]:

### Expected behaviour [期望结果]

legend的宽度和长度可以自由设置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

从文档里并没有看到legend可以设置长度和宽度或者像grid的x2，y2，而且水平或垂直的列数或行数也无法控制。刚接触echarts不久，不知道是否还有其他方式可以达到以上我想要的控制。

**Comment by huchhong** [comment]
抱歉， 之前看到的是版本2的文档，信息有误。

**Comment by zikuai** [comment]
你好吗，请问下你这个设置宽度跟高度生效吗？为什么我设置的都不生效？
[https://github.com/apache/incubator-echarts/issues/8275](https://github.com/apache/incubator-echarts/issues/8275)
