### ISSUE TITLE
折线图 yAxis的值都是错的。一个折线图时正确，折线图堆叠就乱了。

### ISSUE THREAD

**Issue by HouShengLi** [ecomfe/echarts#5679]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
堆叠就是在之前的值基础上累加
