### ISSUE TITLE
legend 无法显示series中不存在的name

### ISSUE THREAD

**Issue by huchhong** [ecomfe/echarts#5681]
### One-line summary [问题简述]

echarts2 中有一个实例：[实例](http://echarts.baidu.com/echarts2/doc/example/legend.html)。可以在legend中添加series中不存在的name，并显示为没有选中的状态，然后根据legend的事件触发做其他操作。我在echarts3中试了一下，无法显示series中不存在的data name。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.x
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: OSX

### Expected behaviour [期望结果]

echarts3的legend能够显示series中不存在的data name

### ECharts option [ECharts配置项]
参见 [官方实例](http://echarts.baidu.com/echarts2/doc/example/legend.html)

**Comment by pissang** [comment]
3 里对于不存在的 series 会不显示，你的这个需求不建议使用 legend 实现
