### ISSUE TITLE
关系图中两个节点间存在多个同向关系时，只能展示一条关系的问题

### ISSUE THREAD

**Issue by lr17951play** [ecomfe/echarts#5688]
### One-line summary [问题简述]

eCharts中使用关系图展示节点间的关系，当两个节点间存在多个同向关系（eg: 2节点有3个关系，source和target相同，描述和类别不同），这时候echarts只能展示出一种关系，而丢失剩下的两种。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]: Firefox 34.0.5
+ OS Version [操作系统类型和版本]: Windows 7 旗舰版

### Expected behaviour [期望结果]

希望能够根据后台数据展示出节点间存在的所有关系。

### ECharts option [ECharts配置项]

```javascript
option = {

}
展示两节点间存在一个关系时没有问题，option的配置应该正确无误。
```

**Comment by pissang** [comment]
关系图的两个节点之间最多只支持正反两条关系变

**Comment by yinyihui** [comment]
是否有机制能够支持同向的多个关系，有个业务场景是想通过不同的颜色去区分不同的关系，是否有这样的案例可以参考一下，谢谢！！

**Comment by pissang** [comment]
@yinyihui 暂时没这个计划

**Comment by kcker** [comment]
shit

**Comment by Leon-OS** [comment]
关系图的两个节点之间最多只支持正反两条关系边。有选项开关筛选正反向关系吗？
