### ISSUE TITLE
值标签的 formatter 问题

### ISSUE THREAD

**Issue by Christbye** [ecomfe/echarts#5689]
### 简述
其他类型的 formatter 会掉是用 function(name){return xxxx;}这样的形式
但是纸标签的 formatter 文档写的是
(params: Object|Array, ticket: string, callback: (ticket: string, html: string)) => string
![image](https://cloud.githubusercontent.com/assets/5178815/25791509/6c97ca3a-33f3-11e7-95e9-5a2cc131c372.png)
 是否能提供样例以说明如何书写呢?

**Comment by pissang** [comment]
formatter: function (params) { return params.name; }
