### ISSUE TITLE
我要绘制一个东莞市的地图，2版本应该怎么引入地图与注入呢

### ISSUE THREAD

**Issue by fantaishao** [ecomfe/echarts#5692]
希望得到解决的问题：echart2中应该怎么引入地图，比方说东莞市地图？
地图版本 echart 2.2.7
安装方式 bower安装
引入方式
    <script src="bower_components/echarts/build/dist/echarts-all.js"></script>

代码
    ```
  var myChart = echarts.init(element[0],'macarons');
      $http({
        method: 'GET',
        url:'datas/441900.json'
      })
        .then(function (res) {
          echarts.registerMap('东莞市', res.data);
          。。。
}）；


```

后台报错
TypeError: echarts.registerMap is not a function

echart2中应该怎么引入地图呢？

**Comment by pissang** [comment]
http://echarts.baidu.com/echarts2/doc/example/map20.html
