### ISSUE TITLE
xAxis.axisLabel.textStyle.align 居中有误

### ISSUE THREAD

**Issue by zhangya5847** [ecomfe/echarts#5693]
### One-line summary [问题简述]

双x轴，有一个轴的label不能居中显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/15855773/25798540/26d1f1bc-3414-11e7-86a7-0d49cac88c08.png)

**Comment by zhangya5847** [comment]
例子：http://gallery.echartsjs.com/editor.html?c=xHkX9F9pJW

**Comment by sevenen** [comment]
![image](https://cloud.githubusercontent.com/assets/23046337/25878794/f7c505c4-355f-11e7-972b-889db12f4789.png)
这是你年份轴的数据。你要的居中的位置上的数据是空字符串。如果你把那个位置上的空字符串换成2016，自然可以显示了。

**Comment by zhangya5847** [comment]
好的，没有注意，谢谢！
