### ISSUE TITLE
Please help me, I need to know How to create district wise map of India ?

### ISSUE THREAD

**Issue by gursimran-dev-desk** [ecomfe/echarts#5696]
I want to create custom district wise map of india states, just like this website.

https://garv.gov.in/garv2/dashboard

**Comment by pissang** [comment]
https://github.com/pissang/starbucks/tree/gh-pages/json

**Comment by akshayat** [comment]
Cannot use directly, doesn't show some of the Disputed territory. It is not legal to hide these disputed territories. Need json with showing Disputed territories in India's chart.
