### ISSUE TITLE
在上海市地图的数据中，闸北区和静安区没有更新合并

### ISSUE THREAD

**Issue by cysear** [ecomfe/echarts#5698]
### One-line summary [问题简述]
在上海市地图的数据中，闸北区和静安区没有更新合并

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

希望能快点更新json数据以及js文件，万分感谢~~

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by cysear** [comment]
已解决，官网没有更新，github里面已更新 ，但是github里面没有崇明岛的数据，两者合并一下就好了

**Comment by bymain** [comment]
官网的上海数据和github的json数据一样,都没有崇明岛的数据
