### ISSUE TITLE
legend-图例项的icon是一张png图片，该图例未选择状态，icon 的处理

### ISSUE THREAD

**Issue by yishangtanhuan** [ecomfe/echarts#5699]
### One-line summary [问题简述]

legend-图例项的icon是一张png图片，该图例选择状态下icon显示是png图片；如果图例未选择，文字置灰了，icon怎么置灰呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
提供解决办法

**Comment by pissang** [comment]
暂时没办法把图片置灰

**Comment by yishangtanhuan** [comment]
ok，谢谢
