### ISSUE TITLE
echarts3.X配置项文档问题

### ISSUE THREAD

**Issue by irealshow** [ecomfe/echarts#5701]
### One-line summary [问题简述]
**series中type:graph** 
配置项中未列出x,y属性。
layout为none时才指出x、y属性，并且不存在链接说明x,y的具体情况。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by irealshow** [comment]
series中type:graph时，文档中缺少x,y属性的说明

**Comment by pissang** [comment]
已加入
