### ISSUE TITLE
手机版引入地图不显示

### ISSUE THREAD

**Issue by shaipxiang** [ecomfe/echarts#5703]
### One-line summary [问题简述]

手机引入 Echarts.min.js 和china.js后，在手机页面上没显示地图，是不是地图还不支持手机端展示

    <div id="main" style="width:100%;height:100%,margin-top:20px;"></div>
	<script>
		var chart = echarts.init(document.getElementById('main'));
		chart.setOption({
			series: [{
				type: 'map',
				map: 'china'
			}]
		});
	</script>

下面是引入的文件

		<script src="../js/dist/echarts.js"></script>
		<script src="../js/map/js/china.js"></script>

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: 手机自带浏览器
+ OS Version [操作系统类型和版本]:三星手机 Android 5.0.1

### Expected behaviour [期望结果]

请查看下是我配置不对，还是手机端还未实现地图这块的适配

### ECharts option [ECharts配置项]

```javascript
option = {
    series: [{
				type: 'map',
				map: 'china'
			}]
}

```

**Comment by shaipxiang** [comment]
你好，请尽快回复，多谢

**Comment by lxfeng** [comment]
is:issue is:open libEGL: call to OpenGL ES API with no current context
