### ISSUE TITLE
请问如何自定义拓展图表类型，是否有相关的文档和文章

### ISSUE THREAD

**Issue by whisperfairy** [ecomfe/echarts#5706]
### One-line summary [问题简述]

请问关于拓展图表类型的api，如extendChartView，与registerVisual等函数的相关内容请问哪里可以查阅

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.4
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
马上要发布的 3.6.0 将支持自定义图形的系列
