### ISSUE TITLE
河流图TypeError: Cannot read property 'x' of undefined 

### ISSUE THREAD

**Issue by sunstdot** [ecomfe/echarts#5711]
options中是我的数据，这段数据单独画每一条都能正常，但是合并在一起画河流图 就会有报错,echarts 某个使用  data.getItemLayout 的地方报错，找不到数据
```javascript
option = {
    data:[
        [
            15,
            13,
           "林允"
        ],
        [
            16,
            5,
            "林允"
        ],
        [
             17,
             1, 
            "林允"
        ],
        [
            9,
           1,
          "姚晨"
        ],
        [
            13,
            1,
            "姚晨"
       ],
       [
             14,
             1,
             "姚晨"
         ],
         [
              10,
              1,
             "吴亦凡"
         ]
    ]
}
请问pissang大大， 这个河流图 的数据有什么要求么？

**Comment by sunstdot** [comment]
已解决该问题， 是数据格式的问题

**Comment by HaoJie23** [comment]
dataBody.push(["2015/11/09", 10, "DQ"]);
    dataBody.push(["2015/11/10", 10, "DQ"]);
    dataBody.push(["2015/11/11", 10, "DQ"]);
    dataBody.push(["2015/11/08", 10, "SS"]);
    dataBody.push(["2015/11/09", 10, "SS"]);
    dataBody.push(["2015/11/10", 10, "SS"]);
    dataBody.push(["2015/11/11", 10, "SS"]);
    dataBody.push(["2015/11/12", 10, "SS"]);
    dataBody.push(["2015/11/13", 10, "QG"]);
    dataBody.push(["2015/11/08", 10, "QG"]);
    dataBody.push(["2015/11/11", 10, "QG"]);
    dataBody.push(["2015/11/13", 10, "QG"]);


遇到同样问题，请问是如何解决的？
