### ISSUE TITLE
如何自定义series下 makeArea的背景颜色

### ISSUE THREAD

**Issue by lsllsllsl** [ecomfe/echarts#5714]
### One-line summary [问题简述]

<img width="1227" alt="screen shot 2017-05-10 at 2 59 21 pm" src="https://cloud.githubusercontent.com/assets/20367199/25886746/9a71833e-3591-11e7-84dd-c15199e7e551.png">

我想设置这个背景的颜色 而且是在 虚线之前设置一种，虚线之后设置一种颜色，请问怎样设置？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新
+ Browser version [浏览器类型和版本]: chrome 
+ OS Version [操作系统类型和版本]: mac os 10.12.4

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
markArea 设置两个 data
