### ISSUE TITLE
双Y轴问题

### ISSUE THREAD

**Issue by chentao0707** [ecomfe/echarts#5722]
双Y轴的左右刻度对齐的问题

如何设置才能使得双Y轴，左右刻度自动对齐，这样设置splitArea显示的时候不会重叠，谢谢

**Comment by lihuabest** [comment]
同上？

**Comment by chentao0707** [comment]
@lihuabest  后来自己改好了，需要设置min，max，splitnumber，然后计算出interval就可以了，interval = (max - min) / splitnumber
