### ISSUE TITLE
window.onresize = function () { myChart.resize(); //使第一个图表适应 myChart_pieMain.resize(); // 使第二个图表适应 }支持ie8吗

### ISSUE THREAD

**Issue by chenqiaohong** [ecomfe/echarts#5724]
### One-line summary [问题简述]
window.onresize = function () { myChart.resize(); //使第一个图表适应 myChart_pieMain.resize(); // 使第二个图表适应 }支持ie8吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echart3.0
+ Browser version [浏览器类型和版本]:win7
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
支持
