### ISSUE TITLE
折线图分区填色

### ISSUE THREAD

**Issue by arrinhzh** [ecomfe/echarts#5726]
##

### One-line summary [问题简述]

折线图根据y轴值分区填色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows

### Expected behaviour [期望结果]
折线图根据y轴值分区填色，如果是大于0显示红色，小于0显示蓝色
- 

- #

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![2017-05-11_104557](https://cloud.githubusercontent.com/assets/19544024/25940487/dd243c30-3668-11e7-964d-04fedee8c133.jpg)

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=line-aqi
