### ISSUE TITLE
No coordinate system that supports convertToPixel found by the given finder

### ISSUE THREAD

**Issue by Anluis** [ecomfe/echarts#5728]
### One-line summary [问题简述]
在实现这个案例的时候 http://echarts.baidu.com/demo.html#calendar-pie
使用了convertToPixel(finder , value)方法，当 finder =  'calendar' 的时候，出现标题所述警告 ，无法渲染图表

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.2
+ Browser version [浏览器类型和版本]: Chrome 58.0.3029.110
+ OS Version [操作系统类型和版本]: MacOS 10.12.4 

### Expected behaviour [期望结果]
能够使用 该案例 http://echarts.baidu.com/demo.html#calendar-pie

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip : {},
                    legend: {
                        data: ['工作', '娱乐', '睡觉'],
                        bottom: 20
                    },
                    calendar: {
                        top: 'middle',
                        left: 'center',
                        orient: 'vertical',
                        cellSize: [80, 80],
                        yearLabel: {
                            show: false,
                            textStyle: {
                                fontSize: 30
                            }
                        },
                        dayLabel: {
                            margin: 20,
                            firstDay: 1,
                            nameMap: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']
                        },
                        monthLabel: {
                            show: false
                        },
                        range: ['2017-02']
                    },
                    series: [{
                        id: 'label',
                        type: 'scatter',
                        coordinateSystem: 'calendar',
                        symbolSize: 1,
                        label: {
                            normal: {
                                show: true,
//                                formatter: function (params) {
//                                    return this.formatTime('dd', params.value[0]);
//                                },
                                offset: [- 80 / 2 + 10, - 80 / 2 + 10],
                                textStyle: {
                                    color: '#000',
                                    fontSize: 14
                                }
                            }
                        },
                        data: []
                    }]
}
请查看  http://echarts.baidu.com/demo.html#calendar-pie
因为数据是由另外的方法生成的
```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/5006927/25944675/c2648b80-3676-11e7-9aaf-7252213c5c27.png)

**Comment by 100pah** [comment]
请问是在什么样的地方调用的 `convertToPixel(finder , value)`？
可以给个含有调用`convertToPixel(finder , value)`的代码么？

**Comment by Anluis** [comment]
`methods: {
            //模仿案例
           
            getVirtulData() {
                let date = +Date.parse('2017-02-01');
                let end =  +Date.parse('2017-03-01');
                let dayTime = 3600 * 24 * 1000;
                let data = [];
                for (let time = date; time < end ; time += dayTime) {
                    let formatTime = this.formatTime(time);
                    data.push([
                        formatTime,
                        Math.floor(Math.random() * 10000)
                    ])
                }
                return data
            },
            getPieSeries(scatterData, chart) {
                return scatterData.map(function (item, index) {
                    let center = chart.convertToPixel({seriesId: 'label'}, item);
                    return {
                        id: index + 'pie',
                        type: 'pie',
                        center: center,
                        label: {
                            normal: {
                                formatter: '{c}',
                                position: 'inside'
                            }
                        },
                        radius: 30,
                        data: [
                            {name: '工作', value: Math.round(Math.random() * 24)},
                            {name: '娱乐', value: Math.round(Math.random() * 24)},
                            {name: '睡觉', value: Math.round(Math.random() * 24)}
                        ]
                    };
                })
            },
            chartsInit() {
                let calendar_pie = this.$refs.calendar_pie;
                let scatterData = this.getVirtulData();
                calendar_pie.mergeOptions(
                    {
                        series: [{data : scatterData}]
                    }
                );
                calendar_pie.mergeOptions(
                    {
                        series: this.getPieSeries(scatterData,calendar_pie)
                    }
                )
            }
        }`

**Comment by Anluis** [comment]
你好，这边是在Vue中还原官网的案例，根据文档 convertToPixel({seriesId: 'label'}, item)
第一个参数可以直接指定坐标系，比如 calender 也可以指定 seriesId，我这边都尝试了

**Comment by Anluis** [comment]
已经解决，vue-echarts引入的问题，更新依赖包到最新版，按照文档走就可用。之前是版本有问题。
