### ISSUE TITLE
删除其中series中的数据后用setOption重新渲染 为什么图没有变化

### ISSUE THREAD

**Issue by huainanhai** [ecomfe/echarts#5730]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
setOption 第二个参数传 true
