### ISSUE TITLE
钓鱼岛不是中国固有领土?为什么在echarts上面没有显示？？

### ISSUE THREAD

**Issue by wjtGitHub** [ecomfe/echarts#5734]
# ***钓鱼岛不是中国固有领土?为什么在echarts上面没有显示？？？***

**Comment by troy351** [comment]
当你把中国地图足够放大后，你会在台湾的东北部找到钓鱼岛的。
地图数据里钓鱼钓写成了台湾的一部分，只是它真的 太小了。如果你一个屏幕显示下中国地图的话，你是看不到钓鱼岛的。那么有必要为了特意突显钓鱼岛而改变它的实际大小吗？

**Comment by wjtGitHub** [comment]
不好意思，把地图放到足够大，也没有

**Comment by hanasakari** [comment]
这个问题毫无意义，在echart的地图里面这些小的地方会影响计算大小，头疼的不行

**Comment by troy351** [comment]
下方为地图，上方阴影遮罩为刚下载的台湾数据解析后的结果。尽管有点小偏移，你要强行说没有也是。。
![diaoyu1](https://github.com/troy351/troy351.github.io/raw/master/images/diaoyu1.png)
![diaoyu2](https://github.com/troy351/troy351.github.io/raw/master/images/diaoyu2.png)
![diaoyu3](https://github.com/troy351/troy351.github.io/raw/master/images/diaoyu3.png)

**Comment by wjtGitHub** [comment]
真的服你了@troy351 
https://github.com/ecomfe/echarts/issues/5638 自己去看看我提的问题。官方人员明确说了，没有

**Comment by wjtGitHub** [comment]
@hanasakari 有需求，就有必要3，不过我已经自己加进去了。

**Comment by troy351** [comment]
@wjtGitHub 数据是不会说谎的，有就是有，没有就是没有。
echarts的官方人员不会去关心我国的领土怎么怎么样，他们只是做好画图表的功能。
如果你觉得官方对于地图数据的回答靠谱的话，那么请看我的另外一个issue [#5573](https://github.com/ecomfe/echarts/issues/5573)，问题直到现在都没有解决而且被关闭了。那么问题来了，连那么多市级地区的地图缺失都不解决，他们会了解钓鱼岛吗？只不过当做一串数据来看待而已，并不会关心数据代表的意义。

**Comment by wjtGitHub** [comment]
[被关闭了又肿么样，钓鱼岛只是一个比较敏感的地方。所以，有的项目需要用到。至于你说的其他地区市县已经包含在省的区域内了。他们并不是不解决，而是一种扩展。钓鱼岛也可以扩展在上面。地区市县也能扩展。但是，中国地图上面没有钓鱼岛这个数据@troy351

**Comment by troy351** [comment]
"至于你说的其他地区市县已经包含在省的区域内了"，我是不是可以理解为“钓鱼岛已经包含在台湾省的区域内了”？而且我需要的不仅仅是省的数据，也需要下钻的市级数据。数据都是数据，不要双标。
说句题外话，你知道我为什么知道台湾数据里包含钓鱼岛这种一般人不会注意到的事情吗？因为我也加过钓鱼岛，而且为了能在正常缩放下看到，放大了好多倍。 echarts地图数据取的高德地图数据，他们也无能为力，纯当发牢骚了。@wjtGitHub

**Comment by pissang** [comment]
钓鱼岛，或者很多其它岛屿没有只是因为岛屿的大小小于轮廓数据的精度，你要想使用详细完整的地图建议使用[百度地图扩展](https://github.com/ecomfe/echarts/tree/master/extension/bmap)

**Comment by 799535610** [comment]
@printjs 你咋加上去的

**Comment by jinzhuming** [comment]
求求你别杠了，现在多少地图数据都被开发者下架了，就是因为你这样的太多了，你觉得有问题你自己加上不就行了么？实在不行你去插个旗子表表忠心，不要把技术牵扯到政治好么？

**Comment by ParryQiu** [comment]
实名反对 @printjs 臭傻逼，是不是太容易高潮了？哈哈哈
