### ISSUE TITLE
echart2下，使用的是grunt，引入echarts-liquidfill插件，报错n.extendSeriesModel is not a function

### ISSUE THREAD

**Issue by fantaishao** [ecomfe/echarts#5735]
echart版本是 2.2.7
使用的事grunt包管理器，没有用webpack

引入echarts-liquidfill.js,控制台报错

**Uncaught TypeError: n.extendSeriesModel is not a function**

是不是一定要在webpack环境下引入echarts-liquidfill.js？
如果实在grunt构建工具下怎么正确引入echarts-liquidfill.js

**Comment by Sioxas** [comment]
在webpack中使用echarts 3.6.1也报错。。。
Cannot read property 'extendSeriesModel' of undefined
![image](https://cloud.githubusercontent.com/assets/9740581/26727154/38ccab0a-47d8-11e7-95bb-ee290a989e53.png)
```js
import echarts from 'echarts'
import '@/utils/echarts-liquidfill.js'
let option={
series: [{
            type: 'liquidFill',
            data: [0.20, 0.30, 0.15, 0.10],
            radius: '19%'
        }]
}
```
