### ISSUE TITLE
可以可以让Y轴显示的时候换一个单位，比如万

### ISSUE THREAD

**Issue by benweizhu** [ecomfe/echarts#5740]
### One-line summary [问题简述]

![image](https://cloud.githubusercontent.com/assets/5471228/26021840/8df00b06-37c8-11e7-9c46-f5857567622b.png)

右边的单位为“个”，希望换成“万”，这样至少不会那么长，请问有什么办法没有呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
用 `yAxis.axisLabel.formatter`
