### ISSUE TITLE
'legend' 'textStyle' 'fontSize'属性在Chrome下不能小于12px.否则无效

### ISSUE THREAD

**Issue by HaiThomson** [ecomfe/echarts#5741]
### One-line summary [问题简述]

'legend' 'textStyle' 'fontSize'属性在Chrome下不能小于12px.否则无效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3
+ Browser version [浏览器类型和版本]:Chrome 58.0.3029.110 (64-bit)（51-58都有这个问题）
+ OS Version [操作系统类型和版本]:Windows 7

### Expected behaviour [期望结果]
可随配置参数调整字体大小

### ECharts option [ECharts配置项]

```javascript
option = {
legend: {
                                        icon: 'rect',
                                        itemWidth: 12,
                                        itemHeight: 5,
                                        itemGap: 4,
                                        /*数据项*/
                                        data: [],
                                        top: '85%',
                                        /*bottom: '5%',*/
                                        left: '2%',
                                        right: '1%',
                                        textStyle: {
                                            fontSize: 9,
                                            color: '#C6C6C6',
                                        }
                                    },
}

```

### Other comments [其他信息]

Chrome：设置值9号字体不生效.
![image](https://cloud.githubusercontent.com/assets/13185510/26023135/2dc7ccd0-37e8-11e7-91de-39eae137c76e.png)
IE11/Firefox： 正常显示9号字体
![image](https://cloud.githubusercontent.com/assets/13185510/26023158/9be20208-37e8-11e7-8800-6d643b2d0088.png)

**Comment by pissang** [comment]
这是 chrome 浏览器的限制

**Comment by gitXiaoQing** [comment]
谷歌浏览器，设置>高级设置>网络内容>自定义字体>最小字号（移动到最左边即可）
