### ISSUE TITLE
地图中配置,航线图散点图只能显示series中的后一项

### ISSUE THREAD

**Issue by HeavenZhangHr** [ecomfe/echarts#5752]
### One-line summary [问题简述]
省份地图中,配置了航线图跟散点图,只能显示series中配置后面的那一项

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
散点图跟航线路能一起显示
![image](https://cloud.githubusercontent.com/assets/19979240/26092538/09192f42-3a44-11e7-95cd-8b0d0134fa8b.png)

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
      trigger: 'item' //触发类型。
    },
    grid: {
      top: 0,
      bottom: 0
    },
    geo: {
      map: '山西',
      roam: false,
      itemStyle: {
        normal: {
          areaColor: '#010D3F',
          // areaColor: '#767B8F',
          borderColor: '#124C8F'
        },
        emphasis: {
          areaColor: '#354EC5'
        }
      }
    },
series: ({
      name: `太原市`, //这里配置的都是起始点
      type: 'effectScatter', //涟漪散点图
      coordinateSystem: 'geo', //使用地理坐标系
      zlevel: 2,
      /*涟漪特效*/
      rippleEffect: {
        brushType: 'stroke' //绘制方式
      },
      label: {
        normal: {
          show: true,
          position: 'right',
          formatter: '{b}'
        }
      },
      itemStyle: {
        normal: {
          color: '#92AEE8',
        }
      },
      //TODO:点击触发散点图更新时,初始化散点图样式
      data: scatter_init().map(function (item) {
        return {
          name: item.name,
          value: item.value
        }
      }),

    }, {
      name: `太原市`, //这里配置的都是起始点
      //配置航线图配置
      type: 'lines',
      // coordinateSystem: 'geo', //使用地理坐标系
      zlevel: 0,
      // symbol: ['none', 'arrow'], //线两端的标记
      symbolSize: 10, //线两端的标记大小
      //线特效的配置
      effect: {
        show: true,
        period: periodTime, //特效动画的时间
        trailLength: 0, //特效尾迹的长度,数字越大轨迹越长
        // symbol: planePath,
        // symbol: 'arrow', //特效路径图形的标记
        // symbolSize: 12   //特效图像的大小
      },
      lineStyle: {
        normal: {
          color: '#F67D7D',
          width: 2,
          opacity: 0.6, //图形的透明度
          curveness: 0.2 //边的曲度
        }
      },
      data: convertData(
        function () {
          for (var i = 0; i < dispose_data_click.length; i++) {
            if (dispose_data_click[i][0] == '太原市') {
              return dispose_data_click[i][1];
            }
          }
        }()
      )
    })
}



/**
 * 初始化散点图
 * 
 */
function scatter_init() {
  let result = [];
  for (var p in geoCoordMap_value_click) {
    result.push({
      name: p,
      value: geoCoordMap_click[p].concat(geoCoordMap_value_click[p])
    })
  }
  // result.map(function (item) {
  //   console.log({
  //     name: item.name,
  //     value: item.value
  //   });
  // })
  return result;
}


//山西省城市坐标组
const geoCoordMap_click = {
  '太原市': [112.549248, 37.857014],
  '大同市': [113.295259, 40.09031],
  '阳泉市': [113.583285, 37.861188],
  '长治市': [113.113556, 36.191112],
  '晋城市': [112.851274, 35.497553],
  '朔州市': [112.433387, 39.331261],
  '晋中市': [112.736465, 37.696495],
  '运城市': [111.003957, 35.022778],
  '忻州市': [112.733538, 38.41769],
  '临汾市': [111.517973, 36.08415],
  '吕梁市': [111.134335, 37.524366]
}

const geoCoordMap_value_click = {
  '太原市': 95,
  '大同市': 95,
  '阳泉市': 95,
  '长治市': 95,
  '晋城市': 95,
  '朔州市': 95,
  '晋中市': 95,
  '运城市': 95,
  '忻州市': 95,
  '临汾市': 95,
  '吕梁市': 95
}

```

**Comment by HeavenZhangHr** [comment]
//测试单机事件数组
var dispose_data_click = [
  ['太原市', DataTest.太原],
  ["晋中市", DataTest.晋中],
  ['大同市', DataTest.大同],
  ["朔州市", DataTest.朔州],
  ['忻州市', DataTest.忻州],
  ["阳泉市", DataTest.阳泉],
  ['吕梁市', DataTest.吕梁],
  ["临汾市", DataTest.临汾],
  ['长治市', DataTest.长治],
  ["晋城市", DataTest.晋城],
  ['运城市', DataTest.运城]
];

**Comment by HeavenZhangHr** [comment]
//测试对象
//声明一个对象，其中每个属性对应一个起点数组
//此对象中的value属性代表每个地区的散点大小
var DataTest = {
  "太原": [
    [{
      name: "太原",
    }, {
      name: "大同",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "晋城",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "朔州",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "吕梁",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "运城",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "晋中",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "临汾",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "忻州",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "长治",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "阳泉",
      value: 95
    }],
    [{
      name: "太原"
    }, {
      name: "运城",
      value: 95
    }],
  ],
  "晋中": [
    [{
      name: "晋中"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "晋中"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "大同": [
    [{
      name: "大同"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "大同"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "朔州": [
    [{
      name: "朔州"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "朔州"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "忻州": [
    [{
      name: "忻州"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "忻州"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "吕梁": [
    [{
      name: "吕梁"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "吕梁"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "阳泉": [
    [{
      name: "阳泉"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "阳泉"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "临汾": [
    [{
      name: "临汾"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "临汾"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "长治": [
    [{
      name: "长治"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "长治"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "运城": [
    [{
      name: "运城"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "晋中",
      value: 80
    }],
    [{
      name: "运城"
    }, {
      name: "晋城",
      value: 80
    }],
  ],
  "晋城": [
    [{
      name: "晋城"
    }, {
      name: "太原",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "大同",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "朔州",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "忻州",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "吕梁",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "阳泉",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "临汾",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "长治",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "运城",
      value: 80
    }],
    [{
      name: "晋城"
    }, {
      name: "晋中",
      value: 80
    }],
  ],
};

**Comment by HeavenZhangHr** [comment]
不好意思,是真的找不到办法了.希望能获得帮助..我的单机事件里面去重置series也是这样的情况,, 总是只触发后面的配置项,比如航线图在前,散点在后就只触发散点.
反之散点配置在前航线图在后就只触发航线图

**Comment by pissang** [comment]
没理解你的问题 http://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all 发个例子？
