### ISSUE TITLE
移动端touch事件

### ISSUE THREAD

**Issue by jingxiawl** [ecomfe/echarts#5755]
我在移动端使用了echarts柱状图，但是为图表绑定点击事件的时候，只能绑定click，在手机上明显感觉又点反应慢
```javascript
myChart.on('click', function (params) {
    console.log(params);
})
```
能不能支持touch事件呢？

**Comment by 100pah** [comment]
目前移动端的 'click' 就是 'touch' 事件（如果设备支持的话）。
反应慢是否可能是其他原因？

**Comment by AlwaysMing** [comment]
> 目前移动端的 'click' 就是 'touch' 事件（如果设备支持的话）。 反应慢是否可能是其他原因？

移动端click事件不响应

**Comment by AlwaysMing** [comment]
> 我在移动端使用了echarts柱状图，但是为图表绑定点击事件的时候，只能绑定click，在手机上明显感觉又点反应慢
> 
> ```js
> myChart.on('click', function (params) {
>     console.log(params);
> })
> ```
> 
> 能不能支持touch事件呢？

兄弟你这个on click事件在移动端能相应？
