### ISSUE TITLE
echarts-gl 的geo3D  无法获取click事件

### ISSUE THREAD

**Issue by xiaomijiayou** [ecomfe/echarts#5758]
### One-line summary [问题简述]
echarts-gl 的geo3D  无法获取click事件

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts-gl
+ Browser version [浏览器类型和版本]:chrome 56.0.2924.87
+ OS Version [操作系统类型和版本]:ubuntu1404

### Expected behaviour [期望结果]

- 点击地图， console打印出地区信息

#

### ECharts option [ECharts配置项]

```javascript
option = {
backgroundColor: '#cdcfd5',
                    geo3D: {
                        map: 'china',
                        shading: 'lambert',
         
                    },
                    series: []
}；

 chart.on('click', function (params) {
                // 控制台打印数据的名称
                console.log("params.name",params.name);
            });
```

### Other comments [其他信息]
地图

**Comment by pissang** [comment]
什么版本？

**Comment by xiaomijiayou** [comment]
"echarts-gl": "^1.0.0-alpha.3",

**Comment by pissang** [comment]
最新版本 1.0.0-alpha.5 支持事件

**Comment by xiaomijiayou** [comment]
换了版本还是没有click 事件， 代码如下        

<script src="../dist/echarts.min.js"></script>
        <script src="../node_modules/echarts/map/js/china.js"></script>
        <script src="../dist/echarts-gl.js"></script>
        <script src="lib/jquery.min.js"></script>
        <script>
            $.get('../node_modules/echarts/map/json/china.json', function (chinaJson) {
            echarts.registerMap('china', chinaJson);
                var chart = echarts.init(document.getElementById('main'));
                chart.setOption({
                    backgroundColor: '#cdcfd5',
                    geo3D: {
                        map: 'china',
                        shading: 'lambert',
                    },
                    series: []
                });

                 chart.on('click', function (params) {
                    // 控制台打印数据的名称
                    console.log("params.name",params.name);
                });


            });

        </script>

**Comment by pissang** [comment]
我试了下有事件的呀

**Comment by pissang** [comment]
我挪到这个 topic 下了 https://github.com/ecomfe/echarts-gl/issues/58

**Comment by xiaomijiayou** [comment]
能把代码给我看吗， 我的代码没有什么问题吧， 就是获取不到事件
