### ISSUE TITLE
boundaryGap 为  false 时，柱状图两侧分别超出X轴

### ISSUE THREAD

**Issue by joy-yi0905** [ecomfe/echarts#5760]
### One-line summary [问题简述]

我希望图形中第一项和最后一项，分别向左和向右顶头对齐。于是我使用 `boundaryGap: false`，结果发现当图形为柱状图时，第一个柱子和最后一个柱子分别超出了X轴。如图：

![样图](https://thumbnail0.baidupcs.com/thumbnail/3ef63a8e2f2a3d9c0c1f6a741865f38b?fid=3098163580-250528-16156804859688&time=1494954000&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-eEghNSFZfnfyeINtkBxzb1cIIhc%3d&expires=8h&chkbd=0&chkv=0&dp-logid=3156004651497014825&dp-callid=0&size=c1920_u1080&quality=90)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: **2.2.7**
+ Browser version [浏览器类型和版本]: **chrome57**
+ OS Version [操作系统类型和版本]: **win7**

### Expected behaviour [期望结果]

希望第一个柱子不要超出X轴的最左侧，最后一个柱子不要超出X轴的最右侧。请问下，有什么好方法吗？

### ECharts option [ECharts配置项]

```javascript
option = {
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['蒸发量','降水量']
    },
    
    xAxis : [
        {
            type : 'category',
          boundaryGap : false,
            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'蒸发量',
            type:'bar',
            data:[88.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 50],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            }
        }
    ]
};
                    

```

**Comment by pissang** [comment]
boundaryGap: true 就是为了防止这种情况的

**Comment by joy-yi0905** [comment]
嗯，感谢！目前设置 `boundaryGap: true` 时，两边的柱状图离两端空间有点大，怎么样将这个空间尽可能的缩小，让最左和最右的柱尽可能的靠近两端呢？

**Comment by mqliutie** [comment]
为什么类目的时候不能自定义 boundaryGap 呢

**Comment by Marylely** [comment]
请问最后是怎么实现的靠y轴显示呢？
