### ISSUE TITLE
ECharts放大缩小位置偏移无法校正

### ISSUE THREAD

**Issue by 1304800050** [ecomfe/echarts#5761]
### One-line summary [问题简述]
ECharts放大缩小位置偏移无法校正
我通过动态控制 zoom 放大浏览器后、ECharts图表 图例和工具区的位置发生偏移 无法矫正，请问如何解决。。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

测试用的例子：

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="echarts.js"></script>
	<script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
    
    <div id="main" style="width:600px;height:400px;"></div>
	<input id="11" onclick="zoomout()">
	<input id="22" onclick="zoomin()">
	<script type="text/JavaScript">

		var size = 1.0;  
		function zoomout() {  
			size = size + 0.1;  
			set(); 
		}  

		function zoomin() {  
			size = size - 0.1;  
			set();  
		}  

		function set() {
			var width = $("#main").css("width").replace("px","");
			var height = $("#main").css("height").replace("px","");
			width=width*size;
			height=height*size;
			
			$("#main").css("width",width+"px");
			$("#main").css("height",height+"px");
			
			var canvas = $('canvas:first');
			canvas[0].style.width = width;
            canvas[0].style.height = height;
			canvas[0].width=width;
			canvas[0].height=height;
			
			
			document.body.style.zoom = size;
			cart();
		} 
    </script>
	
	
    <script type="text/javascript">
		$(document).ready(function(){
			cart();
		});
		
		$(window).resize(function () {          //当浏览器大小变化时
			cart();
		});
	
		function cart(){
			// 基于准备好的dom，初始化echarts实例
			var myChart = echarts.init(document.getElementById('main'));

			// 指定图表的配置项和数据
			var option = {
				title: {
					text: 'ECharts 入门示例'
				},
				toolbox: {
					show : true,
					feature : {
						dataView : {show: true, readOnly: false},
						magicType : {show: true, type: ['line', 'bar']},
						restore : {show: true},
						saveAsImage : {show: true}
					}
				},
				tooltip: {},
				legend: {
					data:['销量']
				},
				xAxis: {
					data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
				},
				yAxis: {},
				series: [{
					name: '销量',
					type: 'bar',
					data: [5, 20, 36, 10, 10, 20]
				}]
			};

			// 使用刚指定的配置项和数据显示图表。
			myChart.setOption(option);
		}
        
    </script>
</body>
</html>

**Comment by WwupengP** [comment]
同问

**Comment by kennez03** [comment]
有解决办法吗？
