### ISSUE TITLE
没有辽宁省沈阳市辽中县数据？

### ISSUE THREAD

**Issue by gjun-neusoft** [ecomfe/echarts#5762]
没有辽宁省沈阳市辽中县数据，为什么生成县级数据不允许选择“包含子区域 subregion”？如何获取县级子区域数据

+ ECharts 3.5.4
+ chrome浏览器
+ win7

**Comment by pissang** [comment]
因为这是我们能获取到的最细的数据了

**Comment by gjun-neusoft** [comment]
地图生成工具“echarts-map-tool”，选择“辽宁省，沈阳市，辽中县”没有生成辽中县边界数据。其他县都有。麻烦确认一下。
