### ISSUE TITLE
K线图开盘值和收盘值相等时自定义颜色

### ISSUE THREAD

**Issue by siminx** [ecomfe/echarts#5767]
### One-line summary [问题简述]
K线图现在只能设置涨和跌的颜色，开盘值和收盘值相等时显示的是跌的颜色，怎么自定义持平时的颜色呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 3.5.4]:
+ Browser version [chrome58]:
+ OS Version [windows10]:

### Expected behaviour [期望结果]
能够设置开盘值和收盘值相等时的颜色。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by yoky** [comment]
candlestick的series设置dimensions:['open','close','low','high','netChange', 'netChangeRatio','volume'],
在echarts.js里修改：
ecModel.eachSeriesByType('candlestick', function (seriesModel) {//源码此model里修改
                        var openVal = args[1];
	                var closeVal = args[2];
	                var lowestVal = args[3];
	                var highestVal = args[4];
	                var netChangeVal=args[5];//新增
                        ..........

                        var bodyEnds = [];
	                addBodyEnd(ocHighPoint, 0);
	                addBodyEnd(ocLowPoint, 1);

	                //以下为新增 start
	                var signVal=0;
	                if(openVal>closeVal){
						signVal=-1;
	                }
	                if(openVal==closeVal&&netChangeVal>0){
	                	signVal=1
	                }
	                if(openVal==closeVal&&netChangeVal<0){
	                	signVal=-1
	                }if(openVal<closeVal){
	                	signVal=1
	                }
                        //以下为新增 end
	                data.setItemLayout(idx, {
	                    chartLayout: chartLayout,
	                    // sign: openVal > closeVal ? -1 : openVal < closeVal ? 1 : 0,//注释此源码
	                    sign:signVal,//新增
	                    initBaseline: openVal > closeVal
	                        ? ocHighPoint[constDim] : ocLowPoint[constDim], // open point.
	                    bodyEnds: bodyEnds,
	                    whiskerEnds: whiskerEnds,
	                    brushRect: makeBrushRect()
	                });
结束。
修改的目的是依据：涨停（开盘价=收盘价，涨跌额为正）还是按阳线颜色，跌停（开盘价=收盘价，涨跌额为负）按阴线颜色。

希望可以帮到你。
