### ISSUE TITLE
dataZoom设置为inside导致页面无法上下滑动

### ISSUE THREAD

**Issue by jingxiawl** [ecomfe/echarts#5769]
看了很多人都在问这个问题、现在也遇到这个问题了，求个解决方案啊。我这边很难做处理了。现在在图表上完全无法滑动页面，问题是图表占得位置还很大，根本无法滚动页面了

**Comment by pissang** [comment]
新版本会加入 shift + 滚轮缩放的功能，应该能解决你的问题

**Comment by jingxiawl** [comment]
@pissang 手机端这个也没法用吧，现在主要是手机端无法滑动的问题。pc端还可以通过滚轮来滑动页面。影响不是很大。主要是手机端。屏幕又小，图表占据又大，直接整个页面都废掉了无法滑动

**Comment by jingxiawl** [comment]
@100pah  新提交这个代码可以下载压缩文件了么？解决了滚动问题了么？

**Comment by Ovilia** [comment]
@jingxiawl 滚动问题解决了，具体参见这几个配置项：
http://echarts.baidu.com/option.html#dataZoom-inside.moveOnMouseMove
http://echarts.baidu.com/option.html#dataZoom-inside.zoomOnMouseWheel
http://echarts.baidu.com/option.html#dataZoom-inside.preventDefaultMouseMove

3.6.0 版本开始支持

**Comment by webCoderJ** [comment]
> @jingxiawl 滚动问题解决了，具体参见这几个配置项：
> http://echarts.baidu.com/option.html#dataZoom-inside.moveOnMouseMove
> http://echarts.baidu.com/option.html#dataZoom-inside.zoomOnMouseWheel
> http://echarts.baidu.com/option.html#dataZoom-inside.preventDefaultMouseMove
> 
> 3.6.0 版本开始支持

不起作用啊  4.x版本

**Comment by Ovilia** [comment]
@webCoderJ 如果有 bug，请开一个新的 issue 并且引用这个已经关闭的 issue。

**Comment by XUKEZXZ** [comment]
你好，这个问题后来解决了吗，我发现还是有这个问题

**Comment by MangoTi** [comment]
必须同时设置zoomLock: true;preventDefaultMouseMove: false;在canvas区域滑动时页面才可以滚动

**Comment by lisonge** [comment]
请问如何设置屏蔽垂直滚动，但是接收横向滚动呢，因为横向滚动不会干扰页面

**Comment by ghostcode** [comment]
> 必须同时设置zoomLock: true;preventDefaultMouseMove: false;在canvas区域滑动时页面才可以滚动

我用的 V5.4.0 版本，设置 zoomLock: true 就行。
