### ISSUE TITLE
响应式布局，缩小屏幕后，柱状图x轴的类目会部分消失

### ISSUE THREAD

**Issue by zhangya5847** [ecomfe/echarts#5772]
### One-line summary [问题简述]

大屏时，柱状图的x轴显示完整，缩小屏幕后只显示第一个，且显示不完整。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新
+ Browser version [浏览器类型和版本]: chrome 最新
+ OS Version [操作系统类型和版本]:
Mac

### Expected behaviour [期望结果]

期望缩小屏幕之后还能完整显示

### ECharts option [ECharts配置项]

```javascript
option = {
  
}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/15855773/26190116/5f6b8970-3bda-11e7-9692-52bdba026517.png)
![image](https://cloud.githubusercontent.com/assets/15855773/26190130/6e77cab4-3bda-11e7-92e9-9e02a74c89c6.png)

http://gallery.echartsjs.com/editor.html?c=xHkX9F9pJW

**Comment by pissang** [comment]
axisLabel.interval 设成 0
