### ISSUE TITLE
geo数据节点过多时， brush选框拖动卡顿

### ISSUE THREAD

**Issue by lzhjie** [ecomfe/echarts#5774]
能否添加支持：将拖动过程中触发Action改为拖动结束后触发Action
60395   (!opt.isEnd || opt.removeOnClick) && this.api.dispatchAction({
             (opt.isEnd || opt.removeOnClick) && this.api.dispatchAction({

GEO节点数为2000
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.4
+ Browser version [浏览器类型和版本]:QQ
+ OS Version [操作系统类型和版本]:WIN7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by MansteinLiliang** [comment]
为什么关了？如何解决的？
