### ISSUE TITLE
ECharts 地图数据在线生成工具 无法生成JSON

### ISSUE THREAD

**Issue by jzz4012650** [ecomfe/echarts#5780]
### One-line summary [问题简述]
打开http://ecomfe.github.io/echarts-map-tool/，
使用下述选项：
- 范围选择：所有省
- 包含子区域 subregion
- 压缩版本
- 名称：test

可以看到预览地图，但是点击“生成JSON”与“生成JS按钮”都没有反应。console中也没有看到发起任何网络请求。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 无
+ Browser version [浏览器类型和版本]: chrome 58.0.3029.110
+ OS Version [操作系统类型和版本]: OSX 10.12.4

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
什么版本的浏览器？

**Comment by jzz4012650** [comment]
尝试了最新safari，chrome，以及FF19都无果

**Comment by jzz4012650** [comment]
chrome 58.0.3029.110 （Mac）可以生成省市区县的JSON，全国范围的不能生成。

另：有没有geoJSON的解压缩工具能够还原下载下来的JSON，想用D3自己渲染。

**Comment by pissang** [comment]
下载不要选择压缩就行

**Comment by dogsmall** [comment]
我也遇到了相同的问题,不选压缩也无法下载json
