### ISSUE TITLE
echarts3.54版本

### ISSUE THREAD

**Issue by huoyuanyuanweb** [ecomfe/echarts#5781]
使用地图

### One-line summary [问题简述]

想修改地图默认的灰色背景色，使用areaStyle:{color:'green'}不生效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.54
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:window7,8

### Expected behaviour [期望结果]
希望尽快给答复，谢谢

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by huoyuanyuanweb** [comment]
@leeight @cnberg

**Comment by pissang** [comment]
itemStyle: { normal: { areaColor: 'gree' } } }
