### ISSUE TITLE
请问echarts2中的tree图中为什么无法添加markPoint

### ISSUE THREAD

**Issue by MarriotLenard** [ecomfe/echarts#5784]
### One-line summary [问题简述]
无论在本地还是在官网的编辑器中添加markPoint都无法让markPoint标记的点显示出来。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 2]:
+ Browser version [chrome56和360]:
+ OS Version [windows10]:

### Expected behaviour [期望结果]
markPoint成功标记出一个点。
想要实现echarts2中特效标记点，在模拟迁徙地图中有很多样例。
下方图中根据option，其中想要标记的点没有任何反应，改成坐标，也没有在相应坐标中出现标记点。

### ECharts option [ECharts配置项]

option = {
    title : {
        text: '树图',
        subtext: '虚构数据'
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : false,

    series : [
        {
            name:'树图',
            type:'tree',
            orient: 'radial',  // vertical horizontal
            rootLocation: {x: 'center',y: 50}, // 根节点位置  {x: 100, y: 'center'}
            nodePadding: 1,
          	roam : true,
            itemStyle: {
                normal: {
                    label: {
                        show: true,
                        formatter: "{b}"
                    },
                    lineStyle: {
                        color: '#48b',
                        shadowColor: '#000',
                        //shadowBlur: 3,
                        //shadowOffsetX: 3,
                        //shadowOffsetY: 5,
                        type: 'curve' // 'curve'|'broken'|'solid'|'dotted'|'dashed'

                    }
                },
                emphasis: {
                    label: {
                        show: true
                    }
                }
            },
            
            data: [
                {
                    name: '根节点',
                    value: 6,
                    children: [
                        {
                            name: '节点1',
                            value: 4,
                            children: [
                                {
                                    name: '叶子节点1',
                                    value: 4
                                },
                                {
                                    name: '叶子节点2',
                                    value: 4
                                },
                                {
                                    name: '叶子节点3',
                                    value: 2
                                },
                                 {
                                    name: '叶子节点4',
                                    value: 2
                                },
                                {
                                    name: '叶子节点5',
                                    value: 2
                                },
                                {
                                    name: '叶子节点6',
                                    value: 4
                                }
                            ]
                        },
                        {
                            name: '节点2',
                            value: 4,
                            children: [{
                                name: '叶子节点7',
                                value: 4
                            },
                            {
                                name: '叶子节点8',
                                value: 4
                            }]
                        },
                        {
                            name: '节点3',
                            value: 1,
                            children: [
                                {
                                    name: '叶子节点9',
                                    value: 4
                                },
                                {
                                    name: '叶子节点10',
                                    value: 4
                                },
                                {
                                    name: '叶子节点11',
                                    value: 2
                                },
                                 {
                                    name: '叶子节点12',
                                    value: 2
                                }
                            ]
                        }
                    ]
                }
            ],
   			markPoint:{
            	symbol:"circle",
              	symbolSize:80,
              	data:[{name:'叶子节点12',value:2}]
            }
        }
    ]
};
                    

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/22310095/26241226/8701ac94-3cb6-11e7-8c9e-c41538a40546.png)

**Comment by pissang** [comment]
新版本的 tree 正在开发中
