### ISSUE TITLE
echarts折线图如何添加几条平行于Y轴的直线

### ISSUE THREAD

**Issue by sxs89** [ecomfe/echarts#5785]
拖拉折线图根据需求如何实现平行于Y轴的直线，（最好每条直线的颜色不通）？

**Comment by pissang** [comment]
markLine

**Comment by mytharcher** [comment]
遇到同样的问题，我看文档上的描述并没有针对平行于 Y 轴的，试了下两个坐标连线，但画出来的是线段，而做不到不设置 Y 值直接画一条直线。最后参照文档中有`{yAxis: value}`的写法推想出来应该有`{xAxis: value}`的写法实现了。

建议文档中能有更好的说明。
