### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by wm370857724** [ecomfe/echarts#5786]
### One-line summary [问题简述]
Angular4 报
```
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
```

### Version & Environment [版本及环境]
+ ECharts version [3.5.4]:
+ Browser version [Chrome 58.0.3029.110]:
+ OS Version [macOS 10.12.4]:

### Expected behaviour [期望结果]

不提示警告信息

### ECharts option [ECharts配置项]
```javascript
option = {
    任何值
}

```

**Comment by pissang** [comment]
跟 echarts 无关

**Comment by realeve** [comment]
![image](https://user-images.githubusercontent.com/448208/28861350-14d5a478-7793-11e7-9080-6cdd547d44ff.png)   @pissang  Zrender引起的，希望能够增强一下

**Comment by candy4290** [comment]
echarts图出现一个就会报一个这样的警告，不使用echarts,就没有这样的警告

**Comment by h136799711** [comment]
至今没解决echarts 5.1.2 ？还是会警告

**Comment by PowerSheetAI** [comment]
I proposed a [fix for this here](https://github.com/ecomfe/zrender/pull/322#issuecomment-1024997989) in the appropriate library (zrenderer which was built for ECharts specifically). 

If you can **upvote** [my comment with fix](https://github.com/ecomfe/zrender/pull/322#issuecomment-1024997989), upvote that issue on ZRenderer, and possibly add a comment in support of it, maybe this can get fixed.

**Comment by sir-ran** [comment]
现在还是有这个问题，，，每个图表都会报一个警告

**Comment by AscendingEagle** [comment]
Very annoying bug. It seems to have gotten worse with even more errors.
![image](https://user-images.githubusercontent.com/41471114/180445410-422b1c5a-788a-4302-92e3-f1d4f642a534.png)

**Comment by mchao123** [comment]
I've noticed this too, the latest chrome based browsers seem to show this warning
