### ISSUE TITLE
Echarts在线编辑器中的自定义Geojson文件如何引入HTML

### ISSUE THREAD

**Issue by lidatou1991** [ecomfe/echarts#5788]
### One-line summary [问题简述]
地图下载器中下载了成都市的Geojson，由于最近简阳市划归成都，重新把简阳市的geojson加入到了下载的文件中。现在在线编辑器中能够正常显示地图。但是希望制作完整的HTML文件，托管到自己的网站上。现在的问题是在线编辑器中引入的geojson文件位置是：http://gallery.echartsjs.com/asset/get/s/data-1493307661784-BJIGZ5y1b.json

如何引入到自己的HTML文件中。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
Ecahrts 3.5
+ Browser version [浏览器类型和版本]:
Chrome 58
+ OS Version [操作系统类型和版本]:
Win 10

### Expected behaviour [期望结果]
在自己的HTML文件中复现在线编辑器中的结果。最后能够直接导出完整HTML文件

### ECharts option [ECharts配置项]
var uploadedDataURL = "/asset/get/s/data-1493307661784-BJIGZ5y1b.json";

//var uploadedDataURL = "/asset/get/s/data-1493307461647-By0Hx5kkb.json";

//var uploadedDataURL = "/asset/get/s/data-1493307255243-ByktJqkJb.json";

//var uploadedDataURL = "/asset/get/s/data-1493306833817-ry90pKJJZ.json";

//var uploadedDataURL = "/asset/get/s/data-1493303460769-rJ6sltyyZ.json";

//var uploadedDataURL = "/asset/get/s/data-1482818963027-Hko9SKJrg.json";

myChart.showLoading();
$.get(uploadedDataURL, function(geoJson) {

    echarts.registerMap('Chengdu', geoJson);
    myChart.hideLoading();
    myChart.setOption({
        title: {
            text: '成都地区容量图',
            subtext: '非官方数据',
        },
        visualMap: {
            min: 500,
            max: 3500,
            text: ['High', 'Low'],
            realtime: false,
            calculable: true,
            inRange: {
                color: ['lightskyblue', 'yellow', 'orangered']
            }
        },
       
        series: [{
            type: 'map',
            roam:true,
            map: 'Chengdu',
            selectedMode: 'single',
            itemStyle: {
                normal: {
                    label: {
                        show: true
                    }
                },
                emphasis: {
                    label: {
                        show: true
                    }
                }
            },
            data: [{
                    name: '成华区',
                    value: 2344
                }, {
                    name: '武侯区',
                    value: 3360
                }, {
                    name: '青羊区',
                    value: 3524
                },{
                    name: '简阳市',
                    value: 1621
                },
                {
                    name: '金牛区',
                    value: 2245
                },{
                    name: '龙泉驿区',
                    value: 2730
                },{
                    name: '锦江区',
                    value: 2479
                },{
                    name: '双流区',
                    value: 4591
                },{
                    name: '新都区',
                    value: 2780
                },{
                    name: '郫都区',
                    value: 2753
                },{
                    name: '温江区',
                    value: 1666
                },{
                    name: '青白江区',
                    value: 1450
                },{
                    name: '彭州市',
                    value: 1751
                },{
                    name: '金堂县',
                    value: 1566
                },{
                    name: '都江堰市',
                    value: 1537
                },{
                    name: '新津县',
                    value: 1921
                },{
                    name: '崇州市',
                    value: 1845
                },{
                    name: '邛崃市',
                    value: 902
                },{
                    name: '大邑县',
                    value: 945
                },{
                    name: '蒲江县',
                    value: 170
                }

            ]
        }]
    });
});

、、、、、、、自己的HTML文件代码、、、、、、、
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/3.5.4/echarts.js"></script>
</head>
<body>
    
    <div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));
        var uploadedDataURL = "http://gallery.echartsjs.com/asset/get/s/data-1493307661784-BJIGZ5y1b.json";

        $.get(uploadedDataURL, function(geoJson) {

        echarts.registerMap('Chengdu', geoJson);
        myChart.hideLoading();

、、、、、、、、、、、、、、、、、、下面的部分都和在线编辑器一样、、、、、、、、、、

### Other comments [其他信息]

![fireshot capture 36 - echarts gallery - http___gallery echartsjs com_editor html_c xbynlgf1yz v 4](https://cloud.githubusercontent.com/assets/28817862/26271995/9fe5d87c-3d40-11e7-92ae-a01a8da24e4c.png)

**Comment by pissang** [comment]
建议学习了解一下相关的前端只是
