### ISSUE TITLE
使用timeline就控制台报 Series has not been initialized yet 

### ISSUE THREAD

**Issue by zgjlxy** [ecomfe/echarts#5789]
在Chart.setOption设置timeline控制台报错“Series has not been initialized yet ”
请问是什么问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: ECharts 3 
+ Browser version [浏览器类型和版本]: IE11
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
 						timeline :{
							show:true,
							axisType:'time',
							autoPlay:true,
							loop : false,
							playInterval :30000,
							padding :15,
							data:[startTime,endTime]
						}, 
}

```

**Comment by pissang** [comment]
没写 series
