### ISSUE TITLE
symbolboundingdata does not work for negative pictorial graph values

### ISSUE THREAD

**Issue by anoosurf** [ecomfe/echarts#5793]
symbolboundingdata does not work for negative pictorial graph values

### Version & Environment [版本及环境]
+ ECharts version 3.5.4
+ Browser version chrome latest
+ OS Version win10

### ECharts option [ECharts配置项]

```javascript
option = 
 {"animation":true,"backgroundColor":"transparboent","title":{"show":false,"top":0,"padding":0,"bottom":0,"itemGap":0,"text":"watch"},"tooltip":{"show":true,"trigger":"axis","axisPointer":{"type":"shadow"}},"toolbox":{"show":false,"feature":{"magicType":{"type":["line","bar","stack","tiled"]},"dataView":{"show":true},"dataZoom":{},"brush":{"type":["rect","polygon","clear"]}}},"brush":{"brushType":"lineX","brushMode":" single","seriesIndex":"all"},"grid":[{"left":"110px","right":"1%","bottom":"0px","top":"0px"}],"xAxis":[{"gridIndex":0,"type":"value","boundaryGap":false,"show":false,"position":"top","min":null,"max":null,"name":"rating","nameLocation":"middle","nameGap":5,"axisTick":{"show":false},"splitLine":{"show":false,"lineStyle":{"color":"rgba(150,150,150,0.15)"}},"axisLine":{"show":false},"axisLabel":{"show":false}}],"yAxis":[{"gridIndex":0,"type":"category","inverse":true,"interval":1,"name":null,"nameLocation":"middle","triggerEvent":true,"axisLabel":{"show":true,"interval":0,"textStyle":{"fontWeight":400,"fontFamily":"Gotham Rounded SSm A,Gotham Rounded SSm B,Montserrat","fontSize":12,"color":"rgba(0,0,0,0.95)"}},"axisTick":{"show":false},"splitLine":{"show":true,"interval":0,"lineStyle":{"width":1,"color":"rgba(150,150,150,0.15)"}},"axisLine":{"show":false},"data":["BNKCAP","BRAHMINFRA","SVCSUPE","JJEXPO","ADVENT","JYOTI","CHANDRAP","CHANDNI","VISIONCINE","UDAYJEW","SIPL","DYNAMIND","VISUINTL","SKSLOGLTD","ABCBEARS","KELENRG","LIBORDFIN","GOLDCORP","TARINI","BLSINFOTE","SABRIMALA","LNIND","MODAIRY","SURYAVA SPIN","SUNSOUI","STURDY","OJASASSET","JAMSHRI","MODERN","APTUS","UPASAFN","RAVILEELA GR","INDBNK","GEMSI","DWEKAM","HINDHARD","SOLIDSTON","OASIS","ODYSSEY","KAMANWALA","ESSARSEC","KANSHST","BULL","MODINATUR","SHREERAM","FIRSTWIN"]}],"visualMap":[{"type":"piecewise","pieces":[{"gte":0,"lt":1,"color":"rgba(60,220,90,0.3)"},{"gte":1,"lt":2,"color":"rgba(60,220,90,0.5)"},{"gte":2,"lt":4,"color":"rgba(60,220,90,0.7)"},{"gte":4,"color":"rgba(60,220,90,0.85)"},{"gt":-1,"lt":0,"color":"rgba(230,40,30,0.4)"},{"gt":-2,"lte":-1,"color":"rgba(230,40,30,0.5)"},{"gt":-4,"lte":-2,"color":"rgba(230,40,30,0.7)"},{"lte":-4,"color":"rgba(230,40,30,0.8)"}],"seriesIndex":0,"show":false,"orient":"horizontal","left":"66.66666666666667%","calculable":true,"padding":2,"dimension":0}],"animationDurationUpdate":800,"animationDuration":800,"series":[{"name":"rating","type":"pictorialBar","data":[{"value":4,"name":"BNKCAP"},{"value":4,"name":"BRAHMINFRA"},{"value":4,"name":"SVCSUPE"},{"value":4,"name":"JJEXPO"},{"value":4,"name":"ADVENT"},{"value":3,"name":"JYOTI"},{"value":3,"name":"CHANDRAP"},{"value":3,"name":"CHANDNI"},{"value":3,"name":"VISIONCINE"},{"value":3,"name":"UDAYJEW"},{"value":3,"name":"SIPL"},{"value":3,"name":"DYNAMIND"},{"value":3,"name":"VISUINTL"},{"value":3,"name":"SKSLOGLTD"},{"value":3,"name":"ABCBEARS"},{"value":3,"name":"KELENRG"},{"value":3,"name":"LIBORDFIN"},{"value":3,"name":"GOLDCORP"},{"value":3,"name":"TARINI"},{"value":2,"name":"BLSINFOTE"},{"value":2,"name":"SABRIMALA"},{"value":2,"name":"LNIND"},{"value":2,"name":"MODAIRY"},{"value":2,"name":"SURYAVA SPIN"},{"value":2,"name":"SUNSOUI"},{"value":2,"name":"STURDY"},{"value":2,"name":"OJASASSET"},{"value":2,"name":"JAMSHRI"},{"value":1,"name":"MODERN"},{"value":1,"name":"APTUS"},{"value":1,"name":"UPASAFN"},{"value":1,"name":"RAVILEELA GR"},{"value":1,"name":"INDBNK"},{"value":1,"name":"GEMSI"},{"value":-1,"name":"DWEKAM"},{"value":-1,"name":"HINDHARD"},{"value":-2,"name":"SOLIDSTON"},{"value":-2,"name":"OASIS"},{"value":-2,"name":"ODYSSEY"},{"value":-2,"name":"KAMANWALA"},{"value":-3,"name":"ESSARSEC"},{"value":-3,"name":"KANSHST"},{"value":-3,"name":"BULL"},{"value":-3,"name":"MODINATUR"},{"value":-4,"name":"SHREERAM"},{"value":-4,"name":"FIRSTWIN"}],"xAxisIndex":0,"yAxisIndex":0,"width":"100%","height":"100%","symbol":"path://m15.5,19c-0.082,0 -0.164,-0.02 -0.239,-0.061l-5.261,-2.869l-5.261,2.869c-0.168,0.092 -0.373,0.079 -0.529,-0.032s-0.235,-0.301 -0.203,-0.49l0.958,-5.746l-3.818,-3.818c-0.132,-0.132 -0.18,-0.328 -0.123,-0.506s0.209,-0.31 0.394,-0.341l5.749,-0.958l2.386,-4.772c0.085,-0.169 0.258,-0.276 0.447,-0.276s0.363,0.107 0.447,0.276l2.386,4.772l5.749,0.958c0.185,0.031 0.337,0.162 0.394,0.341s0.01,0.374 -0.123,0.506l-3.818,3.818l0.958,5.746c0.031,0.189 -0.048,0.379 -0.203,0.49c-0.086,0.061 -0.188,0.093 -0.29,0.093z","symbolSize":20,"colorMappingBy":"value","squareRatio":1,"symbolRepeat":5,"symbolClip":true,"symbolPosition":"center","breadcrumb":{"show":false},"label":{"normal":{"position":"outside","show":true,"offset":[0,-2],"textStyle":{"fontWeight":400,"fontFamily":"Gotham Rounded SSm A,Gotham Rounded SSm B,Montserrat","fontSize":12,"color":"rgba(0,0,0,0.95)"}}},"itemStyle":{"normal":{"gapWidth":1,"color":"rgba(0,200,90,0.9)","borderColor":"transparent","opacity":1}}}]}
 

the above shows star rating from +5 to - 5 ... ( but even for +4 , it shows 5 stars as max repeat) so if i want to clip to maximum +/-5 i add property --> "symbolBoundingData":5,

then the negative red stars don't show 


```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/4696146/26281144/383f7d46-3e0c-11e7-8278-0fde94f10c8e.png)

**Comment by anoosurf** [comment]
ideally it "symbolBoundingData" could also be set as an optional array such as [-5,5] to accomodate negative ranges

**Comment by helgasoft** [comment]
this bug still exists in 5.5.1 - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PQKgUAxArA7AnAZgAQC4kGcAWB7A7ujAFwEMAnJU4wgSwDsBzJAM1OwFskBqKJQ7JALRIeAOjFIAFEgBGAV0JIApgDdFtZtnKcALEgA0Sagqx4CPdCVIFiBNsQAeFRQAdFVAJQZ-1JoaS5iWgU-JABjABtqZ15-O3tqNlkOTmABHmokYgATLKRnVldSQgBPQQEAPiQAInRitmlscIAhbFlaLLp6ABEqYiqUKD0wQkw1XlGkWkV6KmpVJ1yLMgIs7FoAcmMcXCQwEGAwLN6kAF4kAG0wJCQAbyRlYnDZRTRByeI2F6R1poA5AGkAMIAQQACuskABfIbXO4PJ5fbQGWgfL4_ABKwIAEgBZACSvwAYpiIdCrrd7o9nmgke9Pmh1gBlABqgMZAFVQQBRUkwinw6lIWko-nfABSYq5AA1QQB5XnkuFUxHI1EM4FdZlc34AFQVsMpCLQCFVovWYoAmrKdXj9fzlcbTWjAVjgb8upjwVC-UqjUgTXTna73b9bd7FYbBQGRWjmXjGXjZb9AQSeeGDQKvtG1d92V1gRbJQB1O2-qNOhkJ0EAGVLkazFe-XQtv2B-PddczjsDDLjHIJOtr6ftfuzZsZ_0Z1dlAHFqzqup2Hf7G-tgU1AU0ucD0Yyl6PV_8udXteiZ_vyz3vtW8U1ZeiuoSCReG1f1jPZdWuoD716yRnlzHNEdR3Akw3_EdBQAJlXJpqwTIlrTTCCyy-KCRDeGNK3XdE8RxYFq2BF80Bgt9q1DDth1QkjVxxWV8zxdELWIpBSKw74OSY4FmWBJBGVBZ8qPrGi3w5X5GVldlwJ9YTWNXRkdXZB9mKErs5LfWUxWBRltMZLk9VU5c2Jzc020ZLFcJYgBGWj6K5dFfms1cwUUvdDL9Gy305bTgUJRz3MFTz2PWTE4xPY9eJndEnLfAkuj-f4YuCmcuRxBMWIEIKTK6IsuX-NsMqys0sTi10Hwy4zx0_PEugUpMKtXWVtPjBqNObRk9JUlDZIESq0Xy_DfiLAiiICr4BCAhkuQ6nc9MBDLJu-fLxKxBSFtg9lqyHbq1Im2yugJYFFOisa0AEYUTPM9EuXsgrTsEC6zSfXcdSLQTITAABdABuMAHnINg6FOJAcSoTAREB2gJDEEQjhICHiGcCQjEUDgTkqFG2BETN3HcX7_qQOJgdBkYEfsaGxDh4gEaRzHTgxwhUex5Vcd-0I1nQRpFBEcJsHoCQ4jxsBsGcGg1mBm5yWkYhQgAa3oVg2iyQFGk0BlCEoWh0GcMg1EIdY-T4RoaGcNA7hMXA0A154DA16h6HoRRSAZBxqHQA3MnidBQWwOhGedikSlcBksGyPBSWHBXqCyNBzjuUh7cwQgGQADgAUg9hpCD4NgaVtkWRPZoJiDoatiGkRRwit0gbf8aORgZKAoAzqFPr5exgS92PyVhHvrl4Ypg--TMDb764LbQJhHnQRQ-X7vJsHQIxqDWdWRdH-frmCygaAYDfN5jatsFCWZV--QGcnCRR9_nmMZ0R145_7130B1ag5bNjBtkn6fFGHeftaREINWOgXxzbf2YL_f-z8vYgKmJ_CekDwgz2gdcF-ZcK5VwpIgqeyC_4fXngQpAbdyTFE7m7bu89JabwHkPdYJ9Gb0E0MUG-_c6CqCsF8a2s8x68ATg7J2XJVBBGrjbXh6Dy6VzNrw8eEDuFP3nnYUg9A6AkRgjIwwQQnbwjQAABgUf3Rm9hCCMhKFfaRND55MDWIQIsihE7JyFLo_RGjrjWKCISD41BwjFAZDObAIwPhIHRK0doihcgdQ4MCPQ_jAkcBCUrcJfFGQcCaHoHENiZ6kB3qwmh7iTHUAAF5fCsuoyx_d2a8wDusZR0sJD6IaXoXRIg4BQHcOsDRRDCEGJfm_D-2CIG4JQRBee6DQEIMGVAkZ_cqaUMsT8AEIJwQGOuBibE7ZiRERWRxVkHJuS5P7uaSUMp5TbLXJqbUeozmWmtLaM5Lo3QejBAc1ZDyQx3I0esPsiZkyphebmfMhYuQljOVWWsZzmytnbIuM5fYpK6nBZ8icU5ZzzhhZ89cm5ty7n-esI8J5fhnlxTeO8D4nyOTOR-L8P50TLM-SBXCoZcVwQQoSJCuKdJNFwvhQixKKLovKesOiDEmIcqUhabivF-LPlBeycSkkPmCoUkpZsuLNI-Q6vpXFWk0oWUVfM4V9kKUYtBK5XF3kdJ-VxaFPE4VCJICiriuKCVcUpTSvqmh6wcp5QKmckq7oyoCvmRJG8tUdT1TOU1BMe5I3tU6rigabphq8rOdNHSu4uTzTOctcya0zlNE2oiwVwrDrHQ5RZG6mIcS4uegpN6jleGfT7kQkh1xlBu1kI8UGpsLh92oZvIOaJnDUEUKERQuA3bXwMcO0dih0BzJoXcegjM9EGHCI4zylS1bfFqcQCQAA2fRUEoL6LgA0kQCB2moP7kuldSBPLrsLqrapu6D1HpPXoM9TSMJXumVQpAy60JrscbSLdL76B1MPXoY9p7z0wF_ds29KowjPoZK-qDMHP3npTm0u0i6AOOMysB1dKGqloYg3uqCCB9HaH0dR792gEMaNvWdUi67xqbtQzuijEgqM0bo-e3D16DTLrOrSdjrGDBgfI3UvjehaN6Ho80-DeHN53Akw9KTXGak8bkwppTIgU6_sbQYrJI70B4jCfYVdvCcG_wMZoEdIjvg4AToUmxjwDlXyYI49Y-790iH80F4LwWYAZwMSfcIoRZDhHLuYvhYiaE6xyJ0GivCOifC1ivWgejm3klbRgJ25mF23F4YOhkw7Qh8ATo8JoZADlU1M3UBoVdPk6wbsAYAbArJQAwnoKycBQgCGabolOMFdGCGaVZfdSJhsiF0VBSbIgqNwD0HN3R-6rLhDSMtzba30Ip33XAbbvWoJ7YO0dobU390p2_bouAi25sIBgCaEb8AltQCgqt9bCAoLoDm1RwYT3dFWSWyek0c3tDHeaa027O2YDaH3dthAhmrJw5RynNHV2RBWV-2tqbv2lto_xxeqCKcidUZJ1ADb6Bmknu-80hAoPGdwFm4z7QW3esI4Zy0qAKdwjoQQIdtb2gRAwBgFBUII2cMk-m3AJAdO-ck6gjAfdCuRDaG0DAZXqvacXv3a9nHuiYDq819runquBcXuF6L8XUFwhc6h9-2HUuccy5G0z9XCBnvfum4tlnSJ2dWT1yD79z3dBzdKYb6nSOJqo9uxjtH4QYdK8d_u13uime-5TvL9b2hbuM_ewDzPDHBvreFyNzbROU4F_m4gMHq2RuIEKQc2o9RGiMiKWhFxNC28tZaErToPQSBoDiAYJAnWZCyHoLZ5rjR0QuDcI4sfE_gCcBGzZTroubKz_b-EQEkQe3yN3y1n2S8xY5e-GOrRpAvOSKwf2pLi9l5n3WK0QgS8shTo0Yg4_5TsBMBMAzyOLnD6KCBQQFY0JGImJmJgKuIaBBB2IOI0jOLbJuI2KeKAw-J-IBKYBBIJJhIRIpJIDRKxJ4HxKhJf5EGpLpKZJOw5JoEIEFLFJoClKMHSbcZ1KNLnqtLtKdK8JdJQj5ZgCQjfRAA)
