### ISSUE TITLE
如何根据X轴几个特别的点设置平行Y轴的直线

### ISSUE THREAD

**Issue by sxs89** [ecomfe/echarts#5796]
### One-line summary [问题简述]

如何根据时间点增加平行于Y轴的直线。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/5785
