### ISSUE TITLE
echarts3的legend的色块和文本的布局关系可以调整吗

### ISSUE THREAD

**Issue by ericWenjp** [ecomfe/echarts#5797]
### One-line summary [问题简述]

echarts3的legend的色块和文本的布局关系可以调整吗

code:
option.legend.formatter = '{name} Legend';
有没有Legend代表是色块的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echarts 3

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#legend.align
