### ISSUE TITLE
关系图graph中的link怎么画直角折线

### ISSUE THREAD

**Issue by lemo418** [ecomfe/echarts#5800]
### One-line summary [问题简述]
目前关系图的graph，默认节点间是直线箭头连接，能不能设置为直角折线的形式？
echarts2.0里的Tree图（为何在3.0里没有tree图了），lineStyle设置为 'broken' 就是直角折线。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: chrome 57
+ OS Version [操作系统类型和版本]: Windows 7

### Expected behaviour [期望结果]

设置节点连接线为直角折线。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![12356](https://cloud.githubusercontent.com/assets/23307468/26298429/d78e1490-3f09-11e7-94a8-4d0e712c27f9.png)

**Comment by pissang** [comment]
短期内不考虑这个特性

**Comment by lemo418** [comment]
感觉折线需要考虑的情况确实比较复杂。如果只是自己简单实现一下的话，能大概指点从文件哪里或哪个类下手么?用Polyline代替line来连接两点？感谢~

**Comment by yonghuming** [comment]
所以现在关系图和树图现在不可以画折线么

**Comment by jianlingl** [comment]
> 不支持直角折线，短期内也不考虑这个特性

7年过去了 现在可以支持吗
