### ISSUE TITLE
为什么缩放节点，文字不跟着节点一起缩放大小，固定不变，感觉不合理。

### ISSUE THREAD

**Issue by Rainnut** [ecomfe/echarts#5802]
![image](https://cloud.githubusercontent.com/assets/12372532/26299537/ba0db8e0-3f0d-11e7-9101-3d1ae2eaab69.png)
![image](https://cloud.githubusercontent.com/assets/12372532/26299525/ad9b2926-3f0d-11e7-8750-4b2612d82921.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
文字和图形应该同等缩放。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
为了保证文字能够看清楚

**Comment by Lily-Jian** [comment]
想问一下题主，有没有解决“节点缩放，节点的label标签跟着一起缩放”的方法？

**Comment by shangxinbo** [comment]
我也想知道，然而节点缩小应该文字也缩小，如果看不清楚就看不清楚呗，但最起码要协调一致啊

**Comment by Rainnut** [comment]
这个需求被搁置了，我也没往下跟
