### ISSUE TITLE
请问环形图中间可以插入图片吗?如果能怎么实现

### ISSUE THREAD

**Issue by OakMiss** [ecomfe/echarts#5803]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liangxiaoyang** [comment]
http://gallery.echartsjs.com/editor.html?c=xSJZsKhK8g
