### ISSUE TITLE
bmap，选择点连接形成闭合区域后的颜色填充问题

### ISSUE THREAD

**Issue by liliujie93** [ecomfe/echarts#5805]
### One-line summary [问题简述]

在bmap上绘制选取了一些点，并将他们首尾相连，形成一个闭合区域，如何填充这个闭合区域的颜色
绘制直线的点是我用存在json里的数据生成的，可以手动模拟生成几个点就可以进行测试，主要是如何填充闭合区域的颜色，并且在缩放时希望它是跟随地图缩放的，

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:eachart
+ Browser version [浏览器类型和版本]:谷歌浏览器
+ OS Version [操作系统类型和版本]:Windows10

### Expected behaviour [期望结果]

![inkedm pl 3jkjno0m5 vx xls7_li](https://cloud.githubusercontent.com/assets/28034005/26316971/959cc4fc-3f48-11e7-8d55-8567e58b1492.jpg)

### ECharts option [ECharts配置项]

```javascript
option = {
 bmap: {
            center: [106.537085,29.588439],
            zoom: 15,
            roam: true
        },
  series: [
        {
          name:'早高峰',
          type:'scatter',
          coordinateSystem:'bmap',
          // polyline:'true',
          zlevel:3,
          symbolSize:10,
          symbol:'circle',
          itemStyle:{
            normal:{
              color:'yellow'
            }
          },
          areaStyle:{normal:{
            color:'yellow'
          }},
          data:arr3
        },
}

```

### Other comments [其他信息]

![m pl 3jkjno0m5 vx xls7](https://cloud.githubusercontent.com/assets/28034005/26316787/f6b2b4aa-3f47-11e7-94c8-3fa4a8d15547.jpg)

**Comment by 100pah** [comment]
下个版本会在 custom series 中支持 bmap。参见 8b1c215
