### ISSUE TITLE
echarts 力导向图的位置每次刷新都改变，怎么固定位置

### ISSUE THREAD

**Issue by Gungnirs** [ecomfe/echarts#5807]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:window7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
布局完后存下来

**Comment by bitqiang** [comment]
请问下布局后怎么存下来？
