### ISSUE TITLE
echarts3.0  Brush 矩形选择框选中散点无返回值

### ISSUE THREAD

**Issue by duankt** [ecomfe/echarts#5808]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:win10

我使用echarts3.0时候遇到一个问题，
我在 Scatter Map Brush 示例中增加了PM2.0，PM1.0两项后，选中第三个类型pm1.0后用矩形选择框选中散点后，获取不到选中值，柱状图无法绘制出来。具体说明如下图
![lv4 g erq v8 ye_ e hx o](https://cloud.githubusercontent.com/assets/28881899/26335940/e801dc2e-3fa1-11e7-9fc4-4254fdc867f0.png)

### Expected behaviour [期望结果]

选中第三个类型pm1.0也能绘制出柱状图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
根据你的需求自行改一下例子中显示柱状图的代码
