### ISSUE TITLE
省份地图无法全部显示在固定大小的容器内

### ISSUE THREAD

**Issue by chxy020** [ecomfe/echarts#5813]
### One-line summary [问题简述]
echarts3.0 省份地图为何无法全部显示在固定大小的容器内？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts3.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
期望省份地图可以全部显示在固定容器内

### ECharts option [ECharts配置项]

```javascript
option = {
        geo: {
                map: ‘region’,
                layoutCenter: ['50%', '50%'],
                layoutSize:422
        }
}

```

### Other comments [其他信息]

http://echarts.baidu.com/demo.html#map-province

**Comment by pissang** [comment]
如果需要保证显示在容器内，设置 left, top, right, bottom 这几个布局属性

**Comment by chxy020** [comment]
( ⊙ o ⊙ )啊！? 这么设置地图会变形呀？ 请问没有更合理的方式么？

**Comment by chxy020** [comment]
@
( ⊙ o ⊙ )啊！? 这么设置地图会变形呀？ 请问没有更合理的方式么？

**Comment by chxy020** [comment]
@pissang
( ⊙ o ⊙ )啊！? 这么设置地图会变形呀？ 请问没有更合理的方式么？

**Comment by chxy020** [comment]
问题找到了，居然是地图json文件的问题~。。。。

**Comment by gaolian1025** [comment]
@chxy020 什么问题呀

**Comment by xue1234jun** [comment]
@chxy020 @gaolian1025 怎么解决

**Comment by chxy020** [comment]
我解决的方法是，替换了 原来项目里面的 地图 json 数据文件






在 2017-10-23 09:03:27，"xue1234jun" <notifications@github.com> 写道：


@chxy020@gaolian1025 怎么解决

**Comment by xue1234jun** [comment]
@chxy020 就是用的你问题链接里的json文件替换的吗？如果不是能否提供给我一份，1548594810@qq.com,不胜感激
