### ISSUE TITLE
请问哪个例子是讲echartsInstance.group  图表的联动的？

### ISSUE THREAD

**Issue by xiaomijiayou** [ecomfe/echarts#5814]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
```js
chart1.group = 'aaa';
chart2.group = 'aaa';

echarts.connect('aaa');
```
