### ISSUE TITLE
数据显示问题咨询

### ISSUE THREAD

**Issue by jonny77** [ecomfe/echarts#5819]
![image](https://cloud.githubusercontent.com/assets/1962170/26390238/4af09372-4090-11e7-9c86-c4997c41771f.png)
如图: 如何把bar显示在两个刻度之间 ? X轴有13条数据,Y轴只有12条数据.

**Comment by php-cpm** [comment]
我在博客上看到有直方图的示例  http://echarts.baidu.com/blog/2017/05/08/echarts-histogram-tutorial.html

**Comment by jonny77** [comment]
@php-cpm 我的就是一个普通的柱状图.不是直方图. 这个图表的意思 某个时间段内的销售金额.现在的情况有点错位了

**Comment by pissang** [comment]
xAxis.boundaryGap 设为 true

**Comment by mxy2316868975javascript** [comment]
请问你的问题解决的了吗
