### ISSUE TITLE
graph关系图采用force布局时怎么能自动让各个节点区域不产生覆盖效果

### ISSUE THREAD

**Issue by php-cpm** [ecomfe/echarts#5820]
从文档上看force布局只能设置节点间的引力和斥力，节点的symbolSize大了以后会跟其他临近节点挤到一起，很难看

**Comment by wangqianwen0418** [comment]
让每两个点间link value等于这两个点的symbolsize之和, 
然后force.edgelength 设置为一个区间
可以在一定程度上缓解覆盖
但不能从根本解决问题

可以参考下面例子中的防碰撞算法
https://bl.ocks.org/mbostock/1804919
