### ISSUE TITLE
echarts中, legend的formatter属性，当文字中需要参杂icon时，怎么实现？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#5822]
![image](https://cloud.githubusercontent.com/assets/22878190/26391267/7828c78e-4094-11e7-9639-afdfd3a1ca61.png)

### One-line summary [问题简述]

如截图所示，希望在legend各个图表名称后面加上一个提示性的icon，怎么实现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
legend 组件没法这么做，可以考虑自己用 html 实现自定义 legend 组件
