### ISSUE TITLE
使用markarea的x，y出错

### ISSUE THREAD

**Issue by WenzCao** [ecomfe/echarts#5832]
### One-line summary [问题简述]
在线图中使用markarea的series[i]-line.markArea.data.0.x y 属性，但echarts报错Cannot read property '0' of undefined    echarts.js:68598

at markAreaTransform (http://127.0.0.1:8000/assets/js/echarts.js:68598:39)
    at http://127.0.0.1:8000/assets/js/echarts.js:3346:26
    at Array.map (native)
    at Object.map (http://127.0.0.1:8000/assets/js/echarts.js:3246:25)
    at createList (http://127.0.0.1:8000/assets/js/echarts.js:68877:31)
    at ExtendedClass.renderSeries (http://127.0.0.1:8000/assets/js/echarts.js:68745:29)
    at ExtendedClass.<anonymous> (http://127.0.0.1:8000/assets/js/echarts.js:68085:38)
    at ExtendedClass.<anonymous> (http://127.0.0.1:8000/assets/js/echarts.js:2739:21)
    at Array.forEach (native)
    at each (http://127.0.0.1:8000/assets/js/echarts.js:3217:18)

### Version & Environment [版本及环境]
+ ECharts version 3:
+ Browser version chrome 版本 58.0.3029.110 (64-bit):
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
具体描述你的配置项和 echarts 版本

**Comment by WenzCao** [comment]
echarts是3.5.4
我的配置项

option = {
        baseOption: {
            timeline: {
                axisType: 'category',
                orient: 'vertical',
                autoPlay: true,
                inverse: true,
                playInterval: 2000,
                left: null,
                right: 0,
                top: 50,
                bottom: 5,
                width: 55,
                height: null,
                label: {
                    normal: {
                        textStyle: {
                            color: '#999'
                        }
                    },
                    emphasis: {
                        textStyle: {
                            color: '#fff'
                        }
                    }
                },
                symbol: 'none',
                lineStyle: {
                    color: '#555'
                },
                checkpointStyle: {
                    color: '#bbb',
                    borderColor: '#777',
                    borderWidth: 2
                },
                controlStyle: {
                    showNextBtn: false,
                    showPrevBtn: false,
                    normal: {
                        color: '#666',
                        borderColor: '#666'
                    },
                    emphasis: {
                        color: '#aaa',
                        borderColor: '#aaa'
                    }
                },
                data: []
            },
            //backgroundColor: '#404a59',
            title: {
                text: '2005年湘江流域干流各断面水质评价',
                subtext: '水质评价值变化'
            },
            tooltip: {
                trigger: 'axis'
            },
            //legend: {
            //    y: 'bottom',
            //    data:data.riverlist
            //},
            toolbox: {
                show: true,
                feature: {
                    dataZoom: {},
                    dataView: {readOnly: false},
                    magicType: {type: ['line', 'bar']},
                    restore: {},
                    saveAsImage: {}
                }
            },
            grid: {
                left: '3%',
                right: '10%',
                bottom: '3%',
                containLabel: true
            },
            xAxis:  {
                type: 'category',
                boundaryGap: true,
                axisLabel:{'interval':0},
                data: data.session,
                splitLine: {show: true},
                splitArea: {show: true}
            },
            yAxis: {
                type: 'value',
                min:0.72,
                max:0.84
            },
            //series: seriesdata
            series: [
                {
                    //name: "",
                    type: 'line',
                    data: data.series[0],
                    markArea: {
                        data: [ [{
                            name: '永州',
                            x: 100,
                            y: 100
                        }, {
                            x: '90%',
                            y: '10%'
                        }], [{
                            name: '衡阳',
                            itemStyle: {
                                normal: {
                                    color: 'rgba(128, 128, 128, 0.5)'   
                                }
                            },
                            xAxis: '归阳镇'
                        }, {
                            xAxis: '熬洲'
                        }], [{
                            name: '株洲',
                            itemStyle: {
                                normal: {
                                    color: 'rgba(128, 128, 128, 0.5)'   
                                }
                            },
                            xAxis: '朱亭镇'
                        }, {
                            xAxis: '霞湾'
                        }], [{
                            name: '湘潭',
                            itemStyle: {
                                normal: {
                                    color: 'rgba(128, 128, 128, 0.5)'   
                                }
                            },
                            xAxis: '马家河'
                        }, {
                            xAxis: '五星'
                        }], [{
                            name: '长沙',
                            itemStyle: {
                                normal: {
                                    color: 'rgba(128, 128, 128, 0.5)'   
                                }
                            },
                            xAxis: '昭山'
                        }, {
                            xAxis: '乔口'
                        }], [{
                            name: '岳阳',
                            itemStyle: {
                                normal: {
                                    color: 'rgba(128, 128, 128, 0.5)'   
                                }
                            },
                            xAxis: '樟树港'
                        }, {
                            xAxis: '樟树港'
                        }] ]
                    }
                }
            ],
            animationDurationUpdate: 1000,
            animationEasingUpdate: 'quinticInOut'
        },
        options: []
    };

**Comment by Janexr** [comment]
同遇到这个问题，只能单独设置x或者y，同时设置时就报错
