### ISSUE TITLE
希望geo3D支持 “平移缩放中心” 实时变化

### ISSUE THREAD

**Issue by skychx** [ecomfe/echarts#5834]
### One-line summary [问题简述]
在官方示例[Bar3D - Global Population](http://gallery.echartsjs.com/editor.html?c=xSyMekmcTx) 中，鼠标进行点击移动时，只能按照官方预设原始坐标[0,0,0]进行移动和缩放，虽然开发者可以自定义坐标位置，但还是希望echarts实现根据鼠标位置自动改变移动缩放坐标，类似 [全国主要城市空气质量](http://echarts.baidu.com/demo.html#effectScatter-map)的交互效果。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts3
+ Browser version [浏览器类型和版本]: Chrome58
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
希望echarts实现根据鼠标位置自动改变移动缩放坐标，类似 [全国主要城市空气质量](http://echarts.baidu.com/demo.html#effectScatter-map)的效果。

### ECharts option [ECharts配置项]

```javascript
option = {
   geo3D: {
            map: 'world',
            viewControl: {
                distance: 50,
                minDistance: 10,
                maxDistance: 200,
                rotateSensitivity: 1,
                center: [30,0,-10],
            },
    }
}

```

### Other comments [其他信息]

我的例子： [Bar3D - Global Population by skychx](http://gallery.echartsjs.com/editor.html?c=xSJVsw6mWZ&v=3)

**Comment by pissang** [comment]
鼠标中键是你说的平移操作

**Comment by skychx** [comment]
soga，了解了，看来还是我不够认真啊

**Comment by skychx** [comment]
我刚刚试了一下移动端，单指是角度变化，双指是缩放，我目前还没有试出平移的手势操作，echarts有这个功能支持吗？

**Comment by pissang** [comment]
@skychx 这个后续是要优化，谢谢反馈
