### ISSUE TITLE
Error: Bar only support cartesian2d coordinateSystem

### ISSUE THREAD

**Issue by NexusInk** [ecomfe/echarts#5836]
### One-line summary [问题简述]
`Error: Uncaught (in promise): Error: Bar only support cartesian2d coordinateSystem
Error: Bar only support cartesian2d coordinateSystem`

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: via `npm install echarts --save` : `"echarts": '^3.5.4';`

Ionic Framework: 3.2.1
Ionic App Scripts: 1.3.7
Angular Core: 4.1.0
Angular Compiler CLI: 4.1.0
Node: 7.2.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 OPR/45.0.2552.812

### Expected behaviour [期望结果]
From the Echarts Demo (Bar Polar Stack) here: [https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-polar-stack](https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-polar-stack)

### ECharts option [ECharts配置项]

```javascript
option = {
    angleAxis: {
    },
    radiusAxis: {
        type: 'category',
        data: ['周一', '周二', '周三', '周四'],
        z: 10
    },
    polar: {
    },
    series: [{
        type: 'bar',
        data: [1, 2, 3, 4],
        coordinateSystem: 'polar',
        name: 'A',
        stack: 'a'
    }, {
        type: 'bar',
        data: [2, 4, 6, 8],
        coordinateSystem: 'polar',
        name: 'B',
        stack: 'a'
    }, {
        type: 'bar',
        data: [1, 2, 3, 4],
        coordinateSystem: 'polar',
        name: 'C',
        stack: 'a'
    }],
    legend: {
        show: true,
        data: ['A', 'B', 'C']
    }
};

```

### Other comments [其他信息]

Have managed to reproduce this repo: [https://github.com/ralscha/blog/tree/master/echarts](https://github.com/ralscha/blog/tree/master/echarts) and have successfully added: [https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-y-category-stack](https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-y-category-stack) & [https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-weight](https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-weight) and have extended chart views with `toolbox` functionality as well as `get()` for specific datasets.

All chart options have been tested. I

**Comment by Ovilia** [comment]
3.6.0 版本开始支持，谢谢感兴趣~

**Comment by NexusInk** [comment]
Cool-thanks! I just checked that Echarts got bumped to `3.6.0` 
Next time I'll check that first ;)
The charts seem to work perfectly!
Closing this issue.

**Comment by NexusInk** [comment]
Charts all work on other platforms when I call echarts through a library.
Unfortunately `3.6.0` is not available as an `npm` module just yet.
Will leave this open for now.

**Comment by Ovilia** [comment]
Version `3.6.0` is about to release in a day. Thanks! :)

**Comment by NexusInk** [comment]
@Ovilia Excellent! Thanks for the heads-up!
