### ISSUE TITLE
折线图展示bug

### ISSUE THREAD

**Issue by larrymshi** [ecomfe/echarts#5838]
### One-line summary [问题简述]
折线图在官网展示bug，当某一个值为0的时候，折线点并未处于y轴0点处，而处于该y轴最低值处，见图

![wx20170525-160529](https://cloud.githubusercontent.com/assets/14814046/26441710/284c8996-4164-11e7-96ab-99429f9c6a02.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: Mac

官网demo ；；；；
官网demo ；；；；
官网demo ；；；；

http://echarts.baidu.com/demo.html#line-stack

### ECharts option [ECharts配置项]

```javascript
option = {
 title: {
        text: '折线图堆叠'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[0, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[220, 182, 191, 0, 290, 330, 310]
        },
        {
            name:'视频广告',
            type:'line',
            stack: '总量',
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'直接访问',
            type:'line',
            stack: '总量',
            data:[320, 332, 301, 334, 390, 330, 320]
        },
        {
            name:'搜索引擎',
            type:'line',
            stack: '总量',
            data:[820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
}

```

### Other comments [其他信息]

![wx20170525-160529](https://cloud.githubusercontent.com/assets/14814046/26441699/208fa684-4164-11e7-8cce-c8e11035fead.png)

**Comment by MiCoo** [comment]
如果把一组数据都置为0：
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[0, 0, 0, 0, 0, 0, 0]
        },
这条线竟然不是处于Y轴最底的。。。
