### ISSUE TITLE
关于ng2动态更新echarts数据

### ISSUE THREAD

**Issue by wangjian1119** [ecomfe/echarts#5841]
### One-line summary [问题简述]

ng2动态更新echarts图表数据

我看介绍说要再一次setOption

我不知道怎么再继续绑定

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:    npm包的    3.5.4
+ Browser version [浏览器类型和版本]:  chrome
+ OS Version [操作系统类型和版本]:   window10

### Expected behaviour [期望结果]

实现echarts图表数据更新

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 的数据更新就是 setOption，ng 相关的问题可以去相关社区询问

**Comment by wangjian1119** [comment]
谢谢
