### ISSUE TITLE
Does #3067 corrected valus < min too?

### ISSUE THREAD

**Issue by norbertorozas** [ecomfe/echarts#5844]
Issue # 3067 corrected values > Max (pointer doesn't stop), but we see values < min that makes pointer overpass min value.
![gauge](https://cloud.githubusercontent.com/assets/9438544/26460145/29a851ea-414f-11e7-9125-6e23d5c89f95.jpg)

**Comment by pissang** [comment]
Latest echarts version don't have this problem. https://ecomfe.github.io/echarts-examples/public/editor.html?c=gauge
