### ISSUE TITLE
请问3.6.0 不支持直接导入js文件了么？在线等

### ISSUE THREAD

**Issue by dmKiller** [ecomfe/echarts#5846]
我直接引入
` <link rel="stylesheet" href="../assets/plugins/echarts/echarts.common.min.js?v=1.0.0"/>`

报echarts 没定义 ，请问这个版本是否不支持了！  在线等？  必须要require吗？

**Comment by blueagles** [comment]
<script src="../assets/plugins/echarts/echarts.common.min.js?v=1.0.0"></script>
这样引入

**Comment by dmKiller** [comment]
哦

**Comment by dmKiller** [comment]
我居然写成了css~

**Comment by dmKiller** [comment]
傻逼了
