### ISSUE TITLE
饼图百分比之和超过100%

### ISSUE THREAD

**Issue by ShirleyYoung0926** [ecomfe/echarts#5850]
### One-line summary [问题简述]

在使用饼图的时候，如果有三组数据，分别是455，545， 0，在饼图的显示中，如果取整的话分别为46%， 55%， 0%，总和 100%。 现在有没有什么配置项可以保证各项百分之和精确为100%吗？
http://echarts.baidu.com/echarts2/doc/example/pie.html
在线demo中更改了数据，结果如下：

<img width="1305" alt="screen shot 2017-05-26 at 1 59 43 pm" src="https://cloud.githubusercontent.com/assets/23160157/26482967/f4dd162a-421c-11e7-9bd2-4adb2e98dc5a.png">

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个应该是 formatter 中取整后带来的问题，试试精度大一点

**Comment by ShirleyYoung0926** [comment]
谢谢回答，已经跟产品协商能不能保留两位小数，将误差控制到0.01。那会不会考虑采用类似https://en.wikipedia.org/wiki/Largest_remainder_method 这样的方法保证总和为100%。我也有考虑在数据传入之前先做一下检测，处理一下源数据再调用echart，但是感觉怪怪的。

**Comment by ShirleyYoung0926** [comment]
目前的解决方法，是在外部做一下数据的处理，将处理好的百分比和对应项目的名称保存起来，然后在formatter的时候根据这个项目的名称找到它对应的百分比，然后将这个百分比渲染出来。

**Comment by Ovilia** [comment]
@ShirleyYoung0926 这一功能稍后会在 ECharts 3 中支持，我看你用的好像是 ECharts 2，建议升到 3
