### ISSUE TITLE
折线图 yAxis.min/max 问题

### ISSUE THREAD

**Issue by langwuzhe** [ecomfe/echarts#5852]
### One-line summary [问题简述]

1.现在yAxis max/min  用了 'dataMax','dataMin' 来控制y轴画线的上下限值.但是这样画出的线都顶着最上边/最下边,很不美观!(如图,圈住的那条线在最上面

)
2.图例有时候会莫名其妙的出现重影.如图:

![qq 20170526161356](https://cloud.githubusercontent.com/assets/24667395/26486624/7629d5cc-422e-11e7-8066-90c66f8e0f3d.jpg)
![6wm 1_hh2 ywkhc 5wk2cs](https://cloud.githubusercontent.com/assets/24667395/26486650/8dc72d2e-422e-11e7-994a-97a753075a68.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:谷歌  58.0.3029.110
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

图表上下能智能留一点空白 好看
![qq 20170526161958](https://cloud.githubusercontent.com/assets/24667395/26486797/404933b6-422f-11e7-9254-6360bea69f53.jpg)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by langwuzhe** [comment]
echarts 明晃晃了boundaryGap留白属性我居然没有看见  唉。。。。。。。。

**Comment by TonySheva** [comment]
@langwuzhe boundaryGap不是在设置了min和max以后会失效么？

**Comment by langwuzhe** [comment]
@TonySheva 我用的 是类目轴，在非类目轴中会失效

**Comment by TonySheva** [comment]
@langwuzhe thx

**Comment by Aryalina** [comment]
为啥用了min函数后，坐标轴的刻度与值不显示了，
