### ISSUE TITLE
datazoom滑动条上可以添加刻度吗？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#5854]
### One-line summary [问题简述]
![image](https://cloud.githubusercontent.com/assets/22878190/26487247/4b09a982-4231-11e7-8fcc-bf7e21147bd0.png)

如上图，想要把某些有特殊意义的x轴，刻画在datazoom的相应位置，让人能够一打开页面就能通过刻度直接滑动datazoom找到相应x轴数据？？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
计划中
