### ISSUE TITLE
折线图 sampling属性无法使用

### ISSUE THREAD

**Issue by artFollower** [ecomfe/echarts#5855]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
具体点？

**Comment by 100pah** [comment]
Fixed on a39fbd9

**Comment by artFollower** [comment]
已经修复了么？
