### ISSUE TITLE
关于cursor样式设置的问题

### ISSUE THREAD

**Issue by caibird007** [ecomfe/echarts#5856]
### One-line summary [问题简述]
当鼠标指向某个柱状图的时候,鼠标形状会变成pointer的形状,但是我不想用pointer,希望还是arrow的形状(原因是pointer这种形状容易诱导用户点击,而这个图是不需要点击后发生任何效果变化的)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome和火狐
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
希望鼠标的形状是能够设置的

**Comment by 100pah** [comment]
Fixed on 6ded29a

**Comment by yicheny** [comment]
在series里设置cursor:'default'即可

**Comment by yhuayang233** [comment]
![image](https://github.com/apache/echarts/assets/133995431/76ac6b4a-d9cd-4fb4-bbea-9f03f88eef41)我设置了没有任何效果
