### ISSUE TITLE
散点图中多个数据重合到一起的时候,重合点的tooltip只能显示一个

### ISSUE THREAD

**Issue by caibird007** [ecomfe/echarts#5857]
### One-line summary [问题简述]

在散点图中,如果两个点完全重合,就会变成别的颜色,比如图中的蓝色和红色完全重叠到了一起,但是作用用户,当把鼠标放到了这个重合点上面,是想知道所有重合点的tooltip(此时貌似只能显示一中)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome和火狐
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
能够显示所有点的tooltip

### Other comments [其他信息]

![default](https://cloud.githubusercontent.com/assets/28947051/26488258/53db88b0-4235-11e7-858a-841ff93f6c57.png)

**Comment by pissang** [comment]
可以将 tooltip.trigger 设成 axis

**Comment by BadMooncc** [comment]
散点图设置成axis会报错啊求解
