### ISSUE TITLE
label 文字换行后行高怎么调小一点

### ISSUE THREAD

**Issue by sweetyluo** [ecomfe/echarts#5859]
label 文字换行后行高怎么调小一点

**Comment by sweetyluo** [comment]
![1495793578 1](https://cloud.githubusercontent.com/assets/22252654/26492871/099d44b4-4249-11e7-9b02-46393fc9751d.jpg)

**Comment by pissang** [comment]
暂时不行

**Comment by sweetyluo** [comment]
那文字太长在手机上显示不全应该怎么处理，如果不换行的话
