### ISSUE TITLE
最小宽度

### ISSUE THREAD

**Issue by HealerJTF** [ecomfe/echarts#5860]
### One-line summary [问题简述]

外层div隐藏之后canvas（图表绘制之后）所在的div宽度变成了90

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0+
+ Browser version [浏览器类型和版本]:谷歌
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]

外层div隐藏和显示的时候图表的宽度是相同的

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/24707837/26496275/6477c480-4259-11e7-9b6d-8d1bbffd3b56.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echartsInstance.resize
