### ISSUE TITLE
柱形图，两组数据设置重合的问题

### ISSUE THREAD

**Issue by l7612945** [ecomfe/echarts#5861]
### One-line summary [问题简述]
柱形图中，当设置{barGap: 0,barWidth: '100%'}使两个柱子重合的时候，有没有可能显示出重合的颜色，而不是单纯的覆盖和被覆盖？设置了opacity也是无效果。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0+
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望能颜色混合。

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#blendMode 试试这个属性

**Comment by l7612945** [comment]
blendMode我试了下，好像不管用。
也许我问题描述得不是很清楚吧，我是想实现类似嵌套图的效果：两个重叠的柱状图，高的显示出来，矮的也不被覆盖掉。
现在的情况是：即使前面一个柱状图数据都为0，后面一个数据不为0的柱状图就显示不出来，得在legend那里取消掉前一个才能显示后一个，我想问的是：有没有办法同时显示出来？

**Comment by l7612945** [comment]
@pissang

**Comment by pissang** [comment]
设置 opacity 就可以吧，http://gallery.echartsjs.com/explore.html 发一个例子？

**Comment by l7612945** [comment]
见http://gallery.echartsjs.com/editor.html?c=xHkjR7Whbb&v=1

**Comment by l7612945** [comment]
@pissang
