### ISSUE TITLE
yAxis axisTick interval 设置为数值时无效

### ISSUE THREAD

**Issue by 624220042** [ecomfe/echarts#5864]
yAxis axisTick interval 设置为数值时无效，并没有像配置文档中那样，
“如果设置为 1，表示『隔一个标签显示一个标签』，如果值为 2，表示隔两个标签显示一个标签，以此类推”
```js
 yAxis: {
        type: 'value',
        splitNumber: 9,
            axisTick: {
              'interval': 2,
            },
    },
```
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by founderchiu** [comment]
也遇到这个问题。

要求给一个数字和function。

**Comment by pissang** [comment]
标签是 axisLabel ，axisTick 是刻度线
