### ISSUE TITLE
雷达图如何使用timeline组件？

### ISSUE THREAD

**Issue by fanpeizhong** [ecomfe/echarts#5865]
### One-line summary [问题简述]
在直方图等具有二维坐标系的图都可以使用timeline 组件，但因为雷达图没 xAxis和yAxis坐标轴，自己反复尝试都无法实现。
请问雷达图是否可以使用timeline 组件、如何使用？麻烦提供实例，谢谢！！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
所有组件都可以使用 timeline，timeline 其实相当于是不同时间的 option 的组合

**Comment by fanpeizhong** [comment]
如何设置雷达图的timeline呢？也找不到实例。怎么弄都不行
