### ISSUE TITLE
单独设置yAxis的最大值

### ISSUE THREAD

**Issue by wangjian1119** [ecomfe/echarts#5870]
### One-line summary [问题简述]

设置yAxis的最大值需要重新整个setOption吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:    node 7.0.0      ECharts 3.5.4 
+ Browser version [浏览器类型和版本]:    chrome
+ OS Version [操作系统类型和版本]:  win10

### Expected behaviour [期望结果]

单独设置一个按钮点击更改yAxis的最大值

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
```js
setOption ({ yAxis: {max: 100 }})
```
所有配置的设置都是通过 setOption 接口

**Comment by wangjian1119** [comment]
谢谢
