### ISSUE TITLE
y轴的数字在超过3位被隐藏了

### ISSUE THREAD

**Issue by jonny77** [ecomfe/echarts#5872]
![22](https://cloud.githubusercontent.com/assets/1962170/26619406/e91a5d6e-4610-11e7-95bf-02e3d479c419.png)
手机是iPhone5s .横屏正常.echarts版本是 3.4.0
想让左边离屏幕边缘远一点.设置了legend的left没效果.padding也没效果

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#grid.left
