### ISSUE TITLE
showTip Action postion参数没有起到应有的效果

### ISSUE THREAD

**Issue by Shinhwe** [ecomfe/echarts#5874]
### One-line summary 

showTip Action postion参数没有起到应有的效果

chart.dispatchAction({
    type: 'showTip',
    seriesIndex: 0,
    dataIndex: 7,
    position: function() {
      alert(1);
    }
  });
并没有弹出alert

chart.dispatchAction({
    type: 'showTip',
    seriesIndex: 0,
    dataIndex: 7,
    position: [10,10]
  });
tooltip也并没有出现在预期的[10,10]的位置

### Version & Environment
+ ECharts version : v3.6.1
+ Browser version : Google Chrome 58.0.3029.110 (64-bit)
+ OS Version : MAC OSX 10.11.6 (15G1510)

**Comment by pissang** [comment]
用 x, y
