### ISSUE TITLE
没有数据时，series chart无法显示

### ISSUE THREAD

**Issue by TinaC** [ecomfe/echarts#5875]
### One-line summary [问题简述]

在没有数据时，chart无法显示。之前使用的3.2.3版本在这种情况是会显示yAxis的splitLine  & axisLabel的。
这样一片空白但是显示x轴y轴的名字看起来有点奇怪？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]: Chrome 58.0.3029.110
+ OS Version [操作系统类型和版本]: macOS 10.12.3 

### Expected behaviour [期望结果]
显示Y轴的splitLine & axisLabel

### ECharts option [ECharts配置项]

http://gallery.echartsjs.com/editor.html?c=xr1xW1Tibb&comment=0
注释最后部分的代码添加一条数据就能显示正常，并且legend的字体大小也会变化。

**Comment by 100pah** [comment]
这个倒是特意这样做的。没有数据时，显示本就显示不出来 chart；没有数据时，坐标轴上显示出来 splitLine 和 axisLabel 也是个假的值，没有意义。

**Comment by TinaC** [comment]
但是markLine和markArea都会显示，这样看起来不是更奇怪么？

**Comment by TinaC** [comment]
Fixed this problem by setting 

```
    yAxis: {
      max: 1,
      min: 0,
    }
```
    
Then update yAxis.max to 'dataMax' and yAxis.min to 'dataMin' after data loaded.
