### ISSUE TITLE
使用china map时仅显示南海诸岛部分，且提示map china does not exist

### ISSUE THREAD

**Issue by fufjvnvnf** [ecomfe/echarts#5879]
### One-line summary [问题简述]
我想根据http://echarts.baidu.com/demo.html#map-china-dataRange 例子使用echart。然后render出来的地图只有南海诸岛一部分，其余再缩小也看不见。使用“页面源文件”查看时还报出map china does not exist错误，而我已经require('echarts/map/js/china.js');了。尝试通过重新下载并替换china.js文件，然而还是一样的问题。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]: Safari
+ OS Version [操作系统类型和版本]: MacOS 10.12.5

### Expected behaviour [期望结果]
跟http://echarts.baidu.com/demo.html#heatmap-map 一样，显示全国地图及销量图。

### ECharts option [ECharts配置项]

option是跟链接的例子一样的。这里就不再帖一次了。
```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/download-map.html

**Comment by fufjvnvnf** [comment]
没有用 地图早就存在在我的本地js里了。我也使用require引入了地图。地图也显示出了南海诸岛的一部分。 我也尝试了重新下载一遍链接里的地图替换本地的地图但是还是一样的问题。这个link并不能解决问题。请问你可以重新open这个issue吗谢谢你。

**Comment by fufjvnvnf** [comment]
@pissang @kener 请教大神。

**Comment by pissang** [comment]
这个就是地图文件没有引入的错误，至于为什么会没有引入建议你排查一下自己代码中的问题

**Comment by fufjvnvnf** [comment]
解决方法在https://github.com/hustcc/echarts-for-react/issues/66 。
