### ISSUE TITLE
Is there any way to reduce width of labels on yAxis on the bar-chart?

### ISSUE THREAD

**Issue by GreatEarl** [ecomfe/echarts#5880]
question

### One-line summary [问题简述]
I have to use long label names like 
['1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
 '2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
 '3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
 '4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
 '5. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.']	
  
On the chart they appear in single line. Can the be divided in at least two lines?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: Chrome - latest
+ OS Version [操作系统类型和版本]: Win 7x64

### Expected behaviour [期望结果]
1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
 eiusmod tempor incididunt ut labore et dolore magna aliqua.',
 
![bar](https://cloud.githubusercontent.com/assets/3702703/26628513/28727b90-4620-11e7-9873-a108d1ad8c3a.png)
2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua.',
3. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua.',
4. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua.',
5. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua.']	
  

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by wangfengming** [comment]
`\n` will work.

You can insert a `\n` every 5 words.

**Comment by GreatEarl** [comment]
@wangfengming  Oh thank you! I tried <br> but it doesn't work. 
Right now I use this solution as options on yAxis:
` zlevel: 1,
        axisLabel:
        {
        inside: true,
        textStyle:
         {
             color: 'black'
            }
        },`
