### ISSUE TITLE
关系图Les Miserables参数 nodes 数据中的x与y如何自动获得

### ISSUE THREAD

**Issue by Vivomo** [ecomfe/echarts#5881]
### One-line summary [问题简述]
关系图Les Miserables 参数 nodes 中定位参数x和y没有办法自动计算出来.
官网的数据是提前定好的, 但实际应用中, 这个数据是不会有的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0+
+ Browser version [浏览器类型和版本]: chrome58
+ OS Version [操作系统类型和版本]: windows

### Expected behaviour [期望结果]

我希望传入的值不需要自带 x与y, 程序自己生成.

### ECharts option [ECharts配置项]

```javascript 
//非配置问题
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-graph.layout

**Comment by Vivomo** [comment]
怪我没有好好看文档, 十分感谢您的解答

**Comment by xiashan** [comment]
是建议采用circular布局么？

**Comment by wangyong991** [comment]
> http://echarts.baidu.com/option.html#series-graph.layout

您好，如果不想用circular和force布局，然后这个坐标如何生成，或者例子中坐标是如何生成的。
