### ISSUE TITLE
leaflet 扩展echarts3 之模拟迁徙 在iphone6 模拟器下 cpu 占用为 40%到50%，可否降低到10%

### ISSUE THREAD

**Issue by wusheng** [ecomfe/echarts#5884]
leaflet 扩展echarts3 之模拟迁徙 在iphone6 
![qq20170601-111548](https://cloud.githubusercontent.com/assets/2882467/26663300/5ae31e6c-46bc-11e7-8fd2-c85949d5a3e4.png)

模拟器下 cpu 占用为 40%到50%，可否降低到10%

**Comment by pissang** [comment]
关闭动画
