### ISSUE TITLE
同一个div加载两次图标样式错乱问题

### ISSUE THREAD

**Issue by dapengwyp** [ecomfe/echarts#5885]
### One-line summary [问题简述]

版本由3.5.2升级到3.6.1后，同一个div第二次加载图表时，样式错乱。主要体现在div再次加载图表时，原先的图表内容貌似没有清空。
#### 附加说明：
- 出现问题的图表是双y轴。
- 且版本还原到3.5.2后，问题解决了。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]: chrome 58.0.3029.110 (64-bit)
+ OS Version [操作系统类型和版本]:macos sierra 10.12.5

### Expected behaviour [期望结果]
同一个div，没次加载图表，需要清空之前的图表内容

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能否把你的 option 贴一下
