### ISSUE TITLE
xAxis.axisLabel.textStyle.color颜色写function，echarts3.x里面无效了？

### ISSUE THREAD

**Issue by wuhou123** [ecomfe/echarts#5886]
xAxis.axisLabel.textStyle.color颜色写function，echarts3.x里面无效了？

### One-line summary [问题简述]

            axisLabel: {
                formatter:function(v){
                    switch (v + '') {
                        case '0' : return 'E';
                        case '1' : return 'Gas';
                        case '2' : return 'F';
                    }
                },
             textStyle: {
			  color: function(value, index) {
				return value >= 5 ? '#000' : '#0daaf3';
		      }
						} 
            }
没有效果，只显示axisLine里的最后一个lineStyle.color

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.x
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {
 axisLabel: {
                formatter:function(v){
                    switch (v + '') {
                        case '0' : return 'E';
                        case '1' : return 'Gas';
                        case '2' : return 'F';
                    }
                },
             textStyle: {
			  color: function(value, index) {
				return value >= 5 ? '#000' : '#0daaf3';
		      }
						} 
            }
}

```

**Comment by pissang** [comment]
试了没什么问题，建议在 http://gallery.echartsjs.com/ 复现你的问题
