### ISSUE TITLE
IE8 完整压缩版本有问题

### ISSUE THREAD

**Issue by zhuangxiaohui** [ecomfe/echarts#5896]
echarts3.6.1完整压缩版本在IE8下有问题，报以下错误：
  缺少 '}'  echarts.min.js, 行11 字符41
  ECharts is not Loaded
  'echarts' 未定义

**Comment by 100pah** [comment]
我从 <http://echarts.baidu.com/download.html> 中下载了完整版的 echarts.min.js，在 ie8 中没有发现这个问题。如果确实有问题，是否可以提供你的 echarts.min.js？
