### ISSUE TITLE
echarts 配置项的 label属性的textStyle不能设置行高，很丑

### ISSUE THREAD

**Issue by kxcc** [ecomfe/echarts#5898]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```
涉及公司项目仅部分截图。

### Other comments [其他信息]

![image](https://cloud.githubusercontent.com/assets/24751083/26720685/c6c53d2c-47bb-11e7-93ff-76fec9df4487.png)

**Comment by kxcc** [comment]
使用换行符号，间距又太大！

**Comment by 100pah** [comment]
3.7.1 版本已支持富文本标签，参见：<http://echarts.baidu.com/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE>
