### ISSUE TITLE
折线图坐标轴上的文字模糊不清，有重影

### ISSUE THREAD

**Issue by kagol** [ecomfe/echarts#5899]
### One-line summary [问题简述]

折线图坐标轴上的文字模糊不清，有重影，如下图：

![image](https://cloud.githubusercontent.com/assets/9566362/26749989/a6d1b010-484a-11e7-8bad-3aaef47d1969.png)

### Version & Environment [版本及环境]
+ ECharts version [^3.1.6]:
+ Browser version [Goolge Chrome 58.0.3029.110 (64-bit)]:
+ OS Version [Windows 7]:

### Expected behaviour [期望结果]

![image](https://cloud.githubusercontent.com/assets/9566362/26750000/c0dde00a-484a-11e7-98f5-9618226ce1e2.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能具体描述你的环境么？以及把 echarts 版本升级到最新版本看看？

**Comment by webJing** [comment]
echarts.init(document.getElementById(id),'', {devicePixelRatio:2});这样的配置可以解决，设置像素比为2

**Comment by kagol** [comment]
@webJing好的，我试下，蟹蟹~

**Comment by kagol** [comment]
@pissang，应该是我代码的问题，还没解决，不知道是不是重复渲染之类的。。

**Comment by pissang** [comment]
@kagol 最近反馈了好几个类似的问题，好像是 windows 下的 chrome 在窗口缩放到很小的时候会复现

**Comment by kagol** [comment]
@webJing 这个方法是可以解决重影的问题的，在此表示感谢~~

**Comment by mpw0311** [comment]
> echarts.init(document.getElementById(id),'', {devicePixelRatio:2});这样的配置可以解决，设置像素比为2

这个方案主要是提高分辨率的，最近碰到transform:scale(x,y)放大图形导致模糊就是这样解决的
