### ISSUE TITLE
没有办法将x值不同的数据画到同一横坐标的图上

### ISSUE THREAD

**Issue by andrew2015** [ecomfe/echarts#5902]
### One-line summary [问题简述]
我有两组数据：
1- [{x:0,y:0},{x:1,y:1},{x:2,y:2},{x:3,y:3}]
2- [{x:1.5,y:5},{x:2.3,y:4},{x:3.6,y:7},{x:4.2,y:9}]
如何用Echarts将上面 两组数据画在同一个图的同一个横坐标上？我如果使用2个横坐标，两组数据就没有办法对齐

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
用两个 x 轴
