### ISSUE TITLE
关系图环形布局能够提供半径设置选项

### ISSUE THREAD

**Issue by yangmqglobe** [ecomfe/echarts#5903]
关系图采用环形布局时，节点标签往往超出绘图边界而无法显示完全，但缩放后完全可以显示完全，但现在无法找到设置绘制半径的选项

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以设置 width 和 height，radius 会取这两个中小的值
