### ISSUE TITLE
官方示例Scatter Nutrients问题

### ISSUE THREAD

**Issue by cehceh1** [ecomfe/echarts#5904]
### One-line summary [问题简述]
我按照官网给的demo在本地的webstorm运行，发现右上角的图例总是没有，不知道什么原因，请求大神帮助。（另外官网的demo里缺失<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/jquery/jquery.js"></script>）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
echarts3.0以上；
ie11和火狐53
win10

### Expected behaviour [期望结果]
期望将echarts示例里的legend显示出来，如echarts网站里的https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-nutrients

### ECharts option [ECharts配置项]

下面是代码
```javascript 
<!DOCTYPE html>
<html style="height: 100%">
<head>
    <meta charset="utf-8">
</head>
<body style="height: 100%; margin: 0">
<div id="container" style="height: 100%"></div>

<script type="text/javascript" src="config.js"></script>
<script type="text/javascript" src="esl.js"></script>

<script type="text/javascript" src="http://echarts.baidu.com/js/config.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/jquery/jquery.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/bootstrap/js/bootstrap.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/perfect-scrollbar/0.6.8/js/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/lodash.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/dat.gui.min.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/javascripts/editor.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/ace/src/ace.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts-stat/ecStat.min.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/extension/dataTool.min.js"></script>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=ZUONbpqGBsYGXNIYHicvbAbM"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/extension/bmap.min.js"></script>
<script type="text/javascript">
    var dom = document.getElementById("container");
    var myChart = echarts.init(dom);
    var app = {};
    option = null;
    var indices = {
        name: 0,
        group: 1,
        id: 16
    };
    var schema = [
        {name: 'name', index: 0},
        {name: 'group', index: 1},
        {name: 'protein', index: 2},
        {name: 'calcium', index: 3},
        {name: 'sodium', index: 4},
        {name: 'fiber', index: 5},
        {name: 'vitaminc', index: 6},
        {name: 'potassium', index: 7},
        {name: 'carbohydrate', index: 8},
        {name: 'sugars', index: 9},
        {name: 'fat', index: 10},
        {name: 'water', index: 11},
        {name: 'calories', index: 12},
        {name: 'saturated', index: 13},
        {name: 'monounsat', index: 14},
        {name: 'polyunsat', index: 15},
        {name: 'id', index: 16}
    ];

    var fieldIndices = schema.reduce(function (obj, item) {
        obj[item.name] = item.index;
        return obj;
    }, {});

    var groupCategories = [];
    var groupColors = [];
    var data;

    // zlevel 为 1 的层开启尾迹特效
    myChart.getZr().configLayer(1, {
        motionBlur: 0.5
    })

    $.get('nutrients.json', function (originData) {
        data = normalizeData(originData).slice(0, 1000);

        myChart.setOption(option = getOption(data));
    });


    function normalizeData(originData) {
        var groupMap = {};
        originData.forEach(function (row) {
            var groupName = row[indices.group];
            if (!groupMap.hasOwnProperty(groupName)) {
                groupMap[groupName] = 1;
            }
        });

        originData.forEach(function (row) {
            row.forEach(function (item, index) {
                if (index !== indices.name
                    && index !== indices.group
                    && index !== indices.id
                ) {
                    // Convert null to zero, as all of them under unit "g".
                    row[index] = parseFloat(item) || 0;
                }
            });
        });

        for (var groupName in groupMap) {
            if (groupMap.hasOwnProperty(groupName)) {
                groupCategories.push(groupName);
            }
        }
        var hStep = Math.round(300 / (groupCategories.length - 1));
        for (var i = 0; i < groupCategories.length; i++) {
            groupColors.push(echarts.color.modifyHSL('#5A94DF', hStep * i));
        }

        return originData;
    }

    function getOption(data) {

        return {
            backgroundColor: '#2c343c',
            tooltip: {
                padding: 10,
                backgroundColor: '#222',
                borderColor: '#777',
                borderWidth: 1
            },
            xAxis: {
                name: 'protein',
                splitLine: {show: false},
                axisLine: {
                    lineStyle: {
                        color: '#fff'
                    }
                },
                axisLabel: {
                    textStyle: {
                        color: '#fff'
                    }
                },
                axisTick: {
                    lineStyle: {
                        color: '#fff'
                    }
                }
            },
            yAxis: {
                name: 'calcium',
                splitLine: {show: false},
                axisLine: {
                    lineStyle: {
                        color: '#fff'
                    }
                },
                axisLabel: {
                    textStyle: {
                        color: '#fff'
                    }
                },
                axisTick: {
                    lineStyle: {
                        color: '#fff'
                    }
                }
            },
            visualMap: [{
                show: false,
                type: 'piecewise',
                categories: groupCategories,
                dimension: 2,
                inRange: {
                    color: groupColors //['#d94e5d','#eac736','#50a3ba']
                },
                outOfRange: {
                    color: ['#ccc'] //['#d94e5d','#eac736','#50a3ba']
                },
                top: 20,
                textStyle: {
                    color: '#fff'
                },
                realtime: false
            }, {
                show: false,
                dimension: 3,
                max: 1000,
                inRange: {
                    colorLightness: [0.15, 0.6]
                }
            }],
            series: [
                {
                    zlevel: 1,
                    name: 'nutrients',
                    type: 'scatter',
                    data: data.map(function (item, idx) {
                        return [item[2], item[3], item[1], idx];
                    }),
                    animationThreshold: 5000,
                    progressiveThreshold: 5000
                }
            ],
            animationEasingUpdate: 'cubicInOut',
            animationDurationUpdate: 2000
        };
    }

    var fieldNames = schema.map(function (item) {
        return item.name;
    }).slice(2);

    app.config = {
        xAxis: 'protein',
        yAxis: 'calcium',
        onChange: function () {
            if (data) {
                myChart.setOption({
                    xAxis: {
                        name: app.config.xAxis
                    },
                    yAxis: {
                        name: app.config.yAxis
                    },
                    series: {
                        data: data.map(function (item, idx) {
                            return [
                                item[fieldIndices[app.config.xAxis]],
                                item[fieldIndices[app.config.yAxis]],
                                item[1],
                                idx
                            ];
                        })
                    }
                });
            }
        }
    };

    app.configParameters = {
        xAxis: {
            options: fieldNames
        },
        yAxis: {
            options: fieldNames
        }
    };
    if (option && typeof option === "object") {
        myChart.setOption(option, true);
    }
</script>
</body>
</html>
```

### Other comments [其他信息]

这是我在webstorm里运行的结果：
![17 06 04 1112_1](https://cloud.githubusercontent.com/assets/29170406/26758636/b034f622-4916-11e7-9077-b316713db75a.png)
想把它变成echarts里的结果：

![17 06 04 1113_2](https://cloud.githubusercontent.com/assets/29170406/26758655/35c7654a-4917-11e7-9f06-36dee31b74ad.png)

**Comment by pissang** [comment]
这个是例子里的配置代码，不是 echarts 中的，见 https://github.com/dataarts/dat.gui

**Comment by cehceh1** [comment]
请问下如果要在Scatter Nutrients里加入dat.gui的代码该怎么加啊？还请大神指导

**Comment by mwj2011** [comment]
请问下大神，这个问题解决了吗，应该怎么来实现呀？

**Comment by iamsunny999** [comment]
官方例子缺了一段代码，就是dat.gui的设置代码，首先下载、引入这个组件
<script type="text/javascript" src="js/dat.gui.min.js"></script> ，然后在javascript（就是echarts生成图形代码段）中增加如下代码：
app.config = {
    xAxis: 'protein',
    yAxis: 'calcium',
    onChange: function () {
        console.log("调用改变");
        if (data) {
            myChart.setOption({
                xAxis: {
                    name: app.config.xAxis
                },
                yAxis: {
                    name: app.config.yAxis
                },
                series: {
                    data: data.map(function (item, idx) {
                        return [
                            item[fieldIndices[app.config.xAxis]],
                            item[fieldIndices[app.config.yAxis]],
                            item[1],
                            idx
                        ];
                    })
                }
            });
        }
    }
};

app.configParameters = {
    xAxis: {
        options: fieldNames
    },
    yAxis: {
        options: fieldNames
    }
};

  //var gui = new dat.GUI();  

        var gui;
        if (gui) {
            $(gui.domElement).remove();
            gui.destroy();
            gui = null;
        } 
        gui = new dat.GUI(); 
        if (app.config) {
            /*gui = new dat.GUI({
                autoPlace: false
            });*/
            $(gui.domElement).css({  
                //position: 'absolute',//应用后就看不到close controls，出现了滚动条
                right: 5,
                top: 0,
                zIndex: 1000
            });

            //$('.right-container').append(gui.domElement);
            $('.container').append(gui.domElement);

            var configParameters = app.configParameters || {};
            for (var name in app.config) {
                var value = app.config[name];
                if (name !== 'onChange' && name !== 'onFinishChange') {
                    var isColor = false;
                    // var value = obj;
                    var controller;
                    if (configParameters[name]) {
                        if (configParameters[name].options) {
                            controller = gui.add(app.config, name, configParameters[name].options);
                        }
                        else if (configParameters[name].min != null) {
                            controller = gui.add(app.config, name, configParameters[name].min, configParameters[name].max);
                        }
                    }
                    if (typeof obj === 'string') {
                        try {
                            var colorArr = echarts.color.parse(value);
                            isColor = !!colorArr;
                            if (isColor) {
                                value = echarts.color.stringify(colorArr, 'rgba');
                            }
                        }
                        catch (e) {}
                    }
                    if (!controller) {
                        controller = gui[isColor ? 'addColor' : 'add'](app.config, name);
                    }
                    app.config.onChange && controller.onChange(app.config.onChange);
                    app.config.onFinishChange && controller.onFinishChange(app.config.onFinishChange);
                }
            }
        } // if (app.config) 
另外：原官方例子中的json文件我也整理了，下面这一段用到，需要的可以给我发邮件，我把这段官方程序和json文件发给你！
 $.get('../data/nutrients.json', function (originData) {
    data = normalizeData($.parseJSON(originData)).slice(0, 1000);
    myChart.setOption(option = getOption(data));
});

**Comment by iamsunny999** [comment]
我的邮件imasunny999@163.com

**Comment by shushu-leng** [comment]
@iamsunny999 能否把例子中的json给我发一份？ 感激！ lrb499537997@gmail.com

**Comment by dwang888** [comment]
@iamsunny999 , can you please send me a copy to: dwang888@outlook.com  Thanks a lot!

**Comment by feichaohao** [comment]
@iamsunny999 , can you please send me a copy to: 1649932925@qq.com Thanks a lot!
