### ISSUE TITLE
echarts能添加自定义图标吗

### ISSUE THREAD

**Issue by semdy** [ecomfe/echarts#5906]
### One-line summary [问题简述]

echarts能在柱状图上添加自定义图标吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.3.2
+ Browser version [浏览器类型和版本]:56
+ OS Version [操作系统类型和版本]:windows 10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![](http://edm.mcake.com/shuxy/2017/fatherDay2017/images/chart.jpg)

**Comment by pissang** [comment]
用自定义 symbol 的散点图
