### ISSUE TITLE
是否有方法实现折线图的3D视图，如下图？

### ISSUE THREAD

**Issue by Alanrah** [ecomfe/echarts#5913]
### One-line summary [问题简述]
公司需要实现折线图的3D展示，不知道echarts能否实现？现有的charts我大都调研了一下，有3D饼图和3D柱状图，但是没有3D折线图。如果自己画，求指点思路，谢谢。
![_20170602113930](https://cloud.githubusercontent.com/assets/19640807/26786201/5b1cf720-4a38-11e7-8879-c983f919a448.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6
+ Browser version [浏览器类型和版本]:chrome最新
+ OS Version [操作系统类型和版本]:windows10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Alanrah** [comment]
请问一下可以实现吗？

**Comment by pissang** [comment]
试试用 css 的 3d transform

**Comment by zoe-cjf** [comment]
3d饼图在哪里，有链接吗，有线上代码吗

**Comment by Alanrah** [comment]
有的  但是 icharts amcharts，其他开源库有，但是echarts没有
http://www.ichartjs.com/samples/index.html?page=pie3d_02.html&pageno=7 
https://www.amcharts.com/demos/3d-pie-chart/



vzhang_yaru@163.com
 
发件人： zoe
发送时间： 2017-10-19 11:25
收件人： ecomfe/echarts
抄送： Alanrah; Author
主题： Re: [ecomfe/echarts] 是否有方法实现折线图的3D视图，如下图？ (#5913)
3d饼图在哪里，有链接吗，有线上代码吗
―
