### ISSUE TITLE
Echarts地图轨迹能不能实现多个轨迹

### ISSUE THREAD

**Issue by lishuai1021** [ecomfe/echarts#5914]
### One-line summary [问题简述]
现在只实现了一个轨迹，点（effectScatter）之间用线line连接。
![qq 20170606101451](https://cloud.githubusercontent.com/assets/21034631/26810950/4e8e8294-4aa1-11e7-9e17-0015b44ca295.jpg)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![_2017-06-06t02-05-36 497z](https://cloud.githubusercontent.com/assets/21034631/26811045/ebeed354-4aa1-11e7-84ee-2ece09ecf3ad.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=lines-bmap-bus
