### ISSUE TITLE
echarts离线版的地图与实际距离的换算公式是什么？怎么根据zoom和实际距离算出在途中展示的大小？

### ISSUE THREAD

**Issue by pengpenghan** [ecomfe/echarts#5916]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
map 使用的是 GeoJSON，绘制就是把 GeoJSON fit 到屏幕大小

**Comment by pengpenghan** [comment]
我现在的问题是把一个实际距离的数据展示到地图中去，比如200km的圆形图放到地图上应该显示什么样的尺寸。。
