### ISSUE TITLE
echarts能否显示数据表

### ISSUE THREAD

**Issue by liujancy** [ecomfe/echarts#5918]
[
![08e40f74-192a-11e6-90a7-db09bc19676c](https://cloud.githubusercontent.com/assets/20906916/26821398/ded270fe-4ad8-11e7-9358-b802dcbf6a47.png)
](url)

**Comment by liujancy** [comment]
网上查了很多资料，没有发现echarts能够显示数据表，不知道有没有遇到类似的需求？

**Comment by pissang** [comment]
短期内没有这个计划
