### ISSUE TITLE
There is a chart instance already initialized on the dom

### ISSUE THREAD

**Issue by wbl1217** [ecomfe/echarts#5920]
### One-line summary [问题简述]

在VUE里用了多入口，但是按需引入echarts的，为什么会报There is a chart instance already initialized on the dom.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
dom 已经实例化过了

**Comment by iamsabbath** [comment]
请问dispose应该在什么时间点调用？我需要在一个<ion-list></ion-list>里画多个图表。

**Comment by passos** [comment]
同问，如果要在一个页面上渲染多个图标，该怎么 init 呢？

**Comment by beibeijerry** [comment]
这个怎么解决的

**Comment by SunYuqing** [comment]
楼上有找到解决方法吗？分享一下呗

**Comment by FishYu99** [comment]
參考API文檔
http://echarts.baidu.com/api.html#echarts.dispose

`
// DOM
let main = document.getElementById("main");

// 判斷是否已有實例
let existInstance = echarts.getInstanceByDom(main);
if (existInstance) {
    if (true) {
        echarts.dispose(chartStudent);
    }
}

// 初始化&配置設定
let mychart = echarts.init(main);
mychar.setOption({....});
`
