### ISSUE TITLE
charts 扩展地图 与echarts 折线图联动

### ISSUE THREAD

**Issue by hgfjxn** [ecomfe/echarts#5925]
### One-line summary [问题简述]

您好！现在想实现一个echarts百度扩展地图与折线图的联动，就是点击地图上面的点，展示这个点相关数据的折线图。请问有没有方法和思路可以给一点帮助？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts2.2.7
+ Browser version [浏览器类型和版本]:chrome 58
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
建议监听事件后重新 setOption
