### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by Eingx** [ecomfe/echarts#5927]
Windows Script Host

### One-line summary [问题简述]
行：11
字符：16093
错误：缺少‘）’
代码：800A03EE
源：Microsoft JScript编译错误
【这编程方面我比较白痴，希望能通俗简单的解释下】

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:Windows10

### Expected behaviour [期望结果]
我只要能正常使用图表

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
如果平时不写程序的话建议在 http://gallery.echartsjs.com/explore.html 上使用。或者去学习一点基础的前端开发知识
