### ISSUE TITLE
画箱线图我已经有了最大值，最小值以及四分位点的值，请问用echarts怎么画不出来？

### ISSUE THREAD

**Issue by JiaWenqi** [ecomfe/echarts#5928]
http://echarts.baidu.com/demo.html#boxplot-light-velocity
![1](https://user-images.githubusercontent.com/11871338/26859633-ad3c11f6-4b6b-11e7-892e-548856ba6bba.png)

**Comment by 100pah** [comment]
```js
var 处理后的数据 = prepareBoxplotData(这里是原始数据）
```

如果你直接有了 `[0,1,2,5,13]`，直接
```js
var data = [[0,1,2,5,13]];
```
就可以了。

**Comment by JiaWenqi** [comment]
你好，非常感谢你的回答，但是我还有一个问题是写成这样后，结果为什么有负值？？？Q1是-5是为什么？最大值，最小值以及四分位点的值和我给的值不对应啊
