### ISSUE TITLE
能否尽快添加支持typescript 的描述文件

### ISSUE THREAD

**Issue by mokeyish** [ecomfe/echarts#5931]
最近自己在看文档写对应的ts描述文件，难免有疏漏，如果官方出，就更好了。

**Comment by pissang** [comment]
这里有一份 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/echarts/index.d.ts

**Comment by mokeyish** [comment]
@pissang 这里描述的不全面，比如echarts事件返回的那些

**Comment by bondBo** [comment]
这份文件写的太垃圾了，等于没写
