### ISSUE TITLE
如何实现多组图例，或者实现所需的效果即可

### ISSUE THREAD

**Issue by VitoWong** [ecomfe/echarts#5936]
### One-line summary [问题简述]
我想实现一些“非常规的附加”图例

### Version & Environment [版本及环境]
+ ECharts 3
+ Chrome

### Expected behaviour [期望结果]
我有一个关系图，默认的图例用不同颜色来表示不同分组，点击可以关闭（这是已有的，我很满意这个功能）

然后问题来了，我还想增加一些“非常规”的图例：
1、不同形状（我自定两个，比如说圆形和正方形）代表不同意义
2、关系连线的箭头表示依赖关系，并且实线和虚线代表不同。

就是说我能否自定义一些只是展示（不图关联关系）的图标加到图上，就是实现下图红框里面的内容，谢谢！！！

![image](https://user-images.githubusercontent.com/29249733/26871619-6b652548-4ba6-11e7-93a1-5c18102901fc.png)

**Comment by pissang** [comment]
建议自己用 dom 实现
