### ISSUE TITLE
在配合swiper.js 使用时 图表无法显示问题

### ISSUE THREAD

**Issue by itDjango** [ecomfe/echarts#5937]
### One-line summary [问题简述]
echars3.0版本  配合swiper 使用时 

图表无法显示。
但是backgroundColor 可以显示。

 用swiper做的是  URL:   http://www.swiper.com.cn/demo/pcpage/    这个效果
把对应的图表放到每个单页面，图表就无法显示。backgroundColor 可以显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by itDjango** [comment]
求大神解答一下 ，这是echarts的bug吗？

**Comment by pissang** [comment]
不知道什么原因，但是应该不是 echarts 的 bug，看下是不是 init 的时候 dom 没法获取宽高

**Comment by itDjango** [comment]
问题解决了 
swiper 设置 loop=true, 就会出问题

改成loop=false  就可以了。

具体原因还不确定因为什么，但是高度应该是可以获取的，因为echarts的backgroundColor是可以展现的，只是图表没有展现。

**Comment by LoveBabyForeve** [comment]
loop=true的时候 怎么解决这个问题？？？

**Comment by xianghongai** [comment]
既不是echarts的问题，也不是swiper的问题。

是你逻辑问题。

+ 首先，你要构建dom，先生效swiper效果，这样页面有了最后的dom；

+ 然后，你配置好echarts的option对象，这样为填充图形数据做准备；

+ 再然后，通过`document.getElementsByClassName('chartLayer');`获取页面所有要注入数据的dom对象，用官方`id`会有bug，`id`具有唯一性，现在页面loop有了多个相同`id`；

+ 最后，遍历dom对象，用`echarts.init`实例化。

---

demo如下:

```javascript
var myChart= document.getElementsByClassName('chartLayer');
var myChartInit=[];
var option={ ... };
for (let i = 0, len= myChart.length; i < len; i++) {
    myChartInit[i] = echarts.init(myChart[i]);
    myChartInit[i].setOption(option);
}
```
