### ISSUE TITLE
如何忽略显示离群点

### ISSUE THREAD

**Issue by pidongqianqian** [ecomfe/echarts#5941]
### One-line summary [问题简述]

![r yfpkz _gw xrb vmf o](https://user-images.githubusercontent.com/20850873/26910012-025e3b66-4c37-11e7-8443-ba955360956d.png)
有个别远超出范围的点数据，导致正常数据成为几乎为直线

### Expected behaviour [期望结果]
其实就是想问问，有没有剔除毛刺数据的功能，不显示那个远超出当前规律范围的点，但是不能简单通过设置Y轴或X轴范围来实现，因为数据曲线可能有一个总体走势，以后的数据不清楚会到达一个什么样的值，也许会很大。如果不能通过设置echarts实现，我再另寻它法吧

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 不负责数据的处理清洗，建议寻找其他更合适的工具先清洗数据后再用 echarts 展示
