### ISSUE TITLE
地图数值显示bug

### ISSUE THREAD

**Issue by imew** [ecomfe/echarts#5948]
http://echarts.baidu.com/demo.html#scatter-map

在官方实例中，拖动标尺范围在0-11，未显示海门的值，而显示南通的值。
![image](https://user-images.githubusercontent.com/4327446/26915964-e36d3fb2-4c5a-11e7-87f5-38a10fc895e0.png)

![image](https://user-images.githubusercontent.com/4327446/26915983-fd7deb22-4c5a-11e7-959a-024ef43bdf03.png)

**Comment by pissang** [comment]
这个不是 bug，是因为超出范围的只是设成全透明了，图形还能正常的用 tooltip 交互

**Comment by imew** [comment]
海门值为9没有超出范围呀，为什么地图上不显示海门的，而是显示南通的呢？
