### ISSUE TITLE
饼图数据多时的一个问题

### ISSUE THREAD

**Issue by wangbingqian110** [ecomfe/echarts#5952]
### One-line summary [问题简述]
我调用了饼图的接口，里面大约有一百条数据，然后显示的时候出现了如下图所示的情况，请问有没有解决办法？

![3n4a b q 02qihcwpz 0ub](https://user-images.githubusercontent.com/22422711/26921362-645d838a-4c6e-11e7-9b4b-08c43fd6ae99.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echarts3.0+
+ Browser version [浏览器类型和版本]:谷歌浏览器 版本 58.0.3029.110 (64-bit)
+ OS Version [操作系统类型和版本]:Windows10 专业版

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不要这么多数据

**Comment by wangbingqian110** [comment]
就是饼图在数据很多的情况下就不能用了吗？

**Comment by pissang** [comment]
http://gallery.echartsjs.com/  建一个可以复现的例子？
