### ISSUE TITLE
新版本无法多次init主题

### ISSUE THREAD

**Issue by apexglory** [ecomfe/echarts#5953]
### One-line summary [问题简述]

现在只有第一次init的时候theme设置能够生效，之前的版本可以动态设置主题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.1
+ Browser version [浏览器类型和版本]:chromium
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
看控制台错误提示，先 dispose 再重新 init
