### ISSUE TITLE
echart2 力导向图 link链接线如何设置有的是有箭头样式，有的是没箭头样式（只是一条连线）

### ISSUE THREAD

**Issue by 273853065** [ecomfe/echarts#5954]
echart2 力导向图 link链接线如何设置有的有箭头，有的没箭头
力导向图中，linkSymbol只能设置全局的连线有无箭头，但是我想要有的连线有箭头，有的没有，这个怎么设置
感谢

**Comment by pissang** [comment]
建议用 echarts 的关系图
