### ISSUE TITLE
Tooltip is cut by parent container

### ISSUE THREAD

**Issue by eskimoblood** [ecomfe/echarts#5955]
### One-line summary [问题简述]
At the moment the tooltip is placed after the chart in the DOM. In our flex box layout the tooltip is cut when it comes to close to left border of the charts parent container.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.1
+ Browser version [浏览器类型和版本]: chrome 58.0.3029.110
+ OS Version [操作系统类型和版本]: mac osx

### Expected behaviour [期望结果]

Tooltip is always visible. Normally this is solved by adding the tooltip to the end of the document body so it will lay over all elements

**Comment by pissang** [comment]
Perhaps this property will be helpful https://ecomfe.github.io/echarts-doc/public/en/option.html#tooltip.confine

**Comment by eskimoblood** [comment]
Thanks that it

**Comment by dtaub** [comment]
@pissang That only confines the tooltip to be within the canvas, but for a large tooltip that obscures the chart.
Many libraries allow passing a DOM element to put the tooltip in (often the body). Is there a way to do that in echarts?

**Comment by anentropic** [comment]
re the previous comment, you can add `appendTo: 'body'` to the tooltip properties

https://echarts.apache.org/en/option.html#tooltip.appendTo
