### ISSUE TITLE
官方示例代码经过JS混淆被提交

### ISSUE THREAD

**Issue by sjsdfg** [ecomfe/echarts#5959]
### One-line summary [问题简述]
在ECharts Gallery里面对于新的特性
ECharts-GL的示例里面充斥着大量的经过JS混淆之后被提交的代码
例如：
http://gallery.echartsjs.com/editor.html?c=xBJXwhy8Rx
http://gallery.echartsjs.com/editor.html?c=xrJdvs1oRx
等等。

如果这些代码有是官方人员提交的，希望能您能通知该人员把源码重新提交。
希望ECharts越办越好

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个是其他人提交的示例代码
