### ISSUE TITLE
echarts 柱状图如何在每个柱子的底部加文字？

### ISSUE THREAD

**Issue by joy-yi0905** [ecomfe/echarts#5962]
### One-line summary [问题简述]

![](https://thumbnail0.baidupcs.com/thumbnail/d662e6f28889d489687ab61ed97660a2?fid=3098163580-250528-1125481797455647&time=1496995200&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-S73D0gnsLAoXmjIn9mN9FOgzsyE%3d&expires=8h&chkbd=0&chkv=0&dp-logid=3703135245264426816&dp-callid=0&size=c1440_u900&quality=90&vuk=3098163580&ft=image)

如图，这是 echarts 生成的横向柱状图。柱子右边的数字是 `label`，默认情况下，各种类名都是通过 `legend` 放在一起。但突然来了个奇葩需求，需要在柱状图里的每个柱子底部加一个对应的类名。请问有没有解决方案？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.2.3
+ Browser version [浏览器类型和版本]: chrome57
+ OS Version [操作系统类型和版本]: windows7

### Expected behaviour [期望结果]

![](https://thumbnail0.baidupcs.com/thumbnail/d662e6f28889d489687ab61ed97660a2?fid=3098163580-250528-1125481797455647&time=1496995200&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-S73D0gnsLAoXmjIn9mN9FOgzsyE%3d&expires=8h&chkbd=0&chkv=0&dp-logid=3703135245264426816&dp-callid=0&size=c1440_u900&quality=90&vuk=3098163580&ft=image)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没有简单的办法做到
