### ISSUE TITLE
Is there a way to fix specific nodes in force graph 

### ISSUE THREAD

**Issue by eskimoblood** [ecomfe/echarts#5966]
There is a way to set the initial position of nodes in a force graph but is there a way to have this node stay at this position?

**Comment by biolee** [comment]
you use custom physical engine(eg d3) and use echarts [custom series](http://echarts.baidu.com/option.html#series-custom), then you can reuse a lot echarts utility,(like tooltip...)

but [custom series](http://echarts.baidu.com/option.html#series-custom) can't corresponding to mouse event right now, see  https://github.com/ecomfe/echarts/issues/5965

**Comment by pissang** [comment]
@biolee Great thought! Actually each node can have `fixed` property to stick it's position. But integrate d3 layout and custom series will be much more flexible. We will enhance custom series in the later version.

**Comment by eskimoblood** [comment]
@pissang I tried the `fixed` property but it has no effect, is there an example to see how it should work?

**Comment by pissang** [comment]
@eskimoblood Uhhh sorry it's a bug.

**Comment by eskimoblood** [comment]
when will this fix be available in npm?

**Comment by 100pah** [comment]
We have planned to publish the next version at the next week, including this bug fix.

**Comment by Ovilia** [comment]
@eskimoblood It's fixed now. Try it out! :)

**Comment by ys278099744** [comment]
i want to drag one node to somewhere and stay ,but now it always rebound to its init place，this operation is very useful，can you come true？中文版：我想拖动一个点到随便一个位置，但是这个点老是弹回去，有没有办法让他拖到哪，就固定在哪，这个操作很常见，网上查了一下，很多人有这种需求，希望能够解决

**Comment by ys278099744** [comment]
这个fixed属性，为什么设置后报错找不到这个属性呢？我用的也是4.0版本的echart啊
