### ISSUE TITLE
echarts 谷歌浏览器 异步请求的option中 X/Y轴和图例文字重影

### ISSUE THREAD

**Issue by ycl2014** [ecomfe/echarts#5968]
### One-line summary [问题简述]
我是用循环ajax请求多个图表的option 然后谷歌浏览器 的X,Y轴上的文字 和图例的文字 会出现重影（2份数据，我在option 上修改文字的颜色为红色，那么底下还有一个灰色的文字，）

![image](https://user-images.githubusercontent.com/8383602/27001190-472ed136-4df6-11e7-96df-7fadd1e95ff4.png)

+ ECharts version [ECharts 版本]: 3.4.0
+ Browser version [浏览器类型和版本]:谷歌浏览器58.0.3029.110
+ OS Version [操作系统类型和版本]:win7
### ECharts option [ECharts配置项]

**Comment by suifengfengye** [comment]
遇到了同样的问题，怎么解决的呢？
