### ISSUE TITLE
Custom Series with Custom Layouts

### ISSUE THREAD

**Issue by psumstr** [ecomfe/echarts#5970]
### One-line summary [问题简述]
How to use a custom series with a custom layout?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
I would like to use custom layouts like: https://github.com/d3/d3-hierarchy#pack to create a circle packing visualizations. From the available examples, I couldn't tell what would I need to set for the coordinate system. Is there an example you can point me to that could clear things up or is this not yet possible to do with the custom series?

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
Integrating d3 layout and `echarts custom series` is a good idea.
Check this example please: <http://gallery.echartsjs.com/editor.html?c=xHyzR8UUNb&v=2>

**Comment by psumstr** [comment]
@100pah Thanks for the example. Hopefully, you'll add soon a way to specify no coordinate system (https://github.com/ecomfe/echarts/commit/a53bbc304025ee07fbeda3617e902a0b0283cac0) to avoid having to set xAxis and yAxis option properties. The last thing I am looking for is a way to do animations for the graphic elements in the `renderItem` function. I have some D3 charts that I want to replace with Echarts, but I'd miss the animations on those. I already opened:
https://github.com/ecomfe/echarts/issues/5988

Ideally, I'd have a way to set the animation for new/enter, updating, and nodes removed. I see the there's a data differ utility that might be helpful: https://github.com/ecomfe/echarts/blob/master/src/data/DataDiffer.js

**Comment by qpxtWhite** [comment]
@jonavila how to use "no coordinate system"? Any example?
