### ISSUE TITLE
地图可以做出以下动效吗

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#5979]
![image](https://user-images.githubusercontent.com/22878190/27026256-bb583e68-4f8f-11e7-8d76-4541abb79417.png)

### One-line summary [问题简述]
如上面截图， 当页面刚加载出来时，实时的数据再在地图数据点上弹出再慢慢消失？？ 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你可以自己用 dom 实现，定位用 convertToPixel
