### ISSUE TITLE
graph当node很多的时候丢数据了

### ISSUE THREAD

**Issue by boboChina** [ecomfe/echarts#5989]
### One-line summary [问题简述]

graph当node很多的时候丢数据了
 // Filter update
```js
	    graphProto.update = function () {
	        var data = this.data;
	        var edgeData = this.edgeData;
	        var nodes = this.nodes;
	        var edges = this.edges;

	        for (var i = 0, len = nodes.length; i < len; i++) {
	            nodes[i].dataIndex = -1;
	        }
	        for (var i = 0, len = data.count(); i < len; i++) {
	            nodes[data.getRawIndex(i)].dataIndex = i;
	        }
```
nodes.length 274个
 data.count() 774个
实际上我传了774个node
到第二个循环的时候就没有dataindex所以设置报错了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新的3.x
+ Browser version [浏览器类型和版本]:chrom
+ OS Version [操作系统类型和版本]:mac

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://gallery.echartsjs.com/ 上传一个可以复现的例子？

**Comment by boboChina** [comment]
thx，已经解决了，node如果有重复的name属性就会有这个问题，自己去重就解决了
