### ISSUE TITLE
文档小错误

### ISSUE THREAD

**Issue by yszou** [ecomfe/echarts#5990]
http://echarts.baidu.com/option.html#xAxis

> 直角坐标系 grid 中的 x 轴，一般情况下单个 grid 组件最多只能放左右两个 x 轴 ...

![image](https://user-images.githubusercontent.com/530513/27114325-5e089ad4-50f5-11e7-93ad-641da76ef38e.png)

这里不应该是「左右」，应该是「上下」。

「直角坐标系 grid 中的 x 轴，一般情况下单个 grid 组件最多只能放 `上下` 两个 x 轴」

**Comment by pissang** [comment]
谢谢反馈
