### ISSUE TITLE
1.c5933c.js:formatted:4958 Uncaught (in promise) Error: Component series.line not exists. Load it first.

### ISSUE THREAD

**Issue by zhengtulym1991** [ecomfe/echarts#5992]
本地是正常的，但一上到线上就报错：
![default](https://user-images.githubusercontent.com/13768025/27121783-38f59096-511b-11e7-9b1a-05147957bf54.PNG)

而我确实是引入了相关模块：
`import ECharts from 'vue-echarts/components/ECharts.vue'`
`import 'echarts/lib/component/tooltip'`
`import 'echarts/lib/chart/line'`

此处有更详细的描述：https://segmentfault.com/q/1010000009778869

**Comment by pissang** [comment]
看一下是否因为版本原因导致打包了两个 echarts 模块

**Comment by zhengtulym1991** [comment]
我把node_modules文件夹整个删了，重新npm i后正常了，谢谢@pissang

**Comment by zhengtulym1991** [comment]
另外问一下，为什么会出现这种原因呢？ @pissang

**Comment by pissang** [comment]
两个项目依赖了不同的 echarts 版本吧

**Comment by michael-tang0823** [comment]
resolved by import like below
import "vue-echarts/node_modules/echarts/lib/chart/line";

**Comment by BenJ-Q** [comment]
现在出现了这个问题，怎么办呢？大佬们

**Comment by BenJ-Q** [comment]
npm i  没有用

**Comment by BenJ-Q** [comment]
@
