### ISSUE TITLE
echarts3官网页面跳转错误

### ISSUE THREAD

**Issue by xiaoyuanzia** [ecomfe/echarts#5995]
### echarts3官网页面跳转错误：
1.从“工具--地图数据在线工具”，跳转到“实例-官方实例”时出现404页面；
2.从“工具--主题构建工具”，跳转到“实例-官方实例”时出现404页面。
 [问题简述]

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
已修复
