### ISSUE TITLE
折线图，x轴上有一点存在一个日期坐标，但是对应的值为null（但不想让折线图存在断点），怎么让其显示出连续的折线图？

### ISSUE THREAD

**Issue by chenxia123** [ecomfe/echarts#5998]
### One-line summary [问题简述]

折线图，x轴上有一点存在一个日期坐标，但是对应的值为null（但不想让折线图存在断点），怎么让其显示出连续的折线图？

可以做到画折现图时直接略过这个为null的点吗？但是x轴上仍需要显示那点的日期坐标？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-line.connectNulls
