### ISSUE TITLE
关系图-series[i]-graph.name 不可重复的问题

### ISSUE THREAD

**Issue by 903742456** [ecomfe/echarts#5999]
### One-line summary [问题简述]

echarts 关系图中如果 series[i]-graph.name 出现重复的就会报dataIndex的相关错误，下面series[i]-graph.links[i]中的source和target可以指定用索引，有些情况下我们需要name重复。如果echarts不能做到name重复，请在series[i]-graph.name 中明确指出不可重复，这样会造成开发者的困扰。谢谢

### Version & Environment [版本及环境]
+ ECharts version [3.6.2]:
+ Browser version [Chrome  57.0.2950.5 m]:
+ OS Version [Windows10 home]:

### Expected behaviour [期望结果]
echarts 是否可以解决，不能的话请在name中标识

### ECharts option [ECharts配置项]
option = {
//                    title : {
//                        text : 'barra',
//                        left : 'center'
//                    },
                    tooltip: {
                        formatter : function(a,b,c){
                            if(a.dataType == 'edge'){
                                return ;
                            }else{
                                return a.value + ' : ' +a.name
                            }
                        }
                    },
                    animationDurationUpdate: 1500,    //动画效果
                    animationEasingUpdate: 'quinticInOut',
                    series : [
                        {
                        type: 'graph',
                        layout: 'none',
                        symbolSize: 80,
                        roam: false,
                        label: {
                            normal: {
                                show: true
                            }
                        },
                        edgeSymbol: ['circle', 'arrow'],
                        edgeSymbolSize: [4, 10],
                        edgeLabel: {
                            normal: {
                                textStyle: {
                                    fontSize: 20
                                }
                            }
                        },
                        data: [
                            {
                              "name": "0.9523",
                              "value": "总收益",
                              "x": 625,
                              "y": 75,
                              label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        console.log(a)
                                        return '企业规模';
                                    }
                                }
                            }
                            },
                            {
                              "name": "-79.5619",
                              "value": "Beta收益",
                              "x": 400,
                              "y": 200
                            },
                            {
                              "name": "80.5142",
                              "value": "Alpha收益",
                              "x": 800,
                              "y": 200
                            },
                            {
                              "name": "-30.2074",
                              "value": "相对低估性",
                              "x": 560,
                              "y": 350
                            },
                            {
                              "name": "18.8963",
                              "value": "企业规模",
                              "x": 640,
                              "y": 350
                            },
                            {
                              "name": "17.4160",
                              "value": "BETA",
                              "x": 720,
                              "y": 350
                            },
                            {
                              "name": "1.6449",
                              "value": "波动性",
                              "x": 800,
                              "y": 350
                            },
                            {
                              "name": "10.9172",
                              "value": "投资成果",
                              "x": 880,
                              "y": 350
                            },
                            {
                              "name": "29",
                              "value": "宏观经济",
                              "x": 960,
                              "y": 350
                            },
                            {
                              "name": "29",
                              "value": "杠杆性",
                              "x": 1040,
                              "y": 350
                            }
                          ],
                        // links: [],
                        links: [{
                            source: 0,
                            target: 2,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return 'Alpha收益';
                                    }
                                }
                            },
                        },{
                            source: 0,
                            target: 1,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return 'Beta收益';
                                    }
                                }
                            },
                        },{
                            source: 2,
                            target: 3,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return '相对低估性';
                                    },
                                    textStyle : {
                                        fontSize : 18
                                    }
                                }
                            }
                        },{
                            source: 2,
                            target: 4,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return '企业规模';
                                    },
                                    textStyle : {
                                        fontSize : 18
                                    }
                                }
                            }
                        },{
                            source: 2,
                            target: 5,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return 'BETA';
                                    },
                                    textStyle : {
                                        fontSize : 18
                                    }
                                }
                            }
                        },{
                            source: 2,
                            target: 6,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return '波动性';
                                    },
                                    textStyle : {
                                        fontSize : 18
                                    }
                                }
                            }
                        },{
                            source: 2,
                            target: 7,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return '投资成果';
                                    },
                                    textStyle : {
                                        fontSize : 18
                                    }
                                }
                            }
                        },{
                            source: 2,
                            target: 8,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return '宏观经济';
                                    },
                                    textStyle : {
                                        fontSize : 18
                                    }
                                }
                            }
                        },{
                            source: 2,
                            target: 9,
                            label: {
                                normal: {
                                    show: true,
                                    formatter :function(a){
                                        return '杠杆性';
                                    },
                                    textStyle : {
                                        fontSize : 18
                                    }
                                }
                            }
                        }],
                        lineStyle: {
                            normal: {
                                opacity: 0.9,
                                width: 2,
                                curveness: 0
                            }
                        }
                    }
                ]
            };

**Comment by pissang** [comment]
最新的文档已经说明
