### ISSUE TITLE
series.tree in ECharts 3. Alternative?

### ISSUE THREAD

**Issue by Filini** [ecomfe/echarts#6000]
As far as I can see, series.tree from ECharts 2 was removed in ECharts 3.
Is there a way to create a nodes tree in ECharts 3?
I could not find any option in series.treemap or series.graph to create a simple tree with nodes.
Is the only way positioning the nodes of a graph manually, or am I missing something in the options API documentation?

Thanks in advance for the help.

+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: All
+ OS Version [操作系统类型和版本]: All

**Comment by deqingli** [comment]
Recently we have been in the development of the series.tree, and some features are not perfect, we will release it  as soon as possible. Thank you !
