### ISSUE TITLE
zrender最新版本toDataURL()不能使用了吗？

### ISSUE THREAD

**Issue by tonyhao01** [ecomfe/echarts#6003]
### One-line summary [问题简述]
zr.toDataURL();
提示：
Uncaught TypeError: bq.toDataURL is not a function

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
`zr.painter,getRenderedCanvas().toDataURL()`
