### ISSUE TITLE
正负呈现

### ISSUE THREAD

**Issue by yanlililu** [ecomfe/echarts#6007]
### One-line summary [问题简述]

能根据平均值进行正负呈现吗？超过平均值的是正常的柱状图，低于平均值的反向呈现

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by yanlililu** [comment]
@leeight @cnberg @firede @chriswong @firedfox @

**Comment by pissang** [comment]
你可以通过修改数据然后配合 formatter 实现
