### ISSUE TITLE
Graph中的EdgeLabel样式个性化

### ISSUE THREAD

**Issue by lovepp** [ecomfe/echarts#6009]
### One-line summary [问题简述]
[使用Graph时，edgeLabel是否可以定制样式，目前edgeLabel的itemstyle只有fontsize，color等基本样式设置，因为项目需要，edgeLabel除了显示文字外，还需要文字外面有些css样式，比如外面包一个圆形的div等让他更好看。如果基础设置不行，是否可以通过修改echarts源码来简单实现？还望指导！]

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/537555/27221069-dbe67352-52b9-11e7-8bc6-b0af18775635.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没法做到
