### ISSUE TITLE
angular2 中怎么加载echarts的百度地图的插件？

### ISSUE THREAD

**Issue by xushuo** [ecomfe/echarts#6010]
### One-line summary [问题简述]

在html中我可以顺利的加载百度地图出来，但是在angular2中，显示失败，其他的图表显示是成功的。不报错。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请把问题环境，详细的复现方式描述清楚
