### ISSUE TITLE
版本

### ISSUE THREAD

**Issue by niexiaofei1988** [ecomfe/echarts#6017]
### One-line summary [问题简述]

在使用3.5.4版本时,一切正常,更新版本为3.6.1时,控制台会报出There is a chart instance already initialized on the dom,的问题

是不是不能频繁的触发echarts.init

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
嗯不能对一个 dom 初始化多次

**Comment by niexiaofei1988** [comment]
如果是数据变动了,我怎么去重新渲染图表呢

**Comment by pissang** [comment]
setOption 更新

**Comment by liangxiaoxin** [comment]
我是使用vue的，我把init放在mounted之后只有一次init就不会重复init了，再通过获取这个实例，重新setOption就好了
let myChart = echarts.getInstanceByDom(document.getElementById("myChart"));
myChart.setOption()
就好了

**Comment by Maconzhang** [comment]
如果是在v-for里面的使用echart ，我改变数组总是会触发There is a chart instance already initialized on the dom. 这个警告   要等很长时间。
