### ISSUE TITLE
自定义legend图形变形

### ISSUE THREAD

**Issue by sugaE** [ecomfe/echarts#6018]
### One-line summary [问题简述]
series里定义symbol:  'path://xxxx'，改路径图片在legend中显示会被拉伸
http://gallery.echartsjs.com/editor.html?c=xBJsEs2V7b&v=1

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 当前版本及3.4.0
+ Browser version [浏览器类型和版本]:chrome 58.0.3029.110
+ OS Version [操作系统类型和版本]:macos10.12.4

### Expected behaviour [期望结果]
在legend中显示和在图表上的显示一致

### ECharts option [ECharts配置项]
series : [{
symbol:  'path://xxx',
}]

### Other comments [其他信息]
http://gallery.echartsjs.com/editor.html?c=xBJsEs2V7b&v=1
图表中正常的：
<img width="51" alt="wx20170619-105612 2x" src="https://user-images.githubusercontent.com/10446823/27267919-6bfc38de-54de-11e7-958c-944ff272829b.png">
被拉伸的legend：
<img width="87" alt="wx20170619-105556 2x" src="https://user-images.githubusercontent.com/10446823/27267843-ec53b346-54dd-11e7-92d7-11c1f2626bc7.png">

**Comment by pissang** [comment]
设置 itemWidth 和 itemHeight
