### ISSUE TITLE
 echarts 能否实现风场的图？

### ISSUE THREAD

**Issue by randyliu77** [ecomfe/echarts#6019]
echarts 能否实现像https://map.zq12369.com中类似的这种风场的图？ 我们看到热力图是可以的，但风场不知道能否实现。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by biolee** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame+custom series (circle)http://echarts.baidu.com/option.html#series-custom
