### ISSUE TITLE
更新到3.6.2的版本后： 容器大小改变时重绘不起作用。

### ISSUE THREAD

**Issue by losiyo** [ecomfe/echarts#6021]
### One-line summary [问题简述]
更新到3.6.2的版本后： 容器大小改变时不能重绘。
我在容器大小改变时重新 init DOM，然后 setOption,
原来的版本会根据容器大小重绘图表，更新到3.6.2后没有重绘。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:chrome 58.0
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
容器大小改变时重绘函数起作用。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
大小改变时调用 resize 就行了
