### ISSUE TITLE
力导向图的边上的字可以自定义吗？比如给字加背景色，以及放图标？

### ISSUE THREAD

**Issue by dreamyi71** [ecomfe/echarts#6022]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行，只能放文字
