### ISSUE TITLE
3.0 的气泡图 controller 的 symbol 无法自定义

### ISSUE THREAD

**Issue by wm370857724** [ecomfe/echarts#6023]
visualMap: [{
        type:'continuous',
        min: 0,
        max: 400,
        calculable: true,
        // 表示 目标系列 的视觉样式。
        target: {
            inRange: {
                              symbol:"path://M0,28 L18,28 L18,32 L0,32 L0,28 Z M1,33 L18,33 L18,37 L1,37 L1,33 Z M2,38 L18,38 L18,42 L2,42 L2,38 Z M3,43 L18,43 L18,47 L3,47 L3,43 Z M4,48 L18,48 L18,52 L4,52 L4,48 Z M5,53 L18,53 L18,57 L5,57 L5,53 Z M6,58 L18,58 L18,62 L6,62 L6,58 Z M7,63 L18,63 L18,67 L7,67 L7,63 Z M8,68 L18,68 L18,72 L8,72 L8,68 Z M9,73 L18,73 L18,77 L9,77 L9,73 Z M10,78 L18,78 L18,82 L10,82 L10,78 Z M11,83 L18,83 L18,87 L11,87 L11,83 Z M12,88 L18,88 L18,92 L12,92 L12,88 Z M13,93 L18,93 L18,97 L13,97 L13,93 Z M14,98 L18,98 L18,102 L14,102 L14,98 Z M15,103 L18,103 L18,107 L15,107 L15,103 Z M16,108 L18,108 L18,112 L16,112 L16,108 Z M17,113 L18,113 L18,117 L17,117 L17,113 Z",
  color: ['#50a3ba', '#eac736', '#d94e5d']
                // symbolSize: [60, 200]
            }
        },
        // 表示 visualMap-continuous 本身的视觉样式。
        controller: {
            inRange: {
                symbol:"path://M0,28 L18,28 L18,32 L0,32 L0,28 Z M1,33 L18,33 L18,37 L1,37 L1,33 Z M2,38 L18,38 L18,42 L2,42 L2,38 Z M3,43 L18,43 L18,47 L3,47 L3,43 Z M4,48 L18,48 L18,52 L4,52 L4,48 Z M5,53 L18,53 L18,57 L5,57 L5,53 Z M6,58 L18,58 L18,62 L6,62 L6,58 Z M7,63 L18,63 L18,67 L7,67 L7,63 Z M8,68 L18,68 L18,72 L8,72 L8,68 Z M9,73 L18,73 L18,77 L9,77 L9,73 Z M10,78 L18,78 L18,82 L10,82 L10,78 Z M11,83 L18,83 L18,87 L11,87 L11,83 Z M12,88 L18,88 L18,92 L12,92 L12,88 Z M13,93 L18,93 L18,97 L13,97 L13,93 Z M14,98 L18,98 L18,102 L14,102 L14,98 Z M15,103 L18,103 L18,107 L15,107 L15,103 Z M16,108 L18,108 L18,112 L16,112 L16,108 Z M17,113 L18,113 L18,117 L17,117 L17,113 Z",
                // symbolSize: [30, 100]
            }
        },

target的 symbol 可以使用 path://自定义矢量图，controller 的symbol 设置了不起作用

**Comment by pissang** [comment]
controller 手柄暂时没法设置不同的样子
