### ISSUE TITLE
地图数据在线生成工具无法下载全国包含省份轮廓的中国地图

### ISSUE THREAD

**Issue by jamln** [ecomfe/echarts#6025]
### One-line summary [问题简述]

如题, 所有省份和城市, 非压缩版本, 之后无论点击下载 js 或 json格式都没响应.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
chrome 59.0.3071.86
IE 11
FireFox 53.0

+ OS Version [操作系统类型和版本]:
windows7 64位

### Expected behaviour [期望结果]
能够下载包含省份轮廓的非压缩版本的中国地图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
中国地图直接从 http://echarts.baidu.com/download-map.html 下吧

**Comment by jamln** [comment]
谢谢回复.
问题是这里下的是压缩过的版本, 压缩版本使用的是 UTF-8 编码.
我需要的是非压缩的版本,不知为什么定制后下载无响应

**Comment by pissang** [comment]
@jamln 这有非压缩版的 https://github.com/ecomfe/echarts-map-tool/blob/gh-pages/maker/raw/china.json

**Comment by jamln** [comment]
肥肠感谢!!!
