### ISSUE TITLE
折线图（平滑） 自定义各段的颜色

### ISSUE THREAD

**Issue by chaserstrong** [ecomfe/echarts#6027]
### One-line summary [问题简述]

在折线图开发过程中，遇到一个需求：希望能自定义折线的各个区域的颜色。但是似乎我们的echarts api里并没有。 只看到有对折线图做颜色渐变的。请指教。

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=line-sections

**Comment by chaserstrong** [comment]
@pissang  感谢。
