### ISSUE TITLE
effectScatter与setInterval冲突问题

### ISSUE THREAD

**Issue by banshourenbsr** [ecomfe/echarts#6033]
### One-line summary [问题简述]
当使用世界地图中用到散点图时，与自己写的setInterval定时任务冲突，
具体表现一：
       是我写的定时任务没有运行，但是当我关闭浏览器时，我的定时任务触发了-_-；
表现二：
       当我把页面一直打开，等待近20分钟后，我的定时任务开始触发，触发频率越来越快，直到和我设置的定时任务执行时间间隔一样（5s）。

问题猜想，是否散点加载时使其他定时器无效？

### Version & Environment [版本及环境]3.0
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:ie10
+ OS Version [操作系统类型和版本]:window2012

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不会有这种问题，你再看下自己代码中逻辑是否存在问题
