### ISSUE TITLE
时间轴设置min，max后，数据被自动填充为第一个值

### ISSUE THREAD

**Issue by chaserstrong** [ecomfe/echarts#6036]
### One-line summary [问题简述]
横轴为时间轴，纵轴为数值轴。
我的数据时间起始为[21:25-1:55]，然后我把横轴的min设置为21：00，max设置为2：00.
但是我希望我的数据范围内的曲线是不画出来的，而现在似乎是默认按照第一个值作为其他没用值的数据的填充，导致前面是一段直线。请问有办法修改为空嘛？
echarts版本是3.0

### Other comments [其他信息]

![u22r 0u8h e1o y26cadsj](https://user-images.githubusercontent.com/18061322/27363700-a3701714-5668-11e7-9965-d16cd712b3cf.png)

**Comment by pissang** [comment]
在 http://gallery.echartsjs.com/ 建一个例子？

**Comment by chaserstrong** [comment]
@pissang 是我代码的问题。echarts本身是空的。 谢谢
