### ISSUE TITLE
dataZoom cannot be set to stick to values

### ISSUE THREAD

**Issue by ljkania** [ecomfe/echarts#6040]
Hi!

Lately I am working on integrating echarts with our project and we would like to use line plot to stream some values (for example we would like to show plot with currencies value since program was started) that means that we push new values to plots. Also we would like to allow dataZoom but since it works on percentages zoomed data changes - is there any way to tell dataZoom to stick to values/categories instead of percentage interval?

**Comment by 100pah** [comment]
Specify [startValue](https://ecomfe.github.io/echarts-doc/public/en/option.html#dataZoom-slider.startValue) or [endValue](https://ecomfe.github.io/echarts-doc/public/en/option.html#dataZoom-slider.endValue) each time data is updated. It might work for your case I guess.

**Comment by ljkania** [comment]
I've try to do that on dataZoom event ([dataZoom event](https://ecomfe.github.io/echarts-doc/public/en/api.html#events.datazoom)) but it is fired after changing zoom so when I was using slider to do that it was not working correctly since my changes were fighting with events firing by this slider.
