### ISSUE TITLE
自定义toolbar按钮

### ISSUE THREAD

**Issue by hon** [ecomfe/echarts#6043]
### One-line summary [问题简述]

我现在自定义了一个“导出图片”按钮，我想点击这个按钮后实现导出某特图表的功能。
有没有什么方法可以调用。
ps: 我知道可以自定义saveAsImage配置项，但这不是我想要的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  最新版
+ Browser version [浏览器类型和版本]: chrome 最新版
+ OS Version [操作系统类型和版本]: macos sierra

### Expected behaviour [期望结果]
有和toolbar里功能一样的方法可以调用。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echartsInstance.getDataURL
