### ISSUE TITLE
如何在PPT中嵌入echart

### ISSUE THREAD

**Issue by littlebird197911** [ecomfe/echarts#6046]
### One-line summary [问题简述]
搜索论坛，有一个PPT网页插件，使用后发现嵌入echart3.0后显示浏览器太旧，需要升级，但是我升级火狐浏览器并设为默认后仍然是同样的提示，有什么好的解决方案么，谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:火狐
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
能够在PPT中嵌入echart

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
我们也没有太好的解决方案，要是找到方法欢迎反馈

**Comment by hanfengcan** [comment]
@pissang 4.0版本说有PPT插件,哪里找
