### ISSUE TITLE
echarts3 yAxis 怎么添加链接

### ISSUE THREAD

**Issue by Zhongxiangyun** [ecomfe/echarts#6047]
### echarts3 yAxis 怎么添加链接(由于业务需求，需要对x轴和y轴的文字添加跳转链接，不知道怎么配置这块信息，希望得到解答为谢！) [问题简述]

###echarts3   [版本及环境]
+ echarts3 3.0 [ECharts 版本]:
+ 谷歌 [浏览器类型和版本]:
+ win7 [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by WangXiZhu** [comment]
应该是和 yAxis.axisLabel.formatter相关。 
但是 yAxis里面的 formatter居然原样输出。(xAxis也不支持)
而我之前使用tooltip里面的formatter是支持html标签。这个就不知道他们怎么处理的

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#yAxis.triggerEvent 然后监听事件跳转链接

**Comment by wind22zhu** [comment]
监听事件怎么跳转链接？感觉怎么写也会被浏览器阻止。？ @pissang
