### ISSUE TITLE
flex布局echarts缩放问题(bug?)

### ISSUE THREAD

**Issue by geek-zwb** [ecomfe/echarts#6048]
### 在flex布局中，echarts嵌入，并使用mychart.resize()。当前窗口显示正常，放大窗口，正常resize,此时再缩小窗口，flex:1 1 auto(或者一个定值如520px) 无效，大小缩不回来了！！！！

```
.content {
    display: flex;
    justify-content: space-between;
  }
  .content-left {
    flex:1 1 520px;
  }
  .content-right {
    flex:0 0 270px;
  }

<div class="content">
  <div class="content-left">
   <div id="lineChart" style="width:100%, height:210px">
      line chart
   </div>
</div>
<div class="content-right">
...
</div>
</div>
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新
+ Browser version [浏览器类型和版本]: chrome 58.03
+ OS Version [操作系统类型和版本]: MAC

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不管什么布局，echarts 取的都是 dom 的 clientWidth 和 clientHeight 作为容器宽高，保证能正确获取到这两个值就行了

**Comment by geek-zwb** [comment]
所以我请教一下大神，我这样用flex有问题？

**Comment by amor520** [comment]
flex +1

**Comment by zhiyi10** [comment]
flex布局的确有问题，放大窗口的时候正常的，缩小窗口就不行了，强行用float加calc替换flex布局了

**Comment by chris-deng** [comment]
flex布局，echart实例的宽度超出外层容器宽度，外层容器宽度设置为百分比时，echart图固定为615px，请问怎么解决？

**Comment by Guanrui1** [comment]
`created() {
        this.$root.$on('processStatistics', () => {
            if (this.count == 0) {
                this.large.width==0?this.completeRate.resize():this.completeRate.resize({
                    width: this.large.width,
                    height: this.large.height
                })
                this.large.width = this.$refs.echarts.offsetWidth
                this.large.height = this.$refs.echarts.offsetHeight
                this.count++
            } else {
                this.completeRate.resize({
                    width: this.small.width,
                    height: this.small.height
                })
                this.count--
            }
        })
    },
    mounted() {
        this.small.width = this.$refs.echarts.offsetWidth
        this.small.height = this.$refs.echarts.offsetHeight
        this.createChart()
        this.setChartValue()
    }`
**使用resize的opt参数可以解决flex布局缩小的问题**

**Comment by Guanrui1** [comment]
```
    created() {
        this.$root.$on('processStatistics', () => {
            if (this.count == 0) {
                this.large.width==0?this.completeRate.resize():this.completeRate.resize({
                    width: this.large.width,
                    height: this.large.height
                })
                this.large.width = this.$refs.echarts.offsetWidth
                this.large.height = this.$refs.echarts.offsetHeight
                this.count++
            } else {
                this.completeRate.resize({
                    width: this.small.width,
                    height: this.small.height
                })
                this.count--
            }
        })
    },
    mounted() {
        this.small.width = this.$refs.echarts.offsetWidth
        this.small.height = this.$refs.echarts.offsetHeight
        this.createChart()
        this.setChartValue()
    }
```

> 使用resize的opt参数可以解决flex布局缩放时的问题

**Comment by Guanrui1** [comment]
官方不够重视flex布局下使用resize获取的默认容器宽高不正确的问题，目前我只能用这个办法解决了！

**Comment by seminelee** [comment]
+1

**Comment by szchenrong** [comment]
https://segmentfault.com/a/1190000023695095
宽度同样的问题

**Comment by de1ck** [comment]
给父元素 设置 最小宽度 啥的 w-0 min-w-500px  就可以了
