### ISSUE TITLE
折线图 多个series的数据很接近时，datalabel会重叠在一起

### ISSUE THREAD

**Issue by CherishIt** [ecomfe/echarts#6049]
### One-line summary [问题简述]
折线图 多个series的数据很接近时，datalabel会重叠在一起

### Expected behaviour [期望结果]
目前有什么解决方案吗？
有没有类似重叠就只显示其中一个label的属性？

**Comment by pissang** [comment]
暂时没有太好的解决方案，可以只展示重要数据的 label

**Comment by ashen9** [comment]
@pissang “只展示重要数据的 label，或者可以间隔” 通过什么设置做到？
