### ISSUE TITLE
markline两端是否可以同时设置不同的文字？

### ISSUE THREAD

**Issue by ZeyZhang** [ecomfe/echarts#6052]
### One-line summary [问题简述]
markline两端是否可以同时设置不同的文字，如果可以，要怎么实现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行，你可以使用 graphic 组件画 http://echarts.baidu.com/option.html#graphic
