### ISSUE TITLE
Suggestion for new chart type: table chart

### ISSUE THREAD

**Issue by WebCodePro719** [ecomfe/echarts#6058]
I really like ECharts, thank you for releasing as open source. I'd like to suggest a new chart type: table chart. Google Charts includes a table chart that can be sorted and paged. 

Here's a link to the Google Table Chart page: https://developers.google.com/chart/interactive/docs/gallery/table

It would be great if ECharts could create a similar but even better version of Google's table chart. 

Thanks.

![google-table-chart](https://user-images.githubusercontent.com/5958037/27517952-098004c8-59a3-11e7-9d86-696b64ec40cf.png)

**Comment by pissang** [comment]
Thanks for your appreciation.  We won't add table chart in the near future . You can use other alternatives like https://datatables.net/

**Comment by WebCodePro719** [comment]
Ok. Thanks for suggesting datatables.net, I'll check it out.
