### ISSUE TITLE
你好，请问，在2.0中有renderasimage 属性，可以显示为图片，3.0去掉了吗？

### ISSUE THREAD

**Issue by imew** [ecomfe/echarts#6060]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你可以 render 后 getDataURL 获取图片
