### ISSUE TITLE
迁徙地图从后台获取数据时 数据标签不显示

### ISSUE THREAD

**Issue by zml0402** [ecomfe/echarts#6067]
### One-line summary [问题简述]
官方例子上迁徙地图的数据标签是显示的，当数据从后台获取时，数据标签不显示了，设定label:{show:true}也不起作用，如果换成静态数据就显示正常，不知道这是不是一个bug?
```js
 markLine : {
                ...
                itemStyle : {
                    normal: {
                        label:{show:true},
                        borderWidth:1,
                        lineStyle: {
                            type: 'solid',
                            shadowBlur: 10
                        }
                    }
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.7
+ Browser version [浏览器类型和版本]:谷歌59.0.3071.86（32位）和火狐54.0 (32 位)
+ OS Version [操作系统类型和版本]:
 win7

### Expected behaviour [期望结果]
希望从后台获取的数据也可以正常显示数据标签，这样比较直观一些。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
只要你传入 option 的数据是一样的，不会出现一种显示一种不显示的问题，所以建议你找下数据的问题
