### ISSUE TITLE
3.5.0版本以后，nameMap部分国家名称英文改变

### ISSUE THREAD

**Issue by wangyx233** [ecomfe/echarts#6070]
### One-line summary [问题简述]
发现用nameMap渲染的世界地图，美国不能正常显示，而显示United States，进而发现刚果等国家也是相同效果。
经过比较发现，world.js的国家信息在3.5.0后进行了部分修改，但是官网提供的nameMap并没有更改，根据提供的nameMap实例就出现了国家无法匹配显示的情况。
部分更改后国家名称对应如下：
`
var nameMap={
'United States': '美国',
'Korea': '韩国',
'Dem. Rep. Korea': '朝鲜',
'Congo': '刚果共和国',
'Solomon Is.': '所罗门群岛',
'Dominican Rep.': '多明尼加共和国',
'S. Sudan': '南苏丹' ,
'Côte d'Ivoire': '科特迪瓦',
'Central African Rep.': '中非共和国',
'Dem. Rep. Congo': '刚果民主共和国',
'Lao PDR': '老挝',
'W. Sahara': '西撒哈拉',
'Tanzania': '坦桑尼亚联合共和国',
}
`

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: Chrome  57.0.2987.133 (64-bit)
+ OS Version [操作系统类型和版本]: OS X 10.11

### Expected behaviour [期望结果]
希望这种小问题，官网实例也能更新~

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢反馈
