### ISSUE TITLE
subtext提供更多自定义配置

### ISSUE THREAD

**Issue by Gyyi** [ecomfe/echarts#6073]
### One-line summary [问题简述]
关于title里的subtext可否提供一个自定义位置的配置呢，效果类似下图：

![qq 20170627182344](https://user-images.githubusercontent.com/16659067/27583072-c9a3034a-5b65-11e7-8812-20e03a165f4b.png)

目前subtext是默认显示在title下方的，这样同行显示的效果需要通过div来实现，如果能提供一个这样的配置就太好了。
或者有某些配置能够实现subtext的自定义位置，只是我没有找到？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

如上文描述

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你可以用两个 title 组件

**Comment by Gyyi** [comment]
感谢回答，茅塞顿开ing
