### ISSUE TITLE
echarts的折线图的数据的纵坐标的值跟纵坐标应该显示的高度不一致

### ISSUE THREAD

**Issue by jochenshi** [ecomfe/echarts#6079]
echarts的折线图的数据的纵坐标的值跟纵坐标应该显示的高度不一致
以官方示例为例：http://gallery.echartsjs.com/editor.html?c=line-stack
实际纵坐标的数据只有几百，但是却显示在坐标轴100以上的位置

**Comment by pissang** [comment]
去掉 stack
