### ISSUE TITLE
字体粗细加粗和更粗无区别，文字倾斜和斜体无区别

### ISSUE THREAD

**Issue by losiyo** [ecomfe/echarts#6084]
### One-line summary [问题简述]
1. 字体粗细加粗和更粗无区别，
2. 文字倾斜和斜体无区别
3. 图形标签对齐内部下方与内部上方颠倒，内部左下与右上颠倒，内部左上与右下颠倒，

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: chrome 58.0
+ OS Version [操作系统类型和版本]: win7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这是因为有些字体就是没有粗体
