### ISSUE TITLE
map 数据迁移效果 tooltip轮播

### ISSUE THREAD

**Issue by shenggen1987** [ecomfe/echarts#6087]
### One-line summary [问题简述]

```js
var currentIndex = -1
    setInterval(function () {
      var dataLen = options.series[0].data.length
      console.log(currentIndex)
      // 取消之前高亮的图形
      myChart.dispatchAction({
        type: 'downplay',
        seriesIndex: 0,
        dataIndex: currentIndex
      })
      currentIndex = (currentIndex + 1) % dataLen
      // 高亮当前图形
      myChart.dispatchAction({
        type: 'highlight',
        seriesIndex: 0,
        dataIndex: currentIndex
      })
      // 显示 tooltip
      myChart.dispatchAction({
        type: 'showTip',
        seriesIndex: 0,
        dataIndex: currentIndex
      })
    }, 1000)
```
 以上代码放到数据迁移的那个  http://echarts.baidu.com/demo.html#geo-lines  tooltip值显示一次，怎么解决，我们就想放到电视上，给客户看
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts3
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: mac

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没理解你的意思

**Comment by shenggen1987** [comment]
http://trends.baidu.com/trip/index?type=china-city 能提供这个效果的mapstyle吗？

**Comment by shenggen1987** [comment]
自己解决了，谢谢，有需求的同学可以见的我demo  [https://shenggen1987.github.io/echarts-demo/#/](https://shenggen1987.github.io/echarts-demo/#/)     vue2.0+webpack+echarts

**Comment by Janking** [comment]
@shenggen1987 有源码吗？？
