### ISSUE TITLE
希望解除事件绑定和添加事件绑定可以支持链式操作

### ISSUE THREAD

**Issue by yangzhongxun** [ecomfe/echarts#6089]
### 问题简述
解除事件绑定和添加事件绑定不能链式操作。

### 版本及环境
- ECharts 版本: 3.6.0
- 浏览器类型和版本: Google Chrome v59.0.3071.115 64-bit
- 操作系统类型和版本: win10 专业版

### 期望结果
解除事件绑定和添加事情绑定可以链式操作，比如：
为了防止事件重复绑定，需要先解除事件然后再添加事件；
现在的 Echarts 需要这样操作：
``` javascript
chart.off('click');
chart.on('click', doSomething);
```

而我期望的是类似 jQuery 那样的链式操作：
``` javascript
chart.off('click').on('click', doSomething);
```
而我如果在 Echarts 中这样写的话，就会报错。因为这时候 `charts.off('click')` 的返回值是 `undefined`。

Echarts 很棒，但是我希望能更好！

**Comment by pissang** [comment]
新版本会考虑这个建议，谢谢
