### ISSUE TITLE
title 下的 textAlign:"center" ，无效， 改为把textAlign属性改为x 则有效，能说明下原因吗？

### ISSUE THREAD

**Issue by kevinJser** [ecomfe/echarts#6091]
### One-line summary [问题简述]

title 下的 textAlign:"center" ，无效， 改为把textAlign属性改为x 则有效，能说明下原因吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#title.left
