### ISSUE TITLE
echarts3 力导向图缩小比例之后，拖动和放大问题

### ISSUE THREAD

**Issue by LeiO-Angel** [ecomfe/echarts#6092]
### One-line summary [问题简述]
假设我画了个100x100的力导向图，通过滚轮缩小，可能缩小到50x50, 那么在外围的

50-100范围的区域，则无法再拖动导向图，同时在这个区域也无法使用滚轮放大。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
嗯，只有显示的那篇区域才能拖拽，这是为了防止有多个图存在的时候互相会重叠
