### ISSUE TITLE
关于导入js的问题

### ISSUE THREAD

**Issue by lsniuniu** [ecomfe/echarts#6095]
### One-line summary [问题简述]
之前使用echarts的js通过的在线的方式
<script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
下面是具体配置 (此时可以正常使用echarts的功能)
require.config({
		paths : {
			echarts : 'http://echarts.baidu.com/build/dist'
		}
	});

	// 使用
require([ 'echarts', 'echarts/chart/bar', // 使用柱状图就加载bar模块，按需加载  
	          'echarts/chart/line','echarts/chart/pie' ], DrawEChart);
按照网上的教程将echarts的源文件下载下来引入到项目中以后各种报错。
有没有引入本地的echarts.js的求帮助

## Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts

**Comment by lsniuniu** [comment]
这种方式还是不行，我需要动态的加载数据。
