### ISSUE TITLE
No data background

### ISSUE THREAD

**Issue by trix87** [ecomfe/echarts#6101]
### One-line summary [问题简述]
Hello, i am facing a problem where i cant change the animated background when there is no data. I want to change that bubbly background with the text with something custom. Where can i change that cause i looked in tons of places but had no luck.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: Chrome(latest)
+ OS Version [操作系统类型和版本]: win10 64bit

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
ECharts removed no data tip since version 3.
