### ISSUE TITLE
地图定制工具不能使用

### ISSUE THREAD

**Issue by gakaki** [ecomfe/echarts#6107]
### One-line summary [问题简述]

地图定制工具不能使用

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:20170703
+ Browser version [浏览器类型和版本]:safrai 10 chrome 60无法使用
+ OS Version [操作系统类型和版本]:OSX系统

### Expected behaviour [期望结果]
没有输出js和json

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
我这没问题，能否描述下复现方式？
