### ISSUE TITLE
dataZoom不同的start值设置后仅显示部分数据（显示不全）的疑问

### ISSUE THREAD

**Issue by oopsky** [ecomfe/echarts#6116]
One-line summary [问题简述]
http://gallery.echartsjs.com/editor.html?c=xHyX0GpOVZ&v=1
以上是我的一个案例，请参考案例中所提供的option，本案例有135个数据值，当dataZoom的start值设置在100到135中的任何一个值仅显示1个数据点，而当设置小于100时（比如99）则显示大于等2个点的数据（但是还是不全）。不明白为什么出现这个问题？是否是我的option有问题？请教各位大神了。

Version & Environment [版本及环境]

ECharts version [ECharts 版本]: 官方实例中的版本
Browser version [浏览器类型和版本]:Chrome 59
OS Version [操作系统类型和版本]: Win10 64bit

Expected behaviour [期望结果]
dataZoom显示所输入的start值起的全部数据。

ECharts option [ECharts配置项]
{
    "title": {
        "text": "",
        "x": "left"
    },
    "tooltip": {
        "trigger": "axis"
    },
    "animation": false,
    "calculable": true,
    "dataZoom": {
        "show": true,
        "start": 99
    },
    "legend": {
        "data": [
            "文件访问异常",
            "内容不符合规范",
            "json1 失败",
            "json2 失败",
            "异常1",
            "文件访问超时",
            "长度不符合规范",
            "json3失败",
            "T1访问超时",
            "json4失败",
            "T2访问异常",
            "T3内容不符合规范",
            "T4 error",
            "T5长度不符合规范",
            "Header异常"
        ]
    },
    "xAxis": [
        {
            "type": "category",
            "data": [
                "2017-01-25",
                "2017-02-20",
                "2017-02-21",
                "2017-02-23",
                "2017-02-24",
                "2017-02-25",
                "2017-02-26",
                "2017-02-27",
                "2017-02-28",
                "2017-03-01",
                "2017-03-02",
                "2017-03-03",
                "2017-03-04",
                "2017-03-05",
                "2017-03-06",
                "2017-03-07",
                "2017-03-08",
                "2017-03-09",
                "2017-03-10",
                "2017-03-11",
                "2017-03-12",
                "2017-03-13",
                "2017-03-14",
                "2017-03-15",
                "2017-03-16",
                "2017-03-17",
                "2017-03-18",
                "2017-03-19",
                "2017-03-20",
                "2017-03-21",
                "2017-03-22",
                "2017-03-23",
                "2017-03-24",
                "2017-03-25",
                "2017-03-26",
                "2017-03-27",
                "2017-03-28",
                "2017-03-29",
                "2017-03-30",
                "2017-03-31",
                "2017-04-01",
                "2017-04-02",
                "2017-04-03",
                "2017-04-04",
                "2017-04-05",
                "2017-04-06",
                "2017-04-07",
                "2017-04-08",
                "2017-04-09",
                "2017-04-10",
                "2017-04-11",
                "2017-04-12",
                "2017-04-13",
                "2017-04-14",
                "2017-04-15",
                "2017-04-16",
                "2017-04-17",
                "2017-04-18",
                "2017-04-19",
                "2017-04-20",
                "2017-04-21",
                "2017-04-22",
                "2017-04-23",
                "2017-04-24",
                "2017-04-25",
                "2017-04-26",
                "2017-04-27",
                "2017-04-28",
                "2017-04-29",
                "2017-04-30",
                "2017-05-01",
                "2017-05-02",
                "2017-05-03",
                "2017-05-04",
                "2017-05-05",
                "2017-05-06",
                "2017-05-07",
                "2017-05-08",
                "2017-05-09",
                "2017-05-10",
                "2017-05-11",
                "2017-05-12",
                "2017-05-13",
                "2017-05-14",
                "2017-05-15",
                "2017-05-16",
                "2017-05-17",
                "2017-05-18",
                "2017-05-19",
                "2017-05-20",
                "2017-05-21",
                "2017-05-22",
                "2017-05-23",
                "2017-05-24",
                "2017-05-25",
                "2017-05-26",
                "2017-05-27",
                "2017-05-28",
                "2017-05-29",
                "2017-05-30",
                "2017-05-31",
                "2017-06-01",
                "2017-06-02",
                "2017-06-03",
                "2017-06-04",
                "2017-06-05",
                "2017-06-06",
                "2017-06-07",
                "2017-06-08",
                "2017-06-09",
                "2017-06-10",
                "2017-06-11",
                "2017-06-12",
                "2017-06-13",
                "2017-06-14",
                "2017-06-15",
                "2017-06-16",
                "2017-06-17",
                "2017-06-18",
                "2017-06-19",
                "2017-06-20",
                "2017-06-21",
                "2017-06-22",
                "2017-06-23",
                "2017-06-24",
                "2017-06-25",
                "2017-06-26",
                "2017-06-27",
                "2017-06-28",
                "2017-06-29",
                "2017-06-30",
                "2017-07-01",
                "2017-07-02",
                "2017-07-03",
                "2017-07-04"
            ]
        }
    ],
    "yAxis": {
        "type": "value"
    },
    "series": [
        {
            "name": "文件访问异常",
            "type": "line",
            "data": [
                "6",
                "4",
                "1",
                "613",
                "610",
                "613",
                "635",
                "659",
                "580",
                "557",
                "321",
                "173",
                "120",
                "103",
                "103",
                "105",
                "104",
                "2",
                "0",
                "1",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "26",
                "26",
                "17",
                "16",
                "16",
                "148",
                "148",
                "159",
                "143",
                "97",
                "125",
                "109",
                "113",
                "108",
                "110",
                "108",
                "108",
                "100",
                "107",
                "98",
                "107",
                "109",
                "110",
                "108",
                "105",
                "111",
                "111",
                "107",
                "110",
                "92",
                "107",
                "105",
                "164",
                "301",
                "145",
                "323",
                "321",
                "325",
                "125",
                "179",
                "126",
                "180",
                "159",
                "114",
                "101",
                "101",
                "92",
                "92",
                "105",
                "92",
                "105",
                "154",
                "92",
                "93",
                "93",
                "105",
                "93",
                "101",
                "108",
                "96",
                "442",
                "221",
                "111",
                "119",
                "111",
                "98",
                "213",
                "141",
                "107",
                "126",
                "107",
                "108",
                "108",
                "95",
                "95",
                "95",
                "109",
                "95",
                "109",
                "108",
                "108",
                "98",
                "109",
                "109",
                "108",
                "108",
                "108",
                "109",
                "109",
                "108",
                "108",
                "107",
                "107",
                "107",
                "107",
                "102",
                "102",
                "102",
                "102",
                "102",
                "102",
                "102",
                "106",
                "102",
                "102",
                "103",
                "102",
                "102",
                "103"
            ]
        },
        {
            "name": "内容不符合规范",
            "type": "line",
            "data": [
                "0",
                "2",
                "2",
                "126",
                "123",
                "121",
                "121",
                "121",
                "121",
                "124",
                "121",
                "121",
                "121",
                "123",
                "121",
                "121",
                "121",
                "121",
                "121",
                "121",
                "121",
                "121",
                "121",
                "121",
                "121",
                "126",
                "121",
                "127",
                "121",
                "121",
                "121",
                "122",
                "122",
                "122",
                "122",
                "122",
                "125",
                "121",
                "125",
                "125",
                "125",
                "125",
                "125",
                "128",
                "125",
                "125",
                "125",
                "125",
                "125",
                "128",
                "161",
                "125",
                "125",
                "125",
                "125",
                "125",
                "125",
                "125",
                "125",
                "125",
                "128",
                "125",
                "125",
                "125",
                "128",
                "128",
                "128",
                "128",
                "128",
                "128",
                "125",
                "128",
                "125",
                "125",
                "124",
                "125",
                "125",
                "125",
                "125",
                "125",
                "23",
                "125",
                "125",
                "132",
                "127",
                "126",
                "130",
                "126",
                "128",
                "129",
                "129",
                "128",
                "128",
                "125",
                "128",
                "125",
                "125",
                "125",
                "125",
                "125",
                "128",
                "128",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "126",
                "130",
                "127",
                "127",
                "121",
                "127",
                "121",
                "121",
                "127",
                "213",
                "127",
                "127",
                "128",
                "128",
                "125",
                "125"
            ]
        },
        {
            "name": "json1 失败",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "23",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "1",
                "0",
                "41",
                "20",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "1",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "179",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "json2 失败",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "10",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "1",
                "1",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "1",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "1",
                "1",
                "5",
                "7",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "7",
                "1",
                "0",
                "1",
                "0",
                "1",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0…",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "json3失败",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "1"
            ]
        },
        {
            "name": "T1访问超时",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "json4失败",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "T2访问异常",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "T3内容不符合规范",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "T4 error",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "T5长度不符合规范",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        {
            "name": "Header异常",
            "type": "line",
            "data": [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        }
    ]
}

**Comment by 100pah** [comment]
`start` 值是百分比，最大只能设 100。
可以设置 `startValue`，这是具体数值。

**Comment by oopsky** [comment]
多谢,明天试一试。

**Comment by oopsky** [comment]
百分比可以用，多谢
