### ISSUE TITLE
geo 配置的地图不支持 tooltip 吗？

### ISSUE THREAD

**Issue by hele10086** [ecomfe/echarts#6123]
### One-line summary [问题简述]
用 series 配置的地图有 tooltip，但改用 geo 的方式就不行了，需要如何配置？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
geo 因为没数据所以不支持 tooltip

**Comment by ZhengAaron** [comment]
@pissang ，我也遇到这个问题了，所以我就在这个底下再问下：地图里 我要展示地图的数据， 还有effectScatter 的数据，两个数据都得有tooltip（自己formatter成自己想要的数据），没有geo，effectScatter 数据出不来，用了geo，地图的tooltip信息又出不来，然后我把geo和series 都把地图配置上去了。- -看似满足了要求，但是当我放大缩小的时候  实际上是有2张地图的。如果 配置成geo然后监听click事件，这样出来的弹出框就是自己的了，然后我再监听鼠标是否点击了其他地方 然后把这个弹出框消失掉？感觉不完美啊？所以想问问，有没有好的解决方案？先谢谢了。

**Comment by 100pah** [comment]
可以参见这个例子：<http://echarts.baidu.com/demo.html#geo-map-scatter>

**Comment by ZhengAaron** [comment]
@100pah 千言万语汇成一个字：“谢谢谢谢谢谢谢谢谢谢谢谢谢谢............”完美解决。
我一开始也看到了这个demo了~~为什么当时就没觉得这个可以实现我的功能呢。- -还是太年轻了~~~

**Comment by wjfstrive** [comment]
例子地址好像进不去了，还有链接吗，也遇到了这个问题，不知道咋解决。

**Comment by fengshenhai-0727** [comment]
> 例子地址好像进不去了，还有链接吗，也遇到了这个问题，不知道咋解决。

**Comment by yangjunjie0728** [comment]
> > 例子地址好像进不去了，还有链接吗，也遇到了这个问题，不知道咋解决。

https://echarts.apache.org/examples/zh/editor.html?c=geo-map-scatter
从百度换成apche了
