### ISSUE TITLE
饼状图中formatter的内容在图表上悬浮时，可以固定位置吗？

### ISSUE THREAD

**Issue by driind** [ecomfe/echarts#6124]
### One-line summary [问题简述]

饼状图中formatter的内容在图表上悬浮时，如果内容显示较长，或者饼状图比较接近网页边缘，在鼠标移动显示的时候（如果先悬浮一个靠边缘的框，再去悬浮另一个名称比较长的数据），会出现页面闪动，原因是浮动框超过了页面边缘，所以出现了瞬时的滚动条。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

我认为所有的浏览器都会出现这种情况

### Expected behaviour [期望结果]

希望能自定义设置浮动框在鼠标位置的相对方位。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#tooltip.position

**Comment by driind** [comment]
多谢，就是要的这个，怪我自己没找到。
