### ISSUE TITLE
echart3中如何获取value类型的坐标轴的极值

### ISSUE THREAD

**Issue by luguokong** [ecomfe/echarts#6125]
### One-line summary [问题简述]
echarts3中如何获取value类型的坐标轴的极值，通过getOption()获取的对象中没有max，min属性
echarts2中可以通过 myChart.component.yAxis.getAxis(0).getExtremum().max的方式获取极值
请问3有类似的方法吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
myChart.getModel().getComponent('yAxis').axis.extent[1]

**Comment by luguokong** [comment]
谢谢
