### ISSUE TITLE
关于echarts2升级到ehcarts3的问题

### ISSUE THREAD

**Issue by Missyanwen** [ecomfe/echarts#6132]
### echarts3
+ echarts3 [ECharts 版本]:
+ Google浏览器、59.0.3071.115版本 [浏览器类型和版本]:
+ window操作系统版本是window7 [操作系统类型和版本]:

**Comment by pissang** [comment]
echarts 3 不暴露这些内部方法了，如果你是模块化加载（webpack，requirejs等等）的话可以尝试加载 https://github.com/ecomfe/zrender/blob/master/src/contain/polygon.js 这个模块
