### ISSUE TITLE
关于用来作为图表容器DIV的宽高设置问题

### ISSUE THREAD

**Issue by NiuGui8** [ecomfe/echarts#6134]
### One-line summary [问题简述]
    对容器DIV设置不同的宽度高度，有时候图表会缩成一小团在角落里，有时候调整的幅度也不大，请问宽高设置有什么要求吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echarts 3
+ Browser version [浏览器类型和版本]:Chrome V55.0.2883.75 m
+ OS Version [操作系统类型和版本]:WIN 7 64

**Comment by pissang** [comment]
需要在 init 的时候能够获取到 clientWidth 和 clientHeight，如果 init 的时候无法获取的话，在容器准备好后重新 resize
