### ISSUE TITLE
symbol设置为png图片，变得有透明度了

### ISSUE THREAD

**Issue by HeNanBing** [ecomfe/echarts#6138]
### One-line summary [问题简述]

symbol设置为png图片，变得有透明度了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]: chrome 59.0.3071.115
+ OS Version [操作系统类型和版本]: win10 专业版

### Expected behaviour [期望结果]

原样显示，不要透明度

### ECharts option [ECharts配置项]

```javascript
option = {
  series: [
        {
          name: '司机',
          type: 'scatter',
          coordinateSystem: 'geo',
          data: converMapPointData(data),
          symbolSize(value) {
            if (value[2] > 5 && value[2] < 15) {
              return [30, 30];
            }
            return [15, 15];
          },
          symbol: 'image://../src/static/image/truck.png',
          large: true,
          itemStyle: {
            normal: {
              color: 'rgba(255, 255, 255, 1)',
            },
          },
        },
  ]
}

```

### Other comments [其他信息]

![tim 20170705173800](https://user-images.githubusercontent.com/13029560/27858697-c3b156aa-61a8-11e7-8a9a-6ddeaeab5db9.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-scatter.itemStyle.normal.opacity 改成 1

**Comment by HeNanBing** [comment]
嗯嗯，谢谢，可以了，还有一个，为什么会变的模糊呢，就像图片上一样，锯齿明显，png本身大小是200x200，设置的symbolSize为[30,30],[15,15],最大的是[45, 45]，是因为电脑分辨率的原因还是其他的原因啊
