### ISSUE TITLE
在 IPAD的safari和chrome中缩放有echarts的页面，导致浏览器闪退

### ISSUE THREAD

**Issue by guanjinke** [ecomfe/echarts#614]
我们的测试人员发现了这个问题，我们多次验证确实存在。目前使用iPad的safari打开echarts的官网中得实例页面，在一个实例页面中，只要放大，就会导致浏览器闪退。

**Comment by ShanxiangWei** [comment]
我在移动端就一直遇到的问题，很困扰。似乎是内存的问题

**Comment by aimaodeyuer** [comment]
我在移动端用echarts绘制饼图，6plus打开的各浏览器也会闪退，不知道有没有人解决这个问题。
