### ISSUE TITLE
时间组件timeline如何跳到指定的checkpoint

### ISSUE THREAD

**Issue by Wanglinq** [ecomfe/echarts#6140]
### One-line summary [问题简述]
比如我时间轴是4:00开始的，但是我首次加载的时候我希望显示的是8:00的数据，时间组件的checkpoint也是8:00

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:chrome  61.0.3141.7
+ OS Version [操作系统类型和版本]:Windows 10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#timeline.currentIndex
