### ISSUE TITLE
echart -关系图-Graph 简单示例，ajax动态获取数据，报错 Cannot set property 'dataIndex' of undefined   怎么解决呀

### ISSUE THREAD

**Issue by CWSchen** [ecomfe/echarts#6145]
echart - 关系图- Graph 简单示例，
ajax动态获取数据，报错 Cannot set property 'dataIndex' of undefined   怎么解决呀

### One-line summary [问题简述]

$scope.fn_ajax = function() {

                var myChart = echarts.init(document.getElementById('main'));

                var option = {
                    title: {
                        text: ''
                    },
                    tooltip: {},
                    animationDurationUpdate: 1500,
                    animationEasingUpdate: 'quinticInOut',
                    series : [
                        {
                            type: 'graph',
                            symbolSize: 50,
                            label: {
                                normal: {
                                    show: true
                                }
                            },
                            edgeSymbol: ['circle', 'arrow'],
                            data: [],
                            // links: [],
                            links: [],
                            lineStyle: {
                                normal: {
                                    opacity: 0.9,
                                    width: 1,
                                    curveness: 0
                                }
                            }
                        }
                    ]
                };
                myChart.showLoading();// 加载动画
				
				//ajax 获取到数据。通过js数据拼装，得到符合格式的数据
				if( $scope.allData && $scope.allLink ){
					
					myChart.hideLoading();
					// 指定图表的配置项和数据
					option.series[0].data = $scope.allData;
					option.series[0].links = $scope.allLink;
					myChart.setOption(option);
					
				}
				

            };

报错啦。 Cannot set property 'dataIndex' of undefined 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.6.2
+ Browser version [浏览器类型和版本]:
谷歌
+ OS Version [操作系统类型和版本]:
windows 7

### Expected behaviour [期望结果]

得到 关系图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你的数据发我们看下

**Comment by CWSchen** [comment]
{"data":{"bottomLinks":[{"source":"回液泵","target":"test1"},{"source":"供液泵","target":"test1"},{"source":"入气风机","target":"test1"},{"source":"补光灯2","target":"test1"},{"source":"补光灯1","target":"test1"}],"node":[{"id":"cb21c80e-9467-42fc-ae15-49a6f1772884","level":0,"name":"叶菜工厂","type":"factory"},{"id":"7bdcae08-7071-4d84-b999-fc782b5d7baa","level":0,"name":"果菜工厂","type":"factory"},{"id":"69a8fb68-ec63-49bd-a674-bbd59cf201b1","level":1,"name":"回液泵","type":"exeunit"},{"id":"6819904e-5a92-4dd9-93f6-1e359ea85334","level":1,"name":"供液泵","type":"exeunit"},{"id":"4acdb79d-fa4e-43df-8e7e-43e13efb217f","level":1,"name":"入气风机","type":"exeunit"},{"id":"5e9f8f5c-30c2-4953-8169-dd62ee0de446","level":1,"name":"补光灯2","type":"exeunit"},{"id":"4547916d-9702-48eb-94fd-8f699b0befdb","level":1,"name":"补光灯1","type":"exeunit"},{"id":"e6793610-73eb-41bb-8998-fea4dc526e55","level":2,"name":"test1","type":"com"},{"id":"946f8fd9-627a-4694-9350-9f2378ec3ce6","level":2,"name":"test1","type":"com"}],"topLinks":[{"source":"回液泵","target":"叶菜工厂"},{"source":"供液泵","target":"叶菜工厂"},{"source":"入气风机","target":"叶菜工厂"},{"source":"补光灯2","target":"叶菜工厂"},{"source":"补光灯1","target":"叶菜工厂"}]},"error_code":0}

如上是ajax接口获取的数据

``

					
					$rootScope.fn_ajax_map = function(){

						$http({
							method: "post",
							url: ajax_factoryIndex.get_map(),
							data: JSON.stringify( {} ),
							headers: {
								'Content-Type': 'application/x-www-form-urlencoded'
							}})
							.success(function (response) {

								if( response.error_code == 0 ) {
									$rootScope.allNode = response.data.node;
									var arr_1 = response.data.topLinks;
									var arr_2 = response.data.bottomLinks;
									$rootScope.allLink = arr_1.concat.apply(arr_1, arr_2);
								}

							})
							.error(function (response) {

							});
					};
					$rootScope.fn_ajax_map();
					
					
					如下代码是，ajax拿到数据后的数据拼装
					
                    var arr_level = [];
                    var arr_level_1 = [];
                    var arr_level_2 = [];
                    var arr_level_3 = [];
                    for(var i= 0,len=$scope.allNode.length;i<len;i++){
                        if( $scope.allNode[i].level == 0 ){
                            arr_level_1.push( $scope.allNode[i] );
                        }
                        if($scope.allNode[i].level == 1){
                            arr_level_2.push( $scope.allNode[i] );
                        }
                        if($scope.allNode[i].level == 2){
                            arr_level_3.push( $scope.allNode[i] );
                        }
                    }
                    for(var ia= 0,lena=arr_level_1.length;ia<lena;ia++){
                        arr_level_1[ia].x = 100 + 50 * i;
                        arr_level_1[ia].y =100;
                    }
                    for(var ib= 0,lenb=arr_level_2.length;ib<lenb;ib++){
                        arr_level_2[ib].x = 100 + 50 * i ;
                        arr_level_2[ib].y =130;
                    }
                    for(var ic= 0,lenc=arr_level_3.length;ic<lenc;ic++){
                        arr_level_3[ic].x = 100 + 50 * i;
                        arr_level_3[ic].y =160;
                    }
                    //将数组 arr_level_2, arr_level_3 里的所有对象 push到 arr_level_1 里
                    arr_level_1.push.apply(arr_level_1 ,arr_level_2 );
                    arr_level_1.push.apply(arr_level_1 ,arr_level_3 );

                    for(var i2= 0,len2=arr_level_1.length;i2<len2;i2++){
                        arr_level.push({
                            name:arr_level_1[i2].name,
                            x:arr_level_1[i2].x ,
                            y:arr_level_1[i2].y
                        });
                    }
					
					// 指定图表的配置项和数据
                    option.series[0].data = arr_level;
                    option.series[0].links = $scope.allLink;
                    //console.log(option);
                    // 使用刚指定的配置项和数据显示图表。
                    myChart.setOption(option);

**Comment by CWSchen** [comment]
辛苦您了

**Comment by pissang** [comment]
@CWSchen 你还是在 http://gallery.echartsjs.com/ 直接建一个例子吧

**Comment by CWSchen** [comment]
@pissang  好的

**Comment by CWSchen** [comment]
在  http://gallery.echartsjs.com/  这个上面，因为报错 创建不了例子。

**Comment by CWSchen** [comment]
哎呀，问题，解决了，不是echarts的问题，是因为，数据有重复的了。j
