### ISSUE TITLE
力向导图布局节点之间的距离问题，即边的长度问题

### ISSUE THREAD

**Issue by Lily-Jian** [ecomfe/echarts#6149]
### One-line summary [问题简述]
关系图中力向导图的布局，当节点较多时有的点距离较远，有的点距离较近；当节点较少时，节点间距离一样。官方文档说可以通过links下的value属性设置，可是我设置了没用啊。
请问：
节点之间的距离是由什么因素影响的？
怎么可以设置让某些节点靠近一点？
详情请见：
http://gallery.echartsjs.com/editor.html?c=xrkzc9viEZ&comment=0
http://gallery.echartsjs.com/editor.html?c=xHJT53Dj4Z&comment=0

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.62
+ Browser version [浏览器类型和版本]: Firefox
+ OS Version [操作系统类型和版本]: win7 64

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

数据格式如下：
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.2draft" version="1.2" xmlns:viz="http://www.gexf.net/1.2draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.2draft http://www.gexf.net/1.2draft/gexf.xsd">
  <meta lastmodifieddate="2017-01-30">
    <creator>Gephi 0.8.1</creator>
    <description></description>
  </meta>
  <graph defaultedgetype="undirected" mode="static">
    <attributes class="node" mode="static">
      <attribute id="modularity_class" title="Modularity Class" type="integer"></attribute>
    </attributes>
    <nodes>
      <node id="0" label="Myriel">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="28.685715"></viz:size>

      </node>

      <node id="1" label="Napoleon">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="4.0"></viz:size>
       
      </node>

      <node id="2" label="MlleBaptistine">
        <attvalues>
          <attvalue for="modularity_class" value="1"></attvalue>
        </attvalues>
        <viz:size value="9.485714"></viz:size>

      </node>

      <node id="3" label="MmeMagloire">
        <attvalues>
          <attvalue for="modularity_class" value="5"></attvalue>
        </attvalues>
        <viz:size value="15.485714"></viz:size>

      </node>

      <node id="4" label="CountessDeLo">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="4.0"></viz:size>

      </node>

      <node id="5" label="Geborand">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="4.0"></viz:size>

      </node>

      <node id="6" label="Champtercier">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="4.0"></viz:size>

      </node>

      <node id="7" label="Cravatte">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="4.0"></viz:size>

      </node>

      <node id="8" label="Count">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="4.0"></viz:size>

      </node>

      <node id="9" label="OldMan">
        <attvalues>
          <attvalue for="modularity_class" value="0"></attvalue>
        </attvalues>
        <viz:size value="4.0"></viz:size>

      </node>

    </nodes>
    <edges>
      <edge id="0" source="1" target="0" weight="100" value="20">
        <attvalues></attvalues>
      </edge>
      <edge id="1" source="2" target="0" weight="10" value="50">
        <attvalues></attvalues>
      </edge>
      <edge id="2" source="3" target="0"  value="10">
        <attvalues></attvalues>
      </edge>

      <edge id="4" source="4" target="0"  value="200">
        <attvalues></attvalues>
      </edge>

      <edge id="4" source="9" target="4"  value="200">
        <attvalues  value="200"></attvalues>
      </edge>

    </edges>
  </graph>
</gexf>

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#series-graph.force.edgeLength
