### ISSUE TITLE
项目部署到服务器找不到图片

### ISSUE THREAD

**Issue by HeNanBing** [ecomfe/echarts#6150]
### One-line summary [问题简述]

本地测试的时候正常显示图片，部署到服务器就找不到了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]: chrome  59.0.3071.115
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]

正常显示图片

### ECharts option [ECharts配置项]

```javascript
option = {
symbol: 'image://./src/static/image/sun.png',
}

```

### Other comments [其他信息]

项目的结构：
![27892749-0b9b6b78-6234-11e7-9ccb-cf15d32c5182](https://user-images.githubusercontent.com/13029560/27902059-e589cfbe-6266-11e7-9681-1e7b33ef8acf.png)
symbol的image写法：
symbol: 'image://./src/static/image/sun.png',
服务器上显示为:
![tim 20170706162034](https://user-images.githubusercontent.com/13029560/27902109-1b5c2c5e-6267-11e7-976d-70c3fee25cb1.png)
路径不对，是因为服务器配置不对吗，还是我的image路径写的有问题

**Comment by pissang** [comment]
跟 echarts 无关
