### ISSUE TITLE
[Feature Request] Hourly Calendar Chart

### ISSUE THREAD

**Issue by iamacarpet** [ecomfe/echarts#6155]
### One-line summary [问题简述]

Hourly calendar chart, to show orders per hour for the last two weeks.

### Expected behaviour [期望结果]

It would be great to have an calendar chart, but by hour instead of by day.

Drawing it with echarts would offer lots more flexibility than using a table, such as adding graphics and animated alerts for low hours.

### Other comments [其他信息]

Please see mockup of what we are looking for below.

Day of the week on the left, hour on the top.

Hourly boxes have a label with the value, can change colour based on comparison to the same hour on another day (probably handled server side with a fixed colour given to the graph).

![Chart Example](https://user-images.githubusercontent.com/1333857/27908434-b39594b6-6243-11e7-98bc-06ae23c84693.png)

**Comment by iamacarpet** [comment]
Nevermind, we achieved exactly what we wanted, if not better, with the heatmap chart.

We haven't got green -> orange -> red, it is just yellow -> red, but the difference is still easy if not easier to pick out, so we are happy with it.

**Comment by mjesteve** [comment]
Hi, it's been a long time since that issue but iamacarpet could you pass me an example of the chart you implemented?

Thanks.
