### ISSUE TITLE
echarts里的地图没有完全遵循 Geojson的标准

### ISSUE THREAD

**Issue by ZhengAaron** [ecomfe/echarts#6164]
Geojson标准里有段是
![image](https://user-images.githubusercontent.com/29974628/27951284-f72bfd84-6336-11e7-8832-163221e3172e.png)
Polygon  是可以画出带孔的面的。但是echarts里非得让我转成MultiPolygon 来实现。这样我系统还得专门为echarts来维护一套数据。
我用的版本是echarts-3.6.2。
所以有可能，还是希望能改进下。

**Comment by pissang** [comment]
ECharts 是支持带 hole 的 Polygon 的，http://gallery.echartsjs.com/editor.html?c=xHkzvHR3Eb

**Comment by pissang** [comment]
我知道问题在哪了，应该是 ECharts 里画 hole 需要 exterior 和 interior 是不同方向的，也就是 winding rule，这个在 GeoJSON 里之前没有明确的规范，但是现在也有推荐 exterior 为逆时针，interior 为顺时针

**Comment by ZhengAaron** [comment]
@pissang ，谢谢，真是这个方向的问题·~~~这个我需要加什么参数么？还是我这里要改变点的顺序·~不过geojson文件都是自动生成的，如果让我改也不太现实，毕竟我一个程序员对arcgis的使用和理解有限。所以可能的话 ，这个你们是不是能在加载的时候 有什么地方能判断的。

**Comment by pissang** [comment]
@ZhengAaron 这个现在还没有什么参数可以设置，其实要改不麻烦，你把有问题的 geojson 也贴出来了，只需要对 coordinates 后面几项 reverse，或者第一项 reverse 就行了

**Comment by ZhengAaron** [comment]
@pissang 谢谢~~~嗯 这样也可以
