### ISSUE TITLE
如何用MarkLine画指定两点的直线而不是线段？

### ISSUE THREAD

**Issue by HeatherAda** [ecomfe/echarts#6169]
### One-line summary [问题简述]
MarkLine提供的接口好像只可以指定起点和终点，如果要根据coord指定过两点的直线（或射线），应该怎么做？
可否通过两点确定一条无限的直线？
可否通过一个点和斜率来画直线？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
可以尝试用 [custom series](http://echarts.baidu.com/option.html#series-custom) 或 [graphic](http://echarts.baidu.com/option.html#graphic) 画。

**Comment by liihuu** [comment]
@HeatherAda 我也有这样的需求，请问你有解决方案了么？

**Comment by HeatherAda** [comment]
@lilihuu 解决了，用custom series

**Comment by HeatherAda** [comment]
此问题已用custom series解决
