### ISSUE TITLE
边的数值设置无效 问题 （series[i]-graph.links[i].value）

### ISSUE THREAD

**Issue by Lily-Jian** [ecomfe/echarts#6171]
### One-line summary [问题简述]

series[i]-graph.links[i].value 边的数值设置无效问题， 无法映射到边的长度。
详情请见：http://gallery.echartsjs.com/editor.html?c=xB1piwDgHZ&comment=0

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.6.2
+ Browser version [浏览器类型和版本]: Firefox
+ OS Version [操作系统类型和版本]: win7 64

### Expected behaviour [期望结果]
通过设置series[i]-graph.links[i].value，可以指定不同边的长度。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
设置 http://echarts.baidu.com/option.html#series-graph.force.edgeLength

**Comment by siyi8088** [comment]
结果有些不一致，不知道该怎么调整。 有的值较大，但是长度比较小
