### ISSUE TITLE
怎么在堆叠区域图里，每个时间段内，同时显示不同的自定义内容

### ISSUE THREAD

**Issue by gitXiaoQing** [ecomfe/echarts#6173]
### One-line summary [问题简述]
怎么在堆叠区域图里，每个时间段内，同时显示不同的自定义内容

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.4
+ Browser version [浏览器类型和版本]: chrome 版本 57.0.2987.110 (64-bit)
+ OS Version [操作系统类型和版本]: win10专业版

### Expected behaviour [期望结果]

![image](https://user-images.githubusercontent.com/24617758/28006225-fe4a4b56-6580-11e7-9e63-fc7247e43556.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
可以尝试 label 或者 markPoint 或者 custom series 或者 scatter series 写文字

**Comment by gitXiaoQing** [comment]
@100pah ，您好，已根据您的建议，用label实现如下图所示，不知道每个stack的总量是否可以获取到？
我的目的是想让label能够上下居中显示在2个区域之间（比如“周一”和“周二”之间）。
![image](https://user-images.githubusercontent.com/24617758/28196445-4eb95a8c-6883-11e7-9605-46ebc8a5d061.png)

**Comment by 100pah** [comment]
如果要先获取『总量』所对应的像素位置，再画 label 的话，或许只能用 custom series 来写文字了。
custom series 里能进行数据到坐标的转换，得到任何想要的位置。

**Comment by gitXiaoQing** [comment]
哦哦，好的，谢谢！
