### ISSUE TITLE
请问一下地图的更新频率？

### ISSUE THREAD

**Issue by waitingHao** [ecomfe/echarts#6174]
### One-line summary [问题简述]
如深圳市现在的划分已经不是6个区了，地图数据在线生成工具生成的分区只有6个。

### Expected behaviour [期望结果]

希望可以及时更新下地图数据，或者是否可以提供地图数据生成的方法或者工具？
谢谢。

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/4094309/28007185-fdb90bba-6584-11e7-8ba5-13da76c9831b.png)

**Comment by 100pah** [comment]
在线生成工具的地图数据是实时取自第三方地图服务商。

**Comment by shiyuren** [comment]
取自高德
