### ISSUE TITLE
如何使x轴达成这种效果？

### ISSUE THREAD

**Issue by TongDaDa** [ecomfe/echarts#6177]
### One-line summary [问题简述]

![qq 20170710174703](https://user-images.githubusercontent.com/23241188/28012257-cd0ba672-6597-11e7-8559-7a0d57b0a717.png)

想完成以上x轴的效果。可是轴与字之间应该怎样定义呢？ 请求一下大家的看法，目前我用线宽调了x轴的宽度，可是字体上不去呀， 有没有更好的办法呢？

刚才看了一下官方和社区的示例，基本上都是x轴纯字体的，这种块样式应该怎样更改呢？ 
```

**Comment by 100pah** [comment]
这种特殊的 x 轴效果，可以使用 [custom series](http://echarts.baidu.com/option.html#series-custom) 。
比如参见：<http://gallery.echartsjs.com/editor.html?c=xSJfES1Gr-&v=1>

**Comment by TongDaDa** [comment]
@100pah  太感谢了，谢谢谢谢

**Comment by TongDaDa** [comment]
@pissang 大神，有什么好的建议吗？ 目前为止，手动div写的这个图标....
