### ISSUE TITLE
你好，请问目前Echarts能做动态基线吗？如果做动态基线用哪个图形样例比较好

### ISSUE THREAD

**Issue by clearBird** [ecomfe/echarts#6180]
你好！
   Echarts团队

     请问目前Echarts能做动态基线吗？如果做动态基线用哪个图形样例比较好？

![qq 20170711102258](https://user-images.githubusercontent.com/25739770/28048339-f11d6fb0-6622-11e7-80a9-aaef24dc58b2.jpg)

**Comment by 100pah** [comment]
[themeRiver](http://echarts.baidu.com/examples.html#chart-type-themeRiver) 可以满足么？

**Comment by clearBird** [comment]
@100pah 这个可以实现动态基线？？？
