### ISSUE TITLE
请问雷达图的indicator如何换行？

### ISSUE THREAD

**Issue by lynnic26** [ecomfe/echarts#6190]
### One-line summary [问题简述]

当雷达图的indicator中的文字太长时，会溢出容器，溢出的部分会被切掉
开始尝试调整画布的大小，但是grid的配置貌似在雷达图中不起作用，
所以没法设置想要的padding和画布宽度

### Expected behaviour [期望结果]
能换行或者能配置画布大小和位置

**Comment by 100pah** [comment]
调整雷达图的大小请参见：
<http://echarts.baidu.com/option.html#radar.radius>
和
<http://echarts.baidu.com/option.html#radar.center>

**Comment by cobcmw** [comment]
有人解决了吗？https://github.com/apache/incubator-echarts/issues/7134
