### ISSUE TITLE
ECharts的Bar类型图表不能支持强制指定柱状图的间距

### ISSUE THREAD

**Issue by gsmlg** [ecomfe/echarts#6192]
### One-line summary [问题简述]

ECharts的Bar类型图表不能支持强制指定柱状图的间距

### 问题

用柱状图做排行榜，排行数量多少会影响数据的间距，不能通过强制指定宽度来配置图表

**Comment by 100pah** [comment]
参见：
<http://echarts.baidu.com/option.html#series-bar.barGap>
<http://echarts.baidu.com/option.html#series-bar.barCategoryGap>

**Comment by gsmlg** [comment]
@100pah 
这个只是控制bar填充的百分比
刻度之间的间距实际上是不受控制的

**Comment by 100pah** [comment]
刻度之间的间距是指什么。是否可以贴图说明要达到的效果。
