### ISSUE TITLE
tooltip多图表显示不同单位

### ISSUE THREAD

**Issue by Bkengs** [ecomfe/echarts#6194]
![image](https://user-images.githubusercontent.com/8874259/28150820-8755011c-67c9-11e7-9fef-2a2f9d7118f4.png)

如图，如何在tooltip中的每项后面添加不同的单位。通过手动配置
`    tooltip: {
        trigger: 'axis',
        formatter: '{a0}: {c0}V<br />{a1}: {c1}A<br />{a2}: {c2}W'
    },`可以达到效果，还有其他更好的解决办法吗？

**Comment by 100pah** [comment]
这方法不足够好么？
