### ISSUE TITLE
你好，我做了一个简单的图，但是我需要指定的点变色，我改如何处理？

### ISSUE THREAD

**Issue by clearBird** [ecomfe/echarts#6199]
你好！
Echarts团队
 我利用Confidence Band图例，做了一个简单的基线图，但是我不知道如何使特殊的点变色，请帮帮我，谢谢！

代码：

    myChart.setOption(option = {
    tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross',
                animation: false,
                label: {
                    backgroundColor: '#ccc',
                    borderColor: '#aaa',
                    borderWidth: 1,
                    shadowBlur: 0,
                    shadowOffsetX: 0,
                    shadowOffsetY: 0,
                    textStyle: {
                        color: '#222'
                    }
                }
            },
            formatter:'{a2}:{c2}'
          
        },

        xAxis: {
            type: 'category',
            boundaryGap : false,
            data:['一周','二周','三周','四周','五周','六周','七周','八周','九周','十周','十一周','十二周','十三周','十四周']
        },
        yAxis: {
          type : 'value'
          
        },
        series: [
        {
            name: 'L',
            type: 'line',
             data:[300, 350, 320, 260, 200, 190, 260,200, 250, 320, 260, 200, 150, 260],
            lineStyle: {
                normal: {
                    opacity: 0
                }
            },
            stack: 'confidence-band',
            symbol: 'none',
          
        },
           {
            name: 'U',
            type: 'line',
            data:[200, 200, 210, 220,300,210,120,200, 200, 210, 220,300,210,120],
            lineStyle: {
                normal: {
                    opacity: 0
                }
            },
            areaStyle: {
                normal: {
                    color: '#ccc'
                }
            },
            stack: 'confidence-band',
            symbol: 'none'
        },
        {
            name:'M',
            type: 'line',
            data:[420, 520, 420, 320,420,220, 300,320, 470, 420, 320,420,220, 300],
            symbolSize: 6,
            itemStyle: {
                normal: {
                    color: '#c23531'
                }
            },
            
            showSymbol: true
        }
    ]
    });
我如何使第九周这个点，变颜色，以示警告呢？
![9](https://user-images.githubusercontent.com/25739770/28155241-63084fd2-67e0-11e7-8231-10ec269b0325.jpg)

**Comment by 100pah** [comment]
参见：<http://gallery.echartsjs.com/editor.html?c=xr1wQ-VSB-&v=1>
