### ISSUE TITLE
图例是否能够分页？

### ISSUE THREAD

**Issue by sdtazhanghe** [ecomfe/echarts#6200]
### One-line summary [问题简述]

图例是否能够分页？

### Version & Environment [版本及环境]
+ ECharts version [v.3.6.2]:
+ Browser version [chrome最新]:
+ OS Version [win10]:

### Expected behaviour [期望结果]

能够支持图例分页

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by danhuan** [comment]
https://github.com/danhuan/echarts-changed-legend

**Comment by 100pah** [comment]
3.7 已经支持，参见：<http://echarts.baidu.com/option.html#legend.type>
