### ISSUE TITLE
Get currently displayed categories data after zoom or visual map filter changed

### ISSUE THREAD

**Issue by ahmadalibaloch** [ecomfe/echarts#6205]
I have a char with xAxis type category. What I want to get is, the categories displayed on the canvas after data zoom,  and visualMap control filter. For example if there are these categories
`['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']`
now when I move the zoom slider to only point at `['oct','nov','dec']`, the data is filtered, but what I get in the event is 
`{start: xx, end: xx}`, where `xx is number` on the scale of 100 according to where my slider is pointing. What I want to get also is, `['oct','nov','dec']` that is currently displayed on the canvas or is visible to the user. Can any give a hint or solution?

**Comment by 100pah** [comment]
Try this please:

```js
myChart.on('dataZoom', function () {
    var option = myChart.getOption();
    console.log(option.dataZoom[0].startValue, option.dataZoom[0].endValue);
});
```

I hope it can meet your requirement.

**Comment by ahmadalibaloch** [comment]
@100pah this is the problem, the `options` object of the `echart` instance should represent or give a way to to get the same `options` that is displayed on canvas at the time. Your try is not working and it just gives the dataZoom object that I set and which is `{show:true}` and nothing more.

One try could be to manually calculate the category axis position on the scale of 100 and then use the value `start` and `end` to calculate that which axis categories are coming in the selected zoom.

**Comment by ahmadalibaloch** [comment]
After checking the real data on xAxis, I have come to know that `echart` has some other method to calculate placement of categories on the scale, as I have 6 categories but their placement is not done according to above calculation, i.e. 100/6. But its different and not consistent. First value is from 0 to 10, second from 10 to 29 and third from 30 to 48 and then 49 to 70. Only someone who have worked on the echart axis scale can comment and guide about how can we get the categories displayed after zoom or may be expose the values in zoom event. Thanks.
