### ISSUE TITLE
K线图 阴线阳线规则错误

### ISSUE THREAD

**Issue by yangguoquan** [ecomfe/echarts#6208]
### One-line summary [问题简述]
K线图需要一个四位数组来画一个蜡烛
其中开盘价和收盘价决定其颜色
现在当开盘价===收盘价的时候，蜡烛颜色是跌
这是不符合常理的

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  v3.6.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
1. visualMap 支持设置蜡烛每个颜色的配置
2. 当开盘价和收盘价相等时，给另外一个颜色配置
3. 常理 当等于时， 收盘价和上一个收盘价相比较得出涨跌色

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by yoky** [comment]
完整的逻辑应该是开盘价=收盘价的时候，看涨跌幅，如果涨了就是涨的颜色，如果跌了就是跌的颜色。
我目前是自己改了源码，对signVal的值做了判断

**Comment by 100pah** [comment]
Fixed on 85ccf2d
