### ISSUE TITLE
k线图的阴阳线颜色能否通过visualMap进行设置？

### ISSUE THREAD

**Issue by bayun2** [ecomfe/echarts#6209]
### One-line summary [问题简述]
k线图的阴阳线颜色能否通过visualMap进行设置？

### Version & Environment [版本及环境]
ECharts 版本 (ECharts version):
3.6.2
浏览器类型和版本 (Browser version):
Chrome
操作系统类型和版本 (OS Version):
mac

**Comment by 100pah** [comment]
暂时不行，为何要通过 `visualMap` 进行设置呢？

**Comment by bayun2** [comment]
因为当收盘价和开盘价相等的时候，echart的源码里把k线颜色写死成了，阴线的颜色，所以理论上如果支持visualMap，可以通过visualMap来设置自定义相等情况下的颜色

**Comment by 100pah** [comment]
后续版本会改善这个问题。
但是先可以参见这个 [例子](http://gallery.echartsjs.com/editor.html?c=xHyOf6gsrb&v=1) 来自己定义颜色吧。

**Comment by bayun2** [comment]
哇，尽然还有这样的黑科技，厉害了。

**Comment by 100pah** [comment]
Fixed on 85ccf2d
