### ISSUE TITLE
请问ECharts能支持自定义圆柱体吗

### ISSUE THREAD

**Issue by zhangmc** [ecomfe/echarts#6217]
### One-line summary [问题简述]
类似筹码的圆柱体应该能够实现吗？
![unnamed qq screenshot20170717181818](https://user-images.githubusercontent.com/7735737/28264368-377681dc-6b1d-11e7-949e-9f9f0d71e9b1.jpg)

**Comment by pissang** [comment]
可以参考下这个例子？http://echarts.baidu.com/gallery/editor.html?c=pictorialBar-hill

**Comment by zhangmc** [comment]
@pissang 谢谢。
