### ISSUE TITLE
world map当鼠标移动到中国上时，图上会显示两个china字样。

### ISSUE THREAD

**Issue by catiscat** [ecomfe/echarts#6220]
### One-line summary [问题简述]
world map当鼠标移动到中国上时，图上会显示两个china字样。

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: 3.x
+ Browser version [浏览器类型和版本]: chrome 
+ OS Version [操作系统类型和版本]: linux and windows

### Expected behaviour [期望结果]
world map当鼠标移动到中国上时，图上显示一个china字样。

### ECharts option [ECharts配置项]
http://echarts.baidu.com/demo.html#map-world-dataRange

**Comment by 100pah** [comment]
谢谢反馈。已修复。

**Comment by 100pah** [comment]
谢谢反馈。已修复。
