### ISSUE TITLE
可拖动形式的不规则图形图表

### ISSUE THREAD

**Issue by TongDaDa** [ecomfe/echarts#6223]
根据拖动形式来设置图形的变化需求是这样的.

![qq 20170719111005](https://user-images.githubusercontent.com/23241188/28349051-0f2b99e0-6c73-11e7-87e2-23d883c2a86a.png)

请问，echart上有关于这样的图表吗，刚才看了一下官放的示例都是展示类型的，并没有自己操作类的.

恳求大家给一些解决方案..   谢谢。

**Comment by CWSchen** [comment]
要不，下边放一些 input  文本输入框和一个button，把要变的值，input双向数据绑定，待输入值后，点击按钮，重新调echarts方法。呵呵

**Comment by 100pah** [comment]
不知道『可拖动形式』具体指什么。
是否是这种意思呢？<http://echarts.baidu.com/demo.html#line-draggable>
