### ISSUE TITLE
graph(关系图)中是否提供有方法能够获取某个节点的相邻节点？

### ISSUE THREAD

**Issue by majian0012002** [ecomfe/echarts#6228]
### One-line summary [问题简述]

在graph图中，若点击某个节点，是否提供有方法能够获取与该节点相连的其他节点？

**Comment by CWSchen** [comment]
这个里面，有 http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA 点击事件的教程，自己试试，研究研究。

对于获取点击节点的兄弟节点，这个可以 写一个js方法，判断传你点击的 name，for循环匹配，匹配到了，直接取 你拼接好的数组 的 第 i+1 个值，就是获取点击节点的 下一个相邻节点， i-1 就是上一个节点
