### ISSUE TITLE
利用echarts插件来绘画中国地图，一个城市一个点，且每个点都做一个涟漪扩散效果时，页面上使用定时器做的文字滚动会随着地图上的点的增多而变慢

### ISSUE THREAD

**Issue by LQFpohen** [ecomfe/echarts#6233]
利用echarts插件来绘画中国地图，一个城市一个点，且每个点都做一个涟漪扩散效果时，页面上使用定时器做的文字滚动会随着地图上的点的增多而变慢。
我的项目是同一页面三个地图，一个地图最多六百多个点，且每个点回带有涟漪扩散效果。我再使用swiper插件进行淡入淡出轮播。同时，页面上有两个地方的文字是向上滚动，但是文字滚动的速度是随着地图上的点增多而变慢的，现在我设置的是文字50毫秒向上移动两个像素，地图上的点在三百多个的时候明显看出滚动很慢了，如果是六百多个点，文字滚动就相当于我们的时钟的秒针一样一颤一颤的，颤一下两个像素。
经过多次尝试与验证，得出的结论应该是echarts上的点过多造成的内存泄漏。目前我做的优化是除了当前显示的地图外，其他两个地图的数据清空，但数据超过三百也是很卡了。
请各位大神不吝指教

**Comment by 100pah** [comment]
是否能有我们能看到的例子。

**Comment by LQFpohen** [comment]
代码比较多，如果要可以运行的代码比较麻烦，我就弄三个地图的js让你看看，是否我设置有误

**Comment by LQFpohen** [comment]
Duplicate of #

**Comment by LQFpohen** [comment]
var first_timer1, first_timer2, data_len = 0,
	lbsdataAll = [],
	lbsdataAP = [],
	lbsdataAC = [],
	geoCoordMapAll = {},
	geoCoordMapAP = {},
	geoCoordMapAC = {},
	myChartAll, myChartAP, myChartAC,
	lenAll, lenAP, lenAC, mySwiper,
	map_type = '',
	opacity_timer, map_timer, faci_all, faci_ap, faci_ac,
	map_data = {
		"status": 0,
		"data": [{
			"lat": "25.594661",
			"count": 0,
			"area": "中国湖南省武汉市",
			"NAME": "武汉",
			"lng": "113.971155"
		}]
	};
$(document).click(function() {
	map_opacity(map_type);
})
$(document).mousemove(function() {
	map_opacity(map_type);
})
$(window).resize(function() {
	opacity_timer = setTimeout(function() {
		map_opacity(map_type);
	}, 100)
})
$(document).ready(function() {
	$('#box_body').css({
		"width": window.screen.availWidth,
		"height": window.screen.availHeight
	});
	mySwiper = new Swiper('#map_box', {
		direction: 'horizontal',
		autoplayDisableOnInteraction: false,
		loop: false,
		effect: 'fade',
		autoplay: 10000,
		speed: 2000,
		noSwiping: true,
		onAutoplay: function(swiper) {
			map_type = swiper.activeIndex;
			map_opacity(swiper.activeIndex);
		}
	})
})

function slider_switchover() {
	if(mySwiper.params.autoplayDisableOnInteraction == false) {
		mySwiper.params.autoplayDisableOnInteraction = true;
		$(".slider_switch_btn").attr("src", "img/start.png");
		mySwiper.stopAutoplay();
	} else {
		mySwiper.params.autoplayDisableOnInteraction = false;
		$(".slider_switch_btn").attr("src", "img/pause.png");
		mySwiper.startAutoplay();
	}
}

function map_opacity(num) {
	clearTimeout(opacity_timer);
	switch(num) {
		case 0:
			$('#map_all').css("opacity", 1);
			$('#map_AP').css("opacity", 0);
			$('#map_AC').css("opacity", 0);
			break;
		case 1:
			$('#map_all').css("opacity", 0);
			$('#map_AP').css("opacity", 1);
			$('#map_AC').css("opacity", 0);
			break;
		case 2:
			$('#map_all').css("opacity", 0);
			$('#map_AP').css("opacity", 0);
			$('#map_AC').css("opacity", 1);
			break;
		default:
			$('#map_all').css("opacity", 1);
			$('#map_AP').css("opacity", 0);
			$('#map_AC').css("opacity", 0);
			break;
	}
}
refresh_map();

function refresh_map() {
	mapInit();
	setTimeout(function() {
		window.location.reload();
	}, 1000 * 60 * 10)
	first_timer1 = setTimeout(function() {
		lenAll = lenAll ? lenAll : 0;
		lenAP = lenAP ? lenAP : 0;
		lenAC = lenAC ? lenAC : 0;
//		data_len = lenAll + lenAP + lenAC;
//		data_len = data_len ? data_len : 0;
		rank_maps();
		dataAll();
		tableType();
	}, 1000 * 2)
	first_timer2 = setTimeout(function() {
		loadDate();
	}, 500)

}

function loadDate() {
	clearTimeout(map_timer);
	clearTimeout(first_timer2);
	map_timer = setTimeout(function() {
		loadDate();
	}, 1000 * 60 * 5);
	map_alls();
	map_aps();
	map_acs();
}

function map_alls() {
	var often_num = 0;
	facility_all(often_num);
}

function facility_all(num) {
	clearTimeout(faci_all);
	$.ajax({
		type: "get",
		url: "./json/alls.json",
		async: true,
		success: function(data) {
			if(typeof data == "string") {
				alls(map_data);
				error_all(num);
			} else {
				lbsdataAll = [];
				geoCoordMapAll = {};
				if(!data.status) {
//					alls(map_data);
					localStorage.oldAllData = JSON.stringify(data);
					alls(data);
				} else {
					if(data.data == "devmap为空") {
						alls(map_data);
						return false;
					} else {
						if(localStorage.oldAllData == '') {
							error_all(num);
						} else {
							data = JSON.parse(localStorage.oldAllData);
							alls(data);
						}
					}
				}
			}
		},
		error: function(d) {
			if(localStorage.oldAllData == '' || localStorage.oldAllData == undefined) {
				error_all(num);
			} else {
				data = JSON.parse(localStorage.oldAllData);
				alls(data);
			}
		}
	})
}

function error_all(num) {
	if(num == 0) {
		alls(map_data);
	}
	faci_all = setTimeout(function() {
		num++;
		if(num < 4) {
			facility_all(num);
		}
	}, 1000 * 10)
}

function alls(data) {
	clearTimeout(faci_all);
	var genre = "all";
	lenAll = data.data.length;
	for(var i = 0; i < lenAll; i++) {
		var data_item = {
			name: data.data[i].NAME,
			value: data.data[i].count
		};
		lbsdataAll.push(data_item);
		geoCoordMapAll[data.data[i].NAME] = [data.data[i].lng, data.data[i].lat];
	}
	switchingData(genre)
}

function map_aps() {
	var often_num = 0;
	facility_ap(often_num)
}

function facility_ap(num) {
	clearTimeout(faci_ap);
	$.ajax({
		type: "get",
		url: "./json/aps.json",
		async: true,
		success: function(data) {
			if(typeof data == "string") {
				aps(map_data);
				error_ap(num);
			} else {
				lbsdataAP = [];
				geoCoordMapAP = {};
				if(!data.status) {
//					aps(map_data);
					localStorage.oldApData = JSON.stringify(data);
					aps(data);
				} else {
					if(data.data == "devmap为空") {
						aps(map_data);
						return false;
					} else {
						if(localStorage.oldApData == '') {
							error_ap(num);
						} else {
							data = JSON.parse(localStorage.oldApData);
//							aps(map_data);
							aps(data);
						}
					}
				}
			}
		},
		error: function(d) {
			if(localStorage.oldApData == '' || localStorage.oldApData == undefined) {
				error_ap(num);
			} else {
				data = JSON.parse(localStorage.oldApData);
				aps(data);
			}
		}
	})
}

function error_ap(num) {
	if(num == 0) {
		aps(map_data);
	}
	faci_ap = setTimeout(function() {
		num++;
		if(num < 4) {
			facility_ap(num);
		}
	}, 1000 * 10)
}

function aps(data) {
	clearTimeout(faci_ap);
	var genre = "AP";
	lenAP = data.data.length;
	for(var i = 0; i < lenAP; i++) {
		var data_item = {
			name: data.data[i].NAME,
			value: data.data[i].count
		};
		lbsdataAP.push(data_item);
		geoCoordMapAP[data.data[i].NAME] = [data.data[i].lng, data.data[i].lat];
	}
	switchingData(genre);
}

function map_acs() {
	var often_num = 0;
	facility_ac(often_num);
}

function facility_ac(num) {
	clearTimeout(faci_ac);
	$.ajax({
		type: "get",
		url: "./json/acs.json",
		async: true,
		success: function(data) {
			if(typeof data == "string") {
				acs(map_data);
				error_ac(num);
			} else {
				lbsdataAC = [];
				geoCoordMapAC = {};
				if(!data.status) {
//					acs(map_data);
					localStorage.oldAcData = JSON.stringify(data);
					acs(data);
				} else {
					if(data.data == "devmap为空") {
						acs(map_data);
						return false;
					} else {
						if(localStorage.oldAcData == '' || localStorage.oldAcData == undefined) {
							error_ac(num)
						} else {
							data = JSON.parse(localStorage.oldAcData);
//							acs(map_data);
							acs(data);
						}
					}

				}
			}
		},
		error: function(d) {
			if(localStorage.oldAcData == '' || localStorage.oldAcData == undefined) {
				error_ac(num);
			} else {
				data = JSON.parse(localStorage.oldAcData);
				acs(data);
			}
		}
	})
}

function error_ac(num) {
	if(num == 0) {
		acs(map_data);
	}
	faci_ac = setTimeout(function() {
		num++;
		if(num < 4) {
			facility_ac(num);
		}
	}, 1000 * 10)
}

function acs(data) {
	clearTimeout(faci_ac);
	var genre = "AC";
	lenAC = data.data.length;
	for(var i = 0; i < lenAC; i++) {
		var data_item = {
			name: data.data[i].NAME,
			value: data.data[i].count
		};
		lbsdataAC.push(data_item);
		geoCoordMapAC[data.data[i].NAME] = [data.data[i].lng, data.data[i].lat];
	}
	switchingData(genre)
}

function mapInit() {
	option = {
		backgroundColor: "rgba(4,4,4,0)",
		title: {
			target: 'self',
			right: '44%',
			itemGap: 50,
			textStyle: {
				fontSize: 24,
				fontWeight: 'normal'
			}
		},
		tooltip: {
			trigger: 'item'
		},
		legend: {
			orient: 'vertical',
			itemGap: 10,
			itemHeight: 14,
			show: true,
			y: 'bottom',
			x: 'right',
			data: [{
				name: '全部设备分布',
				textStyle: {
					color: '#ff7f00'
				}
			}, {
				name: '大设备分布',
				textStyle: {
					color: '#4ff402'
				}
			}, {
				name: '小设备分布',
				textStyle: {
					color: '#eef81b'
				}
			}],
			selected: {
				'全部设备分布': true,
				'大设备分布': true,
				'小设备分布': true
			},
			selectedMode: false,
			textStyle: {
				fontSize: 20,
				fontWeight: 'normal'
			}
		},
		geo: {
			map: 'china',
			label: {
				emphasis: {
					show: true
				}
			},
			zoom: 1.2,
			show: true,
			nameMap: {
				'China': '中国'
			},
			roam: false,
			itemStyle: {
				normal: {
					areaColor: 'rgba(255,255,255,0)',
					borderColor: '#31c5de'
				},
				emphasis: {
					areaColor: 'pink'
				}
			}
		},
		series: [{
			name: '全部设备分布',
			type: 'effectScatter',
			coordinateSystem: 'geo',
			effectType: 'ripple',
			rippleEffect: {
				period: 6,
				scale: 10,
				brushType: 'stroke',
			},
			legendHoverLink: true,
			symbol: 'circle',
			symbolSize: function(val) {
				if(val[2] <= 5) {
					return 0
				} else if(val[2] > 5 && val[2] <= 10) {
					return 5
				} else if(val[2] > 10 && val[2] <= 20) {
					return 6
				} else if(val[2] > 20) {
					return 7
				}
			},
			hoverAnimation: true,
			label: {
				normal: {
					formatter: '',
					position: 'top',
					show: true
				}
			},
			itemStyle: {
				normal: {
					color: '#ff7f00'
				}
			},
			zlevel: 1
		}, {
			name: '大设备分布',
			type: 'effectScatter',
			coordinateSystem: 'geo',
			effectType: 'ripple',
			rippleEffect: {
				period: 6,
				scale: 10,
				brushType: 'stroke',
			},
			legendHoverLink: true,
			symbol: 'circle',
			symbolSize: function(val) {
				if(val[2] <= 5) {
					return 0
				} else if(val[2] > 5 && val[2] <= 10) {
					return 5
				} else if(val[2] > 10 && val[2] <= 20) {
					return 6
				} else if(val[2] > 20) {
					return 7
				}
			},
			hoverAnimation: true,
			label: {
				normal: {
					formatter: '',
					position: 'top',
					show: true
				}
			},
			itemStyle: {
				normal: {
					color: '#4ff402'
				}
			},
			zlevel: 1
		}, {
			name: '小设备分布',
			type: 'effectScatter',
			coordinateSystem: 'geo',
			effectType: 'ripple',
			rippleEffect: {
				period: 6,
				scale: 10,
				brushType: 'stroke',
			},
			legendHoverLink: true,
			symbol: 'circle',
			symbolSize: function(val) {
				if(val[2] <= 5) {
					return 0
				} else if(val[2] > 5 && val[2] <= 10) {
					return 5
				} else if(val[2] > 10 && val[2] <= 20) {
					return 6
				} else if(val[2] > 20) {
					return 7
				}
			},
			hoverAnimation: true,
			label: {
				normal: {
					formatter: '',
					position: 'top',
					show: true
				}
			},
			itemStyle: {
				normal: {
					color: '#eef81b'
				}
			},
			zlevel: 1
		}, {
			type: 'effectScatter',
			coordinateSystem: 'geo',
			animation: false,
			legendHoverLink: true,
			symbol: 'circle',
			large: true,
			largeThreshold: 100,
			symbolSize: function(val) {
				if(val[2] <= 5 && val[2] > 0) {
					return 4
				} else {
					return 0
				}
			},
			hoverAnimation: true,
			label: {
				normal: {
					formatter: '',
					position: 'top',
					show: true
				}
			},
			itemStyle: {
				normal: {}
			},
			zlevel: 1
		}]
	};
}

function switchingData(genre) {
	switch(genre) {
		case "all":
			all_option();
			break;
		case "AP":
			ap_option();
			break;
		default:
			ac_option();
			break;
	}
}

function all_option() {
	myChartAll = echarts.getInstanceByDom(document.getElementById("map_all"));
	if(myChartAll === undefined) {
		myChartAll = echarts.init(document.getElementById("map_all"));
	}
	option.title.text = "全部设备分布图";
	option.title.textStyle.color = '#ff7f00';
	option.series[3].name = "全部设备分布";
	option.series[3].itemStyle.normal.color = "#ff7f00";
	option.legend.selected['全部设备分布'] = true;
	option.legend.selected['大设备分布'] = false;
	option.legend.selected['小设备分布'] = false;
	option.series[3].data = convertDataAll(lbsdataAll.sort(function(a, b) {
		return b.value - a.value;
	}).slice(0, lenAll), "false");
	option.series[0].data = convertDataAll(lbsdataAll.sort(function(a, b) {
		return b.value - a.value;
	}).slice(0, lenAll), "true");
	myChartAll.clear();
	myChartAll.setOption(option, true);
	lbsdataAll = [];
	geoCoordMapAll = {};
	lenAll;
}

function ap_option() {
	myChartAP = echarts.getInstanceByDom(document.getElementById("map_AP"));
	if(myChartAP === undefined) {
		myChartAP = echarts.init(document.getElementById("map_AP"));
	}
	option.title.text = "大设备分布图";
	option.title.textStyle.color = '#4ff402';
	option.series[3].name = "大设备分布";
	option.series[3].itemStyle.normal.color = "#4ff402";
	option.series[3].data = convertDataAP(lbsdataAP.sort(function(a, b) {
		return b.value - a.value;
	}).slice(0, lenAP), "false");
	option.series[1].data = convertDataAP(lbsdataAP.sort(function(a, b) {
		return b.value - a.value;
	}).slice(0, lenAP), "true");
	option.legend.selected['全部设备分布'] = false;
	option.legend.selected['大设备分布'] = true;
	option.legend.selected['小设备分布'] = false;
	myChartAP.clear();
	myChartAP.setOption(option, true);
	lbsdataAP = [];
	geoCoordMapAP = {};
	lenAP;
}

function ac_option() {
	myChartAC = echarts.getInstanceByDom(document.getElementById("map_AC"));
	if(myChartAC === undefined) {
		myChartAC = echarts.init(document.getElementById("map_AC"));
	}
	option.title.text = "小设备分布图";
	option.title.textStyle.color = '#eef81b';
	option.series[3].name = "小设备分布";
	option.series[3].itemStyle.normal.color = "#eef81b";
	option.series[3].data = convertDataAC(lbsdataAC.sort(function(a, b) {
		return b.value - a.value;
	}).slice(0, lenAC), "false");
	option.series[2].data = convertDataAC(lbsdataAC.sort(function(a, b) {
		return b.value - a.value;
	}).slice(0, lenAC), "true");
	option.legend.selected['全部设备分布'] = false;
	option.legend.selected['大设备分布'] = false;
	option.legend.selected['小设备分布'] = true;
	myChartAC.clear();
	myChartAC.setOption(option, true);
	lbsdataAC = [];
	geoCoordMapAC = {};
	lenAC;
}

function convertDataAll(data, type) {
	var res = [];
	console.log(type);

	console.log(typeof type);

	for(var i = 0; i < data.length; i++) {
		var geoCoord = geoCoordMapAll[data[i].name];
		if(geoCoord) {
			if(type == "true") {
				if(data[i].value > 5) {
					res.push({
						name: data[i].name,
						value: geoCoord.concat(data[i].value)
					});
				}
			} else {
				if(data[i].value <= 5) {
					res.push({
						name: data[i].name,
						value: geoCoord.concat(data[i].value)
					});
				}
			}
		}
	}
	console.log(res.length)
	data_len += res.length;
	return res;
};

function convertDataAP(data, type) {
	var res = [];
	for(var i = 0; i < data.length; i++) {
		var geoCoord = geoCoordMapAP[data[i].name];
		if(geoCoord) {
			if(type == "true") {
				if(data[i].value > 5) {
					res.push({
						name: data[i].name,
						value: geoCoord.concat(data[i].value)
					});
				}
			} else {
				if(data[i].value <= 5) {
					res.push({
						name: data[i].name,
						value: geoCoord.concat(data[i].value)
					});
				}
			}
		}
	}
	data_len += res.length;
	return res;
};

function convertDataAC(data, type) {
	var res = [];
	for(var i = 0; i < data.length; i++) {
		var geoCoord = geoCoordMapAC[data[i].name];
		if(geoCoord) {
			if(type == "true") {
				if(data[i].value > 5) {
					res.push({
						name: data[i].name,
						value: geoCoord.concat(data[i].value)
					});
				}
			} else {
				if(data[i].value <= 5) {
					res.push({
						name: data[i].name,
						value: geoCoord.concat(data[i].value)
					});
				}
			}
		}
	}
	data_len += res.length;
	return res;
};
