### ISSUE TITLE
Yaxis labels are being cut off

### ISSUE THREAD

**Issue by akvaliya** [ecomfe/echarts#6234]
I have used plugin ngEcharts for display charts. is displays like below.
![visitors by industries](https://user-images.githubusercontent.com/25152577/28374012-266d0834-6cc1-11e7-9201-1cf1dca012d1.png)

As you can see yAxis labels are being cut off. can anyone point me on the direction to how to prevent this or increase yAxis label area or decrease chart area?

**Comment by CWSchen** [comment]
please have a try  css padding 
for example   
<div id="main" style="width:100%;height:500px;border:1px solid #ddd;padding:50px;"></div>

**Comment by 100pah** [comment]
Increase [grid.left](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.left),

Or set [grid.containLabel](https://ecomfe.github.io/echarts-doc/public/en/option.html#grid.containLabel) as `true`.

**Comment by akvaliya** [comment]
@100pah Thanks. Got it working!

**Comment by iamtekson** [comment]
Y-axis label name is still cut off. Can anyone suggest to me how to make the y-axis name visible?
