### ISSUE TITLE
你们好,请问如何手动触发折线图上指定点的点击事件

### ISSUE THREAD

**Issue by JasonMgz0411** [ecomfe/echarts#6235]
![image](https://user-images.githubusercontent.com/26475340/28398537-31ecfa4c-6d3a-11e7-8a71-644a82f7b475.png)

**Comment by JasonMgz0411** [comment]
就像我想自动触发出倒数第二个点的事件

**Comment by 100pah** [comment]
并没有简单的方法来触发，除非为每个圆点分别建立个圆点覆盖在上面，然后再调用新创建的圆点的 trigger 方法。
