### ISSUE TITLE
能否自定义legend的选中事件

### ISSUE THREAD

**Issue by WonderfulFuture** [ecomfe/echarts#6236]
有个业务需求，需要在选中图例（legend）时加入自己的业务逻辑，比如默认显示所有series里面的数据，点击某一个legend后，自定义显示某几项series里面的数据，不知这个需求能否实现？

 
+ ECharts version [ECharts 版本]:3.1.2
+ Browser version [浏览器类型和版本]: Chrome 59
+ OS Version [操作系统类型和版本]: Windows 10

**Comment by CWSchen** [comment]
这个里面，有 http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA   点击事件的教程，自己试试，研究研究。

**Comment by 100pah** [comment]
可监听 [legendselectchanged](http://echarts.baidu.com/api.html#events.legendselectchanged) 事件。

**Comment by mqliutie** [comment]
如何触发 ` legendselectchanged`  事件, 在我没有点击 `legend` 的情况下

**Comment by yyccQQu** [comment]
> 如何触发 ` legendselectchanged` 事件, 在我没有点击 `legend` 的情况下
> 
> -----分割线-------
> 
> ```
> myChart.dispatchAction({
>     type: 'legendToggleSelect',
>     name: '上海 Top10'
> });
> ```

myChart.on('legendselectchanged', function (param) {
                var selectedName = param.name; 
                console.log(selectedName, "selectedName",param);
})
