### ISSUE TITLE
如何获取dataZoom缩放的位置

### ISSUE THREAD

**Issue by arssam** [ecomfe/echarts#6239]
如题，目的是：缩放/移动，获取缩放处于的位置，判断当startValue===0时，加载数据。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:   v3.62
+ Browser version [浏览器类型和版本]:  微信浏览器
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by arssam** [comment]
解决了，通过this.chart.getOption().dataZoom

**Comment by cnyb-kwange** [comment]
myChart.getOption().dataZoom 返回的值 startValue ， endValue 与 x轴值 不是一样的值
![image](https://user-images.githubusercontent.com/9961863/40092652-f0ee3ed6-58f0-11e8-9c5b-0bf21c4a8fe3.png)

比图中显示的2860.15625 ， 6764.0625 都大。

这是怎么回事呢？

**Comment by chenchunjie** [comment]
x轴怎么获取缩放后的起始时间
