### ISSUE TITLE
关于数据视图出现多个滚动条的问题

### ISSUE THREAD

**Issue by itboy2java** [ecomfe/echarts#6240]
### One-line summary [问题简述]
数据视图下在会出现多个滚动条，textarea以及外层都会出现滚动条

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: IE11，谷歌：59.0.3071.115
+ OS Version [操作系统类型和版本]: window10

### Expected behaviour [期望结果]
可以提供可是设置textarea的style或将textarea以及父级元素高宽分配好使其没有滚动条。

### ECharts option [ECharts配置项]

```javascript
option = {
        feature : {
	    dataView : {show: true, readOnly: true},
	    restore: {},
	    saveAsImage : {show: true}
        }
}

```

### Other comments [其他信息]

![k8bu8 ums9w n4z 33sa 1](https://user-images.githubusercontent.com/11781463/28407900-68fc315a-6d68-11e7-8941-8761947f0749.png)

**Comment by CWSchen** [comment]
你说的这些，都是可以 通过js 实现的，加油

**Comment by 100pah** [comment]
不了解你的程序环境。可以用 css 来修正。

**Comment by itboy2java** [comment]
是可以通过js来修改元素的属性，但是我觉得对于产品而言，提供一个更加灵活的接口是更好的方式。
