### ISSUE TITLE
地图的收缩和移动tooltip不能跟随移动

### ISSUE THREAD

**Issue by duanliang** [ecomfe/echarts#6243]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.6.2 源代码
+ Browser version [浏览器类型和版本]: chrome 59.0.3071.115（正式版本）
+ OS Version [操作系统类型和版本]: windows10 10.00.15063

### Expected behaviour [期望结果]

tooltip组件,geo组件，map组件
tooltip在地图组件收缩和移动地图的时候，tooltip设置一直显示，但是tooltip不跟着移动；
另外，不知道有不有map组件的收缩或者移动地图的事件？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
map 缩放移动的事件是 `geoRoam`。

**Comment by yijialee** [comment]
我也是出现类似的问题：
只是用鼠标滚轮缩放地图的时候，tooltip的位置是正常的。
如果使用鼠标左键移动地图，tooltip的位置就会朝相反方向移动相同的距离。如果用鼠标连续平移地图数次后，有可能tooltip显示范围就超出组件范围了。

**Comment by duanliang** [comment]
@100pah 那我怎么在geoRoam的事件里面获取tooltip对象实时的转换屏幕坐标给tooltip的position设置最新的值呢?

**Comment by yijialee** [comment]
@duanliang http://echarts.baidu.com/option.html#series-effectScatter.tooltip.position

**Comment by duanliang** [comment]
我用监听geoRoam的事件，在此事件中我调用了“showTip”的方法，暂时解决了地图的缩放和移动时候tooltip不能跟随的问题；
