### ISSUE TITLE
官方样例les-miserables出错

### ISSUE THREAD

**Issue by fausturs** [ecomfe/echarts#6244]
### One-line summary [问题简述]
通过参考文档中的上手教程大概写了个框架，然后将官方这个需要导入数据的例子复制进去了，结果一直转菊花。
花了一个下午我才搞定，原来是没有引入一个dataTool.js和jQuery。
是的，我已经自己搞定了，我来是想说，能不能把官方样例的完整源代码开发下载啊。光下载个option谁知道哪天我又遇到问题了。。。。。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2 源代码
+ Browser version [浏览器类型和版本]:Safari 10.1.2
+ OS Version [操作系统类型和版本]: macOS 10.12.6

### Expected behaviour [期望结果]
官方样例能看到全部源代码，不是每个用这个框架的人都点满了js精通，至少标识一下依赖嘛。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by yijialee** [comment]
使用浏览器开发者工具查看就可以了，自己动手丰衣足食嘛
