### ISSUE TITLE
 tooltip 文字的阴影效果如何去掉

### ISSUE THREAD

**Issue by sky007z** [ecomfe/echarts#6249]
![qq 20170721161424](https://user-images.githubusercontent.com/24928355/28455094-5e16b1ca-6e30-11e7-8c45-698a5c62ea95.png)

**Comment by 100pah** [comment]
可能是外部的 css 影响了 tooltip 中的文字？
可以用这个定制：<http://echarts.baidu.com/option.html#tooltip.extraCssText>
