### ISSUE TITLE
series.dimensions指定维度图表无法绘制

### ISSUE THREAD

**Issue by lanyuechen** [ecomfe/echarts#6252]
### One-line summary [问题简述]
使用dimensions指定维度名称时图表不能正常绘制

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: Chrome 版本 59.0.3071.115（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: Mac OS X EL Capitan

### Expected behaviour [期望结果]
通过dimensions指定维度名称，然后通过encode根据名称指定不动维度对应的坐标轴、tooltip等

### ECharts option [ECharts配置项]

```javascript
option = {
    dimensions: ['a', 'b'],
    encode: {
        x: 'a',
        y: 'b'
    },
    xAxis: [
        {
            type: 'category',
            data: ['1月','2月']
        }
    ],
    yAxis: [
        {
            type: 'value'
        }
    ],
    series: [
        {
            type:'bar',
            data:[
                ['1月', 2.0],
                ['2月', 4.9]
            ]
        }
    ]
};
```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/7270095/28488408-f24771a8-6edb-11e7-819e-d08ba1825155.png)

**Comment by Amy-1989** [comment]
hi,这个bug改完啥时候上线呢？

**Comment by 100pah** [comment]
下个版本，8月初。

**Comment by iamwelk** [comment]
同样的问题，line的dimensions配置之后无法渲染出来图表

demo链接：http://gallery.echartsjs.com/editor.html?c=xH1C6W84rM&comment=0
