### ISSUE TITLE
饼图无数据

### ISSUE THREAD

**Issue by Gyyi** [ecomfe/echarts#6257]
### One-line summary [问题简述]
饼图无数据时一片空白，能否像曲线图无数据那样，显示一个空白饼图

![qq 20170724105937](https://user-images.githubusercontent.com/16659067/28506664-7d00deea-705f-11e7-82d7-d11624e24e3c.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-pie.stillShowZeroSum 设为 false 可以实现有 label 但没扇形的效果。因为理论上没有数据的时候，显示成什么样的饼才合适呢？如果你有特定的需求的话，可以对空数据设置假的数据以显示饼图，也就是说，把 value 设为不为 0 的数字，但是 label、tooltip 等手动设为 0。

**Comment by Gyyi** [comment]
感谢楼上建议，由此得到一个灵感，无数据时候用option配置来显示无数据的样式
![qq 20170724180914](https://user-images.githubusercontent.com/16659067/28518663-3cc3c3b0-709b-11e7-94d5-6cecf8a746ed.png)
