### ISSUE TITLE
echarts 折线图可以给不同的点设置不同的symbol吗

### ISSUE THREAD

**Issue by nikomal** [ecomfe/echarts#6260]
### One-line summary [问题简述]

echarts 折线图可以给不同的点设置不同的symbol吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
虽然严格来说一个系列的只能都一样（http://echarts.baidu.com/option.html#series-line.data.symbol），但是想实现这种效果的话也不是不可以。比如除了折线图产生折线之外，另外在 series 中设几个散点图，每种 symbol 设一个 series，然后显示在折线图同样的位置。

**Comment by mytharcher** [comment]
可以看看 [`markPoint `](http://echarts.baidu.com/option.html#series-line.markPoint) 能不能满足。

**Comment by pissang** [comment]
可以的，http://gallery.echartsjs.com/editor.html?c=xH16uRB7UW
