### ISSUE TITLE
多个grid中的柱形图能否共用一个Y轴

### ISSUE THREAD

**Issue by Potato2009** [ecomfe/echarts#6264]
### 多个grid中的柱形图能否共用一个Y轴 [问题简述]
有需求做多图表阵列排列，横排的图表希望共用一个Y轴， 使用grid拼接后，发现各图表之间刻度计算是私有的，有没有方法可以共享Y轴刻度计算

### Version & Environment [版本及环境]
+ ECharts  3.6 [ECharts 版本]:
+ Chrome 59.0.3071.115 [浏览器类型和版本]:
+ OSX 10.12.5 [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没有支持这个的打算
