### ISSUE TITLE
为什么主标题和副标题不能水平在一行

### ISSUE THREAD

**Issue by zhengyanwen** [ecomfe/echarts#6265]
为什么主标题和副标题不能水平在一行，很多人都有这个需求！！！

**Comment by pissang** [comment]
你可以用两个 title 实现这个功能

**Comment by lizesheng0313** [comment]
title: {
            text: '123',
            textStyle: {
                fontWeight: 'normal',
                color: color2,
                fontSize: '28'
            },
            x: 'center',
            y: 'center',
        },
        title: {
            text :'分',
            textStyle:{
                fontWeight: 'normal',
                color: color2,
                fontSize: '14'
            },
            x: 'center',
            y: 'center'
        },
我这样写会覆盖，是不是我理解错了
