### ISSUE TITLE
line-stack dome stack: '总量', 配置此项后，画出的图异常

### ISSUE THREAD

**Issue by lcp0578** [ecomfe/echarts#6270]
### line-stack dome stack: '总量', 配置此项后，画出的图异常

demo: http://echarts.baidu.com/demo.html#line-stack

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: chrome 52.0.2743.116 m
+ OS Version [操作系统类型和版本]: win7 64

### Expected behaviour [期望结果]
错误结果截图：
![1](https://user-images.githubusercontent.com/10859621/28560398-15733752-714d-11e7-8f67-2f6fe7df5a0e.png)

去掉：stack后，结果正确
![2](https://user-images.githubusercontent.com/10859621/28560365-eb159720-714c-11e7-8f97-8c673d56063d.png)

### ECharts option [ECharts配置项]

```javascript
option = {
    // 数据量较大，见附件option.zip
[option.zip](https://github.com/ecomfe/echarts/files/1172302/option.zip)


}

```

**Comment by mamtou** [comment]
![20170725161017](https://user-images.githubusercontent.com/2018519/28562143-bfe2a49c-7153-11e7-95f5-e382d26d2ffa.png)

**Comment by lcp0578** [comment]
thanks, =_+
