### ISSUE TITLE
平行坐标图形在使用phantomjs打开页面时候报错，应该是Array.from在phantomjs下不支持导致的

### ISSUE THREAD

**Issue by snowzijun** [ecomfe/echarts#6271]
### One-line summary [问题简述]

平行坐标图形在使用phantomjs打开页面时候报错，应该是Array.from在phantomjs下不支持导致的，然后做的兼容处理有问题。

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: phantomjs 2.1.1
+ OS Version [操作系统类型和版本]: window

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你看下是不是自己代码中的问题，ec 代码中没有 Array.from

**Comment by snowzijun** [comment]
else if (TYPED_ARRAY[typeStr]) {
	            result = source.constructor.from(source);
	        }
echarts源代码3048行

**Comment by pissang** [comment]
看到了，谢谢反馈
