### ISSUE TITLE
折线图堆叠，当series 中的data相等时，生成的echarts折线图，不重合，是什么原因？

### ISSUE THREAD

**Issue by tangpenny** [ecomfe/echarts#6275]
![image](https://user-images.githubusercontent.com/11501466/28586706-44751304-71a7-11e7-8459-5e9f3681c0c2.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chengmin** [comment]
这个是堆叠图，不同series的数据是一个一个往上堆叠的。去掉series中的stack属性即可满足你的需求

**Comment by tangpenny** [comment]
提问后又发现自己理解错了，thx
