### ISSUE TITLE
力导向图，动态画线怎样显示连线的生成过程

### ISSUE THREAD

**Issue by GavinLin168** [ecomfe/echarts#6280]
[问题简述]
项目想通过力导向图画关系图，现在节点的初始关系未知，需要生成导向图后，动态指定节点的调用关系并显示关系连线的生成轨迹。以下（1）、（2）已实现，在这个基础上，能否在鼠标的移动过程中（即mousemove）显示连线轨迹，而不是mouseup得到target信息刷新导向图后才看到连线。
（1）java项目后台生成一个力导向图可展示的json串，返回给前台页面，初始时，连线links内容为空；
（2）捕捉节点的mousedown事件，将ServiceA 记录为 source 节点，移动鼠标（mousemove）到另一个节点ServiceB，松开鼠标mouseup记录ServiceB为target节点，将source、target信息放入links中，最后刷新力导向图得到ServiceA->ServiceB的调用连线
{
    "nodes": [
        {
            "name": "serviceA",
            "category": 1,
            "value": 30,
            "label": "serviceA",
            "symbolSize": 90
        },
        {
            "name": "serviceB",
            "category": 0,
            "value": 30,
            "label": "serviceB",
            "symbolSize": 90
        }
    ],
    "links": [
    ]
}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
鼠标的移动过程中（即mousemove）显示连线轨迹

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
要显示连线轨迹，可以直接使用 zrender 的图形元素来进行绘制。
可以参见：<http://gallery.echartsjs.com/editor.html?c=xHJoqu2H8W&v=1>

**Comment by GavinLin168** [comment]
@100pah ，十分感谢问题已完美解决！！

**Comment by pumpkindev** [comment]
@100pah  地址打不开，有没有新的地址呢

**Comment by whitegerry** [comment]
> @100pah 地址打不开，有没有新的地址呢

https://www.makeapie.com/editor.html?c=xHJoqu2H8W&v=1
