### ISSUE TITLE
地图显示问题

### ISSUE THREAD

**Issue by huanledeniuduzi** [ecomfe/echarts#6287]
### One-line summary [问题简述]
想要只显示乡镇范围地图，其余部分不显示。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
想要只显示乡镇范围地图，其余部分不显示。（只显示阴影部分）但是显示的乡镇范围的地图还要有全部地图的这种功能。可不可以实现？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]
![qq 20170726173400](https://user-images.githubusercontent.com/30464088/28614828-ade46830-7229-11e7-98a7-d7f23ad8f068.png)

**Comment by pissang** [comment]
没懂你的意思
