### ISSUE TITLE
地图两种引入方式的适用场景

### ISSUE THREAD

**Issue by luyuekai** [ecomfe/echarts#6288]
### One-line summary [问题简述]
想请教一下, 引入地图的两种方式,一种是js ,另一种是 json.
这两种方式的优缺点是什么呀?  适用场景有什么建议吗?
先谢谢啦!!

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
js 是标签/模块引入，更方便，支持跨域，json 可以异步加载，不能跨域
