### ISSUE TITLE
动态插入数据疑问

### ISSUE THREAD

**Issue by xuekew** [ecomfe/echarts#6290]
echarts 2版本有addDATA接口，插入数据，3版本接口没有了，用什么方法可以实现动态的插入？

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0
