### ISSUE TITLE
有toolbox点击数据视图的事件监听方法吗

### ISSUE THREAD

**Issue by liuzngit** [ecomfe/echarts#6296]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
现在没有。如果有需要的话，是否可以具体描述清需求：
比如你需要做什么事情，期望什么点击什么而触发的监听方法。

**Comment by liuzngit** [comment]
使用到dataView的optionToContent方法生成自定义的页面，需要使用js代码辅助生成页面功能以及某些元素，所以需要监听到toolbox的触发事件              
《ps:以使用侧面方法解决》

**Comment by Greensleeves0906** [comment]
遇到了相同问题，急求侧面解决的思路

**Comment by liuzngit** [comment]
一个做法是，不使用toolbox，而使用一个和toolbox标记一样的icon，定位到合适的位置，给那个icon添加事件，显隐echats和你需要图表等
另一个做法是，给echats的父元素整体添加点击事件，然后判断，具体做法忘记了
