### ISSUE TITLE
散点图scatter emphasis.formatter 无效

### ISSUE THREAD

**Issue by tianzk** [ecomfe/echarts#6297]
###[问题简述]

散点图 设置series[i]-scatter.label.emphasis，formatter不生效。

normal状态无此问题。

官方示例：http://echarts.baidu.com/gallery/editor.html?c=bubble-gradient

鼠标放到item上，显示2015 或1990而不是国家名。
![qq20170727-153916](https://user-images.githubusercontent.com/6689676/28659372-cac99dfe-72e1-11e7-9c8f-571b6744998e.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.x
+ Browser version [浏览器类型和版本]:chrome 59.0.3
+ OS Version [操作系统类型和版本]:macOS 10.12.3

### Expected behaviour [期望结果]

formatter生效

**Comment by pissang** [comment]
设置 normal.formatter 就行

**Comment by wmasfoe** [comment]
> 设置 normal.formatter 就行

人家问题写了，formatter 不生效
