### ISSUE TITLE
我对于echart需要引入的文件不是很了解，请帮忙解惑。

### ISSUE THREAD

**Issue by setLylToxlx** [ecomfe/echarts#6298]
我在官网上下了几个demo，其中的demo都引入了下列的几个文件，分别是：echart.min.js、ecStat.min.js、dataTool.min.js、china.js、world.js、api.map.baidu.com/api?v=2.0&ak=ZUONbpqGBsYGXNIYHicvbAbM、bmap.min.js，其中的ecStat.js和dataTool.js的作用是什么？我在官网并没有看到什么解释，想知道这几个具体的功能是什么？

**Comment by swagerYe** [comment]
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script> 核心
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts-stat/ecStat.min.js"></script> 导出工具
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/extension/dataTool.min.js"></script> 数据关系工具 关系图用
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/map/js/china.js"></script> 中国地图
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/map/js/world.js"></script> 世界地图
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=ZUONbpqGBsYGXNIYHicvbAbM"></script> 百度地图api验证
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/extension/bmap.min.js"></script> 地图数据工具

**Comment by lxn07122945** [comment]
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=ZUONbpqGBsYGXNIYHicvbAbM"></script>      我服了，能不能把这里边的地图ak跟开发者说明一下替换成自己的啊，一群人根本不看代码就复制粘贴使用了，一个个都是地图api校验失败，给我们的工作造成了很大的困扰
