### ISSUE TITLE
so much [Violation] requestAnimationFrame   handler took 90ms  when render more chart instances

### ISSUE THREAD

**Issue by jeffmobiles** [ecomfe/echarts#6302]
### One-line summary [问题简述]

一个页面有N个chart,  8个以上渲染的时候..
[Violation] 'requestAnimationFrame' handler took 142ms
[Violation] 'requestAnimationFrame' handler took 113ms
[Violation] 'requestAnimationFrame' handler took 127ms
[Violation] 'requestAnimationFrame' handler took 110ms
[Violation] 'requestAnimationFrame' handler took 140ms
[Violation] 'requestAnimationFrame' handler took 110ms
[Violation] 'requestAnimationFrame' handler took 105ms
[Violation] 'requestAnimationFrame' handler took 103ms
[Violation] 'requestAnimationFrame' handler took 101ms
[Violation] 'requestAnimationFrame' handler took 104ms
[Violation] 'requestAnimationFrame' handler took 103ms
[Violation] 'requestAnimationFrame' handler took 107ms
[Violation] 'requestAnimationFrame' handler took 119ms
[Violation] 'requestAnimationFrame' handler took 93ms
[Violation] 'requestAnimationFrame' handler took 94ms
[Violation] 'requestAnimationFrame' handler took 93ms
[Violation] 'requestAnimationFrame' handler took 94ms
[Violation] 'requestAnimationFrame' handler took 91ms
[Violation] 'requestAnimationFrame' handler took 96ms
[Violation] 'requestAnimationFrame' handler took 93ms
[Violation] 'requestAnimationFrame' handler took 95ms
[Violation] 'requestAnimationFrame' handler took 92ms
[Violation] 'requestAnimationFrame' handler took 97ms
[Violation] 'requestAnimationFrame' handler took 93ms
[Violation] 'requestAnimationFrame' handler took 96ms
[Violation] 'requestAnimationFrame' handler took 93ms
[Violation] 'requestAnimationFrame' handler took 99ms
[Violation] 'requestAnimationFrame' handler took 92ms
[Violation] 'requestAnimationFrame' handler took 93ms

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.6
+ Browser version [浏览器类型和版本]: Chrome
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
多个渲染的时候，性能会好些。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jeffmobiles** [comment]
chrome console 会不断的 出现[Violation] 'requestAnimationFrame' handler took ** ms ......................

**Comment by pissang** [comment]
暂时无法满足你的需求，console 中的 log 不是 echarts 打的

**Comment by peng2e** [comment]
应该是某一个动画库打出来的，但是这个还不是LOG。 看起来更像是调用了浏览器的某个API ，还没找到……

**Comment by homestylew** [comment]
楼主解决了吗？我绘制echarts的时候也出现了这个情况

**Comment by homestylew** [comment]
> chrome console 会不断的 出现[Violation] 'requestAnimationFrame' handler took ** ms ......................

楼主解决了吗？我现在也遇到这个问题

**Comment by chengzi1222** [comment]
就是echarts里面的动画引起的警告，有人解决了吗

**Comment by chengzi1222** [comment]
一直出现这个警告，然后页面崩溃

**Comment by mmm2006** [comment]
我是在使用force的时候，如果点数比较多的情况下，就会出现不断的刷，判断是node比较多（400以上）的时候，关系图要稳定下来，需要不断刷屏，更新位置。这个估计没有办法解决吧。

**Comment by ZXY0710** [comment]
> 一直出现这个警告，然后页面崩溃

您现在解决了吗

**Comment by daLeiStrive** [comment]
因为requestAnimationFrame重复调用导致的,可以手动封装一个方法来处理这个事情,就是在同一时间只执行一次就行
