### ISSUE TITLE
官方实例的.json地图的demo下载到本地无法运行

### ISSUE THREAD

**Issue by git237491-dd** [ecomfe/echarts#6304]
### One-line summary [问题简述]

我在github下载了你们的echarts-master.zip，按照官网的教程进行了配置，也添加了zrender,但是在test文件下的例子中，只有使用.js的demo能够双击后正常运行，使用.json的demo双击运行后浏览器是一篇空白无法加载任何东西，请问这个怎么解决

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echart3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7\win10

### Expected behaviour [期望结果]

希望能够想使用.js地图数据的demo一样，双击使用.json数据的demo能够正常运行

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
跨域加载的错误，去了解一些 web 开发的基础知识
