### ISSUE TITLE
dataZoom拖拽，如何取得鼠标松开时的事件。

### ISSUE THREAD

**Issue by leosaullv** [ecomfe/echarts#6305]
#### 场景
拖拽滚动条发送请求给服务器，更新部分页面。

#### 问题
连续发送请求给服务器。

### Version & Environment [版本及环境]
+ ECharts 版本:  3.6.2
+ 浏览器类型和版本: chrome
+ 操作系统类型和版本: OS

### Expected behaviour [期望结果]
在拖拽中鼠标松开时发送请求给服务器。

**Comment by pissang** [comment]
dataZoom 去掉 realtime 试试？

**Comment by vision-yip** [comment]
http://echarts.baidu.com/api.html#events.datazoom

**Comment by leosaullv** [comment]
@pissang realtime改为false 已解决，谢谢

**Comment by keyleo** [comment]
改为false后, 拖拽滚动条时图表中的内容也变成在松开后才显示, 有没有办法一方面只影响到事件发送请求给服务器
