### ISSUE TITLE
官网-工具-无法根据选项生成JS或JSON

### ISSUE THREAD

**Issue by zhangqixu** [ecomfe/echarts#6308]
http://ecomfe.github.io/echarts-map-tool/ 官网-工具-地图数据在线工具  无法根据选项生成JS或JSON;
其中的示例也不够完善(对于初学者)也不友好,

### One-line summary [问题简述]
无法根据选项生成JS或JSON;
其中的示例也不够完善(对于初学者)也不友好,

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:版本 59.0.3071.115（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:win7旗舰

### Expected behaviour [期望结果]
能在线啊JS,echart 地图引进JSON的示例很不好友, 希望能给出完整的示例;

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
引入 json 的已经是完整示例了
