### ISSUE TITLE
你好，请问ECharts3的柱状图X轴坐标标签可以用小图片替代吗？谢谢

### ISSUE THREAD

**Issue by HongJianMou** [ecomfe/echarts#6311]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
暂时不行。

**Comment by HongJianMou** [comment]
你知道有哪些库可以支持这个功能吗？谢谢

**Comment by 100pah** [comment]
3.7.1 已经支持，参见：<http://echarts.baidu.com/gallery/editor.html?c=bar-rich-text>
