### ISSUE TITLE
IE8老版本无法正常显示

### ISSUE THREAD

**Issue by renqiang06** [ecomfe/echarts#6315]
### One-line summary [问题简述]
按模板做了一个图，chrome正常，IE11正常，IE8却加载不了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:IE8
+ OS Version [操作系统类型和版本]:WIN10

### Expected behaviour [期望结果]
改善IE8的兼容性

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
检查一下 1. 是否打包了 VML 的兼容模块 2. 自己代码中是否有 IE8 不兼容的部分
