### ISSUE TITLE
在react中，datazoom绑定on事件并在回调函数中使用setstate。导致死循环，无限render

### ISSUE THREAD

**Issue by v587su** [ecomfe/echarts#6321]
### One-line summary [问题简述]
首先初始化图表时绑定datazoom的on事件：
       myChart.on('dataZoom', () => (this.onDataZoom()));
之后在回调函数onDataZoom()中：
       调用echarts的getOption获取dataZoom的起始位置startValue；
       调用react的setState；
经过以上步骤再拖动datazoom便会无限render和onDataZoom

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:Chrome
+ OS Version [操作系统类型和版本]:win

### Expected behaviour [期望结果]
不发生死循环

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Dowgen** [comment]
哥我也遇到这问题，你怎么解决的
