### ISSUE TITLE
echart GL在ie浏览器不显示

### ISSUE THREAD

**Issue by jolychen** [ecomfe/echarts#6322]
### One-line summary [问题简述]
echart GL是否不支持Ie浏览器？GL的官网实例在IE下也根本显示不出来

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echart3、echartgl
+ Browser version [浏览器类型和版本]:IE9-11
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
echart gallery兼容IE的方法

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
GL 使用 WebGL 绘制，IE 11 才开始支持 WebGL

**Comment by jolychen** [comment]
@pissang 有解决的办法吗？比如IE安装个webGL的插件之类的

**Comment by pissang** [comment]
@jolychen 没
