### ISSUE TITLE
有没有一款代码编辑器能给出echarts的语法提示（Hbuilder or sublime）

### ISSUE THREAD

**Issue by wgsn** [ecomfe/echarts#6327]
### One-line summary [问题简述]

如题所示，哪款编辑器能完美支持echarts的语法提示，自动补全

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没
