### ISSUE TITLE
省市地图数据问题

### ISSUE THREAD

**Issue by JRWang1** [ecomfe/echarts#6328]
### One-line summary [问题简述]
在使用安徽省地图时，省市边界和实际不同，如：安庆市内多出一条边界线。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
我们的数据都来自第三方服务
