### ISSUE TITLE
桑基图 sankey 不同层级存在相同node name的问题

### ISSUE THREAD

**Issue by terence1984** [ecomfe/echarts#6330]
### One-line summary [问题简述]

用Echart桑基图构造路径分析可视化时，会遇到 A - B - A - B 这样的情况。

使用下面的数据
var _nodes = [{'id':'A1','name':'A'},
		       {'id':'A2','name':'A'},
		       {'id':'B1','name':'B'},
		       {'id':'B2','name':'B'}];
var _links = [{'source':'A1','target':'B1','value':20},
		    {'source':'B1','target':'B2','value':10}];

显示效果如下
![sankey](https://user-images.githubusercontent.com/11771781/28813602-6d51306c-76cc-11e7-9181-da945158d9c2.PNG)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]: FireFox 43
+ OS Version [操作系统类型和版本]: Windows 7

### Expected behaviour [期望结果]

节点和label显示的是name值，而不是link的source和target名称。

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
	            text: 'Sankey Diagram'
	        },
	        tooltip: {
	            trigger: 'item',
	            triggerOn: 'mousemove'

	        },
	        series: [
	            {
	                type: 'sankey',
	                layout:'none',
	                data: _nodes,
	                links: _links,
	                itemStyle: {
	                    normal: {
	                        borderWidth: 1,
	                        borderColor: '#aaa'
	                    }
	                },
	                lineStyle: {
	                    normal: {
	                        curveness: 0.5
	                    }
	                }
	            }
	        ]
}

```

**Comment by pissang** [comment]
可以使用 `label.normal.formatter`

**Comment by terence1984** [comment]
@pissang 谢谢

**Comment by zhangzhw514** [comment]
这个问题怎么解决？
