### ISSUE TITLE
地图下载-西藏地图缺少山南市

### ISSUE THREAD

**Issue by qikongkong** [ecomfe/echarts#6332]
### One-line summary [问题简述]
地图下载  西藏地图js和json  都缺少山南市的coordinates,encodeOffsets，导致西藏地图缺一块。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://echarts.baidu.com/demo.html#map-province

**Comment by pissang** [comment]
我们的数据都来自第三方，我们没法对地图数据进行修改
