### ISSUE TITLE
饼图动态显示label不生效

### ISSUE THREAD

**Issue by mafeifan** [ecomfe/echarts#6334]
如 http://embed.plnkr.co/zfCKBxcjqSCw6npY4RT3/

当鼠标在圆环上面，如绿色部分，圆中间应该显示"搜索引擎" 即对应的name。鼠标在红色区域上应该显示“直接访问”
如果鼠标离开圆环恢复成默认的文字，显示“BSS域”

**Comment by zuoliang0** [comment]
问题描述的不是很清楚啊

**Comment by mafeifan** [comment]
更新了描述

**Comment by zuoliang0** [comment]
刚刚专门去看了，我发现formatter只有在第一次生成的时候会被调用，后面再更改都不会调用，不知道是不是这个问题

**Comment by mafeifan** [comment]
是这个问题，我刚改了下，应该可以了
http://embed.plnkr.co/cZ3FME47lcFC92abAb3W/
