### ISSUE TITLE
echarts 3.6.2支持折线、柱状、饼图三者互转吗?

### ISSUE THREAD

**Issue by zhangqixu** [ecomfe/echarts#6336]
### One-line summary [问题简述]
toolbox.feature.magicType没有pie;
后期是否会更新引入饼图加入找toolbox.feature里面

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:chrome 59
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
期待toolbox.feature中能支持折线、柱状、饼图三者互转

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不支持，这些切换只需要 setOption 切换系列类型就行
