### ISSUE TITLE
地图的json怎么导到项目里面，为什么会下载失败

### ISSUE THREAD

**Issue by gaolian1025** [ecomfe/echarts#6340]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by zhangqixu** [comment]
我之前遇到过,  你是不是在本地运行的 ,你要到server上运行就可以获取到JSON了; 有可能是这种情况;

**Comment by gaolian1025** [comment]
我就是在服务器上面，就是那个URL路径的问题

**Comment by pissang** [comment]
问题跟 echarts 无关

**Comment by gaolian1025** [comment]
那和什么有关，就是地图显示不正确，全部挤在一起了，导致就一个黑点

**Comment by pissang** [comment]
看下是不是页面不是 utf-8 编码

**Comment by gaolian1025** [comment]
不是，我在同一个页面其他地图都能显示，你下载一下看一下，上海地图的js在浦东新区那一块乱码了，不知道有没有影响
