### ISSUE TITLE
隐藏所有曲线时，坐标轴刻度能够根据配置显隐

### ISSUE THREAD

**Issue by Gyyi** [ecomfe/echarts#6348]
### One-line summary [问题简述]
3.6.2版本中，对无数据的坐标轴不显示，但实际使用中，遇到了以下问题：
1、隐藏坐标轴上的所有曲线时，两边坐标轴都不显示了
![1](https://user-images.githubusercontent.com/16659067/28903424-5c9e1e4e-7837-11e7-9f07-d23dde5ba09e.png)

2、曲线图完全无数据时，坐标轴变成了一片空白
![2](https://user-images.githubusercontent.com/16659067/28903432-68e8ef1c-7837-11e7-98c5-6bae4ee64f63.png)

之前使用的3.2.3版本，是这样的：
1、隐藏坐标轴上的所有曲线时
![qq 20170803103517](https://user-images.githubusercontent.com/16659067/28903445-7cf33a26-7837-11e7-9bd4-a3023845680c.png)

2、曲线图完全无数据时
![qq 20170803103520](https://user-images.githubusercontent.com/16659067/28903483-bea01a98-7837-11e7-91e7-0cab16c4e667.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]:  chrome 59.0.3071.86
+ OS Version [操作系统类型和版本]: win7 x64

### Expected behaviour [期望结果]
期望可以提供配置项，自行配置是否根据数据显隐坐标轴

### ECharts option [ECharts配置项]

```javascript
option = {
    "legend": { "data": ['邮件营销', '联盟广告'] },
    "xAxis": [{
        "data": [],
        "type": "category",
        "boundaryGap": true,
        "splitLine": { "show": false },
        "axisLine": { "show": false }
    }],
    "series": [{
            name: '邮件营销',
            type: 'line',
            stack: '总量',
            areaStyle: { normal: {} },
            data: [120, 132, 101, 134, 90, 230, 210]
        },
        {
            name: '联盟广告',
            type: 'line',
            stack: '总量',
            areaStyle: { normal: {} },
            yAxisIndex: 1,
            data: [220, 182, 191, 234, 290, 330, 310]
        }
    ],
    "title": {
        "text": "状态码比例",
        "textStyle": { "fontSize": 14 },
        "show": true,
        "left": "1%"
    },
    "tooltip": { "trigger": "axis" },
    "toolbox": { "show": false },
    "grid": { "containLabel": true, "bottom": 20, "top": "25%", "left": "6%", "right": "6%" },
    "yAxis": [{
        "type": "value",
        "name": "比例: %           ",
        "nameTextStyle": { "fontSize": 12, "color": "#777" },
        "axisLabel": {},
        "axisLine": { "show": false },
        "axisTick": { "show": false }
    }, {
        "type": "value",
        "name": "请求数: 次",
        "nameTextStyle": { "fontSize": 12, "color": "#777" },
        "axisLabel": {},
        "axisLine": { "show": false },
        "axisTick": { "show": false }
    }]
};

```

**Comment by pissang** [comment]
配置 yAxis 的 min 和 max 就行了

**Comment by Gyyi** [comment]
似乎需要同时设置min 和max才可以。
由于数据是后端接口返回的，变动范围可能在 0 - 几十万 之间， 不太好确定 max 的值

**Comment by pissang** [comment]
原先是没数据的时候默认 min: 0, max: 1，可以试下没数据的时候配置，有数据的时候就去掉
