### ISSUE TITLE
饼图中的label是否可以支持动画？

### ISSUE THREAD

**Issue by zuoliang0** [ecomfe/echarts#6349]
### One-line summary [问题简述]
现有的label中不支持动画效果，希望支持动画

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
这种是我所希望的效果。
![image](http://dev.fanruan.com:8090/download/attachments/1998946/%E6%BB%9A%E5%8A%A8.gif?version=1&modificationDate=1500453097000&api=v2)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

这是现在的效果，不支持定义其中的文字动画
![image](https://user-images.githubusercontent.com/8434253/28904631-f0a5ac90-783e-11e7-849c-d50483fd425c.png)

希望能够提供相关的属性或接口来定义动画谢谢！

**Comment by gaopeng0108** [comment]
您好，请问您已经解决了吗
