### ISSUE TITLE
你好，我想问问下一个版本 笛卡尔坐标系上的热力图可以支持多选?

### ISSUE THREAD

**Issue by PalaChen** [ecomfe/echarts#6351]
### One-line summary [问题简述]
 需要选择热力图多个区域，然后再页面显示指定的数据

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

环境：http://echarts.baidu.com/demo.html#heatmap-cartesian

### Expected behaviour [期望结果]

热力图支持多选

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时还没有这个计划
