### ISSUE TITLE
saveAsImage.pixelRatio 最大值是多少？填写300图片出现错误

### ISSUE THREAD

**Issue by shiwanmenghuxiahuashan** [ecomfe/echarts#6352]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
toolbox.feature.saveAsImage.pixelRatio 最大值是多少？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
pixelRatio 是现在的分辨率基础上再乘上的值，你算下你屏幕分辨率乘 300 的结果...

**Comment by shiwanmenghuxiahuashan** [comment]
谢谢老板，明白了。
