### ISSUE TITLE
能否开一个slack或者gitter讨论问题？

### ISSUE THREAD

**Issue by navono** [ecomfe/echarts#6359]
好像很多都是使用的问题，并不是bug。所以想询问下能否开个slack或者gitter，供大家讨论询问，而不是发issue。这样issue就不会爆炸了。

**Comment by Ovilia** [comment]
谢谢提议，但是核心开发者精力有限，没法在即时通讯工具或 slack 之类的平台上提供支持。

以下是我们对几类常见问题寻求解决方案的建议：

有技术问题怎么办？
1）建议您在提问前，大致阅读一下 http://echarts.baidu.com/option.html 左侧导航，了解 ECharts 有哪些配置项，并且在相关的组件下查找是否有实现您需要功能的配置项；
2）查看常见问题：http://echarts.baidu.com/faq.html ；
3）建议在 http://gallery.echartsjs.com/editor.html 上添加图表，复现你的问题，如果无法使用代码描述需求，可以尝试提供设计稿或画个草图；
4）推荐在 https://stackoverflow.com 、http://www.oschina.net/question/tag/echarts 或 https://segmentfault.com/t/echarts 等问答平台上提问，附上图表链接。

如何报告 bug 或建议支持某功能？
在 https://github.com/ecomfe/echarts/issues 详细描述您的需求，提供复现的代码或需求设计稿。

**Comment by navono** [comment]
你说的对。任何一个有经验的开发者都应该那么做。

我只是看到了很多issue其实是询问贴，所以才有那么个想法。
在其他的开源库的gitter或者slack中，很多活跃的人并不是核心维护者。可能是对库本身使用的很熟练，自然也就能回答一些人又不想看各种文档所遇到的问题。

以上只是我个人的想法。

**Comment by Ovilia** [comment]
再次谢谢你的建议~
