### ISSUE TITLE
echarts.3.6.2有详细的事件文档和实例没?

### ISSUE THREAD

**Issue by zhangqixu** [ecomfe/echarts#6364]
### One-line summary [问题简述]
比如说折线图的线段,点击触发一个事件;,在哪有详细的文档?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA

**Comment by zhangqixu** [comment]
谢谢
