### ISSUE TITLE
echart2 中的树图的文字 如何变成竖的显示，现在是横排显示，求帮助！很急

### ISSUE THREAD

**Issue by yellowStar1992** [ecomfe/echarts#6367]
### One-line summary [问题简述]

用的是echar2中的树图，但是没找到 如何将文字变成竖排显示

### Version & Environment [版本及环境]

echart2版本

### Expected behaviour [期望结果]

希望树图中的文字 变成竖排显示

**Comment by pissang** [comment]
`orient: 'vertical'`
