### ISSUE TITLE
echart的数轴能否变成非等分

### ISSUE THREAD

**Issue by TalonZed** [ecomfe/echarts#6368]
### 在进行工地实验统计的时候，需要用到等差非等距的数值轴，求帮助，着急。。。
###var result = "4.264486132150425;16.22592333179383;25.208509953152;5.3;3.4)";
				var arr = result.split(";");
				var data2 = [
					[arr[0], 2],
					[arr[2], 17]
				];
				var data1 = [
					[arr[3], 2],
					[arr[2], 17]
				];
				var data3 = [
					[arr[4], 2],
					[arr[2], 17]
				];
				var temp0 = Math.floor(arr[0] * 100) / 100;
				option = {
					title: {
						text: '圆锥下沉深度n和与联合测定含水率w曲线图',
						left: 'center'
					},
					tooltip: {
						show: true
					},
					xAxis: {
						type: 'log',
						name: 'x',
						min: 10,
						logBase: 2,
						scale: true,
					},
					yAxis: {
						//type: 'category',
						type: 'log',
						logBase: 2,
						name: '下沉深度(mm)',
						axisTick: {
							alignWithLabel: true
						},
						scale: true,
					},
					series: [{
							type: 'line',
							data: data1,
							animation: false

						},
						{
							markPoint: {
								symbolSize: '5',
								data: [
									{ coord: [Math.floor(arr[2] * 1000) / 1000, 17], symbol: 'emptytriangle', itemStyle: { normal: { color: '#000', label: { position: 'right' } } } },
									{ coord: [Math.floor(arr[0] * 1000) / 1000, 2], valueIndex: 0, symbol: 'emptytriangle', itemStyle: { normal: { color: '#000', label: { position: 'left' } } } },
									{ coord: [Math.floor(arr[1] * 1000) / 1000, 10], symbol: 'emptytriangle', itemStyle: { normal: { color: '#000', label: { position: 'left' } } } }
								],

							},
							type: 'line',
							data: data2,
							animation: false
						},
						{
							type: 'line',
							data: data3,
							animation: false
						}
					]
				};
				var new_div = document.createElement("div");

				new_div.style.width = "600px";
				new_div.style.height = "600px";
				document.body.appendChild(new_div);
				new_div.id = "ks";
				var myChart = echarts.init(new_div);
				myChart.setOption(option);

效果图如下图所示
![image](https://user-images.githubusercontent.com/23493329/28994257-24a682bc-79fc-11e7-9cc4-013efcf2a042.png)

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#yAxis.logBase
