### ISSUE TITLE
Stacked lines legend are in reversed order

### ISSUE THREAD

**Issue by corradio** [ecomfe/echarts#6369]
Hello,

I've made a stacked line chart (using the `line` series) and added legends. Unfortunately I want the legends to appear in the same order as the graph (bottom to top). Is it possible to change?
Documentation doesn't show the possibility.
cc @brunolajoie

![image](https://user-images.githubusercontent.com/1655848/28994689-aeead6d0-79d4-11e7-8f7e-3ba83a1bd800.png)

Thank you in advance.

**Comment by pissang** [comment]
legend display order is same with what you give to `legend.data`. So you can simply reverse `legend.data`

**Comment by corradio** [comment]
Hi @pissang , 

It's a good idea but even if it fixes the legend, the tooltip is still in wrong order.
Do you have a solution for also reverting the tooltip, aside from rewriting a formatter function from scratch?

**Comment by pissang** [comment]
Unfortunately you can only use formatter to change the tooltip content

**Comment by corradio** [comment]
got it. Will rewrite the tooltip from scratch then. Thanks!

**Comment by jbdesbas** [comment]
Since I encountered a similar use case, here is a ready-to-use solution:

```js
legend:{
    data: series.map(s => s.name ?? '').reverse()
}
```
