### ISSUE TITLE
我觉得可以加个 .off() 取消事件方法

### ISSUE THREAD

**Issue by foreverZ133** [ecomfe/echarts#6370]
同事在每次 $.post 之后去绑定 .on('click') 事件，结果造成了重复绑定。
个人觉得可以再加个 off 方法去清除对象事件或所有事件。
虽然贵插件有 clear 等方法，但不如 off 更便于理解吧。

**Comment by pissang** [comment]
http://echarts.baidu.com/api.html#echartsInstance.off 我想问下你有没有去试过呢？
