### ISSUE TITLE
制作股票分时图时，11:30 - 13:00 这段时间是没有交易的，请问这段时间的x轴如何截断？

### ISSUE THREAD

**Issue by agangdi** [ecomfe/echarts#6372]
制作股票分时图时，11:30 - 13:00 这段时间是没有交易的，请问这段时间的x轴如何截断？直接让11:30后面就接 13:00 的点。

**Comment by Ovilia** [comment]
x 轴的数据是自己填的，所以直接跳过即可：http://gallery.echartsjs.com/editor.html?c=xBk_DDgdPb&v=1

**Comment by LiuXiaoJie** [comment]
@pissang 如果横坐标是time类型的，11:30-13:00有办法实现截断吗？

**Comment by xoptimal** [comment]
@Ovilia  如果X轴的 type = time , 如果截断或者跳过 11:30-13:00 ???

**Comment by 100pah** [comment]
<https://www.echartsjs.com/option.html#series-line.connectNulls>
可以截断，但是不知道是不是想要的样子。

**Comment by xoptimal** [comment]
@100pah  并不是我想要的效果, 我要的是截断后, 点是不分离的, 相连的,

**Comment by xoptimal** [comment]
你可以看看 http://www.sse.com.cn/market/price/trends/  上证指数 , 我现在就是想做这个效果,

**Comment by 100pah** [comment]
如果 x 轴是 time 目前确实做不出这个效果。需要 x 轴是 category 类型才行了。
