### ISSUE TITLE
上海市地图数据 崇明区数据缺失

### ISSUE THREAD

**Issue by bymain** [ecomfe/echarts#6373]
### One-line summary [问题简述]
上海市地图数据 崇明区数据缺失

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2

下载最新的 shanghai.json 数据，发现里面缺失崇明区相关坐标信息

`{"id":"310151","type":"Feature","geometry":{"type":"Polygon","coordinates":[],"encodeOffsets":[]},"properties":{"cp":[121.397516,31.626946],"name":"崇明区","childNum":0}}`

![image](https://user-images.githubusercontent.com/11552691/29017445-6da8213a-7b89-11e7-81d0-86922a3e48cc.png)

**Comment by bymain** [comment]
@pissang 这种坐标数据应该从哪里获取？

**Comment by gaolian1025** [comment]
乱码有事什么鬼

**Comment by bymain** [comment]
@gaolian1025 什么乱码？

**Comment by gaolian1025** [comment]
@bymain 你下载的json里面，浦东新区的经纬度有没有乱码

**Comment by bymain** [comment]
@gaolian1025 你说的是coordinates?应该是坐标映射，这个不影响使用吧

**Comment by gaolian1025** [comment]
影响使用，我在项目中不能正常显示，留个联系方式吧，754200689

**Comment by gaolian1025** [comment]
@bymain

**Comment by bymain** [comment]
{"id":"310230","geometry":{"type":"MultiPolygon","coordinates":[["@@^ITIRCZAVEV@bWXCDAVEBERKD@\\U\\K\\GBCNCBJD@RE`MB@JCTDÔoĒmƂZñLcDgG_SY]O£kcIUABoH_H±jãYHNODQH½pÛ`gBUAQImwf±ŧŚEBoH~zh^rXbLpVbJjHP@LANE s`SjoLGJQKCV_JK","@@ODMFYnMLaXŃÈ{^yv[RYLMLAF@HHHHBOJEL]FKPMDCjIÌknGXI`MdKhWPGJGNMT[DEBQFS@SC_GKECKC","@@UDmXOLQPCF@FDBDBN@`ENEJEXQTSBEACACEA","@@BBB@DBDCCAC@@ACB@B","@@CNO\\@DBBTB^ANCNE\\A\\IjMFIPa@IAOAK_uCAS@GEG@YFGH[PSRQZC^"]],"encodeOffsets":[[[124346,32532],[124702,32062],[124547,32200],[125176,32174],[124726,32110]]]},"properties":{"cp":[121.397516,31.626946],"name":"崇明区","childNum":5}}],"UTF8Encoding":true}

**Comment by bymain** [comment]
`{"id":"310230","geometry":{"type":"MultiPolygon","coordinates":[["@@^ITIRCZAVEV@bWXCDAVEBERKD@\\U\\K\\GBCNCBJD@RE`MB@JCTDÔoĒmƂZñLcDgG_SY]O£kcIUABoH_H±jãYHNODQH½pÛ`gBUAQImwf±ŧŚEBoH~zh^rXbLpVbJjHP@LANE s`SjoLGJQKCV_JK","@@ODMFYnMLaXŃÈ{^yv[RYLMLAF@HHHHBOJEL]FKPMDCjIÌknGXI`MdKhWPGJGNMT[DEBQFS@SC_GKECKC","@@UDmXOLQPCF@FDBDBN@`ENEJEXQTSBEACACEA","@@BBB@DBDCCAC@@ACB@B","@@CNO\\@DBBTB^ANCNE\\A\\IjMFIPa@IAOAK_uCAS@GEG@YFGH[PSRQZC^"]],"encodeOffsets":[[[124346,32532],[124702,32062],[124547,32200],[125176,32174],[124726,32110]]]},"properties":{"cp":[121.397516,31.626946],"name":"崇明区","childNum":5}}],"UTF8Encoding":true}
`

**Comment by PureMug** [comment]
我也一样，json和js都试过，都缺崇明

**Comment by bymain** [comment]
@PureMug 我自己找的数据，看着还凑活

**Comment by bymain** [comment]
{"id":"310230","geometry":{"type":"MultiPolygon","coordinates":[["@@^ITIRCZAVEV@bWXCDAVEBERKD@\\U\\K\\GBCNCBJD@RE`MB@JCTDÔoĒmƂZñLcDgG_SY]O£kcIUABoH_H±jãYHNODQH½pÛ`gBUAQImwf±ŧŚEBoH~zh^rXbLpVbJjHP@LANE s`SjoLGJQKCV_JK","@@ODMFYnMLaXŃÈ{^yv[RYLMLAF@HHHHBOJEL]FKPMDCjIÌknGXI`MdKhWPGJGNMT[DEBQFS@SC_GKECKC","@@UDmXOLQPCF@FDBDBN@`ENEJEXQTSBEACACEA","@@BBB@DBDCCAC@@ACB@B","@@CNO\\@DBBTB^ANCNE\\A\\IjMFIPa@IAOAK_uCAS@GEG@YFGH[PSRQZC^"]],"encodeOffsets":[[[124346,32532],[124702,32062],[124547,32200],[125176,32174],[124726,32110]]]},"properties":{"cp":[121.397516,31.626946],"name":"崇明区","childNum":5}}

**Comment by wsxwqn926** [comment]
我也一样，缺失崇明

**Comment by wsxwqn926** [comment]
楼上在哪找的数据

**Comment by gaolian1025** [comment]
这个数据可以用吗

**Comment by wsxwqn926** [comment]
{
        "id": "310151",
        "type": "Feature",
        "geometry": {
            "type": "Polygon",
            "coordinates": ["@@UF\\cN_LABaNYJ[LKDYJCBSFEBYDgFIBOBODQHIBOHgPSF_NGBaTaTmZaRGFEBsVQH[BK@EAO@MGCAGKIMGKS[qbEDEFMJGFURKJaZQPWVIHQRKLWVsrONUXYVEHMNONEFGFIJ_`EBOB_FjfTTDBd\\rX`LB@DBRHZLbJPDD@VDP@LANEFC^OPGNG^OJGB@BARILMHIDC@@BA@AB@@ADAJK@AJCBADEBC@@DGC@CACABAPWDEBCHGJID@NELCHELCRCB@XAPCFABBBAR@^SB@BANAFADADABATCBEJEHED@\\U\\K\\GBANEBHD@RCHCXI@@B@B@HCTDLCDArOXGhKDANCVEF@\\ERCzKjIdGxKbGtKRCXEQxKZñLcDgG_SY]O]_McIUAOASB]BYDUDIB"],
            "encodeOffsets": [[124754, 32190]]
        },
        "properties": {
            "cp": [121.397516, 31.626946],
            "name": "崇明区",
            "childNum": 0
        }
    }

**Comment by bymain** [comment]
我发的那个可用

**Comment by firingdragon** [comment]
请问大家是怎么解决这个问题的

**Comment by chfw** [comment]
以上有乱码。能发个文件到我信箱吗？wangc_2011@hotmail.com. 如果可用的话， 我可以发PR与大家分享。

以下是我改动的地图：
https://github.com/ecomfe/echarts/pull/7020
