### ISSUE TITLE
柱状图中有2.5D的柱状图吗，就是那种立方体图

### ISSUE THREAD

**Issue by chinaxushi** [ecomfe/echarts#6377]
### One-line summary [问题简述]

柱状图中有2.5D的柱状图吗，就是那种立方体图。不是用3D的展现。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没
