### ISSUE TITLE
areaStyle 在chrome和safari上表现不一致

### ISSUE THREAD

**Issue by hefei00** [ecomfe/echarts#6380]
### One-line summary [问题简述]
官网带有areaStyle折线图实例，在chrome和safari上area区域颜色表现不一致。
实例：[http://echarts.baidu.com/demo.html#area-simple](http://echarts.baidu.com/demo.html#area-simple)
chrome下：
![qq20170808-150604](https://user-images.githubusercontent.com/3992113/29060180-36e2a676-7c4b-11e7-9f05-4ee704d1a8b3.png)

safari下：
![qq20170808-150731](https://user-images.githubusercontent.com/3992113/29060212-5f344ce2-7c4b-11e7-873b-14aec1aa1b05.png)

根据设置的颜色值，chrome下表现是正确的，在safari下颜色是不正确的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6
+ Browser version [浏览器类型和版本]: chrome 60.0.3112.90   safari 10.0.1 (12602.2.14.0.7)
+ OS Version [操作系统类型和版本]: macOS 10.12.1

### Expected behaviour [期望结果]
在safari下颜色和chrome下表现一致。

### ECharts option [ECharts配置项]

就是官网的例子，未做任何修改
```javascript
option = {
     //...
}

```

**Comment by pissang** [comment]
改成：

```js
            areaStyle: {
                normal: {
                    opacity: 1,
                    color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                        offset: 0,
                        color: 'rgba(255, 158, 68, 0.7)'
                    }, {
                        offset: 1,
                        color: 'rgba(255, 70, 131, 0.7)'
                    }])
                }
            }
```

试试

**Comment by tanxuewei** [comment]
想请问下楼上这个问题的原因是什么呢，是因为canvas在safari下的问题么？

**Comment by pissang** [comment]
@tanxuewei 应该是的
