### ISSUE TITLE
echarts柱状图设置宽度1300，高度2500px,在android，苹果手机浏览器都不显示，pc显示正常

### ISSUE THREAD

**Issue by wzhan** [ecomfe/echarts#6381]
ECharts 版本：3.6.2

测试代码：

html:
  div id="main" style="width:1300px;height:2500px;"

js:
  var myChart = echarts.init(document.getElementById('main'));
  option = {
    title: {
      text: '世界人口总量',
      subtext: '数据来自网络'
    },
    tooltip: {
      show:true,
      trigger: 'axis',
      axisPointer: {
        type: 'shadow'
      }
    },
    legend: {
      data: ['2011年', '2012年']
    },
    grid: {
      left: '3%',
      right: '4%',
      bottom: '3%',
      containLabel: true
    },
    xAxis: {
      type: 'value',
      //boundaryGap: [0, 0.01]
    },
    yAxis: {
      type: 'category',
      data: ['巴西','印尼','美国','印度','中国','世界人口(万)']
    },
    series: [
      {
        name: '2011年',
        type: 'bar',
        data: [{venue_id:12,value:22222}, 23489, 29034, 104970, 131744, 630230]
      },
      {
        name: '2012年',
        type: 'bar',
        data: [19325, 23438, 31000, 121594, 134141, 681807]
      }
    ]
  };

  // 绘制图表
  myChart.setOption(option);

**Comment by pissang** [comment]
移动端有 dpr ，不能设置成这么大

**Comment by wzhan** [comment]
@pissang  echarts号称兼容pc和手机，如果我pc端设置了这么大的分辨率，在手机就看不见了。我改用highcharts，可以正常显示。
我知道在手机上一般不会设置成这么大的分辨率，我现在用的场景是，用了阿里的手机高清方案，在iphone6 plus 3倍高清屏下，实际的分辨率就会是手机逻辑分辨率的三倍，导致用echarts在很大的分辨率下不显示
