### ISSUE TITLE
toolbox自定义图标如何改变hover时的颜色？

### ISSUE THREAD

**Issue by v587su** [ecomfe/echarts#6382]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by v587su** [comment]
试过iconStyle似乎不管用

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#toolbox.iconStyle.emphasis.borderColor
