### ISSUE TITLE
如何自定义柱状图高度

### ISSUE THREAD

**Issue by OneAndOnly1111** [ecomfe/echarts#6385]
### One-line summary [问题简述]
echarts画柱状图时，数值之间相差太大，导致比较小的数据bar的高度只有一点点，现在想要自己定义高度，把画高度的值设置为开平方之后的值，但是label还是显示原始值, 有什么参数支持？ bar没有提供自定义高度的参数。。

### Expected behaviour [期望结果]
能够自定义高度的值而不毁坏原始数据

### ECharts option [ECharts配置项]

```javascript
option = {
   series:[{
		    name:'数量排行',
		    id:'number',
		    type: 'bar',
	            data: [],
	            yAxisIndex:0,
	            label:{
	            	normal:{
	            		show:true,
	            		position:'right',
	            		textStyle:{
	            			color:'#ddd'
	            		}
	            	}
	            },
	            itemStyle: {
	                normal: {
	                    color: '#19F4F2'
	                }
	            },
	            tooltip:{
	            	formatter:'{b0}:{c0} 个'
	            },
	            zlevel: 2,
    }]
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/18378998/29065938-5158b4fe-7c60-11e7-9912-5b1407e52b59.png)

**Comment by pissang** [comment]
没有，你可以用 formatter 显示真实值

**Comment by OneAndOnly1111** [comment]
我是在还没画图的原始数据上对值开平方，这样导致进去的数据就已经不是原始值，formatter也不是原始值，有没有什么参数支持原始数据进去后再更改数据的高度的？类似symbolSize这样的可自己定义图形大小，抱歉我没找到
