### ISSUE TITLE
地图的大小怎么设值，为什么我的地图初始化太小了，导致就一个点

### ISSUE THREAD

**Issue by gaolian1025** [ecomfe/echarts#6391]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by gaolian1025** [comment]
@pissang  至少给个解释呀，你这样关了

**Comment by Asunny-ren** [comment]
你的问题解决了吗
