### ISSUE TITLE
折线图动态数据实例太丑了

### ISSUE THREAD

**Issue by DXShelley** [ecomfe/echarts#6392]
### One-line summary [问题简述]
百度echarts演示实例中，动态数据部分折线图实时显示界面太丑了，折线跳动的很生硬，一点不顺滑，看上去非常的丑。先更新页面后更新新加的数据更难看

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.0
+ Browser version [浏览器类型和版本]:谷歌浏览器最新版本
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
动态数据的折线图显示能更加平滑点，给人一种实时性的感觉。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by weiyujia** [comment]
提问题这么不客气，活该被秒关了
