### ISSUE TITLE
echarts环形图问题

### ISSUE THREAD

**Issue by huanledeniuduzi** [ecomfe/echarts#6396]
### One-line summary [问题简述]：

用echarts绘制环形图时，遇到一个问题：
环形图中的百分比文字不能垂直居中，不知道该如何设置。请问要如何设置？
不清楚的话请看下图。矩形框框里的文字没有垂直居中。
谢谢！

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: 高版本浏览器
+ OS Version [操作系统类型和版本]: win7
![11](https://user-images.githubusercontent.com/30464088/29150242-dc242a2c-7dab-11e7-97e9-06bf78c900fe.png)

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能否给出完整的配置项？

**Comment by huanledeniuduzi** [comment]
PercentPie.prototype.init = function(){
    var _that = this;
    var option = {
        backgroundColor:_that.backgroundColor,
        color:_that.color,
        title: {
            text: _that.title,
            top:'0',
            left:'0',
            textStyle:{
                color: '#333',
                fontStyle: 'normal',
                fontWeight: 'normal',
                fontFamily: 'sans-serif',
                fontSize: 30,
            }
        },
        series: [{
            name: '来源',
            type: 'pie',
            radius: ['60%', '75%'],
            avoidLabelOverlap: false,
            hoverAnimation:false,
            label: {
                normal: {
                    show: false,
                    position: 'center',
                    textStyle: {
                        fontSize: _that.fontSize,
                        fontWeight: 'bold'
                    },
                    formatter:'{b}\n{c}%'
                }
            },
            data: [{
                    value: _that.value,
                    name: _that.name,
                    label:{
                        normal:{
                            show:true
                        }
                    }
                 },
                {
                    value: 100-_that.value,
                    name: ''
                }
            ]
        }]
    };

**Comment by huanledeniuduzi** [comment]
已解决
