### ISSUE TITLE
3.6.2在window.onresize中无效，旧版3.0可以

### ISSUE THREAD

**Issue by capricorncd** [ecomfe/echarts#6397]
### One-line summary [问题简述]

3.6.2 版
当浏览器窗口大小改变时，重新渲染图表无效
window.onresize = function () {
    // 重新渲染图表代码
}

3.0版可以

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: chrome/firefox
+ OS Version [操作系统类型和版本]: window 7/nginx

**Comment by pissang** [comment]
看看有没有报错

**Comment by capricorncd** [comment]
控制台无报错或也没抛出任何异常

**Comment by capricorncd** [comment]
`
function createEcharts () {
    var myChart = echarts.init(document.getElementById('echartsWrapper'));
    var option = {
        // ...
    }
    myChart.setOption(option);
}

window.onresize = function () {
    createEcharts();
}
`

**Comment by pissang** [comment]
echarts 有 resize 方法，不需要重新生成

**Comment by capricorncd** [comment]
Thank you!
