### ISSUE TITLE
使用brush刷选出一片区域，怎么在鼠标停止刷的时候把brush的遮罩层去掉？

### ISSUE THREAD

**Issue by liping1994** [ecomfe/echarts#6408]
this.myCharts && this.myCharts.dispatchAction({
      type: 'brush',
      areas: []
});

我用的这个方法  但是有时候有效果，有时候没效果

**Comment by liping1994** [comment]
已解决  window.onmouseup = () => {
			setTimeout(() => {
				this.myCharts && this.myCharts.dispatchAction({
					type: 'brush',
					areas: []
				});
			}, 300);
		}

**Comment by liwenda122** [comment]
标准的写法应该是
myCharts && myCharts.dispatchAction({
   type: 'brush',
   command: 'clear',
   // Clear all areas of all brush components.
   areas: []
});
