### ISSUE TITLE
Echars2.2.7采用eachars-all.js引入之后如何设置主题

### ISSUE THREAD

**Issue by gyjx** [ecomfe/echarts#6410]
### One-line summary [问题简述]
请问Echars2.2.7采用eachars-all.js引入之后如何设置主题？

我的代码如下:

<script src="echarts-2.2.7/build/dist/echarts-all.js"></script>
<script src="echarts-2.2.7/build/dist/theme/blue.js"></script>

 var myChar3=echarts.init(document.getElementById('mainLine'),"blue");

出现这个错误

![image](https://user-images.githubusercontent.com/20329819/29206953-c493b25e-7eb6-11e7-9586-f9e26e0661d9.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.2.7
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows7

### Expected behaviour [期望结果]

官网给出的是模块化引入解决，但是我们是单文件引入的，麻烦帮忙解决一下！谢谢！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 3 支持这种引入方式，2 需要 require 引入
