### ISSUE TITLE
关于dataRange.splitList读写问题。

### ISSUE THREAD

**Issue by ansonnw** [ecomfe/echarts#6419]
如：dataRange: {
                    x: 'left',
                    y: 'bottom',
                    splitList: [
                        {start: 1500},
                        {start: 900, end: 1500},
                        {start: 310, end: 1000},
                        {start: 200, end: 300},
                        {start: 10, end: 200, label: '10 到 200（自定义label）',color: 'blue'},
                        {start: 5, end: 5, label: '5（自定义特殊颜色）', color: 'black'},
                        {end: 10}
                    ],
                    color: ['#E0022B', '#E09107', '#A3E00B']
                },

当执行自定义赋值dataRange.splitList[0].start = 5000;没响应。怎么读写splitList数组内容？谢谢。

**Comment by pissang** [comment]
setOption 更新

**Comment by ansonnw** [comment]
你好，读dataRange.splitList[0].start值也不行，但读dataRange.color[0]正常。??  谢谢。

**Comment by ansonnw** [comment]
读写dataRange的splitList的值出错，读写dataRange的其它元素如min,max都正常。什么原因呢?
