### ISSUE TITLE
geo.itemStyle.normal.color有误

### ISSUE THREAD

**Issue by 15171413067** [ecomfe/echarts#6423]
### One-line summary [问题简述]
API中地图区域颜色描述为geo.itemStyle.normal.color
实际使用应为geo.itemStyle.normal.areaColor

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
color 和 areaColor 都可以使用。

**Comment by 100pah** [comment]
Fixed on 783d1f5db338d6108fa1e86f7503e62ad84c58ce
