### ISSUE TITLE
折线图动态增加数据时，坐标轴刻度数据堆积问题

### ISSUE THREAD

**Issue by hsilence** [ecomfe/echarts#6428]
### One-line summary [问题简述]
1. 在折线图动态增加数据时，坐标轴刻度数据会出现堆积，原因是增加数据太快，但是我是从硬件采集数据，所以速度不可能很慢
2. 上述问题是在3.0版本中出现的，由于不合适换成了2.0版本的方法，暂时解决了问题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
当在数据在速度很快增加时不出现数据堆积，并很平稳的显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

我把线上实例的时间改了之后出现的情况如下图
![qq 20170814150837](https://user-images.githubusercontent.com/20702713/29261589-dbf93650-8102-11e7-91dc-cd7b1cbd0fee.png)

**Comment by Ovilia** [comment]
硬件采集频率太高的话，可以不用每次都 setOption。比如可以设个计数器，每采集 10 次调用一次 setOption。
或者把动画关了。

**Comment by hsilence** [comment]
@Ovilia 谢谢
