### ISSUE TITLE
x轴为Time类型时,moment的时间格式无法展示

### ISSUE THREAD

**Issue by bluesh** [ecomfe/echarts#6431]
### Version & Environment [版本及环境]
+ ECharts version [3.6.2]:
+ Browser version [chrome  60.0.3112.90]:
+ OS Version [OS X El Capitan 10.11.6]:

### ECharts option [ECharts配置项]

```javascript
var NOWTIME = moment();
var getData = (range: number) => {
    let result = new Array();
    for(let i = 0; i < 60; i++) {
        result.unshift([
            i === 0 ? NOWTIME.toString() : moment(result[0][0]).subtract(range, 'minutes').toString(),
            Math.random()
        ])
    }
    return result;
}
var data = getData(15);

var option = {
    xAxis: {
        type: 'time',
    },
    yAxis: {},
    series: [{
        type: 'line',
        data: data,
    }],
    dataZoom: [{
        type: 'slider',
        height: '25px',
        bottom: 0,
        top: 0,
    }],
};

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/1687283/29267038-92d785b4-8119-11e7-8039-3d2541132e2c.png)

**Comment by Ovilia** [comment]
你要这样用的话，就把坐标轴类型设为 `category`。
或者数据仍然用 `Date`，然后用 formatter 修改显示的时间格式，在 formatter 里调用 moment。

**Comment by bluesh** [comment]
改成 `category` 也不可以
我按照 http://echarts.baidu.com/demo.html#dynamic-data2 这个例子的`data`数据格式（也就是[{name: moment(), value: number}]）也一样展示不了

**Comment by Ovilia** [comment]
series.data.name 不是用来指定 x 坐标的。
给你写了个例子：http://gallery.echartsjs.com/editor.html?c=xBJ4rjHg_-&v=1

**Comment by bluesh** [comment]
我把`.toString()`转成`.format('YYYY-MM-DD HH:mm')`竟然就可以了

**Comment by bluesh** [comment]
其实想用这个做个时间拖拽器，，利用dataZoom

**Comment by navono** [comment]
使用：
```js
xAxis: {
        type: 'time',
    },
```
x轴上能显示毫秒吗？
我修改[动态更新](http://echarts.baidu.com/demo.html#dynamic-data2)的例子。
将
```js
function randomData() {
    now = new Date(+now + oneDay);
    value = value + Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
            Math.round(value)
        ]
    }
}
```
改成了
```js
function randomData() {
    // now = new Date(+now + oneDay);
    now = new Date(+now + OneSeconds);
    value = value + Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            //[now.getFullYear(), now.getMonth() + 1, now.getDate(),].join('/'),
            now,
            Math.round(value)
        ]
    }
}
```
在x轴上只能显示格式为__HH:mm:SS__的时分秒。
如果将`now = new Date(+now + OneSeconds);`修改成毫秒级别，有没有办法在x轴显示毫秒？

**Comment by navono** [comment]
[demo](http://gallery.echartsjs.com/editor.html?c=xSkiOAzn1G&v=1)这是我修改的一个例子。
