### ISSUE TITLE
Echarts结合百度地图使用，如何让百度地图默认显示为卫星地图

### ISSUE THREAD

**Issue by techzealot** [ecomfe/echarts#6438]
### One-line summary [问题简述]

您好，请问Echarts结合百度地图使用，如何让百度地图默认显示为卫星地图？
单独的百度地图可以通过
var map = new BMap.Map("container", {mapType:BMAP_SATELLITE_MAP});
这种方式来实现，
结合之后找不到地方设置，请问可以实现吗？谢谢！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by luguokong** [comment]
查看百度地图api

**Comment by techzealot** [comment]
thank you!
