### ISSUE TITLE
如何在y轴显示数字和文字

### ISSUE THREAD

**Issue by lhwu** [ecomfe/echarts#6439]
### One-line summary [问题简述]
如何在y轴显示数字和文字

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:chorme
+ OS Version [操作系统类型和版本]:Ubuntu14.04

### Expected behaviour [期望结果]
点击图片时，可以显示出两个legend的值，一个是数字，一个是文字

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
什么意思？

**Comment by lhwu** [comment]
意思是，当点击折线时，要一起显示对应的y轴数字，还有这条数据对应的标签（文字）。不过已经解决了，是通过tooltip.formatter实现想要的结果的
