### ISSUE TITLE
想支持new zealand map

### ISSUE THREAD

**Issue by SparkSqlMVP** [ecomfe/echarts#6448]
### One-line summary [问题简述]

我想支持新西兰的地图，像你们的美国地图一样的效果，我该怎么做？谢谢，如下：
http://echarts.baidu.com/demo.html#map-usa

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/pissang/starbucks/blob/gh-pages/json/New_Zealand.json
