### ISSUE TITLE
笛卡尔坐标系上的graph如何设置name

### ISSUE THREAD

**Issue by lili21** [ecomfe/echarts#6450]
### One-line summary [问题简述]
1. [实例](http://echarts.baidu.com/demo.html#graph-simple)

    这里没有配置坐标系，那么data列表里的x, y代表的是什么意思？

2. 笛卡尔坐标系
    
    配置了笛卡尔坐标系的情况下，data就无法设置为`{ name: 'a', x: 10, y: 10 }` 这样的形式了吗？那怎么设置`name`呢？

**Comment by pissang** [comment]
1. x, y 就是每个节点的位置
2. data 的格式跟散点图一样

**Comment by lili21** [comment]
@pissang 并没有回答如何设置name

> x,y 是节点的位置

坐标系是？相对于什么的位置？
