### ISSUE TITLE
地图数据生成工具不能用啦

### ISSUE THREAD

**Issue by fantasybye** [ecomfe/echarts#6457]
### One-line summary [问题简述]
地图数据生成工具不能用啦

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
什么问题？

**Comment by Ovilia** [comment]
访问 http://ecomfe.github.io/echarts-map-tool/ 而不是 https

**Comment by Ovilia** [comment]
你这个链接是从哪里进的？

**Comment by fantasybye** [comment]
echarts官网。chrome点开这个连接自动就是https了，包括上面你发的那个。

**Comment by yyidota** [comment]
http://ecomfe.github.io/echarts-map-tool/ 这个现在暂时停止了

**Comment by Ovilia** [comment]
项目下线了，如果需要的话，可以使用：https://github.com/ecomfe/echarts-map-tool
