### ISSUE TITLE
echarts3如何支持2中的SVG扩展地图

### ISSUE THREAD

**Issue by llzzll** [ecomfe/echarts#6458]
以前的一个项目要从2移植到3，发现svg地图的api找不到了

**Comment by pissang** [comment]
3 里暂时不支持，你可以试下将 svg 转成 GeoJSON

**Comment by pengliheng** [comment]
2017年8月18日 15:02，"llzzll" <notifications@github.com>写道：

**Comment by stsshenwei** [comment]
想问一下怎么将svg转换成geoJeson
