### ISSUE TITLE
echarts3怎么给x轴y轴添加箭头

### ISSUE THREAD

**Issue by ZjVirus** [ecomfe/echarts#6460]
### One-line summary [问题简述]

echarts3怎么给x轴y轴添加箭头或者如何实现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不能添加
