### ISSUE TITLE
箱线图如何设置填充颜色

### ISSUE THREAD

**Issue by node-rookie** [ecomfe/echarts#6464]
### One-line summary [问题简述]
箱线图如何设置填充颜色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
<http://echarts.baidu.com/option.html#series-boxplot.itemStyle.normal.color>

**Comment by node-rookie** [comment]
`this.ioOption = {
      tooltip: {
        trigger: 'axis',
        axisPointer: {
          type: 'shadow'
        }
      },
      legend: {
        show: false
      },
      grid: {
        left: '6%',
        right: '6%',
        bottom: '3%',
        containLabel: true
      },
      xAxis: [
        {
          name: '系统',
          type: 'category',
          data: ['系统1', '系统2', '系统3', '系统4', '系统5'],
          nameTextStyle: {
            color: 'white'
          }
        }
      ],
      yAxis: [
        {
          name: '平均每次等待时间 ／ms',
          type: 'value',
          nameTextStyle: {
            color: 'white'
          }
        }
      ],
      itemStyle: {
        normal: {
          color: {
            type: 'radial',
            x: 0.5,
            y: 0.5,
            r: 0.5,
            colorStops: [{
              offset: 0, color: 'red' // 0% 处的颜色
            }, {
              offset: 1, color: 'blue' // 100% 处的颜色
            }],
            globalCoord: false // 缺省为 false
          }
        }
      },
      series: [
        {
          type: 'boxplot',
          data: data.boxData
        },
      ]
    };`

设置了 没有任何效果呀
