### ISSUE TITLE
echart 支持水印repeat？

### ISSUE THREAD

**Issue by phypor** [ecomfe/echarts#6469]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/editor.html?c=watermark

**Comment by JX-Zhuang** [comment]
@pissang  添加水印后，主题不生效了
