### ISSUE TITLE
echarts地图 label位置不显示 区域名称，显示数值怎么做

### ISSUE THREAD

**Issue by q269384828** [ecomfe/echarts#6472]
### One-line summary [问题简述]

echarts 地图的 type 为 map 的 系列，如何格式化label为 data中的数值，我在label 中并没有看到有formatter方法，请问 有什么方法可以配置吗？

### Version & Environment [版本及环境]： 
+ ECharts version [ECharts 版本]:3.3.2
+ Browser version [浏览器类型和版本]:IE11 Chrome 60.0.3112.101
+ OS Version [操作系统类型和版本]: window10， 

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
最新版本支持 formatter，见 http://echarts.baidu.com/demo.html#map-labels
