### ISSUE TITLE
markLine没有tooltip层吗？希望鼠标经过markLine时可以把markLine信息在tooltip中显示。

### ISSUE THREAD

**Issue by hellolvs** [ecomfe/echarts#6475]
### One-line summary [问题简述]
markLine如果直接把名称显示在线条上，会使得图表很不简洁美观，而且线条近了名称会有各种重叠情况。现在希望markLine上不显示名称，而在鼠标经过时在tooltip中显示名称。
但是调试发现tooltip的formatter中取不到markLine数据，有解决办法吗？

### Version & Environment [版本及环境]
+ ECharts version 3.5.4:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
希望鼠标经过markLine时可以把markLine信息在tooltip中显示。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ericazhang1990** [comment]
echart3不在支持markLine的tooltip吗？

**Comment by Ericazhang1990** [comment]
echart2支持
option = {
    title : {
        text: '未来一周气温变化',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['最高气温','最低气温']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['周一','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLabel : {
                formatter: '{value} °C'
            }
        }
    ],
    series : [
        {
            name:'最高气温',
            type:'line',
            data:[11, 11, 15, 13, 12, 13, 10],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            }
        },
        {
            name:'最低气温',
            type:'line',
            data:[1, -2, 2, 5, 3, 2, 0],
            markPoint : {
                data : [
                    {name : '周最低', value : -2, xAxis: 1, yAxis: -1.5}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name : '平均值'}
                ]
            }
        }
    ]
};



face5face@163.com
 
发件人： Lvs
发送时间： 2017-08-21 21:16
收件人： ecomfe/echarts
抄送： Ericazhang1990; Mention
主题： Re: [ecomfe/echarts] markLine没有tooltip层吗？希望鼠标经过markLine时可以把markLine信息在tooltip中显示。 (#6475)
@Ericazhang1990 echart2有支持吗，可以给个实例吗

**Comment by Ericazhang1990** [comment]
echart3 支持markpint 的tooltip事件，但是markpoint的tooltip如何进行格式化呢？（格式化不影响label的显示）

**Comment by hellolvs** [comment]
@Ericazhang1990 多谢，试过了，echart2有markline的tooltip，echart3没有。咋升级版本功能还少了呢，可以保留这个功能吗？ @100pah 。 echart3的markpoint支持tooltip吗...格式化的话试一下在tooltip的formatter试试

**Comment by Ericazhang1990** [comment]
@hellolvs  可以保留，tooltip中trigger: 'item'即可，但是存在的问题是不能item和axis同时出发，苦恼中

**Comment by hellolvs** [comment]
@Ericazhang1990 感谢提醒，已经解决了。在轴设置下加入axisPointer就可以item和axis同时触发。如下：
`tooltip: {
        trigger: 'item'
    },
xAxis: {
        data: [],
        axisPointer: {
            show: true,
            type: 'line',
            label: {
                show: false
            },
            lineStyle: {
                width: 0.5
            }
        }
    },`

**Comment by RoMpapp** [comment]
@hellolvs 刚也遇到这种问题，感谢提供。
