### ISSUE TITLE
axisPointer 触发的tooltip展示能否通过formatter回调进行控制？

### ISSUE THREAD

**Issue by mmoonzhu** [ecomfe/echarts#6476]
### One-line summary [问题简述]
我想实现 axis 和 item 都能触发不同的tooltip进行展示，并都通过相应的formatter控制相应的展示效果。仿照 http://gallery.echartsjs.com/editor.html?c=xH1-bHpy0l&v=1 例子，能够做到axis 和item都触发不同的tooltip。但此时，这两个tooltip只有item触发的才能使用series中tooltip的formatter回调进行控制，而axisPointer触发的tooltip我无法通过formatter进行控制。我想问一下，axisPointer触发的tooltip，能否有哪个formatter回调函数进行控制？ 我想利用它进行一些 同x轴数据按从大到小排序等操作。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:chrome  60.0.3112.90
+ OS Version [操作系统类型和版本]:macOS Sierra 10.12.5 

### Expected behaviour [期望结果]

期望 item触发的tooltip使用一个formatter进行控制，x轴的 axisPointer 触发的tooltip使用另一个formatter独立的进行控制。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hellolvs** [comment]
可以的。在tooltip的formatter中判断当前类型是不是markLine，返回不同格式就可以。
```
tooltip: {
        trigger: 'item',
        formatter: function (params) {
            if (params.componentType === 'markLine') {
                return format1;   //自定义format1
            }
            return format2; //自定义format2
        }
    },
```

**Comment by mmoonzhu** [comment]
多谢 hellolvs ，不过componentType都是“series”，是相同的。 又多试了下，发现option.tooltip.formater 能被 x轴的axisPointer触发； 而option.series.tooltip.formatter 能被 在点上的悬浮 触发。所以通过这两个formatter应该就能达到我的效果。

**Comment by hellolvs** [comment]
啊，因为我的markLine和markPoint是单独一个data为空的series，这样多个series不会造成markLine重复，也方便用图例控制是否显示markLine。

**Comment by huainanhai** [comment]
@mmoonzhu 你的这个方法好像不行吧  不会触发series.tooltip
