### ISSUE TITLE
在angular2里面使用echart 导致内存泄漏

### ISSUE THREAD

**Issue by sadydai** [ecomfe/echarts#6482]
在angular2 里面使用了echart 来绘制图表但是发现内存严重泄漏，然后在ngOnDestroy 就是组件销毁的时候用dispose 来销毁图表，但是好像还是没有效果。。。。。

**Comment by pissang** [comment]
提供一个可以让我们复现的项目文件？

**Comment by Amy-1989** [comment]
为什么关了吗？我是用了echart之后，页面非常慢了
