### ISSUE TITLE
echart能实现这样的图表效果吗？

### ISSUE THREAD

**Issue by coderunner-xinxin** [ecomfe/echarts#6484]
### One-line summary [问题简述]

由于echart没有这样的图表类型，所以我猜想可以用多个折线图拼接实现业务逻辑，请问怎样使y轴零刻度线不贴近x轴，而是离x轴有一段距离？图一是业务逻辑图
![image](https://user-images.githubusercontent.com/16172530/29551246-6b4708cc-8744-11e7-9b63-3938fb0ff9d0.png)
图二是目前已实现效果图
![image](https://user-images.githubusercontent.com/16172530/29551266-773a2fec-8744-11e7-8240-a42914d2da03.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by coderunner-xinxin** [comment]
现在有获取在canvas上数据坐标值的API吗，求指教

**Comment by coderunner-xinxin** [comment]
前一个问题已经用比较取巧的方式解决了，现在需要在echart上添加虚线提示。如果能在外部有获取坐标的API的话最好，如果没有的话就试试用echart自定义系列renderItem，求指教
![image](https://user-images.githubusercontent.com/16172530/29594716-50fe7490-87e5-11e7-88e8-bea97605668f.png)

**Comment by ZoeHuang13** [comment]
把线补上，这个单独的数据的lineStyle设成虚线可以吗？

**Comment by coderunner-xinxin** [comment]
应该是达不到这样的效果的，产品原型图里的虚线表示的是一个升降级的关系
![image](https://user-images.githubusercontent.com/16172530/29595226-c8c88242-87e8-11e7-80f7-053bc3e4c999.png)
不知道用自定义renderItem能不能实现😂我第一次用，还没有理解明白，不知道怎么实现，这就很尴尬了

**Comment by coderunner-xinxin** [comment]
我明白你的意思。如果照你说的做，一是怎么单独给那个数据设置成虚线呢？二是y轴的坐标系该怎么实现呢？（y轴的坐标系其实分两部分）谢谢指教，哈哈

**Comment by coderunner-xinxin** [comment]
我觉得要是用echart的自定义系列renderItem的话应该可以实现，但是我还没理解明白怎么才能实现，这就很尴尬了😂

**Comment by ZoeHuang13** [comment]
我这边想到的3种方法：
1.再弄一个series，专门用虚线表示你那个升降级；
2.用markline；
3.每个数据都是可以有自己的style的：
`当需要对个别数据进行个性化定义时：
数组项可用对象，其中的 value 像表示具体的数值，如：
[
    12,
    34,
    {
        value : 56,
        //自定义标签样式，仅对该数据项有效
        label: {},
        //自定义特殊 itemStyle，仅对该数据项有效
        itemStyle:{}
    },
    10
]
// 或
[
    [12, 33],
    [34, 313],
    {
        value: [56, 44],
        label: {},
        itemStyle:{}
    },
    [10, 33]
]`

关于你的2个y轴的问题，如果不能跨轴的话（因为我没用过），2个y轴值就都设为0
renderItem没接触过抱歉

**Comment by coderunner-xinxin** [comment]
主要就是两个y轴的问题，产品需求的话未来还有可能有四个，所以在一个坐标轴上面实现效果不太可能了，谢谢你的三种方法，涨知识了🙂

**Comment by coderunner-xinxin** [comment]
用非常取巧的办法实现了个大概，现在的问题就是判断数据是从哪儿开始升降级的
![image](https://user-images.githubusercontent.com/16172530/29605068-2a4f29fc-881c-11e7-87b9-6c44fbe70db8.png)

**Comment by coderunner-xinxin** [comment]
没想到居然解决了，哈哈
