### ISSUE TITLE
官网地图下载china.json乱码

### ISSUE THREAD

**Issue by szdbb1102** [ecomfe/echarts#6485]
### One-line summary [问题简述]

在控制台看到需要到官网下载地图数据：http://echarts.baidu.com/download-map.html；
然后到官网下载，但是下载到的json、js中文乱码，无论怎样修改文件编码格式都不对

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 
+ Browser version [浏览器类型和版本]: chrome、火狐均为乱码
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
看到实际的数据格式

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这是压缩后的效果，原始文件见 https://github.com/ecomfe/echarts-map-tool/tree/gh-pages/maker/raw

**Comment by heyun6758** [comment]
地图数据文件(Geojson)中,有中文的地方,只有name属性,值为地区名称.使用UTF-8编码查看是正常显示的.让人感觉是乱码的,可能是coordinates属性,但实际并不是乱码,只是对坐标做了处理而已,echarts在加载时,会解析回实际数据.

**Comment by szdbb1102** [comment]
感谢，ღ( ´･ᴗ･` )比心

**Comment by daXiaxuchao** [comment]
@heyun6758 根据您的说法，我可以把某一省市的坐标删除，从而到达不显示的效果？

**Comment by chfw** [comment]
可以

**Comment by daXiaxuchao** [comment]
@chfw ok，但是我要实现的是南沙的九段线进行移除，在map JSON文件中却没有南沙的信息，其中只是发现了China的34个省份

**Comment by zhangquxi** [comment]
666，谢谢！~

**Comment by chfw** [comment]
从这个 [feature or a bug](https://github.com/ecomfe/echarts/blob/8d44355b53833ae0b9a42f3872e6bac699190a9e/src/coord/geo/fix/nanhai.js) 可以看出呢， 与地图无关，但是与地图名字有关系。

需要做的就是改 china 为任何其他名字，南海诸岛就不出现。

声明一下，南海诸岛是中国不可分割的领土。这是技术讨论啊，不谈政治。
