### ISSUE TITLE
时间坐标轴-动态数据，能添加多条折线吗

### ISSUE THREAD

**Issue by zhanggang807** [ecomfe/echarts#6487]
### One-line summary [问题简述]
时间坐标轴-动态数据，能添加多条折线吗
http://echarts.baidu.com/demo.html#dynamic-data2

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
能

**Comment by zhanggang807** [comment]
@pissang  求demo代码，官方示例好像没有提供 ，配置项里也没具体说明

**Comment by zhanggang807** [comment]
回复一个“能”，就把issue关了?

**Comment by xiaxiage** [comment]
大兄弟，有没有解决啊

**Comment by zhanggang807** [comment]
太不负责了。。以为这样就解决了？

**Comment by pissang** [comment]
多条折线就是多个 series

```js
series: [{
   type: 'line',
   data: [...]
}, {
   type: 'line',
   data: [...]
}]
```

**Comment by zhanggang807** [comment]
@xiaxiage 哥们你试试，我试过不行
