### ISSUE TITLE
tooltip显示问题

### ISSUE THREAD

**Issue by Aeero** [ecomfe/echarts#6497]
### One-line summary [问题简述]

折线图，未设置connectNulls时会出现断层，鼠标移动到断层的时候会变成下图这样（红色框中是鼠标的位置）
![tooltip1](https://user-images.githubusercontent.com/13835083/29600822-c8688212-880a-11e7-8488-cab8214f435e.jpg)

希望的结果应该是

![tooltip2](https://user-images.githubusercontent.com/13835083/29600849-f07a2d14-880a-11e7-96c2-c13c7d91d9a7.jpg)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.0
+ Browser version [浏览器类型和版本]: chrome 58
+ OS Version [操作系统类型和版本]: win 7

### Expected behaviour [期望结果]

鼠标移动到断层的时候可以显示最近一个数据点的tooltip。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

https://jsfiddle.net/aav4cLjd/2/

**Comment by Anluis** [comment]
```
var chart = echarts.init(document.getElementById('chart'));
var Xdata = ['09:30', '09:31', '09:32', '09:33', '09:34', '09:35', '09:36', '09:37', '09:38', '09:39', '09:40']
var Ydata = [1, 2, 3, 4, 5, 6, '-', '-', '-', '-']
var lastData = Ydata[Ydata.indexOf('-') - 1];
var opt = {
	tooltip: {
  	trigger: 'axis',
    formatter: function(obj) {
    	return obj[0].data === '-' ? lastData : (obj[0].data)
    }
  },
  xAxis: {
  	type: 'category',
    data: Xdata
  },
  yAxis: {
  	type: 'value'
  },
  series: {
  	type: 'line',
    data: Ydata
  }
};

chart.setOption(opt);
```

给空的数据打上标记，比如'-',用formatter来判断下，如果已经超出最后一个数据就显示最近一个。

示例:https://jsfiddle.net/anluis/tsd7rcs4/
