### ISSUE TITLE
area-stack实例bug

### ISSUE THREAD

**Issue by yueshuiniao** [ecomfe/echarts#6506]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/17233090/29646611-21ab2a26-88b7-11e7-954d-5ee68d82fe08.png)

官方demo： [area-stack](http://echarts.baidu.com/demo.html#area-stack)，图上的1300对应坐标轴上的2500。产生原因应该是，坐标轴上的最大值，默认是根据所有项的和的最大值计算出的，这有问题

### Expected behaviour [期望结果]
图上的值和坐标轴上的值正确对应

我想知道我的代码该怎么写才能是正确的效果

**Comment by pissang** [comment]
http://echarts.baidu.com/faq.html#line-chart
