### ISSUE TITLE
tooltip中的formatter 函数问题

### ISSUE THREAD

**Issue by clearBird** [ecomfe/echarts#6509]
你好！
    Echarts开发组。

    ===========问题描述==============
    我有这样一段代码，放在官网图例中好用，但是当放到我自己的代码中时，缺总是提示错误
    'tooltip': {
        'trigger': 'item',
        'formatter': function(params) {  
            var res = params.name+'<br/>';  
            var myseries = option.series;
            for (i in myseries) {  
                    for(var j=0;j<myseries[i].data.length;j++){ 
                        if(myseries[i].data[j].name==params.name){
                            res+=myseries[i].name+' : '+myseries[i].data[j].value+'</br>';  
                        } 
                }         
            }  
            return res;  
        }
    },
总是提示 option未定义，请问，我如果自己定义的话，这个option 应该是什么？

**Comment by Ovilia** [comment]
就是你 setOption(option) 的这个参数
