### ISSUE TITLE
关系图不能初始默认放大效果

### ISSUE THREAD

**Issue by suptwo** [ecomfe/echarts#6510]
### One-line summary [问题简述]

关系图不能初始默认放大效果,比如图中有1K+数据图上的点会显示得非常小，希望可以配置初始放大多少倍

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版本
+ Browser version [浏览器类型和版本]:  最新版本
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]

希望可以配置放大效果

### ECharts option [ECharts配置项]

```javascript
官网示例即可
option = {

}

```

**Comment by suptwo** [comment]
![2](https://user-images.githubusercontent.com/12033906/29660883-06cf1300-88f5-11e7-8b30-085cc66bcd4a.png)

![1](https://user-images.githubusercontent.com/12033906/29660881-060ccea8-88f5-11e7-8ecb-346f459fde34.png)

**Comment by suptwo** [comment]
初始化是第二幅图  希望可以通过配置初始化之后有这个放大的功能

**Comment by suptwo** [comment]
@pissang 这个需求有计划列入下版本更新中吗？

**Comment by suptwo** [comment]
在中国地图中找到了这个API
myChart.setOption({
        series: [{
            center: [0, 0],
            zoom: 4,
            animationDurationUpdate: 1000,
            animationEasingUpdate: 'cubicInOut'
        }]
    });

**Comment by yaoocheng** [comment]
配置个整个 zoom: 4  就好了 关系图
