### ISSUE TITLE
升级了echarts 3的版本之后（3.3.2升级到3.6.2），原先没有数据时Y轴是有默认刻度的，现在刻度没了，是哪个配置改了吗？

### ISSUE THREAD

**Issue by Justin-Shen** [ecomfe/echarts#6511]
### One-line summary [问题简述]

升级了echarts 3的版本之后（3.3.2升级到3.6.2），原先没有数据时Y轴是有默认刻度的，现在刻度没了，是哪个配置改了吗？

3.3.2版本下：

![echarts2](https://user-images.githubusercontent.com/7840139/29657362-ea89f35a-88e9-11e7-9ca5-4fe10d975b37.png)

3.6.2版本下：

![echarts1](https://user-images.githubusercontent.com/7840139/29657361-ea8089a0-88e9-11e7-8140-62edad0ae14c.png)

**Comment by pissang** [comment]
新版本无数据就不显示刻度了，需要显示的话可以设置`min: 0, max: 1`
