### ISSUE TITLE
重庆地图开州区无法显示

### ISSUE THREAD

**Issue by yuebeifan0** [ecomfe/echarts#6515]
### One-line summary [问题简述]
使用了chongqing.js 地图文件；但开州区好像少了些数据；实际呈现看不到该地区轮廓；

{"id":"500154","type":"Feature","geometry":{"type":"Polygon","coordinates":[],"encodeOffsets":[]},"properties":{"cp":[108.413317,31.167735],"name":"开州区","childNum":0}},

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![aaa1](https://user-images.githubusercontent.com/31308546/29660753-ab03fd1a-88f4-11e7-8d17-2536ed866b41.png)

**Comment by ldcxtu** [comment]
还有chongqing.js这个文件么？现在官方不提供下载了，求分享，501834656@qq.com，非常感谢

**Comment by chfw** [comment]
https://github.com/pyecharts/jupyter-echarts/blob/master/echarts/chongqing.js
