### ISSUE TITLE
k线图中开盘价跟收盘价相等的时候能不能设置一种颜色

### ISSUE THREAD

**Issue by song0320** [ecomfe/echarts#6527]
### One-line summary [问题简述]
现在k线图里只有两种颜色，红和绿，在开盘价和收盘价相等的情况下线条的颜色我不知道是怎么出来的，我能不能自己设置一个颜色，比如 白色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
[color](http://echarts.baidu.com/option.html#series-candlestick.itemStyle.normal.color) 和 [color0](http://echarts.baidu.com/option.html#series-candlestick.itemStyle.normal.color0) 可以是回调函数

**Comment by song0320** [comment]
非常感谢您的回复，我刚才试了一下，我的代码如下
  color: function(a,b){
                        
                        if(a.data[1] == a.data[2])
                        {
                            return '#FFFFFF';
                        }
                        else
                        return '#FD1050';
                    },
                    color0: function(a,b){
                        
                        
                        if(a.data[1] == a.data[2])
                        {
                            return '#FFFFFF';
                        }
                        else
                        return '#0CF49B';
                    },


调试环境是http://echarts.baidu.com/demo.html#candlestick-sh-2015

调试能进，但好像不起做用， 好像改borderColor不成功，应该是不支持回调吧

**Comment by song0320** [comment]
color是里面的background-color，但是当开盘和收盘价相等的时候是只有一条线的，也就是borderColor起做用

**Comment by song0320** [comment]
好像是我理解错了，borderColor也是可以的，但是参数不能传，一传就会出错，我现在是这样写的
 borderColor0: ccc(data)
可是我在ccc这个方法里不知道当前项的值，请问怎么能取到
