### ISSUE TITLE
折线图(line)里面，label的fontSize，color等按照配置项里面正确写了以后不生效的问题

### ISSUE THREAD

**Issue by himushroom** [ecomfe/echarts#6541]
### One-line summary [问题简述]
折线图(line)里面，label的fontSize，color等按照配置项里面正确写了以后不生效，下面是按照官方文档的写法
```javascript
option = {
  ...,
  series: {
    label:{
       normal: {
           fontSize: 24,
           color: '#ccc'
       }
    }
  }
}
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]:  版本 60.0.3112.101（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: mac 10.12.6

### Expected behaviour [期望结果]

这个问题我已经解决了
在写fontSize等textStyle的时候要在外层再套一层textStyle就生效了，希望可以修复官方文档，避免误导，正确配置如下：
```javascript
option = {
  ...,
  series: {
    label:{
       normal: {
          textStyle: {
              fontSize: 24,
              color: '#ccc'
          }
       }
    }
  }
}
```

**Comment by 100pah** [comment]
参见 <http://echarts.baidu.com/changelog.html>
没有 `textStyle` 的写法是从 `3.7.0` 开始的。
