### ISSUE TITLE
Calendar heatmap horizontal: error when computers sets with timezone UTC < -3

### ISSUE THREAD

**Issue by brunolajoie** [ecomfe/echarts#6543]
### One-line summary [问题简述]
Echarts calendar heat map does not work on client's browsers when their computers are set to a timezone of UTC -3 or below (for instance, in the US). Error: "Uncaught TypeError: Cannot read property '0' of undefined"

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3 (https://ecomfe.github.io/echarts-examples/public/#chart-type-calendar)
+ Browser version [浏览器类型和版本]: Chrome 60.0.3112.101
+ OS Version [操作系统类型和版本]: MacOSX 10.12.6

### Expected behaviour [期望结果]
Normal display of the chart

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
        position: 'top'
    },
    visualMap: {
        min: 0,
        max: 1000,
        calculable: true,
        orient: 'horizontal',
        left: 'center',
        top: 'top'
    },

    calendar: [
    {
        range: '2017',
        cellSize: ['auto', 20]
    },
    {
        top: 260,
        range: '2016',
        cellSize: ['auto', 20]
    },
    {
        top: 450,
        range: '2015',
        cellSize: ['auto', 20],
        right: 5
    }],

    series: [{
        type: 'heatmap',
        coordinateSystem: 'calendar',
        calendarIndex: 0,
        data: getVirtulData(2017)
    }, {
        type: 'heatmap',
        coordinateSystem: 'calendar',
        calendarIndex: 1,
        data: getVirtulData(2016)
    }, {
        type: 'heatmap',
        coordinateSystem: 'calendar',
        calendarIndex: 2,
        data: getVirtulData(2015)
    }]
}

```

### Other comments [其他信息]

The error can easily be reproduced at the demo page https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-horizontal as long as timezone setting is set to UTC -3 or below. Error disappear when changing the timezone to European or Asian ones

**NORMAL BEHAVIOR**
![image](https://user-images.githubusercontent.com/22095643/29838155-5d696464-8cc8-11e7-9e12-d4e7bf6154c3.png)
![image](https://user-images.githubusercontent.com/22095643/29838216-8fcf3122-8cc8-11e7-8b06-969148ebe887.png)

**BUGGING BEHAVIOR:**
![image](https://user-images.githubusercontent.com/22095643/29838034-f8d989ac-8cc7-11e7-96d4-712010b5c1e1.png)
![image](https://user-images.githubusercontent.com/22095643/29837999-dadb3bee-8cc7-11e7-834f-43b974b61f42.png)

**Comment by corradio** [comment]
As state here (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset), the getTimezoneOffset() method returns the time zone difference, in minutes, from **current locale (host system settings)** to UTC.
It makes sense to get different results.

**Comment by brunolajoie** [comment]
@100pah I think this may help fix the bug https://stackoverflow.com/questions/2771609/how-to-ignore-users-time-zone-and-force-date-use-specific-time-zone
