### ISSUE TITLE
柱状堆叠图怎么显示百分比

### ISSUE THREAD

**Issue by ruifeng99** [ecomfe/echarts#6544]
目前，tooltips上只能显示财务部下，每个等级的人数，我想在人数后面打个括号，写上百分比，eCharts3能实现吗？例如，L4：12(20%)这样。
![image](https://user-images.githubusercontent.com/13119665/29852300-e516d65a-8d6b-11e7-8c01-fa42c2d7ba6b.png)

**Comment by pissang** [comment]
http://echarts.baidu.com/option.html#tooltip.formatter
