### ISSUE TITLE
为什么echart3没有炫光了！！完全做不出echart2的迁徙图的效果。

### ISSUE THREAD

**Issue by piglingcn** [ecomfe/echarts#6550]
### One-line summary [问题简述]

为什么echart3没有炫光了！！完全做不出echart2的迁徙图的效果。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

炫光！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这个行吗？http://echarts.baidu.com/option.html#series-effectScatter.type 加上 http://echarts.baidu.com/option.html#series-effectScatter.itemStyle.normal.shadowBlur 应该能够模拟的
