### ISSUE TITLE
关系图-树形布局

### ISSUE THREAD

**Issue by freebird816** [ecomfe/echarts#6562]
### One-line summary [问题简述]

现在关系图的布局类型有点少，树形布局是很常见的布局方式，希望ehcarts团队能考虑增加一些布局，比如树形布局

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

增加树形布局

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
新版本将支持树图

**Comment by daxiong-liang** [comment]
同样我这边也是需要树形图

**Comment by seekei** [comment]
> 新版本将支持树图

请问一下这个版本已经发布了吗？
