### ISSUE TITLE
饼图 label Title 重叠

### ISSUE THREAD

**Issue by leipingyi** [ecomfe/echarts#6564]
![screen shot 2017-08-31 at 5 49 54 pm](https://user-images.githubusercontent.com/26576598/29917680-407313b0-8e75-11e7-83c4-17c80b0b2f8e.png)
![screen shot 2017-08-31 at 5 49 02 pm](https://user-images.githubusercontent.com/26576598/29917688-49629e3c-8e75-11e7-9399-84d47b27f71d.png)
![screen shot 2017-08-31 at 5 48 15 pm](https://user-images.githubusercontent.com/26576598/29917707-5179963e-8e75-11e7-9607-d563e4189f70.png)

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/6559
