### ISSUE TITLE
【强烈建议】请提供历史版本文档

### ISSUE THREAD

**Issue by mcdongWang** [ecomfe/echarts#6565]
### One-line summary [问题简述]

我们并没有升级echarts 到 3.7.0 + 

配置文档 已经不一样了 我们需要历史版本文档

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.0-
+ Browser version [浏览器类型和版本]: All
+ OS Version [操作系统类型和版本]: All

### Expected behaviour [期望结果]

提供历史版本文档

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
历史版本文档请参阅：
<https://github.com/ecomfe/echarts-doc/releases/tag/3.6.2>

需本地开启 HTTP Server 访问。
访问其中的 `public/en/option.html` 就是配置项参考手册。

**Comment by mcdongWang** [comment]
感谢开发者的快速响应
