### ISSUE TITLE
x轴相邻的多个刻度都一样，是bug, 还是本身就是正常的

### ISSUE THREAD

**Issue by liping1994** [ecomfe/echarts#6569]
![image](https://user-images.githubusercontent.com/23331306/29954154-510c71ce-8f08-11e7-8955-b23a6ae55f03.png)

**Comment by pissang** [comment]
请提供下配置项，echarts 版本

**Comment by liping1994** [comment]
const timeAxis = {
  color: ['#108ee9'],
  tooltip: {
    show: false,
    trigger: 'axis',
    axisPointer: {
      type: 'shadow',
      axis: 'x',
    },
  },
  legend: {
    show: false,
  },
  grid: {
    top: '20',
    left: '1%',
    right: '90',
    bottom: '3%',
    containLabel: true
  },
  toolbox: {
    top: '12',
    right: '6',
    itemSize: 13,
    itemGap: 6,
    feature: {
      brush: {
        type: ['lineX', 'clear'],
        title: {
          lineX: intl.get('Analysis_NavList_Config_REGION'),   //框选
          clear: intl.get('Analysis_TimeLine_WIPECHOIC'),   //清除
        },
      },
    },
    iconStyle: {
      emphasis: {
        color: '#0d8a71',
	textPosition: 'top'
      }
    }
  },
  brush: {
      toolbox: ['lineX', 'clear'],
      xAxisIndex: 'all',
      transformable: true,
      brushStyle: {
        borderWidth: 1,
        color: 'rgba(26,179,148,0.3)',
        borderColor: 'rgba(26,179,148,0.3)'
      },
      brushMode: 'single',
      brushType: 'lineX',
      removeOnClick: false,
      throttleType: 'debounce',
      throttleDelay: 300,
      inBrush: {
        colorAlpha: 1
      },
      outOfBrush: {
        colorAlpha: 1
      }
  },
  xAxis: {
    type : 'time',
    axisTick: {
      alignWithLabel: true
    },
    nameLocation: 'middle',
    min: null,
    max: null,
    splitNumber: 10,
  },
  yAxis: {
    type : 'value',
    nameGap: 20,
    axisLine: false,
    splitArea: false,
  },
  dataZoom: [
    {
      type: 'inside',
      xAxisIndex: [0],
      throttle: 100,
    },
  ],
}

const Opts = {
  timeAxis,
}

export default Opts

**Comment by liping1994** [comment]
echarts 版本为3.0

**Comment by liping1994** [comment]
![image](https://user-images.githubusercontent.com/23331306/29958396-36c09738-8f25-11e7-97aa-a63aecaa3e86.png)
再滑动之后就出现重复的了 很诡异，关键我不知道问题的原因
![image](https://user-images.githubusercontent.com/23331306/29958413-4d7cbb6e-8f25-11e7-9a38-415fa7994536.png)

**Comment by liping1994** [comment]
我知道原因了 我没有设置最小的间隔  所以返回的时间戳 很接近，然后 就这样了

**Comment by liping1994** [comment]
好像没啥卵用

**Comment by liping1994** [comment]
![image](https://user-images.githubusercontent.com/23331306/29963915-07183c14-8f3b-11e7-937c-c45ddc9637bf.png)
当前已经到天了， 再次放大，只可能是出现重复的，我觉得原因是这个
![image](https://user-images.githubusercontent.com/23331306/29963979-39d2de3e-8f3b-11e7-9deb-982f5efb3abd.png)
