### ISSUE TITLE
k线图如何自定义k柱的颜色

### ISSUE THREAD

**Issue by zhouqing30261114** [ecomfe/echarts#6573]
如何不按照阴阳来定颜色，而是自己写逻辑来定义每根k柱的颜色。

我写了如下代码，发现k柱画不出来：
myChart.setOption({
            xAxis: {
                data: ["2013/1/24"],
            },
            series: [{
                data: [{
                    value: [2320.26,2350.26,2287.3,2362.94],
                    itemStyle: {
                        color: '#ff0000'
                    }
                }]
            }],
        });

**Comment by Ovilia** [comment]
itemStyle 里面先 normal 再 color，参见：http://echarts.baidu.com/option.html#series-candlestick.itemStyle.normal.color

**Comment by zhouqing30261114** [comment]
这种配置画不出来图形，麻烦看下为什么？

option = {
    xAxis: {
        type: 'category',
        data: ['2013/6/13'],
    },
    yAxis: {
        scale: true,
    },
    series: [
        {
            type: 'candlestick',
            data: [{
                value: [2190.1,2148.35,2126.22,2190.1],
                itemStyle: {
                    normal: {
                        color: '#ff0000',
                        color0: '#00ff00',
                        borderWidth: 1,
                        opacity: 1,
                    }
                }
            }]
        },
    ],
};

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html?c=xBk_DDgdPb&v=2

**Comment by zhouqing30261114** [comment]
多谢不厌其烦的指点，其实我的需求是这样的：
正常的k柱颜色都是这样的逻辑，开盘价比收盘价高就用一种颜色，低用另外一种颜色，而我想通过另外一种逻辑来判断颜色。
我想到了一种变通的方法，就是通过调换开盘价和收盘价的位置来取颜色。
