### ISSUE TITLE
Echarts官网的2.0版本的饼图最小角度设置无效

### ISSUE THREAD

**Issue by yixiongmao** [ecomfe/echarts#6579]
我用官网上2.0的实例测试饼图的最小角度无效，哪位大神给指导下2.0版本的echarts饼图如何设置最小角度，要不都堆在一起了
（实例地址：http://echarts.baidu.com/echarts2/doc/example/pie1.html）
![tim 20170902141712](https://user-images.githubusercontent.com/31560439/29993439-9018117a-8fe9-11e7-8f84-cf012cb7c357.png)

**Comment by Ovilia** [comment]
好像是有问题，建议升级到 3.x 版本，因为现在 2.0 已经不维护了
