### ISSUE TITLE
官网桑基图的那个数据（erergy.json）可否提供一下？

### ISSUE THREAD

**Issue by xiaoguozhi** [ecomfe/echarts#6581]
### One-line summary [问题简述]

官网桑基图的那个数据（erergy.json）可否提供一下？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/gallery/data/asset/data/energy.json
