### ISSUE TITLE
饼图 被选中扇形的 样式，可否调整

### ISSUE THREAD

**Issue by yueshuiniao** [ecomfe/echarts#6587]
### One-line summary [问题简述]

饼图，能不能控制被选中的部分，向外移动的距离？看配置参数里itemStyle只有normal和emphasis两项，没有改变被选中的扇形的样式的选项
![image](https://user-images.githubusercontent.com/17233090/30018006-cefcf5ea-918d-11e7-984d-5e2256b4c677.png)

### Expected behaviour [期望结果]
被选中扇形向外扩展的距离可以调整

**Comment by Ovilia** [comment]
准备加一个控制距离的配置项

**Comment by Ovilia** [comment]
已支持 #3857
