### ISSUE TITLE
Nested regions get highlighted borders when moving mouse over 'parent' region

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts#6589]
Version: 3.6.2

![map-border](https://user-images.githubusercontent.com/561365/30022154-6ce88c7a-916a-11e7-8552-ca15ecc3b435.gif)

areaColor work as expected:

![map-area](https://user-images.githubusercontent.com/561365/30022263-eb3689a6-916a-11e7-9f2d-2d163fc64ff1.gif)

Here is a sample geo json: https://gist.githubusercontent.com/jarben/6fe145bc8db35063638060666a3118cf/raw/dba59a4e186ef54e97ae541e69ed276582d7a818/czech_geo_example 

Related (closed) issue: https://github.com/ecomfe/echarts/issues/3171

**Comment by 100pah** [comment]
It seams that it is not the `nested` problem, but the `itemStyle` problem.
Could I have you `option` to check the settings?

**Comment by jarben** [comment]
HI @100pah , sorry you're absolutely right, the inner border should be shown if hovering over the ring area, it just confused my brain so I thought it's a bug related to the #3171 issue. I hope I didn't waste too much of your time!
