### ISSUE TITLE
markLine 根据两个点绘制一条贯穿整个grid的直线

### ISSUE THREAD

**Issue by liihuu** [ecomfe/echarts#6592]
### One-line summary [问题简述]

怎么用markLine 根据两个点绘制一条贯穿整个grid的直线，用graphic也是给出的两个点画的一条线段

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
通过两点计算所在直线，然后把 x 指取 0 到 100% 的距离

**Comment by liihuu** [comment]
@Ovilia 有没有更好的解决方案呢？

**Comment by Ovilia** [comment]
你有什么建议？

**Comment by liihuu** [comment]
@Ovilia 没有想到好的方法，所以才向大佬请教

**Comment by Ovilia** [comment]
你在 http://gallery.echartsjs.com/editor.html 上写个线段的例子，我帮你改成直线

**Comment by liihuu** [comment]
@Ovilia 已加好，请大佬帮忙，谢谢。

**Comment by Ovilia** [comment]
链接？

**Comment by liihuu** [comment]
不好意思   http://gallery.echartsjs.com/editor.html?c=xHJdTVNCKZ&v=1

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html?c=xHJdTVNCKZ&v=2 大致就这么个意思，如果 grid 是百分比的，自己按百分比计算出像素大小

**Comment by liihuu** [comment]
@Ovilia 感谢大佬百忙之中帮忙解答问题，已解决。
