### ISSUE TITLE
3.7 以上版本没有 registerMap 方法

### ISSUE THREAD

**Issue by TangHaiyan** [ecomfe/echarts#6593]
### One-line summary [问题简述]
echarts 3.7 以上版本里没有 registerMap 方法，搜索源码也没有看到相关信息。注册地图失败。 
有什么其他方式注册地图么？
 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: chrome 60
+ OS Version [操作系统类型和版本]: mac

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你需要下载带有地图组件的版本
