### ISSUE TITLE
关于地图lines-bus的生成

### ISSUE THREAD

**Issue by SynChron1zed** [ecomfe/echarts#6595]
### One-line summary [问题简述]

现在我想写入其它地方的lines-bus.json。这个json我想知道如果我要写其它城市的，是需要自己根据经纬度一个个定位写入么，还是会有其它生成工具，麻烦告知下

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
你有数据的话程序转一下就行

**Comment by SynChron1zed** [comment]
@pissang  没有数据 有那种方式能获取到数据么

**Comment by SynChron1zed** [comment]
@pissang  我自己通过坐标拾取弄到数据 怎么转换成[1126800,334544,-12,2,-34,3] 这种格式
