### ISSUE TITLE
是否可以提供一个全国下钻到省市再下钻到地市的合并JS.

### ISSUE THREAD

**Issue by Eric611** [ecomfe/echarts#6597]
使用咱们平台地图做下钻的需求挺多的。能不能提供一个基础版的合并js啊？这样大家就能把更多的时间来丰富地图使用中的其他效果和功能了。大家不用再一块一块的拼接这么一个全国的地图框架。有了这个方便的工具，相信使用echarts的人会越来越多。不知道咱们是要把这个产品做成大众化的产品还是小众化的产品。

**Comment by pissang** [comment]
抱歉暂时没有这个计划

**Comment by chfw** [comment]
Jupyter-echarts含有一线城市和省，以及363个二线城市的地图。下钻自己可以实现。
