### ISSUE TITLE
ehcart如何实现在环形图上hover时高亮放大部分环形？

### ISSUE THREAD

**Issue by hanxiansen** [ecomfe/echarts#6599]
我看到echart用的是canvas绘图的，在环形图示例中，当把鼠标移动到上面时，会高亮放大该部分环形图，在我的理解中canvas不应该是一个整体吗，请问如何做到鼠标hover时只高亮放大该部分呢？

**Comment by Ovilia** [comment]
会对整个 canvas 重绘，绘制的时候特定元素被放大
