### ISSUE TITLE
K线图设置问题

### ISSUE THREAD

**Issue by menkeydyvh** [ecomfe/echarts#6606]
### One-line summary [问题简述]

K线图的配置 markArea.data 设置完区域后  不能设置区域的偏移量吗？

**Comment by Ovilia** [comment]
那你自己加一下不行吗？

**Comment by Ovilia** [comment]
你的意思是不是希望有个 offset 值，可以比数据对应的位置有所偏移，单位是像素或相对容器的百分比？
