### ISSUE TITLE
最小值计算错误

### ISSUE THREAD

**Issue by chenglinquan** [ecomfe/echarts#6613]
### One-line summary [问题简述]

在echarts 3.0官方示例中 http://echarts.baidu.com/demo.html#line-marker  
折线图最低温度显示错误

echarts 2.0示例就不存在这个问题  http://echarts.baidu.com/echarts2/doc/example/line1.html

 [期望结果]
-2   
![image](https://user-images.githubusercontent.com/19650409/30143524-d34f78b6-93b8-11e7-857c-6a02849ef69b.png)

[实际结果]
-1.5

![image](https://user-images.githubusercontent.com/19650409/30143544-f63edede-93b8-11e7-816b-a1f170e32546.png)

**Comment by pissang** [comment]
这个例子写得有点问题，去掉下面途中选中部分的代码就行了
![image](https://user-images.githubusercontent.com/841551/30148524-6310f4d0-93d6-11e7-91b6-cf581e75f2a6.png)
