### ISSUE TITLE
当重复实例化时出现内存泄漏

### ISSUE THREAD

**Issue by liangxiaoyang** [ecomfe/echarts#6615]
### One-line summary [问题简述]
当重复初始化画图时出现内存泄漏

当重复调用这个函数实例化，原先的实例不会释放，导致里面会出现很多个图表实例，当触发点击事件时，实例化几次就会触发几次。这时请求数据或传输数据时，就会呈现2的n次方上涨，问题太严重。另一个也会出现文字标题颜色越来越深，叠加了。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.1
+ Browser version [浏览器类型和版本]:Chrome 59.0.3071.115
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
会自动释放内存

### ECharts option [ECharts配置项]
```js
function others(){
    var myChart = echarts.init(document.getElementById('a'));
		option = {
			title: {
				text: '堆叠区域图'
			},
			tooltip: {
				trigger: 'axis',
				axisPointer: {
					type: 'cross',
					label: {
						backgroundColor: '#6a7985'
					}
				}
			},
			legend: {
				data: ['邮件营销']
			},
			toolbox: {
				feature: {
					saveAsImage: {}
				}
			},
			grid: {
				left: '3%',
				right: '4%',
				bottom: '3%',
				containLabel: true
			},
			xAxis: [{
				type: 'category',
				boundaryGap: false,
				data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
			}],
			yAxis: [{
				type: 'value'
			}],
			series: [{
				name: '邮件营销',
				type: 'line',
				data: [{
					value: 120,
					symbol: 'pin',
					symbolSize: 20
				}, 132, 101, 134, 90, 230, 210]
			}]
		};
		

		window.addEventListener("resize", function() {
			myChart.resize();
		});
		myChart.setOption(option);
}
```

### Other comments [其他信息]
![image](https://user-images.githubusercontent.com/25275166/30144747-b7bcf824-93bf-11e7-8e01-af4ec5aabddb.png)

**Comment by pissang** [comment]
新版本不支持对一个 dom 多次创建实例吧

**Comment by liangxiaoyang** [comment]
那就是说，以后不再支持这种对一个 dom 实例化了是吗

**Comment by liangxiaoyang** [comment]
myChart.setOption({option的内容})，这种就不会出现上述问题，为什么？
