### ISSUE TITLE
反馈一个报错，每天几百万的错误量

### ISSUE THREAD

**Issue by king-king** [ecomfe/echarts#6622]
### One-line summary [问题简述]

我用的是echarts3.2.3版本的代码，我们有一个自动搜集js错误的系统，接入这套系统后发现echarts每天的报错量少则4、5百万，多则将近1千万。原始报错是：
TypeError: Cannot read property 'length' of undefined at a (/js/lib/echarts-a08e672bdf.min.js:9:12466) at q (/js/lib/echarts-a08e672bdf.min.js:9:14526) at e.onframe (/js/lib/echarts-a08e672bdf.min.js:9:15725)。后来我们定位了这个问题：是echarts中的interpolateArray，在执行这段代码：var len2 = p0[0].length;时候报的错误。p0[0]是undefined。请问这是怎么回事呢？我也尝试阅读echarts的代码，也研究了arrDim的机制，从代码里得不到答案。

我们定位似乎是当鼠标划过的时候，数组插值判定是二维数组，但实际上p0[0]是undefined。我们的tootip是这么配置的：
                     tooltip: {
                            show:false,
                            trigger: 'axis',
                            lineStyle: {
                                color: "#9199c2"
                            }
                        }

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.2.3
+ Browser version [浏览器类型和版本]:
```js
[
  {
    "val": 1949463,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3357.400 QQBrowser/9.6.11858.400"
  },
  {
    "val": 1872727,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 1227963,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 1052228,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
  },
  {
    "val": 841802,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
  },
  {
    "val": 779531,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 600900,
    "ua": "Mozilla/5.0 (Linux; Android 6.0; XGIMI TV Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.131 Safari/537.36"
  },
  {
    "val": 513130,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 388466,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 114895,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.108 Safari/537.36 2345Explorer/8.4.1.14855"
  },
  {
    "val": 82635,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3373.400 QQBrowser/9.6.11864.400"
  },
  {
    "val": 67205,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 57766,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 48256,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 40419,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 37398,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 36005,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 33450,
    "ua": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
  },
  {
    "val": 26172,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0"
  },
  {
    "val": 25735,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 23677,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
  },
  {
    "val": 20754,
    "ua": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 20101,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 17130,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 16970,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 13118,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 9337,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 7917,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
  },
  {
    "val": 7273,
    "ua": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 4258,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 3626,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 2831,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0"
  },
  {
    "val": 2524,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 1723,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3226.400 QQBrowser/9.6.11681.400"
  },
  {
    "val": 1563,
    "ua": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 1224,
    "ua": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
  },
  {
    "val": 1058,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0"
  },
  {
    "val": 999,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 701,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0"
  },
  {
    "val": 552,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 433,
    "ua": "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
  },
  {
    "val": 329,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.3397.16 Safari/537.36"
  },
  {
    "val": 329,
    "ua": "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 310,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
  },
  {
    "val": 256,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.3397.16 Safari/537.36"
  },
  {
    "val": 204,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 194,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 171,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.7.1 Chrome/49.0.2623.111 Safari/537.36"
  },
  {
    "val": 85,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.3228.1 Safari/537.36"
  },
  {
    "val": 81,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 57,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
  },
  {
    "val": 31,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  },
  {
    "val": 7,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"
  },
  {
    "val": 1,
    "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3368.400 QQBrowser/9.6.11974.400"
  }
]
```
上面的数据后是一天内采集到的错误，一共9百万多万条，而且里面每一项，都是同一个用户同一次访问的记录，val是报错数量。
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

期望能得到解答

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by king-king** [comment]
忘记放options了：
var option = {
    color: ['#2086A1', '#287445'],
    legend: {
        itemWidth: 10,
        itemHeight: 10,
        right: 20,
        top: 10,
        data: [{
            name: "今日",
            icon: "rect",
            textStyle: {
                color: '#2086A1',
                fontWeight: 'normal',
                fontSize: 12
            }
        }, {
            name: trendCompareDate,
            icon: "rect",
            textStyle: {
                color: '#287445',
                fontWeight: 'normal',
                fontSize: 12,
            }
        }]
    },
    tooltip: {
        show: false,
        trigger: 'axis',
        lineStyle: {
            color: "#9199c2"
        }
    },
    grid: {
        left: '3%',
        right: '5%',
        bottom: '0',
        containLabel: true
    },
    yAxis: {
        name: '下单金额',
        nameTextStyle: {
            color: '#9199c2'
        },
        splitLine: {
            show: false
        },
        type: 'value',
        axisLabel: {
            textStyle: {
                color: '#9199c2',
                fontSize: '12',
                fontFamily: 'ArialMT'
            },
            formatter: '{value}'
        },
        axisTick: {
            inside: true
        },
        axisLine: {
            onZero: true,
            lineStyle: {
                color: "#2F4B5F"
            }
        }
    },
    xAxis: {
        name: '时间',
        nameTextStyle: {
            color: '#9199c2'
        },
        type: 'category',
        nameGap: 5,
        axisLine: {
            onZero: true,
            lineStyle: {
                color: "#2F4B5F"
            }
        },
        axisLabel: {
            textStyle: {
                color: '#9199c2',
                fontSize: '12',
                fontFamily: 'ArialMT'
            },
            step: 3,
            formatter: function (value, index) {
                return Number(value) + ':00';
            }
        },
        axisTick: {
            inside: true
        },
        zlevel: 2,
        z: 2,
        boundaryGap: false,
        data: categories
    },
    series: [
        {
            name: '今日',
            type: 'line',
            smooth: true,
            symbolSize: 0,
            lineStyle: {
                normal: {
                    width: 2,
                    //color:"#00d8ff",
                    color: new echarts.graphic.LinearGradient(0, 0, 1, 0, [{
                        offset: 0, color: '#154C66' // 0% 处的颜色 1188c1
                    }, {
                        offset: 0.3, color: '#00CAF5' // 100% 处的颜色00d8ff
                    }, {
                        offset: 0.6, color: '#00CAF5' // 100% 处的颜色00d8ff
                    }, {
                        offset: 1, color: '#155F77' // 100% 处的颜色
                    }], false),
                    shadowColor: 'rgba(1,198,240,0.8)',
                    shadowBlur: 16,
                    shadowOffsetX: 0,
                    shadowOffsetY: 0
                }
            },
            areaStyle: {
                normal: {
                    color: new echarts.graphic.LinearGradient(0, 0, 1, 0, [{
                        offset: 0, color: 'rgba(8,168,210,0.1)' // 0% 处的颜色 1188c1
                    }, {
                        offset: 0.15, color: 'rgba(8,168,210,0.2)' // 100% 处的颜色00d8ff
                    }, {
                        offset: 0.3, color: 'rgba(8,168,210,0.3)' // 100% 处的颜色00d8ff
                    }, {
                        offset: 0.6, color: 'rgba(8,168,210,0.4)' // 100% 处的颜色00d8ff
                    }, {
                        offset: 0.8, color: 'rgba(8,168,210,0.4)' // 100% 处的颜色00d8ff
                    }, {
                        offset: 1, color: 'rgba(8,168,210,0.3)'
                    }], false),
                    shadowColor: "rgba(23,57,81,0.2)",
                    shadowBlur: 10,
                    shadowOffsetX: 5,
                    shadowOffsetY: 5
                }
            },
            markPoint: {
                symbol: 'circle',
                symbolSize: 4,
                data: [
                    {
                        name: '当前', coord: [markPointNum, today[markPointNum]],
                        clickable: false,
                        label: {
                            normal: {
                                show: false
                            }
                        },
                        value: 130,
                        itemStyle: {
                            normal: {
                                color: '#F9F9F9',
                                borderColor: "rgba(36,198,223,0.8)",
                                shadowColor: 'rgba(36,156,112,0.6)',
                                shadowBlur: 16,
                                shadowOffsetX: 0,
                                shadowOffsetY: 0
                            }
                        }
                    }
                ]
            },
            data: today
        },
        {
            name: trendCompareDate,
            type: 'line',
            smooth: true,
            symbolSize: 0,
            lineStyle: {
                normal: {
                    width: 2,
                    color: new echarts.graphic.LinearGradient(0, 0, 1, 0, [{
                        offset: 0, color: '#1F4644' // 0% 处的颜色 1188c1
                    }, {
                        offset: 0.3, color: '#27B170' // 100% 处的颜色00d8ff
                    }, {
                        offset: 0.6, color: '#27AB6D' // 100% 处的颜色00d8ff
                    }, {
                        offset: 1, color: 'rgba(36,116,88,0.4)' // 100% 处的颜色
                    }], false),
                    shadowColor: 'rgba(36,156,112,0.6)',
                    shadowBlur: 16,
                    shadowOffsetX: 5,
                    shadowOffsetY: 0
                }
            },
            areaStyle: {
                normal: {
                    color: new echarts.graphic.RadialGradient(0.45, 0.01, 1, [{
                        offset: 0, color: 'rgba(38,173,112,0.24)' // 0% 处的颜色 1188c1
                    },
                        {
                            offset: 0.3, color: 'rgba(38,173,112,0.22)' // 0% 处的颜色 1188c1
                        },
                        {
                            offset: 0.5, color: 'rgba(38,173,112,0.21)' // 0% 处的颜色 1188c1
                        },
                        {
                            offset: 0.6, color: 'rgba(38,173,112,0.20)' // 0% 处的颜色 1188c1
                        },
                        {
                            offset: 0.7, color: 'rgba(38,173,112,0.15)' // 0% 处的颜色 1188c1
                        },
                        {
                            offset: 0.8, color: 'rgba(38,173,112,0.12)' // 0% 处的颜色 1188c1
                        },
                        {
                            offset: 0.9, color: 'rgba(38,173,112,0.08)' // 0% 处的颜色 1188c1
                        },
                        {
                            offset: 1, color: 'rgba(38,173,112,0.02)' // 0% 处的颜色 1188c1
                        },
                    ], false),
                    shadowColor: 'rgba(36,156,112,0.5)',
                    shadowBlur: 10,
                    shadowOffsetX: 5,
                    shadowOffsetY: 5
                }
            },
            data: compareday
        }
    ]
};

**Comment by king-king** [comment]
非常神奇的是，这个错误量这么大，我自己却想尽办法也复现不出来

**Comment by pissang** [comment]
前段时间是有修复过一个动画的问题，你更新到最新版本试试

**Comment by king-king** [comment]
追查了一下是数组插值函数的问题，arrDim是2，但是数组并不是二维数组，没有严格的容错处理。后来我自己改了一下代码，添加了容错就好了。
