### ISSUE TITLE
K线图涨停时阴阳线错了。

### ISSUE THREAD

**Issue by arrowwind** [ecomfe/echarts#6624]
在k线图中。假设阳线为红色，阴线为绿色。对于开盘就涨停的情况，国内的炒股工具都是显示为阳线的红色。而echarts在这个情况下显示为绿色。

对于其他情况，echarts的阴阳线颜色都正确。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: chrome 60
+ OS Version [操作系统类型和版本]: win10

**Comment by llsr** [comment]
怎么把这个邮件退掉？？？？？？？？？？？？

在 2017-09-08 00:11:14，"arrowwind" <notifications@github.com> 写道：


在k线图中。假设阳线为红色，阴线为绿色。对于涨停的时候，国内的炒股工具都是显示为阳线的红色。而echarts在这个情况下显示为绿色。

对于其他情况，echarts的阴阳线颜色都正确。

Version & Environment [版本及环境]
ECharts version [ECharts 版本]: 3.7.1
Browser version [浏览器类型和版本]: chrome 60
OS Version [操作系统类型和版本]: win10

**Comment by Ovilia** [comment]
与 #6583 重复，这个问题已修复

**Comment by huogui** [comment]
![image](https://user-images.githubusercontent.com/41716931/210938895-116b6b36-9269-438b-927f-b07b3819ddd2.png)
还有问题呢，以下是另一个示例：
https://codesandbox.io/s/apache-echarts-demo-forked-047g0l?file=/index.js
