### ISSUE TITLE
如何加载图表就启用brush区域选择功能而不需要点击后启用

### ISSUE THREAD

**Issue by caidaorui** [ecomfe/echarts#6627]
### One-line summary [问题简述]
如何加载图表就启用brush区域选择功能而不需要点击后启用，貌似查询文档和API也没有发现提供这种功能呀？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.4.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows 10 14393

### Expected behaviour [期望结果]
跪求相关实现方法

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
参见 #4063

**Comment by caidaorui** [comment]
@100pah 谢谢解决了
