### ISSUE TITLE
echarts v3.6.0之后的版本，setOption之后图表不会自动刷新

### ISSUE THREAD

**Issue by yyddbull** [ecomfe/echarts#6634]
### One-line summary [问题简述]

echarts v3.6.0之后的版本，setOption之后图表不会自动刷新
重现步骤：官网示例，替换3.6.0之后的文件，点击【运行】按钮后，图表不会刷新
不清楚3.6.0之后是否把该功能取消了，或者是要另外调用方法刷新？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.6.0之后都可以
+ Browser version [浏览器类型和版本]:59.0.3071.115 64bit
+ OS Version [操作系统类型和版本]:win7 64bit

### Expected behaviour [期望结果]

反复执行setOption后，图表会有一次刷新显示的效果

### ECharts option [ECharts配置项]

```javascript
option = {
                                                        title : {
						        text: '某地区蒸发量和降水量',
						        subtext: '纯属虚构'
						    },
						    tooltip : {
						        trigger: 'axis'
						    },
						    legend: {
						        data:['蒸发量','降水量']
						    },
						    toolbox: {
						        show : true,
						        feature : {
						            dataView : {show: true, readOnly: false},
						            magicType : {show: true, type: ['line', 'bar']},
						            restore : {show: true},
						            saveAsImage : {show: true}
						        }
						    },
						    calculable : true,
						    xAxis : [
						        {
						            type : 'category',
						            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
						        }
						    ],
						    yAxis : [
						        {
						            type : 'value'
						        }
						    ],
						    series : [
						        {
						            name:'蒸发量',
						            type:'bar',
						            data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
						            markPoint : {
						                data : [
						                    {type : 'max', name: '最大值'},
						                    {type : 'min', name: '最小值'}
						                ]
						            },
						            markLine : {
						                data : [
						                    {type : 'average', name: '平均值'}
						                ]
						            }
						        },
						        {
						            name:'降水量',
						            type:'bar',
						            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
						            markPoint : {
						                data : [
						                    {name : '年最高', value : 182.2, xAxis: 7, yAxis: 183},
						                    {name : '年最低', value : 2.3, xAxis: 11, yAxis: 3}
						                ]
						            },
						            markLine : {
						                data : [
						                    {type : 'average', name : '平均值'}
						                ]
						            }
						        }
						    ]
}

```

**Comment by pissang** [comment]
没理解你的意思

**Comment by yyddbull** [comment]
我把js代码贴出来吧，如下：
$(document).ready(function() {		
    query();    
});
function refresh(){
	query();
}
function query(){
	var myChart = echarts.init(document.getElementById('main_1'));
	var option = {
                                           title : {
						        text: '某地区蒸发量和降水量',
						        subtext: '纯属虚构'
						    },
						    tooltip : {
						        trigger: 'axis'
						    },
						    legend: {
						        data:['蒸发量','降水量']
						    },
						    toolbox: {
						        show : true,
						        feature : {
						            dataView : {show: true, readOnly: false},
						            magicType : {show: true, type: ['line', 'bar']},
						            restore : {show: true},
						            saveAsImage : {show: true}
						        }
						    },
						    calculable : true,
						    xAxis : [
						        {
						            type : 'category',
						            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
						        }
						    ],
						    yAxis : [
						        {
						            type : 'value'
						        }
						    ],
						    series : [
						        {
						            name:'蒸发量',
						            type:'bar',
						            data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
						            markPoint : {
						                data : [
						                    {type : 'max', name: '最大值'},
						                    {type : 'min', name: '最小值'}
						                ]
						            },
						            markLine : {
						                data : [
						                    {type : 'average', name: '平均值'}
						                ]
						            }
						        },
						        {
						            name:'降水量',
						            type:'bar',
						            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
						            markPoint : {
						                data : [
						                    {name : '年最高', value : 182.2, xAxis: 7, yAxis: 183},
						                    {name : '年最低', value : 2.3, xAxis: 11, yAxis: 3}
						                ]
						            },
						            markLine : {
						                data : [
						                    {type : 'average', name : '平均值'}
						                ]
						            }
						        }
						    ]
                               }
         myChart.setOption(option);
       }
}

html页面上有个按钮，按钮的onclick="refresh()";
现象：点击按钮后，图表并没有出现“重新渲染“的效果，而是没有任何反应~
此问题出现在echarts v3.6.0之后的版本~~v3.6.0之前的都是有“重新渲染”效果的

**Comment by pissang** [comment]
refresh 不要重新 init，如果要重新 init 也请先 dispose
