### ISSUE TITLE
echarts.js和echarts-all.js的区别

### ISSUE THREAD

**Issue by sfmgmgmg** [ecomfe/echarts#6635]
### One-line summary [问题简述]
官方例子引用的是echarts.js，但是我在引用echarts.js不能初始化echarts.init(document.getElementById('main')),consloe里提示echarts is undefined，但是引用echarts-all.js一切正常，请问这两个有什么区别吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts 3
+ Browser version [浏览器类型和版本]:IE11
+ OS Version [操作系统类型和版本]:windows 7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

[lib.zip](https://github.com/ecomfe/echarts/files/1290323/lib.zip)

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html
