### ISSUE TITLE
我想在全国地图上显示市级区域

### ISSUE THREAD

**Issue by Ray21688504** [ecomfe/echarts#6640]
现在全国地图上只能显示省级的区域，如果我想在全国地图上画出某些省的某些市的区域应该怎么弄呢？

**Comment by chfw** [comment]
我也想知道。

**Comment by pissang** [comment]
找显示所有城市的 geojson 文件，http://gallery.echartsjs.com/editor.html?c=xrJ4Qz3Wt 比如这个

**Comment by jackywq** [comment]
@pissang 大佬，文件不存在
![image](https://user-images.githubusercontent.com/21954704/46254885-0075f080-c4c9-11e8-8612-65d08c0790b7.png)
