### ISSUE TITLE
图例显示数据值

### ISSUE THREAD

**Issue by 651778286** [ecomfe/echarts#6646]
### One-line summary [问题简述]
想在http://echarts.baidu.com/gallery/editor.html?c=dynamic-data这个例子的基础上，实现将最先的数据值显示先图例中

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echart3
+ Browser version [浏览器类型和版本]:Chrome、IE11、Edge
+ OS Version [操作系统类型和版本]:Win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
顺序是 legend.data 中的顺序，如果你要改变的话，就改变 legend 中的顺序

**Comment by 651778286** [comment]
@Ovilia 
可能是我没说清楚，我画张图来解释一下，我是想将最新生成的数据的值显示到legend 中，如下图所示
![image](https://user-images.githubusercontent.com/7576363/30311211-ce86c156-97c6-11e7-8cf4-a8e0567e94f1.png)

**Comment by limingyangit** [comment]
@651778286  显示出来了吗？ 我也需要这个效果。没想到怎么显示

**Comment by Ovilia** [comment]
那就把 legend data 和 series name 都设为这个值

**Comment by 651778286** [comment]
@Ovilia 按照你的建议修改后，图例在初次显示的时候，预期的效果出来了，但是后面继续插入新的数据之后，legend就无法显示了

**Comment by limingyangit** [comment]
重新插入数据后，再次setOption 一下就可以吧？

**Comment by 651778286** [comment]
@limingyangit 额，不可以哦，您可以试试

**Comment by Ovilia** [comment]
@651778286 插入新数据后， setOption 中需要同时修改 legend data 和 series name

**Comment by 651778286** [comment]
@Ovilia 正如你所说，我就是这么操作

**Comment by Ovilia** [comment]
@651778286 http://gallery.echartsjs.com/editor.html 复现一下，把地址贴上来

**Comment by 651778286** [comment]
@Ovilia 谢谢，已经解决了，我的Echarts版本太低了，换了最新版本就搞定了
@limingyangit 你可以参考这个例子
http://gallery.echartsjs.com/editor.html?c=xrJq42D89b&v=1
下载最新版本的库
![image](https://user-images.githubusercontent.com/7576363/30369908-8ccf7874-98a8-11e7-99dc-d2e87b6e7daf.png)

**Comment by limingyangit** [comment]
@651778286 好的。真棒。我还没做呢，正好参考了
