### ISSUE TITLE
中国地图 ,在省份没有数据的情况下，tooltip {c} 会显示为NaN

### ISSUE THREAD

**Issue by l745230** [ecomfe/echarts#6647]
### One-line summary [问题简述]
中国地图 ,在省份没有数据的情况下，tooltip {c} 会显示为NaN

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: QQ浏览器最新版
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
toolTip 值不显示 或者显示为0

### ECharts option [ECharts配置项]

```javascript
option = {
 tooltip: {
        trigger: 'item',
        formatter: '{b} <br/> 付款金额：{c}'
      },
      visualMap: {
        min: 0,
        max: 20,
        left: 'left',
        top: 'bottom',
        text: ['高', '低'],           // 文本，默认为数值文本
        calculable: true
      },
      series: [
        {
          name: '中国',
          type: 'map',
          mapType: 'china',
          selectedMode: 'single',
          label: {
            normal: {
              show: false
            },
            emphasis: {
              show: true
            }
          },
          data: [
              { name: '安徽', value: '15' },
              { name: '福建', value: '5' }
          ]
        }
      ]
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/15940920/30304857-34d4ddb4-97a2-11e7-9285-a335d130d3ca.png)

**Comment by Ovilia** [comment]
可以定义 formatter

**Comment by wwwmomo** [comment]
我也碰到了这样的问题，发现是geo.json数据里面的name名称和data里面name的名称不对应
