### ISSUE TITLE
使用echarts的时候，有没有一个当数据在图表上渲染完成后执行的方法

### ISSUE THREAD

**Issue by scorpionZK** [ecomfe/echarts#6654]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
关闭动画后 setOption 结束后就立刻结束了，有动画的话暂时还没有相关事件，可以试一下用 setTimeout

**Comment by scorpionZK** [comment]
好的，非常感谢
