### ISSUE TITLE
eChart3中雷达的提示框类型只支持item

### ISSUE THREAD

**Issue by summerruiye** [ecomfe/echarts#6656]
###eChart3中雷达的提示框类型只支持item

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:ECharts3
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:w7

### Expected behaviour [期望结果]
希望也支持axis

### ECharts option [ECharts配置项]

```javascript
option = {
 tooltip: {
                    trigger: 'axis'
}
}

```

**Comment by pissang** [comment]
雷达图暂时不支持 `trigger: 'axis'`

**Comment by vxhly** [comment]
????? 不支持，然后就直接把 issues 关了？？？？感觉是个不负责的行为，，这个需求还是很日常的把
