### ISSUE TITLE
如何隐藏坐标轴指示器和折线交叉的点

### ISSUE THREAD

**Issue by ruanyl** [ecomfe/echarts#6659]
### One-line summary [问题简述]
如何隐藏坐标轴指示器和折线交叉的点
![image](https://user-images.githubusercontent.com/486382/30347849-13b5e622-9816-11e7-8161-7e19937134f6.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v3.7.1

**Comment by pissang** [comment]
symbol: 'none'
