### ISSUE TITLE
极坐标系半径bug

### ISSUE THREAD

**Issue by LYlanfeng** [ecomfe/echarts#6664]
### One-line summary [问题简述]
极坐标系属性polar.radius。API（array）中描述如下：
极坐标系的半径，数组的第一项是内半径，第二项是外半径。
支持设置成百分比，相对于容器高宽中较小的一项的一半。
实际设置数组形式报错，只能为string

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
抱歉 API 描述有误，极坐标系暂时不支持内半径设置

**Comment by LYlanfeng** [comment]
嗯，那了解了~
