### ISSUE TITLE
echarts使用的中国地图是否有审图号？

### ISSUE THREAD

**Issue by yuhounahsui** [ecomfe/echarts#6666]
echarts使用的中国地图审图号是什么？希望提供下。客户要求注明审图号的~

**Comment by pissang** [comment]
审图号是需要你们自己去审批的

**Comment by yuhounahsui** [comment]
应该不是吧？echarts对外提供地图服务，肯定要审批通过吧？大家都是用的同一个地图，不能每个单位都拿同一个图去审核一次啊。

**Comment by pissang** [comment]
我们不直接提供地图服务，GIS 的可视化我们提供的是绘制 geojson 的组件和百度地图组件，百度地图组件已经显示审图好了，关于 geojson 的组件大家在自己的产品中绘制出来的样貌都不一样，理论上来说如果地图样貌发生改变就是需要去审批的

**Comment by yuhounahsui** [comment]
我们地图的样貌并没有发生改变，就是基于地图做了一些动态效果。我们地图样貌跟echarts官网上提供的地图完全一样，这种情况也需要自己审批？

**Comment by pissang** [comment]
@yuhounahsui 是的

**Comment by zhangwenqier** [comment]
您好，我有两个问题需要请教一下：
1.使用了e-charts地图并且用作商用，还需要购买百度地图的权限吗？
2.如果使用了很多e-charts的动态效果，需要每个图都申请审图号，还是只需要申请一个就可以了呢？
