### ISSUE TITLE
地图组件渲染完成之后是否可以调用一次restore时间

### ISSUE THREAD

**Issue by mrmengjun** [ecomfe/echarts#6671]
### One-line summary [问题简述]
在react中使用echarts，全国地图平移或者缩放之后，进入二级页面时需要调用restore。目前没有找到哦啊相关的方法。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts版本3.6.2
+ Browser version [浏览器类型和版本]:react
+ OS Version [操作系统类型和版本]:mac os

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
你说的 `restore` 是哪里的方法？

**Comment by mrmengjun** [comment]
@Ovilia 是这样的。我在项目首页引入全国地图，设定好大小，并且可以缩放和平移。我对全国地图做一定的缩放之后，点击某一个省，setOption为该省份的地图，由于全国地图已经缩放了，所以该省的地图会出现在视图之外，需要点击一次工具栏中的restore按钮，才可以正常显示。所以我的问题是想要在setOption之后能够代码调用一次restore方法，实现视图缩放的重置

**Comment by Ovilia** [comment]
目前应该是没有 setOption 渲染后的回调方法的，`setTimeout` 设个固定值可以满足需求吗？

**Comment by mrmengjun** [comment]
@可以，我主要是想调用restore的方法接口，请问可以提供吗

**Comment by mrmengjun** [comment]
@Ovilia 可以，只要可以调用到restore方法，就可以，请问可以提供这个方法的接口吗

**Comment by Ovilia** [comment]
有的 http://echarts.baidu.com/api.html#action.toolbox.restore

**Comment by Ovilia** [comment]
教程：http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA

**Comment by mrmengjun** [comment]
@Ovilia 好的，谢谢你了。这个问题我关闭了哈，再次感谢你~
