### ISSUE TITLE
barWidth 为百分比的时候应该能被 barMaxWidth 约束

### ISSUE THREAD

**Issue by pissang** [ecomfe/echarts#6673]
柱状图现在设置了 barWidth 是不受 barMaxWidth 影响的，但是如果 barWidth 为百分比的话，我们希望 barWidth 百分比计算出来的宽度能够不超出 barMaxWidth

**Comment by Ovilia** [comment]
试了一下，`barWidth` 已经会被 `barMaxWidth` 限制了。http://gallery.echartsjs.com/editor.html?c=xHJLYjUijZ&v=1

**Comment by cxyxc** [comment]
多个 series 时仍不管用。
![image](https://user-images.githubusercontent.com/20027281/34762790-fb6974b4-f623-11e7-9de8-233db7365ca8.png)

**Comment by Ovilia** [comment]
这不是 bug 吧？因为的确没有超过总宽度的 20% @cxyxc
