### ISSUE TITLE
请问echarts是怎样保持高性能的

### ISSUE THREAD

**Issue by yuanzhaokang** [ecomfe/echarts#6681]
### One-line summary [问题简述]
我仿照 http://echarts.baidu.com/demo.html#geo-lines echarts官网的迁徙图用zrender写了一个类似的，但是发现echarts的迁徙图CPU占用只有7%到10%。而我自己写的却把一个CPU占满了，达到25%。后来发现是因为画飞机尾焰的时候用了一大堆的circle代替，然后动画时候更新circle的位置和透明度，这是造成CPU占用的原因。但是我看echarts的也是用大量的白色的circle做的尾焰，却没有我的问题，去读echarts的源码，没找着怎么处理这个的。请讲解一下，谢谢。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
chrome59
+ OS Version [操作系统类型和版本]:
windows7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/zrender/blob/master/src/Layer.js#L182 可以参考这段代码

**Comment by yuanzhaokang** [comment]
谢啦

**Comment by yuanzhaokang** [comment]
@pissang  
#### 看这个示例上面的飞机尾气好像是很多小圆点，但是CPU占用却这么低。这个是怎么做到的呢？我单独用zrender画了800个Circle做动画，CPU占用就25%了，也就是一个CPU核已经满了，我也做了分层渲染，就是设置了zlevel，但是这个优化有限，现在的瓶颈就是生成的Circle太多了，不知道怎么优化，所以再来请教一下，下面是代码，谢谢。
  

## [这个是官网示例迁徙图的截图](http://gallery.echartsjs.com/editor.html?c=geo-lines)  
![20170918142948](https://user-images.githubusercontent.com/16620101/30531034-23715d64-9c7e-11e7-8947-b2e886dabaf2.png)  
## 下面是chrome的任务管理器显示的CPU占用.  
![20170918143000](https://user-images.githubusercontent.com/16620101/30531039-2e91a1a4-9c7e-11e7-881b-08e608e62b83.png)  
  
```javascript
 let g = [];

      for(let i =0;i<800;i++) {
         let c = new Circle({
            shape: {
               cx: Math.random() * 500,
               cy: Math.random() * 500,
               r: 30,
               zlevel: 2
            },
            style: {
               fill: "red"
            }
         });

         g.push(c);
      }

      let first = g[0];

      first.__t = 0;
      first.animate('', true)
         .when(2000, {
            __t: 1
         })
         .during((target, percent) => {
            for(let i = 0; i < 800; i++) {
               let item = g[i];
               item.setShape('r', 20 * percent);
            }
         })
         .start();
```

**Comment by Ovilia** [comment]
@yuanzhaokang https://github.com/ecomfe/zrender/blob/master/src/Layer.js#L182 这里的代码你可以读一下。
本质上并不是创建更多的 zrender.Circle，而是将上一帧的画面与当前帧进行 blending，这样那些“很多小圆点”就不用在每帧都重新计算位置再绘制，而是都在 Canvas 上。

**Comment by yuanzhaokang** [comment]
@Ovilia 已经画出来了，十分感谢.

**Comment by li2215890610** [comment]
你好，我想问一下，为什么我用百度地图结合echarts 展示在页面上，在谷歌上面页面很流畅，但是在IE上面会卡死，我看IE在任务管理器中的内存，超过了40%,有时候还要多，请问您遇到过这种问题吗？？求解
