### ISSUE TITLE
官方实例中的数据在哪里下载啊

### ISSUE THREAD

**Issue by juslly** [ecomfe/echarts#6683]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
你想要什么数据呀？或者想要哪种实例的数据

**Comment by juslly** [comment]
就比如说官方实例“”各国人口寿命与GDP关系演变“”中的那个life-expectancy.json的json数据，官方实例中用到的数据都在那个地方可以下载啊？不能是自己做数据吧？哪格式也不知道啊，刚学echarts @DukeGJ

**Comment by DukeGJ** [comment]
那个图里面的数据都是自己生成的，你可以看它的代码。官方给的实例里面数据都是虚构的

**Comment by DismalSnail** [comment]
> 就比如说官方实例“”各国人口寿命与GDP关系演变“”中的那个life-expectancy.json的json数据，官方实例中用到的数据都在那个地方可以下载啊？不能是自己做数据吧？哪格式也不知道啊，刚学echarts @DukeGJ

兄弟，你知道数据在哪下了吗？
