### ISSUE TITLE
西藏地图的山南市去哪里了

### ISSUE THREAD

**Issue by tmzhappy** [ecomfe/echarts#6686]
### One-line summary [问题简述]

西藏地图的山南市去哪里了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

西藏地图的山南市去哪里了

### Expected behaviour [期望结果]

西藏地图的山南市不见了，要画出来额

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
https://chfw.github.io/echarts-china-cities-js/dist/xi1_cang2/shan1_nan2.min.js

**Comment by tmzhappy** [comment]
http://echarts.baidu.com/download-map.html ，这个里面下载的xizang.json，山南地图是没有的

**Comment by chfw** [comment]
![image](https://user-images.githubusercontent.com/4280312/30480249-bea3913c-9a10-11e7-904f-ebd94c847a44.png)

**Comment by tmzhappy** [comment]
![image](https://user-images.githubusercontent.com/8792422/30527056-dac4c83e-9c56-11e7-8f17-efe0b00509ea.png)
 这里的西藏下载json，山南区是只有名称没有区域的。

**Comment by tmzhappy** [comment]
![image](https://user-images.githubusercontent.com/8792422/30527078-1427afec-9c57-11e7-9921-de8b885d0231.png)
 这个地方 页面已经加载完成，但是下拉框里面只有省级有数据，市、县是没有数据的，右边的preview也是空白

**Comment by chfw** [comment]
工具在你手上了，耐心用，多试试。除这之外，没有别的更好建议了。

**Comment by tmzhappy** [comment]
我说的是从刚才那个截图页面，直接下载西藏的json，是没有山南的区域的，不是说工具的问题。要解决的是为什么json是没有山南的，不是在这个跟我说工具在我手上。

**Comment by chfw** [comment]
明白了。查了一下，我下载的西藏地图也没有。如果下载局部地区，山南区会出现。
