### ISSUE TITLE
Echarts3 markPoint，markLine，markArea可以增加一个zlevel的属性吗？

### ISSUE THREAD

**Issue by arrowwind** [ecomfe/echarts#6691]
我的图中，markPoint比较多，当一个数据，显示2到3个markPoint的时候，会造成markPoint的遮挡。而目前这些markPoint的前后顺序我是不能设置的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以在全局的 `markPoint` 等设置 `zlevel`。

**Comment by marcong95** [comment]
@Ovilia hi，可以简单的说明一下这个全局的`zlevel`怎么设置吗？需要做一个在x在某个范围内的半透明遮罩，想让markArea在覆盖图表的上方，各种地方都没有找到，查看源码的时候看到markArea有一个默认的z和zlevel的，想着应该是可以通过某种方式修改。先谢了

**Comment by Ovilia** [comment]
@marcong95 http://gallery.echartsjs.com/editor.html?c=xSJYfuJHWG 给你写了个例子

**Comment by marcong95** [comment]
@Ovilia 我刚刚也摸索出来了，正想过来修改一下评论，无论如何还是谢谢了

**Comment by Ovilia** [comment]
同 #6690

**Comment by kkxlkkxllb** [comment]
markArea 目前还是不支持单独配置 z 吗？默认的zIndex 是 小于 Series 的，我希望有的markArea当遮罩层盖在 Series 上，全局的不适合

**Comment by yellowdog-forever** [comment]
2020年了为什么还不支持单个markpoint的zLeve设置

**Comment by 7neves** [comment]
markLine好像还是不行啊，想单独进行canvas单独分层，也分不了

**Comment by kchjxxgh** [comment]
2021年了为什么还不支持单个markpoint, markline的zLeve设置

**Comment by looserLiu** [comment]
都2021年下半年了  为啥还不支持markpoint的zlevel

**Comment by looserLiu** [comment]
> @marcong95 http://gallery.echartsjs.com/editor.html?c=xSJYfuJHWG 给你写了个例子。
> 目前还不支持每个 markPoint 的 z 值设置，之后可以改进一下。

这个链接失效了   我想知道咋写的  麻烦给看一下呢

**Comment by plainheart** [comment]
@looserLiu https://www.makeapie.com/editor.html?c=xSJYfuJHWG

**Comment by lhywell** [comment]
```
option = {
    xAxis: {
        data: ['a', 'b', 'c', 'd']
    },
    yAxis: {
        
    },
    series: [{
        type: 'line',
        data:[1, 10, 4, 3],
        markPoint: {
            data: [{
                type: 'min',
                itemStyle: {
                    normal: {
                        color: 'green'
                    }
                }
            }]
        }
    },{
        type: 'line',
        data:[1.1, 10, 4, 3],
        markPoint: {
            data: [{
                type: 'min',
                itemStyle: {
                    normal: {
                        color: 'green'
                    }
                }
            }]
        }
    }]
};
```

数字1，1.1同时存在，4.9.0版本可以，5.0以上版本不行

**Comment by holdbiao** [comment]
现在不支持单独设置层级，在配置得最顶层添加一个层级可以解决这个问题
 markLine: [
    {
      z: xxx
    }
  ]

**Comment by Korbato** [comment]
2023年了 现在支持了吗

**Comment by huogui** [comment]
2023.09.25....... 真的很需要这个特性 什么时候能支持呢？

**Comment by huogui** [comment]
> @Ovilia 我刚刚也摸索出来了，正想过来修改一下评论，无论如何还是谢谢了

怎么实现的呢，我也遇到了，很头疼

**Comment by huogui** [comment]
真的什么时候能修复下啊，这个苦恼我很久了

**Comment by huogui** [comment]
> 2020年了为什么还不支持单个markpoint的zLeve设置

2023/9/26 依旧不支持。。。。

**Comment by F5F5** [comment]
2023/11/20 依旧不支持。。。。

**Comment by yumeng745570310** [comment]
2024/04/20 依旧不知此。。。。
