### ISSUE TITLE
蜡烛图中，涨停一字板的 和 跌停一字板的时候，都是绿色的？该怎么解决

### ISSUE THREAD

**Issue by luckFine** [ecomfe/echarts#6692]
蜡烛图中，涨停一字板的 和 跌停一字板的时候，都是绿色的

**Comment by Ovilia** [comment]
#6583 已修复，下一个版本会上线，急用的话，参考 https://github.com/ecomfe/echarts/commit/85ccf2ddd4e0234fe25c7aba9a60ddef02acd1a7 修改源码。
