### ISSUE TITLE
日历dayLabel不支持formatter参数

### ISSUE THREAD

**Issue by hswmartin** [ecomfe/echarts#6701]
### One-line summary [问题简述]
日历图的dayLabel不支持formatter参数，怎么使用富文本？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.7
+ Browser version [浏览器类型和版本]:
chrome
+ OS Version [操作系统类型和版本]:
window 10 64bit

### Expected behaviour [期望结果]
希望dayLabel能够支持formatter参数，比如我想让周末显示为红色！！！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by The-only** [comment]
1、【 dayLabel 不支持 formatter 参数】：目前 dayLabel 提供了 [nameMap](http://echarts.baidu.com/option.html#calendar.dayLabel.nameMap) 配置项支持自定义不同的文案描述，暂时没有支持 formatter ，后续可以考虑支持~

2、【周末显示为红色】： dayLabel 是 “[日历坐标系](http://echarts.baidu.com/option.html#calendar)” 的一个配置项，在 ECharts 中，日历图
是通过在 “日历坐标系” 上绘制 “[热力图](http://echarts.baidu.com/option.html#series-heatmap)” 呈现出来的，可以采用的一种实现方案是：
    
增加一个额外的“日历坐标系”，设置 [dayLabel](http://echarts.baidu.com/option.html#calendar.dayLabel) 的 [color](http://echarts.baidu.com/option.html#calendar.dayLabel.color) 、 [nameMap](http://echarts.baidu.com/option.html#calendar.dayLabel.nameMap) 
    
    {
        ...
        ... 
        
        calendar: [
            ...
            ... 
            {   
                ...
                ...
                dayLabel: {
                    nameMap: ['', 'M', 'T', 'W', 'T', 'F', '']
                }
            },
            {
                ...
                ...
                dayLabel: {
                    // 设置为红色    
                    color: '#f00',
                    // 只展现周末文字
                    nameMap: ['S', '', '', '', '','','S']
                },
                // 去掉月份文字
                monthLabel: {
                    show: false
                },
                // 去掉年份文字
                yearLabel: {
                    show: false
                }
            }
        ]

        ...
        ...

        series: [
            ...
            ...
            {
                type: 'heatmap',
                coordinateSystem: 'calendar',
                data: getVirtulData(2016)
            },
            {
                type: 'heatmap',
                coordinateSystem: 'calendar',
                // 数据置空
                data: []
            }
        ]
    }

[具体示例地址](http://gallery.echartsjs.com/editor.html?c=xHk0E1Ekjb)
