### ISSUE TITLE
大数据的时候  出现抽样画图  怎么处理

### ISSUE THREAD

**Issue by weile-gzseeing** [ecomfe/echarts#6703]
### One-line summary [问题简述]
用echarts画50W数据  但出现相邻两个数据相差很大的时候就没有画出来
就例如范围都是90-100的数据里面出现0.01，就没有画出0.01这个点 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-line.sampling 可以设置过滤策略，默认应该是不过滤的。
