### ISSUE TITLE
echarts3之后有什么属性替代noDataLoadingOption？

### ISSUE THREAD

**Issue by 15626262358** [ecomfe/echarts#6704]
echarts3之后有什么属性替代noDataLoadingOption，或者想没数据时显示暂无数据什么属性能做到
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by weile-gzseeing** [comment]
showLoading

**Comment by Ovilia** [comment]
http://echarts.baidu.com/gallery/editor.html?c=doc-example/tutorial-loading
