### ISSUE TITLE
ECharts是否考虑过实现风玫瑰呢？

### ISSUE THREAD

**Issue by liuxupiaoshi** [ecomfe/echarts#6705]
### One-line summary [问题简述]

ECharts 是个非常优秀的库,几乎能找见所有能想到的图表类型，我们很多项目中都用到了,现在项目中有一个风玫瑰图的需求，效果如[ https://www.highcharts.com/demo](https://www.hcharts.cn/demo/highcharts/polar-wind-rose)，但ECharts中并没有该类型的图表，团队是否考虑加入呢，期待回复，感谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
已经支持了 http://echarts.baidu.com/demo.html#bar-polar-stack-radial
