### ISSUE TITLE
Correlation of graphs

### ISSUE THREAD

**Issue by Mahan-F** [ecomfe/echarts#6709]
### One-line summary [问题简述]
Hello, I have looked through echarts documentations for a while and I believe that this feature does not exist.
I would like to know if its possible for echarts to have the feature i am demonstrating in this GIF.

![](https://i.scrny.me/fgHD.gif)

So basically if I have 5 graphs in one page and I hover one, there is a line on every other graph at the same time (value of x axis).

This is my project done with echarts: 
![](https://i.scrny.me/3KVu.gif)
You can see that having a line on every graph can be very helpful.

The first example is from www.datadoghq.com

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: Chrome 60
+ OS Version [操作系统类型和版本]: Windows 10

**Comment by Ovilia** [comment]
Hi, thanks for using ECharts.

This feature is supported, and is called `connect` in ECharts. See https://github.com/ecomfe/echarts/blob/master/test/connect.html or search `connect` in https://github.com/ecomfe/echarts/tree/master/test for more examples.

**Comment by Mahan-F** [comment]
Hi, Thanks for the help! I did not know about this feature.
