### ISSUE TITLE
echarts怎么实现数据的钻取

### ISSUE THREAD

**Issue by pijiang** [ecomfe/echarts#6711]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
通过点击事件修改图表 http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA

**Comment by pijiang** [comment]
谢谢你
