### ISSUE TITLE
设置多个Tooltip会导致卡死

### ISSUE THREAD

**Issue by z-hao** [ecomfe/echarts#6722]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: Chrome 60
+ OS Version [操作系统类型和版本]: Mac OS

### Expected behaviour [期望结果]

显示多个Tooltip

### ECharts option [ECharts配置项]

```javascript
tooltip: [{
      trigger: 'axis',
      formatter: function(params) {

        if (params.length > 2) {

          var kline;
          var vol;
          var increase;
          var amplitude;
          var item;

          for (var i = 0; i < params.length; i++) {

            item = params[i];

            switch (item.seriesIndex) {

              case 0:

                kline = item.name + ' &nbsp; 开：' + item.value[1].toFixed(2) + ' &nbsp; 收：' + item.value[2].toFixed(2) + ' &nbsp; 低：' + item.value[3].toFixed(2) + ' &nbsp; 高：' + item.value[4].toFixed(2);

                increase = '涨幅：' + ((item.value[2] - item.value[1]) / item.value[1] * 100).toFixed(2) + '%';

                amplitude = '振幅：' + ((item.value[4] - item.value[3]) / item.value[1] * 100).toFixed(2) + '%';

                break;

              case 5:

                vol = '量：' + item.value.toFixed(2);

            }

          }

          return kline + ' &nbsp; ' + increase + ' &nbsp; ' + amplitude + ' &nbsp; ' + vol;

        }

      },
      textStyle: {
        color: '#bababa',
        fontSize: 12
      },
      backgroundColor: 'transparent',
      padding: [3, 12],
      position: [0, 0],
      axisPointer: {
        animation: false,
        type: 'cross',
        crossStyle: {
          type: 'solid'
        }
      }
    }, {
      formatter: function(params) {

        console.log(params);

      }
    }],
    axisPointer: {
      link: {
        xAxisIndex: [0, 3]
      },
      label: {
        color: '#bababa',
        backgroundColor: '#000000',
        borderColor: '#bababa',
        borderWidth: 1,
        padding: [3, 6]
      },
      zlevel: 2
    }

```

**Comment by Ovilia** [comment]
显示多个 tooltip 是希望怎么样的效果？多个之间的位置怎么布局？

**Comment by z-hao** [comment]
比如我有一个K线图，一个Volume图，K线图的Tooltip只显示K线图的信息，Volume图的tooltip只显示自己的信息。然后分别有自己的position。具体可看[](https://www.huobi.com/market/cny_btc)这个例子

**Comment by Ovilia** [comment]
看这个例子 https://github.com/ecomfe/echarts/blob/master/test/connect.html

**Comment by z-hao** [comment]
感谢，已经解决。 @Ovilia

**Comment by biaowork** [comment]
@z-hao 请问你是按照 test/connect.html这个例子解决的么？”我有一个K线图，一个Volume图，K线图的Tooltip只显示K线图的信息，Volume图的tooltip只显示自己的信息。然后分别有自己的position。“ 目前我也是有这样的需求，按上面的例子，那就是需要定义3个id，分别setOption()，再connect ？ 这样。。。还能能使用 tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            }
        },
        axisPointer: {
            link: {xAxisIndex: 'all'},
            label: {
                backgroundColor: '#777'
            }
        }, 这个配置？

**Comment by z-hao** [comment]
是的，按照[https://github.com/ecomfe/echarts/blob/master/test/connect.html](https://github.com/ecomfe/echarts/blob/master/test/connect.html)这个例子。分别setOption之后再connect，分别设置好各自的tooltip属性。connect之后就能实现这些联动了
