### ISSUE TITLE
关闭饼图hover时半径增大的效果（hoverAnimation:false），但是highlight的时候开启动画

### ISSUE THREAD

**Issue by somnustd** [ecomfe/echarts#6729]
设置
 series: [
                {
                    hoverAnimation:false,
}]
点击饼图的时候不出现放大效果
但是点击下面的选项希望有放大效果，请问如何实现？
我是这样写的
myChartPie.dispatchAction({
            type: 'highlight',
            seriesIndex:0,
            dataIndex: 0
        });

另： highlight 事件能否控制饼图的颜色，此项目不需要有颜色变化

![3z zdh4qnts7xune j6y2th](https://user-images.githubusercontent.com/16396565/30647844-2388db56-9e4f-11e7-8c5e-6a5627c42163.png)

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-pie.itemStyle.emphasis.color 将这里的颜色设为和 normal 相同的

**Comment by Ovilia** [comment]
放大的问题 #3857

**Comment by JH46666** [comment]
hoverOffset:xx,
