### ISSUE TITLE
markLine 怎样改变两端图形的样式

### ISSUE THREAD

**Issue by AntoniaQiao** [ecomfe/echarts#6732]
markLine:  {
              data: [
                {
                  name: '低',
                  yAxis: this.seriesData[i][0]['normalLow'],
                  label: {
                    normal: {
                      position: 'end',
                      formatter: '临界低值'
                    }
                  },
                },
                {
                  name: '高',
                  yAxis: this.seriesData[i][0]['normalHigh'],
                  label: {
                    normal: {
                      position: 'end',
                      formatter: '临界高值'
                    }
                  },
                }]
            } ,

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-line.markLine.symbol
