### ISSUE TITLE
请问图表能不能嵌套？意思是在一个主图表中包含另一个图表，两个图表有各自独立的标题、图例等属性。

### ISSUE THREAD

**Issue by zhangjiaqing** [ecomfe/echarts#6733]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
通过调节DOM的属性不能满足需求吗

**Comment by zhangjiaqing** [comment]
@DukeGJ 怎么调节？绝对定位？

**Comment by DukeGJ** [comment]
可以参考这个:http://echarts.baidu.com/echarts2/doc/example/mix2.html
另外再提供个思路:series中包含很多个图,你可以调节这个图的属性来设置图表嵌套

**Comment by zhangjiaqing** [comment]
我知道series中可以包含多个图，但这多个图是共享标题tital、图例legen和背景色background的。我现在有个需求是两个图有各自独立的图例、标题和背景色，其中一个图是以副图的形式放在主图里的。这种需求能实现么？ @DukeGJ

**Comment by DukeGJ** [comment]
我明白你的意思了,你可以通过操作div来实现,一个div用来放主图,在主图的div里嵌套一个div,放副图，通过调整副图的div属性来安排副图的最终位置 @zhangjiaqing

**Comment by zhangjiaqing** [comment]
谢谢啦！！ @DukeGJ
