### ISSUE TITLE
折线图，点击图例应该只显示点击的图例这条线比较符号大众吧？而不是隐藏这条数据

### ISSUE THREAD

**Issue by iHadDream** [ecomfe/echarts#6736]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
我感觉没什么反人类的影响啊

**Comment by Ovilia** [comment]
要实现这样的需求的话，可以自己监听并触发事件 http://echarts.baidu.com/api.html#action.legend

**Comment by tmyeahsing** [comment]
那如果有三条线，你想显示其中两条，怎么操作？嘎。。。
