### ISSUE TITLE
自动周期更新数据时setOption，已经触发显示的tooltip会消失

### ISSUE THREAD

**Issue by z-hao** [ecomfe/echarts#6740]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ Browser version [浏览器类型和版本]: Chrome 60
+ OS Version [操作系统类型和版本]: OSX

### Expected behaviour [期望结果]
希望短周期自动更新数据时不会把已经显示的tooltip重置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
[setOption](http://echarts.baidu.com/api.html#echartsInstance.setOption) `lazyUpdate` 在设置完 option 后是否不立即更新图表

**Comment by z-hao** [comment]
666，感谢！ @Ovilia

**Comment by qugemingziburongyia** [comment]
没有用
