### ISSUE TITLE
dataZoom minValueSpan 无效

### ISSUE THREAD

**Issue by liwenda122** [ecomfe/echarts#6747]
### One-line summary [问题简述]

xAxis.type =time 时 dataZoom组件的minValueSpan 无效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.0
+ Browser version [浏览器类型和版本]:chrome 61.0.3163.100
+ OS Version [操作系统类型和版本]: windows 7 64

### Expected behaviour [期望结果]

minValueSpan设置后 可以限制最大缩放等级（现在设置后依然可以使用滚轮无限扩大)

### ECharts option [ECharts配置项]
参见 http://gallery.echartsjs.com/editor.html?c=xryos9eIi-&v=1

```javascript
option = {

}

```

**Comment by 100pah** [comment]
在 `axis.type` 为 `'time'` 是，minValueSpan 的单位是毫秒（ms）。
所以你的例子中，`minValueSpan: 1000` 指的是 1 秒。

**Comment by liwenda122** [comment]
难道我不知道是毫秒吗， 问题是设置了1000之后，还是可以滚轮无限放大

**Comment by liwenda122** [comment]
看清楚描述，不懂就别瞎关闭

**Comment by pissang** [comment]
@liwenda122 既然是1秒的话你例子有啥问题么？
