### ISSUE TITLE
echarts能支持小程序吗？

### ISSUE THREAD

**Issue by gdmec07140537** [ecomfe/echarts#6764]
### One-line summary [问题简述]
echarts可以在小程序上使用吗

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
可以

**Comment by gdmec07140537** [comment]
echarts不是要通过dom操作来生成图标吗，而小程序不支持dom操作

**Comment by gdmec07140537** [comment]
@DukeGJ echarts不是要通过dom操作来生成图标吗，而小程序不支持dom操作

**Comment by skyFi** [comment]
微信小程序的canvas 组件是由客户端创建的原生组件。echarts是基于zrender的，而zrender是基于browser的，与其期待echarts支持小程序，不如期待小程序的veb-view组件不全屏化，直接嵌入。

**Comment by pissang** [comment]
我们正在开发 ECharts 对小程序的适配，新版本会发布

**Comment by Ovilia** [comment]
同 #7514
