### ISSUE TITLE
词云data为空的渲染问题

### ISSUE THREAD

**Issue by zhangya5847** [ecomfe/echarts#6769]
### One-line summary [问题简述]
    背景：因为词云没有筛选的功能，所以自己更改data后，重新setOption的方法来重新渲染图标，达到筛选的功能。
    问题：当把所有类都取消掉之后，即当前的data为空数组渲染的时候，页面还是保持上一次的渲染结果，没有清空掉。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.6.2
+ Browser version [浏览器类型和版本]:latest
+ OS Version [操作系统类型和版本]:mac

### Expected behaviour [期望结果]

 期望能够清空掉。

### ECharts option [ECharts配置项]

```javascript
option = {
          tooltip: {
            show: true,
          },
          series: [{
            type: 'wordCloud',
            gridSize: 22,
            sizeRange: [14, 50],
            rotationRange: [0, 0],
            left: null,
            top: null,
            width: '100%',
            height: '100%',
            right: null,
            bottom: null,
            drawOutOfBound: true,
            textStyle: {
              normal: {
                color: e => {
                  return CATEGORY_COLORS[e.data.category]
                },
                fontWeight: 900,
                fontFamily: 'Arial, Verdana, sans-serif',
              },
            },
            data: this.tempData,
          }],
        }
```
tempData的格式是这样的：
[{
  "category": "a",
  "name":"apple",
  "value":300
}}

### Other comments [其他信息]

1、此时只有product和event两种类别，其中event的数据为空，所以当前只显示了product的数据
![image](https://user-images.githubusercontent.com/15855773/30951794-6d8c6650-a3ea-11e7-8e39-51796500a55e.png)
2、当把product这个类别也取消之后，即只显示event的数据，而当前数据量为空数组，那么，应该什么都没有，但是，真实情况是还是保留着上一次的，而且Tooltip显示的内容也不对
![image](https://user-images.githubusercontent.com/15855773/30951913-0a34c2a4-a3eb-11e7-9812-62c082ba4891.png)

**Comment by Ovilia** [comment]
请到词云插件项目下提问

**Comment by zhangya5847** [comment]
我想请问一下，词云的插件是否还在维护，因为直接不兼容echarts 3.7.0以上版本，快两个月了也没有修复。谢谢！
