### ISSUE TITLE
K线图蜡烛线样式修改

### ISSUE THREAD

**Issue by liihuu** [ecomfe/echarts#6771]
### One-line summary [问题简述]
能不能把蜡烛图的样式改成如下这个样子？
![image](https://user-images.githubusercontent.com/10508024/30954783-182d762e-a3f7-11e7-810b-28af8d3810f3.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
参考 http://www.echartsjs.com/gallery/editor.html?c=custom-ohlc
