### ISSUE TITLE
关系图中，当鼠标悬停在关系边上时，能否让边两端的节点突出显示

### ISSUE THREAD

**Issue by Lily-Jian** [ecomfe/echarts#6772]
### One-line summary [问题简述]
在关系图中，当鼠标悬停在关系边上时，能否让边两端的节点突出显示
http://gallery.echartsjs.com/editor.html?c=xHk28KqP5-&comment=0

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]

当鼠标悬停在关系边上时，能突出显示边两端的节点

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by VitoWong** [comment]
Emphasis the adjacent nodes while hovering on the edge is a great feature, but show the edge label make it a really mess now, how could I only close the annoying edgeLabel?  If can't, could we add a switch to this? Just NOT show the edge labels but keep the nodes, thanks!
Before:
![image](https://user-images.githubusercontent.com/29249733/35201888-dcfb3a32-ff59-11e7-98d7-6a4cfeb5e8e4.png)
After:(notice the black text is the mess edge labels)
![image](https://user-images.githubusercontent.com/29249733/35202021-d3e26db6-ff5a-11e7-8621-2871f71c1a05.png)
