### ISSUE TITLE
文档页超卡

### ISSUE THREAD

**Issue by jingsam** [ecomfe/echarts#6777]
### One-line summary [问题简述]

打开Echarts文档中的“配置项手册”超级卡

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

Chrome 版本 63.0.3223.8（正式版本）dev （64 位）

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
后面有精力会优化文档页的加载

**Comment by zoffyzhang** [comment]
我的chrome也遇到这个问题，但是在firefox下完全不卡，经过排查主要是以下几个插件造成的

- uBlock Ultimate Adblocker
- 为什么你们就是不能加个空格呢？
- Smart TOC
