### ISSUE TITLE
Bullet chart

### ISSUE THREAD

**Issue by RamprashanthA-Hexaware** [ecomfe/echarts#6795]
is there any way to achieve bullet chart in echarts or Bullet chart will be available in future release?

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html?c=xH1xO1oCzl

**Comment by mcse3010** [comment]
@Ovilia is there an updated example for this -- this link no longer works?

**Comment by plainheart** [comment]
@mcse3010 Please refer to this [example](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkwATxDUGbABaMAJsADu9HrAC-xHd3TZqNaCvHaIAYxgNSwAK5mAStStgt6A8WYBBVmwWkiqMYIyEANr0vlyw9ABCsfQAwkkAIkkAovQAuvqGsNL-7EFSsvJxAG6M2A7UXNp8bAAyjABG1NilkgBmwKQAtqGidHFI1bXUOgCkniR6XgVstBDUgbAR2hKSsNCMAxUpwAMgxpAwsM6h9QWSMnIMbYykDTuwT6QA4owEcQC0AGYAAxA2a3EgfADqEBUYEUhAAjEDwegAF6I5HadAhMKRBFIziwACcABZCUSAOyEikADkJADYaTkURgsLgIL9tm8JnUAGL9IZgEaEAAUEwAlAgAHywCawADUcVmWN02m8ki5JD2BwY_GwjGg0GoKlgyWOp2o5zgV1Erx290ObCsw1odskbGkAzaODsbg8LLYEGMIkIYFIdQDnu92AAyhBURUIsDCQBWZkqj1enAAeR6PWWYEi9EBoNiQPTb3RsAATJi3jjwhsiSnycjiW2iW2aWmWZgcHhujsedR-YMXaMxTVJfAZXLFfRlW8FvNwZr0NrDvxGGwOL3yo9nm6Ic9obD4bAU3WdmwwlYANYMTBhbBH7GhRsRCltr_U79_vKSOqJBrrs-yHJ8WAqK-GD7nEHzQVCMJwoQl4BreD5xE-NTQQ2eItrACL4YRhLEQRaZqquKobgwmTMFYnTBv6KoOgeLwsohZ4oVe7roY-wDPjh754SRRGiSJAHzMQeQ6AA3EAA). That website is out of service.

**Comment by FirstVertex** [comment]
Setting barGap to -300% is problematic for multiple series.
So, I rewrote the Bullet chart to have multiple series capability:
https://codepen.io/HugeHugh/pen/ExdjEMb?editors=0010

**Comment by BrazilAmando** [comment]
> Setting barGap to -300% is problematic for multiple series. So, I rewrote the Bullet chart to have multiple series capability: https://codepen.io/HugeHugh/pen/ExdjEMb?editors=0010

Thanks very much sir. I wondered a lot when trying to create multiple series bullet chart because barGap cannot be applied to single series. You did it👍
