### ISSUE TITLE
How to trigger datazoom inside event on a custom button ?

### ISSUE THREAD

**Issue by joelpanor** [ecomfe/echarts#6799]
I have created a chart with echarts latest version. And I would replace each toolbox button by my own custom button. It is possible?

**Comment by Ovilia** [comment]
https://ecomfe.github.io/echarts-doc/public/en/option.html#toolbox.feature.dataZoom.icon

**Comment by joelpanor** [comment]
Thank you for your answer. I would replace toolbox button with html buttons. It is possible?

**Comment by Ovilia** [comment]
Not html, but SVG path. See: http://gallery.echartsjs.com/editor.html?c=xSy83_6qzg

**Comment by joelpanor** [comment]
Hum thanks, I want to replace these buttons with my own ? Is there a dispatch action for each of these buttons ?
<img width="235" alt="capture d ecran 2017-10-09 a 11 31 01" src="https://user-images.githubusercontent.com/20626624/31345962-e1455ef8-acc3-11e7-8e41-f52f8aa231f4.png">

**Comment by Ovilia** [comment]
I made a demo for you: http://gallery.echartsjs.com/editor.html?c=xHyITk2t3Z&v=1
As for dispatch action, only restore action is supported: http://echarts.baidu.com/api.html#action.toolbox

**Comment by joelpanor** [comment]
Ok thank you for your response. I will try what you show me.
