### ISSUE TITLE
请问日历图如何更改黑色边框？

### ISSUE THREAD

**Issue by gyjx** [ecomfe/echarts#6800]
### One-line summary [问题简述]
![image](https://user-images.githubusercontent.com/20329819/31317170-f7127694-ac6e-11e7-932f-936cb30fcfcc.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:windows7.0

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by liangxiaoyang** [comment]
calendar.splitLine.lineStyle.color
