### ISSUE TITLE
echarts在itemStyle支持颜色的斜向渐变？

### ISSUE THREAD

**Issue by daniel-lij** [ecomfe/echarts#6803]
### One-line summary [问题简述]
echarts在itemStyle支持颜色的斜向渐变？类似css中的background-image: linear-gradient(  [ <angle> | <side-or-corner> ,]? <color-stop> [, <color-stop>]+ )的angle

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
echarts v3.6.0
+ Browser version [浏览器类型和版本]:
chrome 版本 61.0.3163.100（正式版本） （64 位）

+ OS Version [操作系统类型和版本]:
windows10 家庭版

### Expected behaviour [期望结果]

希望echarts团队能都帮我解决问题，或者给出解决方法或者替代方法

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
参考 http://gallery.echartsjs.com/editor.html?c=xSkV_o7Lyg

**Comment by daniel-lij** [comment]
你给我的示例还是一个上下的颜色渐变，并没有可以变换角度的渐变，类似CSS3中的 background-image:linear-gradient(135deg, red 100px, yellow 200px)，他有一个135度的角度

**Comment by Ovilia** [comment]
`echarts.graphic.LinearGradient(0, 0, 0, 1, ....)` 这里前四个参数是起始点和结束点的位置，如果要实现 135度的，就是 `(0, 0, 1, 1)`。效果如图所示：
<img width="285" alt="2017-10-10 12 22 44" src="https://user-images.githubusercontent.com/779050/31369276-ed022ade-ad48-11e7-8bf1-ce160c344e14.png">
