### ISSUE TITLE
定时更新treemap中的data，emphasis状态在再次调用setOption不会消除。

### ISSUE THREAD

**Issue by qilerongrong** [ecomfe/echarts#6804]
定时更新数据（调用setOption），前一个emphasis状态并不会消除。

### One-line summary [问题简述]
http://gallery.echartsjs.com/editor.html?c=xHkk18OcqW&v=2

![image](https://user-images.githubusercontent.com/26840864/31368189-b6610ee4-adae-11e7-8dd2-5093b5133a89.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
要clear一次option，然后在setoption

**Comment by 100pah** [comment]
treemap 本来没有支持在叶节点设置 borderWidth。新增了 strokeColor 和 strokeWidth 来描述这个例子里需要的边框。

（另外这个例子里的 setInterval 中的 `4000` 位置写错了，导致例子很卡。）

**Comment by qilerongrong** [comment]
@100pah 新增的strokeColor和strokeWidth可以用了嘛，文档里没有查到~
