### ISSUE TITLE
在graphGL 下 可以默认显示 点的名称吗 label:true

### ISSUE THREAD

**Issue by itDjango** [ecomfe/echarts#6812]
### One-line summary [问题简述]

用了graphGL方式绘制关系图 ，发现不能默认显示 节点的 名称。
就是说label = true 时 不生效。

怎么解决？？ 
求大神解答。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:     Loaded qtek, version 0.4.1   // Loaded echarts, version 3.7.0
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以设置 formatter

**Comment by itDjango** [comment]
graphGL 下 实现了 节点上默认显示 label标签  ，但是文字的颜色却修改不了， 一直显示为黑色。
`label: {
					show: true,
					normal: {
						show: true,
						color: 'auto',
						position: 'top',
					}
				},`
![image](https://user-images.githubusercontent.com/20026376/31528727-babbdbbc-b007-11e7-9181-bc24460ae92e.png)

**Comment by itDjango** [comment]
找到问题了 
更新最新版本的才可以
