### ISSUE TITLE
echarts图表自适应问题

### ISSUE THREAD

**Issue by kevinzzp** [ecomfe/echarts#6822]
### One-line summary [问题简述]
请问如何解决echarts图表自适应外部容器？
1.当我调整树图的title位置时，比如设置top:15%,当容易高度发生变化时这个值可能会导致title下移遮住主体图表或者上移距离图表过远，请问如何设置才能保证在不同高度的容器中都能正常显示。
2.必须手动调用resize以重新适应父容器么？监听div的大小变化是个麻烦事儿

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新版本
+ Browser version [浏览器类型和版本]:chorme63
+ OS Version [操作系统类型和版本]:不限

### ECharts option [ECharts配置项]

```javascript
option ={"title":{"left":"center","top":"15%","text":"","textStyle":{"color":"#737373","fontSize":13}},"series":[{"type":"treemap","width":"100%","height":"100%","roam":false,"nodeClick":false,"breadcrumb":{"show":false},"label":{"normal":{"show":true,"textStyle":{"fontSize":40,"color":"#E14C46"}}},"itemStyle":{"normal":{"show":true,"borderWidth":1,"borderColor":"#fff"}},"data":[{"value":10,"name":"","itemStyle":{"normal":{"color":"#fffff"}}}]}]}

```

**Comment by Ovilia** [comment]
http://echarts.baidu.com/tutorial.html#%E7%A7%BB%E5%8A%A8%E7%AB%AF%E8%87%AA%E9%80%82%E5%BA%94
