### ISSUE TITLE
与Arcgis地图库一起运行出现echarts未定义

### ISSUE THREAD

**Issue by naranakula** [ecomfe/echarts#6837]
### One-line summary [问题简述]

Arcgis 是二维地图最常见的js脚本库，但是在此版本中，echart不能和Arcgis 一起使用；
因为arcgis使用了自己的require，而echart使用的require和arcgis的不兼容；
以下为测试代码:

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">

    <script src="https://js.arcgis.com/4.5/"></script>
    <script src="http://www.echartsjs.com/gallery/vendors/echarts/echarts-all-3.js?_v_=1506498317457"></script>
    <script>

        window.onload=function(){
            alert(typeof(echarts));// undefined 
        };

    </script>
    <title></title>
</head>
<body>
    hello
</body>
</html>

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by naranakula** [comment]
好像和 requirejs 一起用也有问题。。。
我已经自己改源码了，这是echart版本的兼容性设计问题。不能只考虑自己，还得考虑其他库。
好像这个问题很久前有人提过。系统作者改进！

**Comment by pissang** [comment]
你如果用了 requirejs 的话整个模块环境就是 AMD 了，需要用 require 的方式加载，我们考虑了其它库，谢谢
