### ISSUE TITLE
Bar borderTopWidth

### ISSUE THREAD

**Issue by chuhanan** [ecomfe/echarts#6838]
### One-line summary [问题简述]
我想实现下面的UI
![img](http://obqi5r9i0.bkt.clouddn.com/42F8AA7E-0EFB-4FEB-A0B9-B9126EC537BC.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: any
+ Browser version [浏览器类型和版本]: any
+ OS Version [操作系统类型和版本]: any

### Expected behaviour [期望结果]
1. 可以如图自定义样式,但是目前只有borderWidth的设置,没有精确到4条边
2. 下面的图例可以点击并且展开新的bar图

### ECharts option [ECharts配置项]
```javascript
option = {
    //  nothing here
}

```

### Other comments [其他信息]
请告诉我可以实现的方法, 非常感谢!

**Comment by pissang** [comment]
你可以用另一个 stack 的固定高度柱状图模拟这个效果

**Comment by chuhanan** [comment]
2个柱状图覆盖的方法不能使之透明, bad case~
