### ISSUE TITLE
折线图showSymbol设为false，tooltip trigger设为item后无法触发tooltip

### ISSUE THREAD

**Issue by zuoez02** [ecomfe/echarts#6839]
### One-line summary [问题简述]
多组基于时间戳的数据的折线图，由于数据量比较大，设置showSymbol为true的话浏览器会卡死，设为false之后tooltip出不来，echartInstance也获取不到highlight事件，tooltip设置triggle为axis的话，tooltip只能获取到series中的一组，几乎无法使用。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.2
+ Browser version [浏览器类型和版本]: Chrome 61.0.3163.100（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: macOS High Sierra 10.13

### Expected behaviour [期望结果]

希望能够在鼠标悬浮在某一条折线上的时候显示它或者它最近的点的tooltip

### ECharts option [ECharts配置项]

```javascript
function randomData(x) {
    now = new Date(+now + oneDay + x);
    value = value + Math.random() * 21 - 10;
    return {
        name: now.toString(),
        value: [
            // [now.getFullYear(), now.getMonth() + 1, now.getDate()].join('/'),
            now.toISOString(),
            Math.round(value)
        ]
    }
}

var data = [];
var now = +new Date(1997, 9, 3);
var oneDay = 24 * 3600 * 1000;
var value = Math.random() * 1000;
for (var i = 0; i < 1000; i++) {
    data.push(randomData(30));
}

var data2 = [];
var now = +new Date(1997, 9, 3);
for (var i = 0; i < 1000; i++) {
    data2.push(randomData(40));
}

console.log(data[0], data2[0]);
option = {
    title: {
        text: '动态数据 + 时间坐标轴'
    },
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            animation: false
        }
    },
    xAxis: {
        type: 'time',
        splitLine: {
            show: false
        }
    },
    yAxis: {
        type: 'value',
        boundaryGap: [0, '100%'],
        splitLine: {
            show: false
        }
    },
    series: [{
        name: '模拟数据',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data
    }, {
        name: 'name2',
        type: 'line',
        showSymbol: false,
        hoverAnimation: false,
        data: data2,
    }]
};


```

**Comment by pissang** [comment]
建议 tooltip 设置成 axis 然后不显示 axisPointer

**Comment by zuoez02** [comment]
@pissang 嗯，解决了一部分问题，虽然不能解决显示不同series的值的问题，但是可以通过crossline在y轴上看到值，x轴和tooltip展示时间，某种程度上已经可用了。

**Comment by fengguoqing** [comment]
在我做的项目里也出现了这个问题，显示的是关于CPU频率变化的step line 图，x轴类型为time，数据量比较大，所以关闭了showSymbol，不关闭密密麻麻很不好看，trigger为item时tooltip不响应，为axis时会选中同一y值的多个点，非常影响使 用。@pissang

**Comment by Zhang-DaLei** [comment]
我也遇到了这个问题，现在有解决方案吗

**Comment by xunziheng** [comment]
同样的问题，我给symbol设置了一个image://，是一个透明的circle，trigger依然为item，可以正常展示tooltip，但是，hover的时候无法使用emphasis做一个强调的效果，因为目前无法在emphasis的时候替换symbol。 @pissang @fengguoqing @Zhang-DaLei
