### ISSUE TITLE
请问地图有没有国家搜素功能，输入一个国家名称，然后在地图上定位到具体的国家

### ISSUE THREAD

**Issue by denlaku** [ecomfe/echarts#6844]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
用百度地图插件 https://github.com/ecomfe/echarts/tree/master/extension/bmap
