### ISSUE TITLE
echarts当中的世界地图数据错误，把属于亚洲的部分，划入了欧洲当中

### ISSUE THREAD

**Issue by StarOfLife** [ecomfe/echarts#6882]
### One-line summary [问题简述]
世界地图数据错误，把属于亚洲的部分，划入了欧洲当中

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts-2.2.7
+ Browser version [浏览器类型和版本]:firefox56
+ OS Version [操作系统类型和版本]:windows7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://echarts.baidu.com/echarts2/doc/example/map13.html

**Comment by DukeGJ** [comment]
@StarOfLife 2.0的版本已经不维护了，升级3.0版本试试

**Comment by StarOfLife** [comment]
@DukeGJ 3.0取消了地图数据下载。╮(╯▽╰)╭

**Comment by pissang** [comment]
我们不再提供地图数据，有需要的可以从可靠的渠道获取
