### ISSUE TITLE
echarts-gl 中怎么使用涟漪效果

### ISSUE THREAD

**Issue by gaojinbo010** [ecomfe/echarts#6884]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
GL 暂时不支持

**Comment by succulen-plants** [comment]
现在是否支持
