### ISSUE TITLE
我想请问一下配置项的问题。

### ISSUE THREAD

**Issue by lxd0130** [ecomfe/echarts#6895]
### One-line summary [问题简述]
我看到有的实例中title设置了x，y但是我在配置项手册中并没有找到。还有桑基图中的线条颜色可以设置为‘source’，但是配置项里面也是一点都没有提到。我想请问一下到底还能有多少配置选项是官网配置项手册中没有的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
x, y 是老版本的设置，新版本只是做了兼容，推荐用 left 和 top
