### ISSUE TITLE
echarts绘制饼图的时候，如何不设置color,echarts是怎么给各个扇形分配颜色的呢？

### ISSUE THREAD

**Issue by summerhll** [ecomfe/echarts#6908]
### One-line summary [问题简述]
今天做项目突然想到这个问题。去看源码 也没看懂。请问下各位，echarts它是怎么去分配颜色的呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by swagerYe** [comment]
通过主题 有默认的 你也可以加主题或者直接改颜色
