### ISSUE TITLE
echarts3没有网站热力图，还没有2好用，是在倒退么？

### ISSUE THREAD

**Issue by liyugit** [ecomfe/echarts#6911]
### One-line summary [问题简述]

echarts2 网页热力图的配置很简单，3没有相关示例。
能不能做一个示例，实现地图坐标的那样的效果，有模糊渐变效果的 。

![image](https://user-images.githubusercontent.com/1474766/32105975-0040db0e-baf0-11e7-8240-3a11479af2d2.png)

**Comment by realeve** [comment]
heatmap.js [https://www.patrick-wied.at/static/heatmapjs/](https://www.patrick-wied.at/static/heatmapjs/)

**Comment by pissang** [comment]
3 里暂时不再支持这种形式的热力图，可以选择使用 @realeve 提供的组件

**Comment by fanslin** [comment]
3 不打算支持这种形式的热力图了？

**Comment by ZHUYUANWEI** [comment]
实在太可惜了，我现在也想用这种热力图，不想再引一个组件了
