### ISSUE TITLE
关系图中如何设置某个节点作为中心节点

### ISSUE THREAD

**Issue by zhiyouai** [ecomfe/echarts#6913]
### One-line summary [问题简述]
在手机端通过echarts框架绘制关系图谱，由于手机屏幕有限，无法显示所有节点，用户不同时候进行操作时，其关联的节点不同，希望每次都能将与用户关联的节点显示在屏幕中心，请问能不能直接设置某个节点作为中心点，亦或者通过设置坐标将该节点平移到屏幕中心？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以设置 center 试试

**Comment by zhiyouai** [comment]
这个问题解决了，在最初预设各个节点坐标后，将目标节点的fixed属性设置为true，之后将该坐标设置为center
