### ISSUE TITLE
怎样自建一个地图？

### ISSUE THREAD

**Issue by philwu** [ecomfe/echarts#6916]
现在好像只提供了中国和世界地图。我需要澳大利亚悉尼市区的地图。
我看echarts.registerMap方法的参数里的coordinates项里完全不明白是什么东西。能不能介绍一下原理？
如果可以，我会尝试做一个工具出来给大家创建自己想要的地图。

**Comment by chfw** [comment]
我最近自己做了英格兰地图，等我抽空可以写个具体的指导。我用的是这个衍生工具：https://github.com/chfw/echarts-mapmaker

步骤1: 先用property command, 调整geson的properties. 目标是要产生一个地理实体一个"name"
步骤2:再用compress command, 进行压缩，这样适合网上下载。

这个是我做的英格兰地图：
![withit](https://user-images.githubusercontent.com/4280312/31038094-bce96cce-a56c-11e7-887a-3a6c2cb82af5.png)

**Comment by philwu** [comment]
感谢

**Comment by chfw** [comment]
忘了写这个：Ordnance Survey data covered by OS OpenData Licence

地图数据来自这个地方：https://github.com/martinjc/UK-GeoJSON
