### ISSUE TITLE
echarts2.0 气泡图如何自定义象限划分值

### ISSUE THREAD

**Issue by AbelLi18** [ecomfe/echarts#6918]
### One-line summary [问题简述]
- 目前echarts2.0 气泡图默认是以(0,0)点为中心点， 按照正负划分象限值， 但我现在想以平均值为横轴， 那我如何自定义划分象限的标准？ 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 2.0

### Expected behaviour [官方示例]

http://echarts.baidu.com/echarts2/doc/example/scatter2.html

**Comment by DukeGJ** [comment]
可是设置min和max
