### ISSUE TITLE
X轴的splitNumber设定后，为了数据易读性而返回的的值，这段逻辑在源码第几行?

### ISSUE THREAD

**Issue by ShannyShanny** [ecomfe/echarts#6919]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/blob/master/src/scale/Interval.js#L121
