### ISSUE TITLE
Do we have any alternative of Venn Diagram in Echarts 3

### ISSUE THREAD

**Issue by mhaseamol** [ecomfe/echarts#6920]
Do we have any alternative of Venn Diagram in Echarts 3.

I want to use Venn Diagram in my project and I have used Echarts 3 for rest of my visualization but I don't find Venn Diagram in Echarts 3.
Can anyone help.
Thanks in advance.

**Comment by pissang** [comment]
Sorry,  ECharts3 don't support Venn diagram anymore. Please use http://www.benfrederickson.com/venn-diagrams-with-d3.js/ as an alternative.

**Comment by mhaseamol** [comment]
Can I use multiple versions of Echarts V2 and V3 in same application.
As Venn diagram is in V2.

**Comment by pissang** [comment]
Yes, it's possible if you use JS modules like AMD, CommonJS, ES6 modules.

**Comment by mhaseamol** [comment]
Thanks @pissang , is it possible to draw venn diagram with five circles in Echarts V2.
I am new and don't find any solution for that as well.
