### ISSUE TITLE
日历图问题，请教各位大牛

### ISSUE THREAD

**Issue by yliu1993** [ecomfe/echarts#6922]
请教各位大神，怎样让日历图中的周一到周五显示的日期颜色，与周六周日显示日期颜色不同，比如 1号，2号，3号，4号，5号是周一到周五，格子里的数字颜色显示黑色。6号，7号是周末 显示红色

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by The-only** [comment]
参见[#6701](https://github.com/ecomfe/echarts/issues/6701)
