### ISSUE TITLE
ECharts gallery中的示例的下载学习问题

### ISSUE THREAD

**Issue by Jagger3d** [ecomfe/echarts#6925]
### One-line summary [问题简述]

如何能够将不错的ECharts gallery中示例下载下来，以方便学习，谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
保存option里的内容即可

**Comment by Jagger3d** [comment]
但是我看到示例中的json内容和格式啊。。。。。

**Comment by Jagger3d** [comment]
但是我看不到示例中json的内容和形式啊

**Comment by DukeGJ** [comment]
@Jagger3d option里的内容难道不是json格式吗？

**Comment by Jagger3d** [comment]
您看pissang的Flights示例，其中的myChart就看不到怎么写的

**Comment by DukeGJ** [comment]
@Jagger3d 给个地址

**Comment by Jagger3d** [comment]
您好，我模仿文档，新建了一个myChart,但是不知道怎么搞得，报错内容为：Component series.lines3D not exists.Load it first,然后我尝试搜索了解答，但是都跟我的问题不一样。。。是因为我引入echarts.js的版本不一致吗?

**Comment by chfw** [comment]
echarts-gl.js要加载
