### ISSUE TITLE
行情图 markLine 右端是否可以增加呼吸灯效果

### ISSUE THREAD

**Issue by 961900832** [ecomfe/echarts#6927]
### One-line summary [问题简述]
在黑色标注处是否可以添加呼吸灯效果?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
ECarts 3+

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/19699561/32217807-11ea1f06-be64-11e7-9392-023d3fceffeb.png)

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/6926#issuecomment-340958065
