### ISSUE TITLE
how to load more than one provice by registerMap() method

### ISSUE THREAD

**Issue by xiyuyizhi** [ecomfe/echarts#6931]
### One-line summary [问题简述]

I want to both show GuangDong and GuangXi in a map ,but i can only use the registerMap('guangdong',guangdong.json) or registerMap('guangxi',guangxi.json) to show only one.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
You can use 'guangdong' in one series, and 'guangxi' in an other series.

**Comment by xiyuyizhi** [comment]
@100pah thanks,but it not work,i resolve it by another way.
`
import guangDong from "echarts/map/json/province/guangdong.json"
import guangXi from "echarts/map/json/province/guangxi.json"

const guang_dong_xi={
"type": "FeatureCollection",
"features": guangDong.features.concat(guangXi.features),
  "UTF8Encoding": true
}

echarts.registerMap('guangDongXi', guang_dong_xi)

`
