### ISSUE TITLE
toolbox  datazoom 可以默认开启状态吗？

### ISSUE THREAD

**Issue by jerdbo** [ecomfe/echarts#6934]
### One-line summary [问题简述]

toolbox  datazoom 可以默认开启状态吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
可以这么来控制这个功能的开启关闭
```js
myChart.dispatchAction({
    type: 'takeGlobalCursor',
    key: 'dataZoomSelect',
    dataZoomSelectActive: true // 开启或关闭
})
```
