### ISSUE TITLE
java后台如何调用echarts动态生成图片

### ISSUE THREAD

**Issue by abc1991lzm** [ecomfe/echarts#6939]
试了好多方法，都不行，请问有什么好的办法。

**Comment by pissang** [comment]
用 node + node-canvas，或者用 headless chrome

**Comment by FFHHVV** [comment]
搜索：PhantomJS
已成功应用PhantomJS在后台生成图文报告

**Comment by chfw** [comment]
phantomjs:
https://github.com/chfw/pyecharts-snapshot/blob/master/pyecharts_snapshot/phantomjs/snapshot.js

chrome puppeteer:
https://github.com/chfw/echarts-scrappeteer

node-echarts(using node-canvas):
https://github.com/suxiaoxin/node-echarts/issues/9

**Comment by eniac27427** [comment]
如果是echarts+bmap，可以导出图片，但是bmap部分无法导出。求支招
