### ISSUE TITLE
echarts 3.0可以设置内发光效果吗

### ISSUE THREAD

**Issue by arixse** [ecomfe/echarts#6945]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行

**Comment by arixse** [comment]
谢谢
