### ISSUE TITLE
如何针对于树形矩形图的name属性可以设置url来连接一个图片地址进行返回,并进行显示吗?

### ISSUE THREAD

**Issue by shanewds** [ecomfe/echarts#6954]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
（1）
> 如何针对于树形矩形图的name属性可以设置url来连接一个图片地址进行返回,并进行显示吗? 

这句话似乎有些语病。

（2）使用 [richText](http://echarts.baidu.com/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE) 可以在文本中加入图片。

**Comment by shanewds** [comment]
有没有一个demo?发一下
