### ISSUE TITLE
option legend selectedMode

### ISSUE THREAD

**Issue by 15915940450** [ecomfe/echarts#6971]
### One-line summary [问题简述]
option legend selectedMode

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:Chrome 61.0.3163.100
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]
selectedMode能否添加一个选项值，例如mutiple2single。实现用户点击legend之前是mutiple的形式，当用户点击legend之后就变成single形式，并且被点击的legend是选中的状态。

即：
         legend:{
            selectedMode:'multiple'  //multiple,single
          },

         myChart.on('legendselectchanged',function(params){
            for(var k in params.selected){
              //点选
              if(k===params.name){
                myChart.dispatchAction({
                  type:'legendSelect',
                  name:params.name
                });
              }else{
                myChart.dispatchAction({
                  type:'legendUnSelect',
                  name:k
                });
              }
            }

          }); //legendselectchanged

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
什么业务场景，需要这样的需求呢？

**Comment by 15915940450** [comment]
我们老板就是希望这种操作习惯：

**Comment by 15915940450** [comment]
刚开始载入页面的时候，老板希望看到整体全部的曲线趋势图，可是老板想单独细看某条曲线的时候，他直觉就是去点击那条曲线legend。但因为selectedMode:'multiple'，所以操作的结果是把他想看的那条曲线给隐藏了。所以，能否在selectedMode多加一个选项值呢（multiple，single，？）
