### ISSUE TITLE
3.8.0开始不能编译了！

### ISSUE THREAD

**Issue by superddr** [ecomfe/echarts#6981]
居然引入import语法？

**Comment by superddr** [comment]
是不是来了个新人? 热衷各种新技术? 在npm里面放es6语法? 编译的时候babel一般不包含node_module里的东西的, 不管node几,echarts编译就是报错! 
项目下几百个依赖, 唯一编译出错的就是echarts和zrender! 
这种完全不兼容的代码更改居然是小版本更新? jenkins上一更新立刻项目fail!

**Comment by Jeffy2012** [comment]
能用babel转义一下？感觉是低级错误呀

**Comment by YuyangGong** [comment]
老项目， 还在用webpack1.0， 不支持import，如果使用3.8.0版本echarts, 需要babel转码， 所以用最简单粗暴的方式，直接琐死echarts的版本。
在package.json里修改(以3.2.3版本举例)：
- "echarts": "^3.2.3"
+"echarts": "3.2.3"
去掉"^", 锁死当前版本。
相关issue： [https://github.com/ecomfe/echarts/issues/6984](https://github.com/ecomfe/echarts/issues/6984)

**Comment by mygaochunming** [comment]
同样的问题！这是要弄哪样？

**Comment by vankai** [comment]
在package.json的依赖中 把版本号改为以下的 ，可以指定3.7版本 临时解决一下。 
```
"echarts": "https://registry.npmjs.org/echarts/-/echarts-3.7.2.tgz",
 "zrender": "https://registry.npmjs.org/zrender/-/zrender-3.6.3.tgz"
```

ps:这种版本升级，应该在3上面加1吧？大版本升级 :doge:。

**Comment by tianxiaofeng747** [comment]
echarts 好坑。。

**Comment by wssgcg1213** [comment]
同样遇到, @matainer 尽快解决下?

**Comment by xingxinghuo1000** [comment]
请尽快解决一下，这种问题应该不难解决的

**Comment by xingxinghuo1000** [comment]
建议先回滚， 最新版本 就当没发出来

**Comment by jsers** [comment]
麻烦紧急出个修复版本吧

**Comment by mxyzzhong** [comment]
同被坑，昨天几个项目代码更新，CI一跑，项目全挂了，希望引起重视啊。

**Comment by leungwensen** [comment]
建议可以配置一下`package.json`的`main/module/browser`字段，这样可以规避这个问题：

```js
  "main": "build/echarts.js",
  "browser": "build/echarts.min.js",
  "module": "index.js",
```

这样的话还可以保留`index.js`里的es6的写法。另外，不配置`main`字段还有个风险，目前托管`npm`包的`CDN`服务 https://unpkg.com 是会读`package.json`的`main`字段的，这个字段指向的文件必须符合`UMD`标准：
 https://unpkg.com/echarts

@100pah
