### ISSUE TITLE
使用svg渲染饼图时动画消失

### ISSUE THREAD

**Issue by Ellery0924** [ecomfe/echarts#6989]
### One-line summary [问题简述]
首次渲染时动画消失，之后做setOption动画正常

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这个问题是由于 SVG 对于 Text 和其他形状的 clipPath 用了不同的 DOM（因为计算 transform 的方式不同），而第两次 appendChild 会导致前一次的父元素失效。
ecomfe/zrender@c05ac82 已修复该问题，下个版本上线。
