### ISSUE TITLE
图表在博客文章body中无法显示，但在文章外的网页上正常显示

### ISSUE THREAD

**Issue by OakSuen** [ecomfe/echarts#6998]
### One-line summary [问题简述]

图表在博客文章body(text field)中无法显示，但在文章外的网页上正常显示，猜测可能是javascript在文章中失效，用的Django框架。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8
+ Browser version [浏览器类型和版本]: Safari， Chrome
+ OS Version [操作系统类型和版本]: Ubuntu14

### Expected behaviour [期望结果]

在博客文章的某刻特定部位，正常显示图表，而不只是在文章外面。

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

文章详情页的HTML代码
![image](https://user-images.githubusercontent.com/22917789/32599140-e553b676-c53b-11e7-9de8-ca41294bc62b.png)

**Comment by OakSuen** [comment]
图表在博客文章body中无法显示，但在文章外的网页上正常显示

**Comment by Ovilia** [comment]
这是 Django 框架的使用问题。
