### ISSUE TITLE
echarts 3.8.2 无法注册地图

### ISSUE THREAD

**Issue by PUGE** [ecomfe/echarts#7010]
### One-line summary [问题简述]

echarts8.2版本使用echarts.registerMap函数时报错
错误信息： echarts.registerMap为undefined

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.2
+ Browser version [浏览器类型和版本]:Google Chrome最新
+ OS Version [操作系统类型和版本]:windows10

### Other comments [其他信息]
截图
http://puge-10017157.cossh.myqcloud.com/temp/TIM%E6%88%AA%E5%9B%BE20171110150342.png

**Comment by pissang** [comment]
能描述下你是如何引入 echarts 的么？

**Comment by PUGE** [comment]
我的main.js代码
```
import Vue from 'vue'
import App from './App'
import router from './router'
import store from './store'
import echarts from 'echarts'
import Deformation from 'deformation'
import method from './method'
import VueDND from 'awe-dnd'
import 'echarts-gl'
import 'echarts-wordcloud'
import 'echarts-liquidfill' // 水球图

Vue.use(VueDND)
Vue.use(method)

Vue.component('Deformation', Deformation)
// echarts地图注册
// 判断当前网络协议 使用正确的加载方式
if (echarts.registerMap) {
  if (window.location.protocol === 'file:') {
    Vue.prototype.$load('http://dataplus-1251887489.cosbj.myqcloud.com/json/china.json', (response) => {
      echarts.registerMap('china', response)
    })
    Vue.prototype.$load('http://dataplus-1251887489.cosbj.myqcloud.com/json/world.json', (response) => {
      echarts.registerMap('world', response)
    })
  } else {
    Vue.prototype.$load('./static/assets/china.json', (response) => {
      echarts.registerMap('china', response)
    })
    Vue.prototype.$load('./static/assets/world.json', (response) => {
      echarts.registerMap('world', response)
    })
  }
} else {
  console.error('echarts加载失败！')
}
```

**Comment by PUGE** [comment]
通过import echarts from 'echarts'方式引入

**Comment by pissang** [comment]
@PUGE 好像直接引入整个包是有这个问题，可以先 `import echarts from 'echarts/dist/echarts'` 引入构建好的文件

**Comment by PUGE** [comment]
@pissang 使用import echarts from 'echarts/dist/echarts' 虽然不报错了但是地图实际上还是没有注册成功  中国地图显示成了 ![Alt dddddd](http://puge-10017157.cossh.myqcloud.com/temp/TIM%E6%88%AA%E5%9B%BE20171110153759.png)

**Comment by pissang** [comment]
@PUGE 刚发了 3.8.3 解决地图的问题，你再试试`require('echarts')`

**Comment by pissang** [comment]
@PUGE 你不能显示中国地图的代码也发我看下吧

**Comment by PUGE** [comment]
@pissang  十分感谢 使用了3.8.3版本的echarts图表都正常了，中国地图已经能正常加载出来了

**Comment by PUGE** [comment]
中国地图的问题 在3.8.3版本已经解决了

**Comment by pissang** [comment]
把 wordcloud 移除后重新安装试试呢？可能因为安装 wordcloud 的时候也安装了老版本的 echarts，然后打包出现了两个 echarts 的 namespace

**Comment by cchenggit** [comment]
@PUGE  

> 第2个问题.如果webpack.DefinePlugin不设置__DEV__:false允许会出现 DEV is not defined的问题.

确实有用,感谢.

**Comment by PUGE** [comment]
@pissang 移除后重新安装wordcloud 和 echarts-liquidfill依然无效 
```
Component series.liquidFill not exists. Load it first.
series.wordCloud not exists. Load it first.
```
我的引入方法
```
import Vue from 'vue'
import App from './App'
import router from './router'
import store from './store'
import echarts from 'echarts'
import Deformation from 'deformation'
import method from './method'
import VueDND from 'awe-dnd'
import 'echarts-gl'
import 'echarts-wordcloud'
import 'echarts-liquidfill' // 水球图
```
gl是正常的
