### ISSUE TITLE
堆叠折线图数据和堆叠柱状图数据不匹配

### ISSUE THREAD

**Issue by EarlYan** [ecomfe/echarts#7017]
### One-line summary [问题简述]
堆叠折线图按map形式放入数据类似于['周一',120], ['周三',134],['周日',210]
转换为堆叠折线图和数据视图
则为
周一	120
周二	134
周三	210
周四	
周五	
周六	
周日 

### ECharts option [ECharts配置项]
option = {
    title: {
        text: '折线图堆叠'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['邮件营销','联盟广告','视频广告','直接访问','搜索引擎']
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        show : true,
        feature : {
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一','周二','周三','周四','周五','周六','周日']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'邮件营销',
            type:'line',
            stack: '总量',
            data:[['周一',120], ['周三',134],['周日',210]]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            data:[220, null, 191, 200, 290, null, 310]
        },
        {
            name:'视频广告',
            type:'line',
            stack: '总量',
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'直接访问',
            type:'line',
            stack: '总量',
            data:[320, 332, 301, 334, 390, 330, 320]
        },
        {
            name:'搜索引擎',
            type:'line',
            stack: '总量',
            data:[820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
};

**Comment by EarlYan** [comment]
![image](https://user-images.githubusercontent.com/20061577/32685510-c9d42f3c-c6cd-11e7-8814-2dd6d60b0131.png)
![image](https://user-images.githubusercontent.com/20061577/32685513-d8efae56-c6cd-11e7-8130-a4917ffa4bd1.png)
![image](https://user-images.githubusercontent.com/20061577/32685514-e1116fde-c6cd-11e7-9604-eba9410ce739.png)

**Comment by EarlYan** [comment]
请问有没有解决办法呢

**Comment by EarlYan** [comment]
@pissang

**Comment by pissang** [comment]
去掉stack

**Comment by EarlYan** [comment]
@pissang去掉stack数据视图还是有问题
