### ISSUE TITLE
中国地图中有没有钓鱼岛的体现？

### ISSUE THREAD

**Issue by MaggieLijialu** [ecomfe/echarts#7018]
### One-line summary [问题简述]

中国地图中有没有钓鱼岛的体现？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:OSX Serria

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
ECharts 目前不提供地图下载功能，之前提供的版本也是来自第三方的，并且是包含钓鱼岛的。

**Comment by chfw** [comment]
如果我没有弄错的话，下面的圈点是钓鱼岛。

<img width="244" alt="screen shot 2017-11-13 at 08 16 53" src="https://user-images.githubusercontent.com/4280312/32715800-9a890e1c-c84b-11e7-9a50-b1d5f586af4b.png">
