### ISSUE TITLE
我已经是3.8.3版本了，为什么还会报__DEV__ is not defined

### ISSUE THREAD

**Issue by candy1919** [ecomfe/echarts#7021]
### One-line summary [问题简述]
我已经是3.8.3版本了，为什么还会报__DEV__ is not defined

代码：
<template>
  <div class="hello">
    <div class="wrap" id="main">
    </div>
  </div>
</template>
<script>
// 引入 echarts 主模块。
import * as echarts from 'echarts/src/echarts';
// 引入折线图。
import 'echarts/src/chart/line';
// 引入提示框组件、标题组件、工具箱组件。
import 'echarts/src/component/tooltip';
import 'echarts/src/component/title';
import 'echarts/src/component/toolbox';
export default {
  name: 'hello',
  data() {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
  mounted() {
    // 基于准备好的dom，初始化 echarts 实例并绘制图表。
    echarts.init(document.getElementById('main')).setOption({
        title: {text: 'Line Chart'},
        tooltip: {},
        toolbox: {
            feature: {
                dataView: {},
                saveAsImage: {
                    pixelRatio: 2
                },
                restore: {}
            }
        },
        xAxis: {},
        yAxis: {},
        series: [{
            type: 'line',
            smooth: true,
            data: [[12, 5], [24, 20], [36, 36], [48, 10], [60, 10], [72, 20]]
        }]
    });
  }
}
</script>

<style scoped>
h1, h2 {
  font-weight: normal;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  height: 100px;
  margin: 0 10px;
}
.wrap{
  height: 240px;
}
a {
  color: #42b983;
}
</style>

### Version & Environment [版本及环境] vue 2.5.2
+ ECharts version [ECharts 版本]: 3.8.3
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by shikelong** [comment]
看看node_module里面是不是老版本。是的话强制安装新版本。

**Comment by pissang** [comment]
从 echarts/lib 引入
