### ISSUE TITLE
bar borderRadius不能设置成圆弧状吗，无论设置多大值，到一定程度曲率就不变了

### ISSUE THREAD

**Issue by wangtun** [ecomfe/echarts#7023]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.2
+ Browser version [浏览器类型和版本]: chrome, 59
+ OS Version [操作系统类型和版本]: win7

![image](https://user-images.githubusercontent.com/14052340/32707786-e8b35c9c-c7eb-11e7-9540-ebd554efb78a.png)

### Expected behaviour [期望结果]
能和css一致，相关borderRadius能设置成圆弧状

### ECharts option [ECharts配置项]

```javascript
option = {
    type: 'bar',
            barWidth: 50,
            itemStyle: {
                normal: {
                    barBorderRadius: 50,
                    color: new echarts.graphic.LinearGradient(
                        0, 0, 0, 1,
                        [
                            {offset: 0, color: '#00F2FE'},
                            {offset: 1, color: '#4FACFE'}
                        ]
                    )
                }
            },
}

```

**Comment by Ovilia** [comment]
用数组表示 http://echarts.baidu.com/option.html#series-bar.itemStyle.normal.barBorderRadius

**Comment by wangtun** [comment]
@Ovilia 可能我没有表达清楚，我想要的效果类似 css这种的，两端的圆弧曲率接近圆，但是echarts里面无论怎么设置，都只能是椭圆状
![image](https://user-images.githubusercontent.com/14052340/32707946-f0192dd0-c7ec-11e7-87cd-8062f9c6320a.png)

**Comment by Ovilia** [comment]
@wangtun http://gallery.echartsjs.com/editor.html 复现下？

**Comment by wangtun** [comment]
@Ovilia option = {
    title: {
        text: 'Awesome Chart'
    },
    xAxis: {
        data: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },
    yAxis: {},
    series: [{
        type: 'bar',
        barWidth: 50,
            itemStyle: {
                normal: {
                    barBorderRadius: [100,100,100,100],
                    color: new echarts.graphic.LinearGradient(
                        0, 0, 0, 1,
                        [
                            {offset: 0, color: '#00F2FE'},
                            {offset: 1, color: '#4FACFE'}
                        ]
                    )
                }
            },
        data:[220, 182, 191, 234, 290, 330, 310]
    }]
};



css3:

![Uploading image.png…]()
这两个圆弧的曲率不一样，echart那个形成不了圆弧，不知道您明白了没？

**Comment by wangtun** [comment]
![image](https://user-images.githubusercontent.com/14052340/32711989-955973da-c807-11e7-882b-f5c0e7c142c2.png)
![image](https://user-images.githubusercontent.com/14052340/32711999-a1abb436-c807-11e7-9d13-749af7315039.png)

**Comment by Ovilia** [comment]
明白了，好像是有问题
