### ISSUE TITLE
南丁格尔图数据范围太大，半径差距太大

### ISSUE THREAD

**Issue by zhangya5847** [ecomfe/echarts#7026]
### One-line summary [问题简述]

由于数据量差距太大，饼图的半径，数据小的半径很短，基本看不到，查文档，只有设置最小角度的，没有设置最小半径，影响用户体验。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.7.2
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: Mac

### Expected behaviour [期望结果]

能够设置最小半径。

### Other comments [其他信息]

实例：
[http://gallery.echartsjs.com/editor.html?c=xrk356sZkG&v=2](url)

**Comment by Ovilia** [comment]
南丁格尔图本来带有夸大数据的效果，数据量差异大的情况下请谨慎选择。建议自己对数据做预处理，对于太小的数据自己做最小处理。另外，可以考虑极坐标系柱状图：http://echarts.baidu.com/demo.html#bar-polar-stack-radial

**Comment by zhangya5847** [comment]
好的，谢谢你的建议！

**Comment by bichenxi** [comment]
我觉着 那么官方该优化下的

**Comment by pumpkindev** [comment]
我觉着 那么官方该优化下的
