### ISSUE TITLE
饼图富文本标签在svg模式下出现问题

### ISSUE THREAD

**Issue by jackfxq** [ecomfe/echarts#7030]
### One-line summary [问题简述]
饼图在进行富文本标签设置的时候,设置如下：
```javascript
formatter:'{name|{b}}',
rich:{
 name:{
    color:'#ff5577'
}
}
```
在canvas模式下能够正常的显示出来，在svg模式下显示{name|数据名}

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.3
+ Browser version [浏览器类型和版本]:chrome58.0.3029
+ OS Version [操作系统类型和版本]:win 7

### ECharts option [ECharts配置项]

```javascript
option = {
  series:[{
   type:'pie',
   label:{
      normal:{
          formatter:'{name|{b}}',
          rich:{
               name:{
                      color:'#ff5577'
                }
            }
       }
   },
   data:[{name:'测试',value:120}]
}]
}

```

**Comment by jackfxq** [comment]
看到了 beta版还没支持。。。

**Comment by Ovilia** [comment]
SVG 还不支持富文本，谢谢使用
