### ISSUE TITLE
多 grid 情况下，每个 grid 有双 y 轴，会报错

### ISSUE THREAD

**Issue by lynzz** [ecomfe/echarts#7039]
### One-line summary [问题简述]

我想创建多个 grid 的图，每一个 gird 有两个 y 轴，左边的 y 轴，显示 mean 值，右边显示 cv 值。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.2
+ Browser version [浏览器类型和版本]: chrome 62.0.3202.75（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: macOS Sierra 10.12.6

### Expected behaviour [期望结果]

多个 grid 情况，每一个 grid 能显示两个 y 轴，即左右 y 轴，如下图：

![image](https://user-images.githubusercontent.com/348917/32774834-8a84ab52-c968-11e7-8502-17e39ccf1c1e.png)

目前这个，是通过创建两个 echart 图实现的

### ECharts option [ECharts配置项]

```javascript
option = {
  "title": [
    { "top": 90, "left": 0, "text": "水平1" },
    { "top": 315, "left": 0, "text": "水平2" }
  ],
  "grid": [
    { "show": true, "top": 90, "left": 150, "height": 135, "right": 100 },
    { "show": true, "top": 315, "left": 150, "height": 135, "right": 100 }
  ],
  "xAxis": [
    {
      "type": "category",
      "gridIndex": 0,
      "data": [
        "2015年9月",
        "2015年10月",
        "2015年11月",
        "2015年12月",
        "2016年1月",
        "2016年2月"
      ],
      "axisTick": { "alignWithLabel": false }
    },
    {
      "type": "category",
      "gridIndex": 1,
      "data": [
        "2015年9月",
        "2015年10月",
        "2015年11月",
        "2015年12月",
        "2016年1月",
        "2016年2月"
      ],
      "axisTick": { "alignWithLabel": false }
    }
  ],
  "yAxis": [
    {
      "type": "value",
      "min": "dataMin",
      "max": "dataMax",
      "data": [
        0,
        0,
        0,
        19.429166666666667,
        19.323076923076925,
        19.473333333333333
      ],
      "gridIndex": 0,
      "axisLabel": {}
    },
    {
      "type": "value",
      "gridIndex": 0,
      "data": [
        0,
        0,
        0,
        2.665691122036377,
        4.0467169269835725,
        2.3887418375882477
      ],
      "axisLabel": { "formatter": "{value}%" },
      "position": "right",
      "splitLine": { "show": false }
    },
    {
      "type": "value",
      "min": "dataMin",
      "max": "dataMax",
      "data": [
        0,
        0,
        0,
        23.254166666666666,
        23.323076923076922,
        21.686666666666664
      ],
      "gridIndex": 1,
      "axisLabel": {}
    },
    {
      "type": "value",
      "gridIndex": 1,
      "data": [
        0,
        0,
        0,
        3.7830337797621816,
        3.037382282946053,
        6.722645071435536
      ],
      "axisLabel": { "formatter": "{value}%" },
      "position": "right",
      "splitLine": { "show": false }
    }
  ],
  "series": [
    {
      "name": "CV",
      "type": "bar",
      "data": [
        [0, 0],
        [1, 0],
        [2, 0],
        [3, 25],
        [4, 4.0467169269835725],
        [5, 2.3887418375882477]
      ],
      "xAxisIndex": 0,
      "yAxisIndex": 0,
      "barWidth": "20px"
    },
    {
      "name": "均值",
      "type": "line",
      "data": [
        [0, 0],
        [1, 0],
        [2, 0],
        [3, 19.429166666666667],
        [4, 19.323076923076925],
        [5, 19.473333333333333]
      ],
      "xAxisIndex": 0,
      "yAxisIndex": 0,
      "connectNulls": true
    },
    {
      "name": "CV",
      "type": "bar",
      "data": [
        [0, 0],
        [1, 0],
        [2, 0],
        [3, 3.7830337797621816],
        [4, 3.037382282946053],
        [5, 6.722645071435536]
      ],
      "xAxisIndex": 1,
      "yAxisIndex": 1,
      "barWidth": "20px"
    },
    {
      "name": "均值",
      "type": "line",
      "data": [
        [0, 0],
        [1, 0],
        [2, 0],
        [3, 23.254166666666666],
        [4, 23.323076923076922],
        [5, 21.686666666666664]
      ],
      "xAxisIndex": 1,
      "yAxisIndex": 1,
      "connectNulls": true
    }
  ]
}


```

### Other comments [其他信息]

[demo](https://jsfiddle.net/lynzz/obmammm2/4/)

**Comment by lynzz** [comment]
通过一个 grid 对应一个 y 轴来解决了

**Comment by Faithforus** [comment]
请问我的多grid多yaxis数据渲染时，只会对应左边的yaxis，右边的yaxis失效了。这是我哪边弄错了吗？
option = {
    xAxis: [{
            data: []
        },
        { 
            data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            gridIndex: 1,
        }
    ],
    yAxis: [{
            position: 'left',
        },

        {   
            position: 'left',
            gridIndex: 1
        }, {
            position: 'right',
            min: -1.01,
            max: 1.01,

        },
        {
            position: 'right',
            min: 84,
            max: 930,
            gridIndex: '1'

        }
    ],
    grid: [{
        bottom: '50%'
    }, {
        top: '50%'
    }],
    series: [{
            type: 'line',
            grid: 0,
            yAxisIndex: 0,
            areaStyle: {},
            showSymbol: false,
            data: [11, 22, 33, 44, 55, 66, 77]
        },
        {
            type: 'line',
            showSymbol: false,
            data: [56, 78, 95, 100, 120, 130, 140, 200, 20],
            xAxisIndex: '1',
            yAxisIndex: '1'
        },
        {
            grid: 0,
            type: 'line',
            showSymbol: false,
            data: [1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, -0.5]
        }, {
            type: 'bar',
            showSymbol: false,
            data: [30, 40, 80, 60, 70, 70, 60, 600],
            xAxisIndex: '1',
            yAxisIndex: '1'
        }
    ]
};
