### ISSUE TITLE
在Angular应用中使用echart，会持续占用cpu

### ISSUE THREAD

**Issue by hpyou** [ecomfe/echarts#7047]
### One-line summary [问题简述]
echart在Angular里面使用，会持续占用cpu，这是性能图：

![image](https://user-images.githubusercontent.com/15992591/32822847-6fbce142-ca15-11e7-8290-0c5a046b4c9c.png)

主要是触发了AnimationFrame:

![image](https://user-images.githubusercontent.com/15992591/32822864-7f0c266c-ca15-11e7-8878-c3621a4ba67b.png)

通过callstack查询到这个函数会持续调用：

![image](https://user-images.githubusercontent.com/15992591/32823162-f207b144-ca16-11e7-87eb-222baa8962d7.png)

对应的echart里的代码：
![image](https://user-images.githubusercontent.com/15992591/32823200-2017a99a-ca17-11e7-94ce-0259ec1e60dc.png)

主要是Animation对象里的`_startLoop`函数里有个递归调用`step`，并且`self._running`一直是`true`，这使得`step`一直会被调用。这在Angular的zone会触发变更检查，导致占用cpu。一般一张图会占用8、9个点。

![image](https://user-images.githubusercontent.com/15992591/32823482-5c6490d8-ca18-11e7-85f4-caa4b175914d.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.5.4
+ Browser version [浏览器类型和版本]: chrome 60.0.3112.101（正式版本） （32 位）
+ OS Version [操作系统类型和版本]: win7

### Expected behaviour [期望结果]
页面无操作时，不应该占用cpu

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by hpyou** [comment]
Question like #2886

**Comment by Ovilia** [comment]
@hpyou 所以跟 Angular 环境没什么关系是吧？我后面会看下

**Comment by hpyou** [comment]
@Ovilia 是的，我在一个新的html里面引用echart也会有这样的问题

**Comment by rdkmaster** [comment]
请 @hpyou 把你测试的html文件给贴到这里，麻烦 @Ovilia 看看。

这个问题和angular没有任何关系。

**Comment by rdkmaster** [comment]
@Ovilia 当页面上只有少数几个图的时候，看不出区别，但是当一个页面上很多图（我们的一个页面有30个echart图）的时候，浏览器进程就把cpu吃满了。

**Comment by Ovilia** [comment]
@rdkmaster 图片类型有什么特殊的吗？还是每种都会有？

**Comment by hpyou** [comment]
@Ovilia 我用是饼图,

echart代码用npm包里的echarts\dist\echarts.js ，版本是3.5.4。

这是html页面：

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
<div id="main" style="height:400px"></div>
<!-- ECharts单文件引入 -->
<script src="echarts.js"></script>
<script type="text/javascript">
    var myChart = echarts.init(document.getElementById('main'));
    var option = {
        title : {
            text: '某站点用户访问来源',
            subtext: '纯属虚构',
            x:'center'
        },
        tooltip : {
            trigger: 'item',
            formatter: "{a} <br/>{b} : {c} ({d}%)"
        },
        legend: {
            orient : 'vertical',
            x : 'left',
            data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
        },
        toolbox: {
            show : true,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {
                    show: true,
                    type: ['pie', 'funnel'],
                    option: {
                        funnel: {
                            x: '25%',
                            width: '50%',
                            funnelAlign: 'left',
                            max: 1548
                        }
                    }
                },
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        series : [
            {
                name:'访问来源',
                type:'pie',
                radius : '55%',
                center: ['50%', '60%'],
                data:[
                    {value:335, name:'直接访问'},
                    {value:310, name:'邮件营销'},
                    {value:234, name:'联盟广告'},
                    {value:135, name:'视频广告'},
                    {value:1548, name:'搜索引擎'}
                ]
            }
        ]
    };

    // 为echarts对象加载数据
    myChart.setOption(option);

</script>
</body>
</html>
```

**Comment by hpyou** [comment]
@Ovilia 在Angular中有个变更检查机制，会在每个异步操作和事件触发后检查组件树。在echart中如果不停的触发Animation Frame，就会导致Angular不停的检查组件树。如果组件树很庞大，就会占用很多cpu。

Angular每次执行变更检查，会在组件中执行`ngDoCheck`钩子：
![image](https://user-images.githubusercontent.com/15992591/32871021-ac1417b0-cab9-11e7-83a9-82c23d0845ad.png)

在控制台中可以看到不停的打印：
![image](https://user-images.githubusercontent.com/15992591/32871136-4c131c70-caba-11e7-9774-a60a8322a7e2.png)

**Comment by hpyou** [comment]
@Ovilia Hi~, my friend
我也研究了`requestAnimationFrame`的相关问题。`requestAnimationFrame`相对于`setTimeout`是不一样的，不管执行多少`requestAnimationFrame`，网页的`AnimationFrame`事件永远只会有一个，也就是不管有多少张图，页面的cpu占用只会有1、2个点，这对性能的影响可以忽略不计的。
我们这边也用了一个方法，将echarts运行到了`Angular Zone`之外，`AnimationFrame`触发变更检查的问题得到了解决。
谢谢，麻烦了。

**Comment by rdkmaster** [comment]
这个问题是另一个典型的angular的change detection机制与传统前端库的冲突例子，建议echart可以将这个解决方法放到你们的faq里，让在angular中使用echart的其他同学不掉这个坑。
类似的问题[Jigsaw](https://github.com/rdkmaster/jigsaw)已经碰到过个了

**Comment by Ovilia** [comment]
@rdkmaster 谢谢建议

**Comment by liwenda122** [comment]
@rdkmaster 扯，还典型例子

**Comment by ranxiangfu** [comment]
@hpyou @Ovilia 我遇到的问题和题主的是一样的，通过runOutsideAngular是可以让AnimationFrame避开Angular的脏检查，但是当切换到其他页面的时候，上一个页面的requestAnimationFrame还是一直在执行。

- 验证方式：

首先打开有图表的某个页面，通过ngDoCheck()可以发现requestAnimationFrame触发了脏检查：控制台一直在打印。当我切换到一个很简单的页面（没有任何动画和图表），却发现ngDoCheck()依然被一直触发，通过内存分析也可以看到requestAnimationFrame在一直执行，我觉得这是有问题的。
而且当我某个页面绘制的echarts图表有一个比较复杂的动画时，只要打开过这个页面，访问整个整个项目的任何页面都变得CPU特别高，因为requestAnimationFrame一直在执行。

我觉得这是有问题的，requestAnimationFrame不应该被一直执行。

- 我的项目环境是Angular5.0和echarts3.8.5

**Comment by yy7054wyq5** [comment]
@hpyou 你好，有个问题想和你交流一下，希望你有空的时候回复一下。请问你将echart置于zone之外后，那生成的图表是不受zone监控的。那么仅仅是展示的话应该是没问题的。若是有数据交互的话，那不是很麻烦了？

**Comment by hpyou** [comment]
@yy7054wyq5 有数据交互，用zone.run放到zone里面跑，确保echarts.init在zone之外就行

**Comment by yy7054wyq5** [comment]
@hpyou 谢谢解惑。

**Comment by rickyscoder** [comment]
在没有任何操作的情况下无限调用requestAnimationFrame是出于什么原因。。。

**Comment by zhangying2345** [comment]
用angular初始化echarts时需要放到监测zone外面：
`
this.ngZone.runOutsideAngular(() => {
      echarts.init(nativeElement);
})
`

**Comment by new08** [comment]
我在使用 this.ngZone.runOutsideAngular(() => { echarts.init(nativeElement); }) 后，在 Performance 火焰图里看还是由 AnimationFrame Fired -> zone.js -> (zrender) step。    
但如果在 zone.js 加载前，设置标志 __zone_symbol__requestAnimationFrame = true ，就不会有 zone.js 了。[看这个](https://github.com/angular/angular/issues/8804#issuecomment-439694783)
