### ISSUE TITLE
lines设置trailLength:0.5在svg模式下没有特效尾迹

### ISSUE THREAD

**Issue by jackfxq** [ecomfe/echarts#7070]
### One-line summary [问题简述]

lines设置trailLength:0.5在svg模式下没有特效尾迹，在canvas模式下有特效尾迹，是还没支持吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.3
+ Browser version [浏览器类型和版本]:chrome62
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
SVG 不支持尾迹效果
