### ISSUE TITLE
当前官方api错误 series-tree.orient

### ISSUE THREAD

**Issue by xiaoyangkunbao** [ecomfe/echarts#7071]
### One-line summary [问题简述]

官方的api有点问题
http://echarts.baidu.com/option.html#series-tree.orient
series-tree.orient 这个配置是一个string
下面又把它当成一个object 底下还有4个配置项 
测试了下应该是平级的配置请修正

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by deqingli** [comment]
![image](https://user-images.githubusercontent.com/13548221/37086508-b02bc3fe-2232-11e8-9f05-d8004f6ddc5d.png)
 请问下这段话 --- "下面又把它当成一个object 底下还有4个配置项" 是什么意思？
文档中的写法就是一个 string，有两个值 “horizontal” 和 “vertical”
