### ISSUE TITLE
漏斗图能不能映射宽度的同时可以映射高度？

### ISSUE THREAD

**Issue by sdtazhanghe** [ecomfe/echarts#7076]
![image](https://user-images.githubusercontent.com/28133347/33015155-aaeb08a8-ce24-11e7-9eeb-36ef34485f52.png)
现在的漏斗图只能映射每一层的宽度，能不能多加一个高度的映射。这个需求还是挺多的。
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
下一个版本支持以这样的形式设置高度：

```
data:[
    {value:60, name:'访问'},
    {value:40, name:'咨询'},
    {value:20, name:'订单'},
    {value:80, name:'点击', itemStyle: {
        normal: {
            height: '10%'
        }
    }},
    {value:100, name:'展现', itemStyle: {
        normal: {
            height: '30%'
        }
    }}
]
```

高度可以是百分比或者像素值，不指定的数据将根据默认值分配高度（按数据项个数平均分配），但是需要注意保证高度和是 100%。

**Comment by sdtazhanghe** [comment]
3.8.5支持还是更后的版本？

**Comment by Ovilia** [comment]
下一次版本就支持

**Comment by bin9003** [comment]
现在虽然支持可以设置高度了 ， 但是三角形变形了！

**Comment by bin9003** [comment]
我想用 漏斗图 但是可以设置高度但是三角形变形了， 怎样去设置呢？

**Comment by bin9003** [comment]
谢谢您的回复， 我想要的是金字塔效果，现在已经找到其它的了 https://www.hcharts.cn/demo/highcharts/pyramid
