### ISSUE TITLE
折线图-多个series-tooltip.formatter设置

### ISSUE THREAD

**Issue by fuchao2012** [ecomfe/echarts#7081]
### One-line summary [问题简述]

折线图中，两个以上series，添加 legend，tooltip.formatter后，正常显示没问题，勾选一掉其中一个legend后，被勾选的legend formater 字符串仍然存在。

关键配置在最后。

取消掉legend `数据1`只显示  `数据2`的情况下，tooltip显示为

```
Time:  13:00
{b}: {a0}: {c0}  MB 
数据2:  2 MB
```

> 实际业务中，内存单位和数据均为后台接口获得，此处改为实际字符串和数据

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  "echarts": "^3.8.5",
+ Browser version [浏览器类型和版本]: Google Chrome | 62.0.3202.94 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: Node: 8.2.0 & os: darwin x64 & Angular 4.1.0

### Expected behavior [期望结果]

期望，在取消掉 `数据1` 的情况下，tooltip.formatter字符串也不显示，如下

```js
Time:  13:00
数据2:  2 MB
```

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: '内存信息'
    },
    tooltip: {
        trigger: 'axis',
        formatter: 'Time: {b}<br />{a0}: {c0}  MB <br /> {a1} :{c1} MB' 
    },
    legend: {
        data: ['数据1','数据2']
    },
    xAxis: {
        type: 'category',
        data: ['11:00','12:00','13:00','14:00','15:00','16:00','17:00']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name: '数据1',
            type: 'line',
            data: [1,2,3,4,5,6,7]
        },
        {
            name: '数据2',
            type: 'line',
            data: [7,9,2,1,1,2,3]
        }
    ]
}
```

### Other comments [其他信息]

线上实例木有，截个图看看：

![image](https://user-images.githubusercontent.com/5637185/33057596-ad570630-cec6-11e7-8d2a-f5061b36c306.png)

**Comment by fuchao2012** [comment]
自问自答，多有打扰

```
tooltip:{
    trigger: 'axis',
    formatter: function(params){
            var res = 'Time ' + params[0].name + ':<br/>';
            for (var i = 0, l = params.length; i < l; i++) {
                res += (i===0?'':'<br />')+params[i].seriesName + ' : ' + params[i].value +'MB';    
            }
            return res;
    }
}
```
欢迎讨论

**Comment by bingtanghulu** [comment]
我也发现了这个问题，暂时没找到解决的方法
