### ISSUE TITLE
geo3D有监听缩放的事件么

### ISSUE THREAD

**Issue by Lin-Van** [ecomfe/echarts#7089]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
有 `geo3dcamerachanged` 事件

**Comment by Lin-Van** [comment]
@pissang 谢谢 今早自己看源码发现了
