### ISSUE TITLE
line型图的areaStyle的颜色渐变问题

### ISSUE THREAD

**Issue by git-stf-01** [ecomfe/echarts#7096]
### 颜色渐变问题 [问题简述]

当设置两个Y轴后，两个Y轴分别设置min和max后，渐变不是从min开始，而是从0开始。
如图所示（此时min=0，max=301）：
![t1](https://user-images.githubusercontent.com/30710495/33156805-3c1559e0-d038-11e7-8d65-ebe188dd7a25.png)

设置Y轴后（min=300，max=301）：
不知道为什么上传不了。。将下面option运行，就是图像。。。

### V-最新版 & windows7 [版本及环境]
+ 最新版 [ECharts 版本]:
+ Chrome  62.0.3202.94 [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

###我想要 [期望结果]
在设置y轴后（min=300，max=301），也能有渐变效果，渐变是从line开始到x轴（也就是y=300）终止。

### ECharts option [ECharts配置项]
```js
option = {
           grid: [{
                left: '10%',
                right: '10%',
                top: '5%',
                height: '60%'
            }],
            xAxis: [{
                type: 'category',
                data: [1, 2, 3, 4, 5, 6, 7, 8, 9],
                splitLine: {
                    show: true,
                },
            }],
            yAxis: [{
                type: 'value',
                scale: true,
                position: 'left',
                min: 300,
                max: 301,
                splitLine: {
                    show: true,
                },
            }, {
                type: 'value',
                scale: true,
                min: -0.2,
                max: 0.2,
                position: 'right',
                splitLine: {
                    show: false,
                },
                axisLabel: {
                    formatter: '{value}%',
                },
            }],
            axisPointer: {
                link: {
                    xAxisIndex: 'all'
                },
                label: {
                    backgroundColor: '#777',
                }
            },
            series: [{
                type: 'line',
                xAxisIndex: 0,
                yAxisIndex: 0,
                lineStyle: {
                    normal: {
                        color: '#136AA1',
                        width: 1
                    }
                },
                areaStyle: {
                    normal: {
                        color: {
                            type: 'linear',
                            x0: 0,
                            y0: 0,
                            x2: 0,
                            y2: 1,
                            colorStops: [{
                                offset: 0,
                                color: 'green',
                            }, {
                                offset: 1,
                                color: 'blue',
                            }],
                            globalCoord: false
                        },
                    }
                },
                data: [301, 300, 300.8, 300.7, 300.5, 300.6, 301, 300.8, 300.9],
                smooth: true,
                showSymbol: false,
                symbolSize: 1,
            }]
}
```

**Comment by git-stf-01** [comment]
上面的现象必须是双y轴才会有，单y轴就会是正常的渐变。。

**Comment by git-stf-01** [comment]
这是正常的渐变，而且y轴（min=300，max=301），但是这是单Y轴。只有双Y轴时候渐变才会从0开始
![sdf](https://user-images.githubusercontent.com/30710495/33157235-8c40cdd4-d03b-11e7-8f6e-a971693c7df1.jpg)

**Comment by git-stf-01** [comment]
我又有新发现：发现确实是第二个Y轴影响的。但是也是有条件的：当第二个Y轴的（min，max）之间包含0时候才会导致渐变失效。当第二个Y轴的min和max都是正值或者都是负值，这个时候是不会影响x轴的位置的。因此并不会影响渐变。。。
总之，渐变出错是因为第二个Y轴影响了x轴导致的。

**Comment by git-stf-01** [comment]
终于解决了。好开心。。。。。庆祝一波！

**Comment by Ovilia** [comment]
所以这是 bug 吗？

**Comment by git-stf-01** [comment]
不清楚啊。。。应该算是bug吧。。。
应该是写渐变的源码里：渐变是从折线的纵坐标开始，然后到x轴结束。。。
但是其实渐变应该是：从折线的纵坐标开始，然后到y轴的最小值结束。。（因为当有两个Y轴时，x轴可能分不清该和那个Y轴连起来）这样就不会有问题了。。。

**Comment by git-stf-01** [comment]
好像没说解决办法啊，不好意思，太开心了》》》
     当出现双Y轴时，因为默认的xaxis中有一个默认的配置项是:axisLine: {onZero: true,}，
因此，当第二个Y轴出现0值时，x轴会自动与第二个关联。
     此时，第一个Y轴找不到x轴，但是又因为设置了min和max，第一个Y轴中的渐变就是max-0，
所以会出现问题(我想渐变是从max-min)。
    最终解决办法是：xaxis中的配置项：axisLine:{onZero:false}，强制x轴位于坐标系最底下。。。
========================
（逃。。。。。）

**Comment by git-stf-01** [comment]
好像没说解决办法啊，不好意思，太开心了》》》
当出现双Y轴时，因为默认的xaxis中有一个默认的配置项是:axisLine: {onZero: true,}，
因此，当第二个Y轴出现0值时，x轴会自动与第二个关联。
此时，第一个Y轴找不到x轴，但是又因为设置了min和max，第一个Y轴中的渐变就是max-0，
所以会出现问题(我想渐变是从max-min)。
最终解决办法是：xaxis中的配置项：axisLine:{onZero:false}，强制x轴位于坐标系最底下。。。
------------------------------------------
（逃。。。。。）

**Comment by git-stf-01** [comment]
好像没说解决办法啊，不好意思，太开心了》》》
当出现双Y轴时，因为默认的xaxis中有一个默认的配置项是:axisLine: {onZero: true,}，
因此，当第二个Y轴出现0值时，x轴会自动与第二个关联。
此时，第一个Y轴找不到x轴，但是又因为设置了min和max，第一个Y轴中的渐变就是max-0，
所以会出现问题(我想渐变是从max-min)。
最终解决办法是：xaxis中的配置项：axisLine:{onZero:false}，强制x轴位于坐标系最底下。。。

////////////////////////////////////////////
（逃。。。。。）
