### ISSUE TITLE
ie8浏览器的问题！

### ISSUE THREAD

**Issue by Okswwen** [ecomfe/echarts#7100]
### One-line summary [问题简述]
在IE8浏览器下，使用dist/echarts.min.js文件,折线图、饼图等无法显示，IE9以上正常，同时使用未压缩版(dist/echarts.js)的也可以正常展示。其他浏览器正常，报错信息：SCRIPT1028: 缺少标识符、字符串或数字

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新 3.8.5
+ Browser version [浏览器类型和版本]:IE8
+ OS Version [操作系统类型和版本]: Win 

### Expected behaviour [期望结果]
在IE8中，可以正常实现图形！就如同使用（echarts.js【未压缩版】）一样！

### ECharts option [ECharts配置项]

```javascript
option = {
无
}

```

**Comment by 100pah** [comment]
Fixed on v4.0.0
