### ISSUE TITLE
echarts中怎么阻止默认绑定的鼠标单击事件?

### ISSUE THREAD

**Issue by gaoshijun1993** [ecomfe/echarts#7107]
### echarts中怎么阻止默认绑定的鼠标单击事件?

在用echarts做树形图的时候,树形图的每个节点都有默认点击事件,当我为每个节点添加了双击事件后,双击鼠标会触发两次点击事件,请问如何才能阻止双击的时候触发单击事件呢?

**Comment by deqingli** [comment]
请问下，你是想把默认的单击事件关了；还是想保留单击事件，但是双击的时候不触发；如果是前者 echarts 树图里面有个开关 expandAndCollapse ，把它关了试试。

**Comment by gaoshijun1993** [comment]
我是想保留单击事件，但是双击的时候不触发,请问目前有实现的方法吗?

**Comment by deqingli** [comment]
好的，谢谢反馈，我这边抽时间看下。

**Comment by deqingli** [comment]
@gaoshijun1993 我这边刚试了下，任意一个 DOM 节点同时绑定了单双击事件，双击时都会触发两次单击事件。我能问下你们的原始需求是什么么？也就是你们的双击交互是用来干嘛的

**Comment by gaoshijun1993** [comment]
我们是想单击折叠/展开节点,双击弹出一个面板,面板上显示该节点的详细信息和相关操作

**Comment by gaoshijun1993** [comment]
@deqingli 还有就是请问可不可以增加一个展开所有节点的配置项?

**Comment by deqingli** [comment]
@gaoshijun1993  展开所有节点的配置项是 initialTreeDepth 这个：http://echarts.baidu.com/option.html#series-tree.initialTreeDepth , 你把值设为 -1 就行了

**Comment by deqingli** [comment]
@gaoshijun1993 另外，显示节点的详细信息和相关操作这个， 你可以尝试下 tooltip formatter .

**Comment by gaoshijun1993** [comment]
@deqingli 非常感谢~

**Comment by deqingli** [comment]
不客气，如果没什么问题了，我就把 issue 关了哈

**Comment by gaoshijun1993** [comment]
@deqingli 请问有没有api可以添加或者删除节点的?

**Comment by R1310328554** [comment]
对于已经展开的节点，我希望再次点击不要收拢， 试过很多方式都是行不通的， expandAndCollapse: false 也是不行的，params.event.stop(); 也是不行的。 谁可以看看怎么回事吗？   现在情况是， 已经展开的节点，点击之后会快速的收拢然后展开， 感觉很奇怪哦。
