### ISSUE TITLE
svg渲染下，线性过度颜色跟个鬼一样

### ISSUE THREAD

**Issue by aaaLf** [ecomfe/echarts#7113]
如题

**Comment by pissang** [comment]
有截图和可以复现的代码么？

**Comment by aaaLf** [comment]
发现是代码里包含超过1个svg初始化`echarts.init(this.dom, null, {renderer: 'svg'})`的时候，颜色的线性过度就开始出现问题

**Comment by aaaLf** [comment]
1个使用svg渲染
![image](https://user-images.githubusercontent.com/19581648/33253951-3f851fec-d381-11e7-8343-589e8b47d79c.png)

**Comment by aaaLf** [comment]
2个使用svg，红框圈出的
![image](https://user-images.githubusercontent.com/19581648/33253997-8a4dc632-d381-11e7-96ba-00463f6efecd.png)

**Comment by aaaLf** [comment]
全部使用svg，已经完全乱了，感觉是svg引擎拉不起？？
![image](https://user-images.githubusercontent.com/19581648/33254029-c3e06a3a-d381-11e7-9ac8-40a69f499371.png)

**Comment by Ovilia** [comment]
4.0 版本已修复
