### ISSUE TITLE
legend.textStyle.lineHeight 设置无效

### ISSUE THREAD

**Issue by Erimus-Koo** [ecomfe/echarts#7117]
### One-line summary [问题简述]

    legend: [{
        data: legendData,
        bottom: 10,
        selected: selectedData,
        textStyle: {
            color: '#BBB',
            fontWeight:'bold',
            fontSize: 12,
            lineHeight: 100,
        },
    }, ], //图例

如上设置，lineHeight数字设置之后未生效。
PS：同级的其他设置都有效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.4
+ Browser version [浏览器类型和版本]: Chrome&mobile safari
+ OS Version [操作系统类型和版本]: Win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Erimus-Koo** [comment]
试了半天，加了背景色，发现这里行高是生效的。文字部分的行高有变化。  
但是整体的高度（icon+text）是没有变化的。  

然后解决方案是这样的：  

legend项目间的高度差，用参数itemGap控制，这个相当于legend下单个项目的margin，包括横竖。行高也是用这个调整。另一个影响高度的因素是字体号。

然后，调整icon。用itemWidth和itemHeight就可以。

调整文字和icon的间距，用textStyle.padding，这里可以用数组，同css。这样就可以用负值缩小icon和文字的间距，并且用右边padding来控制项目间的横向距离。

lineHeight仅仅影响背景色的范围。且一定要有rich才生效，可以为空。

结合起来就控制legend的大部分细节的。

**Comment by zhongyufan** [comment]
这里一定要设置`backgroundColor:'transparent'`才能让`width、padding`等生效
