### ISSUE TITLE
两个相同的图表，其中一个任何操作行为，另一个能同步呈现视觉效果吗

### ISSUE THREAD

**Issue by saymy** [ecomfe/echarts#7123]
### One-line summary [问题简述]
两个相同的图表，其中一个任何操作行为，另一个能同步呈现视觉效果吗？比如其中一个点击了，或鼠标经过了，视觉变化时，另一个图表能同步变化吗？用什么方法？
"视觉映射组件“？

### Version & Environment [版本及环境]
+ ECharts version [3.6.2]:
+ Browser version [IE11]:
+ OS Version [WINDOWS10]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以使用 `echarts.connect` 方法联动两个图表实例，见 http://echarts.baidu.com/api.html#echarts.connect

**Comment by saymy** [comment]
好的，谢谢。
