### ISSUE TITLE
图例过多高度自适应问题

### ISSUE THREAD

**Issue by qinshenghechu** [ecomfe/echarts#7133]
### One-line summary [问题简述]
我在用2.x的时候，由于图例是基于数据的，动态的，无法预知有多少图例，每个图例文案多长也无法预知，所以会出现图例覆盖图的问题，后来我自己通过赚取canvas的文字计算高度来实现的自适应，我觉得这个问题大家都会出现，如果组件能够提供参数、内部实现高度自适应更优雅一些。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]: 62.0.3202.94（64 位）
+ OS Version [操作系统类型和版本]:Mac OS 10.10.5 

### Expected behaviour [期望结果]
官方组件提供参数、支持高度自适应

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以考虑给图例加上滚动 http://www.echartsjs.com/gallery/editor.html?c=pie-legend

**Comment by qinshenghechu** [comment]
@pissang 多谢，完美解决~

**Comment by qinshenghechu** [comment]
@pissang 你好，legend添加了scoll后分页有点问题，最后一页的临界点计算的页数不对，我的一共有7页。但是显示1/6。但是点击到第6页还是可以点击到第7页的。

**Comment by Xixi20160512** [comment]
加滚动 测试提bug怎么办 哈哈
