### ISSUE TITLE
文档对tree图的描述有歧义

### ISSUE THREAD

**Issue by qzttt** [ecomfe/echarts#7138]
### One-line summary [问题简述]
文档对tree的描述的有问题
orient 在文档上来看是一个object，但是看解释又像是一个string，
请检查一下看看，谢谢！
http://echarts.baidu.com/option.html#series-tree.orient

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image 32](https://user-images.githubusercontent.com/5271315/33307473-92d00484-d451-11e7-8eb5-7234fb045a1e.png)

**Comment by pissang** [comment]
谢谢反馈，这里是文档的一个错误，应该是一个 string，symbol 和它是平级的
