### ISSUE TITLE
官方提供下载的ECharts GL 1.0.0-beta有错

### ISSUE THREAD

**Issue by ljxtest** [ecomfe/echarts#7145]
### One-line summary [问题简述]
在官方下载echart-gl运行报错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新版本
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

parseGeoJSon这个方法在echarts里面是小写的啊，直接久报错了。
![image](https://user-images.githubusercontent.com/25787395/33354493-28e85074-d4ee-11e7-9517-c48dff890b89.png)

**Comment by pissang** [comment]
最新版本的 ECharts GL 修复了这个问题 https://github.com/ecomfe/echarts-gl/releases/tag/1.0.0-beta.6
