### ISSUE TITLE
折线图  鼠标滑动时不显示数值。

### ISSUE THREAD

**Issue by xcmg** [ecomfe/echarts#7151]
目前原生的效果为：车辆状态：100；
![qq 20171130090629](https://user-images.githubusercontent.com/16689548/33407826-1796b49e-d5ae-11e7-8797-b483e643cb9e.jpg)

我想根据这个100值来做过滤，不显示数值，而显示 车辆状态：行驶。   100对应行驶,101对应加速...
如何处理？

**Comment by pissang** [comment]
可以设置 `tooltip.formatter`

**Comment by xcmg** [comment]
@pissang Ｉｔ　ｉｓ　ｃｏｏｌ．
