### ISSUE TITLE
折线图，area面积区域填充色的时候，只填充到0范围内，有解决方案可以填充到y轴最底部吗？

### ISSUE THREAD

**Issue by sunlandong** [ecomfe/echarts#7152]
### One-line summary [问题简述]

折线图，area面积区域填充色的时候，只填充到0范围内，有解决方案可以填充到y轴最底部吗？

### Version & Environment [版本及环境]
+ ECharts version [3.0以上]:
+ Browser version [谷歌]:
+ OS Version [window7]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by sunlandong** [comment]
提问

**Comment by pissang** [comment]
xAxis 的 `axisLine.onZero` 设成 `false`

**Comment by sunlandong** [comment]
就是实现chartsjs里面fill的功能，
![image](https://user-images.githubusercontent.com/22371767/33409554-09f57ae2-d5b7-11e7-96b1-b8a3dbec7e3a.png)
可以通过设置设置填充区域

**Comment by sunlandong** [comment]
@pissang  
配置如下`const xFont = {
            value: '', textStyle: {
                color: '#ffffff'
            }
        }
        const xfdisFont = {
            value: '2017-09-11', textStyle: {
                align: 'left'
            }
        }
        const xldisFont = {
            value: '至今', textStyle: {
                align: 'right'
            }
        }
        echarts.init(document.getElementById('profitLine')).setOption({
            grid: {
                left: 0,
                right: 0,
                bottom: 0,
                containLabel: true
            },
            xAxis: [
                {
                    type: 'category',
                    axisLabel: {
                        fontFamily: ' PingFangSC-Regular',
                        fontSize: 24,
                        color: '#999999',
                        margin: 14
                    },
                    axisLine: {
                        show: false
                    },
                    axisTick: {
                        show: false,
                    },
                    boundaryGap: false,
                    data: [xfdisFont, xFont, xFont, xFont, xFont, xFont, xldisFont]
                }
            ],
            yAxis: [
                {
                    type: 'value',
                    axisLabel: {
                        fontFamily: ' PingFangSC-Regular',
                        fontSize: 22,
                        color: '#999999',
                        lineHeight: 24,
                        margin: 14,
                        formatter: '{value}%'
                    },
                    axisLine: {
                        show: false,
                        onZero:false
                    },
                    axisTick: {
                        show: false,
                    }

                }
            ],
            series: [
                {
                    name: '策略指数',
                    type: 'line',
                    stack: '总量',
                    lineStyle: {
                        normal: {
                            color: '#ff5a1c',
                            width: 4,

                        }
                    },
                    areaStyle: {
                        normal: {
                            color: '#ffebe2'
                        }
                    },
                    data: [-2.1, 1, 3, -4, 3, 4, 8]
                },
                {
                    name: '沪深300指数',
                    type: 'line',
                    stack: '总量',
                    lineStyle: {
                        normal: {
                            color: '#79a1da',
                            width: 4,

                        }
                    },
                    areaStyle: {
                        normal: {
                            color: '#fff'
                        }
                    },
                    data: [-9, -5, 2, 5, 6, 4, 7]
                }
            ]
        });`

![image](https://user-images.githubusercontent.com/22371767/33409836-5b8e7600-d5b8-11e7-9efe-eed8ad02221b.png)
效果还是这样，是配置有什么地方出错了吗？

**Comment by pissang** [comment]
设置 xAxis 的，不是 yAxis 的，相当于不要把 x 轴的 axisLine 对其到 y 轴的 0 刻度上

**Comment by sunlandong** [comment]
@pissang 嗯嗯，明白思路了，不过已经设置xAxis.axisLine.onZero依然没有生效，配置还是刚刚的配置，就是把onZero设置到了x轴

**Comment by pissang** [comment]
@sunlandong 咦好像是有这个问题，我们看看

**Comment by sunlandong** [comment]
好的，感谢解答！！

**Comment by sunlandong** [comment]
@pissang 目前这个版本，有什么应急方案可以解决吗？

**Comment by pissang** [comment]
可能只能修改数据，加上一个 offset 让最小值为 0 然后配合 formatter 实现了

**Comment by Ovilia** [comment]
已修复，目前可以通过设置 `areaStyle.origin` 修改起始位置，可选值包括：
- `'auto'`（默认值）表示从坐标轴原点开始（如果坐标轴原点不在图中，则相应地取最大或最小值，也就是之前 ECharts 的行为）；
- `'start'` 表示从坐标轴底部开始（非 `inverse` 情况是最小值）；
- `'end'` 表示从坐标轴顶部开始（非 `inverse` 情况是最大值）。

**Comment by sunlandong** [comment]
@pissang @Ovilia 感谢感谢！！
