### ISSUE TITLE
背景图的相对路径是如何引用的？

### ISSUE THREAD

**Issue by Zhouxingzu** [ecomfe/echarts#7156]
### One-line summary [问题简述]
背景图的相对路径是如何引用的？我怎么书写好像都不对。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.7.1
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:Windows

### Expected behaviour [期望结果]
series中的背景图希望使用相对路径的图片

### ECharts option [ECharts配置项]

```javascript
option = {
    series : 
    [
        {
            name: 'test',
            type: 'scatter',
            coordinateSystem: 'geo',
            symbol: 'image://./img/pop.png',
        }
    ]
}

```

**Comment by pissang** [comment]
这样就可以
