### ISSUE TITLE
希望柱状图支持最小宽度

### ISSUE THREAD

**Issue by qinshenghechu** [ecomfe/echarts#7163]
### One-line summary [问题简述]
柱状图数据很多的情况下自适应宽度导致很小，肉眼不可见，看了文档支持barMaxWidth可以控制最大宽度，barWidth支持固定宽度，但是又想要自适应且不能小于多少目前无法实现。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]:Chrome  62.0.3202.94
+ OS Version [操作系统类型和版本]:Mac OS 10.10.5

### Expected behaviour [期望结果]
支持barMinWidth，采用自适应的情况下支持最小宽度设置

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
最小宽度会导致柱子重叠？

**Comment by duxiaofeng-github** [comment]
@pissang 左右拖动？

**Comment by duxiaofeng-github** [comment]
我现在数据可能有几千条柱状图，不能缩放很蛋疼。

**Comment by maidoudeniuniu** [comment]
有一种情况，默认是barWidth是固定值10的，然后突出重点，其中有一个barMaxWidth:20的，这个业务场景目前支持不
