### ISSUE TITLE
求图：沧州.geojson

### ISSUE THREAD

**Issue by chfw** [ecomfe/echarts#7166]
有没有人已下载沧州.geojson 地图? 能与我和大家分享么。

现在echarts-china-cities-js漏了大沧州。https://github.com/chfw/echarts-china-cities-js/issues/1

谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by AggerChen** [comment]
{"type": "FeatureCollection", "features": [{"type":"Feature","properties":{"name":"泊头市"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.652823515625,38.219702375],[116.662081328125,38.2077053046875],[116.71478640625,38.18698753125],[116.741832304688,38.1909841132813],[116.747345,38.1838430000001],[116.74267703125,38.1770839667969],[116.695094023438,38.1460964179688],[116.649176054688,38.1289150214844],[116.61970828125,38.1085707832031],[116.6601965625,38.0934206367188],[116.663746367188,38.0775966621094],[116.643013945313,38.0475722480469],[116.632345,38.0499636054688],[116.622345,38.0477223945313],[116.59435671875,38.0539968085938],[116.583013945313,38.0375722480469],[116.5526184375,38.0443862128907],[116.547345,38.0238430000001],[116.51595828125,38.0171376777344],[116.482345,38.0191408515625],[116.472345,38.0185451484376],[116.46209109375,38.0191555],[116.45255984375,38.0084865546876],[116.3768371875,38.020005109375],[116.337564726563,38.0176638007813],[116.30259890625,37.9785305000001],[116.292120390625,37.9791542792969],[116.272628203125,37.9685622382813],[116.227154570313,37.9545204902344],[116.172174101563,37.9692458320313],[116.161539335938,37.9573464179688],[116.163804960938,37.9193691230469],[116.087345,37.9138430000001],[116.104093046875,37.9391847968751],[116.09142703125,37.9479274726563],[116.07326296875,37.9797585273438],[116.057345,37.9838430000001],[116.049893828125,37.9988283515626],[116.054976835938,38.0092348457032],[116.038585234375,38.0298720527344],[116.068116484375,38.03839378125],[116.050704375,38.0472023750001],[116.047345,38.0638430000001],[116.062808867188,38.0683803535156],[116.100616484375,38.0825868964844],[116.14275515625,38.0782912421875],[116.163487578125,38.1119106269531],[116.212633085938,38.0981703925781],[116.223604765625,38.1113784003907],[116.265455351563,38.1295290351562],[116.281881132813,38.1493056464844],[116.292896757813,38.158452375],[116.2884778125,38.2017848945313],[116.317891875,38.1849379707031],[116.438741484375,38.2016347480469],[116.477652617188,38.1793495917969],[116.497345,38.2138430000001],[116.51298953125,38.2094863105469],[116.528424101563,38.1894863105469],[116.56298953125,38.1981996894531],[116.581954375,38.2096401191406],[116.592428007813,38.2080922675782],[116.652823515625,38.219702375]]]]}},{"type":"Feature","properties":{"name":"沧县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[117.111846953125,38.4813491035156],[117.078619414063,38.4344838691407],[117.103780546875,38.3893862128907],[117.080738554688,38.3695351386719],[117.0980871875,38.3545864082032],[117.119722929688,38.3294753242187],[117.143551054688,38.318843],[117.141944609375,38.298843],[117.142764921875,38.2886403632813],[117.13185671875,38.2487892890625],[117.137345,38.233843],[117.109874296875,38.2148744941407],[117.1178528125,38.1792653632813],[117.14326296875,38.1697585273438],[117.15142703125,38.1609841132813],[117.12142703125,38.1497585273438],[117.086246367188,38.1268471503907],[117.072198515625,38.1299965644531],[117.025382109375,38.1154860664063],[117.017345,38.1038430000001],[117.002623320313,38.0976601386719],[116.992198515625,38.0999965644532],[116.945245390625,38.0854433417969],[116.906246367188,38.1108388496095],[116.8726184375,38.1032997871094],[116.86326296875,38.1397585273438],[116.834620390625,38.1504738593751],[116.80435671875,38.1436891914063],[116.785694609375,38.1707155585938],[116.771890898438,38.1676210761719],[116.747345,38.1838430000001],[116.741832304688,38.1909841132813],[116.71478640625,38.18698753125],[116.662081328125,38.2077053046875],[116.652823515625,38.219702375],[116.592428007813,38.2080922675782],[116.581954375,38.2096401191406],[116.56298953125,38.1981996894531],[116.528424101563,38.1894863105469],[116.51298953125,38.2094863105469],[116.497345,38.2138430000001],[116.49281375,38.2568679023438],[116.461158476563,38.2676552558594],[116.457345,38.313843],[116.461158476563,38.3300307441406],[116.493531523438,38.3476552558594],[116.511383085938,38.4006996894532],[116.537315703125,38.392622296875],[116.572261992188,38.4209242988282],[116.5959778125,38.4042714667969],[116.617345,38.413843],[116.643170195313,38.4096681953125],[116.66177859375,38.3837050605469],[116.733170195313,38.3980178046876],[116.75216921875,38.4100795722656],[116.782345,38.3976784492188],[116.817345,38.4120619941406],[116.837345,38.4038430000001],[116.78154421875,38.3292739082031],[116.783140898438,38.318452375],[116.771549101563,38.299233625],[116.773160429688,38.2883315253907],[116.760611601563,38.2786452460938],[116.783424101563,38.2693080878906],[116.770621367188,38.2367397285157],[116.77220828125,38.2094863105469],[116.821900664063,38.2496474433594],[116.842711210938,38.2465724921876],[116.847345,38.273843],[116.857345,38.273843],[116.857345,38.283843],[116.874215117188,38.2721938300782],[116.8710559375,38.2580861640626],[116.890714140625,38.2497585273438],[116.93267703125,38.2770839667969],[116.944503203125,38.2942116523438],[116.941221953125,38.308843],[116.947496367188,38.3368325019532],[116.93142703125,38.3479274726563],[116.92326296875,38.3597585273438],[116.90088015625,38.3679274726563],[116.867345,38.353843],[116.861690703125,38.358716046875],[116.887345,38.4038430000001],[116.89166140625,38.4946303535157],[116.938619414063,38.4749062324219],[116.96142703125,38.4897585273438],[117.01326296875,38.5079274726563],[117.02142703125,38.5197585273438],[117.05326296875,38.5279274726562],[117.077345,38.543843],[117.08271609375,38.5292153144532],[117.09197390625,38.4984706855469],[117.111846953125,38.4813491035156]]]]}},{"type":"Feature","properties":{"name":"东光县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.877345,37.843843],[116.842843046875,37.8353688789063],[116.815343046875,37.8415334296875],[116.758053007813,37.8155666328125],[116.74326296875,37.7579274726563],[116.697345,37.733843],[116.689869414063,37.7606935859375],[116.655889921875,37.7556728339844],[116.632345,37.7698744941406],[116.605636015625,37.7537624335938],[116.56298953125,37.7794863105469],[116.496954375,37.7907045722657],[116.467345,37.783843],[116.467345,37.813843],[116.47312625,37.8285512519532],[116.471607695313,37.8388430000001],[116.473082304688,37.848843],[116.471519804688,37.8594130683594],[116.496324492188,37.8695644355469],[116.532003203125,37.915786359375],[116.552877226563,37.9667983222657],[116.557345,38.0238430000001],[116.653077421875,38.0298110175782],[116.672061796875,38.0085622382813],[116.682628203125,37.9991237617188],[116.69435671875,37.9859963203125],[116.823961210938,37.9657997871094],[116.8426575,37.949095685547],[116.84146609375,37.9290956855469],[116.8537903125,37.9180849433594],[116.8520325,37.8885817695313],[116.885714140625,37.8671620917969],[116.877345,37.843843]]]]}},{"type":"Feature","properties":{"name":"海兴县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[117.807764921875,38.2392055488281],[117.791519804688,38.1996681953125],[117.783170195313,38.1680178046876],[117.761217070313,38.1595510078126],[117.765675078125,38.1369826484375],[117.735694609375,38.115493390625],[117.705445585938,38.0732900214844],[117.672340117188,38.0798317695313],[117.612349882813,38.0678542304688],[117.581456328125,38.0739589667969],[117.5507434375,38.0519448066406],[117.55341921875,38.0384096503907],[117.541519804688,38.0196681953125],[117.537345,38.003843],[117.522789335938,37.9948732734375],[117.503531523438,37.9376552558594],[117.497345,37.933843],[117.491676054688,37.942055890625],[117.455650664063,37.93397971875],[117.464136992188,37.9718349433594],[117.40142703125,37.9879274726563],[117.39326296875,38.0097585273438],[117.365235625,38.0202455878906],[117.384283476563,38.0494960761719],[117.35142703125,38.0579274726563],[117.340186796875,38.0742116523438],[117.345225859375,38.0966884589844],[117.317345,38.1038430000001],[117.320704375,38.1204836250001],[117.34287234375,38.1316994453125],[117.347345,38.153843],[117.352896757813,38.1582900214844],[117.361793242188,38.1793959785157],[117.373013945313,38.1984828925782],[117.370582304688,38.218001935547],[117.412345,38.2231960273438],[117.491275664063,38.2133791328126],[117.562183867188,38.2294850898438],[117.577486601563,38.2275820136719],[117.60302859375,38.2383449531251],[117.601085234375,38.2539833808594],[117.615538359375,38.2882900214844],[117.719429960938,38.2745729804688],[117.761793242188,38.2582900214844],[117.787345,38.2538430000001],[117.807764921875,38.2392055488281]]]]}},{"type":"Feature","properties":{"name":"河间市"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.451519804688,38.5764479804688],[116.443170195313,38.5580178046875],[116.423394804688,38.543843],[116.443170195313,38.5296681953126],[116.457393828125,38.4927846503907],[116.5132825,38.4817409492188],[116.55088015625,38.5056093574219],[116.561519804688,38.4780178046875],[116.587345,38.473843],[116.5933996875,38.4608486152344],[116.621612578125,38.4770217109376],[116.639620390625,38.453559796875],[116.620523710938,38.4306642890625],[116.617345,38.413843],[116.5959778125,38.4042714667969],[116.572261992188,38.4209242988282],[116.537315703125,38.392622296875],[116.511383085938,38.4006996894532],[116.493531523438,38.3476552558594],[116.461158476563,38.3300307441406],[116.457345,38.313843],[116.44197390625,38.3184706855469],[116.429522734375,38.3598220039063],[116.392345,38.3568337226563],[116.333961210938,38.3615248847656],[116.318668242188,38.3437734199219],[116.192056914063,38.3794008613282],[116.18271609375,38.3584706855469],[116.17197390625,38.3492153144532],[116.162667265625,38.3384157539063],[116.141510039063,38.3401149726563],[116.102535429688,38.3183693671876],[116.017345,38.3338430000001],[116.021881132813,38.3493056464844],[116.032896757813,38.358452375],[116.030069609375,38.3861440253907],[116.043233671875,38.4091213203125],[116.0132434375,38.4221279121094],[116.033365507813,38.4388430000001],[116.021881132813,38.4483803535156],[116.010621367188,38.474349591797],[115.91713015625,38.4910097480469],[115.932808867188,38.5183803535157],[115.937345,38.533843],[115.928819609375,38.5541469550782],[115.957345,38.573843],[115.973975859375,38.5497585273438],[116.00326296875,38.5579274726563],[116.032623320313,38.5806825996094],[116.041998320313,38.56710471875],[116.069581328125,38.5850673652345],[116.102345,38.5777223945312],[116.112345,38.5799636054688],[116.157867460938,38.5697585273438],[116.173585234375,38.5883107734375],[116.169537382813,38.6063637519532],[116.20142703125,38.6197585273438],[116.23326296875,38.6279274726563],[116.24201296875,38.6406020332032],[116.279097929688,38.6647524238282],[116.317672148438,38.6733998847657],[116.34142703125,38.6579274726563],[116.357345,38.653843],[116.380074492188,38.6124318671876],[116.413170195313,38.5996681953125],[116.421519804688,38.5880178046876],[116.451519804688,38.5764479804688]]]]}},{"type":"Feature","properties":{"name":"黄骅市"},"geometry":{"type":"MultiPolygon","coordinates":[[[[117.887345,38.313843],[117.890767851563,38.3260353828125],[117.899537382813,38.3172658515626],[117.887345,38.313843]]],[[[117.887345,38.313843],[117.883985625,38.307202375],[117.857423125,38.293764875],[117.847345,38.273843],[117.839693632813,38.2604201484375],[117.799693632813,38.2754970527344],[117.787345,38.2538430000001],[117.761793242188,38.2582900214844],[117.719429960938,38.2745729804688],[117.615538359375,38.2882900214844],[117.601085234375,38.2539833808594],[117.60302859375,38.2383449531251],[117.577486601563,38.2275820136719],[117.562183867188,38.2294850898438],[117.491275664063,38.2133791328126],[117.412345,38.2231960273438],[117.370582304688,38.218001935547],[117.373013945313,38.1984828925782],[117.361793242188,38.1793959785157],[117.352896757813,38.1582900214844],[117.347345,38.153843],[117.307642851563,38.1603652167969],[117.292027617188,38.1580568671876],[117.242662382813,38.1796291328125],[117.203487578125,38.1738393378906],[117.192095976563,38.2016664863281],[117.15170046875,38.2181996894532],[117.14298953125,38.2294863105469],[117.137345,38.233843],[117.13185671875,38.2487892890625],[117.142764921875,38.2886403632813],[117.141944609375,38.298843],[117.143551054688,38.318843],[117.119722929688,38.3294753242187],[117.0980871875,38.3545864082032],[117.080738554688,38.3695351386719],[117.103780546875,38.3893862128907],[117.078619414063,38.4344838691407],[117.111846953125,38.4813491035156],[117.09197390625,38.4984706855469],[117.08271609375,38.5292153144532],[117.077345,38.543843],[117.08298953125,38.5481996894531],[117.097345,38.583843],[117.11326296875,38.5879274726563],[117.14267703125,38.6070839667969],[117.147345,38.613843],[117.183170195313,38.6180178046876],[117.220518828125,38.6465407539063],[117.231519804688,38.6180178046876],[117.245186796875,38.6082228828126],[117.235875273438,38.561108625],[117.259386015625,38.5564638496094],[117.29279421875,38.5701918769532],[117.302115507813,38.5571865058594],[117.343170195313,38.5680178046875],[117.357345,38.5877956367188],[117.374132109375,38.5643727851562],[117.393170195313,38.5780178046875],[117.40314578125,38.5919350410157],[117.48187625,38.6158522773438],[117.529386015625,38.6064638496094],[117.547345,38.613843],[117.567896757813,38.5954811835938],[117.622061796875,38.4985622382813],[117.642628203125,38.4691237617188],[117.687784453125,38.3981179023438],[117.735714140625,38.3444777656251],[117.828048125,38.3060732246094],[117.860240507813,38.3235683417969],[117.887345,38.313843]]]]}},{"type":"Feature","properties":{"name":"孟村回族自治县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[117.192095976563,38.2016664863281],[117.203487578125,38.1738393378906],[117.242662382813,38.1796291328125],[117.292027617188,38.1580568671876],[117.307642851563,38.1603652167969],[117.347345,38.153843],[117.34287234375,38.1316994453125],[117.320704375,38.1204836250001],[117.317345,38.1038430000001],[117.291519804688,38.1080178046875],[117.248580351563,38.1210622382813],[117.232345,38.1178554511719],[117.219386015625,38.120415265625],[117.1805871875,38.1054506660157],[117.143526640625,38.0470754218751],[117.171724882813,38.0077321601563],[117.187613554688,38.0108718085938],[117.205943632813,37.95054221875],[117.153780546875,37.9402346015625],[117.123170195313,37.9596681953126],[117.061519804688,37.9680178046875],[117.053170195313,37.9796681953125],[117.027345,37.993843],[117.03312625,38.0085512519531],[117.030865507813,38.0238430000001],[117.03314578125,38.0392726875],[117.011529570313,38.06843284375],[117.017345,38.1038430000001],[117.025382109375,38.1154860664063],[117.072198515625,38.1299965644531],[117.086246367188,38.1268471503907],[117.12142703125,38.1497585273438],[117.15142703125,38.1609841132813],[117.14326296875,38.1697585273438],[117.1178528125,38.1792653632813],[117.109874296875,38.2148744941407],[117.137345,38.233843],[117.14298953125,38.2294863105469],[117.15170046875,38.2181996894532],[117.192095976563,38.2016664863281]]]]}},{"type":"Feature","properties":{"name":"南皮县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.747345,38.1838430000001],[116.771890898438,38.1676210761719],[116.785694609375,38.1707155585938],[116.80435671875,38.1436891914063],[116.834620390625,38.1504738593751],[116.86326296875,38.1397585273438],[116.8726184375,38.1032997871094],[116.906246367188,38.1108388496095],[116.945245390625,38.0854433417969],[116.992198515625,38.0999965644532],[117.002623320313,38.0976601386719],[117.017345,38.1038430000001],[117.011529570313,38.06843284375],[117.03314578125,38.0392726875],[117.030865507813,38.0238430000001],[117.03312625,38.0085512519531],[117.027345,37.993843],[116.99791140625,37.9711244941407],[117.02744265625,37.9483315253906],[117.021607695313,37.9088430000001],[117.024561796875,37.888843],[117.0216028125,37.8688088203126],[117.027345,37.8338430000001],[116.96281375,37.8401894355469],[116.957345,37.8338430000001],[116.947345,37.8338430000001],[116.947345,37.843843],[116.937345,37.843843],[116.877345,37.843843],[116.885714140625,37.8671620917969],[116.8520325,37.8885817695313],[116.8537903125,37.9180849433594],[116.84146609375,37.9290956855469],[116.8426575,37.949095685547],[116.823961210938,37.9657997871094],[116.69435671875,37.9859963203125],[116.682628203125,37.9991237617188],[116.672061796875,38.0085622382813],[116.653077421875,38.0298110175782],[116.557345,38.0238430000001],[116.547345,38.0238430000001],[116.5526184375,38.0443862128907],[116.583013945313,38.0375722480469],[116.59435671875,38.0539968085938],[116.622345,38.0477223945313],[116.632345,38.0499636054688],[116.643013945313,38.0475722480469],[116.663746367188,38.0775966621094],[116.6601965625,38.0934206367188],[116.61970828125,38.1085707832031],[116.649176054688,38.1289150214844],[116.695094023438,38.1460964179688],[116.74267703125,38.1770839667969],[116.747345,38.1838430000001]]]]}},{"type":"Feature","properties":{"name":"青县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.8740246875,38.6829872871094],[116.912628203125,38.6781862617188],[116.946763945313,38.6913075996094],[117.030987578125,38.7017836738282],[117.041793242188,38.6882900214844],[117.054156523438,38.6783901191407],[117.048980742188,38.6367787910157],[117.071793242188,38.6082900214844],[117.082896757813,38.5993959785157],[117.091793242188,38.5882900214844],[117.097345,38.583843],[117.08298953125,38.5481996894531],[117.077345,38.543843],[117.05326296875,38.5279274726562],[117.02142703125,38.5197585273438],[117.01326296875,38.5079274726563],[116.96142703125,38.4897585273438],[116.938619414063,38.4749062324219],[116.89166140625,38.4946303535157],[116.887345,38.4038430000001],[116.855797148438,38.4115920234376],[116.837345,38.4038430000001],[116.817345,38.4120619941406],[116.782345,38.3976784492188],[116.75216921875,38.4100795722656],[116.733170195313,38.3980178046876],[116.66177859375,38.3837050605469],[116.643170195313,38.4096681953125],[116.617345,38.413843],[116.620523710938,38.4306642890625],[116.639620390625,38.453559796875],[116.621612578125,38.4770217109376],[116.5933996875,38.4608486152344],[116.587345,38.473843],[116.59197390625,38.4792153144531],[116.6080871875,38.4930995917969],[116.622667265625,38.5100221992188],[116.643961210938,38.5083107734375],[116.667232695313,38.5353224921876],[116.640347929688,38.5584889960938],[116.6627746875,38.5684963203125],[116.661163359375,38.5885195136719],[116.67271609375,38.5984706855469],[116.68197390625,38.6092153144532],[116.72271609375,38.6184706855469],[116.74197390625,38.6292153144531],[116.77752078125,38.6450771308594],[116.7619153125,38.6585195136719],[116.762745390625,38.6688430000001],[116.761944609375,38.6788430000001],[116.762750273438,38.6888808417969],[116.757345,38.7438430000001],[116.864273710938,38.7393386054688],[116.861085234375,38.7137026191407],[116.8740246875,38.6829872871094]]]]}},{"type":"Feature","properties":{"name":"任丘市"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.197345,38.923843],[116.201881132813,38.8783803535156],[116.24302859375,38.8605361152344],[116.241793242188,38.8484194160157],[116.262808867188,38.8393056464844],[116.271881132813,38.8183803535157],[116.334068632813,38.8091176582031],[116.405455351563,38.7781569648438],[116.421881132813,38.7583803535156],[116.427345,38.7538430000001],[116.423985625,38.717202375],[116.361373320313,38.685805890625],[116.357345,38.653843],[116.34142703125,38.6579274726563],[116.317672148438,38.6733998847657],[116.279097929688,38.6647524238282],[116.24201296875,38.6406020332032],[116.23326296875,38.6279274726563],[116.20142703125,38.6197585273438],[116.169537382813,38.6063637519532],[116.173585234375,38.5883107734375],[116.157867460938,38.5697585273438],[116.112345,38.5799636054688],[116.102345,38.5777223945312],[116.069581328125,38.5850673652345],[116.041998320313,38.56710471875],[116.032623320313,38.5806825996094],[116.00326296875,38.5579274726563],[115.973975859375,38.5497585273438],[115.957345,38.573843],[115.95052859375,38.6283864570313],[115.967803984375,38.6422182441407],[115.951695585938,38.6986257148438],[115.953013945313,38.7092031074219],[115.941612578125,38.7285976386719],[115.947345,38.7538430000001],[115.970787382813,38.7598586250001],[116.003082304688,38.8066347480469],[116.033638945313,38.8180690742188],[116.03119265625,38.828989484375],[116.04349734375,38.868696515625],[116.037686796875,38.8946169257813],[116.083814726563,38.9118764472657],[116.110191679688,38.9059633613282],[116.117345,38.933843],[116.155733671875,38.9432729316407],[116.197345,38.923843]]]]}},{"type":"Feature","properties":{"name":"肃宁县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[115.937345,38.533843],[115.932808867188,38.5183803535157],[115.91713015625,38.4910097480469],[116.010621367188,38.474349591797],[116.021881132813,38.4483803535156],[116.033365507813,38.4388430000001],[116.0132434375,38.4221279121094],[116.043233671875,38.4091213203125],[116.030069609375,38.3861440253907],[116.032896757813,38.358452375],[116.021881132813,38.3493056464844],[116.017345,38.3338430000001],[116.00978640625,38.3240492988281],[115.955220976563,38.3321120429687],[115.874342070313,38.2717458320313],[115.86298953125,38.2994863105469],[115.847345,38.303843],[115.832896757813,38.3393959785156],[115.76259890625,38.3594960761719],[115.751890898438,38.3581642890625],[115.742545195313,38.3698378730469],[115.722589140625,38.3581081367187],[115.697345,38.3638430000001],[115.7060559375,38.3751308417969],[115.725675078125,38.3902724433594],[115.709014921875,38.4474135566406],[115.7286340625,38.4625551582032],[115.74170046875,38.4794863105469],[115.77298953125,38.4881996894532],[115.78170046875,38.5094863105469],[115.817345,38.5238430000001],[115.860094023438,38.5133425117188],[115.873013945313,38.5320558906251],[115.902843046875,38.5253688789063],[115.937345,38.533843]]],[[[115.853922148438,38.5360353828126],[115.857345,38.5238430000001],[115.845152617188,38.5272658515625],[115.853922148438,38.5360353828126]]]]}},{"type":"Feature","properties":{"name":"吴桥县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.56298953125,37.7794863105469],[116.605636015625,37.7537624335938],[116.632345,37.7698744941406],[116.655889921875,37.7556728339844],[116.689869414063,37.7606935859375],[116.697345,37.733843],[116.671793242188,37.7193959785157],[116.662896757813,37.6982900214844],[116.610709257813,37.6330336738281],[116.5601575,37.6023281074219],[116.532896757813,37.5682900214844],[116.516236601563,37.5549489570313],[116.507345,37.543843],[116.444464140625,37.5043508125],[116.428678007813,37.4699648261719],[116.397906523438,37.5044057441407],[116.372515898438,37.5270912910156],[116.362628203125,37.5591237617188],[116.340260039063,37.569389875],[116.327345,37.583843],[116.3335559375,37.6061537910157],[116.365953398438,37.6194130683594],[116.361529570313,37.6493544746094],[116.37298953125,37.6581996894532],[116.38170046875,37.6894863105469],[116.410894804688,37.7288661933594],[116.423160429688,37.7383315253907],[116.421519804688,37.7494130683595],[116.449659453125,37.7609291816407],[116.467345,37.783843],[116.496954375,37.7907045722657],[116.56298953125,37.7794863105469]]]]}},{"type":"Feature","properties":{"name":"献县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.192056914063,38.3794008613282],[116.318668242188,38.3437734199219],[116.333961210938,38.3615248847656],[116.392345,38.3568337226563],[116.429522734375,38.3598220039063],[116.44197390625,38.3184706855469],[116.457345,38.313843],[116.461158476563,38.2676552558594],[116.49281375,38.2568679023438],[116.497345,38.2138430000001],[116.477652617188,38.1793495917969],[116.438741484375,38.2016347480469],[116.317891875,38.1849379707031],[116.2884778125,38.2017848945313],[116.292896757813,38.158452375],[116.281881132813,38.1493056464844],[116.265455351563,38.1295290351562],[116.223604765625,38.1113784003907],[116.212633085938,38.0981703925781],[116.163487578125,38.1119106269531],[116.14275515625,38.0782912421875],[116.100616484375,38.0825868964844],[116.062808867188,38.0683803535156],[116.047345,38.0638430000001],[116.028189726563,38.0936659980469],[116.04298953125,38.1181996894531],[116.043863554688,38.1481996894532],[115.987345,38.1259804511719],[115.932081328125,38.1477053046875],[115.92298953125,38.1594863105469],[115.897345,38.163843],[115.88603640625,38.1698000312501],[115.90037234375,38.2017128730469],[115.861905546875,38.2219765449219],[115.853892851563,38.2603932929688],[115.839464140625,38.267993390625],[115.82541140625,38.2992714667969],[115.847345,38.303843],[115.86298953125,38.2994863105469],[115.874342070313,38.2717458320313],[115.955220976563,38.3321120429687],[116.00978640625,38.3240492988281],[116.017345,38.3338430000001],[116.102535429688,38.3183693671876],[116.141510039063,38.3401149726563],[116.162667265625,38.3384157539063],[116.17197390625,38.3492153144532],[116.18271609375,38.3584706855469],[116.192056914063,38.3794008613282]]]]}},{"type":"Feature","properties":{"name":"新华区"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.857345,38.283843],[116.857345,38.273843],[116.847345,38.273843],[116.847345,38.283843],[116.857345,38.283843]]],[[[116.857345,38.283843],[116.86170046875,38.3194863105469],[116.867345,38.353843],[116.90088015625,38.3679274726563],[116.92326296875,38.3597585273438],[116.93142703125,38.3479274726563],[116.947496367188,38.3368325019532],[116.941221953125,38.308843],[116.944503203125,38.2942116523438],[116.93267703125,38.2770839667969],[116.890714140625,38.2497585273438],[116.8710559375,38.2580861640626],[116.874215117188,38.2721938300782],[116.857345,38.283843]]]]}},{"type":"Feature","properties":{"name":"盐山县"},"geometry":{"type":"MultiPolygon","coordinates":[[[[117.248580351563,38.1210622382813],[117.291519804688,38.1080178046875],[117.317345,38.1038430000001],[117.345225859375,38.0966884589844],[117.340186796875,38.0742116523438],[117.35142703125,38.0579274726563],[117.384283476563,38.0494960761719],[117.365235625,38.0202455878906],[117.39326296875,38.0097585273438],[117.40142703125,37.9879274726563],[117.464136992188,37.9718349433594],[117.455650664063,37.93397971875],[117.491676054688,37.942055890625],[117.497345,37.933843],[117.47922,37.9213295722656],[117.424346953125,37.8398415351563],[117.316046171875,37.8664430976563],[117.307345,37.853843],[117.291881132813,37.8493056464844],[117.262608671875,37.838305890625],[117.207345,37.8439394355469],[117.152345,37.8383339667969],[117.06341921875,37.8473976875],[117.027345,37.8338430000001],[117.0216028125,37.8688088203126],[117.024561796875,37.888843],[117.021607695313,37.9088430000001],[117.02744265625,37.9483315253906],[116.99791140625,37.9711244941407],[117.027345,37.993843],[117.053170195313,37.9796681953125],[117.061519804688,37.9680178046875],[117.123170195313,37.9596681953126],[117.153780546875,37.9402346015625],[117.205943632813,37.95054221875],[117.187613554688,38.0108718085938],[117.171724882813,38.0077321601563],[117.143526640625,38.0470754218751],[117.1805871875,38.1054506660157],[117.219386015625,38.120415265625],[117.232345,38.1178554511719],[117.248580351563,38.1210622382813]]]]}},{"type":"Feature","properties":{"name":"运河区"},"geometry":{"type":"MultiPolygon","coordinates":[[[[116.847345,38.273843],[116.842711210938,38.2465724921876],[116.821900664063,38.2496474433594],[116.77220828125,38.2094863105469],[116.770621367188,38.2367397285157],[116.783424101563,38.2693080878906],[116.760611601563,38.2786452460938],[116.773160429688,38.2883315253907],[116.771549101563,38.299233625],[116.783140898438,38.318452375],[116.78154421875,38.3292739082031],[116.837345,38.4038430000001],[116.855797148438,38.4115920234376],[116.887345,38.4038430000001],[116.861690703125,38.358716046875],[116.867345,38.353843],[116.86170046875,38.3194863105469],[116.857345,38.283843],[116.847345,38.283843],[116.847345,38.273843]]]]}}]}

**Comment by AggerChen** [comment]
河北沧州的 不谢

**Comment by chfw** [comment]
谢谢。赶在2018年来之前给我了。我打算再没有，就在2018年自己描，这下子不需要。省下的时间，可以做pyecharts的地图扩展。

**Comment by chfw** [comment]
<img width="794" alt="screen shot 2017-12-30 at 00 24 19" src="https://user-images.githubusercontent.com/4280312/34450047-747c4212-ecf8-11e7-9bc2-df4c13659d38.png">
