### ISSUE TITLE
echarts地图通过require引入时，中国地图可以显示，指定省无法显示

### ISSUE THREAD

**Issue by jiweixia233** [ecomfe/echarts#7172]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  3.1.7
+ Browser version [浏览器类型和版本]:chrome  62.0.3202.94
+ OS Version [操作系统类型和版本]: windows

### Expected behaviour [期望结果]
///导入echarts 
var echarts = require('echarts'); 
require('echarts/map/js/china.js'); 
require('echarts/map/js/province/guangdong.js'); 

但是，我在地图里面mapType: 'china'是显示中国地图，我改为guangdong就提示说Map  not exists

### ECharts option [ECharts配置项]

```javascript
option = {
   title: {
        show: false
    },
    tooltip: {
        trigger: 'item'
    },
    visualMap: {
        min: 0,
        max: 0,
        left: 'right',
        top: '40%',
        text: ['高', '低'],           // 文本，默认为数值文本
        calculable: true,
        precision: 2,
        inRange: {
            color: ['#DCF0FF', '#68BDFF', '#4593FF', '#1483D9', '#106BB2']
        }
    },
    series: [
        {
            name: '省级地域分布',
            type: 'map',
            mapType: 'guangdong',
            roam: false,
            label: {
                normal: {
                    show: false
                },
                emphasis: {
                    show: false
                }
            },
            selectedMode: 'single',
            itemStyle: {
                emphasis: {
                    areaColor: '#FEAC5B'
                }
            },
            data: []
        }
    ]
}

```

### Other comments [其他信息]

通过webpack安装的echarts3.1.7
![1512238519 1](https://user-images.githubusercontent.com/16102130/33518433-dd775d30-d7cf-11e7-89de-ea1eff2b5f97.jpg)

**Comment by chfw** [comment]
空空如也：https://github.com/ecomfe/echarts/blob/master/map/js/province/guangdong.js，就是为什么广东不显示。
试试这个：https://raw.githubusercontent.com/chfw/jupyter-echarts/master/echarts/guangdong.js

**Comment by jiweixia233** [comment]
已经解决了，mapType的值不是拼音，而是中文，向上面那样引用后，mapType改为‘广东’，即可加载出广东的地图

**Comment by chfw** [comment]
哦 原来如此
