### ISSUE TITLE
在动态展示图表时，如何再添加一条折线

### ISSUE THREAD

**Issue by xiaxiage** [ecomfe/echarts#7179]
### One-line summary [问题简述]
异步加载数据显示一条折线，如何增加一条折线呢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

**Comment by pissang** [comment]
添加一个 series 后再 setOption
