### ISSUE TITLE
求助：Echart制作HTML文件如何导入PPT展示

### ISSUE THREAD

**Issue by ProfBlackMa** [ecomfe/echarts#7180]
### One-line summary [问题简述]
Echart编译的图表，保存为HTML格式，如何在PPT中进行展示？带动画的形式，而不是图片的形式

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.0
+ Browser version [浏览器类型和版本]:Chrome
+ OS Version [操作系统类型和版本]:Windows 10

### Expected behaviour [期望结果]
以Echart编译的HTML文件以带动画的形式在PPT中运行

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
问题跟 ECharts 无关
