### ISSUE TITLE
在线定制下载后的js缺少了graphic方法

### ISSUE THREAD

**Issue by whitetrident** [ecomfe/echarts#7182]
做的是一个类似股票的k线图，我使用官网的在线定制功能，但是下载后缺少了一个graphic方法，导致图表出不来。

**Comment by pissang** [comment]
能否截图看下你报的错误？

**Comment by whitetrident** [comment]
![image](https://user-images.githubusercontent.com/29626161/33546941-6170056c-d91d-11e7-92c3-2bbd91d460d5.png)

**Comment by whitetrident** [comment]
缺少了graphic这个方法，用常用包和完整包倒是有graphic方法，但是完整包大了，常用包没有k线图

**Comment by pissang** [comment]
在线构建下面的 API 选项选上了么？

**Comment by whitetrident** [comment]
勾了

**Comment by pissang** [comment]
@whitetrident 抱歉好像是有这个 bug，你可以先通过声明的方式创建 gradient 对象

```js
color: { 
  type: 'linear',
  x: 0,
  y: 0,
  x2: 0,
  y2: 1,
  colorStops: [{ offset: 0, color: '#474019'}, {offset: 1, color: '#262922' }]
}
```

后面会修复这个问题

**Comment by 100pah** [comment]
Fixed.

**Comment by whitetrident** [comment]
确实修复了，在线定制后有grahpic了，强！
