### ISSUE TITLE
yAxis min: function无效

### ISSUE THREAD

**Issue by PosseWang** [ecomfe/echarts#7187]
### One-line summary [问题简述]

yAxis min:　直接设置值有效 函数无效
min:-2有效
min: function(value) {          // 无效
            return value.min - 20;
          }

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

min: function(value) {          // 无效
            return value.min - 20;
          }
有效

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
echarts 版本是什么？
