### ISSUE TITLE
svg模式下饼图初始化没有动画效果

### ISSUE THREAD

**Issue by jackfxq** [ecomfe/echarts#7188]
### One-line summary [问题简述]

饼图在设置canvas时初始化有动画效果，在svg模式下没有动画效果

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.0
+ Browser version [浏览器类型和版本]:chrom62
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jackfxq** [comment]
而且，如果同时有折线图和饼图的情况下，其初始化动画效果会相互影响

**Comment by jackfxq** [comment]
好像和这个问题[https://github.com/ecomfe/echarts/issues/6989]是一样的

**Comment by Ovilia** [comment]
同 #6989，已修复
