### ISSUE TITLE
Echarts漏斗图如何改变数据但不改变形状大小

### ISSUE THREAD

**Issue by zhangyalins** [ecomfe/echarts#7206]
echarts 雷达图如何修改数值但却不改变形状的图形呢？   
![image](https://user-images.githubusercontent.com/26652910/33662598-4c525332-dac7-11e7-8d78-4017d064a20d.png)

源码：
```js
option = {
    title: {
        text: '漏斗图',
        subtext: '纯属虚构'
    },
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            dataView: {readOnly: false},
            restore: {},
            saveAsImage: {}
        }
    },
    legend: {
        data: ['展现','点击','访问','咨询','订单']
    },
    calculable: true,
    series: [
        {
            name:'漏斗图',
            type:'funnel',
            left: '10%',
            top: 60,
            //x2: 80,
            bottom: 60,
            width: '80%',
            // height: {totalHeight} - y - y2,
            min: 0,
            max: 100,
            minSize: '0%',
            maxSize: '100%',
            sort: 'descending',
            gap: 2,
            label: {
                normal: {
                    show: true,
                    position: 'inside'
                },
                emphasis: {
                    textStyle: {
                        fontSize: 20
                    }
                }
            },
            labelLine: {
            normal   : {
            length   : 10,
            lineStyle: {
            width    : 1,
            type     : 'solid'
                    }
                }
            },
            itemStyle: {
                normal: {
                    borderColor: '#fff',
                    borderWidth: 1
                }
            },
            data: [
                {value: 60, name: '访问'},
                {value: 40, name: '咨询'},
                {value: 20, name: '订单'},
                {value: 80, name: '点击'},
                {value: 100, name: '展现'}
            ]
        }
    ]
};





```

**Comment by pissang** [comment]
没法做到，你可以用填加的数据，然后配合 formatter 显示实际数据

**Comment by Charlie500** [comment]
> echarts 雷达图如何修改数值但却不改变形状的图形呢？ ![image](https://user-images.githubusercontent.com/26652910/33662598-4c525332-dac7-11e7-8d78-4017d064a20d.png)
> 
> 源码：
> 
> ```js
> option = {
>     title: {
>         text: '漏斗图',
>         subtext: '纯属虚构'
>     },
>     tooltip: {
>         trigger: 'item',
>         formatter: "{a} <br/>{b} : {c}%"
>     },
>     toolbox: {
>         feature: {
>             dataView: {readOnly: false},
>             restore: {},
>             saveAsImage: {}
>         }
>     },
>     legend: {
>         data: ['展现','点击','访问','咨询','订单']
>     },
>     calculable: true,
>     series: [
>         {
>             name:'漏斗图',
>             type:'funnel',
>             left: '10%',
>             top: 60,
>             //x2: 80,
>             bottom: 60,
>             width: '80%',
>             // height: {totalHeight} - y - y2,
>             min: 0,
>             max: 100,
>             minSize: '0%',
>             maxSize: '100%',
>             sort: 'descending',
>             gap: 2,
>             label: {
>                 normal: {
>                     show: true,
>                     position: 'inside'
>                 },
>                 emphasis: {
>                     textStyle: {
>                         fontSize: 20
>                     }
>                 }
>             },
>             labelLine: {
>             normal   : {
>             length   : 10,
>             lineStyle: {
>             width    : 1,
>             type     : 'solid'
>                     }
>                 }
>             },
>             itemStyle: {
>                 normal: {
>                     borderColor: '#fff',
>                     borderWidth: 1
>                 }
>             },
>             data: [
>                 {value: 60, name: '访问'},
>                 {value: 40, name: '咨询'},
>                 {value: 20, name: '订单'},
>                 {value: 80, name: '点击'},
>                 {value: 100, name: '展现'}
>             ]
>         }
>     ]
> };
> ```

legend 改变时，保持图形不变你做到了吗
