### ISSUE TITLE
Legend Type 使用 scroll 时无效

### ISSUE THREAD

**Issue by ruancheng77** [ecomfe/echarts#7214]
### One-line summary [问题简述]
使用折线图的时候，legend 过多想使用scroll类型，但是设置之后并没有实现scroll效果。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.0
+ Browser version [浏览器类型和版本]: 360、谷歌、火狐
+ OS Version [操作系统类型和版本]: windows

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/23415499/33709705-2dc789ac-db79-11e7-98c9-938a2fa25eaf.png)

**Comment by pissang** [comment]
用最新版本的 echarts
