### ISSUE TITLE
chrome35版本，hbuilder内置的浏览器显示图的时候，缺右边的一块

### ISSUE THREAD

**Issue by mifox** [ecomfe/echarts#7219]
### One-line summary [问题简述]

chrome35版本，hbuilder内置的浏览器显示图的时候，缺右边的一块滑动轴，

http://echarts.baidu.com/tutorial.html#%E5%9C%A8%E5%9B%BE%E8%A1%A8%E4%B8%AD%E5%8A%A0%E5%85%A5%E4%BA%A4%E4%BA%92%E7%BB%84%E4%BB%B6

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:chrome35  可以用hbuilder8内置的浏览器测试
+ OS Version [操作系统类型和版本]:
win10

### Expected behaviour [期望结果]

修复下这个bug，浏览器兼容性上稍微好一点

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
暂时没精力考虑 hbuilder 里的兼容性问题
