### ISSUE TITLE
echart 能实现正态分布图吗？

### ISSUE THREAD

**Issue by menkeydyvh** [ecomfe/echarts#7224]
### One-line summary [问题简述]
没有找到实现正态分布图的用例

### Expected behaviour [期望结果]
是否给个官方例子？ 或者如果没有是否会引入正态分布图

**Comment by pissang** [comment]
可以的，你用一个正态分布的数据就行

**Comment by yunsile** [comment]
你这个回答真的是...无语，正态分布数据从哪来？就是无法获取正态分布数据无法使用折线
