### ISSUE TITLE
the color about axisLabel

### ISSUE THREAD

**Issue by LJade** [ecomfe/echarts#7236]
### One-line summary [问题简述]

I can't set up the color of axisLabel with 'color'

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

echart v3.6.2
browser chrome .etc
OS win7

### Expected behaviour [期望结果]
I want to set the axisLabel color  of xAxis and yAxis through 'color'.But it failed.
I set 'axisLine.lineStyle.color' in my code, it makes sence to 'color of axisLabel' ,
According to  document,  this way should be effective.
But I must set color by 'data:[value:X.textStyle:{color:'XXX'} rather than 'xAixs:{color:'XXX']'
It is very redundancy!
Finally, chart works correctlly,only color

### ECharts option [ECharts配置项]

```javascript
option = {
 xAxis: {
              type: 'category',
              data: [{value:'XXX',textStyle:{color:'#54585a'}}...],
              axisLabel:{
                width:225
              },
              axisTick: {show: false},
              axisLine:{
                lineStyle:{
                  color:'#f1f1f1'
                }
              },
              splitLine:{
                  show:true,
                  lineStyle:{
                    color:'#f1f1f1'
                  }
              }
            }
         ,
          yAxis:
            {
              type: 'value',
              axisLine:{
                lineStyle:{
                  color:'#f1f1f1'
                }
              },
              min:0,
              max:5,
              axisTick:{
                show:false
              },
              splitLine:{
                lineStyle:{
                  color:'#f1f1f1'
                }
              },
              axisLabel:{
                  color:'#54585a'
              }
            }
}

```

abouve all, X=>success   Y=> fail

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/17740329/33819855-81cc82f8-de87-11e7-8fc2-baa9f55d7d00.png)

**Comment by pissang** [comment]
Update to the latest version of ECharts, which is 3.8.5
