### ISSUE TITLE
Question for heatmap: Highlight / different format for coordinates

### ISSUE THREAD

**Issue by OliverAndersRWE** [ecomfe/echarts#7242]
Hi,
I have a question regarding the heatamps like https://ecomfe.github.io/echarts-examples/public/editor.html?c=heatmap-cartesian:

Is there a way for changing the bordercolor of an item in a heatmap (Cartesian) based on the data provided (through additional dimension)?

putting a function as attribute does not work..

itemStyle: {
            normal:{
                borderColor:function(parms){return 'red'}
            },

Kind Regards,
Oliver

**Comment by pissang** [comment]
You can set the itemStyle in the particular data item. Like following:

```js
data: [ { value: 10, itemStyle: { normal: { borderColor: 'red' } } } ]
```

**Comment by OliverAndersRWE** [comment]
Thanks for the quick reply!!!
