### ISSUE TITLE
edgeLabel.emphasis.position 不起作用

### ISSUE THREAD

**Issue by SevenChan07** [ecomfe/echarts#7243]
### One-line summary [问题简述]

使用关系图绘制图形。设置 `option` 的 `edgeLabel.emphasis.position` 为 `middle`，不起作用，始终显示在`start`位置。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: Chrome, 62.0.3202.94
+ OS Version [操作系统类型和版本]: OSX EI Capitan 10.11.6

### Expected behaviour [期望结果]
edgeLabel的位置随着，`edgeLabel.emphasis.position` 的设置而变化。

### ECharts option [ECharts配置项]

```javascript
option = {
    series: [{
        type: 'graph',
        layout: 'circular',
        symbolSize: 30, //图形的大小（示例中的圆的大小）
        roam: true, //鼠标缩放及平移
        focusNodeAdjacency: true, //是否在鼠标移到节点上的时候突出显示节点以及节点的边和邻接节点
        label: {
            normal: {
                show: true, //控制非高亮时节点名称是否显示
                position: 'top',
                fontSize: 20
            }
        },
        edgeSymbol: ['circle', 'arrow'],
        edgeSymbolSize: [1, 10], //箭头的大小
        edgeLabel: {
            normal: {
                show: false,
                position: 'start',
            },
            emphasis: {
                show: true,
                position: 'middle',
                color: 'blue',
                textStyle: {
                    fontSize: 70 //边节点显示的字体大小
                }
            }
        },

        //节点信息
        data: [{
                name: 'h1',
            }, {
                name: 'h2',
            },
        ],
        links: [{
            source: 'h1',
            target: 'h2',
        }],
    }]
}

```

### Other comments [其他信息]

![2017-12-12 10 23 11](https://user-images.githubusercontent.com/10449096/33864210-98d2ce18-df26-11e7-8639-bd3fe077773a.png)

demo地址： <https://jsbin.com/huriyer/edit?js,console,output>

**Comment by Erimus-Koo** [comment]
可以用 normal.textStyle.color:'transparent' 凑合一下。
normal.show 然后normal.position还是有效的。

**Comment by SevenChan07** [comment]
明白了，还是要靠黑科技。。。

**Comment by chaegumi** [comment]
好像还是存在这样的问题
