### ISSUE TITLE
根据教程来，echarts结合百度地图无法展示，小白一枚，求大神帮助!!!

### ISSUE THREAD

**Issue by didijiang** [ecomfe/echarts#7248]
### One-line summary [问题简述]
echart结合百度地图无法展示

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:官网下载的完整版本
+ Browser version [浏览器类型和版本]:IE11
+ OS Version [操作系统类型和版本]:WIN7

### Expected behaviour [期望结果]

百度地图上出现散点图

`<!DOCTYPE html>  
<html lang = "en">  
<head>  
    <meta charset="utf-8" />  
    <title>Baidu Map </title>  
	<script src="http://api.map.baidu.com/api?v=2.0&ak="></script>	
	<script src ='/extension/bmap.js'>
	</script>
	<script src ='echarts.min.js'>
	</script>
	<script src='jquery.min.js'></script>
</head>  
<body>
	<div id = "allmap" style="height:1000px;"></div>
	<script type="text/javascript">
	var bmapChart = echarts.init(document.getElementById('allmap'));
	var  mydata =[{name: '海门', value: [121.15, 31.89, 90]}];
	var option = {
		bmap: {
			center: [116.307698, 40.056975],
			zoom: 5, 
			roam: true 
		},
		visualMap: {	// 视觉映射组件
			type: 'continuous',
			min: 0,
			max: 200,
			calculable: true,
			inRange: {
					color: ['#50a3ba','#eac736','#d94e5d']
		 }},
		series: [
			{
				name: '销量',
				type: 'scatter',
				coordinateSystem: 'bmap', 
				data: mydata
			}
		]

	};
	bmapChart.setOption(option);
	</script>
</body>

</html>`

**Comment by pissang** [comment]
描述清楚你的问题

**Comment by didijiang** [comment]
已解决 。因为引入位置错误
