### ISSUE TITLE
异步获取多个表的数据

### ISSUE THREAD

**Issue by shenghou** [ecomfe/echarts#7249]
异步获取多个表的数据时添加到表格里

+ ECharts version [3.8.4]:
+ Browser version [ 谷歌浏览器62.0.3202.94]:
+ OS Version [win7 64位]:

异步获取的数据动态添加到表格中

                        var timeData = [];
			var serValue = [];
			function mediaConfig(type){
				return	mediaConfig = {
					"ledActive":$scope.ledActive,
					"getType":type,
				}

			}
			var myChart = echarts.init(document.getElementById('main'));
			myChart.showLoading();
			var option = {
				title: {
					text: monitoringTitel,
					subtext: 'xxxxxxx',
					x: 'center'
				},
				tooltip: {
					trigger: 'axis',
					axisPointer: {
						animation: false
					}
				},
				legend: {
					data:['误码率','温度','湿度'],
					x: 'left'
				},
				toolbox: {
					feature: {
						dataZoom: {
							yAxisIndex: 'none'
						},
						restore: {},
						saveAsImage: {}
					}
				},
				axisPointer: {
					link: {xAxisIndex: 'all'}
				},
				dataZoom: [
					{
						show: true,
						realtime: true,
						start: 30,
						end: 70,
						xAxisIndex: [0, 1, 2]
					},
					{
						type: 'inside',
						realtime: true,
						start: 30,
						end: 70,
						xAxisIndex: [0, 1, 2]
					}
				],
				grid: [{
					left: 50,
					right: 50,
					top: '10%',
					height: '22%'
				}, {
					left: 50,
					right: 50,
					top: '38%',
					height: '22%'
				},{
					left: 50,
					right: 50,
					top: '70%',
					height: '22%'
				}],
				xAxis : [
					{
						type : 'category',
						boundaryGap : false,
						axisLine: {onZero: true},
						data: []
					},
					{
						gridIndex: 1,
						type : 'category',
						boundaryGap : false,
						axisLine: {onZero: true},
						data: [],
						position: 'bottom'
					},
					{
						gridIndex: 2,
						type : 'category',
						boundaryGap : false,
						axisLine: {onZero: true},
						data: [],
						position: 'top'
					}
				],
				yAxis : [
					{
						name : '误码率(%)',
						type : 'value',
						max : 100,
						min : 0,
						fontStyle :'italic',
						
					},
					{
						gridIndex: 1,
						name : '温度(℃)',
						type : 'value',
						inverse: true,
						max : 60,
						min: -40,
						fontStyle :'italic',
						nameGap :20,
					},
					{
						gridIndex: 2,
						name : '湿度(%)',
						type : 'value',
						inverse: true,
						max : 100,
						min : 0,
						fontStyle :'italic'
					}
				],
				series : [
					{
						name:'误码率',
						type:'line',
						symbolSize: 8,
						hoverAnimation: false,
						data:[]
					},
					{
						name:'湿度',
						type:'line',
						xAxisIndex: 1,
						yAxisIndex: 1,
						symbolSize: 8,
						hoverAnimation: false,
						data:[]
					},
					{
						name:'温度',
						type:'line',
						xAxisIndex: 2,
						yAxisIndex: 2,
						symbolSize: 8,
						hoverAnimation: false,
						data:[]
					}
				]
			};
			myChart.setOption(option);
			$scope.getMonitorInfo = function(type){
				terminal.getMonitor(mediaConfig(type),function(data){
                                       //这异步回调的数据
					myChart.hideLoading();
					for(var i = 0, l = data.data.length; i < l; i++){
						timeData.push(data.data[i].date); 
						serValue.push(parseFloat(data.data[i].sensorValue));
					};
					myChart.setOption({
						xAxis: {
							data: timeData   //下面两个调用数据怎么添加到这里
						},
						series: [{
							data: serValue  //下面两个调用数据怎么添加到这里
						}]
					});
				});
			};
			$scope.getMonitorInfo("error_rate");
			$scope.getMonitorInfo("humidity");
			$scope.getMonitorInfo("temperature");

**Comment by pissang** [comment]
问题是？

**Comment by shenghou** [comment]
不好意思，写在下面的注释中不太显眼。
在一个option中添加了三个表格，表格中的数据一开始为空，然后从三个不同接口获取数据填入表格中，填入数据的时候设置了series的name属性但无法添加到表中。

**Comment by ihuguowei** [comment]
个人觉得你这么做逻辑上没问题，你可以先试试获取全部数据再`setOption`。
