### ISSUE TITLE
textStyle 全局字体样式应用混乱，不具备一致性

### ISSUE THREAD

**Issue by LE88I5** [ecomfe/echarts#7255]
### One-line summary [问题简述]
配置选项中，textStyle 全局字体样式应用混乱，不具备一致性。

以下是部分属性目前应用的效果，例如 “fontSize， 图例” 表示仅图例有效果，其他没有效果。
fontSize， 图例
color,         坐标文字
fontWeight，图例、坐标轴文字
textBorderColor， 图例、坐标轴文字、标题
textBorderWidth，图例、坐标轴文字、标题（如果该属性不提供， 图例的文字会错乱到左上角）
fontStyle，图例、坐标轴文字、标题

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版本
+ Browser version [浏览器类型和版本]: 最新版本 Chrome
+ OS Version [操作系统类型和版本]: macOS 10.13.2

### Expected behaviour [期望结果]
textStyle 全局字体样式能够统一应用，保持一致的效果。

### ECharts option [ECharts配置项]

```javascript
option = {
    title: {
        text: 'ECharts 入门示例'
    },
    tooltip: {},
    legend: {
        data:['销量']
    },
    xAxis: {
        data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
    },
    yAxis: {},
    series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
    }],
    textStyle:{
        fontSize:50,
        color:'blue',
        fontWeight:'lighter',
        textBorderColor: 'yellow',
        textBorderWidth: 10
    }
}

```

**Comment by pissang** [comment]
这是因为部分组件有对于它们自己更合适的默认文本样式，会覆盖掉全局样式
