### ISSUE TITLE
地图插件data range UI问题

### ISSUE THREAD

**Issue by vercha** [ecomfe/echarts#7257]
![image](https://user-images.githubusercontent.com/13897098/33918678-b9f3201a-dfef-11e7-9824-0b29438ba0b8.png)

###
如图， datarange 是否支持定义两种统计方式？
目前可以定义datarange 范围，对series中data统计并区域颜色梯度展示；
如UI，我想多加一种统计方式，统计前5 前10 地区，并显示城市位置。
这可以通过datarange里多加一项定义来实现么？
或者这个需求可以通过什么option来配置？

谢谢！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
3.0 之后的 echarts 可以用多个 visualMap（也就是 2 里面的 dataRange） 组件

**Comment by vercha** [comment]
ok
啊哈哈 醉了 难怪echarts3文档下找不到datarange相关配置了
thanks very much！
