### ISSUE TITLE
echarts 在线定制可以指定某个版本的吗？

### ISSUE THREAD

**Issue by xmchyabi** [ecomfe/echarts#7261]
### One-line summary [问题简述]

http://echarts.baidu.com/builder.html
在这里可以定制所需要的图表，但是可以指定之前的版本吗？

我目前使用的是3.5.4的版本，升级到最新后， 会有一些地方不兼容，暂时没有时间一个个图表去验证修改，想说是否可以用定制下载之前的3.5.4版本。

谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
不行

**Comment by xmchyabi** [comment]
@pissang 
谢谢回复，那我直接用3.5.4完整版好了。

有不少小地方https://github.com/ecomfe/echarts/issues/7223
