### ISSUE TITLE
对隐藏的dom初始化echarts时，页面空白

### ISSUE THREAD

**Issue by shunzizhan** [ecomfe/echarts#7266]
### One-line summary [问题简述]
对隐藏的dom初始化echarts时，页面空白

页面上有两个tab，一个是报表形式展示数据，一个是图表形式展示数据
在请求数据后，对数据进行处理，并初始化echarts图表(此时dom是隐藏的)，点击tab切换，展示图表为空白，改变浏览器的大小，正常显示图表
我也曾尝试在点击tab时，再去初始化图表，但是依旧显示空白

### Version & Environment [版本及环境]
+ ECharts version [3.0]:
+ Browser version [谷歌   62.0.3202.94]:
+ OS Version [Windows 64]:

### Expected behaviour [期望结果]
切换tab时正常显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by xmchyabi** [comment]
初始化图表监听一个事件
window.addEventListener('resize', myChart.resize);

切换TAB时，触发resize事件
 timeout(function () {
                            window.dispatchEvent(new Event('resize'));
                        }, 10);
