### ISSUE TITLE
动态加载不同数量的子图时显示有误

### ISSUE THREAD

**Issue by LiCasey** [ecomfe/echarts#7268]
### One-line summary [问题简述]
绘制森林图，当图中的树从两棵变为一棵时，被删除的第二棵树仍然显示在图表中

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: Chrome 63.0.3239.84
+ OS Version [操作系统类型和版本]: Win10 x64

### Expected behaviour [期望结果]
删除树之后，被删除的树不再显示在图表中

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

https://jsfiddle.net/hhLbq4ut/3/

**Comment by pissang** [comment]
setOption 第二个参数传 true
