### ISSUE TITLE
svg 渲染模式下，如果存在多个带渐变的实例，渐变颜色渲染不正确

### ISSUE THREAD

**Issue by Tk-archer** [ecomfe/echarts#7276]
### One-line summary [问题简述]

渲染模式为 svg 

如果同时有两个 bar 实例 ，且其 itemStyle.color 为不同的渐变颜色的时候

第二个实例的渐变颜色渲染不正确

下方 JSFiddle 的例子里面第二个实例的图例的颜色，跟实际上柱状图的渐变颜色不一样（图例的颜色才是对的）

我看了一下生成的 svg，
上下两个实例为了渲染渐变效果，会产生多个 id 相同的 linearGradient 

感觉因为 id 重复而导致了引用错误 

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: chrome 63 /firefox 58.0b11
+ OS Version [操作系统类型和版本]: ubuntu 17.04

### Expected behaviour [期望结果]

每个实例渐变渲染应当不受别的实例影响

### ECharts option [ECharts配置项]

请直接看 jsfiddle 的例子

### Other comments [其他信息]

JSFiddle 的例子

https://jsfiddle.net/qohdmdxo/3/

**Comment by Ovilia** [comment]
4.0 版本中已修复。
