### ISSUE TITLE
Legend itemGap属性同时设置了水平与竖直间隔

### ISSUE THREAD

**Issue by eidonjoe** [ecomfe/echarts#7277]
### One-line summary [问题简述]
itemGap文档描述为图例每项之间的间隔。横向布局时为水平间隔，纵向布局时为纵向间隔。
实际与布局没关系, 会同时设置水平和纵向间隔

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.5.4
+ Browser version [浏览器类型和版本]:chrome 63
+ OS Version [操作系统类型和版本]: Mac OSX

### Expected behaviour [期望结果]
itemGap可以不用区分布局去单独设置水平与竖直间隔, 可以使图例更灵活

### ECharts option [ECharts配置项]

```javascriptvar
 legendData = [
    '图例', '比较长的图例', 'abc', '',
    'How to align', 'vvv', '飒飒地方', '',
    'e', 'd', 's'
];

var series = [];

echarts.util.each(legendData, function (name) {
console.log(name);
    if (name) {
        series.push({
            name: name,
            type: 'scatter',
            data: [[Math.random(), Math.random()]]
        });
    }
});
    
option = {
    legend: {
        bottom: 20,
        orient: 'vertical',
        itemGap: 45,
        data: legendData  
    },
    xAxis: {},
    yAxis: {},
    grid: {
        bottom: 120
    },
    series: series
};
```

### Other comments [其他信息]
http://gallery.echartsjs.com/editor.html?c=xrkKj1YHze

![image](https://user-images.githubusercontent.com/11781454/33983881-abbba1fa-e0f0-11e7-976f-db0c01c715da.png)

**Comment by Erimus-Koo** [comment]
看我之前写的 #7117 
itemgap相当于单个legend的margin
可以用padding来控制item间距
`textStyle:{padding:[0,50,0,0]},//文字右边距50px`

**Comment by eidonjoe** [comment]
十分感谢

**Comment by 1160105398jack** [comment]
十分感谢
