### ISSUE TITLE
overlap issue.

### ISSUE THREAD

**Issue by gksdnr89** [ecomfe/echarts#7284]
### One-line summary [问题简述]
Pie charts's labels are overlapped

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: chrome 63
+ OS Version [操作系统类型和版本]: win 10

### Expected behaviour [期望结果]
do not overlap

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
        trigger: 'item',
        formatter: "{b} <br/> {c} ({d}%)",
    },
	series : [ {
				type : 'pie',
				radius : [ '45%', '80%' ],
				avoidLabelOverlap : false,
				label : {
					normal : {
						show : true,
						position : 'inner'
					},
					emphasis : {
						show : true,
						textStyle : {
							fontSize : '14',
							color:'#fff'
						}
					}
				},
				labelLine : {
					normal : {
						show : false
					}
				},
				data : [{name: "공동", value: "849"},{name: "김종호", value: "471"},{name: "김복순", value: "379"},{name: "김관태", value: "15"},{name: "김복순, 김종호", value: "5"},{name: "아들들", value: "3"},{name: "김복순의 친정 엄마", value: "2"},{name: "손녀", value: "2"},{name: "김종호, 김복순", value: "1"},{name: "아들", value: "1"},{name: "막내아들", value: "1"},{name: "세아들", value: "1"}]
			} ]
}

```

### Other comments [其他信息]

Screenshot
![overlap](https://user-images.githubusercontent.com/33612401/34026026-a13c06f6-e196-11e7-8b68-3abe86e2fca6.PNG)

**Comment by Ovilia** [comment]
In this situation, you'd better set [label.normal.position](http://echarts.baidu.com/option.html#series-pie.label.normal.position) to be `'outside'`.

**Comment by gksdnr89** [comment]
Thanks. but inner position is requirement spec.

**Comment by Ovilia** [comment]
How do you expect it to be displayed inside, without overlapping?

**Comment by gksdnr89** [comment]
Sorry. By inserting condition of percentage, I solved this problem.
Close issue! Thanks.

**Comment by Ovilia** [comment]
That's cool. :)
