### ISSUE TITLE
饼图 部分占比被0.001%或者更低的，是否可以通过千分之或者万分之显示的？

### ISSUE THREAD

**Issue by Meow-z** [ecomfe/echarts#7287]
### One-line summary [问题简述]

饼图 部分占比被0.001%或者更低的，是否可以通过千分之或者万分之显示的？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:最新
+ Browser version [浏览器类型和版本]:chorme 最新
+ OS Version [操作系统类型和版本]: Mac Windows

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以自行修改 formatter http://echarts.baidu.com/option.html#series-pie.label.normal.formatter
