### ISSUE TITLE
echart 热地图无法限制百度地图缩放

### ISSUE THREAD

**Issue by Sanagiig** [ecomfe/echarts#7290]
### One-line summary [问题简述]
调用echart 内的bmap.enableScrollWheelZoom(false) 无法禁用 地图的缩放

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

Google Chrome 
版本 63.0.3239.84（正式版本） （64 位）
windows 10

### Expected behaviour [期望结果]

期望能告知如何禁止 echart 热地图缩放（禁止缩放，但能拖动）

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
bmap: { roam: false }

**Comment by Sanagiig** [comment]
谢谢，我查到该怎么做了
