### ISSUE TITLE
堆叠折线图数据与Y轴不一致的bug

### ISSUE THREAD

**Issue by BurningJump** [ecomfe/echarts#7292]
### One-line summary [问题简述]
[[官方折线图实例里面有一个bug，当显示多条折线时，其中有些的数据会和Y轴不一致，单独显示单条折线则不会有问题。]](http://echarts.baidu.com/demo.html#area-stack)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

http://echarts.baidu.com/demo.html#area-stack

**Comment by Erimus-Koo** [comment]
因为这线一多吧 它就容易乱呀 ...⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄....

**Comment by pissang** [comment]
去掉 stack
