### ISSUE TITLE
Cannot set color for splitLine in grid3D

### ISSUE THREAD

**Issue by marswong** [ecomfe/echarts#7295]
### One-line summary [问题简述]

when using `grid3D`, the color just remain default `#ccc`

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.8.5
+ Browser version [浏览器类型和版本]: Chrome 62+
+ OS Version [操作系统类型和版本]: macOS 10.13.2

### Expected behaviour [期望结果]

the color of  splitLine should be mutable

### ECharts option [ECharts配置项]

take an official [gallery](http://gallery.echartsjs.com/editor.html?c=xSJUxZ-c6x) as an example, just modify the config like this:

```javascript
option = {
    ...option,
    grid3D: {
        boxWidth: 200,
        boxDepth: 80,
        light: {
            main: {
                intensity: 1.2
            },
            ambient: {
                intensity: 0.3
            }
        },
        splitLine: {
            interval: {
                color: '#fff' // ['#fff'] cannot work either
            }
        }
    },
}
```

**Comment by pissang** [comment]
It should be

```js
splitLine: {
  lineStyle: {
    color: '#fff'
  }
}
```

**Comment by marswong** [comment]
thanks, it works now :)
