### ISSUE TITLE
map 中国地图 省市坐标点

### ISSUE THREAD

**Issue by vercha** [ecomfe/echarts#7301]
###哪个option可以实现下图效果，前10区域显示省会坐标点，其它不显示；

需求如图：
统计销量前十与前三城市；
对销量前十与前三的城市设置不同颜色的坐标点；

### Version & Environment [版本及环境]
echart3.8.1
vue 2.9

### Expected behaviour [期望结果]

目前通过map option->itemStyle->normal->color:'transparnt'设置可以不显示坐标点；
单独设置某些省市的itemstyle->normal->color:'orange'。没有出现期望的效果。

**Comment by jiangshichao** [comment]
为什么不能单独设置......

**Comment by vercha** [comment]
单独设置是通过itemstyle->normal->color:么？我试了没效果哇

**Comment by jiangshichao** [comment]
是的,刚刚特定试了一下，官亭 点的确已经变成红色了，不知道你是否是什么参数搞错了
data:[
        {"name": "鱼卡", "value": [94.06,37.46], "symbolSize": 10},
        {"name": "柴达木", "value": [93.56,36.46], "symbolSize": 10},
        {"name": "海西", "value": [96.65,36.85], "symbolSize": 10},
        {"name": "郭隆", "value": [102.18,36.69], "symbolSize": 10},
        {"name": "西宁", "value": [101.18,36.39], "symbolSize": 10},
        {"name": "日月山", "value": [99.58,36.89], "symbolSize": 10},
        {"name": "塔拉", "value": [98.08,36.09], "symbolSize": 10},
        {
            "name": "官亭", 
            "value": [102.38,35.69], 
            "symbolSize": 10,
            "itemStyle":{
                "normal":{
                    "color":'red'
                }
            }
        }
    ]

**Comment by jiangshichao** [comment]
不行你就多搞几组scatter呗，或者使用visualMap绑定到scatter，设置不同的值展示不同的颜色

**Comment by vercha** [comment]
按照你的方法试了下是可以的；
但我用了visual map，再这样设置不起作用；
另一个问题：两个visual map会互相影响；怎么可以让visualMap绑定到scatter；

**Comment by jiangshichao** [comment]
参考api以及官网示例，http://gallery.echartsjs.com/editor.html?c=scatter-map
