### ISSUE TITLE
mapbox无法展现heatmap？

### ISSUE THREAD

**Issue by knowbyyou** [ecomfe/echarts#7307]
### One-line summary [问题简述]
想再mapbox上通过type: "heatmap"来展现，但是按照文档和例子进行相关配置后，提示错误：Uncaught TypeError: geo.getViewRect is not a function。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:Chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
展现出和demo中类似的热力图。

### ECharts option [ECharts配置项]

```javascript
option = {
mapbox: {
			center: [116.39157, 39.90673],
			zoom: 12,
			pitch: 55,
			style: 'mapbox://styles/mapbox/dark-v9'
		},
		visualMap: {
            show: false,
            top: 'top',
            min: 0,
            max: 5,
            seriesIndex: 0,
            calculable: true,
            inRange: {
                color: ['blue', 'blue', 'green', 'yellow', 'red']
            }
        },
		series: [{
			type: "heatmap",
			coordinateSystem: 'mapbox',
			data: points,
			pointSize: 5,
            blurSize: 6
		}]
}

```

**Comment by pissang** [comment]
mapbox 现在是 echarts GL 里为三维可视化提供支持的组件

**Comment by SongYg** [comment]
使用echartsLayer设置heatmap依旧会报Uncaught TypeError: geo.getViewRect is not a function的错误

**Comment by Desever** [comment]
遇到了同样的问题，在使用geo3D构建3d地图时，如何叠加热力图呢？
