### ISSUE TITLE
 Data unclear when displaying single Date data point with bars

### ISSUE THREAD

**Issue by c-okelly** [ecomfe/echarts#7308]
### One-line summary [问题简述]

When only single data data point is displayed it is ECharts buffers the xAxis around this making the data displayed unclear.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

Version 3.8.5
Browser: Chrome Version 63.0.3239.84 
OS : OSX

### Expected behaviour [期望结果]

When displaying a single date on the xAxis it would be more clear that the bars are being plotted around a single point rather then a range of times as seen on the xAxis.

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
        text: 'Date display demo'
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type : 'time'
    },
    yAxis: {
        type : 'value'
    },
    series: [
        {
            name: 'Left',
            type: 'bar',
            data:[[new Date(2018, 0, 10), 200]]
        },
        {
            name: 'Right',
            type: 'bar',
            data:[[new Date(2018, 0, 10), 20]]
        }
    ]
}

```

### Other comments [其他信息]

In this example two data points are plotted around 2018/1/10

![screen shot 2017-12-18 at 17 07 23](https://user-images.githubusercontent.com/8889083/34118201-05f9180a-e416-11e7-87ed-9f1947360351.png)

**Comment by pissang** [comment]
Perhaps it's more appropriate to use a `category` axis rather than a `time` axis.

Or you can workaround on this issue by only show the start and end axis tick. And show the time of each bar with `label`. Like following:

```js
option = {
title: {
        text: 'Date display demo'
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type : 'time',
        splitNumber: 1
    },
    yAxis: {
        type : 'value'
    },
    series: [
        {
            name: 'Left',
            type: 'bar',
            label: {
                normal: {
                    show: true,
                    position: 'bottom',
                    color: '#000',
                    formatter: '01-09\n2018'
                }  
            },
            data:[[new Date(2018, 0, 10), 200]]
        },
        {
            name: 'Right',
            type: 'bar',
            label: {
                normal: {
                    show: true,
                    position: 'bottom',
                    color: '#000',
                    formatter: '0-10\n2018'
                }  
            },
            data:[[new Date(2018, 0, 10), 20]]
        }
    ]
}
```

**Comment by c-okelly** [comment]
@pissang Thanks for your reply!

I think we will probably try and display the data as a category instead. I will close the issue!

Conor
