### ISSUE TITLE
series data为二维数组，数组内第一个值为字符时表格不生成

### ISSUE THREAD

**Issue by shenghou** [ecomfe/echarts#7314]
### One-line summary [问题简述]

当设置series内data为多维数组时，数组内第一个值为字符，第二值为数字时表格不生成

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
Version 3.8.5
Browser: Chrome Version 63.0.3239.84
OS : OSX

### Expected behaviour [期望结果]
当数组内的值不均为数字时也能生成。

### ECharts option [ECharts配置项]

```javascript
var data = [[15, 0], [-50, 10], [-56.5, 20], [-46.5, 30], [-22.1, 40]];
var datas = [
    ["2017-12-19 07:47:13", 0], 
    ["2017-12-19 07:48:41", 10], 
    ["2017-12-19 07:49:41", 20], 
    ["2017-12-19 07:50:41", 30], 
    ["2017-12-19 07:41:41", 40]
 ]
option = {
    title: {
        text: 'ECharts 入门示例'
    },
    tooltip: {},
    legend: {
        data:['大小']
    },
    xAxis: {
        type: 'value',
        axisLine: {onZero: false}
    },
    yAxis: {
        type: 'value',
        axisLine: {onZero: false}
    },
    series: [{
        name: '大小',
        type: 'line',
        data: datas
    }]
};

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/24260845/34146814-66f57e9e-e4d6-11e7-86eb-84b896501c92.png)

**Comment by pissang** [comment]
xAxis.type 改成 'time'

**Comment by shenghou** [comment]
谢谢回复，我想做的是在同一个表中生成多根线，每根线根据时间轴生成但可能会出现某根线一部分数据漏掉后又续上来，当设置 类型为“time”时候会导致时间轴上时间数据重复的bug.
![image](https://user-images.githubusercontent.com/24260845/34153980-e89f30b2-e4ee-11e7-8ce4-65d9c56f4bc3.png)
