### ISSUE TITLE
echarts3的tree如何翻转？2版本的direction：‘inverse’无效

### ISSUE THREAD

**Issue by yyanhg** [ecomfe/echarts#7317]
### One-line summary [问题简述]

echarts3的tree如何翻转？比如节点由右侧向左侧展开，根节点在右侧。
2版本的direction：‘inverse’，在3中无效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by kang558** [comment]
我也是在弄这个翻转问题。echarts3不支持了。楼主现在解决了吗？ @yyanhg

**Comment by deqingli** [comment]
这个功能我已经加上了，下个版本会上；在下个版本中，可以配置series-tree.orient: 'RL' ，控制方向从右到左
