### ISSUE TITLE
echarts-gl 如何给每个省市设置颜色？

### ISSUE THREAD

**Issue by jiangshichao** [ecomfe/echarts#7330]
echarts-gl 如何给每个省市设置颜色？

**Comment by pissang** [comment]
参考 http://gallery.echartsjs.com/editor.html?c=xB1SRBzq6x

**Comment by jiangshichao** [comment]
谢谢，但是我是用Map3D之后scatter3D的坐标系怎么办，没法与之关联 @pissang

**Comment by pissang** [comment]
这个问题关了，后续在 https://github.com/ecomfe/echarts/issues/7333 讨论
