### ISSUE TITLE
echarts3 自定义geojson  地理数据数组怎么压缩？

### ISSUE THREAD

**Issue by canyueGard** [ecomfe/echarts#7342]
### One-line summary [问题简述]
自定义了geojson地理数据较大，而官网提供的demo地理数据都是压缩过的，所以特别小，我也想压缩，但不知道怎么做

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
希望给个压缩算法demo

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by chfw** [comment]
`npm install -g echarts-mapmaker`

你需要compress 命令. 

如果好用，请star我的这个工具箱 https://github.com/chfw/echarts-mapmaker，

**Comment by canyueGard** [comment]
已star~

**Comment by canyueGard** [comment]
【makejs能成功，compress数据压缩没成功】这是咋回事？

[shenzhen_map_geojson.txt](https://github.com/ecomfe/echarts/files/1621027/shenzhen_map_geojson.txt)
