### ISSUE TITLE
echarts scatter8万个点dataZoom卡顿

### ISSUE THREAD

**Issue by 1209823208** [ecomfe/echarts#7347]
### One-line summary [问题简述]

 项目需求是：series data symbolsize随着dataZoom放大变大
在dataZoom回调函数中 放大　symbolsize时很卡。有没有快速放大点的大小

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}
for (const val of change_options_params_arr) {
      if (val[0] === 'y1') {
        for (let key = 0; key < this.current_options_series.length;) {
          this.current_options_series[key].symbolSize = val[1];
          key += 3;
        }
      }
      if (val[0] === 'y2') {
        for (let key = 0; key < this.current_options_series.length; key++) {
          if (key % 3 !== 0) {
            this.current_options_series[key].symbolSize = val[1];
          }
        }
      }
    }
    this.echartsIntance.setOption({
      series: this.current_options_series
    });
```

##
<img width="1210" alt="2017-12-22 1 52 38" src="https://user-images.githubusercontent.com/29597482/34287175-62b64e66-e720-11e7-9521-0c2fe51833d8.png">

**Comment by pissang** [comment]
```js
large: true
```
或者试试用 ECharts GL
