### ISSUE TITLE
How can I split colors of the area under line chart after a certain threshold (beyond x-axis)

### ISSUE THREAD

**Issue by nubela** [ecomfe/echarts#7353]
I'm trying to build a depth chart, like this ![chart](https://www.amcharts.com/wp-content/uploads/2017/09/demo_9306_light-1.jpg).

How can I do this?

Thank you!

**Comment by pissang** [comment]
You can use `visualMap` component. Check this example https://ecomfe.github.io/echarts-examples/public/editor.html?c=line-sections

**Comment by nubela** [comment]
Looks good, seems to solve what I need perfectly. Thanks!

**Comment by sridhar-fx** [comment]
Can i get an examople
