### ISSUE TITLE
您好，请问在官网的demo中，查看关系图的数据，需要我们给出所有图的坐标吗？很不好用啊

### ISSUE THREAD

**Issue by zxj19951029** [ecomfe/echarts#7371]
使用的是当前最新版本，查看的是这个示例：http://echarts.baidu.com/demo.html#graph-npm

这个示例的数据地址是:http://www.echartsjs.com/gallery/data/asset/data/npmdepgraph.min10.json

如果要用户提供所有点的坐标，那么这个关系图很不好用啊

**Comment by 15036900300** [comment]
@pissang graph可不可以通过echarts动态给出每个节点的坐标，但是展示的效果想要累死树图的那种展示有层级的样子，因为我们根节点暂时不止一个，所以在自己计算的时候给出来的坐标总是差强人意

**Comment by seekei** [comment]
同上+1
