### ISSUE TITLE
[建议]增加环形图默认放大效果

### ISSUE THREAD

**Issue by ccsulzf** [ecomfe/echarts#7382]
### One-line summary [问题简述]

环形图不能控制某一项的放大,只能鼠标移上去才能放大

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
echarts@3.8.5
+ Browser version [浏览器类型和版本]:
Google Chrome 版本 62.0.3202.89（正式版本） （64 位）
+ OS Version [操作系统类型和版本]:
window7 64位

### Expected behaviour [期望结果]
![image](https://user-images.githubusercontent.com/25943682/34399375-e06bc0f2-ebc1-11e7-8c22-6fe134e7abe7.png)
在data里面可以对某一项配置进行放大,就像selected:true一样,能否增加hover:true这样的属性

**Comment by hanfengcan** [comment]
http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA

这里的`代码触发 ECharts 中组件的行为`满不满足需求
