### ISSUE TITLE
d3 使用world.js

### ISSUE THREAD

**Issue by zsjun** [ecomfe/echarts#7383]
### One-line summary [问题简述]
使用echars提供的world.js 文件，使用d3不能正确显示地图

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-map-tool/tree/gh-pages/maker/raw
