### ISSUE TITLE
能认认真真做产品不？把说明书写仔细了，可以不？别让人用着你的产品还骂垃圾

### ISSUE THREAD

**Issue by wlhebut** [ecomfe/echarts#7384]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by DukeGJ** [comment]
用着开源免费的还喷作者，你是我见过的第一个

**Comment by ThunderLT** [comment]
百度出的东西就是垃圾

**Comment by ThunderLT** [comment]
文档稀烂的一批，我用过开源产品里文档写的最垃圾的就是这垃圾玩意儿了
