### ISSUE TITLE
在线定制选择了svg渲染，但是还是渲染成canvas,不用定制的就渲染成svg

### ISSUE THREAD

**Issue by DYMFbigdata** [ecomfe/echarts#7386]
### One-line summary [问题简述]
在线定制选择了svg渲染，但是还是渲染成canvas,不用定制的就渲染成svg

![image](https://user-images.githubusercontent.com/28290826/34404115-17a34cf0-ebe7-11e7-86d7-fa4389b8e944.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.84
+ Browser version [浏览器类型和版本]:chrome62
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by rcjiang** [comment]
你理解的有误, 在线定制包含svg渲染是指压缩后的源代码中包含此项功能, 而不是说只用svg渲染, 默认的依然是canvas, 仍然需要配置 echarts.init(yourdom, null, { renderer: 'svg' });
