### ISSUE TITLE
树状图更新数据bug

### ISSUE THREAD

**Issue by gaoshijun1993** [ecomfe/echarts#7388]
### One-line summary [问题简述]
树状图更新数据后，重新setOption，图表结构错乱，无法正常更新

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:chrome 63.0.3239.84
+ OS Version [操作系统类型和版本]:win10

### Expectation [期望效果]
更新节点数据后，图表能够局部刷新

### Other comments [其他信息]

线上实例：
http://gallery.echartsjs.com/editor.html?c=xrJkQ6mfXG&v=3

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts/issues/7315

**Comment by Adelaide1014** [comment]
http://gallery.echartsjs.com/editor.html?c=xrJkQ6mfXG&v=5

![image](https://user-images.githubusercontent.com/17764048/39557835-13a3797a-4ebd-11e8-88f2-83849b98e986.png)


![image](https://user-images.githubusercontent.com/17764048/39557848-21bb6dce-4ebd-11e8-9a90-546a23b86f68.png)

还是报错
