### ISSUE TITLE
graph图的roundRect如何设置border-radius?

### ISSUE THREAD

**Issue by AlkalizZ** [ecomfe/echarts#7393]
### One-line summary [问题简述]

看文档一圈，没找到关于roundRect设置圆角大小的配置项

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

能不能添加相应的配置项？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没法设置

**Comment by AlkalizZ** [comment]
好吧， 已经用svg解决了，谢谢

**Comment by extrame** [comment]
同求
