### ISSUE TITLE
请问树图可以设置dataZoom吗?

### ISSUE THREAD

**Issue by yanjiaquan** [ecomfe/echarts#7398]
### One-line summary [问题简述]
 我想让树图拥有inside的效果不过加入这个属性之后一直没什么反应, 是因为树图不能设置dataZoom还是我设置有问题.... 请可以设置出来的贴一下代码, 谢谢!

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/7399 ，后面会加上，谢谢建议
