### ISSUE TITLE
Tooltip 里面是否可以创建其他图，例如柱状图

### ISSUE THREAD

**Issue by HongJianMou** [ecomfe/echarts#7401]
### One-line summary [问题简述]
你好，请问ECharts 是否支持创建其他图形（柱状图或折线图）在Tooltip里面，谢谢

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以的，formatter 里可以创建，不过不建议这么做
