### ISSUE TITLE
当渲染引擎为renderer: 'svg'时, 分别设置两个独立的直方图的渐变色,后一个直方图的渐变色会覆盖前一个图形设置的值.

### ISSUE THREAD

**Issue by hnboy2005** [ecomfe/echarts#7404]
### One-line summary [问题简述]
当渲染引擎为renderer: 'svg'时, 分别设置两个独立的直方图的渐变色,后一个直方图的渐变色会覆盖前一个图形设置的值.
如果是Canvas则没有这个问题.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.4
+ Browser version [浏览器类型和版本]: Chrome 63 正式版
+ OS Version [操作系统类型和版本]: MacOS 10.13.2

### Expected behaviour [期望结果]
两个直方图的渐变色分别独立,不相互影响.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/3166227/34473632-27a17a4c-efb0-11e7-9bd9-0cf2ecc4c459.png)

**Comment by Ovilia** [comment]
@hisune 请给出完整的测试代码。

我按下面的测试代码测试，没有能复现出问题：

```
var chart = echarts.init(document.getElementById('main'), null, {
    renderer: 'svg'
});

chart.setOption({
    xAxis: {
        data: ['a', 'b']
    },
    yAxis: {},
    series: [{
        type: 'bar',
        data: [{
            value: 2,
            itemStyle: {
                normal: {
                    color: new echarts.graphic.LinearGradient(
                        0, 0, 0, 1,
                        [{
                            offset: 0,
                            color: 'red'
                        }, {
                            offset: 1,
                            color: 'blue'
                        }]
                    )
                }
            }
        }, {
            value: 1,
            itemStyle: {
                normal: {
                    color: new echarts.graphic.LinearGradient(
                        1, 0, 0, 0,
                        [{
                            offset: 0,
                            color: 'red'
                        }, {
                            offset: 1,
                            color: 'blue'
                        }]
                    )
                }
            }
        }]
    }]
});
```

渲染结果（SVG）：

<img width="526" alt="2018-01-09 10 56 43" src="https://user-images.githubusercontent.com/779050/34703024-d3b0ab98-f52b-11e7-81a3-358d9d9f92a2.png">

**Comment by hnboy2005** [comment]
@Ovilia  谢谢你的回复 我想表达的是问题出现在两个图表之间,而不是一个图表的两个柱子之间,
我写了一份范例代码 你可以看一下:
https://codepen.io/anon/pen/baaXKP

**Comment by Ovilia** [comment]
@hnboy2005 明白了，谢谢反馈

**Comment by Ovilia** [comment]
@hnboy2005 已在 https://github.com/ecomfe/zrender/commit/6426e9633ed473ec4d646a69c869f65442877d89 修复，下个版本上线。
