### ISSUE TITLE
echarts version is too old

### ISSUE THREAD

**Issue by HelenGuohx** [ecomfe/echarts#7410]
### One-line summary [问题简述]

echarts version is too old, needs 3.8.5 or higher

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:echarts@3.7.2 zrender@3.6.3 --save
+ Browser version [浏览器类型和版本]:Google Chrome 版本 63.0.3239.84
+ OS Version [操作系统类型和版本]: macOS Sierra 版本10.12.3 (16D30)

### Expected behaviour [期望结果]

echarts@3.7.2 zrender@3.6.3 安装的版本这个能够有效

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
用了最新版本的 ECharts GL？如果是的话需要最新版本的 ECharts
