### ISSUE TITLE
IE8兼容问题

### ISSUE THREAD

**Issue by snowzijun** [ecomfe/echarts#7411]
### One-line summary [问题简述]

Echarts3.8.4压缩代码在IE8上报错，但是源码并不会报错

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.8.4
+ Browser version [浏览器类型和版本]:
IE8
+ OS Version [操作系统类型和版本]:
win xp

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
报了什么错？

**Comment by liqingzheng** [comment]
这个是min版本的代码里面有t`rue ``false` `undefined`这几个是js的关键字。IE8下的js引擎会将属性名为保留关键字的作为关键字处理
具体可以看我说的[https://github.com/liqingzheng/blog/blob/master/Echarts%203.7.2%E7%89%88%E6%9C%AC%E5%85%B3%E4%BA%8E%E6%94%AF%E6%8C%81IE8%20%E7%9A%84%E4%BF%AE%E6%94%B9.md](链接)

**Comment by pissang** [comment]
@liqingzheng 谢谢反馈

**Comment by mzymcm** [comment]
sankey 图列 对象不支持“map”属性或方法
