### ISSUE TITLE
echart获取百度地图示例报错

### ISSUE THREAD

**Issue by jamesmarva** [ecomfe/echarts#7418]
### One-line summary [问题简述]

[Echarts 常用问题](http://echarts.baidu.com/faq.html#baidu-map) 中，关于如何获取百度地图的实例中：
例子代码：`chart.getModel().getComponent('bmap').getBMap()`

但是我使用代码：
`var myChart = echarts.init(document.getElementById('main'));
var baiduMap = myChart.getModel().getComponent('bmap').getBMap();
baiduMap.centerAndZoom(new BMap.Point(116.404, 39.915), 11);`

浏览器获取实例的时候报错：

`chinamap.js:428 Uncaught TypeError: Cannot read property 'getComponent' of undefined`

用的是最新的echart完整的包。
以下是引入的代码：
`<script type="text/javascript" src='static/js/jquery-3.2.1.min.js'></script>
<script type="text/javascript" src="static/js/echarts.min.js"></script>
<script type="text/javascript" src='static/js/bmap.min.js'></script>
<script src="http://api.map.baidu.com/api?v=2.0&ak=ybv6IR47eKHwgLxjeFH5SORXx0upXGUk"></script>`

我在浏览了API后，也没有找到关于：
`getModel().getComponent('bmap')`
的说明。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本] 3.8.4 :
+ Browser version [浏览器类型和版本] Google Chrom 62.0.3202.94（正式版本）  :
+ OS Version [操作系统类型和版本] windows 10:

### Expected behaviour [期望结果]
是文档没有同步修改么？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
需要先 setOption 创建 bmap 组件

**Comment by jamesmarva** [comment]
楼上的前辈正解，需要先进行setOption才能获取到bmap。
`
var option = {
    // color: ['#85b6b2', '#6d4f8d','#cd5e7e', '#e38980','#f7db88'],
    bmap: {
        center: [106.078786,32.43926],
        zoom: 5,
        roam: true,
        enableMapClick: false,
        mapStyle: {
            styleJson: []
        }
    },
    legend: {
        show: false,
        orient: 'vertical',
        right: 20,
        top: 15,
        padding: 10,
        backgroundColor: "rgba(255,255,255,0.8)",
        data: []
    },
    series:[]
};
myChart.setOption(option);
var map = myChart.getModel().getComponent('bmap').getBMap();
`
类似这样才能获取。
