### ISSUE TITLE
官网文档未更新

### ISSUE THREAD

**Issue by dazhi1011** [ecomfe/echarts#7420]
### One-line summary [问题简述]

官网文档与最新版本代码未同步，有些参数说明未更新，如`dataZoom.singleAxisIndex`等。
或者把文档提出来，添加**doc文件夹**方便大家共同维护呢？:relaxed::relaxed:

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
谢谢反馈，文档源码在 https://github.com/ecomfe/echarts-doc/tree/gh-pages/cn，欢迎提 PR:)

**Comment by dazhi1011** [comment]
@pissang :clap: 原来是我跑偏了……
