### ISSUE TITLE
axisLabel width无效

### ISSUE THREAD

**Issue by phypor** [ecomfe/echarts#7421]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/12208097/34552383-06a4d20a-f15c-11e7-83ea-284a9cda578e.png)

**Comment by pissang** [comment]
文本不会根据 width 自动换行
