### ISSUE TITLE
坐标轴设置箭头与坐标线宽的问题

### ISSUE THREAD

**Issue by Loinver** [ecomfe/echarts#7422]
### One-line summary [问题简述]
比如给Y轴设置
`axisLine: {
       lineStyle: {
       color: "#9f8d6a",
       width: 4
       },
       symbol: ['none', 'arrow'],
       symbolSize: [15, 20]
 },`
此时的箭头看起来就是这样
![image](https://user-images.githubusercontent.com/8012098/34552613-6aadc74c-f15d-11e7-9c36-65b4d48393f6.png)
是不是很奇怪
有没有设置箭头位置偏移的呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.85
+ Browser version [浏览器类型和版本]:谷歌 63
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
可以设置箭头位置偏移

**Comment by Ovilia** [comment]
@Loinver 可以，后面我加下

**Comment by Loinver** [comment]
好的，谢谢

**Comment by Ovilia** [comment]
@Loinver 修复完再 close 哈~

**Comment by Loinver** [comment]
@Ovilia  好的

**Comment by Loinver** [comment]
@Ovilia 已修复了么？

**Comment by Ovilia** [comment]
@Loinver 修复了，可以设置 symbolOffset，比如 `[-10, 20]` 表示起始端箭头往上（或左）移动 10，结束箭头往下（或右）移动 20。
只修改了 src 文件，需要使用的话要自己编译，或者等下一次发版吧~

**Comment by Loinver** [comment]
@Ovilia  好的，谢谢

**Comment by Ovilia** [comment]
后面会改进一下极坐标系等的情况
