### ISSUE TITLE
how to disable a specific serie by default

### ISSUE THREAD

**Issue by greenlevel** [ecomfe/echarts#7433]
### One-line summary [问题简述]

I use the line chart with multiple series. However when loading i want to disable 1 specific serie by default. So the label will be light grey and you have to click on the label to show the line.

I looked at the options. but i don't see anything related to that.

https://ecomfe.github.io/echarts-doc/public/en/option.html#series

Need some help. Thank you!

**Comment by pissang** [comment]
You can use http://echarts.baidu.com/option.html#legend.selected to disable the specified series

**Comment by mehmetific** [comment]
Note: When zoomed if we use legend.selected, the chart is getting reset. It must keep the zoom level same.
