### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by pennyz** [ecomfe/echarts#7434]
### One-line summary [问题简述]

安装时发现Jscript compilation error无法下载 char179598 Code800A0404

### Version & Environment [full package]
+ ECharts version [ECharts 版本]:
+ Browser version [chrome latest]:
+ OS Version [windows]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts
