### ISSUE TITLE
利用echarts中bmap绘制上海地图，隐藏地铁显示仍然出现17号线地铁

### ISSUE THREAD

**Issue by gaopeng0108** [ecomfe/echarts#7435]
### Version & Environment [版本及环境]
+ ECharts version [^3.8.5]:
+ Browser version [chrome 最新版]:
+ OS Version [MacOS 10.12.6]:

### 如图所示
应该是17号线地铁最近刚开通的原因
![image](https://user-images.githubusercontent.com/22069371/34647645-8e321558-f3c2-11e7-8d9e-c7bd4a0ea049.png)

**Comment by pissang** [comment]
这个问题可以跟百度地图反馈
