### ISSUE TITLE
仪表盘如何底部靠齐

### ISSUE THREAD

**Issue by shmilyoo** [ecomfe/echarts#7436]
### One-line summary [问题简述]
![](https://ws1.sinaimg.cn/mw690/566418e8gy1fn83wn6i3ej20cy08xt92.jpg)
仪表盘所在div的外层div是flex布局，align-items: flex-end; 并列div底部对齐方式。但是仪表盘的canvas默认是靠在所在div顶部的，radius为100%，grid设置不起作用。
请问如何让仪表盘靠在底部？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:chrome 61
+ OS Version [操作系统类型和版本]:Ubuntu 16.04

### Expected behaviour [期望结果]
仪表盘靠在底部，现在是靠在顶部

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
设置 `center` 属性

**Comment by shmilyoo** [comment]
center我知道，不过api文档里面的series-gauge中没有center，可能是漏了
如果设置center:['50%','?%'] 垂直方向设置多少才合适，能够正好贴到容器div的底部呢，而且我这里面是两个水平的仪表盘，一个大一个小，如何让它们可以在底部自动对齐？

**Comment by zmzimpl** [comment]
两年了，`center`属性也没写到文档里，写一半发现没有center属性，吓一跳
