### ISSUE TITLE
关于下载矢量地图数据陈旧

### ISSUE THREAD

**Issue by Sys-Myl** [ecomfe/echarts#7438]
### One-line summary [问题简述]
公司最近在做关于地图的项目，需要地图下钻到县级，在做地图下钻时发现原来的JSON数据有些陈旧了；现在有很多区域都重新划分了；例如：1.四川省，原来简阳市（县级）属于资阳市（地级市），现在简阳市属于成都市；2.四川省，巴中市原来的巴州区现在拆分成了恩阳区+巴州区；3.四川省，广安市原来的广安区现在拆分成了前锋区+广安区；等等。。。看看能不能更新一下地图的新的版本？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: ECharts 3.0
+ Browser version [浏览器类型和版本]: Chrome  63.0.3239.84
+ OS Version [操作系统类型和版本]: Windows 7

### Expected behaviour [期望结果]
由衷希望能更新下地图的最新数据；谢谢echarts团队的大神们啦！

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
因为审图号的问题，ECharts 不再提供地图下载。
