### ISSUE TITLE
[Bug] echarts 做实时数据更新的时候会有闪烁

### ISSUE THREAD

**Issue by DongShi** [ecomfe/echarts#7455]
### One-line summary [问题简述]
参考官方示例：
http://www.echartsjs.com/gallery/editor.html?c=dynamic-data

对比highcharts的效果
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/dynamic-update/

可以把highcharts的图形type改成 bar图，对比更明显。

可能是因为echarts底层用了canvas，每次都要擦除绘图区域？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
没看出来有闪烁，你用的什么浏览器

**Comment by DongShi** [comment]
浏览器 chrome
版本： Version 63.0.3239.132 (Official Build) (64-bit)


今天重新试了下，确实无法重现。
那天同时在跑几个webGL heavy的工程，可能导致浏览器处理变缓？
但是每个project都分散在不同的tab中，按理来说chrome应该有对应的优化。。。。

Anyway，先关掉了，后面能稳定重现了再来处理。
感谢！
