### ISSUE TITLE
K线图getOption获得的data不正确

### ISSUE THREAD

**Issue by PUGE** [ecomfe/echarts#7459]
### One-line summary [问题简述]
原始K线图数据为:
```
[
	[2320.26, 2320.26, 2287.3, 2362.94],
	[2300, 2291.3, 2288.26, 2308.38]
]
```
调用echarts.getOption()时 获取到的数据为:
```
[
	[0, 2320.26, 2320.26, 2287.3, 2362.94],
	[1, 2300, 2291.3, 2288.26, 2308.38]
]
```
导致我如果将getOption的数据修改再设置回Echarts时会导致K线图显示不正确（这是一个BUG吗）

如果不是想请教有什么好的解决办法（难道我需要判断如果图表类型是K线图并且数据数组长度为5就去掉数组第一位）

**Comment by PUGE** [comment]
使用版本为 最新echarts和最新的和最新谷歌浏览器

**Comment by git-stf-01** [comment]
那最后是怎么解决呢？

**Comment by PUGE** [comment]
@git-stf-01 4.2版本echarts不存在那个问题了
