### ISSUE TITLE
请问提示框是否可以绑定我自己获取到的设备状态信息且可以动态更新？

### ISSUE THREAD

**Issue by surick** [ecomfe/echarts#7460]
### One-line summary [问题简述]

请问提示框是否可以绑定我自己获取到的设备状态信息且可以动态更新？
![default](https://user-images.githubusercontent.com/14833969/34757144-4696e170-f60a-11e7-96b9-62f946cae755.png)
希望可以得到类似下图的结果
![default](https://user-images.githubusercontent.com/14833969/34757165-64dc9b8e-f60a-11e7-9197-96f20132e84a.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:2.0
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win7

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
请修改你的标题描述清楚你的问题

**Comment by surick** [comment]
who can help me?

**Comment by surick** [comment]
dead space
