### ISSUE TITLE
请问地图json数据什么时候可以下载， 比如 汝州县， 这种县级地图

### ISSUE THREAD

**Issue by succulen-plants** [ecomfe/echarts#7474]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by haoLingLing** [comment]
echarts  git  上有，需要你自己拼一下

![image](https://user-images.githubusercontent.com/25626661/34982906-c70d027c-fae6-11e7-94a1-7828448ce45c.png)

**Comment by succulen-plants** [comment]
明白了， 谢谢
