### ISSUE TITLE
获取Tooltip 显示的值，在图表外展示。

### ISSUE THREAD

**Issue by Yawenina** [ecomfe/echarts#7478]
### One-line summary [问题简述]

1. 折线面积图。当我在面积上任意点击某处，都会显现tooltip以及相对应的值。设置移动端的拖拽手柄，也能显示相应的额Tooltip及值。但是我监听`mousemove `, `click`, `mouseenter `, `mouseleave`事件时，并不能有效的触发该事件， 获取相应的值。

2. 当不设置标题、图例时，图表上方有一块空白区域(应该是预留给标题、图例的区域)，怎样去掉这块空白区域？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
3.8.5
+ Browser version [浏览器类型和版本]:
Google Chrome 
版本 63.0.3239.132（正式版本）
+ OS Version [操作系统类型和版本]:
macOS High Sierra 10.13.1

### Expected behaviour [期望结果]

1. 或许可以监听“showTip”事件，只要 tooltip 一显示，我就能获取到 tooltip 显示的值，在图表之外展示。
2. 没有设置`title`, `legend`的时候，能够去掉图表上部预留的空白。

### ECharts option [ECharts配置项]

```javascript
option = {
  tooltip: {
    trigger: 'axis'
  },
  xAxis: {
    type: "category",
    axisPointer: {
      handle: {
        show: true
      },
    },
    boundaryGap: false,
  }
}

```

**Comment by tudou167** [comment]
tooltip: {  
		trigger: 'item',  
		formatter: function(params) { 
// alert(JSON.stringify(params));
			return params.data.beizhu;
		}  
	},
这样能获取节点的值 你可以在节点添加自己想要的属性 不过不清楚再 trigger: 'axis' 还能不能行

**Comment by Yawenina** [comment]
@tudou167  可以的，谢谢了~

**Comment by Yawenina** [comment]
第一个问题解决方案： 使用 @tudou167 提出的 `tooltip.formatter` 解决。
第二个问题解决方案： 使用 `grid.top`， `grid.right` 等属性可以改变坐标图表的位置。
