### ISSUE TITLE
箱线图官网示例代码错误

### ISSUE THREAD

**Issue by seanfly** [ecomfe/echarts#7481]
### One-line summary [问题简述]
官网箱线图的示例，tooltip显示的数据有错误
代码错误截图：
![image](https://user-images.githubusercontent.com/13298682/34870908-905a0ec8-f7c6-11e7-8a7a-c7c4422bb5d6.png)

错误截图：
![error](https://user-images.githubusercontent.com/13298682/34870881-715ae02e-f7c6-11e7-8cc8-97680948f47a.png)

### Version & Environment [版本及环境]
官网箱线图示例地址：[http://echarts.baidu.com/demo.html#boxplot-light-velocity：](http://echarts.baidu.com/demo.html#boxplot-light-velocity)

**Comment by Ovilia** [comment]
已修复
