### ISSUE TITLE
Resize multiple charts

### ISSUE THREAD

**Issue by Kopyov** [ecomfe/echarts#7483]
I have 3 charts on 1 page, but resizing works only in the last one and works only for extending width, not when i resize browser window to smaller width. Can you please suggest a solution?

**Comment by Kopyov** [comment]
Figured out - this bug is related to flexbox layout, if i remove display: flex; from parent containers, all works fine. Otherwise i can resize the charts only in 1 direction

**Comment by chj-damon** [comment]
@pissang I think this is a bug that echarts should try to fix. because flexbox layout is now popular.

**Comment by Shonke** [comment]
@Kopyov @chj-damon 
I also encountered this problem.
Flex-grow set to 0 or fixed values can be repaired. I hope I can help you.

**Comment by Kopyov** [comment]
I kinda found a solution - adding overflow: auto; to the flex container solves the issue. Basically as far as i know this is a general fix for other libraries as well.

**Comment by chj-damon** [comment]
@Kopyov thanks for that!

**Comment by mikias10** [comment]
I was having the same issue. But there was flebox container. As a solution, during initialization, I stored each chart  to `charts` array.  And, on `window.resize()` , I looped the array and invoked `resize()` on each chart object.

```
  charts: [],
  initalizeChart(data) {
    const values = [];
    const timestamps = [];
    const self = this;

    data.forEach((item) => {
      values.push(item.value);
      timestamps.push(item.timestamp);
    });

    const option = this.setupOptions(values, timestamps);
    const chart = document.querySelector(`#${this.elementId} .chart`);
    **const myChart = window.echarts.init(chart);**

    **self.charts.push(myChart);**

    **window.onresize = function() {
      self.charts.forEach((obj) => {
        obj.resize();
      });
    };**

    myChart.setOption(option);
  },
```

**Comment by tnt-freskim-veliu** [comment]
I've fixed in this way:

**Comment by tnt-freskim-veliu** [comment]
I was using the grid for showing multiple charts, and made it responsive in this way:

In app.js (inside resources/js) I've added this part of code:
`window.allCharts = [];
window.onresize = function () {
    allCharts.forEach((chart) => {
        chart.resize();
    })
};
`

and then inside the files I've write this part of code:

**Comment by kasirye** [comment]
@tnt-freskim-veliu how can I use Echarts on a Laravel Livewire  project.

**Comment by DominikPeters** [comment]
These solutions weren't working for me. What did work was an adaptation of code posted by @plainheart at https://github.com/apache/echarts/issues/13004. I don't know how it works exactly, but it first hides all the charts, then resizes, then shows them again. In the code, `charts` should contain all echarts instances.

```js
function showChartDom(chart, visible) {
  chart.getZr().painter.getViewportRoot().style.display = visible ? "" : "none";
}

window.addEventListener("resize", resize);
function resize() {
  charts.forEach((chart) => showChartDom(chart, false));
  charts.forEach((chart) => chart.resize());
  charts.forEach((chart) => showChartDom(chart, true));
}
```
