### ISSUE TITLE
请问：graph除了重绘setoption可以怎样更新option数据？

### ISSUE THREAD

**Issue by then0917** [ecomfe/echarts#7485]
### One-line summary [问题简述]

在用graph画图的时候，需要一个鼠标滑过隐藏和展示一些节点，用setoption会引起界面抖动，鼠标滑过的节点失去焦点，请问下有什么方案可以不抖动的或者不重绘的更新option的数据呢？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
只能通过 setOption 更新数据

**Comment by tudou167** [comment]
你打印下对象 myChart._model.option.series[0].data[i] 这个里面有数据 可以尝试push一下 我还没有试过

**Comment by FEShuai** [comment]
您最后有解决方案吗？
