### ISSUE TITLE
Publish error for echarts-www

### ISSUE THREAD

**Issue by Teamop** [ecomfe/echarts#7492]
### One-line summary [问题简述]

Today when I tried to browser the examples in ecomfe.github.io, but seems the examples cannot be loaded successfully, but when I switched to http://echarts.baidu.com, seems everything is ok.

Got error for ecomfe.github.io:
```Uncaught TypeError: $container.find(...).lazyload is not a function```
seems missing jquery-lazyload.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]: Chrome latest stable
+ OS Version [操作系统类型和版本]: win 10

### Expected behaviour [期望结果]
Examples can be displayed.

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
Thanks for the feedback! Fixed now:)
