### ISSUE TITLE
echarts-examples page fails to show previews

### ISSUE THREAD

**Issue by GerardvdStelt** [ecomfe/echarts#7496]
### One-line summary [问题简述]
$container.find(...).lazyload is not a function which causes all the previews to not be visisble.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3
+ Browser version [浏览器类型和版本]: Chrome & Edge
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
No errors in browser console and previews showing

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Which page is it?

**Comment by GerardvdStelt** [comment]
https://ecomfe.github.io/echarts-examples/public/index.html

**Comment by Ovilia** [comment]
@GerardvdStelt Thanks for report! We'll follow up.
