### ISSUE TITLE
数据下载问题

### ISSUE THREAD

**Issue by juslly** [ecomfe/echarts#7497]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以打开控制台看 url

**Comment by pissang** [comment]
或者在 https://github.com/ecomfe/echarts-examples/tree/gh-pages/public/data/asset/data 也可以直接下载
