### ISSUE TITLE
升级到echart4 图列图表重叠

### ISSUE THREAD

**Issue by cuiken** [ecomfe/echarts#7502]
### One-line summary [问题简述]

升级到4后，图列滚动或者hover或者点击图列。然后出现如图现象。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/1669444/34993122-5b63db4e-fb0a-11e7-86d5-620a78f05b5e.png)

**Comment by pissang** [comment]
有可以复现的代码吗？

**Comment by cuiken** [comment]
@pissang 图列出现滚动时才会复现
` var option = {
        legend: {
            data: ["MA050K0011790223", "MA050K0011790162","MA050K0011790151","MA050K0011790189","MA050K0011790187"],
            type: 'scroll'
        },
        tooltip: {
            trigger: 'axis', axisPointer: {
                type: 'cross'
            }
        },
        grid: {
            left: '10', right: '4%', top: '20%', bottom: '3%', containLabel: true
        },
        xAxis: [{
            type: 'category',
            boundaryGap: false,
            data:["2018-01-07", "2018-01-08", "2018-01-09", "2018-01-10", "2018-01-11"],
            axisTick: {
                alignWithLabel: true
            }
        }], yAxis: [{
            type: 'value', axisLabel: {
                formatter: '{value} '
            }, name: 'kWh',
        }], series: [
            {
                name: "MA050K0011790223",
                data: [0, 33, 5, 3131, 222],
                type: 'line',
                smooth: 'true',
            },
            {
                name: "MA050K0011790162",
                data: [0, 33, 6, 3131, 222],
                type: 'line',
                smooth: 'true',

            },
            {
                name: "MA050K0011790151",
                data: [0, 33, 2, 3131, 222],
                type: 'line',
                smooth: 'true',

            },
            {
                name: "MA050K0011790189",
                data: [0, 33, 1, 3131, 222],
                type: 'line',
                smooth: 'true',

            },
            {
                name: "MA050K0011790187",
                data: [0, 33, 7, 3131, 222],
                type: 'line',
                smooth: 'true',

            }
        ]
    };`

**Comment by pissang** [comment]
我这没复现，是什么系统和浏览器

**Comment by cuiken** [comment]
@pissang 
macOS 10.13.2
Safari,Chrome,Firefox 都会复现。
<img width="548" alt="screen shot 2018-01-17 at 13 10 13" src="https://user-images.githubusercontent.com/1669444/35026754-d41e6a0e-fb87-11e7-869a-90e70b91a5f6.png">

**Comment by pissang** [comment]
好像在窗口很小的时候会复现
