### ISSUE TITLE
echats里如何在单个节点绑定多个category

### ISSUE THREAD

**Issue by tudou167** [ecomfe/echarts#7507]
myChart.on('click', function (params) {
	
});
即使是绑定点击事件也无法获取到分类的params 
            //category: 2,
            //category: 1,
            //category:[1,2] ,
也无法绑定多个节点 以上都不能绑定多个节点 

请问有其他人解决这个问题吗

**Comment by pissang** [comment]
目前不支持单个节点绑定多个 category

**Comment by tudou167** [comment]
那是否可以绑定点击事件

**Comment by pissang** [comment]
可以的

**Comment by tudou167** [comment]
myChart.on('click', function (params) {

}); 但是点击的时候 我这样获取不了信息
能麻烦说一下具体是如何获取吗 
我在myChart 里面也找不到对象

**Comment by tudou167** [comment]
应该说获取不了顶上分类的信息 节点和线没有问题 但是点击分类时没有返回

**Comment by tudou167** [comment]
我下载的是4.0.1版本
