### ISSUE TITLE
echarts 4版本微信小程序支持怎么弄？

### ISSUE THREAD

**Issue by derekhe** [ecomfe/echarts#7514]
### One-line summary [问题简述]

echarts 4版本微信小程序支持怎么弄？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0 
+ Browser version [浏览器类型和版本]: 微信小程序
+ OS Version [操作系统类型和版本]: Andriod/iOS

### Expected behaviour [期望结果]
微信小程序支持得配置文档在哪里？

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
目前还在等微信版本更新后支持，预计一个月左右上线，到时候会有相应的文档支持。

**Comment by derekhe** [comment]
好的

**Comment by bashen1** [comment]
微信都更新了，也不见个文档啥的

**Comment by Ovilia** [comment]
年后正式发布，敬请期待~

**Comment by derekhe** [comment]
都已经过年了呢～～～

**Comment by slyang520** [comment]
@Ovilia   上班第三天了  啥时候发布~~~~

**Comment by Ovilia** [comment]
在写教程了，正常的话下周就能公布了，谢谢各位支持~~

**Comment by Pridory** [comment]
为你们点赞

**Comment by czhongm** [comment]
期待中。。。

**Comment by WuHuaJi0** [comment]
希望能快点发布，因为在等着用，在线等。。

**Comment by zend** [comment]
目前是小程序和echarts互相推锅的状态，关注吧。 [捂脸.jpg]

**Comment by WuHuaJi0** [comment]
@zend 别这么说，好歹人家辛苦做的 ：）

**Comment by zend** [comment]
@WuHuaJi0 无恶意，玩笑话。非常感谢作者们的辛苦付出，如果信息可以再透明一点就好了。：）

**Comment by Pridory** [comment]
开发者们非常不容易，我们得支持他们

**Comment by yvlf** [comment]
啥时候能出哦，着急用。。。

**Comment by Ovilia** [comment]
来了来了~~
https://github.com/ecomfe/echarts-for-weixin

**Comment by Ovilia** [comment]
有问题请在 https://github.com/ecomfe/echarts-for-weixin/issues 反馈，这里先关了
