### ISSUE TITLE
官网的旭日图示例中，点击中心区域下钻后，有时如果鼠标不移出该区域，无法上钻

### ISSUE THREAD

**Issue by luguokong** [ecomfe/echarts#7518]
### One-line summary [问题简述]
http://www.echartsjs.com/gallery/editor.html?c=sunburst-book
复现方式：
在从内向外第二层某块，鼠标触发高亮后(如"心理")移动到中心位置(如"非虚构")后，点击进行下钻，此时如果鼠标不移出中心区块，无法进行上钻。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
chrome版本 63.0.3239.84（正式版本） （64 位）
Firefox57.0.4 (64 位)
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
这个不是旭日图代码的 bug，只能说是这个例子写得不好（比如应该禁用数据下钻功能）。
产生这个问题的原因是 `levels[0]` 写了 `r0: 0`，也就是最内的一层显示在圆心，这样数据下钻的时候就没有空间了。如果有需要，也可以把这个 `r0` 写大一点，留个地方给数据下钻的返回点；或者在点击时改变这个值。
