### ISSUE TITLE
不设置width，height居然不显示

### ISSUE THREAD

**Issue by toop** [ecomfe/echarts#7529]
### One-line summary [问题简述]
不设置style="width: 600px;height:400px;居然不显示，希望能解决下这个问题，有时候过来的是动态数据，无法固定大小

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.2
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]

不设置width和height也能显示

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
只要你的容器能够获取到 clientWidth 和 clientHeight 就能显示
