### ISSUE TITLE
Can Version 3.x upgrade to version 4.x without extra work?

### ISSUE THREAD

**Issue by shikelong** [ecomfe/echarts#7532]
Seem release note not talk about the migration guideline.

Regards.  😄

**Comment by fmal** [comment]
http://echarts.baidu.com/changelog.html#v4-0-0 maybe this might be a bit of help in case you haven't seen it

**Comment by pissang** [comment]
Basically you don't have to change the code when upgrading to 4.0. The biggest change is `normal`  status in `itemStyle`, `label`, `areaStyle` will be removed.

**Comment by joker-xc** [comment]
what f

**Comment by chfw** [comment]
[pyecharts](https://github.com/pyecharts/pyecharts/issues/343) found that svg renderer is limited to echarts and can not be applied to echartsgl, however, canvas is universally applicable.

**Comment by shikelong** [comment]
Thank you. 👍
