### ISSUE TITLE
你好，台湾 澳门，香港，怎么合并到中国去了

### ISSUE THREAD

**Issue by csx-java** [ecomfe/echarts#7539]
### One-line summary [问题简述]
世界地图怎么区分香港澳门

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]
跟2.0一样，香港跟中国区分开

**Comment by chfw** [comment]
1997之后就不分香港 中国了

**Comment by wynzn2009** [comment]
感觉是问题没描述清楚

**Comment by 411805576** [comment]
你怕不是有什么搞事情的想法

**Comment by tangd** [comment]
想分的话，自己改代码去吧，我不同意分

**Comment by 992013005** [comment]
如果我是开发者，我都想禁了，这个人的ip




| |
15631095293
邮箱：15631095293@163.com
|

签名由 网易邮箱大师 定制

在2018年01月22日 09:16，tangd 写道：

想分的话，自己改代码去吧，我不同意分

**Comment by bericb** [comment]
你这个需求有问题，该打回去

**Comment by LydiaHua** [comment]
@csx-java 我真的无语了, 政治竟然能渗透到技术领域, 真是一个充满民族主义的插件, 什么事情都上纲上线
@992013005 作为中国人我都感到羞愧
@bericb 你知道人家想干什么嘛? 就要给人打回去, 我现在在做一个货币汇率的功能, 你觉得这些地方的人和大陆一样都用人名币嘛?
打心眼里瞧不起你们!
