### ISSUE TITLE
如何实现自适应显示？

### ISSUE THREAD

**Issue by toop** [ecomfe/echarts#7546]
### One-line summary [问题简述]
如何响应式显示？
设置宽、高后响应失效，无法根据设备尺寸自适应

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.2
+ Browser version [浏览器类型和版本]:chrome
+ OS Version [操作系统类型和版本]:win10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by luguokong** [comment]
监听窗口resize ，在事件里执行echarts实例的resize 方法

**Comment by toop** [comment]
谢谢！
