### ISSUE TITLE
官网的文档描述错误，请纠正

### ISSUE THREAD

**Issue by pndx** [ecomfe/echarts#7547]
链接：http://echarts.baidu.com/option-gl.html#grid3D.viewControl.maxDistance

grid3D.viewControl.maxDistance number
[ default: 400 ]
视角通过鼠标控制能拉远到主体的**最小**距离。在 projection 为'perspective'的时候有效。

链接：http://echarts.baidu.com/option-gl.html#yAxis3D

yAxis3D
三维笛卡尔坐标系中的 **x** 轴。

链接：http://echarts.baidu.com/option-gl.html#zAxis3D
zAxis3D

三维笛卡尔坐标系中的 **x** 轴。

@pissang

**Comment by pissang** [comment]
已修复，谢谢反馈
