### ISSUE TITLE
移动端饼图 legend分页可不可以做成滚动的

### ISSUE THREAD

**Issue by liyihu** [ecomfe/echarts#7551]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

https://user-images.githubusercontent.com/15995111/35202588-875b0f8a-ff5e-11e7-9c1e-7969ab22fc08.png

**Comment by pissang** [comment]
http://echarts.baidu.com/examples/editor.html?c=pie-legend

**Comment by liyihu** [comment]
您好   我的意思能不能做成滚动条形式的   而不是分页按钮
