### ISSUE TITLE
4.0.2完整版设置series的itemStyle.color无效

### ISSUE THREAD

**Issue by travelalife** [ecomfe/echarts#7552]
### One-line summary [问题简述]
从官网下载地址下载的完整版，设置series的itemStyle.color后不生效，
换成精简版和源代码版都可以生效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
Echarts：4.0.2 完整版（echarts.min.js）
+ Browser version [浏览器类型和版本]:
浏览器：chrome最新版（63.0.3239.132（正式版本） （64 位））
+ OS Version [操作系统类型和版本]:
OS：win10

### ECharts option [ECharts配置项]

```javascript
option = {
title: {
            text: '',
            left: 0
        },
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            },
            formatter: function (params) {
                return params[0].seriesName + ':' + params[0].data + '<br>' +
                    params[1].seriesName + ':' + params[1].data + '<br>' +
                    params[2].seriesName + ':' + params[2].data + '<br>';
            }
        },
        grid: {
            left: '10%',
            right: '10%',
            bottom: '15%'
        },
        xAxis: {
            type: 'category',
            data: ['00:00','03:00','06:00','09:00','12:00','15:00','18:00'],
            boundaryGap: false,
        },
        yAxis: {
            type: 'value',
        },
        series: [
            {
                name: '最低价',
                type: 'line',
                data: [10,8,11,9,10,10,11],
                itemStyle: {
                    color: 'rgba(0,0,0,0)',
                }
            },
            {
                name: '最高价',
                type: 'line',
                data: [12,13,15,14,17,18,19],
                itemStyle: {
                    color: 'rgba(0,0,0,0)',
                }
            },
            {
                name: '当前价',
                type: 'line',
                data: [10,11,11,12,11,10,11]

            }]
}

```

**Comment by pissang** [comment]
我试了完整版可以的，你把使用的发一下？

**Comment by travelalife** [comment]
![_20180122124821](https://user-images.githubusercontent.com/12226635/35205736-8ee85708-ff72-11e7-8274-84d2232388af.png)

<script src="${ctx }/res/js/echarts.simple.min.js"></script>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('k-diagram'));

    // 数据意义：开盘(open)，收盘(close)，最低(lowest)，最高(highest)
    var data0 = splitData([
        <c:forEach items="${k.kLines }" var="n" varStatus="idx">
        ['${n.time}', '${n.lowestPrice}', '${n.highestPrice}', '${n.currentPrice}'],
        </c:forEach>
        ['08:00', 1.00, 1.75, 1.44],
        ['09:00', 1.01, 1.75, 1.24],
        ['10:00', 1.10, 1.45, 1.21],
        ['11:00', 0.05, 1.85, 1.44],
        ['12:00', 1.43, 1.75, 1.54],
        ['13:00', 1.20, 1.75, 1.43],
        ['14:00', 1.00, 1.64, 1.34],
        ['15:00', 0.91, 1.75, 1.44],
        ['16:00', 0.54, 1.85, 1.34],
        ['17:00', 1.23, 1.75, 1.29],
        ['18:00', 1.44, 1.75, 1.44],
        ['19:00', 0.43, 2.01, 1.84],
        ['20:00', 0.70, 1.75, 1.44],
        ['21:00', 1.41, 1.75, 1.44],
        ['22:00', 1.02, 1.83, 1.23],
        ['23:00', 0.84, 1.91, 1.41],
        ['00:00', 1.21, 1.85, 1.44],
        ['01:00', 0.80, 1.95, 1.20],
        ['02:00', 1.24, 1.75, 1.44],
        ['03:00', 0.60, 1.75, 1.24],
        ['04:00', 1.10, 1.35, 1.24],
        ['05:00', 0.46, 1.17, 1.44],
        ['06:00', 1.30, 1.75, 1.44],
    ]);

    function splitData(rawData) {
        var categoryData = [];
        var values0 = [],
            values1 = [],
            values2 = [];
        for (var i = 0; i < rawData.length; i++) {
            categoryData.push(rawData[i].splice(0, 1)[0]);
            values0.push(rawData[i][0]);
            values1.push(rawData[i][1]);
            values2.push(rawData[i][2]);
        }
        return {
            categoryData: categoryData,
            values0: values0,
            values1: values1,
            values2: values2
        };
    }

    // 指定图表的配置项和数据
    var option = {
        title: {
            text: '',
            left: 0
        },
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            },
            formatter: function (params) {
                return params[0].seriesName + ':' + params[0].data + '<br>' +
                    params[1].seriesName + ':' + params[1].data + '<br>' +
                    params[2].seriesName + ':' + params[2].data + '<br>';
            }
        },
        grid: {
            left: '10%',
            right: '10%',
            bottom: '15%'
        },
        xAxis: {
            type: 'category',
            data: data0.categoryData,
            boundaryGap: false,
        },
        yAxis: {
            type: 'value',
        },
        series: [
            {
                name: '最低价',
                type: 'line',
                data: data0.values0,
                itemStyle: {
                    color: 'rgba(0,0,0,0)',
                }
            },
            {
                name: '最高价',
                type: 'line',
                data: data0.values1,
                itemStyle: {
                    color: 'rgba(0,0,0,0)',
                }
            },
            {
                name: '当前价',
                type: 'line',
                data: data0.values2,

            }]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>
这是我的代码

**Comment by travelalife** [comment]
这是相同代码下调用不同版本的效果图：
![image](https://user-images.githubusercontent.com/12226635/35205835-36844e04-ff73-11e7-8750-11befcff9a03.png)

**Comment by pissang** [comment]
把使用的 echarts 版本代码发一下？

**Comment by travelalife** [comment]
@pissang 
是把echarts.min.js的代码发出来吗？

**Comment by pissang** [comment]
@travelalife 嗯，最好是能够确认下是否用的是 4.0.2，是的话可以传到网盘或者某个地方

**Comment by travelalife** [comment]
[echarts.min.zip](https://github.com/ecomfe/echarts/files/1650799/echarts.min.zip)

这是我使用的（错误结果的）echarts版本，即官网下载页面（http://echarts.baidu.com/download.html）的完整版








<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>管理后台</title>

    <meta name="keywords" content="">
    <meta name="description" content="">

    

    <link rel="shortcut icon" href="favicon.ico">
    
    

    <script>
        var ctx = 'http://localhost:8080';
    </script>

    <script src="http://localhost:8080/res/hplus/js/jquery.min.js?v=2.1.4"></script>

    <script src="http://localhost:8080/res/hplus/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <link href="http://localhost:8080/res/hplus/css/bootstrap.min.css?v=3.3.5" rel="stylesheet">
    <link href="http://localhost:8080/res/hplus/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="http://localhost:8080/res/hplus/css/animate.min.css" rel="stylesheet">
    <link href="http://localhost:8080/res/hplus/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="http://localhost:8080/res/hplus/css/plugins/steps/jquery.steps.css" rel="stylesheet">
    <link href="http://localhost:8080/res/hplus/css/style.min.css?v=4.0.0" rel="stylesheet">


    
	<link href="http://localhost:8080/res/hplus/css/plugins/jsTree/style.min.css" rel="stylesheet">

	<link href="http://localhost:8080/res/hplus/css/plugins/bootstrap-table/bootstrap-table.min.css" rel="stylesheet">
	<link href="http://localhost:8080/res/hplus/js/plugins/fancybox/jquery.fancybox.css" rel="stylesheet">
	<link href="http://localhost:8080/res/hplus/css/plugins/iCheck/custom.css" rel="stylesheet">

    <script src="http://localhost:8080/res/hplus/js/bootstrap.min.js?v=3.3.5"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/layer/layer.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/hplus.min.js?v=4.0.0"></script>
    <script src="http://localhost:8080/res/hplus/js/contabs.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/pace/pace.min.js"></script>

    
	<script src="http://localhost:8080/res/hplus/js/plugins/jsTree/jstree.min.js"></script>

    <script src="http://localhost:8080/res/hplus/js/plugins/jeditable/jquery.jeditable.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/footable/footable.all.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/content.min.js?v=1.0.0"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/staps/jquery.steps.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/validate/jquery.validate.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/validate/messages_zh.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/bootstrap-table/bootstrap-table-mobile.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="http://localhost:8080/res/hplus/js/demo/bootstrap-table-demo.min.js"></script>

	<script src="http://localhost:8080/res/hplus/js/plugins/layer/laydate/laydate.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/iCheck/icheck.min.js"></script>

    
	<link href="http://cdn.bootcss.com/summernote/0.8.2/summernote.css" rel="stylesheet">
	<script src="http://cdn.bootcss.com/summernote/0.8.2/summernote.min.js"></script>
	<script src="http://cdn.bootcss.com/summernote/0.8.2/lang/summernote-zh-CN.min.js"></script>

    
    <script type="text/javascript" charset="utf-8" src="http://localhost:8080/res/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="http://localhost:8080/res/ueditor/ueditor.all.min.js"> </script>
    <script type="text/javascript" charset="utf-8" src="http://localhost:8080/res/ueditor/lang/zh-cn/zh-cn.js"></script>

    <script src="http://localhost:8080/res/js/jquery.form.js"></script>
    <script src="http://localhost:8080/res/hplus/js/plugins/fancybox/jquery.fancybox.js"></script>
    <script src="http://localhost:8080/js/jquery.validate.custom.js"></script>
    <script src="http://localhost:8080/js/common.js"></script>
    <script src="http://localhost:8080/js/canvasCommon.js"></script>
    <script src="http://localhost:8080/res/js/my-hplus.js"></script>
    <script src="http://localhost:8080/res/js/k.plugin.js?v=2"></script>

    



	<link href="http://localhost:8080/res/css/my-hplus.css?v=3" rel="stylesheet">
	<link href="http://localhost:8080/res/css/edian.css?v=3" rel="stylesheet">
    <link href="http://localhost:8080/css/edian_btn.css" rel="stylesheet">
    <link rel="stylesheet" href="http://localhost:8080/css/query-form.css">

</head>


<link rel="stylesheet" href="http://localhost:8080/css/edian_tables.css">
<link rel="stylesheet" href="http://localhost:8080/css/pages/bayMarket.css">
<body class="white-bg">
<div class="wrapper wrapper-content animated fadeInRight">

    <h2>今日分时K线图</h2>
    <div id="k-diagram">

    </div>
    <div class="tb">
        <h3>实时单价（元）：<span class="num">1.21</span></h3>
        <table class="tables">
            <tbody>
            
            </tbody>
        </table>
        <table class="tables">
            <tbody>
            
            </tbody>
        </table>
    </div>

    <p class="err not_allowed">交易期间不可撤单</p>
    <div class="btns">
        <button type="button" class="btn btn-normal" onclick="turnIn()">买入</button>
        <button type="button" class="btn btn-normal" onclick="turnOut()">卖出</button>
        <button type="button" class="btn btn-normal" onclick="cancelOrder()">撤单</button>
        <button type="button" class="btn btn-normal" onclick="toMybay()">我的</button>
    </div>

</div>

<div class="temp" id="temp1">
    <div class="layer-cus-cont">
        <div class="form-group">
            <label>海贝系统中的：</label>
            <span class="num aval_points">0.00</span>
        </div>
        <div class="form-group">
            <label>本单将锁定的：</label>
            <span class="num cost_points">0.00</span>
        </div>
        <table class="tb-normal" name="turnIn">
            <thead>
            <tr>
                <th></th>
                <th>买入价格</th>
                <th>买入数量</th>
                <th>锁定</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>买一</td>
                <td class="editable">
                    <input type="text" class="form-control price money_input" placeholder="请填写">
                </td>
                <td class="editable">
                    <input type="text" class="form-control amount money_input" placeholder="请填写">
                </td>
                <td class="points">0.00</td>
            </tr>
            <tr>
                <td>买二</td>
                <td class="editable">
                    <input type="text" class="form-control price money_input" placeholder="请填写">
                </td>
                <td class="editable">
                    <input type="text" class="form-control amount money_input" placeholder="请填写">
                </td>
                <td class="points">0.00</td>
            </tr>
            <tr>
                <td>买三</td>
                <td class="editable">
                    <input type="text" class="form-control price money_input" placeholder="请填写">
                </td>
                <td class="editable">
                    <input type="text" class="form-control amount money_input" placeholder="请填写">
                </td>
                <td class="points">0.00</td>
            </tr>
            </tbody>
        </table>
        <p class="err point_err">系统中的积分不足，请在确认后重新输入</p>
        <p class="err price_err">价格不能相等，请在确认后重新输入</p>
        <div class="form-group layer-cus-btn">
            <input type="hidden" value="1">
            <button type="submit" class="btn btn-normal" onclick="sub(1, this)">确定</button>
            <button type="submit" class="btn btn-cancel" onclick="closeLayer()">取消</button>
        </div>
    </div>
</div>

<div class="temp" id="temp2">
    <div class="layer-cus-cont">
        <div class="form-group">
            <label>我的：</label>
            <span class="num aval_points">1000000.00 </span>
        </div>
        <div class="form-group">
            <label>本单将锁定：</label>
            <span class="num cost_points" id="total">0</span>
        </div>
        <table class="tb-normal" name="turnOut">
            <thead>
            <tr>
                <th></th>
                <th>卖出价格</th>
                <th>卖出数量</th>
                <th>锁定</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>卖一</td>
                <td class="editable">
                    <input type="text" class="form-control price money_input" placeholder="请填写">
                </td>
                <td class="editable">
                    <input type="text" class="form-control amount" placeholder="请填写">
                </td>
                <td class="points">0</td>
            </tr>
            <tr>
                <td>卖二</td>
                <td class="editable">
                    <input type="text" class="form-control price money_input" placeholder="请填写">
                </td>
                <td class="editable">
                    <input type="text" class="form-control amount" placeholder="请填写">
                </td>
                <td class="points">0</td>
            </tr>
            <tr>
                <td>卖三</td>
                <td class="editable">
                    <input type="text" class="form-control price money_input" placeholder="请填写">
                </td>
                <td class="editable">
                    <input type="text" class="form-control amount" placeholder="请填写">
                </td>
                <td class="points">0</td>
            </tr>
            </tbody>
        </table>
        <p class="err point_err">不足，请在确认后重新输入</p>
        <p class="err price_err">价格不能相等，请在确认后重新输入</p>
        <div class="form-group layer-cus-btn">
            <input type="hidden" value="2">
            <button type="submit" class="btn btn-normal" onclick="sub(2, this)">确定</button>
            <button type="submit" class="btn btn-cancel" onclick="closeLayer()">取消</button>
        </div>
    </div>
</div>

<div class="temp" id="temp3">
    <div class="layer-cus-cont">
        <h3>我的买入单</h3>
        <table class="tb-normal" name="turnIn">
            <thead>
            <tr>
                <th></th>
                <th>买入价格</th>
                <th>买入数量</th>
                <th>锁定</th>
                <th>撤销</th>
            </tr>
            </thead>
            <tbody>
            
            </tbody>
        </table>

        <h3>我的卖出单</h3>
        <table class="tb-normal" name="turnOut">
            <thead>
            <tr>
                <th></th>
                <th>卖出价格</th>
                <th>卖出数量</th>
                <th>锁定</th>
                <th>撤销</th>
            </tr>
            </thead>
            <tbody>
            
            </tbody>
        </table>
        <div class="form-group layer-cus-btn">
            <input type="hidden" value="3">
            <button type="submit" class="btn btn-normal" onclick="sub(3, this)">确定</button>
            <button type="submit" class="btn btn-cancel" onclick="closeLayer()">取消</button>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $(".i-checks").iCheck({checkboxClass: "icheckbox_square-green", radioClass: "iradio_square-green",})
    });

    /**
     * 公共操作
     * @param url
     */
    function operation(url) {
        layer.open({
            type: 2,
            skin: 'layui-layer-rim', //加上边框
            area: [layer_default_width, layer_default_height], //宽高
            content: ctx + url,
            btn: ['确定', '取消'],
            yes: function (index, layero) { //或者使用btn1
                var detailForm = layer.getChildFrame('form', index);

                if (detailForm.valid()) {
                    detailForm.ajaxSubmit({
                        success: function (data) {
                            if (isSuccess(data)) {
                                layer.close(index);
                                location.reload();
                            } else {
                            }
                        }
                    });
                }
            }, cancel: function (index) { //或者使用btn2
                //按钮【按钮二】的回调
            }
        });
    }


    /**
     * 公共add方法
     * @param url
     */
    function add(url) {
        operation(url);
    }

    /**
     * 公共edit方法
     * @param url
     */
    function edit(url) {
        var selections = $('#table').bootstrapTable('getAllSelections');
        if (selections.length == 0) {
            error('请选择一条记录');
            return;
        } else if (selections.length > 1) {
            error('只能选择一条记录');
            return;
        }
        var id = selections[0].id;
        operation(url+ "?id=" + id);
    }

    /**
     * 公共del方法
     * @param url
     */
    function del(url) {
        var selections = $('#table').bootstrapTable('getAllSelections');
        if (selections.length < 1) {
            error('请选择要删除的记录');
            return;
        }
        layer.confirm('确认要删除吗?', {
            icon: 3,
            title: '提示'
        }, function (index) {
            var ids = new Array();
            for (var i = 0; i < selections.length; i++) {
                ids.push(selections[i].id);
            }
            $.ajax({
                url: ctx + url,
                data: {
                    ids: ids.join(',')
                },
                success: function (data) {
                    if (isSuccess(data)) {
                        layer.close(index);
                        location.reload();
                    }
                }
            });
        });
    }
</script>

</body>
<script src="http://localhost:8080/res/js/echarts.simple.min.js"></script>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('k-diagram'));

    // 数据意义：开盘(open)，收盘(close)，最低(lowest)，最高(highest)
    var data0 = splitData([
        
        ['09:03', '0', '0', '1.21'],
        
        ['09:08', '0', '0', '1.21'],
        
        ['09:13', '0', '0', '1.21'],
        
        ['09:18', '0', '0', '1.21'],
        
        ['09:23', '0', '0', '1.21'],
        
        ['09:28', '0', '0', '1.21'],
        
        ['09:33', '0', '0', '1.21'],
        
        ['09:38', '0', '0', '1.21'],
        
        ['09:43', '0', '0', '1.21'],
        
        ['09:48', '0', '0', '1.21'],
        
        ['09:53', '0', '0', '1.21'],
        
        ['09:58', '0', '0', '1.21'],
        
        ['10:03', '0', '0', '1.21'],
        
        ['10:08', '0', '0', '1.21'],
        
        ['10:13', '0', '0', '1.21'],
        
        ['10:18', '0', '0', '1.21'],
        
        ['10:23', '0', '0', '1.21'],
        
        ['10:28', '0', '0', '1.21'],
        
        ['10:33', '0', '0', '1.21'],
        
        ['10:38', '0', '0', '1.21'],
        
        ['10:43', '0', '0', '1.21'],
        
        ['10:48', '0', '0', '1.21'],
        
        ['10:53', '1', '1', '1'],
        
        ['10:58', '1', '1', '1'],
        
        ['11:03', '1.2', '1.2', '1.2'],
        
        ['11:08', '1.2', '1.2', '1.2'],
        
        ['11:13', '0', '0', '1.21'],
        
        ['11:18', '10', '10', '10'],
        
        ['11:23', '0', '0', '1.21'],
        
        ['11:28', '1.21', '1.21', '1.21'],
        
        ['11:33', '1.21', '1.21', '1.21'],
        
        ['11:38', '0', '0', '1.21'],
        
        ['11:43', '0', '0', '1.21'],
        
        ['11:48', '0', '0', '1.21'],
        
        ['11:53', '0', '0', '1.21'],
        
        ['11:58', '0', '0', '1.21'],
        
        ['12:03', '0', '0', '1.21'],
        
        ['12:08', '0', '0', '1.21'],
        
        ['12:13', '0', '0', '1.21'],
        
        ['12:18', '0', '0', '1.21'],
        
        ['12:23', '0', '0', '1.21'],
        
        ['12:28', '0', '0', '1.21'],
        
        ['12:33', '0', '0', '1.21'],
        
        ['12:38', '0', '0', '1.21'],
        
        ['12:43', '0', '0', '1.21'],
        
        ['12:48', '0', '0', '1.21'],
        
        ['12:53', '0', '0', '1.21'],
        
        ['08:00', 1.00, 1.75, 1.44],
        ['09:00', 1.01, 1.75, 1.24],
        ['10:00', 1.10, 1.45, 1.21],
        ['11:00', 0.05, 1.85, 1.44],
        ['12:00', 1.43, 1.75, 1.54],
        ['13:00', 1.20, 1.75, 1.43],
        ['14:00', 1.00, 1.64, 1.34],
        ['15:00', 0.91, 1.75, 1.44],
        ['16:00', 0.54, 1.85, 1.34],
        ['17:00', 1.23, 1.75, 1.29],
        ['18:00', 1.44, 1.75, 1.44],
        ['19:00', 0.43, 2.01, 1.84],
        ['20:00', 0.70, 1.75, 1.44],
        ['21:00', 1.41, 1.75, 1.44],
        ['22:00', 1.02, 1.83, 1.23],
        ['23:00', 0.84, 1.91, 1.41],
        ['00:00', 1.21, 1.85, 1.44],
        ['01:00', 0.80, 1.95, 1.20],
        ['02:00', 1.24, 1.75, 1.44],
        ['03:00', 0.60, 1.75, 1.24],
        ['04:00', 1.10, 1.35, 1.24],
        ['05:00', 0.46, 1.17, 1.44],
        ['06:00', 1.30, 1.75, 1.44],
    ]);

    function splitData(rawData) {
        var categoryData = [];
        var values0 = [],
            values1 = [],
            values2 = [];
        for (var i = 0; i < rawData.length; i++) {
            categoryData.push(rawData[i].splice(0, 1)[0]);
            values0.push(rawData[i][0]);
            values1.push(rawData[i][1]);
            values2.push(rawData[i][2]);
        }
        return {
            categoryData: categoryData,
            values0: values0,
            values1: values1,
            values2: values2
        };
    }

    // 指定图表的配置项和数据
    var option = {
        title: {
            text: '',
            left: 0
        },
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            },
            formatter: function (params) {
                return params[0].seriesName + ':' + params[0].data + '<br>' +
                    params[1].seriesName + ':' + params[1].data + '<br>' +
                    params[2].seriesName + ':' + params[2].data + '<br>';
            }
        },
        grid: {
            left: '10%',
            right: '10%',
            bottom: '15%'
        },
        xAxis: {
            type: 'category',
            data: data0.categoryData,
            boundaryGap: false,
        },
        yAxis: {
            type: 'value',
        },
        series: [
            {
                name: '最低价',
                type: 'line',
                data: data0.values0,
                itemStyle: {
                    color: 'rgba(0,0,0,0)',
                }
            },
            {
                name: '最高价',
                type: 'line',
                data: data0.values1,
                itemStyle: {
                    color: 'rgba(0,0,0,0)',
                }
            },
            {
                name: '当前价',
                type: 'line',
                data: data0.values2,

            }]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>
<script>
    function turnIn() {
        layer.open({
            type: 1,
            title: '买入',
            closeBtn: 1,
            area: ['700px', '450px'],
            shadeClose: true,
            skin: 'layer-cus',
            content: $("#temp1").html()
        });
    }

    function turnOut() {
        layer.open({
            type: 1,
            title: '卖出',
            closeBtn: 1,
            area: ['700px', '450px'],
            shadeClose: true,
            skin: 'layer-cus',
            content: $("#temp2").html()
        });
    }

    function cancelOrder() {
        layer.open({
            type: 1,
            title: '挂单撤销',
            closeBtn: 1,
            area: ['850px', '570px'],
            shadeClose: true,
            skin: 'layer-cus',
            content: $("#temp3").html()
        });
    }

    function closeLayer() {
        $(".cost_points").html("0.00");
        layer.closeAll();
    }

    // 表单提交ajax
    function sub(type, ele) {
        var data_dom = $(ele).parents(".layer-cus-cont"); 
        // type，1、买入，2、卖出，3、撤单
        switch (type) {
            case 1:
            case 2:
                var points =0.0;
                var coins =1000000.0;
                var priceList = new Array();
                var amountList = new Array();
                var url;
                $(data_dom).find("input.price").each(function () {
                    if ($(this).val() != null && $(this).val() != "") {
                        priceList.push($(this).val());
                    }
                });
                $(data_dom).find("input.amount").each(function () {
                    if ($(this).val() != null && $(this).val() != "") {
                        amountList.push($(this).val());
                    }
                });
                if (priceList.length == 0 || amountList.length == 0) {
                    alert2("请填写完整信息");
                    return false;
                }

                if (parseInt(type) == 1) {
                    url = "http://localhost:8080/admin/baySystem/tradeBid";
                } else {
                    url = "http://localhost:8080/admin/baySystem/tradeAsk";
                }
                $.ajax({
                    type: 'post',
                    url: url,
                    data: {priceList: priceList.join(','), amountList: amountList.join(',')},
                    dataType: 'json',
                    success: function (data) {
                        if (isSuccess(data)) {
                            layer.closeAll();
                            location.reload();
                        }
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
                break;
            case 3:
                var turnIn = new Array();
                var turnOut = new Array();
                data_dom.find("table[name=turnIn] input[name=cancel]:checked").each(function () {
                    turnIn.push(this.value);
                });
                $(data_dom.find("table[name=turnOut]")).find("input[name=cancel]:checked").each(function () {
                    turnOut.push(this.value)
                });
                $.ajax({
                    type: 'post',
                    url: 'http://localhost:8080/admin/baySystem/cancel',
                    data: {askIds: turnOut.join(','), bidIds: turnIn.join(',')},
                    dataType: 'json',
                    success: function (data) {
                        if (isSuccess(data)) {
                            layer.closeAll;
                            location.reload();
                        }
                        layer.closeAll();
                        location.reload();
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
                break;
            default:
                alert("操作异常，请联系管理员！");
                return false;
        }

    }

    // 买入卖出校验
    function check(ele) {
        var data_dom = $(ele).parents(".layer-cus-cont");
        var cost_points = 0;
        var aval_points = $(data_dom).find(".aval_points").html();
        $(data_dom).find(".points").each(function () {
            var val = $(this).html();
            cost_points = (cost_points * 100 + parseFloat(val ? val : 0) * 100) / 100;
        });
        return cost_points <= aval_points;

    }

    //价格不能相等
    function checkPrice(priceList) {
        var bool = true;
        if (priceList.length > 1) {
            for (var i = 0; i < priceList.length - 1; i++) {
                if (priceList[0] == priceList[i + 1]) {
                    bool = false;
                    return false;
                }
            }
        }
        return bool;
    }

    // 跳转
    function toMybay() {
        parent.$('a.J_menuItem[href="http://localhost:8080/admin/baySystem/detail"]').click();
//        parent.$("li a:contains('我的')").click();
    }

    // 数量输入框只允许输入数字
    $(document).on("input", ".amount", function () {
        $(this).val(($(this).val()).replace(/\D/g, ''));
    });

    // 点击撤销表格时触发表格内多选框点击事件
    $(document).on("click", ".checktd", function () {
        var check = $(this).find("input").prop("checked");
        $(this).find("input").prop("checked", !check);
    });

    // 阻止冒泡
    $(document).on("click", ".checktd input", function (e) {
        e.stopPropagation();
    });

    // 买入卖出输入框变化时计算总数并显示警告内容
    $(document).on("input", ".price, .amount", function () {
        var price = $(this).parents("tr").find(".price").val();
        var amount = $(this).parents("tr").find(".amount").val();
        if (!price || !amount) {
            return false;
        }
        var type = $(this).parents(".tb-normal").attr("name");
        if (type == "turnIn") {
            var total = ((parseFloat(price ? price : 0) * 100 * parseFloat(amount ? amount : 0)) / 100).toFixed(2);
            $(this).parents("tr").find(".points").html(total);

        } else {
            $(this).parents("tr").find(".points").html(amount);
        }

        var totalamount = 0;
        $(this).parents(".tb-normal").find(".points").each(function () {
            totalamount += parseFloat($(this).html());
        });
        $(this).parents(".tb-normal").prev(".form-group").find(".cost_points").html(totalamount);
        check($(this)) ? $(".point_err").hide() : $(".point_err").show();
    })
    //价格验证,价格不能相同
    $(document).on("click", "div.layer-cus-btn .btn-normal", function () {
        var type = $(this).prev().val();
        if (type == 1 || type == 2) {
            var priceList = new Array();
            var data_dom = $(this).parents(".layer-cus-cont")
            $(data_dom).find("input.price").each(function () {
                if ($(this).val() != null && $(this).val() != "") {
                    priceList.push($(this).val());
                }
            });
        }
        checkPrice(priceList) ? $(".price_err").hide() : $(".price_err").show();
    })
</script>
</html>

**Comment by pissang** [comment]
[test.zip](https://github.com/ecomfe/echarts/files/1650821/test.zip)

我拿你发的代码试了下没什么问题

**Comment by travelalife** [comment]
@pissang 
好吧，大概是和我引的其他文件里的东西某些冲突了，关掉吧
