### ISSUE TITLE
关于legend.data属性

### ISSUE THREAD

**Issue by Makerpol** [ecomfe/echarts#7559]
### 关于legend.data属性的作用，不是很明白.
`[饼图](http://www.echartsjs.com/gallery/editor.html?c=pie-legend)官方实例中，下面的代码：
```
data: data.legendData,
```
这一句代码在这个过程中起到了什么作用呢？

**Comment by pissang** [comment]
设置了图例的数据？

**Comment by Makerpol** [comment]
图例是指饼图旁边的那一排。了解，感谢！
