### ISSUE TITLE
legend中data项太多,如何控制显示几个，且收起其他

### ISSUE THREAD

**Issue by YouToBeYourself** [ecomfe/echarts#7566]
### One-line summary [问题简述]
当legend中data项太多时，展示出现堆积，不美观，整洁问题。
1.是否可以控制显示n个图例，收起其他图例，当鼠标经过收起icon时，可以以下拉列表形式展示
2.如果1不可行，那么是否可以有接口可以获取到各个legenddata中的颜色，放在图外，同时提供接口控制显示隐藏某个图例

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
参见<http://echarts.baidu.com/examples/editor.html?c=pie-legend>

**Comment by YouToBeYourself** [comment]
thank you !
