### ISSUE TITLE
关于旭日图块排列问题

### ISSUE THREAD

**Issue by zetakv** [ecomfe/echarts#7570]
### One-line summary [问题简述]
每层的数据都必须以从大到小的排列吗？不能以data中数据的顺序排列？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.02
+ Browser version [浏览器类型和版本]:chrome63
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
生成的图型可按照data中数据顺序排列，而不是固定value从大到小

### ECharts option [ECharts配置项]

```javascript
option = {
[
name: '111',
value: 1
],
[
name: '222',
value: 0.5
],
[
name: '333',
value: 3
],
}

```

**Comment by Ovilia** [comment]
可以用 `series.sort` 控制排序方式，默认的 `'desc'` 降序排列，还可以设为 `'asc'` 升序排列、`null` 使用原数据的顺序、回调函数控制排序。

发现文档里忘记写了，抱歉，过会儿我补上。

**Comment by zetakv** [comment]
@Ovilia 可以了，感谢！····
方便的话看一下我发的另一个关于旭日图的问题,关于颜色渐变的.

**Comment by Ovilia** [comment]
@zetakv 嗯嗯，在看了。
