### ISSUE TITLE
Sunburst only works if you import visualMap

### ISSUE THREAD

**Issue by jonavila** [ecomfe/echarts#7575]
### One-line summary [问题简述]
When using echarts 4 with a module bundler like Webpack, the sunburst will chart will not work if visualMap component is not imported

The following error is seeing in the console:
```Uncaught TypeError: Cannot read property 'length' of undefined```

Seems to be failing in this if statement:
https://github.com/ecomfe/echarts/blob/6a86e0227600f72f4c087ce90c3d2780ec67f7a1/src/chart/sunburst/SunburstPiece.js#L306

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
Sunburst should work without including visualMap

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
@pissang How can I fix this?

**Comment by pissang** [comment]
Add a condition to avoid the case there is no `visualMap` component.

```js
if (! visualMetaList || visualMetaList.length === 0) {
...
}
```
