### ISSUE TITLE
关于现echarts4.0是否支持微信小程序的适配？

### ISSUE THREAD

**Issue by hoganjobs** [ecomfe/echarts#7576]
### One-line summary [问题简述]
您好，关于现echarts4.0是否已支持支持微信小程序的适配？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by blockmood** [comment]
见 #7514

**Comment by Ovilia** [comment]
现已支持，请参见：https://github.com/ecomfe/echarts-for-weixin
