### ISSUE TITLE
此种漏斗图能否实现？

### ISSUE THREAD

**Issue by sdtazhanghe** [ecomfe/echarts#7577]
### One-line summary [问题简述]
现在，牛逼的产品经理想要这个自行车，，，能不能给造？
![image](https://user-images.githubusercontent.com/28133347/35261065-7b50216c-0049-11e8-8ee3-cdcce9367bf7.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jamesmarva** [comment]
感觉这个不像是漏斗图，更像是一种横向的柱状图啊。

**Comment by sdtazhanghe** [comment]
对，感觉挺麻烦应该
