### ISSUE TITLE
axisTick怎么可以设置成直尺那种样式

### ISSUE THREAD

**Issue by Long-Dress** [ecomfe/echarts#7580]
每隔几个，刻度的长度会比其他的长些。

**Comment by Mying666** [comment]
用双轴可以实现吧

**Comment by Mying666** [comment]
http://gallery.echartsjs.com/editor.html?c=xS1K2uiHSz
可以参考一下

**Comment by Mying666** [comment]
![image](https://user-images.githubusercontent.com/28644984/35317848-b0c11d22-0113-11e8-8a48-3a5a5e2789ff.png)
