### ISSUE TITLE
饼状图 标签重叠在一起 怎么处理？

### ISSUE THREAD

**Issue by azbo** [ecomfe/echarts#7584]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/5110699/35266922-a58de3cc-005f-11e8-9f91-b9fa3729e5f0.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
用最新版的 ECharts 应该没有这个问题了

**Comment by davinma** [comment]
可以修改 startAngle 角度起始值试试
