### ISSUE TITLE
4.0.2版本series里的rotate没有效果(svg渲染)

### ISSUE THREAD

**Issue by kevinceHH** [ecomfe/echarts#7586]
### One-line summary [问题简述]

4.0.2版本使用svg渲染，在柱状图上series里的rotate并没有旋转的效果呈现，我使用的ie8，不兼容了吗？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.2
+ Browser version [浏览器类型和版本]:360安全浏览器，IE8
+ OS Version [操作系统类型和版本]:windows7专业版

### Expected behaviour [期望结果]
期望能够改进

### ECharts option [ECharts配置项]

```javascript
echarts.init(document.getElementById('showList'),null, {renderer: 'svg'});
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        label:{
            show:true,
            position:'top',
            rotate:40,
        },
        type: 'bar'
    }]
}

```

### Other comments [其他信息]

![360 20180123170455212](https://user-images.githubusercontent.com/35723953/35267460-50e6019a-0061-11e8-9a51-ac32bca8cecb.jpg)

**Comment by Ovilia** [comment]
我会跟进看一下哈~

**Comment by Ovilia** [comment]
已修复，下个版本上线，谢谢支持！@kevinceHH
