### ISSUE TITLE
vendor.js:241428 Uncaught Error: Component series.liquidFill not exists. Load it first.

### ISSUE THREAD

**Issue by succulen-plants** [ecomfe/echarts#7589]
### Version & Environment [版本及环境]
+ ECharts version [4.0.2]:
+ Browser version [chrome]:
+ OS Version [mac10.1]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
需要加载 https://github.com/ecomfe/echarts-liquidfill 水球图组件

**Comment by succulen-plants** [comment]
加载了， echarts 4.0.2；   echart-liquidfill 1.1.1
import echarts from 'echarts';
import liquidFill from 'echarts-liquidfill';
