### ISSUE TITLE
Missing Docs: Sunburst label->rotate can be set to 'tangential', 'radial', or number

### ISSUE THREAD

**Issue by jonavila** [ecomfe/echarts#7591]
### One-line summary [问题简述]
The sunburst series has the option of setting the label.rotate property to 'tangential', 'radial' or the documented number value.

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]
Add the string options for 'tangential' and 'radial' in docs

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
Thanks for report! I'll update later.
