### ISSUE TITLE
下图如何用echarts实现

### ISSUE THREAD

**Issue by why007** [ecomfe/echarts#7607]
### One-line summary [问题简述]
就是想要上面是柱状图，下面对应的如图所示的格式

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![1516847505 1](https://user-images.githubusercontent.com/28586778/35367795-42ce9832-01bb-11e8-83a4-52a332fe4338.png)

**Comment by Ovilia** [comment]
http://gallery.echartsjs.com/editor.html?c=xBk7TY_hWx
