### ISSUE TITLE
如何在微信小程序中使用Echart4.0

### ISSUE THREAD

**Issue by 719872045** [ecomfe/echarts#7610]
### One-line summary [问题简述]
如何在微信小程序中使用Echart4.0

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echart4.0
+ Browser version [浏览器类型和版本]:谷歌浏览器
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
能够在微信小程序中使用Echart4.0

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/7514

**Comment by Ovilia** [comment]
现已支持，请参见：https://github.com/ecomfe/echarts-for-weixin
