### ISSUE TITLE
旭日图能设置文字可视最小角度吗？或如何让文字在点击到扇块时才显示？

### ISSUE THREAD

**Issue by zetakv** [ecomfe/echarts#7614]
### One-line summary [问题简述]

有些饼块的角度不够，容纳不下文字，formatter中隐藏后，不知道怎么在点击下挖中重新显示，请问有没有相关的API？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by zetakv** [comment]
还有一个问题，旭日图是不是还不支持tooltip？

**Comment by Ovilia** [comment]
tooltip 刚支持，下个版本上线。
下钻后可以给你一个回调函数，觉得 ok 不？

**Comment by zetakv** [comment]
@Ovilia 
感谢大佬。
我现在是禁用下钻并监听click事件然后重新渲染了图形，还算是可以实现了

**Comment by Ovilia** [comment]
@zetakv 下个版本上线，可以通过 label.minAngle 设置，当扇形块的角度（角度制）小于该值时，对应的文字不显示。
