### ISSUE TITLE
4.0 定制的版本不支持svg渲染

### ISSUE THREAD

**Issue by JunweiHu-ITClub** [ecomfe/echarts#7619]
### Version & Environment [版本及环境]
+ ECharts version [ECharts4.0]:
+ Browser version [谷歌 63.0.3239.132]:
+ OS Version [win10]:

### Expected behaviour [以svg渲染]

###init[var count = echarts.init(document.getElementById('manage-count'),null,{renderer: 'svg'})]
### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
下面勾上 svg 了吗？

**Comment by JunweiHu-ITClub** [comment]
肯定勾上了，，，，，你下载个demo  试试

**Comment by JunweiHu-ITClub** [comment]
@pissang

**Comment by pissang** [comment]
好像是有这个问题，谢谢反馈，我们修复一下

**Comment by pissang** [comment]
@JunweiHu-ITClub  已修复
