### ISSUE TITLE
echarts 能支持小程序吗？

### ISSUE THREAD

**Issue by wj811** [ecomfe/echarts#7624]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见https://github.com/ecomfe/echarts/issues/7514

**Comment by Ovilia** [comment]
现已支持，请参见：https://github.com/ecomfe/echarts-for-weixin
