### ISSUE TITLE
柱状图自适应时的一个小问题

### ISSUE THREAD

**Issue by three-ago-zhou** [ecomfe/echarts#7630]
### One-line summary [问题简述]
Bar图表自适应的情况下感觉在根据canvas在做居中变化，能否增加一个bar图表的配置让其不做居中自适应，或者是否已经有了这个配置项。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.1
+ Browser version [浏览器类型和版本]: Google Chrome 63.0.3239.132 (正式版本)  (64位)
+ OS Version [操作系统类型和版本]:  macOS high Sierra 版本(10.13.2)

### Expected behaviour [期望结果]
PC端希望柱状图根据屏幕宽度自适应的情况下，柱状图左侧（或者说整个Bar图表）能够不会有一种在居中的感觉，而是贴着左边或者是充满这个canvas在自适应。

现在的感觉就是下面这个，图表在自适应过程中在根据宽度居中，左侧在明显的一直变化，图表在居中。
http://echarts.baidu.com/examples/editor.html?c=bar1

希望类似这个左侧的效果，自适应式左侧保持不动。能够有一种填满canvas的感觉。
http://echarts.baidu.com/examples/editor.html?c=scatter-punchCard

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
可以通过设置 [grid](http://echarts.baidu.com/option.html#grid) 的 `left`、 `right`、 `top`、 `bottom` 控制图表绘图区，可是是百分比或像素数值。
