### ISSUE TITLE
有深圳的前端吗，招一个2+年前端

### ISSUE THREAD

**Issue by jiangtu2018** [ecomfe/echarts#7634]
有深圳的前端吗，招一个2+年前端
有深圳的前端吗，招一个2+年前端
小写LT2468LT   ，微信
小写LT2468LT   ，微信
小写LT2468LT   ，微信
有深圳的前端吗，招一个2+年前端

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by jiangtu2018** [comment]
小写LT2468LT   ，微信

**Comment by jiangtu2018** [comment]
有深圳的前端吗，招一个2+年前端
有深圳的前端吗，招一个2+年前端
小写LT2468LT，信微
小写LT2468LT，信微
小写LT2468LT，信微
有深圳的前端吗，招一个2+年前端

**Comment by BlackBerserker0xff** [comment]
楼主给毅神交了广告费了么，哈哈
