### ISSUE TITLE
如何在django项目中将mysql数据库查询到的数据插入到echarts中

### ISSUE THREAD

**Issue by Vickey-Wu** [ecomfe/echarts#7635]
### Version & Environment [版本及环境]
+ ECharts 4.02源码:
+ Chrome 63.x 64位:
+ win7 旗舰版:

### Expected behaviour [期望结果]
代码展示在echarts中如何插入查询到的数据

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 [五分钟上手](http://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts) 和 [dataset教程](http://echarts.baidu.com/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE)

**Comment by Vickey-Wu** [comment]
cool，用pyecharts可以动态插入数据了。不过又有了新问题，怎么将生成的pyecharts.html嵌入到一个另一个html（exam: home.html），当访问home.html时可以显示2个页面的内容，直接include没效果{% include "app/pyecharts.html" %}我想是因为没有在views.py中调用生产pyecharts.html的方法，如果可以，麻烦提供下思路，谢谢

**Comment by chfw** [comment]
DIY 请参照： http://pyecharts.org/#/zh-cn/django
懒一懒，请参照： https://github.com/kinegratii/django-echarts

**Comment by Vickey-Wu** [comment]
说实话，django-echarts没搞懂咋用。。后来在[这里](https://www.youtube.com/watch?v=nWRboXrcipU&index=5&list=PLQVvvaa0QuDeA05ZouE4OzDYLHY-XH-Nd)看到可以将Python变量传到html，试了下就成功了。
