### ISSUE TITLE
像这种特殊的饼图有办法实现吗？

### ISSUE THREAD

**Issue by zetakv** [ecomfe/echarts#7648]
![voronoi-bitcoin_2-7b4d](https://user-images.githubusercontent.com/14759296/35501222-4a693d34-0514-11e8-83cf-62bfb9cefeaa.png)

![world-gdp-updated-f4f4](https://user-images.githubusercontent.com/14759296/35501250-605d0a1c-0514-11e8-8df6-5592a1b4315f.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
用[自定义系列](http://echarts.baidu.com/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B3%BB%E5%88%97)自己实现吧，切割的算法需要自己实现

**Comment by zetakv** [comment]
明白了，谢谢~

**Comment by pissang** [comment]
可以参考这个 Circle Packing 的例子 http://gallery.echartsjs.com/editor.html?c=xHyzR8UUNb
