### ISSUE TITLE
用echarts customs系列 自定义图形, 需要绘制虚线, 但是没有发现对应的api方法

### ISSUE THREAD

**Issue by Mmpc1994** [ecomfe/echarts#7652]
### 用echarts customs系列 自定义图形, 需要绘制虚线, 但是没有发现对应的api方法. 考虑用api.style()方法, 但无法找到对应参数, 请问应该用其他方法么, 或者还有什么额外的参数.

echart 版本 3.6.2 echarts.common.js
mac os
谷歌浏览器

![image](https://user-images.githubusercontent.com/17062182/35505836-4f820b6c-0522-11e8-8a1d-03cdf954991e.png)

**Comment by Ovilia** [comment]
http://echarts.baidu.com/option.html#series-custom.itemStyle.borderType 这个？

**Comment by BookChan** [comment]
请问可以画吗？我用borderType:"dotted" 还是不行

**Comment by BookChan** [comment]
应该是在  series 里面设置 。 
itemStyle:{
normal:{
 borderType: "dashed"
}
}

**Comment by lemon0815** [comment]
如果需要return_group,但是需要不同的borderType，怎么设置?
