### ISSUE TITLE
关于echarts的自适应

### ISSUE THREAD

**Issue by kaiyuanbaba** [ecomfe/echarts#7657]
echarts怎么根据屏幕的大小来显示多个曲线图，我用的 window.addEventListener("resize", function () {                        option.chart.resize();                    });不起作用啊

**Comment by pissang** [comment]
请具体描述问题

**Comment by kaiyuanbaba** [comment]
有多个曲线图，移动浏览器的大小，曲线图适应浏览器（浏览器变小，曲线图变小，反之，浏览器变大，曲线图变大）。

**Comment by pissang** [comment]
你要先保证你的容器宽度是自适应而不是写死的

**Comment by kaiyuanbaba** [comment]
我设置宽度为100%，曲线图怎么是100px啊，这个是怎么回事啊

**Comment by pissang** [comment]
你不具体描述我也不知道是怎么回事

**Comment by kaiyuanbaba** [comment]
我用echart做的曲线图，我想让曲线图根据浏览器的大小来改变曲线图的大小，我之前是获取屏幕的宽度(document.body.clientWidth),但是这个方法必须重新刷新浏览器的时候曲线图才变小，我换个一个方法就是设置曲线图的宽度为100%，结果是曲线图就以100px显示。我在网上搜索的结果是用window.addEventListener("resize", function () { option.chart.resize(); });这个方法，但是我用了之后，这个方法不起效果。我现在想做成放大浏览器，曲线图变大，反之变小，这个方法怎么做啊？

**Comment by pissang** [comment]
因为你初始化图表的时候 echarts 获取不到容器的宽度（比如容器是隐藏的）需要容器有宽度后调用一下 resize

**Comment by kaiyuanbaba** [comment]
容器的宽度我设置成document.body.clientWidth这样，但是resize也不起作用啊

**Comment by pissang** [comment]
你设成 clientWidth 不就写死了么

**Comment by kaiyuanbaba** [comment]
那应该怎么设置啊
