### ISSUE TITLE
是否可以提供一个全局的默认renderer设置

### ISSUE THREAD

**Issue by troy351** [ecomfe/echarts#7660]
### One-line summary [问题简述]

默认的renderer为canvas，是否可以将其可配置化。
如默认为svg，而不用每个实例声明的时候都设置一遍？

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.1
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这个还真有....有一个 `__ECHARTS__DEFAULT__RENDERER__` 的环境变量

**Comment by troy351** [comment]
@pissang 看了下代码好像只有在`__DEV__`下才有，压缩过的包里面没有

**Comment by pissang** [comment]
嗯，是的，开始是为了我们自己方便调试用的
