### ISSUE TITLE
旭日图高亮问题

### ISSUE THREAD

**Issue by DoubleHYH** [ecomfe/echarts#7662]
### One-line summary [问题简述]
鼠标第一次移动到旭日图上是可以触发高亮，但之后就无法触发了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by Ovilia** [comment]
已修复这个问题，下个版本发布
