### ISSUE TITLE
实例的getModel().getComponent("组件名")是否已经无效？

### ISSUE THREAD

**Issue by zhangby01** [ecomfe/echarts#7667]
### One-line summary [问题简述]

我使用chart.getModel().getComponent("mapbox")，返回的是undefined，请问这种获取组件方法是否已经失效，更换为其他方法了？还是这个方法存在bug？

### Version & Environment [版本及环境]
+ ECharts version: 4.0.2
+ ECharts-gl version: 1.0.1
+ Browser version: Chrome x64 63.0.3239.132
+ OS Version: Windows 10 x64

### Expected behaviour [期望结果]

chart.getModel().getComponent("mapbox")，应该返回mapbox的实例，我需要根据这个继续访问并控制mapbox。

### ECharts option [ECharts配置项]

```javascript
option = {
    mapbox: {
        center: [103, 35],
        zoom: 10,
        pitch: 60,
        style: "mapbox://styles/mapbox/streets-v10"
    },
    series: [{
        name: "test",
        type: "bar3D",
        coordinateSystem: "mapbox",
        barSize: 0.5,
        data: [{
            name: "test01",
            value: [103, 35, 100]
        }]
}

```

**Comment by pissang** [comment]
1.0.0 开始 `mapbox` 改为了 `mapbox3D`

**Comment by zhangby01** [comment]
谢谢
