### ISSUE TITLE
4.0版本主题坐标轴标签颜色设置项axisLabel无效

### ISSUE THREAD

**Issue by es3154** [ecomfe/echarts#7675]
### One-line summary [问题简述]

4.0版本主题坐标轴标签颜色设置项axisLabel无效

现有主题设置
"axisLabel": {
                "show": true,
                "textStyle": {
                    "color": "#eeeeee"
                }
            },

修改如下：
"axisLabel": {
                "show": true,
                "color": "#eeeeee",
                "textStyle": {
                    "color": "#eeeeee"
                }
            },
也就是说需要增加color属性

### Version & Environment [版本及环境]
+ ECharts version [4.02]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
3.7.0 开始 textStyle 这个层级被移除了，见 http://echarts.baidu.com/changelog.html#v3-7-0 ，之前有做兼容，但是 4.0 这个兼容有点问题，已经在最新代码中修复

**Comment by es3154** [comment]
好的
