### ISSUE TITLE
一个页面有多个图表，每个图表都要根据窗口大小缩放怎么做

### ISSUE THREAD

**Issue by dlzxl** [ecomfe/echarts#7678]
### One-line summary [问题简述]
一个页面放了多个图表，有面积图，有折线图，有饼图，每一个图表的setOption后面都写了window.onresize=chartXX.resize;但是只有最后一个会随窗口变化而变化，其余图标都没自适应，这是为什么？有什么方法可以让每个图表都自适应（每个图表占屏幕宽度不一，如：面积图占100%，折线图占50%，饼图占50%）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3
+ Browser version [浏览器类型和版本]:Google 49.0.2623.87
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![default](https://user-images.githubusercontent.com/19336864/35607535-9b1d836c-068f-11e8-84f7-6f40b5431e3a.png)

**Comment by Ovilia** [comment]
假设图表在数组 `charts` 中
```js
window.onresize = function() {
    for (var i = 0; i < charts.length; ++i) {
        charts[i].resize();
    }
};
```
