### ISSUE TITLE
如何使得柱状图上的数值倾斜？

### ISSUE THREAD

**Issue by JackZhouMine** [ecomfe/echarts#7680]
### One-line summary [问题简述]
柱状图比较多，数值比较大的情况下，柱状图上显示的数值会重叠，能为这个数值设置一个较小的字体，但是字体变得太小也不好，请问能不能使得柱状图的数值倾斜一个角度，使得数值分开一些呢？

![tim 20180131165030](https://user-images.githubusercontent.com/21340150/35613405-f0858aae-06a6-11e8-862d-e2c1bf2d51a6.png)

**Comment by pissang** [comment]
参考 http://www.echartsjs.com/gallery/editor.html?c=bar-label-rotation
