### ISSUE TITLE
ie8下可运行的demo

### ISSUE THREAD

**Issue by guxingke201** [ecomfe/echarts#7682]
### One-line summary [问题简述]
[2.0时存在demo](http://echarts.baidu.com/echarts2/doc/example/line1.html)可以直接在ie8,ie9下运行，4.0找不到了

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]:ie8,ie9
+ OS Version [操作系统类型和版本]:win7

### Expected behaviour [期望结果]

* 4.0有可以直接在ie8,ie9下运行的demo

* 有地方查询不兼容低版本ie的功能

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

2.0：http://echarts.baidu.com/echarts2/doc/example/line1.html
4.0：http://echarts.baidu.com/examples/editor.html?c=line-simple

**Comment by pissang** [comment]
你按照[教程](http://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts)新建一个最简单的例子就可以在 IE8 下运行了
