### ISSUE TITLE
echarts4.0现在已经支持小程序了吗？

### ISSUE THREAD

**Issue by lxg1208** [ecomfe/echarts#7683]
echarts4现在是否已经支持小程序了？没找到说明或者例子啊

**Comment by EasingLab** [comment]
应该没有，肯定是忽悠下老板的 ，年底了你懂的

**Comment by pissang** [comment]
见 https://github.com/ecomfe/echarts/issues/7514

**Comment by Ovilia** [comment]
现已支持，请参见：https://github.com/ecomfe/echarts-for-weixin
