### ISSUE TITLE
移动端axisPointer是否可以自动隐藏？

### ISSUE THREAD

**Issue by MrLiZ** [ecomfe/echarts#7684]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]: h5
+ OS Version [操作系统类型和版本]: android7.1

**Comment by MrLiZ** [comment]
用自己的方法解决了

**Comment by Say-Hello** [comment]
@MrLiZ 我也遇到了这个问题，请问你是怎么解决的呢

**Comment by MrLiZ** [comment]
@Say-Hello 监听手指离开屏幕的事件，然后把axisPointer线宽设置为0.
