### ISSUE TITLE
react-redux 项目，引用的echarts，使用点击事件，无法获取更新的state

### ISSUE THREAD

**Issue by lettywiterock** [ecomfe/echarts#7686]
使用了react-redux项目，redux更新state数值，在页面调用了监听事件，打印state值，可以显示，在监听内部，打印，为空。
但是打印显示有占位，展开，无值，这是什么原因，redux无法更新监听的数值么？

**Comment by pissang** [comment]
问题跟 echarts 无关，你可以去相关项目的 issue 下咨询
