### ISSUE TITLE
多张图表的切换如何实现

### ISSUE THREAD

**Issue by newsweet** [ecomfe/echarts#7688]
### One-line summary [问题简述]
现在有多组数据，希望点击某个按钮后显示不同数据的图表，实现思路是怎样

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:Echarts3
+ Browser version [浏览器类型和版本]:FireFox
+ OS Version [操作系统类型和版本]:Windows 10

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
见 [异步数据加载和更新](http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0)
