### ISSUE TITLE
v4.0.2 多图标resize报错

### ISSUE THREAD

**Issue by authasme** [ecomfe/echarts#7695]
### One-line summary [问题简述]
vue+echarts,resize失败，Schedule.js 159行空指针异常。
规律：页面有一个图表时，resize正常，当出现2个以上图表时，只有其中一个resize正常，其他的都报相同的错误

调用resize的方法：myChart.resize(); 

错误信息：
```
vue.esm.js?efeb:1717 TypeError: Cannot read property 'seriesTaskMap' of null
    at eval (Scheduler.js?bee6:159)
    at Array.forEach (<anonymous>)
    at each (util.js?fe0c:298)
    at performStageTasks (Scheduler.js?bee6:152)
    at Scheduler.proto.performDataProcessorTasks (Scheduler.js?bee6:137)
    at ECharts.update (echarts.js?21c7:739)
    at refresh (echarts.js?21c7:974)
    at ECharts.echartsProto.resize (echarts.js?21c7:968)
    at ECharts.eval (util.js?fe0c:424)
    at VueComponent.resize (eval at ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/iview-loader/index.js?{"prefix":false}!./src/views/app/widgets/pies/PieSimple.vue (9.js:7), <anonymous>:39:20)
```

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: v4.02
+ Browser version [浏览器类型和版本]: chrome 版本 63.0.3239.132（正式版本） （64 位）
+ OS Version [操作系统类型和版本]: win7 旗舰版

### Expected behaviour [期望结果]
多个图表resize互不影响，正常缩放。

### ECharts option [ECharts配置项]

```javascript
option = {
      tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
      },
      legend: {
        orient: 'vertical',
        left: 'left',
        data: ['直接访问', '邮件营销', '联盟广告', '视频广告', '搜索引擎']
      },
      series: [{
        name: '访问来源',
        type: 'pie',
        radius: '55%',
        center: ['50%', '60%'],
        data: [{
            value: 335,
            name: '直接访问'
          },
          {
            value: 310,
            name: '邮件营销'
          },
          {
            value: 234,
            name: '联盟广告'
          },
          {
            value: 135,
            name: '视频广告'
          },
          {
            value: 1548,
            name: '搜索引擎'
          }
        ],
        itemStyle: {
          emphasis: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
          }
        }
      }]
}

```

**Comment by authasme** [comment]
当resize一个图表时，Schedule.js的performStageTasks方法会执行多次，其中一次执行到这里报错：
![image](https://user-images.githubusercontent.com/22970441/35712937-b74531f4-07ff-11e8-9044-e4b5869e8c4d.png)
![image](https://user-images.githubusercontent.com/22970441/35712949-c3eb6090-07ff-11e8-9eda-6609a801cb72.png)
![image](https://user-images.githubusercontent.com/22970441/35712964-d2934392-07ff-11e8-87e1-2d7cc05921fa.png)

**Comment by 100pah** [comment]
我现在不能复现出这个问题。有没有可能是因为，比如页面中多个图的时候，引入了多个 echarts 名空间？不知道能不能看到您的工程代码。

**Comment by authasme** [comment]
@100pah 我的工程使用了vue + jqueryui + echarts， 使用了jqui的Resizable 放大dom后，再调用echarts的resize方法，实现自适应缩放。整个工程不方便展示，我正在尝试写一个demo复现问题，如能复现，我及时回复给你，感谢。

**Comment by authasme** [comment]
@100pah 我刚写了下面这个例子，可以直接运行；未能还原console的错误报告，但是效果类似，就是动态创建的图表，始终只有一个可以正常resize,其他的不行，我感觉是echarts示例动态生成后未能正确记录的问题，但是dom元素中的_echarts_instance_是有区别的。

里面的图表鼠标放到边界部位可以直接缩放。

`<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
		<script src="https://cdn.bootcss.com/echarts/4.0.2/echarts.js"></script>
        
        <link href="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet">
        <script src="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.js"></script>
        
		<style type="text/css">
			div.content {
				border: 1px solid #4682b4;
                width:100%;
                height:100vh;
				margin-top: 5px;
			}
            div.widget {
                width:100px;
                height:100px;
                border: 1px solid #A020F0;
            }
		</style>
		<title>echarts resize测试</title>
	</head>
	<body>
		<div class="content">
            <div class="widget" id="ec1"></div>
            <div class="widget" id="ec2"></div>
            <div class="widget" id="ec3"></div>
		</div>
        <script>
            var option = {
              tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
              },
              legend: {
                orient: 'vertical',
                left: 'left',
                data: ['直接访问', '邮件营销', '联盟广告', '视频广告', '搜索引擎']
              },
              series: [{
                name: '访问来源',
                type: 'pie',
                radius: '55%',
                center: ['50%', '60%'],
                data: [{
                    value: 335,
                    name: '直接访问'
                  },
                  {
                    value: 310,
                    name: '邮件营销'
                  },
                  {
                    value: 234,
                    name: '联盟广告'
                  },
                  {
                    value: 135,
                    name: '视频广告'
                  },
                  {
                    value: 1548,
                    name: '搜索引擎'
                  }
                ],
                itemStyle: {
                  emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                  }
                }
              }]
            };
            var doms = ["ec1", "ec2", "ec3"];
            for(i in doms){
                var domId = doms[i];
                var myChart =  echarts.init(document.getElementById(domId));
                myChart.setOption(option);
                
                //jqui的缩放                
                $("#"+domId).resizable({
                    handles: "all",
                    stop: function(event, ui) {
                        //图表适应容器
                        myChart.resize();
                    }
                });
            }
            
        </script>
	</body>
</html>`

**Comment by pissang** [comment]
@authasme 这个是你代码中的问题，整个作用域只有一个 myChart 变量，所有 resize 后操作的也是最后一个 myChart，建议了解下 JS 中的作用域相关知识
