### ISSUE TITLE
向echarts传递给不存在在页面中的Jquery对象，会报错

### ISSUE THREAD

**Issue by sevenen** [ecomfe/echarts#7699]
### One-line summary [问题简述]

我希望赋给echarts一个不存在在页面中的jquery的对象。但是这样会报错。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:  echarts3
+ Browser version [浏览器类型和版本]:  Chrome
+ OS Version [操作系统类型和版本]:window

### Expected behaviour [期望结果]
我希望这个echarts图是可以迁移的。

### ECharts option [ECharts配置项]

```javascript
option = {

}
var div = $('<div style="width: 800px; height: 229px; "></div>');
var myChart = echarts.init(div);
myChart.setOption(option);
$('.right-container').html(div);


//或者 这样子 也会报错
var div = $('<div style="width: 800px; height: 229px; "></div>');
$('.right-container').html(div);
var myChart = echarts.init(div);
```

**Comment by pissang** [comment]
echarts 不支持传入 jQuery 对象，可以用 div[0] 获取到实际的 dom 对象
