### ISSUE TITLE
模拟迁徙怎样实时刷新数据呢

### ISSUE THREAD

**Issue by RainLii** [ecomfe/echarts#7702]
### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
setOption 刷新数据

**Comment by RainLii** [comment]
想实现一次一条线,且不覆盖前一条的效果
