### ISSUE TITLE
自定义南京地图如何画出来

### ISSUE THREAD

**Issue by chfw** [ecomfe/echarts#7709]
### One-line summary [问题简述]

echarts 不能画出来。是到达了echarts的极限了么？

<img width="1129" alt="screen shot 2018-02-03 at 14 10 21" src="https://user-images.githubusercontent.com/4280312/35767896-0d710aa2-08ec-11e8-93f4-41aab49a8b84.png">

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: echarts 3.6.2
+ Browser version [浏览器类型和版本]: chrome 63.x
+ OS Version [操作系统类型和版本]: MacOS

### Expected behaviour [期望结果]

<img width="790" alt="screen shot 2018-02-03 at 13 53 56" src="https://user-images.githubusercontent.com/4280312/35767857-33c0199c-08eb-11e8-8221-952fc4a26c6b.png">

### ECharts option [ECharts配置项]

```javascript
      $.getJSON('nanjing.geojson', function (data) {
      var cityname='nanjing';
      console.log(data);
        echarts.registerMap(cityname, data);
      var chart = echarts.init(document.getElementById('map'));
      var option =  {
		"title": [
	  {
				"textStyle": {
					"color": "#000", 
					"fontSize": 18
				}, 
				"subtext": "", 
				"text": cityname, 
				"top": "auto", 
				"subtextStyle": {
					"color": "#aaa", 
					"fontSize": 12
				}, 
				"left": "auto"
			}
		], 
		"legend": [
			{
				"selectedMode": "multiple",
				"top": "top",
				"orient": "horizontal",
				"data": [
					""
				],
				"left": "center",
				"show": true
			}
		],
		"backgroundColor": "#fff",
		"series": [
			{
				"mapType": cityname,
				"data": [],
				"name": "",
				"symbol": "circle",
				"type": "map",
				"roam": true
			}
		]
	};
        chart.setOption(option); 
      }).fail(function(xhr, status, error){
	   console.log(error);
	  });
```

### Other comments [其他信息]

源文件可以在 http://mapshaper.org 上打开的
[nanjing.geojson.txt](https://github.com/ecomfe/echarts/files/1691803/nanjing.geojson.txt)

**Comment by pissang** [comment]
echarts 的地图只支持 GeoJSON 的 Polygon 和 MultiPolygon，如果要画线的话可以转换下用 http://echarts.baidu.com/option.html#series.lines

PS: 这个数据量离 echarts 的极限还很远

**Comment by chfw** [comment]
谢谢指导，我能把图画出来了：

<img width="914" alt="screen shot 2018-02-05 at 20 51 22" src="https://user-images.githubusercontent.com/4280312/35828143-66e866f4-0ab6-11e8-91dc-fa4aa5824abf.png">

我现在的问题是，我需要提供一个江苏地图，而这个地图让画出来的需要放大才行。请问有更好的实现方式吗？

```
	      geo: {
        map: '江苏',
        label: {
            emphasis: {
                show: false
            }
        },
        roam: true,
        itemStyle: {
            normal: {
                areaColor: 'white',
                borderColor: '#404a59'
            },
            emphasis: {
                areaColor: '#2a333d'
            }
        }
    },

```

<img width="267" alt="screen shot 2018-02-05 at 20 52 47" src="https://user-images.githubusercontent.com/4280312/35828201-93f0798e-0ab6-11e8-8d4d-4258a3f3eb83.png">

**Comment by chfw** [comment]
哦，想到了，我可以用南京市地图做基准坐标。谢谢！

**Comment by IdenPin** [comment]
@pissang   请问GEOJSON 数据的LineString类型何时能支持

**Comment by 735759079** [comment]
您好，请问您的这种线式的地图，具体echarts的配置是什么，有实际项目可以让clone下来参考一下吗

**Comment by chfw** [comment]
@735759079 我把代码放[这里](https://github.com/chfw/nanjing-demo).
