### ISSUE TITLE
[!Bug!] inside dataZoom & datazoomselect显示异常

### ISSUE THREAD

**Issue by Frankzhaopku** [ecomfe/echarts#7712]
### One-line summary [问题简述]
在自己实现的custom火焰图，较大数据量下inside dataZoom缩放后左右拖拽会出现图形残留，而使用toolbox的dataZoom框选缩放，则无法正常显示数据

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
Chrome
+ OS Version [操作系统类型和版本]:
Windows7

### Expected behaviour [期望结果]
可以正常显示和缩放

### ECharts option [ECharts配置项]

```javascript
option = {
tooltip: {
        formatter: function (params) {
          return params.marker + params.name + ': ' + params.value + ' ms';
        }
      },
      title: {
        text: 'Profile',
        left: 'center'
      },
      dataZoom: [
        {
          type: 'inside',
          filterMode: 'none'
        }
      ],
      grid: {
        height:300
      },
      xAxis: {
        type: 'value',
        name: 'ratio',
        min: 0,
        max: 1,
        show: true,
        scale: true
      },
      yAxis: {
        type: 'value',
        name: 'sp',
        min: 0,
        max: maxStack + 1,
        show: true,
        scale: true
      },
      series: [{
        type: 'custom',
        data: showData,
        renderItem: function (params, api) {
          var p = api.coord([api.value(3), api.value(0)]);
          var s = api.size([api.value(4), 1]);
          return {
            type: 'rect',
            shape: echarts.graphic.clipRectByRect({
              x: p[0],
              y: p[1],
              width: s[0],
              height: s[1]
            }, {
              x: params.coordSys.x,
              y: params.coordSys.y,
              width: params.coordSys.width,
              height: params.coordSys.height
            }),
            style: api.style()
          }
        }
      }]
//      toolbox:{
//        feature: {
//          dataZoom: {
//            show: true
//          }
//        }
//      }
}

```

### Other comments [其他信息]

示例请见：[http://cdn.frankzhao.org/demo/graphTest.html](http://cdn.frankzhao.org/demo/graphTest.html)
可使用滚轮缩放后左右拖拽，会发现有数据残留，打开toolbox配置，则数据无法显示

**Comment by pissang** [comment]
把  `filterMode: 'none'` 改成 `filterMode: 'weakFilter'` 试试

**Comment by Frankzhaopku** [comment]
@pissang 不行的，之前使用的weakFilter，表现增加奇怪，只能显示出一行数据，而且缩放后如果不在最右侧，就连那行都无法显示出来

**Comment by pissang** [comment]
@Frankzhaopku 这个应该是因为没有指明哪些数据在 x 轴上的缘故，我看你是第三个数在 x 轴上，试试用 [encode](http://www.echartsjs.com/option.html#series-custom.encode) 声明一下

**Comment by Frankzhaopku** [comment]
@pissang 确实，限制了encode:{x:3,y:0}后在weakFilter下可以显示了，但缩放后有些段无法正常显示，如图，但左右拖动不会出现图形残留，若使用none则会出现图形残留。
![image](https://user-images.githubusercontent.com/8512426/35787789-b817a8be-0a6b-11e8-89e6-a97f40ece814.png)

**Comment by Frankzhaopku** [comment]
@pissang 另外，使用了encode后，toolbox的datazoomselect功能也正常了，就差如何使得缩放后大于屏幕显示的横条可以显示出来

**Comment by pissang** [comment]
@Frankzhaopku 把每一个数据横轴上的起始数据和结束数据都存下来，比如第三项是起始，第四项是结束（我看现在存的是长度）然后 encode 的时候写 

x: [3, 4]

**Comment by Frankzhaopku** [comment]
@pissang 按照x起始终止位置存储到3、4，x:[3,4]后效果还是一模一样的，超过屏幕范围的图形会整个都被隐藏

**Comment by pissang** [comment]
@Frankzhaopku 能把改过后的例子发我下么？

**Comment by Frankzhaopku** [comment]
@pissang 这里[http://cdn.frankzhao.org/demo/graphTest2.html](http://cdn.frankzhao.org/demo/graphTest2.html)

**Comment by Frankzhaopku** [comment]
@pissang 我的错，我写成filter了，如果是weakFilter就好了

**Comment by Frankzhaopku** [comment]
不过FilterMode选择none时还是有图形残留的问题，不知道是不是属于正常
