### ISSUE TITLE
echarts是否规划支持柱形范围图(需求)

### ISSUE THREAD

**Issue by grath10** [ecomfe/echarts#7727]
### One-line summary [问题简述]
echarts是否支持柱形范围图

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### Expected behaviour [期望结果]

能够提供类似于highcharts  columnrange类型柱形范围图

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![chart](https://user-images.githubusercontent.com/17782336/35848899-bcc47078-0b5a-11e8-9781-4cf3450c0ab2.png)

**Comment by pissang** [comment]
暂时没有计划，用自定义系列可以很方便的实现 http://www.echartsjs.com/gallery/editor.html?c=custom-profile

**Comment by grath10** [comment]
@pissang 好的，那就暂时先用自定义系列实现相关功能，多谢指教
