### ISSUE TITLE
关于dataset遇到的问题

### ISSUE THREAD

**Issue by cn-xufei** [ecomfe/echarts#7733]
### One-line summary [问题简述]
使用dataset配置数据，当dimensions中的维度，没有在，source中出现，也就是说，某个维度没有数据，则图表无法渲染，如下图中没有维度‘2017’的数据，整个图表都无法展示
![image](https://user-images.githubusercontent.com/14144811/35857025-c8155f4c-0b72-11e8-8a48-c3ae633df2cb.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]: Chrome 64
+ OS Version [操作系统类型和版本]: win10

### Expected behaviour [期望结果]
希望没有数据的维度不展示，但其他有数据的维度照常展示

### ECharts option [ECharts配置项]

```javascript
option = {
    legend: {},
    tooltip: {},
    dataset: {
        // 这里指定了维度名的顺序，从而可以利用默认的维度到坐标轴的映射。
        // 如果不指定 dimensions，也可以通过指定 series.encode 完成映射，参见后文。
        dimensions: ['product', '2015', '2016', '2017'],
        source: [
            {product: 'Matcha Latte', '2015': 43.3, '2016': 85.8},
            {product: 'Milk Tea', '2015': 83.1, '2016': 73.4},
            {product: 'Cheese Cocoa', '2015': 86.4, '2016': 65.2},
            {product: 'Walnut Brownie', '2015': 72.4, '2016': 53.9}
        ]
    },
    xAxis: {type: 'category'},
    yAxis: {},
    series: [
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'},
        {type: 'bar'}
    ]
};

```

**Comment by cn-xufei** [comment]
👍

**Comment by adsort** [comment]
+1

**Comment by cn-xufei** [comment]
期待尽快发布，辛苦了echarts的攻城狮，希望echarts越来越好🎉
