### ISSUE TITLE
在China地图中不显示南沙群岛的九段线标识

### ISSUE THREAD

**Issue by daXiaxuchao** [ecomfe/echarts#7755]
### One-line summary [问题简述]

不显示南沙群岛的九段线突出标识

### Version & Environment [版本及环境]
+ ECharts version [3.8]:
+ Browser version [Chrome 59.0.3]:
+ OS Version [win 10 64bit]:

### Expected behaviour [期望结果]

在China地图中不显示南沙群岛的九段线标识

### ECharts option [ECharts配置项]

```javascript
let option = {
  title: {
    text: "购买对象所在省份TOP10",
    subtext: "销售面积区间",
    x: "center"
  },
  geo: {
    map: "china",
    show: true,
    roam: true,
    label: {
      normal: {
        show: false
      },
      emphasis: {
        show: false
      }
    },
    itemStyle: {
      normal: {
        areaColor: '#031525',
        borderColor: '#3B5077'
      },
      emphasis: {
        areaColor: '#2B91B7'
      }
    }
  },
  series: [
    {
      name: "credit_pm2.5",
      type: "scatter",
      coordinateSystem: "geo",
      data: []
    }
  ]
}
this.myChart.setOption(option);

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/24410104/35956814-e98f9df2-0cd2-11e8-802e-8133760c5319.png)

**Comment by Ovilia** [comment]
不能不显示南沙群岛，这是国家领土的一部分

**Comment by saviorZSC** [comment]
@Ovilia 在echarts-gl中，中国三维地图没有南沙群岛的部分，请问如何解决

**Comment by Ovilia** [comment]
@saviorZSC ECharts 不提供地图数据，请到第三方寻找解决方案。
