### ISSUE TITLE
Photographic map overlay; Adding texture to geo regions

### ISSUE THREAD

**Issue by sicksaduser** [ecomfe/echarts#7772]
### One-line summary [问题简述]

How to use geo: {itemStyle: {areaColor: {image: imageDom... to get accurate texturing?

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Firefox 58.0.1 (64-bit)
+ OS Version [操作系统类型和版本]: Lubuntu 17.10

### Expected behaviour [期望结果]

I would like regions to be filled with texture, like here:
http://gallery.echartsjs.com/editor.html?c=xryrIm5ulx
(When the switch is changed to photographic view)

My background is statically loaded and is available in full size, i don't want the dynamic tiles fetching.

### ECharts option [ECharts配置项]
```javascript

/* Based on this OTHER example http://gallery.echartsjs.com/editor.html?c=xBycRXbPgx */
option = {
    geo: {
        map: 'world',
        itemStyle: {
            normal: {
                /* fullImage is declared in the original example with base64 encoding */
                color: {image:fullImage,repeat:'repeat'}
            }
        }
    }
}

```

### Other comments [其他信息]

I'm trying to overlay a scatter plot in geographic coordinates on top of an actual photographic map background, like in this example http://gallery.echartsjs.com/editor.html?c=xryrIm5ulx but with smoother scrolling and zoom. I want my background to be always aligned with the map and respond to panning and zooming in the same way.

I've tried setting backgroundColor on echartsInstance or markArea on series, but it wouldn't respond to zooming. I've looked into dataZoom, but apparently geo is designed to work with the roam: true param instead. I've tried creating a graphic: {type: 'image',... on echartsInstance, listening for mousemove and wheel, extracting myChart._coordSysMgr._coordinateSystems[0]._center and _zoom, and using getOption()/setOption() in the events handler to alter the graphic's style: {x, y, width, height} to follow the viewport, but the movements look jagged.

I've thought the best way might be to inject a {"geometry":{"type":"Polygon","coordinates":[[[-180,90],[180,90],[180,-90],[-180,-90]]]},"properties":{"name":"background","childNum":1}} into my world.js, then styling it using geo: {regions: [{ name: "background",  itemStyle: {areaColor: {image: document.getElementById('myearthphoto')}} }], but have run into the problem i've distilled above under "ECharts option": instead of texture, i get areas as if smudged with the colors of the texture's palette, like if my image is being cropped to a few pixels and then upscaled all over the region.
(And there's a lesser curiosity, that after i inject my background region into the map's json, the map somehow gets shrinked a bit. Perhaps i'm using the wrong coords for it.)

What should i do? Is there a better way? Why doesn't texturing work?

Sorry for verbosity and thanks for the inspiring library.

**Comment by 100pah** [comment]
The geo coords of echarts does not support texture yet. But there are two ways to probably solve this requirement:
(1) Use geo3D (in echarts-gl), for example: <http://gallery.echartsjs.com/editor.html?c=xH1w9_Zcag>.
(2) Use [custom series](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Custom%20Series) to draw the background image on geo coords (and off course the custom series can roam with the geo coord)

**Comment by sicksaduser** [comment]
Thank you.

Going for the 2nd option, i did the following, using custom series with dummy data to do coord conversion and move my graphic:

```
{
    type: 'custom',
    coordinateSystem: 'geo',
    data: [[0, 0]],
    renderItem: function (params, api) {
        var lt = api.coord([-180, 90]), rb = api.coord([180, -90]);
        return {type:'image', style: {image: 'url...', x:lt[0], y:lt[1], width:rb[0]-lt[0], height:rb[1]-lt[1]}}
    }
}
```

The movement is smooth and it works as intended if only lags due to image size.
Probably if i return nothing and alter transforms on an underlying picture instead, there will be no lag (as panzoom.js has none).
It would still be tricky to get picture-to-geojson alignment and scaleLimit right, though.

I think i'll explore other options for production, but it was still great to be able to preview the desired result.
