### ISSUE TITLE
官方文档中series-graph.top默认值错误

### ISSUE THREAD

**Issue by whxru** [ecomfe/echarts#7780]
### One-line summary [问题简述]

在官方文档[关于top值的描述](http://echarts.baidu.com/option.html#series-graph.top)中提到top的值可以为具体像素值、百分比、top、middle、bottom，但显示的默认值为center，疑是将middle误写。另外在series-map.top等页面中也有类似错误（未一一找出）。

### Expected behaviour [期望结果]

serires-graph.top的默认值为`middle`

**Comment by 100pah** [comment]
多谢指出 :)
