### ISSUE TITLE
Issue with dataset and stacked bar

### ISSUE THREAD

**Issue by jrandhawa09** [ecomfe/echarts#7786]
### One-line summary [问题简述]
Stacked bar column values are incorrect when using dataset.

### Version & Environment 
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Chrome 64.0.3282.167
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
Stacked columns for series 2 and 3 should be correct values

See http://jsfiddle.net/3uy51e8a/41/

### ECharts option [ECharts配置项]

var myChart = echarts.init(document.getElementById('main'));
var option = {
  legend: {},
  tooltip: {
    trigger: 'axis',
  },
  dataset: {
    source: [
                            ['serie', 'A', 'B', 'C', 'D', 'E', 'F'],
                            ['Test1', 50, 50, 50, 50, 50, 50],
                            ['Test2', 100, 50, 100, 50, 100, 50],
                            ['Test3', 10, 20, 30, 40, 30, 20],
    ],
  },
  xAxis: { type: 'category' },
  yAxis: { gridIndex: 0 },
  series: [
    { type: 'bar', stack: 'same'},
    { type: 'bar', stack: 'same'},
    { type: 'bar', stack: 'same'},
    { type: 'bar', stack: 'same'},
    { type: 'bar', stack: 'same'},
    { type: 'bar', stack: 'same'},
  ],
};
myChart.setOption(option);

### Other comments [其他信息]

See jsfiddle
http://jsfiddle.net/3uy51e8a/41/

**Comment by 100pah** [comment]
Fixed on bf0df08.
New version is coming in several days later.

**Comment by mpaduada** [comment]
@100pah When can we expect a release that includes these changes?

**Comment by soulmotion21** [comment]
You must add dimensions to your dataset.
