### ISSUE TITLE
how to set the percent type chart by yAxis

### ISSUE THREAD

**Issue by alextgco** [ecomfe/echarts#7804]
Hi, i have the following code:

var option = {
                title: {
                    text: ''
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data:['asda','werewr','hfgh','直接访问','搜索引擎']
                },
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true
                },
                toolbox: {
                    feature: {
                        saveAsImage: {}
                    }
                },
                xAxis: {
                    type: 'category',
                    boundaryGap: false,
                    data: ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь']
                },
                yAxis: {
                    type: 'value'
                },
                series: [
                    {
                        name:'Ольга Ларина',
                        type:'line',
                        stack: 'abc',
                        data:[12, 13, 11, 13, 90, 23, 20,11, 13, 9, 23, 21],
                        itemStyle:{
                            color: '#3485cc'
                        }
                    },
                    {
                        name:'Николай Кириенко',
                        type:'line',
                        stack: 'abc',
                        data:[22, 18, 19, 23, 29, 33, 31, 19, 23, 29, 33, 31],
                        itemStyle:{
                            color: '#57b446'
                        }
                    },
                    {
                        name:'Сергей Ладогов',
                        type:'line',
                        stack: 'abc',
                        data:[50, 23, 20, 15, 19, 33, 41, 20, 15, 10, 33, 41],
                        itemStyle:{
                            color: '#c23531'
                        }

                    }
                ]
            };

----------------

The highest value in series is 90, so why does 150 by Y appears?

And one more question, in a rendered chart the highest value appears below lowest.

Please help me to setup my chart correctly.

Thaks a lot!

PS This is a great work, guys, respect!

**Comment by Ovilia** [comment]
Just remove the `stack: 'abc'` in all series will do. This makes series stack on each other.
