### ISSUE TITLE
graph 节点 symbol 为 svg路径（‘path:// ...’） 时，设置 symbolSize 改变图标大小时怎么保持宽高比

### ISSUE THREAD

**Issue by Hjinbin** [ecomfe/echarts#7813]
### One-line summary [问题简述]

关系图 graph，设置 symbol 为任意 svg，设置 symbolSize 为 Number 类型时，原宽高不一样的 svg 图标变形，设置 symbolSize 为 Array, 即为 symbol 分别设置宽高时可以解决变形的问题，但是前提不知道 svg 宽高比。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.2
+ Browser version [浏览器类型和版本]: Chrome 64
+ OS Version [操作系统类型和版本]: Windows 10

### Expected behaviour [期望结果]
设置 symbol 大小时保持宽高比

### ECharts option [ECharts配置项]

```javascript
option = {
    series: [
{
type: 'graph',
layout: 'none',
data: [
{
    name: '邮件',
    x: 0,
    y: 10,
    symbol: 'path://M164,210.677v33.47l154.656,66.356L468,243.681v-33.004H164L164,210.677z M164,282.255L164,282.255v134.76h304V282.061l-149.012,66.615L164,282.255L164,282.255z',
    symbolSize: 20,
},
{
    name: '手机',
    x: 10,
    y: 20,
    symbol: 'path://M23 0h-14c-1.65 0-3 1.35-3 3v26c0 1.65 1.35 3 3 3h14c1.65 0 3-1.35 3-3v-26c0-1.65-1.35-3-3-3zM12 1.5h8v1h-8v-1zM16 30c-1.105 0-2-0.895-2-2s0.895-2 2-2 2 0.895 2 2-0.895 2-2 2zM24 24h-16v-20h16v20z',
    symbolSize: 20,
},
],
links: [
{source: '邮件', target: '手机'}
],
},
],
};

```

**Comment by Ovilia** [comment]
下个版本上线，支持以 `series.symbolKeepAspect` 或 `series.data.symbolKeepAspect` 设置是否保持 path 长宽比，为了兼容性，默认 `false`。
