### ISSUE TITLE
this.painter is null

### ISSUE THREAD

**Issue by jiangshichao** [ecomfe/echarts#7866]
### One-line summary [问题简述]
echarts会时不时报错this.painter is null，很奇怪，目前是间歇性的报错，时间不固定，情况不固定，没法指定操作复现......不清楚是为什么

### Version & Environment [版本及环境] 
+ ECharts version [ECharts 版本]: echarts4.0.4
+ Browser version [浏览器类型和版本]:火狐58.0.2
+ OS Version [操作系统类型和版本]:win7

**Comment by pissang** [comment]
是不是已经 dispose 但是还在使用？

**Comment by jiangshichao** [comment]
thanks，我刚看echarts代码也怀疑是不是dispose导致的，现在修改了代码在进行测试

**Comment by damiangreen** [comment]
What's the solution? I'm receiving tihs.
