### ISSUE TITLE
http://echarts.baidu.com/examples/editor.html?c=line-stack纵坐标的值与实际不符

### ISSUE THREAD

**Issue by slowtech** [ecomfe/echarts#7893]
### One-line summary [问题简述]

http://echarts.baidu.com/examples/editor.html?c=line-stack

最大值是1320，但是从纵坐标的位置来看，都超过2500了

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
这是 stack 属性的表现
