### ISSUE TITLE
LineChart symbol需要一个透明空心圆/填充跟背景一样颜色

### ISSUE THREAD

**Issue by seeddyan** [ecomfe/echarts#7906]
### One-line summary [问题简述]

![image](https://user-images.githubusercontent.com/3996319/37195706-e9fb9b90-23ae-11e8-941b-4b625d964849.png)
如图所示，已有的symbol样式无法实现图中效果，需要添加一个透明空心圆 或者 填充跟背景一样颜色项。
谢谢大神！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by pissang** [comment]
可以设置 symbol 为 `circle`，然后设置 color 和背景色一样，再设置 borderColor 和 borderWidth 表现边框

**Comment by loubenjin** [comment]
这样图例还有提示颜色都是背景颜色了，该怎么单独设置呢
