### ISSUE TITLE
Hide Loading not working

### ISSUE THREAD

**Issue by AllanCodes** [ecomfe/echarts#7911]
Hello,

I have an echarts component like so:

```
<ReactEcharts ref={(e) => { this.echarts_react_overallpreview = e; }}
            option={this.state.overallPreview.getOption()}
            showLoading={true}
            style={{height: '100%', width: '100%'}}
          />
```
I later call:

```
this.echarts_react_overallpreview.getEchartsInstance().hideLoading();
this.echarts_react_overallpreview.getEchartsInstance().setOption( g.getOption() );
```
However, loading remains enabled and the loading swirl does not get cleared. What can the problem be?

**Comment by hustcc** [comment]
After you setOption, you should call `hideLoading` every time. Demo [here](https://github.com/hustcc/echarts-for-react/blob/master/demo/src/charts/Loading.jsx).
