### ISSUE TITLE
官方 demo 的折线图最后一列不显示圆点

### ISSUE THREAD

**Issue by amio** [ecomfe/echarts#7913]
### One-line summary [问题简述]

http://echarts.baidu.com/examples/editor.html?c=line-stack
这个示例里最后一列的圆点默认不显示，要鼠标指向才显示出来。
估计也是这个原因，导致跟随圆点的自定义 label 也不能显示。

![default](https://user-images.githubusercontent.com/215282/37265021-ba98b5ba-25eb-11e8-8c15-58d3f3eab0e7.png)

（作为对照的另一个情况是，http://echarts.baidu.com/examples/editor.html?c=line-simple 这里的最后一列又是没问题的，大概是因为圆点没有顶到图表的边缘？BTW，也看不出是哪个配置导致了这个图和另一张折线图的区别）

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0
+ Browser version [浏览器类型和版本]: Chrome Dev 66
+ OS Version [操作系统类型和版本]: macOS 10.13.3

### Expected behaviour [期望结果]

折线图表右边缘的圆点能像左边缘的一样默认显示出来

**Comment by GuessKing** [comment]
同样问题

**Comment by comkis** [comment]
echart宽高自适应也要搞一下呢。不然只剩下手动js了

**Comment by gzzhengbingyi** [comment]
同样的问题，走查时候才发现

**Comment by sdtazhanghe** [comment]
同样的问题 集成测试发现
