### ISSUE TITLE
咋计算 dataZoom 的资料范围呢

### ISSUE THREAD

**Issue by c75a91** [ecomfe/echarts#7949]
### One-line summary [问题简述]
我透过事件可以知道 dataZoom 的 start & end 的 percent，可是我咋透过 percent 与 资料长度去计算开始的资料与结束的资料呢？

我现在的算法是
```javascript
var start = Math.round(zoom.batch[0].start * this.trueContent.length / 100.0)
var end = Math.round(zoom.batch[0].end * this.trueContent.length / 100.0)
```
不论是起始资料还是结束的资料总是会误差一点，可能是开始的 Index - 1 或 end 也会有时需要 -1

**Comment by yanzijun** [comment]
參考: [https://github.com/ecomfe/echarts/issues/4906](https://github.com/ecomfe/echarts/issues/4906)

Vue-echarts 的方法:
在原始 component (Echarts.vue) 內加上這個 method 即可。

```javascript
 getOptions (){
      return [this.chart.getOption().dataZoom[0].startValue, this.chart.getOption().dataZoom[0].endValue]
 }
```

然後去呼叫他就好。
