### ISSUE TITLE
echarts横坐标data的textStyle的color无效

### ISSUE THREAD

**Issue by LunchFood** [ecomfe/echarts#7954]
### One-line summary [问题简述]
单独设置横坐标的每个坐标字体颜色无效

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0+
+ Browser version [浏览器类型和版本]:chrome 64
+ OS Version [操作系统类型和版本]:windows10

### Expected behaviour [期望结果]
能狗单独设置每个坐标的颜色

### ECharts option [ECharts配置项]

```javascript
option = {
xAxis: {
        type: 'category',
        nameTextStyle:{
            color:'#03ff00'
        },
        data: [{ 
            value: 'test',
            textStyle: {color: '#03ff00',fontSize:36},
        },
        'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'
        ]
    },
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/22734894/37507068-d7ccaeb8-2927-11e8-879a-3b262ade19d3.png)

**Comment by evaseemefly** [comment]
这个后续有解决吗？
