### ISSUE TITLE
force graph, link（edge）的emphasis属性不起作用

### ISSUE THREAD

**Issue by muhm21cn** [ecomfe/echarts#8015]
### One-line summary [问题简述]
Echarts4.0.4的版本给force graph的links设置emphasis属性后，鼠标hover后没有任何效果。
不论是设置在links属性同一层次的emphasis->lineStyle,还是links属性下的emphasis->lineStyle,都没有起到效果。在版本3.6.1的时候links的emphasis属性是正常有作用的。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 4.0.4
+ Browser version [浏览器类型和版本]: chrome
+ OS Version [操作系统类型和版本]: mac OS

### Expected behaviour [期望结果]
emphasis属性设置后，鼠标hover能有相应的效果

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

**Comment by 100pah** [comment]
Fixed in c10d7559a0a3ae7f6aa1929b3d3cb5d7deb0e797
