### ISSUE TITLE
鼠标点击拖动timeline上的checkpoint，无法捕捉到事件。

### ISSUE THREAD

**Issue by ZhuGYao** [ecomfe/echarts#8025]
### One-line summary [问题简述]

鼠标点击拖动timeline上的checkpoint，无法捕捉到事件，并且后面整合的百度地图也会随着拖动进行拖动。很影响使用体验。另外，还有渲染bug问题，我在前两天提了.  #7963   以及 #7970
希望开发者们能在百忙之中给我一个答复，谢谢！非常感谢！！！

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:3.8.5
+ Browser version [浏览器类型和版本]:谷歌最新
+ OS Version [操作系统类型和版本]:win10

### Expected behaviour [期望结果]
完美运行

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![bug](https://user-images.githubusercontent.com/24791960/37897819-bd12022c-3119-11e8-89da-a6f0ff492c00.png)

**Comment by GAOYINGMING** [comment]
Is there any solution?
