### ISSUE TITLE
怎么让地图和散点图的高亮效果同时生效？

### ISSUE THREAD

**Issue by 767994269** [ecomfe/echarts#8031]
当鼠标放上或者划过时，散点图和地图颜色同时发生变化。如图所示：当美国高亮变绿时，让散点图变白；
![1522130726 1](https://user-images.githubusercontent.com/33504847/37949605-f3f1e434-31c7-11e8-86da-9d83188cad8c.jpg)

**Comment by dadazhouRenee** [comment]
最后怎么解决的呀 dispatchAction吗
