### ISSUE TITLE
用safari打开graph的demo“网页内容”意外退出

### ISSUE THREAD

**Issue by Ngone51** [ecomfe/echarts#8044]
### One-line summary [问题简述]
用Safari打开链接http://echarts.baidu.com/examples/editor.html?c=graph ，
鼠标指针在图示节点上移动，网页会意外退出然后重载。

![echarts_issue](https://user-images.githubusercontent.com/16397174/38023313-8a78d466-32b4-11e8-9094-b8f9b728d657.png)

**Comment by pissang** [comment]
这个可能是 safari 的问题，我们暂时无法复现

**Comment by Ngone51** [comment]
ok, fine.
