### ISSUE TITLE
中国地图展示方式，建议添加钓鱼岛

### ISSUE THREAD

**Issue by muye100110** [ecomfe/echarts#8057]
### One-line summary [问题简述]
中国地图展示方式，建议图形添加钓鱼岛。没有钓鱼岛，给政府部门做统计无法使用。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:4.0.4
+ Browser version [浏览器类型和版本]:Google65
+ OS Version [操作系统类型和版本]:Windows7

### Expected behaviour [期望结果]
地图展示添加钓鱼岛

### ECharts option [ECharts配置项]

```javascript
option = {

}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/31815119/38066989-ff1d0642-333c-11e8-8001-75dc1d19888c.png)

**Comment by pissang** [comment]
因为地图的问题太过敏感，ECharts 现在不再提供地图数据，可以自行寻找更合适的数据源，抱歉

**Comment by lizy-DK** [comment]
> 因为地图的问题太过敏感，ECharts 现在不再提供地图数据，可以自行寻找更合适的数据源，抱歉

作为一个百度的开源项目，这样撇清关系的做法实在令人费解。背靠大企业应该勇于担当，让所有用户轻松地获取最权威的中国地图资讯，而不是千方百计转移风险
