### ISSUE TITLE
桑基图是否有提供交叉部分的api。

### ISSUE THREAD

**Issue by zoii** [ecomfe/echarts#8074]
### One-line summary [问题简述]
桑基图是否图表交叉部分是否有提供api，需求是：希望鼠标经过交叉部分可以显示交叉的数据。

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 最新版本
+ Browser version [浏览器类型和版本]: chrome 65.0.3325.181
+ OS Version [操作系统类型和版本]: OSX El Capitan 10.11.6 (15G19009)

### Expected behaviour [期望结果]

希望鼠标经过交叉部分可以显示交叉的数据。

**Comment by deqingli** [comment]
您好，目前没有这方面的 api .
