### ISSUE TITLE
[enhancement]堆积图的问题

### ISSUE THREAD

**Issue by appleskiller** [ecomfe/echarts#863]
如题，请加入百分比堆积的图形支持。这个我相信echarts完全能够做到（因为已经显式指定了的轴类型为value）

**Comment by xinke7hao** [comment]
借题咨询一下，现有的堆积图是否支持柱顶端显示total呢？
如一个堆积柱由三个柱体，值分别为2，3，4组成，是否支持在柱顶端显示总和 9 呢？

e.g. http://www.highcharts.com/demo/column-stacked

**Comment by kener** [comment]
加个markPoint实现吧

**Comment by xinke7hao** [comment]
thx!

**Comment by xinke7hao** [comment]
谢谢，现在实现的效果如图，我想设置markPoint在最后一个柱体的顶端(像2015-01-01那样)，只能这样设置y坐标吗？或者有api可以算出chart高度-堆积柱的高度得到y值？
![image](https://cloud.githubusercontent.com/assets/9262825/5674967/f781c0ae-97ee-11e4-8647-177cb70039f1.png)

**Comment by kener** [comment]
数据驱动，计算你的堆积和作为mp的yAxis值就可以了。
如果想做得更好，响应图例开关动态计算当前选择系列后修正mp的值实现动态加和，都不是难事。

**Comment by xinke7hao** [comment]
这两天才回头来看这个问题了。根据你的提示，也做到了想要的效果，响应开关修正和值计算高度；但是调用addMarkPoint接口的话，接口参数里seriesIdx是必须的，当用户把对应的图例隐藏后，markpoint跟着也隐藏了，这样貌似就不行了。
想了另一个解决办法，就是不用markpoint，而是push一个total series到option.series，背景设透明也能达到效果，总感觉这样实现像走了弯路。想再来请教是否有更好的方法～

**Comment by kener** [comment]
可以的，就是一个系列专门做mp的数据驱动，不用设置透明，就用空数据就行，响应legend就改这个系列的mp值

**Comment by xinke7hao** [comment]
恩！也是total series基础上改改就是了。非常感谢～
不过发现个问题，也不知道算不算bug，用example里面的bar12做的测试，就是关闭图例BBB时，堆积体和值必然是减少，y轴应该也减少或不变，但实际反而增大了一倍；再开启图例BBB，理论上应该跟初始化一样，实际如图3，导致图表中一大半是空白；
![b1](https://cloud.githubusercontent.com/assets/9262825/5849920/4ba61260-a227-11e4-93f8-07addc99ecbf.png)
![image](https://cloud.githubusercontent.com/assets/9262825/5849911/383762a6-a227-11e4-9786-75368a95409a.png)
![image](https://cloud.githubusercontent.com/assets/9262825/5849930/68e07582-a227-11e4-8a26-01e8fe092d90.png)

option = {
    title : {
        text: 'ECharts2 vs ECharts1',
        subtext: 'Chrome下测试数据'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:[
            'VIP','单点'
        ]
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    grid: {y: 70, y2:30, x2:20},
    xAxis : [
        {
            type : 'category',
            data : ['20150106','20150107','20150108','20150109','20150110']
        },
        {
            type : 'category',
            axisLine: {show:false},
            axisTick: {show:false},
            axisLabel: {show:false},
            splitArea: {show:false},
            splitLine: {show:false},
            data : ['20150106','20150107','20150108','20150109','20150110']
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLabel:{formatter:'{value} ms'}
        }
    ],
    series : [
        {'stack':'group1','name':'VIP','type':'bar',itemStyle:{normal: {label:{show:true, position: 'inside'}}},'data':[2672.0,2557.0,1504.0,3956.0,4222.0]},
        {'stack':'group1','name':'单点','type':'bar',itemStyle:{normal: {label:{show:true, position: 'inside'}}},'data':[241.0,235.0,87.0,348.0,492.0]}
        
    ]
};

**Comment by kener** [comment]
恩，同#1021 已经修复，本月内发布新版本。

**Comment by xinke7hao** [comment]
nice work!!

**Comment by ytzhangFTD** [comment]
@xinke7hao 你好，我这里也遇到了同样计算堆积图的total值问题，但是卡在了“响应开关修正和值计算高度”这一步，想请教下该如何操作。如能帮助，万分感谢。
