### ISSUE TITLE
[enhancement]请将雷达图重构成真正的极坐标

### ISSUE THREAD

**Issue by appleskiller** [ecomfe/echarts#864]
如题，目前echarts的雷达实现是多轴的实现，还不能完全等同于极坐标，且显示轴标签后使画面很乱。

建议重构成极坐标，而现在的多轴作为极坐标的子实现（同时也避免了要求外部计算indicator.max），同时建议使用极坐标实现rose - rose绝对不应是饼图子类

**Comment by kener** [comment]
@wind108369 ，同时还有个建议。关于雷达图的data格式重构，弄成跟其他图表一致吧。
拿 http://echarts.baidu.com/doc/example/radar1.html 为例子

    series : [
        {
            name: '预算 vs 开销（Budget vs spending）',
            type: 'radar',
            data : [
                {
                    value : [4300, 10000, 28000, 35000, 50000, 19000],
                    name : '预算分配（Allocated Budget）'
                },
                 {
                    value : [5000, 14000, 28000, 31000, 42000, 21000],
                    name : '实际开销（Actual Spending）'
                }
            ]
        }
    ]

建议重构为

  series : [
        {
            name: '预算',
            type: 'radar',
            data : [
                {  name : '销售', value : 4300},
                {  name : '管理', value : 10000},
                ...
            ]
        },
        {
            name: '实际',
            type: 'radar',
            data : [
                 {  name : '销售', value : 4100},
                 {  name : '管理', value : 12000},
                ...
            ]
        }
    ]

**Comment by wind108369** [comment]
确实这里的 polar 是一个多级坐标，并非是通过θ和r来进行计算的极坐标系。当初只是为了雷达图和设计，算是名字起得不好吧。目前还没有遇到需要使用θ和r作为数据的输入，如果有也可以很轻松的转换成直角坐标中的 x,y。

数据的格式是为了能显示多个坐标，一个坐标能显示多个图形，你说的统一是为了不同图表的转换吧，之后有时间改吧。

**Comment by kener** [comment]
数据格式的改动不影响显示多少个啊？统一的意义还在于容易使用和代码复用，比如tooltip的默认formatter就不用区分，用户自己的formatter也可以跟其他类似，抛出事件的参数也比较一致。有空搞搞~：）

**Comment by zhump** [comment]
是的 我现在就是比对 两个数组 自己算的最大值，然后 数据格式和其他图还不一样，单独做了处理
