### ISSUE TITLE
如果可能的话，希望echarts加入框选（多选）的功能

### ISSUE THREAD

**Issue by appleskiller** [ecomfe/echarts#942]
如题。
基于：
1.做高亮。
2.做数据钻取。

**Comment by ShanxiangWei** [comment]
我觉得很有需要哈，就是参数的筛选。
从业务的需求来看，一般来说图表是呈现数据的方式，如果没有参数，相当于固定了展示的内容，无法动态的展示所需要的数据。我目前都是自己引入div自己加的参数
